### ISSUE TITLE
The pop-up disappears, if the mouseup event is performed  outside of pop-up borders

### ISSUE THREAD

**Issue by admizh** [reportportal/reportportal#100]
Steps to reproduce:
1. Open "Edit Defect Type" pop-up
2. Set comment
3. Perform left click and release outside of popup (select all via mouse)

Results: Pop-up is disappears, сomments not saved

![2017-04-07_16-25-08](https://cloud.githubusercontent.com/assets/6014483/24800076/8c4ec952-1baf-11e7-8fb1-e8c234476fad.gif)

**Comment by DzmitryHumianiuk** [comment]
@admizh 
Will be fixed with next, like if user have changed something, then backdrop block will not react on click.
And highlight 'save' button
