### ISSUE TITLE
In reference to data migration #992

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1000]
@DzmitryHumianiuk , I followed the steps provided in https://github.com/reportportal/reportportal/issues/992

1. Backed-Up PostgreSQL DB data. -- Using docker exec -t your-db-container pg_dumpall -c -U postgres > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql

2. Restoring db with new instance -- Using cat your_dump.sql | docker exec -i your-db-container psql -U postgres -d your-db-name 

But I see multiple error as shared in screenshot below. 
![picturemessage_krtkdzc4 cqd](https://user-images.githubusercontent.com/50797731/83880780-52225400-a75d-11ea-9160-4b7adf7b200a.png)

What am I missing?

**Comment by pbortnik** [comment]
Your database is not clear. You need to restore backup to absolutely clear and fresh db.

**Comment by priyankachaturvedi30** [comment]
@pbortnik : How do I check that the new instance of db is fresh. I just hosted the new instance of reportportal on Server B using : docker-compose -p reportportal up -d --force-recreate
I am assuming doing that should not create any data for postgres

**Comment by priyankachaturvedi30** [comment]
It worked. Thanks @pbortnik
