### ISSUE TITLE
ClassCast exception with saml login

### ISSUE THREAD

**Issue by maartenjanvangool** [reportportal/reportportal#1001]
The piece of code below breaks saml login, at least in our case. Not surprising, since the principal here is just not a report portal user. When I now try to login with saml, I get a class cast exception... 

https://github.com/reportportal/service-authorization/blob/701807d5f7a0fd60e1be19adb4ea7e6b6fafca2d/src/main/java/com/epam/reportportal/auth/event/UiAuthenticationSuccessEventHandler.java#L58

**Comment by VolhaKarenko** [comment]
SAML is working in versions 5.7 and later, please see the documentation for SAML Okta integration: https://reportportal.io/docs/Okta-SAML-integration
and SAML Azure integration: https://reportportal.io/docs/Azure-SAML-integration
