### ISSUE TITLE
Unable to raise JIRA defect in RP[v5]

### ISSUE THREAD

**Issue by ghost** [reportportal/reportportal#1003]
Describe the bug
I'm unable to post a defect in Report Portal. whereas I'm able to post a request

To Reproduce
I have added JIRA plugin - plugin-bts-jira-5.1.0-all.jar.
I had done all the required configurations:
![image](https://user-images.githubusercontent.com/50138350/80967441-03b72800-8e34-11ea-98ca-8242b0f59349.png)

The same configurations when done from the JIRA UI... I'm able to post the defect.
![image](https://user-images.githubusercontent.com/50138350/80967465-0b76cc80-8e34-11ea-980a-5b7ffd61bdf6.png)

when i checked the docker logs for container: reportportal/service-api:5.1.0
it says: [com.epam.ta.reportportal.exception.ReportPortalException: Impossible interact with integration. [ErrorCollectionstatus=400, errors=customfield_10111=data was not an object, errorMessages=[]]]

Here: customfield_10111 is the "found in" field.

Question is: why is various field like "found in" mandatory? whereas in my JIRA UI its not mandatory parameter. is there any way to unmandate it ?

Expected behavior
A valid Defect should be created.

Desktop (please complete the following information):

OS: Windows
Browser: chrome
Version: RP v5
![image](https://user-images.githubusercontent.com/50138350/80967484-13cf0780-8e34-11ea-9c0f-f9bd8c9825c1.png)

**Comment by evjlobanova** [comment]
Will be added in scope of Jira refactoring

**Comment by MaryiaRymarchyk** [comment]
The issue is not reproducible in latest versions of RP and Jira plugin - therefore ticket will be closed.
If any concerns remain - feel free to create new  ticket.
