### ISSUE TITLE
Unable to Post bug to Rally from RP[v5.2.2]

### ISSUE THREAD

**Issue by nsmaniqa** [reportportal/reportportal#1004]
**Describe the bug**
I'm unable to post a defect in Report Portal. whereas I'm able to link defect from rally

**To Reproduce**
I have added Rally plugin 
I had done all the required configurations:(link o BTS, ProjectID IN bts, accessKey)- connection connected .

**Expected behavior**
It should display configured project in the project drop down box and it should allow to create defect from report portal

**Actual behavior**

1,Project drop down box is not listed out configured project but some other project getting displayed
2, Not able to post issue

when i checked the docker logs for container: reportportal_api_1
it says: [com.epam.ta.reportportal.exception.ReportPortalException: Impossible interact with integration. UNABLE TO SUBMIT TICKET:imposible intteract with integration.Errored]

Question 1:
 why is various field like "found in" mandatory? whereas in my Rally UI its not mandatory parameter. is there any way to change as non mandatory field?

Question 2:is this issue related to rally access or any additional configuration  required?

could you please help me on this?

**Comment by evjlobanova** [comment]
*Question 1:*
We just receive information from Rally, so that no, you can not

Question 2: 
I did not get you question, what do you mean? Please elaborate

We need logs of API services

**Comment by nsmaniqa** [comment]
I am not able to post any defect  to rally from report portal .
Question1.
How to get project id from rally that appear in the "create Manual integration window"?

![image](https://user-images.githubusercontent.com/24572238/84219368-596b9980-aa9e-11ea-8623-c141e28d3826.png)
[](url)
I got it from below url - please confirm me whether that is correct or not.
"https://rally1.rallydev.com/slm/ebservice/V2.0/project?query=(Name=%22SAMPLE%20PROJECT%22)&fetch=objectID")

2. If above url is correct to get project ID corresponding project name should display in project drop down list after successful integration but is is not displaying.
however i am able view other project name for which i have view access only.
 Even if i give project ID as "123456789" in integration window it gets connected successfully and same list of projects gets displayed under project drop down.
![image](https://user-images.githubusercontent.com/24572238/84218971-8c615d80-aa9d-11ea-956f-39142d51a97d.png)


3, Please share me if you have any screenshot or sample document

Please help me to resolve post issue

**Comment by evjlobanova** [comment]
1.  ProjectID is a <project key in bug tracking system>
Example of URL https://rally1.rallydev.com

**Comment by evjlobanova** [comment]
![image](https://user-images.githubusercontent.com/30413511/84360311-8caf4500-abd2-11ea-9d51-4e4ef82438c5.png)

**Comment by evjlobanova** [comment]
Once you resolve the first issue, I suppose the second question will be resolved also.
Regarding the 3rd question, what screenshot do you need?

@svettsova maybe you have an idea?

**Comment by nsmaniqa** [comment]
Still you are not answering my first question. 
what is project key bug tracking system? 
how to get project key from rally?

please help me on this one.

**Comment by e-olga** [comment]
hello @nsmaniqa,
1) As I understand, the question about the url resolved (url: https://rally1.rallydev.com/ could be used)
2) The project id could be found in the url **'https://rally1.rallydev.com/#/<**projectId**> when you are already logged in Rally
3) The access key could be generated on https://rally1.rallydev.com/login/accounts/index.html#/keys

Please let us know whether your issues resolved.

Regards,
Olga

**Comment by evjlobanova** [comment]
closed due to no answer
please reopen if it is still valid
