### ISSUE TITLE
Analyzer: Add a boost for items with the latest Defect Type 

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1005]
I have a use case wherein I have executed 3 builds. There was 1 failure with the same stacktrace(log) in each of the 3 builds.
For the first build, I marked it as and Product Bug. When the Second build executed it got Auto-analyzed as Product Bug, but then I realized it is no longer a Product Bug but an Automation Bug instead. So I manually updated it to the category of Automation Bug. Now the same failure occurred in the 3rd Build. It now got Auto Analyzed as Product Bug. Can you help me understand why it didn't get AA as Automation Bug (even when I manually override it)? Is there some priority within the defect types defined? 

![image](https://user-images.githubusercontent.com/50797731/84143091-95d5d000-aa73-11ea-8f94-424824cb4431.png)

**Comment by evjlobanova** [comment]
@priyankachaturvedi30 please answer on several questions:
1. Version of ReportPortal
2. Could you please click on History of Actions tab, click on the link to item that has been used for autoanalysis, and  send me a screenshot of this item

**Comment by priyankachaturvedi30** [comment]
@evjlobanova :
Please find the details below.

ReportPortal Version - 
![image](https://user-images.githubusercontent.com/50797731/84152858-d12bcb00-aa82-11ea-8dd3-24a2919f2e9c.png)

History of Items tab screenshot -- 
![image](https://user-images.githubusercontent.com/50797731/84153572-b1e16d80-aa83-11ea-8626-5ad9d00e8f35.png)

Please let me know if you need more details.  From what I thought, Manual update of any Auto-Analysed issues should take precedence for the next run.

**Comment by evjlobanova** [comment]
So as I see on the screenshot, item from the Launch # 3 takes his defect type from the item from Launch # 1. 
Because they have the same log.
Should  item in Launch # 1 have defect type Product Bug?

**Comment by priyankachaturvedi30** [comment]
Yes, infact the same log is present for Launch # 2. 
![image](https://user-images.githubusercontent.com/50797731/84158159-2e2a7f80-aa89-11ea-97e1-3832d6a7bdf0.png)


My question here is if I updated some item manually to a different defect type, should it not be given precedence in next runs if the logs are the same.

**Comment by evjlobanova** [comment]
In this exact situation, in ES there 2 equal logs with different Defect types. So that for Analyzer it is a tricky question. But in the future run, f.e. if you will have 3 equal logs: 1 PB, 2 AB - analyzer will choose AB.

**Comment by evjlobanova** [comment]
Does it help? Can I close the issue?

**Comment by priyankachaturvedi30** [comment]
yes @evjlobanova. This is helpful. So what I infer is that it takes the most accurately matching log in account while auto-analysing and if there happens to be more than 1 match (say 1 PB ; 1 AB) then it takes the number of occurrence(count as defined in last comment) as well to boost up the percentage value. And then categorize it in the highest percentage value defect type.

**Comment by evjlobanova** [comment]
@MariyaIvanina Masha could you please help me with the better explanation?

**Comment by MariyaIvanina** [comment]
@priyankachaturvedi30 Yes, you are right, we taking most similar log and calculate per group statistics. We are also trying to break the tie if we have the same probability we are choosing the one with most recent date, if dates are the same, then it is just random. I see in your case test item dates are just the same "2020-06-09 00:16:17", that's why it was just random allocation of PB, if you had 2 AB and 1 PB, I'd guess the probabilities won't be the same and AB will be chosen.

**Comment by evjlobanova** [comment]
Thank you @MariyaIvanina 
Anyway @priyankachaturvedi30 we will discuss internally your use case, and think how it is better to deal in such a situation.

**Comment by priyankachaturvedi30** [comment]
Thanka @MariyaIvanina @evjlobanova : I have got a better understanding now.Just 1 more doubt. Say if I have similar stacktrace and have marked the launches as below:
Launch 1 : PB (manual)
Launch 2 : PB (Auto-Anlayzed)
Launch 3 : AB (Manual  - in a case say where PB got resolved and I now need to update my Automation script so the defect now becomes AB for me)

Now that the item with same stacktrace is 2PB and 1AB (in the latest run) -- what would be the AA result for Launch 4 ? Would it mark it as PB (Since the count for it is 2) or would it mark it as AB (since this is the most recent manual overwrite I have made)?

**Comment by evjlobanova** [comment]
@priyankachaturvedi30  PB
But in the launch # 5 there is most likely will be AB  (if you have changed to AB in launch 4)

**Comment by MariyaIvanina** [comment]
@priyankachaturvedi30 We don't have a separate logic about manual overriding defect types, so I think the result will be PB, because we have 2:1 proportion of defect types.

**Comment by evjlobanova** [comment]
@priyankachaturvedi30 As I told you earlier, we will think about adding of this logic) 
I suppose it could be, but we should think about it carefully

**Comment by priyankachaturvedi30** [comment]
@evjlobanova One more use case got across my mind. Say I have 2 test cases(TC1 and TC2). There is a message pop-up that I need to verify in both these cases as one of the intermediate scenarios. Now suppose,  Failure occurs while validating the pop-up in TC - 1 -> due to system slowness the pop-up did not gets loaded and in TC - 2 -> the pop-up genuinely does not load because of some product bug in that particular testcase. My teststep for validating the pop-up is same, so it will through same error for both the above scenario. (say for eg -- error loading pop-up timeout after 60 seconds : Could not locate element:). But for TC-1 , I would mark the scenario as System Issue and for TC-2 , I would mark as Product Bug. Now in Launch # 2 , either of the two TC1 or TC2 failed again, how is AA going to categorize considering the stacktrace is again the same?

**Comment by MariyaIvanina** [comment]
@priyankachaturvedi30 we use a test case history as a boost, so analysis will have this information, but the model is trained and it has different weights for used statistics, so I guess that defect type from TC1 will have advantage for the next run and for the same log, but we can't say exactly what the probability will be.

**Comment by MariyaIvanina** [comment]
@priyankachaturvedi30 One more question about your first use case. Could you please explain, why would you like to override the defect type for the test item with the same log? I wonder whether the first run was a real Product bug, and in the 3rd run it is not a Product bug, but Automation bug, so other conditions implies you to say different defect types for the same error logs? or the first run was too Automation bug(but you thought it a Product bug earlier), but you understood it only in the 3rd and that's why decided to override it like this?

**Comment by priyankachaturvedi30** [comment]
@MariyaIvanina : Same error log can be seen in an example where say the some button is actually missing(PB) or the same button xpath is incorrectly specified in automation Script(AB). In both these case the same error would be thrown : Unable to locate element. Now for 1 launch : Since button is not there so I marked it as PB. The issue got fixed and now the button is there. So now when I run my Launch 2 : the script would fail because of the incorrect xpath reason so I would want to mark it as AB. This is just an example scenario where I would want to override my bug type in subsequent runs. Hence some boost which returns the latest defect types in case of same log trace would be really helpful. Please suggest if you have a better way to handle such cases. Much appreciated.

**Comment by priyankachaturvedi30** [comment]
Also, as suggested by you, Maybe the user realizes it on further investigation that the issue is not actually a PB but an AB. So he might want to override it so that it is correctly analyzed in future runs. There can be a fair possibility as stated by you that maybe in later runs the actual issue type is discovered and the user would want to override the previously marked defect type.

**Comment by evjlobanova** [comment]
@priyankachaturvedi30 We are planning to add this improvement in a scope of 5.3

**Comment by priyankachaturvedi30** [comment]
Great ! Much Appreciated.

**Comment by priyankachaturvedi30** [comment]
Hey @evjlobanova : This is algorithm that takes a "boost on recency VS frequency" is highly anticipated for our use case. Just to follow up, till when can we expect this feature to get released?

**Comment by evjlobanova** [comment]
Will be available in version 5.3 (~27th of July)
