### ISSUE TITLE
results of testcases mixed between executions while displaying history

### ISSUE THREAD

**Issue by odubaj** [reportportal/reportportal#1009]
There might be a problem with displaying history of test-cases and their results between launches

It is awaited, that one launch will have its test-case results in one column. In this case, it is mixed. 

screen 3 contains on row 1 column 1 launch No.7 for ruby-el8

screen 2 contains on row 1 column 2 launch No.6 for ruby-el7

screen 1 contains on row 2 column 2 launch No.7 for ruby-el8

It means that results of launch No.7 of ruby-el8 is displayed in multiple columns and not in one, as we might expect. It seems to me, like non-deterministic results reading from DB, but not sure about it.

Applicable on version currently available on web.demo.reportportal.io 

![1](https://user-images.githubusercontent.com/44674278/84278247-cc275400-ab34-11ea-9fe1-9694003b9d9a.png)
![2](https://user-images.githubusercontent.com/44674278/84278253-cdf11780-ab34-11ea-854b-1762e051bbdd.png)
![3](https://user-images.githubusercontent.com/44674278/84278261-ce89ae00-ab34-11ea-8991-554d4f52741f.png)

**Comment by evjlobanova** [comment]
@odubaj it is not a bug, it is a new logic for History of Table. 
You can find a description in our documentation:
https://reportportal.io/docs/History-of-launches%3Ehistorical-trend-of-executions

If you have any question regarding this functionality, please let us know
