### ISSUE TITLE
Does RP REST API support basic authentication?

### ISSUE THREAD

**Issue by lifemanship** [reportportal/reportportal#101]
See my comment https://github.com/reportportal/reportportal/issues/99#issuecomment-292557094

**Comment by avarabyeu** [comment]
@lifemanship it doesn't. but you can request token the same way as ui does (via basic auth) and then use it. Have a look at request to server after clicking login button

**Comment by lifemanship** [comment]
@avarabyeu Thanks

**Comment by EricLSD** [comment]
So I may be missing something but I feel like the question here isn't entirely answered.  When I look at the request to the server after clicking the login button, I see /ui/#login.  The contents of the `requests.get()` response provides no insight into what the API token is.  

I'm using python requests.get() with basic auth.  Any pointers on how to get passed this would be helpful - I do not have access to the server logs and RP is running on a container.  -Thanks!

**Comment by DzmitryHumianiuk** [comment]
@EricLSD please take a look here:
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#retrieving-api-token
it might give the answer
