### ISSUE TITLE
Launch never finishes but CI job finishes successfully [v5]

### ISSUE THREAD

**Issue by serhiikachan** [reportportal/reportportal#1011]
We have upgraded RP from 4.3 to 5.2.
Upgraded agents accordingly: 
**agent-java-cucumber4** 5.0.0-Beta-9
**client-java** 5.0.0
**logger-java-logback** 5.0.0

Launch stucks and never finishes until performing force finish manually, however job completes successfully.
We might have up to 50 launches executing in parallel, and this problem applies for several pipelines, not for all of them.

![image](https://user-images.githubusercontent.com/33296989/84308289-e9751600-ab66-11ea-9387-10f126ce9a11.png)

Explanation: on the screenshot RP indicates that launch is still running and started 1 hour ago, but it already finished within 23 minutes since started.

Previously we hadn't had issue like that is 4th version.

**Comment by DzmitryHumianiuk** [comment]
@SerhiiKachan try to clean the cache.
there is not option not to finish launch in v5, that was a groundbreaking change in v5.
the only possible reason is kill of process.

please try to refresh dependencies.

**Comment by SerhiiKachan** [comment]
@DzmitryHumianiuk thanks, will try to clear cache. 
looks like here are used the latest releases of agents. Or what do you mean ?

**Comment by DzmitryHumianiuk** [comment]
@SerhiiKachan we see quite often that after version bump, mvn dependencies continue to use old cached versions.
