### ISSUE TITLE
Display more results in Flaky/Most Failed test case tables

### ISSUE THREAD

**Issue by snackattas** [reportportal/reportportal#1013]
**Describe the solution you'd like**
Right now, My 2 favorite widgets are the `Most failed test-cases table` and the `Flaky test cases table`. 

<img width="187" alt="06-11-2020 09 26 38_F0ycdT" src="https://user-images.githubusercontent.com/12533693/84398601-c594ed00-abc5-11ea-8a2d-02aec66c68ff.png">

But they only display the TOP 20 results !?!?!  I would LOVE it if these charts were able to configure the amount of results to display. If it were up to me, I'd configure it to show ALL tests.

But at least, configuring to like 50 or 100 would be nice

Side note: it's funny that in the widget `Most failed test-cases`, the word test cases has a hyphen, but no hyphen in `Flaky test cases table`

**Is your feature request related to a problem? Please describe.**
Well, its related to the problem where I have a flaky test suite, and want to better manage the flakiness at play

**Comment by evjlobanova** [comment]
@snackattas It will be really nice! For now limit 20 has been chosen because of performance limitations. 
We are planning to implement in the future a materialized view widgets, which will show a really  heavy statistics.

For now, we have a History table view, on that view, you can find Flaky and Most failed items by yourself.
![image](https://user-images.githubusercontent.com/30413511/84401782-55f62080-ac0c-11ea-9cb0-aeee3ba61629.png)

https://github.com/reportportal/reportportal/issues/896

**Comment by evjlobanova** [comment]
#884

**Comment by snackattas** [comment]
I understand if there are performance concerns.

But my test launch is pretty tiny, one run is only like 200 tests

So i would gladly incur performance costs if there was a way to hack it together

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova top20 was a limit for MongoDB based API.
Queueing PostgreSQL might be cheaper from performance standpoint.

**Comment by evjlobanova** [comment]
@snackattas so I suppose, you are proposing the same thing as described in #884. am I right?

**Comment by snackattas** [comment]
#884 is about adding filtering capabilities to the "Most failure test-cases" widget (now it only allows filtering by name)

I'm talking about showing MORE test cases in the widget. Right now it only shows TOP 20, but I'd like to show top 100

**Comment by idxn** [comment]
Upvoted this. I really want to see this implement soon.

**Comment by ananthprasads** [comment]
Are there any updates on this?

**Comment by DzmitryHumianiuk** [comment]
@ananthprasads Flaky test cases widget. Increase the amount of items to be displayed on widget from 20 to 50. 
will be in version 5.8

**Comment by Kozovskaya** [comment]
Hello @snackattas and @ananthprasads, in our latest release 23.1 the Flaky test cases table widget was updated and now it shows TOP-50 test cases.
