### ISSUE TITLE
Unable to post screen recorded video in project path to reportportal logs section 

### ISSUE THREAD

**Issue by Nagalakshmi17** [reportportal/reportportal#1015]
public static void StartRecorder() {
		((CanRecordScreen) driver).startRecordingScreen();
	}

	public static void StopRecorder(String methodName) throws Exception {
		String media = ((CanRecordScreen) driver).stopRecordingScreen();
	
		java.util.Date d = new java.util.Date();

		String dirPath = "./videos/" + methodName + " " + d.toString().replace(":", "_");

		File videoDir = new File(dirPath);

		synchronized (videoDir) {
			if (!videoDir.exists()) {
				videoDir.mkdirs();
			}
		}
		FileOutputStream stream = null;
		ReportPortalMessage message = null;
		
		try {
			 stream= new File(videoDir + File.separator + ".mp4");
			 stream = new FileOutputStream(videoDir + File.separator + ".mp4");
                         stream.write(Base64.decodeBase64(media));
			stream.close();
                       String rp_message = "test message for ReportPortal";
	        	message = new ReportPortalMessage(stream,rp_message);
		

		} catch (Exception e) {
			utils.log().error("error during video capture" + e.toString());
		} finally {
			if (stream != null) {
			}
		}
	}

**Comment by DzmitryHumianiuk** [comment]
@Nagalakshmi17 there is a file size limit.
128Mb in single request (@Yumfriez  can confirm).

@Nagalakshmi17 any errors in logs?

**Comment by Nagalakshmi17** [comment]
error during video capturejava.lang.NullPointerException

**Comment by Yumfriez** [comment]
@Nagalakshmi17 @evjlobanova Exception is not related to the RP components. Also I can't see RP method for sending attachments in your code example. Try to use one of our examples with attachments reporting flow and let me know if you still have any issues.
https://github.com/reportportal/examples-java
