### ISSUE TITLE
Launch Specific URL redirects to the last login project for the user

### ISSUE THREAD

**Issue by chhatbarjignesh** [reportportal/reportportal#1018]
**Describe the bug**
I am generating the Launch URL for the slack notifications dynamically after each launch completes for example `https://reportportal.****.com/ui/#project_name/launches/all/100969` where #project_name is the project in which launch was executed and 100969 is the id of launch now when user clicks on that link and if they are not logged in or in the different project then it automatically changes to `https://reportportal.****.com/ui/#last_login_project/launches/all/100969` where #last_login_project is the project that logged in user is currently on or was logged in. 

This is creating problems like below hope screenshots will help

**Expected behavior**
It should open the correct project

**Screenshots**
Last Login Project:
![image (9)](https://user-images.githubusercontent.com/34551874/84521746-758c5800-aca3-11ea-903c-e2278a25a0e8.png)
URL Screenshot:
![image (10)](https://user-images.githubusercontent.com/34551874/84521784-8046ed00-aca3-11ea-8e19-0ba56cd85056.png)
Actual Behavior in RP:
![imagefinal](https://user-images.githubusercontent.com/34551874/84521810-8b9a1880-aca3-11ea-9603-39da66ca20ad.jpg)

**Versions:**
 - OS, Browser
 - Version of RP 5.2.2

**Comment by chhatbarjignesh** [comment]
While doing further investigation, I found that if I pass the project name in lowercase it works fine. Now the priority is changed but it's worth looking into

**Comment by evjlobanova** [comment]
@Yumfriez could you please check this issue?

**Comment by evjlobanova** [comment]
@chhatbarjignesh projects are saved in DB in lowercase, so it works as it was considered, I suppose
It is not actually a bug

**Comment by chhatbarjignesh** [comment]
@evjlobanova I agree but when I make the API calls its not case sensitive, upper or lower case my API call works but when I enter in URL as upper case its not working. I am fine closing the issue but I think it should return the correct data irrespective of the case in URL too as it is returning the data via API.

**Comment by chhatbarjignesh** [comment]
Closing this issue as discussed in the above thread, Future visitors, however, you enter the project name upper case lower case while creating through UI it stores it in lowercase in the database, API call works fine irrespective of case, but when entering URL in browser you have to use Project Name as a lower case to make it work.
