### ISSUE TITLE
Attachments preview in pop-up

### ISSUE THREAD

**Issue by admizh** [reportportal/reportportal#102]
We have html attachments, in prev PR release - attachments (non image) is oppened in new browser tab. But in current release for see html attachments we should click to attachment, save content and put it to IDE for rendering html. Pls add MIME type detection  in to attachments preview pop-up

![2017-04-11_16-06-39](https://cloud.githubusercontent.com/assets/6014483/24908432/102599da-1ed1-11e7-93c4-f12270f606d1.png)

**Comment by avarabyeu** [comment]
@admizh actually, UI don't need to detect type of attachment since its returned from server. Doesn't really understand what kind of update do you suggest. Would you like to see HTML (only) attaches in new window?

**Comment by aliaksandrbasau** [comment]
I would also like to see a functionality to render html from an attachment. It's really inconvenient that you have to copy and paste source from the dialog, put into a document on the file system and open the document in a browser. In 100% cases I need to see the rendered html, not its source.
The functionality can be implemented as a link/button on the dialog (e.g. Render HTML) that would open html attachment in a new tab. Or you can render html directly in the dialog within iframe but it's less preferable.

@lexecon You can use the following workaround for now - open Web Inspector, click HTML attachment that opens the dialog, copy the url of the request to the server, open the url in a new tab. For me it's easier that copy-pasting into a new file.

**Comment by DzmitryHumianiuk** [comment]
will be opened in new tab.
remove support of HTML mime type.
