### ISSUE TITLE
[v5] Logs order within the same second is wrong

### ISSUE THREAD

**Issue by goncaloneto** [reportportal/reportportal#1020]
**Describe the bug**
The logs should take into consideration the milliseconds in the timestamp. Right now, if the 2 or more messages are logged in the same second, ReportPortal is displaying the wrong order.

**To Reproduce**
Log multiple messages, one after the other.

**Expected behavior**
The order you used should be the same as the order displayed in RP logs.

**Screenshots**
![Screenshot 2020-06-18 at 13 46 47](https://user-images.githubusercontent.com/12399934/85021886-66594e80-b16a-11ea-8922-b095df6307d2.png)

**Desktop (please complete the following information):**
 - OS: macOS, Windows 10
 - Browser: Chrome 83
 - Version: 83

**Additional context**
I'm using xUnit to run the tests.

**Comment by evjlobanova** [comment]
@svettsova Valya could you please check this issue and try to reproduce?

**Comment by nvborisenko** [comment]
Not reproducible with the latest xunit agent v2.0.0-beta.3 and RP v5.2.2

```c#
for (int i = 0; i < 10; i++)
{
  Log.Debug($"From Class1.Test1 log #{i}");
}
```

And result
![image](https://user-images.githubusercontent.com/22616990/85200555-195bb080-b301-11ea-947b-a2946f905315.png)

**Comment by evjlobanova** [comment]
@nvborisenko @goncaloneto Can this issue be closed?

**Comment by VeranikaRymzha** [comment]
Hello @goncaloneto,
JFYI
We plan transferring from milliseconds to microseconds in ReportPortal version 6 so as to provide a higher level of precision and accuracy in the logs timestamps.

**Comment by VeranikaRymzha** [comment]
Hello @goncaloneto , 
I wanted to let you know that the ReportPortal 24.2 version is now live, along with the improvement you requested. We've added microseconds to the timestamp, providing higher accuracy in the log sequence.

You can find more details about the new features and enhancements in the [release notes](https://reportportal.io/docs/releases/Version24.2/). 
Feel free to try it out and share any feedback you may have.

Have a great day!
