### ISSUE TITLE
Unable to integrate Ready API with Report Portal (Not Soap UI)

### ISSUE THREAD

**Issue by bzsharm** [reportportal/reportportal#1021]
**Issue – Unable to integrate Ready API with Report Portal (Not Soap UI),**

When I checked in the “ready api” documentation from “reportportal.io”,
It says “DEPRECATED in favor of soapui agent (Refer Below),

https://github.com/reportportal/agent-readyapi

So, I opened another link from the above url ,
https://github.com/reportportal/agent-java-soapui

There were instructions to download the zip files, Instruction says
Copy the jar file from “ext folder” and Files from “Listener folder” to same location
Where we have installed soap UI.
In the zip file downloaded, I couldn’t find ext folder present in Ready API Folder.

Can you please advise on the above & Guide me any possible solutions available ?
About the configuration as custom properties, shall I make use of the same setting as soap ui ?

**Comment by evjlobanova** [comment]
We are not supported Ready API now. Only Soap UI.
We will be glad if you decided to contribute and update the Ready API agent.

**Comment by bzsharm** [comment]
> We are not supported Ready API now. Only Soap UI.
> We will be glad if you decided to contribute and update the Ready API agent.

Thanks for your response. 
I will definitely update if I have any progress.

**Comment by bzsharm** [comment]
, I won't be able to support it in the near future :(..

**Comment by bzsharm** [comment]
> We are not supported Ready API now. Only Soap UI.
> We will be glad if you decided to contribute and update the Ready API agent.

I accidentally closed this issue , could you please reopen it

**Comment by bzsharm** [comment]
> We are not supported Ready API now. Only Soap UI.
> We will be glad if you decided to contribute and update the Ready API agent.

Hey I have found a solution it's working in my local system, it perfectly works with Ready Api ( v 3.0) as well as Soap Ui (5.0.4) , 
I got it from a different community, 

Step 1 : copy attached an xml listener file in to Listener folder in bin and attached jar file in to Ext folder in bin, (Home directory Soap UI / Ready API) 

Step 2 : Update the Properties , 

In Ready ApI - Right click top most parent, project settings -> 3rd tab -> copy uuid, project, url and launch name from your report portal instance. Save and restart ready api. 

In Soap UI - add the properties directly to the custom properties , then save and Restart. 

Step 3 : Run the test. 


Could your please publish this listener and - jar file in to the main website. 

I was not able to attach the listener file and Jar file, please download it from the below git link

https://github.com/reportportal/agent-java-soapui/files/3405635/soapui-4.0.0-SNAPSHOT-full.zip

**Comment by bzsharm** [comment]
closing the ticket , as we found a solution for ready api integration with RP

https://github.com/reportportal/reportportal/issues/1084
