### ISSUE TITLE
[v5] Most failed test cases and Flaky test cases widget fail to populate data

### ISSUE THREAD

**Issue by snackattas** [reportportal/reportportal#1022]
**Describe the bug**
We are deploying report portal in kubernetes

We have about 60 launches, should be enough to populate either the Flaky test cases widget or the Most Failed test cases widget. but they consistently show up as having no data available

<img width="669" alt="06-18-2020 10 49 11_VOm7cu" src="https://user-images.githubusercontent.com/12533693/85042888-5f721200-b151-11ea-8548-aae8ce9de956.png">

**To Reproduce**
I haven't tried repro-ing

**Expected behavior**
Widget populates with data from runs

**Screenshots**
Not sure if this is relevant but I saw these msgs in the analyzer<img width="1388" alt="06-18-2020 10 46 16_Mq8r5U" src="https://user-images.githubusercontent.com/12533693/85042908-66992000-b151-11ea-849f-a5d98f61a464.png">

And these in rabbitmq
<img width="1395" alt="06-18-2020 10 35 18_kwVazT" src="https://user-images.githubusercontent.com/12533693/85042964-757fd280-b151-11ea-9322-ff8968d4399f.png">

**Comment by evjlobanova** [comment]
@snackattas Please send us a screenshot for widget wizard for this widget

**Comment by evjlobanova** [comment]
Regarding logs for Analyzer and Rabbit

The problem with the widget does not connect with these logs.
But these logs are not good at all)
I suppose the problem is in deployment.

Do you use Auto-Analysis?

**Comment by snackattas** [comment]
Is auto Analysis related to the display of those 2 widgets?
<img width="1380" alt="06-19-2020 09 31 46_yDTNts" src="https://user-images.githubusercontent.com/12533693/85143730-bb9b6b80-b20f-11ea-8d66-e71257a5d97b.png">
<img width="797" alt="06-19-2020 09 31 27_tTSebK" src="https://user-images.githubusercontent.com/12533693/85143738-bccc9880-b20f-11ea-95c4-618e29119735.png">
As you can see here, `HYDRA` is a found launch name
![2020-06-19 09 32 43](https://user-images.githubusercontent.com/12533693/85143851-e980b000-b20f-11ea-991e-1f2d33ebc764.gif)

**Comment by evjlobanova** [comment]
> Is auto Analysis related to the display of those 2 widgets?
No

**Comment by evjlobanova** [comment]
Do you have such launch?
Does this launch have failed items?

**Comment by evjlobanova** [comment]
Could you please share a screensot
 history table for this launch?

**Comment by snackattas** [comment]
Heres a history tab for one of the runs (there have been 74 runs)
<img width="1466" alt="06-19-2020 13 26 47_jk7OP3" src="https://user-images.githubusercontent.com/12533693/85168851-8eab8080-b230-11ea-8357-1de0d967cad2.png">

The history tab takes a REALLY long time to load, like, 30-40s
![2020-06-19 13 28 13](https://user-images.githubusercontent.com/12533693/85169215-17c2b780-b231-11ea-9e0a-944fd2e7797e.gif)

**Comment by evjlobanova** [comment]
I suppose the problem in the structure.
As I can on the screen you have report suite as a last element in structure
But a step is supposed to be the last element.
And Most failed widget is built on base of steps.

As far as there is no steps in the run, a widget shows no Data available.

Which agent do you use?
