### ISSUE TITLE
White space removed in stdout output

### ISSUE THREAD

**Issue by allan-silverstein** [reportportal/reportportal#1023]
Hi,
I'm using reportportal with pytest.  In some cases I have data written out to the screen in a table like format (using python tabulate).  When the data is displayed in my Linux shell, all the columns line up as the column data is padded to make the columns like up nice:

```
Device    Version    Uptime
--------  ---------  ----------------
au21      11.5.6.5   51 days, 1:13:23
hu22      11.5.6.5   51 days, 1:12:03
hu21      11.5.6.5   51 days, 1:15:40
au22      11.5.6.5   51 days, 1:18:06
dc21      11.5.7.6   3 days, 3:16:31
ph21      11.5.7.6   3 days, 3:29:29
```

However, when viewing the same data in Report Portal (when the Logging slider bar is at info), it appears multiple whitespaces are condensed into 1 and the column data no longer aligns:

```
Device Version Uptime
-------- --------- ----------------
au21 11.5.6.5 51 days, 1:00:06
hu22 11.5.6.5 51 days, 0:58:45
au22 11.5.6.5 51 days, 1:04:47
hu21 11.5.6.5 51 days, 1:02:24
dc21 11.5.7.6 3 days, 3:03:13
ph21 11.5.7.6 3 days, 3:16:10
```

Any suggestions to keep my original formatting?
Thx
Al Silverstein

**Comment by evjlobanova** [comment]
@iivanou Could you please check if this behavior is handled on the agent side on the server-side?

**Comment by iivanou** [comment]
First of all, I'd like to see how exactly "tabulated" data is being sent to RP. Try to run your tests with the DEBUG log level and you will see the exact text messages which are sent to the RP API. If they include 4 spaces, then the problem is on the server-side.

**Comment by allan-silverstein** [comment]
Sorry for not doing this sooner...
Here is the output with DEBUG log level.  It appears the proper spaces are intact in this log message but multiple spaces are condensed to a single space when displayed in Report Portal.  Hope this provides some insight for an easy solution.
thx
Al

DEBUG:reportportal_client.service_async:Processing item: ('log', {'time': '1592941875158', 'message': 'Report\nDNET Version Report\n\nDevice    Version    Uptime\n--------  ---------  ----------------\nau21      11.5.7.6   0 days, 6:47:54\ndc21      11.5.7.6   0 days, 22:39:35\nhu22      11.5.7.6   0 days, 6:52:01\nph21      11.5.7.6   4 days, 1:51:53\nhu21      11.5.7.6   0 days, 7:09:18\nau22      11.5.7.6   0 days, 7:13:08', 'level': 'WARN', 'attachment': None}) (queue size: 0)
DEBUG:reportportal_client.service_async:Processing log item: {'time': '1592941875158', 'message': 'Report\nDNET Version Report\n\nDevice    Version    Uptime\n--------  ---------  ----------------\nau21      11.5.7.6   0 days, 6:47:54\ndc21      11.5.7.6   0 days, 22:39:35\nhu22      11.5.7.6   0 days, 6:52:01\nph21      11.5.7.6   4 days, 1:51:53\nhu21      11.5.7.6   0 days, 7:09:18\nau22      11.5.7.6   0 days, 7:13:08', 'level': 'WARN', 'attachment': None}

**Comment by iivanou** [comment]
@evjlobanova It looks as a server-side problem 'cause the agent sends messages with the correct number of spaces.

**Comment by allan-silverstein** [comment]
We are using install from Docker container.  Do you think it is fixed a newer version?  We were planning to upgrade Report Portal version, if it is fixed in the newer version that would be a reason to upgrade sooner rather than later...
Here is what we are currently running:
Version Info:
API Service: 4.3.0
Index Service: 4.2.0
Jira Service: 4.3.0
Rally Service: 4.3.0
Authorization Service: 4.2.0
Service UI: 4.3.0

**Comment by evjlobanova** [comment]
Try to use the latest version.
We do not support 4 versions now.
Please upgrade your instance with the latest version, and tell us if the bug is still actual

**Comment by allan-silverstein** [comment]
Ok, I'll let you know what happens after we upgrade... It may be a couple of weeks.
Thx

**Comment by iivanou** [comment]
@allan-silverstein, You can use https://beta.demo.reportportal.io/ with your GitHub credentials for testing purposes while you are upgrading your environment.

**Comment by evjlobanova** [comment]
@iivanou  It is better to use  this env for user testing https://web.demo.reportportal.io/ui/

**Comment by allan-silverstein** [comment]
Just upgrade to Report Portal 5.2.2 and the problem has been fixed.  Thank you for your help.
