### ISSUE TITLE
Pattern Analysis - search scope expanded to whole log

### ISSUE THREAD

**Issue by mihtac** [reportportal/reportportal#1024]
I noticed that pattern analysis (for string at least) seems to only be looking in the "marked as failed" step in logs, and not whole log trace for that scenario. I'd prefer it to search through the whole log set for the scenario (bdd)
...

I am limited in what patterns I can define, since the search scope is only on failed steps
...

**Comment by evjlobanova** [comment]
Could you please provide more details on that request?

Now PA is searching patterns in Error logs and higher because the main goal for PA to define the items which failed with the same known problem.

Do you use nested steps? 
Which version of ReportPortal do you use?

**Comment by mihtac** [comment]
Yes, using nested steps.

It's report portal 5.2.1

Thing is, if I look for patterns (strings) higher than the failed steps, it does not match them. 

So if I have a negative test: 

step 5: when you make the request {...} - with the response body logged
step 6: then you receive a "bad request" response <- failed step, and scenario, because it was not a bad request

if my patterns looks for something that was logged as part of step 5, which PASSED but contains the error message, it does not match it. It only matches strings in step 6 that failed.

**Comment by evjlobanova** [comment]
Please try it with version 5.2.2
We fix this bug in this version
Please let we know regarding results

**Comment by evjlobanova** [comment]
Please reopen if the bug is still occuring
