### ISSUE TITLE
History of test cases not displayed fully - v5.2

### ISSUE THREAD

**Issue by odubaj** [reportportal/reportportal#1025]
Test case results are not displayed in history. 

We have 2 types of launches. Launch ruby-el7 is runned 3 times, lauch ruby-el8 is runned 4 times. So we have 7 launches in our system. The test plans are named the same and most of the test cases are identical. But if we display the history, we do not see all results, but just a few of them. The missing ones are displayed as if there were no such test-cases.

In the pic1 we can see that the history displays all launches of ruby-el8 with some launches of ruby-el7. In pic2 we see the exact same oposite -> all launches of ruby-el7 with some launches (exactly what is missing in pic1) of ruby-el8

Can you please explain why is the history not complete ? I might think, that I should be able to see full history in both views (pic1 and also pic2)

Thank you.

![pic1](https://user-images.githubusercontent.com/44674278/85105924-9dcc0780-b20b-11ea-8cbb-2fff6e95e4cd.png)
![pic2](https://user-images.githubusercontent.com/44674278/85105927-9f95cb00-b20b-11ea-85b4-6fd36af7945c.png)

**Comment by evjlobanova** [comment]
@odubaj Does a launch 'ruby-el8 # 4' have earlier start time as a launch 'ruby-el7 # 3'?

**Comment by odubaj** [comment]
No, the results of launches were imported (via API endpoint /v1/{projectName}/launch/import
) in the given order:

ruby-el7 #1
ruby-el7 #2
ruby-el7 #3
ruby-el8 #1
ruby-el8 #2
ruby-el8 #3
ruby-el8 #4

The only thing, that could potentionaly disturb something is file modification time, but I do not think this is relevant. If it was, we will be able to see full history from ruby-el7 #3 launch, which we do not see.

 From my point of view, there might be some kind of binding between test-cases in different-named launches, which should be both-sided (as in same-named launches), but from any reason it is only one sided -> that might be the reason, why we see part of full history from one launch (ruby-el7 #3) and the rest from second lauch(ruby-el8 #4)

**Comment by odubaj** [comment]
I am prividing reproducers for this issue
[ruby-el7.zip](https://github.com/reportportal/reportportal/files/4803627/ruby-el7.zip)
[ruby-el8.zip](https://github.com/reportportal/reportportal/files/4803628/ruby-el8.zip)

You need to just import the archives via mentioned API endpoint in the above mentioned order

**Comment by evjlobanova** [comment]
![image](https://user-images.githubusercontent.com/30413511/85125990-3cb92980-b235-11ea-8ea5-fb14b62924da.png)
![image](https://user-images.githubusercontent.com/30413511/85126046-55294400-b235-11ea-9011-81e0f7cd257b.png)


Hover the highlighted panels on the History and send me a screenshot with tool tip please

**Comment by evjlobanova** [comment]
https://reportportal.io/docs/History-of-launches%3Ehistorical-trend-of-executions

**Comment by odubaj** [comment]
![Snímka obrazovky z 2020-06-19 13-03-41](https://user-images.githubusercontent.com/44674278/85126444-c5cc6280-b22d-11ea-91fe-271bb743b264.png)
![Snímka obrazovky z 2020-06-19 13-04-08](https://user-images.githubusercontent.com/44674278/85126446-c6fd8f80-b22d-11ea-96b2-04f57adea6b1.png)
![Snímka obrazovky z 2020-06-19 13-04-16](https://user-images.githubusercontent.com/44674278/85126450-c82ebc80-b22d-11ea-9d4d-71669488880b.png)
![Snímka obrazovky z 2020-06-19 13-04-20](https://user-images.githubusercontent.com/44674278/85126454-c95fe980-b22d-11ea-8cca-eedcb8f8add5.png)
![Snímka obrazovky z 2020-06-19 13-04-32](https://user-images.githubusercontent.com/44674278/85126458-ca911680-b22d-11ea-8df0-19f05ebe1e2b.png)

**Comment by evjlobanova** [comment]
@odubaj The root cause here is an imported file. 

We are trying to debug this an get back to you

**Comment by evjlobanova** [comment]
@svettsova Valya could you please recheck this issue

**Comment by odubaj** [comment]
Hello, is this issue a bug ? Are you willing to fix it ? Thanks

**Comment by evjlobanova** [comment]
@odubaj We have problem with the History for imported files 
The priority for features connected with import is minor, because our  main functionality is real-time reporting

I can not say exact estimations.  
Firstly we need to debug the nature of this.

If this bug is really crucial for you, we can propose a paid support and we can fix  it in a scope of the contract

**Comment by e-olga** [comment]
hi @odubaj 
I tried to import your launches in the order you mentioned above one by one.
After the each file imported, I had been waiting for all the test cases got the start time with "time ago" meaning, e.g. "some seconds ago".
When all the seven launches were imported I got the next view of history table
![import 1025](https://user-images.githubusercontent.com/22497746/86240899-a7118880-bbaa-11ea-865d-4083e76bf2f0.png)

The issue could refer to the start time of items that are in the queue, so do not got the real start time, as far as the import is asynchronous operation. 
Please import the files one by one and wait for the reporting of all the test cases from a particular launch to prevent the non-consistent view of history table.

Regards,
Olga

**Comment by odubaj** [comment]
Thank you for the explanaition, this might be the source of problems
