### ISSUE TITLE
Launch not getting created after successful execution

### ISSUE THREAD

**Issue by sateeshg** [reportportal/reportportal#1026]
I'm new to report portal. Just want to integrate with testng framework and view the test execution details. As suggested in the report portal documentation, i cloned report portal java examples repository (https://github.com/reportportal/examples-java), modified report portal properties in example-testng-log4j and example-testng-logback and executed the tests.

I'm getting following error when I executed tests in example-testng-log4j project

"2020-06-19 16:30:05,463 main ERROR Error processing element ReportPortalLog4j2Appender ([Appenders: null]): CLASS_NOT_FOUND
2020-06-19 16:30:05,528 main ERROR Unable to locate appender "ReportPortalAppender" for logger config "root"
2020-06-19 16:30:05,528 main ERROR Unable to locate appender "ReportPortalAppender" for logger config "com.epam.reportportal.service"
2020-06-19 16:30:05,528 main ERROR Unable to locate appender "ReportPortalAppender" for logger config "com.epam.reportportal.utils"
2020-06-19 16:30:14,975 [rp-io-9] ERROR com.epam.reportportal.service.Launch - [25] ReportPortal execution error
com.epam.reportportal.exception.InternalReportPortalClientException: Report portal is not functioning correctly. Response is not json. Uri: [http://localhost:8080/api/v2/superadmin_personal/launch]; statusCode: [403]; statusMessage: [No valid crumb was included in the request];
"

Whereas tests run without any errors in 'example-testng-logback' project, but no launches are created in report portal.
 T E S T S
-------------------------------------------------------
Running TestSuite
WARNING! More than one ReportPortal listener is added
[TestNG] [WARN] Ignoring duplicate listener : com.epam.reportportal.testng.ReportPortalTestNGListener
[TestNG] [WARN] Ignoring duplicate listener : com.epam.reportportal.testng.ReportPortalTestNGListener
[AppClassLoader@18b4aac2] warning javax.* types are not being woven because the weaver option '-Xset:weaveJavaxPackages=true' has not been specified
Tests run: 36, Failures: 0, Errors: 0, Skipped: 20, Time elapsed: 10.869 sec - in TestSuite

Results :

Tests run: 36, Failures: 0, Errors: 0, Skipped: 20

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.493 s
[INFO] Finished at: 2020-06-20T09:21:41-07:00
[INFO] ------------------------------------------------------------------------

could anyone please let me know why the launch is not getting created in report portal after tests are completed? also, how to resolve report portal execution error in 'example-testng-log4j' project?

**Comment by sateeshg** [comment]
Figured the issue. This issue happened as jenkins was also running on same port. Resolved by updating report portal port.

**Comment by HardNorth** [comment]
@sateeshg Please pull latest changes from examples, I found an issue with them and updated them.
