### ISSUE TITLE
Is there a way to generate a Delta between 2 launches?

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1027]
Given UseCase:
Launch # 1 -- PB1 ; AB1 ; SI1 
Launch # 2 -- PB1; AB1 (Both AA) + New PB2(To Invest)
Launch # 3 -- AB1; PB2 (AA)

Now as I see, Launch # 2 does not have any System Issue (it must have been fixed). Similarly, Launch # 3 does not have PB1 (fixed again). So I want to know if we have can any delta report or something which compares the two launches and tells us the difference between them. This way I would have a fair idea of what issues got fixed in subsequent runs. Please suggest.

**Comment by evjlobanova** [comment]
Hello, it depends on the fidelity you need.

We have several approaches that can be used:

**1. Widget**

You can make a filter based on the launches with the same name. And then you can create a widget "Launch Statistics chart" and track the defect type structure from run to run: 
![image](https://user-images.githubusercontent.com/30413511/85510961-c0da2b00-b600-11ea-9bf4-0ec8a17125d9.png)
Details are here: https://reportportal.io/docs/Launch-statistics-chart

**2. Comparing launches side by side:**
You can make a filter based on the launch you want to use a the base for comparing. And the drill down by statistics to the step view, go to History view and add a custom column to History table. 
 
![image](https://user-images.githubusercontent.com/30413511/85511531-5fff2280-b601-11ea-9462-56d134951dbc.png)

Details are here: https://reportportal.io/docs/History-of-launches%3Ecompare-launch-results-with-the-filter

Do these approaches suit you? Please share your vision

**Comment by priyankachaturvedi30** [comment]
Thanks @evjlobanova . I tried creating a widget as suggested by you. I am facing the following error while adding a widget to a filter.
![image](https://user-images.githubusercontent.com/50797731/85532040-fb59bd00-b62c-11ea-9fed-aa0b8bbe2ae3.png)

**Comment by evjlobanova** [comment]
@priyankachaturvedi30 I see, we have a known issue with creating a widget from All launches
We will be fixed in the next bugfix versions.

Try to create this widget from the Dashboard page.
