### ISSUE TITLE
API Automation - Launch not created

### ISSUE THREAD

**Issue by Bharadwaj-vana** [reportportal/reportportal#1029]
Hi Team,

I am trying to use API & create a launch in ReportPortal.io, but when I tried POST call using RestAssured I was able to get response but I was not able to see any launch in ReportPortal.io UI. I also tried hitting the API using postman and unable to see launch results in ReportPortal.io UI. Please refer below body tried as request.

**Base URL** : http://{{Report Portal instance Path}}/api/v1/superadmin_personal/launch
**Sample Body:** 
{
   "name":"superadmin_Web",
   "description":"My first launch on RP",
   "startTime":"1574423221000",
   "mode":"DEFAULT",
   "attributes":[
      {
         "key":"build",
         "value":"0.1"
      },
      {
         "key":"test",
         "value":"test"
      }
   ]
}

**Sample - Response:** 
{
    "id": "76c1e6f5-60bb-4248-8350-03a9c162a83a",
    "number": 17
}

Please let me know what needs to be done on same Thanks !

**Comment by evjlobanova** [comment]
@svettsova Valya could you please assist here?

**Comment by svettsova** [comment]
Dear @Bharadwaj-vana,

From the response we can see that your launch is created. It has "UUID": "76c1e6f5-60bb-4248-8350-03a9c162a83a" and number 17. 
Can we have a call via skype to solve an issue? live:valya.svettsova 

Regards,
Valentina

**Comment by Bharadwaj-vana** [comment]
> Dear @Bharadwaj-vana,
> 
> From the response we can see that your launch is created. It has "UUID": "76c1e6f5-60bb-4248-8350-03a9c162a83a" and number 17.
> Can we have a call via skype to solve an issue? live:valya.svettsova
> 
> Regards,
> Valentina

Hi Valentina,

Sure Thanks for the help !

**Comment by Bharadwaj-vana** [comment]
Hi @svettsova 

Thanks for the support, Can you please let me know how to proceed further with same issue, as still we are not able to see launch results in ReportPortal.io UI.

Thanks,
Bharadwaj Vana.

**Comment by svettsova** [comment]
@Bharadwaj-vana can I close the issue?

**Comment by Bharadwaj-vana** [comment]
@svettsova  

Thanks for the support, Yes it worked with  RestAssured as well !

**Comment by evjlobanova** [comment]
Thank you, Valya!
