### ISSUE TITLE
Issue: How to log data using TestNG in Report Portal

### ISSUE THREAD

**Issue by SahabNathYadav** [reportportal/reportportal#1030]
Hi Team,

I am trying to use report portal for my project  based on TestNG framework and Extent Reports. I have added report portal listener and trying to log execution status (i.e Pass or Fail) along with Test case description,  but I am unable to see logs in report portal UI.

Please let me know, what I need to do to get the logs in Report Portal UI.

Thanks,

**Comment by evjlobanova** [comment]
As I have seen you didn`t configure the logger.
Please read our documentation.

We have a well-described ReadMe file with a description here: https://github.com/reportportal/agent-java-testNG

Also, you can try to find your case in the provided examples:
https://github.com/reportportal/examples-java/tree/master/example-testng-log4j
https://github.com/reportportal/examples-java/tree/master/example-testng-logback

One more option, we have a dev guide regarding reporting:
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#save-single-log-without-attachment


Actually, we would recommend redirecting such kind of issues to SLack chat https://reportportal-slack-auto.herokuapp.com/

There is a community of active users across the globe, which can help each other with configuration and adoption.
The development team itself focused on tool development and answering questions in the community once have spare time for it.

Having a lot of active clients and tens of requests a day, we share the highest priority with paid engagement first,
And then follow general priority and backlog for the rest of the requests.

In case if your organization is interested in cross-organization adoption we can support you here.
The development team can provide dedicated professional support, based on various options:
-	one time fixed price engagement with production-ready setup and on-boarding, training, custom integration with your test framework ;
-	recurring long-term support, which will guarantee the reserved time of our developer to your team to undress any related queries.

Please let me know if you are interested in  details.
