### ISSUE TITLE
Assigning category for failures takes 5 mins on docker started Report Portal

### ISSUE THREAD

**Issue by kaszarek** [reportportal/reportportal#1031]
**Setup:**
1. T2.large AWS EC2 instance deployed with Linux AMI
2. Report Portal deployed using docker using the instruction provided on https://reportportal.io/docs/Deploy-with-Docker%3Edeploy-reportportal-with-docker

**Steps to reproduce:**
1. Run test
2. Get some failures to analyze
3. open failure and assign "Production bug"

**Expected outcome:**
Processing of the call that happens in the backgound takes a reasonable time - I know it is ambigous.

**Actual outcome:**
It takes over 5 minutes for the call to complete and be reflected in the UI.

![image](https://user-images.githubusercontent.com/15947322/85589716-13890680-b644-11ea-8959-77529d34d000.png)

**Comment by evjlobanova** [comment]
@kaszarek Could you please firstly check this documentation, try to perform described steps, and give us feedback,if it helps
https://reportportal.io/docs/How-to-resolve

**Comment by nvborisenko** [comment]
T2 instances are CPU burstable. Basically you have some CPU credit, and earn it when your instance is idle. This might be a reason of performance degradation.

**Comment by kaszarek** [comment]
Hi @nvborisenko @evjlobanova , 

thanks for the answers with suggestions. I changed the machine to C5, the issue still persisted. 
After the investigation it turned out that some steps from installations were skipped during the setup.

Solution was :
`chown 1000:1000 data/elasticsearch/`

thanks for the promt responses.
