### ISSUE TITLE
Adding Attributes To Tests : User Should Have The Ability To Add Dynamic Values Using Variables (SLID Specific Issue)

### ISSUE THREAD

**Issue by sethijatin** [reportportal/reportportal#1035]
Based on the documentation, custom attributes to the scenario or test case can be added by using annotations as described on wiki page for [attributes](https://github.com/reportportal/client-java/wiki/Test-item-attributes).

**PROBLEM:**
Since, I cannot provide variables in attributes, it becomes impossible to parameterise the values for the predefined keys. For example: In case of SLID : <SESSION_ID>, SESSION_ID cannot be known before hand, and adding hundreds of session ids manually doesn't make sense.

**REQUEST:** 
Either provide a way to add test attributes via a method (function) or solve the problem for Sauce Labs integration in a different way.

**Comment by MaryiaRymarchyk** [comment]
Seems that there are no remain actions from ReportPortal side.
Therefore, ticket will be closed.
