### ISSUE TITLE
Data backend is not freely selectable

### ISSUE THREAD

**Issue by sysreport** [reportportal/reportportal#1037]
Hi

**Describe the solution you'd like**
We need a full automatic recreation of our reportportal host without lost of data from database and artifacts.
We have configured all of them without the data store like MinIO. 
We would like to use S3 instead of MinIO. We have tested to configure MinIO as a S3 Proxy, but we can not configure the specific Bucket.

I have read the Issue: https://github.com/reportportal/service-api/issues/1045
I think it is not the best solution to use each bucket for each project. If is posible to use one bucket with folders for each project?

**Is your feature request related to a problem? Please describe.**
Our Problem is, that we can not make our reportportal fully recreatable. If we do this, we lost all our artifacts from reportportal.
Our problem is not the backup. we make the backup seperatly. 

With kind regards
thoralf

**Comment by evjlobanova** [comment]
@Cyberglamdring @Yumfriez Could you please check this issue?

**Comment by Yumfriez** [comment]
@evjlobanova If I'm not wrong @AlehB implemented MinIO as S3 proxy. There was only one bucket (by default `rp-bucket` but this name can be customized through the env variable) with folders for each project inside

**Comment by Cyberglamdring** [comment]
Dear @sysreport,

Here are some steps to help you:
1. You can attach the disk to the MinIO service (Volume for Docker or PVC for Kubernetes) and set up backup snapshots in the Cloud or Local VM.
2. Also, you can deploy MinIO S3 proxy. By default, ReportPortal services create projects buckets in MinIO. We do not plan to change the structure in the near future.

**How to deploy MinIO S3 proxy**:
1. Add to MinIO values S3 getaway: [Link](https://docs.min.io/docs/minio-gateway-for-s3.html)
2. Add environment variables for `UAT` and `API` services:
```bash
RP_BINARYSTORE_MINIO_DEFAULTBUCKETNAME: <backet_name>
RP_INTEGRATION_SALT_PATH: <backet_name>
```
3. Before deploying ReportPortal to existing environment, you need to clean up the database tables:`attachments`, `integratin_type`, and `integration`:
```SQL
DELETE FROM attachment;
DELETE FROM integration_type WHERE group_type IN ('BTS', 'OTHER');
DELETE FROM integration WHERE type IN (SELECT id FROM integration_type where name IN ('email', 'jira', 'ldap', 'ad'))
```

**Comment by Cyberglamdring** [comment]
No response from user
