### ISSUE TITLE
demo data XML junit example

### ISSUE THREAD

**Issue by odubaj** [reportportal/reportportal#1038]
Hello,

I am trying to import results into RP, but I am facing problems with importing test steps to RP via xml. According to XML junit standard, there are only 3 levels of tests results: Suite > Test > Logs.

RP provides one level more, which is needed for our purposes: Suite > Test > Step > Log. For our reasons, the "Step" is very important. Can you please provide an example XML file, which contains also the "Step" ? Or is there please  another solution, how we can fullfil our goal ?

Thank you

**Comment by pramodbhalerao** [comment]
Hello @odubaj ,

After reading your issue, even I got curious to see how the import functionality works in RP as I found RP last week.

Somehow, I reached to this [post](https://stackoverflow.com/questions/4922867/what-is-the-junit-xml-format-specification-that-hudson-supports) and I tried the last answer's sample xml (converted into ZIP file), which I found good enough for me.

I hope this will help you in some way.

**Comment by odubaj** [comment]
thanks for your comment, I think you are pointing on the XML scheme> I also found this format, but I think there is something missing there (from my opinion, there should be en element "step" in "testcase" element). Simply, I want to make the same structure as is made by RP demo data, but I am unable to do that with the mentioned XML scheme standard. I might think, RP has its own implemented XML standard, or they are doing something what I do not understand yet.

**Comment by evjlobanova** [comment]
[Launch C2.zip](https://github.com/reportportal/reportportal/files/4846904/Launch.C2.zip)

**Comment by evjlobanova** [comment]
This is  an example of XML file

**Comment by odubaj** [comment]
Thank you!

**Comment by odubaj** [comment]
I just have an additional question regarding to attributes and code reference. I would like to add some attributes, code reference and parameters via importing my XML junit file. Is it possible ? Example what I need below in the screenshot. According to XML junit standard (https://llg.cubic.org/docs/junit/) it should be made via <properties> tag, but it does not work, am I missing something ? Do you have your own XML tags for such data ?
Thank you.
![Snímka obrazovky z 2020-07-02 09-49-37](https://user-images.githubusercontent.com/44674278/86331884-fe1a6a80-bc49-11ea-9bdb-78431378d6c6.png)

**Comment by evjlobanova** [comment]
@odubaj import feature is limited functionality. You can not add attributes and coderef via import. For now, we are not planning to support and expand import functionality, because our main priority is real-time reporting.

**Comment by odubaj** [comment]
Thanks for the info

**Comment by torarnv** [comment]
Can you point me to the repository and code that handles the import? I have a similar use-case and would like to improve on the JUnit importer.

**Comment by odubaj** [comment]
Hi, it is service-api repository, where in LaunchController you have ImportLaunchHandler. We can collaborate on this issue. My aim is to modify import, so it will automatically add attributes to launches, test-suites and test-cases. The attributes should be stored in Junit XML tag <properties>. Standard here: https://llg.cubic.org/docs/junit/

**Comment by MaryiaRymarchyk** [comment]
Hi @odubaj , seems that there are no remain actions from RP team' side.
Due to that - ticket will be closed.
Feel free to contact us in case of any questions.
