### ISSUE TITLE
Skipped tests are automatically labelled with "To Investigate"

### ISSUE THREAD

**Issue by naddison** [reportportal/reportportal#1043]
When a test has a status skipped, it is labelled with "To Investigate", even with auto-analysis turned off. Is it possible to turn off this behavior?

Or is is behavior different in v5.

**Comment by HardNorth** [comment]
@naddison Which agent do you use?

**Comment by naddison** [comment]
I am using java-client, making our own requests to the API.

**Comment by HardNorth** [comment]
Put this into properties:
`rp.skipped.issue=false`

**Comment by vlbolotin** [comment]
Could you please explain whether this could be done for Python client.
Also were this setting should be defined? in pytest.ini? or in configuration files of RP itself

**Comment by chgans** [comment]
I'm using python client, and i pass `is_skipped_an_issue=False` to `ReportPortalService`, yet all the skipped are marked as "To investigate". Am I doing something wrong?

**Comment by chgans** [comment]
hmm, just checked the source de: https://github.com/reportportal/client-Python/blob/master/reportportal_client/service.py#L409
and status has to be upper case! :(

**Comment by poliveira-fuze** [comment]
This is not working anymore. But from what I'm reading on other topic it seems the rules have changed. As is not supposed to work as before.
https://github.com/reportportal/reportportal/issues/1538

**Comment by evjlobanova** [comment]
@HardNorth Vadzim could you please check this issue? 
Flag skipped: false should remove To investigate label from skipped items
