### ISSUE TITLE
Security issue: possible to hack passwords

### ISSUE THREAD

**Issue by dimit999** [reportportal/reportportal#1045]
hash I took from 3_default_data.up.sql 

![image](https://user-images.githubusercontent.com/43273472/86363054-f3c69380-bc7e-11ea-9e8a-38591106746a.png)

the same for reportportal\README.md

**Comment by pbortnik** [comment]
In the oldest version we have changed hashing from md5 to bcrypt. 
What you see in the file is a hash of default users. It is open information.

**Comment by dimit999** [comment]
@pbortnik where u changed this?

what is it https://github.com/reportportal/migrations/blob/develop/migrations/3_default_data.up.sql ????

**Comment by dimit999** [comment]
> In the oldest version we have changed hashing from md5 to bcrypt.
> What you see in the file is a hash of default users. It is open information.

@pbortnik where u changed this?

what is it https://github.com/reportportal/migrations/blob/develop/migrations/3_default_data.up.sql ????

**Comment by dimit999** [comment]
how to re-open this issue? @pbortnik

**Comment by pbortnik** [comment]
The script that you mentioned is a script that creates default users while first deploy. In 5.2.2 version all your passwords encrypted with bcrypt. You can verify it in your database.

**Comment by dimit999** [comment]
thanks

**Comment by pbortnik** [comment]
Check this out
https://github.com/reportportal/migrations/blob/develop/migrations/11_password_encoding.up.sql
