### ISSUE TITLE
Excessive logs

### ISSUE THREAD

**Issue by Invictum** [reportportal/reportportal#1047]
Our RP instance is shared across whole organization and it produces a huge amount of logs in `/var/log/messages` on the host machine where docker service is running. The amount of produced logs in a one day sometimes consumes more space that actual stored results data.

Are there any way to reduce that logs verbosity or configure log levels?

**Comment by Yumfriez** [comment]
@Invictum You can disable http/rabbit messages logging using env variable for `API` container:

RP_REQUESTLOGGING=false

You can also set root logging level higher then `INFO`:

LOGGING_LEVEL_ROOT=error

**Comment by Invictum** [comment]
@Yumfriez 
Seems like it worked. Thank you!

**Comment by renan** [comment]
What about other components such as `reportportal/service-authorization` and `reportportal/service-ui`? I am using the Kubernetes helm and I am not able to find what are the options for lowering the verbosity on them. Especially `reportportal/service-authorization` with hundreds of `DEBUG` messages.
