### ISSUE TITLE
[feature request] Add a possibility to be able to see only logs with level equals or more than selected one

### ISSUE THREAD

**Issue by doctordrue** [reportportal/reportportal#105]
The thing is that in our project we have custom level of logs between INFO and WARN.
So e.g. if DEBUG level is selected I want to see all logs with level more than DEBUG (ERROR, WARNING, INFO and even custom levels of logs)

**Comment by DzmitryHumianiuk** [comment]
implement on UI `=>` condition for filters of log levels.

for instance,
If you Select `INFO`: this filter will show you `INFO + WARN + ERROR`
If you Select `DEBUG`: this filter will show you `DEBUG + INFO + WARN + ERROR`

this will cover any in-between levels of logs
