### ISSUE TITLE
Add UUID data to TestItem Controller when querying using filters

### ISSUE THREAD

**Issue by sspieker-cc** [reportportal/reportportal#1050]
**Describe the solution you'd like**
... Current implementations of the TestItemController GET method using query parameters do NOT return the TestItem's UUID value.

**Is your feature request related to a problem? Please describe.**
... This request is NOT related to a specific problem, however, the return type from the controller is a Page<TestItemResource> however, when querying using filters, the returned records do not contain the record's UUID value.  When performing the GET operation with the Item's ID, we are then supplied with the fully populated TestItemResource.

For the sake of consistency it would be ideal to have all queries return a fully populated TestItemResource record including the UUID.  Doing so would cut down on the number of queries performed to gather this key piece of information when attaching files to a testsuite or testcase level record.

Currently our workflow is utilizing RP 5.0.0 and we have to query the TestItem endpoint multiple times in order to gather the information that is necessary to move onto the next step in our workflow.

**Comment by evjlobanova** [comment]
@sspieker-cc thank you for sharing this. I suppose this a valid request,
@HardNorth what do you think?

**Comment by HardNorth** [comment]
@evjlobanova I think this is a good request

**Comment by evjlobanova** [comment]
We will add this to the release
