### ISSUE TITLE
No logs in report portal

### ISSUE THREAD

**Issue by Anastasia-Zinoveva** [reportportal/reportportal#1051]
Hi, i was trying to send logs by test run, but the page with results is empty. I can see my tests and status of it, but there is no my logs. That is the reason why i cannot attache the screenshot to logs
![image](https://user-images.githubusercontent.com/63168440/86997362-ea798180-c1be-11ea-9755-f4c90cafe899.png)

I already google an issue and found something similar with my: https://github.com/reportportal/reportportal/issues/137
but i can't use the solution - can't downgrade my pom testng version lowest than 4.3.0

Could you please advise? 

**There is my POM:**

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.epam.automation</groupId>
    <artifactId>hello-webdriver</artifactId>
    <version>1.0-SNAPSHOT</version>
    <repositories>
        <repository>
            <id>bintray</id>
            <url>http://dl.bintray.com/epam/reportportal</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.1.0</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>4.3.0</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.7</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.7</version>
        </dependency>

        
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.141.59</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-io</artifactId>
            <version>1.3.2</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.30</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.12.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>6.1.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>4.7.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-java-commons</artifactId>
            <version>2.13.3</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-to-slf4j</artifactId>
            <version>2.8.2</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.16</version>
                <configuration>

                    
                    <testFailureIgnore>true</testFailureIgnore>
                    <suiteXmlFiles>
                        <xmlFile>.\src\test\resources\tests.xml</xmlFile>
                    </suiteXmlFiles>
                    
                    <workingDirectory>./</workingDirectory>
                    <includes>
                        <include>.\src\test\resources\tests.xml</include>
                        <include>/src/test/resources/log4j.xml</include>
                        <include>/src/test/resources/reportportal.properties</include>
                    </includes>

                    <properties>
                        <property>
                            <name>usedefaultlisteners</name>
                            <value>false</value>
                        </property>
                        <property>
                            <name>listener</name>
                            <value>com.epam.reportportal.testng.ReportPortalTestNGListener</value>
                        </property>
                    </properties>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

**log4j.xml**

  <?xml version="1.0" encoding="UTF-8"?>
  <Configuration status="WARN">
      <appender name="ReportPortalAppender" class="com.epam.ta.reportportal.log4j.appender.ReportPortalAppender">
          <layout class="org.apache.log4j.PatternLayout">
              <param name="ConversionPattern" value="[%d{HH:mm:ss}] %-5p (%F:%L) - %m%n"/>
          </layout>
      </appender>
      <logger name="com.epam.reportportal.apache">
          <level value="OFF"/>
      </logger>
      <Loggers>
          <root>
              <level value="info" />
              <appender-ref ref="ReportPortalAppender" />
          </root>
     </Loggers>
  </Configuration>

![image](https://user-images.githubusercontent.com/63168440/86998140-ca4ac200-c1c0-11ea-8c46-0ca94ba360fb.png)

**testng suite**

<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Demo Suite" parallel="tests" thread-count="1">

    <listeners>
        <listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener"/>
    </listeners>

    <test name="ControlCtest">
        <classes>
            <class name="tests.iCanWinTest.ControlCtest"></class>
        </classes>
    </test>
    <test name="ColorCommandTest">
        <classes>
            <class name="tests.bringItOutTest.ColorCommandTests"></class>
        </classes>
    </test>
    <test name="ColorTextTests">
        <classes>
            <class name="tests.bringItOutTest.ColorTextTests"></class>
        </classes>
    </test>

**my Runner**

public class Runner {
    public static void main(String[] args) {

        TestNG testNG = new TestNG();

        XmlSuite suite = new XmlSuite();
        suite.setSuiteFiles(Arrays.asList("src/test/resources/tests.xml"));

        List<XmlSuite> suites = new ArrayList<>();
        suites.add(suite);

        testNG.setXmlSuites(suites);

        testNG.run();
    }
}

And i have an reportportal.properties file with filled needfull fields.

Appreciate your help very much!

**Comment by evjlobanova** [comment]
Please update your instance to the latest version and the latest version of agent.
We do not support 4th version now,
If issue is still valid, please reopen this issue

**Comment by Anastasia-Zinoveva** [comment]
> Please update your instance to the latest version and the latest version of agent.
> We do not support 4th version now,
> If issue is still valid, please reopen this issue

If I update up to 5ve version, I've faced with another one known issue:
![image](https://user-images.githubusercontent.com/63168440/87011796-6f719480-c1d9-11ea-91dd-f97e022b37ec.png)

This issue already mentioned in https://github.com/reportportal/reportportal/issues/684 and resolvied by downgraded to 4th version

**Comment by evjlobanova** [comment]
Do you use latest agents?

**Comment by Anastasia-Zinoveva** [comment]
looks like 5.0.4 is the latest version

![image](https://user-images.githubusercontent.com/63168440/87013832-4a325580-c1dc-11ea-890d-5858e8fd01d0.png)

**Comment by Anastasia-Zinoveva** [comment]
so, yes

**Comment by evjlobanova** [comment]
@HardNorth Vadzim can you please check this issue with TestNG

**Comment by HardNorth** [comment]
@Anastasia-Zinoveva So you have V4 server instance, correct?

**Comment by HardNorth** [comment]
Abandoned
