### ISSUE TITLE
Help in integrating reportportal with BDD Automation tool

### ISSUE THREAD

**Issue by python-auto-hc** [reportportal/reportportal#1052]
I was looking for something which can help me to reduce my Automation Result analysis time. While browsing, I came across Report Portal tool; which looks like a fit to my requirement. Have installed it on my local using docker. Tried my hands on Demo Data and the tool looks promising. 

I am using GWEN for Automating my tests (https://github.com/gwen-interpreter/gwen-web). It is an open source which is written in scala. GWEN generates report logs in html, json and junit format. I played around with report portal by uploading junit zip; But I wish to integrate GWEN with report portal so that I can view my log trace and screenshots directly into launches on Report Portal. Your Kind help will be very much appreciated.

@evjlobanova @DzmitryHumianiuk

**Comment by evjlobanova** [comment]
Hello @python-auto-hc  thank you for sharing this request.
We investigate this tool and discuss the priority for this implementation internally.

Also we will be glad if you decide to contribute and implement your own integration with this tf. We have prepared a dev guide that can be useful:
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md
and overall description of integrations https://reportportal.io/docs/Test-Framework-Integration


Also, we are providing paid support, in a scope of this support we can implement a custom integration for your organization.  If it is interesting for you we can make a call and discuss details.

**Comment by python-auto-hc** [comment]
Thanks @evjlobanova.  I will explore the pointers.

**Comment by python-auto-hc** [comment]
Just one point before we even think of custom integration; can you please check gwen and help me conclude that none of the existing integrations of Report Portal can be reused ? Like Cucumber, Scalatest, Serenity, etc.

**Comment by python-auto-hc** [comment]
gwen uses log4j for logging - can it be of help ? https://github.com/reportportal/logger-java-log4j

**Comment by python-auto-hc** [comment]
@evjlobanova  Apologies for pushing this; but did you get chance to go through the tool ?

**Comment by python-auto-hc** [comment]
Hi @evjlobanova @DzmitryHumianiuk  , 

I tried my hands on the python client (ReportPortalService); and was able to post process the json logs generated by gwen; succeeded in pushing them in the report portal tool. But I am not convinced whether I will be be missing on something if I don't integrate it real time with gwen. Would like to add to what I stated about Gwen earlier; it is an open source framework which is based on top of selenium which provides an easy way to implement more of business readable tests which can be conveniently done by a non technical user. Because of the mentioned features, gwen is quite popular among the users who want faster turn around; and I believe report portal also has the intent of making delivery lot more swifter by doing Auto Run Analysis. I feel that if we can make through this integration then it will be good for both the worlds.

Please give me your thoughts on the above. Awaiting your kind response.

Regards,
-Himanshu Chauhan

**Comment by python-auto-hc** [comment]
Hi Team,

In reference to integration of gwen with report portal -
https://github.com/reportportal/reportportal/issues/1052 .

If any of the existing integrations are not helping us then can we get on a
call and discuss the option of custom integration. Please schedule a call
(google meet) for the same so that we can progress on this.

Thanks,
Himanshu.

**Comment by bjuric** [comment]
FYI - Gwen report portal integration has just been released. See: https://github.com/gwen-interpreter/gwen/wiki/Report-Portal-Integration
