### ISSUE TITLE
How to Set the Name of our test result as per our Script Name 

### ISSUE THREAD

**Issue by dharma-keyutech** [reportportal/reportportal#1053]
<img width="1280" alt="Screenshot 2020-07-09 at 12 06 39 PM" src="https://user-images.githubusercontent.com/58975085/87005503-bad97200-c1dc-11ea-9c2c-530ef31f7fb0.png">

How to change the name  of the test Like : Test_Demo_SmokeTest_Launch Application

**Comment by evjlobanova** [comment]
During reporting your can specify any launch name you want in a property file.
But launch name can not be edited after
