### ISSUE TITLE
Cannot set defect type on test methods with Interrupted status

### ISSUE THREAD

**Issue by naddison** [reportportal/reportportal#1054]
Is it expected behaviour that I cannot add a defect type to a test method that has interrupted status?

![Capture](https://user-images.githubusercontent.com/3034767/87088533-c7b09280-c1e9-11ea-978f-6f59bc456d80.PNG)

**Comment by evjlobanova** [comment]
Hello @naddison 
Please update the version of ReportPortal to the latest one.
For interrupted items, you will be able to change status to Failed and set a defect type.

**Comment by naddison** [comment]
Is this fixed in the latest versions of v4 or v5?

**Comment by evjlobanova** [comment]
Version 4 is not supported anymore.

Started from version 5
