### ISSUE TITLE
xctest integration with report portal 5

### ISSUE THREAD

**Issue by sateeshg** [reportportal/reportportal#1055]
I'm getting lot of errors when using xctest integration with report portal 5.* version. Please let me know if xctest agent  (https://github.com/reportportal/agent-swift-XCTest) supports report portal 5 version?

"typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "content", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "id", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil))"

If It doesn't support, would I be able to install 4.3 version of report portal by modifying the version in the docker compose file (https://github.com/reportportal/reportportal/blob/master/docker-compose.yml)?

please share if there is any other link to install 4.3 version using docker

**Comment by MaryiaRymarchyk** [comment]
Hi @sateeshg, sorry for the silence.
Could you please update to the latest version of RP and try again? 
Info about deployment with Docker can be found in our Documentation - [here ](https://reportportal.io/docs/installation-steps/DeployWithDockerOnLinuxMac#deploy-reportportal-with-docker).
