### ISSUE TITLE
Automation Report Imported as launch is not read by Report portal

### ISSUE THREAD

**Issue by Naumansh** [reportportal/reportportal#1056]
**Describe the bug**

I have just started to use report portal. After installation and setting up the project, i have imported one automation report. The report is imported successfully, and it is shown in launches but no test information is fetched by report portal.
...

**Expected behavior**

The report portal should show all test information.
...

**Screenshots**
<img width="1792" alt="Report Portal1" src="https://user-images.githubusercontent.com/30106669/87116198-25bd9400-c243-11ea-92a1-639a0c914206.png">
<img width="1792" alt="Report Porta2" src="https://user-images.githubusercontent.com/30106669/87116210-2bb37500-c243-11ea-9376-9f88594c7fde.png">

**Versions:**
 - OS : mac , Browser: chrome
 - Version of RP : 4.3.0

**Comment by HardNorth** [comment]
@Naumansh RP 4.3.0 is out of support. Can you please try import it on a late 5th version?

**Comment by alena-babrova** [comment]
Hello @Naumansh,
Have you managed to upgrade to the latest ReportPortal version?
Is the issue still relevant?

**Comment by MaryiaRymarchyk** [comment]
Hi @Naumansh, 
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
