### ISSUE TITLE
Unable to Create Widgets in Dashboard based on Launches

### ISSUE THREAD

**Issue by Nagalakshmi17** [reportportal/reportportal#1057]
Displaying  no data in the widgets that created under Dashboard

please find the attached video Below for reference

[RP.mp4.zip](https://github.com/reportportal/reportportal/files/4908143/RP.mp4.zip)

**Comment by evjlobanova** [comment]
Hello
You created a filter that includes launches that contain "pass" in their name. As far as there is no such launches on your project the widget shows "No data available"
Please firstly create a filter based on needed criteria, and then create a widget

Documnetation is here https://reportportal.io/docs/Dashboards-and-Widgets

**Comment by Nagalakshmi17** [comment]
Thank you, I am able to create a widgets
