### ISSUE TITLE
Java out of memory error when uploading log to the report portal[v5]

### ISSUE THREAD

**Issue by madhukeshava** [reportportal/reportportal#1059]
**Describe the bug**

**To Reproduce**
Exception when trying to save screenshot to reportportal: 5000: Unclassified error [Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space]
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by evjlobanova** [comment]
@madhukeshava which version of ReportPortal do you use?
Which agent name and agent version do you use?
Steps for reprodiuction

**Comment by harshagv12** [comment]
Agent agent: pytest Agent
Version: pytest_reportportal-5.0.3.dist-info

Steps:
1. Read the file with size more then 80 MB. Below code,
  with open(file_name, "r") as fh:
         file = fh.read()
         rp_logger.info(file)
2. Logs the data to report portal
3. Java out of memory error is seen

**Comment by Yumfriez** [comment]
@evjlobanova We have to investigate and fix this issue

**Comment by evjlobanova** [comment]
Added task to Jira

**Comment by MaryiaRymarchyk** [comment]
Hi @madhukeshava , @harshagv12  the bug was fixed in Sep-21.
I'll close the ticket, however if you still have any questions or help is required - feel free to reopen.
