### ISSUE TITLE
[v5] UI Filter Editing - When Creating a Filter manually the sharing cannot be toggled after being created

### ISSUE THREAD

**Issue by sspieker-cc** [reportportal/reportportal#1068]
**Describe the bug**
After creating a filter its sharing state cannot be modified through the edit UI elements (either the edit of the filter name or through editing through assigning as a part of creating a widget.

**To Reproduce**
Create a filter, then attempt to edit the filter in each mode (Filters view or through assigning through a widget).  Attempt to change the sharing option on the Filter through the UI.

**Expected behavior**
Either a slider option in the FIlters view (similar to the "Display on Launches" column, or an edit option that would allow for that option to be toggled.

**Screenshots**
N/A

**Additional context**
Currently the filter has to be removed and re-created with the toggling being set appropriately.

**Comment by evjlobanova** [comment]
@sspieker-cc Which version of ReportPortal do you use?

**Comment by VolhaKarenko** [comment]
Can not reproduce the issue on version 5.0. 
@sspieker-cc Could you please provide a screenshot specifying the broken toggle

**Comment by sspieker-cc** [comment]
We are currently running two versions - 5.0.0 and 5.2.2 (locally using docker compose).  Local testing confirms that there are no regressions in processes that we have in place.

**Comment by sspieker-cc** [comment]
Closing this issue as it has not been reproduced after restart.
