### ISSUE TITLE
[v5]  I cannot start reportportal (analyzerApp cannot start)

### ISSUE THREAD

**Issue by cesar-montoya** [reportportal/reportportal#1069]
**Describe the bug**
I cannot start reportportal

**To Reproduce**
After I enter **docker-compose -p reportportal up** this keeps showing up and I am unable to launch reportportal:

_analyzer_1       | 2020-07-20 14:54:52,503 - analyzerApp - INFO - Starting waiting for AMQP connection
analyzer_1       | 2020-07-20 14:54:52,504 - analyzerApp - INFO - Try connect to /analyzer?heartbeat=600
analyzer_1       | 2020-07-20 14:54:52,507 - analyzerApp - ERROR - Amqp connection was not established_

**Desktop (please complete the following information):**
 - MacOS

**Comment by MariyaIvanina** [comment]
Hi, @cesar-montoya ! Please, add AMQP_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672 under environment section of analyzer module in the docker-compose.yml. As far as now the default value of the path to rabbitmq was not set.

**Comment by evjlobanova** [comment]
@cesar-montoya  please let`s know if it helps you

**Comment by cesar-montoya** [comment]
Thank you this worked!!
