### ISSUE TITLE
Not able to login to portal

### ISSUE THREAD

**Issue by saikrishna321** [reportportal/reportportal#107]
After building the project from docker and hitting 
http://localhost:8080/ui/

Username and Password: default\1q2w3e and superadmin\erebus

Didn't help .. It always says i no permissions. Can someone please help on this?

**Comment by SrinivasanTarget** [comment]
+1 Same here too

**Comment by DzmitryHumianiuk** [comment]
@saikrishna321 @SrinivasanTarget 
please allocate at least **4GB of RAM** for docker
and give ReportPortal **5-10 mins** to initialize all services.

re-open if still actual

**Comment by avarabyeu** [comment]
If there is 4 gb of ram, 1-2 mins should be enough to bootstrap application
