### ISSUE TITLE
[v5] Be able to use an elasticsearch that requires basic auth

### ISSUE THREAD

**Issue by naddison** [reportportal/reportportal#1070]
**Describe the solution you'd like**
I currently see that it is possible to set the value of the environment variable ES_HOSTS to point https://github.com/reportportal/kubernetes/blob/master/reportportal/v5/values.yaml#L147.

The ES cluster that is already available to me requires Basic Authentication. Can username and password environment variables be added, that are read and used to perform basic auth connecting to the given hostname.

**Comment by Yumfriez** [comment]
@evjlobanova We can create a JIRA ticket with this improvement

**Comment by MariyaIvanina** [comment]
Yes, this improvement can be done. We can add username and password environment variables and use authentication based on them.

**Comment by evjlobanova** [comment]
@MariyaIvanina Could  you please add this task to you backlog?

**Comment by MariyaIvanina** [comment]
@naddison I've just checked, that we already have a possibility to authenticate with user and password into Elasticsearch. You need to set in the ES_HOSTS http://{ your elastic username}:{your elastic password}@{elastic endpoint}:9200 . Please, write here, whether you have managed to login via this approach.

**Comment by e-jjj** [comment]
@MariyaIvanina Currently using basic authentication in reportportal analyzer to authenticate to Elastisearch with the ES_HOST variable. It is working as expected however I'm wondering if there is a way to set the authentication using an IAM role that is associated to the container running reportportal analyzer. I've searched some information about it but I havent been able to find anything yet.

Thanks!
