### ISSUE TITLE
Data Retention Policy

### ISSUE THREAD

**Issue by pravinupganlawar** [reportportal/reportportal#1073]
Do we have any Data Retention Policy for ReportPortal ?
How to setup the Data Retention Policy for ReportPortal ?

RP Version : 4.3.0

**Comment by evjlobanova** [comment]
We do not support version 4.3, because the latest version is 5.2.3 

You can configure data retention policy via Project Setting> General

![image](https://user-images.githubusercontent.com/30413511/88151150-fd527400-cc0a-11ea-8290-28487b67b3c5.png)

**Comment by pravinupganlawar** [comment]
Thanks
