### ISSUE TITLE
Adding a link as attachment

### ISSUE THREAD

**Issue by orgads** [reportportal/reportportal#1075]
Hi,

We're trying to add a link to an external URL for each test. I found #499 which was solved by using markdown.

We have 2 problems with this:
1. the logs are long, and I have to scroll down through all the logs to find the link.
2. The link itself is very long (over 1000 characters, and after ~500 chars the link is terminated, and the rest is displayed as plain text. I tried different link representations in markdown, and none of them worked.

We also tried to add the URL as attachment by passing this to the logger:
```
attachment={
  "name": "Link title",
  "data": f'<a href={my_link}>Link title</a>',
  "mime": "text/html"
}
```

This way works, but it creates an HTML attachment, which requires first clicking the 
![image](https://user-images.githubusercontent.com/1246544/88083669-07815d80-cb8c-11ea-9109-503ddb079635.png) icon twice, then clicking the same icon that appears above the previous one, and this opens a new tab with the desired link. That's way too much for a simple link :)

Can you suggest another way to attach a link with easy access?

Thanks.

CC: @bivas6

**Comment by orgads** [comment]
Hi,

Any progress?

**Comment by AmsterGet** [comment]
Hi @orgads !
We've reduced the number of clicks on attachments by adding appropriate buttons to download and open in a new tab (see screenshot below). This feature will be released in version 5.4.
![image](https://user-images.githubusercontent.com/31861805/99637593-21f21780-2a56-11eb-8561-dc5f93795436.png)
If you still want to use large links in logs or item descriptions, try shortening them using any URL shortener.
Hope this helps!

**Comment by orgads** [comment]
Thanks! Do you have a planned release date?

**Comment by evjlobanova** [comment]
±January
