### ISSUE TITLE
[v5] io.reactivex.exceptions.UndeliverableException exception in gradle run output

### ISSUE THREAD

**Issue by automationhacks** [reportportal/reportportal#1076]
**Describe the bug**
While running tests with report portal 5, below exception are printed

```
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with.
```

**To Reproduce**
- Clone the repo and check out to [this](https://github.com/automationhacks/grasp-reporting/commit/8fbeebab7a27b4660450b7a9f7bbef2460a0c6d2) commit

**Expected behavior**
There should be no such exception

**Screenshots**
Screenshot of the exception.

> Note: The report portal displays the failed test cases properly. So this issue is only transparent if someone is looking at the runtime logs (Could discourage folks from trying V5)

<img width="2013" alt="report_portal_looks_fine" src="https://user-images.githubusercontent.com/26017734/88128435-95446380-cbf3-11ea-8fe5-f8b3e2e3065d.png">

<img width="1729" alt="exception" src="https://user-images.githubusercontent.com/26017734/88128440-98d7ea80-cbf3-11ea-82d5-3fcca5e440d1.png">

**Desktop (please complete the following information):**
 - OS: [Mac OS Catalina]
 - Browser [Chrome]
 - Version [Version 84.0.4147.89 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**
N/A

**Additional context**

Below are the versions of components being used (from UI)

```
Current version:
API Service: 5.2.3;
Index Service: 5.0.9;
Authorization Service: 5.2.3;
Service UI: 5.2.3;
```

build.gradle

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    compile group: 'com.epam.reportportal', name: 'agent-java-testng', version: '5.0.4'
    testCompile group: 'org.testng', name: 'testng', version: '7.1.0'
}
```

**Comment by HardNorth** [comment]
Your gradle task failed due to assertion error, the latter error message is related to a minor bug, which should not affect execution results. BTW it is already fixed in 5.0.6:
https://github.com/reportportal/agent-java-testNG/releases/tag/5.0.6
https://bintray.com/epam/reportportal/agent-java-testng/5.0.6

**Comment by automationhacks** [comment]
Thank you @HardNorth , Upgrading to 5.0.6 solves the issue. This was really much needed.

**Comment by priyankachaturvedi30** [comment]
@HardNorth  : I faced a similar exception for RP version 5.3.5 . Using java-client integration (https://github.com/reportportal/client-java) for running my bdd driven automation. Can we please get this checked. @evjlobanova

**Comment by HardNorth** [comment]
@priyankachaturvedi30, `client-java` has 59 releases, which one you use? Moreover just `client-java` library is not sufficient itself to report to Report Portal.

And I have to give you a warning, this is not the first and not the second time you are asking vague questions, you waste people time make them asking additional questions. If you keep doing this I'll have to apply administrative actions. Please be more specific in your questions.

**Comment by priyankachaturvedi30** [comment]
@HardNorth : Below are the dependencies I am using -
https://search.maven.org/artifact/com.epam.reportportal/client-java/5.0.21/jar.  
https://search.maven.org/artifact/com.epam.reportportal/commons-model/5.3.3/jar
Apologies, I am still on a learning curve with respect to Report Portal and Java. So, please pardon me.
