### ISSUE TITLE
Java heap space out of memory "5000: Unclassified error [Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space]"

### ISSUE THREAD

**Issue by harshagv12** [reportportal/reportportal#1080]
When we uploading the logs to report portal when more 75 MB, we are seeing the java heap space memory error. Below is the complete error,

**5000: Unclassified error [Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space]
Exception when trying to save logs to reportportal: 5000: Unclassified error [Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space]**

**Comment by evjlobanova** [comment]
It seems that there is no space left on your device. You can try to increase the disk space of your machine and/or provide more disk space resources to the Docker on your machine.

cc: @irynakozak2

**Comment by harshagv12** [comment]
fvt@bulfct04:~$ sudo docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              16                  13                  7.305GB             2.482GB (33%)
Containers          26                  10                  6.096GB             5.721GB (93%)
Local Volumes       10                  9                   9.726GB             1.497GB (15%)
Build Cache         0                   0                   0B                  0B
 
There is sufficient space, expect the containers. Can you helps us how to increase the containers size

**Comment by evjlobanova** [comment]
Which version of rp do you usr?

**Comment by harshagv12** [comment]
I am able to solve this issue by increasing the java heap memory in docker.yml file
