### ISSUE TITLE
[v5] cannot add users to a specific project

### ISSUE THREAD

**Issue by mihtac** [reportportal/reportportal#1082]
We have multiple projects on our report portal instance (5.2.1, but tried upgrading to 5.2.2 and this still occurs post-upgrade). I can create new users, can add them to projects, except one. I tried both creating a user directly to that project, or create to another one and invite to that project - both fail.

**To Reproduce**
One particular thing that makes that project different to the rest, is that it has many users attached (27)

**Expected behavior**
I Should be able to add users to any project that we have
**Screenshots**
![image](https://user-images.githubusercontent.com/65647517/88516495-07eb7f80-cff6-11ea-8cab-174f1704d08f.png)

![image](https://user-images.githubusercontent.com/65647517/88516532-16399b80-cff6-11ea-88a6-5be05e634aa9.png)

**Desktop (please complete the following information):**
 - Windows 10
 - BrowserEdge and Chrome
 - Version 5.2.1 / 5.2.2

**Additional context**
please let us know what logs to provide, as we had a look and couldn't find anything suspicious

**Comment by ostratila** [comment]
Hello! Are there any updates on the above issue?

**Comment by Yumfriez** [comment]
@mihtac @osherdp 
`SELECT *
FROM acl_object_identity
         JOIN acl_class ac on ac.id = acl_object_identity.object_id_class
WHERE ac.class = 'com.epam.ta.reportportal.entity.ShareableEntity';`

Could you please attach the result of the above query, so we can see how many entities were corrupted and then fix them in the DB

**Comment by PirvuDanielCatalin** [comment]
![image](https://user-images.githubusercontent.com/37099336/95735659-c762e000-0c8d-11eb-93e4-b0ffe4ad5308.png)
