### ISSUE TITLE
[v5.2.1] auto analysis does not automatically start, but works manually

### ISSUE THREAD

**Issue by mihtac** [reportportal/reportportal#1083]
**Describe the bug**
We have a few test runs (not all!) where auto analysis does not seem to work automatically. Don't think it's a matching issue, as if I go and manually trigger AA on a test run of that series (same launch name), it does match failures with previous runs.

**To Reproduce**

**Expected behavior**
I'm expecting AA to automatically label failures if set to do so, when there are tests to be matched. Don't think it's a matching issue, as when triggered manually, it does find matches.
**Screenshots**
n/a
**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
I do realize this is not a lot of info, but please let me know what to add (logs, if needed)

**Comment by evjlobanova** [comment]
![image](https://user-images.githubusercontent.com/30413511/88549463-fd96a900-d028-11ea-9313-fe7a856a3fe1.png)

Switch auto analysis on in Settings

**Comment by mihtac** [comment]
it is currently like so:
![image](https://user-images.githubusercontent.com/65647517/88550380-34b98a00-d02a-11ea-8f6c-d1315813b63d.png)
does work on some of the launches we're having, but on others it consistently doesn't work (automatically, as it does match manually)

**Comment by evjlobanova** [comment]
![image](https://user-images.githubusercontent.com/30413511/88552024-3c7a2e00-d02c-11ea-8fc5-3c9d86fc5cdd.png)
In accordance with settings, it is analyzing only launches with the same name

I need more details)

**Comment by mihtac** [comment]
they do have the same name:
![image](https://user-images.githubusercontent.com/65647517/88552903-4e100580-d02d-11ea-9c67-07d019ca9093.png)

**Comment by mihtac** [comment]
when I say manually triggered analysis, I mean this option: 
![image](https://user-images.githubusercontent.com/65647517/88552963-6122d580-d02d-11ea-9ac1-fd6d99245130.png)

**Comment by evjlobanova** [comment]
![image](https://user-images.githubusercontent.com/30413511/88553561-16558d80-d02e-11ea-9a70-4315a6a93d49.png)
Why all your launches have been interrupted?
The problem is that your launches have not been finished inappropriately. So that AA hasn`t been triggered

**Comment by mihtac** [comment]
Good spot, I do not know - is it because the time is in red? 

We'll investigate! - any hint for where to start looking? any specific log entry?

**Comment by mihtac** [comment]
undefined step :( thanks for the help!

**Comment by evjlobanova** [comment]
It is difficult to say why without any contex)
Which agent do you use?
