### ISSUE TITLE
Solution for Report Portal – integration with Ready API

### ISSUE THREAD

**Issue by bzsharm** [reportportal/reportportal#1084]
**Solution for Report Portal – integration with Ready API**

I have found a solution for report portal integration with ready api, it perfectly works with Ready Api ( v 3.0) as well as Soap Ui (5.0.4) , It was tested on latest report portal release 5.2 & it’s working perfectly fine.
Please find below the steps followed:
Step 1: Download & Extract the attached ZIP File,

It will have a jar file and XML listener file,
( soapui-4.0.0-SNAPSHOT-all.jar
bin/listeners/reportportal-listeners.xml
)

Step 2: Copy and paste the jar file to “${ReadyAPI_HOME}/bin/ext folder

Step 3: copy the “reportportal-listeners.xml” and paste it in “${ReadyAPI_HOME}/bin/listeners folder

Step 4: Restart the Ready API.

Step 5: Open the URL of Report Portal and click on the Avatar on top right corner of the screen and click on Profile, Now click on “SOAPUI” (same applicable for Ready API Too) “CONFIGURATION EXAMPLES”, we need to add these details in to the Project Global Properties, PFB the screenshot with an example
 
![rp](https://user-images.githubusercontent.com/64862297/88574048-4e28f900-d05f-11ea-8c71-430f0b0f4b12.png)

**Could you please publish this listener and - jar file in to the main website (reportportal.io)?** 

Attached the listener file and Jar file for testing.
[Listerner&JarFile.zip](https://github.com/reportportal/reportportal/files/4983608/Listerner.JarFile.zip)

Same solution can be applied for SOAP UI integration too , only thing is that instead of Ready API home , Soap UI homepath is location where ,file needs to be copied.

**Comment by Yumfriez** [comment]
We have similar guide for the SoapUI integration. So we will add `installation guide` part for ReadyAPI to our repository

**Comment by evjlobanova** [comment]
@bzsharm Thank you for your contribution!
