### ISSUE TITLE
[v5] Retried test is shown as a separate test. They don't merge in single one when the tests are triggered via dataproviders

### ISSUE THREAD

**Issue by srinidhis05** [reportportal/reportportal#1085]
**Describe the bug**
The retried tests are shown as separate tests when triggered via a data provider and retried . The same doesnt seem to happen for regular test cases run 
**To Reproduce**
```
public class test {
    @DataProvider()
    public static Iterator<Object[]> getData() {
        List<Object[]> inputData = new ArrayList<>();
        inputData.add(new Object[]{Utilities.getRandomString(5)});
        inputData.add(new Object[]{Utilities.getRandomString(5)});
        return inputData.iterator();
    }

    @Test(dataProvider = "getData")
    public void test2(String data){
        System.out.println(data);
        Assert.assertTrue(false);
    }

    @Test()
    public void test1(){
        Assert.assertTrue(false);
    }
}

```
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Test Suite" parallel="classes" thread-count="3" verbose="1"  >
    <test name="Test One">
        <classes> <class name="com.test.test"/> </classes>
    </test>
    <listeners>
        <listener class-name="com.retryUtility.RetryListener"/>
    <listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener"/>
    </listeners>
</suite>

```

A standard retry analyzer is being used here 

**Expected behavior**
The test results needs to be merged with retry numbers in the dashboard

**Screenshots**

![image](https://user-images.githubusercontent.com/6957843/88578899-df4f9e00-d066-11ea-9141-b8f11b14723b.png)

**Desktop (please complete the following information):**
Report portal version : 5.0.2 
Testng client : 5.0.6
**Additional context**
https://github.com/reportportal/migrations/pull/129 , the fix doesnt seem to be working here .

**Comment by HardNorth** [comment]
@srinidhis05 Please update your RP Server version to 5.2.3.
