### ISSUE TITLE
compiling reportportal/commons-model into docker API image

### ISSUE THREAD

**Issue by odubaj** [reportportal/reportportal#1088]
Hi,
I am having problem to build a local docker API image containing local changes of reportportal/commons-model together with reportportal/service-api. When I run "./gradlew buildDocker -x test", it creates a image, but olny with local changes of reportportal/service-api and ignores changes of reportportal/commons-model.
How can I reflect changes from both local repositories ?

Thanks.

**Comment by odubaj** [comment]
genle ping

**Comment by evjlobanova** [comment]
Dev team will look at this issue, as soon as they have free time)

**Comment by odubaj** [comment]
Thank you very much

**Comment by odubaj** [comment]
Hello, any updates ?

**Comment by odubaj** [comment]
Hello, gentle ping, any updates ?

**Comment by Yumfriez** [comment]
@odubaj We don't create docker image from components such as dao/model etc. These are just dependency libraries so this is not possible.

If you want to make some changes in the `model` and apply them to the `api` - modify your `model` repo, include it as a dependency in your `api` project and build a docker image from `api`. This will work

**Comment by odubaj** [comment]
Hi, thanks for the update, I've already resolved the issue the way, as you described
