### ISSUE TITLE
[REST API] GET /{projectName}/item/{testItemId} Find test item by ID

### ISSUE THREAD

**Issue by lifemanship** [reportportal/reportportal#109]
The request "Find test item by ID" has two parameters:
1) projectName
2) testItemId

Which request is used to obtain {testItemId}?
My use case is to find all failed tests in the specified launch with using REST API.
The list of all launches i can obtain with using next request:
**GET /{projectName}/launch Get list of project launches by filter**

**Comment by pictureb00k** [comment]
There will be provided a method probably in 3.0.2 that will allow you to find test items by specified filter.
