### ISSUE TITLE
[v5] Report portal not able to filter the attribute value based on attribute key

### ISSUE THREAD

**Issue by harshagv12** [reportportal/reportportal#1094]
**Describe the bug**
We are able to generate attribute key & value and push the data to report portal.  But filtering the value based on attribute key, results are not listing. 

**To Reproduce**
Using latest python agent-python-pytest 5.0.4 and client-Python 5.0.3 with below data structure,
```python
config._inicache["rp_launch_attributes"] = ['SuiteName: {0}'.format(string),
                                              'Build: {0}'.format(config.getoption("string")),
                                              'SETUPID: {0}'.format(config.getoption("string")),                                         
                                              'Platform: {0}'.format(OS),                                             
                                              ]
```
Push the data to report portal 5.2.3 you should see the launch.  Using filter option attribute key with build and attribute value with build version. it is not listing the launch.

**Expected behavior**
Report portal should list the launch based on filter with attribute value based on attribute key

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.0.4
 - Browser: Chrome
 - Version: 84

**Additional context**
Launch is not listing with attribute value based on attribute

**Comment by DzmitryHumianiuk** [comment]
@harshagv12 based on screen above, you did send attribute values only.
We keep backward compatibility with RP v4, which was accepting tags only.
So if you send your attribute as plain string `Build: xxxx` it will be stored as **Attribute Value.**
Which is equal to Empty Key : Value.

So please send them as key:value object

```json
{
  "attributes": [
    {
      "key": "string",
      "value": "string"
    }
  ],
}
```

**Comment by harshagv12** [comment]
Below is the format i am planning to send the object to report portal
{
  "attributes": [
	{
	  "key": "SuiteName",
	  "value": "{0}".format(testsuite)
	},
	{
	  "key": "Build",
	  "value": "{0}".format(1.0)
	},
	{
	  "key": "Platform",
	  "value": "{0}".format(OS)
	}
  ],
}

"attributes" which value i need to pass this attribute. Please conform on this data structure.

Also can you provide which report portal Version(current we are using 5.0.3) and pytest_reportportal, reportportal_client version to be used. So that this information helps to work on key and value attributes filter.

**Comment by evjlobanova** [comment]
@iivanou Ivan, I suppose we have already have a feature request for pytest to add a possibility to report attribute with key: value structure, am I right?

**Comment by iivanou** [comment]
@evjlobanova You are right. Moreover, this feature has already been implemented and will be available in the next 5.0.5 release.

**Comment by harshagv12** [comment]
i am able to filter the data based on key now with below structure,
 [
{
"key": "SuiteName",
"value": "{0}".format(testsuite)
},
{
"key": "Build",
"value": "{0}".format(1.0)
},
{
"key": "Platform",
"value": "{0}".format(OS)
}
]

But i am able to filter the data for one build from report portal UI.  
If i want to filter the data Ex: suitename across build, I cannot "CHOOSE FILTER FROM THE LIST BELOW" in add new widget view

**Comment by evjlobanova** [comment]
@harshagv12 Please provide steps on how we can reproduce it

**Comment by rplevka** [comment]
@evjlobanova
The issue here is, that we are able to filter the launches based on attribute keys separately, then based on attribute values separately,
but we're unable to combine the filter in a way to get the Launches with a specific value of a *specific* attribute.
e.g.
let's assume, we have launch tagged with the following attributes:

```
[
  {
    "key": "version",
     "value": "1"
  },
  {
    "key": "number_of_threads",
    "value": "1"
  }
]
```

- now, i want to filter all launches with a `version: 1` and `number_of_appliances: 1`. (which should return 0 results)
- When using filter: `attribute key eq version && attribute value eq 1`, it returns the above launch, as it matches the attribute value of the other attribute, not the one i'm interested in.

**Comment by DzmitryHumianiuk** [comment]
@rplevka right. current filtering implementation assumes condition combinations via `AND` operator.

we plan filtering mechanism improvements for version 6.
it's in design stage right now.

**Comment by rplevka** [comment]
@DzmitryHumianiuk i think we still don't understand each other.
i don't have problem with the `AND` operator. I just need ability to be able to filter launches/tests based on **a value of a specific attribute**.
It seems not to be possible and attribute keys and attribute values just act like yet another 1-word tags.

**Comment by DzmitryHumianiuk** [comment]
@VolhaKarenko could you please double check?

**Comment by VolhaKarenko** [comment]
The issue is reproducible. Some UI changes are needed in attribute filtering, task is added to backlog

**Comment by evjlobanova** [comment]
In the version 5.6 we have added a possibility to filter launches/suites/ steps based on the key/value combination:
![image](https://user-images.githubusercontent.com/30413511/142056278-1647ad58-eb07-43a5-89dc-62441dab6541.png)
![image](https://user-images.githubusercontent.com/30413511/142056501-648c2bcf-2f72-46e0-abc6-4b2f0058b067.png)
