### ISSUE TITLE
Filtering logs with attachments

### ISSUE THREAD

**Issue by admizh** [reportportal/reportportal#11]
In my case i have two messages:
1. INFO log with attachment
2. Assertion error
Also filters not selected

![2016-11-25_0-49-27](https://cloud.githubusercontent.com/assets/6014483/20609814/aa6fa6c2-b2aa-11e6-8851-b4f7e3082fa9.png)

When select filters  ERROR + ATTACHMENT - i see  "No results found"message. But it is not correct. 
1. INFO log with attachment - should be displayed
2. Assertion error - should be displayed

![2016-11-25_0-53-01](https://cloud.githubusercontent.com/assets/6014483/20609864/853917f2-b2ab-11e6-8b4f-a501e56b909f.png)

**Comment by DzmitryHumianiuk** [comment]
Here is usability issue.

Log level [Trace, Debug, Info, Warn, Error] - is separate filer
`Attachment` - is a separate filer also.

so then you requesting `Attachment`+`Log level` in request you will have like 
`filter.in.level=ERROR & filter.ex.binary_content=true`

It uses `AND` logic.

**Comment by avarabyeu** [comment]
@DzmitryHumianiuk resolution?

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu closed
@admizh if you interested in enchantment - please propose it as idea.
