### ISSUE TITLE
Applied filters are cleared when you navigate back to the previous level in a suite tree

### ISSUE THREAD

**Issue by aliaksandrbasau** [reportportal/reportportal#110]
Steps to reproduce:
1. Open a launch.
2. Filter the suites by some criteria.
3. Click any suite.
4. Go back to the precious level with applied filter by clicking breadcrumb link. => You are navigated back to that level but the filter are cleared.

It's a regression from the previous version.

**Comment by DzmitryHumianiuk** [comment]
We intentionally removed this.

this can be handled by handled by Browser History Back button

We will raise it for the voting.

**Comment by DzmitryHumianiuk** [comment]
**done**
Verified in Chrome, FF, EDGE.
