### ISSUE TITLE
[v5] Failed Cases Trend Chart includes skipped tests

### ISSUE THREAD

**Issue by CalebFW** [reportportal/reportportal#1105]
**Describe the bug**
The Failed Cases Trend Chart includes Skipped tests in its graph, but if you click on it, the filter only shows Failed or Interrupted.

**To Reproduce**
1. Import a JUnit XML file into your project as a launch that includes Skipped tests.
2. Create a filter that includes the imported launch.
3. Create a Dashboard for this project.
4. Add a Failed Cases Trend Chart widget using the filter.

**Expected behavior**
The Failed Cases Trend Chart should ONLY display the count of Failed or Interrupted tests, just like its filter.

**Actual behavior**
The Failed Cases Trend Chart includes Skipped tests in its graph.

**Screenshots**
Failed Cases Trend Chart (1 Failed test, but 107 Skipped tests):
![image](https://user-images.githubusercontent.com/45899086/89656141-288ac380-d899-11ea-94e9-b037bf7bf3bc.png)

Clicked on the graph where the launch shows 108 failures, but actually only has 1:
![image](https://user-images.githubusercontent.com/45899086/89656373-7e5f6b80-d899-11ea-9d1b-9347dfabed5c.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v84

**Additional context**
ReportPortal v5.3.0

**Comment by evjlobanova** [comment]
@VolhaKarenko Could you please check if we have the same bug in the backlog?

**Comment by svettsova** [comment]
@evjlobanova the ticket exists in our backlog

**Comment by VolhaKarenko** [comment]
Fixed in version 5.6
