### ISSUE TITLE
Add more filter options: regex, startsWith, endsWith

### ISSUE THREAD

**Issue by CalebFW** [reportportal/reportportal#1106]
Add more filter options: regex, startsWith, endsWith

We are trying to filter our reports based off of the branch that the tests were run in. However, some branches contain the names of our protected branches, so they still are pulled into the filters. Our launches are named as ${branch}-${testSuite}-${pipelineID}, which allows us to trace failures through our pipelines. A simple RegEx or startsWith option in the filters instead of only "contains", "not contains", "equals", "not equals" would make this work a lot better for us.

For example:
Filter: master-UnitTests-
Launches found by filter:
master-UnitTests-12345
QA-1234-for-master-UnitTests-13546
develop-into-master-UnitTests-12574

**Comment by evjlobanova** [comment]
@CalebFW  It is a very complicated way for filter options.
I would recommend you to add attributes and create a filter based on attributes, not launch names

**Comment by CalebFW** [comment]
The Api doesn't allow me to import attributes, only a zip file with the xml results and the project name. I use the name of the Zip file to define the launch name based off of this criteria. Having RegEx as a filter option seems like a pretty standard thing for filters or even being able to have multiple contains or not contains against the same field, so selecting Launch Name twice in the filters.

**Comment by evjlobanova** [comment]
@CalebFW for now import is a feature with the low priority. 
Our main functionality is real-time reporting which allows you to add attributes automatically and creates widgets on base of attributes.

But you can add attributes manually to launch and it resolved your problem

**Comment by CalebFW** [comment]
Having manual steps is not an acceptable approach.

**Comment by evjlobanova** [comment]
@CalebFW in the nearest plans we do not have intentions to re-work import feature.  

In the version 6th (next year +) we are planning to improve filters with RPQL (details here #726)
So that you can follow the progress on this request in the mentioned ticket.

As a quick patch in your case - use real-time reporting. 
Is it possible for you to use it?

Also, we can provide paid support in the scope of what we can implement any feature (improvement) you need.

**Comment by CalebFW** [comment]
#726 would be a good approach for us. We cannot use real-time reporting, because this is a massive legacy project and we are trying to get insight into test runs without investing a lot of time adding the integration into our thousands of tests. The Api allows us to easily import reports through our existing CICD platform and pipelines. Our newer repositories will probably use real-time reporting.

**Comment by evjlobanova** [comment]
Closed in order to #726
