### ISSUE TITLE
Twistlock scan Issues

### ISSUE THREAD

**Issue by BibinQA** [reportportal/reportportal#1107]
As part of adopting this tool we ran twistlock scan against docker images of various service compromising Report portal. Below is the break up of vulnerabilities I saw. My question is are you aware of such vulnerabilities and if so do you have plans to get them fixed? I am just trying to find some answers.

Docker   Image - V5.2.3 | Critical | High | Medium | Low | Total
-- | -- | -- | -- | -- | --
reportportal/migrations | 0 | 1 | 0 | 0 | 1
reportportal/service-authorization | 0 | 11 | 6 | 0 | 17
reportportal/service-api | 1 | 11 | 6 | 0 | 18
reportportal/service-auto-analyzer | 1 | 10 | 8 | 0 | 19
reportportal/service-index | 0 | 1 | 0 | 0 | 1
reportportal/service-ui | 0 | 1 | 0 | 0 | 1

I am also attaching the reports for reference on the vulnerabilities details. 
[Twistlockscanreports.zip](https://github.com/reportportal/reportportal/files/5054140/Twistlockscanreports.zip)

**Comment by artisood** [comment]
Do we have update on this issue. Thanks

**Comment by evjlobanova** [comment]
We are in progress.
I will update this ticket accordingly

**Comment by DzmitryHumianiuk** [comment]
We've implemented regular security scans for the images and address vulnerabilities with each release.
