### ISSUE TITLE
[v5] SSL configuration update for new traefik container

### ISSUE THREAD

**Issue by winstondz** [reportportal/reportportal#1109]
**Describe the bug**
The existing documentation at 
https://reportportal.io/docs/Setup-SSL 
is not accurate for setting up SSL. 

It will fail with the following error :
command traefik error: failed to decode configuration from flags: field not found, node: acm

It needs to be updated for v2 : https://docs.traefik.io/migration/v1-to-v2/

**Comment by evjlobanova** [comment]
@Cyberglamdring Hleb, could you please check and update if it is needed

**Comment by Cyberglamdring** [comment]
@evjlobanova, Traefik is used by developers, we need to ask them if there will be any problems with the migration to version 2

**Comment by Yumfriez** [comment]
@Cyberglamdring We've already upgraded traefik version to v2.0.5 so there won't be a problem

**Comment by Cyberglamdring** [comment]
Dear @winstondz,
We will update the documentation soon. Please use the official [Traefik documentation](https://traefik.io/blog/traefik-2-tls-101-23b4fbee81f1/) or use the [link](https://doc.traefik.io/traefik/migration/v1-to-v2/) you provided.
Thank you

**Comment by jsmongeski** [comment]
Are there any updates on this?  I'm also looking to implement https access, not really sure how to approach the problem via the Traefik docs, an working docker-compose.yml example here would help, if any RP developers could provide one.
