### ISSUE TITLE
[v5.3]  Potentially Fatal Deserialization Operation

### ISSUE THREAD

**Issue by babantax** [reportportal/reportportal#1113]
**Describe the bug**
After upgrading RP from version 5.0 to 5.3 in k8s many "Potentially Fatal Deserialization Operation" are logged in "reportportal-api" pod. Seems to happend during test executions are received.

**To Reproduce**
Upgrade form 5.0 to 5.3 and launch test executions.

**Screenshots**
![image](https://user-images.githubusercontent.com/52815118/90397049-8f795b00-e097-11ea-875e-0cc5c918feed.png)

**Desktop (please complete the following information):**
 - Kubernetes and rp 5.3

**Comment by pbortnik** [comment]
Hi, try to regenerate api token in your profile.

**Comment by evjlobanova** [comment]
@babantax ^^

**Comment by babantax** [comment]
I regenerated the tokens and error is still been logged. Any other possible solution?

**Comment by evjlobanova** [comment]
@pbortnik Could you please check this?

**Comment by avarabyeu** [comment]
Duplicates https://github.com/reportportal/reportportal/issues/1970
