### ISSUE TITLE
Latest Defect Type Boost feature not working

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1116]
**Describe the bug**
This is in reference to the feature #1005 . I added defect type - "System Slowness" in Build 38. For the same stacktrace i overwritted the defect type as "Jira Raised" in Build 39. Now as per the boost feature - for the same stacktrace, Build 40 should AA the issue as "Jira Raised"(latest defect type), but it still categorizes it as "System Slowness"

**Screenshots**
Attached video for the same.

**Versions:**
![Boost](https://user-images.githubusercontent.com/50797731/90607237-954d7880-e21e-11ea-8236-4938d1c6aa54.gif)

 - Version of RP - 5.3.0
@evjlobanova  Can you please check once.

**Comment by evjlobanova** [comment]
Hello
Please open execution in 40th launch
Open History of action
And click on the link in activity for Analysis
And share results
One more question, please provide startime for the last 3 items

**Comment by priyankachaturvedi30** [comment]
The activity of Analysis points to the execution for Launch #38, the first time it was categorized as "System Slowness".
Each build gets executed on a daily basis. One on each day.
I have one query - Re-iterating through the comments discussed in #1005 - Does this logic works only in situations were the count of defect types is equal ? (As mentioned in one of your comments - 1 PB 1 AB - tricky one for analyzer -- Would apply boost logic and mark the next one as AB) -- Does booster logic works for the situation were -  2PB 1AB (then according to booster logic it should be AB) or would it take count 2:1 in consideration and mark it as PB ignoring the booster logic?

**Comment by priyankachaturvedi30** [comment]
@evjlobanova : Did you get a chance to check this?

**Comment by evjlobanova** [comment]
@priyankachaturvedi30 error log of execution 38,39, 40 are the same?

**Comment by priyankachaturvedi30** [comment]
Yes @evjlobanova : Exactly same. what I wanted to check is if this booster logic is dependent on the count? Would it work when say, 15 times a bug been marked as PB and 16th time been marked as AB. Then on 17th time would it mark it AB or since the count of PB> AB , it would mark it as PB.

**Comment by evjlobanova** [comment]
@MariyaIvanina Could you please recheck this issue?

**Comment by MariyaIvanina** [comment]
@priyankachaturvedi30 Hi! The new logic shouldn't take counts of previous defect type assignments for the same log. I was trying to recreate your situation, but I didn't manage to. Could you please show start times for this test time in each build from 38 till 40, could you please show what particular item was linked to your test item from 40 build (click on the activity tab in the test item and open the link in the "based on item").
![image](https://user-images.githubusercontent.com/11046087/91695422-c90d9400-eb76-11ea-9f00-e29ddbea2ba0.png)
![image](https://user-images.githubusercontent.com/11046087/91695673-302b4880-eb77-11ea-8701-4c4c94857407.png)

**Comment by evjlobanova** [comment]
@priyankachaturvedi30 Could you please check Marya response
