### ISSUE TITLE
[v5] Unable to open log attachments while an adblocker is active

### ISSUE THREAD

**Issue by jibby0** [reportportal/reportportal#1119]
**Describe the bug**

When clicking on a log attachment, the attachment tab is hindered by popular adblockers, in both Chrome and Firefox.

When an adblocker is active, the created attachment tab will immediately be closed.

**To Reproduce**

- Access a ReportPortalv5 launch with attachments, in Chrome or Firefox, while an adblocker is active & enabled for that website.
- Click on an attachment.
- A new tab attempts to open with the contents of the attachment, but is immediately closed by the adblocker.

**Expected behavior**

A new tab opens with the contents of the attachment.

**Screenshots**

The video below shows the described behavior: after disabling uBlock Origin, the attachment appears without trouble.

https://gfycat.com/fearfulslimygrunion

**Desktop:**

Observed on:

- OS: Ubuntu 20.04.01 LTS

With both:
- Browser: Firefox
- Version: 79.0 (uBlock Origin v1.29.0 or Adblock Plus v3.9.4)

And

- Browser: Chrome
- Version:  84.0.4147.135 (uBlock Origin v1.29.0 or Adblock Plus v3.9.4)

**Additional context**
In the case of uBlock Origin, popup blocking was not explicitly enabled in the plugin, yet the attachments were still blocked.

This identical setup allowed the viewing of attachments in ReportPortalv4, with no adblock configuration necessary.

Please let me know if you need any more information from me. Cheers!

**Comment by AmsterGet** [comment]
Hi @jibby0 !
We care about security and decided to restrict access to attachments via direct link.
This is true for the current implementation of UI and authorization services (version 5.*).
Use ad blocker exception rules to whitelist RP.
