### ISSUE TITLE
report attributes are not updating in portal from reportportal.properties file 

### ISSUE THREAD

**Issue by SharadSharma99** [reportportal/reportportal#1120]
**Describe the bug**
report attributes are not updating in portal from reportportal.properties file 
**Expected behavior**
report attributes should be update in portal from reportportal.properties file  with below details and both way tried
rp.attributes = platform:android;android;
rp.attributes = platform:android;

**Screenshots**
If applicable

**Versions:**
 - Mobile execution
 - 5.1.0

**Comment by evjlobanova** [comment]
Any details? 
Could you please specify steps for reproducing and expected results?

**Comment by SharadSharma99** [comment]
![2020-08-24_165241](https://user-images.githubusercontent.com/39654729/91039564-6a9e5e00-e62a-11ea-8838-9718c1c74f64.jpg)
![2020-08-24_165058](https://user-images.githubusercontent.com/39654729/91039573-6d994e80-e62a-11ea-93c2-b4d5c0693e91.jpg)

**Comment by SharadSharma99** [comment]
Hi @DzmitryHumianiuk 

Please help us with it.

**Comment by DzmitryHumianiuk** [comment]
@SharadSharma99 please follow up with the help from community, by joining the SLACK chat here:
https://reportportal-slack-auto.herokuapp.com/

**Comment by evjlobanova** [comment]
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#start-launch

This is our dev guide on how to report results toreportportal

**Comment by vineethmaller** [comment]
@DzmitryHumianiuk @evjlobanova 

Hi Team, could you please provide a solution to the issue rather than just pointing to slack or guide. We have followed the guide but we still get the same issue.

**Comment by evjlobanova** [comment]
@vineethmaller Could you please tell me what agent and what version do you use for reporting?

**Comment by vineethmaller** [comment]
@evjlobanova Build: 5.1.0
Connecting to an endpoint using access token from Java application.

rp.attributes = RegressionTestVersion:2;

**Comment by Yumfriez** [comment]
@vineethmaller What Java agent do you use to report results to the RP instance?

**Comment by vineethmaller** [comment]
@evjlobanova @Yumfriez 
Java cucumber agent, version 4.0.2

**Comment by Yumfriez** [comment]
@vineethmaller For 4th version agents this property should be - `rp.tags`, not `rp.attributes` (this property for 5th version agents)

**Comment by vineethmaller** [comment]
@Yumfriez Which agent should I use for Report portal endpoint with build 5.1.0? I want to use attributes.

**Comment by evjlobanova** [comment]
Use agents 5+ 
Agent 4 and version 4 of ReportPortal is not supported any more

And we recommend updating your ReportPortal штыкефтсу to the latest version (5.3.1)

**Comment by silwalrajan** [comment]
I am having some similar issues with attributes in rp properties file. 
Use case:  To sort out the feature/scenario based upon its severity;critical;severity;high;severity;low AND execute the features with selected severity so that I can analyze the report based on the severity. 

How can we implement this?
I am using RP 5.7.2 with Cucumber v6. and agent-java-cucumber6  5.1.1.

**Comment by DzmitryHumianiuk** [comment]
@silwalrajan attributes in `reportportal.properties` files are aimed to be a launch level attributes.
It has nothing to do with test case level.

for the test case level. you have to add attribute via annotations in the test code:
https://github.com/reportportal/client-java/wiki/Test-item-attributes
https://github.com/reportportal/client-java/wiki/Test-item-attributes-examples

And then use `Component Health Check` widget to represent it:
https://reportportal.io/docs/Component-health-check
https://reportportal.io/docs/Table-Component-health

**Comment by silwalrajan** [comment]
Can this be implemented via feature files and not through the step-definition? As same step-definition can be used for multiple use cases with different severities (attributes). Or is this not supported ?

**Comment by DzmitryHumianiuk** [comment]
@silwalrajan it's not supported.
but you can contribute into this.

with the functionality on the agent side (framework side) and then with the parser logic for the API side.

please don't hesitate to contribute
