### ISSUE TITLE
Project setting are not updating 

### ISSUE THREAD

**Issue by vaibhavshukl12** [reportportal/reportportal#1123]
Hi Team, 
Since few days I am seeing that project setting is not updating in Report Portal 
it's coming invalid date in all dropdown.

And when I am updating it then below message is coming.

Failed to update project settings.

Hi,@evjlobanova  Hope you are doing well.
Please help with this.

**Comment by evjlobanova** [comment]
@vaibhavshukl12 
Which version do you use?
Any screens, logs, details will be appreciated

**Comment by vaibhavshukl12** [comment]
Hi, @evjlobanova in both versions 5 and 5.3 I am facing the same issue.
Please find the screenshot.

![Errror](https://user-images.githubusercontent.com/49065599/91038831-1646ae80-e629-11ea-9869-abc78b66d79a.JPG)

**Comment by vaibhavshukl12** [comment]
Attaching a screenshot after updating the setting -  error message.

![image](https://user-images.githubusercontent.com/49065599/91039038-73dafb00-e629-11ea-84c0-9e731ae5a3e9.png)

**Comment by vaibhavshukl12** [comment]
Hi, @evjlobanova Hope you are doing well.
Is there any update on this issue.

**Comment by evjlobanova** [comment]
@vaibhavshukl12 please send us a number of versions you have

**Comment by vaibhavshukl12** [comment]
Hi @evjlobanova  -Pleaser find below versions number 
Report Portal - 5.0

**Comment by evjlobanova** [comment]
All versions for all services, such as mistake can be met in case you use different versions for different services.

Update to the latest version, for now, the latest version is 5.3
