### ISSUE TITLE
How do I get a link to the report at runtime

### ISSUE THREAD

**Issue by zhangyh35** [reportportal/reportportal#1127]
How do I get the URL of this build in the script, like this
http://127.0.0.1:8080/ui/#local_test/launches/all/63/1779/1781/1788/log
I want to get this URL at the runtime,Or is there a function to get the launchid? testid?
I use the Java language,Help me.

**Comment by Gulats** [comment]
related to https://github.com/reportportal/reportportal/issues/247
but the url stated here is not working for me either.

**Comment by mchundi** [comment]
I see the same error as Gulats


wd @ analytics.js:39
/api/v1/polaris/launch/NaN:1 Failed to load resource: the server responded with a status of 404 (Not Found)

any help is appreciated.

**Comment by HardNorth** [comment]
@Gulats @mchundi In RP 5 we changed reporting key from launch ID to launch UUID. So that feature got broken. But I believe we fixed it in the latests version, or it's right behind the corner to fix.
@AmsterGet, please comment.

**Comment by AmsterGet** [comment]
@mchundi We've already fixed this issue and it's awaiting the 5.4 release (see RP [releases](https://github.com/reportportal/reportportal/releases))

**Comment by mchundi** [comment]
@AmsterGet Thank you for the update.
Can you please let me know when I can expect version 5.4. This fix is important for our release.

**Comment by mchundi** [comment]
@AmsterGet can you please let me know when can I expect the latest version?

**Comment by evjlobanova** [comment]
This month
