### ISSUE TITLE
Password for new users 

### ISSUE THREAD

**Issue by babantax** [reportportal/reportportal#1128]
**Describe the bug**
In version 5.3 when a new user is created, in the email sent with the password, the password seems coded. 

If you try to login, fails. 

![image](https://user-images.githubusercontent.com/52815118/91278348-671eea00-e784-11ea-8686-081dced577be.png)

![image](https://user-images.githubusercontent.com/52815118/91278441-8453b880-e784-11ea-8577-d3ec315aadc2.png)

**Comment by svettsova** [comment]
issue is submitted
