### ISSUE TITLE
Missing breadcrumb links for test suites when the test item was opened from failures page

### ISSUE THREAD

**Issue by aliaksandrbasau** [reportportal/reportportal#113]
Steps to reproduce:
1. Find a launch with a few failures.
2. Click a link in Failed column that will show the failed items.
3. Click a link of a failed test item.
![image](https://cloud.githubusercontent.com/assets/6681200/25447346/dfcb4952-2a82-11e7-84ac-5171591df9a8.png)
=> Test item is opened but there are no breadcrumb links for test suites.
![image](https://cloud.githubusercontent.com/assets/6681200/25447381/fc4cbb42-2a82-11e7-9853-c9840ffb8af9.png)
It may be an intentional design change but it gives no way to navigate to upper level in test suite tree from the current page.

**Comment by DzmitryHumianiuk** [comment]
**Valid**

under discussion.
will return full path in breadcrumbs 
or
add special component to present full path

_issue now_: can't open parent of item from current view.

**Comment by DzmitryHumianiuk** [comment]
this will be returned,
but in other view.

**Comment by DzmitryHumianiuk** [comment]
**done**
Verified on
- Chrome 58.0.3029.110 (64-bit)
- Firefox 53.0.2 (64-bit)
- Edge 38.14393.1066.0
