### ISSUE TITLE
[v5]

### ISSUE THREAD

**Issue by the-octopus** [reportportal/reportportal#1132]
**Describe the bug**
I'm not able to login to the report portal UI login.

**To Reproduce**
- please use the docker version to let you report portal up and running
- I'm using latest version from docker file 5.3.0
- open the browser.
- write the portal URL.
- enter user name and password.
**Expected behavior**
expected to login to the report portal

**ISSUE**

the system give green message signed in successful but no redirect to the home page.

**Comment by the-octopus** [comment]
Hi @evjlobanova , thanks for your interest. in fact all services are running and also the server was working fine for 1 day.
after that I'm not able to login.

hereinafter is server Memory Details:
                    total        used        free      shared  buff/cache   available
Mem:           6986        5274         374          97        1338        1536
Swap:          5999         672        5327


Please advice by a solution

**Comment by LakshmiPriya0408** [comment]
I am facing the same issue, still not resolved. Please suggest me a solution for this.

**Comment by evjlobanova** [comment]
Which version do you use ?
Which error in the log you can see?

**Comment by MaryiaRymarchyk** [comment]
Hello @LakshmiPriya0408, @the-octopus 
As we haven't received a reply from you,  and issue is quite old - it will be closed for now.
Just in case you still have the issue, please, do not hesitate to get in touch with more details.
