### ISSUE TITLE
Can we upload video in attachment on RP 

### ISSUE THREAD

**Issue by vaibhavshukl12** [reportportal/reportportal#1134]
Hi @DzmitryHumianiuk can we upload the video as an attachment on RP

**Comment by DzmitryHumianiuk** [comment]
@vaibhavshukl12 yes.
the same way like screenshot

**Comment by vaibhavshukl12** [comment]
Thanks, @DzmitryHumianiuk one more doubt -we have to upload video against each test case or we can upload against the test suite for a full run ?

**Comment by DzmitryHumianiuk** [comment]
@vaibhavshukl12 there is so call `Launch attachment`. So you can upload recording of run in a whole.

**Comment by hager-yousri** [comment]
@vaibhavshukl12 @DzmitryHumianiuk 
how we please I can show screenshots / recorded videos in RP ?

**Comment by DzmitryHumianiuk** [comment]
@hager-yousri 
https://github.com/reportportal/examples-java - various examples in Java
https://github.com/reportportal/examples-java/tree/master/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/logging - examples of files logging in logback

https://github.com/ihar-kahadouski/dev-guide/blob/master/reporting.md#batch-save-logs devguide for the custom solution.

**Comment by hager-yousri** [comment]
Thanks @DzmitryHumianiuk for your reply but am using Robot framework with python do you have any idea please how to do this with Robot?

**Comment by DzmitryHumianiuk** [comment]
Hey @HardNorth, any suggestions for @hager-yousri ?
