### ISSUE TITLE
How to implement ReportPortal with TestNG framework

### ISSUE THREAD

**Issue by gopikishan1995** [reportportal/reportportal#1135]
Hi team,
I am having a project (POM framework) where in i have base class in which i have all common methods and i have few other classes. I have to integrate report portal with my framework. like i have to create a method in base call and call in for all the other methods. I need to catagorise pass and fail logs in report portal.. can i get help on this?

**Comment by HardNorth** [comment]
Please refer our examples: https://github.com/reportportal/examples-java
