### ISSUE TITLE
No data available for component health check and cumulative trend chart widgets

### ISSUE THREAD

**Issue by jgroet1** [reportportal/reportportal#1136]
I'm not sure if this is a bug or I'm doing something incorrectly. I can't seem to get data to populate for component health check and cumulative trend chart for our data. It works ok with the demo data.

Currently, I've tried the following ways to get data to populate...

- 3 launches, 1 suite, 272 tests with area attributes being marked by area
- 10 launches, 1 suite, 272 tests with area attributes being marked by area
- 10 launches, 1 suite with type attribute, 272 tests with area attributes being marked by area
- 10 launches, 4 suites with area attribute, 272 tests with area attributes being marked by area
- 10 launches marked with 3 attributes, 4 suites with area attribute, 272 tests with area attributes being marked by area

component health check
Filter: Name contains [product name]
Level1: area

cumulative trend chart
Level 1: run
Level 2: build

The attribute filters appear to work in the ui in the appropriate sections but don't in the widgets. Any help would be great. Thanks!

**Comment by evjlobanova** [comment]
Widgets work as expected, something is on your side.
 Please send me a screenshot of your launches with attributes /test items. Screenshot with widget wizard.
Please check if you are reporting attributes with key: value structure. It can be that you report all attributes only in value.

**Comment by jgroet1** [comment]
![01-Launch](https://user-images.githubusercontent.com/68276673/92458755-72faab00-f18b-11ea-90d0-edaa9bd9c5a8.png)
![02-Launch](https://user-images.githubusercontent.com/68276673/92458759-72faab00-f18b-11ea-93ef-731c2d3725f8.png)
![03-Tests with filter on attributes](https://user-images.githubusercontent.com/68276673/92458761-73934180-f18b-11ea-9486-3a8003811d07.png)
![04-Widget wizard 1](https://user-images.githubusercontent.com/68276673/92458762-73934180-f18b-11ea-85ca-5e794a8f5431.png)
![04-Widget wizard 2](https://user-images.githubusercontent.com/68276673/92458764-742bd800-f18b-11ea-81a4-c13200077f22.png)

Thanks for getting back. Here are the screenshots. The key values appear correctly entered.

**Comment by evjlobanova** [comment]
So that the problem can be in a way how you report attributes.
Attribute should have key and value

![image](https://user-images.githubusercontent.com/30413511/92465305-145b1e80-f1d7-11ea-839f-d15dff54bafd.png)

Please open edit modal for launch, and check if the attribute has right structure

**Comment by jgroet1** [comment]
![05-Launch attributes unclicked](https://user-images.githubusercontent.com/68276673/92466179-57949d80-f195-11ea-9853-4d105e8a0e76.png)
![06-Build clicked](https://user-images.githubusercontent.com/68276673/92466180-57949d80-f195-11ea-8cb4-39852248bc3f.png)
![07-Suite attribute clicked](https://user-images.githubusercontent.com/68276673/92466181-582d3400-f195-11ea-9633-12f513c3ab1d.png)
![08-Test item attribute clicked](https://user-images.githubusercontent.com/68276673/92466182-582d3400-f195-11ea-951d-0ad180773a0f.png)

They seem right, unless I'm missing something

**Comment by evjlobanova** [comment]
Are you in our slack chat?

**Comment by eugen0309** [comment]
We've been experiencing the same problem for a while and I cannot get any solutions for it.
Is there a minimum number of launches / tests that are required for this widget to work?

Thanks!
