### ISSUE TITLE
Database documentation

### ISSUE THREAD

**Issue by odubaj** [reportportal/reportportal#1142]
Hello,

do you have some kind of documentation according to the database ? For example ER-diagrams, class diagrams etc.

If yes, can you please share them?

Thanks.

**Comment by evjlobanova** [comment]
No, we do not 
Could you please tell us your use case, why do you need it? 
Maybe we can find a workaround or prepare this info for users in future

**Comment by odubaj** [comment]
It will help developers to better understand how reportportal backend is working and how data are stored

**Comment by alena-babrova** [comment]
Hello @odubaj,
Could you please tell me is this request still relevant for you?

**Comment by alena-babrova** [comment]
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
