### ISSUE TITLE
[v5] Unable to get ReportPortal running via Docker Compose

### ISSUE THREAD

**Issue by abryleuski** [reportportal/reportportal#1143]
**Describe the bug**
Unable to get ReportPortal running via Docker Compose

**To Reproduce**
wget https://raw.githubusercontent.com/reportportal/reportportal/master/docker-compose.yml
docker-compose -p reportportal up

**Expected behavior**

**Desktop (please complete the following information):**
 - Device: VM
 - OS: "20.04.1 LTS (Focal Fossa)

**Additional context**
[rp.log](https://github.com/reportportal/reportportal/files/5211817/rp.log)

**Comment by evjlobanova** [comment]
Do you follow steps described here https://reportportal.io/docs/Deploy-with-Docker?
