### ISSUE TITLE
1) How to segregate launches based on different Platform (IOS, Android, Web(Chrome, FF)) & different Applications .(FB, AMAZON & Filpcart)

### ISSUE THREAD

**Issue by gopikishan1995** [reportportal/reportportal#1145]
1) How to segregate launches based on different Platform (IOS, Android, Web(Chrome, FF)) & different Applications (FB, AMAZON and flipcart)

**Comment by Invictum** [comment]
@gopikishan1995 
You have several options that depends on your needs:
- Keep each app-platform in separate RP projects. E. g. FB-IOS, FB-ANDROID, FB-WEB
- Keep each app in separate RP project and use launch name to segregate platform. E. g. for FB project: WEB_TESTS, ANDOID_TESTS, IOS_TESTS
- Keep all apps and platforms in one huge project and segregate app-platform using launch attributes. E. g. TESTS launch with attributes: platform - iOS, app - FB. Keep in mind that this variant may cause issues with auto-analysis feature.

**Comment by evjlobanova** [comment]
Just small adding to the last point: Component Health Check Widget (table view) helps to group launches arround different attributes and see all results in one table
