### ISSUE TITLE
How to delete Old entry launches automatically (2 weeks once / 1 month once)

### ISSUE THREAD

**Issue by gopikishan1995** [reportportal/reportportal#1146]
How to delete Old entry launches automatically (2 weeks once / 1 month once)

**Comment by mnicula** [comment]
go to Settings -> General -> Keep launches

**Comment by evjlobanova** [comment]
use the latest version of report portal 5.3.1

**Comment by dzoryn-clgx** [comment]
Hello, I've updated reportal to the latest version and set up "Keep launches" setting to 90 days. But when I navigated to launches I saw 2 years old launches.  What could the problem?
