### ISSUE TITLE
How to differentiate between launches like Main launch vs debug launch ie: only main launch should display & debug launch shouldn't display  

### ISSUE THREAD

**Issue by gopikishan1995** [reportportal/reportportal#1147]
How to differentiate between launches like Main launch vs debug launch ie: only main launch should display & debug launch shouldn't display

**Comment by evjlobanova** [comment]
https://reportportal.io/docs/View-launches
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#start-launch
