### ISSUE TITLE
Launch stats missing in tabular view

### ISSUE THREAD

**Issue by rjswitzer3** [reportportal/reportportal#1148]
**Overview:**
I am using the python `reportportal-client` package to report test results to our Report Portal instance. After switching from Report Portal version 4.3 to version 5.2, I noticed that the launch stats are no longer displayed in the tabular view. Note: After the switch, I did update my implementation in accordance with the official [ github guide](https://github.com/reportportal/client-Python).  Screen shots below:

Report Portal 4.3:
![image](https://user-images.githubusercontent.com/7348369/93356132-d1b7c880-f80c-11ea-8943-9b1a9bceb8fc.png)
![image](https://user-images.githubusercontent.com/7348369/93356851-aed9e400-f80d-11ea-9dad-50114caf1a39.png)

Report Portal 5.2:
![image](https://user-images.githubusercontent.com/7348369/93356463-2f4c1500-f80d-11ea-8618-449dcdf9613a.png)
![image](https://user-images.githubusercontent.com/7348369/93357011-d9c43800-f80d-11ea-99fd-60fc8137479f.png)

Only once you click all-the-way down on a specific test's results, are you able to accurately see if a launch passed/failed and the trend.

Report Portal 5.2:
![image](https://user-images.githubusercontent.com/7348369/93357368-345d9400-f80e-11ea-86a9-231b6e6ec189.png)

**Actions Taken:**
- Read through the `reportportal-client` source code to confirm behaviors and my own implementation
- Enabled debug logging in tests and confirmed that the tests and launches are being completed/finished successfully
- Verified launch and test information/details are in the database and are valid
- Confirmed there are no errors being thrown on the back-end or front-end
- Confirmed there is no value in table in the UI that might be hidden
- Confirmed behavior across browsers and devices

**Specifications**
- python: v3.6
- reportportal-client: v5.0.5
- Report Portal: 5.2 [API Service: 5.2.1; Index Service: 5.0.7; Authorization Service: 5.2.1; Service UI: 5.2.0;]
- Report Portal Instance AMI: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20200112 (ami-07ebfd5b3428b6f4d)
- Docker: v19.03.8
- docker-compose: v1.25.5
- Browser: Chrome on Windows 85.0.4183.102

**Conclusion:**
I'm not sure what the issue is at this point, everything seems to indicate my implementation is correct, and that the report portal instance is running fine. Is there a setting or flag somewhere that I am missing? Or is there something I'm overlooking? Or is this an actual bug?

**Comment by evjlobanova** [comment]
@iivanou could you please check if the issue on the agent side may be?

**Comment by iivanou** [comment]
@rjswitzer3 Are you using the reportportal-client directly in your Python code? In this case, check how exactly you call the start_test_item() method of the client. You should pass the "STEP" value for the item_type option instead of the "TEST".

Or, maybe, you are using the client in combination with the (pytest/robot/unittest) agents?

**Comment by rjswitzer3** [comment]
@iivanou Yes I am using the reportportal-client directly and I'm not using any other agent.

For the example provided, I call `start_test_item()` with `item_type='SUITE'`. I make a call to `start_test_item()` before the suite starts and `finish_test_item()` with the correct parameters after the completion of the test suite. For our purposes, we only want to report at the suite level to report portal whether it passed/failed/skipped and not at the individual test level.

Given your feedback, are you suggesting I call `start_test_item(..item_type='STEP'..)` after my initial call of `start_test_item(..item_type='SUITE'..)`?

**Comment by iivanou** [comment]
> Given your feedback, are you suggesting I call `start_test_item(..item_type='STEP'..)` after my initial call of `start_test_item(..item_type='SUITE'..)`?

Exactly.

**Comment by rjswitzer3** [comment]
@iivanou The described changes rectified the tabular view stats, but resulted in two entries being logged under the same launch - one with stats and details displayed, and one without. Given this behavior behavior I have removed the call of `start_test_item(..item_type='SUITE'..)` and have opted to only use `start_test_item(..item_type='STEP'..)` for the time being.


Now this begs the following questions: 

- Where and how did the functionality change between `reportportal-client` v2 and v3, that are used with report portal v4 and v5 respectively? In other words, this used to work

- What is the intended use/purpose of `item_type='SUITE'` - stats pertinent to which aren't displayed, and steps/tests executed from within don't appear to have relations when viewed in the UI - is this being deprecated?

**Comment by iivanou** [comment]
@rjswitzer3 
You are getting two entries being logged under the same launch because in Report Portal v5 you should add the correct parent UUID to the item. Please, read through the [reporting guidelines ](https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md) to start working with RP v5 correctly.

Answers:

- Report Portal V5 reporting is different comparing to reporting to V4. Consider using reportportal-client v5.0.5 for reporting to v5.

- "SUITE" will be used as part of the test hierarchy when you start reporting it via API correctly. Sending test items as "STEP" will be resolved in Report Portal V6.

**Comment by rjswitzer3** [comment]
@iivanou 
The correct `uuid` is being passed, and the correct `launchUuid` is being passed - as previously mentioned, I have read through.  

> Report Portal V5 reporting is different comparing to reporting to V4. Consider using reportportal-client v5.0.5 for reporting to v5.

Typo on my behalf, I've edited my post accordingly. I'm referring to difference between `reportportal-client` v3 and v5.

> "SUITE" will be used as part of the test hierarchy when you start reporting it via API correctly.

Once again, they are being reported correctly to the API... is that all the support/advise you can provide? would you prefer code?

>  Sending test items as "STEP" will be resolved in Report Portal V6.

Thanks.

**Comment by iivanou** [comment]
@rjswitzer3 See [this method](https://github.com/reportportal/agent-python-pytest/blob/8a6c2fdac4292762baa12cd42ebe65c990de1089/pytest_reportportal/service.py#L272). It reports Pytest results correctly through the reportportal-client v 5.0.5.

**Comment by rjswitzer3** [comment]
@iivanou I almost forgot to follow-up. The cause of my latter issue was a typo on my behalf - I misspelled `parent_item_id` as `paernt_item_id` - and the `**kwargs` just let it carry-on gracefully. 

Thanks for the assistance.
