### ISSUE TITLE
Report Portal Integration with Azure SSO

### ISSUE THREAD

**Issue by venky223** [reportportal/reportportal#1149]
Hi, 
Im trying to integrate Reportportal with Azure SSO, but gets this error.

Does Reportportal works with Azure SSO??
If yes can help me out on this.

![image](https://user-images.githubusercontent.com/34525366/93507408-7bad5880-f8d2-11ea-84ad-51a587eb8fff.png)

![image](https://user-images.githubusercontent.com/34525366/93507129-0fcaf000-f8d2-11ea-8b8a-bd19968c5dfa.png)

**Comment by evjlobanova** [comment]
RP has integration with SAML/Active directory/ LDAp/GitHub

**Comment by kirillbilchenko** [comment]
@venky223 did you manage to integrate with azure?

**Comment by amitngm** [comment]
any update on this and also please help me to know that whether azure ad based SAML (not okta) work with RP

**Comment by fkrivsky** [comment]
@amitngm looks like its coming eventually per https://github.com/reportportal/reportportal/issues/1198
