### ISSUE TITLE
Report Portal Not Getting Launched after shell installation (issue with traefik )

### ISSUE THREAD

**Issue by bzsharm** [reportportal/reportportal#1150]
We followed all the steps that were present in documentation but at the end we could see that “trafek file” was present in the directory where installed all the dependencies but that was an empty file (it did not have.toml extension as mentioned in the download.sh file), so I mocked a file and placed it in installation directory with the port details with traefik.toml file,

Then I Updated the version number for few services as “UI_VERSION="5.2.0"
SERVICE_INDEX_VERSION="5.0.9"’ in ‘download_services.sh’ file, previously the version from the documentation was 5.0.0 for every services,

Also updated the below from version v1.7.19 to v1.7.26,
# GATEWAY
wget -c -N -O traefik https://github.com/containous/traefik/releases/download/v1.7.26/traefik_linux-amd64
Triggered ‘start_rp.sh’ after stopping the services, but I still could see that “Tomcat” is successfully launched in the logs .

But when I ran the command to see list of services which are up using the below command,
I could not  see that traefik is not listed .
“lsof -i -P -n | grep LISTEN”

![image](https://user-images.githubusercontent.com/64862297/93511496-8f8fa380-f940-11ea-9401-0d4a2a3289e4.png)

 

Could anyone please help us with it, or if you have a updated documentation, can anyone share it Please! 
we did the version updates because versions from the documentations were not working .

**Comment by bzsharm** [comment]
@lexecon @abotalov  Please take a look at this issue.

**Comment by bzsharm** [comment]
evjlobanova  hi ,can you please help me with this

**Comment by bzsharm** [comment]
@evjlobanova  could you please help me with this !

**Comment by Yumfriez** [comment]
@evjlobanova I suppose we need task (if it doesn't exist) for our shell installation documentation update

**Comment by Yumfriez** [comment]
https://github.com/reportportal/reportportal/issues/973

**Comment by evjlobanova** [comment]
Closed
All progress should be tracked in the ticket #973
