### ISSUE TITLE
[help required] Read bearer token using credentials

### ISSUE THREAD

**Issue by vishallanke** [reportportal/reportportal#1151]
I had gone through API documentation.
How can I fetch Bearer Token from credentials ?
I am not finding this inside doc..

I tried below from Postman
```
POST http://ec2:8080/uat/sso/oauth/token
I send grant-type, username, and password as  x-www-form-urlencoded body
```

However it always return me - `{"timestamp":"2020-09-18T06:47:26.082+0000","status":401,"error":"Unauthorized","message":"Unauthorized","path":"/sso/oauth/token"}`

**Comment by DzmitryHumianiuk** [comment]
@vishallanke did you try this?
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md

**Comment by vishallanke** [comment]
Hi @DzmitryHumianiuk 
I tried...its not working.
I tried to debug the issue via Postman

I analyse network call by manually logged-in to report portal and capture `""Authorization" : "Basic dWk6dYltYX3="" `

Inside Header if I put
"Authorization" : "Basic dWk6dYltYX3=", then I can get access token

Now CURL and POSTMAN query is working ?

I was wondering whats` "Authorization" : "Basic dWk6dYltYX3="` and why should I provide this inside Postman/ Curl call ?


Below call not working

```
curl --header "Content-Type: application/x-www-form-urlencoded" \
     --request POST \
     --data "grant_type=password&username=superadmin&password=erebus" \
     --user "ui:superadmin" \
     http://ec2.com:8080/uat/sso/oauth/token
```

BELOW CALL IS WORKING
`curl --header "Content-Type: application/x-www-form-urlencoded" --header "Authorization: Basic dWk9eWltTW4=" --request POST --data "grant_type=password&username=superadmin&password=erebus"   http://ec2:8080/uat/sso/oauth/token`

**Comment by subhash403** [comment]
Below call is also not working for me 

`url --header "Content-Type: application/x-www-form-urlencoded" --header "Authorization: Basic dWk9eWltTW4=" --request POST --data "grant_type=password&username=superadmin&password=erebus"   http://ec2:8080/uat/sso/oauth/token`

**Comment by DzmitryHumianiuk** [comment]
@subhash403 https://reportportal.io/docs/dev-guides/ReportingDevelopersGuide#retrieving-api-token
