### ISSUE TITLE
[v5] StackTrace quick view do not wrap log

### ISSUE THREAD

**Issue by Shakevg** [reportportal/reportportal#1153]
**Describe the bug**
StackTrace quick view do not wrap log

**To Reproduce**

1. Report Portal integrated with .Net Framework 4.8 (mstest, agent-net-vstest, NLog).
2. Exception logging to report portal
=> Log is not wrapped in StackTrace quick (display as one string)

**Expected behavior**
Log should be wrapped in StackTrace quick view

**Screenshots**
![image](https://user-images.githubusercontent.com/42133199/93847734-6ceaeb00-fcb0-11ea-944e-77581d35d9dc.png)

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome]
 - Version [85]

**Additional context**
StackTrace that return from the server has wrapping but it is not take into account when display in StackTrace quick view
![image](https://user-images.githubusercontent.com/42133199/93847973-1e8a1c00-fcb1-11ea-802c-f1e3ab54f96f.png)

**Comment by evjlobanova** [comment]
Hello
We have fixed this issue in version 5.3.3 
±ETA the end of October
