### ISSUE TITLE
[v5] [doc] Installing RP on UBuntu not working

### ISSUE THREAD

**Issue by vishallanke** [reportportal/reportportal#1154]
Installing RP on UBuntu
Steps - https://reportportal.io/docs/Deploy-ReportPortal-on

`sudo apt install python-pip`
 is no longer valid. 

Here, user should strictly avoid above steps, else he will face plenty of issues related to PIP, Docker Compose Compatibility with Python, Uninstalling Python2.7 fully

Instead of this `sudo apt install python-pip` , user need to follow detailed steps to install Python3.5
Python3.5 wont have PIP. So need to install PIP3
Now docker compose can be installed using PIP3 command than PIP command

**Comment by evjlobanova** [comment]
@Cyberglamdring Hleb, could you please check this issue

**Comment by Cyberglamdring** [comment]
Thanks, we'll update the documentation soon. Also you can install docker-compose from the [official documentation](https://docs.docker.com/compose/install/#install-compose-on-linux-systems)
