### ISSUE TITLE
Filters to allow for child tag (tags on test suites and individual tests) 

### ISSUE THREAD

**Issue by Shazear** [reportportal/reportportal#1157]
**Describe the solution you'd like**
When applying a filter, I would like to filter on tags that might exist at a child level, not just the Test Launch level. 

Current Functionality:
When adding tag: "Foo" to Tags filter dialog box, only Test Launches with "Foo" are found.  If no tag "Foo" is found, then no results displayed.  There are no tags at the Test Suite or Test Case level available for filtering.  This requires the user to go into each test run, and then filter.  This makes it difficult to build dashboards that might have functionality-based or team-based filters.

Expected Functionality:
When adding tag: "Foo" to Tags filter dialog box, Launches display metrics based on any child objects that match the tag filter, and any children of objects with matching tags.
This will allow a dashboard for all tag:"Foo" as an option, so I can track tag:"Foo" via a dashboard/widget.
Assuming:
Launch#1234
Contains Suite1, Suite2, Suite3
Suite1 has Test1.1, test1.2, test1.3
Suite2 has Test2.1, test2.2, test2.3
Suite3 has Test3.1, test3.2, test3.3
And 
Suite1 has tag "Foo"
Test2.1 & Test3.2 also have tag "Foo"

Filter result would then show for Launch#1234:
All results in Suite1
Plus only Results for Test2.1 and Test3.2

**Is your feature request related to a problem? Please describe.**
Not really a problem.

**Comment by evjlobanova** [comment]
Firstly you need to update to the latest version (5.3), use attributes instead of tags
For described reasons you can use Component Health Check widget anв Component Health Check Widget (table view)
https://reportportal.io/docs/Table-Component-health
