### ISSUE TITLE
how to export lanuches with screenshot ?

### ISSUE THREAD

**Issue by loudDD** [reportportal/reportportal#1159]
the export function can only export logs , is this possible to export lanuch with screenshot?
i can copy files manully

**Comment by evjlobanova** [comment]
Actually there is no possibility to export launch with logs as well as screenshots now.
Could you please provide more details on what you are trying to do?
Could you please describe your business need? How do you plan to use this information?

**Comment by loudDD** [comment]
Here is the deal.
we have two reportportal , the reportportal_a have some import launches ,it contains the logs and screenshots.
then we create reportportal_b and try to abandon reportportal_a because of some reason , and we'd like to copy the important launches from reportportal_a

**Comment by evjlobanova** [comment]
we do not have such functionality out of the boxes

We need to know your use case and business needs, in order to define if we can add this request to backlog.

**Comment by DzmitryHumianiuk** [comment]
@loudDD we have migration scripts, which can migrate data from instance of RP v4.x to instance of RP v5.3.x
but this is more about version to version migration.

In case if you want to migrate data to the same version of product, then you just can backup database.
And restore it at new instance.
in Version 4 all screenshots stored in database. so you all covered.
in Version 5 all screenshots stored in separe MinIO layer on filesystem, thus you need to copy this file structure as well.

Does it help you?

We also can provide dedicated paid consultancy and complete this migration for you.
let us know.
