### ISSUE TITLE
Hide filter criteria panel by default on Launches page

### ISSUE THREAD

**Issue by aliaksandrbasau** [reportportal/reportportal#116]
The panel with filter criteria occupies 20% of the window height but it's not quite useful to see it in case of launch filters (especially shared ones). My filter were created years ago and I don't change them often (or even at all). There is no need for me to see the filter criteria each time when I open the filter. I would rather see more launches.
I would suggest to add a link to show/hide the filter criteria panel and to hide it by default in case of launch filters. And I would leave it shown by default for test suites and test items since the filtering is used very often there if you have a lot of tests.
And padding around the filter criteria panel can be improved - it's too big.
![image](https://cloud.githubusercontent.com/assets/6681200/25448754/82993960-2a87-11e7-8a93-98059f5eac6d.png)

**Comment by DzmitryHumianiuk** [comment]
**done**
Verified in Chrome, FF, EDGE.
