### ISSUE TITLE
Automatically remove old build - Not working

### ISSUE THREAD

**Issue by deepak571** [reportportal/reportportal#1162]
**Describe the bug**
I have set up 'Keep launches' setting as 1 month, but older builds are not being deleted automatically. 

**Expected behavior**
As per documentation, all builds older than the specified duration should get deleted automatically

**Screenshots**
![image](https://user-images.githubusercontent.com/42932074/94450266-57445c80-01ad-11eb-8cb1-9d8a7b8bc881.png)

**Versions:**
 - OS, Browser : Linux, Chrome
 - Version of RP: Current version:API Service: 5.0.0;Index Service: 5.0.5;Authorization Service: 5.0.0;Service UI: 5.0.0;

**Comment by DzmitryHumianiuk** [comment]
fixed in 5.3.1
https://github.com/reportportal/reportportal/releases/tag/5.3.1
