### ISSUE TITLE
How to customize widgets in report portal based on attribute value

### ISSUE THREAD

**Issue by gopikishan1995** [reportportal/reportportal#1165]
How to create our own widgets or customize widgets in report portal.

**Comment by evjlobanova** [comment]
https://reportportal.io/docs/Component-health-check
https://reportportal.io/docs/Table-Component-health
https://reportportal.io/docs/Cumulative-trend-chart

**Comment by gopikishan1995** [comment]
What i mean is can we create own widgets based on our requirement.
Like apart from using above(report.io) widgets can we customize widgets by creating by our own.

**Comment by evjlobanova** [comment]
https://github.com/reportportal/reportportal/issues/610
