### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by tomern** [reportportal/reportportal#1168]
I'm running SpecFlow tests that send their logs to report portal by using ReportPortal.config.json file. 
The tests perform a REST request to another service (not related to report portal) which returns a valid response when I set the enabled property in ReportPortal.config.json to 'false'.
**Once it's set to 'true' I get the following SSL Exception:**

System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel. at System.Net.HttpWebRequest.GetResponse() 
at RestSharp.Http.GetRawResponse(HttpWebRequest request) at RestSharp.Http.GetResponse(HttpWebRequest request).

I've added the following code and now it works:

ServicePointManager.SercurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12
ServicePointManager.ServerCeritificateValidationCallback = delegate {return true;};

Why do I get the SSL/TLS error when setting the 'enabled' property to 'true' in ReportPortal.config.json?

**Versions:**
 - Windows
 - Version of RP Build 5.2.2

**Comment by nvborisenko** [comment]
When RP integration is enabled, it modifies `ServicePointManager.SercurityProtocol`: https://github.com/reportportal/client-net/blob/5ca060829e7e4ab9bc725fbfbad3a3fe142cb00b/src/ReportPortal.Client/Service.cs#L36 (adds TLS1.2 support explicitly).

Cannot understand how it affects your tests...

**Comment by tomern** [comment]
The tests send an API request to a service with TLS1.0.  So I guess it gets the TLS exception since you are overriding it with TLS1.2.
Are you adding TLS1.2 to all existing protocols or setting it as the only protocol?

**Comment by nvborisenko** [comment]
It adds TLS1.2 to existing protocols, in theory. And does it once.

**Comment by Cyberglamdring** [comment]
Older Windows systems (prior to version 10) use ssl ciphers that are not supported in TLS 1.2. Try adding these ciphers to your proxy or web server (for example [nginx](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_ciphers))

**Comment by nvborisenko** [comment]
This issue is not related to server configuration.

@tomern You are still using deprecated `HttpWebRequest` (RestSharp uses it). Try to upgrade RestSharp package where new `HttpClient` is involved in sending requests.
