### ISSUE TITLE
Externalize tokens 

### ISSUE THREAD

**Issue by tomassatka** [reportportal/reportportal#1169]
Would it be possible to persist the generated access tokens?

Problem is that if reporportal is used by multiple projects to report test executions all of unit test and cucumber properties has to hold token. But if pvc has hickup or few pods gets restarted these tokens are not valid anymore and they have to be redeployed to all projects again. 

IMHO after generating the token they can be passed to property file that would take priority on startup so once available it can be moved to values.yaml and propagated to configmap.

**Comment by evjlobanova** [comment]
@HardNorth @pbortnik @Yumfriez what do you think about this request?

**Comment by Yumfriez** [comment]
@tomassatka API tokens, that are displayed in the profile on UI are stored in the DB. So if there are no changes on the DB side these tokens will be valid. Do you use API token and if so could you plz provide a stack trace from the API pod with auth errors?

**Comment by tomassatka** [comment]
@Yumfriez in our use case multiple teams use single reportportal instance. Problem comes if pods get restarted due to some outage or if we decide to move this instance of reportportal to another location. So at the moment our app works fine and i cant provide you the stack trace. I am only proposing here in this issue the option to extract the tokens to be able to be able to restore them.

**Comment by tomassatka** [comment]
Basically this can be achieved when posgresql & elasticsearch data are dumped from current pvcs by rsync and then migrated into pvcs of new new deployment. Just tried out and this solution works

**Comment by MaryiaRymarchyk** [comment]
Hi @tomassatka, due to the fact you have found working solution , current ticket will be closed.
If you still have questions - contact us.
