### ISSUE TITLE
Access denied, Status code: 403

### ISSUE THREAD

**Issue by barakbottomline** [reportportal/reportportal#1173]
When running my project, in log:
`com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 403
Status message: Forbidden
Error Message: You do not have enough permissions.
Error Type: ACCESS_DENIED
`

I couldn't find why is happening

**Comment by evjlobanova** [comment]
Any steps for reproducing?
Version of ReportPortal?
Also if it possible please provide any available logs

**Comment by barakbottomline** [comment]
The rp.project was incorrect
