### ISSUE TITLE
Logs attachments imported by /v2/.../log API doesn't have correct name

### ISSUE THREAD

**Issue by kontownik** [reportportal/reportportal#1176]
**Describe the bug**
1. Create launch object
2. Import binary attachment to logs using `/api/v2/{projectName}/log`

Send POST to `/api/v2/default_personal/log`

with data:
json_request_part -> json.json
binary_part -> html-report.zip

Inside json.json:
`[{"file":{"name":"html-report.zip"},"level":"info","time":"2020-09-15T09:37:39.333Z","launchUuid":"45a1dfc3-6400-47f5-93c3-49fbd09d4dca","message":"html-report.zip"}]`

**Expected behaviour:**
Imported attachment name will match with value inside the request.

**Actual behaviour:**
Attachment is imported successfully.
I was thinking that attachment name (while downloaded) will match with `name` parameter send on the request. Instead attachment is named after it's UUID and what is worse, without original extension.

**Versions:**
 - Browser: Chrome Version 86.0.4240.75 (Official Build) (x86_64)
 - Report Portal hosted using docker, with default settings - Current version:API Service: 5.3.0;Index Service: 5.0.10;Authorization Service: 5.3.0;Service UI: 5.3.0;

Edit. I updated Report Portal lib to 5.0.5, based on changelog it should be fixed, but it isn't just changed a bit.
**Expected behaviour:**
Imported attachment name will match with value inside the request.

**Actual behaviour:**
Attachment is imported successfully.
I was thinking that attachment name (while downloaded) will match with `name` parameter send on the request. Instead attachment was `attachment_51049.form-data`, without original extension.

Logs:
```
[10:15:10] [INFO] [ReportPortalHelper.addAttachmentToLaunch] Adding 'html-report.zip' to launchUuid '4f2dbf90-0dbd-45e4-a735-a7d011228cf1'
[10:15:10] [INFO] [okhttp3.internal.platform.Platform log] --> POST http://reportportal.dummy:8080/api/v2/playground/log (1107347-byte body) 
[10:15:11] [INFO] [okhttp3.internal.platform.Platform log] <-- 201 Created http://reportportal.dummy:8080/api/v2/playground/log (686ms, 61-byte body) 
[10:15:11] [INFO] [CucumberExtentLibrary.services.ReportPortalService executeRequest] {"responses":[{"id":"b69cf438-afc0-4b4b-90a4-9c6d5dae9e0b"}]} 
[10:15:11] [INFO] [ReportPortalHelper.addAttachmentToLaunch] Attachment 'html-report.zip' successfully imported.
```

Same attachment visible at Report Portal UI
<img width="963" alt="Screenshot 2021-05-13 at 13 10 28" src="https://user-images.githubusercontent.com/3976951/118118104-c3966800-b3ec-11eb-8a98-e46e8df37017.png">

**Comment by kontownik** [comment]
When I tried using `emitLaunchLog()` from Report Portal lib `agent-java-cucumber6:5.0.0-RC-1` to upload the exact same file, it worked and extension was correct. 
Unfortunately in our flow attachment is created and uploaded after test execution so I cannot use this method.

Not sure if I need to use /v1/ API to send the attachments?

**Comment by kontownik** [comment]
Should I provide something for you to test and confirm the issue @evjlobanova ?

**Comment by kontownik** [comment]
Tested with there issue is still there, can I ask for retest @evjlobanova ? I think above scenario can be added to your regression test suite?

**Comment by HardNorth** [comment]
@kontownik It is relate to how Report Portal stores files, and it's actually "by design". Changing this behavior can cause either file name collision, when one file overrides another, either performance issues, because in this case we have to make additional query to database before file transfer. Either way it's not in priority right now.

**Comment by kontownik** [comment]
Ok, that's strange I thought the name parameter is meaningful, any solution can be better than just ignoring that fact, even creating a directory name after launch `45a1dfc3-6400-47f5-93c3-49fbd09d4dca` and then `html-report.zip` as a file.

**Comment by alena-babrova** [comment]
Hi @kontownik,
As commented above, attachments renaming is by design in sake of files consistency.
Also, I see, that in the latest version of Report Portal file extensions are preserved, so this issue seem to be resolved. Below is the example of how downloaded attachments look like:
![image](https://user-images.githubusercontent.com/89584140/201021990-c55314e3-3616-484b-9d0f-eb3264e02be2.png)
