### ISSUE TITLE
how to upgrade report portal version from lower to higher version

### ISSUE THREAD

**Issue by gopikishan1995** [reportportal/reportportal#1177]
![image](https://user-images.githubusercontent.com/60506449/95829278-ac5aa380-0d53-11eb-865d-f883d2e6382e.png)
 now i am using Build 5.2.0 version i want to use latest report portal version, how to do it.

**Comment by gopikishan1995** [comment]
<repositories>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>bintray-epam-reportportal</id>
			<name>bintray</name>
			<url>http://dl.bintray.com/epam/reportportal</url>
		</repository>
<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>logger-java-log4j</artifactId>
			<version>5.0.3</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-testng</artifactId>
			<version>5.0.7</version>
			<scope>compile</scope>
		</dependency>


i am using the above dependencies

**Comment by evjlobanova** [comment]
https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.5.3
