### ISSUE TITLE
When having many filters, after setting filter in widget, filter is not found [v5.2.2]

### ISSUE THREAD

**Issue by bearclawz** [reportportal/reportportal#1178]
I started noticing widgets were not showing accurate data, then on inspecting the widget shows 'Filter not found'
When adding same filter, same thing happens

After trying many times, I found filters with names lower in alphabet do not have this issue
so filter with name 'A filter' is stable and 'Z filter' not. 
Workaround was to rename important filters I need for the dashboard starting with A_

So I suppose this is a problem when having many filters
Using launch name, description, attribute keys and values in the filters

Filter example:
![Screenshot 2020-10-13 at 12 27 28](https://user-images.githubusercontent.com/32574874/95849526-e164f700-0d4f-11eb-8cd9-0a624fb6175f.png)

I also noticed using _not contains_ in description of filters tends to reset back to _contains_, so this is not usable, but thats a different issue

We have a shared Report Portal server for several projects

Thanks,
Kevin

**Comment by evjlobanova** [comment]
Which version of ReportPortal.io do you use?

**Comment by bearclawz** [comment]
> Which version of ReportPortal.io do you use?

Hi, its still on version 5.2.2

**Comment by evjlobanova** [comment]
Please update to the latest version
We have fixed a bug with "Filter not found"
Please let us know about the results and reopen the issue if it is still valid
