### ISSUE TITLE
No history of test-items with defect

### ISSUE THREAD

**Issue by odubaj** [reportportal/reportportal#1184]
**Describe the bug**
I am unable to display history of test-items with selected issues after clicking on chart from testsuite page. If i click on chart on launches page, I am able to display the history.

**Expected behavior**
I should be able to display the history of test-items anytime

![step3](https://user-images.githubusercontent.com/44674278/96596294-d8929900-12ec-11eb-9851-c6e40f6795b4.png)
![step2](https://user-images.githubusercontent.com/44674278/96596296-d9c3c600-12ec-11eb-8e39-6f0da7ee66d8.png)
![step1](https://user-images.githubusercontent.com/44674278/96596301-da5c5c80-12ec-11eb-997e-9601bf6fa433.png)

**Comment by evjlobanova** [comment]
@svettsova could you please add this bug to our Jira

**Comment by evjlobanova** [comment]
@odubaj thank you for sharing this, we will fix this

**Comment by svettsova** [comment]
Jira ticket is created

**Comment by odubaj** [comment]
thanks!

**Comment by svettsova** [comment]
Fixed in v.5.3.3

**Comment by odubaj** [comment]
Hello, can you please point to a commit/commits which are fixing the issue, so I can backport it ? thanks.

**Comment by Yumfriez** [comment]
https://github.com/reportportal/service-api/pull/1313

**Comment by odubaj** [comment]
Thanks a lot!
