### ISSUE TITLE
Arrays support in test parameters

### ISSUE THREAD

**Issue by kshirunov** [reportportal/reportportal#119]
If we pass an array as a test parameter we got a generic string with missing trailing bracket like:
Method Type / Name / [test params]
Test / testName / [  [Ljava.lang.String;@36d2ea  ]

It would be useful to resolve arrays, something like:
param instanceof Object[] ? Arrays.toString((Object[]) param) : param.toString();

**Comment by avarabyeu** [comment]
@kshirunov agent type? version? Could you please provide some example to be able to reproduce?

**Comment by kshirunov** [comment]
<dependency>
     		<groupId>com.epam.reportportal</groupId>
     		<artifactId>agent-java-testng</artifactId>
     		<version>2.7.0</version>
  		</dependency>
  		<dependency>
     		<groupId>com.epam.reportportal</groupId>
     		<artifactId>logger-java-logback</artifactId>
     		<version>2.6.0</version>
  		</dependency>
  		<dependency>
     		<groupId>com.epam.reportportal</groupId>
     		<artifactId>logger-java-log4j</artifactId>
     		<version>2.6.1</version>
  		</dependency>

	@Test (dataProvider="addCommentString")
	public void addComment(String[]comments){}

	@DataProvider(name = "addCommentString")
	public Object[][] addCommentInput() {
		 return new Object[][] {
		           { new String[]{"Test 1 ","Test 2"} },
		           { new String[]{"Comment ", "Testing"} },
		        };
	}

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu @pictureb00k

**Comment by avarabyeu** [comment]
starting from 4x, test parameters are being reported as separate structure (like key->value)
