### ISSUE TITLE
Sending Log Message

### ISSUE THREAD

**Issue by vrakr19** [reportportal/reportportal#1197]
Hello,

Is there any way, we can send log message to ReportPortal from custom listener?
Logging is done by log4j.

Thanks

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/documentation/tree/master/src/md/src/DevGuides >
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md >
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#save-single-log-without-attachment
