### ISSUE TITLE
Issue with adding new widget to dashboard [v5]

### ISSUE THREAD

**Issue by dkdk91** [reportportal/reportportal#1199]
**Describe the bug**
Created new dashboard in report portal. When trying to add a new widget to the dashboard I get an error message:

`Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "undefined"`

I currently have 55 dashboards in report portal
with 56 filters.

Is there a limitation on how many dashboards and filter one can have?

**To Reproduce**
Create a new dashboard and then try adding a widget to the dashboard will throw this error message

**Expected behavior**
Should be able to add any widget to the dashboard without error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 86.0.4240.111

**Comment by gadesharath** [comment]
We are also facing same issue in report portal, when trying add a new widget to the dashboard.

**Comment by evjlobanova** [comment]
Could you please tell us version of RP that you are using?
@VolhaKarenko @svettsova please review this issue

**Comment by dkdk91** [comment]
> Could you please tell us version of RP that you are using?
> @VolhaKarenko @svettsova please review this issue

Current version:
API Service: 5.3.2;
Index Service: 5.0.10;
Authorization Service: 5.3.2;
Service UI: 5.3.2;

**Comment by VolhaKarenko** [comment]
@dkdk91 Could you please give more detailed steps to reproduce?
specify the widget type and filter conditions, if any filter is used for widget creation

**Comment by VolhaKarenko** [comment]
Managed to reproduce the issue. The amount of dashboards could be a possible reason, though we don't have any limitations.
A bug is added to backlog

**Comment by evjlobanova** [comment]
@dkdk91 @gadesharath could you please tell us how many dashboards you are planning to create? I want to collect all details in order to discuss them with the team?

**Comment by dkdk91** [comment]
> @dkdk91 @gadesharath could you please tell us how many dashboards you are planning to create? I want to collect all details in order to discuss them with the team?

More applications are going to be added for different environments, we are planning to be around 60-70 dashboards in total. As mentioned by @VolhaKarenko there shouldn't be any limitations.

**Comment by evjlobanova** [comment]
Thank you for your information. It is vey helpful!

No exactly 
We discus with a team, and define why this limitation appeared.
And after that find the best solution

**Comment by dkdk91** [comment]
> Thank you for your information. It is vey helpful!
> 
> No exactly
> We discus with a team, and define why this limitation appeared.
> And after that find the best solution

Great looking forward to your positive feedback on the solution. Thanks!

**Comment by dkdk91** [comment]
@evjlobanova @VolhaKarenko - any updates from the team regarding this issues?
We are not able to create new dashboards because of this issue. It's a show-stopper for us currently.
Looking forward to your resolution.

**Comment by dkdk91** [comment]
BUMP...
@evjlobanova @VolhaKarenko - any updates from the team regarding this issues?

**Comment by VolhaKarenko** [comment]
@dkdk91 sorry for the late reply
The team is now busy with other tasks, the backlog is overloaded
Fix for this issue is planned for version 5.4 in February

**Comment by dkdk91** [comment]
@VolhaKarenko - Thank you for that information. Looking forward to the release.

**Comment by KatsiarynaTatarynovich** [comment]
Hi @dkdk91. We have increased the limit on the UI side to 300 dashboards (the same limitation (300) is also on the Backend side). Discussions are underway to add pagination for dashboards to remove this 300 dashboard limit.

**Comment by gadesharath** [comment]
@KatsiarynaTatarynovich  - Thanks for the fix! To which version we should upgrade to get this functionality.

**Comment by KatsiarynaTatarynovich** [comment]
@gadesharath - As Volha said the fix for this issue is planned for version 5.4 in February

**Comment by jmodi1982** [comment]
@KatsiarynaTatarynovich - Do we have any updates on v5.4 ? I don't think it is available yet for download

**Comment by MaryiaRymarchyk** [comment]
Hello @dkdk91 , @jmodi1982 the fix already in live, so the ticket will be closed.
However if you have any questions or support is needed - feel free to contact us.
