### ISSUE TITLE
LDAP authorization

### ISSUE THREAD

**Issue by fasterfish** [reportportal/reportportal#12]
Good day!

Could you add feature as a user authorization by AD domain by using ldap?

**Comment by avarabyeu** [comment]
@fasterfish  It's actually possible, but usually such kind of auth requires lots of modifications for each particular ldap server (for example: grabbing DNs, password validation). 
We will put it in the backlog, but we start working on it in nearest future. 
You can try to add it by yourself adding modifications to authorization-server, truth be said, it should be faster :)
Thanks for the issue!

**Comment by avarabyeu** [comment]
@fasterfish Implementation in progress. Just curious, do you need LDAP or Active Directory authentication. AD is like special case of LDAP, but they have a little bit different mechanics of authentication.

**Comment by fasterfish** [comment]
@avarabyeu we need Active Directory authentication

**Comment by DzmitryHumianiuk** [comment]
Completed
