### ISSUE TITLE
Not able to login to online demo portal. 

### ISSUE THREAD

**Issue by aditidubey05** [reportportal/reportportal#1202]
When trying to login with "default" "1q2w3e" bad credential error is coming.

**Comment by ItachGal** [comment]
Hi, there are several related issues, more details are welcome but please check the following:
https://github.com/reportportal/reportportal/issues/917
https://github.com/reportportal/reportportal/issues/617
And update :)

**Comment by evjlobanova** [comment]
https://reportportal.io/
![image](https://user-images.githubusercontent.com/30413511/98941113-f0e77500-24a0-11eb-9154-2ff098fde452.png)
![image](https://user-images.githubusercontent.com/30413511/98941182-08bef900-24a1-11eb-9e86-35711f52dca7.png)
![image](https://user-images.githubusercontent.com/30413511/98941199-107e9d80-24a1-11eb-9e4f-ecffc3644d13.png)

Please try one more time

**Comment by Dmitry-Ostashev** [comment]
Hello,

I've encountered the same problem when just trying to open: 

 ![image](https://user-images.githubusercontent.com/24777868/140926850-7f107934-9f05-46b1-b491-8867967b9333.png)

**Comment by HardNorth** [comment]
@Dmitry-Ostashev Default logins is not available now, please use "Login with github" button
