### ISSUE TITLE
get API token of user logged in via github

### ISSUE THREAD

**Issue by odubaj** [reportportal/reportportal#1203]
Hello,

is it please possible to get a UI_TOKEN and API_TOKEN of a user logged via github.com account ? I used the example available here [1] but with no success.

Thanks!

[1] https://github.com/ihar-kahadouski/dev-guide/blob/master/bash-example/auth_client.sh

**Comment by MaryiaRymarchyk** [comment]
Hi @odubaj, sorry for the silence. Unfortunately it is not possible to  get a token for github user in current RP versions. However we are going to introduce new feature in next release with API Keys (approximately end of the June 2023). With this feature each user will be able to generate API Tokens from his profile so you will be able to get the token.

**Comment by MaryiaRymarchyk** [comment]
Hi @odubaj  with latest versions you can use API Keys, create them from user profile.
Current ticket will be closed, feel free to reopen or create a new issue.
