### ISSUE TITLE
Attach excel file to Report Portal

### ISSUE THREAD

**Issue by BraveLittleTapok** [reportportal/reportportal#1204]
Hi everyone! Maybe anyone know how to attach excel file to report portal, I do the same as for screenshots and it works. Screenshots are present in my report in RP. But excel file doesn't. Do I need some extra properties maybe? Or dependencies?
Code:
```java
            ReportPortalMessage message = new ReportPortalMessage(excelService.getDownloadedExcelFile(),
                    "Downloaded Excel File");
            ReportPortal.emitLog(message, "info", new Date());
```
So again:  exactly the same works for screenshots. Only first parameter changing to screenshot file. And screenshots appears at RP, but not excel file.

**Comment by DzmitryHumianiuk** [comment]
@BraveLittleTapok it should be the same.
unless any specific MIME type should be mentioned.

What are your agent/dependencies versions?

**Comment by BraveLittleTapok** [comment]
Yes, thanks it's working now)
