### ISSUE TITLE
Is it possible to uploud test results (manually) via REST API?

### ISSUE THREAD

**Issue by wlad** [reportportal/reportportal#1206]
Instead of sending test results live during each mvn build is it possible to send the results (.xml files) to RP via REST API at the end of a build on a CI pipeline?

**Comment by wlad** [comment]
Just noticed that I actually wanted to files this issue in [agent-java-junit5](https://github.com/reportportal/agent-java-junit5/issues). But it may be interesting for other frameworks as well I guess.

**Comment by DzmitryHumianiuk** [comment]
@wlad there is an 'import' functionality.
it can eat xunit standard results.
Thus you can make an API call at the end of execution and upload results.

**Comment by wlad** [comment]
@DzmitryHumianiuk  thanks for the hint 👍
That was exactly what I looked for :)



NOTE: requires junit conform .xml output. Default Robot Framework output.xml is not supported directly but can be transformed into a junit conform file with Robot's **rebot** tool. It seems to flatten the test suite structure, though.
