### ISSUE TITLE
[v5] Log attachments being attached to the wrong test function with Pytest 

### ISSUE THREAD

**Issue by allan-silverstein** [reportportal/reportportal#1209]
This something that has been happening to me for a while when initiating the tests from a particular system.  In this case, I have 17 test functions spread across 8 modules.  I'm running them using the pytest markers flag (-m <pattern>).  After each test function runs, the following code is called to send detailed log files to report portal:

```
def attach_session_logs(testinfo,rp_logger):
    for dev in testinfo['log_files']: # loop through session log file names
        dirpath = os.getcwd()

        # get log file in current working directory
        log_dir = Path(dirpath,testinfo['log_files'][dev]) 

        # open log file and send contents as an attachment to reportportal
        with open(log_dir) as file: 
            contents = file.read()
            rp_logger.info("Session Log Attachment - " + testinfo['log_files'][dev],
                                     attachment={"name": testinfo['log_files'][dev],
                                    "data": contents, "mime": "text/plain"})
```

After some troubleshooting between initiating the pytest test between two different systems.  I noticed it only happens on the system with specific versions of reportportal-client.  

When the versions are this, everything works fine:
pytest-reportportal==5.0.3
reportportal-client==5.0.3

Anything newer and the problem happens:
I've tried with this:
pytest-reportportal==5.0.6
reportportal-client==5.0.6
and this:
pytest-reportportal==5.0.3
reportportal-client==5.0.5
and probably a few other combinations.

Before troubleshooting the pytest modules I upgraded reportportal from 5.2.2 to the lateset 5.3.2 (what I'm running now) but that had no effect.

**Expected behavior**
Each test function result should have its own log files in ReportPortal as such:

![image](https://user-images.githubusercontent.com/18428970/99468109-d7fe1a00-290d-11eb-86c6-8b359aac8a75.png)

Report Portal is running with Docker Compose on ubuntu 16.0.4

**Comment by evjlobanova** [comment]
@iivanou does this issue relate to python agents? or problem is on the back end side?

**Comment by allan-silverstein** [comment]
Honestly, not sure.  Based on my notes, what is your opinion?
Thx

**Comment by allan-silverstein** [comment]
You may be correct.  I posted this question on pytest reportportal plugin.  If I get some activity there, I will close this out.  Thx

**Comment by DzmitryHumianiuk** [comment]
it might be issue on python-client side.
don't see any reason to be misled on server side.

**Comment by MaryiaRymarchyk** [comment]
Hi @allan-silverstein did you solve the issue? can we close the ticket?

**Comment by DzmitryHumianiuk** [comment]
@MaryiaRymarchyk after 3 years :) probably yes.
