### ISSUE TITLE
How to modify the hyperlink in ReportPortal generated email

### ISSUE THREAD

**Issue by allan-silverstein** [reportportal/reportportal#1210]
I'm using ReportPortal 5.3.2.  I have it configured such that an email is sent to users after a test completes. The problem is the reportportal IP address is behind a Firewall and uses a private IP address (e.g. 10.x.x.x).  The hyperlink in the email references that private IP address.  However, the users are actually located in a different part of the network and traffic is "natted" when users access Reportportal.   When users click on the link, that "private" ip address is unreachable.   How can I get ReportPortal to configure the email hyperlink so it references the "public" IP address?

**Comment by DzmitryHumianiuk** [comment]
@allan-silverstein 
**Resolution:** add field in e-mail configuration with server address, which should be used in emailed report.
it can resolve:
- http/https issue (in case if ssl configured on load-balancer)
- custom port for web-ui
- api server hidden behind firewall

**Comment by allan-silverstein** [comment]
Thank you for the response.  Any ETA on this enhancement.
Thx
Al

**Comment by evjlobanova** [comment]
Most likely this fix will be available in version 5.4 (the end of January)

**Comment by evjlobanova** [comment]
![image](https://user-images.githubusercontent.com/30413511/101609909-610fea80-39bc-11eb-8145-4c55e3b4ab52.png)

**Comment by ntthaibk** [comment]
sorry, how could I put the server address into email config?

**Comment by alena-babrova** [comment]
Hello @ntthaibk 

1. You can create new email integration and it will use current server address for links in RP emails
2. If you want to change the existing email integration, you need to update "rpHost" field as described above
