### ISSUE TITLE
clean-up project in rp

### ISSUE THREAD

**Issue by nagaeva-anastasia** [reportportal/reportportal#1211]
I found that auto-deletion of old launches does not work. For now, I have about 1500 launches and it causes really slow work for RP. I upgraded RP to the latest versions (to fix bug with auto-deletion). But I can't delete old launches manually because it takes a while. For example, deletion of one launch takes about 2 hours. Please, advise something. Maybe I can delete it on DB level? 

My goal is to clean up old launches and keep only 100 latest.

Current version:API Service: 5.3.2;Index Service: 5.0.10;Authorization Service: 5.3.2;Service UI: 5.3.2;

**Comment by DzmitryHumianiuk** [comment]
@nagaeva-anastasia 2 hours to delete a launch that's incredibly low performance. Which is abnormal.
1500 launches in not a problem for ReportPortal at all. It works at scale of millions of launches.

You should check performance of database.
Do you keep database and application on separate VMs/nodes?
if yes, then check memory and CPU usage. Increase of required.

**Comment by evjlobanova** [comment]
@nagaeva-anastasia https://reportportal.io/docs/Optimal-Performance-Hardware please check our requirements to the instance. 
If your instance is different from our requirements, please let us know what point it is different in.

**Comment by nagaeva-anastasia** [comment]
we have HDD and service / db on one vm
working on resolving this, thanks!

one more question about auto-deletion schedule. for example, I changed it yesterday and set 14 days. when it will delete old launches? will it delete launches created last year?

**Comment by DzmitryHumianiuk** [comment]
ReportPortal uses scheduled jobs to clean the data, which exceeded selected period above.
Jobs are triggered once in:
* 3 days for binary attachments (minio)
* 7 days for logs
* 14 days for launches (launch, test_item, test_item_results tables)

Jobs works based on formula _(NOW - time_of_creation > SELECTED_PERIOD_TO_KEEP_DATA)_
thus it will delete everything what is older then selected _14 days_

Jobs schedule can also be configured as env variables for API container.

**Comment by nagaeva-anastasia** [comment]
our devops engineer spent some time on postgresql investigation and analysis
he adds several indexes to the tables 

public.log 
public.test_item 
public.parameter 
public.statistics 
public.test_item 
public.item_attribute 

before this optimization delete of one launch takes 46 minutes, after this it takes only 0.015 seconds
so, now everything works fast.
