### ISSUE TITLE
[v5]

### ISSUE THREAD

**Issue by sdblepas** [reportportal/reportportal#1214]
**Describe the bug**
After upgrade from V4 to V5 (5.3.3) the total numbers are not displayed. Only the "To investigatre are diplayed

**To Reproduce**
simple upgrade i guess

**Expected behavior**
I should see all th edetails 
**Screenshots**
![image](https://user-images.githubusercontent.com/6726241/99949916-7e21a800-2d84-11eb-9716-41cb023a641d.png)

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Browser Chrome and Firefox
 - Versionlatest

**Additional context**

**Comment by DzmitryHumianiuk** [comment]
@sdblepas 
https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.5.3.2

**Comment by sdblepas** [comment]
Hi 
There's a misunderstanding here, i did not do a migration. 
I had a docker on V4 and now a new one on V5. In V5 i recreated the filters and then run my tests via Jenkins as usual.
I see the tests in V5 and I see the issues "TO investigate" but not the Total/passed/Skipped, these I could see in V4.
I hope this is more clear now
Thank you for the help
