### ISSUE TITLE
ActiveDirectory integration supports only userPrincipalName but not samaccountname

### ISSUE THREAD

**Issue by AndriiFrolov** [reportportal/reportportal#1215]
**Describe the bug**
Can't integrate Report Portal with active directory using samaccountname. Logs:
`Searching for entry under DN '', base = 'dc=mydc1,dc=mydc2', filter = '(&(objectClass=user)(userPrincipalName={0}))' `

**Expected behavior**
Active directory plugin can be integrated both with samaccountname and userPrincipalName

**Screenshots**
N/A

**Versions:**
 - API Service: 5.3.2;Index Service: 5.0.10;Authorization Service: 5.3.2;Service UI: 5.3.2;

**Comment by alena-babrova** [comment]
Really??
I am so sorry for the confusion. Just processing the out-dated issues...

Thank you for your contribution!

**Comment by AndriiFrolov** [comment]
@alena-babrova  yes, I found jira task EPMRPP-57883 in old conversation with Ilya Nazarov and Ivan Budayeu

**Comment by alena-babrova** [comment]
Dear @AndriiFrolov,
Yes, now I see. Thank you so much for your help!
