### ISSUE TITLE
Defect type abbreviation not used in API layer

### ISSUE THREAD

**Issue by AndriiFrolov** [reportportal/reportportal#1216]
Can't post custom defect resolution using API request.

Steps to reproduce:
1. Go to Settings -> Defect types
2. Click 'Add Defect type'
3. Add custom defect type, e.g. 'Question raised' with abbreviation QUE

**Expected behavior**
The same abbreviation is used in API

Actual: 
Auto-generated abbreviation is used, e.g. pb_1ji4fwgclss39 

**Versions:**
 - API Service: 5.3.2;Index Service: 5.0.10;Authorization Service: 5.3.2;Service UI: 5.3.2;

**Comment by VolhaKarenko** [comment]
@AndriiFrolov 
Hello,
It seems that auto-generated value is locator, not abbreviation. The abbreviation is displayed in "shortName". 
When posting defect type, use locator value in "issueType" field.
![image](https://user-images.githubusercontent.com/42797492/100605562-27364880-3319-11eb-9e80-a45ae7967e96.png)
