### ISSUE TITLE
Attachment dialog doesn't show pdf attachments

### ISSUE THREAD

**Issue by aliaksandrbasau** [reportportal/reportportal#122]
Even though the pdf attachment has correct mime type, attachment dialog shows it as a text file.
![image](https://cloud.githubusercontent.com/assets/6681200/25662007/dd6bae5a-2fe0-11e7-9588-c8c985fcf376.png)

**Comment by avarabyeu** [comment]
@aliaksandrbasau which agent do you use? could you please share response from /log/{id} resource  to make sure it has correct mime type value

**Comment by aliaksandrbasau** [comment]
@avarabyeu we use custom version of agent-net-specflow.
![image](https://cloud.githubusercontent.com/assets/6681200/25773751/37dabcc4-3251-11e7-9127-08ad35f6a7db.png)

**Comment by lexecon** [comment]
will be fixed on 3.0.2
