### ISSUE TITLE
[v5] 'Failed to update defects' but defects is updated after 5-10 min

### ISSUE THREAD

**Issue by AndreiValnianka** [reportportal/reportportal#1221]
**Describe the bug**

Sometimes when I try to update a defect type manually 'item' call failed with 504 Status Code

![ice_screenshot_20201126-100424](https://user-images.githubusercontent.com/37652976/100318246-c8966500-2fce-11eb-9615-fd8c4d5cb5bc.png)

 and 'Failed to update defects' red message displays
But defect type is updated after 5-10 min

![ice_screenshot_20201126-100518](https://user-images.githubusercontent.com/37652976/100318335-e9f75100-2fce-11eb-94f1-22b912cabb80.png)

API Service: 5.3.2;Index Service: 5.0.10;Authorization Service: 5.3.2;Service UI: 5.3.2;

**Comment by evjlobanova** [comment]
Could you please check youк instance set up and compare with our requirements?
If you find any difference please let us know

**Comment by AndreiValnianka** [comment]
analyzer
    Limits:
      cpu:     100m
      memory:  512Mi

api
    Limits:
      cpu:     1
      memory:  2Gi 

index
    Limits:
      cpu:     200m
      memory:  256Mi 

uat
    Limits:
      cpu:     500m
      memory:  2Gi 

ui
    Limits:
      cpu:     200m
      memory:  128Mi

**Comment by AndreiValnianka** [comment]
And no one achieves the maximum

**Comment by evjlobanova** [comment]
https://reportportal.io/docs/Optimal-Performance-Hardware

**Comment by AndreiValnianka** [comment]
All settings corresponding to the required

**Comment by evjlobanova** [comment]
+ Data Base is Aurora db (is filled on 21%)

@irynakozak2 please check this issue and info that have been provided

**Comment by irynakozak2** [comment]
@AndreiValnianka hello, we've already checked the issue from the ReportPortal side and didn't reproduce(checked on the steps with Jira ticket and without) - the response time is pretty fast and takes up to 102ms on similar with your service limits.
The root problem may be with service-analyzer, so could you please send me some logs during updating defect type?

**Comment by irynakozak2** [comment]
https://github.com/reportportal/reportportal/issues/1222#issuecomment-759511646
