### ISSUE TITLE
[v5] Auto-analysis doesn't work

### ISSUE THREAD

**Issue by AndreiValnianka** [reportportal/reportportal#1222]
**Describe the bug**
Auto-analysis doesn't find the bug
Suspect that this issue and '[v5] 'Failed to update defects' but defects are updated after 5-10 min' are related

**To Reproduce**
1. Set up auto-analysis
![ice_screenshot_20201126-170320](https://user-images.githubusercontent.com/37652976/100359946-5000ca00-3009-11eb-9a9b-3fade193a10c.png)
2. Launch test with the failed method 10 times
3. Mark this fail in 10 launches as a 'product bug' and link Jira ticket (all fails have the same stack trace)
![ice_screenshot_20201126-170455](https://user-images.githubusercontent.com/37652976/100360087-88a0a380-3009-11eb-96f2-225501197aaa.png)
4. Launch test with the failed method again

**Expected behavior**
Auto-analysis starts automatically after launch ending and marks fail

**Actual behavior**
nothing

4. Launch auto-analysis manually
![ice_screenshot_20201126-101027](https://user-images.githubusercontent.com/37652976/100360354-e46b2c80-3009-11eb-99c0-2f47821f25af.png)

**Expected behavior**
Auto-analysis starts and marks fail

**Actual behavior**
![ice_screenshot_20201126-101641](https://user-images.githubusercontent.com/37652976/100360486-0e245380-300a-11eb-8464-6906723e9d58.png)
200 Status Code on 'analyze' call
'Auto-analysis' blinks constantly, nothing was marked

API Service: 5.3.2;Index Service: 5.0.10;Authorization Service: 5.3.2;Service UI: 5.3.2;

**Comment by evjlobanova** [comment]
@AndreiValnianka please answer on questions #1221

**Comment by irynakozak2** [comment]
That issue was resolved by revising deployment issues and missed permissions to ElasticSearch for service-analyser. If logs "ERROR: ES Url "<your_es_url>" appears in the service-analyzer container, firstly, please review necessary permissions and follow these suggestion to figure out the root cause of the issue.
