### ISSUE TITLE
[v5] Data retention does not work very well

### ISSUE THREAD

**Issue by coufalja** [reportportal/reportportal#1223]
**Describe the bug**
The data retention does not work very well.
- ~You cannot set unlimited retention via UI (API complains that 0 is unsupported value)~
- Dubious default values
  - in the `application.yaml` sets the initial delay of all Cleanup jobs to 7Days, that in practice means that the process has to survive 7D in order to launch the job. The counter is reset each time the process is restarted which in a dynamic environment like K8s could mean *never* in practice.
  - Another weird default setting is that the period is set to 7 and 14D respectively. Cleaning up launches once 14 days could mean you need to go through thousands of launches.
- Together with another issue where the whole <Whatever>CleanupJob run is run in a single large transaction e.g. `com.epam.ta.reportportal.job.service.impl.LaunchCleanerServiceImpl#cleanOutdatedLaunches` leads to the situation when the cleanup could take days generating tons of temporary data in the Postgres (due to being in a single large transaction and Postgres having to create duplicates to ensure transaction isolation)

**To Reproduce**

**Expected behaviour**
* ~Unlimited retention could be set~ (fixed in v5.3.3)
* Sane default values built-in
* Not using single huge transactions to cleanup all launches etc... at once so there is a chance to finish the Job

**Additional context**
* We run reportportal in K8s v5.3.2

**Comment by evjlobanova** [comment]
Hello @coufalja 
We have a possibility on UI to choose Forever value 
![image](https://user-images.githubusercontent.com/30413511/100480115-2d23f380-30a5-11eb-8b4a-a1c408100fdc.png)

Could you please send us a screenshot with your General setting configurations?

**Comment by coufalja** [comment]
I know but that is what my first point is about it cannot be set as it fails on API validation.
Original settings:
![Screenshot 2020-11-30 at 9 22 03](https://user-images.githubusercontent.com/23357992/100585345-b75e9880-32ed-11eb-9826-4d0bf953b2c2.png)
Switch to:
![Screenshot 2020-11-30 at 9 22 13](https://user-images.githubusercontent.com/23357992/100585365-c04f6a00-32ed-11eb-9aa0-208686d8935c.png)
Fails with:
![Screenshot 2020-11-30 at 9 22 59](https://user-images.githubusercontent.com/23357992/100585378-c6dde180-32ed-11eb-8882-44edc812943c.png)

**Comment by evjlobanova** [comment]
@svettsova Valya, could you please check this issue?

**Comment by svettsova** [comment]
@coufalja please upgrade your RP to 5.3.3 version. The issue was fixed

**Comment by coufalja** [comment]
Hello @svettsova It wasn't, the API bug yes but the rest of the issue (which is way more important) was not. I will rephrase the issue and remove the notice about the API call If you won't mind reopening the issue or should I create a new one?
