### ISSUE TITLE
[v5] Defect comment is overlapped by scrollWrapper in UI with zoom less than 100%

### ISSUE THREAD

**Issue by Shakevg** [reportportal/reportportal#1228]
**Describe the bug**
Defect comment is overlapped by scrollWrapper in UI with zoom less than 100%

**To Reproduce**
Precondition: set Chrome browser zoom 90% (if 1 line comment), 80% (if 2 lines comment)
Reproduced on https://reportportal.epam.com/
1. Open test run and add defect comment
=> Defect comment is overlapped by scrollWrapper in UI
2. Open a specific launch with the test run, move the cursor to any test
=> Defect comment is overlapped by scrollWrapper in UI

**Screenshots**
![image](https://user-images.githubusercontent.com/42133199/100583096-5211a400-32fb-11eb-9053-580bc958eb25.png)
![image](https://user-images.githubusercontent.com/42133199/100583182-66ee3780-32fb-11eb-9792-be70a9ba3cc0.png)

**Desktop (please complete the following information):**
 - OS: window 10
 - Browser: chrome
 - Version: 87
- Screen Resolution: 1920x1200

**Comment by evjlobanova** [comment]
Could you please specify versions of all services?

**Comment by Shakevg** [comment]
Sorry, the Issue reproduced only with browser zoom less than 100%
Reproduced on https://reportportal.epam.com/
Version: API Service: 5.3.3; Index Service: 5.0.10; Authorizsation Service: 5.3.3; Service UI: 5.3.3

**Comment by VolhaKarenko** [comment]
Can't reproduce the issue with provided details. @Shakevg could you please specify your screen resolution?

**Comment by Shakevg** [comment]
Updated original message:
- Screen Resolution: 1920x1200
Precondition: set Chrome browser zoom 90% (if 1 line comment), 80% (if 2 lines comment)

**Comment by VolhaKarenko** [comment]
Issue is added to backlog

**Comment by KatsiarynaTatarynovich** [comment]
Hi @Shakevg 
Unfortunately, we have no way to fix it on our side, as this issue connects with react-custom-scrollbars https://github.com/malte-wessel/react-custom-scrollbars/issues/210

**Comment by Shakevg** [comment]
OK, let's close for now until react fix will be released
