### ISSUE TITLE
Uncaught Error parsing bindings

### ISSUE THREAD

**Issue by iKozzz** [reportportal/reportportal#123]
If stacktrace contains:
`ElementShould: Element should be visible {.paymentCarrierTipCheck}
Element: '<div class="class" data-bind="click: TipClick, css: HasTip() ? 'Checked' : 'UnChecked' " displayed:false></div>'`

It will break Test Case Log for Report Portal with error:

`Uncaught Error parsing bindings: "click: TipClick, css: HasTip() ? 'Checked' : 'UnChecked' " ReferenceError: TipClick is not defined`

**Comment by DzmitryHumianiuk** [comment]
fixed.
available in 3.0.2 `service-ui`
