### ISSUE TITLE
[v5] Component health check widget levels issue

### ISSUE THREAD

**Issue by egilsdq** [reportportal/reportportal#1230]
**Description**
Added attribute key to suite not working in component health check widget.

**To Reproduce**
Add attribute to suite. Add component health check widget to some dashboard. Add level with added attribute key.

**Expected behavior**
Suites with added attribute key are displayed.

**Screenshots**
Suite:
![image](https://user-images.githubusercontent.com/15646224/100591463-7a4ed200-32fe-11eb-8ad7-7dbed28dabd3.png)

Test:
![image](https://user-images.githubusercontent.com/15646224/100591475-8044b300-32fe-11eb-82c8-8c2653f4b406.png)

Dashboard with widgets:
![image](https://user-images.githubusercontent.com/15646224/100591515-8cc90b80-32fe-11eb-83ea-94dcff594603.png)

**Desktop:**
 - OS: Windows 10 Enterprise
 - Browser: chrome
 - Version; 86.0.4240.198

**Comment by evjlobanova** [comment]
Works as expected.
Because of performance, we are using only attributes for launches and execution.
Just report your execution with this attribute.

For now, we do not plan to change this logic
