### ISSUE TITLE
Api/client to send junit xml report

### ISSUE THREAD

**Issue by Whiletru3** [reportportal/reportportal#1232]
Hello,

I developped my own AutomationUI test scenarios (in c#) without a test framework (but using a console application) and I output a junit xml format out of it.
Is there any available client (best in C# but could be another language) to directly send junit xml report to RP ?

Thanks

**Comment by bzsharm** [comment]
You can zip that xml file and Upload it to RP using upload option, it ll be
directly updated, if there is any issue, you might have to add / remove a
"T" From the time stamp,

End time for test should be available in the xml.

**Comment by Whiletru3** [comment]
I would like to do it automatically, not manually (and also add some key/values).

**Comment by nvborisenko** [comment]
https://github.com/reportportal/client-net - api client for C#, importing launch is not added there yet. But there is api endpoint `/v1/{projectName}/launch/import`.

**Comment by MaryiaRymarchyk** [comment]
Hi @Whiletru3, as it mentioned above, import of xml  can be done via api endpoint /v1/{projectName}/launch/import.
In 5.7.5 release import of xml will be possible from UI also, but now only zip format is supported.
I'll close ticket as there no remain actions/ open questions. In case you have something to ask, clarify - feel free to reopen and comment.
