### ISSUE TITLE
Offer: Manual Tests status

### ISSUE THREAD

**Issue by odubaj** [reportportal/reportportal#1235]
Hello,

recently I have implemented manual test status into ReportPortal-5.2.2. Would you be interested in such a feature ? I can provide you a patch and we can discuss together how we can improve it. Adding some screenshots as well

I've also implemented some other features regarding to history displaying, filtering (filtering by launches and by items at the same time), so if you are interested, we can discuss about them. Adding screenshots as well.
![history](https://user-images.githubusercontent.com/44674278/100854530-6aafc480-3489-11eb-880a-f851e81bc992.png)
![history_filter_launch](https://user-images.githubusercontent.com/44674278/100854535-6be0f180-3489-11eb-9e79-cb4fb05074b8.png)
![manual_tests](https://user-images.githubusercontent.com/44674278/100854539-6d121e80-3489-11eb-80ce-714daa05213c.png)
![manual_tests_charts](https://user-images.githubusercontent.com/44674278/100854542-6e434b80-3489-11eb-8e4e-3fed4cfb3217.png)
![manual_defects](https://user-images.githubusercontent.com/44674278/100854545-6edbe200-3489-11eb-81fe-6db41da698eb.png)

**Comment by evjlobanova** [comment]
Hello @odubaj 
Thank you for posting this ticket.
Could you please send us a pr for these features, so that we can review it and understand if we can proceed with this.

**Comment by odubaj** [comment]
Sure, it will take some time to rebase the changes to the current version. But will make it

**Comment by evjlobanova** [comment]
@odubaj thank you one more time for your feature offering, if you have any questions or issues please let me know.
Is it possible to contact you in Slack on any other tool. I would like to share our vision for manual testing and discuss several questions. What do you think about it?

**Comment by odubaj** [comment]
Sure, glad to discuss. I am on slack under email odubaj@redhat.com

**Comment by DzmitryHumianiuk** [comment]
@odubaj while team will take a look into PRs, I'd like to admit that your changes are relevant to our goals as well.
We assume to have manual test cases along with automated, in one picture soon.
But plan to make it at higher level.

First of all, I'd like to highlight that `Test Cases Type` (manual/automated) is just a characteristics (or attribute) of test case (TC).
TC can be executed manually, then automated and be a part of automation suite, but it still will the the same TC.
That's why we plan to differentiate `manual` and `automated` via TC attributes.
this also will help us to build charts based on attribute statistics, and have possibility to see all test cases or manual/auto at one picture.

What i see from pictures above: you used extended Defect Type object with Group Manual, which is good one, but goes against our logic.
Defect type should correspond only to NON-PASSED TC (failed or skipped), and should describe root of failure.

TC itself should have only statuses as: `passed` | `failed` | `skipped`.
e.g. `failed` status can be relevant both for manual and automated test.
Defect Type should be relevant to failed (or Non-passed TC) only.

Your workaround is a good one, based on possible flexibility, and perfectly uses it to reach the goal.
But the issue will come with next releases, since we will follow logic described above, and backporting of your customization will have issues with each next release.

Our goal is to have a separate tab for all test case library, no matter automated or manual, just a full list of all existing test cases relevant to your project. List can be fulfilled from automation script or from sync with other TMS (Test Case Management System).
Launches tab will represent test reports for both manual and automated executions, and will generate a Set of test reports from which we can draw information about the subset based on the selection criteria (manual/automated, platform, browser, env, etc.).

**Comment by odubaj** [comment]
Thanks for the explanation. I already explained our use-case in the email thread.

Adding reference to the first PR for /migrations repository https://github.com/reportportal/migrations/pull/168

I will continue with creating PRs for the other repositories as well, but it will take some time, as I need to rebase them against the current develop branch and test it properly.

**Comment by odubaj** [comment]
PR for /commons-dao repository prepared here https://github.com/reportportal/commons-dao/pull/706

**Comment by odubaj** [comment]
PR for /service-api repository here https://github.com/reportportal/service-api/pull/1338

I face some issues with failing tests, but until I resolve them, posting the code here for investigion.

In the next week I might prepare the PR also for /service-ui repository.

**Comment by odubaj** [comment]
PR for /service-ui repository https://github.com/reportportal/service-ui/pull/2537

**Comment by odubaj** [comment]
According to today's meeting I think we can adopt your concept of manual testing. I will take a look at our manual testing requirements and try to re-implement the feature according to our call. Additionally, we want to add a history of test-case description changes. The history of description changes are (from my investigation) not available in the database. There is probably just a description column update in test_item table. @DzmitryHumianiuk  can you please confirm this ? Are you planning any specific approach for this use-case, or should the data be stored in activity table ? I would prefer this this option, as it seem logical have information about status update together with the description update in one table.

I will also update the pull-requests when the changes will be prepared.

Thanks!

**Comment by DzmitryHumianiuk** [comment]
@odubaj yep, we don't save TestItem description change.
But it can easily added into activity table, the same like it's done for the rest of recorded data there.

@evjlobanova please add it as a task for the next sprints: record in `History of Actions` the change of description field.

**Comment by odubaj** [comment]
@DzmitryHumianiuk thanks. I will have a look at this feature as well.

**Comment by odubaj** [comment]
I will like to run a discussion about the name of the newly implemented status. Some of the options might be

- untriggered
- manual
- unexecuted

Please share your opinion or propose a name.

Thanks.

**Comment by evjlobanova** [comment]
I suppose that the good options are:
- untested (because it is pretty short and understandable)
- undefined

Unexecuted/untriggered - are also ok, but they are too long, and we should handle their reflections on UI

@odubajWhat do you think about 'untested'?

**Comment by odubaj** [comment]
Untested seems fine to me. We can continue with this option and if there will be a better proposal, we can change it.

Thanks.

**Comment by odubaj** [comment]
Updated pull-requests adding UNTESTED state for test-cases. @DzmitryHumianiuk @evjlobanova can you please review them, so we can move to the ui changes ? Facing some DataSource initialization issues during service-api testsuite, is it expected ?

Thanks.

https://github.com/reportportal/service-api/pull/1338
https://github.com/reportportal/commons-dao/pull/706
https://github.com/reportportal/commons-model/pull/277
https://github.com/reportportal/migrations/pull/168

**Comment by odubaj** [comment]
UNTESTED state feature accordingly added also to service-ui

https://github.com/reportportal/service-ui/pull/2537

**Comment by odubaj** [comment]
Changed compilaton dependencies in gradle.build file in both commons-dao and service-api repository are due to testing purposes to my repositories.

**Comment by evjlobanova** [comment]
Task on code review is added to the backlog

**Comment by odubaj** [comment]
Hello, any updates ?

Thanks.

**Comment by evjlobanova** [comment]
Sorry for the delay in response
The team is on NY vacations.

We have checked a pull request, and we are planning to create a list with code style issues, and also from my side I will prepare functional requirements, which should be also taken into account in this pr

**Comment by odubaj** [comment]
Great, looking forward to your advices.

**Comment by odubaj** [comment]
Hi @DzmitryHumianiuk, 

are there please any updates about adding changes of description field in history of action ? We discussed in in previous comments (https://github.com/reportportal/reportportal/issues/1235#issuecomment-742625787).

Thanks!

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova please double check we have this improvement in backlog.

**Comment by evjlobanova** [comment]
@DzmitryHumianiuk @odubaj Improvement is in the backlog - and assigned to the next sprint. 
It has been delayed a little bit because of appearing tasks with critical priority

**Comment by odubaj** [comment]
Understand, thank you!

Any updates about the UNTESTED state review?

**Comment by DzmitryHumianiuk** [comment]
@odubaj where was no discussion yet for `untested` state.
Team focused on data cleaning jobs, and will back to it afterwards.

**Comment by odubaj** [comment]
Hello, any updates ?

**Comment by evjlobanova** [comment]
We will send a letter with review details on this or earlier next week

**Comment by odubaj** [comment]
Thank you

**Comment by odubaj** [comment]
gentle ping

**Comment by odubaj** [comment]
Hello, any updates here ?

**Comment by evjlobanova** [comment]
Hello @obudaj on the last week a BackEnd team should send comments on your pr

**Comment by odubaj** [comment]
Ok, thank you

**Comment by odubaj** [comment]
Hello, I would like to ask about the possibility to make a specific project "public". That means, all users, which are logged in, can see results in the given project (all have roles = MEMBER). Do you have this feature somehow available ? If not, can it be done explicitly by adding a new row to "project_user" table for all newly created users (auth via SAML) ? Is anything other needed to be done ?

Thank you

**Comment by odubaj** [comment]
Sure, I will create a feature request for this.

**Comment by odubaj** [comment]
created request: https://github.com/reportportal/reportportal/issues/1339

**Comment by odubaj** [comment]
Hello, any updates about merging the pull-requests ? Seems that review is already completed, thanks.

**Comment by odubaj** [comment]
Gentle ping.

**Comment by evjlobanova** [comment]
Hello  @odubaj 
Your final rp is in the next sprint, on this sprint we finalizing version 5.4 for release.
And your pr is assigned to version 5.4.1 - as soon as we finish 5.4, your pr will be merged.

**Comment by odubaj** [comment]
Thank you!

**Comment by evjlobanova** [comment]
Sorry for the delay, but it is crucial change in RP, so that it should be tested well. And 5.4 contains big changes with retention policy jobs, so that we decided to separate them to the different versions

**Comment by odubaj** [comment]
Understand, thanks for information.

**Comment by evjlobanova** [comment]
We have merged your PR to dev branch, 
The feature will be available in 5.6
Now it is on the testing stage, some fixes are required, so our team will take them in the next sprint.


I just was wondering, if you send the second pr regarding the launch attribute value, our team can not find it. Could you please double check it

**Comment by odubaj** [comment]
Thank you for merging the feature! 

I have not created PRs for other features as currently I do not have the capacity to do so. We can discuss the possible features, but I can create the PRs earliest in the second half of August.

Thanks.

**Comment by thrix** [comment]
@evjlobanova hi, this seems not to be commited at all? Could we reconsider the UNTESTED state pretty please?

**Comment by DzmitryHumianiuk** [comment]
@thrix hi, this brings a list of inconstancies into our logic.
we do assume to put it as a part of our steps to 6.0 version, which will bring manual tests in place.

you already can see our transition to it with updates representation of Setting, starting from 5.7.2

**Comment by psss** [comment]
Thanks for the info. What is the expected/planned ETA for the 6.0 release?

**Comment by DzmitryHumianiuk** [comment]
@psss in 2023

**Comment by ondrahu** [comment]
Hi, is this feature available already or what is the ETA?

**Comment by DzmitryHumianiuk** [comment]
@ondrahu in design stage.
API is in implementation right now.

So there might be some `developer previews` available in Q2 2025

**Comment by vhdirk** [comment]
Hi, what's the status of this feature?

**Comment by DzmitryHumianiuk** [comment]
@vhdirk will be a part of the larger release 26.1 - ETA end of June 2026.
please watch the release updates closer.
