### ISSUE TITLE
Customized columns in a launch

### ISSUE THREAD

**Issue by evelinashames** [reportportal/reportportal#1236]
Hello everyone,

Can you please suggest for me how can I add a new column with an additional data in a launch?
For example, I would like to add an 'Owner' column to know who is working on each failure.

Maybe there is another existing column that can be used for this?

Thanks

**Comment by evjlobanova** [comment]
Hello 
This information is already presented on Launches Table 
![image](https://user-images.githubusercontent.com/30413511/100861345-8e9de680-3446-11eb-967e-6a34f07ca009.png)

Also, you can filter launches by this parameter 
![image](https://user-images.githubusercontent.com/30413511/100861408-9fe6f300-3446-11eb-8e08-429d3e96b144.png)


For now, there is no possibility to customize columns on the launches table

**Comment by evelinashames** [comment]
> Hello
> This information is already presented on Launches Table
> ![image](https://user-images.githubusercontent.com/30413511/100861345-8e9de680-3446-11eb-967e-6a34f07ca009.png)
> 
> Also, you can filter launches by this parameter
> ![image](https://user-images.githubusercontent.com/30413511/100861408-9fe6f300-3446-11eb-8e08-429d3e96b144.png)
> 
> For now, there is no possibility to customize columns on the launches table

This is for each lunch, is there an option to label owner per test case?

**Comment by evjlobanova** [comment]
you can add attributes like - owner: Jhon / owner: Michel and so on.
And on the base of these attributes, you will be able to create Component Health Check Widget (table view) https://reportportal.io/docs/Table-Component-health and track summary for each person
