### ISSUE TITLE
Download mp4 attachment

### ISSUE THREAD

**Issue by YBB8201** [reportportal/reportportal#1240]
Hi, I managed to send mp4 file attachment to report portal, but when trying to download it by "save target as" or similar way, it does not give any option for download/save the file. 
I tried it on google chrome and brave browser, in both it did not work.
the file is ok, on the local machine the mp4 is running if clicking on it.
any suggestions of how download attachments from RP?

![Capture](https://user-images.githubusercontent.com/66330263/100994744-956c4c80-355f-11eb-8f0d-f02b24b9fd9f.PNG)

**Comment by evjlobanova** [comment]
@svettsova Valya? could you please recheck this issue and try to reproduce?
@YBB8201 which version of ReportPortal do you use?

**Comment by YBB8201** [comment]
Hi,
build 5.0.0
[image: image.png]

**Comment by evjlobanova** [comment]
Update to the latest version
