### ISSUE TITLE
[v5] Lost logs after merge launches

### ISSUE THREAD

**Issue by beregeyko** [reportportal/reportportal#1242]
Configuration: 
reportportal.epam.com version 5.3.3
client - java client 5.0.15
agent - java cucumber 5.0.1
logger -logger java log4j 5.0.1

Unfortunately there are no specific steps to reproduce.
Issue reproducible after merge launches into one using deep merge method. 
After merge part or all launches doesn't have logs.
Please see attached gif. Part of launches has logs, part doesn't have and there is no possibility to expand section inside launch.

![logs_hide](https://user-images.githubusercontent.com/31613659/101133294-8053f400-3619-11eb-808d-a3b2e77b4c94.gif)

**Comment by svettsova** [comment]
Issue is added to backlog
