### ISSUE TITLE
ReportPortal Client should have ability to bypass google analytics reporting

### ISSUE THREAD

**Issue by djasani** [reportportal/reportportal#1245]
**Describe the solution you'd like**
- ReportPortal client should have property which determine if data should be posted to Google Analytics.

**Is your feature request related to a problem? Please describe.**
We are running report portal in controlled environment where instance does not have access to public internet. I have seen test shutdown hooks run for almost 2-3 minutes after test is finished. I believe its waiting on trying to close connection on google Analytics. I did fork of client locally and removed posting to Google Analytics and now test shutdown hook is completed in less than second.

**Comment by HardNorth** [comment]
Duplicate: https://github.com/reportportal/client-java/issues/125
