### ISSUE TITLE
[v5] Unable to configure LDAP plugin for LDAPS (VDS)

### ISSUE THREAD

**Issue by IharBletskoTR** [reportportal/reportportal#1247]
5.3.3, docker, LDAP-plugin.
Setting up RP to work with VDS (virtual ldaps server), but when trying to connect receiving error 49: org.springframework.security.authentication.InternalAuthenticationServiceException: [LDAP: error code 49 - Invalid Credentials]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]
Tested connection from command line of the RP server and it worked with
ldapsearch -x -b "cn=C<username-to-find>,ou=ead,ou=users,dc=enterpriseAD" -H ldaps://LDAPS-SERVER -D "cn=SERVICE-ACCOUNT,ou=ead,ou=users,dc=enterpriseAD" -W

**To Reproduce**
Use ldaps settings in LDAP-plugin

**Expected behavior**
Succeful login to ldaps-server, succeful find user from entered to RP's login screen.

**Screenshots**
LDAP-plugin settings used:
![image](https://user-images.githubusercontent.com/68950579/101477468-4d369b00-3960-11eb-8056-dac8f0c06bd8.png)
Similar settings worked for other ldap(not ldaps) server.

**Comment by evjlobanova** [comment]
Please send us logs from auth service

**Comment by IharBletskoTR** [comment]
Logs sent to email: support@reportportal.io
subj: [v5] Unable to configure LDAP plugin for LDAPS (VDS) #1247

**Comment by IharBletskoTR** [comment]
Thanks to Andrei Varabyeu, issue is fixed by changing settings to correct ones.
Fields Base DN and Manager DN should look exactly like this to work in my LDAPS server:
![image](https://user-images.githubusercontent.com/68950579/104594236-eb193600-5681-11eb-8901-807e9fe4ec4b.png)
Also, user search filter should contain either: "sAMAccountName={0}" or "cn={0}".
User DN pattern and Group search base can be empty.
