### ISSUE TITLE
Sometime tests remain in the state "in progress" instead of "pass"

### ISSUE THREAD

**Issue by SergeVKom** [reportportal/reportportal#125]
agent-java-testng - version:‘3.0.0’
logger-java-logback - version:‘3.0.0’
testng - version:'6.9.10'

Exception log:
https://gist.github.com/SergeVKom/6b5f80e76c3215f22fd1079bcd0e83d2

When we stop such tests they have status "INTERRUPTED" and there is no possibility to set status "pass" for them.

**Comment by avarabyeu** [comment]
Couple of update have been released for java integration. Do you still have the issue?

**Comment by DzmitryHumianiuk** [comment]
@SergeVKom did you check with latest client?

**Comment by SergeVKom** [comment]
@DzmitryHumianiuk no, I did not. Let me check.

**Comment by evjlobanova** [comment]
@SergeVKom can you share with your results?

**Comment by SergeVKom** [comment]
Sorry for delay. We are running tests many times and sometimes still have the same problem:
https://gist.github.com/SergeVKom/8210cd14767d6680c8565316bb19268b

**Comment by DzmitryHumianiuk** [comment]
@SergeVKom is it still reproducible with 4.0.1 agent for testNG?

**Comment by evjlobanova** [comment]
@SergeVKom ^

**Comment by DzmitryHumianiuk** [comment]
@SergeVKom plz open new issue if still actual.

Condidered as fixed
