### ISSUE TITLE
Adding public certificate in report portal chart

### ISSUE THREAD

**Issue by rubico259** [reportportal/reportportal#1252]
I installed report portal using helm chart.
Now, i want to configure the saml plugin for sso.
When it send the request to identity manager for the xml it failed on ssl exception:

Caused by: javax.net.ssl.... PIKX path build failed..unable to find valid certification path to request target

How can i add public certificate of the identity manager into trust store in helm chart?

**Comment by Cyberglamdring** [comment]
Dear @rubico259,
Try to set up SAML according to the existing guide at [reportportal.io]( https://reportportal.io/docs/SAML-integration) and [Youtube](https://youtu.be/ljXvCVWG4mQ)

**Comment by rubico259** [comment]
That's exactly what i did.
The problem:
Uat service is deployed on k8s and the idp deployed on vm outside k8s. 
When the uat service trying to send the request to the idp it requires public key of the idp. So i need somehow a way to configure the idp public key inside the truststore uat service.

**Comment by rubico259** [comment]
Any comment?

**Comment by Cyberglamdring** [comment]
Try to looking into https://reportportal.io/docs/Issues-with-LDAPS:
You can create Configmap with certificate and add mount them as volume. [Help](https://medium.com/@paraspatidar/add-ssl-tls-certificate-or-pem-file-to-kubernetes-pod-s-trusted-root-ca-store-7bed5cd683d)
PATH for volume /usr/local/openjdk-11/lib/security/cacerts and /etc/ssl/certs/ca-certificates.crt

Or you can rebuild docker UAT image [like this](https://docs.idalko.com/exalate/display/ED/How+to+add+a+new+root+certificate+to+the+java+key+store)

**Comment by rubico259** [comment]
The first solution didn't work.
I rebuild docker with my certs.
But this is not a preferred solution as i need to manage Dockerfile for each new release.
