### ISSUE TITLE
SSO - agnostic IDM

### ISSUE THREAD

**Issue by rubico259** [reportportal/reportportal#1254]
Currently, saml works only with OKTA.
We have VIDM as Identity Manager.

Can you please implement saml with any identity manager?

**Comment by raikbitters** [comment]
@rubico259 hello. We implement SAML configuration for typical Identity providers to the SAML plugin. 
At the current moment, we support only HTTP-POST binding.
You can try to set-up your SAML plugin like in [Azure SAML integration]( https://reportportal.io/docs/Azure-SAML-integration).
