### ISSUE TITLE
Accuracy analysis

### ISSUE THREAD

**Issue by Whiletru3** [reportportal/reportportal#1256]
Hello,

Is there a way to analyse launches and compare them based on an accuracy level (in %age) instead of Failed/Passed. The accuracy level is in each test log.

Thanks

**Comment by evjlobanova** [comment]
Hello @Whiletru3 
could you please clarify what you mean?
Now the analyzer is working on the base of error logs similarity https://www.youtube.com/watch?v=HUNvNv-q1XE&t=8s ?
![image](https://user-images.githubusercontent.com/30413511/102315396-f1a07a80-3f28-11eb-91a9-880e236968e6.png)
