### ISSUE TITLE
Getting error java.lang.NoClassDefFoundError: com/epam/reportportal/service/tree/TestItemTree while using selenium+testng

### ISSUE THREAD

**Issue by Mandeepsheoran** [reportportal/reportportal#1257]
Hi
I am using Selenium+testng and getting below error while running it.

There was an error in the forked process. 

java.lang.NoClassDefFoundError: com/epam/reportportal/service/tree/TestItemTree
[ERROR] at com.epam.reportportal.testng.TestNGService.(TestNGService.java:87)
[ERROR] at com.epam.reportportal.testng.ReportPortalTestNGListener$1.get(ReportPortalTestNGListener.java:32)
[ERROR] at com.epam.reportportal.testng.ReportPortalTestNGListener$1.get(ReportPortalTestNGListener.java:29)
[ERROR] at rp.com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
[ERROR] at com.epam.reportportal.testng.ReportPortalTestNGListener.(ReportPortalTestNGListener.java:37)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[ERROR] at java.lang.Class.newInstance(Class.java:442)
[ERROR] at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:69)
[ERROR] at org.testng.TestNG.addListeners(TestNG.java:949)
[ERROR] at org.testng.TestNG.initializeConfiguration(TestNG.java:912)
[ERROR] at org.testng.TestNG.initializeEverything(TestNG.java:996)
[ERROR] at org.testng.TestNG.run(TestNG.java:1009)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
[ERROR] at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] Caused by: java.lang.ClassNotFoundException: com.epam.reportportal.service.tree.TestItemTree
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

My pom file is below:

com.epam.reportportal
logger-java-logback
5.0.3
com.epam.reportportal agent-java-testng 5.0.8-TESTNG6 com.epam.reportportal client-java 3.0.0 com.google.inject guice 4.1.0 com.fasterxml.jackson.core jackson-annotations 2.8.6

false bintray-epam-reportportal bintray https://dl.bintray.com/epam/reportportal 

I have completed listeners setting also in testng.

**Comment by HardNorth** [comment]
Already answered here: https://github.com/reportportal/agent-java-testNG/issues/152
Please do not spam with issues, or I have to block you.
