### ISSUE TITLE
[v5] comma in time in xml report -> import error: Wrong state: item is not 'In progress', but has no finish time

### ISSUE THREAD

**Issue by pako88** [reportportal/reportportal#1258]
**Describe the bug**
If there is a comma in the time value of a xml report (maven surefire creates these kind of values when running for a longer time), the import fails with the message "Error while importing the file. 'For input string: "3,226.156"'
The launch is marked as "Wrong state: item is not 'In progress', but has no finish time"
all tests before that point in the xml report are reported correctly - all other tests aren't reported at all.

**To Reproduce**
Upload a xml test report with following example testcase:
`<testcase name="myCommaTest" classname="com.tests.CommaTest" time="3,226.156"/>`

**Expected behavior**
import should also work with such comma values

**Desktop (please complete the following information):**
 - OS: doesn't matter
 - Browser doesn't matter
 - Version doesn't matter

**Additional context**
Tested with Report Portal 5.3.3
additional infos and a possible fix can be found here: https://github.com/junit-team/junit5/issues/1381

**Screenshot**
![image](https://user-images.githubusercontent.com/28978631/102454885-fd7e6080-403e-11eb-8e75-3ce7f26de716.png)

**Comment by MaryiaRymarchyk** [comment]
Hello @pako88 ,
sorry for late response.

This time field represents duration for the test item completion and it is optional for the import functionality.  Format = seconds.milliseconds.
We don't  support comma in the 'time' field and don't have plans to enhance this functionality for now.
