### ISSUE TITLE
Report Portal launches with incorrect test counts

### ISSUE THREAD

**Issue by Hsillman** [reportportal/reportportal#1260]
Hello Folks!

We are fetching Jenkins results and importing them into Report Portal. However, some launches have some tests missing in comparison to the total test count from Jenkins job. If we compare the amounts, we see that some launches have missing tests (around 1-6 tests) that do not appear at all in the Portal.

Test amount in Jenkins Job:
![Captura de Tela (202)_LI](https://user-images.githubusercontent.com/18448914/102618621-e2345380-4119-11eb-965a-d44620b12e86.jpg)

Test amount in Report Portal launch: In this case 2 tests are missing.
![Captura de Tela (203)](https://user-images.githubusercontent.com/18448914/102618791-2a537600-411a-11eb-903b-cad27c24989c.png)

We seem to have a clue, not entirely sure. Report Portal has a "service.py" file found in "reportportal_client/service.py" where a method called "start_test_item" is implemented. This method has a structure called "data" which presents us with "start_time" attribute for each test in the .xml file extracted from Jenkins.
We happened to find that the tests that are missing in the RP launch have the attribute "start_time" in a different format from those tests that appear in the portal. 
Whilst the "start_time" attribute from the tests that show in the portal look like this  **2020-12-18T11:55:01.655Z**, the ones that do not show have the "start_time" set as something like this **2020-12-18T12:00Z** (missing the seconds and miliseconds from the timestamp)

[This is a very similar issue we found](https://github.com/reportportal/agent-js-cypress/issues/63)

This is the Report Portal version we are using!
![Captura de Tela (201)](https://user-images.githubusercontent.com/18448914/102618202-2410ca00-4119-11eb-969f-a2d0f7179f12.png)

**Comment by HardNorth** [comment]
@Hsillman which exact agent and version do you use?

**Comment by Hsillman** [comment]
Hello @HardNorth @iivanou it turns out to be a problem in the parser we were using to parse the .xml file from Jenkins. Not a report portal or python agent issue. Closing the issue
