### ISSUE TITLE
[v5] Incorrect file extension generated for video file aatchment during download in v5.3.4

### ISSUE THREAD

**Issue by Shakevg** [reportportal/reportportal#1263]
**Describe the bug**
In v5.3.4 incorrect extension generated for the video attachment file during the download

**To Reproduce**
1. Test created using mstest executed in Azure DevOps
2. Test failed and video attachment with WMV  should be added
3. Open Failed tests in Report Portal v5.3.4
4. Try to download the video attachment 
=> Incorrect file extension generated (need to update it to wmv to open file)

**Expected behavior**
The correct extension should be for the video file attachment

**Screenshots**
![image](https://user-images.githubusercontent.com/42133199/103509776-f47df380-4e74-11eb-9518-fad3f9dc3cf9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
In the previous version 5.3.3, it was correct file extension like c8d713a1-af4e-4ca0-99a4-a7103a5b8aad.wmv

**Comment by Shakevg** [comment]
Could somebody provide ETA when it unpleasant issue will be fixed (because need each time to modify the file name manually)?

**Comment by HardNorth** [comment]
@Shakevg Which agent do you use for upload the video?

**Comment by Shakevg** [comment]
@HardNorth I use .Net [agent-net-vstest](https://github.com/reportportal/agent-net-vstest)

**Comment by Shakevg** [comment]
The issue is not reproduced now (https://reportportal.epam.com/ Build: 5.6.0)

**Comment by VolhaKarenko** [comment]
Closed as not reproducible

**Comment by Shakevg** [comment]
@VolhaKarenko Issue is reproduced again on Chrome 99, could you please reopen it?

**Comment by Shakevg** [comment]
The issue is still reproduced Chrome 110

**Comment by Kozovskaya** [comment]
@Shakevg correspondent ticket has been added to our Backlog and we will take it into work in accordance with priority!

**Comment by VolhaKarenko** [comment]
Hello @Shakevg, the fix will be available in version 23.2.

**Comment by Kozovskaya** [comment]
Hello @Shakevg! The fix is already available with our latest release 23.2!
