### ISSUE TITLE
how to fail a particular test in report portal

### ISSUE THREAD

**Issue by gopikishan1995** [reportportal/reportportal#1265]
Issue 1: 
without using assertion, i want to fail particular @test in multiple @test class.
Issue 2:
i want to fail a particular @test like below is the example scenario:
example scenario: in one @test i have few parameter or arguments to test and if one argument or parameter fails then script should fail and it should not hard stop the script, it should proceed with other parameters validation but in the script should fail if any of the parameter validations fails.

**Comment by HardNorth** [comment]
@gopikishan1995 we are reporting tool, not a test framework. We only report what a test framework give us. I believe you need to address this question to a framework you use.
