### ISSUE TITLE
[v5] Configuring SAML does not add a Login With SAML button

### ISSUE THREAD

**Issue by robertlagrant** [reportportal/reportportal#1266]
**Describe the bug**
Configuring SAML does not add a Login with SAML button to the login screen

**To Reproduce**
Follow the configuration steps in the Youtube video - https://www.youtube.com/watch?v=ljXvCVWG4mQ. We use Okta SAML, just like the video. The SAML plugin reports it is connected.

**Expected behavior**
A Login With SAML button on the login screen:
![image](https://user-images.githubusercontent.com/1766161/103672872-d0094080-4f74-11eb-84e3-7794c74fd502.png)

**Additional context**
ReportPortal 5.3.

**Comment by danclegg** [comment]
@robertlagrant I can't offer an official answer from the project, but this _might_ help.

I have a config that is connected to Okta and works as you'd expect, with a button present and the login creating the user. There were some critical things that the Okta application and SAML settings have to have in common, [in particular the audience value](https://github.com/reportportal/service-authorization/blob/fe1f39f903e598ac4323b5b467dc50ac9f964989/src/main/resources/application.yaml#L71). You are correct in noting that it reports a successful connection, but the only way to know for sure is by trying the login.

**OKTA:**
![image](https://user-images.githubusercontent.com/1900734/127702005-90ea5b4e-de6c-460e-b358-7fc95c5eede6.png)

**RP:**
![image](https://user-images.githubusercontent.com/1900734/127702109-a359e1a3-5e9b-48a2-a7c8-4dd396368813.png)

My docker-compose uses the following image versions. I had to downgrade to 5.3.0 on the UI to get things totally working.
- reportportal/service-authorization:5.3.5
- reportportal/service-ui:5.3.0

It took a lot of trial & error, watching the logs, but in the end, things worked fine. 

Good luck!

**Comment by VolhaKarenko** [comment]
Hi @robertlagrant, was the answer above useful for you or are you still having the issue?

**Comment by MaryiaRymarchyk** [comment]
Hi @robertlagrant 
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to contact us.
