### ISSUE TITLE
JIRA Integration deployment with Docker

### ISSUE THREAD

**Issue by mamarton** [reportportal/reportportal#1267]
Hi, the documentation is unclear and there are different sources for service-jira.

The [documentation](https://reportportal.io/docs/Plugins%3Eupload-plugin) points to binary for service-jira with v 5.1.0
Although in DockerHub there is only an older version of the same v4.3.0

- [DockerHub](https://hub.docker.com/r/reportportal/service-jira)
- [BinTray](https://bintray.com/beta/#/epam/reportportal/plugin-bts-jira?tab=files)

The latest docker-compose-yml does not contain service-jira and there is lack of guidance how to install it with docker.
If this service no longer support dockerized deployment, it should be clear how to deploy and configure to work with a dockerized deployment of ReportPortal.

Please support.

**Comment by HardNorth** [comment]
The documentation is absolutely clear. Try reading it.

We moved away from standalone services in V4 and introduced a new plugin mechanism in V5.

**Comment by mamarton** [comment]
So the answer is there is no JIRA integration deployed via Docker. One has to download the jar files and go from there.

**Comment by DzmitryHumianiuk** [comment]
@mamarton 
In ReportPortal version 2-4 Jira integration was implemented as separate micro-service, which should be deployed via Docker along with whole application.

Starting from ReportPortal v5 we moved away from standalone services and introduced a new plugin mechanism in V5.
Which minimizes resource consumption and enables instant plugin availability, without app restart.
We plan to have some sort of in-app plugin marketplace, thus you can find all available plugins right within ReportPortal itself.

For now you have to follow up to [https://reportportal.io/docs/Plugins](https://reportportal.io/docs/Plugins) page and download jar file. Then upload it in `Administrative page` > `Plugins`.

Sorry for a misleading information in documentation, we will address it soon as well.
