### ISSUE TITLE
Add ability to switch to test cases stats (Total, Passed, Failed, Skipped) in launches

### ISSUE THREAD

**Issue by maximustremor** [reportportal/reportportal#127]
For automated metrics measurement it would be cool to have a test cases view for Launches. Because it is usually all about test cases not test methods.
For now all stats we have in Launches are devoted to test methods.
![launches-only-show-methods-stats](https://cloud.githubusercontent.com/assets/5155590/26055189/5279cbbe-3978-11e7-9b35-e5625f8baf64.png)
To reach out to actual test cases list user should go two levels deeper. And that's how it goes for every run under analyzing.

**Comment by DzmitryHumianiuk** [comment]
@maximustremor this really depends on agent implementation. RP just shows received data. Data structure and counts generated by agents.

Do you use BDD approach and CucumberJVM?

**Comment by avarabyeu** [comment]
We are planning to introduce different statistics calculation strategies in next release. There will be test-based (not step-based) strategy which is what you are asking from

**Comment by maximustremor** [comment]
We are to use RP widgets for last run status. So to be able to show number of test cases passed, failed, skipped etc. It will increase visibility quality of autotest results for the team. We are also using RP stats for quarterly reports. It may be a way more convenient to switch to test cases view for it.

**Comment by DzmitryHumianiuk** [comment]
@maximustremor which agent you use? (testng, cucumber, junit, nunit, ...)
i guess you problem is in configuration of agent.

**Comment by evjlobanova** [comment]
@maximustremor up ^
