### ISSUE TITLE
Popup dialog is closed when during text selection cursor move out of the border

### ISSUE THREAD

**Issue by Shakevg** [reportportal/reportportal#1271]
**Describe the bug**
Sometimes it is a long text inside Edit Dashboard\Edit Filter\Link Issue Popup. And when I quickly try to select text the popup is closed when during text selection cursor move out of the popup border

**To Reproduce**
1. Open Edit Dashboard\Edit Filter\Link Issue Popup
2. Try select text using pressed left mouse button
=>  Popup is closed when during text selection cursor move out of the popup border

**Expected behavior**
Just text selected, popup is not closed

**Screenshots**
https://user-images.githubusercontent.com/42133199/104556151-197e1d80-5650-11eb-84a9-2f47032a784a.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
Issue reproduced not for all popups (e.g. working for EDIT DEFECT TYPE \ TEST ITEM DETAILS)

**Comment by DzmitryHumianiuk** [comment]
`mouseUp` event generated outside the pop-up screen, which causes pop-up closure.

hmmmmm....
need to discuss with @AmsterGet

**Comment by VolhaKarenko** [comment]
fixed in version 5.5
