### ISSUE TITLE
remove method types that are not test from reportportal

### ISSUE THREAD

**Issue by tanyaso** [reportportal/reportportal#1272]
hey,
I have a test project with junit 5 that reports to reportportal.
Before running the suite I have some configuration that is annotated with @beforeall.
And some configuration before each test that is annotated @beforeeach.
as a result when checking the reports beside test I see all those annotations which makes it hard to understand which is which.
Is there a way to not show those methods/include them in the test log?
![image](https://user-images.githubusercontent.com/70099385/104575281-a4b2df80-565f-11eb-9828-7309d8aac75e.png)

I saw there is an option to filter out everything besides test in the RP UI, is there a way to do this filter to all runs?
![image](https://user-images.githubusercontent.com/70099385/104575358-b300fb80-565f-11eb-8258-609b29791533.png)

**Comment by DzmitryHumianiuk** [comment]
@tanyaso 

![image](https://user-images.githubusercontent.com/11332788/106308993-8d384100-6272-11eb-92df-8286d5b96c42.png)

**Comment by NikitaBQ** [comment]
Having same question in 2025. There is no option to pin any filters:

![Image](https://github.com/user-attachments/assets/c81d5fb6-1958-45eb-9900-5f3c9586e8cf)
