### ISSUE TITLE
how can i update the launch with attributes/description

### ISSUE THREAD

**Issue by willyhalim** [reportportal/reportportal#1273]
how can i update the launch with attributes/description after launch started via API

I am able to do it by logging to reportportal web but is wondering if i can do it via API.
The use case will be it will be nice to tag specific launch with specific application version / test version at the same time

**Comment by evjlobanova** [comment]
@VolhaKarenko could you please add info about needed API call

**Comment by VolhaKarenko** [comment]
Hi @willyhalim 
You can update the launch using
PUT
​/v1​/{projectName}​/launch​/{launchId}​/update

Request body example:
{
  "attributes": [
    {
      "key": "string",
      "value": "string"
    }
  ],
  "description": "string",
  "mode": "DEFAULT"
}
