### ISSUE TITLE
User Provided TestCaseID with Cucumber6 + Junit5 + Java + Maven

### ISSUE THREAD

**Issue by Shivin89** [reportportal/reportportal#1276]
Hey Everyone, 
 
Background info: We Have implemented ReportPortal in our Organization for Dashboards and reporting purposes. We have already installed it and now we are trying to configure our test automation framework with it. We have a different Testing framework and we want to integrate that with the report portal. I have seen the integration page and successfully integrated it. The framework I am currently working on is using Cucumber6 + Junit + Maven + Java. 
 
I need help in regards to TestCaseID, Right now for every step (Given, when then format) TestID is getting generated auto, but I need to provide my own TestID like Jira ID (QUALITY-1333),
How can I achieve this?  
I tried @TestCaseId annotation in my Stepdefinition file but it’s not working.
Can you please help me out with this 

![image](https://user-images.githubusercontent.com/22401226/104662011-afc93800-567e-11eb-8d58-9a1041e3ec47.png)
![image](https://user-images.githubusercontent.com/22401226/104662054-ccfe0680-567e-11eb-94f7-8f2eb70bca8a.png)

**Comment by DzmitryHumianiuk** [comment]
discussion: https://reportportal.slack.com/archives/C2GTJTTNH/p1610662363006400

you need to use `ScenarioReporter` and you need to override [`buildStartScenarioRequest`](https://github.com/reportportal/agent-java-cucumber6/blob/develop/src/main/java/com/epam/reportportal/cucumber/AbstractReporter.java#L237) method inside [`AbstractReporter`](https://github.com/reportportal/agent-java-cucumber6/blob/develop/src/main/java/com/epam/reportportal/cucumber/AbstractReporter.java) class to set your own Test Case ID.

![image](https://user-images.githubusercontent.com/11332788/104816305-5c481d00-582b-11eb-9a2b-31018067dad7.png)

The tag above scenario will be inside attributes of result object of `buildStartScenarioRequest` method, just set it into TestCaseId field [here](https://github.com/reportportal/agent-java-cucumber6/blob/develop/src/main/java/com/epam/reportportal/cucumber/AbstractReporter.java#L248).

**Comment by DzmitryHumianiuk** [comment]
@Shivin89 did it help?

**Comment by Shivin89** [comment]
Yes, it worked

Thanks

**Comment by HardNorth** [comment]
A reporter example:
https://github.com/reportportal/examples-java/blob/master/example-cucumber4/src/main/java/com/epam/reportportal/example/cucumber4/reporter/ScenarioReporterTestCaseId.java
