### ISSUE TITLE
Ability to specify behavior for defect description for manual Analyze

### ISSUE THREAD

**Issue by Shakevg** [reportportal/reportportal#1278]
**Describe the solution you'd like**
Propose to add to "ANALYZE LAUNCHES" dialog ability to specify behavior for defect description when some option from "Choose the test items that should be analyzed:" is selected like for bach defects update:
![image](https://user-images.githubusercontent.com/42133199/104992292-ca5e3100-5a31-11eb-8ad3-8510ec481203.png)

**Is your feature request related to a problem? Please describe.**
Defect description appended without separator after Analyze failures with existing defect description (manual or set by AA)
![image](https://user-images.githubusercontent.com/42133199/104807713-f8edc900-57f1-11eb-9f7b-cb74374591c9.png)

**To Reproduce**
1. Launch should have failed tests with defect types and description that set manually or by AA
2. Open "ANALYZE LAUNCHES" dialog for launch (Analysis item from Launch context menu ) and select "Items analyzed manually" or "Items analyzed automatically (by AA)" option
=>  Defect description appended (duplicated or added new) without separator after Analyze failures with existing defect description (see the screen above).

**Comment by DzmitryHumianiuk** [comment]
@Shakevg did you add description for the defect before manual triggering of Auto-Analysis?

@evjlobanova do we append defect comment with comment from equal issue?
if it's according to designed flow, then we need at least to start it from the new line.

**Comment by Shakevg** [comment]
> @Shakevg did you add description for the defect before manual triggering of Auto-Analysis?
> 
> @evjlobanova do we append defect comment with comment from equal issue?
> if it's according to designed flow, then we need at least to start it from the new line.

@DzmitryHumianiuk I updated the description with more clear steps. Yes, for some defects I added a description manually, but the same issue for defects that were set by AA.

**Comment by VolhaKarenko** [comment]
Fixed in version 5.4.1
