### ISSUE TITLE
Parsing of timestamp in Junit report import using REST API is giving error

### ISSUE THREAD

**Issue by akthomas2108** [reportportal/reportportal#1279]
I was trying to use the REST API for importing the junit report through the UI's API "try it out" option.
http://hostname:port/api/v1/test/launch/import

On attempting, i get the following error
```json
{
  "errorCode": 40035,
  "message": "Error while importing the file. 'Text '2021-01-15T03:39:20 UTC' could not be parsed, unparsed text found at index 19'"
}
```
Note the the timestamp was reported as the issue. If i switch the timestamp as formated to "13 Jan 2021 22:56:44 GMT" then the import works.
```json
{
  "message": "Launch with id = b3e081ff-450f-4c77-bc9e-ad3f1b9b0076 is successfully imported."
}
```

Please find attached the samples. TestReport1.xml works while TestReport2.xml fails.
[sample-junit-reports.zip](https://github.com/reportportal/reportportal/files/5828065/sample-junit-reports.zip)

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova @pbortnik this should be considered for improvement.
please take it to the next sprint and minor release.

**Comment by evjlobanova** [comment]
Added to the next sprint grooming session

**Comment by pbortnik** [comment]
Fixed. Will be available in the version 5.4

**Comment by avd1989** [comment]
Hi, this error is happening again on 5.7.2 : {"errorCode":40035,"message":"Error while importing the file. 'Text '2022-11-17 10:15:43' could not be parsed, unparsed text found at index 0'"}

![image](https://user-images.githubusercontent.com/23204159/202599251-2c07c76c-aefc-4258-8efb-136141c0282f.png)

**Comment by VolhaKarenko** [comment]
Hi @avd1989,
The samples you provided earlier are both imported successfully on 5.7.2, so the initial issue is fixed.
I tried the timestamp you mentioned and got the same error, but it works with a timestamp in the format "2022-11-17T10:15:43". Please let me know if this works for you or open another issue for it

**Comment by avd1989** [comment]
I kept on looking for a format that could work, tried GMT and that also did the trick. I guess the only improvement that could be done is to mention what formats are accepted. But overall, the tool is great! @VolhaKarenko thanks for the quick follow-up

**Comment by VeranikaRymzha** [comment]
Hello @avd1989,
Thank you for your request and suggestion. 
The task for our Tech Writer has been created. I think we'll be able to add this information to the website in December.

**Comment by VeranikaRymzha** [comment]
Hello @avd1989,
Just to keep you informed:
As promised, the information about the acceptable data formats has been added to the documentation:
https://reportportal.io/docs/Import-data-to

If there are any other questions, please, let us know.

**Comment by avd1989** [comment]
Hi @VeranikaRymzha , I really appreciate the quick response and effort! Thanks a lot!

**Comment by rujutashinde** [comment]
Hello @VeranikaRymzha  I am still seeing this issue with RP version 5.7.2
I did open a new issue for this https://github.com/reportportal/reportportal/issues/2008
The link you posted https://reportportal.io/docs/Import-data-to no longer exists, do we have an updated documentation on what is the format for `time ` attribute in the xunit files that is accepted by the api
