### ISSUE TITLE
Onboarding queries related to Report Portal Performance Optimization

### ISSUE THREAD

**Issue by python-auto-hc** [reportportal/reportportal#1283]
1. Need help in selecting the required machine configuration on the basis of below points -
-Daily log size for me across all projects is around 400MB-1000MB across organization
-Approx 20 users will be using report portal dashboard
-10 projects will be present on RP dashboard and out of which 3-4 can be running a launch at a given point.

Please suggest if there are more parameters to be considered.

2. Also as mentioned above would like to know if we do have some archiving or cleanup strategy for old launches without disturbing the baselines which are set ?
3. Is there a way to reset/remove all the baselines what are set ?
4. should we be using docker on linux VM for hosting RP or non docker setup on VM ?
Apologies for too many questions 🙂 
![image](https://user-images.githubusercontent.com/68046094/105453240-cb979400-5ca5-11eb-92f8-6014d3c96733.png)

@evjlobanova

**Comment by python-auto-hc** [comment]
@priyankachaturvedi30

**Comment by DzmitryHumianiuk** [comment]
@python-auto-hc @priyankachaturvedi30
I extended documentation with explanation how to transform system capacity into real test cases.
Please let me know if it makes sense.

It will be available in docs at: https://reportportal.io/docs/Optimal-Performance-Hardware (section 3)
and via direct link here:
https://github.com/reportportal/documentation/blob/master/src/md/src/TipsAndTricks/PerfIssuesResolving.md#3-which-scale-i-need-configuration-testing-results-and-saturation-points

**Comment by python-auto-hc** [comment]
@DzmitryHumianiuk thanks for updating the section. I went through it but it isnt that straight forward. May be we need to start from small and then scale up as per the need. Because it will also depend upon both volume and size of log.

Apart from that will also need help on -

-archiving or cleanup strategy for old launches ? if possible then without disturbing the baselines which are set.
-Is there a way to reset/remove all the baselines what are set ?

**Comment by evjlobanova** [comment]
For now, all old launches are removed from the system.
We are planning to add a Release lock functionality, that helps to save a baseline #674
