### ISSUE TITLE
is there any way for enabling step reporter without using RunCukesTest class 

### ISSUE THREAD

**Issue by tejchaitanya** [reportportal/reportportal#1284]
@RunWith(Cucumber.class)
@CucumberOptions(plugin = {"pretty", "com.epam.reportportal.cucumber.StepReporter"})
public class RunCukesTest {
}

**Comment by HardNorth** [comment]
@tejchaitanya What's wrong with RunCukesTest class?

Anyway it's how Cucumber officially states to run their tests:
https://github.com/cucumber/cucumber-jvm/blob/main/examples/java-calculator/src/test/java/io/cucumber/examples/java/RunCucumberTest.java

No matter which framework you choose it's alway almost the same file, E. G. JUnit 5:
https://github.com/cucumber/cucumber-jvm/blob/main/examples/java-calculator-junit5/src/test/java/io/cucumber/examples/junit5/calculator/RunCucumberTest.java
