### ISSUE TITLE
[v5] InternalReportPortalClientException: Wait for Launch start timed out

### ISSUE THREAD

**Issue by naddison** [reportportal/reportportal#1286]
Hi I am using the Java Client directly in my Java code and sometimes when starting the launch I get the following error:

```
Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Wait for Launch start timed out
        at com.epam.reportportal.utils.Waiter.till(Waiter.java:131)
        at com.epam.reportportal.service.launch.SecondaryLaunch.waitForLaunchStart(SecondaryLaunch.java:56)
        at com.epam.reportportal.service.launch.SecondaryLaunch.start(SecondaryLaunch.java:88)
```

I am unable to troubleshoot much further, is there additional context or common scenarios/configuration that could cause this I may be missing?

Sample code of how I use the client.
```java
reportPortalClient =  ReportPortal.builder()
          .withParameters(reportPortalConfig)
          .build()
          
launch = reportPortal.newLaunch(createNewLaunchRequest())

launch.start(); // this is where my error occurs
```

Some additional context. Inside the same container/virtual machine I have a single Java process that creates a new thread for each new launch we want to create. My service (Java) is creating launches for different projects, so I end up creating a new thread and a new instance of ReportPortal.class on the same machine for every launch. I am not sure how else to support creating launches in different projects.

This is with version 5.0.11 of the client-java.

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu this is definitely the question for you

**Comment by naddison** [comment]
With client.join = false, my issue is resolved. I believe it has to do with the lock files created when the feature is turned on. I don't think I am using ReportPortal.class in its intended use case. Usually, it's plugged into a test framework and is only expecting to send launches to the same project. Those are my assumption anyway.

**Comment by DzmitryHumianiuk** [comment]
most likely it is right assumption.

can we close issue now?

**Comment by gpapadakis** [comment]
> With client.join = false, my issue is resolved

Where do you set this @naddison as we are experiencing same issue randomly

**Comment by DzmitryHumianiuk** [comment]
@gpapadakis if you set it to `false`, then each of started thread in your test runner will be reported as separate launch.

`reportportal.properties` is the right place to add it. Works for Java.

**Comment by gpapadakis** [comment]
> @gpapadakis if you set it to `false`, then each of started thread in your test runner will be reported as separate launch.
> 
> `reportportal.properties` is the right place to add it. Works for Java.

thanks @DzmitryHumianiuk my problem is that i need one launch containing all feature files. So there are lots of features skipped at the moment due to this issue. I tried multiple solutions like increasing the limit of connections on Postgres (if it is a performance issue on the handling of requests) but nothing seems to solve the issue. By the way we use Concurrent JUnit Runner that each cucumber java class executed in its own thread. Each one tries to create a new Launch instance and there is the issue. Any other hints?
