### ISSUE TITLE
Regarding Multiple launch 

### ISSUE THREAD

**Issue by tejchaitanya** [reportportal/reportportal#1290]
I'm working with Cucumber and I have 10 features running in parallel but in reportportal i have 10 separate launches :disappointed_relieved:.
I want to have only one launch that contains features running in parallel .
Is that possible!?

**Comment by DzmitryHumianiuk** [comment]
Most likely you were referring to this: 
how to configure multi-threaded execution in java
https://github.com/reportportal/client-java/wiki/How-to-aggregate-Multi-thread-process-execution-in-one-launch
