### ISSUE TITLE
How to create multiple-levels nested step in Java client

### ISSUE THREAD

**Issue by ansonliao** [reportportal/reportportal#1294]
Dear,
I can create two-levels nested step by the code below:
```java 
StepReporter stepReporter = Launch.currentLaunch().getStepReporter();
stepReporter.sendStep("Step level 1");
logger.info("Step level 2");
```

If I want to create more than 2-levels nested step, could you kindly help to provide the sample code?
```shell
step level 1
  |-- step level 2
    |-- step level 3
      |-- step level 4
      ...
        |-- step level N
```
Thanks.

**Comment by HardNorth** [comment]
@ansonliao You can't. At least with this class. This is a drawback of bad design. The class is going to be rewritten in version 6:
https://github.com/reportportal/client-java/issues/127

As a workaround you can use a `@Step` annotated method which accepts `Function` class as a parameter. And then do something like that:
```
step (()->{
// your step code here
});
```

To make `@Step` annotation works you need to run your tests with AspectJ agent as here:
https://github.com/reportportal/examples-java/blob/master/example-testng-logback/pom.xml#L86

And the example:
https://github.com/reportportal/examples-java/blob/master/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/step/NestedStepsTest.java

**Comment by ansonliao** [comment]
@HardNorth 
thanks for your reply, currently my implementation is this one with 2 level step.
https://github.com/reportportal/examples-java/blob/master/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/step/NestedStepsTest.java
