### ISSUE TITLE
[v5.3.3] looping the log Closing expired connection

### ISSUE THREAD

**Issue by Tonicku** [reportportal/reportportal#1295]
**Describe the bug**
Once the run test finished, the rp connection should close

**To Reproduce**
Report Portal installed using the docker-compose method

in a maven project,

Set ReportPortal.properties
Set TestNg
in pom repositirories  section
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>bintray-epam-reportportal</id>
            <name>bintray</name>
            <url>http://dl.bintray.com/epam/reportportal</url>
        </repository>

in pom dependencies section
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>${reportportal.agent.version}</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>${reportportal.logger.version}</version>
        </dependency>

add the listener in the testng xml llistener section
        <listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener"/>

run a test via TestNg xml via a job jenkins maven command

**Expected behavior**
once the run test is finished, closing the connection should be done without blocking the jenkins job

**Screenshots**
![image](https://user-images.githubusercontent.com/69209540/106363284-e2825a00-6327-11eb-8081-5aa73006794e.png)

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core)
 - Browser chrome
 - Version 88.0.4324.96

**Comment by Tonicku** [comment]
i updated the Java Agent... then it seems it fixed the issue.

**Comment by Tonicku** [comment]
the update didn't fix it
i am still having looping closing connections

2:02:10 [2021-01-31 01:00:27] [DEBUG] [com.epam.reportportal.service.Launch:38] - TestItem with ID = '11820eb2-9a31-4522-85fa-3f2471677965' successfully finished.
02:02:10 [2021-01-31 01:00:27] [DEBUG] [com.epam.reportportal.utils.SubscriptionUtils:104] - Finish test item completed
02:02:10 [2021-01-31 01:00:30] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:00:30] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:00:35] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:00:35] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:00:35] [DEBUG] [rp.org.apache.http.impl.conn.DefaultManagedHttpClientConnection:79] - http-outgoing-859: Close connection
02:02:10 [2021-01-31 01:00:35] [DEBUG] [rp.org.apache.http.impl.conn.DefaultManagedHttpClientConnection:79] - http-outgoing-860: Close connection
02:02:10 [2021-01-31 01:00:35] [DEBUG] [rp.org.apache.http.impl.conn.DefaultManagedHttpClientConnection:79] - http-outgoing-858: Close connection
02:02:10 [2021-01-31 01:00:40] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:00:40] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:00:45] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:00:45] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:00:50] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:00:50] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:00:55] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:00:55] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:01:00] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:01:00] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:01:05] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:01:05] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:01:10] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:01:10] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:01:15] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:01:15] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:01:20] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:01:20] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:01:25] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:01:25] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:01:30] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:01:30] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:01:35] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:01:35] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:01:40] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:01:40] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:01:45] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:01:45] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:01:50] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections
02:02:10 [2021-01-31 01:01:50] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:422] - Closing connections idle longer than 5000 MILLISECONDS
02:02:10 [2021-01-31 01:01:55] [DEBUG] [rp.org.apache.http.impl.conn.PoolingHttpClientConnectionManager:429] - Closing expired connections

**Comment by Tonicku** [comment]
after monitoring carefully, it closed it then end as as i see in the log

00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:49] - Thread 58 is dead. Let's close webdriver null
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:60] - No webdriver found for thread: 58 - nothing to close
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:49] - Thread 58 is dead. Let's close webdriver null
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:60] - No webdriver found for thread: 58 - nothing to close
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:49] - Thread 58 is dead. Let's close webdriver null
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:60] - No webdriver found for thread: 58 - nothing to close
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:49] - Thread 58 is dead. Let's close webdriver null
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:60] - No webdriver found for thread: 58 - nothing to close
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:49] - Thread 58 is dead. Let's close webdriver null
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:60] - No webdriver found for thread: 58 - nothing to close
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:49] - Thread 58 is dead. Let's close webdriver null
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:60] - No webdriver found for thread: 58 - nothing to close
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:49] - Thread 58 is dead. Let's close webdriver null
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:60] - No webdriver found for thread: 58 - nothing to close
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:49] - Thread 58 is dead. Let's close webdriver null
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:60] - No webdriver found for thread: 58 - nothing to close
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:49] - Thread 58 is dead. Let's close webdriver null
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:60] - No webdriver found for thread: 58 - nothing to close
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:49] - Thread 58 is dead. Let's close webdriver null
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:60] - No webdriver found for thread: 58 - nothing to close
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:49] - Thread 58 is dead. Let's close webdriver null
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:60] - No webdriver found for thread: 58 - nothing to close
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:49] - Thread 58 is dead. Let's close webdriver null
00:02:52 [2021-01-31 23:02:52] [INFO ] [com.codeborne.selenide.impl.UnusedWebdriversCleanupThread:60] - No webdriver found for thread: 58 - nothing to close

but it's taking time.

is there an additional configuration to take it less time ?

**Comment by MaryiaRymarchyk** [comment]
Hi @Tonicku is it still actual with the latest RP version? (RP 5.10.0 is the latest)
