### ISSUE TITLE
[v5] Notifications are not sent when notification rule set to "In case Launch has issues"

### ISSUE THREAD

**Issue by PeterRozum** [reportportal/reportportal#1299]
**Describe the bug**
ReportPortal notification emails are not sent in the case when notification rule is set to "In case Launch has issues" for launches containing failures.
Notifications work correctly with different "in case" setting. Confirmed to work OK with 'Always' and 'Launch has "To Investigate" items'.

**To Reproduce**
1. create notification rule with property 'in case' set to 'Launch has issues'
2. push new launch that contains failures and satisfies conditions for the notification created in previous step
3. notification is not sent

**Expected behavior**
The notification should be sent as the new launch contains failures and satisfies criteria of the notification rule.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 88.0.4324.146

**Additional context**
ReportPortal v5.3.4. Deployed on Linux using Compose. The bug was not present on v5.0.0.

**Comment by alena-babrova** [comment]
Hello @PeterRozum 

The bug has been fixed since version 5.7.0.
Please, upgrade your Reportportal application to later versions.
