### ISSUE TITLE
Add feature to update test results in scope of one launch [re-run functionality]

### ISSUE THREAD

**Issue by MikalaiBiazruchka** [reportportal/reportportal#13]
There is a need to have a chance to update test's result during rerun or other functionality.

**Comment by DzmitryHumianiuk** [comment]
This also was proposed as `re-run` feature.
when it possible to execute test cases, and add parameter for rp as `-rerun` or  `-rerun LAUNCH_ID` and update test case status in RP, if `failed/skipped` state changed to `passed`

**Comment by ksuglotova** [comment]
This idea was proposed @mva730 either at [#165](https://github.com/reportportal/reportportal/issues/165)

E.x.: we have failed launch. We collect all failures and run them again. After finishing we merge these results to our first launch.

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/reportportal/issues/264

will be completed with #264
