### ISSUE TITLE
Java Cucumber-4 TestNG: ScreenShot Scenario.embed -- Image file in RP UI is broken

### ISSUE THREAD

**Issue by arunkumar-muthusamy-personal** [reportportal/reportportal#1301]
Hi,

I'm using `Java+Cucumber-4+TestNG`. While attaching the screenshot to RP using Cucumber `Scenario.embed`, the image is broken/not getting displayed appropriately in ReportPortal UI. Where as the embedded image is displayed appropriately in the local cucumber html report.

`<cucumber.version>4.2.0</cucumber.version>`
```
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-cucumber4</artifactId>
            <version>5.0.0-BETA-9</version>
        </dependency>
```
Cucumber Plugin config in runner class: `"pretty", "com.epam.reportportal.cucumber.ScenarioReporter"`

**Expected behavior**
Screenshot should display appropriately in RP UI. 

**Screenshots**

```
            final byte[] screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
            Scenario.embed(screenshot, "image/png");
```
**Debug View:**
`com.epam.reportportal.cucumber.AbstractReporter:embedding`
![image](https://user-images.githubusercontent.com/74924947/107106348-bca9f900-67f0-11eb-8068-8f5b090afb99.png)

`com.epam.reportportal.cucumber.Utils:sendLog`
![image](https://user-images.githubusercontent.com/74924947/107106362-d2b7b980-67f0-11eb-95a9-d47e00ee53f5.png)

**Image in the RP UI:**
![image](https://user-images.githubusercontent.com/74924947/107106382-faa71d00-67f0-11eb-856c-aa99b2bf3994.png)

![image](https://user-images.githubusercontent.com/74924947/107106688-5b832500-67f2-11eb-9cb8-a64a021fb81f.png)

![image](https://user-images.githubusercontent.com/74924947/107106700-68077d80-67f2-11eb-92c0-8d090db293f9.png)

**Versions:**
 - Mac, chrome
 - Version of RP 
 ```
 Current version:API Service: 5.1.0;Index Service: 5.0.7;Authorization Service: 5.1.0;Service UI: 5.1.0;
 ```

I appreciate the help here!

**Comment by HardNorth** [comment]
Do not use BETA versions of the agent. It's `5.0.1` already: https://github.com/reportportal/agent-java-cucumber4/releases
