### ISSUE TITLE
traefik/gateway container errors - bump traefik image to v2.0.7 or higher

### ISSUE THREAD

**Issue by michaeIryan** [reportportal/reportportal#1302]
**Describe the bug**
Every 5-7 days our ReportPortal instance will go offline and can't be reached through the browser or api. After re-running the usual `docker-compose` command it comes back online until it eventually falls over again. After taking a look at the logs we have found the following from the gateway/traefik container:

```
[rpdockeruser@ip-10-102-65-89 ~]$ docker-compose -p reportportal logs --tail="all" gateway
Attaching to reportportal_gateway_1
gateway_1        | time="2021-02-06T00:05:06Z" level=info msg="Configuration loaded from flags."
gateway_1        | time="2021-02-08T00:31:30Z" level=error msg="accept tcp [::]:8080: accept4: too many open files" entryPointName=web
```

This issue has been resolved in v2.0.7 of traefik as per the PR here https://github.com/traefik/traefik/pull/5935 and the release: https://github.com/traefik/traefik/releases/tag/v2.0.7

Can you please look at increasing the version that ReportPortal uses from v2.0.5 to v2.0.7 or higher?

**Expected behavior**
Don't throw errors and start timing out on high connection loads.

**Screenshots**
N/A.

**Versions:**
 - Version of RP: 5.3.3

**Comment by evjlobanova** [comment]
@Cyberglamdring Hleb, could you please check this issue?

**Comment by Cyberglamdring** [comment]
Hello @michaeIryan,

You can use 2.0.7 of Traefik, we add this version with a new release next week for docker-compose. Also, we planned to update to version 2.4 with future releases.
