### ISSUE TITLE
Issue with Number of log lines

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1304]
**When my log lines are less, then AA does not work for me.**
...

**Irrespective of the number of lines provided, the AA should do the analysis of my subsequent runs **

Since we have the capability provided here to compare limited lines, we should be able to perform AA on trace with fewer lines as well. Please suggest if I am missing anything @DzmitryHumianiuk  @evjlobanova 
![image](https://user-images.githubusercontent.com/50797731/107752836-4869db00-6d45-11eb-9cbd-7b710c8d1cfc.png)

...
![LogLine](https://user-images.githubusercontent.com/50797731/107752764-30925700-6d45-11eb-9e09-e4380b9ef4f5.gif)

**Comment by evjlobanova** [comment]
fixed in 5.3.5
Please update to the latest version
