### ISSUE TITLE
Values inside <> are missing on report portal web

### ISSUE THREAD

**Issue by shatulsky** [reportportal/reportportal#1305]
Executing of this code
`_log.Trace($"Processing '{value}' with {strategy.GetType().Name} strategy");`

with ReportPortalAppender configured with the example from [https://github.com/reportportal/logger-net-log4net/blob/master/README.md](README) has the following result

![image](https://user-images.githubusercontent.com/22248285/107790500-7eb25500-6d5b-11eb-85f0-8895085c034b.png)

**Comment by nvborisenko** [comment]
@HardNorth @DzmitryHumianiuk @evjlobanova 
This issue is about that any text between `<` and `>` is hidden on UI.

Any opinions?

**Comment by evjlobanova** [comment]
@AmsterGet please check

**Comment by HardNorth** [comment]
@evjlobanova @nvborisenko @shatulsky @AmsterGet the same issue as here:
https://github.com/reportportal/reportportal/issues/1280

@shatulsky As I can see you made your own fix. Well, but you broken ability to format your output with HTML.

**Comment by DzmitryHumianiuk** [comment]
@HardNorth @shatulsky @nvborisenko
looks like this is specific of Markdown formatter and html tags escaping in HTML output.
`<>` symbols should be either escaped on logging side (replaced with `&gt;` and `&lt;`).
or outputted with code snipped wrapper as here:
```html
   ``` <div>my HTML code</>```
```
