### ISSUE TITLE
Can not consolidating test results as to who they can be viewed ?

### ISSUE THREAD

**Issue by shubham18-code** [reportportal/reportportal#1307]
**Describe the solution you'd like**
... I am using ReportPortal for Automation project, Tests are executing based on there environment (UNT, UAT, PERF).
 want to separate test results environment wise and want to show to specific team (UAT team, UNT team). In the current position i can not identify the tests results for the specific env.
can anyone help me in that ?
Thank you.

**Comment by shubham18-code** [comment]
Reportportal results grouped by test environment :
On our project we try to collect all tests results into reportportal. Since our project has several tests environments before the application is shipped to production i would like to display the results aggregated per environment. Like UNT, UAT, Production and group the results accordingly. Is there such feature available?

**Comment by evjlobanova** [comment]
Hello @shubham18-code 
thank you for your request. For now, there are 2 options for how you can resolve this problem:
- create a project for each env, but in this case, you can not create a dashboard for all projects
- the second option - to use filters. You can report launches with custom attributes in the format 'key: value' and via attribute, you can send info about env.
This helps you to create attribute-based filters. Also with the attribute, you will be able to build filters, and check launches for different environments.

In version 6 we are planning to implement groups of filters, that help users to manipulate filters even easily.
Connected with #517

**Comment by evjlobanova** [comment]
![image](https://user-images.githubusercontent.com/30413511/114995262-7e653180-9e52-11eb-925c-46e5b0d114d5.png)

![Uploading image.png…]()

**Comment by shubham18-code** [comment]
Hi @evjlobanova 
Thanks for reply, I implemented the same way the Filters. added env as attribute and create a dynamic launch name which really help me to create a dashboards.
