### ISSUE TITLE
System brings me the following error        java.lang.NoSuchMethodError: 'java.lang.String org.testng.ITestNGMethod.getQualifiedName()'

### ISSUE THREAD

**Issue by Artashes1996** [reportportal/reportportal#1313]
part of my Pom.xml

<repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>bintray-epam-reportportal</id>
            <name>bintray</name>
            <url>http://dl.bintray.com/epam/reportportal</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>5.0.9</version>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>5.0.3</version>
        </dependency>
 <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.1.0</version>
        </dependency>

**Comment by HardNorth** [comment]
Where? What you are trying to do? Any example to reproduce?

**Comment by HardNorth** [comment]
Abandoned
