### ISSUE TITLE
'Edit Defect Type' for all launches with same name is not changing the defect type in further launches

### ISSUE THREAD

**Issue by ivanhorin** [reportportal/reportportal#1314]
**When** I'm editing the defect type with changing similar items for all Launches with the same name **Then** an error appearing and same issue in further launch with same name, has 'To Investigate' status. 
![image](https://user-images.githubusercontent.com/25904584/108363107-3c769100-71fd-11eb-96a6-70bf14a33b62.png)

**Comment by evjlobanova** [comment]
Hello @ivanhorin could you please share logs and info from a dev toll in the browser?
@VolhaKarenko , could you please check this issue

**Comment by VolhaKarenko** [comment]
Didn't manage to reproduce the issue. 
@ivanhorin does the error occur when you select option "Launches with the same name" or after any other action?
Could you please give more detailed steps to reproduce and specify the RP version you are using?

**Comment by VolhaKarenko** [comment]
Closed due to inability to reproduce. Feel free to re-open in case of recurrence of the issue
