### ISSUE TITLE
Is reportportal going to stay on bintray/jcenter?

### ISSUE THREAD

**Issue by sleekweasel** [reportportal/reportportal#1320]
We've been evaluating ReportPortal, but see that it lives on bintray (jcenter/jfrog).

Please, you could indicate whether it's going to stay there, or will it be moving as a result of JFrog's decision?

Thanks

**Comment by fkrivsky** [comment]
Details on the Jfrog/Bintray/JCenter change - https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by HardNorth** [comment]
Ok, we have a solution. Here is our plan.

Starting from March 31st 2021 bintray is going to stop accepting new artifacts, but they will be still available by the old location till May 1st. As we already publish some artifacts using github packages we are going to extend this practice and publish all of them here in the "reportportal/reportportal" project. So https://github.com/reportportal/reportportal/ is going to be a single point for all our distributions. Stable java artifacts will be also replicated on Maven Central. This migration is going to happen in the first half of April.

Additionally we have plans to migrate our legacy artifacts to github and Maven Central till the 1st of May. We are going to save only stable versions, all BETA and other pre-release artifacts (unless they are not the only version available) are going to die with bintray. Major part of this work will be happening in the second half of April.

Hence ideally on the 1st of May we will have all artifact on github and all stable artifacts on Maven Central.

**Comment by v1-wizard** [comment]
Hi, guys. Do you have any updates about this issue? Where could i find instruction about migration? Our pipeline was broken according to bintray plans:
April 12th, 26th, 2021 | We will have some short service  brown-outs to remind users about the services that are going away on May  1st. (Specific hours will be advertised in the Bintray status page.)
-- | --

**Comment by HardNorth** [comment]
@v1-wizard Unfortunately their "short service brown-outs" means 8 hours downtime from 6 AM to 2 PM PDT. And they not only turned off bintray, but jcenter too, which was completely unexpected. We will try to speed-up our migration process to finish it till the end of the week. Since it will be Maven Central I expect no additional migration steps will be needed.

**Comment by v1-wizard** [comment]
@HardNorth thank you. We will wait and cross our fingers =)

**Comment by HardNorth** [comment]
At last, we've got first artifact published on Maven Central: https://search.maven.org/artifact/com.epam.reportportal/client-java/5.0.12/jar
All other will come in a few days after several checks.

**Comment by HardNorth** [comment]
Well, everything on its place, except some really old artifacts and beta versions, which weren't migrated.
