### ISSUE TITLE
[v5] Report Portal responding with 503s when api reaches max memory

### ISSUE THREAD

**Issue by grant-mccarriagher** [reportportal/reportportal#1321]
**Describe the bug**
We're running RP on k8s, and seeing 503 responses from the API for some period of time (maybe a few minutes) after the api reaches max memory and does a heap dump.

**To Reproduce**
Submit test data to RP until reportportal-api reaches max memory, and observe the responses.

**Expected behavior**
RP either gracefully keeps its memory low or doesn't lose responsiveness when recovering.

**Additional context**
RP 5.3.5. Using the official k8s charts. https://github.com/reportportal/kubernetes/tree/master/reportportal

We're basically using the same values as well, and have toyed with increasing api limits all the way up to 1500m CPU and 3GiB memory, with no effect. Memory climbs pretty rapidly all the way up to max, and then the 503s start.

**Comment by grant-mccarriagher** [comment]
Changing the default `jvmArgs` for `api` seems to have resolved this for us.

What it is in the official charts repo:
`"-Djava.security.egd=file:/dev/./urandom -XX:+UseG1GC -XX:MinRAMPercentage=60.0 -XX:InitiatingHeapOccupancyPercent=70 -XX:MaxRAMPercentage=90.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"`

What we changed it to:
`"-Djava.security.egd=file:/dev/./urandom -Xms500M -Xmx1G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"`

Values for `Xms` and `Xmx` are set at half of our min and max memory.

**Comment by Cyberglamdring** [comment]
@grant-mccarriagher, thanks. We will test `jvmArgs` in future release
