### ISSUE TITLE
Attach HTML Reports to Launches 

### ISSUE THREAD

**Issue by Bharadwaj-vana** [reportportal/reportportal#1322]
Hi Team,

I am generating HTML reports after my automation execution with test results, & I am trying to attach HTML report into Launch created in dashboard.  Can you please let me know how Can I achieve this. 

Please let me know Thanks in Advance ! 

Thanks
Bharadwaj

**Comment by Bharadwaj-vana** [comment]
Hi Team,

Please let me know if the above requested feature supports RP or Not ? Is it Possible to upload/ attach HTML to launches.

**Comment by MaryiaRymarchyk** [comment]
Hi @Bharadwaj-vana  it is possible to attach HTML file to item as well as other file formats.
![image](https://github.com/reportportal/reportportal/assets/122868739/7962634d-4725-42a0-8393-3555d4b40811)
Guide is here: https://reportportal.io/docs/dev-guides/AttachmentsGuide/#how-to-log-attachments-screenshots-on-java-agents
