### ISSUE TITLE
How to import html report  from Local to Report Portal

### ISSUE THREAD

**Issue by DEEPAKCHANDRA7** [reportportal/reportportal#1323]
Hi Team,

 

We are trying to import HTML report from Local that are created while running automation scripts to Report Portal dashboard for that specific launch. Please let me know how to do this Thanks ! 

 

PS:Html reports also contains screenshots(.jpg files) that took using Phyton !

**Comment by alena-babrova** [comment]
Hi @DEEPAKCHANDRA7,

We do not support anything like this, because HTML report is mainly for human readability - not for data transferring.
ReportPortal provides a plenty of clients that work with various platforms and send report results directly to RP via our API.
