### ISSUE TITLE
Jira Integration :- To show linked issue (Parent jira ticket)when posting a bug from RP.

### ISSUE THREAD

**Issue by Shivin89** [reportportal/reportportal#1325]
**Describe the bug**
With reference to the Slack channel communication with Yauheniya Labanava.
Given: I click on the Post Issue button
When: Jira Post issue Dialog box opens
And: I provide the Linked issue key on the field named “Link issue” See screenshot below.
THEN: The bug I created for failed step links to the actual story/Ticket for which these tests failed.
if a new Bug with “JIRA ID” in the name has been created in Jira - should be added to a story and the bug should be linked

In the first screenshot, as you can see I have an attribute @testcaseid = QUALITY-1618. This test case is failed, Now I want to open a bug for the failed step that you can see in the second screenshot.

In the third screenshot, I click on the Post bug link and start creating a bug for this failed step. Now I want this new bug to be linked to the @testcaseid =QUALITY-1618.

**Expected behavior**
The bug should be linked to the actual story Jira ID via Linked Issue or a new field option should be provided while posting a bug to link the bug to the parent ticket.

**Screenshots**
![image](https://user-images.githubusercontent.com/22401226/109699641-a9ffb700-7b45-11eb-907c-bc4e344d48bc.png)

![image](https://user-images.githubusercontent.com/22401226/109699929-05ca4000-7b46-11eb-9bb8-c1d81decb160.png)

![image](https://user-images.githubusercontent.com/22401226/109699462-73c23780-7b45-11eb-8928-269ca6cfd679.png)

**Versions:**
 - OS , Browser
 - Version of RP : Current version:API Service: 5.3.4;Index Service: 5.0.10;Authorization Service: 5.3.3;Service UI: 5.3.4;

**Comment by alena-babrova** [comment]
Hello @Shivin89 

Is the issue still relevant?
Do you need any assistance?

The "Post issue" functionality works like this:
If you post issue from some failed test, a BTS ticket is linked to that failed test and you can see the label
![image](https://user-images.githubusercontent.com/89584140/195845199-f8334a46-180e-43b1-86f0-92ad9c1e1c8a.png)

**Comment by alena-babrova** [comment]
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
