### ISSUE TITLE
Unable to investigate skipped tests

### ISSUE THREAD

**Issue by talgreen1** [reportportal/reportportal#1328]
I would like to be able to set a defect type for skipped tests. Currently - I'm able to do so only for failed tests.
I'm using Java & TestNG. I tried setting the 'rp.skipped.issue' to true / false - no change.

Is this possible?

10x.

![POWERPNT_3VmBhXTYVw](https://user-images.githubusercontent.com/26517162/109924800-849bb600-7cc9-11eb-97d1-ff2c836b6780.png)

**Comment by HardNorth** [comment]
No, it's not possible, since it's by design. The only way for you is to override this logic by yourself.

Your test was skipped due to `Before class` method failure and you can see `To Investigate` on the method.
