### ISSUE TITLE
[v5]reportportal/dev-deployment/start.sh  doesn't work properly on mac

### ISSUE THREAD

**Issue by hnm372** [reportportal/reportportal#1330]
**Describe the bug**
When I use the sh start.sh command, it cannot be executed normally，I will be very grateful for your help！

**Error logs**
admin@C02D853YML85 dev-deployment % sh start.sh
Already on 'develop'
Your branch is up to date with 'origin/develop'.
Already up to date.

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 449ms
Already on 'develop'
Your branch is up to date with 'origin/develop'.
Already up to date.
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Already on 'develop'
Your branch is up to date with 'origin/develop'.
Already up to date.
Already on 'develop'
Your branch is up to date with 'origin/develop'.
Already up to date.
ERROR: build path /Users/admin/IdeaProjects/reportportal/dev-deployment/service-authorization/build/libs either does not exist, is not accessible, or is not a valid URL.

**Desktop :**
 - OS: Mac OS 10.15.7
 - Docker version 20.10.2, build 2291f61
 - Java version 15.0.2

**Comment by MaryiaRymarchyk** [comment]
Hello @hnm372,
Sorry for the silence – a lot’s been going on at RP team.
Please check out our page with deployment guide for Mac and  let us know if you have any questions/issues during installation.

**Comment by MaryiaRymarchyk** [comment]
Hello @hnm372, 
As we haven't received a reply from you, we'll close the issue for now.
If  the issue still relevant, just get in touch.

By the way we have successful result of installation RP 7.4 on Mac.
The guide is here: https://reportportal.io/docs/installation-steps/DeployWithDockerOnLinuxMac
