### ISSUE TITLE
After RP ugrade to 3.0.1 impossible to open single 'To investigate' item

### ISSUE THREAD

**Issue by maaxlee** [reportportal/reportportal#134]
**Current version**: Gateway Service: 3.0.0;
UI Service: 3.0.1;Rally Service: 3.0.0;Authorization Service: 3.0.0;
API Service: 3.0.0;Jira Service: 3.0.0;Registry Service: 3.0.0;

**Steps:**

1) Open launch with failed TCs (
[screen1](https://cloud.githubusercontent.com/assets/6975495/26347402/2949f1a2-3fb2-11e7-88a1-e55d98486eda.png)
2) Press number on 'To investigate' column
Expected result:
Item's screen with logs is opened

3) Actual result:
Item not found
![screen2](https://cloud.githubusercontent.com/assets/6975495/26347475/60d6af3e-3fb2-11e7-93f0-dbe238cedd86.png)

Network error is shown in Browser's console 
![screen3](https://cloud.githubusercontent.com/assets/6975495/26347602/bfd049a0-3fb2-11e7-97b5-403bd591a53f.png)

NOTE: If item is opened not by clicking on number but on test name then it opens correctly 
![screen4](https://cloud.githubusercontent.com/assets/6975495/26347720/1baeb608-3fb3-11e7-8698-0bed76239e51.png)

**Comment by avarabyeu** [comment]
@maaxlee could you please make sure you've cleared browser cache

**Comment by maaxlee** [comment]
I tried to clear cache and use incognito mode/another browser but it didn't help

**Comment by avarabyeu** [comment]
@maaxlee should be fixed in 3.0.3/3.0.4. Could you please check?

**Comment by DzmitryHumianiuk** [comment]
fixed
