### ISSUE TITLE
Fixture level steps are displayed as tests

### ISSUE THREAD

**Issue by Bakanych** [reportportal/reportportal#1341]
Hi all,
I'm using nunit tests with step-like notations to have better report details.
I've found that steps that reported from fixture level methods, e.g. `OneTimeSetUp` and `OneTimeSetUp` are displayed as tests in report portal suite list.

Repro steps:
- Run tests from https://github.com/Bakanych/example-net-nunit/blob/master/src/Example/Tests/Class5.cs
- Open debug run from report portal: 
![image](https://user-images.githubusercontent.com/17307409/111576008-96fa1180-87ea-11eb-804e-520d13ffb742.png)
- Click on `Class5`
- Notice fixture level steps are displayed among tests:
![image](https://user-images.githubusercontent.com/17307409/111576271-21db0c00-87eb-11eb-996c-a237e1606b96.png)

**Comment by MaryiaRymarchyk** [comment]
HI @Bakanych, sorry for silence, 
if you talking about "Before" and "After" methods - it works as designed. 
Before and After methods are in the same list with test items but they have different method type (as on my screen below). 
Let me know if you have other questions or ticket can be closed.
![image](https://user-images.githubusercontent.com/122868739/234855008-30bc0588-26e3-4220-a304-9d05d458c5ad.png)

**Comment by nvborisenko** [comment]
@Bakanych will https://github.com/reportportal/commons-net/issues/140 work for you? Thus you will be able to specify concrete LogScope type like on the screenshot from @MaryiaRymarchyk ?

**Comment by MaryiaRymarchyk** [comment]
Hi @Bakanych , as we haven't received a reply from you, we'll close the issue for now.
If  the issue still relevant, just get in touch.

**Comment by alena-babrova** [comment]
Dear @nvborisenko,

Could you please tell me what the plan is for the issue? Are we going to fix it in our .NET client?

**Comment by alena-babrova** [comment]
Dear @nvborisenko,

As we haven't received a reply from you, we'll close the issue for now.
If you still have an idea about how to fix, please do not hesitate to reopen the ticket with details and let's discuss what, where and who should handle it.
Thank you!
