### ISSUE TITLE
Increase Number of items per page

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1343]
I have huge number of cases running on daily basis. 
![image](https://user-images.githubusercontent.com/50797731/111995874-7362fe00-8b3f-11eb-8019-194ae5e72df6.png)

But from what I see, there is a limitation on number of items that can be displayed per page to 300 
![image](https://user-images.githubusercontent.com/50797731/111995985-94c3ea00-8b3f-11eb-9108-42529609e9ac.png)

Need a little enhancement to display the count uptil few thousands mayb ?

**Comment by omkarnathsingh** [comment]
@priyankachaturvedi30 That's not very ideal, the webpage will be too heavy to display so many test launches. you can apply filters to view what data you need. Also from API perspective it will cause slowness.

**Comment by priyankachaturvedi30** [comment]
Understood.! No problm @omkarnathsingh
