### ISSUE TITLE
Issue with restoring backup on Windows

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1345]
I am using RP - 5.3.5 version. 
I tried taking backup of my postgres container with specified steps in documentation but when I tried restoring it I got the following issues - 
![image](https://user-images.githubusercontent.com/50797731/112172479-c2ca2c80-8c1a-11eb-990d-c2f8c1472b5f.png)

I am trying to retain backup on my windows enviornment. I very well remember it used to work for me previously. Does it have something to do with screenshot (Just thinking out loud - because previously I was not logging failure screenshots to RP)? Please Suggest? @DzmitryHumianiuk  @evjlobanova

**Comment by Cyberglamdring** [comment]
Hello @priyankachaturvedi30,

Before restoring we recommend stopping reportportal services:
```bash
docker stop reportportal_api_1 reportportal_index_1 reportportal_analyzer_1 reportportal_ui_1 reportportal_uat_1
```
After restoring check database tables and compare them.

About `invalid command \<command>`. You can get these messages when a copy statement fails, but the loading of the dump continues. This message is a false alarm.
