### ISSUE TITLE
Does General Setting mentioned on RP ui applicable for baselines ?

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1347]
I see the following settings mentioned on report portal UI under settings -
![image](https://user-images.githubusercontent.com/50797731/112597999-f502a680-8e33-11eb-835d-51dab1dcced7.png)

Curious to understand whether these would be applicable for Baselines as well. for eg: Keep Launches/ Keep logs - tend to remove data longer than a specified period. Would that delete baselines as well which might me created with those launches ?

**Comment by evjlobanova** [comment]
@priyankachaturvedi30 for now all data is removed from reportportal.
We are planning to implement the Release Lock feature #674- which helps to save baselines in the app. 
Approximate ETA for feature ver 6.
Does this functionality cover your needs?

**Comment by priyankachaturvedi30** [comment]
Yes @evjlobanova
