### ISSUE TITLE
[5.3.5] Direct link to dashboards are not working

### ISSUE THREAD

**Issue by ersuniljoshi** [reportportal/reportportal#1349]
**Describe the bug**
try to open a dashboard directly
Example: http://reportio.xxxx.com:8080/ui/#my_regression/dashboard/1234

**Expected behavior**
Dashboard should open...

**Actual behavior**
Nothing loads up in the dashboard.

**Screenshots**
If applicable

**Versions:**
 - Not OS Specific, Any browser.
 - Version of RP- Current version:API Service: 5.3.5;Index Service: 5.0.10;Authorization Service: 5.3.5;Service UI: 5.3.5; 

**Note: It was working fine with RP 5.3.3**

**Comment by evjlobanova** [comment]
@VolhaKarenko please recheck

**Comment by VolhaKarenko** [comment]
Couldn't reproduce the issue
@ersuniljoshi are there any errors in console on get dashboard? is it reproducible with all dashboards?

**Comment by ersuniljoshi** [comment]
@VolhaKarenko yes we can reproduce this everytime after we upgraded to RP 5.3.5 ...  No console errors.

**Comment by VolhaKarenko** [comment]
@ersuniljoshi could you tell how many dashboards you have on the project?

**Comment by ersuniljoshi** [comment]
@VolhaKarenko  We have 50+ dashboards. Also another thing when we are adding new dashboard( we found it now only). AS soon as we try add a widget Dashboard name disappears.

![Screenshot 2021-04-03 at 15 11 03](https://user-images.githubusercontent.com/4852488/113474666-eac55580-948e-11eb-9b5c-5b097e8d8f07.png)

**Comment by VolhaKarenko** [comment]
@ersuniljoshi this is a known issue, occurs due to large number of dashboards (50+). We have extended this limitation to 300 dashboards in version 5.4
