### ISSUE TITLE
Page is overlayed when opening failure with specific message

### ISSUE THREAD

**Issue by idancie** [reportportal/reportportal#135]
RP Version: 3.0.0

Steps:

1. Create failing Test Case;
2. In error message log "url("https://somehostname.com/assets/content/images/KB/p/PAN_183660338-1470x827.jpg")";
3. Launch test with RP;
4. After completion in launch open 'To Investigate' item;
5. See that page is overlayed and you can't interact with page elements;

Screenshots are attached
<img width="1280" alt="2017-05-20 17 30 59" src="https://cloud.githubusercontent.com/assets/2893447/26350249/354b2832-3fbb-11e7-8a3e-75c962af6c82.png">
<img width="852" alt="2017-05-23 13 17 35" src="https://cloud.githubusercontent.com/assets/2893447/26350251/371c6cca-3fbb-11e7-9447-7bba94a22df7.png">
<img width="877" alt="2017-05-23 13 19 04" src="https://cloud.githubusercontent.com/assets/2893447/26350252/38e9bf80-3fbb-11e7-8f63-b3ef8b6e0b69.png">

skype: hanna.vashchilo

**Comment by lexecon** [comment]
Please use markdown syntax like [this](https://simplemde.com/markdown-guide)
