### ISSUE TITLE
Link issue as part of Edit Defects dialog

### ISSUE THREAD

**Issue by tmatveyeva** [reportportal/reportportal#1352]
**Describe the solution you'd like**
...
Inside the run
1. Select tests I would like to edit
2. Click Edit defects

Be able to provide in same dialog defect type, comment and Jira ticket link

**Is your feature request related to a problem? Please describe.**
...
When analysing results, especially in bulks, for each defects that I marked as product bug I would like to link a bug, currently these two things are done from two different places, as result I have to do:
1. Select tests
2. Select Link issue and provide link
3. Select tests again
4. Select Edit Defects

Instead I would like to be able to do same in two steps

**Comment by Shakevg** [comment]
@tmatveyeva You can perform now your actions more quickly just changing the order of steps if it fits your needs (without double tests selection):
1. Select tests
2. Select Edit Defects
3. Select defect type and set description
4. Select Link issue and provide a link

**Comment by Kozovskaya** [comment]
Hello @tmatveyeva, 
@Shakevg is right! These steps can be performed in "Make decision' modal choosing the 'Edit defects' option in 'Actions'.
![image](https://github.com/reportportal/reportportal/assets/106231727/29311285-9518-4bba-bd46-cf48e57b10b9)

I will close the issue!
In case any questions regarding the issue, feel free to reopen it with comment!
