### ISSUE TITLE
Sequence of steps are interchanged in Report Portal

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1354]
We have observed at times that the sequence in which steps are logged on RP is not sequential. This usually happens for skipped cases. Attached screenshot for the same. We feel that this is because the time logged against all such steps is the same. We verified that on RP, time is displayed up to seconds, however, through our logging we are sending time up to milliseconds. Can there be a possibility that since RP is just considering time till seconds and not until milliseconds, this is causing this incorrect sequence? @evjlobanova @DzmitryHumianiuk 
![image](https://user-images.githubusercontent.com/50797731/113258311-6d141500-92e9-11eb-82de-e9d8656e4044.png)

**Comment by DzmitryHumianiuk** [comment]
@priyankachaturvedi30 ReportPortal consider time in milliseconds.
you can see it in Network tab of your browser, once list of items updated, find a start time value.
But UI shows it only in seconds, but sorts it according to milliseconds on the backend first.

Most likely your framework sends all these items with the equal timestamp in start time, thus for server side filtering there is 
no any difference in them. And the items are displayed according to the order in which they entered the database.


![image](https://user-images.githubusercontent.com/11332788/113300798-fab22d80-9306-11eb-8424-7ec981b25912.png)
