### ISSUE TITLE
[5.3.5] Test total on launch keeps updating after test run is finished

### ISSUE THREAD

**Issue by robholt** [reportportal/reportportal#1355]
I've observed that the total number of tests in a launch, along with number of failed/passed/skipped tests, can continue to change long after the actual test run itself has finished the launch and completed. The total number only goes up, but the number of failed tests usually goes down. Eventually these totals converge on the real test results, but that sometimes takes over 30 minutes. The faster a test run is (more tests per minute) the worse the problem is.

I noticed this behavior in an app we have that uses the Report Portal API to retrieve launch information after the test run is done. The app is using the `/api/v1/{project_name}/launch` and `/api/v1/{project_name}/launch/{launch_id}` API endpoints.

I saw this behavior very infrequently on v5 previously, but after upgrading to 5.3.5 it became much more frequent, affecting almost all test runs.

**Comment by MaryiaRymarchyk** [comment]
Hi @robholt sorry for the silence, is the issue still valid ? It seems to be related to performance. Could you please try it with latest version ([23.1](https://github.com/reportportal/reportportal/releases/tag/v23.1)   )?

**Comment by MaryiaRymarchyk** [comment]
@robholt,  as we haven't received a reply from you, we'll close the issue for now.
In case you still have the issue - just get in touch.
