### ISSUE TITLE
Unable to log lengthy string to report portal

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1359]
I am using bdd framework which involves the usage of lengthy string. I have observed facing error while pushing logs when string length is lenghty. In case, partial logs are populated on RP. Sample string which was not logged at RP :

_Given I search and validate test case "${data[TestCaseNo]}" using cashflow basic search details for reference numbers "${data[ReferenceNumbers]}" with value date "${data[ValueDate]}" currency "${data[Currency]}" legal entity "${data[LegalEntity]}" account name "${data[AccountName]}" amount "${data[Amount]}" and advance search details with source system "${data[SourceSystem]}" source side "${data[SourceSide]}" book "${data[Book]}" product type "${data[ProductType]}" load time date "${data[LoadTimeDate]}" ordering customer "${data[OrderingCustomer]}" and detail match created date "${data[DetailMatchCreatedDate]}" trade type "${data[TradeType]}" late trade indicator "${data[LateTradeIndicator]}" match status "${data[MatchStatus]}" overall status "${data[OverallStatus]}" cashflow active status "${data[CashflowActiveStatus]}" manual adjustment type "${data[ManualAdjustmentType]}" match type "${data[MatchType]}" match id "${data[MatchID]}" for each data record_

Considering the error i understand there is some kind of check at string level.
![image](https://user-images.githubusercontent.com/50797731/113850644-4efe5700-97b8-11eb-8313-61ea956c517f.png)
 Can there be some property through which we can control the number of characters per line that can be pushed to RP?

**Comment by priyankachaturvedi30** [comment]
@DzmitryHumianiuk  : Did we get a chance to check this?

**Comment by DzmitryHumianiuk** [comment]
@priyankachaturvedi30 There is no much of the sense to have such a huge name for test case.
First of all, just because of it useless on UI while you browsing. And UI will cut it with "..." at the end to keep UX stable.
Second, it's not really readable. If you need this size of info, that add it to the description.
Third, are the technical limitations, mentioned above.

**Comment by priyankachaturvedi30** [comment]
Agreed @DzmitryHumianiuk : Just to add here, this is not a test case name but a test step. so there are chances that my feature\meta may contain such lengthy steps. RP was not logging such steps. So was thinking out loud what best can we do to atleast log such steps. We have multiple such instances where we have lengthy javascripts which gets evaluated. All such steps would never be logged in RP. Would it be possible to at least trim with "..." and log once it goes beyond 1024 rather than completely not logging it?

**Comment by DzmitryHumianiuk** [comment]
@priyankachaturvedi30 under `test step` you mean NestedStep at log view?

like here?
![image](https://user-images.githubusercontent.com/11332788/114898355-b05aa180-9e1a-11eb-8384-008acca4af85.png)

**Comment by priyankachaturvedi30** [comment]
Yes @DzmitryHumianiuk, It's not logging the entire step itself there. Additionally if there a failure for that step, the stacktrace also goes missing along with the step.
![Missing Step](https://user-images.githubusercontent.com/50797731/114978795-653aa000-9ea7-11eb-88df-0d9b5a1408ff.png)

**Comment by evjlobanova** [comment]
Nested Step name length has a limit 1024 symbols. The remaining part should be reported as logs. Which agent do you use?
Could you please expand on "Additionally if there a failure for that step, the stacktrace also goes missing along with the step"?

**Comment by priyankachaturvedi30** [comment]
We use - https://github.com/reportportal/client-java
So, @evjlobanova : if you'll have a close look at the screenshot
![image](https://user-images.githubusercontent.com/50797731/115390005-64817100-a1fb-11eb-9f60-4d0106bcd761.png)

Line 378 is missing in RP logs, however, all other lines are been captured. So it was a lenghty step at line numner 378 which failed and was not captured in the logs.

**Comment by HardNorth** [comment]
@priyankachaturvedi30 We went out of the original topic. Can you please open a separate feature request for this?
