### ISSUE TITLE
Add a filter for linked bugs

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [reportportal/reportportal#136]
Could you please add a filter for linked bugs, so it will be possible to see all failed tests caused by one issue

by Katsiaryna_Kulbitskaya in USERVIOCE

**Comment by DzmitryHumianiuk** [comment]
Equal to grouping

**Comment by DzmitryHumianiuk** [comment]
sub-launch widget,
which will make grouping, based on assigned BTS ticket

**Comment by ailjushkin** [comment]
Hi, could you please also implement an ability to filter out failed tests that are not linked with jira issues or vice versa?

**Comment by DzmitryHumianiuk** [comment]
>Hi, could you please also implement an ability to filter out failed tests that are not linked with jira issues or vice versa?
@evjlobanova please convert it into the story.
for UI and WS.
and add it to the upcoming sprint.

**Comment by evjlobanova** [comment]
the filter for linked bugs will be added with 4.0
