### ISSUE TITLE
AWS elastic search usage

### ISSUE THREAD

**Issue by QualoZe0t** [reportportal/reportportal#1369]
Hi,
I have deployed reportportal k8s version based on your docu. I have replaced all service like (minio,Postgres,elastic,rabbit) with AWS managed services. After deploying helm chart i have checked if indexes will be present on elastic search but based on the documentation present here https://github.com/reportportal/kubernetes/tree/master/reportportal#4-elasticsearch-installation I am unable to see any indexes due to missing authentification . I am using AWS elastic with master authentification. Is there any extra thing which have to be added to be able logging ?

```
elasticsearch:
  installdep:
    enable: false
  endpoint: <AWS ES domain Endpoint URL>
```
I have tried to send payload but by default aws is expecting to be authentificated .. should by enabled anonymous mode ? or should I modify helm chart to be able use credentials ?

**Comment by QualoZe0t** [comment]
just idea if this could help:
edit file: ./analyzer-statefulset.yaml
```
        - name: ES_HOSTS
          value: "{{ .Values.elasticsearch.endpoint }}"
```
Add to the endpoint authentification varuable from values.yaml ( taken from external secret or passed directly from var

**Comment by QualoZe0t** [comment]
I have executed  test:
Added credential login:password into elastic 
example: analyzer-statefulset.yaml
```
        - name: ES_HOSTS
          value: "https://{{ .Values.elasticsearch.user }}:{{ .Values.elasticsearch.password }}@{{ .Values.elasticsearch.endpoint }}/"
```

changed values.yaml
```
elasticsearch:
  SecretName: ""
  installdep:
    enable: false
  endpoint: search-reportportal-dev-XX.eu-central-1.es.amazonaws.com
  user: admin
  password: Password1?
```
after deployment helm received in logs - received in analyzer-0  .. particualar logs ..elasticsearch is requesting in passw:
upper character, little character,number,special character
```
ValueError: invalid literal for int() with base 10: 'Reportportal1'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
/venv/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Traceback (most recent call last):
  File "app.py", line 260, in <module>
    es_client = EsClient(APP_CONFIG, SEARCH_CONFIG)
  File "./commons/esclient.py", line 41, in __init__
    self.es_client = self.create_es_client(app_config)
  File "./commons/esclient.py", line 66, in create_es_client
    client_key=app_config["esClientKey"])
  File "/venv/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 206, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/venv/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 44, in _normalize_hosts
    if parsed_url.port:
  File "/usr/local/lib/python3.7/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'Reportportal1'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
```

now this message is still repeating isn't this a bug ?

**Comment by MariyaIvanina** [comment]
@QualoZe0t 
Hi!

You need to specify the port as well here:
` - name: ES_HOSTS
          value: "https://{{ .Values.elasticsearch.user }}:{{ .Values.elasticsearch.password }}@{{ .Values.elasticsearch.endpoint }}:{{<port>}}/"`

And as well your username and user password shouldn't have characters @, /, \ due to the Elasticsearch client library (python) we use.
