### ISSUE TITLE
Sometimes logs for some tests are missed

### ISSUE THREAD

**Issue by daroshchanka** [reportportal/reportportal#137]
We have api test-suite (300 tests in 3 minutes 1 thread).
Sometimes autoanalysis doesn't work (test status not populated) for failed tests.
We found that it happends because of missed logs for this test.
**All logs always present in console appender!** but sometimes missed in RP
When some logs missed no any specific RP errors found in console during test run.

See history of runs for test
233 - all logs for test missed
![image](https://cloud.githubusercontent.com/assets/28945630/26441301/a00cf1c2-4138-11e7-868f-3e47a9cc3e85.png)

236 - all logs present
![image](https://cloud.githubusercontent.com/assets/28945630/26441316/ad6eba58-4138-11e7-9ff0-d3d3e3a6fa0b.png)

242 - only stacktrace..
![image](https://cloud.githubusercontent.com/assets/28945630/26441330/baa44e7c-4138-11e7-8dbd-5dc6374607e4.png)

**NOTE: logs may be missed for any test (not only failed).**

RP: 

> Current version: Gateway Service: 3.0.0;UI Service: 3.0.1;Rally Service: 3.0.0;Authorization Service: 3.0.0;API Service: 3.0.0;Jira Service: 3.0.0;Registry Service: 3.0.0;

We use
```
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.9.13.6</version>
        </dependency>
	<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>3.0.0</version>
        </dependency>
```
Listener defined in _maven-surefire-plugin(2.17)_

**Comment by DzmitryHumianiuk** [comment]
@daroshchanka 3.0.2 with fixes available
https://bintray.com/epam/reportportal/agent-java-testng

try it and re-open ticket, if still occurs.
```xml
	<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>3.0.2</version>
        </dependency>
```

**Comment by avarabyeu** [comment]
@daroshchanka Please, make sure you are logging when test in 'started' state. For example, consider the following situation:
```
RP Listener marks test as started -> tests is executing -> RP listener marks test as finished
```
You should log when test is 'started'
Another case:

```
RP Listener marks test as started -> tests is executing -> RP listener marks test as finished -> Something is being logged from another listener
```
In this case logs are not being reported to ReportPortal

**Comment by daroshchanka** [comment]
@avarabyeu I have logs in test-body.
I have different results for same conditions. Sometimes it works, sometimes no.
Update to agent-java-testng 3.0.2 not solved the problem.

@DzmitryHumianiuk, could you please reopen? seems I have no rights to do it myself.

**Comment by avarabyeu** [comment]
@daroshchanka could you please prepare some demo project in order to reproduce issue?

**Comment by DzmitryHumianiuk** [comment]
@daroshchanka up

**Comment by daroshchanka** [comment]
@avarabyeu, sorry for the long response..
I'll provide you updates next week. I am on vacation until September 11th.

**Comment by daroshchanka** [comment]
@avarabyeu, we cannot reproduce this problem any more (last 2-3 weeks).
client:
```
<dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.11</version>
</dependency>
<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>3.0.3</version>
</dependency>
<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>3.0.1</version>
</dependency>
```
server:
```
Current version: API Service: 3.2.0; Service Index: 3.1.1; Authorization Service: 3.2.0; Service UI: 3.2.4;
```

I think we can close this. Thank you.
