### ISSUE TITLE
[v5] How to end my Automation gracefully if Report Portal server goes down

### ISSUE THREAD

**Issue by anshu781126** [reportportal/reportportal#1371]
https://github.com/reportportal/client-java

using this client java-client to send logs to report portal. If say in some scenario Report Portal server goes down then my Automation Run still continues to execute the tests and the log messages are not persisted in Report Portal. Is there a way by which I can ensure that I can check whether Report Portal is running or not and accordingly stop my Automation tests if its down.

I found something called as **rp.reporting.callback** but not sure if it can help me as I am not clear with the example given.
Also, to keep you on same page I am using aync approach to send logs to Report Portal.

Intent here is I dont want to lose the data (logs) which will be required in subsequent Automation runs by Report Portal for Analysis. For that one of failure runs; I can definitely manually Analyze the failures but I dont wish to take that route.

Also, if I get a way to manage and check that Report Portal is up or not; then in case if its down then there is high probability of my Automation code not knowing the details of which items are persisted in Report Portal. Is there a way to gracefully end the Report Portal launch in case of such failure instance. So that what all is logged RP is not in interrupted state and gets AA.

@DzmitryHumianiuk @evjlobanova @MariyaIvanina

**Comment by anshu781126** [comment]
Also i tried setting async as false still couldn't see any difference in behavior. Was playing with this setting in order to capture the failure of RP server going down so that Automation can stop itself at the same point. Which might help to keep logs on RP end and logs at Automation end in sync. We can resume the run of remaining tests when the RP server is up.

**Comment by DzmitryHumianiuk** [comment]
@anshu781126, well... it's a controversial functionality.
We build the app with idea of 99% of availability. I would rather focus on instance stability, rather then on shutting down automation during execution.

In other hand, sometimes it makes sense to record data on local env during execution, and push it on server once particular part/suite is done. But this brings another challenge, if say process of automation failed itself, then you need some sort of separated thread, which will monitor and upload created data.

I don't see a simple answer at this point.

cc @HardNorth

**Comment by anshu781126** [comment]
Whats the easiest way to know if the Report Portal server is down ?

**Comment by DzmitryHumianiuk** [comment]
@anshu781126 https://SERVER/health returns server status.

Errors will appear at `service-api` container. Not sure it's accessible from outside.

**Comment by anshu781126** [comment]
This call max waits for 20-21 seconds ? I have been trying to make this timeout configurable, in spite of me setting it to 60 seconds it fails at 20-21 seconds. Is this something which is expected behavior ?

**Comment by DzmitryHumianiuk** [comment]
@anshu781126 yes, it is.
API always has a limited capacity of open connections.
We have a rule to close requests which stays longer then 20 secs.

This prevents hang-ups of many connections left after the automation was interrupted.

**Comment by MaryiaRymarchyk** [comment]
Hi @anshu781126  have you managed to solve this issue?
any other questions?

**Comment by MaryiaRymarchyk** [comment]
@anshu781126 Seems that there are no remain actions from ReportPortal side. just get in touch.
Therefore, ticket will be closed.
If you have open questions - just get in touch.
