### ISSUE TITLE
ReportPortalClient#startTestItem ignores description for log items

### ISSUE THREAD

**Issue by slihelly** [reportportal/reportportal#1372]
**Summary:** When using agent-java-cucumber6 default `ScenarioReporter`, `com.epam.reportportal.service.ReportPortalClient#startTestItem(java.lang.String, com.epam.ta.reportportal.ws.model.StartTestItemRQ)` client call is used to post scenario step as **log item**. When scenario is using multi-line arguments (doc strings, data tables), they are passed as StartTestItemRQ description. This is composed correctly in reported, but then doesn't appear in report portal log item itself.

**How to reproduce:**
1. Use unit test from in agent-java-cucumber6: `com.epam.reportportal.cucumber.ParameterStepReporterTest#verify_docstring_parameters`
2. Use `com.epam.reportportal.cucumber.ScenarioReporter` as reporter
3. Execute test case having doc string as parameter with reporting to Report Portal
4. Validate respective scenario step(mapped to RP log item) description

**Actual result:**
![image](https://user-images.githubusercontent.com/18449052/115239725-b789f400-a127-11eb-8e21-4d3fe551c16d.png)

Report portal version: 5.3.5
Agent version: agent-java-cucumber6 5.0.1
(reproduces on 5.0.5)

**Comment by evjlobanova** [comment]
In version 5 Logical steps on Log view don't have a description on UI. In version 5 we do not plan to change the logic for it.
This information can be sent as a log with level info (f.e) to the needed logical step.

**Comment by HardNorth** [comment]
@evjlobanova Well, this actually already was implemented in the latest agent versions.
