### ISSUE TITLE
[v5] Performance degradation on launches deletion

### ISSUE THREAD

**Issue by Invictum** [reportportal/reportportal#1374]
**Describe the bug**
After upgrade from 5.3.3 to 5.3.5, we are experiencing significant performance degradation on launch deletion operations. Single launch deletion may take up to 5 minutes. Interesting that for batch deletion issue isn't always reproduced.

On deletion`postgres` container performs intensive reads operations and utilizes disk to 100%
Also deadlock errors are observed in logs.

```
2021-04-20 12:53:43.124 UTC [2443] ERROR:  deadlock detected
2021-04-20 12:53:43.124 UTC [2443] DETAIL:  Process 2443 waits for AccessExclusiveLock on tuple (974740,60) of relation 17388 of database 16384; blocked by process 2330.
	Process 2330 waits for ShareLock on transaction 360066178; blocked by process 2281.
	Process 2281 waits for ShareLock on transaction 360066181; blocked by process 2630.
	Process 2630 waits for AccessExclusiveLock on tuple (974740,60) of relation 17388 of database 16384; blocked by process 2443.
	Process 2443: SELECT t.item_id FROM test_item t WHERE t.unique_id = $1 AND t.launch_id = $2  AND t.parent_id = $3 AND t.item_id != $4 AND t.has_stats AND t.retry_of IS NULL ORDER BY t.start_time DESC, t.item_id DESC LIMIT 1 FOR UPDATE
	Process 2330: SELECT t.item_id FROM test_item t WHERE t.unique_id = $1 AND t.launch_id = $2  AND t.parent_id = $3 AND t.item_id != $4 AND t.has_stats AND t.retry_of IS NULL ORDER BY t.start_time DESC, t.item_id DESC LIMIT 1 FOR UPDATE
	Process 2281: SELECT t.item_id FROM test_item t WHERE t.unique_id = $1 AND t.launch_id = $2  AND t.parent_id = $3 AND t.item_id != $4 AND t.has_stats AND t.retry_of IS NULL ORDER BY t.start_time DESC, t.item_id DESC LIMIT 1 FOR UPDATE
	Process 2630: SELECT t.item_id FROM test_item t WHERE t.unique_id = $1 AND t.launch_id = $2  AND t.parent_id = $3 AND t.item_id != $4 AND t.has_stats AND t.retry_of IS NULL ORDER BY t.start_time DESC, t.item_id DESC LIMIT 1 FOR UPDATE
2021-04-20 12:53:43.124 UTC [2443] HINT:  See server log for query details.
2021-04-20 12:53:43.124 UTC [2443] STATEMENT:  SELECT t.item_id FROM test_item t WHERE t.unique_id = $1 AND t.launch_id = $2  AND t.parent_id = $3 AND t.item_id != $4 AND t.has_stats AND t.retry_of IS NULL ORDER BY t.start_time DESC, t.item_id DESC LIMIT 1 FOR UPDATE
```

**To Reproduce**
Remove launch manually via UI

**Expected behavior**
Launch is removed within several seconds as it was in v5.3.3

**Screenshots**

Disk reads graph

![Screen Shot 2021-04-20 at 11 13 10 AM](https://user-images.githubusercontent.com/4653335/115433444-308f5700-a1cd-11eb-849b-31ebc84088aa.png)

**Additional context**
RP deployed on a single host via docker-compose. HDD is used as underlying storage.
Each launch contains around 500 test cases with approximately 25 log entries.

**Comment by evjlobanova** [comment]
@irynakozak2 Ira, could you please check this issue?

**Comment by irynakozak2** [comment]
@Invictum hello! That behavior doesn't reproduce in any of our environments on different data sets much bigger, than your case, so can you please point us out with following things:
1) Instance capacity by CPU/Memory/Disk (read/write IOPS)
2) Do all of the containers are up and running and don't restart?
2) PostgreSQL configuration.
3) Database container resources utilization stats, if available.
3) Did something changed in reporting?

Please note, that the HDD Disk isn't recommended hardware for the ReportPortal PostgreSQL database storing. Please consider to chose SSD Disk Hardware and make sure that all of the required tuning options for PostgreSQL Database are applied.

You may found all information about PostgreSQL tuning in our official documentation [here](https://reportportal.io/docs/Optimal-Performance-Hardware)

**Comment by MaryiaRymarchyk** [comment]
@Invictum hi, 
long time no hear from you, so we'll close the issue for now.
Just in case you still have the issue, please, provide more details as describes in comment above.
