### ISSUE TITLE
Regarding Reporting Widgets

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1377]
I was going through the following link to understand what dashboards are offered in terms of reporting - https://reportportal.io/docs/Dashboards-and-Widgets
Can you suggest a few of the widgets or dashboards that are used widely across your customers? 

My team is particularly interested in the BDD-related charts, Number of Features, Number of Scenario/Steps at feature level . Execution times for scenarios, etc. Can this be captured through some metrics in Report Portal ?
@DzmitryHumianiuk

**Comment by DzmitryHumianiuk** [comment]
In ReportPortal 6 we will have this view available by default for launches view.

BDD widget may come separately in 5.x version beforehand.


Closing as duplicate with respect to https://github.com/reportportal/reportportal/issues/1306
