### ISSUE TITLE
Utilising Jira status to flag Closed issues which reoccurs

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1378]
There was this use case where I linked a Jira with one of my failures in Report Portal. At that time the status of Jira was -> Open.
Over subsequent runs the issue got auto analysed. The status of Jira changed from Open -> In Progress -> Closed and I got the issue fixed. Now after few runs the same issue got reopened and was auto analyzed. (The status was shown as Closed). There is a high possibility to end up missing such bugs which got auto analyzed but are actually reopened.

![BTS Link](https://user-images.githubusercontent.com/50797731/115900566-b6392e00-a47d-11eb-8456-8931caf41c1c.PNG)

Can there be a flag/ or something through which we get a notification for issues that are still present but the status of Jira is Closed?

Additionally, I have observed that there is some issue around Jira status getting updated/reflected On RP dashboard. Like in my case(above screenshot) , it did not get updated from Open(Launch 5) to In progress (launch 6) , but it did get updated in launch 8 to closed. Not sure if there some polling mechanism which checks and updates. Please confirm ? @evjlobanova @DzmitryHumianiuk

**Comment by priyankachaturvedi30** [comment]
![BTS Link](https://user-images.githubusercontent.com/50797731/115900749-ed0f4400-a47d-11eb-950f-f246e839675d.PNG)

**Comment by priyankachaturvedi30** [comment]
![BTS Link](https://user-images.githubusercontent.com/50797731/115901084-6018ba80-a47e-11eb-85fe-ba8062024326.PNG)

**Comment by priyankachaturvedi30** [comment]
For some strange reason I am unable to put up an attachment 
![BTS Link](https://user-images.githubusercontent.com/50797731/115901937-770bdc80-a47f-11eb-88e1-06ce649a568d.PNG)

**Comment by DzmitryHumianiuk** [comment]
@priyankachaturvedi30 this is a polling mechanism, which refreshes Jira issue status once in 10 min.

As for initial ask,
it's a good case, which requires investigation.

We might need to think about separate ISSUE section inside RP.

**Comment by priyankachaturvedi30** [comment]
@DzmitryHumianiuk : Thanks about info regarding the polling mechanism. That helps.
Do you want me to open a separate ticket for the requirement related to Jira status which might help us track down closed issues?

**Comment by DzmitryHumianiuk** [comment]
@priyankachaturvedi30 yes please.
