### ISSUE TITLE
404 redirect for some tests

### ISSUE THREAD

**Issue by daroshchanka** [reportportal/reportportal#138]
Sometimes(quite rare) I open test logs and catch 404 redirect!
Page started to load, I see some data and then get redirect.
In other launch the same test opened without problems..
No errors in console.

![ezgif-1-dfe41c928c](https://cloud.githubusercontent.com/assets/28945630/26442518/86de8ba2-413d-11e7-93b0-709e18363b3d.gif)

RP: 

> Current version: Gateway Service: 3.0.0;UI Service: 3.0.1;Rally Service: 3.0.0;Authorization Service: 3.0.0;API Service: 3.0.0;Jira Service: 3.0.0;Registry Service: 3.0.0;

We use
```
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.9.13.6</version>
        </dependency>
	<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>3.0.0</version>
        </dependency>
```
Listener defined in _maven-surefire-plugin(2.17)_

**Comment by avarabyeu** [comment]
good catch! Seems like UI issue. May i ask you to enable 'preserve log' in Chrome's development tools and send me screenshot of what you have in network tab.

**Comment by daroshchanka** [comment]
@avarabyeu , see
![image](https://cloud.githubusercontent.com/assets/28945630/26497480/5b53967e-4234-11e7-8da6-26cc1f9f7770.png)

**Comment by avarabyeu** [comment]
@lexecon @daroshchanka could you please specify full request URL of the highlighted line? parentType is not parameter that is supported by server, actually.

**Comment by daroshchanka** [comment]
@avarabyeu this request with 'parentType' param is the request from my test scenario. I sent it to our test-app api. Also this request uri was logged to RP. Looks like report-portal UI tries to execute the same request... 
I'll try to reproduce the problem again to add more details. But I cannot remember last time when I catch this.. (3-4 month ago).

**Comment by daroshchanka** [comment]
@avarabyeu we cannot reproduce this any more.
