### ISSUE TITLE
RP etup on AWS (Centos 7) - Help

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1383]
I followed steps described to setup rp instance on AWS- https://github.com/reportportal/shell-installation

However, looks like my uat service (which uses port 9999) does not starts becasue the port is already in use by some other process-
![image](https://user-images.githubusercontent.com/50797731/116540544-ee21f480-a907-11eb-84f3-3dbf430e6c73.png)

I tried changing the UAT port to 9998 in following file.
https://github.com/reportportal/shell-installation/blob/master/reportportal/traefik.toml
But it still seems to be expecting it on 9999 port. Am i missing something?

**Comment by DzmitryHumianiuk** [comment]
close as duplicate to https://github.com/reportportal/shell-installation/issues/11
