### ISSUE TITLE
Inactive Launches - Dashboard 

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1386]
I see a setting which says Launch Inactivity timeout - Schedule time for Job to interrupt inactive launches
![image](https://user-images.githubusercontent.com/50797731/116683679-951c9400-a9cd-11eb-9494-ec7ca0aad55f.png)

What is inactive launch ?

Suppose my automation was pushing logs to RP and for some reason my automation got terminated/crash. In that case my launches still look in progress. 
![image](https://user-images.githubusercontent.com/50797731/116683808-bd0bf780-a9cd-11eb-8662-7303ee6ad681.png)

Would this be stopped/interrupted by the above setting of Inactivity timeout?

**Comment by evjlobanova** [comment]
@VolhaKarenko Could you please recheck Time out functionality on 5.3.5?

**Comment by VolhaKarenko** [comment]
Hello @priyankachaturvedi30,
It also depends on the frequency of the job execution. Your launch might not be interrupted right after 1 hour, but if it lasts more than an hour, it will be interrupted as soon as the job is executed

**Comment by evjlobanova** [comment]
@VolhaKarenko could you please check to add info, where in DB @priyankachaturvedi30 can check this info, and how she can adjust the time for execution.

**Comment by VolhaKarenko** [comment]
@priyankachaturvedi30 you can only change 'next_fire_time' for 'interruptLaunchesTrigger' in quartz schema-> tables-> scheduler_triggers. There is no option to set job execution periodicity via DB, I need some time to investigate whether it is possible to do any other way
