### ISSUE TITLE
Access denied while building

### ISSUE THREAD

**Issue by vrakr19** [reportportal/reportportal#1387]
Failed to execute goal on project CoreFramework: Could not resolve dependencies for project com.sap.he2e.framework:CoreFramework:jar:0.0.1: Failed to collect dependencies at org.uncommons:reportng:jar:1.1.4 -> org.testng:testng:jar:6.13 -> com.beust:jcommander:jar:1.66: Failed to read artifact descriptor for com.beust:jcommander:jar:1.66: Could not transfer artifact com.beust:jcommander:pom:1.66 from/to bintray (http://dl.bintray.com/epam/reportportal): Access denied to: http://dl.bintray.com/epam/reportportal/com/beust/jcommander/1.66/jcommander-1.66.pom , ReasonPhrase:Forbidden. -> [Help 1]

Access is denied for bintray/epam?

**Comment by HardNorth** [comment]
Duplicate: https://github.com/reportportal/agent-java-testNG/issues/163
