### ISSUE TITLE
Backing up and Restoring Specific project in Report Portal

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1388]
@DzmitryHumianiuk : I had this use case back in mind when i started working on RP.
Consider I have single RP instance running for my multiple solutions. (S1, S2, S3....) Each of these solutions is entirely independent and unknown to each other. The Admin user (Head of Engineering) has access to all the projects. But individual solutions are owned by respective owners. 
We have a backup/restore rule through which we can take and mitigate backup for entire RP instance. (all solution data would be backed up using  )
![image](https://user-images.githubusercontent.com/50797731/116892549-8f34e600-ac4d-11eb-9c92-48d58a82684d.png)

Now if the user wants to take backup specific to its solution (S1) and not for other solution how can i do that ?

**Comment by priyankachaturvedi30** [comment]
@evjlobanova : Can you help me with the above query ?

**Comment by priyankachaturvedi30** [comment]
@DzmitryHumianiuk @evjlobanova : Did you get a chance to look at the above use case ? Is it possible to have it in RP?

**Comment by DzmitryHumianiuk** [comment]
@priyankachaturvedi30 **there is no possibility to backup the only selected project**.
this approach was chosen due to the fact that for separate small projects it is possible to have their own instance.

**Comment by priyankachaturvedi30** [comment]
Hey just coming back with the problem more accurately -> Suppose I have multiple enviornments maintained for Automation Runs across India and Belarus. (Both environments have with different stacks on them). 
Env1 (Oracle/Weblogic)- India
Env2 (Oracle/Jboss)- India
Env3 (Mssql/Weblogic)- India
Env4 (Mssql/Websphere)- Belarus
Env5 (Oracle/Websphere)- Belarus
These are 4 solutions (S1,S2,S3,S4) using these 5 environments. Now for the sake of avoiding data losses across locations due to network glitches (for which we are looking for some fault-tolerant mechanism #1393 ), I maintain 2 RP instances 1 at India and 1 at Belarus. I ensure that when I run Automation using Env1, Env2, Env3 I'll use RP-India and while I am running Automation using Env4 and Env5 i'll use RP-Belarus instance. The trouble here is to maintain/copy baselines between these RP instances always. (In order to benefit from the Investigated history). Is there a better way to handle this ?

**Comment by DzmitryHumianiuk** [comment]
@priyankachaturvedi30 for now, the best option will be to have one instance hosted in the cloud, with back-up nodes and database backups.

A fault tolerant capabilities at scale for multi-locations we plan to put as a part of version 6.

**Comment by priyankachaturvedi30** [comment]
@DzmitryHumianiuk : Thanks for the update. 
Regarding the option you suggested about having a cloud-hosted instance, can you help me with few more details so that I can explore that front.  Much Appreciated.

**Comment by DzmitryHumianiuk** [comment]
@priyankachaturvedi30 it's all about deployment of RP via K8s (https://github.com/reportportal/kubernetes/tree/master/reportportal)
and having Database as a service from cloud-provider.
