### ISSUE TITLE
On page launch view, link "Go to Stack Trace in Log Message" scroll to last error, not to stacktrace

### ISSUE THREAD

**Issue by esoskovets** [reportportal/reportportal#139]
If you have some "error" type records in launch, then click on to link "Go to Stack Trace in Log Message" scroll to last one, but not to the real stacktrace. In my case stack trace is a first error type record.

Please look my video: https://nimbus.everhelper.me/client/notes/share/938952/v0z01ao01gc721n1ee25

**Comment by avarabyeu** [comment]
@esoskovets That's expected behaviour. We assume the last log with the error level contains stacktrace.
