### ISSUE TITLE
Ability to display Stack trace or at least some start part of it in tests list view

### ISSUE THREAD

**Issue by Shakevg** [reportportal/reportportal#1390]
**Describe the solution you'd like**
Ability to display Stack trace or at least some start part of it in tests list view
![image](https://user-images.githubusercontent.com/42133199/117110789-5735bc00-ad8f-11eb-9fa5-e8b71316de12.png)

**Is your feature request related to a problem? Please describe.**
Very often during analysis, a lot of tests failed with the same issue, with similar errors (in most cases RP does not detect such issues as similar). And need to open each test to check that it is really the same issue to set defect type.
If we have stack trace information in the table then it helps to decrease the time for analyzing.
Pattern analysis can help for such cases, but not for all cases.

Propose to add such column as last in the table. There is a lot of free space for others columns that can be used. Also, due to performance issues, we can show this column optionally and display only the first 300 chars for example and show full in the tooltip.

**Comment by evjlobanova** [comment]
Hello @Shakevg 

There are 2 options from the box we can share with you:

1. Grouping by failure reason
Now report portal adds all items with the same error logs to defect, editor,
![image](https://user-images.githubusercontent.com/30413511/117132621-ef17b380-ad57-11eb-8f4d-8dbca38a4227.png)

2. You can add stack trace to test item description programmatically from the test framework

**Comment by Shakevg** [comment]
Hi, @evjlobanova 

1. Grouping by failure reason
Now report portal adds all items with the same error logs to defect, editor,
 => As I mentioned in the description: in most cases, RP does not detect such issues as similar and do not display in a similar section of "Edit defect type dialog"
2. You can add stack trace to test item description programmatically from the test framework
=> Test description already filled with test information in my case
![image](https://user-images.githubusercontent.com/42133199/117133713-498f2f00-adad-11eb-8133-56a8ce4695f7.png)

**Comment by evjlobanova** [comment]
@Shakevg "in most cases RP does not detect such issues as similar" could you please clarify this point? could you please send us an example of similar stack traces? Do you have different failure reasons from run to run? Do you use Auto-Analysis?

**Comment by evjlobanova** [comment]
Regarding stack trace in the description, you can add this info to the description after your description.
Because you will be able to search for similar logs via filters

For now we do not add stack trace as a separate column, because it takes a lot of space and makes the test table very loaded.

The main idea is to automate the process of a similar items search.
Pattern analysis and Auto-analysis are features that should help there.

It will be great if you describe your logs and case in details so that we can adjust this functionality

**Comment by evjlobanova** [comment]
The issue resolved by:

1. Increased number of log lines that are used for analysis (Project Setting/ Auto-analysis)
2. User will work with logs, and standardize them by removing test names from error logs.

**Comment by atomescu01** [comment]
@evjlobanova 
Hi, 
There is an API to get the test_name and error message from the stack trace, as follows:
![image](https://user-images.githubusercontent.com/60103107/117648025-63a68400-b196-11eb-8364-a941066a01d5.png)?

Eg:
"Suite_name", "Test_name", "E       IndexError: list index out of range" - for each suite in the launch?
