### ISSUE TITLE
reportportal.properties

### ISSUE THREAD

**Issue by anin2002** [reportportal/reportportal#1394]
Hi.

I nead set a parametr rp.description (and other) by set value from application.properties parameter, but i don't undersatnd is it possible or not. I tried use masks like ${param_name_from_application.properties}, or create @Component @PropertySource("classpath:reportportal.properties") @Value("${rp.description}") with setters, but it doesnot work (it change value only in code, but not in final report in reportportal).

Can you help me?

**Comment by anin2002** [comment]
i found solution - in application.properties add "spring.config.import=reportportal.properties" and when start test add -Drp.description=value_what_you_need.

May be someone knows other variants?

**Comment by HardNorth** [comment]
We do not provide consultancy on custom implementations.
