### ISSUE TITLE
5.3.5 - Unable to open screenshot attachments in layer

### ISSUE THREAD

**Issue by staind825** [reportportal/reportportal#1397]
**Describe the bug**
When I click a png attachment, nothing happens. In previous versions (as late as 5.3.2) if you click your screen shot attachment, it opens the screen shot in a layer. The only way I can view the screenshot now is to download the screen shot or open it in a new tab. 

**To Reproduce**
Attach a PNG to a test log - We are using base64 images to log attachments - {rp#base64#image/png#" + screenshotBase64 + "}"

**Expected behavior**
When click the attachment i expect a layer to popup with a full size screen shot.

**Comment by evjlobanova** [comment]
In version 5.3.5 - we remove this ability
But in the version 5.4, it is returned back
