### ISSUE TITLE
API to retrieve each error message from Stack trace 

### ISSUE THREAD

**Issue by atomescu01** [reportportal/reportportal#1399]
Hi,
There is an API to get the test_name and error message from the stack trace, as follows:
?
![image](https://user-images.githubusercontent.com/60103107/117651117-3c51b600-b19a-11eb-94a7-bd8c38a04f32.png)

Eg:
"Suite_name", "Test_name", "E IndexError: list index out of range" - for each suite in the launch?

This should be very useful for tracking similar kind of errors walking through the whole launch. I looked on the APIs found on : http://your_host/ui/#api but I didn't found one to fits this need and also I didn't found a documentation to explain how to do that.

Thank you!

**Comment by evjlobanova** [comment]
@atomescu01 no such API request right now.
in the next versions, we provide a feature Unique errors in the launch. 
For now workaround is described in  #1390

**Comment by evjlobanova** [comment]
Also, you can use Pattern analysis and look for similar patterns in the error logs.

**Comment by atomescu01** [comment]
Thank you for the clarification. I will use Pattern analysis.
