### ISSUE TITLE
[Integration] Adapter for Nightwatch_js  (Node.js powered End-to-End testing framework)

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [reportportal/reportportal#140]
http://nightwatchjs.org/

**Comment by thasherwin** [comment]
Is there any plans to implement this adapter soon?

**Comment by DzmitryHumianiuk** [comment]
@thasherwin there is not plans to make it soon,
but it's in backlog.

anyway, i think it's pretty equal to existing [JS integrations](https://github.com/reportportal?utf8=%E2%9C%93&q=js&type=&language=) and you can use them to wire nightwatch.

Don't hesitate to contribute.
we just have no enough hands to do everything

**Comment by thasherwin** [comment]
Alright

**Comment by DzmitryHumianiuk** [comment]
@thasherwin try it
https://github.com/reportportal/agent-js-nightwatch
