### ISSUE TITLE
Unable to log in after Linux installation

### ISSUE THREAD

**Issue by caponord** [reportportal/reportportal#1401]
Hi all,
Followed the steps https://github.com/reportportal/linux-installation to install on Ubuntu 18.04
RabbitMQ and Postgres installed locally (works) and db migration applied (checked tables) and it's pointing to the elastic cloud instance. 

I have gotten this far, can't seem to get the services used to display under the 'current version' banner. 
![image](https://user-images.githubusercontent.com/38348999/117809961-b8113880-b256-11eb-9b80-b5d6a849e0cb.png)

Now, the services all come up with no issues, no error during boot up and it's all up and running. However, can't login using neither the superadmin nor default user; get bad credentials errors in the log. I checked in the users table to  make sure they exist and they do. 

Any pointers?

**Comment by caponord** [comment]
These are the versions used:
API_VERSION="5.3.5"
UAT_VERSION="5.3.5"
MIGRATIONS_VERSION="5.3.5"
UI_VERSION="5.3.5"
SERVICE_INDEX_VERSION="5.0.10"
SERVICE_ANALYZER="5.3.5"

See uat log for exception when I try to login using superadmin/erebus

The log files are:
[service_api.log](https://github.com/reportportal/reportportal/files/6467534/service_api.log)
[service_uat.log](https://github.com/reportportal/reportportal/files/6467536/service_uat.log)

**Comment by Cyberglamdring** [comment]
@caponord, API say that `Unable to find file 'keystore/migration'`, which means API can't find or create directory on the filesystem. Make sure that services are started as root and directory /data/storage/keystore/migraiton exists

**Comment by caponord** [comment]
I don't believe that's the issue. Because absence of a migration file just suggests that there are no migrations to be applied (see log immediately after this error message).
![image](https://user-images.githubusercontent.com/38348999/118102663-fb8fb200-b3d0-11eb-96a0-ddc79e679b95.png)

The service was able to create dir /data/storage/users/ and /data/storage/keystore
![image](https://user-images.githubusercontent.com/38348999/118102049-32b19380-b3d0-11eb-9422-b7520c0b3925.png)

The services are running as root:
![image](https://user-images.githubusercontent.com/38348999/118101885-00079b00-b3d0-11eb-810f-7f0fa332c2b5.png)

Now, you only get this migration folder not found error when the service is restarted. On a fresh install(first time service is started) you don't see this message.

**Comment by caponord** [comment]
Doing a little bit more digging.
![image](https://user-images.githubusercontent.com/38348999/118105910-ed439500-b3d4-11eb-8037-75bd7d3091dd.png)

However, down migration for 5.3.5 shows:
![image](https://user-images.githubusercontent.com/38348999/118106018-0ea48100-b3d5-11eb-8aea-3e83ca16bfdb.png)


Up migration for 5.3.5 shows:
![image](https://user-images.githubusercontent.com/38348999/118106088-23811480-b3d5-11eb-9af1-8bd1257705fb.png)

Does this help you in anyway?

**Comment by caponord** [comment]
As per linux installation in the migration step. The script 3_default_data.up.sql is run and this sets up the password.

![image](https://user-images.githubusercontent.com/38348999/118107096-4233db00-b3d6-11eb-9b26-76c5d3744691.png)

I changed it use the password as per 11_password_encoding.up.sql and got successful login now. However, no redirect after that.  The page just stays put! I think the linux instructions are not accurate, would someone update the steps. Please try and recreate the issue in Ubuntu and see for yourself. 

![image](https://user-images.githubusercontent.com/38348999/118108293-bae76700-b3d7-11eb-91f1-9ef9cfea31ea.png)

**Comment by Cyberglamdring** [comment]
Thanks for paying attention to the problem! We updated the [migration steps](https://github.com/reportportal/linux-installation#migration). You need to run all 25 migration scripts

**Comment by caponord** [comment]
Cheers! I will give that a try. If could also update the documentation for the env variables as '"https://dl.bintray.com/epam/reportportal' is no longer valid. One needs to download .exe files from the respective modules github release page and the exec-jar files from maven central. 

![image](https://user-images.githubusercontent.com/38348999/118115193-8fb54580-b3e0-11eb-8245-780899e855e1.png)

**Comment by caponord** [comment]
Okay now it works! Or at least I am able to login and see the tool. Thanks for the fix.

**Comment by bldragon101** [comment]
I have reached the same point however the analyzer shows as not running in the settings page. At the login page i dont have anything coming up under 'current version'. Hitting the `composite/info` endpoint returns an empty response. @caponord have you been able to get it working?

**Comment by caponord** [comment]
I was able to enable auto-analyser, as to whether it works I will find out once I have a launched tests (which I will do soon and post results here)

![image](https://user-images.githubusercontent.com/38348999/118236814-74a10f00-b48e-11eb-8628-929928a0a5ed.png)

Nothing comes up under the 'current version' but info and health(replace info with health) endpoints are available. 

Here are the info endpoints:
 For UI:   http://ip:8080/ui/info
     
![image](https://user-images.githubusercontent.com/38348999/118238040-e62d8d00-b48f-11eb-8181-2a72342c711a.png)

For API: http://ip:8080/api/info
![image](https://user-images.githubusercontent.com/38348999/118238125-03faf200-b490-11eb-8162-426be0bfccbc.png)

For index: http://ip:8080/info

![image](https://user-images.githubusercontent.com/38348999/118238291-3e648f00-b490-11eb-9bbc-1c17e9818b5b.png)

For uat: http://ip:8080/uat/info

![image](https://user-images.githubusercontent.com/38348999/118238439-6ce26a00-b490-11eb-8abe-b3dab6b149f4.png)

**Comment by Cyberglamdring** [comment]
@caponord, by default, the Auto Analyzer service is not displayed in the "Current version". For example, you can see that in our [Demo environment](https://demo.reportportal.io) on the Kubernetes. Also, you can try to generate demo data and launch auto-analyze.
[Analyzer works](https://github.com/reportportal/linux-installation#Analyzer) in a Python virtual environment. You can view the logs and see if the Analyzer is connected to ElasticSearch, and the auto-analysis process.

**Comment by caponord** [comment]
Hi all, 
I can confirm that it works. We are now able to register test launches and see reports. Nice one all. This tool is going to just what we needed!

**Comment by bzsharm** [comment]
@caponord we are actually struggling with the installation :( ! if you have free time could you please let me know the step-by-step process to update the migration files!  We are totally new to Linux!

**Comment by bzsharm** [comment]
every thing looks greek and Latin for me :(

**Comment by caponord** [comment]
@bzsharm 
The migration instructions has changed at https://github.com/reportportal/linux-installation. Provided you have the right versions installed the migrations do work. There are whitespaces post the command continuation maker (\) remove them and it will run. 

Here's a copy without whitespaces and it does work.

`PGPASSWORD=$RP_POSTGRES_PASSWORD psql -U $RP_POSTGRES_USER -d reportportal -a \
  -f migrations/migrations/0_extensions.up.sql \
  -f migrations/migrations/1_initialize_schema.up.sql \
  -f migrations/migrations/2_initialize_quartz_schema.up.sql \
  -f migrations/migrations/3_default_data.up.sql \
  -f migrations/migrations/4_size_limitations.up.sql \
  -f migrations/migrations/5_test_case_id_type.up.sql \
  -f migrations/migrations/6_retries_handling.up.sql \
  -f migrations/migrations/7_auth_integration.up.sql \
  -f migrations/migrations/8_sender_case_enabled_field.up.sql \
  -f migrations/migrations/9_analyzer_params.up.sql \
  -f migrations/migrations/10_attachment_size.up.sql \
  -f migrations/migrations/11_password_encoding.up.sql \
  -f migrations/migrations/12_remove_ticket_duplicates.up.sql \
  -f migrations/migrations/13_add_allocated_storage_per_project.up.sql \
  -f migrations/migrations/14_test_case_id_size_increase.up.sql \
  -f migrations/migrations/15_statistics_decreasing.up.sql \
  -f migrations/migrations/16_remove_unused_indexes.up.sql \
  -f migrations/migrations/17_status_enum_extension.up.sql \
  -f migrations/migrations/18_job_attributes.up.sql \
  -f migrations/migrations/19_retries_handling_extension.up.sql \
  -f migrations/migrations/20_deep_merge_statistics_handling.up.sql \
  -f migrations/migrations/21_deep_merge_retries_fix.up.sql \
  -f migrations/migrations/22_deep_merge_nested_steps_fix.up.sql \
  -f migrations/migrations/23_rerun_item_statistics_fix.up.sql \
  -f migrations/migrations/24_widget_views_cleanup.up.sql \
  -f migrations/migrations/25_deep_merge_nested_steps_path_fix.up.sql 2>&1 &
`

**Comment by bzsharm** [comment]
Were you able to log in after the installation?

**Comment by caponord** [comment]
@bzsharm 
Yes, works well. The steps does work.
