### ISSUE TITLE
Unable to get anazlyer or index to work correctly - Linux installation

### ISSUE THREAD

**Issue by bldragon101** [reportportal/reportportal#1402]
Hi I have been trying to deploy RP on RHEL7 linux environment using the steps found here:
https://github.com/reportportal/linux-installation

I have managed to get it running and have been able to login and run tests however it seems the service-index and service-auto-analyzer are not working correctly.

When i go to login the is nothing displayed in the "Current Version" area as per the screenshots in the installation guide:
![Screen Shot 2021-05-12 at 3 27 45 pm](https://user-images.githubusercontent.com/33268959/117924832-b8363480-b339-11eb-8372-bc75e13a5c69.png)

Checking the network tab also shows an empty response in the /composite/info call:
![Screen Shot 2021-05-12 at 3 28 15 pm](https://user-images.githubusercontent.com/33268959/117924922-dd2aa780-b339-11eb-8a12-cee003f0676b.png)

Once I have logged in and I go to the settings page, the index buttons are greyed out and I cannot select them. Hovering over the buttons shows that the analyzer is not running.
![Screen Shot 2021-05-12 at 3 28 44 pm](https://user-images.githubusercontent.com/33268959/117925368-7c4f9f00-b33a-11eb-89d5-d91a7756938f.png)

I have attached logs below:
[elasticsearch.log](https://github.com/reportportal/reportportal/files/6464043/elasticsearch.log)
[rabbitmq.log](https://github.com/reportportal/reportportal/files/6464044/rabbitmq.log)
[reportportal.log](https://github.com/reportportal/reportportal/files/6464045/reportportal.log)
[traefik.log](https://github.com/reportportal/reportportal/files/6464079/traefik.log)

Have tried on both RHEL7 in aws and Ubuntu VM locally to the same outcome.

Any help is appreciated. Thanks.

**Comment by evjlobanova** [comment]
@Cyberglamdring Hleb, could you please check?

**Comment by Cyberglamdring** [comment]
@bldragon101 we updated the [migration steps](https://github.com/reportportal/linux-installation#migration). You need to run all 25 migration scripts

**Comment by bldragon101** [comment]
@Cyberglamdring I have done this. I was able to figure it out from the Docker version. The problem still persists.

**Comment by bldragon101** [comment]
Hi @Cyberglamdring is there a command to run the 'Remove Index' and 'Generate Index' options? So far this is the only thing that is not working in our installation. 

If i manually start an analysis on a launch i can see in the analyzer logs that it is working and communicating with Elasticsearch but there is a `A non-string value was supplied for self.routing_key` error coming up, not sure if this could be a problem.

[analyzer.log](https://github.com/reportportal/reportportal/files/6490337/analyzer.log)

**Comment by marintrooper23** [comment]
I have a similar problem. Made installation via docker - compose. All containers are running and the status is healthy. But when I try to create an elasticsearch index, I get an error. Also, during manual analysis, the red inscription auto-analysis lights up in the line with the analysis.
elasticsearch_1  | {"type": "server", "timestamp": "2021-05-19T07:40:09,610+0000", "level": "DEBUG", "component": "r.suppressed", "cluster.name": "docker-cluster", "node.name": "43a92eaec33d", "cluster.uuid": "BRXlBQNFSy-ZLUIE_kpBLQ", "node.id": "nm7p5-4kSwiEFIh0IsKTaA",  "message": "path: /3, params: {index=3}" ,
elasticsearch_1  | "stacktrace": ["org.elasticsearch.index.IndexNotFoundException: no such index [3]",
elasticsearch_1  | "at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.indexNotFoundException(IndexNameExpressionResolver.java:761) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolver.java:713) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:669) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:163) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:142) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:75) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:88) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:49) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:170) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.start(TransportMasterNodeAction.java:161) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:138) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.doExecute(TransportDeleteIndexAction.java:83) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.doExecute(TransportDeleteIndexAction.java:49) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:145) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:121) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:64) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:392) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1212) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.delete(AbstractClient.java:1348) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.rest.action.admin.indices.RestDeleteIndexAction.lambda$prepareRequest$0(RestDeleteIndexAction.java:52) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:113) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:240) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:344) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:174) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:320) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:370) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:299) [elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:66) [transport-netty4-client-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:31) [transport-netty4-client-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:58) [transport-netty4-client-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-codec-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) [netty-handler-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.36.Final.jar:4.1.36.Final]",
elasticsearch_1  | "at java.lang.Thread.run(Thread.java:835) [?:?]"] }

**Comment by evgenytkachenko** [comment]
@bldragon101 how did you fix this issue, could you share, please?

**Comment by bldragon101** [comment]
@evgenytkachenko was not able to fix the issue.

**Comment by evgenytkachenko** [comment]
I had a redirect from http to https set up using traefik 2.2.8 version, I had to give up on this redirect and switch to 2.0.7 and follow the instructions from this doc https://github.com/reportportal/documentation/blob/master/src/md/src/InstallationSteps/TraefikTLS.md
