### ISSUE TITLE
[v5] cannot log in to fresh reportportal installation

### ISSUE THREAD

**Issue by TimB0** [reportportal/reportportal#1403]
**Describe the bug**
http://localhost:8080/ui/#login tells me that im successfully logged in, but it dosent take me to the dashboard...it keeps me on the login page

**To Reproduce**
1.  download the latest docker-compose yaml file
2. docker-compose -p reportportal up -d --force-recreate
3. wait for all the services to start
4. go to:  http://localhost:8080/
5. i logged in with default\1q2w3e
6. i attached a screenshot that it shows me that im logged in successfully....but it keeps me on the home page

**Expected behavior**

**Screenshots**
<img width="1230" alt="Screen Shot 2021-05-13 at 6 49 36 PM" src="https://user-images.githubusercontent.com/1301825/118209035-af6a5f00-b41c-11eb-9117-681d9d11e54b.png">

![Screen Shot 2021-05-13 at 6 45 36 PM](https://user-images.githubusercontent.com/1301825/118209102-d759c280-b41c-11eb-9c42-61ddaf0bf9aa.png)

**Desktop (please complete the following information):**
 - macOS Big Sur Version 11.3.1
 - Chrome
 - 90.0.4430.212

**Comment by evjlobanova** [comment]
Hello @TimB0,  do you still have an issue with login?
@Cyberglamdring could you please recheck

**Comment by MaryiaRymarchyk** [comment]
@TimB0 as we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
