### ISSUE TITLE
Excel Attachments getting downloaded in different format

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1404]
When I send excel file(.xls/.xlsx) to RP as an attachment and try to download the file, it gets downloaded with a random name as .sheet extension.  
![image](https://user-images.githubusercontent.com/50797731/118264018-b2288b00-b4d4-11eb-8d48-3a53a170437d.png)

Can we not preserve the name/format/extension of the uploaded file while downloading?

**Comment by nvborisenko** [comment]
Looks like RP uses mime type as file extension.

![image](https://user-images.githubusercontent.com/22616990/118359020-18bbb080-b58a-11eb-8f84-0b553d84d26c.png)

In this case file name for downloading is `attachment_666.png2`.

**Comment by alena-babrova** [comment]
Hello @priyankachaturvedi30,
We have registered it as a defect for our backlog.
Thank you for contribution!

**Comment by VolhaKarenko** [comment]
Hello @priyankachaturvedi30, the fix will be available in version 23.2.

**Comment by Kozovskaya** [comment]
Hello @priyankachaturvedi30! The fix is already available with our latest release 23.2!
