### ISSUE TITLE
[v5] Not all tests reported

### ISSUE THREAD

**Issue by gpapadakis** [reportportal/reportportal#1405]
**Describe the bug**
Not all of integration tests executed. We are running reportportal v5.3.5 in GCP.

Log report of the failure:
`
May 17, 2021 9:16:41 AM rp.org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://...:443: Broken pipe (Write failed)
`

Also the failure cause:
`com.epam.reportportal.exception.InternalReportPortalClientException: Wait for Launch start timed out
	at com.epam.reportportal.utils.Waiter.till(Waiter.java:126)
	at com.epam.reportportal.service.launch.SecondaryLaunch.waitForLaunchStart(SecondaryLaunch.java:56)
	at com.epam.reportportal.service.launch.SecondaryLaunch.start(SecondaryLaunch.java:88)
`

This is random it could be related to performance as we run multiple projects at the same time

**Expected behavior**
All tests reported in ReportPortal

**Screenshots**
![test](https://user-images.githubusercontent.com/25581661/118496597-f0b88280-b72c-11eb-9948-db96824860bf.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g. chrome]
 - Version [e.g. 90]

**Additional context**
#1286

**Comment by irynakozak2** [comment]
@gpapadakis hello! looks like it isn't an issue related to the instance performance, but let's check several things:

1) Do all of the containers are up and running and don't restart during reporting?
2) Do you have enough Disk space capacity on your instance for the PostgreSQL database?
3) What is your actual instance spec by CPU/RAM size and load stats of your instance by CPU/RAM?
4) What is your reporting amount? (total test-cases in the 1 launch, approximate logs amount per 1 launch, number of the parallel launches execution)
4) What actual amount of PostgreSQL connections do you have(max_connections parameter in PostgreSQL configurations)?

**Comment by gpapadakis** [comment]
> 1. Do all of the containers are up and running and don't restart during reporting?

We receive restarts on the two API pods we have on our cluster frequently and this seems to be the reason that many launches restarts in RP.

We do receive though this messafe in logs io.minio.errors.ErrorResponseException: Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed. 


For CPU/RAM we have installed in GCP middle type: 8 CPU's with 16 GB RAM

> 5. What actual amount of PostgreSQL connections do you have(max_connections parameter in PostgreSQL configurations)?
We have 400 max_connections added recently


> 4. What is your reporting amount? (total test-cases in the 1 launch, approximate logs amount per 1 launch, number of the parallel launches execution)

We do have multiple projects running on average i would say one launch per project with up to 10 concurrent sessions

**Comment by halradaideh** [comment]
@irynakozak2 the DB is underutilized and there is plenty of storage available 

we are facing issues with the number of connections that the API is making, `FATAL: remaining connection slots are reserved for non-replication superuser connections` we get this error a lot

we are using GCP SQL Postgres 11, with MAX_CONNECTION = 1000, and i defined RP_DATASOURCE_MAXIMUMPOOLSIZE to the API as 401
