### ISSUE TITLE
[v5] : Jira Integration : Priority of bug posted gets changed

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1406]
I have integrated Report Portal with Jira. When I try to post a bug with say P1 priority -> the bug gets posted to jira but with P3 priority. Additionally, while configuring I have unchecked Incident ID to be a non-mandatory field. Still, i could see a not accessible incident id url be passed to the jira. Can someone check this?
Using following jira jar plugin - plugin-bts-jira-5.1.0-all

**Comment by evjlobanova** [comment]
Does Incident ID is Jira custom field?

**Comment by priyankachaturvedi30** [comment]
Yes, so when I create a bug in jira it suggest me to associate the bug with an incident id if any (non-mandatory field) 
![image](https://user-images.githubusercontent.com/50797731/119683072-016da480-be61-11eb-93d9-72bbac64dd58.png)

However, as i said, its optional. So when I integrated RP with BTS - i did not checked for this field 
![image](https://user-images.githubusercontent.com/50797731/119683410-40035f00-be61-11eb-9f8b-80f5e31e401f.png)

But this is still been passed with some dummy value while I post an issue to Jira through RP.

**Comment by evjlobanova** [comment]
Do you use Cloud Jira?

**Comment by evjlobanova** [comment]
We have some known issues with Jira custom fields and custom issues. 
We are planning to work with them in a scope of Jira integration refactoring

**Comment by alena-babrova** [comment]
Hi @priyankachaturvedi30,
Is the issue still relevant?
If yes, please try to update Report Portal to the latest version and use corresponding Jira Server Plugin (5.7.0).

**Comment by alena-babrova** [comment]
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
