### ISSUE TITLE
ReportPortal Plugin Roadmap & Development Guides

### ISSUE THREAD

**Issue by saarmstrong** [reportportal/reportportal#1409]
Are there any updates on the plugin feature roadmap? 

I am very interested in developing some plugins for my instance and I think the community could also benefit from these plugins.

**Comment by evjlobanova** [comment]
Hello @saarmstrong 
unfortunately no, because of the nearest release.
But for now ready only UI part, BackEnd will be added this or next month.
https://github.com/reportportal/service-ui/blob/develop/app/docs/14-plugins.md

**Comment by evjlobanova** [comment]
We are planning to make plugin example this month
