### ISSUE TITLE
[MAILS] Add tags in email body

### ISSUE THREAD

**Issue by lifemanship** [reportportal/reportportal#141]
It would be very helpfull to have list of the **tags** in email body. 
We have to run tests on different platforms/timezones/browsers/locales etc. and **tags** are used to describe test configuration, but email contains only the name of the launch.
After all tests are passed we have bunch of the emails with same contents. 
Could you please add **tags** inside email body?

**Comment by avarabyeu** [comment]
Makes sense. @lexecon could you please update templates?

**Comment by lifemanship** [comment]
Is it possible to implement it feature in the next release build 3.4?

**Comment by evjlobanova** [comment]
@lifemanship it will be a future release
