### ISSUE TITLE
Previous logged in users data still in local storage after logout

### ISSUE THREAD

**Issue by mgiamberardino** [reportportal/reportportal#1414]
**Describe the bug**
After login and logout with different users when inspecting local storage there is some information regarding previous users.

**Expected behavior**
On users log out clean up local storage to avoid leaking information like ids from other users' projects.

**Screenshots**
![Captura de Pantalla 2021-05-21 a la(s) 20 02 06](https://user-images.githubusercontent.com/5713631/119205724-701cbd80-ba6f-11eb-95f5-2b3085700bc8.png)

**Versions:**
 - MacOS, Mozilla Firefox
 - 5.3.5

**Comment by evjlobanova** [comment]
We will take this fix to the next version in devrlopment

**Comment by AmsterGet** [comment]
Hello @mgiamberardino !
Could you explain your case in more detail? Are multiple users using a RP application from the same browser on the same machine?
Saving f.e. the user's `activeProject` in `localStorage` can reduce the amount of interaction with the user to find the desired project after the session expires (similar to logging out).
