### ISSUE TITLE
[v5.3.3] Editing a defect type is too slow

### ISSUE THREAD

**Issue by nirmalashish** [reportportal/reportportal#1421]
**Describe the bug**
Editing a defect type for a failed case takes around 5-6 minutes to update

**Expected behavior**
Previously, edits used to happen real-time

**Desktop (please complete the following information):**
 - OS: macOS (Catalina 10.15.7)
 - Browser Chrome/Firefox
 - Version 91.0.4472.77/88.0.1

**Additional context**
Looks like elastic search is the culprit behind the slowness

**Comment by evjlobanova** [comment]
@irynakozak2 could you please check if this issue relates to a known issue or instance settings should be updated

**Comment by irynakozak2** [comment]
@nirmalashish hello, can you please check out several things:

1. Do all containers are up and running or there are some containers that are keeping restarted from time to time?
2. Container logs for the service-analyzer and elasticsearch.
3. Do Elasticsearch has enough free Disk storage amount for working correctly?

**Comment by MaryiaRymarchyk** [comment]
@nirmalashish  hi, 
long time no hear from you, so we'll close the issue for now.
Just in case you still have the issue, please, provide more details as described in comment above.
