### ISSUE TITLE
Unable to do a strict match even when match level set to 100 %

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1424]
I have configured Auto Analyser to work at 100% match level:
![image](https://user-images.githubusercontent.com/50797731/120450997-9c5d0600-c3ae-11eb-97dc-1ee55bc8c1ee.png)

Following the above setting, I started Analyser for my Launch 2.
Launch 1:
![image](https://user-images.githubusercontent.com/50797731/120451347-f65dcb80-c3ae-11eb-8983-68413de98542.png)
Launch 2: (**This is a new issue which was not present in previous run** It got auto-analyzed on the basis of stack trace - checked from History of Items)
![image](https://user-images.githubusercontent.com/50797731/120451687-450b6580-c3af-11eb-890f-25f78a9c2a30.png)

As you can see from the above screenshot both these stack trace are not 100% matching but still it treated them as same. Am I missing something around here? Considering I applied for a strict match with 100% level how can I ensure that my Auto- Analysis happens for the exact match? RP Version: 5.3.5
@evjlobanova

**Comment by evjlobanova** [comment]
Analyzer removes all numbers and compares words. I guess if these logs have differences only in numbers, Analyzer can define logs as similar.
I guess, ib this situation, you should change defect type manually on the right defect type. And in the next run, the model should be retrained.
@MariyaIvanina please fix me if I am wrong

@priyankachaturvedi30 could you please send us a full log message for both logs in order we can debug problem

**Comment by priyankachaturvedi30** [comment]
First Launch Log : 
`assertion failed: Expected alert message [locator: javascript=document.querySelectorAll("tlmv-alert .tlmv-c-alert-content-body-message")[2]] to be 'IDs: [13933,13936] could not be rejected. The user is not authorised to reject this Manual Adjustment.' but got 'IDs: [13928,13929] could not be rejected. A user cannot reject a Manual Adjustment that they have created.'

Hierarchy:

I verify "error" alert message in number "2" container on screen is "IDs: [13933,13936] could not be rejected. The user is not authorised to reject this Manual Adjustment."
alert message should be "IDs: [13933,13936] could not be rejected. The user is not authorised to reject this Manual Adjustment."`


Second Launch Log : 

`assertion failed: Expected alert message [locator: javascript=document.querySelectorAll("tlmv-alert .tlmv-c-alert-content-body-message")[1]] to be 'IDs: [13965,13958,13956] could not be rejected. The user is not authorised to reject this Manual Adjustment.' but got 'IDs: [13956,13958,13965] could not be rejected. The user is not authorised to reject this Manual Adjustment.'

Hierarchy:

I verify "error" alert message in number "1" container on screen is "IDs: [13965,13958,13956] could not be rejected. The user is not authorised to reject this Manual Adjustment."
alert message should be "IDs: [13965,13958,13956] could not be rejected. The user is not authorised to reject this Manual Adjustment."`

@evjlobanova

**Comment by evjlobanova** [comment]
![image](https://user-images.githubusercontent.com/30413511/120490963-b4606580-c36d-11eb-92db-673e5cc4d990.png)

**Comment by priyankachaturvedi30** [comment]
yes, so as i understand there are differences in words as well as numbers :( Considering match level as 100% should it be behaving in this fashion ? @evjlobanova

**Comment by MariyaIvanina** [comment]
@priyankachaturvedi30 Hi! Thank you for sharing your use case. In our process we remove numbers and calcualte similarity without them, but it is strange that some words are not the same(but some words like a/the/is, they are not taken into consideration, because they are english stopwords, but authorised and created should have been compared) and it still matches them, so I need to debug the problem to answer you.

**Comment by priyankachaturvedi30** [comment]
Thanks @MariyaIvanina : I'll wait for your revert on the above. Much Appreciated.

**Comment by priyankachaturvedi30** [comment]
@MariyaIvanina : Did you get a chance to look at the above problem?

**Comment by MariyaIvanina** [comment]
@priyankachaturvedi30 Hi! Sorry for late response. I've looked at the problem, and I see that some words in square brackets was not accounted, as far as I added the logic for checking the similarity to be either the message or message without info in brackets to handle the situation by the trained model. But I can see that the model won't be trained so fast to account for it, and in 5.4 I return checking similarity strictly by the whole message. So your test items won't be linked if you select 100% min should match. 5.4 version will be released quite soon.

**Comment by evjlobanova** [comment]
We are waiting for 5.4 this month

**Comment by priyankachaturvedi30** [comment]
@MariyaIvanina : Just one quick question around your last comment. When you say that you would be implying logic to **check similarity strictly by the whole message**  - does this imply that the numbers would be removed first and then the words would be matched strictly?

**Comment by MariyaIvanina** [comment]
@priyankachaturvedi30 Yes, I mean that numbers will be removed(this logic stays the same), but all words would be taken into account.

**Comment by priyankachaturvedi30** [comment]
@evjlobanova  @MariyaIvanina : Is this a part of 5.4 release that happened yesterday ?

**Comment by MariyaIvanina** [comment]
@priyankachaturvedi30 yes, it is the part of 5.4 release. Didn't it work for you?

**Comment by priyankachaturvedi30** [comment]
Just checking...would update you :)
