### ISSUE TITLE
[v5] The status of a Launch is marked as passed even if no tests were executed.

### ISSUE THREAD

**Issue by itzikb** [reportportal/reportportal#1425]
**Describe the bug**
The status of a Launch is marked as passed even if no tests were executed.
**To Reproduce**
Trigger a launch where it fails and no tests are being executed 
**Expected behavior**
Either the launched should be set to failed (or something other than passed) or there should be an option to change it through the API.
**Version**
5.3.5

**Comment by HardNorth** [comment]
@itzikb Your description does not provide any picture of what happens. Could you please implement an example project?

**Comment by itzikb** [comment]
@HardNorth I'm not sure it will be easy for me to do in an example project

**Comment by MaryiaRymarchyk** [comment]
Hello @HardNorth, as no additional info provided - we can't help you.
Ticket will be closed.
In case still have questions - just contact us with providing more details .
