### ISSUE TITLE
Do not display before and after hooks

### ISSUE THREAD

**Issue by harish4b4** [reportportal/reportportal#1426]
Hello Team, I have newly adopted report portal as a report dashboard in my project.
I need help in not displaying before and after hook methods in the reportportal. is there any trick to achieve this.

I'm using,
rp: 5.3.5
agent-java-cucumber4: 5.0.2

![image](https://user-images.githubusercontent.com/25383966/120585090-0914e680-c429-11eb-8008-127cb60407b7.png)

 I have a requirement of adding @before hook to each of the step definition file I created, this facilitates getting hold of Scenario interface.

**Comment by evjlobanova** [comment]
@HardNorth could you please check

**Comment by harish4b4** [comment]
Any update on this request please?

**Comment by DzmitryHumianiuk** [comment]
@harish4b4 could you please try the latest version of the cucumber agent. It was re-implemented from scratch.

If this still remains a concern, please feel free to create a new issue. 

Thank you for your understanding and contributions to the project!
