### ISSUE TITLE
Add ForceFinishAndDelete to "Action" combo box

### ISSUE THREAD

**Issue by YBB8201** [reportportal/reportportal#1428]
Hi,
when i run some test and i finish it ungracefully, I can see in report portal as if the test continue to run. in order to delete this run/launch, I need first to mark it and pick "Force Finish", and than check it again and pick "Delete" - this is 6 clicks. I want to reduce this to 3 clicks - add ForceFinishAndDelete option to combo box
![Capture](https://user-images.githubusercontent.com/66330263/120595649-67eb5780-c44b-11eb-89d8-db3423ccab1a.PNG)

**Comment by evjlobanova** [comment]
You can set a parameter for Launch inactivity on the Project Settings> General, and then these launches will be interrupted by the job.
Force finish and Delete are 2 independent processes and they can not be combined together.

But I have got your point. 

Could you please describe your case, why do you have so much run that should be interrupted manually?

**Comment by YBB8201** [comment]
Hi
I have it because I debug some tests in visual studio. Each debug is a
different launch.
I always go to "launches" and filter them by my name - and I want that this
filter will not contain too many launches - therefore I delete them. if i
stop one lrun in the middle (stop the debug process in the middle), the
launch appears in the report portal as not finished. and therefore I need
to forch finish, and then delete it. it's a little bit inconvenient.
thx

**Comment by YBB8201** [comment]
In addition, may be you can do the following:
after selecting the launches I want to force finish, and click on force finish, when the list of launches get refreshed, save the launches i just checked seconds ago. it will eliminate the necessity of mark the tests again

**Comment by evjlobanova** [comment]
You can use debug mode in order not to send debug launches to All launches, but send it to Debug.
rp.mode = DEBUG
It helps you separate broken and debug launches from prod results
![image](https://user-images.githubusercontent.com/30413511/120631646-f694b000-c41c-11eb-83c4-9d8491b540cf.png)

**Comment by YBB8201** [comment]
hi
looks great.
How can I set this in advance? Do you have some environment variables I can
use in order to set it? i don't want to do it manually, but automatically

**Comment by evjlobanova** [comment]
I send in a previous message, you can make it programmatically via  rp.mode = DEBUG 
Which agent do you use?

**Comment by YBB8201** [comment]
I want to understand how I can change debug mode in the config file via the
environment variable. it will set the env var by jenkins and then it will
send to debug or production depending on the env var i set. Is it possible ?

**Comment by Yumfriez** [comment]
you can pass it using java variables:
-Drp.mode=DEBUG

**Comment by YBB8201** [comment]
Sorry, i didnt understand. Can i set envirenment vaiable in order to choose
debug or production?

בתאריך יום ה׳, 3 ביוני 2021, 17:13, מאת Ivan ***@***.***>:

**Comment by YBB8201** [comment]
I found the solution. add new env var "ReportPortal_Launch_DebugMode" and set it to true/false
thx

**Comment by nvborisenko** [comment]
Or even yes/no. Please help us to improve documentation, where you found this solution, to be clearer for everybody.

**Comment by YBB8201** [comment]
Well, i assume it would be great to have a full list of the possiable keys
and corrisponding values that can be used in the jason config file. In
addition, to have the same list for environment variables and thier
optional values. Will be v e r y usful. Thx!

בתאריך יום ה׳, 3 ביוני 2021, 22:18, מאת Nikolay Borisenko ‏<
***@***.***>:

**Comment by evjlobanova** [comment]
On profile page, you have a list with options

**Comment by YBB8201** [comment]
ok,
but I can't see any list for *environment variables* and their optional
values.
I found what I was looking for in some "Issue" in your github - I think
it's not convenient  - you need specific instructions with the Environment
variables names we can use in order to control the configuration.
thx
