### ISSUE TITLE
[v5] Loading test item page not loading, spinning loading wheel

### ISSUE THREAD

**Issue by naddison** [reportportal/reportportal#1430]
**Describe the bug**
When drilling down into the leaf test-item in a chain, it does not load and I end up on a spinning loading wheel indefinitely.

**To Reproduce**
Click through a launch, test suites, until clicking on the final leaf node, the test case.

**Expected behavior**
The page should load without issue.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: Chrome
 - Version: 92

**Additional context**
I noticed that the call to `/api/v1/<project>/item/history?historyDepth=10&type=line&filter.eq.id=24024408` was not returning within a few seconds. Eventually the call would return, and then I could reload the page and would see results. My guess is that once it returns once, its cached either browser or server side (traefik?) so that I can load the page.

Ideally I wouldn't have to watch the network traffic to know when that call returns, and then reload the page. We have set this project to store launches and logs forever. We are starting to see performance issues as time goes on. What is the recommended/tested max amount of data RP can store before it degrades in performance?

**Comment by evjlobanova** [comment]
@irynakozak2 could you please check this issue? Can DB reindex can help here?

**Comment by irynakozak2** [comment]
@naddison hello, which version of ReportPortal do you use? Please also check, that your instance capacity is met minimal performance requirements, especially Disk specification, and revise the database configuration following the Performance Docs [here](https://reportportal.io/docs/Optimal-Performance-Hardware%3E5-postgresql-performance-tuning)

**Comment by naddison** [comment]
API Service: 5.3.0
Index Service: 5.0.10
Authorization Service: 5.3.0
Service UI: 5.3.0

Our machine is 4 cpu, 16G Memory and 500 GB of space, of which only 11% is being used `488G   54G  435G  11%`

All services are running on the same machine using docker-compose.

**Comment by irynakozak2** [comment]
@naddison thank you! Our latest version is 5.3.5, and 5.4 is on the release way, so please firstly update the service versions.
Do you use SSD or HDD on this machine? The database performance tuning options also required for the ReportPortal DB. Please, revise them, based on the docs placed [here](https://reportportal.io/docs/Optimal-Performance-Hardware%3E5-postgresql-performance-tuning)
