### ISSUE TITLE
API for flaky test

### ISSUE THREAD

**Issue by mchundi** [reportportal/reportportal#1431]
As a super admin, is there a way I can retrieve flaky tests for all the applications on report portal?
This can include application that do not have flaky tests widget created on their dashboard.

**Comment by evjlobanova** [comment]
No, there is no such functionality but ReportPortal has a History table, you can retrieve this info, and after that use this infor for your needs.
Could you please describe your case and business need for this operation?

**Comment by mchundi** [comment]
We have onboarded multiple teams to reportportal and the tests flow through a common framework. From this framework I would like to retrieve the flaky tests for all teams and show in summary dashboard for admin (Either through API or through UI).

**Comment by evjlobanova** [comment]
Could you please elaborate on what the onboarding process includes in your case?

**Comment by mchundi** [comment]
created a separate project for each team.
Like we have "cumulative trend chart", is there a widget/API to get the flaky tests?

**Comment by evjlobanova** [comment]
We have "TOP-20 f laky tests" widget, but it shows info for launches with the same name for 1 project

**Comment by MaryiaRymarchyk** [comment]
Hi @mchundi , we already have similar request here https://github.com/reportportal/reportportal/issues/193
It is planned for some future release according Backlog priority.
I'll close current ticket as duplicate, however if you have other questions - feel free to reopen or create a new one.
