### ISSUE TITLE
Duplicate reporting to Report Portal

### ISSUE THREAD

**Issue by keydiram** [reportportal/reportportal#1433]
Hi, I wrote the following class that extends the ReportPortalExtension and sends logs to the Report Portal. In the test classes I use @ExtendWith(BtRunner.class) instead of ReportPortalExtension. When I run a test class as junit, it runs exactly as it should. The problem is that when I run maven integration test, there's a double report for every item. Once with my buildFinishTestItemRq method and once with the ReportPortalExtension-buildFinishTestItemRq method. Can you tell me why it sends the report twice? Thanks! 
public class BtRunner extends ReportPortalExtension {
	@Override
	protected FinishTestItemRQ buildFinishTestItemRq(ExtensionContext context, Status status) {
		FinishTestItemRQ rq = new FinishTestItemRQ();
		System.out.println(Thread.currentThread().getStackTrace()[2].toString());
		System.out.println(("In the method " + Thread.currentThread().getStackTrace()[2]));
		System.out.println("Run class: " + context.getRequiredTestClass());
		rq.setStatus(status.name());
		rq.setEndTime(Calendar.getInstance().getTime());
		if (!context.getUniqueId().contains("/[method:"))
			rq.setDescription("description");
		sendLogToReportPortal("Place hoder for log. Can be modified in the BtRunner class.");
		return rq;
	}
	public static void sendLogToReportPortal(String log, File file) {
		ReportPortal.emitLog(itemUuid -> {
			SaveLogRQ rq = new SaveLogRQ();
			rq.setItemUuid(itemUuid);
			rq.setLevel("INFO");
			rq.setLogTime(Calendar.getInstance().getTime());
			rq.setMessage(log);
			rq.setLogTime(Calendar.getInstance().getTime());
			rq.setFile(file);
			return rq;
		});
	}
	public static void sendLogToReportPortal(String log) {
		sendLogToReportPortal(log, null);
	}
}

**Comment by evjlobanova** [comment]
Which agent and version of it do you use?

**Comment by keydiram** [comment]
<artifactId>agent-java-junit5</artifactId>
<version>5.0.2</version>

Report Portal version: Build: 5.1.0

**Comment by evjlobanova** [comment]
We are using the latest version 5.3.5
Since version 5.1 we have fixed a lot of bugs.
Please update to the latest version, and try to reproduce bug again
