### ISSUE TITLE
Unable to redeploy the report portal with out loosing the data.

### ISSUE THREAD

**Issue by lakshminagandla** [reportportal/reportportal#1434]
Hi ReportPortal Team,

Recently we come across with an issue saying, Report portal instance/machine recently crashed all the softwares that are deployed in C: drive. But we have Docker volume is stored in another drive.  Now we followed the below steps but unable to rollback the Report portal data.  

Procedure - 1: 
1. Installed docker.
2. Pointed the docker image location to the existing docker image location.  
3.  After that we tried to run the docker compose with old dokcer-compose.yml file. 

We have noticed report portal launched freshly, and not able to see any of the existing data. 
 
Can any one suggest how we can overcome this situation.

Note: As I informed earlier, we have existing docker image location "MobyLinuxVM.vhdx" file in safe.

**Comment by alena-babrova** [comment]
Hello @lakshminagandla,

Is the issue still relevant for you?

**Comment by alena-babrova** [comment]
Dear @lakshminagandla,
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
