### ISSUE TITLE
No Defect Category - Does AA works for this category?

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1438]
Just Checking - We have a category as No Defect. For those failed cases that I put in this category, would analyzer be able to categorize those as well in subsequent runs?

**Comment by evjlobanova** [comment]
For now not - No Defect is not included to AA.
In version 5.4.1 - we have added a possibility to automatically mark by No Defect failures which appear in the next run. But still, we are not planning to use No Defect as full defect
