### ISSUE TITLE
Wrong version in docker-compose

### ISSUE THREAD

**Issue by rosariotech** [reportportal/reportportal#1439]
I was trying to run the latest docker-compose and it was showing a Manifest error. I figure it was the version on service-ui that was incorrect in the docker-compose.yml.

![20210617-000009](https://user-images.githubusercontent.com/23159394/122403787-051eb380-cf55-11eb-8fac-ddf85255ede3.png)
![20210617-000008](https://user-images.githubusercontent.com/23159394/122403796-05b74a00-cf55-11eb-8161-75d251d15641.png)

When I changed the version from "5.4.0" to "v5.4.0" it worked!

**Comment by evjlobanova** [comment]
Version 5.4 is not officially released yet.
Please wait for an official annoncment
