### ISSUE TITLE
Video Attachments cannot be downloaded after upgrading to RP 3.0

### ISSUE THREAD

**Issue by HDimka** [reportportal/reportportal#144]
In 2.7 everything was working fine.

Our tests send the video attachment to RP, its recorded by https://github.com/SergeyPirogov/video-recorder-java.

Previously clicking on attachment it was downloaded by browser
![image](https://user-images.githubusercontent.com/11332788/27141437-d6466d38-5130-11e7-87d5-650e74ee6a74.png)

at the moment it it tries to decode it in new window 
![image](https://user-images.githubusercontent.com/11332788/27141468-ed1b3480-5130-11e7-95b0-349bb0a3214a.png)

Please fix it as it worked previously or add html video player to RP (better option)

**Comment by DzmitryHumianiuk** [comment]
@HDimka please specify version of `service-ui` you use.
you can find it on login page.

**Comment by DzmitryHumianiuk** [comment]
@HDimka looks like you send incorrect `contentType` of attachement.
you can find it in browser responce. for this line of log.

I guess, you have `contentType: text/plain` in it. So RP tries to represent it as a text.
if no any content type, RP will show it for download.

@avarabyeu do we have a code example for contentType of attachments?


BTW
videoPlayer is already mentioned in request #117 
in will be considered for 3.2 or 3.3
but still, if `contentType` will be incorrect, then videoPlayer will not detect in as source.

**Comment by HDimka** [comment]
UI Service: 3.0.0

Again, nothing was changed from our side.

we send video to RP as previously
ReportPortalMessage message = new ReportPortalMessage(new File(file.getAbsolutePath()), file.getName());

I see that inside it MimeTypeDetector distinguish a contentType. 
Which version of tika do you use? There can be a conflict between our libs

**Comment by HDimka** [comment]
Just read the content type using Files.probeContentType(Paths.get(file.getPath()));
it shows video/avi
I believe its correct

**Comment by DzmitryHumianiuk** [comment]
@HDimka please update to the latest UI-service: 3.0.2
and 3.0.3 will be also available during current week

**Comment by HDimka** [comment]
Video attachments can be downloaded with new UI-service: 3.0.2.
Thanks a lot!!!
