### ISSUE TITLE
Highlight Verification Step Pass/Fail with Green/Red Color coding.

### ISSUE THREAD

**Issue by rameshchandru88** [reportportal/reportportal#1442]
As part of a nunint framework, we use ReportPortal to capture the run report for each Test case executed .
Query: Is it possible to highlight or capture the verification steps in a separate report with Color coding as Pass/Fail with Green/Red color.

Expected Solution:

An clear HTML Report with Table of Test case Steps and Step status(Pass/Fail) highlighted in different colors in separate column s

Logs for each method executed are part of the report file generate in Report Portal which is not readable due to many contents and need to differentiate with the expected results steps.

**Comment by rameshchandru88** [comment]
Yes, I can control the logging level, but can we have the verification points Pass/Fail status to be highlighted for better understanding of the report(for the management)

**Comment by evjlobanova** [comment]
@rameshchandru88 do you try to use Nested Steps for that reasons?
![image](https://user-images.githubusercontent.com/30413511/123402124-4407c700-d55c-11eb-964d-7a0e83929818.png)
