### ISSUE TITLE
Started the report portal but not able to login with superadmin credentials [v5] after dataclean up

### ISSUE THREAD

**Issue by NLRKUM1** [reportportal/reportportal#1444]
**Describe the bug**

Started the reportportal with the command "docker-compose -p reportportal -f docker-compose.yml up -d --force-recreate"
but after data cleanup but now not able to login to the webpage with credentials  superadmin or default credentials or any previously created credentials.
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/48484003/123009426-f012ac00-d3bc-11eb-85eb-f85422a690d2.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by evjlobanova** [comment]
You can change a password 

For that, system admins should:

Generate a hash for new passwords of superadmin and default here
Add hash to password field into the script (default hashed passwords added below):
    UPDATE users
    SET password = 'a0$vhlxLsj.HcuQVrbRTmOu6OOjTYK/ZeiLTKEA2Sf5JOaxZ98/KHGem'
    WHERE login = 'superadmin';
    UPDATE users
    SET password = 'a0$WS7BhDl4caORMzBQz7y9zeF.iwLr87OipoubI5oo0D7OQ1qIZN8Jm'
    WHERE login = 'default';

**Comment by nandha081992** [comment]
@evjlobanova  How can I reset the password. I see the same issues now

**Comment by MaryiaRymarchyk** [comment]
Seems that there are no remain actions from ReportPortal side.
Therefore, ticket will be closed.
