### ISSUE TITLE
[v5.3.0] Exporting launches doesn't work for LDAP users

### ISSUE THREAD

**Issue by muratyazar** [reportportal/reportportal#1447]
Users who authenticated via LDAP can't export test results from launches page. When selecting an export option from launches page, file can be downloaded but it is empty and not consists any data. The file's size is 0 KB. But we don't encounter this issue  for internal users.

![image](https://user-images.githubusercontent.com/32167896/123257013-4afded80-d4fa-11eb-9c96-b3be174d5900.png)

**Comment by evjlobanova** [comment]
@svettsova Valya, could you please recheck this issue?

**Comment by Kalyan1989** [comment]
Hi Report Portal Team,
Do we have any update on this issue? It is really important to export the execution results offline, so that they can be distributed over email.
I will appreciate if you can please provide fix on this issue.

Thank you,
Kalyan

**Comment by MaryiaRymarchyk** [comment]
Hi @Kalyan1989, @muratyazar, i've checked export for LDAP user and it works fine for me. I as LDAP user able to export results and file contains all required info.
 Could you please try with the latest RP version?

**Comment by MaryiaRymarchyk** [comment]
UPD. Same issue were found on other landscapes and it doesn't relate to user type. Investigation is in progress.

**Comment by MaryiaRymarchyk** [comment]
Hi @Kalyan1989 , @muratyazar  
we have the problem with empty export on service-api:5.8.0 image. To make export work you need to change service-api version to service-api:5.8.0-exportFix.
Please update it and share if that helped with your issue
