### ISSUE TITLE
[v5.4] Launch URL by UUID still can't be displayed

### ISSUE THREAD

**Issue by zarashima** [reportportal/reportportal#1450]
Related to this: https://github.com/reportportal/reportportal/issues/1127. When I tried on 5.4 version, ReportPortal shows me the 'Not Found' page

My sample URL: http://reportportal.url/ui/v-key/launches/all/0df442ed-c450-41d4-a2ae-32fae564b385

Can anyone double-check again?

Thanks

**Comment by evjlobanova** [comment]
https://localhost:8080/ui/#project_name/launches/all/UUID

**Comment by zarashima** [comment]
Got it, my mistake. Thanks @evjlobanova . Close this for now
