### ISSUE TITLE
Add the option to go to the last stack trace page from the upper part of the screen

### ISSUE THREAD

**Issue by YBB8201** [reportportal/reportportal#1451]
I would like to have the >> sign on the upper part of the screen. at the moment it is located down below. if it would be in the upper part of the screen it would be easy to move to the last page of the stack trace without the need of scrolling down and click on it

**Is your feature request related to a problem? Please describe.** no
...
![Capture](https://user-images.githubusercontent.com/66330263/123945474-db2ead80-d9a6-11eb-8eec-9a7efbb9665f.PNG)

**Comment by evjlobanova** [comment]
You can use sorting for this reasons 
![image](https://user-images.githubusercontent.com/30413511/123958980-82d5bc80-d962-11eb-9af0-9efb4eb645bc.png)

**Comment by YBB8201** [comment]
great.
How can I set *by default*, that the checkbox "log with attachments" is
checked, and trace log is sorted from end to start ?

**Comment by evjlobanova** [comment]
These options are stored in local storage

**Comment by YBB8201** [comment]
Can you be more specific? How to configure it?

בתאריך יום ד׳, 30 ביוני 2021, 16:00, מאת Yauheniya Labanava ‏<
***@***.***>:

**Comment by evjlobanova** [comment]
You can not set it by default. But both of these parameters are stored in a local  storage for one user session. So that ypu can choose neededoptions first time, and during the session, chosen option will be aplyed
