### ISSUE TITLE
How to customise dashboard widgets.

### ISSUE THREAD

**Issue by krishnaPedd** [reportportal/reportportal#1452]
Hi Team,

i am planning to customise dashboard widget  which has details of last two execution launch details + build version + time took for execution.

can you please let me know how i can customise widgets to display all above data.

Thanks,
Krishna

**Comment by evjlobanova** [comment]
Hello 
Info is shown on widgets (axsis, tool tips) cannot be customized.
You can use widgets Cumulative trend chart, Component Health Check, Component Health Check (table widget). These widgets are working  using attributes, and it helps you to see information regarding build number
https://reportportal.io/docs/Cumulative-trend-chart
https://reportportal.io/docs/Component-health-check
https://reportportal.io/docs/Table-Component-health
