### ISSUE TITLE
No tests or logs reported after services are restarted with docker-compose 

### ISSUE THREAD

**Issue by muktarhassen** [reportportal/reportportal#1454]
I had to restart the services and so after the docker containers are restarted, the uuid, project and launch remained the same, but when tests are executed, the launch name appears under Launches in the UI, but clicking into it does not show any of the running tests or logs. I checked the docker-compose logs and I see the test logs appear except they say this:
ssage : Test Item '667829b5-ff9a-4c19-9043-45ec79672466' not found. Did you use correct Test Item ID?

Here is a fuller log:

api_1             | 2021-06-30T21:22:26.978547209Z 2021-06-30 21:22:26.978 DEBUG 7 --- [cTaskExecutor-1] c.e.t.r.w.rabbit.AsyncReportingListener  : onMessage - Rabbit message
api_1             | 2021-06-30T21:22:26.978563968Z  itemId: 667829b5-ff9a-4c19-9043-45ec79672466
api_1             | 2021-06-30T21:22:26.978568689Z  requestType: LOG
api_1             | 2021-06-30T21:22:26.978572238Z  x-first-death-exchange: reporting
api_1             | 2021-06-30T21:22:26.978575825Z  x-death: [{reason=expired, count=2, exchange=reporting.retry, routing-keys=[1], time=Wed Jun 30 21:21:26 UTC 2021, queue=reporting.retry.1}, {reason=rejected, count=2, exchange=reporting, routing-keys=[1], time=Wed Jun 30 21:20:26 UTC 2021, queue=reporting.1}]
api_1             | 2021-06-30T21:22:26.978579475Z  x-first-death-reason: rejected
api_1             | 2021-06-30T21:22:26.978582697Z  x-first-death-queue: reporting.1
api_1             | 2021-06-30T21:22:26.978585955Z  projectId: 3
api_1             | 2021-06-30T21:22:26.978589092Z  __TypeId__: com.epam.ta.reportportal.core.configs.rabbit.DeserializablePair
api_1             | 2021-06-30T21:22:26.978592269Z  -- Body --
****api_1             | 2021-06-30T21:22:26.978595432Z  {"left":{"itemUuid":"667829b5-ff9a-4c19-9043-45ec79672466","uuid":"e8fb02f5-1836-4c8a-a777-cb033d270fff","launchUuid":"5838ccd2-360f-43bb-87b0-08c0c42a5908","time":1625088026215,"message":"Starting new HTTP connection (1): astcoord.companyx.com:8080","level":"DEBUG"},"right":null}****
**api_1             | 2021-06-30T21:22:26.979178488Z 2021-06-30 21:22:26.979 DEBUG 7 --- [cTaskExecutor-1] c.e.t.r.w.rabbit.AsyncReportingListener  : exception : com.epam.ta.reportportal.exception.ReportPortalException, message : Test Item '667829b5-ff9a-4c19-9043-45ec79672466' not found. Did you use correct Test Item ID?,  cause :**
api_1             | 2021-06-30T21:22:26.979401817Z 2021-06-30 21:22:26.979  WARN 7 --- [cTaskExecutor-1] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.
api_1             | 2021-06-30T21:22:26.979425612Z
api_1             | 2021-06-30T21:22:26.979430393Z org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener threw exception
api_1             | 2021-06-30T21:22:26.979434153Z      at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:1693)
api_1             | 2021-06-30T21:22:26.979437840Z      at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1639)
api_1             | 2021-06-30T21:22:26.979441500Z      at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1509)
api_1             | 2021-06-30T21:22:26.979444808Z      at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1486)
api_1             | 2021-06-30T21:22:26.979448045Z      at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1477)
api_1             | 2021-06-30T21:22:26.979451533Z      at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1421)
api_1             | 2021-06-30T21:22:26.979458888Z      at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:963)
api_1             | 2021-06-30T21:22:26.979462361Z      at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:913)
api_1             | 2021-06-30T21:22:26.979465855Z      at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:81)
api_1             | 2021-06-30T21:22:26.979469098Z      at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1284)
api_1             | 2021-06-30T21:22:26.979472512Z      at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1190)
api_1             | 2021-06-30T21:22:26.979475791Z      at java.base/java.lang.Thread.run(Unknown Source)
api_1             | 2021-06-30T21:22:26.979478988Z Caused by: org.springframework.amqp.AmqpRejectAndDontRequeueException: null
api_1             | 2021-06-30T21:22:26.979482733Z      at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener.onMessage(AsyncReportingListener.java:179)
api_1             | 2021-06-30T21:22:26.979486109Z      at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener$$FastClassBySpringCGLIB$$3032a8df.invoke(<generated>)
api_1             | 2021-06-30T21:22:26.979489736Z      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
api_1             | 2021-06-30T21:22:26.979492939Z      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
api_1             | 2021-06-30T21:22:26.979496169Z      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
api_1             | 2021-06-30T21:22:26.979499472Z      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
api_1             | 2021-06-30T21:22:26.979506046Z      at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
api_1             | 2021-06-30T21:22:26.979509470Z      at com.epam.ta.reportportal.core.logging.RabbitMessageLoggingAspect.log(RabbitMessageLoggingAspect.java:70)
api_1             | 2021-06-30T21:22:26.979525759Z      at jdk.internal.reflect.GeneratedMethodAccessor303.invoke(Unknown Source)
api_1             | 2021-06-30T21:22:26.979529245Z      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
api_1             | 2021-06-30T21:22:26.979532421Z      at java.base/java.lang.reflect.Method.invoke(Unknown Source)
api_1             | 2021-06-30T21:22:26.979535628Z      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
api_1             | 2021-06-30T21:22:26.979538877Z      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
api_1             | 2021-06-30T21:22:26.979542139Z      at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
api_1             | 2021-06-30T21:22:26.979545250Z      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
api_1             | 2021-06-30T21:22:26.979550031Z      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
api_1             | 2021-06-30T21:22:26.979553402Z      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
api_1             | 2021-06-30T21:22:26.979556633Z      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
api_1             | 2021-06-30T21:22:26.979559787Z      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
api_1             | 2021-06-30T21:22:26.979562931Z      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
api_1             | 2021-06-30T21:22:26.979566542Z      at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener$$EnhancerBySpringCGLIB$$b75d7c19.onMessage(<generated>)
api_1             | 2021-06-30T21:22:26.979570141Z      at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1635)
api_1             | 2021-06-30T21:22:26.979573434Z      ... 10 common frames omitted
api_1             | 2021-06-30T21:22:26.979576589Z Caused by: com.epam.ta.reportportal.exception.ReportPortalException: Test Item '667829b5-ff9a-4c19-9043-45ec79672466' not found. Did you use correct Test Item ID?
api_1             | 2021-06-30T21:22:26.979579872Z      at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener.onLogCreate(AsyncReportingListener.java:216)
api_1             | 2021-06-30T21:22:26.979583092Z      at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener.onMessage(AsyncReportingListener.java:156)
api_1             | 2021-06-30T21:22:26.979586382Z      ... 31 common frames omitted
api_1             | 2021-06-30T21:22:26.979589587Z

**Comment by evjlobanova** [comment]
Which version of report portal do you use?
Which agent and which agent version do you use?

**Comment by muktarhassen** [comment]
![reportPortal](https://user-images.githubusercontent.com/25141949/125646297-2b35dce5-1d1b-4c07-b584-ce8978cbbae6.PNG)
 I'm using version 5.4. Here are the containers.  The migration service keeps restarting every minute.

**Comment by evjlobanova** [comment]
@Cyberglamdring Hleb, could you please check

**Comment by MaryiaRymarchyk** [comment]
@muktarhassen as Issue is quite old and no updates here - i'll close it. 
Recent RP version - https://github.com/reportportal/reportportal/releases/tag/v24.1
If the issue still actual or any concerns remains - please create new one or reopen it with updated information

**Comment by BenManifold** [comment]
I had to resize the rabbit storage, and elasticsearch, and this is biting me now. Not sure why it was closed, it's still clearly a problem.

**Comment by Pink-Bumblebee** [comment]
@BenManifold , I think that this old issue was closed because it was related to version 5.4.0. If you have same version - please upgrade to 24.1. If you already did it and problem still existing - you could open new issue.
