### ISSUE TITLE
The stack trace for failure in case of html snippet for element failure shows that HTML control instead of escaping it or showing as plain text

### ISSUE THREAD

**Issue by mayuresh49** [reportportal/reportportal#1455]
`org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element <input type="checkbox" id="addMeetLink_0" ng-model="interview.addMeetLink" ng-disabled="interview.interview_type !== 'TH_ATS_ONLINE'" class="ng-pristine ng-untouched ng-valid ng-empty"> is not clickable at point (1179, 210). Other element would receive the click: <th ng-if="review_interview.is_google_calender">...</th> (Session info: chrome=91.0.4472.114) Build info: version: '4.0.0-beta-3', revision: '5d108f9a67' System info: host: 'peoplehums-MacBook-Pro.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '15.0.2' Driver info: org.openqa.selenium.chrome.ChromeDriver Command: [f6cee7c116f21eacd41639a7502c2b92, clickElement {id=af3cd164-6f29-4056-a150-0bf440376fae}] Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 91.0.4472.114, chrome: {chromedriverVersion: 91.0.4472.101 (af52a90bf870..., userDataDir: /var/folders/yw/nhvsdyfj2sb...}, goog:chromeOptions: {debuggerAddress: localhost:52240}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), se:cdp: ws://localhost:52240/devtoo..., se:cdpVersion: 91.0.4472.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true} Element: [[ChromeDriver: chrome on MAC (f6cee7c116f21eacd41639a7502c2b92)] -> xpath: //input[contains(@id,"addMeetLink") and contains(@class,"ng-empty")]] Session ID: f6cee7c116f21eacd41639a7502c2b92 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481) at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:198) at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:131) at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52) at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184) at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:153) at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:128) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:619) at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:237) at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:75) at com.xxx.automation.pages.hire.XPage.reviewAndSchedule(XPage.java:6032) at com.xxx.automation.tests.hire.integrations.google.XTest.XTest(XTest.java:35) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:564) at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) at org.testng.internal.Invoker.invokeMethod(Invoker.java:583) at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719) at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989) at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) at org.testng.TestRunner.privateRun(TestRunner.java:648) at org.testng.TestRunner.run(TestRunner.java:505) at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) at org.testng.SuiteRunner.access$000(SuiteRunner.java:40) at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489) at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) at java.base/java.lang.Thread.run(Thread.java:832) `

![image](https://user-images.githubusercontent.com/39514615/124065791-138cc500-da55-11eb-96aa-4b3cb90430b3.png)

**Comment by mayuresh49** [comment]
This leads to HTML injection and might be concerning for cloud users.

**Comment by evjlobanova** [comment]
@AmsterGet Ilya, could you please suggest a possible options?

**Comment by HardNorth** [comment]
@evjlobanova @mayuresh49 It's by design. If you need your messages escaped you have to do this by yourself. And there is no any concerns for cloud users since we accept processing of very limited amount of tags.
