### ISSUE TITLE
Issues Observed after upgrade from V5.3.5 to V5.4

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1456]
My tests were running on RP setup1 -  V5.3.5 . I took the dump of this data on V5.3.5 and restored it on RP instance for which I had setup2 - V5.4.

Now on my RP setup 2 (V5.4 - which has dump restored from 5.3.5)  i see a few anomalies:
1. After restore when an looked at few of the existing launches, the test steps were missing (which were present in V5.3.5).  
![image](https://user-images.githubusercontent.com/50797731/124103533-fec52700-da7e-11eb-9e9b-277e89ea728f.png)

2. When I triggered a fresh run on this instance, my stacktrace was not been captured for any of the failed steps -  
![image](https://user-images.githubusercontent.com/50797731/124104029-7bf09c00-da7f-11eb-9b43-f5f97b18bc25.png)

Can you suggest, if I am missing anything while doing an upgrade? 
@evjlobanova

**Comment by SavvasLakshmiNagandla** [comment]
Hi Priyanka, 

Can you please let me know detailed steps that you followed to dump the data  from 5.3.5 to  from 5.4.

**Comment by Invictum** [comment]
@priyankachaturvedi30 
5.3.5 and 5.4 have different data structure, there is why migration is needed. If you just dumped and restored DB data I'm not sure it will work as expected because of data inconsistency.

**Comment by priyankachaturvedi30** [comment]
@SavvasLakshmiNagandla : Yes, So I just dumped and restored DB data from 5.3.5 onto 5.4 . using the following steps : 
![image](https://user-images.githubusercontent.com/50797731/124454809-7f996100-dda6-11eb-8b22-050102dec924.png)

@Invictum : Can you help me with how do I go ahead with migration if I want to upgrade my version?

**Comment by Invictum** [comment]
@priyankachaturvedi30 
Migration scripts is a part of RP distribution so it will happen automatically when v5.4 will detect old DB structure. The only thing you should to consider is migration time that depends on initial DB size. And I suggest to copy directory with DB before migration just in case.
Refer to https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.5.4 for detailed instructions

**Comment by priyankachaturvedi30** [comment]
Sure, I'll try it out once.

**Comment by evjlobanova** [comment]
@priyankachaturvedi30 Have you resolved the issue? Can I close the issue?

**Comment by MaryiaRymarchyk** [comment]
Hi @priyankachaturvedi30 ,
as we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
