### ISSUE TITLE
Suggestions for UI test steps page improvements

### ISSUE THREAD

**Issue by ksuglotova** [reportportal/reportportal#146]
Recieved from @serporit (slack/reportportal/russian):
1. Set defect type and add link are now two separate actions. The reasoning for that is unclear. And such approach is highly uncomfortable especially in bulk operations.
2. Being in section "To investigate", when the defect type was set then the test step stays in a list and user has to refresh page to make test step disappear from the list "To investigate"
3. When user wants to perform bulk operation and check first item then page jumps with check mark shifting out of screen (see gif)
4. When user opens new tab, hit the End key to go to the end of log then nothing happens. To go to the end of log user has to click on tab working area first then hit the End button. In previous versions we could just hit the End key without clicking on tab working area.

**Comment by ksuglotova** [comment]
Fixed

**Comment by ksuglotova** [comment]
i.2 is fixed

**Comment by DzmitryHumianiuk** [comment]
i.1 in progress

**Comment by e-olga** [comment]
fixes of 2-4 issues are already available in 3.0.5 released version
fix of the 1 issue will be included in 3.1.
