### ISSUE TITLE
Merge report portal launchers automatically, which created on the same day

### ISSUE THREAD

**Issue by lasithdilshan20** [reportportal/reportportal#1460]
Hi,

I am using Cypress as our main test framework.

We are doing a couple of executions on the same day (including CI/CD). Then it is creating several launchers with **same name**.
Would you mind letting me know? Is their way to merge launchers automatically (Not manually), **which created on the same day**.

![image](https://user-images.githubusercontent.com/16818367/124434249-45719480-dd91-11eb-8c9c-2138f2ca9932.png)

**Comment by Invictum** [comment]
@lasithdilshan20 
Almost all RP ui functionality are available via rest API. So you can create a job that will run once per day, query all the launches for that day and then execute launch merge. It is literally 2 sequential API queries.

**Comment by lasithdilshan20** [comment]
> @lasithdilshan20
> Almost all RP UI functionality is available via rest API. So you can create a job that will run once per day, query all the launches for that day and then execute launch merge. It is literally 2 sequential API queries.

@Invictum Thanks for the reply. Could you please elaborate?

**Comment by evjlobanova** [comment]
Hello @lasithdilshan20! You can find merge calls on API documentation page. Could you please describe which kind of problems do you have?

**Comment by lasithdilshan20** [comment]
> Hello @lasithdilshan20! You can find merge calls on API documentation page. Could you please describe which kind of problems do you have?

 "reporter": "@reportportal/agent-js-cypress",
  "reporterOptions": {
    "endpoint": "https://reportportal.sana-commerce.com/api/v1",
    "token": "xxxxxxxxxxxxxx",
    "launch": "Addon Automation Nightly Build Report",
    "project": "xxxxxxxxxxxx_personal",
    "description": "Regression Test Automation Report for CI/CD",
    "autoMerge": true
  }
}

this is my code block on cypress.json , but automatically merge is not working after the execution

**Comment by evjlobanova** [comment]
The idea is that you can add an api call to your pipeline and trigger API when you need it

**Comment by MaryiaRymarchyk** [comment]
Hello @lasithdilshan20, did you solve your problem or support from us still required?

**Comment by lasithdilshan20** [comment]
> Hello @lasithdilshan20, did you solve your problem or support from us still required?

I just reconfigured the report configuration. Then this issue was sorted out, but the same issue was raised again after a few months. I used an alternative workaround (Automation script) to merge the result.
