### ISSUE TITLE
Unable to Integrate Auto-Analysis Feature to Project

### ISSUE THREAD

**Issue by dy6wang** [reportportal/reportportal#1462]
Hi,

Currently, I have ensured that the auto-analysis feature was turned on. I have also ran test scenarios multiple times and I have manually analyzed the issues that are labelled "To Investigate". However, it doesn't seem like the auto-analysis feature is working. On the other hand, when I login with GitHub via (https://demo.reportportal.io/ui/#login) and perform the same steps using demo data from ReportPortal, I was able to see Auto-Analyzed (AA) test scenarios. I am wondering if auto-analysis wasn't working due to the test scripts I'm using. Currently, the log messages of all my failed tests only show up in "Trace", however it doesn't show up in "Error" within ReportPortal (screenshot provided below). I am wondering if auto-analysis feature is not working in my case because auto-analysis only works on test scenarios that have log messages in "Error" section. Can I get confirmation on whether or not this could be the cause? Thanks in advance. 

screenshot:
![image](https://user-images.githubusercontent.com/87076896/124781727-a32cea80-df11-11eb-9cc2-66aabdaac54e.png)

**Comment by MariyaIvanina** [comment]
@dy6wang Hi! We analyze only error/fatal logs, so if you have Trace logs we won't use them for analysis. If you'd like to setup Analysis, please report your logs as error or fatal ones.
