### ISSUE TITLE
Can we push direct data directly to postgress database running in my local docker container 

### ISSUE THREAD

**Issue by skmvali** [reportportal/reportportal#1464]
Hi ,

I just finished setup for reportal in my local machine using docker . Connected to reportal postgress db instance running in my local.

Is there sample sqls statements, provided to push all data directly from backend instead from UI?

Thanks
vali

**Comment by evjlobanova** [comment]
Could you please elaborate on your request? Could you please describe what problem do you try to resolve?

**Comment by MaryiaRymarchyk** [comment]
@skmvali hi, 
long time no hear from you, so we'll close the issue for now.
Just in case you still have the issue, please, provide more details.
