### ISSUE TITLE
[v5]Need uuid or id for created launch

### ISSUE THREAD

**Issue by lavanyach-sailo** [reportportal/reportportal#1467]
I am trying to get uuid or id for created launch but the result uuid is not matching with the report portal api values. I am using java for this scenario.

Getting uuid as Maybe object as below
io.reactivex.internal.operators.maybe.MaybeCache@74babce8

but i am trying to match it with the API calls dont know how to get that value which API returns.
And unable to find any method in java to get launch id that API resturns

Can anyone help on this?

Thanks,

**Comment by evjlobanova** [comment]
Hello! Here you can find a full description of how to report results to reportportal https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#start-launch

UUID is returned in the response at the launch start
