### ISSUE TITLE
Attachments section only are displaying 12 screenshots 

### ISSUE THREAD

**Issue by babantax** [reportportal/reportportal#1469]
**Describe the bug**
When a test execution has more than 12 screenshots, only first 12 are shown on attachments section. 
Im sure all the screenshots were properly saved because I can see them attached on the steps in the log section

**To Reproduce**
Execute a test with more than 12 screenshots

**Expected behavior**
See all the screenshots in the attachments section.

**Screenshots**
![image](https://user-images.githubusercontent.com/52815118/125771185-66dbeaac-650b-4745-b3df-c32d9af6e491.png)
![image](https://user-images.githubusercontent.com/52815118/125771677-99589be3-e3e8-48bd-bff3-57e6bbb0b265.png)

**Additional context**
Report Portal version 5.3.1

**Comment by HardNorth** [comment]
@evjlobanova please check

**Comment by evjlobanova** [comment]
@VolhaKarenko Olya, could you please try to reproduce this issue?

**Comment by VolhaKarenko** [comment]
hi @babantax, please upgrade to RP 5.5, the issue is not reproducible on versions 5.4 and higher
