### ISSUE TITLE
Stack trace/error message is minimized to 10 lines, other to 4 lines

### ISSUE THREAD

**Issue by ksuglotova** [reportportal/reportportal#147]
Recieved from @serporit (slack/reportportal/russian):
Stack trace/error message is minimized to 4 lines. It might be better to show at least 10 lines of log for each test step.

**Comment by ksuglotova** [comment]
Idea for discussion: to add user config option how many lines leave for stack trace/error messages on a Test steps page.

**Comment by DzmitryHumianiuk** [comment]
error message will be shown with 10 lines collapse

default size for other messages will be 4
