### ISSUE TITLE
Failed Cases Trend Chart shows FL+SKP count

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1475]
As described, Failed cases trend chart - Shows the trend of growth in the number of failed test cases from run to run.
As per my understanding it should have gave me the count specific to failures , but it is showing the count for Failed+Skipped cases. 
![image](https://user-images.githubusercontent.com/50797731/126644128-77a9ccfd-9fc1-4447-8800-39a2e2b9128c.png)

THis is misleading for me as the status of skipped cases comes as Skipped for me, and not failed.
![image](https://user-images.githubusercontent.com/50797731/126644335-d9e024c4-9d52-4927-96a5-7a1bf431c964.png)
 If it still is configured to behave in the same fashion (rendering FL+SK count), can we at least have the option of selecting whether we want just failed cases or skipped cases while creating this widget ? @evjlobanova @DzmitryHumianiuk 

Adding to the same , I observed this, where non-passed test-cases shows FL+SK, while Failed cases just shows Failed, but still displays FL+SKP :( (Looks more like a bug)
![image](https://user-images.githubusercontent.com/50797731/126649289-175d5b35-2913-4073-9b7f-d252bd9c6a83.png)

**Comment by VolhaKarenko** [comment]
Fixed in version 5.6
