### ISSUE TITLE
Jira Integration does not seems to be working after few runs

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1477]
@DzmitryHumianiuk @evjlobanova : I integrated Jira with Report Portal when i started my first run. Each day the execution happens and issues gets aa for me. I noticed in my lastest- 10th run, the issues still have jira associated with them, but when I hover it says:
![image](https://user-images.githubusercontent.com/50797731/127118890-7f8aa934-c8b1-4eb5-8153-ea0676573f7b.png)

However, when I click on the associated jira, I am redirected to the jira. 
I checked back in this settings and it shows the following:
![image](https://user-images.githubusercontent.com/50797731/127119142-ae1dc26c-49ed-4d76-835d-9b5f57567d30.png)

Do I need to remove integration and add again? And most importantly what caused this issue? Please help.

**Comment by priyankachaturvedi30** [comment]
Hey, @evjlobanova : did you get a  chance to look at this one? Should I re-configure jira ? But just worried if re-configuring would impact the baselines where I have already associated failures with jiras...Please suggest.

**Comment by VolhaKarenko** [comment]
Hi @priyankachaturvedi30, try removing the integration and adding it again, associated jiras will remain + corresponding tooltips on hover should be displayed. The root cause is probably issues on jira side.

**Comment by Shakevg** [comment]
@priyankachaturvedi30 I had the same issue after changing my domain password. The issue was resolved only after the Support team several times clears the Jira cache and I re-login to Jira.
