### ISSUE TITLE
Feature request: Don't set a number in launch name (#1 etc.) if the launch has unique name

### ISSUE THREAD

**Issue by jurteg** [reportportal/reportportal#149]
We're using generated names for launches, that come from the Jenkins and every time launch name reflects appropriate build number on Jenkins. It is difficult to read launch names, when RP sets it's own launch number to launch which has unique name and already has it's own number.

![rp_feature_request_1](https://user-images.githubusercontent.com/25842206/27383644-8f55932c-5694-11e7-9a04-3de27c2970c9.png)

**Comment by DzmitryHumianiuk** [comment]
@jurteg this part will stay as obligatory,

until column configuration will be introduced.
but it's not planned for now.
