### ISSUE TITLE
Analyser not working after removing/regenerating index

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1491]
Facing this error while trying to work with analyzer. All services are healthy.
![image](https://user-images.githubusercontent.com/50797731/128137792-9a51ffae-2574-4f21-96bf-4fee687ff63d.png)
Can you please suggest what needs to be done?

**Comment by realsilversurfer** [comment]
Facing same issue. Any update on this?

**Comment by MariyaIvanina** [comment]
@priyankachaturvedi30 Hi! Could you show more of your log? and whether analyzer works? or after this error it doesn't work completely?

**Comment by realsilversurfer** [comment]
It actually does not work completely, index buttons are greyed out and AA is not working anymore.

**Comment by MariyaIvanina** [comment]
and what about log? whether you have a full log? was it on the generation index step or on other?

**Comment by realsilversurfer** [comment]
[analzyer.log](https://github.com/reportportal/reportportal/files/6967359/analzyer.log)
Here is a log from analyzer

**Comment by MariyaIvanina** [comment]
I can see you use 5.3.5 version. Our new version is 5.5.0. The error is not a problem at all, it is just for our system communication, and in a newer version this error doesn't happen.

**Comment by MariyaIvanina** [comment]
@realsilversurfer Did you manage to generate index? or they were always greyed out? If they are always greyed out, there is a problem in service-index or traefik.

**Comment by realsilversurfer** [comment]
They are always greyed out now and since that AA does not work.

**Comment by MariyaIvanina** [comment]
Have you changed something recently in the Report portal configuration recently? updated some parts?
