### ISSUE TITLE
Widget - Launches Table shows a "Status" Column from where ?

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1496]
@evjlobanova  @DzmitryHumianiuk : I created a Launches Table widget, but I see a status column present there, can you point me to how this gets resolved to Failed? I could not find any reference for it from the documentation page..
![image](https://user-images.githubusercontent.com/50797731/128187137-5362d252-175e-48d5-844e-5997a0027064.png)

**Comment by evjlobanova** [comment]
Status of launch is calculated automatically: if a least one test is not passed, a launch status is failed. Or you can send a launch status explicitly, and in this case, auto-calculated status is rewritten by a status that has been sent by the user.

Each launch has a status, but on the All launches table this info is not shown.
