### ISSUE TITLE
add option for show passing rate per filter on test level

### ISSUE THREAD

**Issue by AmrWatad** [reportportal/reportportal#1498]
current version show an passing rate on launches level
when filtering tests, it's show the relevant tests with **passing rate on launch level**
its nice to show passing rate on test level when be filtered not on launch level

Example: 
1. filtering 
2. pass rate on launch level
3. test level: 4 passed, 1 skipped

**if pass rate on test level found, the report should show: 4/5=80.00% pass rate**
![image](https://user-images.githubusercontent.com/33550928/128691763-ee332a95-5354-4b83-820d-91055e5b48f0.png)

Example2:
- current
after filter found two passed test from 5, pass rate 80.00%
new feature(on test level)
should show: 2/2 with 100.00%  
![image](https://user-images.githubusercontent.com/33550928/128694168-332ab56d-db2d-4039-963e-6b4837ecf493.png)

**Comment by evjlobanova** [comment]
Thank you for the request!
Could you please describe your business case? Why do you need this feature?

**Comment by AmrWatad** [comment]
@evjlobanova 
we run a suit of tests with tags 
we need this feature for see the pass rate of specific tests(filter by tag) on the launch

**Comment by evjlobanova** [comment]
For that reason, you can use a widget Component Health Check Widget or Component Health Check Widget (table view) https://reportportal.io/docs/Table-Component-health

**Comment by DzmitryHumianiuk** [comment]
Please try for this
https://reportportal.io/docs/dashboards-and-widgets/TableComponentHealthCheck/
