### ISSUE TITLE
Get the "launch name" or link to launch

### ISSUE THREAD

**Issue by YBB8201** [reportportal/reportportal#1499]
Hi 
I am trying to get a link or at least the launch name in order to report it in my own code. this way i can get to the run much easily.
is there a way to get it via code (api) or some other way. 
thx
Yohai

**Comment by evjlobanova** [comment]
If you are using version 5.5, you can generate a link based on https://localhost:8080/ui/#projectName/launches/all/UUID_launch

**Comment by YBB8201** [comment]
hi
how can I get UUID_launch while I am running my test ?
I want to get the link in order to "log" it. That way I can find the report
easily.

**Comment by evjlobanova** [comment]
In response at the launch start you receive a UUID

**Comment by YBB8201** [comment]
hi
i tried to use the following:

https://github.com/reportportal/example-net-nunit/blob/master/src/Example/ReportPortalCustomization/Customization.cs

but developers told me it is not ready yet - will be ready in the
future (see [reportportal/example-net-nunit] mark skipped tests as
No-Defect type (#12))

I am trying to understand how to get the UUID back to my code.

Can you refer me to some examples that will work on version 5.5 ?

**Comment by nvborisenko** [comment]
The link provided by you above works good, at least on my side and all known real users. You are able to customize default agent's behavior. If something doesn't work properly on your side, please share your simple test project to reproduce the issue.

> but developers told me it is not ready yet
Right, separate nuget package (extension for the agents), which will remove requirement to investigate skipped tests, is planned and will be developed when time will allow me. But you are still able to do it on your side, via extension. Code is ready and accessible for everyone. Again, if something doesn't work, please share specific details.

> I am trying to understand how to get the UUID back to my code.
The same approach - via extension.

![image](https://user-images.githubusercontent.com/22616990/130083672-823db9fd-e940-42d5-9f5f-3de703a2743d.png)

Welcome to contribute.

**Comment by YBB8201** [comment]
Hi, great news!
So, just to make it clear, I need to upgrade my RP to version 5.5 and it
should work, right?
As I understood version 5.3.4 does not support getting Uuid.

בתאריך יום ה׳, 19 באוג׳ 2021, 17:12, מאת Nikolay Borisenko ‏<
***@***.***>:
