### ISSUE TITLE
Migrate data to new instance

### ISSUE THREAD

**Issue by asaflevyz** [reportportal/reportportal#1505]
We want to migrate projects settings and users only to new instance.
Is there any way we can export from old instance and then import to new instance the data?

Thanks.

**Comment by evjlobanova** [comment]
There is no such function out-of-the box.
ReportPortal provides professional support on top of the product,
Which may include deployment, consultancy, customizations, training, and integration.
Then we can offer a service provided by the ReportPortal development team.

Please let us know, if you need more details

**Comment by asaflevyz** [comment]
Thanks.
