### ISSUE TITLE
Add possibility to create custom rules for analyzer

### ISSUE THREAD

**Issue by ghost** [reportportal/reportportal#151]
In many cases auto-analyze system does not match similar failed tests. 

For example, on our project responces can return different combination of errors/warnings when broken by one issue. It can be 1 error + 1 warning, or 2+2, or 1+2, or the same but in different order. 
As a result, the auto-investigation system gives no matches at all.

It could be very useful to have possibility of creating "rules" for analyzing system, such as:
"If error message contains "Error receiving asynchronous response" - mark failed test as a product bug and load jira ticket #ADC-4551"

**Comment by ksuglotova** [comment]
In case of math algorithm using false positive results are worse (algorithm sets particular defect type and it's wrong)

**Comment by ksuglotova** [comment]
Upon a log messages provided the 'stop word' approach looks useful.
Actually, the key error message for analyzer is placed between words 'description' and 'type' or 'description' and line feed character or 'description' and special symbol. The result should be cleaned from any special symbols and digits.
As a result we'll get a set of strings, like:
test_step#1:
Error receiving asynchronous response message
Exception occured in AmadeusAirLowFareSearchHandlerImpl
NOFLIGHTSFOUND
test_step#2:
NOFLIGHTSFOUNDnswarning
Exception occured in AmadeusAirLowFareSearchHandlerImpl
Error receiving asynchronous response message
After sorting, we get pairs:
1) Error receiving asynchronous response message
    Error receiving asynchronous response message
2) Exception occured in AmadeusAirLowFareSearchHandlerImpl 
    Exception occured in AmadeusAirLowFareSearchHandlerImpl
3) NO FLIGHTS FOUND
    NO FLIGHTS FOUND

**Comment by ksuglotova** [comment]
The last point is to check other stack-trace logs to make sure the assumption about error message place is valid.

**Comment by evjlobanova** [comment]
In version 5.0 we have added #673 Pattern analysis.
In version 5.3+ we are planning to add Actionable Pattern analysis.

**Comment by evjlobanova** [comment]
Closed as the duplicate #569
