### ISSUE TITLE
[v5] DOM based XSS vulnerability on login page using vulnerable errorAuth parameter

### ISSUE THREAD

**Issue by IoTravis** [reportportal/reportportal#1522]
**Describe the bug**
The ReportPortal login page does not validate / sanitize the `errorAuth` parameter.  

This issue could be leveraged by an attacker to steal login credentials of the reporting portal as well as cookies.

**To Reproduce**
This URL demonstrates the behavior on demo.reportportal.io.
`https://demo.reportportal.io/ui/#login?errorAuth=aaa<iframe%20src=javascript:alert(document.domain)></div>`

**Expected behavior**
Input is validated and escaped or discarded.
https://cheatsheetseries.owasp.org/cheatsheets/DOM_based_XSS_Prevention_Cheat_Sheet.html

**Screenshots**
<img width="1542" alt="rp_v5_xss_errorAuth" src="https://user-images.githubusercontent.com/18267047/132864281-1a85c5c0-b0f6-405a-8bfc-f10cc7e6f3ef.png">

**Desktop**
 - OS:  macOS Big Sur (11.5.2)
 - Browser: Chrome 93.0.4577.63, Firefox 92.0, Safari 14.1.2
 - Version: API Service: 5.5.0; Index Service: 5.0.10; Jobs Service: 5.5.0; Authorization Service: 5.5.0; Service UI: 5.5.0;

**Comment by evjlobanova** [comment]
@IoTravis thank you for posting this bug!
We will fixed is soon as a possible and make announcement for users

**Comment by IoTravis** [comment]
Thanks for the quick evaluation and getting a fix in the pipeline!

**Comment by VolhaKarenko** [comment]
The issue is fixed in version 5.5.1
