### ISSUE TITLE
Uploading junit style xml reports using REST API

### ISSUE THREAD

**Issue by kwmlodozeniec** [reportportal/reportportal#1525]
Hi!

Great project btw. I am trying to integrate RP into our CI pipeline as we have various homegrown frameworks. Is there a way of using the REST API to simply upload a Junit style test report to the RP instance? I searched and searched and could not find an obvious example.

**Comment by DzmitryHumianiuk** [comment]
https://reportportal.io/docs/log-data-in-reportportal/ImportDataToReportPortal/#import-via-api
