### ISSUE TITLE
Extend possibilities of filter

### ISSUE THREAD

**Issue by ghost** [reportportal/reportportal#153]
It will be very useful to have a possibility to combine AND/OR operators when using filter.
For example:
I want to filter launches with tags 
("10.160.6.136" OR "10.160.6.167") AND ("regression" OR "smoke")
For today we don't have a possibility to create such filters. Only OR or AND filters are possible.

**Comment by dmitryyu** [comment]
In general, it would be cool to activate some filters at the same time.
For example we have filters: 
"Filter1"  - contains name "Name1"
"Filter2"  - contains name "Name2"
for now we can activate only one possible filter, 
In case of multi filter selection - we would be able to activate both filters: and a result it'd display all launches based on the combine of filters:
contains name "Name1" OR contains name "Name2"

**Comment by evjlobanova** [comment]
I joined this request with #845.
You can follow the progress on this feature in the mentioned ticket.
