### ISSUE TITLE
What happened to Latest Launches Widget?

### ISSUE THREAD

**Issue by SamZigo** [reportportal/reportportal#1530]
Hello Report Portal Team,

In version 5.3 We had something called Latest Launches widget which was quite uselful for us. However when I upgraded to version  5.5.0 It is no longer working and it is not even there when I want to add a new one. I thought this was some kind of error during migration so I tried a clean installation of Report Portal 5.5.0 on another machine but it is not there either. I was looking at the feature list and introduction videos but I couldn't find any information about this feature being removed. Can you please tell me what could be wrong? 

These widgets worked just fine before upgrade.
![image](https://user-images.githubusercontent.com/72862495/133971441-2ef48463-e524-4e5a-b8e2-e8c4b02805cd.png)

Latest launches is not even among the listed widgets when I want to add the new one. 
![image](https://user-images.githubusercontent.com/72862495/133971514-32df9a2c-316d-49e8-b65d-8d68dcee541b.png)

**Comment by MaryiaRymarchyk** [comment]
@SamZigo  hello,
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have questions, please, do not hesitate to contact us.
