### ISSUE TITLE
Report portal crashing due to maximum upload size exceeded

### ISSUE THREAD

**Issue by allan-silverstein** [reportportal/reportportal#1533]
**Describe the bug**
Report Portal crashes with the following trace. 

```
021-09-21 01:38:05failures/test_ncc_failure.py:627: in test_ncc_failure
    logger, testinfo, rp_logger)
lib/dnet_generic.py:802: in process_test_function_results
    attach_session_logs(testinfo,rp_logger)
lib/dnet_generic.py:788: in attach_session_logs
    "data": contents, "mime": "text/plain"})
/usr/local/lib/python3.7/logging/__init__.py:1378: in info
    self._log(INFO, msg, args, **kwargs)
/opt/p1-dir/python-venv/p1-user-venv/lib/python3.7/site-packages/pytest_reportportal/rp_logging.py:49: in _log
    self.handle(record)
/usr/local/lib/python3.7/logging/__init__.py:1524: in handle
    self.callHandlers(record)
/usr/local/lib/python3.7/logging/__init__.py:1586: in callHandlers
    hdlr.handle(record)
/usr/local/lib/python3.7/logging/__init__.py:894: in handle
    self.emit(record)
/opt/p1-dir/python-venv/p1-user-venv/lib/python3.7/site-packages/pytest_reportportal/rp_logging.py:102: in emit
    attachment=record.__dict__.get('attachment', None),
/opt/p1-dir/python-venv/p1-user-venv/lib/python3.7/site-packages/pytest_reportportal/service.py:329: in post_log
    self.rp.log(**sl_rq)
/opt/p1-dir/python-venv/p1-user-venv/lib/python3.7/site-packages/reportportal_client/service.py:391: in log
    return self.log_batch([data], item_id=item_id)
/opt/p1-dir/python-venv/p1-user-venv/lib/python3.7/site-packages/reportportal_client/service.py:461: in log_batch
    return _get_data(r)
/opt/p1-dir/python-venv/p1-user-venv/lib/python3.7/site-packages/reportportal_client/service.py:98: in _get_data
    raise ResponseError(error_messages[0])
E   reportportal_client.errors.ResponseError: 5000: Unclassified error [Maximum upload size of 67108864 bytes exceeded; nested exception is org.apache.commons.fileupload.FileUploadBase$FileSizeLimitExceededException: The field file exceeds its maximum permitted size of 67108864 bytes.]
```

**To Reproduce**
Certain tests I'm running produce large log files.  These log files are uploaded to report portal via the reportportal_client.  (I believe this is happening during log file upload...)  Is there a way to increase this value to accommodate larger File uploads? 

This is the code that is uploading log files:
```
#############################################################
# Send netmiko session logs as attachments to ReportPortal
#############################################################
def attach_session_logs(testinfo,rp_logger):
    for dev in testinfo['log_files']: # loop through session log file names
        dirpath = os.getcwd()

        # get log file in current working directory
        log_dir = Path(dirpath,testinfo['log_files'][dev]) 

        # open log file and send contents as an attachment to reportportal
        with open(log_dir) as file: 
            contents = file.read()
            rp_logger.info("Session Log Attachment - " + testinfo['log_files'][dev],
                                     attachment={"name": testinfo['log_files'][dev],
                                    "data": contents, "mime": "text/plain"})
```

**Desktop (please complete the following information):**
 - OS: [e.g. Docker Container running on Ubuntu]

**Comment by evjlobanova** [comment]
Hello 
Which version of ReportPortal do you use? Which agent (and version) do you use?

**Comment by allan-silverstein** [comment]
Report Portal Version: 5.3.5

I'm using Pytest Report Portal Client
pytest-reportportal==5.0.3
reportportal-client==5.0.3

**Comment by koenigcode** [comment]
no i have the latest with the same problem 
{"errorCode":5000,"message":"Unclassified error [Maximum upload size of 134217728 bytes exceeded; nested exception is org.apache.commons.fileupload.FileUploadBase$SizeLimitExceededException: the request was rejected because its size (175337995) exceeds the configured maximum (134217728)]"}
answer from docker installed reportportal.

**Comment by irynakozak2** [comment]
@koenigcode Hello,
Yes, we have two limits regarding max file size uploading:
 - from the service-API side(by default - 64Mb), which is have been configured by the adding to API proper environment variable;
 - from the proxy service side(traefik for Docker, Nginx for Kubernetes).
 
 I'll notify you in advance about the needed settings.

**Comment by DavidDahan1** [comment]
@irynakozak2 any progress on this one?

**Comment by Oleksii-kh89** [comment]
Hi @DahanDv 
You can try to config the size from the service-API side using these variables:

RP_UPLOAD_MAXUPLOADSIZE: 128MB
RP_UPLOAD_MAXFILESIZE: 64MB

**Comment by zathoma-sys** [comment]
@Oleksii-kh89, were those environment variables intended to be placed under the api service definition like so: 
![{144926D2-5A8E-4537-88D6-389911F5CE26}](https://github.com/user-attachments/assets/56862c58-a434-4607-96a4-b0a7c7f3c44c)

Or were they supposed to go the top level like so:
![{0CB6EF12-65AA-4072-AAC5-2E1719A2E963}](https://github.com/user-attachments/assets/d19ff6f2-c11c-4ad3-afc8-eee9dde2abf8)
