### ISSUE TITLE
When filter is used, links are not valid for other users

### ISSUE THREAD

**Issue by andrei-khveras** [reportportal/reportportal#154]
Occurs on RP v. 3.0.2

**Given**
- User1 has created and shared some filter.
- User2 has not marked given filter as favorite 

**When**
User1 activates the filter, navigates to some launch using filter and shares link w/ User2

**Then**
User2 is unable to see the launch by the link provided.

**Comment by ksuglotova** [comment]
In progress

**Comment by DzmitryHumianiuk** [comment]
in 3.1
