### ISSUE TITLE
[v5] Service Analyzer actions are not available due to exception in service-index

### ISSUE THREAD

**Issue by srgynmv** [reportportal/reportportal#1547]
**Describe the bug**
When trying to use ML suggestions or actions with ElasticSearch index, Report Portal says that "Service Anlayzer is not available", but at the same time the service is alive and successfully displayed among the running docker containers. 

A quick investigation led me to the service-index logs showing an error on fetching the traefik services info. I found that a similar issue has already been reported in the service-index repository: https://github.com/reportportal/service-index/issues/14, and the corresponding PR has already been created: https://github.com/reportportal/service-index/pull/15.

Applying the same patch locally resolves the issue and makes Service Analyzer available in the Report Portal UI.

**To Reproduce**
This issue is probably reproducible starting with a specific version of traefik. Our RP instance uses `traefik:v2.2.1` docker image.

1. Make sure that auto-analysis services are running on the system
2. Login to Report Portal
2. Open any project settings
3. Navigate to Auto-Analysis tab
4. Hover "Remove Index" or "Generate Index" buttons
    _Buttons are disabled and their tooltip display "Service Analyzer is not running" message_
5. Open any failed test result and open "Change defect type and comment" view
6. Try to click on "Choose among ML suggestions" or "Apply for: Similar errors"
    _All listed actions are disabled, and hovering over them displays "Service Analyzer is not running" message_

**Expected behavior**
All Service Analyzer actions are available.

**Additional context**
The Report Portal version used is 5.5, and the service-index version is 5.0.10.

**Comment by irynakozak2** [comment]
Hi @srgynmv !
If the issue is still valid for you, my suggestion is to upgrade RP to the latest version and check If the issue would occur.
