### ISSUE TITLE
"Add Project" Button - make visible for tablet view

### ISSUE THREAD

**Issue by Tset-Noitamotua** [reportportal/reportportal#155]
Often I use my browser not maximized over whole display but instead use only half of the screen. On Management Board view the "Add Project" button disappears if browser is too small.

 
![image](https://user-images.githubusercontent.com/5635462/27446361-872497c2-577d-11e7-83b4-9d6ab70c2927.png)

![image](https://user-images.githubusercontent.com/5635462/27446369-90ed4934-577d-11e7-9cbb-d68f76105560.png)

![image](https://user-images.githubusercontent.com/5635462/27446378-99c0612c-577d-11e7-84b6-bf14c84b9fad.png)

**Comment by e-olga** [comment]
Hi @Tset-Noitamotua 
Desktop and mobile versions could be different in enabled options.
'Add Project'  button will be present for desktop version of Report Portal.
For mobile version only view options is available. You are not able to edit, but only view the content.
On the second and the third screens above the Report Portal has mobile screen resolution. Therefore, 'Add project' button is not shown.

**Comment by DzmitryHumianiuk** [comment]
looks like it is a `tablet` view on screens.
@Iren-Melnyk, can we enable this button for tablet view?
will it affect other views, which responsible for project configuration?

**Comment by DzmitryHumianiuk** [comment]
@Tset-Noitamotua availability of `add project` button for tablet view, leads to review of all functionality, which became available with this button under tablet size of window.

for now we will reject this effort, since have more prioritized issues.

but will leave it in backlog

**Comment by DzmitryHumianiuk** [comment]
@Tset-Noitamotua 
Do you really still need this?
or we can close that issue?
