### ISSUE TITLE
[v5] Low performance of /v1/{project_name}/item/v2 API endpoint

### ISSUE THREAD

**Issue by mrbinwin** [reportportal/reportportal#1550]
Hello!
It seems that the current version of service-api runs some heavy SQL queries that takes too much time (2-3 minutes) when user opens launch or test_item pages.

1. UI: http://rp.local/report/ui/#{project_name}/launches/all/{launch_id}
2. UI sends this request to service-api: 
http://rp.local/api/v1/{project_name}/item/v2?filter.level.path=1&page.page=1&page.size=50&page.sort=startTime%2CASC&providerType=launch&launchId={launch_id}
3. TestItemController.getTestItemsV2() runs **TestItemRepositoryCustomImpl.getPathNamesResult()**
that produces this heavy SQL query:
```
select "full_tree"."item_id", "full_tree"."id", "full_tree"."launch_name", "full_tree"."number", "full_tree"."name" 
from 
(
	with recursive "supplytree" as (
		(
			select "public"."test_item"."item_id", "public"."test_item"."parent_id", "public"."test_item"."name" as "leaf_name", "public"."launch"."name" as "launch_name", "public"."launch"."number", ARRAY [CAST("public"."test_item"."name" AS TEXT)] AS names, ARRAY ["public"."test_item"."item_id"] AS ids 
			from "public"."test_item" 
			join "public"."launch" on "public"."test_item"."launch_id" = "public"."launch"."id" 
			where (
				"public"."test_item"."parent_id" is null and "public"."launch"."project_id" = 966 and 
				"public"."test_item"."launch_id" in (688461))
		) 
		union all 
		(
			select "public"."test_item"."item_id", "public"."test_item"."parent_id", "public"."test_item"."name" as "leaf_name", "public"."launch"."name" as "launch_name", "public"."launch"."number", "names" || CAST("public"."test_item"."name" AS TEXT) AS names, "ids" || "public"."test_item"."item_id" AS ids 
			from "public"."test_item" 
			join "public"."launch" on "public"."test_item"."launch_id" = "public"."launch"."id" 
			join "supplytree" on "public"."test_item"."parent_id" = "supplytree"."item_id" 
			where (
				"public"."launch"."project_id" = 966 and 
				"public"."test_item"."launch_id" in (688461)
			)
		)
	) 
	select "supplytree"."item_id", unnest("ids") as "id", "supplytree"."launch_name", "supplytree"."number", unnest("names") as "name" 
	from "supplytree" 
	where "supplytree"."item_id" in (47164277, 47164434, 47165470, 47165621, 47165738, 47165847, 47165897, 47165969, 47166169, 47167000, 47167722, 47167895, 47167944, 47168203, 47168796, 47169195, 47169204, 47169235, 47170287, 47171442, 47171444, 47171494, 47172184, 47173063, 47174574, 47174807, 47186709, 47189983, 47189999, 47196320, 47198778, 47200083, 47201780, 47201920, 47202051, 47202311, 47205488, 47209439, 47209641, 47209659, 47209895, 47209941, 47209943, 47210217, 47212248, 47212273, 47212502, 47212572, 47212687, 47216608) 
	order by "supplytree"."item_id"
) as "full_tree"
```

It takes 4m 38 sec to complete this query and fetch 50 rows from db

It happens when user opens launch page
http://rp.local/api/v1/{project_name}/item/v2?filter.level.path=1&page.page=1&page.size=50&page.sort=startTime%2CASC&providerType=launch&launchId={launch_id}

and also when user opens a test step page 
http://rp.local/report/ui/#{project_name}/launches/all/689483/47540756/47540764/log
it sends to service-api a request 
http://rp.local/api/v1/{project_name}/item/history?historyDepth=12&type=line&filter.eq.id=47540764
that produces the same slow sql query

**Additional context**

service-api version: 5.5.0
server RAM size: 32GB

launch database table: 191MB
test_item database table: 67GB

some pg_settings:
name                      |setting|unit|
--------------------------|-------|----|
maintenance_work_mem      |1048576|kB  |
shared_buffers            |524288 |8kB |
temp_buffers              |1024   |8kB |
wal_buffers               |4096   |8kB |
work_mem                  |98304  |kB  |

**Comment by irynakozak2** [comment]
@mrbinwin hello. It's a known issue and it was fixed in version 5.5.1: related to the performance of the endpoints you listed. Please update to version 5.5.1 and recheck.
