### ISSUE TITLE
[help required] Auto Analysis not working

### ISSUE THREAD

**Issue by vishallanke** [reportportal/reportportal#1552]
When our test cases get failed, it pushes very detailed logs inside the report portal. Now, all the time, the only email id/ unique id different. For example, 
```
Error: Activations for organization cee5dc2e-1808-42a7-8140-xxxxxxx have not been completed within 2 minutes.
 at Context.check (https://platform-alarm.apps.cloud/__cypress/tests?p=cypress/integration/int/Sub/Sub_API_ts:11111:13)
 at Context.eval (https://platform-alarm.apps.horizonint.cloud/__cypress/tests?p=cypress/integration/int/Sub/Sub_API_enf_activate_products_with_add_ons.ts:8729:12)
```

`cee5dc2e-1808-42a7-8140-xxxxxxx` => will get changed every time. Other logs are the same. If I set Auto Analysis to 100% words and all log lines should match, then Auto Analysis will not work.

But, I can not lighten this criterion to let's say 60% of words should match.  

Because....

We also have many scenarios where API returns just an invalid status code inside the error log. For sometimes, 403, 404 etc. So, if I choose light criteria like 60% words should match, then also Auto Analysis will not work. It will show incorrect results.
```
API return 403. Expected 200
```

```
API returns 404. Expected 200
```
We just can not lighten Auto Analysis Criteria for such logs.

**Comment by MariyaIvanina** [comment]
@vishallanke Hi! We have a logic to find potential status codes, so if you'd like to have strict rules for status codes, please add to your logs keywords "status" or  "code", For example, "API return code 403. Expected 200" and RP will extract from this log 403 and 200 as important status codes and they should match for Auto-analysis.
When you change the log, you'd better choose min should match from 90-95% for Auto-analysis to work better and use ML suggestions to train the model specifically for your project (it is available from 5.5 version). We also delete uuids from text not to match by them, the extended logic is delivered in the 5.6 version(which will be available somewhen in the next few weeks), so check it after the release.
