### ISSUE TITLE
Screenshots doesn't attach to report

### ISSUE THREAD

**Issue by sergei820** [reportportal/reportportal#1554]
##**Describe the bug**
Reports successfully create at ReportPortal, but screenshots don't attach to report, using different structures:
    logger.info("RP_MESSAGE#FILE#{}#{}", failScreenshot.getAbsolutePath(), "message");
    logger.info("RP_MESSAGE#FILE#{}#{}", failScreenshot.getPath(), "message");
    logger.info("RP_MESSAGE#FILE#{}#{}", failScreenshot.getCanonicalPath(), "message");
    logger.info("RP_MESSAGE#FILE#{}#{}", "./screenshots/" + result.getMethod().getMethodName() + "_" + failTime + ".png", 
    "message");
    logger.info("RP_MESSAGE#FILE#{}#{}", failScreenshot, "message");
also I tried:
    ReportPortalMessage message1 = new ReportPortalMessage(failScreenshot,"image file");
    logger.info(message1);

##Environment: Java, TestNG, Log4j

##**Expected behavior**
Screenshots successfully attach to report

##**Versions:**
 - OS=Win10, Browser=firefox
 - Version of RP [find it under Login form, copy as is] = Current version:API Service: 5.5.0;Index Service: 5.0.10;Jobs Service: 5.5.0;EPAM Authorizsation Service: 5.5.0;Service UI: 5.5.0
 - 
[logFile.log](https://github.com/reportportal/reportportal/files/7354438/logFile.log);

**Comment by HardNorth** [comment]
That's not actually true, our examples works.
