### ISSUE TITLE
[v5.5.0] After migration from 5.3.3 to 5.5.0 anazlyer/index works incorrectly

### ISSUE THREAD

**Issue by evgenytkachenko** [reportportal/reportportal#1558]
**Describe the bug**
I followed all of the instructions and migrated the db successfully using scripts https://github.com/reportportal/migrations/tree/develop/migrations 

After deploying RP containers (db is running on a separate VM) they are all healthy and do not have exceptions.
The login page does not have a SAML login button and the current versions are not displayed. I see in the network composite/info returns an Internal server error, only
 Panic: runtime error: invalid memory address or nil pointer dereference
[36;1mindex_1             |[0m 2021/10/18 13:22:24 "GET http://reportportal.service.csnzoo.com/composite/info HTTP/1.1" from 172.22.0.13:47300 - 000 0B in 1.995039ms
and 
[36manalyzer_1          |[0m 2021-10-18 13:27:33,564 - analyzerApp.esclient - ERROR - NotFoundError(404, 'index_not_found_exception', 'no such index [175_suggest]', 175_suggest, index_or_alias)

Attaching docker-compose logs:

[myDockerCompose.log](https://github.com/reportportal/reportportal/files/7365478/myDockerCompose.log)

**To Reproduce**
Db (running on a separate machine) for 5.3.3 version migrate to 5.5.0
Install RP 5.5.0 using docker
**Expected behavior**
composite/info should return the versions of containers
**Screenshots**

<img width="1364" alt="Screen Shot 2021-10-18 at 9 23 10 AM" src="https://user-images.githubusercontent.com/7163245/137745501-673644c5-69b1-450f-b333-b76532a126a4.png">

**Desktop (please complete the following information):**
 - OS: Centos
 - Browser Chrome

**Additional context**

**Comment by evgenytkachenko** [comment]
I believe the issue is related to the traefik settings, I have HTTPS redirects in place

**Comment by bldragon101** [comment]
Hi @evgenytkachenko  what changes did you make to the traefik settings? I have had a similar issue with our HTTPS config.
