### ISSUE TITLE
Launches not removed according to policy

### ISSUE THREAD

**Issue by talmoshe24** [reportportal/reportportal#1560]
My RP (currently 5.4.0, was 5.3.5 till 3 months ago) keeps the launches on all projects indefinitely
The setting is default (90 days)

How can I debug this issue?

**Comment by talmoshe24** [comment]
Hi @irynakozak2  any update?

**Comment by irynakozak2** [comment]
@talmoshe24 @Ramandus hi, please specify the next information:
- project retention settings(Project Settings - General), 
- env variables for all jobs in the deployment,
- content of the "shedlock" table in the PostgreSQL database.

Also, a completely new service is responsible for executing Clean Jobs (service-jobs) from v5.4.
Please check the logs of the service-jobs container, if there any errors occur during the cleaning attachments process.

Please note, that the attachments count cleaned for the one job execution is limited to 1000. If it is not suitable for your attachments count, consider increasing this chunk size to a bigger value. Examples can be found here: https://reportportal.io/docs/Report-Portal-jobs

**Comment by Ramandus** [comment]
@irynakozak2  after updating ReportPortal to version 5.5.1 it seems that launches cleanup is working as expected removing old launches according to each project retention rule and as a result the database shrunk from 80+ GB to 40 GB :)
