### ISSUE TITLE
Impossible interact with integration. There are no analyzer services with search logs support deployed.

### ISSUE THREAD

**Issue by nkagri** [reportportal/reportportal#1566]
I have set up ReportPortal in my ubuntu machine and also configured it into my Java+TestNG project, it's working fine. But after executing and investigating failures, found that auto-analysis is not working at my end. Showing this error every time "Impossible interact with integration. There are no analyzer services with search logs support deployed.".

I also checked the elasticsearch configuration via command 'curl -X GET "localhost:9200/"' and here is the results:
{
  "name" : "SVM-SPARTANS-VM2",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "yPdtUcBFQHeGKXYwBoTM-w",
  "version" : {
    "number" : "7.15.1",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "83c34f456ae29d60e94d886e455e6a3409bba9ed",
    "build_date" : "2021-10-07T21:56:19.031608185Z",
    "build_snapshot" : false,
    "lucene_version" : "8.9.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

**Comment by evjlobanova** [comment]
Could you please check documentation https://reportportal.io/docs/Resolve-Analyzer-Known on how to fix problems with analyzer?

**Comment by itaymizsap** [comment]
Hi @nkagri,
Did you figure this out?
We're having the same issue on our Report Portal v5.3.5 docker deployment

@evjlobanova, I went over the guide mentioned above and couldn't find a solution, can you suggest other solutions?

![image](https://user-images.githubusercontent.com/35661672/156535804-3ae63ba2-8caf-4262-9019-9b01c40a74b4.png)
![image](https://user-images.githubusercontent.com/35661672/156536161-8566dabe-6f72-4bcb-ae98-c2c7dcbd7663.png)

**Comment by irynakozak2** [comment]
Hi @nkagri !
If the issue is still valid for you, my suggestion is to upgrade RP to the latest version and check If the issue would occur.
