### ISSUE TITLE
Port value for service-auto-analyzer is hardcoded 

### ISSUE THREAD

**Issue by swadalkar** [reportportal/reportportal#1569]
**Describe the bug**
For service auto-analyzer in DockerFile there is option to use user define port,(https://github.com/reportportal/service-auto-analyzer/blob/5737c8c99a54e5f207d28b207234da1f540ba28b/Dockerfile#L43)
but again in app.py file port value is hardcoded.(https://github.com/reportportal/service-auto-analyzer/blob/5737c8c99a54e5f207d28b207234da1f540ba28b/app.py#L374)
Due to this hardcoded value can't use both ANALYZER TRAIN and  ANALYZER services.
**Expected behavior**
In app.py file value should come dynamically from DockerFile. 

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

**Comment by MariyaIvanina** [comment]
@swadalkar Hi! Why do you need to change the port inside Docker? You can map the port to any you want while running images. For example, you can change in the docker-compose file like this inside "ports" section:
![image](https://user-images.githubusercontent.com/11046087/139661793-e45b93ba-b8a2-4f84-a30f-bb25bddd4393.png)

**Comment by swadalkar** [comment]
Hi @MariyaIvanina , thanks for reaching out.
we have already done that, but in app.py script itself has fix value in that.
[](https://github.com/reportportal/service-auto-analyzer/blob/5737c8c99a54e5f207d28b207234da1f540ba28b/app.py#L374)
app.py should pick dynamic port value .

**Comment by MariyaIvanina** [comment]
@swadalkar Could you please specify what problem did you encounter with this port value and why do you need a dynamic port value?
