### ISSUE TITLE
Config parameter rp.enable = false doesn't work

### ISSUE THREAD

**Issue by ksuglotova** [reportportal/reportportal#157]
Received from @kiryl, Slack/reportportal/russian

If I put rp.enable = false in config then Report Portal doesn't turn off.
Config file reportportal.properies

**Comment by avarabyeu** [comment]
@ksuglotova what agent issue is related to? cucumber? version of agent?

**Comment by ksuglotova** [comment]
@avarabyeu The agent is Cucumber the latest version for the last Thursday

**Comment by kovaku** [comment]
@avarabyeu I have the same issue with agent-java-cucumber (3.0.0-BETA-1)
