### ISSUE TITLE
minimal installation

### ISSUE THREAD

**Issue by unmurphy** [reportportal/reportportal#1577]
Hi! Can I install reportportal with minimal installation? Such as without rabbitmq, elasticsearch, minio. I just need service-api

**Comment by evjlobanova** [comment]
All services are needed for the build-in ReportPortal functionality.
We can not guarantee the functionality of ReportPortal without them or in another configuration.

Service description
service-authorization Authorization Service. In charge of access tokens distribution
service-api API Service. Application Backend
service-ui UI Service. Application Frontend
service-index Index Service. Info and health checks per service.
service-analyzer Analyzer Service. Finds most relevant test fail problem.
gateway Traefik Gateway Service. Main entry point to application. Port used by gateway should be opened and accessible from outside network.
rabbitmq Load balancer for client requests. Bus for messages between servers.
minio Attachments storage.
