### ISSUE TITLE
[v5] No logs being posted for scenarios that fail when using RemoteWebDriver

### ISSUE THREAD

**Issue by ashishkaran** [reportportal/reportportal#1579]
**Describe the bug**
I'm running TestNG test cases using Selenoid for the remote browser instances.
When I run a test case that fails using a local webdriver instance, the logs and attachments are published in Report Portal, but when I run a scenario that fails in a remote webdriver instance, I don't get any logs or attachments and the test case is marked as **interrupted**.

Log4j2.xml
```<?xml version="1.0" encoding="UTF-8"?>
<Configuration packages="com.epam.ta.reportportal.log4j.appender" status="WARN">
    <Appenders>
        <Console name="ConsoleAppender" target="SYSTEM_OUT">
            <PatternLayout
                    pattern="%-5p [%M] %m %n"/>
        </Console>
        <ReportPortalLog4j2Appender name="ReportPortalAppender">
            <PatternLayout
                    pattern="%-5p [%M] - %msg%n%throwable"/>
        </ReportPortalLog4j2Appender>
    </Appenders>
    <Loggers>
        <Root level="INFO">
            <AppenderRef ref="ConsoleAppender"/>
            <AppenderRef ref="ReportPortalAppender"/>
        </Root>
        <Logger name="com.epam.reportportal.service" level="WARN" additivity="false">
            <AppenderRef ref="ConsoleAppender"/>
            <AppenderRef ref="ReportPortalAppender"/>
        </Logger>
        <Logger name="com.epam.reportportal.utils" level="WARN" additivity="false">
            <AppenderRef ref="ConsoleAppender"/>
            <AppenderRef ref="ReportPortalAppender"/>
        </Logger>
    </Loggers>
</Configuration>
```
**To Reproduce**
Run a TestNG case that logs a few log lines and uploads an attachment and fails using a remote webdriver.

**Expected behavior**
Even for failed test cases the logs and attachments should be published to Report Portal

**Desktop:**
 - OS: Linux 20.04 (report portal docker machine), Windows 10(Java test cases execution machine)
 - Browser: chrome
 - Version: 95 (similar issue with prior versions as well)

**Additional context**
I've tried Remote Webdrivers both using Selenium Grid as well as Selenoid.

**Comment by evjlobanova** [comment]
@HardNorth Could you please check

**Comment by MaryiaRymarchyk** [comment]
Hi @ashishkaran , sorry for the silence.
Could you please check with the latest version of RP and let us know if the issue still relevant or not.
