### ISSUE TITLE
Any tutorial for the reportportal upgrade?

### ISSUE THREAD

**Issue by troyhugs** [reportportal/reportportal#1580]
I am using the RP version 5.3.5.
Can you help me out to upgrade to the latest 5.5, without any launches data?
At-least- the I need the dashboards which are created to present in the database.

**Comment by evjlobanova** [comment]
Please use a tutorial https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.5.5
In case of problems please use the troubleshooting guide https://reportportal.io/docs/How-to-resolve
