### ISSUE TITLE
Screenshots within "Capture page Screenshot" steps displayed as broken

### ISSUE THREAD

**Issue by hossameldinmohamed** [reportportal/reportportal#1584]
**Describe the bug**
Attached screenshots are not displayed correctly as they 're displayed as broken images and when we click on it it goes to 404 page - not found .

**To Reproduce**
Run Tests using RobotFramework and connect it to reportportal 
 
**Expected behavior**
Screenshots should be displayed in steps with no issue 

**Screenshots**
![image](https://user-images.githubusercontent.com/11408969/141965017-2d53cdd1-79d2-4c0a-8ac7-3f4ef79c7d38.png)

**Additional context**
Hint : we 're upgrading from reportPortal version 3 to the new one & the screenshots was displayed successfully within the capture screenshot normally .

Below 're the libraries versions which we use , i have tried to install different version of each one of them to check if  it's versions compatibility issue or not but didn't work either  :

reportportal-client==5.0.12
robotframework==4.1.2
robotframework-databaselibrary==1.2.4
robotframework-dependencylibrary==3.0.1
robotframework-excellib==2.0.1
robotframework-pythonlibcore==3.0.0
robotframework-reportportal==5.2.1
robotframework-requests==0.9.2
robotframework-seleniumlibrary==5.1.3
selenium==4.0.0

**Comment by HardNorth** [comment]
`Capture Page Screenshot` is designed to embed the screenshot into Robot Report only. There is no way to make it work with RP. To log screenshot in Robot there is a workaround in our examples: https://github.com/reportportal/examples-python/blob/master/robotframework/robot/screenshot.robot

**Comment by hossameldinmohamed** [comment]
@HardNorth  But this worked with the old version of report Portal and the screenshot got attached t attachments tab 
![image](https://user-images.githubusercontent.com/11408969/141975167-4c62cbfb-f6a5-444e-9501-32a495dff776.png)

**Comment by HardNorth** [comment]
On which agent/robot version it worked?

**Comment by hossameldinmohamed** [comment]
it worked on report portal 3  - robotframework-reportportal==3.0.0 

Also note that selenium.Capture page Screenshot () function is triggered automatically when the test case is failed in RobotFramework So i didn't write any code for it or anything so the workaround is not relevant in this case.

**Comment by HardNorth** [comment]
@hossameldinmohamed Which version of robotframework-seleniumlibrary did you use?

**Comment by hossameldinmohamed** [comment]
@HardNorth  robotframework-seleniumlibrary==5.1.3

And below 're the list of libraries i use : 

reportportal-client==5.0.12
robotframework==4.1.2
robotframework-databaselibrary==1.2.4
robotframework-dependencylibrary==3.0.1
robotframework-excellib==2.0.1
robotframework-pythonlibcore==3.0.0
robotframework-reportportal==5.2.1
robotframework-requests==0.9.2
robotframework-seleniumlibrary==5.1.3
selenium==4.0.0

**Comment by HardNorth** [comment]
@hossameldinmohamed I asked about previously used libraries.

**Comment by hossameldinmohamed** [comment]
@HardNorth  my bad 

Her you 're : 
robotframework==3.2.2
robotframework-csvlibrary-py3==1.0.2
robotframework-databaselibrary==1.2.4
robotframework-datadriver==1.0.0
robotframework-dependencylibrary==1.0.0.post1
robotframework-excel==1.0.0b4
robotframework-excellib==2.0.1
robotframework-faker==5.0.0
robotframework-jsonlibrary==0.3.1
robotframework-jsonvalidator==2.0.0
robotframework-pythonlibcore==2.2.1
robotframework-reportportal==3.0.0
robotframework-reportportal-ng==1.0.4.9
robotframework-requests==0.7.0
robotframework-seleniumlibrary==4.5.0

**Comment by HardNorth** [comment]
@hossameldinmohamed Used your old dependencies, still got broken screenshot. Everything as I said: "`Capture Page Screenshot` is designed to embed the screenshot into Robot Report only".

You might modified your library to log images directly, in this case it will appear on RP correctly.

OK, spent 3 hours on that, so not going to continue discussion anymore.

**Comment by hossameldinmohamed** [comment]
@HardNorth Thanks a lot for your great support really appreciate it.
