### ISSUE TITLE
Curl request connection timed out

### ISSUE THREAD

**Issue by hadizia** [reportportal/reportportal#1587]
**Describe the bug**

So in one of our jenkins pipelines, we have a step which uploads junit results to our report portal instance via curl commands. The issue is that this process is very flaky. Sometimes all test results get uploaded normally whereas sometimes certain curl requests get timed out regardless of how many times you retry the curl command. I've used several ways to keep retrying the curl command but nothing works.

**Expected behavior**
All curl requests should complete successfully. The retry mechanism will ensure no two curl commands are being sent at the same time (which could cause a timeout). 

**Screenshots**
The screenshot below shows one instance of uploading testcase results that times out. There are cases where even creating a test suite times out(not shown in screenshot but has the same timeout error)
![s](https://user-images.githubusercontent.com/46935151/142653444-f90672c1-c5e9-49b1-bb94-37846ecac397.png)

**Versions:**
 - OS, Browser
 The reportPortal instace is deployed on an ubuntu image. We access it through a linux machine with firefox. The pipeline sends curls requests on a jenkins agent
 
 - Version of RP [find it under Login form, copy as is]
 Current version:API Service: 5.3.5;Index Service: 5.0.10;Authorization Service: 5.3.5;Service UI: 5.3.5;

**Comment by Oleksii-kh89** [comment]
Hi @hadizia 
Please, update RP to the latest released version paying attention to the optimal performance hardware setup on https://reportportal.io/docs/Optimal-Performance-Hardware . If the issue occurs after you update RP to the latest released version share your API logs, please.
