### ISSUE TITLE
Test fails, RP shows it's runnung

### ISSUE THREAD

**Issue by ksuglotova** [reportportal/reportportal#159]
Received from @kiryl, Slack/reportportal/russian

If test fails (cucumber), then RP shows that test is running and user has to force finish test
Last agent version

**Comment by avarabyeu** [comment]
@ksuglotova agent, version, example?

**Comment by Gidroid** [comment]
agent -java -cucumber, version 3.0.0-BETA-2
For example need help with gradle

**Comment by avarabyeu** [comment]
@Gidroid  feel free to create the same example based on maven. You can even send it to me via email

**Comment by DzmitryHumianiuk** [comment]
@Gidroid ?

**Comment by Gidroid** [comment]
Right now I can't reproduce this error on our project. I will add code when error come up again

**Comment by avarabyeu** [comment]
@Gidroid OK. closing for now. Feel free to re-open or create new issue if problem appears again
