### ISSUE TITLE
[v5]Docker compose failing on mac M1

### ISSUE THREAD

**Issue by sylvain-viole** [reportportal/reportportal#1590]
**Describe the bug**
Containers `report_portal_uat1` and `report_portal_api1` keep restarting

**To Reproduce**
- `curl https://raw.githubusercontent.com/reportportal/reportportal/master/docker-compose.yml -o docker-compose.yml`
- `docker-compose up -d`

**Expected behavior**
- Stable docker configuration
- Report Portal UI accessible

**Screenshots**
![image](https://user-images.githubusercontent.com/71819292/142929340-1e46bf2f-0368-45c4-9049-1577e89d4d93.png)
![image](https://user-images.githubusercontent.com/71819292/142929582-5136c13a-1010-4a06-9402-29362216f23f.png)

**Desktop (please complete the following information):**
 - Mac os `12.0.1`
![image](https://user-images.githubusercontent.com/71819292/142929710-19ff81b7-ef48-42d1-9284-f7b6a62a78a4.png)
- CHROME Version `96.0.4664.45` (Build officiel) (arm64)
- report Portal : `5.6.0`

**Additional context**
Error message on both restarting containers :
`start.sh: applet not found`

**Comment by Cyberglamdring** [comment]
Hello @sylvain-viole, can you provide the full API and UAT log as files?

**Comment by lohanimohit** [comment]
@sylvain-viole, even I am getting the same issues. Did you reloved it ?

@Cyberglamdring, how can we get the logs, as its startup is failing
Log Below:-
start.sh: applet not found

For me it's happening on the m1 chip

**Comment by lohanimohit** [comment]
Reportportal UAT logs :
start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found

start.sh: applet not found/



Same logs are for reportportal_api and reportportal_jobs

**Comment by evjlobanova** [comment]
@Cyberglamdring

**Comment by DzmitryHumianiuk** [comment]
please follow up M1/ARM related discussion in https://github.com/reportportal/reportportal/issues/1815
