### ISSUE TITLE
[v5] Assertion Failure Marked Under <> is missing in markdown view but displayed in console view

### ISSUE THREAD

**Issue by ReddyNitheeesh** [reportportal/reportportal#1591]
**Describe the bug**
Java 8 + Junit 5 + Report porta 5.5

**To Reproduce**

**Expected behavior**
Expected and Actual which are wrapped under less than (<) and greater than (>) are replaced with empty text in markdown view, working fine in console view

Markdown view
![Empty](https://user-images.githubusercontent.com/28997011/143005141-3860ce65-2910-4805-83db-3ee16d619c08.PNG)

Console view :
![Consoleview](https://user-images.githubusercontent.com/28997011/143005202-bcd113e2-fd92-4e6c-a017-e17c6c482e61.PNG)

**Comment by HardNorth** [comment]
Duplicates: https://github.com/reportportal/reportportal/issues/1280
