### ISSUE TITLE
[v5] Filter Test Cases by attribute key or value

### ISSUE THREAD

**Issue by gpapadakis** [reportportal/reportportal#1592]
**Describe the solution you'd like**
It would be great to create filters per launch that can aggregate the test cases by attribute key or value. 

**Is your feature request related to a problem? Please describe.**
This particular request will help us create dashboards per launch based on a particular set of test cases when different categories are running in the same launch.

**Comment by evjlobanova** [comment]
This feature already exists in the widgets Component Health Check Widget and Component Health Check Widget (table view)
https://youtu.be/T98iy0mJk0s

https://reportportal.io/docs/Component-health-check
https://reportportal.io/docs/Table-Component-health

In the version 6 we will add a custom dashboards based on the custom queries
