### ISSUE TITLE
Add support async/non-blocking sending data to RP instead of batch

### ISSUE THREAD

**Issue by admizh** [reportportal/reportportal#16]
Root cause of this. sending events with batch - provide increasing tests execution time.
Currently data sending performed after collecting 10 events (rp.batch.size.logs). When sending data to RP the tests are blocked. This is appreciable at poor internet speed. My proposal to use non-blocking client.
1. Using event queue/msg bus + async http client
2. Add more logs when events send started/finished
3. Add warning if data transfering takes long time (configurable via properties)

**Comment by avarabyeu** [comment]
Good idea! We have already started initial research on that. Now there is http client based on Apache HttpAsync which connected with Reactor (projectreactor.io). So, all interaction with ReportPortal server is based on callbacks plus we have ability to add backpressure logic. We need some time to test it and implement all needed REST API methods so can not really give you any estimates on releasing that to public access.

**Comment by abotalov** [comment]
We've done it in Ruby agent using a worker thread and a queue. A worker thread just takes events to-be-processed from the queue.
https://github.com/reportportal/agent-ruby/blob/master/lib/reportportal/cucumber/formatter.rb

**Comment by avarabyeu** [comment]
fixed
