### ISSUE TITLE
Reportingportal.io loading issue with V5

### ISSUE THREAD

**Issue by srinivas2501** [reportportal/reportportal#1602]
Hi All,

I have successfully installed the report portal v5 on my Mac Laptop (Big Sur ,Version 11.0.1) and followed the installation steps using Docker and able to configure the reportingportal.io successfully . But When I am running first time after installation  it is showing as “Loading.. “ . I am unable to sign in or Login screen is not loading .I have tested this issue in other my team mates mac machine . Issue still persists

I have verified in the developer tools console logs, error is shown as follows

main.app.09cf54.js:364 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at main.app.09cf54.js:6
    at c (main.app.09cf54.js:8)
    at Generator._invoke (main.app.09cf54.js:8)
    at Generator.S.forEach.e.<computed> [as next] (main.app.09cf54.js:8)
    at D (main.app.09cf54.js:60)
    at y (main.app.09cf54.js:60)
    at main.app.09cf54.js:60
    at i (main.app.09cf54.js:20)
    at c (main.app.09cf54.js:20)

Could you please help me in resolving the issue

Thanks and much appreciated your support
<img width="505" alt="Screenshot 2021-12-03 at 10 02 06 AM" src="https://user-images.githubusercontent.com/16115589/144537981-088ddb61-6cc6-40b5-897f-36b0021c965c.png">

**Comment by lohanimohit** [comment]
Even I am getting the same issue.

**Comment by axxyhtrx** [comment]
same

**Comment by SHI-ZP** [comment]
Same

**Comment by omarsawara** [comment]
same

**Comment by avaparna-max** [comment]
i am also getting same issue, what is the solution for it
<img width="1440" alt="Screenshot 2022-06-13 at 8 55 40 AM" src="https://user-images.githubusercontent.com/81403537/173274029-0a1994eb-fe59-4024-b6aa-33d380e5be63.png">
?

**Comment by mparkhomenko** [comment]
same

**Comment by Jmainguy** [comment]
@avarabyeu @DzmitryHumianiuk yall have any ideas? or know who would? I just got done finishing installing on k8s using the helm chart, and seeing the same behavior, nothing in the logs indicates much.

The API pod for me is throwing a minio error, I am not sure if it matters or not.

```
2022-08-02 18:17:53.947  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8585 (http) with context path ''
2022-08-02 18:17:53.949  INFO 1 --- [           main] c.e.t.r.core.configs.ReportPortalApp     : Started ReportPortalApp in 42.097 seconds (JVM running for 43.486)
2022-08-02 18:17:54.140 ERROR 1 --- [           main] c.e.t.r.f.d.minio.MinioDataStore         : Unable to find file 'keystore/migration'

io.minio.errors.ErrorResponseException: The specified key does not exist.
```

**Comment by DzmitryHumianiuk** [comment]
@Jmainguy @mparkhomenko @avaparna-max @omarsawara @SHI-ZP @axxyhtrx @lohanimohit @srinivas2501 guys, are you all on Mac with M1?

**Comment by axxyhtrx** [comment]
> @Jmainguy @mparkhomenko @avaparna-max @omarsawara @SHI-ZP @axxyhtrx @lohanimohit @srinivas2501 guys, are you all on Mac with M1?

Hi, yes my client is M1. But this is a server side issue. I fixed it by increasing resource limits for containers (for jvm and something etc).

**Comment by DzmitryHumianiuk** [comment]
**RESOLUTION:**
increase available RAM for docker.

**Comment by mdandreanextech** [comment]
How much do we need to up the RAM by @DzmitryHumianiuk?

**Comment by DzmitryHumianiuk** [comment]
@mdandreanextech https://reportportal.io/docs/installation-steps/HardwareRequirements

**Comment by mdandreanextech** [comment]
@DzmitryHumianiuk  Thanks and maybe I'm just missing it, but does this talk about the memory limits for each reportingportal container?

**Comment by DzmitryHumianiuk** [comment]
@mdandreanextech 
https://github.com/reportportal/kubernetes/blob/master/reportportal/values.yaml#L17
and search for `memory:` thru entire file.

**Comment by mdandreanextech** [comment]
Thanks @DzmitryHumianiuk!  That's what we're trying to figure out right now.  We are getting the JavaScript error above.  Do we need to bump up the "memory:" entries to something higher to avoid those errors?

**Comment by DzmitryHumianiuk** [comment]
@mdandreanextech API, rabbit and database needs the most attention.
every setup is different and depends on the load.
so just try to bump up the numbers and see how it helps.
