### ISSUE TITLE
[v5] Cancel edit common attributes button is not working

### ISSUE THREAD

**Issue by Shakevg** [reportportal/reportportal#1603]
**Describe the bug**
Cancel edit common attributes button is not working

**To Reproduce**

1. Open launch
2. Select several tests (all tests should have common attribute)
3. Select edit "Edit items" in the menu
4. Click on any common attribute
5. Click the Cancel button for this attribute

**Expected behavior**
Edit mode for attribute should be closed

**Screenshots**
![image](https://user-images.githubusercontent.com/42133199/144994103-0d1748d7-4653-471a-a86a-fc4c9a4d9789.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 96.0.4664.45

**Additional context**
Script error in console (see on the screen above)

**Comment by evjlobanova** [comment]
@VolhaKarenko Olya, could you please a bug to the next sprint?

**Comment by YerassylNurzhan** [comment]
Fixed in version 5.7
