### ISSUE TITLE
Error migrating Database from 5.3 to 5.4

### ISSUE THREAD

**Issue by babantax** [reportportal/reportportal#1605]
We are trying to upgrade Report Portal from version 5.3 to 5.4 in K8s. The database is hosted in AWS (Aurora PostgreSQL)

While deploying, we are getting the following error:

`Error: UPGRADE FAILED: pre-upgrade hooks failed: job failed: BackoffLimitExceeded`

And If we check the logs of the migrations pod we get the folowing:

`$ kubectl logs report-portal-stg-reportportal-migrations-6x5s9
wait-for-it.sh: waiting 15 seconds for report-portal-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.amazonaws.com:5432
wait-for-it.sh: report-portal-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.amazonaws.com:5432 is available after 0 seconds
error: Dirty database version 39. Fix and force version.`

![image](https://user-images.githubusercontent.com/52815118/145549126-081315c7-0ba3-42d1-a98b-89bc17ab0751.png)

Can anyone help me to understand what can be happening and how could I fix this?

Thanks a lot in advance

**Comment by mlarrea** [comment]
Migration fails throwing this error:
![image](https://user-images.githubusercontent.com/24795563/145777720-87e45951-c095-4b40-8a96-3da5d9008069.png)

**Comment by evjlobanova** [comment]
https://reportportal.io/docs/How-to-resolve
Could you please try to follow the steps described in the article

**Comment by babantax** [comment]
Good morning!
But we are getting the same result. Any idea on what can be happening?

**Comment by mlarrea** [comment]
The problem was we were using an Aurora serverless instance for the DB and the latest PostgreSQL available version was 10, this version does not allow PROCEDURES so it was failing. I think you can considet this issue as resolved. Thanks Yauheniya
