### ISSUE TITLE
Is it possible to add a commit hash to the UI?

### ISSUE THREAD

**Issue by patsevanton** [reportportal/reportportal#1610]
Hello!
Thanks for Reportportal.
Is it possible to add a commit hash to the UI?
Thanks!

For example
Run autotest in git hash commit 1
Run autotest in git hash commit 2
Run autotest in git hash commit 3
Run autotest in git hash commit 4

![image](https://user-images.githubusercontent.com/10828883/146036637-3c0f46ee-df8f-441a-9285-c5b946153167.png)

**Comment by evjlobanova** [comment]
Hello @patsevanton 
Thank you for your request.
Could you please provide more details on your request: 
* what is the business need for the request? 
* What problem are you trying to resolve?
* how do you plan to utilize commit hash in your test activities?

**Comment by patsevanton** [comment]
Ok. I will use attribute. Thanks!
