### ISSUE TITLE
JIRA syncronization with different issue types.

### ISSUE THREAD

**Issue by mva730** [reportportal/reportportal#162]
As RP user I want to post bugs to JIRA with different issue types. But field with issue type selection is not editable.
![image](https://user-images.githubusercontent.com/17176601/27785634-e9cbeea4-5fe6-11e7-984c-46f41d190c68.png)

**Comment by ksuglotova** [comment]
This request is similar to [#66](https://github.com/reportportal/reportportal/issues/66)

**Comment by ksuglotova** [comment]
@mva730  I suggest you to track the progress at https://github.com/reportportal/reportportal/issues/66
This issue will be closed as duplicate
