### ISSUE TITLE
Finer control over how test_names and launch_names appear in RP history window

### ISSUE THREAD

**Issue by NeuroDuck** [reportportal/reportportal#1621]
I understand the following likely involves changes in both pytest-reportportal and in ReportPortal itself, so I'm starting this discussion here and in RP's general Slack channel...

<img width="730" alt="Can the test run modify these fields1" src="https://user-images.githubusercontent.com/11916373/81447672-ed5de480-9131-11ea-94ed-356db7ac8ccc.png">
<img width="710" alt="Can the test run modify these fields2" src="https://user-images.githubusercontent.com/11916373/81447700-fcdd2d80-9131-11ea-8a28-27456e9f8466.png">

Referring to the images above, do any of the existing pytest.ini settings allow us to have a "flat" hierarchy in RP, *and* have only the test_name shown under "NAME" in the history, so no clicking is needed to burrow down through RP's test_results hierarchy to finally see a particular test's results?

I.e., in the Green-circle, could we see only the test_name, i.e.:
`test_color_index`?

If not, would it be easier to (i.e., for me to send you a PR that) adds a new pytest.ini rp_hierarchy_* setting that does this, 
or:
changes an existing rp_hierarchy_* setting, 
    so that we can specify one of several %variables% 
    as that setting's value, to avoid having to create many 
    new rp_hierarchy_* settings for all the possibilities?

Likewise, for the Blue-circle, assuming a RP change is made to make the text that's displayed for "EXECUTION reportportal/agent-python-pytest#5" changeable, what is the best approach on the pytest-reportportal plugin side, to support sending this info to ReportPortal?

I.e., instead of "EXECUTION reportportal/agent-python-pytest#4, 5, 6", I'd like to send our build# that each Launch is testing.

Our build# never changes during a particular launch, so that hopefully simplifies things.

Please let me know how to most succinctly organize this discussion.  
Thanks much.

**Comment by MaryiaRymarchyk** [comment]
Hi @NeuroDuck , this feature is already in live.  There is only the test_name is displayed in the column NAME on history tab.
