### ISSUE TITLE
Auto analysis for existing marked issues is not working after migrating from 5.3.5 to 5.6.2

### ISSUE THREAD

**Issue by sse2ebdd** [reportportal/reportportal#1629]
We have followed migration instructions from https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.5.6. Once the docker containers are recreated, we executed one sample test which was suppose to be auto analyzed but it's still remaining in To Investigate state.
We also generated the index before executing the run.
Can you please help me understand what could be the issue.

**Comment by sse2ebdd** [comment]
@evjlobanova @DzmitryHumianiuk Hi Team can you please help me resolve the above issue.

**Comment by DzmitryHumianiuk** [comment]
@sse2ebdd please go to setting -> Auto Analysis and click `Generate index` at the bottom of the page.
Before that, please make sure your `service-analyzer` and `elastic` are up and running

**Comment by evjlobanova** [comment]
@sse2ebdd Does Index generation help?

**Comment by sse2ebdd** [comment]
Hi @DzmitryHumianiuk @evjlobanova,
We tried using generate index and then auto analysis worked as expected.
Thanks for your help.
