### ISSUE TITLE
[v5] Test automatically mark as fail when it's passed and vice versa

### ISSUE THREAD

**Issue by baovu2512** [reportportal/reportportal#1637]
**Describe the bug**
Test automatically mark as fail when it's passed and vice versa 

**Expected behavior**

**Screenshots**
![Screen Shot 2022-01-18 at 17 17 47](https://user-images.githubusercontent.com/46682545/149918196-6f98324e-ab74-4938-9a19-871ef6337ee9.png)

**Additional context**
Hi team, I'm using Report Portal version like below screenshot:
![Screen Shot 2022-01-18 at 17 19 40](https://user-images.githubusercontent.com/46682545/149918357-9e3ea0e7-abf8-4a1a-a727-453d0eeaea8e.png)

After enable callback for adding attribute to test item, some test automatically as fail even if it's passed or vice versa.
I have added test result from TestNG as Attribute and seem fine: 
![Screen Shot 2022-01-18 at 17 22 40](https://user-images.githubusercontent.com/46682545/149918918-fe63bb14-5ece-4ec5-b11f-21882ea22549.png)

Any ideas ?

**Comment by evjlobanova** [comment]
Can you please share a request, that you've sent on item update?

**Comment by baovu2512** [comment]
![Screen Shot 2022-01-25 at 15 22 19](https://user-images.githubusercontent.com/46682545/150938958-02e65812-f590-4f27-be69-114fd286bb2d.png)
Hi @evjlobanova , is this the one you needed?.

**Comment by evjlobanova** [comment]
Which agent and client do you use ? Could you please send me a link to your agent?

**Comment by HardNorth** [comment]
@evjlobanova It's TestNG. But I very doubt that we can do anything here. It's custom code, so the issue might be in custom logic. Unless someone points me on the pure agent code misbehavior I consider that as not our issue.
