### ISSUE TITLE
[v5] Choose among ML suggestions dropdown percent values format (54.000004%)

### ISSUE THREAD

**Issue by shatulsky** [reportportal/reportportal#1638]
**Steps**
Click Make Decision
Open Choose among ML suggestions dropdown
The percent value is 54.000004
 
**Expected behavior**
Percent values are int

**Screenshots**
![image](https://user-images.githubusercontent.com/22248285/149937069-7d0ec9f2-945d-4b17-8081-38225244801a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 97.0.4692.71 

**Additional context**

**Comment by evjlobanova** [comment]
Release 5.7 are planning on Feb 2022
