### ISSUE TITLE
Missing data after pulling 5.6 image and starting 

### ISSUE THREAD

**Issue by linexlee** [reportportal/reportportal#1639]
Had some issues with version 5.5 and decided to pull down the latest docker-compose.  After doing so and starting 5.6 up unable to login with project users and was only able to login with default Admin account (superadmin).  Anyone know how I can point back to my old data? Or what might have happened to my data?

**Comment by Oleksii-kh89** [comment]
Hi @linexlee 
Could you please describe the process how did you migrate from version 5.5 to 5.6? Did you use our migration guide https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.5.6 during upgrading?
