### ISSUE TITLE
Usage of elasticsearch in report portal - Question

### ISSUE THREAD

**Issue by sreesankargm** [reportportal/reportportal#1641]
I'm very new to report portal and my team is evaluating the usage in our product (internal). It is a long term project, so I just wanted to get some things clear about the usage of elastic search.

1. There are some licensing changes that happened on elastic search when they moved to a dual licensing strategy. This even prompted AWS to fork its own version and introduced OpenSearch. Does this impact Report Portal in any way? I have this question because it looks like ES is bundled with Report Portal.
2. Is there a usage of Kibana anywhere in Report portal? I'm guessing the chart displays are separate UI components but I wanted to get this confirmed.

**Comment by evjlobanova** [comment]
Hello
1. ReportPortal is a free open-source tool, so for now there are no changes in ES usage for us. 
2. Could you please elaborate on your question? Dashboards and widgets are built-in functionality in RP, so you can use it without using any other tools or services.

**Comment by sreesankargm** [comment]
Thank you for the response @evjlobanova !

For the second part, I just wanted to know if you're using the Kibana component from ELK to display the charts and all on dashboard. If you just use the 'Elasticsearch' component for any of the features in report portal, that answer would be no - I just wanted to verify that.

**Comment by evjlobanova** [comment]
Here you can find a playlist with video which describe how we are using ES https://www.youtube.com/playlist?list=PL3antCyL8vgqSXNvbFJxa_YKNq9eDxWsQ

**Comment by HardNorth** [comment]
@sreesankargm no, we don't use Kibana in any way.

**Comment by sreesankargm** [comment]
All good. Thanks for the responses @HardNorth  & @evjlobanova ! I got what I needed to go forward.
