### ISSUE TITLE
Migration 4.3 -> 5.0 fails

### ISSUE THREAD

**Issue by krzysztof-kois-rft** [reportportal/reportportal#1645]
Hi guys. I'm tried to migrate RP4.3 ->5.0 and stuck in 2.2 - [migrate settings
](https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.5#2-data-migration-from-v4-to-v5)
My setup is:
- Standalone MongoDB
- PostgreSQL 12.6 as RDS
- ReportPortal 4.3 (some images in 4.2 as in [official release](https://github.com/reportportal/reportportal/blob/4.3/docker-compose.yml))
- from [reportportal 5.0](https://github.com/reportportal/reportportal/blob/5.0.0/docker-compose.yml): minio and  migrations:5.0.0
- from [migration procedure](https://github.com/reportportal/data-migration/blob/settings-migration/docker-compose.yml): settings-migration:latest

I checked Mongo, MinIO and Postgres access. It seems that migration container prepare postgres database by create schemas, but I still get error inside migration container.
```
ERROR org.springframework.batch.core.step.AbstractStep.execute - Encountered an error executing step user in job settingsMigrationJob
org.springframework.batch.item.ItemStreamException: Could not move to stored position on restart
        at org.springframework.batch.item.support.AbstractItemCountingItemStreamItemReader.open(AbstractItemCountingItemStreamItemReader.java:170)
...
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.util.NoSuchElementException: null
        at java.base/java.util.ArrayList$Itr.next(Unknown Source)
```
Do anybody facing that error and can tell me what is wrong?

**Comment by pbortnik** [comment]
Hello @krzysztof-kois-rft ,
Actually it is not a root problem. It is problem of restart. So, you ran migration and it was failed. You ran it again and got this error. 
To find out the root cause, please, deploy postgres from the scratch and run migration again.

**Comment by krzysztof-kois-rft** [comment]
Thanks for explain what error means and how to proceed.
