### ISSUE TITLE
Blank page when opening Report Portal after V5 upgrade

### ISSUE THREAD

**Issue by DavidsUrbantz** [reportportal/reportportal#1646]
Overview:
Navigating to the Report Portal site more than once from a browser results in a blank screen. The console shows blocked resource errors. The issue occurred for some users after we upgraded Report Portal to V5.
Details:
Opening Report Portal for the first time from any browser results in the expected behavior. However navigating away/closing the browser and then reopening it the user is landed on a blank page. This issue treats any incognito mode as a separate browser, so on each browser Report Portal can only be accessed twice.
Cleaning everything from the browsers or reinstalling them doesn't solve the problem.

Console errors:
"Failed to find a valid digest in the 'integrity' attribute for resource '<address>/ui/main.app.3c10c4.js' with computed SHA-384 integrity '<hash code>'. The resource has been blocked."

"Failed to find a valid digest in the 'integrity' attribute for resource '<address>/ui/main.3c10c4.css' with computed SHA-384 integrity '<hash code>'. The resource has been blocked."

"Failed to find a valid digest in the 'integrity' attribute for resource '<address>/ui/main.app.3c10c4.js' with computed SHA-384 integrity '<hash code>'. The resource has been blocked."

Note: First and last error is the same, but the hash is different.

Steps to reproduce:
1. Navigate to Report Portal in any browser either on normal or incognito mode.
2. Close the page.
3. Navigate to Report Portal again.

Expected behavior:
The user is landed on the login page.

System info:
 - OS: Windows 10
 - Browser: Opera V82, Chrome V97, Edge V97, Firefox V96

Report Portal info:
- Version: 5.6.0

**Comment by irynakozak2** [comment]
Hi @DavidsUrbantz ! 
Please update RP to the latest released version and check if the issue still occurs.
