### ISSUE TITLE
Launches merging with results updating

### ISSUE THREAD

**Issue by mva730** [reportportal/reportportal#165]
E.x.: we have failed launch. We collect all failures and run them again. After finishing we merge these results to our first launch.

**Comment by ksuglotova** [comment]
[https://github.com/reportportal/reportportal/issues/13](re-run feature)

**Comment by avarabyeu** [comment]
in we close it in favor of reportportal/reportportal#13

**Comment by ksuglotova** [comment]
I think we can. ) Moved comment to https://github.com/reportportal/reportportal/issues/13
@mva730 Please track the progress on https://github.com/reportportal/reportportal/issues/13

**Comment by ksuglotova** [comment]
Closed as duplicate
