### ISSUE TITLE
Getting Bad request while login to report portal 

### ISSUE THREAD

**Issue by MJMayur02** [reportportal/reportportal#1655]
Hello Team we are getting bad request while login to report portal have restart all servies as well
![reportportal](https://user-images.githubusercontent.com/98796920/151915912-28199992-efb3-4c46-b29c-da1702b63459.png)

**Comment by VinGt22** [comment]
Any update on this? It seems with the latest release something is broken. This is causing lot of delays in the automation. Can we get an update if some developer is working to fix this?

**Comment by gregorygold** [comment]
We have just run into the same issue and would like to get a solution soon.

**Comment by gregorygold** [comment]
Please help, i have tried the older version of the application, but still facing the same 502, Bad Gateway error on login.

**Comment by Cyberglamdring** [comment]
Hello,

1. What type of installation are you using? Docker/Kubernetes/From source?
2. Describe the status of the services. We need to make sure all services are up and running.
3. Attach API, UAT, and Gateway logs

**Comment by gregorygold** [comment]
Update: Hello all,

The issue had been resolved,  it was due to the S3 bucket setup.

Regards

Greg

"I can't change the direction of the wind, but I can adjust my sails to always reach my destination"...- Jimmy Dean
________________________________

**Comment by alena-babrova** [comment]
Hello everyone,
I see that @gregorygold has resolved the issue, and it was not related to ReportPortal but to S3 bucket setup, is it true?
@MJMayur02 @VinGt22 is the issue still relevant for you?

**Comment by MaryiaRymarchyk** [comment]
@MJMayur02 @VinGt22, as we haven't received a reply from you, we'll close the issue for now.
If  the issue still relevant - reopen or just get in touch.
