### ISSUE TITLE
Null instead of IP in a hyperlink in an email message[v5]

### ISSUE THREAD

**Issue by maxten** [reportportal/reportportal#1656]
**Describe the bug**
Email notification set up. We noticed a pattern, if it hangs for one day and later stops due to a timeout, then there is no IP address of the server in the hyperlink of the email message, null is displayed instead

Version Report Portal 5.6.0

**Screenshots**
![image](https://user-images.githubusercontent.com/14238511/151924129-cd316a7d-aac6-4083-a87a-aa680c20e127.png)
![image](https://user-images.githubusercontent.com/14238511/151924170-ef73dcc8-24d0-4657-be71-d5f789885e85.png)
![image](https://user-images.githubusercontent.com/14238511/151924306-ab34db96-14e9-4253-8907-766998c0bbb8.png)

**Comment by MaryiaRymarchyk** [comment]
Hello @maxten , thank you for reaching us with this issue!
I've reproduced it on later versions of RP (5.7.5) and have created the defect in our backlog (EPMRPP-83956). The Defect will be fixed according to the priority in next versions of RP. 
As temporary workaround you can remove 'null' manually from the link, as it is extra value, not unresolved variable.

**Comment by MaryiaRymarchyk** [comment]
UPD: Fix will be available with RP-23.3 release.

**Comment by Kozovskaya** [comment]
Hello @maxten 
I'm pleased to let you know that the fix is already released!
https://github.com/reportportal/reportportal/releases/tag/v24.1
