### ISSUE TITLE
Public page with widget with acceptance tests result. (read-only access without password)

### ISSUE THREAD

**Issue by mva730** [reportportal/reportportal#166]
As RP user I want to have public page with widget with acceptance tests result

**Comment by ksuglotova** [comment]
@mva730 Could you please specify what way you are going to use such public page for? For example, it may be some kind of dynamically updated page for the Customer who has access to the current project? Or other goal/project need?

**Comment by avarabyeu** [comment]
Not really sure it's good idea to implement it from security perspective. I would rather suggest to use export in order provide non-users with execution results

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu problem is that our client also looking for such functionality.

there options here:
1. read-only user and hardcoded login button for it on UI
2. special export tunnel for specific data. kind of `read-only dashboard`

**Comment by DzmitryHumianiuk** [comment]
Can be covered with:

1. LDAP/AD integration
2. for #164 and #2 will be added auth-service mock, which will return only one user for everyone.

it self, access to specific data, when everything else covered by access permission, real overhead for implementation.
