### ISSUE TITLE
[v5] Newly installed RP not working due to Elasticsearch permission issue

### ISSUE THREAD

**Issue by derkraken21** [reportportal/reportportal#1664]
**Describe the bug**
I installed the RP thru WSL2. RP UI works but tests are not reflecting in the dashboard. Logs show that there is Elasticsearch access problem. Im new to Linux and Docker. Hopefully someone could help out.

**To Reproduce**
Install RP to WSL2 , follow the instruction [here for Ubuntu](https://reportportal.io/docs/Deploy-ReportPortal-on), add the Cypress plugin and run the test.

**Expected behavior**
Launch and test activities should be in Dashboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/87989944/152537772-60e80efb-4537-4ea2-90e6-2b0bc14a707e.png)

**Desktop (please complete the following information):**
 - OS: WIn 10
 

**Additional context**
Plugin used: @reportportal/agent-js-cypress

**Comment by axxyhtrx** [comment]
maybe you need to add permisisions to data folder, where your elastisearch is installed.
Check this part here: https://reportportal.io/docs/Deploy-with-Docker

**Comment by derkraken21** [comment]
Hi! I actually did that part as well and tried the RP installation twice but i always get the same thing. But maybe i have to remove Elasticsearch completely and install again. Is there a way to remove Elasticsearch completely so I can redo the whole installation process for RP (3rd time ? Thank you so much for the help. I badly needed this tool to analyse my flaky tests.

**Comment by derkraken21** [comment]
Update:

I managed to remove the Elasticsearch and reinstalled it. The issue has been fixed.
