### ISSUE TITLE
Customize or creating own widget with respect to user need 

### ISSUE THREAD

**Issue by test1sele** [reportportal/reportportal#1667]
For our QA team, we need the possibility of adding custom widgets (with custom filter)
Example: Most time consumed test cases widget only shows the execution time taken for a test case/scenario under one particular launch. 
What we want is to get a similar graph but for the same test case with reruns. 

So these kind of situations may occur later on, so it would be helpful if a a feature for adding custom filter was added.

**Comment by DzmitryHumianiuk** [comment]
@test1sele there are 2 simple way to do so:
1. contribute implementation
2. request a paid service from ReportPortal team at https://reportportal.io/ and `Ask Service` button.
