### ISSUE TITLE
Notification getting generated with no test case run

### ISSUE THREAD

**Issue by aanchal-narang** [reportportal/reportportal#1668]
We are facing an issue with report portal notification after latest deployment. 
It is giving notification for the job with no test cases.

It used to work fine with previous build. Please check this issue.
My expectation is if there is no test case run with the report, it should not give a blank notification with null attributes.

**Comment by aanchal-narang** [comment]
Previous version was 5.6.1.
Current version:API Service: 5.6.3; Jobs Service: 5.6.3; Authorization Service: 5.6.3; Service UI: 5.6.0

**Comment by VolhaKarenko** [comment]
hi @aanchal-narang, as far as I understand, you have a launch with no tests inside, right? Could you please share a screenshot of the notification received?

**Comment by DzmitryHumianiuk** [comment]
@aanchal-narang ^

**Comment by aanchal-narang** [comment]
[](url)
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/68216031/180418918-176e9670-d96b-4a84-9db0-17ba230316b7.png">

**Comment by aanchal-narang** [comment]
@DzmitryHumianiuk , @VolhaKarenko Please refer above screenshot

**Comment by VolhaKarenko** [comment]
Hi @aanchal-narang, I didn't manage to reproduce the issue. Could you please attach a screenshot of how the blank notification with null attributes looks? Also, please share the attributes of the launch

**Comment by MaryiaRymarchyk** [comment]
Hi @aanchal-narang , do you have updates here? 
Is the issue still relevant?

**Comment by MaryiaRymarchyk** [comment]
hi @aanchal-narang 
long time no hear from you, so we'll close the issue for now.
Just in case you still have the issue, please, provide more details as described in comment above.
