### ISSUE TITLE
error: Dirty database version 37. Fix and force version after a portal upgrade from 5.4.0 to 5.5.1

### ISSUE THREAD

**Issue by TanVin90** [reportportal/reportportal#1669]
Hello,

The container (migration) is failing with the following error after portal upgrade from 5.4.0 to 5.5.1.

09/02/2022 17:29:58 wait-for-it.sh: waiting 15 seconds for postgresql.reportportal-##:5432
09/02/2022 17:29:59 wait-for-it.sh: postgresql.reportportal-##5432 is available after 0 seconds
09/02/2022 17:29:59 error: Dirty database version 37. Fix and force version.

**Comment by DzmitryHumianiuk** [comment]
@TanVin90 your migration process failed while data transit.
clean up target database and restart migration.

https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.5.5
