### ISSUE TITLE
Check issues, holding Shift and Ctrl

### ISSUE THREAD

**Issue by mva730** [reportportal/reportportal#167]
When investigating launch, often we have same failures. It would be nice to check same issues just holding Shift and clicking, and not checking via interface. Now we are doing it next way (clicking on checkbox):
![image](https://user-images.githubusercontent.com/17176601/27786803-4f3a9084-5feb-11e7-9ff8-71ab772d2173.png)

**Comment by DzmitryHumianiuk** [comment]
and Ctrl (Control) and CMD button

**Comment by lexecon** [comment]
fixed in version 3.2

**Comment by Iren-Melnyk** [comment]
Thank you for your request.
We are going to add the functionality of 'hot keys':
- use 'Cmd' ('Ctrl' for Windows) to check one item not only on a checkbox but on the whole area of the item except links;
- use 'Cmd+Alt' ('Ctrl+Alt' for Windows) to check multiple items.
