### ISSUE TITLE
Printing Dashboard is not working properly

### ISSUE THREAD

**Issue by satishkumar9549** [reportportal/reportportal#1671]
I have few widgets on my project which I am trying to print but when I did click on Print and I don't see the exact colors or fonts. Can you please help me with this fix. Please find the below screenshot. 
![image](https://user-images.githubusercontent.com/22459825/153482337-eaf2d364-29e1-444f-abd9-de7f47a548fb.png)

**Comment by VolhaKarenko** [comment]
Hi @satishkumar9549, could you specify the Report portal version and browser that you are using?

**Comment by satishkumar9549** [comment]
Versions:

OS, Browser
Version of RP - 5.3.5

**Comment by tr1ble** [comment]
Hello [satishkumar9549](https://github.com/satishkumar9549), there is no such an issue for RP 5.6.3 and higher. Please upgrade to this version and Feel free to let me know if issue is still actual.
