### ISSUE TITLE
Post Jira Issue for Jira Cloud

### ISSUE THREAD

**Issue by Syed-Saad-Ali-GIT** [reportportal/reportportal#1672]
Was wondering when the support for posting issue on Jira cloud will be created - a rough ETA , messages on slack have mentioned version 5.7 which had an ETA for December 

Any updates

Thanks in advanced

**Comment by Houssem985** [comment]
Hello, 
We are facing the same issue. Any updates regarding it?
Thanks in advanced

**Comment by DzmitryHumianiuk** [comment]
ETA ~March 15, 2022
