### ISSUE TITLE
Unable to install report portal with the latest docker version using docker-compose

### ISSUE THREAD

**Issue by shrinivasbb** [reportportal/reportportal#1674]
Unable to install report portal using docker-compose.yml present in master branch.

$ docker-compose -p reportportal up -d
ERROR: Version in "./docker-compose.yml" is invalid. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

How to resolve this?

**Comment by DzmitryHumianiuk** [comment]
@Cyberglamdring please take a look
