### ISSUE TITLE
Is it possible to widgets to be filtered to test level

### ISSUE THREAD

**Issue by test1sele** [reportportal/reportportal#1678]
is there Filter options for widgets so that i can filter out test cases too?

**Comment by DzmitryHumianiuk** [comment]
@test1sele 
**Component Health Check** allows you to structure filtered data on test levels.
https://reportportal.io/docs/Component-health-check

<img width="806" alt="image" src="https://user-images.githubusercontent.com/11332788/155433199-b300781f-e06d-4961-b190-633cfdf10900.png">
