### ISSUE TITLE
Importing group of suites (JUnit) is very slow compared to separate import (and merge)

### ISSUE THREAD

**Issue by tanov** [reportportal/reportportal#1679]
I have a big JUnit XML file with the following structure:
`<testsuites>
   <testsuite></testsuite>
   <testsuite></testsuite>
   ...
</testsuites>`
It contains 11 suites with total tests count of 3400.
The following import API call:
```bash
curl -X POST "https://example.com/api/v1/user/launch/import" -H "accept: */*" -H "Content-Type: multipart/form-data" -H "Authorization: bearer example" -F "file=@file.xml;type=text/xml"
```
blocks for 19 min (the import duration). Doing the import through the GUI takes the same time.

When doing the call for each suite as a separate xml file, all the 11 calls take 5 min. Merging the results in the GUI is instant.

**Expected behavior**
I expect the import time of the big xml file (900Kb) to take the same time as the separate files import. I don't think the issue is in the file size and the upload, because in the GUI you can see that it is in progress and the tests count is rising, so it seems to be the processing time.

**Versions:**
Current version:API Service: 5.2.1;Index Service: 5.0.10;Authorization Service: 5.3.3;Service UI: 5.2.0;

UPDATE:
After zipping the xml before the call, it is very fast, tests are imported well, but in the end I am getting:
```
{"errorCode":40035,"message":"Error while importing the file. 'Error during parsing the xml file: 'Content is not allowed in prolog.''"}
```

**Comment by Oleksii-kh89** [comment]
Hi @tanov 
When the upcoming version 23.1 will be released please update RP and check if the issue still occurs. Thank you!

FYI we are switching to a new version naming, a separate article will be published soon!
