### ISSUE TITLE
Find launch via launch number.

### ISSUE THREAD

**Issue by mva730** [reportportal/reportportal#168]
Now we can filter launches only by its name. It's convenient for my team to find launch by it's number, because number is unique.

**Comment by avarabyeu** [comment]
@mva730 do you need this parameter on UI level? It's actually already possible to do via API, just add ```filter.eq.number=10```

**Comment by ksuglotova** [comment]
The same question is on a [#22 Unable to search by launch number](https://github.com/reportportal/reportportal/issues/22)
