### ISSUE TITLE
Unable to change general settings once it is selected.

### ISSUE THREAD

**Issue by KS310** [reportportal/reportportal#1680]
We first set Keep launches and Keep logs to 90 days in the general settings screen, and now we want to change it to fewer than 90 days, but there is no way to do so.

Expected behavior:
Providing an option to change back general settings whenever required.

Screenshots:

Versions:
 - Chrome
 - Version of RP : API Service: 5.6.2;Jobs Service: 5.6.2;Authorization Service: 5.6.2;Service UI: 5.6.0;

**Comment by DzmitryHumianiuk** [comment]
@KS310 is it a self-hosted instance?
Do you have screenshots or smth?

is the list disabled or just don't open? or items disabled.
Since what you describing is more relevant for a managed instance with a limited data keeping.

**Comment by KS310** [comment]
@DzmitryHumianiuk  yes. Please find the screenshots
![Capture1](https://user-images.githubusercontent.com/99957271/155929667-7b1eef77-e0f1-47ee-99b7-34e739169d8d.JPG)
![Capture](https://user-images.githubusercontent.com/99957271/155929682-9151a579-2b4d-4b15-bbcd-f1fbc7210739.JPG)

Items seems to disabled. 
I could only see the items greater than the selected one.

**Comment by KS310** [comment]
@DzmitryHumianiuk
Any update on this?

**Comment by DzmitryHumianiuk** [comment]
@VolhaKarenko ^^ please verify

**Comment by VolhaKarenko** [comment]
Hi @KS310, please check your "Keep attachments" value should be lower or equal to "Keep logs" and "Keep launches" values you want to set
![image](https://user-images.githubusercontent.com/42797492/157510323-1d978c46-532e-4d1d-9c83-09efa45ce29c.png)

**Comment by KS310** [comment]
Hi @VolhaKarenko, Tried as you said. It seems based on keep attachments keep logs is changing. But still I don't see items enabled for keep launches.

**Comment by KS310** [comment]
Hi @VolhaKarenko, Tried as you said. It seems based on keep attachments keep logs is changing. But still I don't see items enabled for keep launches.

**Comment by KS310** [comment]
Yes it works, Thanks @VolhaKarenko!!
