### ISSUE TITLE
LDAP Manager passsword is in plain text

### ISSUE THREAD

**Issue by ofir2006** [reportportal/reportportal#1681]
In the LDAP plugin configuration, the manager password appears to be in plain text

![LDAPO](https://user-images.githubusercontent.com/2917161/155094345-b1b66cd2-eaab-4f58-a305-32e071c0faca.jpeg)

**Comment by VolhaKarenko** [comment]
The issue is added to backlog, planned to be fixed in version 5.8

**Comment by Kozovskaya** [comment]
Hello @ofir2006 
I'm pleased to let you know that the fix is already released!
https://github.com/reportportal/reportportal/releases/tag/v24.1
