### ISSUE TITLE
Customized widget background colour

### ISSUE THREAD

**Issue by see-quick** [reportportal/reportportal#1683]
Hi,

I would like to ask if there is an option to specify the background colour of the widget in the report portal. I did not find anything in your doc ([1]), so I want to double-check if there are the possible way how to achieve it. 

[1] - > https://reportportal.io/docs/Widget-Creation

**Comment by DzmitryHumianiuk** [comment]
@see-quick Hey,
it was not meant to be possible.

what's the point to change it?

**Comment by MaryiaRymarchyk** [comment]
@see-quick Hi!
As we haven't received a reply from you, we'll close the issue for now.
If you want something to add, please, do not hesitate to contact us.
