### ISSUE TITLE
Not able to update in report portal while running from .jar file.

### ISSUE THREAD

**Issue by JYOTIPRAKASH225** [reportportal/reportportal#1685]
**Describe the bug**
Not able to update in report portal while running from .jar file.
It successfully updates when I run from any IDE.

**Expected behavior**
It should update while from .jar also.

**Screenshots**

**Versions:**
 - Version of RP [find it under Login form, copy as is]: 5.1.0

**Comment by HardNorth** [comment]
Any details? Why do you think this is RP bug and not your configuration issue? Which agent, version, configuration options do you use? Closing this until detailed description.
