### ISSUE TITLE
redirect from https to http

### ISSUE THREAD

**Issue by kshcherban** [reportportal/reportportal#169]
Hello,

After configuring services in docker and visiting https://portal.example.com/ i'm being redirected to http://portal.example.com/ui/

```
curl -I localhost:10284/
HTTP/1.1 302 
X-Application-Context: gateway:docker:8080
Location: http://localhost:10284/ui/
Content-Language: en
Transfer-Encoding: chunked
Date: Mon, 03 Jul 2017 15:49:23 GMT
```
I've forwarded both ports 8080 and 8443 but 8443 doesn't work.

Can you please advise how to keep https if it's possible?

**Comment by avarabyeu** [comment]
@kshcherban https is disabled by default. There is an option to setup https on some reverse proxy (like nginx) and put report portal behind it.

**Comment by kshcherban** [comment]
@avarabyeu thanks, i try to run application in front of AWS Application Loadbalancer

**Comment by DzmitryHumianiuk** [comment]
@kshcherban it would be great, if you can share instructions after that )

**Comment by kshcherban** [comment]
@DzmitryHumianiuk the funny thing that it doesn't work with https because app has all the redirects to http, i just created http listener in ALB as well.

**Comment by avarabyeu** [comment]
@kshcherban right. Another option is to configure gateway to handle https. You can actually do it via environment variables. Here is how it can be done: https://drissamri.be/blog/java/enable-https-in-spring-boot/

**Comment by avarabyeu** [comment]
@kshcherban can we close the issue?

**Comment by DzmitryHumianiuk** [comment]
@kshcherban up

**Comment by kshcherban** [comment]
I think with the latest versions changes it can be resolved. Thank you.
