### ISSUE TITLE
Data migration from v4.3 to v5.0 fails - Factory method 'levelItemsFlow' threw exception

### ISSUE THREAD

**Issue by mdzierzecki** [reportportal/reportportal#1691]
**Describe the bug**

When migrating data from ReportPortal v4.3 to v5.0 via the provided latest docker-compose, the process fails with multiple dependency errors. Logs provided below.

I was trying to delete mongo collection ('filterMapping', 'widgetMapping', 'optimizeTest') but I don't have this collections in my Mongodb(mongo:3.4) database.

"db.getCollection('testItem').find()". <--- this command returns data
"db.getCollection('testItem').find({"start_time" : {$exists : false}})"   <--- this command after about 20 seconds, there is nothing in response
"db.getCollection('optimizeTest').find()"  <--- this command does not return data

Our db has about 50GB. The data is from about 2019 to 2022.

Unfortunately there is no any sufficient information whats wrong with migration.  Moreover, there is no 'batch_job_execution' table in Postgres.

**Expected behaviour**
I expected data to be moved from the mongo database to the postgres database without issue.

**Screenshots**
Logs:
[rpv4-migration.txt](https://github.com/reportportal/reportportal/files/8206062/rpv4-migration.txt)

Docker-compose .YAML config:
[docker-compose.txt](https://github.com/reportportal/reportportal/files/8206182/docker-compose.txt)

**Versions:**
Current version: Analysis Service: 4.3.0; API Service: 4.3.4; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.6;

**Comment by pbortnik** [comment]
Hi @mdzierzecki,
Please, try to upgrade API version to 4.3.11 and restart the migration.

**Comment by Mark-Zhang-007** [comment]
Hi, @pbortnik 
Actually, you should check if without any error when run settings-migration & data-migration. 
And you should expose your MongoDB port before migration otherwise the connection between MongoDB & Postgres will generate timeout issue when data-migration.
Hope it is helpful for you.

**Comment by mdzierzecki** [comment]
> Hi @mdzierzecki, Please, try to upgrade API version to 4.3.11 and restart the migration.

@pbortnik Should I only change the image tag of the service-api to 4.3.11? Is there any migration script needed? Or just changing the image tag will do the job on the MongoDB side?

**Comment by mdzierzecki** [comment]
@pbortnik I have changed the API version as you mentioned but the is no any changes in script behaviour. Errors still occur

**Comment by pbortnik** [comment]
Hi, @mdzierzecki 
Can you send the list of existed collections in your MongoDB ?
