### ISSUE TITLE
Can't change Base Url of Email Notification HyperLink After Migration

### ISSUE THREAD

**Issue by Mark-Zhang-007** [reportportal/reportportal#1692]
I migrated reportportal v4.3 from Server A to ServerB with v5.6.2 successfully, but the hyperlinks in email notification still using ServerA's host name after specific launch finished. 
Is this one issue in migration or we can modify related settings about launch url link to new server's after migration? 
Thanks so much for your guides!

![image](https://user-images.githubusercontent.com/38271436/157367467-b38e4ca0-b92c-4c68-b480-6a9c7529d775.png)

**Comment by MaryiaRymarchyk** [comment]
Hi @Mark-Zhang-007,  sorry for the silence.
If the issue still relevant,  could you please check with the latest version of RP ?
