### ISSUE TITLE
Filter cannot be assigned by superadmin to other user

### ISSUE THREAD

**Issue by llowinge** [reportportal/reportportal#1695]
**Describe the bug**
1) Superadmin creates shared filter with ID=128
2) User llowinge see that filter in filters list, but the filter is by default disabled
3) Superadmin tries to remove the filter from llowinge account: `curl -sS -XDELETE "${httpHeaders[@]}" "$API_URL/project/camel-quarkus/preference/llowinge/128"`
Response: `{"message":"Filter with id = 128 successfully removed from launches tab."}%`
4) Superadmin tries to add the filter to llowinge account: `curl -sS -XPUT "${httpHeaders[@]}" "$API_URL/project/camel-quarkus/preference/llowinge/128"`
Response: `{"message":"Filter with id = 128 successfully added to launches tab."}%`

After step 3) there are no changes in the filters UI (the filter is still there and not enabled)
After step 4) there are no changes in the filters UI (the filter is still there and not enabled)

**Expected behavior**
After step 3) filter is removed from account llowinge filters UI
After step 4) filter is assigned to account llowinge filters UI and it is visible

**Screenshots**
If applicable

**Versions:**
 - OSX, Chrome
 - Version of RP: 5.5.1

**Comment by llowinge** [comment]
Just additional note, if all operations are done by one user (eg. llowinge), then it works. So the problematic part is when superadmin is trying to enable the filter to different user.

**Comment by alena-babrova** [comment]
Hello @llowinge 

We haven't managed to reproduce the case.

Is the issue still relevant?
Do you need any assistance?

**Comment by alena-babrova** [comment]
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
