### ISSUE TITLE
Error 500 on login of EPAM user with accepted invitation sent to work email

### ISSUE THREAD

**Issue by Rider1982** [reportportal/reportportal#17]
I sent an invitaion from RP to some EPAM user to his corporate email.
The user tries to login (the both EPAM and email/password logins shows the same) and see the following error message:

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Thu Dec 01 08:11:30 GMT 2016
There was an unexpected error (type=Internal Server Error, status=500).
Incorrect authentication type: User with your domain email already exists. You cannot create duplicate

**Comment by avarabyeu** [comment]
@Rider1982 Could you please attach stacktrace? Actually, it's not an issue, because *.epam.com users are synchronized automatically and RP does not login them via standard basic auth mechanism. But problem here is that you use 500 instead of some more informative error.

**Comment by Rider1982** [comment]
I do not see any stack trace on error page.

**Comment by avarabyeu** [comment]
@Rider1982 could you please grab response body and put it here?
