### ISSUE TITLE
SendGrid Integration Issue

### ISSUE THREAD

**Issue by ksg1998** [reportportal/reportportal#1700]
SendGrid Integration is not working on our ReportPortal Instance (5.6.3) deployed on a  Kubernetes Cluster

![image](https://user-images.githubusercontent.com/45259290/158641709-8b5c5c15-4bc2-4997-92c0-584687a7a7c4.png)

We have configured the details correctly and have used the same details on other apps and it works perfectly. When we try to submit the configurations getting Bad Credentials error.

We have noticed another interesting scenario where when we replace the sender email with the username the integration is successful. But then on testing the email notifications getting a "SMTP 550 error when trying to configure Sendgrid as SMTP server"

**Comment by MaryiaRymarchyk** [comment]
Hi @ksg1998 , sorry for the silence.
The field 'sender email' should be filled with  email, not with username. Error 'Bad credentials' with provided mail - seems that issue not on RP side. Could you please check your email account settings for any connection restrictions?
If the issue still relevant - Please see the email server integration guide: https://reportportal.io/docs/plugins/EmailServer/#add-e-mail-server-integrations. 
Let us know if additional support is required. In case of no answer - ticket will be closed in 21 days.

**Comment by MaryiaRymarchyk** [comment]
Hi @ksg1998, as we haven't received a reply from you, we'll close the issue for now.
If  the issue still relevant, just get in touch.
