### ISSUE TITLE
Editing defects in bulk doesn't rewrite the existed comment for the item

### ISSUE THREAD

**Issue by anastasiia-petrenko** [reportportal/reportportal#1702]
**Description**
It is possible (and often useful) to edit the several defects at once on the launches page by selecting several items. But if the item has already had a comment the new will be added at next line and the old one remains in the comment which creates a mess for Auto-Analysis and harder to analyze the failures

**Expected behavior**
I would expect if I use the 'Edit defects' action then the comment field will be cleaned and rewritten by the new comment

**Screenshots**
![image](https://user-images.githubusercontent.com/76481576/158760738-6055dfb9-912e-495c-8580-2e88ad1d0d40.png)
![image](https://user-images.githubusercontent.com/76481576/158761069-8653d655-ce8c-4e4a-8d27-dfcb8bd002b7.png)

**Versions:**
 - OS, Browser (Windows 10, Edge 99.0.1150.39)
 - Version of RP (5.6.0)

**Comment by anastasiia-petrenko** [comment]
I have just noticed that the same occurs when you select a new explanation for the failed test from the 'history line'
1. I have that issue and I want to change the defect information
![image](https://user-images.githubusercontent.com/76481576/159262806-fdc4c043-2680-4c7a-bc6a-ad8c324e7ee3.png)

2. I open the decision page and select the one from the 'history line'
![image](https://user-images.githubusercontent.com/76481576/159263070-be545d2c-5d67-4c70-9c1c-1291877f6082.png)

3. The new comment and the old one are added to the defect
![image](https://user-images.githubusercontent.com/76481576/159263328-e487916c-7424-431a-b676-254f7c245aff.png)

**Comment by Rickdickulous** [comment]
Seconding this. Could have an option to replace comment or append to existing comment.

**Comment by anastasiia-petrenko** [comment]
Right, Now I can replace the comment, apply it to existing or just clear it. Thanks

**Comment by Kataklizmic** [comment]
I am experiencing the same issue with the comments under the Defect Type column; and when using "Edit Item" and selecting to replace all, it adds the comment to the description field rather than the comment on the defect type. After a lot of time searching, there appears to be no way to bulk replace the defect type comment.
