### ISSUE TITLE
Unable to delete data stored in file system

### ISSUE THREAD

**Issue by Jiyvn** [reportportal/reportportal#1706]
**ReportPortal settings**
data is kept only for 7 days
<img width="799" alt="image" src="https://user-images.githubusercontent.com/73217816/159624957-3af8ebca-6567-438b-b5c5-e0a0bd11097b.png">

**Data folder**
but actually data not deleted in data folder, which induces a continuously increasing size.
<img width="653" alt="image" src="https://user-images.githubusercontent.com/73217816/159615664-130ea4e2-76fc-4857-bb27-f97d9febdf58.png">

**Versions:**
 - RP [5.6.0]

By the way, how to delete these data? deleting launches does not help. Could I directly delete the data file older than 7 days?

- https://github.com/reportportal/reportportal/issues/1211#issuecomment-731272963

**Comment by talmoshe24** [comment]
My DB is huge, almost 500GB now.  Most of the data is on "log" table
Not shrinking even if I reduce the retention policy to 30 days.
Any solution for that?

**Comment by Jiyvn** [comment]
solved by deleting these attachments above, have to use `crontab` to clean periodically

**Comment by koenigcode** [comment]
I can confirm, the attachments are still not deleted in minio despite having only 14d or less as data to keep configured.
configured on my system is minio/minio:RELEASE.2020-10-27T04-03-55Z   with reportportal/service-jobs:5.7.1
not latest, but bug still seems to be open? this should be cleaned by reportportal and not some cron hack or manually?

**Comment by Oleksii-kh89** [comment]
Hi @koenigcode 
My suggestion is to wait for the RP v 5.7.3 and update.

Also, there are similar issues, please look through these related topics:
#1792 
#1796

**Comment by Oleksii-kh89** [comment]
Solved by Requestor
