### ISSUE TITLE
Is there a way to show new failures in latest launch?

### ISSUE THREAD

**Issue by lizzyliuY** [reportportal/reportportal#1707]
Hi,

Does there have any widget to show the new added failed cases in latest launch? Or is there any other way to show those failures?

Thanks,
Lizzy

**Comment by alena-babrova** [comment]
Hello @lizzyliuY 

Yes, Report portal provides such feature. It is "Quality gate" plugin where you can configure rules for launch results analysis. 
![image](https://user-images.githubusercontent.com/89584140/200577819-3aca0e15-4b09-4daf-81ea-30c911d16ddc.png)
But it is Enterprise feature and there are several options to purchase this plugin:
1. buying this plugin (you can contact support@reportportal.io to get more details)
2. using saas instance which is also a paid service (https://reportportal.io/pricing)

Don't hesitate if any questions.
Thank you

**Comment by alena-babrova** [comment]
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
