### ISSUE TITLE
Imposible to invite user using LDAP

### ISSUE THREAD

**Issue by iSpirydonava** [reportportal/reportportal#1708]
**RP version** 5.5

A new user is not possible to add in RP project. This user logined  at least once. 

![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/37439187/160358116-3d2be3d3-4a88-41d1-9e42-4e528e69b413.png)

In log we see the issue: 
![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/37439187/160358121-3b492dfd-86df-4be0-8d93-05ca215d5ca0.png)

**Comment by AmsterGet** [comment]
@Yumfriez could you please take a look?

**Comment by Yumfriez** [comment]
Probably we have troubles between syncing users registered using external authentication.
@iSpirydonava Could u please provide us a scenario to reproduce this issue on our dev env?

**Comment by ecavalcante** [comment]
Hi all,  where i find a documentation more complete about the LDAP configuration? I put the informations in the LDAP’s plugging, but I can’t invited  the LDAP users to ReportPortal projects. What’s the next steps after filling out the ldap plug-in form? Are  you have  a exemple of LDAP configuration? I tried with a online Ldap called Forumsys, but does worked too.

**Comment by iSpirydonava** [comment]
@Yumfriez  The LDAP configuration has been done by using the superadmin account in the plugin section.
We have a separate LDAP security group and provided the password for it.
Then a project was created and certain users were provided 'project manager' roles in order to invite new members. This worked previously, but it stopped working around a month ago for the given project.
For testing purposes we have created another project and there the person with 'project manager' rights is able to invite users (the same users we are unable to invite on the main project).

**Comment by alena-babrova** [comment]
Hello @iSpirydonava 

Could you please tell the issue is still relevant?
Have you managed to solve it?
Thanks!

**Comment by iSpirydonava** [comment]
Dear colleagues,

The issue is not actual anymore. Thanks.


Best regards,
Iryna Spirydonava
Solution Architect I
Office:  +36 1 327 7400x30255<tel:+36%201%20327%207400;ext=30255>    Mobile:  +7 921 445 38 78 <tel:+7%20921%20445%2038%2078>
Call On ***@***.***>    LinkedIn<https://www.linkedin.com/in/iryna-spirydonava-8a434580>
Belgrade, Serbia Timezone: (America/New_York)
Working Remotely Timezone: (UTC+02:00)
epam.com <http://www.epam.com>
***@***.***


CONFIDENTIALITY CAUTION AND DISCLAIMER

This message is intended only for the use of the individual(s) or entity(ies) to which it is addressed and contains information that is legally privileged and confidential. If you are not the intended recipient, or the person responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. All unintended recipients are obliged to delete this message and destroy any printed copies.

**Comment by alena-babrova** [comment]
Dear @iSpirydonava,

Fine, thank you. 
Please, do not hesitate to get in touch in future questions.
