### ISSUE TITLE
Feature request: make launch depth for AA to be configurable

### ISSUE THREAD

**Issue by jurteg** [reportportal/reportportal#171]
Current auto analisys depth is 4 (four) launches, if I'm not mistaken.
Requesting to make this number configurable, so any stand alone RP server could use it's own setting.
This feature will likely increase AA time for all launches in the particular project, however will give a possibility to trace long term issues within the scope of launches.

**Comment by avarabyeu** [comment]
it's actually already configurable. I've updated documentation with that parameter:
http://reportportal.io/#documentation/Additional-configuration-parameters
