### ISSUE TITLE
Reportportal to JIRA integration fails with error: Impossible interact with integration. connection refused

### ISSUE THREAD

**Issue by vaibhavjagdale** [reportportal/reportportal#1713]
**Describe the bug**
I am trying to integrate a project in reportportal.io to JIRA project. When trying to configure, it is failing with error "Impossible interact with integration. connection refused." like the attached picture.

I have set-up report portal using https://reportportal.io/docs/Deploy-with-Docker and then added Jira plugin from https://github.com/reportportal/reportportal `plugin-bts-jira-5.1.0-all.jar.` No container with name `reportportal/service-jira `running. I have generated API keys for my Jira projects in order to use instead of password. still I am getting error. 
**Expected behavior**
Able to integrate jira with report portal if all configuration are correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/50039131/161490957-0b2821a7-feb3-4508-993a-1496da2286ec.png)

**Versions:**
 - OS: Windows 10
 - Browser: chrome
 - **Version of RP: 5.6.3**

**Comment by serdnago** [comment]
This works for me, try the following:
1.- Remove from the Link to BTS everything after atlassian.net
2.- Project name in Jira should be the project key
3.- BTS password should be the API token from Jira

**Comment by vaibhavjagdale** [comment]
My BTS link was wrong. I correct it and its work now !

**Comment by JayashreePhataangare** [comment]
> My BTS link was wrong. I correct it and its work now !

Hey Vaibhav, 

Could you please tell me what was the URL changed later? I am also facing same issue with RP Version: 5.6.0 and installed Jira "plugin-bts-jira-5.1.0-all.jar". 

And when trying integration - its showing same error as you were facing. 

[stackoverflow question](https://stackoverflow.com/questions/73441446/report-portal-io-integration-with-jira-server-error-occurred-while-connectin)
