### ISSUE TITLE
create a open read user

### ISSUE THREAD

**Issue by fenchu** [reportportal/reportportal#1718]
I like to have a read user that can see all cases and dashboards, but the user api insists on setting password:

```
{
  "errorCode": 4001,
  "message": "Incorrect Request. [Field 'password' should have size from '4' to '256'.] [Field 'password' should not contain only white spaces and shouldn't be empty.] "
}
```
How can we add an open user?

**Comment by alena-babrova** [comment]
Hello @fenchu,
For now, we don't have possibility to create a user with global read only permissions.
Please try to use existing roles. Hopefully this may solve your task.
You can see the available permission schema in the screenshot below: 
![image](https://github.com/reportportal/reportportal/assets/89584140/3a994323-6b85-42c5-94f3-aab9f9c4c2d5)
