### ISSUE TITLE
Allow logs to be sent in plaintext format

### ISSUE THREAD

**Issue by abotalov** [reportportal/reportportal#172]
Currently our custom client/agent sends plaintext error messages and stacktraces to Report Portal using "POST /{projectName}/log".
Exception messages / stacktraces contain special symbols like \* and others.
But when I view UI, I see these \* symbols converted into \<strong\> tags. There are some other issues, presumably because of markdown as well.
I think a parameter should be added to "POST /{projectName}/log" to indicate whether log is markdown or not.
Also if a log is plaintext, it should be displayed as is. For example several spaces in a row should be displayed as several spaces in a row rather than being replaced with a single space.

**Comment by DzmitryHumianiuk** [comment]
@abotalov please check it with 3.0.5

**Comment by DzmitryHumianiuk** [comment]
3.1 markdown disabled by default in logs
