### ISSUE TITLE
Test results not pushed if rp.endpoint is updated to use a DNS URL

### ISSUE THREAD

**Issue by akshayamaldhure** [reportportal/reportportal#1724]
We recently enabled DNS for our local Reportportal instance via Kong. After doing this, Reportportal is accessible through a browser with HTTP (the URL shows strikeout HTTPS, like this ~https~, so basically there's a redirect from http to https), but if we update the `rp.endpoint` to use the URL, we see that the test results are not pushed (tried with both http and https). If we use the same old IP address:port number format, then the results are populated as usual.

Below are some additional observations:

```
curl -k http://our-rp-instance.xyz.com
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>

curl -k https://our-rp-instance.xyz.com
<a href="/ui/">Found</a>.
```

```
➜  ~ telnet our-rp-instance.xyz.com 443
Trying <kong_proxy_ip_address>...
Connected to proxy.xyz.com.
Escape character is '^]'.
^C^C^ZConnection closed by foreign host.
➜  ~ telnet our-rp-instance.xyz.com 8080
Trying <kong_proxy_ip_address>...
telnet: connect to address <kong_proxy_ip_address>: Connection refused
telnet: Unable to connect to remote host
```

I have no way to understand what's going wrong since I do not see any HTTP logs even with `rp.http.logging=true` on the latest version of `agent-java-testng`.

How do I debug this? Is the redirection part a problem?

**Comment by HardNorth** [comment]
@akshayamaldhure It is definitely a problem. The client wasn't written to follow redirects. 
What regards to `rp.http.logging=true` try configure your logging framework. Client does not log HTTP traffic directly, passing this role to `OkHttp` library instead, which we have not updated for about a year.

**Comment by akshayamaldhure** [comment]
I did try tweaking the logging configuration in my framework with no luck. As an intermediate solution, I've moved the DNS in a domain that has got a proper SSL setup for now and that works. As a solution, I believe it would be nice to have the redirection handled in Reportportal client.
