### ISSUE TITLE
Java Cucumber test count mismatch in Reportportal

### ISSUE THREAD

**Issue by asahu8x8** [reportportal/reportportal#1725]
Hi team,
We have our automation tests integration with Cucmber, TestNG and ReportPortal. The total no of tests are always different than that of actual count in test code base. Below are some screenshot of actual vs reportportal count.

![Screenshot 2022-04-22 at 3 51 32 PM](https://user-images.githubusercontent.com/84776989/164690397-6084f6f0-8cb3-4bf5-a63a-0351c0dc5279.png)

![Screenshot 2022-04-22 at 3 52 48 PM](https://user-images.githubusercontent.com/84776989/164690505-da274f3b-9630-4e8d-b9b6-c298041dcf47.png)

The actual count is 282, one of them is not part of the test suite, so the second screenshot shows 281 as total count.
Our concern is with report portal, which is showing different values for total count for different runs.

Sometime the launches are shown as running even after the test run is complete in jenkins, we have to Force Finish them from UI.

One possible clue - Sometime reportportal UI goes down and user goes into infinite loading on the UI. May be during that time the reportportal API does not respond as well. But we are not sure if this is the actual cause.

We are using **com.epam.reportportal.cucumber.ScenarioReporter** plugin with our Cucumbet TestNG test class.
We are using reportportal.properties file to provide configuraions to the agent.
_Values removed to comply with organisation policy._
`rp.mode=
rp.enable=
rp.tags=
rp.launch=
rp.project=
rp.uuid=
rp.endpoint=`

Application and API version -
**Report Portal API - 5.2.3** 
Java dependencies -

             <dependency>
  			<groupId>com.epam.reportportal</groupId>
  			<artifactId>agent-java-cucumber4</artifactId>
			<version>5.1.1</version>
		</dependency>

		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>logger-java-log4j</artifactId>
			<version>5.1.4</version>
		</dependency>

**Comment by HardNorth** [comment]
@asahu8x8 Well, server stability is the first culprit here. Because in other case your numbers will be alway different, not time-to-time.

**Comment by gnazgit** [comment]
We had similar issue, it was due to connection timed out error. Connection to our server has timed out and this is intermittent. You could get the actual error if you have enabled ReportPortal logs in your client. 

`[ERROR] 21-May-2022 13:43:34.870 [SubscriptionUtils] [onError] [51] - Start test item completed with error 
java.net.SocketTimeoutException: connect timed out`

BTW, we were still not able to figure out the solution yet.

FYI @HardNorth

**Comment by HardNorth** [comment]
@gnazgit There is no simple answer here. These are performance and deployment issues, they are tightly chained with how you deployed and loaded your instance.
