### ISSUE TITLE
disk storage at /data/storage/

### ISSUE THREAD

**Issue by talgreen1** [reportportal/reportportal#1728]
Hi,
Our disk is running our of space. The folders that takes most of the space are: 
/home/ec2-user/reportPortal/data/storage/prj-3/2022-3 
/home/ec2-user/reportPortal/data/storage/prj-3/2022-4

In the settings - we are keeping the launches for 30 days, and the logs & attachments for 14 days.
How can we clean up the disk? Can we manually delete these folders?

Tal.

**Comment by mchundi** [comment]
Seeing the same issue. Appreciate any help!!

**Comment by Mark-Zhang-007** [comment]
Facing the same issue, is there any updates on this? Thanks!

**Comment by Oleksii-kh89** [comment]
Hi, @talgreen1 I recommend you to clean manually (don`t delete folders but files) and in the database, to clean the attachments manually too.
