### ISSUE TITLE
Public API documentation

### ISSUE THREAD

**Issue by abotalov** [reportportal/reportportal#173]
Previously there used to be a link to public API in Report Portal footer.
But currently it's not there.
Also I don't see where it is documented on http://reportportal.io/#documentation

**Comment by avarabyeu** [comment]
@abotalov now you can find public api at right menu. [See screenshot](http://prntscr.com/fsb4tp)

**Comment by dharma-keyutech** [comment]
HOw to use RP API as OUR requirement
