### ISSUE TITLE
Link to models broken

### ISSUE THREAD

**Issue by serdnago** [reportportal/reportportal#1730]
Clicking on any of the models' links (API documentation section) produces this in RP:

TypeError: Cannot read properties of undefined (reading 'getScrollToKey')

Current version:API Service: 5.7.0;Jobs Service: 5.7.0;Authorization Service: 5.7.0;Service UI: 5.7.0;

**Comment by AmsterGet** [comment]
Hello @serdnago !
This issue will be fixed in the RP version 5.8 with dependencies update.
It is connected with issue in swagger UI lib.

**Comment by alena-babrova** [comment]
Hello @serdnago, 
We have fixed the issue in the 23.1 version of ReportPortal.
