### ISSUE TITLE
Getting error: Field 'attributes[].value' should have size from '1' to '128'

### ISSUE THREAD

**Issue by itramya333** [reportportal/reportportal#1733]
I am getting the following error when I run tests in Jenkins.

[ERROR] **Start test item completed with error** 
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'attributes[].value' should have size from '1' to '128'.] 
Error Type: INCORRECT_REQUEST

[ERROR] [100] **ReportPortal Finish test item execution error**
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'attributes[].value' should have size from '1' to '128'.] 
Error Type: INCORRECT_REQUEST

Also some of the scenario counts are not reflecting in Report portal and no results are found.

I am using
 <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-jbehave</artifactId>
            <version>5.0.0-RC-3</version>
        </dependency>

Could you please help in resolving this issue.

**Comment by HardNorth** [comment]
The latest version of the agent is 5.1.2, please use it: https://github.com/reportportal/agent-java-jbehave/releases/tag/5.1.2
