### ISSUE TITLE
Fetch execution history based on launch name

### ISSUE THREAD

**Issue by ASaiAnudeep** [reportportal/reportportal#1738]
Hello Team,

Is it possible to get execution history based on launch name instead of launch id?

Currently I'm able to get the history using launch ID

```sh
https://<domain>/api/v1/<project>/item/history?historyDepth=5&filter.eq.launchId=<launch_id>&filter.%21ex.parentId=true
```

**Comment by alena-babrova** [comment]
Hello @ASaiAnudeep,
Unfortunatelly, no, there is no other way to use this endpoint. The action relies on launchId.
Moreover, it is not a reliable way to use launch name as a filter parameter when we are trying to get the specific launch data.
So it is as designed and you should use launchId to get the relevant data.

Thanks!
