### ISSUE TITLE
Dashboard auto-refresh enables all defect type series on widgets

### ISSUE THREAD

**Issue by aliaksandrbasau** [reportportal/reportportal#174]
1. Open a dashboard that has a defect types in legend (e.g. Launch statistics line chart, Launch execution and issue statistic).
2. Uncheck a few defect types in legend.
![image](https://user-images.githubusercontent.com/6681200/28075479-9b92b490-6629-11e7-9694-6d5a9f79e74c.png)
3. Wait till the dashboard auto-refreshes. => Unchecked defect types are now checked.
![image](https://user-images.githubusercontent.com/6681200/28075531-c1011398-6629-11e7-9592-dbb786017841.png)

**Comment by evjlobanova** [comment]
@aliaksandrbasau it is planned to be done in 4.0
