### ISSUE TITLE
Postgres 13.4 Compatibility

### ISSUE THREAD

**Issue by sim-dav** [reportportal/reportportal#1741]
We upgraded to Aurora Postgres 13.4 last week and performance has been really poor, despite going from a db.r5.xlarge
 to a db.r5.xlarge instance.
 
 Is there a compatibility issue with RP and that version of Postgres?

**Comment by DzmitryHumianiuk** [comment]
@sim-dav hey, we haven't try it yet.
it would be great if you can contribute into this verification.

based on what i see from here:
https://alibaba-cloud.medium.com/first-experience-with-postgresql-13-beta-1-f842c0db61f1#:~:text=Compared%20with%20PostgreSQL%2012%2C%20PostgreSQL,plan%20uses%20index%20only%20scan.
it has a different way to work with the indexes.

just an idea from the top of my head: to regenerate indexes for database tables.
and give it a try.

P.S. another thing, that it might actually start to regenerate index itself, thus gives your an overload and slowdowns.

please let me know how it goes for you, @sim-dav

**Comment by sim-dav** [comment]
Thanks for replying @DzmitryHumianiuk , this got resolved. We did a DB Vacuum ( https://www.postgresql.org/docs/current/sql-vacuum.html ) and that really improved performance

**Comment by sim-dav** [comment]
Thanks for replying @DzmitryHumianiuk , this got resolved. We did a DB Vacuum ( https://www.postgresql.org/docs/current/sql-vacuum.html ) and that really improved performance

**Comment by DzmitryHumianiuk** [comment]
awesome. thanks @sim-dav 
afaik, PG regenerates indexes after `VACUUM`.

thank you for confirmation

**Comment by DzmitryHumianiuk** [comment]
starting 24.2 we support PG16 (tested and verified).

previous versions were tested with PG12 only.
For those of you who still reside on the 5.x versions, and 23.x-24.1, we recommend using PG12.
other PG versions are at your own risk.
