### ISSUE TITLE
Report Portal is logging assumptions as a test failure

### ISSUE THREAD

**Issue by Robert-Murphy** [reportportal/reportportal#1742]
When using the JUnit Assumptions class to determine if the correct conditions have been met to make a test meaningful, any failed assumption is reported as a failure in Report Portal. 
In this scenario my pipeline skips the test as expected and continues to complete successfully, however my test results become inaccurate in Report Portal. 

I have tried using `rp.skipped.issue=false` as I think the test should be marked as skipped after a failed assumption and therefore not be raised to investigate in Report Portal, however it is the TestAbortedException as a result of the failed assumption that is being logged as a failure in Report Portal

```
org.opentest4j.TestAbortedException: Assumption failed: assumption is not true
    at org.junit.jupiter.api.Assumptions.throwTestAbortedException(Assumptions.java:258)
    at org.junit.jupiter.api.Assumptions.assumeTrue(Assumptions.java:115)
    at org.junit.jupiter.api.Assumptions.assumeTrue(Assumptions.java:66)
```

Is this intended functionality or is it possible to have a seperate flag for aborted tests such as `rp.aborted.issue=false` ?

Thank you

**Comment by HardNorth** [comment]
That was already fixed in: https://github.com/reportportal/agent-java-junit5/issues/102
Please use the latest JUnit5 agent version.
