### ISSUE TITLE
Demo instance not working

### ISSUE THREAD

**Issue by ravibabu101143** [reportportal/reportportal#1744]
**Describe the bug**
Demo instance not working. I logged with default user id and pwd and it says signin successfull but still in sign in page

**Expected behavior**
dashboard page should be displayed

**Screenshots**
If applicable

**Versions:**
 Windows 10
chrome and edge browser

**Comment by HardNorth** [comment]
That means something heavy going on on the instance. Some people time-to-time decide that our demo instance is his own instance and start pushing all their project data to it, therefor overloading it. Also they changing credentials for `default` user. In this case just try waiting another day, all the data will be wiped out and you can play with demo free. Also please use "Login with Github" button if `default` password changed.
