### ISSUE TITLE
Most time-consuming test cases widget (TOP-20) is not reporting accurate results

### ISSUE THREAD

**Issue by realqpat** [reportportal/reportportal#1759]
**Describe the bug**
The widget is failing to list some tests that should be in the top-20. In fact the longest test in our suite is not always listed
When we drill down to this specific test we do see the correct run time is reported (6 minutes) but for some reason, it did not make it in the widget
...

**Expected behavior**
Should list the top 20 as expected
...

**Screenshots**
If applicable

**Versions:**

Current version:API Service: 5.5.0;Index Service: 5.0.10;Authorization Service: 5.5.0;Service UI: 5.5.0;

**Comment by alena-babrova** [comment]
Hello @realqpat 

This widget takes into consideration time of test execution.
![image](https://user-images.githubusercontent.com/89584140/198898835-07f405b5-997f-4a7c-a94d-0ce5290eb75d.png)

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/89584140/198898877-338a17d7-e6e6-4174-be09-b85a20cde8af.png">

Could you please provide your examples (screenshots) where you see incorrect time?

**Comment by alena-babrova** [comment]
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
