### ISSUE TITLE
Split test desc and test parameters in RP

### ISSUE THREAD

**Issue by ksuglotova** [reportportal/reportportal#176]
As a user, I would like to store test parameters and test description separately.
For each test I should be able to see the set of parameters:
{parameter name: parameter value}
grouped by pairs.
Simultaneously test parameters and their values should the excluded from the test description.
Test parameters (name+value) may be used to identify test uniqueness.

**Comment by DzmitryHumianiuk** [comment]
done on server side.
**will be available with 3.2**

adapters should be also extended. as separate task
