### ISSUE TITLE
ReportPortal shows incorrect number of test cases while triggering the email

### ISSUE THREAD

**Issue by dsharma8x8** [reportportal/reportportal#1760]
**Incorrect data showing in the email sent by RP **
We are using SMPT in RP for email triggering once the Job has finished. But we have observed that when we run large number of test cases ~380 RP is sending email with incorrect data. 

The total number of test cases - Incorrect
The total pass and failed test cases. - Incorrect

But in the Report Portal launch it is showing the correct information.

**Expected behavior**
It should show the correct data in the email also which is triggering from RP.

**Versions:**
OS - MAC
Browser - Chrome
Version of RP - Current version:API Service: 5.6.3;Jobs Service: 5.6.3;Authorization Service: 5.6.3;Service UI: 5.6.0;

**Comment by alena-babrova** [comment]
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
