### ISSUE TITLE
Container reportportal-rabbitmq-1  Waiting, unable to get RP working

### ISSUE THREAD

**Issue by EugeneGolden** [reportportal/reportportal#1761]
**Describe the bug**
After the running "docker compose -p reportportal up -d --force-recreate" I get the following result:
![Result after docker compose -p reportportal up -d --force-recreate](https://user-images.githubusercontent.com/11062762/175537648-91662cb9-fb26-4746-9023-4682b8f66fb5.png)
When I went to http://localhost:8080/ui/ - I saw just "Loading..."
Ran "docker ps -a" command:
![docker ps -a](https://user-images.githubusercontent.com/11062762/175538068-2c324724-475c-4058-a51c-8ec27f8890b0.png)
Looked through containers' logs:
"docker logs reportportal-rabbitmq-1" - returned empty
You can find logs for reportportal-postgres-1, reportportal-db-scripts-1, reportportal-metrics-gatherer-1, reportportal-ui-1 here:

[docker logs.zip](https://github.com/reportportal/reportportal/files/8976233/docker.logs.zip)

**Expected behavior**
I can see http://localhost:8080/ui/ authentication form and can get reportportal
...

**Screenshots**

**Versions:**
 - OS: Fedora 36
 
 - docker compose version
Docker Compose version v2.6.0

 - docker version
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:51 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

**Comment by EugeneGolden** [comment]
Would like to add more logs 
[logs.zip](https://github.com/reportportal/reportportal/files/9028439/logs.zip)

**Comment by Oleksii-kh89** [comment]
Hi @EugeneGolden 
Could you share your API logs?
