### ISSUE TITLE
Postgres deadlock occur while retrying failing test

### ISSUE THREAD

**Issue by bogdanbrinzei** [reportportal/reportportal#1762]
**Describe the bug**
I have 3 tests ( test 1 and test 3 should not pass ). All 3 tests should be retried 3 times.

I found that retried tests are correctly displayed in RP. Sometimes RP shows 3 incorrect retries (1 FAILED, 2 SKIPPED, 3 FAILED), sometimes only 2 (1 FAILED, 2 SKIPPED) and sometimes retries are not shown.
Launch 1
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/66304850/175953354-7e7f8bb7-e552-46e6-89e4-2b5e941ab265.png">
Launch 2
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/66304850/175953451-385ef1d0-fa27-4ccc-8c81-32eb6ec98e69.png">
Launch 3
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/66304850/175953535-aced5da6-d470-4bbb-918c-ee87c820ea38.png">

Logs from docker container:
```Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected

  Detail: Process 1648 waits for ShareLock on transaction 12587; blocked by process 1634.

Process 1634 waits for ShareLock on transaction 12579; blocked by process 1648.

  Hint: See server log for query details.

  Where: while updating tuple (8,17) in relation "test_item"

SQL statement "UPDATE test_item

    SET retry_of    = retry_parent_id,

        launch_id   = NULL,

        has_retries = FALSE,

        path        = (new_parent_path :: TEXT || '.' || item_id) :: LTREE

    WHERE item_id IN (SELECT item_id

                      FROM test_item

                      WHERE retry_of = retry_id

                      ORDER BY item_id)"

PL/pgSQL function handle_retry(bigint,bigint) line 23 at SQL statement```

I've also tried to change docker file for postgress and I've added `      -c effective_io_concurrency=200` but without any result.

POM.xml dependencies

```
<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>5.1.2</version>
        </dependency>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.5</version>
            <scope>compile</scope>
            <type>jar</type>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>5.1.4</version>
            <exclusions>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

```
**Expected behavior**
Test 1 and Test 3 should have status failed with 3 retried (1st SKIPPED, 2nd SKIPPED, 3rd FAILED)


**Versions:**
 - OS Macos, Browser Chrome
 - Version of RP Current version:API Service: 5.7.1;Authorization Service: 5.7.0;Service UI: 5.7.0;

**Comment by HardNorth** [comment]
@bogdanbrinzei What is your server version?

**Comment by miracle8484** [comment]
Hello, @bogdanbrinzei, what you mentioned before looks like known issue with lock with retires.
We will refactor this part (according to our priority, i can't tell you some dates unfortunately), 
But trying report retries with some delay between it, can possibly help in you case.
