### ISSUE TITLE
Getting blank screen when clicking on Add Integration in Plugins section

### ISSUE THREAD

**Issue by RghvChaurasia** [reportportal/reportportal#1768]
**Describe the bug**
... I'm getting a complete blank screen when clicking on 'Add Integration' in Plugins section while working with Healenium plugin report portal. And hence the report is not getting generated.
Further , on clicking 'back' ( <- ) arrow , present on top left corner in browser, the previous pages are also appearing complete blank. They appear only after reloading the page but the Add Integration pop up does not appear even after reloading.

**Expected behavior**
...I should be able to configure the plugin so that it can be used

**Screenshots**
![add integration](https://user-images.githubusercontent.com/105626260/177129774-25b7aa64-91b0-4175-ad8b-b244936c775e.png)
![blank screen](https://user-images.githubusercontent.com/105626260/177129889-30b3589f-e893-462b-9ba2-6d9f766155fd.png)

Console error (inspect)
![console ](https://user-images.githubusercontent.com/105626260/177134652-74ed44a2-fe3f-492c-901d-4c822ebb10d7.png)

**Versions:**
 - OS, Browser : Windows, Chrome
 - Version of RP [find it under Login form, copy as is] : 5.6.0

**Comment by alena-babrova** [comment]
Hello @RghvChaurasia 

This plugin is developed by a third party and Report Portal team is not responsible for supporting it.
Please, raise the issue in the repository where the plugin resides:
https://github.com/healenium/healenium-plugin-reportportal

Thanks
