### ISSUE TITLE
Sometimes attachments doesn't show up on reportportal UI, when the rest API call have been successful. 

### ISSUE THREAD

**Issue by arunapadhu85** [reportportal/reportportal#1772]
**Describe the bug**
I created a test item with hasStats=False within a suite in a launch. I used the following restapi, to create a log with attachment.
POST ​/v1​/{projectName}​/log

The rest api call returned with  {"responses":[{"id":"dcd54ef1-7170-4032-8639-2962622239c6"}]}

On UI, when I scroll to the particular section, the log is seen but the attachment is not present. 

I have the same API call to add attachment in several other places and I am able to see the log and attachment on reportportal UI. 

**Expected behavior**
Have attachment shown on reportportal UI. 

**Screenshots**

**Versions:**
5.6.0

 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

**Comment by alena-babrova** [comment]
Hello @arunapadhu85 
Is the issue still relevant?
If yes, could you please provide an example of POST request you execute (body)

**Comment by alena-babrova** [comment]
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
