### ISSUE TITLE
services.volumes Additional property minio is not allowed

### ISSUE THREAD

**Issue by Sesha1993** [reportportal/reportportal#1775]
While trying to deploy reportportal in Windows Server 2019 Datacenter, we are running the following command -
docker-compose -p reportportal up-d --force-recreate
Attaching the docker-compose.yml to this post
[docker-compose.zip](https://github.com/docker/docker.github.io/files/9086204/docker-compose.zip)

We are receiving the following error :
services.volumes Additional property minio is not allowed

We have checked via YAML validators and it seems like a valid yml file.
Can someone please check this issue?

**Comment by IvanKustau** [comment]
Volumes property should be on the same level in docker compose file as services property
Like this:
version: '2.4'
services:

  gateway:
  ...
volumes:

**Comment by MaryiaRymarchyk** [comment]
Hi @Sesha1993 , do you have updates here? 
Did you manage to deploy reportportal successfully ?

**Comment by MaryiaRymarchyk** [comment]
@Sesha1993  As we haven't received a reply from you, we'll close the issue for now.
If  the issue still relevant, just get in touch.

**Comment by nitairoy** [comment]
> 

Thanks. I managed to solve my issues while searching. [Docker Compose "volumes Additional property is not allowed"]
