### ISSUE TITLE
Have the availability to add default recipient on the notification 

### ISSUE THREAD

**Issue by kshammout** [reportportal/reportportal#1777]
**Is your feature request related to a problem? Please describe.**
Recently we faced an issue that we are not able to modify any of the notification rules and add any new recipients, in the end we find this is due to one of the notifications having a notification rule with an empty recipients list.
after modify this notification recipients list the things working fine again.

****Describe the solution you'd like**
If there is a way to add a default recipients to the notifications to avoid such cases 
...

Note: We are using Build: 5.7.0

**Comment by Kozovskaya** [comment]
Hello @kshammout
Yes, it a known issue for us. It's really so, if you have at least one rule where the recipient list is empty, all other rules can't be updated. We have already fixed it and it will be released this year - 23.3 version.

**Comment by Kozovskaya** [comment]
Hello @kshammout 
I'm pleased to let you know that the fix is already released!
https://github.com/reportportal/reportportal/releases/tag/v24.1

**Comment by kshammout** [comment]
@Kozovskaya thank you
