### ISSUE TITLE
Launch not finish issue

### ISSUE THREAD

**Issue by AlexBraslavskyi** [reportportal/reportportal#1780]
Have interrupted launches, use @reportportal/client-javascript": "^5.0.6", on v5.6.2 
my after block: 

  after(async function () {
      await rpClient.getPromiseFinishAllItems(launchObj.tempId);
      await rpClient.finishLaunch(launchObj.tempId, {
        endTime: await rpClient.helpers.now()
      });
    if (await this.app && await this.app.isRunning()) {
     stopApp();
    }
  });

**Comment by alena-babrova** [comment]
Hi @AlexBraslavskyi,
Is the issue still relevant? Have you managed to resolve it?

**Comment by alena-babrova** [comment]
Dear @AlexBraslavskyi,
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
