### ISSUE TITLE
metrics-gatherer:1.1.20  container unhelathy

### ISSUE THREAD

**Issue by srikar6118686** [reportportal/reportportal#1789]
Hi Team,

metrics-gatherer:1.1.20  container showing un healthy we are thinking that due to AMQP_VIRTUAL_HOST: analyzer it is showing unhelathy.

RP Version : 5.7.2

**Comment by srikar6118686** [comment]
Hi @HardNorth, Please help us on above ask.

**Comment by srikar6118686** [comment]
Hi @miracle8484, Please help us on how to clear the above mentioned bug

**Comment by srikar6118686** [comment]
Hi Team, We are facing very serious issue. Please help us here

**Comment by HardNorth** [comment]
@srikar6118686 You can turn this container off, it's our monitoring service, it doesn't contain any business logic.

**Comment by srikar6118686** [comment]
Hi @HardNorth,

Describe the bug
With the Latest Version of the Report portal 5.7.2 we observed minio size utilization got doubled previous utilization size was 480gb , but current size is 980gb

Expected behavior
Utilization of minio to be increased gradually and proper cleanup to be done

Please help us with delete script

**Comment by Komorebi-E** [comment]
I also have the `metrics-gatherer:1.1.20` but with this error from the logs.

Checking the repo for the container build, there is already an issue logged for it:
https://github.com/reportportal/service-metrics-gatherer/issues/53

```log
Tue Aug  9 10:58:52 2022 - *** uWSGI listen queue of socket ":3031" (fd: 6) full !!! (35753024/1) ***
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    from flask import Flask, Response
  File "/venv/lib/python3.7/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/venv/lib/python3.7/site-packages/jinja2/__init__.py)
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
```

**Comment by HardNorth** [comment]
@srikar6118686 please do not spam with irrelevant messages.
@Komorebi-E Pease apply the very same recommendation as above:
`You can turn this container off, it's our monitoring service, it doesn't contain any business logic.`
