### ISSUE TITLE
Not able to find Report Portal Service API executable JAR

### ISSUE THREAD

**Issue by satishkumar9549** [reportportal/reportportal#1791]
We are upgrading Linux version of Report Portal to 5.7.2 and tried downloading the API file from below URL:
```curl -L $MAVEN_REPO/service-api/$API_VERSION/service-api-$API_VERSION-exec.jar -o service-api.jar```but there is no executable jar file available in the url: https://repo1.maven.org/maven2/com/epam/reportportal/service-api/5.7.2/

Can you please provide this file so that we can upgrade report portal to latest version.

**Comment by DzmitryHumianiuk** [comment]
@satishkumar9549 please stop generating equals issues in different repositories.

if you are looking for a same-minute support on top of the open source solution, we are ready to propose you a paid support.

**Comment by satishkumar9549** [comment]
Sure, I thought this issue needs to be submitted in service-API repository.

There is no executable jar for Service-API  versions above 5.3.5, is there any reason for this?

**Comment by miracle8484** [comment]
@satishkumar9549, thx for reporting, Issue is confirmed, will be fixed in order of priorities.

**Comment by satishkumar9549** [comment]
Can you please provide timeline when this issue will be completed?

**Comment by DzmitryHumianiuk** [comment]
@satishkumar9549 it's already there for 5.7.4
https://repo1.maven.org/maven2/com/epam/reportportal/service-api/5.7.4/
<img width="639" alt="image" src="https://user-images.githubusercontent.com/11332788/221663631-4ee7325f-b3e8-4c90-8589-fc818390da0a.png">

**Comment by satishkumar9549** [comment]
We still don't see executable jars on https://repo1.maven.org/maven2/com/epam/reportportal/service-authorization/5.7.4/?
