### ISSUE TITLE
Can't start app on Mac M1 (Infinity Loading...)

### ISSUE THREAD

**Issue by mparkhomenko** [reportportal/reportportal#1795]
**Describe the bug**
I just start RP in Docker and when I open localhost:8080 I see Loading... and error in console

**Expected behavior**
I just start RP in Docker and when I open localhost:8080 I see Loading... and error in console

**Screenshots**
<img width="1680" alt="Снимок экрана 2022-08-01 в 13 55 34" src="https://user-images.githubusercontent.com/47244665/182123572-68f6cf23-f4a0-4eaa-b06e-744ec0a2f187.png">

**Versions:**
 - OS - Mac OS, Browser Chrome
 - Version of RP [find it under Login form, copy as is]

**Comment by hanikhan** [comment]
@mparkhomenko Have you tried increasing memory assigned to docker and running this again?

**Comment by DzmitryHumianiuk** [comment]
please follow up M1/ARM related discussion in https://github.com/reportportal/reportportal/issues/1815

**Comment by DzmitryHumianiuk** [comment]
All ReportPortal images now support multiple platforms.: linux/amd64.
