### ISSUE TITLE
How to clean up Minio Data in ReportPortal if it uses a lot of storage

### ISSUE THREAD

**Issue by ReddyNitheeesh** [reportportal/reportportal#1796]
RP Version: 5.7.2

Current Pattern to clear RP attachments and other:

```
  RP_ENVIRONMENT_VARIABLE_CLEAN_ATTACHMENT_CRON: 0 0 */24 * * *
  RP_ENVIRONMENT_VARIABLE_CLEAN_LOG_CRON: 0 0 */24 * * *
  RP_ENVIRONMENT_VARIABLE_CLEAN_LAUNCH_CRON: 0 0 */24 * * *
  RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CRON: 0 0 */24 * * *
  RP_ENVIRONMENT_VARIABLE_STORAGE_PROJECT_CRON: 0 */5 * * * *
```

We see daily utilization is up to 10GB, can you please help us by providing a script for explicit data clean of minio , or else can we go ahead and manually delete from minio, does it affect existing report portal instance ??

**Comment by ReddyNitheeesh** [comment]
@Gl-Canon  @evjlobanova @HardNorth can you please help us on this ??

**Comment by Oleksii-kh89** [comment]
Hi @ReddyNitheeesh 

Yes, you can clean attachments manually in the folders. Please, don`t delete folders
If you don`t have MinIO Web UI, go through these steps:
1.	Go to MinIO volueme.
2.	Choose the project which you want to clean.
3.     Check the projects in the data directory: `ls -l /data`

- The output should be like the following:
![image](https://user-images.githubusercontent.com/82764347/204292300-f7fc2bbc-cdd3-4f9e-94fb-86c686f6c668.png)

- Choose the project which you want to clean `ls -l /data/prj-100647`

5.	Delete attachments from the necessary folder `rm -R /data/prj-100647/2022-8/*`

**Comment by Oleksii-kh89** [comment]
Closed by time
