### ISSUE TITLE
Requesting support for Amazon Load Balancer (ALB) Controller

### ISSUE THREAD

**Issue by gnazgit** [reportportal/reportportal#1797]
**Support for Amazon Load Balancer (ALB) Controller**

Right now, NGINX support and example is provided. But considering performance and native TLS certificate from AWS, ALB looks better.

The current issue with ALB controller is, they don't provide support for rewrite-target and a complex regex. Because of this, even if we bring up the Login page with ALB, rest of the redirection is not working.

Please consider supporting ALB controller.

@HardNorth

**Comment by gnazgit** [comment]
ALB annotations used:

> annotations:    
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/actions.ssl-redirect: "{\"type\": \"redirect\", \"redirectConfig\": { \"protocol\": \"HTTPS\", \"port\": \"443\", \"statusCode\": \"HTTP_301\"}}"
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: "xxxxxxxxxxxxxxxxxxxxxx"
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\":80,\"HTTPS\":443}]"
    alb.ingress.kubernetes.io/scheme: "internal"
    alb.ingress.kubernetes.io/subnets: "subnet-xxxxxxx,subnet-xxxxxxx"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/tags: "xxxxxx: yyyyyyyy"
    alb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=300"

ALB ingress file:

>   - host: {{ $host }}
    http:
      paths:
      - path: /ui/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $fullName }}-ui
            port:
              number: 8080
      - path: /uat/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $fullName }}-uat
            port:
              number: 9999
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $fullName }}-api
            port:
              number: 8585
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $fullName }}-index
            port:
              number: 8080

**Comment by Idosegal** [comment]
Any update on this?

**Comment by gnazgit** [comment]
Moved this issue to https://github.com/reportportal/kubernetes/issues/274
