### ISSUE TITLE
Automatically Auto analysis is not working every time i need to start auto-analyzer manually

### ISSUE THREAD

**Issue by monika-framework** [reportportal/reportportal#1798]
Automatically Auto analysis is not working every time i need to start auto-analyzer manually.

I have done the setup. manual AA feature is working not properly and sometimes it miss some already defined bugs. 
But my main concern is once launch is completed it is not recognizing defects automatically  i have to start manually.

**Comment by alena-babrova** [comment]
Hello @monika-framework 

Is the issue still relevant?
Please, check if auto analysis option is enabled.
![image](https://user-images.githubusercontent.com/89584140/200607305-f441f1b3-163d-4bfc-bd35-cf7a9eeaa419.png)

**Comment by alena-babrova** [comment]
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
