### ISSUE TITLE
[WIDGETS] Launch execution statisics: get the graph up

### ISSUE THREAD

**Issue by ksuglotova** [reportportal/reportportal#180]
Received from Alisa Guseva

It would be more informative to change the graph and legend on a  Launch execution and issue statistic widget. I.e. get the graph on top and legend to the down on a widget area.
![launch execution and issue statistics](https://user-images.githubusercontent.com/29129137/28123834-000a835a-66f0-11e7-9bd3-1b840bbcf8dc.JPG)

**Comment by evjlobanova** [comment]
There was implemented  a new widget design, and a legend has a scroll now. So this issue has been resolved.
