### ISSUE TITLE
Can't install latest Jira plug-in (5.7.0) onto Report Portal build 5.6.0

### ISSUE THREAD

**Issue by cheesehead72** [reportportal/reportportal#1802]
I am trying to install the latest Jira plug in onto our Report Portal (build 5.6.0) and am getting the following error:
![image](https://user-images.githubusercontent.com/93950244/182951465-08fac85a-a061-4aec-b6d3-fafdc4694a57.png)

Any ideas how to get past this issue and get the latest Jira plug in installed? Thanks in advance

**Comment by HardNorth** [comment]
@cheesehead72 It is not supposed to be backward compatible.
