### ISSUE TITLE
Email server Integration - Password Error

### ISSUE THREAD

**Issue by gryan322a** [reportportal/reportportal#1804]
We are getting the following error on Report Portal 5.5.0 whenever trying to configure the Email Server using with authorization On.

[java.security.spec.InvalidKeySpecException: Password is not ASCII]

![email](https://user-images.githubusercontent.com/54869482/183126952-6455d385-0886-499d-bbb5-457c22927aa1.JPG)

**Comment by gryan322a** [comment]
Upgraded to Report Portal 5.7.0, still getting same error.  Doesn't matter if smtp is amazon, or sendgrid, or gmail.

**Comment by alena-babrova** [comment]
Hello @gryan322a 

Is the issue still relevant?
Maybe you have any non ASCII characters in your password?

**Comment by gryan322a** [comment]
Yes, we still get this error.

There are no non ASCII characters in our password.

**Comment by alena-babrova** [comment]
As I see in your screenshot you've managed to create Email integration sometime before (connected status). What have changed with your account/credentials since then?
I'm just trying to get the full picture of your scenario.

**Comment by gryan322a** [comment]
The connected status was from when Authorization was turned off.  Which doesn't work because the smtp servers need authorization.

Removing the connection and recreating with authorization on gives the same error.

**Comment by alena-babrova** [comment]
Have you tried different Email accounts and servers? Do you experience the same error even though different accounts and passwords used?

**Comment by LittleSixfie** [comment]
I have the same problem, the email server isn't capable of login with aws  credentials

**Comment by alena-babrova** [comment]
Hello!

We have registered a task regarding this issue in our backlog.
Once it's resolved, we will notify you here.
Thanks!

**Comment by gryan322a** [comment]
Our RP server is also in AWS.

We have tried sendmail and gmail smtp servers in addition to the amazonaws smtp server and get the same error when configuring with authorization on.

**Comment by IvanKustau** [comment]
@gryan322a @LittleSixfie Can you please share with us content of secret-integration-salt file that should lay in keystore bucket in MinIO

**Comment by DzmitryHumianiuk** [comment]
@gryan322a @LittleSixfie Can you please share with us content of secret-integration-salt file that should lay in keystore bucket in MinIO?

**Comment by gryan322a** [comment]
I am no longer with this company, so I can't answer your question about the
Report Portal installation.

Thanks,
Gregory Ryan
