### ISSUE TITLE
start time while creating a launch using API

### ISSUE THREAD

**Issue by sathishkumaranbu** [reportportal/reportportal#1805]
HI team,

I would like to know what is the format for passing start time in the payload of create launch API,
it would be a great help if you can send me the sample for the same.

Thanks and Regards,
Sathish

**Comment by HardNorth** [comment]
Just milliseconds from the Unix epoch.

**Comment by sathishkumaranbu** [comment]
@HardNorth ,
Thanks for the respose,
it would be helpful if you tell me how to get the Unix epoch in python

**Comment by HardNorth** [comment]
@sathishkumaranbu we have example in our Python client: https://github.com/reportportal/client-Python/blob/develop/reportportal_client/helpers.py#L145

PS: We are not free Python school, further questions of such kind will be ignored.
