### ISSUE TITLE
passing IST date format to the Launch

### ISSUE THREAD

**Issue by sathishkumaranbu** [reportportal/reportportal#1806]
Hi Team,

wanted to check how to pass the Current time as the start time for launch while creating launch using API,
if we cannot give the date format, how to get the current time's for the Unix epoch

Thanks and Regards,
Sathish

**Comment by nvborisenko** [comment]
Example of conveting date time in .NET/C# https://github.com/reportportal/client-net/blob/develop/src/ReportPortal.Client/Converters/DateTimeConverter.cs

**Comment by HardNorth** [comment]
@sathishkumaranbu we have example in our Python client: https://github.com/reportportal/client-Python/blob/develop/reportportal_client/helpers.py#L145

PS: We are not free Python school, further questions of such kind will be ignored.
