### ISSUE TITLE
Time based data

### ISSUE THREAD

**Issue by mchundi** [reportportal/reportportal#1807]
Does Reportportal support time based data analysis? for instance, passing rate for the last 7 days OR top 20 flaky tests in the last month?

**Comment by VolhaKarenko** [comment]
Hi @mchundi ,
The widgets that require a filter can be created based on the time period, as you can create a filter with the 'Start time' condition and specify the start time of the needed launches. 
Regarding the 'Flaky test cases' widget, which is based on the launch name, there is no such possibility, as it shows the TOP-20 test cases from the latest launches only, based on the launch name.
Could you please share your case, so we could better understand the idea of your request?

**Comment by MaryiaRymarchyk** [comment]
Hi @mchundi, 
Did the provided information help you solve the problem?
Do you have any updates on the ticket?

**Comment by mchundi** [comment]
Hi Maryia,
Yes this helped me create the required.
We can close this ticket.

Regards,
Manjusha
