### ISSUE TITLE
Question: Is it possible to create a Global Default Dashboard for all Projects?

### ISSUE THREAD

**Issue by brabenetz** [reportportal/reportportal#1809]
My alternative planned Workaround would be:
I create a Dashboard in a hidden Project for the superadmin.
And write a small utility which do the following:
Via Rest-API I copy the dashboard into all other projects:
 - GET ​/v1​/user => get all assignedProjects
 - GET /v1/DASHBOARD_TEMPLATE/dashboard  => read dashboard, set shared=true
 - for each Project:
	- GET /v1/{projectName}/dashboard => check if dashboard with same name already exist
	- if exist: PUT /v1/{projectName}/dashboard//v1/{projectName}/dashboard/{dashboardId}
	- else: POST /v1/{projectName}/dashboard

**Comment by VeranikaRymzha** [comment]
Hello @brabenetz,

Thank you for your request!
At the moment, ReportPortal doesn't have such functionality. 
However, we plan it to be developed as a separate plugin and to be released together with ReportPortal version 5.9. 

Regarding the workaround you have, unfortunately, we can't guarantee that ReportPortal dashboards and widgets will work as expected. But if its covers your needs - that's great!

Have a nice end of the week! 
And just let us know if there are any other questions.

**Comment by brabenetz** [comment]
Thanks,

It was a little more complex (calling the rest-api for filters, widgets and finally the dashboards).
But it works now: Our template-dashboard will now be copied into all other projects.

**Comment by brabenetz** [comment]
It is complicated, but it helps to use the object-library for the Rest-API:

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>commons-model</artifactId>
            <version>5.7.0</version>
        </dependency>

1 Get Template-Dashboard Infos Dashboard, Widgets and Filter:
- GET /v1/{projectName}/dashboard
- if widget isSupportMultilevelStructure() ( https://github.com/reportportal/service-ui/blob/cebf31022be50b0e0c8e56959461a8e943a2a3d2/app/src/components/widgets/index.js#L80-L93 )
  - GET /v1/{projectName}/widget/multilevel/{widgetId}
- otherwise:
  - GET /v1/{projectName}/widget/{widgetId}
- GET /v1/{projectName}/filter

2a Update Dashboard in target Project (if exists):
- DELETE /v1/{projectName}/dashboard/{dashboardId}/{widgetId}  # remove existing Widgets
- PUT /v1/{projectName}/dashboard/{dashboardId}

2b Or Create Dashboard in target Project:
- POST /v1/{projectName}/dashboard

3a Update Filter (if exists):
- PUT /v1/{projectName}/filter/{filterId}

3b Or Create Filter:
- POST /v1/{projectName}/filter

4 Create Widgets and add it to the new Dashboard:
- POST /v1/{projectName}/widget
- PUT /v1/{projectName}/dashboard/{dashboardId}/add
