### ISSUE TITLE
Weird Question: Is there a way to create a Filter without Filter, because Widgets need a filter to select?

### ISSUE THREAD

**Issue by brabenetz** [reportportal/reportportal#1810]
My Current Workaround: I create a Filter "All" with Filter: LaunchName != "DOSNT-CARE"

**Comment by alena-babrova** [comment]
Hello @brabenetz 

Unfortunately, there is no way to use widgets without a filter.
However, your workaround is totally applicable in current situations.
I would also suggest to use the following filter, in case you need all data from the system:
![image](https://user-images.githubusercontent.com/89584140/194898176-22e49f70-b276-4fb0-bb5e-b60eadbbcfce.png)

**Comment by alena-babrova** [comment]
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Comment by brabenetz** [comment]
Thanks, seems that I stick with the workaround for now ;(
