### ISSUE TITLE
Assign roles in projects automatically based on info from the auth provider

### ISSUE THREAD

**Issue by skorobogatydmitry** [reportportal/reportportal#1812]
SAML auth is configured for the ReportPortal. Users can login, but, by default, can not access "shared" projects.
So we had to add every new user to every project, despite that SAML provider (Okta) maintains membership and can push this info to ReportPortal.

FR is to assign project roles automatically based on the user's attribute, filled by SAML provider.

The way above is a shortcut for proper RBAC. I just assumed that it will be easier to implement.

**Comment by Vikas1712** [comment]
Is this feature implemented. Even I am encountering this issue . I am able to setup azure SAML with Report portal. But I get unauthorized page error 403

**Comment by raikbitters** [comment]
@skorobogatydmitry @Vikas1712 hello. The existing implementation of SAML in ReportPortal covers only authentication cases, not authorization cases. We plan to implement SCIM to synchronize users' roles and projects between ReportPortal and Identity providers.

**Comment by skorobogatydmitry** [comment]
@raikbitters , could you leave some link so whoever comes across the thread can check feature's status ?

**Comment by raikbitters** [comment]
@skorobogatydmitry  hi. We've already implemented it. You can find out more here: https://reportportal.io/docs/external-integrations/UserProvisioning/Scim/
