### ISSUE TITLE
Report Portal Linux version connecting to a new Postgress Database facing issues

### ISSUE THREAD

**Issue by satishkumar9549** [reportportal/reportportal#1814]
Report Portal Linux version connecting to a new Postgress Database facing issues:
I have tried connecting our newly created postgress db in a different server but after everything is completed, we couldn't access login application as it is still connected to older DB even after updating the below commands with newly created DB

export RP_POSTGRES_USER=*********
export RP_POSTGRES_PASSWORD=*****

RP_AMQP_HOST=localhost RP_AMQP_APIUSER=$RP_RABBITMQ_USER RP_AMQP_APIPASS=$RP_RABBITMQ_PASSWORD RP_AMQP_USER=$RP_RABBITMQ_USER RP_AMQP_PASS=$RP_RABBITMQ_PASSWORD RP_DB_USER=$RP_POSTGRES_USER RP_DB_PASS=$RP_POSTGRES_PASSWORD RP_DB_HOST=************ /opt/jdk/java/bin/java $SERVICE_API_JAVA_OPTS -jar service-api.jar 2>&1 &

RP_DB_HOST=********** RP_DB_USER=$RP_POSTGRES_USER RP_DB_PASS=$RP_POSTGRES_PASSWORD /opt/jdk/java/bin/java $SERVICE_UAT_JAVA_OPTS -jar service-uat.jar 2>&1 &

**Comment by irynakozak2** [comment]
Hi @satishkumar9549!
Could you please specify the service versions and the ReportPortal version?

The currently supported versions are defined here:
https://github.com/reportportal/linux-installation
cc @Gl-Canon
