### ISSUE TITLE
Please provide images built for ARM64 (and Apple M1 chip)

### ISSUE THREAD

**Issue by 375gnu** [reportportal/reportportal#1815]
**Describe the solution you'd like**
ARM64 CPU architecture is facing increasing popularity and virtual machines based on this architecture are much cheaper then their AMD64 counterparts.
Dependencies for Reportportal  like ES, PgSQL or minio already provide ARM64 images. Only RP itself is built for AMD64 only despite the fact that underlying technologies (java, python, js) are working fine with ARM64.

**Comment by DzmitryHumianiuk** [comment]
@375gnu are there any trusted sources with articles/surveys/statistics in regards to the growth of ARM64 usage as a VM envs?
I legitimately believe that demand is growing, but just want to know are we behind the "wave", on the edge, or it's something upcoming in next 3-6 months?

**Comment by 375gnu** [comment]
I can't provide such sources, but I see that more and more software vendors provide official support for arm64 architecture. The same for cloud providers: AWS now has 2 generations of arm64-based instances, even compute instances. Azure added arm64 instances support to their managed k8s solution. And don't forget about users of modern Apple laptops.

**Comment by fenchu** [comment]
The Rasberry Pis using the BCM27XX processor (Zero2, pi3, pi4) are ARM64. So it means you can run it there.

As my personal server I have a RPI4 running debian with mediawiki(php), gogs(go), jupyter(python) and some personal webpages and apis in python.

I have an external usb3 ssd connected.

Very little power use (around 35W included ssd) and completely silent (Have a large passive heatsink) and small makes a perfect home server.

**Comment by DzmitryHumianiuk** [comment]
> The Rasberry Pis using the BCM27XX processor (Zero2, pi3, pi4) are ARM64. So it means you can run it there.
> As my personal server I have a RPI4 running debian with mediawiki(php), gogs(go), jupyter(python) and some personal webpages and apis in python.

@fenchu hah. cool, but it doesn't seem to be a case for the ReportPortal installation.
The reason is simple:
- you most likely need to aggregate a numerous amount of testing results in near real-time and utilize ML power to categorize fails in case if you have a larger automation set. Then you most likely can set it up in the cloud or bare-metal.

i'm not sure how many companies will be ready to run and rely on the app, which is spin on Raspberry PI )

**Comment by DzmitryHumianiuk** [comment]
Consolide Apple Silicon (M1-Mx)/ ARM related issues:
- https://github.com/reportportal/reportportal/issues/1815
- https://github.com/reportportal/reportportal/issues/1795
- https://github.com/reportportal/reportportal/issues/957
- https://github.com/reportportal/reportportal/issues/1590

**Comment by DzmitryHumianiuk** [comment]
**Latest update:**

Both for ARM64 and Apple Silicon (M1-Mx) ReportPortal images are missing compiled version of jar files and dependencies in ARM compatible form.

At the moment:
- Java microservices extended with ARM builds
- ML related (in progress)

ETA ~~1-2 months.

**Comment by orgads** [comment]
Workaround until there are native images: https://enlear.academy/run-amd64-docker-images-on-an-arm-computer-208929004510

```
docker run --privileged --rm tonistiigi/binfmt --install amd64
```

Add `platform: linux/amd64` for each reportportal image in docker-compose.

**Comment by bogdanganzha** [comment]
@DzmitryHumianiuk hi there. Any updates regarding M1? Current "Deploy with Docker on Linux/Mac" guide doesn't work for M1 chip.
https://reportportal.io/docs/installation-steps/DeployWithDockerOnLinuxMac/

**Comment by DzmitryHumianiuk** [comment]
@bogdanganzha it's underway.
All services are being updated for compatibility with ARM (M1). 
We're also creating a separate Docker file for the ARM build in the 2023.2 update. 

Stay tuned!

**Comment by DzmitryHumianiuk** [comment]
All ReportPortal images now support multiple platforms.: linux/amd64.
