### ISSUE TITLE
Test rerun is interrupting multithreaded running launch

### ISSUE THREAD

**Issue by MichalZemanSiemens** [reportportal/reportportal#1817]
I am running a lot of tests in parallel and they are taking quite a lot of time. Using the API to start launch and then the test machines are using the launch uuid to report results to this run. 

Problem is when someone start a test rerun when the other tests are still running. The rerun is executed, properly sorted and launch is marked as launch with rerun, but then the launch is finished when the rerun finishes and the categories for tests have "status:interrupted"

The other threads are still running and adding those test results to the launch, but it appears as finished. The test rerun should not stop the launch if there are other tests running in the launch.

Used versions:
RP 5.7.0
ReportPortal.NUnit 4.1.0
ReportPortal.Shared 3.1.3
ReportPortal.Log4Net 2.0.0

**Comment by Aleh-Yanushkevich** [comment]
Hello @MichalZemanSiemens. If to be honest, I am not sure that it is a bug, because rerun functionality assumes, that all you tests have already finished and only after that you start rerun of your failed tests. As I understood you correctly, someone starts rerun of the launch, which has not been finished yet. If would be more correct, if on your side will be implemented synchronization. when rerun should be started only when launch has been finished.

**Comment by MichalZemanSiemens** [comment]
The tests we are running are very time consuming, it may take days to finish the last tests. Usually 10+ test agents starts in parallel and produce a lot of results over night and the testers want to evaluate as much as possible in the morning and letting just few tests finish over the next day (on like 1-2 agents). 
I would assume that the rerun functionality behaves exactly same as normal run - since it is just a run with pairing of the tests to other tests. Normal run also does not finish the launch when the tests are finished.

**Comment by Aleh-Yanushkevich** [comment]
@evjlobanova could you please clarify is it bug or expected behaviour?
@MichalZemanSiemens I'll check if it possible to customize it on agent level.

**Comment by alena-babrova** [comment]
Hello @MichalZemanSiemens,

As @Aleh-Yanushkevich mentioned above, the rerun action is supposed to be used only when the initial run of the launch is completed. It is not designed to rerun some part of launch while the launch is still in progress. So it is as designed and the behaviour seem to be expected - items that were not finished when starting rerun receive status "interrupted"

So the rerun functionality is useful for finished launches only.

P.S. @Aleh-Yanushkevich Thanks for contribution!
