### ISSUE TITLE
Junit test framework integration

### ISSUE THREAD

**Issue by dkozlov** [reportportal/reportportal#182]
Hi,

Is there any way to integrate Junit reports with ReportPortal ?

**Comment by avarabyeu** [comment]
@dkozlov yes. we are about to release 'import' feature that supports junit XML reports. 
BTW, which framework do you use? If it's JUnit, why don't you use [junit agent](https://github.com/reportportal/agent-java-junit)?

**Comment by dkozlov** [comment]
> BTW, which framework do you use?

I use several frameworks: JUnit, Cucumber. 

> If it's JUnit, why don't you use junit agent?

Because it is not trivial to find any information about JUnit agent in http://reportportal.io/#documentation and https://github.com/search?q=org%3Areportportal+example

**Comment by dkozlov** [comment]
According to reportportal.slack.com (https://reportportal-slack-auto.herokuapp.com/): 
If Maven used - then listener could be included in maven-surefire-plugin configuration in pom.xml.
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-surefire-plugin</artifactId>
   <version>2.15</version>
   <configuration>
      <properties>
         <property>
            <name>listener</name>
            <value>com.epam.reportportal.junit.ReportPortalListener</value>
         </property>
      </properties>
   </configuration>
</plugin>

Only 3 ways available:
1. core.addListener(new ReportPortalListener())
2. maven-surefire-plugin for JUnit
3. annotation @RunWith(com.epam.reportportal.junit.CustomJUnitRunner.class)

**Comment by avarabyeu** [comment]
@dkozlov Thanks for the comprehensive response. I believe, issue can be closed

**Comment by talmoshe** [comment]
Hi, can anyone help me with the below error?

09:43:40 1157 [main] ERROR com.epam.reportportal.junit.ParallelRunningHandler - Unable start test suite: 'null'
09:43:40 com.epam.reportportal.exception.ReportPortalClientException: Report Portal returned error
09:43:40 Status code: 400
09:43:40 Status message: Bad Request
09:43:40 Error Message: Incorrect Request. [Field 'name' shouldn't be null.] 
09:43:40 Error Type: INCORRECT_REQUEST

It was solved by switching to @RunWith(com.epam.reportportal.junit.CustomJUnitRunner.class)
But not I'm getting error - No runnable methods
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   null
[ERROR]   simpleTestSuite1.initializationError »  No runnable methods
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
