### ISSUE TITLE
common-bom not published to the maven central

### ISSUE THREAD

**Issue by brabenetz** [reportportal/reportportal#1821]
**Describe the bug**
the current common-bom 5.7.0 is not published to the maven central:
https://mvnrepository.com/artifact/com.epam.reportportal/commons-bom
last published release was 5.3.5

Other published libraries depend on this, like "common-dao":
https://repo1.maven.org/maven2/com/epam/reportportal/commons-dao/5.7.0/commons-dao-5.7.0.pom

**Expected behavior**
all transitive dependencies of "common-dao" can be resolved from the maven central

**Comment by miracle8484** [comment]
Thx you for you issue, publishing has been fixed. 
Last 3 boms have been added to maven repository
https://mvnrepository.com/artifact/com.epam.reportportal/commons-bom/5.7.3
https://mvnrepository.com/artifact/com.epam.reportportal/commons-bom/5.7.2
https://mvnrepository.com/artifact/com.epam.reportportal/commons-bom/5.7.1
