### ISSUE TITLE
Report Portal io - Integration with Jira Server - error occurred while connecting to server : impossible interact with integration. Connection refused

### ISSUE THREAD

**Issue by JayashreePhataangare** [reportportal/reportportal#1822]
I am trying to integrate **Jira server** with Report Portal io.  After logged in with admin credentials to Report Portal in administrative - plugins panel - I had uploaded "**plugin-bts-jira-5.1.0-all.jar**" to make plugin available. 

Now I am trying to create Integration with correct BTS Username and BTS Password - _but_ getting error as "**an error occurred while connecting to server : impossible interact with integration. Connection refused**".

**Expected behavior**
...  Integration should get created successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/111840909/186074169-b4563964-52b4-4eed-8b88-3c853472b223.png)

Also for more reference adding company's jira server about screenshot - https://jira.[companyName].com/

![image](https://user-images.githubusercontent.com/111840909/186114103-1d365bc6-c60a-4f9b-9d09-a8fa426253fe.png)

409 - network tab screenshot
" 
![image](https://user-images.githubusercontent.com/111840909/186083704-3248a100-97e9-438f-b707-bd66f0240344.png)

I had tried - copying API Token from "https://id.atlassian.com/manage-profile/security/api-tokens", still getting same error. 

**Versions:**
 - OS - windows 10 Enterprise , Browser - Edge
 - Version of RP - as in screenshot below
![image](https://user-images.githubusercontent.com/111840909/186113673-c7336a5e-8487-412e-bcb5-cd6f56ebfca0.png)

**Comment by JayashreePhataangare** [comment]
Any updates on this? Can anybody please look into this issue?

**Comment by VolhaKarenko** [comment]
Hi @JayashreePhataangare, Jira plugin version 5.1.0 is not compatible with Report Portal version 5.6.3.
Jira plugin version 5.4 should be used instead: https://github.com/reportportal/plugin-bts-jira/packages/895590?version=5.4.0 
However, I would recommend updating to the latest version (5.7.2 for now) and try with Jira plugin version 5.7 https://github.com/reportportal/plugin-bts-jira/packages/895590?version=5.7.0
