### ISSUE TITLE
Login Issue for UI dashboard

### ISSUE THREAD

**Issue by sharathhatter1** [reportportal/reportportal#1824]
After adding Username and password as "superadmin/erebus", getting success message as signed in successfully. But later again it asks for the localhost username and password.
![Reportportal unauthorized - Copy](https://user-images.githubusercontent.com/55090052/186596967-695b1bf0-f49f-4314-9d0b-6f5e7752d195.png)
![Reportportal unauthorized](https://user-images.githubusercontent.com/55090052/186596974-e978ae26-0147-4c0e-9949-be99e45b7d5e.png)

![ReportPortal](https://user-images.githubusercontent.com/55090052/186597338-310c9ebf-1693-4fb1-b3d9-fa98833cd70a.png)

But after sometime when I remove the #login from the keyboard, it navigates to dashboard. 
Can anyone let me know what is the issue here

**Comment by axxyhtrx** [comment]
check:
1) containers status
2) size of available ram
3) disk space

**Comment by DzmitryHumianiuk** [comment]
same as here: https://github.com/reportportal/reportportal/issues/1836

https://reportportal.io/installation

Allocate at least 5+Gb of RAM for Docker via Docker Settings > Advanced
We strongly recommend to deploy in Linux based environment

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/11332788/190030848-dbc0e79f-54c4-4970-a4bf-c0f17f22c4e9.png">
