### ISSUE TITLE
Minio does not clean up the data correctly

### ISSUE THREAD

**Issue by ezienecker** [reportportal/reportportal#1828]
While running the Report Portal, the disk has filled up. After some analysis I noticed that Minio has the following folder structure:

```
2022-5
2022-6
2022-7
2022-8
...
```

I assume that this corresponds to the following pattern: <year>-<month>. In the portal itself it is set to keep the jobs only 7 days. 

What is the reason that the folders in Minio are not cleaned up? There are still images in the folders. Is there a problem with the clean storage job execution? 

**Is there a way to start this job execution manually?** What happens if I delete the folders 2022-5, 2022-6, 2022-7 manually? Will there be collisions with possible postgresql entries? Unfortunately we are running out of memory on the system and need to act.

It's maybe related to the following issues:
* https://github.com/reportportal/reportportal/issues/1796
* https://github.com/reportportal/reportportal/issues/1792

**Expected behavior**
I would expect the Report Portal to clean up/delete the screenshots in Minio.

**Versions:**
 - RP: 5.7.0

**Comment by DzmitryHumianiuk** [comment]
@ezienecker files should be deleted from there, for sure.
the pattern is related to the date of creation. YYYY-m
thus, it can be cleaned.

i'm not sure if you can just delete the entire folder of the month.
@pbortnik is more familiar with actual implementation of this.

**Comment by Oleksii-kh89** [comment]
Hi @ezienecker 
I guess the issue can be related to the clean storage job (cleanStorage)

Could you provide service-jobs logs and search for "cleanStorage" job execution logs?
Regarding manual deletion. You can clean attachments in the folder manually.
