### ISSUE TITLE
Attach Test ScreenShots to Logs in reportportal Using TestNG and Log4j2 With java getting error

### ISSUE THREAD

**Issue by sharathhatter1** [reportportal/reportportal#1829]
Attach Test ScreenShots to Logs in reportportal Using TestNG and Log4j2 With java getting error

On the console - "    [INFO ] 2022-08-30 13:39:30.541 [Test worker] CoreLogger - com.epam.reportportal.message.ReportPortalMessage@1d0305fb"

![image](https://user-images.githubusercontent.com/55090052/187408432-3686f688-9971-45fe-a8b3-f7a5422d5d0a.png)

**Versions:**
 - Windows, chrome
 - Version of RP-     implementation 'com.epam.reportportal:logger-java-log4j:5.1.3'

code -  
```java
protected void takeScreenshot(WebDriver driver, String methodName) {
        ReportPortalMessage message = null;
        TakesScreenshot scrShot = ((TakesScreenshot) driver);
        File fileSourceFile = scrShot.getScreenshotAs(OutputType.FILE);
        logger.info("Inside screenshot method");
        String strDirectory = System.getProperty("user.dir");
        File fileDestinationFile = new File(strDirectory + "/test-outputs/Screenshots/" + methodName + ".jpg");
        try {
            FileUtils.copyFile(fileSourceFile, fileDestinationFile);
            String rp_message = "test message for ReportPortal";
            message = new ReportPortalMessage(fileSourceFile, rp_message);
        } catch (IOException e) {
            e.printStackTrace();
        }
        logger.info(message);
    }
```

**Comment by HardNorth** [comment]
@sharathhatter1 I don't see any error messages. Please provide more details.

**Comment by sharathhatter1** [comment]
@HardNorth I am not seeing the error. 

But I donot see my logs in the reportportal io

I have added below prop in the log4j properties file
# Send logs into Report Portal
rootLogger = INFO, reportportal
appender.reportportal=com.epam.ta.reportportal.log4j.appender.ReportPortalAppender
appender.reportportal.layout=org.apache.log4j.PatternLayout
appender.reportportal.layout.ConversionPattern=[%d{HH:mm:ss}] %-5p (%F:%L) - %m%n

Log4j Dependency - 2.17.2

Only errors are showing in the report porter, rest of the logs are not shown. Im trying to attach screenshot also and not seeing it.

**Comment by HardNorth** [comment]
@sharathhatter1 You are using `Log4j 1.x.x` configuration file format to configure `Log4j 2.17.2`. It won't work, they are incompatible. Please read carefully our configuration guide: https://github.com/reportportal/logger-java-log4j#configuration---log4j2

**Comment by DzmitryHumianiuk** [comment]
@sharathhatter1 and make sure this file size is less then 16mb.
it's a default configuration for this request.
