### ISSUE TITLE
how to display grouped tests in pytest-reportportal

### ISSUE THREAD

**Issue by pbezpal** [reportportal/reportportal#1830]
Hello! I write tests with pytest and use the pytest-reportportal package for reporting in RP. Now my reports looked like
![My reports](https://automated-testing.info/uploads/default/original/2X/1/152e1c7488459dc6ce3a6bdefc3e1eede3e95773.png)

Is it possible to group tests so that the reports look like this
![Report with group tests](https://automated-testing.info/uploads/default/original/2X/2/28077bb6d7a64d0eb90602e852a3246c12e2147f.png)

**Comment by HardNorth** [comment]
Duplicates: https://github.com/reportportal/agent-python-pytest/issues/316
