### ISSUE TITLE
No documentation for POST ​/v1​/{projectName}​/log json_request_part

### ISSUE THREAD

**Issue by WillGibson** [reportportal/reportportal#1831]
Is anyone able to help with the documentation of what can/should be in json_request_part for the POST requests to the v1 log endpoint?

<img width="614" alt="image" src="https://user-images.githubusercontent.com/8738245/187671740-9ff4ca9a-6196-42f1-a62b-bd16116cc08a.png">

**Comment by HardNorth** [comment]
@WillGibson, take a look here: https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#batch-save-logs

**Comment by WillGibson** [comment]
Thanks @HardNort. Is `launchUuid` the ID of the scenario we want the logs attached to?

**Comment by HardNorth** [comment]
@WillGibson No, it's `launchUuid`. Scenario ID should be set into `itemUuid`.

**Comment by DzmitryHumianiuk** [comment]
@WillGibson seems like you are implementing a ruby agent. Right?

don't hesitate to contact me in the slack channel.
we would be glad to receive your contribution into the ruby agent.
thank you!

BTW, here is our old one.
it might be outdated, but at least something to look at: https://github.com/reportportal/agent-ruby
