### ISSUE TITLE
Filter for History table doesn't work correctly

### ISSUE THREAD

**Issue by kkaarreell** [reportportal/reportportal#1833]
**Describe the bug**
Open Launch -> See Test suite, Click on History button -> See a table with former test results for test items (test suites and test cases).
Filtering by name works properly but filtering per attribute:value does not. It seems that the filter is not properly applied to launches and test items.

For example, I have one test suite named /tier1-swtpm with attribute 'pool:aws' and in a different launch I have the same test suite with attribute 'pool:beaker'. In the History view I can see both results (from both launches) but after adding filter per attribute 'pool:aws' I would expect to see just one launch but either both or none launches are visible.
I tried setting attributes to launches, test suite and test cases, there was no difference.

**Expected behavior**
Filtering in the History view is applied properly to test item attributes. 
In fact, except Suite name filter it is not clear how filtering is supposed to work. Is it filtering by test items attributes or by launch attributes? Both would make sense and both would be IMHO useful.

**Screenshots**
![image](https://user-images.githubusercontent.com/16130993/188132252-0e2edaae-8789-4651-8742-44e97548078b.png)
![image](https://user-images.githubusercontent.com/16130993/188132327-04e296f1-c2c4-41f8-8f0d-a4ffab58ad41.png)
![image](https://user-images.githubusercontent.com/16130993/188132411-3a8f2203-09c8-467b-b991-97d1b235bcdf.png)

**Versions:**
 - OS, Browser
 RHEL8.6, Firefox 91.9.0esr
 - Version of RP [find it under Login form, copy as is] 
 v5.6

**Comment by DzmitryHumianiuk** [comment]
@kkaarreell looks like a bug.

@VolhaKarenko could you please double check it.
thanks.

**Comment by kkaarreell** [comment]
Hi @DzmitryHumianiuk , thank you for the confirmation.

> In fact, except Suite name filter it is not clear how filtering is supposed to work. Is it filtering by test items attributes or by launch attributes? Both would make sense and both would be IMHO useful.

Could you please also clarify the expected behavior?

**Comment by alena-babrova** [comment]
Hello @kkaarreell 
Indeed, the behaviour is a little confusing, but it works as designed.

The filter works only within the current (selected) Launch - you can see the current selected Launch in the breadcrumbs on the top of the page. 
![image](https://user-images.githubusercontent.com/89584140/190196282-4840ece4-74eb-468c-9662-c05ee790c177.png)

Yes, the history tab displays also information regarding the previous runs of the item - and this is what makes the confusion. While we do see the information about previous runs, the filter attribute applies ONLY for the latest run (which is the current scope).

In your example, filter by attribute works only for attributes which exist in Execution#2.
![image](https://user-images.githubusercontent.com/89584140/190198176-bbfab4c7-759c-4563-adb4-e4210406ff17.png)

**Comment by kkaarreell** [comment]
I see. Thank you for the clarification @alena-babrova . This is unfortunate as it makes this table less useful. I guess I should turn the issue into a RFE then.

**Comment by kkaarreell** [comment]
> I see. Thank you for the clarification @alena-babrova . This is unfortunate as it makes this table less useful. I guess I should turn the issue into a RFE then.

Reported as https://github.com/reportportal/reportportal/issues/1842
