### ISSUE TITLE
disable METHOD TYPE column in launch

### ISSUE THREAD

**Issue by swathisnice** [reportportal/reportportal#1835]
Our requirement dont need the method type. How to diable this collumn in launch table

**Comment by DzmitryHumianiuk** [comment]
@swathisnice it can't be removed.

the majority of test runners has supplementary methods as `@Before/After` methods.
They are not related to the test case itself, but do a very important job with a precondition steps.
thus, other people use it widely.


In RP6 test cases list will look different, and this column will be gone.
