### ISSUE TITLE
When Started Reportportal through DockerContainer it says 'An Error Occured while connecting to server'

### ISSUE THREAD

**Issue by heyrmi** [reportportal/reportportal#1836]
**Describe the bug**
When Started Reportportal through DockerContainer it says 'An Error Occured while connecting to server', sometimes it shows 'Signed In Sucessfully' but does not let in.

This is what I see in terminal: 
**reportportal_elasticsearch_1 exited with code 137**

**Expected behavior**
It should let user login. 

**Screenshots**
![Screenshot from 2022-09-05 14-00-11](https://user-images.githubusercontent.com/42892759/188406597-d3c931a1-378e-4565-bf3c-a0dbe1d010b0.png)

**Versions:**
 - Ubuntu, Firefox
 - Version of RP Jobs Service: 5.7.2; Service UI: 5.7.2;

**Comment by DzmitryHumianiuk** [comment]
https://reportportal.io/installation

Allocate at least 5+Gb of RAM for Docker via Docker Settings > Advanced
We strongly recommend to deploy in Linux based environment

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/11332788/190030848-dbc0e79f-54c4-4970-a4bf-c0f17f22c4e9.png">
