### ISSUE TITLE
Cucumber agent/RP: Cucumber reports do not display Cucumber hooks

### ISSUE THREAD

**Issue by jurteg** [reportportal/reportportal#184]
Cucumber reports on RP do not reflect the Cucumber hooks that go as pre/post conditions for scenarios.
This is very important since hooks usually setting up proper test data or appropriate conditions.
Moreover, when the hook is failing - the stacktrace before scenario is misleading and non-informative because of absence of the root cause.
Again, it is very confusing to see the stacktrace at the end of the scenario, if all steps have passed. This case will take place if  @ After hook has failed.
In the attachment you could see the stacktrace of failed @ Before hook, but there is no visible prove of its existence.

![rp_bug_2](https://user-images.githubusercontent.com/25842206/28217585-4f99d270-68be-11e7-8e8f-5132603a12a8.png)

Here how it looks on Jenkins (there is another scenario):

![rp_bug_2_1](https://user-images.githubusercontent.com/25842206/28217904-81b48862-68bf-11e7-8926-0f0102b1eb7b.png)

**Comment by avarabyeu** [comment]
@jurteg good catch. can you prepare PR and fix it? Agent is [placed here](https://github.com/reportportal/agent-java-cucumber)

**Comment by DzmitryHumianiuk** [comment]
correlates with #226

**Comment by DzmitryHumianiuk** [comment]
@jurteg any luck?

**Comment by jurteg** [comment]
I was pretty sure I have closed this issue. This issue is reproduceable only for ScenarioReporter in Cucumber agent. I spend some time and got the solution on this, considering it's not a bug.
The 'hookFinished()' method is empty for this type of reporter, so you need just add appropriate override:

` @Override
    protected void hookFinished(Match match, Result result, Boolean isBefore) {
        reportResult(result, (isBefore ? "@Before" : "@After") + "\n" + match.getLocation());
    }`
