### ISSUE TITLE
Issue with upgrade to v5.7.2 and service-metrics-gatherer:1.1.20

### ISSUE THREAD

**Issue by Ramandus** [reportportal/reportportal#1844]
Hello, I just updated our ReportPortal instance from 5.6.2 to 5.7.2 using docker-compose. 

Everything works as expected except for the service-metrics-gatherer:1.1.20 container which has status unhealtly. 

Below is the log from that container:
*** Starting uWSGI 2.0.18 (64bit) on [Fri Sep 16 08:04:41 2022] ***
compiled with version: 10.2.1 20210110 on 06 July 2022 13:05:07
os: Linux-3.10.0-1160.76.1.el7.x86_64 #1 SMP Tue Jul 26 14:15:37 UTC 2022
nodename: ad32a1c4068f
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /backend
detected binary path: /venv/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :5000 fd 3
uwsgi socket 0 bound to TCP address :3031 fd 6
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.7.13 (default, Jun 23 2022, 12:05:54)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /venv
Set PythonHome to /venv
Python main interpreter initialized at 0x5647a010d610
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 7, cores: 1)
spawned uWSGI http 1 (pid: 8)
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    from flask import Flask, Response
  File "/venv/lib/python3.7/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/venv/lib/python3.7/site-packages/jinja2/__init__.py)
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
--- no python application found, check your startup logs for errors ---
[pid: 7|app: -1|req: -1/1] 127.0.0.1 () {28 vars in 293 bytes} [Fri Sep 16 08:05:42 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---

**Comment by HardNorth** [comment]
Duplicate: #1789
