### ISSUE TITLE
Cucumber agent/RP: Cucumber reports do not reflect feature description and other information

### ISSUE THREAD

**Issue by jurteg** [reportportal/reportportal#185]
RP Cucumber reports do not contain:
- Feature description
- Hooks and feature/scenario tags
- Text inline comments
Such information is most useful for 'documentation by example' approach used in BDD process and allows to track changes in features.
P.S. Cucumber passing all this information, so I believe it could be used this way

![rp_bug_3](https://user-images.githubusercontent.com/25842206/28218349-f21cb448-68c0-11e7-96af-d49616d2381c.png)
![rp_bug_4](https://user-images.githubusercontent.com/25842206/28218451-3e3d2132-68c1-11e7-93cd-bda8d3f2482e.png)

**Comment by avarabyeu** [comment]
@jurteg is that related to cucumber or cucumberJVM?

**Comment by jurteg** [comment]
Yes, that's right, sorry for lack of details.

**Comment by jurteg** [comment]
CucumberJVM

**Comment by avarabyeu** [comment]
@jurteg 
Thanks for posting this. 
Are you able to fix the issue? 
If not, may i ask you to update gherkin file in this project: https://github.com/reportportal/example-java-cucumber in order to have some example of events that are missed. 

Thank you!

**Comment by jurteg** [comment]
@avarabyeu 
I'm not sure I will have enough time for fixing this, however I will definitely will add working examples to highlight the issue.

**Comment by jurteg** [comment]
Not a bug. The issue could be easily fixed by adding appropriate implementation to the agent.
