### ISSUE TITLE
Issue with migrations on upgrading from version 5.6.0 to 5.7.2.

### ISSUE THREAD

**Issue by akshayamaldhure** [reportportal/reportportal#1851]
Steps:

1. Reportportal version 5.6.0 running using Docker without any issues.
2. Download the docker-compose.yml for the 5.7.2 version.
3. Run docker-compose `docker-compose -f docker-compose.yml -p reportportal up -d --force-recreate --remove-orphans`.
4. Above command brings up all the containers successfully, but the `reportportal/migrations:5.7.2` container keeps restarting.

Attaching the evidences like the error from the `reportportal/migrations:5.7.2` container, running containers, symptoms we see on the UI (perhaps due to the incomplete migrations), etc.

Please advise how we could handle the migrations so that we are able upgrade to 5.7.2 fully.

![Screenshot 2022-09-28 at 9 25 44 AM](https://user-images.githubusercontent.com/8114665/192674338-40a09721-62a3-4074-9583-a950d9198472.png)
![Screenshot 2022-09-28 at 9 26 05 AM](https://user-images.githubusercontent.com/8114665/192674343-eae5f873-cbff-4c1a-abe9-086d13045e8b.png)
![Screenshot 2022-09-28 at 9 26 27 AM](https://user-images.githubusercontent.com/8114665/192674347-d9b3efb1-cb4c-43d5-975e-c98e18989c6b.png)

**Comment by irynakozak2** [comment]
@akshayamaldhure hi! Unfortunately, It can be a common issue while upgrading to the latest versions, so we've created a guide on how to resolve it. Please check it [here](https://reportportal.io/docs/How-to-resolve%3Eerror-dirty-database-version-xx-fix-and-force-version-) and notify us about the issue resolution. Thank you!

**Comment by akshayamaldhure** [comment]
> @akshayamaldhure hi! Unfortunately, It can be a common issue while upgrading to the latest versions, so we've created a guide on how to resolve it. Please check it [here](https://reportportal.io/docs/How-to-resolve%3Eerror-dirty-database-version-xx-fix-and-force-version-) and notify us about the issue resolution. Thank you!

Hi. Thanks for sharing the guide. Unfortunately, owing to the migration issues, we had to set up the latest instance from scratch.
