### ISSUE TITLE
Discrepancy in failed tests count.

### ISSUE THREAD

**Issue by akshayamaldhure** [reportportal/reportportal#1857]
**Describe the bug**
As seen in the attached screenshots, there are actual 4 failures, but Reportportal report shows 9 failures. This issue is observed when there are tests running in parallel. Such incorrectly marked failed tests do not show any failure exception in the detailed view of logs in Reportportal.

**Expected behavior**
The number of failed tests reported by Reportportal should be equal to the actual number of failed tests.

**Screenshots**
![Screenshot 2022-05-23 at 10 30 24 AM](https://user-images.githubusercontent.com/8114665/195075747-8cdba800-a114-4789-89a8-5398e7e15d28.png)

**Versions:**
 - OS, Browser: Mac OS, Chrome 106.0.5249.61 (Official Build) (arm64) 
 - Version of RP: 5.7.2

**Comment by DzmitryHumianiuk** [comment]
@akshayamaldhure do you have a code example to reproduce this?

thanks.

**Comment by akshayamaldhure** [comment]
> @akshayamaldhure do you have a code example to reproduce this?
> 
> thanks.

Here's what my setup looks like:

```
// A custom Reportportal listener in order to have exception stack trace in the tests list view.

package listeners;

import com.epam.reportportal.listeners.ItemStatus;
import com.epam.reportportal.testng.BaseTestNGListener;
import com.epam.reportportal.testng.TestNGService;
import com.epam.ta.reportportal.ws.model.FinishTestItemRQ;
import com.google.common.base.Strings;
import com.google.common.base.Throwables;
import org.testng.ITestResult;

public class CustomReportPortalTestNGListener extends BaseTestNGListener {

    public CustomReportPortalTestNGListener() {
        super(new ParamTaggingTestNgService());
    }

    public static class ParamTaggingTestNgService extends TestNGService {

        @Override
        protected String createStepName(ITestResult testResult) {
            return testResult.getTestName();
        }

        @Override
        protected FinishTestItemRQ buildFinishTestMethodRq(ItemStatus status, ITestResult testResult) {
            FinishTestItemRQ finishTestItemRQ = super.buildFinishTestMethodRq(status, testResult);
            if (testResult.getThrowable() != null) {
                String description = Strings.nullToEmpty(testResult.getMethod().getDescription());
                description = description
                        + "\n\n"
                        + "```error"
                        + Throwables.getStackTraceAsString(testResult.getThrowable())
                        + "```";
                finishTestItemRQ.setDescription(description);
            }
            return finishTestItemRQ;
        }
    }
}

```

```
// imports removed

package base;

import constants.pricing.PricingTestGroups;
import objectMappers.base.SimpleObjectMapperFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testng.ITest;
import org.testng.annotations.BeforeMethod;

import java.lang.reflect.Method;
import java.util.Map;
import java.util.UUID;

import static utils.PricingTestUtils.generateServiceArea;
import static utils.PricingTestUtils.generateServiceType;

public class MyTest implements ITest {

    private static final Logger LOG = LoggerFactory.getLogger(MyTest.class);
    private ThreadLocal<String> testName = new ThreadLocal<>();

    @Override
    public String getTestName() {
        return testName.get();
    }

    @BeforeMethod()
    public void setup(Method method, Object[] testDataRecordObj) {
        Map<String, Object> testDataRecord = new ObjectMapper().convertValue(testDataRecordObj[0], Map.class);
        String testNameStr = method.getName() + "_" + testDataRecord.get("someTestAttribute");
        testName.set(testNameStr);
    }

   @DataProvider(name = "testDataProvider", parallel = true)
    public Object[][] getTestData() {
       // logic to populate and return test data as Object[][]
    }
    
    @Test(description = "My test", dataProvider = "testDataProvider")
    public void verifySomething(HashMap<String, Object> dataFilesHashMap) {
       // test steps here
    }
}
```

```
// build.gradle configuration

task runTests(type: Test) {
    useTestNG {
        parallel = getSysPropEmptyValueWithDefault('runinparallel', 'methods')
        testLogging.exceptionFormat = 'full'
        threadCount = Integer.parseInt(getSysPropEmptyValueWithDefault('parallel', '50'))
        useDefaultListeners = true
        listeners << 'listeners.CustomReportPortalTestNGListener'
        includeGroups System.getProperty('tag', 'NONE')
        outputDirectory = file("$buildDir/" + System.getProperty('tag', 'NONE'))
    }

    group 'verification'

    doFirst {
        def weaver = configurations.runtimeClasspath.find { it.name.contains("aspectjweaver") }
        jvmArgs = jvmArgs << "-javaagent:$weaver"
    }
}
```

**Comment by akshayamaldhure** [comment]
One thing I forgot to mention about this issue is that it is intermittent and it not observed across all the runs for me. So far I've tried to make the `protected` methods in `CustomReportPortalTestNGListener.java` as `protected synchronized`, but that did not help. Could this be happening because the class `ParamTaggingTestNgService` in `CustomReportPortalTestNGListener` is declared as `static`?

**Comment by DzmitryHumianiuk** [comment]
@HardNorth  ^^^
![Alt Text](https://media.tenor.com/RAbDiX4JrjAAAAAC/spongebob-maximum-power.gif)

**Comment by akshayamaldhure** [comment]
@DzmitryHumianiuk 
> Could this be happening because the class ParamTaggingTestNgService in CustomReportPortalTestNGListener is declared as static?
Is this an obvious mistake here? Please let me know if anything needs to be fixed. Thanks. 😄

**Comment by DzmitryHumianiuk** [comment]
@akshayamaldhure seems to be.
but I want @HardNorth to take a look into it.

**Comment by akshayamaldhure** [comment]
> @akshayamaldhure seems to be. but I want @HardNorth to take a look into it.

I just noticed that this documentation http://reportportal.io/documentation/documentation.html?n has `ParamTaggingTestNgService` declared as `static` only.

**Comment by HardNorth** [comment]
@akshayamaldhure Can you show these failures, where they happens and their stacktrace?

**Comment by akshayamaldhure** [comment]
> @akshayamaldhure Can you show these failures, where they happens and their stacktrace?

Hi. I'm sharing another repro for this issue where the actual number of failed cases is 6 (console logs are `Pass - 41 | Fail - 6 | Skip - 0 | Duration - 00:04:09` which are printed by another listener we use which internally just prints these numbers using `ITestContext` e.g. `testContext.getFailedTests().size()`) whereas Reportportal shows 14 failures. The ones that has actually failed (6 tests) are all `java.lang.AssertionError` failures for which stacktrace that looks like below (`Sample number` is the log I added as an assertion `message`).

```
java.lang.AssertionError: Sample number [1] but found [0]
    at org.testng.Assert.fail(Assert.java:99)
    at org.testng.Assert.failNotEquals(Assert.java:1037)
    at org.testng.Assert.assertEqualsImpl(Assert.java:140)
    at org.testng.Assert.assertEquals(Assert.java:122)
    at org.testng.Assert.assertEquals(Assert.java:907)
```
![Screenshot 2022-10-17 at 2 59 50 PM](https://user-images.githubusercontent.com/8114665/196110803-8e1c9332-be69-44ab-ae92-08c81ce7065d.png)

The other tests that are shown as failed by Reportportal but are actually passed do not show any exceptions, they are indeed the passing ones.

**Comment by HardNorth** [comment]
> The other tests that are shown as failed by Reportportal but are actually passed do not show any exceptions, they are indeed the passing ones.

This usually means an issue in third-party code, unfortunately. Try run your tests without any listener but ReportPortal.

**Comment by akshayamaldhure** [comment]
> > The other tests that are shown as failed by Reportportal but are actually passed do not show any exceptions, they are indeed the passing ones.
> 
> This usually means an issue in third-party code, unfortunately. Try run your tests without any listener / extension but ReportPortal.

I'm not sure if I understand that correctly. This should not be an issue in the third-party code since I verified that the tests that are being shown as failed (in the item list view in the screenshot I shared in my last message) are not actually the failed ones. Even Reportportal does not show those as failed in the item details view. Could you please elaborate? I cannot remove the other listener since it is responsible to handle Slack alerting for my test runs.

**Comment by HardNorth** [comment]
@akshayamaldhure Most likely somewhere in your custom code, outside the test logic itself, exceptions are thrown, which does not cont in test results but fire `onConfigurationFailure` event. That's why you have empty failed tests.

My bet that happens somewhere on Json conversion.

**Comment by akshayamaldhure** [comment]
> @akshayamaldhure Most likely somewhere in your custom code, outside the test logic itself, exceptions are thrown, which does not cont in test results but fire `onConfigurationFailure` event. That's why you have empty failed tests.
> 
> My bet that happens somewhere on Json conversion.

The Reportportal test logs and console logs appear clean for such tests. Do you intend to say that the tests will not show those exceptions (supposedly originating from outside the tests) in Reportportal? But won't TestNG also mark such tests as failed in such cases? Also, which JSON conversion are you referring to?

**Comment by HardNorth** [comment]
@akshayamaldhure
> Do you intend to say that the tests will not show those exceptions
Yes, build systems usually hide test logs. To get logs for gradle you need to enable logging, [see here](https://stackoverflow.com/questions/9356543/logging-while-testing-through-gradle)

> But won't TestNG also mark such tests as failed in such cases?
Not necessarily, if an exception happens outside its Test abstraction. 

> which JSON conversion are you referring to?
This one:
> Map<String, Object> testDataRecord = new ObjectMapper().convertValue(testDataRecordObj[0], Map.class);

>Also, is there a way to check and confirm if this is indeed happening due to some exception being throws outside of the test somewhere?
I told it, get rid of all custom code. Usually I ask for a plain example project in this case to prove that the issue in the our agent. And usually it's really rare case when people come back with a real bug.

**Comment by akshayamaldhure** [comment]
> 

Thanks a lot for all the pointers. I understand it could be frustrating to deal with issues that do not originate from within Reportportal. Let me investigate this at my end again.
