### ISSUE TITLE
Report Portal setup on AWS

### ISSUE THREAD

**Issue by satishkumar9549** [reportportal/reportportal#1858]
Hello, can you please provide more documentation on how to migrate on prem Report Portal application to AWS?
I found some documentation on webpage but that didn't help on the whole, can you please provide simple steps on how to deploy application in AWS using EKS?

**Comment by DzmitryHumianiuk** [comment]
@satishkumar9549 here are the kubernetes helm charts:
https://github.com/reportportal/kubernetes/tree/develop/reportportal

While migrating you should do next things:
1. dump local database and restore it inside the AWS hosted DB or RDS
2. copy underlying structure of minIO files.
