### ISSUE TITLE
Calling method 'start_suite' of listener 'robotframework_reportportal.listener' failed: TypeError: Object of type _PresenceSentinel is not JSON serializable

### ISSUE THREAD

**Issue by wshdota2** [reportportal/reportportal#1865]
There are lot of methods in robotframework_reportportal.listener failed: TypeError: Object of type _PresenceSentinel is not JSON serializable. 
robotframework : Window 10
reportprotal : Centos 8
![1666176677(1)](https://user-images.githubusercontent.com/51727190/196671562-075b9365-eb0f-4e62-a8b5-aaf48bdd88d4.png)

**Comment by HardNorth** [comment]
Duplicate: https://github.com/reportportal/agent-Python-RobotFramework/issues/154
