### ISSUE TITLE
Client exception with client-javascript, Request failed with status code 400

### ISSUE THREAD

**Issue by dkamenov-fitted** [reportportal/reportportal#1868]
We have a few instances of a test running and being submitted to report portal failing. Not sure what is causing the problem or how to get to the bottom of the underlying issue.

**Versions:**
API Service: 5.7.2;Jobs Service: 5.7.2;Authorization Service: 5.7.0;Service UI: 5.7.2; Report portal is running within a GKE instance (kubernetes).
@reportportal/client-javascript: latest NPM package

Our setup is that on a PR open, as a github action, we run our Jest test with the --coverage flag. The tests themselves pass, but when they get submitted to RP, it comes back with:

> Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Field 'attributes[].value' should have size from '1' to '128'.] [Field 'attributes[].value' should not contain only white spaces and shouldn't be empty.] "}

As far as our jest configuration, within our jest.config.ts file we have:
```
  // If enabled, add the Report Portal reporter configuration
  if (reportPortalEnabled) {
    options.reporters?.push(
      ["@reportportal/agent-js-jest",
      {
        endpoint: "https://reportportal.cicd.fittedretail.dev/api/v1",
        project: productName,
        launch: `unittest-${serviceName}`,
        description: `Jest unit-test suites for ${serviceName}`,
        restClientConfig: {
          timeout: 0
        }
      }]
    )
  }
```
We also set RP_ENABLED and RP_TOKEN as env variables that are passed in
Below is the stack reported from the API service:

> org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [1] in public com.epam.ta.reportportal.ws.model.launch.StartLaunchRS com.epam.ta.reportportal.ws.controller.L
aunchController.startLaunch(java.lang.String,com.epam.ta.reportportal.ws.model.launch.StartLaunchRQ,com.epam.ta.reportportal.commons.ReportPortalUser) with 2 errors: [Field error in object 'startLaunchR
Q' on field 'attributes[].value': rejected value []; codes [NotBlank.startLaunchRQ.attributes[].value,NotBlank.startLaunchRQ.attributes.value,NotBlank.attributes[].value,NotBlank.attributes.value,NotBla
nk.value,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [startLaunchRQ.attributes[].value,attributes[].value]; arguments []; default message [attributes[
].value]]; default message [must not be blank]] [Field error in object 'startLaunchRQ' on field 'attributes[].value': rejected value []; codes [Size.startLaunchRQ.attributes[].value,Size.startLaunchRQ.a
ttributes.value,Size.attributes[].value,Size.attributes.value,Size.value,Size]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [startLaunchRQ.attributes[].value,att
ributes[].value]; arguments []; default message [attributes[].value],128,1]; default message [size must be between 1 and 128]]

The interesting part is that the same repo will work randomly with no issues, but other times it fails with the above.

**Comment by DzmitryHumianiuk** [comment]
@dkamenov-fitted looks like backend returns an error because of the long value or key in attribute which is longer than 128 symbols.
we definitely can make it bigger.

**Comment by dkamenov-fitted** [comment]
> @dkamenov-fitted looks like backend returns an error because of the long value or key in attribute which is longer than 128 symbols. we definitely can make it bigger.

@DzmitryHumianiuk , is there a way to tell which attribute this is related to, or a way to log out all the attributes?

**Comment by DzmitryHumianiuk** [comment]
@dkamenov-fitted practically no.

on RP side we will increate the limitation in 5.7.4


<img width="1463" alt="image" src="https://user-images.githubusercontent.com/11332788/200333982-7bc4b18f-d101-44db-9df2-997cc7c7ff9c.png">

**Comment by VeranikaRymzha** [comment]
Hello @dkamenov-fitted,
Could you please give an example of your longest attribute keys and values? 
It will help us to identify reasonable limits for them.

**Comment by dkamenov-fitted** [comment]
@VeranikaRymzha, I don't know what the longest attribute key/values are as we do not pass any on client instantiation. 
Is there a list of default attributes that are always submitted and what those values might be?

**Comment by DzmitryHumianiuk** [comment]
128 is still pretty big. here an example of attribute with 128 in key and 128 in value.
`Sed_ut_perspiciatis_unde_omnis_iste_natus_error_sit_voluptatem_accusantium_doloremque_laudantium,_totam_rem_aperiam,_eaque_ipsa:Sed_ut_perspiciatis_unde_omnis_iste_natus_error_sit_voluptatem_accusantium_doloremque_laudantium,_totam_rem_aperiam,_eaque_ipsa`

@VeranikaRymzha let's make it 512 for both
It won't be readable on UI, but 128 is not something we can show on UI either.
I mean, we still have to collapse the representation of such an attribute on UI, and it doesn't make much of the difference if it is 128 or 512 limit.


512 example
`Sed_ut_perspiciatis_unde_omnis_iste_natus_error_sit_voluptatem_accusantium_doloremque_laudantium,_totam_rem_aperiam,_eaque_ipsa_quae_ab_illo_inventore_veritatis_et_quasi_architecto_beatae_vitae_dicta_sunt_explicabo._Nemo_enim_ipsam_voluptatem_quia_voluptas_sit_aspernatur_aut_odit_aut_fugit,_sed_quia_consequuntur_magni_dolores_eos_qui_ratione_voluptatem_sequi_nesciunt._Neque_porro_quisquam_est,_qui_dolorem_ipsum_quia_dolor_sit_amet,_consectetur,_adipisci_velit,_sed_quia_non_numquam_eius_modi_tempora_incidunt:Sed_ut_perspiciatis_unde_omnis_iste_natus_error_sit_voluptatem_accusantium_doloremque_laudantium,_totam_rem_aperiam,_eaque_ipsa_quae_ab_illo_inventore_veritatis_et_quasi_architecto_beatae_vitae_dicta_sunt_explicabo._Nemo_enim_ipsam_voluptatem_quia_voluptas_sit_aspernatur_aut_odit_aut_fugit,_sed_quia_consequuntur_magni_dolores_eos_qui_ratione_voluptatem_sequi_nesciunt._Neque_porro_quisquam_est,_qui_dolorem_ipsum_quia_dolor_sit_amet,_consectetur,_adipisci_velit,_sed_quia_non_numquam_eius_modi_tempora_incidunt`

**Comment by VeranikaRymzha** [comment]
Okay. 
Thank you for your replies, @DzmitryHumianiuk, @dkamenov-fitted.

**Comment by nvborisenko** [comment]
And make trimming on server side? Why not?

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko seems tricky. since we are not sure which part should be trimmed?
at the end? from the beginning or in the middle.

Since you can have such a attribute keys like:
`component_testing_system........_version1 : value`
`component_testing_system........_version2 : value`

and if we can it at the end, that it will be equal attributes.

`component_testing_system........: value`
`component_testing_system........: value`

**Comment by nvborisenko** [comment]
Just proposed generic way to solve the issue for all bindings.

**Comment by DzmitryHumianiuk** [comment]
thanks @nvborisenko 
I think, 512 symbols will not take a lot in DB,
on UI we still will trim them visually, since it's ridiculous to show it in the full size.
but from the API side, they will be different objects.

**Comment by DzmitryHumianiuk** [comment]
and trim everything longer than 512 ))

**Comment by Kozovskaya** [comment]
Hello @dkamenov-fitted,
In our latest version we've increased the allowed max. length of attribute key and value up to 512 symbols. Hope now everything will be ok on your side. 
Link to the release info https://reportportal.io/releases

**Comment by dkamenov-fitted** [comment]
> Hello @dkamenov-fitted, In our latest version we've increased the allowed max. length of attribute key and value up to 512 symbols. Hope now everything will be ok on your side. Link to the release info https://reportportal.io/releases

Thank you team!
