### ISSUE TITLE
Api service restart with readiness probe error - minikube installation

### ISSUE THREAD

**Issue by hagayparavy** [reportportal/reportportal#1870]
Hi,
I'm trying to install the RP and for some reason, the "reportportal-api" service is restarting with the following error "**Readiness probe failed: Get "http://172.17.0.15:8585/health": dial tcp 172.17.0.15:8585: connect: connection refused**" and I can't find out why,

all other services are up and I can access **"reportportal.k8.com**" locally ( login with _superadmin\erebus_ fails with 503)

I've installed the prerequisites (rabbitmq,postgresql,minio & ES) and updated the "values.yaml"

the last print in the service log says:
"**Caused by: com.epam.ta.reportportal.exception.ReportPortalException: Unclassified Report Portal Error**"

Can you help me understand what is the problem?

Here are the full logs of the service
[reportportal-api.log](https://github.com/reportportal/reportportal/files/9859124/reportportal-api.log)

and the deployed replicaset
[rp-api-replicaset.txt](https://github.com/reportportal/reportportal/files/9859175/rp-api-replicaset.txt)

**Comment by HardNorth** [comment]
The error tells you that something wrong with Rabbit MQ connection:
```
Caused by: com.epam.ta.reportportal.exception.ReportPortalException: Unclassified Report Portal Error
	at com.epam.ta.reportportal.core.configs.rabbit.RabbitMqConfiguration.connectionFactory(RabbitMqConfiguration.java:67)
```
Please ensure that you RadbbitMQ is deployed and its service name is: `rabbitmq`

**Comment by hagayparavy** [comment]
Thanks for directing me, I found the issue in the rabbitmq logs. 
The address was right but I failed to authenticate to the rabbitmq API
