### ISSUE TITLE
requirements.yaml images upgrade

### ISSUE THREAD

**Issue by babantax** [reportportal/reportportal#1871]
**Upgrade rabbitmq and minio image versions**
![image](https://user-images.githubusercontent.com/52815118/198274210-ddd960b0-a3e2-4c72-a59b-c68236ad6873.png)

If I´m not wrong, current versions of [minio and rabbitmq in the Report Portal last current version (5.7.2)](https://github.com/reportportal/kubernetes/blob/reportportal-5.7.2/reportportal/requirements.yaml) are:
- minio: 7.1.9 -> using a **2021.6.17-debian-10-r57** from bitnami/minio
- rabbitmq: 7.5.6 -> using a **3.8.5-debian-10-r38** from bitnami/rabbitmq

I would like to know if is there any plan to upgrade. 

Versions are quite old and from the perspective of avoiding security or vulnerability problems, it would be a nice improvement.

Thanks a lot in advance

**Comment by HardNorth** [comment]
1) We are going to get rid of minio.
2) Our version of rabbitmq does not have any known critical vulnerabilities, why should we bother?
https://www.cvedetails.com/vulnerability-list/vendor_id-15183/product_id-30922/Pivotal-Software-Rabbitmq.html
