### ISSUE TITLE
How to get LaunchID  via API?

### ISSUE THREAD

**Issue by deod** [reportportal/reportportal#1872]
After a successful `/v1/{projectName}/launch/import` , I would like to update the description of that launch using `/v1/{projectName}/launch/{launchId}/update`. 
How do I get the launch's launchID via API? 
I have access to the uuid, but that doesn't work.
OR 
How can I update launch description using launch UUID?

**Comment by APiankouski** [comment]
Hi @deod, you can get launchID using GET /v1/{projectName}/launch/uuid/{uuid}
