### ISSUE TITLE
ReportPortal jobs Elasticsearch health check failed

### ISSUE THREAD

**Issue by dmitriishuvalov** [reportportal/reportportal#1873]
Dear all!
Can you please kindly help me to understand how to complete RP setup.
I've deployed in my EKS cluster rabbitmq, postgresql, elasticsearch and minio (Configured as gateway to S3) using usual Helm charts from bitnami, with almost default values (Just set some auth and node affinity)
All components seems to be up and running expect reportportal-jobs pod - it's running but never goes to READY state.
In logs i see 

```
2022-11-01 16:04:17 | at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:849) ~[elasticsearch-rest-client-7.9.3.jar!/:7.9.3]
-- | --
  |   | 2022-11-01 16:04:17 | java.net.ConnectException: Connection refused
  |   | 2022-11-01 16:04:17 |  
  |   | 2022-11-01 16:04:17 | 2022-11-01 15:04:17.104  WARN 1 --- [nio-8686-exec-5] s.b.a.e.ElasticsearchRestHealthIndicator : Elasticsearch health check failed
  |   | 2022-11-01 16:04:17 |  
  |   | 2022-11-01 16:04:17 | ... 1 common frames omitted
  |   | 2022-11-01 16:04:17 | at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
  |   | 2022-11-01 16:04:17 | at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
  |   | 2022-11-01 16:04:17 | at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351) ~[httpcore-nio-4.4.14.jar!/:4.4.14]
  |   | 2022-11-01 16:04:17 | at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148) ~[httpcore-nio-4.4.14.jar!/:4.4.14]
  |   | 2022-11-01 16:04:17 | at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174) ~[httpcore-nio-4.4.14.jar!/:4.4.14]
  |   | 2022-11-01 16:04:17 | at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777) ~[na:na]
  |   | 2022-11-01 16:04:17 | at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:na]
  |   |   | 2022-11-01 16:04:17 | Caused by: java.net.ConnectException: Connection refused
  |   | 2022-11-01 16:04:17 | at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
  |   | 2022-11-01 16:04:17 | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]

```

I don't see any other e  | 2022-11-01 16:04:17 | Caused by: java.net.ConnectException: Connection refused
  |   | 2022-11-01 16:04:17 | at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
  |   | 2022-11-01 16:04:17 | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]

```

I don't see any other errors in other services. 
The documentation is really not so good to understand what happened.
Please let me know what detailed information you might need, i will add as comments.
After successful installation I will create PR with updated real instruction on how to deploy ReportPortal in AWS EKS with Terraform :-)

**Comment by HardNorth** [comment]
@dmitriishuvalov Most likely you are cloned our dev branch of https://github.com/reportportal/kubernetes repository. It's containing new features which are not supported by `service-jobs` yet. Please use either `master` branch, either use our chart repository:
```
helm repo add rp_repo https://reportportal.github.io/kubernetes
```

**Comment by alexandrsemak** [comment]
@HardNorth Hey are you sure that 5.7.2 works with external Elasticsearch ?

I got the same error during upgrade from 5.7.1 and I don't see any envs variables in jobs service for elasticsearch

**Comment by HardNorth** [comment]
@alexandrsemak I'm sure that will work in 5.7.3, until then that issue is a known bug.

**Comment by alexandrsemak** [comment]
@HardNorth We can't as we deploy it by HelmRelease and we got ready status failed which block as for future releases.
Can we use 5.7.1 for jobs service and 5.7.2 for others?

**Comment by HardNorth** [comment]
@alexandrsemak Your issue is that you use cloned repo from `develop` branch. Just switch on `master` or use our Helm Chart repositor.

**Comment by alexandrsemak** [comment]
@HardNorth The same issue for master

**Comment by HardNorth** [comment]
@alexandrsemak Then it's unrelated or you confuse it with another issue, since `master` does not even has health checks for `service-jobs`: https://github.com/reportportal/kubernetes/compare/master...develop#diff-581b813263be67a16a6eee93f187853c98bfb4c4ac652afa46eaa5ca90c7f632R156-R179

**Comment by alexandrsemak** [comment]
@HardNorth sorry you right we forget cleanup readiness and liveness . It is work from master
