### ISSUE TITLE
We have 21 Dashboard-widgets in the list in the website. But in our report portal, we have only 20. How can I implement the one (Most-time-consuming-test) that is missing?

### ISSUE THREAD

**Issue by arunkumargceb** [reportportal/reportportal#1874]
We have 21 Dashboard-widgets in the list in the website. But in our report portal, we have only 20. How can I implement the one (Most-time-consuming-test) that is missing?

**Comment by DzmitryHumianiuk** [comment]
please update to the latest version.
this widget was added in v5.4
