### ISSUE TITLE
In the widgets – timeline mode displays date only for one day, not showing for all the records/launches. Is it possible to display dates for all the launches/records in X-axis for any widget for eg: Launch statistics report?

### ISSUE THREAD

**Issue by arunkumargceb** [reportportal/reportportal#1875]
In the widgets – timeline mode displays date only for one day, not showing for all the records/launches. If it is not an issue, Is it possible to display dates for all the launches/records in X-axis for any widget for eg: Launch statistics chart?

**Comment by VolhaKarenko** [comment]
Hello @arunkumargceb, thank you for pointing this out! The issue has already been added to our backlog and will be fixed in version 5.7.4.
