### ISSUE TITLE
Sending notifications to test owners

### ISSUE THREAD

**Issue by gadgadskiy** [reportportal/reportportal#1878]
Hi guys!
I have a project with launches, which can contain a few tests with different owners. Notifications in the project are set up to send emails to all owners, not depending on the launch content.

I'm trying to find a way to send emails to each owner with only tests assigned to this owner, but I can't find the way. Is it possible?

Owners are added as an attribute to each test, but ReportPortal can't find such an attribute during the notification creation.

Example of test with the owner attribute:
<img width="401" alt="Screenshot 2022-11-10 at 15 25 27" src="https://user-images.githubusercontent.com/23098882/201106660-e51f13d1-42c9-4309-8cf6-873f6f5f3c88.png">

Still, it's absent in the available attributes list:
<img width="486" alt="Screenshot 2022-11-10 at 15 40 57" src="https://user-images.githubusercontent.com/23098882/201107343-c0471604-467d-4004-ac41-f8484eb4ff8e.png">

**Comment by VolhaKarenko** [comment]
Hello @gadgadskiy, 
the attributes specified in a notification rule are related only to launch attributes, not test items.
In your case, you should add all test owners as attributes to a launch and create several notification rules, adding 1 attribute (launch owner) in each rule. As all attributes, specified in one rule, have 'and' condition, so only launch with a combination of all attributes will trigger a notification - we will add 'or' condition in version 5.7.5, so 1 rule will be enough then. 
Let me know if this works for you or if you have any questions left

**Comment by gadgadskiy** [comment]
Hi, @VolhaKarenko, thank you for the response!
Am I right, with the setting you described, each mentioned owner will receive mail with ALL tests in the launch where he owns at least one test? We searched for an option to send emails with only tests owned by the appropriate owner (each launch has many tests with different owners).
