### ISSUE TITLE
Random error while log-in using SAML plugin with Azure AD

### ISSUE THREAD

**Issue by babantax** [reportportal/reportportal#1894]
Report Portal Version 5.7.2

Random error, it happens more often when you already have a browser opened and SSO already done for other tools.

Using incognito mode rarely happens but I faced sometimes. 

SAML plugin configuration:
![image](https://user-images.githubusercontent.com/52815118/205008856-8c6bf896-8daf-4513-972a-f8f839431523.png)

Error displayed in the browser:
![image](https://user-images.githubusercontent.com/52815118/204856679-a4222e6c-6479-488f-a264-adfef558c579.png)

Output logs in uat pod:
![image](https://user-images.githubusercontent.com/52815118/204857039-0f23aa68-84a4-4830-8e10-96e75cb5bc8d.png)

Output logs in api pod:
![image](https://user-images.githubusercontent.com/52815118/204857231-aaafb994-b23d-48f2-ad3d-1eac65cf9e85.png)

Can be related to some misconfiguration?

Thanks a lot in advance

**Comment by alena-babrova** [comment]
Hello @babantax,

Yes, it is a known issue. Please, pay attention that the same ticket is not already created.
The same problem is described here: https://github.com/reportportal/reportportal/issues/1876

The issue has already been fixed and will be released in the **5.7.5 version**.
As a workaround, please, remove cookies or use incognito window.

I hope this information will help you! And thank you for your contribution!
I am closing the ticket as duplicate. The progress can be tracked using the ticket link mentioned in this message.
