### ISSUE TITLE
Test case steps as a part of Defect Description

### ISSUE THREAD

**Issue by ksuglotova** [reportportal/reportportal#190]
Received from Andrew Patin

It would be great to create the test case steps to reproduce bug, i.e. choose steps (test items) before bug and add them to the Description as a test case steps. As a user, I would like to choose what steps should be added as test case steps.

**Comment by avarabyeu** [comment]
which agent is used? java-based agent already support extensions so it can be customized on client side.

**Comment by DzmitryHumianiuk** [comment]
@andrey-patin really custom thing.
should be done via client-side extension. not server
