### ISSUE TITLE
easiest way to send test artifacts as attachments 

### ISSUE THREAD

**Issue by sanbhattdeep** [reportportal/reportportal#1900]
Hi,

Am using playwright with pytest and my test run will generate test logs and test trace (consisting of zip files) in different folders like this
![image](https://user-images.githubusercontent.com/99815301/208427574-50af41c8-8e01-4b90-a705-307df2018c2e.png)

i want to upload the contents of test_logs and trace_results folders to report portal so that i can view them under attachments under the launch
![image](https://user-images.githubusercontent.com/99815301/208427969-6ff134e2-11d2-4ca5-a39b-3bbef8d89f9a.png)

**Comment by DzmitryHumianiuk** [comment]
@HardNorth do we have an examples for sending attachements for the pytest?

**Comment by DzmitryHumianiuk** [comment]
@sanbhattdeep https://github.com/reportportal/agent-python-pytest#examples
