### ISSUE TITLE
/v1/{projectName}/item API endpoint not returning all items

### ISSUE THREAD

**Issue by avd1989** [reportportal/reportportal#1901]
The /v1/{projectName}/item API endpoint is not returning all items

The endpoint doesn't specify that the launchId as required (which could be an improvement - known when trying without it).
After specifying the project name and the launchId, the response does not contain all the items that belong to the launch. I am getting 20 out of the 77 that exist in the launch.

All items should that belong to the launch should be retrieved

**Comment by DzmitryHumianiuk** [comment]
@avd1989 this endpoint returns paged response.
you can either specify the page size (300 is maximum) or iterate pages.

This is a common pattern for the data at scale.
Just image that some launches may contain 15000+ test cases...


`/api/v1/{project}/item/v2?page.page=1&page.size=50`
- `page.page`
- `page.size`

this is the way to control pages and page size.

and this request always returns your positions on the page.
Check the tail of the JSON response.
```json
"page":{
    "number":1,
    "size":50,
    "totalElements":190,
    "totalPages":4
}
```
