### ISSUE TITLE
report portal sso config

### ISSUE THREAD

**Issue by hamzarezgui** [reportportal/reportportal#1902]
Hello,

How can we generate the metadata xml file for sso config please ?
Thank you for the help !

Regards

**Comment by DzmitryHumianiuk** [comment]
@hamzarezgui i guess the sso tool should generate this, not the RP.

**Comment by alena-babrova** [comment]
Hello @hamzarezgui,
Could you please tell me if the issue is still relevant for you? Have you managed to configure?

**Comment by alena-babrova** [comment]
Dear @hamzarezgui,
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
