### ISSUE TITLE
How To Backup And Restore Data

### ISSUE THREAD

**Issue by Rickdickulous** [reportportal/reportportal#1906]
I'm trying to figure out how to preserve and restore our data.  I'm trying to do it as though I'm starting from a brand new instance with only the backup.sql file. This is on a linux VM with Report Portal deployed from Docker.

I'm trying to follow this documentation: https://reportportal.io/docs/Maintain-commands-Cheat

My steps are:
1. Start up existing RP instance.
2. Stop other services as described here: https://github.com/reportportal/reportportal/issues/1345 
3. Run the data dump command get the backup.sql file from here: https://reportportal.io/docs/Maintain-commands-Cheat
   a. Note - I tried the backing up and cleaning up the data in both orders and it didn't work either time for different reasons.
5. Rename my data folder to something else and create a new data folder with the data/elasticsearch folder and permissions as described here: https://reportportal.io/docs/Deploy-with-Docker.
6. Start report-portal application using `docker-compose -p reportportal up -d --force-recreate`.
7. Stop other services.
8. Run restore data command.

What am I missing or doing wrong here? How is backup and restore intended to work and be performed?

**Comment by hlebkanonik** [comment]
Hi @Rickdickulous, your decision is correct. 

To effectively backup ReportPortal data, it's important to create backups of both the database (postgres) and binary storage (minio). 

In a Docker-based setup, it is enough to back up the directory containing the docker-volumes. For a database volume, this directory would be `./data/postgresql`, and for binary storage, it would be `./data/storage`.

The backup process follows Docker principles.

----
**Example of database backup:**
1. Copy volume:
```
cp -r ./data/postgresql ./data/postgresql-restored
```

2. Change the volume path [here](https://github.com/reportportal/reportportal/blob/v23.2/docker-compose.yml#L402)
```yaml
  postgres:
    volumes:
      -./data/postgresql-restored:/var/lib/postgresql/data
```

3. Redeploy ReportPortal:
```
docker compose up -d --force-recreate
```

**Comment by alena-babrova** [comment]
Hello @Rickdickulous,

Could you please tell me if your request is resolved and I can close the ticket?

**Comment by Rickdickulous** [comment]
I don't think I was ever able to get the backup procedure to work. The link to https://reportportal.io/docs/Maintain-commands-Cheat returns 404 now. I would recommend providing a link to the official backup and restore procedure documentation as part of closing this ticket. Thanks.

**Comment by alena-babrova** [comment]
Dear @Rickdickulous,

Try to use this documentation for your purposes:
https://reportportal.io/docs/reportportal-configuration/ReportPortalBackupRestoreGuide/

**Comment by alena-babrova** [comment]
Dear @Rickdickulous,

Could you please tell me if you have managed to solve the issue? Is the information from above helpful for you?

**Comment by alena-babrova** [comment]
Dear @Rickdickulous,

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
