### ISSUE TITLE
Postgres getting full and services are not able to write anything on db . 

### ISSUE THREAD

**Issue by samagarw** [reportportal/reportportal#1909]
After every 10 days or so we frequently see that the postgres is getting full and the services are not able to write anything on postgres . 

We have changed the settings of each project  and allowed only 7 days retention but i think the automatic cleaning of data is not working in reportportal . 

Can you please help us ? How we can clean up the data and make sure this issue doesn't occur ? The jobs pod is running but not cleaning up the data .

**Comment by irynakozak2** [comment]
@samagarw Hi! It's important to mention that PostgreSQL doesn't allow to reclaim of the physical storage on the disk after deleting the data by retention jobs. VACUUM FULL and then VACUUM ANALYZE are essential options that should be done manually at the maintenance window to reclaim the PostgreSQL storage. Please check our guide on how to perform it [here](https://reportportal.io/docs/How-to-clean). 
To make sure, that ReportPortal jobs are working correctly, please connect to the ReportPortal PostgreSQL database using any suitable tool and send the result of the following query:
`select * from shedlock;`

**Comment by samagarw** [comment]
@irynakozak2  : 

Output of the command : 

`reportportal=> select * from shedlock;
           name            |         lock_until         |         locked_at          |              locked_by
---------------------------+----------------------------+----------------------------+-------------------------------------
 calculateAllocatedStorage | 2022-10-14 15:25:00.976375 | 2022-10-14 15:25:00.266933 | reportportal1-jobs-584d5b6785-72zxh
 cleanLog                  | 2022-10-14 00:00:24.609443 | 2022-10-14 00:00:00.00255  | reportportal1-jobs-584d5b6785-g5kpr
 cleanLaunch               | 2022-10-14 00:01:19.109934 | 2022-10-14 00:00:24.614085 | reportportal1-jobs-584d5b6785-g5kpr
 cleanStorage              | 2022-10-14 00:01:23.11615  | 2022-10-14 00:01:19.115315 | reportportal1-jobs-584d5b6785-g5kpr
 cleanAttachment           | 2022-10-14 00:01:23.194516 | 2022-10-14 00:01:23.124898 | reportportal1-jobs-584d5b6785-g5kpr
 cleanMaterializedView     | 2022-10-14 00:01:23.299376 | 2022-10-14 00:01:23.29152  | reportportal1-jobs-584d5b6785-g5kpr`

**Comment by irynakozak2** [comment]
@samagarw hi, thank you for the data provided. I see, that all required jobs are executed properly. To make the database storage clean up from the dead tuples which still persist in the database after jobs execution(mentioned above). Please consider making it periodically in the maintenance window and/or increasing the storage capacity.
My recommendation is also to check the `chunk_size` value in the service-jobs deployment: if you have a lot of attachments reported, consider increasing that value from 1000(by default) up to 200000 to have a possibility to clean up much more attachments per 1 execution of the `cleanStorage`.

**Comment by irynakozak2** [comment]
@samagarw hi!
long time no hear from you, so we'll close the issue for now.
Just in case you still have the issue, please, provide more details as describes in comment above.
