### ISSUE TITLE
Is there any support for alternative MQ Platforms other than RabbitMq?

### ISSUE THREAD

**Issue by sagardeo2105** [reportportal/reportportal#1911]
As per my understanding, RabbitMQ is a pre-requisite to run Reportportal. Can any other Messaging or event streaming platform be used instead, for eg: IBM MQ or Kafka?

**Comment by alena-babrova** [comment]
Hello @sagardeo2105,
Thank you for being interested in ReportPortal.

As for now, RabbitMQ is the pre-requisite with no other options. All the official information regarding installation process and requirements can be found here:
https://reportportal.io/docs/category/installation-steps
