### ISSUE TITLE
Cloud Jira Integration Post Issue is not Coming 

### ISSUE THREAD

**Issue by vaibhavshukl12** [reportportal/reportportal#1912]
Hi @evjlobanova, Hope you are doing well.
I integrated the Cloud Jira with Report Portal.
Integration is done successfully, but Post Issue option is not enabled .
Configuration option is not coming also.
![image](https://user-images.githubusercontent.com/49065599/210734943-c707357b-60bc-4e6e-84ad-9f9bc08148d5.png)
![image](https://user-images.githubusercontent.com/49065599/210735149-7fe2fd41-27d9-4116-8f45-fde4e1aaac1b.png)
![image](https://user-images.githubusercontent.com/49065599/210736670-04bc04b0-859f-40f8-bf43-930564801056.png)

RP Version--5.7.3
Jira Cloud Plugin--5.7.0,5.7.1 and 5.7.2(tried with all three versions )

Please help on this .

**Comment by DzmitryHumianiuk** [comment]
@VolhaKarenko could you please verify this?

**Comment by DzmitryHumianiuk** [comment]
might be related https://github.com/reportportal/plugin-bts-jira/issues/41

**Comment by alena-babrova** [comment]
Hi @vaibhavshukl12,

It turned out that Jira Cloud had changed their API and this is the root cause of the problem.
Now ReportPortal team is working on using the updated API for integration.

We are going to fix this asap in the nearest time.

**Comment by vaibhavshukl12** [comment]
Okay @alena-babrova .Thanks for the quick reply.
Waiting for the fix.

**Comment by vaibhavshukl12** [comment]
HI @alena-babrova Is there ETA for this fix

**Comment by alena-babrova** [comment]
Hello @vaibhavshukl12 
I have come with good news 😊
Jira Cloud plugin 5.7.3 with the fix is released.
You can it [here](https://github.com/reportportal/plugin-bts-jira-cloud/packages/1366483)

**Comment by vaibhavshukl12** [comment]
@alena-babrova Thanks so much for the quick fix and update.

**Comment by vaibhavshukl12** [comment]
@alena-babrova I checked again with the configuration getting same issue .Please check

**Comment by VolhaKarenko** [comment]
Hi @vaibhavshukl12, please try to remove the integration and set up a new one

**Comment by vaibhavshukl12** [comment]
Hi @VolhaKarenko Done the same thing .

**Comment by yaggarwal** [comment]
@VolhaKarenko 
Even I am facing the same thing.
I have removed and installed JIRA cloud pluin 5.7.3

seeing same issue and getting below exception

api_1               | 2023-01-19 04:20:30.172 ERROR 1 --- [nio-8585-exec-3] c.e.r.e.j.command.GetIssueFieldsCommand  : null
api_1               | 
api_1               | java.util.NoSuchElementException: null
api_1               | 	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1000)
api_1               | 	at com.epam.reportportal.extension.jira.command.GetIssueFieldsCommand.invokeCommand(GetIssueFieldsCommand.java:88)
api_1               | 	at com.epam.reportportal.extension.jira.command.GetIssueFieldsCommand.invokeCommand(GetIssueFieldsCommand.java:43)
api_1               | 	at com.epam.reportportal.extension.AbstractRoleBasedCommand.executeCommand(AbstractRoleBasedCommand.java:19)
api_1               | 	at com.epam.ta.reportportal.core.integration.impl.ExecuteIntegrationHandlerImpl.lambda$executeCommand$7(ExecuteIntegrationHandlerImpl.java:96)
api_1               | 	at java.base/java.util.Optional.map(Optional.java:265)
api_1               | 	at com.epam.ta.reportportal.core.integration.impl.ExecuteIntegrationHandlerImpl.executeCommand(ExecuteIntegrationHandlerImpl.java:88)
api_1               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
api_1               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
api_1               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
api_1               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
api_1               | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
api_1               | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
api_1               | 	at com.sun.proxy.$Proxy234.executeCommand(Unknown Source)
api_1               | 	at com.epam.ta.reportportal.ws.controller.IntegrationController.executeIntegrationCommand(IntegrationController.java:233)
api_1               | 	at com.epam.ta.reportportal.ws.controller.IntegrationController$$FastClassBySpringCGLIB$$255e9ef9.invoke(<generated>)
api_1               | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
api_1               | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.

**Comment by alena-babrova** [comment]
Hello @vaibhavshukl12 @yaggarwal
Yes, we've found the issue, and now we are going to fix this asap in the nearest time.
Thank you for your patience.

**Comment by vaibhavshukl12** [comment]
Okay @alena-babrova ,Thanks

**Comment by alena-babrova** [comment]
Dear @vaibhavshukl12 @yaggarwal 
We have reuploaded the new version of the plugin which contains the fix.

Could you please download Jira Cloud plugin 5.7.3 again (from [here](https://github.com/reportportal/plugin-bts-jira-cloud/packages/1366483), install it and recheck integration one more time?
Please, don't forget to uninstall the existing plugin before head.

**Comment by vaibhavshukl12** [comment]
@alena-babrova Thank you so much.
For the quick reply and fix.
Its working fine now

**Comment by alena-babrova** [comment]
@vaibhavshukl12 
You are welcome 😊
Thank you for your patience and sorry for the inconvenience!

**Comment by yaggarwal** [comment]
@vaibhavshukl12  Thanks for fixing and releasing quickly 👍

**Comment by Ishidres** [comment]
Thank you for the fix. I had the same issue even though I was also using the latest version v5.7.3. However. I downloaded the broken JAR file from Maven. Using this JAR I had the same issue like described here. When downloading the JAR from https://github.com/reportportal/plugin-bts-jira-cloud/packages/1366483 this issue does not apply anymore. In other words: maybe the Jira cloud integration plugin JAR file distibuted on Maven is outdated, even though it is also v5.7.3 ? @alena-babrova

**Comment by alena-babrova** [comment]
Hello @Ishidres,
Unfortunately, no. We've made investigations and found out that there were changes with customs fields on Jira Cloud side. It's another issue.
Please, follow Jira Cloud Post issue related discussion in https://github.com/reportportal/plugin-bts-jira-cloud/issues/36
And please try to install the plugin as described in the thread ([plugin-bts-jira-cloud-5.7.4.zip](https://github.com/reportportal/plugin-bts-jira-cloud/files/12792687/plugin-bts-jira-cloud-5.7.4.zip)) and check if it helps.

**Comment by Ishidres** [comment]
Sorry, maybe I didn't explain correctly: using the .JAR release on https://github.com/reportportal/plugin-bts-jira-cloud/packages/1366483 works perfectly fine and as expected, however I just noticed that the same .JAR version on Maven still has the same problem where the "Post link" does not appear but the release on GitHub works! :smiley::+1:

**Comment by alena-babrova** [comment]
Dear @Ishidres, I guess I didn't understand it correctly 😔
Thank you very much for highlighting this - we will check it.
