### ISSUE TITLE
Skipped tests impact on passing rate in the launch and widgets

### ISSUE THREAD

**Issue by vfedirko5** [reportportal/reportportal#1914]
**Describe the bug**
When the test is marked as skipped it will impact the passing rate for the launch.

**Expected behavior**
I hope that "passed" means only tests that successfully completed. If the test was initially marked as "ignore" it should not impact the passing rate. I guess it's skipped rate.
in the case is a feature - could we create some Settings for the project how to include skipped tests into passing rate or exclude from it
 
**Screenshots**
![v3ZJW37DrV](https://user-images.githubusercontent.com/97690476/210884689-f156a360-8dd4-4571-bca8-dce16508b87e.png)

**Versions:**
 - Version of RP 5.7.3

**Comment by AskhatAbelseitov** [comment]
Hello @vfedirko5,

Your remark is really important and timely. 

Indeed, now the logic looks exactly like that, test cases with the ‘Skipped’ status are considered as ‘Not passed’.

RP team plans to start working on improving the functionality of the widget, including adding a new function related to the selection or exclusion of ‘Skipped’ tests from the overall rate.

This option will be added in one of the future versions of the RP.

I hope this information will be useful for you!

**Comment by Kozovskaya** [comment]
Hello @vfedirko5 
The ReportPortal version 24.2 is already released!
I'm closing the issue.
Thank you for using ReportPortal!

**Comment by dgur** [comment]
Hello, I am using e ReportPortal version 24.2.1 I don;t see this fix. Can somebody explain how I enable  this feature?
In the Health Check Table View - I want to see Launches that have only Skipped,  No failed  - Marked as Passed

**Comment by Kozovskaya** [comment]
Hello @dgur 
The Component Health widget can either include Skipped test in statistic or exclude them.
Skipped test are included by default in the widget statistics but you can exclude them by selecting the checkbox. See below:

![Image](https://github.com/user-attachments/assets/5eb4ebd1-5a02-428f-b8bd-fe1ed1ba160e)

**Comment by dgur** [comment]
<img width="862" alt="Image" src="https://github.com/user-attachments/assets/f7a1648c-9c8d-404d-b656-9f1f72c9e64a" />
@Kozovskaya  hi Viktoria, unfortunately, I don't see that check box... anything I need  to enable it?

**Comment by Kozovskaya** [comment]
@dgur
The feature doesnn't require any additional efforts from your side.
could you please share your the service versions? You can find them on the login page

**Comment by dgur** [comment]
<img width="503" alt="Image" src="https://github.com/user-attachments/assets/1e1e63da-b92d-40d5-8689-b3a5335ce65d" />

Added @Kozovskaya
