### ISSUE TITLE
Test items (steps) with the same name but different position in a suite (test) to show separately

### ISSUE THREAD

**Issue by ksuglotova** [reportportal/reportportal#192]
Received from Andrew Patin

I would like to see the same test steps but in different places in a test item as separately from each other. In other words, to see the several items with the reason 'There are several items with the same names, descriptions and tags' in inconvenient because in our project may be tens of such steps in one test.

**Comment by avarabyeu** [comment]
custom test IDs can help here.

**Comment by avarabyeu** [comment]
@ksuglotova now you can specify your custom uniqueID for the test. Details in documentation will be coming shortly.

**Comment by ksuglotova** [comment]
@avarabyeu Andrey, this request was from Andrey Patin (epam)
