### ISSUE TITLE
Pytest-BDD results in Reportportal

### ISSUE THREAD

**Issue by ghost** [reportportal/reportportal#1920]
Hi Team, 

We are using Pytest-BDD framework for test automation. We are not able integrate our results into ReportPortal. 
Since this tool is developed on top of Pytest, we are able to upload results in Pytest format but that is not including scenario & steps used in BDD format.

Can you please check if any quick solution available around this.

Thanks & Regards,
Deepa

**Comment by globaldeepa** [comment]
Hi Team , did you get a chance to look into this.

**Comment by alena-babrova** [comment]
We are closing the ticket since the requester has been deleted and there is no way to contact.
