### ISSUE TITLE
Azure pipelines runs doesn't displayed on the report portal

### ISSUE THREAD

**Issue by BraveLittleTapok** [reportportal/reportportal#1921]
Hello!

I add configuration of the report-portal in my project, such as reportPortal.properties and pom.xml as integration from allure and everything working fine for the local run - it shows on RP, but when our tests runs on azure pipelines nothing shows on RP. 
Basically azure run our test using mvn command in the script file, like `mvn clean test` , which should start to send our test run to RP, but nothing happens. The same mvn command from local run  is working for RP, run is displayed on the portal.

 I don't think we need additional properties in azure-pipelines file , am I wrong?

**Comment by goblinmaks** [comment]
First, check connection from your AzDO to reportportal instance. 
What of RP instance do you use ?

**Comment by alena-babrova** [comment]
Hello @BraveLittleTapok,
Could you please tell me if the issue is still relevant for you?

**Comment by alena-babrova** [comment]
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
