### ISSUE TITLE
Lack of attribute validation leads to: Unclassified error [null]

### ISSUE THREAD

**Issue by dus7eh** [reportportal/reportportal#1924]
**Describe the bug**
Use the `/v2/{projectName}/launch` API call and in json body pass attribute without `key`, for example:
```
{
  "attributes": [
    {
      "some_entry": "string",
      "system": true,
      "value": "string"
    } // this entry is missing a `key` key
  ],
  "description": "string",
  "mode": "DEFAULT",
  "name": "string",
  "rerun": true,
  "rerunOf": "string",
  "startTime": "2023-01-12T10:45:35.204Z"
}
```
This call actually responds with an `uuid`. However, when navigating to launches section in the UI nothing is displayed (not even previous launches) except an unclassified null error.
In the api service error log is printed:

```
api_1               | java.lang.NullPointerException: null
api_1               | 	at java.base/java.util.ImmutableCollections$Set12.contains(ImmutableCollections.java:524)
api_1               | 	at com.epam.ta.reportportal.ws.converter.resource.handler.attribute.launch.LaunchResourceMetadataAttributeUpdater.lambda$handle$2(LaunchResourceMetadataAttributeUpdater.java:44)
api_1               | 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
api_1               | 	at com.epam.ta.reportportal.ws.converter.resource.handler.attribute.launch.LaunchResourceMetadataAttributeUpdater.handle(LaunchResourceMetadataAttributeUpdater.java:43)
api_1               | 	at com.epam.ta.reportportal.ws.converter.resource.handler.attribute.launch.LaunchResourceMetadataAttributeUpdater.handle(LaunchResourceMetadataAttributeUpdater.java:33)
```

Further api calls to get some more information about the corrupted run (having its uuid) end up with error 500 and body:
```
{
  "errorCode": 5000,
  "message": "Unclassified error [null]"
}
```
**Workaround to get things working back again**
Deleting the corrupted launch via API was possible. However I don't know how to efficiently get the launch ID (int64) needed for deletion from the uuid I was given in the first place. I was able to get ID (int64) from my previous runs via an API call with uuid and then guessed that my corrupted launch ID value is simply incremented.

**Expected behavior**
Mentioned api call should be rejected - validated before responding OK and storing it internally.

**Screenshots**

**Versions:**
 - Ubuntu 22, Chrome
 - Version of RP: API Service: 5.7.3;Index Service: 5.7.3;Jobs Service: 5.7.3;Authorization Service: 5.7.3;Service UI: 5.7.3;

**Comment by VolhaKarenko** [comment]
Hi @dus7eh, thank you for pointing this out! Actually, it is possible to create an attribute with value only, so the API call should not be rejected, but the error on the launches page is definitely a bug.
I managed to reproduce it and the issue is added to the backlog

**Comment by alena-babrova** [comment]
Hello @dus7eh,
Please, do not use the parameter **"system"** in attributes: skip it or always set to false.
e.g.
`{
  "attributes": [
    {
      "value": "string"
    }
  ],
 ...`
Anyway, we are going to fix the issue. Before that, please, follow the instructions above.

Thank you for your contribution!

**Comment by dus7eh** [comment]
Thanks for the tip @alena-babrova 
In that case maybe it would be also a good idea to set `"system": false` as a default value in swagger sample payloads.

**Comment by alena-babrova** [comment]
Dear @dus7eh,
Yes, we will discuss with our team how to make it better.
Thanks for the advice!

**Comment by hymanallan** [comment]
We've also seen in one out of many instances.
##[error]Invoke-WebRequest : {"errorCode":5000,"message":"Unclassified error [JSON conversion problem: Invalid UTF-8 start byte 
0xa0; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 start byte 0xa0\n a

**Comment by MaryiaRymarchyk** [comment]
Hello everyone, the fix is available with the [latest version of RP ](https://reportportal.io/docs/releases/Version23.2#5-released-versions).
Ticket will be closed, if there are still some concerns - feel free to open new ticket.
