### ISSUE TITLE
How could I deploy ReportPortal without ElasticSearch? With OpenSearch

### ISSUE THREAD

**Issue by elife1** [reportportal/reportportal#1925]
Due to sanctions, I can't use elasticsearch. Can I use opensearch, if so, what will dockercompose look like

**Comment by irynakozak2** [comment]
@elife1 hi, about 2 years ago we made high-level verification from our side that in terms of performance and functionality OpenSearch can be used instead of Elastic. For the latest versions, we haven't been tested it yet, but that task is already in our backlog.

**Comment by DzmitryHumianiuk** [comment]
we gonna test OpenSearch in the next sprint.

**Comment by alena-babrova** [comment]
Dear @elife1,

Please be informed that we have released version 24.1 that supports OpenSearch.
You can find information [here](https://reportportal.io/docs/releases/Version24.1#3-technical-improvements).
