### ISSUE TITLE
Rabbitmq version seems not updated for v5.7.3 in k8s 

### ISSUE THREAD

**Issue by babantax** [reportportal/reportportal#1926]
Good morning, 
I´m trying to deploy latest version 5.7.3 in kubernetes. I´m a little confuse because [according with the release notes](https://github.com/reportportal/reportportal/releases/tag/5.7.3), Rabbitmq has been updated to version 3.10.7. But if I [check the chart](https://github.com/reportportal/kubernetes/blob/reportportal-5.7.3/reportportal/Chart.yaml), I see the same rabbitmq version (7.5.6) as we have until now. 

Am I missing something? Which rabbitmq chart version should I use?

Thanks a lot in advance

![image](https://user-images.githubusercontent.com/52815118/213642281-3aed64e2-723e-4ed6-ac3b-8bbb9808f597.png)

![image](https://user-images.githubusercontent.com/52815118/213642329-94578bc3-0215-4643-b37f-50f4be58abb3.png)

**Comment by irynakozak2** [comment]
@Gl-Canon Hleb, could you please check?

**Comment by irynakozak2** [comment]
@babantax Hi! I suggest you to upgrade your ReportPortal version and [charts to 5.7.4](https://github.com/reportportal/kubernetes/blob/reportportal-5.7.4/reportportal/Chart.yaml). We have updated the RabbitMQ version to the 10.3.9 here.

Thank you and waiting for your reply.

**Comment by irynakozak2** [comment]
@babantax Hi! 
Long time no hear from you, so we'll close the issue for now.
Just in case you still have the issue, please, provide more details and create a new one.
Thank you.
