### ISSUE TITLE
Report portal page stuck on loading after installation on Ubuntu 22.04, k3s v1.24+k3s

### ISSUE THREAD

**Issue by assiakhateeb** [reportportal/reportportal#1927]
I have installed report portal according to the instructions provided in this documentation: [Install ReportPortal](https://epam.github.io/edp-install/operator-guide/install-reportportal/) on k3s v1.24+k3s1 running on an Ubuntu 22.04 (64-bit) VM.

Access to the "report-portal-reportportal-ui" service has been established using kubectl port forwarding on port 8080, however, the page is stuck on loading. No errors have been detected in the pods logs and all pods are running.

CPU and memory usage have been checked and no issues have been identified.

**Steps to Reproduce:**

- Installation of report portal using the above-mentioned documentation

- Connection to "report-portal-reportportal-ui" service using kubectl port forwarding on port 8080

**Expected Behavior:**

- The report portal page should load correctly

**Actual Behavior:**

- The report portal page is stuck on loading

**Environment:**

- Ubuntu 22.04 (64-bit)
- k3s v1.24.6+k3s1 (a8e0c66d)
- kubectl version 1.23.0 
- Helm version 3.10.2
- RP version 5.7.3

**Screenshots**
<img width="1346" alt="Screenshot 2023-01-22 at 19 25 25" src="https://user-images.githubusercontent.com/39053503/213930478-837f73dc-bcf0-4042-ac76-44803c38b8fd.png">

<img width="1340" alt="Screenshot 2023-01-22 at 19 25 57" src="https://user-images.githubusercontent.com/39053503/213930499-04fa084c-ee49-420a-9424-4c5dee444d33.png">

response from /info endpoint:
`{"build": { "version": "5.7.3", "branch": "a39dd17da9d14530c959bf3cab5826d6d4009238", "build_date": "2022-11-10T11:57:55+0000", "name": "Service UI", "repo": "reportportal/service-ui"}}`

**Comment by qtheya** [comment]
Hello. I got the same error. Setup:
- EKS 1.24
- AWS Rabbit MQ 3.10.10
- AWS RDS Postgres 13.9
- AWS OpenSearch 2.3
Allocated resources for each pod are:
request cpu 500m, ram 2Gi / limit cpu 2, ram 8Gi
so, this is not a case https://github.com/reportportal/reportportal/issues/1602#issuecomment-1224946622

**Comment by safredAAs** [comment]
Facing the same issue, any update?

**Comment by jpita** [comment]
increasing the RAM (solution from linked task) doesn't work?

**Comment by qtheya** [comment]
To which numbers? Lower version is working with these resource parameters.

**Comment by jpita** [comment]
No idea, just saw that it worked for other people on the other issue. 

Try to double of triple it ?

**Comment by assiakhateeb** [comment]
Solved in issue https://github.com/reportportal/kubernetes/issues/297
