### ISSUE TITLE
JIRA credentials (different from global setup) not working when posting an issue from RP.

### ISSUE THREAD

**Issue by quldude** [reportportal/reportportal#1928]
**Describe the bug**

1. In the post issue (to jira) page after entering my creds (different creds than the one used in global jira integration setup), I'm unable to post the issue. It looks like I have to use the same creds used in integration setup. Is it possible to use different creds?
2. Also, if I have a failed test linked to a jira bug and the bug gets closed, the jira status shown in RP does not show closed status instead remains in open status. Status does not get updated after a page refresh. It seems like there is some delay in getting the correct update. Is that expected?

**Expected behavior**

1. Should be able to use any jira creds to post issues.
![Capture](https://user-images.githubusercontent.com/21183880/214083227-b4cd37f4-0e01-45da-b0ed-94895d77a052.PNG)

3. Bug status should be updated in RP once updated in JIRA and on page refresh.
![Capture2](https://user-images.githubusercontent.com/21183880/214083230-2d3b22ac-7f07-4a70-b7c7-ad3ed0441b6d.PNG)

**Versions:**
 - OS, Browser = Any, chrome
 - Version of RP [find it under Login form, copy as is] = API Service: 5.7.3;Index Service: 5.7.3;Jobs Service: 5.7.3;Authorization Service: 5.7.3;Service UI: 5.7.3;
- JIRA Server version 5.7.2 (plugin)

**Comment by alena-babrova** [comment]
Hello @quldude,
Both described scenarios are not bugs.

1. Yes, you should enter the same credentials which you used to create the project/global integration. 
It is a legacy behaviour. It has been already fixed (the fields will be gone) and will be released in version 5.8.0.

2. Yes, you are right. But the sync doesn't happen every minute. Usually it takes about 15 minutes to update. And there are no improvements planned regarding this in the near future.

I'm closing the issue for now, but do not hesitate to get in touch in future.
Thank you!
