### ISSUE TITLE
Аpi service unable to load data from db

### ISSUE THREAD

**Issue by kendysh-plus** [reportportal/reportportal#1931]
https://user-images.githubusercontent.com/72374603/215443433-d3ec3ecb-2353-496c-bcd6-443e05312561.mp4

**Describe the bug**
The issue happens when a user is editing a type of test failure and after about 10 changes the API service stops working at all. We assumed that increasing the maximum number of connections of the DB connection pull could help us. We have increased max_connections from 100 (by default) to 800 in DB and increased the API and UAT services variables RP_DATASOURCE_MAXIMUMPOOLSIZE (API - 600, UAT - 150). However, even after these changes, the API is still  stuck after submissions about 60 changes.

**Versions:**
 - Version of RP [5.7.3]

**Comment by irynakozak2** [comment]
@evgscorp hi! Can you please describe in detail, what type of action takes a long time to download? Can you please consider my comment above and check the service analyzer, and optimal database configuration applied?

**Comment by evgscorp** [comment]
@irynakozak2 Hello. Thanks for the tip! The database tuning increased only number of submissions that the api-service can handle. **However, fixing connection issues from the service analyzer to the Elasticsearch really helps!**

**Comment by irynakozak2** [comment]
@evgscorp glad to hear, appreciate your feedback!

**Comment by kendysh-plus** [comment]
@irynakozak2 Thanks for your tip about Elasticsearch. We finally managed out how to solve the issue! BTW, why don't you add a condition that checks the Elasticsearch service ? It seems like now if Elasticsearch service is offline all connections to the database will be with 'transaction' status  after some user editing activity .

**Comment by irynakozak2** [comment]
@kendysh-plus glad to hear, appreciate your feedback! It's difficult to answer it right now, but I've raised a point with our DevOps engineer and update you with the resolution.

**Comment by kendysh-plus** [comment]
@irynakozak2 thx, it's very nice!

**Comment by irynakozak2** [comment]
@kendysh-plus Hi! We discussed your question about checks on Elasticsearch and we are going to add the set of checks for the services(especially, for the service-API and service-analyzer) after full logs migration to Elasticsearch (v5.8).
