### ISSUE TITLE
Pass credentials via URL

### ISSUE THREAD

**Issue by JasonMageeLQ** [reportportal/reportportal#1932]
If we wanted to display ReportPortal in an iframe, would it be possible to authenticate ourselves with the URL (either with a UUID or credentials)?

I've tried passing credentials in via http basic auth but that didn't seem to work for us -> http://user:pass@myreportportal.com

**Comment by alena-babrova** [comment]
Hello @JasonMageeLQ 
We are not going to implement something like this because passing credentials via URL is insecure.
You can use an existing POST end-point to authenticate and get an access token which you can use to work with ReportPortal.

**Comment by alena-babrova** [comment]
We are closing the ticket as we are not going to implement the feature request.
