### ISSUE TITLE
Clone dashboard

### ISSUE THREAD

**Issue by ksuglotova** [reportportal/reportportal#194]
Received from @ kostia.izotov Slack / reportportal / general

Can I clone a dashboard? 
**Use case:** there's a dashboard, I need another 10 similar ones but with slightly different filters (for other environments, suites, tests - Selenium/Rest/Unit) and shared dashboard shows the same launches. I need information about tests on higher and lower environments with different statistics.

**Comment by evjlobanova** [comment]
Duplicate of #784
