### ISSUE TITLE
Configuring custom hierarchy levels (pytest)

### ISSUE THREAD

**Issue by ehsaan-bhati** [reportportal/reportportal#1954]
I have certain set of tests running for multiple scenarios
All the test are visible on the single page with no segregation, I have to scroll to the entire list to look for particular test-case.

As of now by default the hierarchy level in Report Portal is fixed. >> file-name::class-name::test-name
Is there any configuration where I can define the hierarchy for better visibility ?

Like I am looking for something like below:
scenario-1::test1
scenario-1::test2
scenario-2::test1
scenario-2::test2

Any help here would be appreciated

P.S: I am a beginner in python-pytest

**Comment by DzmitryHumianiuk** [comment]
@ehsaan-bhati, ReportPortal displays data the way it's reported or, more precisely, how the reporter (in this case, pytest) sends it. 

So, if the data is sent in a Scenario-test structure, it will be displayed like that.

I apologize, but the question is quite broad, so I can only provide a general answer.

**Comment by alena-babrova** [comment]
Dear @ehsaan-bhati,
Could you please tell me if your question is still relevant, or you have already figured it out?
