### ISSUE TITLE
The performance of launch filter is too low 

### ISSUE THREAD

**Issue by JianLi-RH** [reportportal/reportportal#1955]
When we are using the filter function to filter launches, it always takes more than 10 seconds to get a key or value, it is not so friendly for us, can we just enter attribute key and value as a filter?

For example, below screenshot shows that when I enter an attribute key to the filter, it takes 12 seconds to show the available keys, similarly, I have to wait 10+ seconds to select a value.

![image](https://user-images.githubusercontent.com/83053288/225243042-2b020b29-98db-4ece-aed6-79e412ed465a.png)

**Comment by JianLi-RH** [comment]
hi @irynakozak2
Here are my answers:

1. ReportPortal version you use, 
**[jianl] Build: 5.7.2**

As I am just a regular user, I can't answer following questions, I can only say is the RP instance is https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow, maybe @rujuta or @knarra can answer them.

2. the deployment type: Docker or Kubernetes, services health,
4. hardware specification: CPU, RAM per service/per installation, disk type - SSD or HDD,
5. data amount in the PostgreSQL database,
6. PostgreSQL configuration(it can be postgres.conf file or Parameter Group if you are using PostgreSQL as a service),
7. launches count in the project, and total db_size.

**Comment by JianLi-RH** [comment]
Adding @Josiah England ***@***.***> to the thread because they would
be knowing all the internal details that has been requested below.

@Josiah England ***@***.***> Could you please help provide the
requested information?

**Comment by irynakozak2** [comment]
@JianLi-RH hi!
Long time no hear from you, so we'll close the issue for now.
Just in case you still have the issue, please, provide more details as described in the comment above, reopen that issue, or create a new one.

**Comment by JianLi-RH** [comment]
All right. Seems no one from our side can answer those questions. Thank you all the same.
