### ISSUE TITLE
A single dashboard to display widgets/metrics for multiple projects

### ISSUE THREAD

**Issue by arunkumargceb** [reportportal/reportportal#1957]
As A COP (Centre of Practice) team, we need to monitor the metrics as widgets for multiple projects in a single dashboard. Is there any existing feature or have any plan in the upcoming release?

To see widgets of another project, as an admin, need to get added to the project and then navigate to Dashboard and then widgets. For multiple projects, we need to do the same multiple times.

**Comment by Kozovskaya** [comment]
Hi @arunkumargceb! Thanks for your request! Could you please specify? Do you want to see on the Dashboard just separate widgets per project? Or do you want to have a widget that will show info about several projects at once? If you could provide specific metrics you need for the widget, that would be great!

**Comment by MaryiaRymarchyk** [comment]
Hi @arunkumargceb , we already have similar request here #193 
It is planned for 5.9 version release.

**Comment by MaryiaRymarchyk** [comment]
I'll close current ticket as duplicate, however if you have other questions - feel free to reopen or create a new one.
