### ISSUE TITLE
Email notification rule prevents submition

### ISSUE THREAD

**Issue by iKozzz** [reportportal/reportportal#196]
1. Go to "../settings/notifications"
2. set "E-mail Notifications"  to ON
3. setup everything and add at least 1 rule.
4. Submit
(emails should work now)
5. go to "../settings/notifications" again
6. edit rule to not valid (clear "Recipients")
7. set "E-mail Notifications" to OFF
8. Submit

Actual - Error will appear regarding incorrect rule settings.
Expected - remove any rules behind the scene and save "E-mail Notifications" state (OFF) when Submit button is clicked.

severity: minor

**Comment by e-olga** [comment]
As for today, all notifications rules are saved on backend side. The option ON/OFF works only as switcher to enable or disable it. 
So, the saved rule should be correct. One of required parameter is to have at least one recipient for the rule.
In case no any user is added to the rule it assumed as invalid. And lead to the error on submit operation even with OFF selected.
So, with new workflow of Email notification option the issue above is not a bug, but work as designed.

**Comment by DzmitryHumianiuk** [comment]
work as designed
