### ISSUE TITLE
Logs not reflecting in report portal after integrating with log4j2

### ISSUE THREAD

**Issue by surajsharmagit** [reportportal/reportportal#1960]
Hello` Team, I'm trying to print log.info messages along with other log messages in reporting portal. I have included all the relevant dependencies . Please advice what I'm missing here

log4j.properties

```
# Send logs into Report Portal
log4j.rootLogger = INFO, reportportal

log4j.appender.reportportal=com.epam.ta.reportportal.log4j.appender.ReportPortalAppender
log4j.appender.reportportal.layout=org.apache.log4j.PatternLayout
log4j.appender.reportportal.layout.ConversionPattern=[%d{HH:mm:ss}] %-5p (%F:%L) - %m%n
```

POM.XML

```
<?xml version="1.0" encoding="UTF-8"?>


<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.eoriginal.esign</groupId>
    <artifactId>eSignUI</artifactId>
    <version>1.1.0-SNAPSHOT</version>
    <build>
<!--        <plugins>-->
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-surefire-plugin</artifactId>-->
<!--                <version>3.0.0-M4</version>-->
<!--                <configuration>-->
<!--                    <parallel>classes</parallel>-->
<!--                    <threadCount>2</threadCount>-->
<!--                </configuration>-->
<!--            </plugin>-->
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-compiler-plugin</artifactId>-->
<!--                <version>3.10.1</version>-->
<!--                <configuration>-->
<!--                    <source>1.8</source>-->
<!--                    <target>1.8</target>-->
<!--                    &lt;!&ndash;                    <encoding>UTF-8</encoding>&ndash;&gt;-->
<!--                </configuration>-->
<!--            </plugin>-->
<!--        </plugins>-->
        <testResources>
            <testResource>
                <directory>src/test/java/com/esign/input</directory>
                <filtering>true</filtering>
            </testResource>
        </testResources>
    </build>
    <properties>
        <cucumber.version>7.8.1</cucumber.version>
        <username>usernameValue</username>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>19</maven.compiler.source>
        <maven.compiler.target>19</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>1.28.1</version>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-cucumber6</artifactId>
            <version>5.1.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-logback</artifactId>
            <version>5.1.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-testng</artifactId>
            <version>7.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>gherkin</artifactId>
            <version>25.0.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.4.5</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>7.8.1</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.9.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>7.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <version>7.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.browserstack</groupId>
            <artifactId>browserstack-local-java</artifactId>
            <version>1.0.6</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
        </dependency>
        <dependency>
            <groupId>net.masterthought</groupId>
            <artifactId>cucumber-reporting</artifactId>
            <version>5.7.4</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>3.1.0</version>
        </dependency>
                <dependency>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-simple</artifactId>
                    <version>2.0.5</version>
                </dependency>
                <dependency>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                    <version>2.0.5</version>
                </dependency>
                <dependency>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                    <version>2.0.5</version>
                </dependency>
    </dependencies>
</project>

```
log4j.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration packages="com.epam.ta.reportportal.log4j.appender" status="WARN">
    <Appenders>
        <Console name="ConsoleAppender" target="SYSTEM_OUT">
            <PatternLayout
                    pattern="%d [%t] %-5level %logger{36} - %msg%n%throwable"/>
        </Console>
        <ReportPortalLog4j2Appender name="ReportPortalAppender">
            <PatternLayout
                    pattern="%d [%t] %-5level %logger{36} - %msg%n%throwable"/>
        </ReportPortalLog4j2Appender>
    </Appenders>
    <Loggers>
        <Root level="INFO">
            <AppenderRef ref="ConsoleAppender"/>
            <AppenderRef ref="ReportPortalAppender"/>
        </Root>
        <Logger name="com.epam.reportportal" level="INFO" additivity="false">
            <AppenderRef ref="ConsoleAppender"/>
            <AppenderRef ref="ReportPortalAppender"/>
        </Logger>
        <Logger name="binary_data_logger" level="DEBUG" additivity="false">
            <AppenderRef ref="ReportPortalAppender"/>
        </Logger>
    </Loggers>
</Configuration>

```

TESTRUNNER

```
package com.esign.steps;


import io.cucumber.junit.Cucumber;
import io.cucumber.testng.AbstractTestNGCucumberTests;
import io.cucumber.testng.CucumberOptions;
import org.json.simple.parser.ParseException;
import org.junit.runner.RunWith;
import org.testng.annotations.BeforeSuite;

import java.io.IOException;

@RunWith(Cucumber.class)
@CucumberOptions(plugin = {"pretty", "html:report.html", "com.epam.reportportal.cucumber.ScenarioReporter"},
        features = {"src/test/java/com/esign/features"},
        glue = {"com/esign/steps"}, tags = "@signingpackagetest", dryRun = false )

public class TestRunner extends AbstractTestNGCucumberTests {
    @BeforeSuite
    public void data() throws IOException, ParseException, InterruptedException {

    }
}
```

CONSOLE 

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.esign.steps.TestRunner
SLF4J: Class path contains multiple SLF4J providers.
SLF4J: Found provider [ch.qos.logback.classic.spi.LogbackServiceProvider@3cb5cdba]
SLF4J: Found provider [org.slf4j.simple.SimpleServiceProvider@56cbfb61]
SLF4J: Found provider [org.slf4j.reload4j.Reload4jServiceProvider@1134affc]
SLF4J: See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual provider is of type [ch.qos.logback.classic.spi.LogbackServiceProvider@3cb5cdba]
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@1f554b06
13:12:31.526 [main] DEBUG org.testng.internal.Graph - [Graph] ADDING NODE TestRunner.data()[pri:0, instance:null] -1361929145
13:12:31.529 [main] DEBUG org.testng.internal.Graph - [Graph] ================ SORTING
13:12:31.532 [main] DEBUG org.testng.internal.Graph - [Graph] =============== DONE SORTING
13:12:31.533 [main] DEBUG org.testng.internal.Graph - [Graph] ====== SORTED NODES
13:12:31.533 [main] DEBUG org.testng.internal.Graph - [Graph] ====== END SORTED NODES
13:12:31.538 [main] DEBUG org.testng.internal.Graph - [Graph] ADDING NODE AbstractTestNGCucumberTests.setUpClass(org.testng.ITestContext)[pri:0, instance:null] -39
3284817
13:12:31.538 [main] DEBUG org.testng.internal.Graph - [Graph] ================ SORTING
13:12:31.538 [main] DEBUG org.testng.internal.Graph - [Graph] =============== DONE SORTING
13:12:31.538 [main] DEBUG org.testng.internal.Graph - [Graph] ====== SORTED NODES
13:12:31.538 [main] DEBUG org.testng.internal.Graph - [Graph] ====== END SORTED NODES
13:12:31.541 [main] DEBUG org.testng.internal.Graph - [Graph] ADDING NODE AbstractTestNGCucumberTests.tearDownClass()[pri:0, instance:null] 1523153566
13:12:31.541 [main] DEBUG org.testng.internal.Graph - [Graph] ================ SORTING
13:12:31.541 [main] DEBUG org.testng.internal.Graph - [Graph] =============== DONE SORTING
13:12:31.542 [main] DEBUG org.testng.internal.Graph - [Graph] ====== SORTED NODES
13:12:31.542 [main] DEBUG org.testng.internal.Graph - [Graph] ====== END SORTED NODES
13:12:31.548 [main] DEBUG org.testng.internal.Graph - [Graph] ADDING NODE TestRunner.data()[pri:0, instance:com.esign.steps.TestRunner@131774fe] 1050173847        
13:12:31.548 [main] DEBUG org.testng.internal.Graph - [Graph] ================ SORTING
13:12:31.549 [main] DEBUG org.testng.internal.Graph - [Graph] =============== DONE SORTING
13:12:31.549 [main] DEBUG org.testng.internal.Graph - [Graph] ====== SORTED NODES
13:12:31.549 [main] DEBUG org.testng.internal.Graph - [Graph] ====== END SORTED NODES
13:12:31.550 [main] DEBUG org.testng.internal.Graph - [Graph] ADDING NODE AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.test
ng.FeatureWrapper)[pri:0, instance:com.esign.steps.TestRunner@131774fe] -830054961
13:12:31.550 [main] DEBUG org.testng.internal.Graph - [Graph] ================ SORTING
13:12:31.550 [main] DEBUG org.testng.internal.Graph - [Graph] =============== DONE SORTING
13:12:31.550 [main] DEBUG org.testng.internal.Graph - [Graph] ====== SORTED NODES
13:12:31.550 [main] DEBUG org.testng.internal.Graph - [Graph] ====== END SORTED NODES
13:12:33.010 [main] INFO com.epam.reportportal.service.Launch - Rerun: false
13:12:33.730 [rp-io-1] DEBUG com.epam.reportportal.service.Launch - ReportPortal launch with ID '971944b2-4b45-43c1-954c-9b173b17d666' has been created
13:12:33.730 [rp-io-1] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Launch start successfully completed

@signingpackagetest
Scenario: Test to validate package created using API                  # src/test/java/com/esign/features/smoke/SigningRoom.feature:105
13:12:34.105 [main] INFO com.esign.steps.Hooks - Before step
13:12:34.105 [rp-io-4] DEBUG com.epam.reportportal.service.Launch - ReportPortal item with ID '35301847-fe39-41d7-8faf-52a03b0f09ed' has been created
13:12:34.105 [rp-io-4] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Start test item successfully completed
13:12:34.105 [rp-io-4] DEBUG com.epam.reportportal.service.Launch - Starting test item...rp-io-4
13:12:34.105 [main] INFO com.esign.steps.Hooks - Starting scenario "Test to validate package created using API" at 2023-03-21T07:42:34.105328Z
13:12:34.133 [rp-io-12] DEBUG com.epam.reportportal.service.Launch - ReportPortal item with ID '2fcf8ada-f4af-4963-b937-a84fd069aefa' has been created
13:12:34.133 [rp-io-12] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Start test item successfully completed
13:12:34.133 [rp-io-12] DEBUG com.epam.reportportal.service.Launch - Starting test item...rp-io-12
13:12:34.178 [rp-io-13] DEBUG com.epam.reportportal.service.Launch - ReportPortal item with ID '781ae0f4-2b4d-4b10-92ce-9d58db30b7a3' has been created
13:12:34.178 [rp-io-13] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Start test item successfully completed
13:12:34.178 [rp-io-13] DEBUG com.epam.reportportal.service.Launch - Starting test item...rp-io-13
13:12:34.232 [rp-io-14] DEBUG com.epam.reportportal.service.Launch - ReportPortal item with ID 'b47061ed-6861-45ab-89f4-a7690d30b34a' has been created
13:12:34.233 [rp-io-14] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Start test item successfully completed
13:12:42.230 [main] INFO com.esign.steps.SigningRoomSteps - user fetched all the identifiers created yesterday
13:12:42.230 [main] INFO com.esign.steps.SigningRoomSteps - user fetched all the identifiers created yesterday
  Given user fetched all the identifiers created yesterday            # com.esign.steps.SigningRoomSteps.userFetchedAllTheIdentifiersCreatedYesterday()
13:12:42.235 [main] INFO com.esign.steps.SigningRoomSteps - create singing room URL with identifiers
  And create singing room URL with identifiers                        # com.esign.steps.SigningRoomSteps.createSingingRoomURLWithIdentifiers()
13:12:42.239 [main] INFO com.esign.steps.SigningRoomSteps - user trigger signing room url and started verifying the actions
13:12:42.239 [main] INFO com.esign.pages.SigningRoomComponent - verifySigningRoomUrl....
launchUrl...https://qa-smartsign.eoriginal.com/signingroom/landing/8bdrsgylmd8a
13:12:42.256 [rp-io-17] DEBUG com.epam.reportportal.service.Launch - Starting test item...rp-io-17
13:12:42.279 [rp-io-18] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Logging context completed
13:12:42.283 [rp-io-21] DEBUG com.epam.reportportal.service.Launch - Starting test item...rp-io-21
13:12:42.284 [rp-io-22] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Logging context completed
13:12:42.284 [rp-io-24] DEBUG com.epam.reportportal.service.Launch - Starting test item...rp-io-24
13:12:42.305 [rp-io-27] DEBUG com.epam.reportportal.service.Launch - ReportPortal item with ID 'ba85294c-3759-4555-adc4-e76f7d49644a' has been created
13:12:42.305 [rp-io-27] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Start test item successfully completed
13:12:42.336 [rp-io-26] DEBUG com.epam.reportportal.service.Launch - TestItem with ID = 'b47061ed-6861-45ab-89f4-a7690d30b34a' successfully finished.
13:12:42.336 [rp-io-26] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Finish test item completed
13:12:42.339 [rp-io-28] DEBUG com.epam.reportportal.service.Launch - ReportPortal item with ID '4de7b21f-e5ec-47fe-874e-96d2d3c2c032' has been created
13:12:42.341 [rp-io-28] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Start test item successfully completed
13:12:42.386 [rp-io-29] DEBUG com.epam.reportportal.service.Launch - ReportPortal item with ID '7637d5fd-bb29-4d67-87c2-f16127341e59' has been created
13:12:42.387 [rp-io-29] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Start test item successfully completed
13:12:42.392 [rp-io-31] DEBUG com.epam.reportportal.service.Launch - TestItem with ID = '4de7b21f-e5ec-47fe-874e-96d2d3c2c032' successfully finished.
13:12:42.392 [rp-io-31] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Finish test item completed
13:12:42.403 [rp-io-30] DEBUG com.epam.reportportal.service.Launch - TestItem with ID = 'ba85294c-3759-4555-adc4-e76f7d49644a' successfully finished.
13:12:42.404 [rp-io-30] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Finish test item completed
13:12:46.198 [main] INFO com.esign.pages.SigningRoomComponent - getNavigatedUrl....
13:12:46.414 [main] INFO com.esign.pages.SigningRoomComponent - verifyCustomPinPage....
13:12:46.941 [main] INFO com.esign.pages.SigningRoomComponent - getNavigatedUrl....
13:12:47.146 [main] INFO com.esign.pages.SigningRoomComponent - verifyErrorPage....
There was a problem while verifying...Package ID:38w1fmK8Yp9gtcVYPJg527  Role:Signer  Error Code:500  Error Message:Internal Server Error.
  And user trigger signing room url and started verifying the actions # com.esign.steps.SigningRoomSteps.userTriggerSigningRoomAndStartedVerifyingTheActions()
13:12:47.187 [rp-io-32] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Logging context completed
13:12:47.189 [rp-io-35] DEBUG com.epam.reportportal.service.Launch - Starting test item...rp-io-35
13:12:47.190 [main] INFO com.esign.steps.Hooks - After Step
13:12:47.190 [main] INFO com.esign.steps.Hooks - ending scenario "Test to validate package created using API" at 2023-03-21T07:42:47.190370Z
13:12:47.190 [main] INFO com.esign.steps.Hooks - recordLogs Step
13:12:47.191 [main] INFO com.esign.steps.Hooks - Completed scenario "Test to validate package created using API" at 2023-03-21T07:42:47.190370Z (Duration: {} ms)  
13:12:47.192 [main] INFO com.esign.steps.Hooks - takeScreenshot Step
13:12:47.210 [rp-io-34] DEBUG com.epam.reportportal.service.Launch - TestItem with ID = '7637d5fd-bb29-4d67-87c2-f16127341e59' successfully finished.
13:12:47.211 [rp-io-34] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Finish test item completed
13:12:47.243 [rp-io-37] DEBUG com.epam.reportportal.service.Launch - ReportPortal item with ID '1c0ee9b5-a742-4882-b65c-31dc0283101d' has been created

```

**Comment by surajsharmagit** [comment]
`I changed the log4j.xml file..logs start to reflect in the console but I still do not see log messages in the reporting portal. `
![image](https://user-images.githubusercontent.com/60651167/226544733-e33a8fbc-1bc2-409d-a9b1-7990cf1a1c27.png)
`"I don't know if the error below is the cause."`
13:13:17.220 [main] ERROR com.epam.reportportal.service.Launch - Item io.reactivex.internal.operators.maybe.MaybeEmpty@57545c3f not found in the cache

**Comment by nikhilsecret** [comment]
@surajsharmagit i am getting the same issue, loggers are printed on the IntellJ console, but not pushed in report portal. How did you fix the problem ?

**Comment by ntthaibk** [comment]
also same here, can't get the log eventhough the log flooded on console

```xml

<configuration status="WARN" shutdownHook="disable">
	<appenders>
		<RollingRandomAccessFile name="File"
			fileName="./logs/aladdin-processor.log"
			filePattern="./logs/$${date:yyyyMMdd}/aladdin-processor-%d{yyyy-MM-dd}.log.%i.gz"
			immediateFlush="true" append="true">
			<PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss,SSS} [%t] %-5p %c - %m%n" />
			s
			<Policies>
				<TimeBasedTriggeringPolicy />
				<SizeBasedTriggeringPolicy size="500MB" />
			</Policies>
			<DefaultRolloverStrategy max="10" />
		</RollingRandomAccessFile>
<!--		<Console name="Console" target="SYSTEM_OUT">-->
<!--			<PatternLayout pattern="[%d{yyyy-MM-dd HH:mm:ss,SSS}] %-5p [%t] | %c: %m%n" />-->
<!--		</Console>-->
		<Syslog name="Syslog" format="RFC5424" host="localhost" port="514"
			protocol="UDP" appName="aladdin-processor" includeMDC="true" newLine="true"
			mdcId="mdc">
			<LoggerFields>
				<KeyValuePair key="AppMsg"
					value="%d{yyyy-MM-dd HH:mm:ss,SSS} [%t] %-5p %c" />
			</LoggerFields>
		</Syslog>
	</appenders>
	<loggers>
		<logger level="info" name="org.springframework" />
		<logger level="info" name="org.hibernate" />
		<root level="INFO">
			<appender-ref ref="File" />
			<appender-ref ref="Console" />
			<appender-ref ref="Syslog" level="WARN" />
		</root>
	</loggers>
</configuration>
```

our configuration look like this

**Comment by HardNorth** [comment]
@ntthaibk You didn't configure our appender, so there is no logs. Please read carefully our Log4j configuration guide:
https://github.com/reportportal/logger-java-log4j

@nikhilsecret Asked you for more details in your issue.
