### ISSUE TITLE
Unable to upgrade Service UI

### ISSUE THREAD

**Issue by sjyzheng** [reportportal/reportportal#1963]
Hi,

Our team is trying to upgrade from 5.6 to 5.7.3 using k8s. We have successfully upgraded all the components except service-ui. It is currently running on v5.6.0.

We saw the error below - 

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/03/21 16:08:35 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)

The securityContext is:
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001

This is the first time we upgrade RP since we first launched our system last year. Please advice what the issue might be, thanks!

**Comment by alena-babrova** [comment]
Hello @sjyzheng,
Is the issue still relevant? Have you managed to resolve it?

**Comment by sjyzheng** [comment]
> Hello @sjyzheng, Is the issue still relevant? Have you managed to resolve it?

Hi, the issue has not been resolved. I have tried to upgrade service-ui to 5.8.0

**Comment by alena-babrova** [comment]
Hello @sjyzheng,
Have you managed to resolve the issue using the suggestion?

**Comment by sjyzheng** [comment]
> Hello @sjyzheng ! Referring the same issue [reportportal/kubernetes#287](https://github.com/reportportal/kubernetes/issues/287). Additionally, if the upgrade to the service-ui 5.8.0 didn't help, may you reference [this](https://github.com/reportportal/kubernetes/issues/308) issue? Please let us know if this helps.

Hi @AmsterGet, upgrading to the latest version didn't work, but added the config following [this issue] (https://github.com/reportportal/kubernetes/issues/308) helps.
