### ISSUE TITLE
Not able to logged the defect from Report Portal to Cloud Jira with Custom Field 

### ISSUE THREAD

**Issue by vaibhavshukl12** [reportportal/reportportal#1973]
**Not able to log the defect from Report Portal to Cloud Jira with Custom Field which is a drop-down (project picker field)**
...

Expected Result- As manually I am able to log the defect so from Jira Rest API  it should log from Report Portal 
...
Error Message : message: "Impossible interact with integration. [ErrorCollectionstatus=400, errors=customfield_12729=Specify a valid 'id' or 'key' for Project - Name, errorMessages=[]]"
Getting this error message in Response of API 

**Screenshots**
If applicable

**Versions:**
 - Version of RP- 5.7.3

**Comment by vaibhavshukl12** [comment]
@evjlobanova -Hi Hope you are doing well.
Please update on it

**Comment by vaibhavshukl12** [comment]
@[Kozovskaya](https://github.com/Kozovskaya) Pls update on it

**Comment by Kozovskaya** [comment]
Hello @vaibhavshukl12, need to check with the team and will revert to you soon.

**Comment by Kozovskaya** [comment]
@vaibhavshukl12, Unfortunately, we haven't fixed it yet, the ticket is still in our backlog as we have tasks with higher priority

**Comment by MaryiaRymarchyk** [comment]
UPD: same issue in  https://github.com/reportportal/reportportal/issues/536
Current ticket will be closed as duplicate. Please check updates in  #536 ticket.
@vaibhavshukl12  Let me know if you have any objections.
