### ISSUE TITLE
the response of rp client 0.3.6 contains `before post the value of self._batch_logs is []`

### ISSUE THREAD

**Issue by JianLi-RH** [reportportal/reportportal#1974]
**Describe the bug**
When we use 0.3.6 to upload payload, it returns something not a formal json object, please see following output:
```shell
03-29 17:55:59.327  Execute: rp_preproc -c config.json -l /tmp/rp_preproc.log --debug
03-29 17:55:59.327  The first time rp_preproc response is:
03-29 17:55:59.327  before post the value of self._batch_logs is []
03-29 17:55:59.327  {
03-29 17:55:59.327    "reportportal": {
03-29 17:55:59.327      "launch_info": [
03-29 17:55:59.327        {
03-29 17:55:59.327          "launch_id": 348453,
03-29 17:55:59.327          "launch_name": "periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-alibaba-ipi-fips-p3-f28",
03-29 17:55:59.327          "launch_uuid": "9785dc28-83b1-4022-9817-e1c0ab78d331"
03-29 17:55:59.327        }
03-29 17:55:59.327      ],
03-29 17:55:59.327      "launches": [
03-29 17:55:59.327        348453
03-29 17:55:59.327      ]
03-29 17:55:59.327    },
03-29 17:55:59.327    "rp_preproc": {
03-29 17:55:59.327      "elapsed_time": 0,
03-29 17:55:59.327      "end_time": 1680083711,
03-29 17:55:59.327      "start_time": 1680083711
03-29 17:55:59.327    }
03-29 17:55:59.327  }
```

**Expected behavior**
Return json object as before

**Versions:**
 - Version of RP [0.3.6]

**Comment by HardNorth** [comment]
@JianLi-RH Could you please provide more details what you are trying to do and how? None of our libraries has version `0.3.6`.

**Comment by JianLi-RH** [comment]
Thanks @HardNorth for the quick feedback.
0.3.6 is a gitlab tag, we are using `pip3 install git+https://gitlab.cee.redhat.com/ccit/reportportal/rp_preproc.git@0.3.5` to install rp client.
as @rujuta answered in https://chat.google.com/room/AAAA1aARbE0?cls=7, 0.3.6 is a temporary tag/version, we have not fix some issue.

so maybe @rujuta can help follow up this issue.

**Comment by HardNorth** [comment]
@JianLi-RH This software is out of our control. As far as I see it's related to RedHat. There is nothing we can do to help you. Sorry.

**Comment by JianLi-RH** [comment]
Sorry, my bad, I really don't aware I was using a wrong Repo. sorry @HardNorth
