### ISSUE TITLE
How to create a Generic userid with a password on Reportportal?

### ISSUE THREAD

**Issue by satishkovuru** [reportportal/reportportal#1979]
I have created a a userID and password manually from db and trying to access it from UI but throwing bad credentials, How do I convert password parameter to a encrypted one or can you provide a generic encrypted password to update on db ?

**Comment by elvovsky** [comment]
@satishkovuru  I am not from the reportportal team, but I believe that you have to create a user account in UI, which will then write it to db as encrypted. Also even admin can't change the password for the user, only user by using forgot password

**Comment by IvanKustau** [comment]
@satishkovuru You can use BCrypt to hash your password and put it in DB if you want to do this manually
