### ISSUE TITLE
Broken links to results in email notification

### ISSUE THREAD

**Issue by ssfxate** [reportportal/reportportal#1988]
Received the email, but the domain link is broken. It's equal `null`.
![image](https://user-images.githubusercontent.com/18144023/234192882-e40c6ee2-d76f-44ea-bee0-e1aabec4d3ec.png)

**Comment by ssfxate** [comment]
It was okay on 21 April (Friday), but was broken since 22 April (Saturday).

**Comment by ssfxate** [comment]
Now it's working well.

**Comment by MaryiaRymarchyk** [comment]
@ssfxate glad to know it! did you managed to find the root cause?

**Comment by ssfxate** [comment]
@MaryiaRymarchyk, nope. Just noticed, that there is no issue.
