### ISSUE TITLE
Memory leak when loading report page

### ISSUE THREAD

**Issue by sporitskiy** [reportportal/reportportal#199]
When loading report page of a test with big (relatively) log, the browser takes too much memory.

My case: test log size = 520 kb.
Chrome: browser tab's memory went to 2 Gb and stuck.
![chrome](https://user-images.githubusercontent.com/15995047/28670605-277334ac-72e2-11e7-8aec-f1f4c4fbf779.jpg)

FireFox: browser takes 10.5 Gb and loads the page. 
![firefox](https://user-images.githubusercontent.com/15995047/28670619-33daa55e-72e2-11e7-8569-c9237d8159da.jpg)

The log, screenshots and gif record are attached.
[log.txt](https://github.com/reportportal/reportportal/files/1179910/log.txt)
![record_gif](https://user-images.githubusercontent.com/15995047/28670650-4ad44954-72e2-11e7-85d4-f05e6ad15b92.gif)

**Comment by lexecon** [comment]
fixed in version 3.3
