### ISSUE TITLE
Analyzer Service Not Running

### ISSUE THREAD

**Issue by maximilian-mueller67** [reportportal/reportportal#1990]
Hello,
we have ReportPortal running with Kubernetes and have some issues regarding auto analysis. It says that the service is not running, but it clearly is. I had to make adjustments to disable RBAC see (https://github.com/reportportal/service-index/issues/43) and hard coded the url for the services. 
It would be great if anyone could give some information what is wrong. 
Version is 5.7.4

Output of composite/info
{
"reportportal-api": {
"build": {
"branch": "master-a9f21ec1b06bca37c10ffb46a6ec509c3bf614e5",
"description": "ReportPortal API Service",
"name": "API Service",
"repo": "reportportal/service-api",
"version": "5.7.4"
},
"environment": {},
"extensions": {
"analyzers": [
{
"analyzer": "analyzer-default",
"analyzer_cluster": true,
"analyzer_index": true,
"analyzer_log_search": true,
"analyzer_priority": 1,
"analyzer_suggest": true,
"version": "5.7.4"
}
],
"extension": [],
"result": {
"server.analytics.all": "true",
"server.details.instance": "5ade40a6-7e20-41b1-ac03-e5251e427826"
}
},
"jobs": {
"cleanExpiredCreationBidsTrigger": {
"triggersIn": 258344
},
"interruptLaunchesTrigger": {
"triggersIn": 258330
}
},
"metadata": {
"activityAction": [
"createDashboard",
"updateDashboard",
"deleteDashboard",
"createWidget",
"updateWidget",
"deleteWidget",
"createFilter",
"updateFilter",
"deleteFilter",
"analyzeItem",
"createDefect",
"updateDefect",
"deleteDefect",
"createIntegration",
"updateIntegration",
"deleteIntegration",
"startLaunch",
"finishLaunch",
"deleteLaunch",
"updateProject",
"updateAnalyzer",
"postIssue",
"linkIssue",
"linkIssueAa",
"unlinkIssue",
"updateItem",
"createUser",
"deleteIndex",
"generateIndex",
"startImport",
"finishImport",
"createPattern",
"updatePattern",
"deletePattern",
"patternMatched"
],
"activityEntityType": [
"launch",
"item",
"dashboard",
"defectType",
"emailConfig",
"filter",
"import",
"integration",
"itemIssue",
"project",
"sharing",
"ticket",
"user",
"widget",
"pattern"
]
}
},
"reportportal-index": {
"build": {
"branch": "96a584c",
"build_date": "2023-04-25T12:35:12+0000",
"name": "Index Service",
"repo": "reportportal/service-index",
"version": "5.7.3_custom_24"
}
},
"reportportal-jobs": {
"build": {
"branch": "master-b62775eb18889e7be111a8da7de07cde3d7f1ff2",
"description": "ReportPortal Jobs Service",
"name": "Jobs Service",
"repo": "reportportal/service-jobs",
"version": "5.7.4"
}
},
"reportportal-uat": {
"authExtensions": {},
"build": {
"branch": "master-d7d13c1991cb7faf644024fd90ce7a67465b3be7",
"description": "Unified Authorization Trap for all ReportPortal's Services",
"name": "Authorization Service",
"repo": "reportportal/service-authorization",
"version": "5.7.4"
},
"metadata": {
"project_roles": [
"OPERATOR",
"CUSTOMER",
"MEMBER",
"PROJECT_MANAGER"
]
}
},
"reportportal-ui": {
"build": {
"branch": "b70d420295de80fe9ac72b1176ea8bc6be2457f3",
"build_date": "2023-01-30T14:00:09+0000",
"name": "Service UI",
"repo": "reportportal/service-ui",
"version": "5.7.4"
}
}
}

![sa_nr_1](https://user-images.githubusercontent.com/46567653/234503745-cab0fd76-886e-4974-bd64-272b87f94024.png)
![sa_nr_4](https://user-images.githubusercontent.com/46567653/234503750-bd3400c4-0c3b-4ad7-89dc-8fd6a69040c1.png)
![sa_nr_3](https://user-images.githubusercontent.com/46567653/234503751-5264ed57-73ad-4e00-93b4-45c775de49e5.png)
![sa_nr_2](https://user-images.githubusercontent.com/46567653/234503754-eb3f5cb1-72c7-4430-ad7b-85a5d468434a.png)

**Comment by maximilian-mueller67** [comment]
Hi @irynakozak2 , here are the log files. Also we use OpenSearch instead of ElasticSearch. Maybe that causes some issues?
[analyzer.txt](https://github.com/reportportal/reportportal/files/11330931/analyzer.txt)
[analyzer-train.txt](https://github.com/reportportal/reportportal/files/11330932/analyzer-train.txt)

**Comment by irynakozak2** [comment]
Yes, It definitely can be the issue related to OpenSearch because in the 5.7.4 we enabled by default logs double-entry to both Elasticsearch and PostgreSQL but haven't tested it with OpenSearch yet, just for ES as the Kubernetes pods. I suppose the issue can be with the missing default indices in the OpenSearch.

**Comment by maximilian-mueller67** [comment]
Hi, i just tried it and it actually works, wow. I can see that there are now defect types set by Auto Analysis. Thank you very much for your help!

**Comment by irynakozak2** [comment]
Thank you so much for the quick response!
