### ISSUE TITLE
CleanStorageJob does not delete MinIO files

### ISSUE THREAD

**Issue by Timremmert** [reportportal/reportportal#1992]
**Issue:**

We found that our server was using an enormous amount of memory for no apparent reason. After researching, we found that the MioIO folder is very large. In the project settings we have set that attachments are deleted after 2 weeks. However, this is not the case because the "CleanStorageJob" job does not work properly. 

Since the PostgreSQL database is on a separate server, we suspect that the job is not running on the productive PostgreSQl database, but on the standard database that is created when the Docker Compose file is started. The job therefore has a short runtime of just a few milliseconds, since there are no files in the standard database. Configuring the .yaml file shouldn't be a problem as all connections to the PostgreSQL database have been properly configured.

Also, it's weird that the "cleanAttachmentsJob" job moves entries to the PostgreSQL database. The job "CleanStorageJob" on the other hand cleans the table in the other database (which is empty).

Is the issue known? And how can we fix it?

Related service-jobs:
![image](https://user-images.githubusercontent.com/25347130/234860036-b8f1f1da-8400-4a86-95d1-3548319d3981.png)

**Ideas from my side:**
Should I add "RP_DB_URL" in the enviroment of service-jobs (because I saw this in the file down below)? Or is "RP_DB_HOST" enough (like in the screenshot above)? 

![image](https://user-images.githubusercontent.com/25347130/234859201-3529412d-d233-4e32-9924-61a348a15453.png)

**Versions:** 
API Service: 5.7.4;Index Service: 5.7.3;Jobs Service: 5.7.4;Authorization Service: 5.7.4;Service UI: 5.7.4;

**Comment by Oleksii-kh89** [comment]
Hi @Timremmert 

As I understand right, you suspect that you have two databases. If yes, what database are your logs written to? 

Also,
- Can you provide service-jobs logs and search for "cleanStorage" job execution logs?
- Check the last clean storage job execution in the PostgreSQL database (shedlock table data).
- If you have a lot of attachments, the value of RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CHUNKSIZE can be increased to 200000.

**Comment by Timremmert** [comment]
The logs are written on Server 1 (were ReportPortal runs and not the Postgres-Database)

Latest log entries for cleanStorage execution in the last 3 days: 
![image](https://user-images.githubusercontent.com/25347130/236221543-d35c82d0-c358-4ef7-825a-e28ebc0f667a.png)

Last cleanStorage execution: 
![image](https://user-images.githubusercontent.com/25347130/236216515-edbaf521-0b14-43da-9512-3d4c3a006f89.png)

**Comment by Oleksii-kh89** [comment]
@Timremmert 
Thank you for your response. Regarding clean attachments increase the value of `RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CHUNKSIZE` as I mentioned above and check the results. Also, you can try to clean manually attachments in MinIO (don`t delete folders but files) and in the database.

**Comment by irynakozak2** [comment]
@Timremmert Hi! Are there any updates from you regarding increasing the RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CHUNKSIZE?
