### ISSUE TITLE
Launch description is limited to 1K

### ISSUE THREAD

**Issue by roniezr** [reportportal/reportportal#1996]
**Describe the solution you'd like**
launch description is limited to 1K,

**Is your feature request related to a problem? Please describe.**
...
The launch description is limited to 1K, any idea how it can be increased?
If not can it be increased? 
we are using the description to publish the pipeline status, putting links and some HTML tags

**Comment by HardNorth** [comment]
Launch description increased to 2048 symbols at release 5.7.3: https://reportportal.io/releases/5.7.3

There is no any plans to increase it more due to software and performance limitations.
