### ISSUE TITLE
Add feature to merge the launches without deleting them

### ISSUE THREAD

**Issue by OstapJ** [reportportal/reportportal#20]
Actual: When we merge two launches they disappear and we can't gather statistic by each of them. We can gather only from merged one.

Expected: After merging launches they stay alive in the 'Lunches' tab.

Why it is important: It is quite convenient to build test suites hierarchy based on Teams/Components
in that turn it is valuable to gather statistic by Teams or Components.

**Comment by DzmitryHumianiuk** [comment]
@OstapJ preserving of source lunches after a merge goes against the logic.
During merge we move all child to new launch. In this case source launches will be empty.
Source Luanch object itself will have statistics, but will have no child under it, in such a case.

the only option, i guess, is to move item from all merged lauches to particular selected. But still we have to delete the rest.

Still can't get why you need to keep initial source launches.

**Comment by OstapJ** [comment]
@DzmitryHumianiuk Thanks for the answer. The merge functionality works as expected I don't have any objections. I am talking about kind of new feature 'create new launch based on existing ones'.
I'll describe necessity in scope of our project and my colleagues one. 

Launch structure:
Launch -> Suite (in our case it's a Team name) -> Test
![image](https://cloud.githubusercontent.com/assets/5707734/20878036/1a1ace0c-bad5-11e6-8743-6bfd3ce6041b.png)

Instead of the 'Team name' could be Component name or something another important. 

1. Each team works on certain functionality and doesn't intercept with others team. Hence it is important to gather statistic by team and analyze it, the overall regression statistic doesn't say anything which relates to the certain team. It's just general amount of passed, failed tests. We can't track the state of each team. 
2. Imagine, we have 'Component' name instead of 'Team' name. From business prospective it is important to know the health of each component. For example:
- Navigation component
- Accounting component

Finally it could be kind of health check by each component.  From business prospective we can observe that amount of failures are increased in 'Accounting' component it may be caused by integrating 
the code base with new module in the system.
The same approach suits well for case with 'Teams'. We can observe that 'Ajax' team got 20% failures more then usual it may say that something has broken in 'Integration' team.

Please let me know you thoughts.

**Comment by evjlobanova** [comment]
#363

**Comment by evjlobanova** [comment]
closed as duplicate

**Comment by evjlobanova** [comment]
In version 5.0 we are adding a widget Health Check widget, that helps you to combain test items from different launches and calculate a passing rate for different components.
https://reportportal.io/docs/Component-health-check
