### ISSUE TITLE
Downloaded Excel file have different name and extension

### ISSUE THREAD

**Issue by aliaksei777** [reportportal/reportportal#2000]
I noticed that when I tried to download attached any Excel file, it gets downloaded with a different name and extension.
What should I do to have initial file name and extension while downloading?

![Screenshot_831](https://github.com/reportportal/reportportal/assets/133098291/7f82f214-5fd4-4c73-9dc5-9ff62339198c)

- Report Portal build: 5.7.4.
- Agent Java TestNG: 5.2.0.

**Comment by DzmitryHumianiuk** [comment]
@aliaksei777 super strange behaviour.
seems like something on the storage side converts it.
Do you use S3 amazon bucket for the storage underneath of your ReportPortal instance?

**Comment by aliaksei777** [comment]
Hi @DzmitryHumianiuk! Thank you for response!
No, I just have Linux VM and started docker service  on it.

Also, attachments on logs page have the following page source (`src` changed):
* Images:
`<img src="..." alt="image/png" class="attachmentBlock__attachment--1jCr2">`

* Text files:
`<img src="..." alt="text/plain" class="attachmentBlock__attachment--1jCr2">`

* Excel files:
`<img src="..." alt="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" class="attachmentBlock__attachment--1jCr2">`

For attaching any file, I'm using the following method (`com.epam.reportportal.service.ReportPortal`): 
* `public static boolean emitLog(final String message, final String level, final Date time, final File file)`

**Comment by MaryiaRymarchyk** [comment]
Hi @aliaksei777  it is known defect, it is already in our backlog (EPMRPP-83874).
And your request duplicate #1404.

**Comment by Kozovskaya** [comment]
Hi @aliaksei777, the issue is fixed in our latest release 23.2!
