### ISSUE TITLE
Enable the possibility for Member role to make actions not only on his own items (launches, test items etc.) but also on the items reported by other users

### ISSUE THREAD

**Issue by avihaie** [reportportal/reportportal#2003]
**Describe the solution you'd like**
Currently, only Project admin is able to add Edit a Test Item for adding attributes for Not own item(created by another user).
We would like to enable this also for members (or enable more granularity to configure it) to avoid elevating permission to everyone to project managers.

**Is your feature request related to a problem? Please describe.**
We want to have the ability to know which member is investigating which test item by adding an attribute that reflects that in the test item for Test items created by another person(Not own items).
Currently, this is not possible but only to project managers/admin.

As RP and members level are the one's investigating a test item, we need members to be able to add attributes to the test item while they are investigating a test item as there might be one or more changing members that investigate one test item. 

This is related to https://github.com/reportportal/reportportal/issues/1964 as the solution mentioned there at March:
"""
updating our Permission Map for different types of roles on the project. The task is already in our Backlog. And according to planned scope the Member role will be able to make actions not only on his own items (launches, test items etc.) but also on the items reported by other users.
"""

**Comment by Kozovskaya** [comment]
Hey @avihaie, thanks for your request, I've already answered in the issue  https://github.com/reportportal/reportportal/issues/1964 
As your feature request is the same I will close this issue, if you don't mind, so for me it will be easier to track the issue and sending the updates. Hope for your understanding!
 If you have any questions don't hesitate to ping me!
