### ISSUE TITLE
Marking a failure with "no defect" causes a potential miss with combination of AA feature

### ISSUE THREAD

**Issue by yoavws** [reportportal/reportportal#2004]
**Describe the bug**
Mark a failure with "no defect" causes a potential miss with combination of AA feature

**Expected behavior**
The item will be marked, however the marking won't influence AA feature.
And Why is that? we found ourself forbidding the use of "no defect" marking at all in our organization, as future AA marking of "no defect" can hide a real issue (if the root cause differs but the stack-trace is the same)
The user won't be able to even know there is an issue in his launch as no marking on the top of the launch and only further inspection will show that.

**We caught it by mistake due to an observant Eng. however with thousands of tests it is impossible to guess this behavior and it can cause loose of real bugs**.

**Versions:**
5.7.3

 - Version of RP [find it under Login form, copy as is]
5.7.3

**Comment by DzmitryHumianiuk** [comment]
@yoavws Auto-Analysis (AA) is designed to bypass the 'NO DEFECT' status. 
That means, if the same issue occurs in a subsequent execution, 'NO DEFECT' won't be taken into account by AA.

The inclusion of the 'NO DEFECT' group was largely in response to user requests. 
These users needed a way to mask temporary glitches and other non-recurring issues. 
While it might not seem like the best solution, it does address the need in some testing frameworks and project processes that aren't perfect.

Thus, your project workflow and agreement with the team to avoid NO DEFECT is the best approach here.
