### ISSUE TITLE
launch import presumes timestamps in UTC time 

### ISSUE THREAD

**Issue by dkrowl** [reportportal/reportportal#2006]
**Describe the bug**
When importing via launch API the start_time in launch and test information is incorrect if user and your tests xml timestamp is in other than UTC time.

Service-api container is set with TZ environment variable to user timezone.
Unsetting this won't fix the problem.

It seems that setting browser timezone to UTC will fix the absolute time but not the relative time. And this is not a real fix as you should'n handle the xml timestamps in UTC time.

**Expected behavior**
The timestamp element in xml is handled as it would be the correct time with timezone taken into consideration. No need to do the timezone difference transformation to UI.

**Screenshots**
![reportportal](https://github.com/reportportal/reportportal/assets/42459691/3035fb61-2b89-4b43-8f37-b6a71f38d688)

**Versions:**
 - Browser Firefox/Chrome
 - Version of RP  5.7.4

**Comment by DzmitryHumianiuk** [comment]
@dkrowl good catch.

**Comment by alena-babrova** [comment]
Dear @dkrowl,

ReportPortal expects "timestamp" values specified in the JUnit XML file to be in the UTC Time Zone. So it's up to the client side to prepare and send data where all date-time values are in the UTC timezone.

Further, the UI of ReportPortal shows time in the current user browser's (e.g. OS System) time zone and this way everything is aligned and the real time respecting the End user's TZ is displayed.

**Comment by alena-babrova** [comment]
Dear @dkrowl,

Could you please share an example of XML file you use when importing to check the format of date-time used?

Thanks!

**Comment by dkrowl** [comment]
@alena-babrova 

Here's the format that it is in:
`timestamp="2023-08-16T08:55:11.659000"`

**Comment by DzmitryHumianiuk** [comment]
@dkrowl for the timezone offset it should have this added into the time format.

JUnit reports often use timestamps in the ISO 8601 format. This format includes the date and time, and optionally, fractional seconds and a timezone offset.

An example of a timestamp in an XML file of a JUnit report might look like this:
`timestamp="2023-08-16T08:55:11"`

If timezone information is included, it could be in UTC, represented with a `Z` at the end:
`timestamp="2023-08-16T08:55:11Z"`

Or with an explicit offset:
`timestamp="2023-08-16T08:55:11+00:00"`


@alena-babrova looks like a missing capability of the import parser.
And we need to add the consideration of the TimeZone offset from details above.

**Comment by DzmitryHumianiuk** [comment]
@alena-babrova i've tested it with various formats, and it doesn't consider the timezone offset for now:

i've tried:
```properties
timestamp="2023-08-18T14:15:01.659000-04:00" 
timestamp="2023-08-18T14:15:01.659000+03:00"
timestamp="2023-08-18T14:15:01.659000"
timestamp="2023-08-18T14:15:01.659000Z-04:00" #(returned error of parsing)

```
the result was the same for all of them
<img width="1644" alt="image" src="https://github.com/reportportal/reportportal/assets/11332788/9e8ab14a-361c-43d8-9566-2702f17715ea">

**Comment by dkrowl** [comment]
@DzmitryHumianiuk Thanks,

I'd like to just add that timestamps in the ISO 8601 format without Z or offset should be considered as local time.

**Comment by alena-babrova** [comment]
@DzmitryHumianiuk, thanks for the clarifications.

Summarizing:
We should improve import functionality so that RP understands time with timezone offset when specified and saves into DB according to it. In the DB we save everything in UTC timezone anyway. E.g.:
- 2023-08-18T**14**:15:01**-04:00** -> imported as 023-08-14T**10**:15:01
- 2023-08-18T**14**:15:01 -> imported as 023-08-14T**14**:15:01

But anyway, it will require import files to respect date in local time by specifying the offset value, as in the example. So the import file should provide the dates with the offset value.

We will register this as an improvement.

@dkrowl, thanks for your contribution.

**Comment by Kozovskaya** [comment]
Hi @dkrowl 
FYI 
We plan to add this functionality in our release 23.3 which is planned on the end of this year!

**Comment by Kozovskaya** [comment]
Hello @dkrowl, 
I'm pleased to let you know that the fix is already released!
https://github.com/reportportal/reportportal/releases/tag/v24.1
