### ISSUE TITLE
Timezone unsync between Start time in Launches and the widget Launches Table

### ISSUE THREAD

**Issue by arunkumargceb** [reportportal/reportportal#2007]
**Describe the bug**
We are using report portal 5.3.5
Start time in launches is for example: 5 pm (our local time UTC+5.30) but start time in the widget Launches Table is: 10 pm (UTC+10.30) in this case.

**Expected behavior**
...The time zone in both places should be the user time zone

**Screenshots**
unable to attach due to security
**Versions:**
 - OS - Windows 10, Browser - Edge 113
 - Version of RP [find it under Login form, copy as is] - Current version: (no version displayed)

**Comment by MaryiaRymarchyk** [comment]
@arunkumargceb  could you clarify which widget you use? 
Would you mind testing it with the latest version of Report Portal [5.7.4 ](https://github.com/reportportal/reportportal/releases)
I have checked it by myself with widget 'Launch statistic chart' and for me it works fine - time zone in both places are in my time zone.

**Comment by DzmitryHumianiuk** [comment]
Not reproducible. 
no response.
closing.
