### ISSUE TITLE
403 Error while accessing report portal

### ISSUE THREAD

**Issue by souravdutta711** [reportportal/reportportal#2010]
**Describe the bug**
Getting 403 error while trying to connect to reportal portal via jenkins build with cucumber integration.

**Expected behavior**
...

**Screenshots**
![image](https://github.com/reportportal/reportportal/assets/113052618/7aba6aa7-bc74-4071-b881-b2e63eabd797)

**Versions:**
 - Not applicable - Trying the connection from jenkins build via agent
 - Version of RP - Build: 5.6.0

**Comment by MaryiaRymarchyk** [comment]
Hi @souravdutta711, could you please try latest version of RP which is [5.7.4](https://github.com/reportportal/reportportal/releases). Please keep us updated with the results.

**Comment by MaryiaRymarchyk** [comment]
Hi @souravdutta711 as we haven't received a reply from you, we'll close the issue for now.
If  the issue still relevant, just get in touch.
