### ISSUE TITLE
Is it possible to change "Email From" value? reportportal 5.7.4

### ISSUE THREAD

**Issue by heilwood** [reportportal/reportportal#2017]
Hi,

We faced with issue that we stopped receiving emails from reportportal. Integration configured correct, no errors in api container. tcpdump shows that emails has been sent but we still not getting emails and looks like our smtp server recognized reportportal emails as spam because name of sender is: "root@3xvfd3r34ffd3". Is it possible to change "Email from"  somehow?

**Comment by heilwood** [comment]
> We are facing Similar issue but not sure about the error though, with below docker logs . Mails suddenly stopped working from April without changing anything from our side <img alt="reportportal-mail" width="1748" src="https://user-images.githubusercontent.com/45026234/240891178-4f0e862a-5204-4b24-b923-c4dfa9c7c250.png">

Looks like for some launches we also have same error in our api container

**Comment by alena-babrova** [comment]
Hi @heilwood 
Are you sure that "root@3xvfd3r34ffd3" is not something that you specified in the email integration configuration? Looks like it is just an account name.

Emails are sent the way you configure (account you provide). Also, there is an option to specify Sender name (label):
![image](https://github.com/reportportal/reportportal/assets/89584140/d99193bd-5570-43fd-b271-2539583e7254)

**Comment by alena-babrova** [comment]
I would suggest using authorization so that a specific (real) email account is used as a sender. As on my screenshots.

**Comment by heilwood** [comment]
problem solved by changing api docker-container hostname. In docker-compose.yml you need to add `hostname: you_host_name` in api section.
