### ISSUE TITLE
report_portal_restrat_issue

### ISSUE THREAD

**Issue by Ajinkyapandhare01** [reportportal/reportportal#2020]
report-portal container restarts, while running [test-cases]
<img width="1492" alt="Screenshot 2023-05-29 at 7 05 17 PM" src="https://github.com/reportportal/reportportal/assets/134942708/2515b96b-730b-417a-bc8d-d4f0b80afcdd">
<img width="891" alt="Screenshot 2023-05-29 at 7 08 20 PM" src="https://github.com/reportportal/reportportal/assets/134942708/7e6014da-77fb-4887-b222-ffecb20a1a24">

error1:-
o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: insert or update on table "activity" violates foreign key constraint "activity_user_id_fkey"

Error2:-
"2023-05-29 11:33:54.653 ERROR 1 --- [ntContainer#0-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: insert or update on table "activity" violates foreign key constraint "activity_user_id_fkey""

error3:-
"  Detail: Key (user_id)=(185) is not present in table "users"

**Comment by irynakozak2** [comment]
@Ajinkyapandhare01 Hi! Did you have a chance to review the user persistence in the database?
Waiting for your reply!

**Comment by DzmitryHumianiuk** [comment]
no response.
closing
