### ISSUE TITLE
Documentation Issue for Reportportal upgrade

### ISSUE THREAD

**Issue by shubhangiBajpai** [reportportal/reportportal#2034]
We were trying to upgrade Report portal from 5.6.3 to latest (23.1), we went through the documentation for the same:
https://reportportal.io/docs/installation-steps/MaintainCommandsCheatSheet
https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.23.1

Here it is mentioned to take backup of the data using the following command which will generate a backup.sql:
docker exec <postgres_container_name> pg_dump -U <POSTGRES_USER> <database_name> > backup.sql

We then updated our reportportal using latest docker compose (for v 23.1 )and dropped the schema as mentioned:

docker exec -it <postgres_container_name> psql -U <POSTGRES_USER> -d <database_name>

DROP TABLE schema_migrations;
DROP SCHEMA quartz CASCADE;
DROP SCHEMA public CASCADE; CREATE SCHEMA public;
\q
But after restoring this data using the command:

docker exec -i <postgres_container_name> psql -U <POSTGRES_USER> -d <database_name> < backup.sql

**We were unable to see data restored for screenshots and file attachments, on doing an RCA we figured out that "storage" folder created by minio also needs to be backed up which is no where mentioned in the documentation.**

Can you confirm that the approach is correct and storage folder needs to be backed up? **If yes, can we update the documentation to reflect the same.**

CC:
@anandbagmar
@nitin-vhanakaware

**Comment by DzmitryHumianiuk** [comment]
@shubhangiBajpai your findings are spot on. 
Along with the steps you've already taken, don't forget to copy the storage folder of MinIO in the version where MinIO is still in use. 
Alternatively, for versions that utilize S3-enabled storage, be sure to copy the S3 buckets with attachments.

We appreciate you bringing this to our attention, and we'll make sure to update our documentation to reflect these steps. Thanks for your contribution!
