### ISSUE TITLE
Error `container for service "rabbitmq" is unhealthy` when setting docker in local

### ISSUE THREAD

**Issue by hanif-pelago** [reportportal/reportportal#2035]
I tried to setup reportportal on my local (mac) using docker by following this step https://reportportal.io/docs/installation-steps/DeployWithDockerOnLinuxMac/

On reportportal version 5.7.4 I can do it smoothly without encountering any issue. But when I try with new version 23.1, I encounter this error
<img width="913" alt="Screenshot 2023-06-20 at 4 27 17 PM" src="https://github.com/reportportal/reportportal/assets/93503826/0374d78a-f0a8-4617-bc25-53236fea11af">

`dependency failed to start: container for service "rabbitmq" is unhealthy`

Is there any changes on how to setup docker on local?

**Comment by HardNorth** [comment]
Duplicates #1604
