### ISSUE TITLE
Unknown 'Auto-analysis' end status.

### ISSUE THREAD

**Issue by forelock7** [reportportal/reportportal#2037]
**Describe the bug**
1. Open Launches page
2. Open 'More' menu for particular launch
3. Choose 'Analysis'
4. Auto-analysis started

**Actual behavior**
 'Auto-analysis' icon appears and constantly flashing all time.
There is no  any provided status of analysis. How should I recognise when it finishes?

**Expected behavior**
The end status of auto-analysis is displayed.

**Screenshots**
![Screenshot 2023-06-26 at 16 12 11](https://github.com/reportportal/reportportal/assets/11822634/3acb75e0-7c84-4a21-abb6-83b1c0f30475)

**Versions:**
 - macOS 13.3.1 (a), Chrome 114.0.5735.133 
 - Version of RP 23.1

**Comment by MaryiaRymarchyk** [comment]
Hi @forelock7 , it work as designed, you have to refresh to see the results. Usually the analysis works out quickly enough - about few seconds. Automatic update works only for Auto-Analysis for launches in progress.
Let me know if you have more questions or the ticket can be closed.

**Comment by forelock7** [comment]
Unfortunately I wouldn't say that is 'quickly enough'. I have a small number of launches and it works approximately 30 seconds and more. I caught the situation when 'AA' marked only half of similar issues. When I re-started AA, it marked all other.
Now the question is what happens when we add more than hundreds times of test suites to this system. And yes, indeed, my company is considering using this system.

**Comment by DzmitryHumianiuk** [comment]
@forelock7 this `AA` flag on the launch is controlled by the `service-analyzer`.
If analyzer or elasticsearch has a lack of the resources it would work slow and even fail with OutOfMemory, which will cause the AA flag flashing endlessly.

Please check stability and performance of service-analyzer, service-train, and elastic.
