### ISSUE TITLE
Question: Is there any other way to link a Jira bug without JIra plugin configured

### ISSUE THREAD

**Issue by Dannyb48** [reportportal/reportportal#2038]
Is there any way to update the ExternalIssues fields of test item issue with a Jira Ticket Id and Url without configuring the plugin?

My use case is simple: I create a bug outside of RP but I used RP to troubleshoot the issue. When investigating an issue we would like to update the BTS field and manually link the jira to the issue. Currently, we do this by either updating the comment field of the defect with the link to the jira or as an attribute but it feels awkward when there is a specific BTS bug field we can update but it seems like those buttons are greyed out unless you have the plugin configured.

**Comment by MaryiaRymarchyk** [comment]
Hi @Dannyb48, unfortunately i can't propose you any other solution to link Jira ticket to the test item except you've already listed: comment and attribute.
If you have uploaded plugin and configured integration correctly you will be able not only post issue but also link a bug created outside. 
![image](https://github.com/reportportal/reportportal/assets/122868739/342383eb-3297-4c8a-b1bd-3cc8ccbfbde3)

Let me know if you have more questions or ticket can be closed.

**Comment by DzmitryHumianiuk** [comment]
@Dannyb48 well, you can configure any sort of integration. Even to a demo instance of the Jira.
ANd this will enable you a LINK functionality.

Even if Jira integration will expire after time, LINK issue will work.
