### ISSUE TITLE
Is there a way to add Attributes based dropdown in the dashboard?

### ISSUE THREAD

**Issue by saurabhsrivastava2009** [reportportal/reportportal#2043]
Hi Team,

Current Approach:
As per our project we have different set of environment and products whose automation run status we wanted to show through RP. Right now the current way we are doing it is by having different dashboard for different products/environments, so that a single dashboard will not look clumsy and will not be hard to read for the end user.

The issue that we feel with the current approach is as we have multiple dashboard, in order to switch between products and environment or a combination of these two, we need always come back to the dashboard list landing page and select the one we want to see.

Is there a way to add a drop down in the dashboard, so that instead of switching between multiple pages, we can choose the one we want in the same page itself or if possible have the widgets auto-update based on the attributes we are selecting from the dropdown.

Thanks in advance. :)

**Comment by DzmitryHumianiuk** [comment]
**Coming in ReportPortal v6.**

**For the workaround in ReportPortal version 5.x (23.x):**

- Filters can act as changeable parameters/attributes. A single filter or multiple filters can be used to build an entire dashboard.
- You can create multiple dashboards that represent, for example, the latest and previous build results (like today's build and yesterday's build).
- Adjustments to the parameters of these filters will update all widgets on these dashboards.
- To further automate this process, you can use an API call to modify these filters every time you run a Jenkins job or something similar. 
- Launches from that job could contain a specific attribute (configured through the config file or command line) related to the current period of executions (e.g., build, day, testing cycle), and with the API call, these filters can be updated to correspond with this attribute.
