### ISSUE TITLE
There is no way to login to demo.reportportal.io with default credentials

### ISSUE THREAD

**Issue by manowarqqq** [reportportal/reportportal#2045]

**Comment by Kozovskaya** [comment]
Hello @manowarqqq! Try now. Don't hesitate to contact us if you have the issue again.

**Comment by manowarqqq** [comment]
> Hello @manowarqqq! Try now. Don't hesitate to contact us if you have the issue again.

Thanks for answering. Now I can see a green login notification. But the home page is not opened.
503 Service Temporarily Unavailable

**Comment by Kozovskaya** [comment]
@manowarqqq investigating the issue. Sorry for the inconvenience. Will revert to you ASAP.

**Comment by Kozovskaya** [comment]
@manowarqqq Please check again. Seems like everything is ok now!

**Comment by manowarqqq** [comment]
@Kozovskaya  thanks. Works now
