### ISSUE TITLE
Trouble Adding SAML authentication

### ISSUE THREAD

**Issue by siavasht** [reportportal/reportportal#2047]
**Describe the bug**
I'm trying to add SAML plugin to authenticate users with an idm provider. I've configured the required fields as documented [here](https://reportportal.io/docs/reportportal-configuration/authorization/SAMLProvider/) but I don't see any option on the UI to log in with SAML (as seen in this [videos](https://www.youtube.com/watch?v=ljXvCVWG4mQ)). I've checked the logs but can't see any error either and am puzzled if this is a UI issue or a misconfiguration that is not reported in the logs. I found a similar issue in https://github.com/reportportal/reportportal/issues/1266 but it's not clear if it's resolved and what was the resolution.

**Expected behavior**
Seeing an option on the UI to log in with SAML.

**Screenshots**
![image](https://github.com/reportportal/reportportal/assets/4457135/1c4cc16b-70bc-4308-b135-ff750c9dff56)
![image](https://github.com/reportportal/reportportal/assets/4457135/626a6c3f-da5b-4d14-beef-4630bd59c333)

**Versions:**
- Browser: Firefox 110
 - Version of RP: 23.1

**Comment by siavasht** [comment]
The issue was in gateway configs. I had disabled insecure API which meant saml integration didn't get created in the auth service. Though would have been nice if there was a warning in the logs. It was hard to diagnose as there was no errors.

**Comment by BenManifold** [comment]
> The issue was in gateway configs. I had disabled insecure API which meant saml integration didn't get created in the auth service. Though would have been nice if there was a warning in the logs. It was hard to diagnose as there was no errors.

Can you share how you got around this? I can't see anything in the Helm chart that enables or disables https for the API here.

**Comment by KriTh07** [comment]
> > Can you share how you got around this? I can't see anything in the Helm chart that enables or disables https for the API here.
> 
> Looking back at the issue report I have written I realize I should have been clearer, sorry. My setup is on docker compose not with kubernetes.

I am using Docker compose too and facing the same issue. Can you help me understand how to solve this please?
