### ISSUE TITLE
Start launch API throwing Internal Server Error

### ISSUE THREAD

**Issue by saurabhsrivastava2009** [reportportal/reportportal#2050]
Hi Team,

We have observing an intermittent issue while starting the launch via API. The same curl works sometimes and othertimes it throws the following error 
`<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1></body></html> `

Is there a way to fix this intermittent issue?

Command we are using is
```
curl -k -X POST https://ourHostedRPPage/api/v1/Automation_Dashboard/launch -H 'Content-Type: application/json' -H 'Authorization: Bearer randomeAlphaNumeric' -d '{"name":"Launch_name","description":"This is the build","startTime":"1688360252653","mode":"DEFAULT",
          "attributes":[
                  {
                      "key":"product",
                      "value":"ProductName"
                  },
                  {
                      "key":"buildNumber",
                      "value":"59810"
                  },
                  {
                      "key":"corelationid",
                      "value":"someAlphaNumbericValue"
                  },
                  {
                      "key":"jobName",
                      "value":"Execute_Tests"
                  },
                  {
                      "key":"transactionid",
                      "value":"someAlphaNumbericValue"
                  },
                  {
                      "key":"runType",
                      "value":"sanity"
                  },
                  {
                      "key":"environment", 
                      "value":"Test"
                  }
                  ]
                  }'
```

**Comment by DzmitryHumianiuk** [comment]
@saurabhsrivastava2009 your request looks good and it works on my side in the way you've sent it.

A 500 error usually indicates something is amiss on the server side, not with the request itself. It could suggest an issue with the availability of the RP API (Out of memory, etc.).

I'd recommend taking a look at the `service-api` logs at the time you encounter the 500 error.

**Comment by DzmitryHumianiuk** [comment]
request is correct.
no related issue in the request itself
