### ISSUE TITLE
Filter Launches based on creation date.

### ISSUE THREAD

**Issue by arunkumar832** [reportportal/reportportal#2051]
**Is your feature request related to a problem? Please describe.**
I have seen that there is an option to filter launches based on latest created launch as a dropdown.
But we see that this option is not available for some of the widgets on dashboard, for instance as below.
<img width="902" alt="image" src="https://github.com/reportportal/agent-Python-RobotFramework/assets/96721487/ae0bffe1-8e28-4ab9-a148-1bf42b9af0d9">

For some cases it exists as highlighted below
<img width="923" alt="image" src="https://github.com/reportportal/agent-Python-RobotFramework/assets/96721487/08b69931-2682-4878-92d2-0f2de1c5a832">

But we require this option everywhere, when Filters were used to create widget, to show the latest created launch metrics.

Either create a section to display above option whenever, filters are used to create widget or make this dropdown part of filters as a new filter value, to filter based on latest created.

Here filtering by "Today" wont helpful for us, as we need to list all launches created latest even if it created yesterday.

**Comment by DzmitryHumianiuk** [comment]
@arunkumar832 for some widgets, such as the `Failed Case Trend Chart` you're looking at, focusing solely on the "latest" launches doesn't necessarily make sense. This is because this widget is built based on a series of launches (executions) and draws data from these. If you switch it to the 'latest' mode, it will only ever show a single point on the chart. This contradicts the concept of a _Trend Chart_ and could instead be replaced with a `Passing Rate` widget.

I hope this makes sense.

**Comment by DzmitryHumianiuk** [comment]
@arunkumar832 StartTIme filter allows to enable Dynamic Range for the time frame.

The Dynamic Range in filters (checkbox in the Start Time filter) helps to dynamically adjust the timeframe with every request. If this checkbox is enabled, it would save the offset of the time frame from the current moment. This saved offset is then used to adjust the time at the moment of the next request.
This ensures that your filter adapts to the changing time and always captures the relevant offset moment.

https://reportportal.io/docs/work-with-reports/FilteringLaunches/#launch-level-filters - search for `Dynamic`


Another way around:
get the specific attribute for the set of launches this day and update filter with API call, filter should be used to build widgets on the dashboard:
https://github.com/reportportal/reportportal/issues/2043#issuecomment-1656337203
