### ISSUE TITLE
Unable to connect to JIRA

### ISSUE THREAD

**Issue by saurabhsrivastava2009** [reportportal/reportportal#2058]
Hi Team,

I was trying the following plugin to connect our locally deployed ReportPortal with BTS JIRA
- Jira Cloud
- Jira Server

But both of them are not working and throwing the following error respectively
- _An error occurred while connecting to server: Impossible interact with integration. Unable to connect to Cloud Jira. Message : java.nect.ConnectException: Timeout connecting_
- _An error occurred while connecting to server: Impossible interact with integration. Connection refused._

I have used the following values for the mandatory fields
- Link to BTS - https://jira.ourCompanyName.com
- Project key in BTS - AF  ( as this is an assigned project for me, and ticket are AF-123)
- Email - my company's email ID that we use for Jira login
- API token - generated through my profile in jira

Is there something that I'm doing wrong here? or missing any value?

Thanks in advance

**Comment by MaryiaRymarchyk** [comment]
Hello @saurabhsrivastava2009.
Please check info here https://reportportal.io/docs/plugins/JiraServer/#some-tricks-when-you-create-a-new-connection
and here: https://github.com/reportportal/plugin-bts-jira/blob/develop/src/main/java/com/epam/reportportal/extension/bugtracking/jira/JiraStrategy.java  
If the info won't be helpfull - let us know the version of RP you use and version of Jira plugin. Jira Cloud plugin.

**Comment by MaryiaRymarchyk** [comment]
Hi @saurabhsrivastava2009, any updates there?

**Comment by MaryiaRymarchyk** [comment]
@saurabhsrivastava2009, as we haven't received a reply from you, we'll close the issue for now.
In case you still have the issue - just get in touch.
