### ISSUE TITLE
RP #administrate/users - button export is not works properly, export size = 0 

### ISSUE THREAD

**Issue by evgeny-grushko** [reportportal/reportportal#2067]
**Describe the bug**
Button Export users is not works properly
Go to sections "Administrate" --> all users --> press Export button 
(/ui/#administrate/users)

**Expected behavior**
All users exported? Selected users exported to CSV file

Actual result: 
Empty file **RP_USERS_CSV_Report.csv** exported, size 0 bytes 
[RP_USERS_CSV_Report.csv](https://github.com/reportportal/reportportal/files/12123024/RP_USERS_CSV_Report.csv)

**Versions:**
 - MacOS, Chrome (latest)
 - Current version:API Service: 5.8.0;Index Service: 5.8.0;Jobs Service: 5.8.0;Authorization Service: 5.8.0;Service UI: 5.8.0;

**Comment by DzmitryHumianiuk** [comment]
image with fix published.
Assumed as resolved.

@evgeny-grushko please reopen if still relevant

**Comment by DzmitryHumianiuk** [comment]
@evgeny-grushko 
https://github.com/reportportal/reportportal/issues/2040#issuecomment-1664337609
