### ISSUE TITLE
Not able to login to report portal 

### ISSUE THREAD

**Issue by subha0990** [reportportal/reportportal#2070]
![image](https://github.com/reportportal/agent-Python-RobotFramework/assets/140379815/f36a0331-f5c9-4286-85ed-1b6a07278e56)
BY referring  above not able to login either as default or admin user 
![image](https://github.com/reportportal/agent-Python-RobotFramework/assets/140379815/d43f2cc0-e5b7-47d1-aeb7-d122a58bcfe2)

**Comment by DzmitryHumianiuk** [comment]
duplicates https://github.com/reportportal/reportportal/issues/2072
