### ISSUE TITLE
How to get stacktrace under "Stack Trace" tab

### ISSUE THREAD

**Issue by saurabhsrivastava2009** [reportportal/reportportal#2071]
Hi Team,

I'm using "Save Single log without attachment" docs to save my stacktrace logs with the level being "trace" as per the documentation, but it is not showing up under the "Stack Trace" tab, although I can see it in "All Logs" tab. I tried with "error" level as well, but that did not work.
Is this is the correct way of approaching it or there is another way of doing it?

Thanks in advance :)

**Comment by DzmitryHumianiuk** [comment]
@saurabhsrivastava2009 could you please provide more details about your process and what you're seeing on the ReportPortal screens?

**Comment by DzmitryHumianiuk** [comment]
https://reportportal.io/docs/dev-guides/ReportingDevelopersGuide/#save-single-log-without-attachment

Field level controls the _level_ of the log.
Allowable values: debug(10000), info(20000), warn(30000), error(40000), trace(5000), fatal(50000), unknown(60000)

Anything above 40000 (error level) recognized as a stacktrace.

```json
{
  "launchUuid": "96d1bc02-6a3f-451e-b706-719149d51ce4",
  "itemUuid": "22e55c62-d028-4b49-840f-195d7a48b114",
  "time": "1574423245000",
  "message": "An error occurred while connecting to the server [Nested exception is java.lang.NoClassDefFoundError]",
  "level": "error"
}
```
