### ISSUE TITLE
Is report portal support IMPORT functionality of xml which generated by robot framework ?

### ISSUE THREAD

**Issue by subha0990** [reportportal/reportportal#2078]
Hi Team,

Kindly help me with better understanding  Is report portal support IMPORT functionality of xml which generated by robot framework?

I saw from official website it is supporting with JUNIT format.

**So kindly let me know how to import xml which are generated by robot execution ?**
![image](https://github.com/reportportal/reportportal/assets/140379815/a454b52f-efbf-4d6b-9b48-c47bd56d1cb6)

Thanks in Advance

**Comment by subha0990** [comment]
Hi Team,

Any update on this or i shall move as this as a bug .

**Comment by avarabyeu** [comment]
hey @subha0990 XML from the snippet does not seem to be JUnit format. 
https://github.com/testmoapp/junitxml
The file you provided is native robot framework XML report which isn't supported by ReportPortal. Feel free to submit feature request, the development team will prioritise it and add to the backlog. Unfortunately, ReportPortal team isn't able to provide you with any estimations in terms of implementation timelines.
