### ISSUE TITLE
As Discussed on #2078 IMPORT functionality support with native robot framework XML report 

### ISSUE THREAD

**Issue by subha0990** [reportportal/reportportal#2082]
[](url)Hi Team,

Kindly support on import functionality with native robot framework XML.
![image](https://github.com/reportportal/reportportal/assets/140379815/dd9d4d0d-b7cc-4a90-8f1a-3f880f7062f6)

Thanks IN Advance

**Comment by Kozovskaya** [comment]
Hello @subha0990. In our recent release 23.1 we added possibility to import not only .zip files but .xml also!

**Comment by subha0990** [comment]
hi @Kozovskaya , Could you pls provide me docker-compose file for 23.1 release with which robot framework import xml is fixed ?

Thanks in Advance

**Comment by APiankouski** [comment]
Hi @subha0990, you can find docker-compose file for 23.1 here https://github.com/reportportal/reportportal/blob/master/docker-compose.yml

**Comment by subha0990** [comment]
hi @APiankouski , This file i was referring. It is having 5.8.0. I am looking for 23.1 where IMPORT functionality support with native robot framework XML report

**Comment by APiankouski** [comment]
All right, 5.8.0 it is versions of service, but in general this is compose file contains images for 23.1 release of product

**Comment by APiankouski** [comment]
Btw in 23.1 we add possibility to add xml import via ui, but via api you can do it with version.

**Comment by subha0990** [comment]
hi @Kozovskaya , Can u re-open the tkt .
I am looking for **IMPORT functionality support with native robot framework XML report** 
Kindly refer https://github.com/reportportal/reportportal/issues/2078
![image](https://github.com/reportportal/reportportal/assets/140379815/3be68bef-ebb3-4a40-99ac-a500ad44074f)

**Comment by APiankouski** [comment]
We support only junit xml format. It look like this:
`<?xml version="1.0" ?>
<testsuites disabled="0" errors="2" failures="0" name="This is a test." skipped="0" tests="4" time="10" timestamp="2022-12-09T08:00:00">
	<testsuite disabled="0" errors="2" failures="0" name="This is a test." skipped="0" tests="4" time="10" timestamp="2022-12-09T08:00:00" hostname='hostname'>
		<testcase name="test 1" classname="test.anywhere_analytics.id1" status="error" startTime="2022-12-09T08:00:00" endTime="2022-12-09T08:00:03" time="5">
			<error type="error" message="Runtime Error in test.anywhere_analytics.id1">!!!MARKDOWN_MODE!!!Runtime Error in **test.anywhere_analytics.id1</error>
		</testcase>
		<testcase name="test 2" classname="test.anywhere_analytics.id2" status="pass" startTime="2022-12-09T08:00:00" endTime="2022-12-09T08:00:05" time="5"/>
		<testcase name="test 3" classname="test.anywhere_analytics.id3" status="pass" startTime="2022-12-09T08:00:00" endTime="2022-12-09T08:00:05" time="5"/>
		<testcase name="test 4" classname="test.anywhere_analytics.id4" status="error" startTime="2022-12-09T08:00:05" endTime="2022-12-09T08:00:10" time="5">
			<error type="error" message="Error in test.anywhere_analytics.id4">!!!MARKDOWN_MODE!!!Error in **test.anywhere_analytics.id4</error>
		</testcase>
	</testsuite>
</testsuites>`

**Comment by subha0990** [comment]
hi @APiankouski , Have u gone through my pervious comments  !!  and also https://github.com/reportportal/reportportal/issues/2078

I have request feature support for robot type xml  file import .

**Comment by Kozovskaya** [comment]
Hi @subha0990, sorry for misunderstanding, yes currently we support only junit xml format, and I will create a ticket in our Backlog regarding your feature request and we will discuss it internally. But we will be able to take into into work only based on the priority of tasks.
Will keep you updated!

**Comment by Kozovskaya** [comment]
Hello @subha0990 
The ReportPortal version 24.2 is already released!
Here you can find more info https://reportportal.io/docs/plugins/RobotFramework/ 
I'm closing the issue.
Thank you for using ReportPortal!
