### ISSUE TITLE
Can I customize the formula for calculating the pass rate

### ISSUE THREAD

**Issue by KzDog** [reportportal/reportportal#2084]
**Describe the solution you'd like**
I would like to calculate the pass rate using only the passed and failed results, rather than the official formula given:
> Total test cases = Passed + Not Passed, while Not Passed = Failed + Skipped + Interrupted
> Thus, Passing rate = Passed / (Passed + Failed + Skipped + Interrupted)

**Is your feature request related to a problem? Please describe.**
In my testing scenario, due to the need for re runs, the calculation results using existing formulas are not accurate

**Comment by Kozovskaya** [comment]
Hello @KzDog, thank you for your feature request. You are not the only one who requested this feature! And we are working on the updates. In future you will have the ability to define which tests should be counted as a base. We are planning to have 2 options:
- Total test cases (Passed, Failed, Skipped, Interrupted)
- Total test cases excluding Skipped

This functionality is planned to be released by the end of this year. Will this work for you?

**Comment by DzmitryHumianiuk** [comment]
@KzDog gonna be in 23.3 release.
ETA ~Dec 2023.

**Comment by Kozovskaya** [comment]
Hello @KzDog
I'm pleased to let you know that the fix is already released!
https://github.com/reportportal/reportportal/releases/tag/v24.1
