### ISSUE TITLE
NOT able to load report portal login page : UI (Noticed in 10-15 days interval) IS API key getting expired ?

### ISSUE THREAD

**Issue by subha0990** [reportportal/reportportal#2087]
Hi Team,

Getting Gateway Timeout. Not able to load report portal login page : UI
![image](https://github.com/reportportal/reportportal/assets/140379815/e3e18a3f-d45a-4b45-8e64-ab0af23e5ad2)

![image](https://github.com/reportportal/reportportal/assets/140379815/9eab217b-4d31-4b65-b6dc-52c73afd65bf)

![image](https://github.com/reportportal/reportportal/assets/140379815/29b856f6-a3dd-4522-95bd-4aff0080911a)

Docker containers are in running state
![image](https://github.com/reportportal/reportportal/assets/140379815/1ef15b48-e4f6-412c-8603-062c01f470c9)

Kindly have a look.
Thanks in Advance !

**Comment by subha0990** [comment]
Now able to see login in page but not able to log in
![image](https://github.com/reportportal/reportportal/assets/140379815/bafb87dd-a852-4e26-943f-3a170a082301)

![image](https://github.com/reportportal/reportportal/assets/140379815/f7f0a5f7-9f6d-4901-a0d5-a9d0dbedf666)

**Comment by subha0990** [comment]
Every time i need to re-deploy and create new credential ?

All pervious data with old creation gone  

Is this the correct behavior , Is api key expiring ?

**Comment by MaryiaRymarchyk** [comment]
Hi @subha0990 , 
ReportPortal functionality has retention policy for the users.
In RP configuration you can find **cleanExpireduserCron**  for deleting users by retention policy.
The job removes users with only type USER (doesn't remove users with type ADMINISTRATOR) who have not logged and have not reported longer than specified in **Expireduser_RetentionPeriod** parameter.
Probably it could be the case, i'm not sure. 
Please check your configuration.
If config analysis won't help here - please send us service-api and service-uat logs  at the moment of error.

**Comment by MaryiaRymarchyk** [comment]
@subha0990 any updates here?
