### ISSUE TITLE
Report Portal not starting Docker images in Mac M1 chip

### ISSUE THREAD

**Issue by coderrenish** [reportportal/reportportal#2088]
Docker Compose is not able to start all the images required for Report Portal.
I have followed the instructions mentioned in the below link. Docker images are not starting.
https://reportportal.io/docs/installation-steps/DeployWithDockerOnLinuxMac/
...

I should be able to see Report Portal login page
...

**Screenshots**
<img width="675" alt="image" src="https://github.com/reportportal/reportportal/assets/142405016/f1e189f7-d59a-4127-a07b-fabede816440">

<img width="344" alt="image" src="https://github.com/reportportal/reportportal/assets/142405016/e833d37e-3f70-4668-8fff-fee5ecbc4fea">

<img width="352" alt="image" src="https://github.com/reportportal/reportportal/assets/142405016/e03d2887-7732-443a-b20b-58975a0bd40c">

<img width="1025" alt="image" src="https://github.com/reportportal/reportportal/assets/142405016/bf1d26cd-4cb4-481c-aa5c-59284f82a476">

**Versions:**
 - MacBook Pro, Apple M1 Pro, 16 GB, MacOS Version 13.4 (22F66)

**Comment by alena-babrova** [comment]
Hello @coderrenish,
Please follow up M1/ARM related discussion in https://github.com/reportportal/reportportal/issues/1815.
