### ISSUE TITLE
Actions Drop-Down Only Showing 2 Items - No Edit Defects - Please Help!

### ISSUE THREAD

**Issue by sethkhon** [reportportal/reportportal#2089]
I'm trying to bulk update my results, but it appears that the Actions drop-down doesn't list the Edit Defects.  It only lists Edit items and Delete.

I have selected all the items I want to "make decision" on and then clicked on Actions.
I can individually "make decision", but I have a lot of similar defects.
The "Apply for: Similar "To Investigate" in the launch..." don't list the similar items either.  So, I can't use that feature to mark all defects.

I'm new to Report Portal.  Perhaps I missed some setup somewhere?
Please help.

**Comment by MaryiaRymarchyk** [comment]
Hi @sethkhon , thank you for your interest in RP!
Can you please specify which version of RP you used and share the status of [services](https://reportportal.io/docs/installation-steps/DeployWithDockerOnWindows/#reportportal-services) . Are all of them up and running ? Probably there are some issues with Analyzer or Elastic - if you can't see suggestions.
I also suggest reading the article -[ML suggestions](https://reportportal.io/docs/analysis/MLSuggestions/#how-the-ml-suggestions-functionality-is-working).
If this info won't help you to find the cause - please share the screenshot with 'Actions' dropdown menu, and logs of analyzer, analyzer-train and api services at the moment you "Make decision".

**Comment by sethkhon** [comment]
@MaryiaRymarchyk , thank you for your response.  How do I find out the version?  How do I find out the status of services?

**Comment by MaryiaRymarchyk** [comment]
@sethkhon ,
versions can be found under the login button 
![image](https://github.com/reportportal/reportportal/assets/122868739/94bff514-a634-4547-9ccb-e3162a95d108)
To get status of the services you can use command:
     docker:            docker ps -a  
     kubernetes:    kubectl get pods
Do you have access to logs?

**Comment by sethkhon** [comment]
@MaryiaRymarchyk ,
I should have access to logs, but I need help with how to download them.
Below are the info. you asked for earlier:
![image](https://github.com/reportportal/reportportal/assets/139490076/40ea0c04-61c6-4dcb-9e3e-2cce500fb982)

![image](https://github.com/reportportal/reportportal/assets/139490076/0d50d52b-dbd3-43d8-999b-add890d4140d)

**Comment by MaryiaRymarchyk** [comment]
Hi @sethkhon , thank you for the provided info. Everything looks ok here. 
Please share the screenshot with issue where you don't see some options in dropdown.

**Comment by MaryiaRymarchyk** [comment]
@sethkhon, thank you for the comparison with documentation - it is much easier to understand, now i see what you mean and have a solution. 
List of actions in drop-down menu depends on the level of depth in the structure. A typical Launch structure comprises the following elements: Launch> Suite > Test > Step > Log.
The list of actions you expected to see (example from documentation) is available only on Step level. On Suite and Test level - only 2 options from the list: Edit and Delete. It works as expected.
So please drill down to step level and check the menu.

**Comment by sethkhon** [comment]
@MaryiaRymarchyk , sorry for the delay, but things had been hectic!  Due to lack of results and other higher priority assignments, this project had been put on hold indefinitely.  Thank you for all your help.

**Comment by MaryiaRymarchyk** [comment]
@sethkhon got it, then i'll close the ticket, if you face it again - you can reopen it.
