### ISSUE TITLE
Need help on Screenshots files appearing blank from report portal 

### ISSUE THREAD

**Issue by subha0990** [reportportal/reportportal#2090]
Hi Team,

After execution completed able to see blank screenshots on failed test cases from report portal.
![image](https://github.com/reportportal/reportportal/assets/140379815/5537068c-9d4f-44c4-999e-0e740bd8b82d)
![image](https://github.com/reportportal/reportportal/assets/140379815/167bab07-39fa-4cdd-a2c5-dcd8def33489)

kindly help how to fix it.

Thanks in Advance !

**Comment by subha0990** [comment]
Hi Team,

Any update on this ?

**Comment by subha0990** [comment]
Hi Team,

Kindly help !

**Comment by subha0990** [comment]
HI Team,

Kindly suggest !!

**Comment by APiankouski** [comment]
Hi @subha0990, you can upload screenshots to logs using this api 
![image](https://github.com/reportportal/reportportal/assets/109206864/2fb39a89-fae0-4048-84f9-04110a06ba07)
In postman it will be look like 
![image](https://github.com/reportportal/reportportal/assets/109206864/58bd682e-f033-41a6-84c7-d5119a55558b)
![image](https://github.com/reportportal/reportportal/assets/109206864/d2b3dbad-d8ee-45ca-8eee-6d050a185e28)

**Comment by subha0990** [comment]
Can someone Please help on the screenshots .
After execution completed able to see blank screenshots on failed test cases from report portal.
image
image

kindly help how to fix it.

Thanks in Advance !

**Comment by MaryiaRymarchyk** [comment]
Hi @subha0990 , it can be related to file storage, what do you use  - Minio multi or single, S3 ? 
Can you upload and save user avatar successfully? 
Can you try to generate Demo data on your instance and check how screenshots look like in Demo launches ? (e.g. Demo Api Tests #3> beforeSuite with 1 To Investigate item - it should have attachments)

**Comment by subha0990** [comment]
hi @MaryiaRymarchyk , 

I am able to upload direct images to report portal log.

My requirement is on failed test cases screenshots should directly upload inside logs.

I can see a screenshot file appearing but while opening it is taking server path as below
![image](https://github.com/reportportal/reportportal/assets/140379815/c2028d48-e3a9-4ffc-b7fe-ad2ce3b183e8)
![image](https://github.com/reportportal/reportportal/assets/140379815/17b980cd-a174-4a8e-83d8-e261f599d6f1)

Kindly suggest and help

**Comment by subha0990** [comment]
Any Update on this Team ?

**Comment by subha0990** [comment]
Hi Team,

Could someone pls have a look on above and suggest further how to achieve it?

Thanks In Advance

**Comment by MaryiaRymarchyk** [comment]
@subha0990  if you are able to upload direct attachments - Report Portal works fine. I suppose that your reporting should be adjusted somehow to log attachments correctly. Guide for attachments is here - https://reportportal.io/docs/dev-guides/AttachmentsGuide/

**Comment by subha0990** [comment]
Hi @MaryiaRymarchyk ,

I have gone through the above link. I am able to upload the single screenshot captured by automation failure to Report porta.

My requirement is:- **on failed test cases screenshots should directly upload inside logs.**
I can see a screenshot file appearing but while opening it is taking server path as below


Could you pls suggest on this !

**Comment by MaryiaRymarchyk** [comment]
@subha0990 what agent do you use for reporting?
![image](https://github.com/reportportal/reportportal/assets/122868739/bb42d913-0360-42ff-b31d-3209ce0be6ba)
https://reportportal.io/docs/dev-guides/AttachmentsGuide/

**Comment by subha0990** [comment]
hi @MaryiaRymarchyk ,

I think you are not able to undusted my requirement !!

There is already default method written in reobotframework-reportportal listner.py for copy the logs to report portal
![image](https://github.com/reportportal/reportportal/assets/140379815/55b1b4df-dd98-4612-9c74-b9df35a84bf6)

By default when execution completed logs are copied to report portal with empty screenshots !!

![image](https://github.com/reportportal/reportportal/assets/140379815/56b85d9a-d5fa-43c2-955d-87000d130911)

But path of this image taking as report portal server path as below
![image](https://github.com/reportportal/reportportal/assets/140379815/a1f21453-c60c-4626-9fb1-9dd450d270f4)

So how to copy the screenshots along with log file  when in real time screenshots being captured by automation ?

**Comment by APiankouski** [comment]
Hi @subha0990, make sure that attachments saved in blob store as minio
You can look stored files here http://localhost:9000 if you use minio

The right api for getting attachment is http://localhost:8080/api/v1/data/{projectName}/{dataId}
![image](https://github.com/reportportal/reportportal/assets/109206864/cb72a1cb-420f-49bf-8700-7f2eca341105)

**Comment by subha0990** [comment]
hi @APiankouski ,
http://localhost:9000/    link is not opening
![image](https://github.com/reportportal/reportportal/assets/140379815/67e956f6-add0-4d38-9365-9940502fa142)

For the API you suggested where to get the dataId?

**Comment by subha0990** [comment]
Hi Team,

Any update on this ?

**Comment by MaryiaRymarchyk** [comment]
@subha0990 we have described info regarding file storage in our documentation - https://reportportal.io/docs/installation-steps/ReportPortal23.1FileStorageOptions/

**Comment by subha0990** [comment]
> @subha0990 we have described info regarding file storage in our documentation - https://reportportal.io/docs/installation-steps/ReportPortal23.1FileStorageOptions/

This is not my requirement @MaryiaRymarchyk , I am asking help on how to fix path mismatch issue for screenshots copied with  log in report portal !

**Comment by APiankouski** [comment]
@subha0990 for access to http://localhost:9000/ open port minio:9000 port in docker compose and restart minio (this part commented)
You can find id of attachment here, this api called on log opening
![image](https://github.com/reportportal/reportportal/assets/109206864/873a99ff-e37f-4b0b-8470-25d16e3100fd)

**Comment by subha0990** [comment]
> @subha0990 for access to http://localhost:9000/ open port minio:9000 port in docker compose and restart minio (this part commented) You can find id of attachment here, this api called on log opening ![image](https://user-images.githubusercontent.com/109206864/266941462-873a99ff-e37f-4b0b-8470-25d16e3100fd.png)

Thank u @APiankouski ,

1. After uncomment     ports: - '9000:9000'  from docker compose file i can load the minio browser .

But not able to login !!
Kindly help with where to get access and secret key ?
![image](https://github.com/reportportal/reportportal/assets/140379815/ec55d98f-bd51-47c5-84ae-e6a20777f31a)

2. From below API here my response 
GET
​/v1​/{projectName}​/log​/{logId}
Get log by ID

<html>
<body>


Response body{   "id": 15,   "uuid": "d3d15e78-2961-4663-9392-ac84db9616af",   "time": 1692176864151,   "message": "</td></tr><tr><td colspan=\"3\"><a href=\"selenium-screenshot-7.png\"><img src=\"selenium-screenshot-7.png\" width=\"800px\"></a>",   "level": "INFO",   "itemId": 50 }

So how to use this response on this api as u suggested earlier 
![image](https://github.com/reportportal/reportportal/assets/140379815/c8ecbe28-4ded-4ff2-bd11-742581f1efe1)

**Comment by subha0990** [comment]
hi @APiankouski ,

Could you pls help on this .

**Comment by subha0990** [comment]
Hi @APiankouski , Could you pls help us here !!

**Comment by HardNorth** [comment]
@subha0990 Before opening an issue please get familiar with our examples, at least:
https://github.com/reportportal/examples-python/blob/master/robotframework/robot/screenshot_as_file.robot

There is no way to do it differently, since Robot Screenshot library designed to work with report files.
