### ISSUE TITLE
Filter using attributeKey and attributeValue is not working

### ISSUE THREAD

**Issue by sramasudha** [reportportal/reportportal#2094]
**Describe the bug**
...
Filter using attributeKey and attributeValue is not working

**Expected behavior**
...
https://reportportal.dc.pa.sophos/api/v1/NSG-SFOS/launch?filter.eq.attributeKey=Branch&filter.eq.attributeValue=RELEASE%23staging%2Fv19.5.Maint.060.Hitra&filter.eq.name=CICD%20Suite should return the launches matching the attributes.
**Screenshots**
If applicable
<img width="1324" alt="Screenshot 2023-08-18 at 12 13 58 PM" src="https://github.com/reportportal/reportportal/assets/112937362/c8df480f-b4fc-48b6-b22d-95ee8032f109">

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

**Comment by APiankouski** [comment]
Hi @sramasudha, try to use "filter.has.compositeAttribute" parameter as on screen
![image](https://github.com/reportportal/reportportal/assets/109206864/aebaa404-348b-4183-9e1d-c6309673724c)

**Comment by sramasudha** [comment]
Thanks @APiankouski,  
Iam getting expected data using "filter.has.compositeAttribute"
