### ISSUE TITLE
Unclassified error [org.hibernate.exception.GenericJDBCException: could not execute statement]

### ISSUE THREAD

**Issue by ssfxate** [reportportal/reportportal#2100]
Started to get this error overnight. Still happening.
...

```Error: Request failed with status code 500: {"errorCode":5000,"message":"Unclassified error [org.hibernate.exception.GenericJDBCException: could not execute statement]"}```

**Screenshots**
![image](https://github.com/reportportal/reportportal/assets/18144023/86f6f522-4dad-4e9c-88d6-471cdf6cdfab)

**Versions:**
- client-javascript v5.0.12
 - Version of RP v5.8.0

**Comment by alena-babrova** [comment]
Hello @ssfxate,

Yes, right now we have an issue at https://reportportal.epam.com/ environment.
We are working on fixing it.
Please give us some time to fix it. As soon as everything is ready, I will inform.

**Comment by ssfxate** [comment]
@alena-babrova, sorry, 24 hours passed but it's still there. It blocks my work a lot. I need it.

**Comment by robert-haidul** [comment]
Also reproduce for me. Upgrading agent-java-testng to 5.3.1 partially helped, but another problem appeared - test execution reports appear on https://reportportal.epam.com/ with a delay, and some of them completely disappear and reports are not displayed.

**Comment by alena-babrova** [comment]
Dear @ssfxate and @robert-haidul,
Yes, we have a problem with the environment. We are working on it.
I will inform you as soon as it is fixed.

**Comment by alena-babrova** [comment]
Dear @ssfxate and @robert-haidul,
We have fixed the issue at https://reportportal.epam.com/.
You can continue working with ReportPortal.

Thank you for your patience!
