### ISSUE TITLE
Service-Job health status is always unhealthy

### ISSUE THREAD

**Issue by Priyanshu19992002** [reportportal/reportportal#2101]
**Describe the bug**
The health status for `reportportal/service-jobs:5.8.2` is not getting healthy. It is taking a much longer time to start than it was previously taking (for earlier mentioned service version in earlier docker-compose file) and then after starting it is showing as unhealthy. Pls look into this. 

**Expected behavior**
Service-Job health status should be healthy

**Screenshots**
<img width="1622" alt="Screenshot 2023-08-23 at 2 17 26 PM" src="https://github.com/reportportal/reportportal/assets/51071514/9923ae4f-546e-425e-b639-e0cd2b8cf376">

**Versions:**
 - OS - MacOs Ventura 13.3.1, Browser - Chrome
 - Version of RP - API Service: 5.9.2;Index Service: 5.8.0;Authorization Service: 5.8.2;Service UI: 5.9.0;

**Comment by quldude** [comment]
workaround is to update docker-compose file > jobs service to:
```
 healthcheck:
      test: curl -f http://0.0.0.0:8686/health || exit 1
```
instead of 
```
wget --no-verbose --tries=1 --spider http://0.0.0.0:8686/health
```

**Comment by Priyanshu19992002** [comment]
Is this updated for the service-jobs component mentioned in the `docker-compose.yml ` file  or it will be updated ?

**Comment by APiankouski** [comment]
Hi @quldude @Priyanshu19992002, docker-compose was updated.
Thank you.
