### ISSUE TITLE
reportportal/service-*-analyzer consumes 24GB memory on a fresh setup with few launches

### ISSUE THREAD

**Issue by chanyk-joseph** [reportportal/reportportal#2103]
**Describe the bug**
The ReportPortal setup was deployed on a instance with 8GB memory using [docker-compose](https://raw.githubusercontent.com/reportportal/reportportal/master/docker-compose.yml).
Initially, the setup works fine, and we managed to create launches via API.

After few weeks without touching the setup, it is found that the UI is inaccessible due to OOM of the "uwsgi" process.
`[ 1661.075663] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/system.slice/docker-88625dd7c1994cb919c74f13701150840fecf55beb388eb0c0839172c1c74bad.scope,task=uwsgi,pid=13592,uid=0
[ 1661.091685] Out of memory: Killed process 13592 (uwsgi) total-vm:8441272kB, anon-rss:6827320kB, file-rss:0kB, shmem-rss:16kB, UID:0 pgtables:16500kB oom_score_adj:0`

So we tried to upgrade the instance from 8GB to 16GB, but the "uwsgi" process was still getting kill continously after process restart.

Further increasing the memory to 32GB, the ReportPortal web portal becomes accessible.
But it is found that reportportal/service-*-analyzer consumes 24GB memory
`8b62b7a6409d  reportportal/service-auto-analyzer:5.7.5  "/venv/bin/uwsgi --h…"  21 hours ago  Up 20 hours (healthy)  5001/tcp reportportal-analyzer_train-1  `
`88625dd7c199  reportportal/service-metrics-gatherer:5.7.4 "/venv/bin/uwsgi --h…"  21 hours ago  Up 20 hours (healthy)  5000/tcp reportportal-metrics-gatherer-1  `
`ee8165ae1798  reportportal/service-auto-analyzer:5.7.5 "/venv/bin/uwsgi --h…"  21 hours ago  Up 20 hours (healthy)  5001/tcp reportportal-analyzer-1`
these three used 8.xGB memory x3 = 24GB !!!

**Expected behavior**
The ReportPortal service with low usage should be able to run on instance with 8GB ram

**Screenshots**
<img width="1042" alt="image" src="https://github.com/reportportal/reportportal/assets/28205157/4f979757-df2f-4b2b-be93-5018871afbf8">
<img width="1096" alt="image" src="https://github.com/reportportal/reportportal/assets/28205157/ebdda48f-9ff1-450b-9a08-18bf801df291">
<img width="645" alt="image" src="https://github.com/reportportal/reportportal/assets/28205157/0c83c934-55c2-4eb6-bb23-966d0572a900">
<img width="612" alt="image" src="https://github.com/reportportal/reportportal/assets/28205157/6a3b457b-9b8c-4f33-8f98-99df0f1d95b8">

**Versions:**
 - Host OS: RockyLinux 9
 - Version of RP: 5.8.0

**Comment by irynakozak2** [comment]
@chanyk-joseph Hi! We have also encountered such issues in our Docker environments and plan to prepare a separate Docker compose file with the limits for the containers as a temporary solution. My recommendation is to add limits for the metrics-gatherer and analyzer-train services. For example, you can add the following lines to your docker-compose(for each mentioned service):

`  analyzer-train:
    image: reportportal/service-auto-analyzer:5.7.5
    deploy:
        resources:
            limits:
              cpus: 0.50
              memory: 512M
            reservations:
              cpus: 0.25
              memory: 128M    
    logging:
      <<: *logging
    environment:
      LOGGING_LEVEL: info
      AMQP_EXCHANGE_NAME: analyzer-default
      AMQP_VIRTUAL_HOST: analyzer
      AMQP_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      ES_HOSTS: http://elastic:elastic1q2w3e@elasticsearch:9200
      MINIO_SHORT_HOST: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      INSTANCE_TASK_TYPE: train
      UWSGI_WORKERS: 1
    depends_on:
      elasticsearch:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - reportportal
    restart: always`
    
Please let us know if the limits will help you. Besides, we plan to investigate and fix the issue in the upcoming versions as soon as possible.

**Comment by chanyk-joseph** [comment]
Hi @irynakozak2 , it works now, thank you for the effort and time!

**Comment by chanyk-joseph** [comment]
BTW, have we identified the root cause yet?

**Comment by irynakozak2** [comment]
@chanyk-joseph Hi! Yes, the issue was in the file descriptors count: uWSGI allocates memory by the system's max fd size. It can be easily resolved by adding the following environment variable to the **service-analyzer**, **service-analyzer-train**, and **metrics-gatherer** to limit file descriptors usage:

Valid only for docker-compose v3+:

`
UWSGI_MAX_FD=10000
`

Hope it helps! Waiting for your reply.

**Comment by irynakozak2** [comment]
@chanyk-joseph Hi! Did you have a chance to review and apply the solution above?

**Comment by chanyk-joseph** [comment]
Hi @irynakozak2 , I will get back to you before Apr

**Comment by irynakozak2** [comment]
@chanyk-joseph Hi! Could you please clarify if you had a chance to apply the solution above?

**Comment by chanyk-joseph** [comment]
Hi @irynakozak2 , Sorry to notice you that we are not able to test the setup on Linux as we have switched to Windows docker desktop deployment which is working fine at this moment. 

I will revisit the issue once we have migrated the setup to linux
