### ISSUE TITLE
Update docker_compose examples to v23.1.1

### ISSUE THREAD

**Issue by wargamez** [reportportal/reportportal#2108]
Are you planning to update the docker-compose files with the new version any time soon?

**Comment by MaryiaRymarchyk** [comment]
@wargamez yes, we plan to release new open source version soon, about 1-2 weeks.

**Comment by irynakozak2** [comment]
@wargamez Hi! Please check the 23.1.1 released docker-compose here:
https://github.com/reportportal/reportportal/tree/v23.1.1

Besides, we have also released the newer 23.2 version, please also check it out:
https://github.com/reportportal/reportportal/tree/v23.2

Seems like the question is resolved, but if you still have any specific issues, please consider creating a new one.
Thank you!
