### ISSUE TITLE
How to access ReportPortal Database?

### ISSUE THREAD

**Issue by saurabhsrivastava2009** [reportportal/reportportal#2110]
Hi Team,
How do we access the RP database?
I have a requirement where I would like to get some details from the database and based on that add a attribute with some value.
Is there a way to do that?

Thanks in advance :)

**Comment by MaryiaRymarchyk** [comment]
Hi @saurabhsrivastava2009 , find RP architecture here - https://github.com/reportportal/.
You can open connection in PgAdmin with host and credentials.
