### ISSUE TITLE
Cumulative trend chart doesn't show data in order of startTime

### ISSUE THREAD

**Issue by saurabhsrivastava2009** [reportportal/reportportal#2111]
Hi Team,
I have a confusion regarding the cumulative trend chart.
We have some runs and we are trying to build the chart based on master build number, as we can see in the below image.
![image](https://github.com/reportportal/reportportal/assets/38876539/7bffbbf9-092e-4064-a580-759803206638)
The data being presented here is correct but if you observe the bars are not based on the date. It has divided it based on numbers of tests. The one having more is to the left and the less one to the right.

Is this a expected behavior or something else needs to be done?

Here is a screenshot of the filter.
![image](https://github.com/reportportal/reportportal/assets/38876539/8246a760-21df-4562-b167-362e19fcc38a)

**Comment by DzmitryHumianiuk** [comment]
@saurabhsrivastava2009 strange behaviour.
Are all of these launches has the unique name?

**Comment by saurabhsrivastava2009** [comment]
@DzmitryHumianiuk no the launches have different names with a common attribute

**Comment by DzmitryHumianiuk** [comment]
@saurabhsrivastava2009 If your concern is related to the sorting order of the X-axis, it's based on the value in the X-axis, which in your case is `MasterBuildNumber`.

Aside from that, is everything else working as expected with it? 
Is the statistics for each individual `MasterBuildNumber` correctly aggregated for the launches that fall into that group?

**Comment by MaryiaRymarchyk** [comment]
@saurabhsrivastava2009 any updates here or the issue can be closed?

**Comment by alena-babrova** [comment]
Dear @saurabhsrivastava2009,

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to reopen it.
