### ISSUE TITLE
Unable to login reportportal with LDAP credentials.

### ISSUE THREAD

**Issue by MelakeGebrehawariatTR** [reportportal/reportportal#2115]
**Describe the bug**
Unable to login reportportal with LDAP credentials.

**Expected behavior**
Used to log in with no issues until recently

**Screenshots**
![rp error](https://github.com/reportportal/reportportal/assets/52469724/e47e8124-dd72-4c30-86ee-67172d297a56)

**Comment by MaryiaRymarchyk** [comment]
Hi @MelakeGebrehawariatTR ,
please specify which version of RP do you use and  did your LDAP user logged in/ reported data  recently? 
Is everything correct with LDAP integration? Could other users from your team login?

**Comment by HarshitSaraswatTR** [comment]
Hi @MaryiaRymarchyk ,
We are using the 5.7.4 version and we did report recently. Everything is correct with LDAP integration. I am also not able to login. Getting the same "User could not be found" error.

**Comment by MaryiaRymarchyk** [comment]
Hi HarshitSaraswat, it is hard to understand what was changed  if you didn't make any updates in application/changes in configuration. My proposal would be - update Report Portal to the latest version - 23.1 https://github.com/reportportal/reportportal/releases. Or another option is to rebuild services.
Docs for LDAP config - https://reportportal.io/docs/reportportal-configuration/authorization/LDAP

**Comment by MelakeGebrehawariatTR** [comment]
@MaryiaRymarchyk any updates on this? Look at my response above. Thanks!

**Comment by HarshitSaraswatTR** [comment]
Hi @MaryiaRymarchyk ,
We are only seeing the error when we are trying to log in with our LDAP account.

**Comment by MaryiaRymarchyk** [comment]
@MelakeGebrehawariatTR ,@HarsitSaraswarTR, please provide us with details to investigate the issue :
- ldap configuration (screenshot)
- logs from service-uat at the moment of unsuccessfull login
- evidence that user existing in Ldap

**Comment by HarshitSaraswatTR** [comment]
Hi @MaryiaRymarchyk , can we schedule a call. It will be easier for us to explain and you to understand what exactly is the issue.

**Comment by MaryiaRymarchyk** [comment]
@HarshitSaraswatTR, currently our team is busy with 23.2 release activities and it is not easy to allocate time for call, we assume that provided service-uat logs will help a lot with investigation, please provide info requested above.

**Comment by MelakeGebrehawariatTR** [comment]
@MaryiaRymarchyk can you log in to this report portal UI using your LDAP account?

https://cr-reportportal.1129.aws-int.thomsonreuters.com/ui/#login

Please try and let us know.

**Comment by MaryiaRymarchyk** [comment]
@HarshitSaraswatTR  following recommendations may help you to solve the issue:
1. Ensure the password set on the Service Account in Safeguard matches that of AD
2. Ensure "User must change password at next logon" is unticked in the users Account properties in AD
3. Ensure the account in AD is not locked or disabled
4. Ensure there no "Logon Hours" restrictions in the users Account properties in AD
5. Ensure "Log On To" in the users Account properties in AD is set to "All Computers"
6. Ensure the password set on Service Account in Safeguard matches with password set on managed account under AD asset.

**Comment by MaryiaRymarchyk** [comment]
@HarshitSaraswatTR  did you manage to solve the issue? any updates?

**Comment by DzmitryHumianiuk** [comment]
Assuming as resolved.
