### ISSUE TITLE
[DASHBOARD] no search for "ADD SHARED WIDGET" window

### ISSUE THREAD

**Issue by iKozzz** [reportportal/reportportal#212]
It's unable to search for shared widget when adding to dashboard. You should find it in the list.

**Comment by DzmitryHumianiuk** [comment]
@Iren-Melnyk could you please review this request?

**Comment by DzmitryHumianiuk** [comment]
![image](https://user-images.githubusercontent.com/11332788/31892297-56ba16f8-b811-11e7-96f3-00fc25571f90.png)
@Iren-Melnyk

**Comment by Iren-Melnyk** [comment]
@iKozzz 
Where in the app do you want to search for the shared widget? Do you mean to search for shared widget while you make a new dashboard and want to add this shared widget on it?

**Comment by iKozzz** [comment]
@Iren-Melnyk 
Yes. This is for dialog of adding shared widget to dashboard

**Comment by Iren-Melnyk** [comment]
@iKozzz 
Ok, thanks. We'll improve this.
