### ISSUE TITLE
Wrong links in filtered launch list view duo to some cache issue

### ISSUE THREAD

**Issue by dorShalomRedis** [reportportal/reportportal#2120]
**Describe the bug**
When clicking a link in the launch list view it saves the url for some reason
and then other links (which suppose to point to different urls) leads to the first link.

**Expected behavior**
links should work as expected

**Screenshots**
look at the url in the bottom left corner 
https://github.com/reportportal/reportportal/assets/102724292/e635c4fa-5a23-45d6-8164-f57e7532de67

**Versions:**
 - OS, Browser
 Mac, Chrome
 - Version of RP [find it under Login form, copy as is]
Build: 5.7.4

**Comment by MaryiaRymarchyk** [comment]
Hello @dorShalomRedis , i see issue from the video whereas I can't reproduce it in our instances. 
I haven't try MAC yet, in Windows it works fine. I am going to check MAC later.
Anyway I suggest to upgrade RP version to the latest and  try again.

**Comment by alena-babrova** [comment]
Hello @dorShalomRedis,

Yes, indeed, there is a bug with links rendering. We have reproduced it in our environment.
I have registered a bug in our backlog. Once it is fixed, I will reflect in the thread.

Thank you for your contribution!

**Comment by VeranikaRymzha** [comment]
Hello @dorShalomRedis ,
I wanted to let you know that the ReportPortal 24.2 version is now live, along with the improvement you've requested.

You can find more details about the new features and enhancements in the [release notes](https://reportportal.io/docs/releases/Version24.2/). 
Feel free to try it out and share any feedback you may have.

Have a great day!
