### ISSUE TITLE
NEED Help:- 

### ISSUE THREAD

**Issue by subha0990** [reportportal/reportportal#2121]
Hi Team,

I have jenkins job created for robot framework tests. I want to run my robot framework tests from jenkins and see the results in  report portal. 
**What is the configuration i need to do from jenkins ?**

His is how i added parameters from jenkins but no data pushed to report portal
![image](https://github.com/reportportal/reportportal/assets/140379815/03b33da2-1693-430b-a9e9-cb289e20a5ac)

I referred this page but did not get much info.
https://reportportal.io/docs/quality-gates/IntegrationWithCICD/IntegrationWithJenkins

**Comment by subha0990** [comment]
Any Update Team ?

**Comment by yarynafd** [comment]
@subha0990 have you found the solution?
