### ISSUE TITLE
Error in ARM image of service-authorization

### ISSUE THREAD

**Issue by hriddhighosh4** [reportportal/reportportal#2124]
On deploying arm image of service-authorization 5.8.0-arm64 getting error 

```Error: Unable to access jarfile service-authorization-doc5.8.0-exec.jar```

Image URL - https://hub.docker.com/layers/reportportal/service-authorization/5.8.0-arm64/images/sha256-cac6b47970fa59d67b8a4e19a5591f09fb0c2c99ea8aec57b8f0dea63729e4bd?context=explore

**Comment by DzmitryHumianiuk** [comment]
@hriddhighosh4 should be fixed now with full multi-platform images support
