### ISSUE TITLE
Need Help:- How to send email notification on start of launch 

### ISSUE THREAD

**Issue by subha0990** [reportportal/reportportal#2127]
Hi Team,

Could you pls help me How to send email notification on start of launch ?

Thanks In Adv

**Comment by Kozovskaya** [comment]
Hello @subha0990, 
Currently, ReportPortal functionality provides only an ability to create Notification rules only on launch finish event.
https://reportportal.io/docs/reportportal-configuration/ProjectConfiguration/#e-mail-notifications, point 11
