### ISSUE TITLE
What is the best approach migrating reportportal with a separate database (not container) ??

### ISSUE THREAD

**Issue by anetka07** [reportportal/reportportal#2128]
**Describe the bug**
After trying to upgrade reportportal from 5.7.4 to 23.1 we have a problem with the database, which is set up separately on this same server (rhel).
First we updated docker-compose, in the next step we execute on database scripst that are different from version 5.7.3 on branch master https://github.com/reportportal/migrations/tree/5.7.3/migrations compared to 5.10.0 : https://github.com/reportportal/migrations/tree/5.10.0/migrations
So that was scripts from 60 do 72_up.  Aplication containers start up successfuly, but thats gives 2 error on database with table activity that no have column user_id and "public.api_keys" does not exist  - was in another schema.

I don't have the entire logs due to the quick downgrade and restoring the database from a backup.
But my question is like in the topic : 
What is the best approach migrating reportportal with a separate database ?

**Versions:**
 - OS, Browser rhel7, postgres11 soon will be 15
 - Version of RP [5.7.4]

**Comment by DzmitryHumianiuk** [comment]
assume resolved
