### ISSUE TITLE
Report portal version Build: 5.3.4 is not removing the old launches

### ISSUE THREAD

**Issue by satizz123** [reportportal/reportportal#2129]
**Describe the bug**
...
I'm using report portal version 5.3.4 , and i specified the retention period for launches and logs as 30 days. however I still see the launches which executed three year before. 

I'm using docker-compose.yml file to bring up the service. I didn't set the  RP_ENVIRONMENT_VARIABLE_CLEAN_LAUNCH_CRON in services-jobs section. Is it mandatory to set this variable. Suppose if I specify the retention period as 30 days and specified the RP_ENVIRONMENT_VARIABLE_CLEAN_LAUNCH_CRON in service-jobs section, Will it delete the file which are older than 30 days ?  or Will it remove the entire logs?

**Comment by HardNorth** [comment]
@satizz123 Version 5.3.4 is already 2.5 years old and it was known issue for this release as I recall. If you need that feature working you have to update to newer versions, see: https://github.com/reportportal/reportportal/releases

**Comment by satizz123** [comment]
@HardNorth Thank you. Do I need to specify the environment variable RP_ENVIRONMENT_VARIABLE_CLEAN_LAUNCH_CRON  along with UI genera keep logs setting ?  Or only specifying the project->general setting is enough ?
