### ISSUE TITLE
[DASHBOARD] Owner can't see owned widgets in "SELECT SHARED WIDGET" list

### ISSUE THREAD

**Issue by iKozzz** [reportportal/reportportal#213]
Go to dash board (or create one)
Click ADD SHARED WIDGET button

**Expected**: User should be able to add own widgets (shared) to multiple dashboards. (instead of creating same widget with different name)

**Actual**: Only foreign widgets are shown in the list.

**Comment by DzmitryHumianiuk** [comment]
will discuss with the team

**Comment by pbortnik** [comment]
Ignoring own shared widgets in the list of them are removed.
