### ISSUE TITLE
Api service is crashing frequently due to "OutOfMemoryError" 

### ISSUE THREAD

**Issue by sramasudha** [reportportal/reportportal#2130]
**Describe the bug**
...
Api service is crashing frequently due to "OutOfMemoryError" 
Issue is observed more while browsing the testcase results having more number of test steps.
PFA below
**Expected behavior**
...

**Screenshots**
If applicable
<img width="1007" alt="image" src="https://github.com/reportportal/reportportal/assets/112937362/91e47520-bbb4-4cce-929a-5a8840ef31b1">

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]
 -

**Logs:**
```
Exception in thread "http-nio-8585-Acceptor" Exception in thread "not.a.Spring.bean-1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AsyncAppender-Worker-ASYNC_CONSOLE"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "not.a.Spring.bean-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "not.a.Spring.bean-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "http-nio-8585-Poller"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AMQP Connection 172.20.0.4:5672"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "reportportal_QuartzSchedulerThread"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "http-nio-8585-Acceptor"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "not.a.Spring.bean-1"
Exception in thread "not.a.Spring.bean-1" java.lang.OutOfMemoryError: Java heap space
Exception in thread "not.a.Spring.bean-1" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-3-thread-2" java.lang.OutOfMemoryError: Java heap space
Exception in thread "analyzerRabbitTemplate#0-consumerMonitor-1" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-2-thread-2" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-8585-exec-5" java.lang.OutOfMemoryError: Java heap space
com.sun.org.apache.xerces.internal.util.XMLGrammarPoolImpl()

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "not.a.Spring.bean-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-3-thread-2"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "not.a.Spring.bean-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "reportportal_QuartzSchedulerThread"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "http-nio-8585-Acceptor"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "http-nio-8585-Poller"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "not.a.Spring.bean-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#0-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "not.a.Spring.bean-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "not.a.Spring.bean-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "not.a.Spring.bean-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "HikariPool-1 housekeeper"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "not.a.Spring.bean-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-2-thread-2"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "not.a.Spring.bean-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "QuartzScheduler_reportportal-api:59f4ab150401a0c5fd4d1bf46a0f957f_MisfireHandler"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "not.a.Spring.bean-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "not.a.Spring.bean-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AMQP Connection 172.20.0.4:5672"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Catalina-utility-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AMQP Connection 172.20.0.4:5672"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "default-task-sched5"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "default-task-sched4"
root@reportportal:~#
```

**Comment by sramasudha** [comment]
docker stats:

CONTAINER ID   NAME                              CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
686b37a36768   reportportal-analyzer-1           0.32%     6.644GiB / 31.64GiB   21.00%    183GB / 80.1GB    608MB / 125MB     226
4f8184ef992d   reportportal-analyzer_train-1     0.01%     91.49MiB / 31.64GiB   0.28%     14MB / 13.1MB     27.7MB / 14.6MB   32
a81c0e8cbc42   reportportal-api-1                1.05%     1.42GiB / 31.64GiB    4.49%     23.3GB / 15.1GB   142MB / 12.3kB    109
7f3caff7265c   reportportal-metrics-gatherer-1   0.01%     141.1MiB / 31.64GiB   0.44%     12GB / 164MB      172MB / 442kB     18
eb2613ebffe8   reportportal-uat-1                0.08%     730.2MiB / 31.64GiB   2.25%     101MB / 90.1MB    687MB / 61.4kB    46
2e14e4e85925   reportportal-uat-2                0.07%     747.3MiB / 31.64GiB   2.31%     102MB / 92MB      648MB / 295kB     43
314f39bfd54d   reportportal-index-1              0.00%     12.96MiB / 31.64GiB   0.04%     72.5MB / 14.7MB   62MB / 0B         10
c7cc58724a99   reportportal-autoheal-1           0.00%     12.74MiB / 31.64GiB   0.04%     227kB / 0B        14.3MB / 4.48MB   2
62c952a0bc90   reportportal-gateway-1            1.51%     25.01MiB / 31.64GiB   0.08%     6.48GB / 8.07GB   84MB / 53.2kB     23
1cb5c9245a19   reportportal-minio-1              2.42%     113.1MiB / 31.64GiB   0.35%     42.7GB / 791MB    1.37GB / 812MB    25
7938e5d4ba8b   reportportal-elasticsearch-1      2.62%     2.167GiB / 31.64GiB   6.85%     79GB / 124GB      27.6GB / 153GB    119
b6b4154b5d3a   reportportal-ui-2                 0.00%     10.12MiB / 31.64GiB   0.03%     7.55MB / 238MB    57.4MB / 0B       2
b242ce809642   reportportal-rabbitmq-1           0.93%     3.75GiB / 31.64GiB    11.85%    80.9GB / 62.5GB   137MB / 20GB      38
df43f54b0574   reportportal-ui-1                 0.00%     6.688MiB / 31.64GiB   0.02%     7.12MB / 218MB    54.1MB / 0B       2
44379ff03706   reportportal-postgres-1           0.95%     8.245GiB / 31.64GiB   26.06%    34.1GB / 350GB    448GB / 756GB     234

**Comment by DzmitryHumianiuk** [comment]
@sramasudha at least you should get rid of all duplicated containers, which has `-2` postfix. That's UI and UAT.
And i have no idea what is `autoheal` container.

As for the Java Heap:
set more in heap size in params for service-api here https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L224
like that: https://stackoverflow.com/questions/1565388/increase-heap-size-in-java

**Comment by irynakozak2** [comment]
@sramasudha Hi! Long time no hear from you, so I close that issue as for now.
However, please find below the stable JAVA_OPTS we are using currently in our environments (for "-Xmx" you can set the more suitable than 1Gb, e.g. RP_host_os_memory/2):

```
JAVA_OPTS: -Xmx1g -Djava.security.egd=file:/dev/./urandom -XX:+UseG1GC -XX:+UseStringDeduplication -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=60 -XX:MaxRAMPercentage=70.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp
```

If the issue is still relevant for you even on those JAVA_OPTS and after applying the suggestions above, please consider creating a new GitHub issue.
Thank you!

**Comment by sramasudha** [comment]
Hi @irynakozak2,
Thanks for the information, I have not observed this issue after upgrading to  Build: 5.10.0.
