### ISSUE TITLE
Doubt double entry logs in 2023.1 release

### ISSUE THREAD

**Issue by babantax** [reportportal/reportportal#2132]
Good morning,
After read 2023.1 release in deep, I´m quite confuse about the change of where Report Portal save logs of the launches.
As far as I understand:
- If I **enable** "doubleEntry", test logs will be saved in Posgresql and in ElasticSearch
- If I **disable** "doubleEntry", test logs will be **only** saved in ElasticSearch
Please, correct me if I´m wrong.

My main concern is what happens in case of a Data lost or corrupted with this new this version. 
With previous versions, in case of ElasticSearch data issue, was just fixed with a regenerate index of the projects.

I have been testing the elastic search recovery snapshots capability and seems not very trustable.... Which options do you recommend to save the data in a safe way.
Thanks a lot in advance

**Comment by alena-babrova** [comment]
Hello @babantax,
There is a correction in your statements:

- If I **disable** "doubleEntry", test logs will be **only** saved in **Posgresql** 

So you can safely disable the option - all test logs will be saved into the DB.

**Comment by DzmitryHumianiuk** [comment]
@babantax, the reason for having two sources to save logs is to facilitate the transitional period as we switch log storage from PostgreSQL to Elastic/OpenSearch.

Having duplicated records removes the need for data migration.

However, the drawback is the increased complexity in maintaining and backing up RP data.

Although Elastic/OpenSearch provides us with a x5-8 times increase in log processing and clean-ups, considering the challenges in maintenance and the computational power required, we took some time to re-evaluate our options. 

Based on this, we'll decide whether to continue with Elastic or explore other avenues.

**Comment by babantax** [comment]
Hello @DzmitryHumianiuk,
Totally clear now :) I was a little worried about move data to Elastic/OpenSearch as last dry runs I did to recover a backup from Elastic/OpenSearch (in my case I have it under AWS) was not success and I want to avoid loss data problems.
Thank a lot for the info
