### ISSUE TITLE
Invalid access token issue with report portal 

### ISSUE THREAD

**Issue by yadhavaram** [reportportal/reportportal#2134]
Hi,
We are using report portal API to generate reports for functional tests, and we are facing some weird issue. I have generated access token from UI. And that user has ADMINISTRATOR permissions. When accessing projects api (/api/v1/project/names/search) we are getting following response.
`{
    "error": "invalid_token",
    "error_description": "Invalid access token"
}`

Version details:
Build: 5.9.0

We are accessing API via Authorization Header  with token generated under  profile section of that administrator user.
Bearer <<Access token generated via UI>>
I couldn't able to find any container logs pertaining to this invalid token(Even in API or authorization container). One another thing we are updating report portal to new version aligning to report portal compose file present in master branch.

Any leads would be useful to debug the issue?

**Comment by varundunga** [comment]
did you try changing the Bearer to bearer(b should be small letter).
it should be of format bearer <apikey>

**Comment by HardNorth** [comment]
@yadhavaram You should include the whole token as it appear on screen with named prefix, not only encoded part.
@varundunga `Bearer` is correct form by RFC standard.

**Comment by DzmitryHumianiuk** [comment]
Assuming as resolved.
@yadhavaram open new issue if still actual
