### ISSUE TITLE
PostgreSQL memory leak after last update in kubernetes

### ISSUE THREAD

**Issue by mmohrwinkel** [reportportal/reportportal#2136]
**Describe the bug**
Since the last update (to 5.7.4) we are experiencing strange behaviour with the postgres in our stup inside a kubernetes cluster. Postgres is accumulating more and more RAM with every run and never releasing the ram again. We can only free it again if we redeploy the container. We have experienced it using more than 73GB. 

In the logs there is thousands of messages like this:

```shell
23 20:51:02.293 GMT [292998] STATEMENT:  insert into public.log (attachment_id, cluster_id, last_modified, launch_id, log_level, log_message, log_time, project_id, item_id, uuid) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
 RETURNING *
2023-09-23 21:44:38.129 GMT [298186] ERROR:  invalid byte sequence for encoding "UTF8": 0x00
``` 

It seems that it is trying to write 0 Characters into the field "log_message", which is not supported because it is a text field. Do you have any idea how we can get rid of that problem?

**Expected behavior**
Postgres should run with a decent amount of RAM and should free up unused RAM regularly

**Screenshots**
- 

**Versions:**
 - OS, Browser: Any
 - Version of RP 5.7.4
   Current version:API Service: 5.7.4;Index Service: 5.7.3;Jobs Service: 5.7.4;Authorization Service: 5.7.4;Service UI: 5.7.4;

**Comment by DzmitryHumianiuk** [comment]
@pbortnik ^ looks like a serious issue

**Comment by raikbitters** [comment]
@mmohrwinkel hello. Could you specify the PostgreSQL version that you use?

**Comment by mmohrwinkel** [comment]
Hi @raikbitters it should be 11.13.0

**Comment by pmaus22** [comment]
Hi, we have the same problem running ReportPortal v5.7.3 and PostgreSQL v12.9 via Docker Compose. We did not notice an increase in RAM usage but the log of the database container is full of these error messages, with hundreds of them coming in every day:

```
reportportal-v5-postgres-1  | 2023-11-28 07:23:44.063 UTC [153676] ERROR:  invalid byte sequence for encoding "UTF8": 0x00
reportportal-v5-postgres-1  | 2023-11-28 07:23:44.063 UTC [153676] STATEMENT:  insert into public.log (attachment_id, cluster_id,
last_modified, launch_id, log_level, log_message, log_time, project_id, item_id, uuid) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
reportportal-v5-postgres-1  |   RETURNING *
```
We are also currently trying to get rid of that problem because the db log is getting really cluttered with these errors. Please let me know if there is a solution yet or if I can provide any more information to help resolve the issue!

**Comment by raikbitters** [comment]
@pmaus22 hello. You should update your version to the latest (23.2); it can help.
Moreover, can you provide a log request payload? It looks like you send a null character in a log message.

**Comment by Pikaboo48** [comment]
Hello! We were able to solve it by checking the logs from test plans and noticing there are not in UTF8 encoding which resulted in flooded database with the above errors. 
![image](https://github.com/reportportal/reportportal/assets/127962362/05889541-6d1d-4019-bbb2-85c86975e314)
just check for any weird characters in your logs :heart:

**Comment by irynakozak2** [comment]
@Pikaboo48 Hi! Thank you for the updates. Glad to hear the issue is resolved. I'll close that issue for now.
