### ISSUE TITLE
How to send images attachment in POST api/v1/{projectname}/log in Script using TestComplete Jscript

### ISSUE THREAD

**Issue by pradeep1299** [reportportal/reportportal#2139]
> To create a log with an attachment you should send a POST request to the 'api/v1/{projectname}/log' endpoint and configure it like this:
> 
> 1. content type of the request - multipart/form-data
> 2. in the body of the request should be 2 params:
>    a) json_request_part - json file of the following format:
>    [
>    {
>    "file":{
>    "name":"NAME_OF_THE_FILE_TO_UPLOAD"
>    },
>    "itemId":"ID_OF_THE_TEST_ITEM",
>    "level":"LOG_LEVEL",
>    "message":"YOUR_MESSAGE",
>    "time":"2019-11-15T14:35:55.006Z"
>    }
>    ]
>    b) file - all files that you want to upload (file names should match with file names from the 'json_request_part'
> 
> Here is a raw example from Postman ![image](https://user-images.githubusercontent.com/31598109/52042679-d6a00980-254e-11e9-8e42-f49a2d1c9bb0.png)

The API request mentioned above was sent using Postman, but when attempting to send an image as part of the multipart/form-data in a script, we encountered an issue. 
<img width="865" alt="image" src="https://github.com/reportportal/reportportal/assets/50439015/da6a9147-488b-45c6-b2ba-06178ed4151a">
Is there anyone available to assist with uploading an image in Report Portal (RP)?

**Comment by HardNorth** [comment]
@pradeep1299 This might be storage issue, did you check API logs?

**Comment by pradeep1299** [comment]
Could you assist me in understanding the process for reviewing API logs?

**Comment by DzmitryHumianiuk** [comment]
@pradeep1299 if you run a ```docker ps -a``` command in your terminal, you will see the list of the running containers.
Then you need the ID of `service-api` container and follow the next:

https://phoenixnap.com/kb/docker-container-logs#:~:text=Docker%20Command%20for%20Checking%20Container%20Logs,-The%20docker%20logs&text=Replace%20container_id%20with%20the%20ID,command%20to%20list%20running%20containers.&text=As%20in%20the%20image%20below,specific%20container%20in%20the%20output.

**Comment by DzmitryHumianiuk** [comment]
@alena-babrova are there any suggestions from your end on Postman configuration how to send the logs with attachements?

**Comment by DzmitryHumianiuk** [comment]
@pradeep1299 try this for the configuration of the POstman:
https://github.com/reportportal/reportportal/issues/1841#issuecomment-1251540710
