### ISSUE TITLE
SAML login redirects to http:// instead of https:// after successful OKTA authentication

### ISSUE THREAD

**Issue by abalasub-wm** [reportportal/reportportal#2144]
**Describe the bug**
SAML login redirects to http:// instead of https:// after successful OKTA authentication
I have same issue as described in this https://github.com/reportportal/reportportal/issues/1660 
**Expected behavior**
https to https

**Screenshots**
If applicable

**Versions:**
 - OS, Browser - Mac and chrome
 - Version of RP - Current version:API Service: 5.10.0;Index Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0;

**Comment by raikbitters** [comment]
@abalasub-wm hello. Could you show your OKTA configuration?

**Comment by abalasub-wm** [comment]
@raikbitters Please find the screenshot
![image](https://github.com/reportportal/reportportal/assets/77071859/21e1bfb1-d723-4348-aef6-ef7efb33ece5)

**Comment by abalasub-wm** [comment]
Docker compose logs 

`docker-compose-uat-1               | 2023-10-04 21:31:42.187 DEBUG 1 --- [nio-9999-exec-4] o.s.security.web.FilterChainProxy        : Securing POST /saml/sp/SSO/alias/report-portal-sp
docker-compose-uat-1               | 2023-10-04 21:31:42.188 DEBUG 1 --- [nio-9999-exec-4] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
docker-compose-uat-1               | 2023-10-04 21:31:42.258 DEBUG 1 --- [nio-9999-exec-4] s.p.s.a.SamlAuthenticationResponseFilter : Set SecurityContextHolder to com.epam.reportportal.auth.integration.saml.ReportPortalSamlAuthentication@46a74a57
docker-compose-uat-1               | 2023-10-04 21:31:42.266 DEBUG 1 --- [nio-9999-exec-4] o.s.s.web.DefaultRedirectStrategy        : Redirecting to http://<dns>.tech/ui/#authSuccess?token=eXXXXosYiberAcuz5Pf_U46w&token_type=bearer
docker-compose-uat-1               | 2023-10-04 21:31:42.267 DEBUG 1 --- [nio-9999-exec-4] w.c.HttpSessionSecurityContextRepository : Created HttpSession asSecurityContext is non-default`

**Comment by raikbitters** [comment]
@abalasub-wm this's a ReportPortal SAML configuration. For redirecting, Identity providers can use their configuration. Could you check the Single sign-on URL value on the OKTA side?

**Comment by abalasub-wm** [comment]
![image (28)](https://github.com/reportportal/reportportal/assets/77071859/caf4f99b-80a0-4677-a67f-a3bd60e9b246)

**Comment by abalasub-wm** [comment]
![image (28)](https://github.com/reportportal/reportportal/assets/77071859/775872d5-62e1-4607-89a9-3405a9d36588)

**Comment by raikbitters** [comment]
Do you have a gateway that redirects this request from https to http? As an option, you can check redirect in the browser developer console in the Network tab.

**Comment by abalasub-wm** [comment]
We are using an Application load balancer in front of EC2 with docker compose where the target ports are like below

`  target_group_ports = [ { from_port="80", to_port="8081", protocol="HTTP" },
                         { from_port="443", to_port="8081", protocol="HTTPS" },
                         { from_port="8081", to_port="8081", protocol="HTTP" } ]`

**Comment by raikbitters** [comment]
It looks like ALB redirects your traffic to http

**Comment by abalasub-wm** [comment]
Nope no WAF settings. I hit https url and able to login as https when using custom user (superadmin) - This is without saml. 

When it comes to saml login. I hit https URL . click saml login and after okta verify , I'm able to login as saml user but the end point is in secure.

**Comment by abalasub-wm** [comment]
![Screenshot 2023-10-05 at 10 15 37 AM](https://github.com/reportportal/reportportal/assets/77071859/31c01087-0485-45a1-82ce-42ddcd7408f8)

**Comment by abalasub-wm** [comment]
![Screenshot 2023-10-05 at 10 20 44 AM](https://github.com/reportportal/reportportal/assets/77071859/70c89d22-6c31-43b7-a453-d48b09d1b314)

**Comment by raikbitters** [comment]
Could catch request data which REportPortal sand to SAML IDp? There is a payload. 
![image](https://github.com/reportportal/reportportal/assets/13565058/07cae137-4915-420a-b545-343a24e65b5c)
Decode it, and please check the AssertionConsumerServiceURL value.

**Comment by raikbitters** [comment]
Moreover, you can try this approach for debug https://help.okta.com/oag/en-us/content/topics/access-gateway/add-app-saml-pass-thru-test.htm#Configure

**Comment by abalasub-wm** [comment]
Yes I decoded that response and looks good only

`<?xml version="1.0" encoding="UTF-8"?><saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceURL="https://<DNS>/uat/saml/sp/SSO/alias/report-portal-sp" Destination="https://ssodev.<domain>.com/app/xxxx/sso/saml" ForceAuthn="false" ID="XXX" IsPassive="false" IssueInstant="2023-10-05T14:30:15.166Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"><saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">report.portal.sp.id</saml2:Issuer></saml2p:AuthnRequest>`

**Comment by raikbitters** [comment]
Looks like an infrastructure routing issue. I can't reproduce it. To be sure, try to catch a request from the Okta side to `/uat/saml/sp/SSO/alias/report-portal-sp.`

**Comment by abalasub-wm** [comment]
![Screenshot 2023-10-05 at 3 33 01 PM](https://github.com/reportportal/reportportal/assets/77071859/6aa506f0-948d-400d-ae4e-d47f7aae8f7c)

**Comment by abalasub-wm** [comment]
I was able to resolve it after adding forward headers in Traefik

- --entrypoints.web.forwardedheaders.trustedips=0.0.0.0/0

**Comment by geoL86** [comment]
+1
