### ISSUE TITLE
'No space left on device' error occurs when tests try to post data to Report Portal, when linux agent has enough space

### ISSUE THREAD

**Issue by Roman1137** [reportportal/reportportal#2147]
**Describe the bug**
It has been 3 weeks since Report Portal was installed on a Linux agent.
But now there is a problem that launches are displayed as started and not finished. Also, launches do not include any information about tests.

![image](https://github.com/reportportal/reportportal/assets/32763749/1735c29e-ca21-4ed3-b908-54420f8a6092)

I took a look at the logs on API container and found 'No space left on device' error:
![image](https://github.com/reportportal/reportportal/assets/32763749/085e7ad2-9611-4683-b849-17fe305b821c)

After that, I checked a space on my Linux agent. The space is enough, I believe:
![image](https://github.com/reportportal/reportportal/assets/32763749/bf88bd9b-4e54-46ef-b900-e3a9b4fd55f9)

**Expected behavior**
Error about not enough space should not occur when there is no space shortage on a device.

**Screenshots**
If applicable

**Versions:**
 - OS: Ubuntu 22.04.3 LTS, Release:        22.04
 - Version of RP Current version:API Service: 5.9.2;Index Service: 5.8.0;Jobs Service: 5.8.2;Authorization Service: 5.8.2;Service UI: 5.9.0;

**Comment by Roman1137** [comment]
Unfortunately, I was not able to resolve this issue.

I have tried specifying a folder in 'volumes' section for Postgres.
![image](https://github.com/reportportal/reportportal/assets/32763749/95bdabc1-62ab-4ef6-b9f5-b4d9c60aac76)
I added a  'data/postgres' folder manually and graded the permissions according to this instruction(did it for data/postgres).
So Docker could mount the folder.
![image](https://github.com/reportportal/reportportal/assets/32763749/071a66bb-fb58-4eee-adfd-024a1c0ea6d3)

But, unfortunately, I did not help. I still have 3.9Gb of memory, and the volume is not mounted.
![image](https://github.com/reportportal/reportportal/assets/32763749/3b54821d-b41f-4fa4-b4e2-c20daa59294f)

Also, I figured out that there are docker volumes in the initial docker-compose. That was a change introduced on 18th of September 2023
![image](https://github.com/reportportal/reportportal/assets/32763749/9e0e673f-2cb8-42c6-813e-5b8515c79aac)
I deleted 'postgres' from that section and tried to mount the folder accordingly:
![image](https://github.com/reportportal/reportportal/assets/32763749/cca6aa7d-2f66-4808-8b7a-cab11c94b2fd)
But that did not help either.

May be, I am using the wrong docker-compose file?
I will attach an actual docker-compose file that I am using.

I also tried executing the commands for deleting all volumes/images/containers from docker and rebooted the agent afterward:
docker image prune
docker container prune
docker volume prune
docker system prune
docker builder prune

Another option might be to increase the default disk space allocated to Docker Volume by default. But I do not know how to do that.
But it is definitely clear from the screenshot that Iryna shared, that there should be some shared volume:
image.png

Please, advise what I am doing wrong.

**Comment by DzmitryHumianiuk** [comment]
@Roman1137 have you tried this execution on the DEMO instance?
https://demo.reportportal.io/

please see if it reports perfectly there.

**Comment by DzmitryHumianiuk** [comment]
@Roman1137 the compose file you shared is not related to the ReportPortal, but to selenoid.

the link to the latest compose file is here: https://github.com/reportportal/reportportal/blob/master/docker-compose.yml

**Comment by Roman1137** [comment]
@DzmitryHumianiuk, thanks for the reply.
Sorry for sharing the wrong file.
Here is the actual docker-compose file:
[docker-compose.txt](https://github.com/reportportal/reportportal/files/13161566/docker-compose.txt)

**Comment by Roman1137** [comment]
@DzmitryHumianiuk , demo server will not help in this case.
I have report portal running fine (launches, dashboards, everything worked) for 3 weeks and then the issue with memory happened.

**Comment by Roman1137** [comment]
I see, that there is a commit made on September 18th 2023
![image](https://github.com/reportportal/reportportal/assets/32763749/560af766-0dc3-4471-925e-d5d6500d93f0)
Link: https://github.com/reportportal/reportportal/commit/87d80ec89d647de2af9db42f2415c1fce9a7fc5c

that gives the instruction to docker use 'Docker volumes'
![image](https://github.com/reportportal/reportportal/assets/32763749/72632d06-967f-41a6-a914-3c91bca843e0)

instead of 'regular volumes':
![image](https://github.com/reportportal/reportportal/assets/32763749/1b431e6f-8c05-43a4-82d7-3455b1b69b40)

I think that there might a case.

**Comment by Roman1137** [comment]
The issue was resolved.
1) I used the latest docker-compose file
2) Then added this file in /etc/docker/daemon.json (this will be applied to all containers):
{
    "storage-driver": "devicemapper",

    "storage-opts": [

        "dm.basesize=20G"
    ]
}
3) Restarted the agent
4) And it mapped the folder
![image](https://github.com/reportportal/reportportal/assets/32763749/6742f0a9-2606-44fa-867e-a0749f0213ce)
