### ISSUE TITLE
Test runs sometimes hangs with Start test item is not allowed. Parent Item '' already has log items

### ISSUE THREAD

**Issue by adamkanovak** [reportportal/reportportal#215]
Exception in thread "RxCachedThreadScheduler-3" io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
error    11-Aug-2017 01:21:08    Status code: 406
error    11-Aug-2017 01:21:08    Status message: 
error    11-Aug-2017 01:21:08    Error Message: Start test item is not allowed. Parent Item '598d4cd136d1a0000626c873' already has log items
error    11-Aug-2017 01:21:08    Error Type: START_ITEM_NOT_ALLOWED

From avarabyeu:
This is our old constraint - only items without childs may have logs.

**Comment by DzmitryHumianiuk** [comment]
@adamkanovak 
this is constraint.

We expect that only test cases, as an end level in hierarchy can have logs.
If you item already have logs: this should be a test cases, and it should not have sub objects.

Could you please give details? Which integration do you use?

**Comment by adamkanovak** [comment]
Cucumber JVM 3.0.0,
Report Portal is on Build: 3.0.2

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu is it in 3.3 or only 4.0?
