### ISSUE TITLE
Report portal launches/attachments/logs are not cleaned up based on retention settings

### ISSUE THREAD

**Issue by rajbht** [reportportal/reportportal#2150]
**Describe the bug**

Report portal is currently configured to retain data up to 7 days, but this has never worked. We had to clean up storage every 2 months, as we stop seeing failure screenshots in report portal and `no space left` errors in the logs.

...

**Expected behavior**

Launches/Logs/Attachment should be cleaned up based on the retention window selected in the RP settings.

...

**Screenshots**
If applicable
![Screenshot 2023-10-05 at 12 51 10 PM](https://github.com/reportportal/reportportal/assets/11417923/45f50ed5-f994-4d4b-afd1-8f0237447155)

**Versions:**

 - Version of RP [find it under Login form, copy as is]
Current version:API Service: 5.6.2;Authorization Service: 5.6.2;Service UI: 5.6.0;

**Comment by DzmitryHumianiuk** [comment]
@rajbht probably your cleaning jobs are not configured properly.
And there was a fix for that in version 5.7.

Please update to the latest version to implement the fix.
Re-open the issue if still relevant.
