### ISSUE TITLE
***Need Help:- To add more main bugs group from report portal

### ISSUE THREAD

**Issue by subha0990** [reportportal/reportportal#2152]
HI Team,

Could you pls help me with how to add more main bugs group from report portal. Currently we have only 5 groups.
1. PRODUCT BUGS GROUP
2. AUTOMATION BUGS GROUP
3. SYSTEM ISSUES GROUP
4. SYSTEM ISSUES GROUP
5. TO INVESTIGATE GROUP

Thanks in Advance

**Comment by Kozovskaya** [comment]
Hi @subha0990! Unfortunately there is no ability to add additional defect type groups. There is 5 main defect type groups and you still have the ability to create sub defects.
