### ISSUE TITLE
landing page redirect issue

### ISSUE THREAD

**Issue by abalasub-wm** [reportportal/reportportal#2157]
Describe the bug
I'm using docker-compose with Linux setup. To access the application URL I need to give /ui/ to access the login page.
Is there a way I can have an automatic redirect to the login page if I hit the URL?

Expected behavior
Hit the application in the browser and land in /ui/
Screenshots
If applicable

Versions:

OS, Browser - Chrome
Version of RP [find it under Login form, copy as is] - 5.10

**Comment by Pink-Bumblebee** [comment]
Could you please explain what do you mean by "automatic redirect"?
Actually, RP login page is opening if you hit the link : http://<your.ip>:8080
(point 5 in https://reportportal.io/docs/installation-steps/DeployWithDockerOnLinuxMac/#deploy-reportportal-with-docker )

**Comment by abalasub-wm** [comment]
That helps thanks.
My target group in ALB was pointing from 443 to 8081 instead of 8080.
