### ISSUE TITLE
Flaky test cases table (TOP 50) widget Skipped tests handle

### ISSUE THREAD

**Issue by qasamppa** [reportportal/reportportal#2159]
**Describe the bug**
Skipped tests should not be calculated as flaky tests by default. This widget should calculate cases between test status Fail <-> Pass. Or at least Skipped test including should be configurable.

**Expected behavior**
Skipped tests should be filtered out from flaky tests table.

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]: Current version:API Service: 5.10.0;Index Service: 5.10.0;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0;

**Comment by Kozovskaya** [comment]
Hello @qasamppa for your request. It sounds for me more like feature request as currently the widget works as intended. But it's a good point and I'll discuss it the team and will revert to you.

**Comment by Kozovskaya** [comment]
FYI
@qasamppa 
I've created a ticket in our Backlog to add the mentioned functionality!

**Comment by DzmitryHumianiuk** [comment]
@qasamppa will go into 23.3

**Comment by Kozovskaya** [comment]
Hello @qasamppa 
I'm pleased to let you know that the fix is already released!
https://github.com/reportportal/reportportal/releases/tag/v24.1
