### ISSUE TITLE
After upgrade to V 23.2 auth with token is not working

### ISSUE THREAD

**Issue by chahalprabh92** [reportportal/reportportal#2163]
**Describe the bug**
In my profile we get Access token 

we use that with pytest integration, Now after we migrated to V23.2
auth with this access token is not working

I have also tried with generating new token, still getting 401

**Expected behavior**
With Access token we should be able to get access 
...

**Screenshots**

` curl -X GET "http://10.66.102.145:8080/api/v1/iam/launch" -H  "accept: */*" -H  "Authorization: bearer QMjStwZ_ghSDZM4aBoVxEE0U3fU"                                                                                  
{"error":"invalid_token","error_description":"Invalid access token"}%                                                          (myenv) chahal@Prabhleens-MBP zscaler % 
(myenv) chahal@Prabhleens-MBP zscaler % curl -X GET "http://10.66.102.145:8080/api/v1/iam/launch" -H  "accept: */*" -H  "Authorization: bearer QMjStwZ_ghSDZM4aBoVxEE0U3fU" -v
Note: Unnecessary use of -X or --request, GET is already inferred.
* processing: http://10.66.102.145:8080/api/v1/iam/launch
*   Trying 10.66.102.145:8080...
* Connected to 10.66.102.145 (10.66.102.145) port 8080
> GET /api/v1/iam/launch HTTP/1.1
> Host: 10.66.102.145:8080
> User-Agent: curl/8.2.1
> accept: */*
> Authorization: bearer QMjStwZ_ghSDZM4aBoVxEE0U3fU
> 
< HTTP/1.1 401 Unauthorized
< Cache-Control: no-store
< Content-Type: application/json
< Date: Mon, 23 Oct 2023 21:23:33 GMT
< Pragma: no-cache
< Www-Authenticate: Bearer realm="oauth2-resource", error="invalid_token", error_description="Invalid access token"
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-Xss-Protection: 1; mode=block
< Content-Length: 68
< 
* Connection #0 to host 10.66.102.145 left intact
{"error":"invalid_token","error_description":"Invalid access token"}%    `
If applicable

**Versions:**

 - OS, Browser 
curl 8.2.1
 
 - Version of RP [find it under Login form, copy as is]
 - Current version:API Service: 5.10.0;Index Service: 5.10.0;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0;

**Comment by Pink-Bumblebee** [comment]
Please check https://reportportal.io/docs/reportportal-configuration/HowToGetAnAccessTokenInReportPortal/#2-authorization-with-users-api-key-for-agents and https://reportportal.io/docs/releases/Version23.2

**Comment by chahalprabh92** [comment]
@Pink-Bumblebee so I am using pytest 
and we use Access token and give it as uuid in pytest.ini
so should n't my old token continue to work as it is?

**Comment by chahalprabh92** [comment]
I tried generating the new API key. that one worked
thanks @Pink-Bumblebee

**Comment by DzmitryHumianiuk** [comment]
@chahalprabh92 the upgrade mechanism was actually developed to prevent to need to update all access tokens. Keeping them as a legacy keys in the system.

Thus, this is an abnormal behaviour. 
but i'm glad this is resolved for you.
