### ISSUE TITLE
X-Frame-Option is set as Deny causing the iframe of report portal 

### ISSUE THREAD

**Issue by py2206** [reportportal/reportportal#2167]
We had a requirement where we were showing the reportportal as iframe . it was working fine before upgrade to v23.1 .
Just wanted to know that can we mark X-Frame-option as allow in report portal server side or any other workaround.

**Comment by Pink-Bumblebee** [comment]
This option was turned off.
https://github.com/reportportal/service-ui/blob/develop/nginx.conf#L37

**Comment by py2206** [comment]
Do we have provision to remove the X-Frame-Option in service-ui?

**Comment by Pink-Bumblebee** [comment]
You can comment this option in nginx.conf file in your ui container and then restart container.
But you have to remember that you do it at your own risk

**Comment by Kozovskaya** [comment]
Hi @py2206,
I will close the issue as the the problem was clarified and a workaround proposed. If you still need clarifications or assistance - don't hesitate to reopen the issue or create a new one.
