### ISSUE TITLE
Need upgrade steps.

### ISSUE THREAD

**Issue by quldude** [reportportal/reportportal#2169]
Is there documentation on how to upgrade RP, eg, from 5.9 to 5.10?
I tried running these commands:
```
docker stop $(docker ps -a -q)
curl -LO https://raw.githubusercontent.com/reportportal/reportportal/master/docker-compose.yml
sudo docker-compose up -d
```
But this wiped out the database and started fresh. I then referred to the cheat [sheet](https://reportportal.io/docs/installation-steps/MaintainCommandsCheatSheet/) to backup and restore db.

**Comment by Pink-Bumblebee** [comment]
Please read this page : https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.23.2

**Comment by Pink-Bumblebee** [comment]
Information provided.
