### ISSUE TITLE
As a user I want to export or "print" dashboard data

### ISSUE THREAD

**Issue by hajdun** [reportportal/reportportal#217]
Our customer needs nice reports, he does not want to log in to report portal as some other test results are available from other test management tool or Jenkins.

Please
have a printable css formatting for dashboards (project name, widgets)>
"print" it to pdf >
 let me send it in email from report portal (have a recurrence setting like send it monthly or weekly, at a given time )

Alternative solutions
1) Minimum requirements: have a printable css -  right now it doesn't seem to print all pages (needs to be resized to 50% if I want to save  a full-page pdf )

2) Or have an export button on dashboard, which saves a pdf

**Comment by DzmitryHumianiuk** [comment]
in progress
