### ISSUE TITLE
Edit defects bulk update -> update comment is  getting appended

### ISSUE THREAD

**Issue by chahalprabh92** [reportportal/reportportal#2170]
**Describe the bug**
When we do bulk edit defects and put a new comment
it gets appended to old comment. 

**Expected behavior**
It should be new comment only

**Screenshots**
<img width="1115" alt="Screen Shot 2023-10-30 at 11 36 19 AM" src="https://github.com/reportportal/reportportal/assets/74168134/4255e2e1-a182-4952-b0dd-af6709310f9b">

**Payload**

`curl 'http://10.66.102.145:8080/api/v1/smca-regression/item/' \
  -X 'PUT' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTg3Nzg0MjIsInVzZXJfbmFtZSI6InByYWJoIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTklTVFJBVE9SIl0sImp0aSI6IlBnLVVwaTJFb1kxZGdock9Lczdfa0Iyd3dyWSIsImNsaWVudF9pZCI6InVpIiwic2NvcGUiOlsidWkiXX0.EA8li95rCSVrUnmaVxNF_VxYyK3p52n4TpeaU4nknoc' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: _ga=GA1.1.936482445.1678811909; _ga_Z22WZS0E4E=GS1.1.1698689577.17.1.1698692057.0.0.0' \
  -H 'Origin: http://10.66.102.145:8080' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://10.66.102.145:8080/ui/' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' \
  --data-raw '{"issues":[{"testItemId":58378,"issue":{"issueType":"ab001","comment":"Bad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58379,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58380,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58384,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58385,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58386,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58390,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58391,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58392,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58396,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58397,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58398,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58402,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58403,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58404,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58408,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58409,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58410,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58414,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58415,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58416,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58438,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58439,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58440,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58444,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58445,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58446,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58450,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58451,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58452,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58456,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58457,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58458,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58462,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58463,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58464,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58468,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58469,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58470,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58474,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58475,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}},{"testItemId":58476,"issue":{"issueType":"ab001","comment":"IDP seems incorrect, Landing on to 404 page\nsome idps are inactive, auth going to oktaidp initiated IDP\nBad Request. Groupd id is null\nGroup id is null. incorrect payload\n.\nnew comment\nnew comment2","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]}}]}' \
  --compressed \
  --insecure`

**Versions:**
 - OS, Browser Mac OS Monterey .. Chrome Version 116.0.5845.187 (Official Build) (arm64)
 - Version of RP [find it under Login form, copy as is]
 Current version:API Service: 5.10.0;Index Service: 5.10.0;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0;

**Comment by alena-babrova** [comment]
Hello @chahalprabh92,
When you add a comment to test items, please, select "be clear for all chosen items" option in the "Following results will be applied" section.
![image](https://github.com/reportportal/reportportal/assets/89584140/0e893bbc-416a-4acf-beaa-f939f9890dc1)

**Comment by chahalprabh92** [comment]
thanks @alena-babrova
