### ISSUE TITLE
Dashboard is shared option not showing in latest report portal latest version dashboards

### ISSUE THREAD

**Issue by shyamala97** [reportportal/reportportal#2171]
Previosul we are able to see the Dashboard is shared option in our Dashboards ,Now we are not able to see that options in latest version

**Comment by Pink-Bumblebee** [comment]
Hello! 
Probably this is related to the fact that we reduced the possibility to share widgets.
Thus it might be the case, that some of your widgets on the dash or even all of them are just were shared previously.
and after update the sharing mode is gone.

**Comment by Kozovskaya** [comment]
Hello @shyamala97! 
In the release 23.1 we removed the functionality of sharing dashboards, widgets and filters. Now all the dashboards, widgets and filters including actions with them are available to all the project members!
https://reportportal.io/docs/releases/Versionv23.1
