### ISSUE TITLE
Russian characters are not displayed in transmitted attributes (Не отображаются русские символы в передаваемых атрибутах)

### ISSUE THREAD

**Issue by Zenin-Dmitry** [reportportal/reportportal#2175]
We use integration with https://github.com/reportportal/agent-net-nunit. ReportPortal.json contains Russian characters
````
{
  "$schema": "https://raw.githubusercontent.com/reportportal/agent-net-vstest/master/ReportPortal.VSTest.TestLogger/ReportPortal.config.schema",
  "enabled": true,
  "server": {
    "url": "http://my_url:8080/api/v1",
    "project": "my_project",
    "authentication": {
      "uuid": "API_my_API"
    }
  },
  "launch": {
    "name": "my_name",
    "description": "this is description",
    "debugMode": false,
    "attributes": [
                    "OS:win10 (19045)",
                    "PC:DESKTOP",
                    "user:Фамилия Имя",
                    "runType:Manual"
    ]
  },
  "rootNamespaces": [ "ExampleUnitTests" ]
}
```
`
**Screenshots**
![errors](https://github.com/reportportal/reportportal/assets/114991037/371e0f37-bfac-4343-bd50-21b0371341a7)

**Comment by nvborisenko** [comment]
Not reproducible:
![image](https://github.com/reportportal/reportportal/assets/22616990/f37d1eae-e78e-40a3-8d49-47c313566ea1)

**Comment by Zenin-Dmitry** [comment]
I have the latest version installed, currently 5.10. Installed in docker, did not change any settings. What could be causing the encoding problem?

**Comment by MaryiaRymarchyk** [comment]
@nvborisenko do you have any ideas what may cause the issue?
@Zenin-Dmitry is the issue still valid?

**Comment by nvborisenko** [comment]
Just last guess the `ReportPortal.json` file was written as not UTF.

**Comment by Zenin-Dmitry** [comment]
@nvborisenko  Thank you very much, the problem was in this file.
The default file for manually running autotests in the repository is in UTF encoding, but for autotests the file is generated in GitLab by a script, and there the generation was in Windows-1251 encoding. We explicitly specified the UTF encoding of the ReportPortal.json file in the pipeline and everything worked!
Thanks again!

**Comment by nvborisenko** [comment]
You might be interested in how to override configuration properties via environment variables https://github.com/reportportal/commons-net/blob/develop/docs/Configuration.md#environment-variables, it is easier that generating config file.
