### ISSUE TITLE
How can I add attributes after launch started

### ISSUE THREAD

**Issue by yanisst** [reportportal/reportportal#2177]
I am able to add attributes via cmd - for example:

dotnet test --filter:"FullyQualifiedName~MyTests" --logger:ReportPortal;Launch.Name="My Launch name";Launch.Attributes=k1:v1,k2:v2

I would like to add more attributes via C# code after the launch is started (launch in progress) - Is it possible?

**Comment by yanisst** [comment]
OK Thank you for your quick response

**Comment by nvborisenko** [comment]
Does it work for you?

**Comment by yanisst** [comment]
The option to modify/add attributes before the launch is started is not good for me.
I would like to add attributes while the launch is in progress.
For my project it will be useful while running test/s to get some data from the DUT and set it as attributes in the Report portal launch.

**Comment by alexandre-marquis** [comment]
There's a example that worked for me here
https://github.com/reportportal/example-net-nunit/blob/master/src/Example/ReportPortalCustomization/Customization.cs

**Comment by nvborisenko** [comment]
It's kind of `dynamic launch attributes`. We already have a possibility to dynamically append test attributes directly from test. I think the following is more close to resolve the issue:
```csharp
ReportPortal.Shared.Context.Launch.Metadata.Attributes.Add("os", "win12");
```

Seems we can implement it using current approach as we use it for tests attributes. But attributes are visible on UI when **a launch finishes**. This is why I have no good approach to the request.

Probably @yanisst can reveal more about use case... what kind of dynamic data should be appended as launch attributes.. whether it can be fetched before launch run...

**Comment by yanisst** [comment]
This is not correct:
![image](https://github.com/reportportal/reportportal/assets/50665352/752cf3b0-db78-4eee-8015-a6f2ac5304bd)

I tried this but that does not work (attributes are not added):
ReportPortal.Shared.Context.Current.Metadata.Attributes.Add("my_key", "my_value");

My use case:
The DUT is an embedded system, in ClassInitialize I turn it ON and then send some commands - for example query for FW version, query for other data from various components of the DUT so this data can be collected after the launch is started.

**Comment by nvborisenko** [comment]
It is not implemented yet, I just proposed approach how it could be done.

**Comment by yanisst** [comment]
OK thank you for your suggestions.
So is there a plan for implementation?

**Comment by nvborisenko** [comment]
I don't think so. I can guide how to implement it.

**Comment by MaryiaRymarchyk** [comment]
@yanisst any updates from your side? may the ticket be closed?

**Comment by yanisst** [comment]
@MaryiaRymarchyk no update from my side. As I understand it my request can not be implemented.
