### ISSUE TITLE
Cucumber skipped steps marked as issues (java)

### ISSUE THREAD

**Issue by sbakharev** [reportportal/reportportal#218]
Using Cucumber Java agent 3.0.0-BETA-2.

When a scenario fails, the failed step is marked as issue to investigate and that's fine. But the steps following the failed one are marked as issues even though their status is SKIPPED. This is strange since the steps skipped in such way definitely do not represent any separate issues. This behavior occurs even with **rp.skipped.issue** set to **false**.

The expected behavior is either not to mark skipped steps as issues or at least not to do it when the abovementioned flag is explicitly disabled.

**Comment by andytrofimov** [comment]
@avarabyeu is there any news on this issue?

**Comment by avarabyeu** [comment]
@andytrofimov actually, it's expected behaviour. Will discuss with the team whether skipped tests should have issue.

**Comment by avarabyeu** [comment]
Fixed in 4.0
