### ISSUE TITLE
Jira Integration Able to Link Jira Cloud Issues but Unable to Create from RP

### ISSUE THREAD

**Issue by itz4blitz** [reportportal/reportportal#2180]
**Describe the bug**
We attempt to create an issue from RP and it fails with a 500 error.

**Expected behavior**
 The issue should be created with appropriate attachments

**Screenshots**
![image](https://github.com/reportportal/reportportal/assets/60281870/38abec9a-0fba-4594-bbc1-71a219a7ac29)

**Additional Notes**
We have removed and manually readded the integration. I've downloaded from [here](https://github.com/reportportal/plugin-bts-jira-cloud/packages) and reinstalled but the error still persists.

**Versions:**
Happens for any user in our RP
```Current version:API Service: 5.9.2;Index Service: 5.8.0;Jobs Service: 5.8.2;Authorization Service: 5.8.2;Service UI: 5.9.0;```

**Comment by itz4blitz** [comment]
Also, here's the "response" we see:

```{"errorCode":5000,"message":"Unclassified error [null]"}```

**Comment by Pink-Bumblebee** [comment]
@itz4blitz Could you please check plugin for this message: https://github.com/reportportal/plugin-bts-jira-cloud/issues/36#issuecomment-1744679220 ?

**Comment by itz4blitz** [comment]
> @itz4blitz Could you please check plugin from this message: [reportportal/plugin-bts-jira-cloud#36 (comment)](https://github.com/reportportal/plugin-bts-jira-cloud/issues/36#issuecomment-1744679220) ?

Thanks for the response and apologies on the delay with responding, I was away over the US holidays.

![image](https://github.com/reportportal/reportportal/assets/60281870/bc45b52f-1284-4619-9523-843ca88602aa)

I deleted my old integration and added the one you linked, however it still fails.

![image](https://github.com/reportportal/reportportal/assets/60281870/5a7e30c2-9bbf-4035-a395-81e842a37511)

**Comment by iproff2011** [comment]
Hello. I also confirm that I'm receiving error 500 with {"errorCode":5000,"message":"Unclassified error [null]"}
when trying to post a ticket from Report Portal.
And this feature would be very useful for our project.

**Comment by pbortnik** [comment]
Hi @itz4blitz, @iproff2011, do you have possibility to share full serivce-api log after facing the issue?

**Comment by iproff2011** [comment]
but to be clear, @pbortnik, I see the same issue on reportportal.epam.com when trying to create issue:
Here are logs:

Request URL:
https://reportportal.epam.com/api/v1/integration/ihar_pryshchepau_personal/464/postTicket
Request Method:
PUT
Status Code:
500 Internal Server Error
Remote Address:
35.156.45.8:443
Referrer Policy:
strict-origin-when-cross-origin

Cache-Control:
no-cache, no-store, max-age=0, must-revalidate
Content-Type:
application/json
Date:
Tue, 30 Jan 2024 13:41:51 GMT
Expires:
0
Pragma:
no-cache
Strict-Transport-Security:
max-age=63072000; includeSubDomains
X-Content-Type-Options:
nosniff
X-Frame-Options:
DENY
X-Xss-Protection:
1; mode=block

:authority:
reportportal.epam.com
:method:
PUT
:path:
/api/v1/integration/ihar_pryshchepau_personal/464/postTicket
:scheme:
https
Accept:
application/json, text/plain, */*
Accept-Encoding:
gzip, deflate, br
Accept-Language:
en-US,en;q=0.9,ru;q=0.8
Authorization:
bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY2NjUxNTMsInVzZXJfbmFtZSI6ImloYXJfcHJ5c2hjaGVwYXUiLCJqdGkiOiJRbzFaZG1IMWlLZUxhbmhfb0l0QzdWNXVhSmciLCJjbGllbnRfaWQiOiJ1aSIsInNjb3BlIjpbInVpIl19.NFcfiJsxMMJU1XO-xTX7EiF5cs9Bvi-NBY_tkHvxLU0
Content-Length:
502
Content-Type:
application/json
Cookie:
FPID=FPID1.2.7%2Bsr9DXFjf%2FQ%2FVtn8G61Ad2tmeYT2PrAgFiNx%2B6AADw%3D.1633939648; AMCV_98CF678254E93B1B0A4C98A5%40AdobeOrg=-2121179033%7CMCMID%7C48687784866820333810687647005577619534%7CMCAAMLH-1647010945%7C6%7CMCAAMB-1647010945%7C6G1ynYcLPuiQxYZrsz_pkqfLG9yMXBpb2zX5dvJdYQJzPXImdj0y%7CMCOPTOUT-1646413345s%7CNONE%7CvVersion%7C5.3.0; _hjSessionUser_1638007=eyJpZCI6ImQ1OTg3M2M0LTM1M2UtNWRiZS05MTRiLWFmM2RjYzk0MDUyZCIsImNyZWF0ZWQiOjE2NTMxMzcxOTc3ODMsImV4aXN0aW5nIjp0cnVlfQ==; _ga_98C5ZBQ1D0=GS1.1.1680122007.1.1.1680122022.45.0.0; _ga_4BQNRGQ7DK=GS1.1.1680122007.1.1.1680122022.0.0.0; _ga_FDP6S5DCK4=GS1.1.1680296272.13.1.1680296316.0.0.0; _hjSessionUser_3447857=eyJpZCI6IjY0OGYwYmUyLTMxYzUtNWM5OC1hNWUzLWFhNDZhNzBiOTgxZCIsImNyZWF0ZWQiOjE2ODE3MjQ1MzQzODgsImV4aXN0aW5nIjp0cnVlfQ==; _ga_HD29NCJB84=GS1.1.1681766008.2.0.1681766008.0.0.0; amp_be9149=vod6uwzYIRlsjWMFJ-W7Vd.MDFmNmQ4YTgyMWQwYTJiMDk3ODU0NGFjNzMyZDA0MDAyY2I5Y2NmOTEzOTMwNDU5YzQ4MDU4OGIyMTEzMWVkNw==..1gv3kucp5.1gv3kud8v.1o.d.25; amp_cc7cb0=EizDZq5WnxLC_caUDsEl5V.MDFmNmQ4YTgyMWQwYTJiMDk3ODU0NGFjNzMyZDA0MDAyY2I5Y2NmOTEzOTMwNDU5YzQ4MDU4OGIyMTEzMWVkNw==..1h140oob4.1h140opdv.10.7.17; _ga_H1FPGFH7H6=GS1.1.1684958552.2.0.1684958552.0.0.0; amp_f6e48c=h64klb5gKBmahc5o_WuxkA.MDFmNmQ4YTgyMWQwYTJiMDk3ODU0NGFjNzMyZDA0MDAyY2I5Y2NmOTEzOTMwNDU5YzQ4MDU4OGIyMTEzMWVkNw==..1h266o131.1h266olc2.cm.d.d3; _ga_GSN102FN3V=GS1.1.1685983068.1.1.1685983100.0.0.0; amplitude_id_6a846d331c4aa7672fd634cdc13b0adcepam.com=eyJkZXZpY2VJZCI6IjhjZWJhZTViLWNjZTEtNDgxYi1iYjA2LTk3ODVmNDdiNzQxZlIiLCJ1c2VySWQiOiI4NzYwMDAwMDAwMDAwMDE2ODA2Iiwib3B0T3V0IjpmYWxzZSwic2Vzc2lvbklkIjoxNjg2MDU5NTA1MjY4LCJsYXN0RXZlbnRUaW1lIjoxNjg2MDU5NTA1MjY4LCJldmVudElkIjowLCJpZGVudGlmeUlkIjowLCJzZXF1ZW5jZU51bWJlciI6MH0=; amp_b03d66=Hk_JHZboJPhfcNaLLkIobI...1h28l13t8.1h28l13t8.0.0.0; _ga_G52F7W3W0X=GS1.1.1686065984.1.1.1686066019.0.0.0; _ga_5X6CTCZW7V=GS1.1.1686221537.2.0.1686221537.0.0.0; _ga_GD6GJ1R3D3=GS1.1.1686580827.2.1.1686580861.0.0.0; _ga_YK1S0HFX1L=GS1.1.1686580827.2.1.1686580861.0.0.0; _ga_4KH6066E1W=GS1.1.1686580827.2.0.1686580861.0.0.0; amp_aae40f=0M6tVxRMsl1FW1u8Vkd1lV.OTIyNDE=..1h2o0r99j.1h2o12ltd.32.12.44; _mkto_trk=id:030-GZP-996&token:_mch-epam.com-1687780344127-91854; _fbp=fb.1.1687780344179.401119596; _hjSessionUser_3178737=eyJpZCI6Ijg3Njg4OWFmLTFmMGMtNTEzMC1hN2M4LWRhOWM5MmVlOTZmZiIsImNyZWF0ZWQiOjE2ODYwNjM5MzQwOTUsImV4aXN0aW5nIjp0cnVlfQ==; amplitude_id_2292894aec3430f33158866b991b38efepam.com=eyJkZXZpY2VJZCI6ImYyMzE1YmU4LTUyODYtNDU4MC1iZTc0LWFjMzdlYWYyZTc3N1IiLCJ1c2VySWQiOiIwMWY2ZDhhODIxZDBhMmIwOTc4NTQ0YWM3MzJkMDQwMDJjYjljY2Y5MTM5MzA0NTljNDgwNTg4YjIxMTMxZWQ3Iiwib3B0T3V0IjpmYWxzZSwic2Vzc2lvbklkIjoxNjg4MzI4MDEyNDAzLCJsYXN0RXZlbnRUaW1lIjoxNjg4MzI5MzQ3OTI0LCJldmVudElkIjo0NSwiaWRlbnRpZnlJZCI6Niwic2VxdWVuY2VOdW1iZXIiOjUxfQ==; _ga_GC65FXEVYS=GS1.1.1688394450.4.1.1688394475.0.0.0; _ga_EX7JVZ7E0Q=GS1.1.1688395046.1.1.1688395183.0.0.0; amp_35f65f=TaBBMBwei1sDanO2iGudQG.MDFmNmQ4YTgyMWQwYTJiMDk3ODU0NGFjNzMyZDA0MDAyY2I5Y2NmOTEzOTMwNDU5YzQ4MDU4OGIyMTEzMWVkNw==..1h61u51j6.1h61u52bl.3q.0.3q; _ga_YEZPFNFWCW=GS1.2.1690321740.13.1.1690322636.0.0.0; amp_4ee2eb=g5Ob_IdhDm9GT9Mf0gT-ti...1h67h9673.1h67h9677.o.p.1h; _ga_QYNT67CTC5=GS1.2.1692378007.1.1.1692380921.0.0.0; _ga_93QK6GV0YH=GS1.1.1692377707.70.1.1692381118.0.0.0; _ga_QKL78T20SX=GS1.1.1692381107.107.1.1692381118.0.0.0; amp_b11780=6lR_YM6asSG2lIamzv4r_v.MDFGNkQ4QTgyMUQwQTJCMDk3ODU0NEFDNzMyRDA0MDAyQ0I5Q0NGOTEzOTMwNDU5QzQ4MDU4OEIyMTEzMUVENw==..1h8tiklul.1h8tikm2u.e.0.e; AMP_MKTG_44bfb4cc30=JTdCJTdE; _ga_QKZGZ7BYFH=GS1.1.1695393509.1.1.1695393981.0.0.0; _uetvid=0dbfb720d90411eca78ee9f138218bb0; _ga_EYGYLWSTX2=GS1.1.1696193728.2.1.1696193745.43.0.0; _ga_R1LGR2KX6X=GS1.1.1696193330.1.1.1696195655.0.0.0; _ga_D8FQ3B2PT0=GS1.1.1698686034.1.1.1698686072.0.0.0; amplitude_id_97364965512571fbbed0820e6055bee7epam.com=eyJkZXZpY2VJZCI6ImVjOTgzOWE1LWJjZDMtNDEzZS1iYTAxLTY5MTk4Njk3NzA3M1IiLCJ1c2VySWQiOm51bGwsIm9wdE91dCI6ZmFsc2UsInNlc3Npb25JZCI6MTY5ODc0MzM1ODI3MiwibGFzdEV2ZW50VGltZSI6MTY5ODc0MzM1ODQ1MCwiZXZlbnRJZCI6MiwiaWRlbnRpZnlJZCI6MCwic2VxdWVuY2VOdW1iZXIiOjJ9; _ga_DDNBLYBLTY=GS1.2.1698921955.23.1.1698922024.0.0.0; amp_aa3ab3=k2wYennk0w9TdAu5pXotgl.MDFGNkQ4QTgyMUQwQTJCMDk3ODU0NEFDNzMyRDA0MDAyQ0I5Q0NGOTEzOTMwNDU5QzQ4MDU4OEIyMTEzMUVENw==..1hels0t81.1hels2bif.2p.0.2p; amp_924ef6=9Tx9kYHBMNp1aJuRHY8aYG.MDFmNmQ4YTgyMWQwYTJiMDk3ODU0NGFjNzMyZDA0MDAyY2I5Y2NmOTEzOTMwNDU5YzQ4MDU4OGIyMTEzMWVkNw==..1hi65itun.1hi65likk.c6.c.ci; amp_3cc2dc=CFjMlEIPcaLfAYSewfgfL9...1hjpmj9l2.1hjpmjae2.a.0.a; amp_3b0583=p9gXKA_Jw_WfWoBOGaYyTp.Nzg3NDM=..1hjpmcfbd.1hjpnsqvk.7.3.a; amp_234e05=CShO7k_YqUgjbcLx73x0TV.ODk0ZmQwZjg0ZjYzM2QyNjNiZWEzYTU1ZDI0MTM0NjdhMWY0OGFjZTU4MjA5ZjEzODkwMGZhMGFiZDQxN2I2NA==..1hjsl6d7i.1hjsl6d7i.0.0.0; _ga_GRFFMC0FYX=GS1.1.1704990029.1.0.1704990029.0.0.0; amp_f62b16=c1yAbyrHnpcWydZyeFqlud.MDFmNmQ4YTgyMWQwYTJiMDk3ODU0NGFjNzMyZDA0MDAyY2I5Y2NmOTEzOTMwNDU5YzQ4MDU4OGIyMTEzMWVkNw==..1hjufrn2t.1hjugl6d6.4m.1.4n; _ga_PZLN70KVX8=GS1.1.1706000309.27.1.1706000325.0.0.0; AMP_44bfb4cc30=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJiZmNjZWIxMi0xY2Q3LTRhYWMtOTVhMy00MjBiZGRjYWNhNWYlMjIlMkMlMjJ1c2VySWQlMjIlM0ElMjIwMWY2ZDhhODIxZDBhMmIwOTc4NTQ0YWM3MzJkMDQwMDJjYjljY2Y5MTM5MzA0NTljNDgwNTg4YjIxMTMxZWQ3JTIyJTJDJTIyc2Vzc2lvbklkJTIyJTNBMTcwNjAwMDMwOTAzNCUyQyUyMm9wdE91dCUyMiUzQWZhbHNlJTJDJTIybGFzdEV2ZW50VGltZSUyMiUzQTE3MDYwMDAzMjU3OTElMkMlMjJsYXN0RXZlbnRJZCUyMiUzQTU0JTdE; amp_1927e7=YCdX0WRM4ep1mlOsVWQg6u.MDFGNkQ4QTgyMUQwQTJCMDk3ODU0NEFDNzMyRDA0MDAyQ0I5Q0NGOTEzOTMwNDU5QzQ4MDU4OEIyMTEzMUVENw==..1hku5hc1l.1hku5hg1g.18.0.18; _ga_R362KM4BZ0=GS1.1.1706114406.67.1.1706114654.0.0.0; _ga_8JF66MBNHE=GS1.1.1706116563.2.1.1706116568.55.0.2022789731; _clck=1ub77m9%7C2%7Cfio%7C0%7C1272; _hjSessionUser_3802578=eyJpZCI6IjY2MzhlZTA0LTVlNDAtNTRkNS05MGMwLTY2ODc3NjAwOTk4ZiIsImNyZWF0ZWQiOjE3MDYwMDAzMzU3NDcsImV4aXN0aW5nIjp0cnVlfQ==; _ga_BLQDLWJP23=GS1.1.1706462122.19.1.1706462270.0.0.0; _gid=GA1.2.1244568607.1706608167; amp_3ed3e6=Z8UFlzPqRMVDZH3utv-9dE.ZmNmMTJiMjg2ZTU0Njk4ZGJiOGRmMjg5MDIyNDRmMThkNmZhNjFjZmRhNWU4N2E4NjYzZjc2OTliMTc1OGFiYQ==..1hlcsclu9.1hlcscluu.1j.q.2d; _ga_ZMJYZTWTVJ=GS1.1.1706608167.56.1.1706608190.0.0.0; AMP_MKTG_9f4964f90a=JTdCJTdE; _ga=GA1.1.8760000000000016806; AMP_9f4964f90a=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJlMTlhNWJkOC0xNDExLTQyMGEtYTFlMC04NmJiNjg2NmQ5NTQlMjIlMkMlMjJ1c2VySWQlMjIlM0ElMjIyMTM0YjA4ODZmYmVmYTY0MGQzNzVhYzhhN2U4Nzk2N2ViZmUzMWFiNjllY2M4ZDQ0ZWUyOTRjMmY5NWU5ZWNlJTIyJTJDJTIyc2Vzc2lvbklkJTIyJTNBMTcwNjYwODE5Mzk4NSUyQyUyMm9wdE91dCUyMiUzQWZhbHNlJTJDJTIybGFzdEV2ZW50VGltZSUyMiUzQTE3MDY2MDgyMTM5OTUlMkMlMjJsYXN0RXZlbnRJZCUyMiUzQTEzJTdE; _ga_BRWYXPQZ3C=GS1.1.1706608194.13.1.1706608214.0.0.0; _ga_W1T3XZ3Z92=GS1.1.1706611681.136.0.1706611681.0.0.0; _ga_WBGDS7S6W6=GS1.1.1706611680.138.1.1706611946.60.0.0; _ga_7BL0YYR4HF=GS1.1.1706611683.158.1.1706611946.0.0.0; JSESSIONID=3F5C271EDB4B0216974CC2DDA9949345; _ga_Z22WZS0E4E=GS1.1.1706621943.13.1.1706622111.0.0.0
Origin:
https://reportportal.epam.com
Referer:
https://reportportal.epam.com/ui/
Sec-Ch-Ua:
"Not_A Brand";v="8", "Chromium";v="120", "Microsoft Edge";v="120"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"Windows"
Sec-Fetch-Dest:
empty
Sec-Fetch-Mode:
cors
Sec-Fetch-Site:
same-origin
User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0

{"projectId":22435,"entity":{"includeComments":true,"includeData":true,"includeLogs":true,"logQuantity":50,"item":3802637050,"fields":[{"id":"summary","value":["RP_Issue_1"],"required":true,"fieldName":"Summary","fieldType":"string","definedValues":[]}],"backLinks":{"3802637050":"https://reportportal.epam.com/ui/#ihar_pryshchepau_personal/launches/all/6820147/3802637008/3802637041/3802637050/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.issueType%3Dpb001"}}}

Response:
{"errorCode":5000,"message":"Unclassified error [null]"}

Same I have  on my project RP.

**Comment by MaryiaRymarchyk** [comment]
@iproff2011  have you tried to post issue with mandatory fields only ? Please uncheck all check boxes (logs, attachments) and try to post - does it work?

**Comment by MaryiaRymarchyk** [comment]
As we haven't received a reply from you, we'll close the issue for now.
In case you still have the issue - just get in touch.

**Comment by D951516** [comment]
Hi, I'm encountering the same issue with the Azure DevOps integration in Report Portal. While we are able to link manually created bugs from Azure DevOps into Report Portal, we are unable to create or post a bug from Report Portal into Azure DevOps.

I have verified that all required values are being passed correctly.
Could someone please advise on this?

{errorCode: 5000, message: "Unclassified error [No value present]"}
errorCode
: 
5000
message
: 
"Unclassified error [No value present]"

@MaryiaRymarchyk
