### ISSUE TITLE
Test Items Wrongly Marked as `FAILED` (Occasionally) While Asserting for Exception in Nested Step's Test Case

### ISSUE THREAD

**Issue by adamiBs** [reportportal/reportportal#2184]
**Describe the bug**
While using `pytest`, along with the `reportportal` `pytest` client.
Specifically under higher-than-usual loads (500+ RPS), we experience the following behavior:
Consider the following example test snippet:
```python
def test_step_issue():
  with step("outer step that will consider itself as passed."):
    with pytest.raises(Exception):
      with step("inner step that doesn't 'know' that Pytest is expecting an exception above it."):
        raise Exception("inner step will think it has thrown an unexpected exception.")
```

This will lead to the following outcome when Report Portal server load is low and requests are processed 'fast':
![image](https://github.com/reportportal/reportportal/assets/22242862/0f3f95c0-91da-4f95-8cf2-a658ee043352)

In case we are experiencing peak loads on the Report Portal web server, the order of requests might be reported in an un-orderly fashion leading to:
![image](https://github.com/reportportal/reportportal/assets/22242862/1e75666b-8d0e-43c8-92cb-2c926f7542e1)

This un-expectedly leads to the test item being marked as 'FAILED' instead of 'PASSED'.

**Expected behavior**
We expect for the parent test's status to persist and avoid the change of it from `PASSED` to `FAILED`.

**Screenshots/Logs**
During investigation of this, it seems like the difference between the states relate to test result message handling order, this is according to the SQL query logs we've witnessed on `public.test_item_results`:
#### Test Item Marked as `PASSED`
1. Outer step `IN_PROGRESS`
2. Inner step `IN_PROGRESS`
3. Inner step `FAILED`
4. Outer step `PASSED`

#### Test Item Marked as `FAILED`
1. Outer step `IN_PROGRESS`
2. Inner step `IN_PROGRESS`
3. Outer step `PASSED`
4. Inner step `FAILED`
5. Outer step `FAILED`

**Versions:**
 - OS, Browser: Irrelevant
 - Version of RP: `v23.1`
 - Pytest Plugins installed:
   - repeat-0.9.3
   - reportportal-5.3.0

**Comment by Kozovskaya** [comment]
@IvanKustau could you please have a look?

**Comment by adamiBs** [comment]
Any chance of looking at this?

**Comment by IvanKustau** [comment]
Hi @adamiBs . We have a task: [EPMRPP-87187](https://jiraeu.epam.com/browse/EPMRPP-87187) related to your problem that should be featured in next release

**Comment by adamiBs** [comment]
Great thanks.
When is the next release planned?

**Comment by Kozovskaya** [comment]
@adamiBs Next release is planned for the end of this year!

**Comment by adamiBs** [comment]
Hi team!
I've found the intended Hotfix: https://github.com/reportportal/service-api/pull/1859 and attempted to resolve the issues by hot fixing our current version.
It seems as if the issue is still reproduced with the Hotfix version.
Could there be a different `service-api` codepath that might also be responsible for updating the test item status?

**Comment by Kozovskaya** [comment]
Hello @adamiBs 
I'm pleased to let you know that the fix is already released!
https://github.com/reportportal/reportportal/releases/tag/v24.1
