### ISSUE TITLE
Logs are not getting shown on Report Portal properly

### ISSUE THREAD

**Issue by snehabhandge** [reportportal/reportportal#2185]
**Describe the bug**
All the different types of log messages are getting shown on the portal only when DEBUG log type is selected. The reference code is below.

```
import { Logger } from "log4js";
logger = Logger('Testing logs')
getLogs();

getLogs()
{
logger.trace(`Checking TRACE logs to output.json`);
logger.debug(`Checking DEBUG logs to output.json`);
logger.info(`Checking INFO logs to output.json`);
logger.warn(`Checking WARN logs to output.json`);
logger.error(`Checking ERROR logs to output.json`);
logger.fatal(`Checking FATAL logs to output.json`);
}
```

**Expected behavior**
Whatever log type is selected on the portal, logs should be shown depending on the standard ranking of the log levels.

**For ex.**: 
If **INFO** log type is selected on the portal, then all the logs reported for INFO < WARN < ERROR < FATAL  should be shown.
If **DEBUG** log type is selected on the portal, then all the logs reported for DEBUG < INFO < WARN < ERROR < FATAL should be shown.

**Screenshots**

1. ![image](https://github.com/reportportal/reportportal/assets/20770459/d964eff9-faf6-4190-ac07-2d0d87aee663)

2. ![image](https://github.com/reportportal/reportportal/assets/20770459/a1482b2e-f56f-4939-ab3d-33468395baf2)

**Versions:**
 - OS: Windows, Browser: Chrome
 - Version of RP: API Service: 5.10.1;Index Service: 5.10.0;Jobs Service: 5.10.0;EPAM Authorization Service: 5.10.0;Service UI: 5.10.0;
 - "log4js": "6.9.1"

**Comment by alena-babrova** [comment]
Hello @snehabhandge,

Looks like the issue is on the calling side - you need to check how do you post logs to ReportPortal.
We can see on the screenshot that ReportPortal saved logs with "Info" and "Debug" types, no matter what text they have inside.
So the question is how do you post these logs to ReportPortal, what client do you use and how is it configured?

**Comment by snehabhandge** [comment]
Hi @alena-babrova 
[RP_logs_issue.txt](https://github.com/reportportal/reportportal/files/13488281/RP_logs_issue.txt)
Plz refer attached file for the API responses.

**Comment by alena-babrova** [comment]
Dear @snehabhandge,

As I mentioned above, you are posting logs to ReportPortal with only 2 types of levels (Info and Debug). You can see it from the file you provided as well:
![image](https://github.com/reportportal/reportportal/assets/89584140/605f67d9-cef2-441e-af16-1546732637f5)

So, the question is how do you report your logs to ReportPortal? Which library you use and how is it configured?
