### ISSUE TITLE
Opening tests from combined launches do not redirect to the correct launch

### ISSUE THREAD

**Issue by CosminGramada** [reportportal/reportportal#2187]
**Describe the bug**
We have split our tests based on the most important areas of the product and when they got too large, we split them further to be able to have a lower run time. 

This being said, our Gitlab pipeline looks like this:
test from ProductAreaOne are assigned to 3 jobs named `ProductAreaOne-Job1`, `ProductAreaOne-Job2` and `ProductAreaOne-Job3`

And in the ReportPortal config the `launch` property looks like this:
```
'launch': ProductAreaOne, // -Job1 -Job2 and -Job3 are removed so that all tests are grouped together in ReportPOrtal
```

However in the Flaky tests widget only some tests can be opened (if I figured it out correctly, only the ones from the latest launch) and for the the rest I'm getting `No results found`

**Expected behavior**
Tests can be opened successfully from the widgets.

**Versions:**
 - OS, Browser: All
 - Version of RP: Current version:API Service: 5.7.2;Jobs Service: 5.7.2;Authorization Service: 5.7.0;Service UI: 5.7.2;

**Comment by MaryiaRymarchyk** [comment]
Hi @CosminGramada 
it is known issue, we've discussed it in #1711 (if the test changes his parent/ path - link from some widgets will be broken)
We have registered ticket in our backlog but there are many tickets with higher prio.
So, I hope you don't mind, i close current ticket as duplicate. All updates will be provided in #1711.
