### ISSUE TITLE
Only text of message displays in UI but attachment doesn't

### ISSUE THREAD

**Issue by guoguojenna** [reportportal/reportportal#2190]
Hi, when I add attachments to message, only the message text is displayed, but attachment isn't. . Am I missing sth?

![Screenshot from 2023-12-08 14-26-54](https://github.com/reportportal/reportportal/assets/28432976/9bc13a08-a811-496b-b62f-54c6e81f2eab)

The post response is 201: created.

![Screenshot from 2023-12-08 14-20-57](https://github.com/reportportal/reportportal/assets/28432976/52a96f7e-fd24-4d3f-9008-07ad33c2560c)

**Comment by MaryiaRymarchyk** [comment]
UPD: We will create ticket in our backlog: to add possibility to Upload the file via swager (screen from your example).

**Comment by MaryiaRymarchyk** [comment]
@guoguojenna  have you checked this guide ? https://github.com/reportportal/client-Python#send-attachment-screenshots
https://reportportal.io/docs/dev-guides/AttachmentsGuide/#how-to-log-attachments-screenshots-on-python-agents

**Comment by guoguojenna** [comment]
> @guoguojenna have you checked this guide ? https://github.com/reportportal/client-Python#send-attachment-screenshots https://reportportal.io/docs/dev-guides/AttachmentsGuide/#how-to-log-attachments-screenshots-on-python-agents

Thank you for the info.
