### ISSUE TITLE
total numbers mismatch with passed and failed after rerun of the same launch

### ISSUE THREAD

**Issue by umitsethi** [reportportal/reportportal#2197]
I am using pytest. I ran 3 tests with a new launch (dry-run-1) which created new launch with 0 passed and 3 failed.
Then I used api: /v1/{projectName}/launch and used uuid of previous launch

{
  "mode": "DEFAULT",
  "name": "dry-run-1",
  "rerun": true,
  "rerunOf": "22b7e839-8102-4752-aa47-ff2685814e7a",
  "startTime": "2023-12-20T23:57:02.686Z"
}

I ran the 3 tests again and 1 passed and 2 failed. I can see the passed and failed have the numbers from the latest run results but the total number is accumulating previous 3 tests as well and showing total numbers as 6 as you can see in the screenshot. Is that expected?

How can we make sure that total number is the sum of passed and failed even after rerun?

![issue-2](https://github.com/reportportal/reportportal/assets/1943806/192878ad-d32d-472a-932a-529afc3aa188)

**Comment by alena-babrova** [comment]
Hello @umitsethi,

I have tried to reproduce it using our API and everything works OK for me.
Do you always experience it? Maybe you can provide detailed requests (the first launch run and the rerun) when it is reproduced on your side?

**Comment by alena-babrova** [comment]
Dear @umitsethi,

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to reopen the ticket with details.
