### ISSUE TITLE
Screenshots are not getting rendered/displayed after we migrated from v23.1 to v23.2

### ISSUE THREAD

**Issue by scandula123** [reportportal/reportportal#2198]
Screenshots are not getting rendered/displayed after we migrated from v23.1 to v23.2
...

Screenshots should be displayed as it used to be earlier
...

**Screenshots**
Image not rendered/displayed in v23.2
![image](https://github.com/reportportal/reportportal/assets/98139460/ef706457-a297-405c-a3cf-202bfa76b05f)

Reverting back to v23.1, Image is displayed
![image](https://github.com/reportportal/reportportal/assets/98139460/74c6627c-8bff-4e3a-bad8-bdb715bcb4b7)

**Versions:**
 - Viewing RP in Chrome Browser(Version 120.0.6099.130) on Windows 10
- **v23.2 version where screenshots are not displayed** API Service: 5.10.1;Index Service: 5.10.0;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0;
 - **v23.1 version where screenshots are displayed** API Service: 5.8.0;Index Service: 5.8.0;Jobs Service: 5.8.0;Authorization Service: 5.8.0;Service UI: 5.8.0;

**Comment by Pink-Bumblebee** [comment]
Hello @scandula123 ,
Before we will check your issue, we need to check some things. Could you please inform us: 
1. What was your storage in version 23.1 and what is your storage in 23.2? Haven't you changed (for example) MinIO to S3?
2. Haven't you checked 23.2 with another browser?
3. Have you tried to make launches with screenshots in 23.2? And if yes - was images (screenshots) visible?

Thank you.

**Comment by scandula123** [comment]
> Hello @scandula123 , Before we will check your issue, we need to check some things. Could you please inform us:
> 
> 1. What was your storage in version 23.1 and what is your storage in 23.2? Haven't you changed (for example) MinIO to S3?
It was minio in both those version, we haven't moved to S3, and we use the docker-compose.yml exactly as uploaded in github
> 2. Haven't you checked 23.2 with another browser?
Checked with latest edge browser and chrome browser and images are not displayed there
> 3. Have you tried to make launches with screenshots in 23.2? And if yes - was images (screenshots) visible?
New launches with v23.2, we are able to see images
> 
> Thank you.

So, conclusion is old launch images are not getting displayed in v23.2

Thanks

**Comment by scandula123** [comment]
Hello @Pink-Bumblebee , Any updates on this? Thanks for looking into this.

**Comment by scandula123** [comment]
No I haven't connected to minio storage.

Here are the 2 versions we are using, as said earlier, there are no changes when compared to original version of github, except for port 8085
[docker-compose_v23.1.1.txt](https://github.com/reportportal/reportportal/files/13864055/docker-compose_v23.1.1.txt)
[docker-compose_v23.2.txt](https://github.com/reportportal/reportportal/files/13864056/docker-compose_v23.2.txt)
