### ISSUE TITLE
Unable to search by launch number

### ISSUE THREAD

**Issue by admizh** [reportportal/reportportal#22]
Some times we need switch to specific execution/launch but currently no any ability to perform search by execution number

![2016-12-05_1-13-49](https://cloud.githubusercontent.com/assets/6014483/20869317/3fd42824-ba89-11e6-9123-e2d325faa458.png)

**Comment by DzmitryHumianiuk** [comment]
@admizh it was never planned and not even considered.

Will put it as a long-term enhancement.
Once, on a wonderful day.

**Comment by DzmitryHumianiuk** [comment]
do via API, just add `filter.eq.number=10`

**Comment by evjlobanova** [comment]
@admizh a filter by a launch number will be added in 4.0
