### ISSUE TITLE
Repoportal UI Login issue

### ISSUE THREAD

**Issue by hailez** [reportportal/reportportal#2201]
We are unable to login to the UI page of Repoportal using the default admin login details, even though the login page says successfully logged in it's stuck on the same page.

On Further analysis using developer tools following error message is received 
Full authentication is required to access this resource, I have attached a screenshot for reference.

<img width="1728" alt="Screenshot 2023-12-27 at 10 45 24 AM" src="https://github.com/reportportal/reportportal/assets/46279058/728b227c-490a-404f-8d9f-8a0ccd659cac">

The application is deployed on Docker, and I have accessed it from Safari and Chrome Browser, both showing the same issue.

**Comment by Pink-Bumblebee** [comment]
@hailez , are Dockers statuses = "healthy"?
Please also try to login in Incognito mode.

BTW, have you changed initial password during 1st login? https://reportportal.io/docs/releases/Versionv23.1/#2-technical-improvements

**Comment by hailez** [comment]
@Pink-Bumblebee Yeah containers are in healthy status, I haven't logged in yet to change password.

**Comment by Pink-Bumblebee** [comment]
@hailez , this is strange behavior. Actually, I'm not familiar with Mac platform.
Could you please try to use Incognito mode of Chrome?

**Comment by hailez** [comment]
@Pink-Bumblebee Same with Incognito mode also

**Comment by Pink-Bumblebee** [comment]
@hailez, have you tried to use http:// instead of https://
Maybe it is certificate issue. Please take a look into this article : https://reportportal.io/docs/installation-steps/SetupTSLSSLInTraefik2.0.x

**Comment by hailez** [comment]
This issue has been sorted out , seems to be issue with SSL configuration.
