### ISSUE TITLE
Widget to Show how many are getting fixed Suite Wise from Flaky

### ISSUE THREAD

**Issue by paresh-celigo** [reportportal/reportportal#2203]
Hi Team, I am trying to achieve stability in my pipeline, and I have added widgets for most failed and most Flaky test cases , and I Need the widget for getting data of how many are getting fixed Suite Wise from Flaky, Can you please suggest me How can i achieve this...?

**Comment by Kozovskaya** [comment]
Hello @paresh-celigo,
could you please provide more details on what you are trying to get? 
I do understand that you have two widgets - one for flaky tests, the other one - for most Failed test cases. 
Do you need a widget with info how many of these flaky/failed test have been fixed?

**Comment by paresh-celigo** [comment]
Hi @Kozovskaya , Yes I need a widget with info how many of these flaky/failed test have been fixed

**Comment by Kozovskaya** [comment]
@paresh-celigo 
Well, ReportPortal doesn't know if the issue was fixed, as it's done outside the ReportPortal.
But if you test is linked to a ticket in your Bug Tracking system, then we can show you the status of the ticket in your BTS. 
Are you looking for that kind of information on the widget?

**Comment by MaryiaRymarchyk** [comment]
@paresh-celigo any comments from your side?

**Comment by paresh-celigo** [comment]
> if you test is linked to a ticket in your Bug Tracking system, then we can show you the status of the ticket in your BTS



> @paresh-celigo Well, ReportPortal doesn't know if the issue was fixed, as it's done outside the ReportPortal. But if you test is linked to a ticket in your Bug Tracking system, then we can show you the status of the ticket in your BTS. Are you looking for that kind of information on the widget?

Hi @Kozovskaya yes this will work for me

**Comment by MaryiaRymarchyk** [comment]
Great, then ticket will be closed.
If you have other questions/ concerns , please feel free to create a new issue.
