### ISSUE TITLE
Request for Widget to get Most Passed Test cases

### ISSUE THREAD

**Issue by paresh-celigo** [reportportal/reportportal#2204]
Hi Team, We have Most failed and Most flaky widget but we dont have most passed or passed test case widget, I would like to request you to please add the widget for passed test cases

**Comment by Kozovskaya** [comment]
Hello @paresh-celigo, 
could you please clarify for what purposes you need such widgets?

**Comment by ninamazurenka** [comment]
Hello @paresh-celigo !
Do you have any updates or comments from your side?
