### ISSUE TITLE
reportportal_api_1 keeps going unhealthy

### ISSUE THREAD

**Issue by hager-yousri** [reportportal/reportportal#2209]
reportal portal keeps working and up untill starting to post results on it
-it goes down as shown in attached image 
<img width="617" alt="image" src="https://github.com/reportportal/reportportal/assets/69680400/13267109-c26b-48df-ba32-4bd7d521c433">

-this container " reportportal_api_1" becomes "unhealty"
-no results are posted

**I tried many times to restart that container and docker compose and it goes up but once running the command to post the results it goes down again and again**

API Service: 5.8.0;
Index Service: 5.8.0;
Jobs Service: 5.8.0;
Authorization Service: 5.8.0
Service UI: 5.8.0;

**Comment by MaryiaRymarchyk** [comment]
Hello @hager-yousri  please try with latest version of RP services which is 5.10 and let us know if the issue remains.

**Comment by polskomleko** [comment]
I''ll add this as a comment as to not duplicate the issue.

We've being using 5.10 version and started to experience the same thing lately. API containers just goes unhealthy all of a sudden and logs show a huge amount of stack traces that indicate that it can't connect to rabbitmq for some reason, even though the rabbitmq container seems healthy and doesn't appear to have any issues. There's no space issues or any resource issue on the node according to monitoring, the healthcheck just start failing at random intervals after restarting the containers.
I can provide any logs if necessary.

**Comment by IvanKustau** [comment]
@hager-yousri @polskomleko Can you share logs of the service-api please

**Comment by hager-yousri** [comment]
> @hager-yousri @polskomleko Can you share logs of the service-api please

@IvanKustau here are the logs
[rpLogs.docx](https://github.com/reportportal/reportportal/files/14021175/rpLogs.docx)
[rplogs2.docx](https://github.com/reportportal/reportportal/files/14021176/rplogs2.docx)

**Comment by IvanKustau** [comment]
@hager-yousri Your issue is known to us: https://github.com/reportportal/reportportal/issues/1970

It's resolved in 5.10.0 version, please check it out

**Comment by MaryiaRymarchyk** [comment]
@hager-yousri As we haven't received a reply from you, we'll close the issue for now.
With latest version of RP issue should not be relevant.
