### ISSUE TITLE
Reportportal and Podman

### ISSUE THREAD

**Issue by anetka07** [reportportal/reportportal#2214]
Is it possible to deploy reporptortal on podman (with podman-compose)? 
...

I tried but there are many problems with rootless in podman. Is there a chance for compatibility not only with docker?
...

**Comment by hlebkanonik** [comment]
Hi @anetka07

The current guide is tailored for Docker. Although ReportPortal services work with Podman, there are Traefik-related issues. You can try modifying the Traefik settings to make them compatible with Podman. For instance, investigate launching Podman in rootless mode and attempt to change the path to podman.sock [here](https://github.com/reportportal/reportportal/blob/v23.2/docker-compose.yml#L327) (e.g., /run/user/1000/podman/podman.sock:/var/run/docker.sock).



Additionally, you have the option to use our Kubernetes Helm chart, which is compatible with OpenShift. You can find it at https://github.com/reportportal/kubernetes/tree/reportportal-23.2.0/reportportal.

**Comment by MaryiaRymarchyk** [comment]
@anetka07  any feedback from your side?

**Comment by anetka07** [comment]
I tried to modify the settings on podman but nothing helped. Error after another error. Spoko i went back to the docker.

**Comment by MaryiaRymarchyk** [comment]
Thanks for the update! 
As there are no remain actions from ReportPortal side - ticket will be closed.
