### ISSUE TITLE
v23.2 Migration of Legacy UUID Auth Tokens not working

### ISSUE THREAD

**Issue by pmaus22** [reportportal/reportportal#2216]
**Describe the bug**
After upgrading from v5.7.3 to v23.2 of RP, the previously used UUID auth tokens stopped working. This is the same issue as in https://github.com/reportportal/reportportal/issues/2163, but for us regenerating the token for every user is no solution because of many users with regular launches.

We also tried different upgrade approaches but the migration of UUIDs to Legacy API Keys never worked:

- Using UUIDs to integrate agents in v5.7.3, then upgrading from v5.7.3 to v23.2
- Using UUIDs to integrate agents in v5.7.3, then upgrading from v5.7.3 to v23.1 and then from v23.1 to v23.2
- Upgrading from v5.7.3 to v23.1, then using UUIDs to integrate agents in v23.1 and then upgrading from v23.1 to v23.2

**Expected behavior**
"If you’ve previously integrated agents using UUID, it has been converted to a Legacy API Key at the moment of migration to newest version and it remains valid and operational."

see https://reportportal.io/docs/reportportal-configuration/HowToGetAnAccessTokenInReportPortal/#2-authorization-with-users-api-key-for-agents

**Screenshots**
No API Keys after the upgrade, even though the UUID should have been migrated to a Legacy API Key because it was used to upload test results:
<img width="685" alt="image" src="https://github.com/reportportal/reportportal/assets/103952726/e6c62a0c-ce6a-49b1-adcd-4be38971040b">

Error 401 Unauthorized in client log:
<img width="843" alt="image" src="https://github.com/reportportal/reportportal/assets/103952726/6ac61143-df26-4f8a-a9e6-d758b3fa894b">

**Versions:**
 Deployment via Docker Compose https://raw.githubusercontent.com/reportportal/reportportal/v23.2/docker-compose.yml
- OS: Debian GNU/Linux 12 (bookworm)
- Docker: v25.0.1
- Docker Compose Plugin: v2.24.2
 - Version of RP: API Service: 5.10.1;Index Service: 5.10.1;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.1;

**Comment by Pink-Bumblebee** [comment]
Please read this guide: https://github.com/reportportal/migrations-complex/blob/master/README.md, especially https://github.com/reportportal/migrations-complex/blob/master/README.md#old-tokens-to-api-keys-migration

**Comment by pmaus22** [comment]
Thanks, @Pink-Bumblebee! The migrations-complex service helped resolve our issue and could migrate all of our old UUID Tokens.

I think this service was not mentioned in the [v23.2 Migration Guide](https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.23.2), nor was it mentioned in the [documentation regarding the api keys](https://reportportal.io/docs/reportportal-configuration/HowToGetAnAccessTokenInReportPortal/#2-authorization-with-users-api-key-for-agents). Maybe a link could help other people to find the migrations-complex service as well.
