### ISSUE TITLE
enable Unique Errors table sorting by cluster size

### ISSUE THREAD

**Issue by pondrejk** [reportportal/reportportal#2219]
**Describe the solution you'd like**
...

At the `Unique Errors` page, I'd like to be able to sort the clusters by size, so that I can address the most impactful error first. Right now, one needs to expand the clusters one by one to find out the number of cluster members.

It would be great if the response of `​/v1​/{projectName}​/launch​/cluster​/{launchId}` contained the number of members per cluster. This information could then be used in the UI, displayed at the top level clusters and used for filtering. Small mockup of how it could look like
![image](https://github.com/reportportal/reportportal/assets/8287578/508733bf-9bbd-4e70-ab87-0df1f93c9340)
 

**Is your feature request related to a problem? Please describe.**
...

**Comment by alena-babrova** [comment]
Hello @pondrejk,
Thank you for the input. The suggestion is indeed valuable and can be convenient to all users.
We have created a task within our development team to discuss the feature and decide on the possibility of implementation.

Thanks for your contribution!

**Comment by Kozovskaya** [comment]
Hello @pondrejk 
We are now discussing the possibility to show the number of tests per cluster and sorting.
Could you please share with us the information how many clusters per launch you usually have? The max number?
How many tests in cluster you faced up with?
This will help us to make the performance testing on more realistic setup!
Thanks in advance

**Comment by pondrejk** [comment]
Hello, I think the biggest number I've seen so far is around 250

**Comment by Kozovskaya** [comment]
Hello @pondrejk 
The ReportPortal version 24.2 is already released! The improvement is there!
I'm closing the issue.
Thank you for using ReportPortal!
