### ISSUE TITLE
"Launch 'xxx' not found. Did you use correct Launch ID?"

### ISSUE THREAD

**Issue by Haja49** [reportportal/reportportal#2222]
Hi Team,
I have been using report portal for last couple of months as a docker service. But I am facing some issue recently where though test execution completes without any error, launch is not getting added in the report. Please help me here.

Error Message:
Launch 'xxx' not found. Did you use correct Launch ID?

I could observe the same error while debugging the service class (get_launch_info()) of reportportal-client library.
{'errorCode': 4041, 'message': "Launch 'xxx' not found. Did you use correct Launch ID?"}

I am using v5.10.1 for service-api with python pytest-reportportal (v5.1.3) library.

- Browser: Chrome
- OS: ubuntu
- Current version:API Service: 5.10.1;Index Service: 5.10.0;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0;

**Comment by Pink-Bumblebee** [comment]
Discussed here https://github.com/reportportal/reportportal/discussions/1250#discussioncomment-8366908
