### ISSUE TITLE
Jira issue status is not updated

### ISSUE THREAD

**Issue by alikaratana** [reportportal/reportportal#2224]
I have created an issue from local Report Portal instance to a local Jira server successfully. When i update the status of the issue to In Progress, In Review and Done respectively, it was still To Do in Report Portal.

I am not sure if it is a bug or a not implemented feature but i think the status should be updated since it can be seen on Report Portal.

 - OS: Windows 10
 - Report Portal Instance Runs On OS: Ubuntu 22.04.3 LTS
 - Browser: Chrome (121.0.6167.140)
 - Version of RP: 5.10.0
 - Version of Jira: v9.4.14

**Comment by Pink-Bumblebee** [comment]
@alikaratana , Status in RP should update, but not immediately after changing it in Jira.
