### ISSUE TITLE
Service-api container alone going unhealthy state frequently

### ISSUE THREAD

**Issue by smslingam** [reportportal/reportportal#2227]
Dear Team,

I successfully installed the reportportal application using docker on a server with a configuration of 8 CPUs and 32GB RAM. To push data to reportportal from an XML file, I am using the following command:

`python3 -m robotframework_reportportal.post_report -v RP_ENDPOINT:xxxx -v RP_PROJECT:xxxx -v RP_API_KEY:xxxx -v RP_LAUNCH:xxxx -v RP_LAUNCH_ATTRIBUTES:"xxxx" output.xml`

Sometimes, the output.xml file can be quite large. However, I am dynamically pushing the data and it has been successfully uploaded. The problem I am facing is that the service-api container frequently goes into an unhealthy state. The reportportal UI shows a loading state and the data is not able to be published to the reportportal.

I have attached the logs for your reference. I would greatly appreciate your assistance in resolving this issue.

![image](https://github.com/reportportal/reportportal/assets/159430616/259e22bb-ada1-4c39-992d-4183c6615841)

[5th_FEB_RABBIT.txt](https://github.com/reportportal/reportportal/files/14207983/5th_FEB_RABBIT.txt)
[LOG FILE.zip](https://github.com/reportportal/reportportal/files/14208028/LOG.FILE.zip)
 Is this  issue from reportportal end , or anything issue from my end. Can you please let me know the reason for this unhealthy state.

**Comment by irynakozak2** [comment]
@smslingam Hi! Could you please specify the data amount in the output.xml: how many suites, tests, steps, and logs do you have? It would be beneficial if you also provide the output of the `docker stats` while you're pushing the output.xml to the ReportPortal.
Howewer, I suppose the issue can be with the connectivity from API service to the RabbitMQ, we will check at our side.

**Comment by sankar222** [comment]
Please see the docker stats 
<img width="738" alt="dockerstats" src="https://github.com/reportportal/reportportal/assets/5201779/ed2272a6-2ce7-489d-98b4-76641eace6e7">

**Comment by irynakozak2** [comment]
@sankar222 Thank you for providing the stats, see no excessive usage both CPU and Memory by containers.
But what about the actual data amount(file size of output.xml) you're pushing to the ReportPortal + data amount in the output.xml: how many suites, tests, steps, and logs do you have?

**Comment by sankar222** [comment]
output.xml file has 2GB size. We have many suites and tests and steps.  we have multiple programs runs on parallely. So plenty of xml file we're publishing

**Comment by irynakozak2** [comment]
@sankar222 Hi! Please try to split the large file into the smallest *.XML files to make the smooth uploading.

**Comment by irynakozak2** [comment]
@sankar222 Hi! It's been a while since we last heard from you, so I'll close the issue for now.
If the problem persists, please reopen the issue. Alternatively, consider increasing the memory allocated for your ReportPortal installation and re-checking the issue.
