### ISSUE TITLE
Reqnroll agent dotnet

### ISSUE THREAD

**Issue by 4OTbIPE** [reportportal/reportportal#2228]
After SpecFlow's [death](https://github.com/SpecFlowOSS/SpecFlow/issues/2719#issuecomment-1934292742), its fork Rignroll was created. Can you please create an agent for ReportPortal to integrate with this new fork. I think in the [existing agent for Specflow](https://github.com/reportportal/agent-net-specflow) it will be enough just to replace packages and namespaces and create a new one

**Comment by nvborisenko** [comment]
Yeah, I saw. Definitely we will do it.

**Comment by 4OTbIPE** [comment]
> Yeah, I saw. Definitely we will do it.

I have seen the new repository for the Reqnroll agent, but the link to the nuget package is broken. Is it not ready for publication yet?

**Comment by nvborisenko** [comment]
It is still in development.

**Comment by nvborisenko** [comment]
Track the progress there: https://github.com/reportportal/agent-dotnet-reqnroll/issues/1

**Comment by nvborisenko** [comment]
`v1.0.0` is out, file your issues there if any. Thanks.
