### ISSUE TITLE
test run not showing under launch section when deployed RP in Ubundu AWS server

### ISSUE THREAD

**Issue by uschouhan** [reportportal/reportportal#2229]
### Discussed in https://github.com/reportportal/reportportal/discussions/2226

<div type='discussions-op-text'>

<sup>Originally posted by **uschouhan** February  8, 2024</sup>
I  am using RP version 5.10.0 and agent-java-testng as 5.4.0 .When i deploy this in local everything works fine and i can my test launches are getting captured properly however when same is deployed in AWS ubuntu server then i can access the page but launches arent showing . I have given correct ip/port and key details ...Anything i need to check ? 

</div>

**Comment by Pink-Bumblebee** [comment]
@uschouhan , please check my understanding: are you trying to deploy using info from this article https://reportportal.io/docs/installation-steps/DeployWithAWSECSFargate or just docker on top of Ubuntu server in AWS? Thank you in advance for clarification.

**Comment by uschouhan** [comment]
@Pink-Bumblebee just docker on top of Ubuntu server in AWS .Followed below steps to install https://reportportal.io/installation

**Comment by Pink-Bumblebee** [comment]
Is <your_rp_instance>:8081 showing someting? This is Traefik port.

**Comment by uschouhan** [comment]
<img width="1686" alt="Screenshot 2024-02-12 at 5 26 00 PM" src="https://github.com/reportportal/reportportal/assets/118183806/0cbdf5bf-a9b4-4699-b7cc-676ec92bbcf8">
This is how docker container for reporting portal looks like .
Thing is i have whitelisted port 8080 for reporting portal .. do i need to whitelist port 8081 also ?

**Comment by Pink-Bumblebee** [comment]
1. just try open page <your_rp_instance>:8081. Is it visible?
2. you wrote that at your local instance you have successful installation. Have you had postgres 15 at your local env?

**Comment by uschouhan** [comment]
@Pink-Bumblebee I need to whitelist to access port 8081 . will try that . Regarding local setup i just had postgres:12-alpine in my local however in remote as per above screenshot i can see 2 instances for postgres postgres:12-alpine and postgres-15 .Can it create an issue ?

**Comment by Pink-Bumblebee** [comment]
@uschouhan , in compare with local instance you have additional postgres-15 and redis. Who and why installed them? 
Also please check that your Ubuntu server has enough resources to run reportportal : at least 16Gb Ram and 4 cores.
Maybe adding 'dozzle' container (https://hub.docker.com/r/amir20/dozzle) into docker-compose could help you to get information from logs. ;)

**Comment by Pink-Bumblebee** [comment]
@uschouhan , as we haven't received any new reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Comment by uschouhan** [comment]
@Pink-Bumblebee that machine has other service running which needs postgrey-15 . To avoid i am trying to install reportportal in our windows server 2019 however facing this issue now while making docker-compose up 
![image](https://github.com/reportportal/reportportal/assets/118183806/9b4167ac-6dca-41c2-acb4-eaf716a8c191)
let us know if we can use report portal in windows server 2019 or not
