### ISSUE TITLE
link type of a failure to testName

### ISSUE THREAD

**Issue by armadco** [reportportal/reportportal#2232]
In Report Portal, as I understand you can link failures specificly to text messages. after that it willl be copied to future runs.

Is is possible to link type of failure to testName? so it will not be dublicated to other tests with the same error message?

**Comment by Kozovskaya** [comment]
Hello @armadco 
Could you please specify your case in more details? Are you talking about the Analyzer which takes into account the error message?

**Comment by Kozovskaya** [comment]
@armadco please check if your case is similar to this one https://github.com/reportportal/reportportal/issues/2106
