### ISSUE TITLE
No Option to Log in via SSO after setting up SAML, no error

### ISSUE THREAD

**Issue by BenManifold** [reportportal/reportportal#2234]
**Describe the bug**
I've configured the necessary fields as described [here](https://reportportal.io/docs/reportportal-configuration/authorization/SAMLProvider/)

There is a closed bug with this same behavior, but there's no indication of what was done to correct the issue, just a reference to "gateway configs" and enabling "insecure api". Should there be some documentation explaining that SAML authentication will not work unless some default settings are changed? If so, which ones?

**Expected behavior**
An option to log in via OAUTH should appear after entering valid parameters as described above, if some misconfiguration makes this impossible, there should be a visible error message or other indication.

**Screenshots**
If applicable

**Versions:**
 - Windows, Firefox
 - Version of RP, the current version is left blank in the UI, no idea why. The images seem to be 5.10.0

**Comment by BenManifold** [comment]
We're running Helm Chart version 5.10.0, there do not appear to be any configurations that resemble the solution for Issue #2047, any guidance on how to set up the istio configurations for this chart to allow SSO would be appreciated.

**Comment by BenManifold** [comment]
It seems like the actual SAML integration is there, there's just no green button at all to use it. We've eaten up most of a day trying to understand why.

If we hack together a URL that looks like 
https://<host-name>/uat/saml/sp/discovery?idp=<keycloak-realm-url>and paste it into the browser, we're allowed to log in with our existing browser token, so the actual SAML credentials are good and valid, it seems like there's a UI bug preventing the actual SAML option from showing up on the login page as of image tag 5.10.0

**Comment by BenManifold** [comment]
Ok, as before, The problem was Istio Routing Logic, the actual bug here is basically a failure to surface the 404 that comes back from the call to /composite/info

Istio routing is finicky and doesn't follow the same logic as Nginx gateway rules, so if you're going to use Istio, watch out for that, if you have an exact match on "/", nothing else will ever go to /index

Your Istio VirtualService should look like this, with no match on the *-index entry.

**Comment by KriTh07** [comment]
Can you please help me with workaround? I am facing the same issue. I can see the version in the login screen, also cannot see the SAML login button.
