### ISSUE TITLE
Getting error - Failed to send log Error: Request failed with status code 500: {"errorCode":5000,"message":"Unclassified error [org.hibernate.exception.GenericJDBCException: could not execute statement]"

### ISSUE THREAD

**Issue by anud22** [reportportal/reportportal#2237]
Getting error - Failed to send log Error: Request failed with status code 500: {"errorCode":5000,"message":"Unclassified error [org.hibernate.exception.GenericJDBCException: could not execute statement]"

We suddenly started seeing above issue. Not sure how to troubleshoot it. When does ReportPortal throw this error?

**Comment by alena-babrova** [comment]
Dear @anud22,

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
