### ISSUE TITLE
Report Portal UI is stuck in loading

### ISSUE THREAD

**Issue by ArinaNichko** [reportportal/reportportal#2244]
Hello, 
I use minikube and try to run RP locally, but I see only "Loading"
![rp](https://github.com/reportportal/reportportal/assets/104902526/d7421a60-7dcb-4cb6-8f49-0471443a7418)

PS C:\WINDOWS\system32> kubectl get pods
NAME                                                        READY   STATUS     RESTARTS         AGE
elasticsearch-coordinating-0                                0/1     Running    21 (86s ago)     121m
elasticsearch-coordinating-1                                0/1     Running    21 (86s ago)     121m
elasticsearch-data-0                                        0/1     Running    22 (2m47s ago)   121m
elasticsearch-data-1                                        0/1     Running    21 (86s ago)     121m
elasticsearch-ingest-0                                      0/1     Running    21 (87s ago)     121m
elasticsearch-ingest-1                                      0/1     Running    21 (87s ago)     121m
elasticsearch-master-0                                      0/1     Running    21 (86s ago)     121m
elasticsearch-master-1                                      0/1     Running    21 (97s ago)     121m
minio-65795cf9b-z9s79                                       1/1     Running    11 (13m ago)     113m
my-release-minio-77875dbd9c-8ghrq                           1/1     Running    7 (13m ago)      87m
my-release-postgresql-0                                     1/1     Running    2 (20m ago)      87m
my-release-rabbitmq-0                                       0/1     Running    8 (3m3s ago)     84m
my-release-reportportal-analyzer-0                          0/1     Pending    0                87m
my-release-reportportal-analyzer-train-0                    0/1     Init:0/1   4 (14m ago)      87m
my-release-reportportal-api-dbb4fd8bb-cn8nz                 0/1     Pending    0                87m
my-release-reportportal-index-668b55bfd5-x9ngp              1/1     Running    1 (20m ago)      87m
my-release-reportportal-jobs-84f7cbf97-58lwz                0/1     Init:0/1   3                87m
my-release-reportportal-metrics-gatherer-5887f6cfc8-gksv8   0/1     Init:0/1   4 (14m ago)      87m
my-release-reportportal-migrations-9v4gn                    1/1     Running    1 (20m ago)      87m
my-release-reportportal-uat-566c6746cd-bhp6j                0/1     Init:0/1   5                87m
my-release-reportportal-ui-5677b7db48-7zfl9                 1/1     Running    1 (20m ago)      87m
nginx-ingress-ingress-nginx-controller-7756947456-zs5zx     1/1     Running    0                2m3s
opensearch-cluster-master-0                                 0/1     Pending    0                87m
postgresql-0                                                1/1     Running    13 (2m53s ago)   122m
rabbitmq-0                                                  0/1     Running    12 (4m20s ago)   113m
PS C:\WINDOWS\system32> kubectl port-forward my-release-reportportal-ui-5677b7db48-7zfl9 8080:8080
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080

**Comment by Pink-Bumblebee** [comment]
@ArinaNichko , as I could see, you have a lot of extra pods. And _migration_ service "Running" but _uat_ - "Init". Need to see logs.

**Comment by raikbitters** [comment]
@ArinaNichko, hello. I see that `my-release-reportportnal-migrations-wqmdm 0/1` has a `Pending` status; this is why API and UAT don't run (Init status means that the Init container is waiting). While API and UAT won't be run, you will see Loading...

Moreover, `opensearch-cluster-master-0 0/1` has a `Pending` statute, so Migration has a `Pending` status. Please check the `opensearch-cluster-master` logs. It looks like you don't have the required resources.

**Comment by ArinaNichko** [comment]
@raikbitters hello, it's now and logs for opensearch-cluster-master

C:\Windows\System32>kubectl get pods
NAME                                                        READY   STATUS        RESTARTS         AGE
elasticsearch-coordinating-0                                0/1     Running       72 (5m4s ago)    44h
elasticsearch-coordinating-1                                0/1     Running       72 (5m4s ago)    44h
elasticsearch-data-0                                        0/1     Running       105 (5m4s ago)   44h
elasticsearch-data-1                                        0/1     Running       106 (5m4s ago)   44h
elasticsearch-ingest-0                                      0/1     Running       73 (5m4s ago)    44h
elasticsearch-ingest-1                                      0/1     Running       72 (5m4s ago)    44h
elasticsearch-master-0                                      0/1     Running       72 (5m5s ago)    44h
elasticsearch-master-1                                      0/1     Running       72 (5m4s ago)    44h
minio-65795cf9b-z9s79                                       1/1     Running       70 (5m5s ago)    44h
my-release-minio-77875dbd9c-lnfjl                           1/1     Running       1 (56s ago)      117s
my-release-rabbitmq-0                                       0/1     Terminating   37 (5m9s ago)    42h
my-release-reportportal-analyzer-0                          0/1     Init:0/1      0                117s
my-release-reportportal-analyzer-train-0                    0/1     Pending       0                115s
my-release-reportportal-api-786d97d997-6r98q                0/1     Pending       0                117s
my-release-reportportal-index-668b55bfd5-5tnmn              1/1     Running       0                118s
my-release-reportportal-jobs-7d84844fdd-rhbtq               0/1     Init:0/1      0                118s
my-release-reportportal-metrics-gatherer-8567478fb5-rbfv5   0/1     Init:0/1      0                118s
my-release-reportportal-migrations-n8kcf                    1/1     Running       0                118s
my-release-reportportal-uat-77b4999b65-g8ql2                0/1     Init:0/1      0                118s
my-release-reportportal-ui-5677b7db48-4dkw7                 1/1     Running       0                118s
nginx-ingress-ingress-nginx-controller-7756947456-zs5zx     1/1     Running       45 (5m5s ago)    42h
opensearch-cluster-master-0                                 0/1     Pending       0                117s
postgresql-0                                                1/1     Running       49 (5m15s ago)   44h
rabbitmq-0                                                  0/1     Running       68 (5m7s ago)    44h

C:\Windows\System32>kubectl describe pod opensearch-cluster-master-0
Name:             opensearch-cluster-master-0
Namespace:        default
Priority:         0
Service Account:  default
Node:             <none>
Labels:           app.kubernetes.io/component=opensearch-cluster-master
                  app.kubernetes.io/instance=my-release
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=opensearch
                  app.kubernetes.io/version=2.11.1
                  apps.kubernetes.io/pod-index=0
                  controller-revision-hash=opensearch-cluster-master-7785d4bb74
                  helm.sh/chart=opensearch-2.17.0
                  statefulset.kubernetes.io/pod-name=opensearch-cluster-master-0
Annotations:      configchecksum: efda1eda81f713ee210587b63871d8b3f25f0dd79d29db13d68e5f05ced62c2
Status:           Pending
IP:
IPs:              <none>
Controlled By:    StatefulSet/opensearch-cluster-master
Init Containers:
  fsgroup-volume:
    Image:      busybox:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
    Args:
      chown -R 1000:1000 /usr/share/opensearch/data
    Environment:  <none>
    Mounts:
      /usr/share/opensearch/data from opensearch-cluster-master (rw)
Containers:
  opensearch:
    Image:       opensearchproject/opensearch:2.11.1
    Ports:       9200/TCP, 9300/TCP, 9600/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP
    Requests:
      cpu:      1
      memory:   100Mi
    Readiness:  tcp-socket :9200 delay=0s timeout=3s period=5s #success=1 #failure=3
    Startup:    tcp-socket :9200 delay=30s timeout=3s period=10s #success=1 #failure=30
    Environment:
      node.name:                    opensearch-cluster-master-0 (v1:metadata.name)
      discovery.seed_hosts:         opensearch-cluster-master-headless
      cluster.name:                 opensearch-cluster
      network.host:                 0.0.0.0
      OPENSEARCH_JAVA_OPTS:         -Xmx512M -Xms512M
      node.roles:                   master,ingest,data,remote_cluster_client,
      discovery.type:               single-node
      DISABLE_INSTALL_DEMO_CONFIG:  true
      DISABLE_SECURITY_PLUGIN:      true
    Mounts:
      /usr/share/opensearch/config/opensearch.yml from config (rw,path="opensearch.yml")
      /usr/share/opensearch/data from opensearch-cluster-master (rw)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  opensearch-cluster-master:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  opensearch-cluster-master-opensearch-cluster-master-0
    ReadOnly:   false
  config:
    Type:        ConfigMap (a volume populated by a ConfigMap)
    Name:        opensearch-cluster-master-config
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  2m22s                default-scheduler  0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..
  Warning  FailedScheduling  23s (x2 over 2m21s)  default-scheduler  0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..

C:\Windows\System32>kubectl describe pod my-release-reportportal-uat-77b4999b65-g8ql2
Name:             my-release-reportportal-uat-77b4999b65-g8ql2
Namespace:        default
Priority:         0
Service Account:  reportportal
Node:             minikube/192.168.59.102
Start Time:       Thu, 07 Mar 2024 12:55:08 +0200
Labels:           component=my-release-reportportal-uat
                  pod-template-hash=77b4999b65
Annotations:      <none>
Status:           Pending
IP:               10.244.1.6
IPs:
  IP:           10.244.1.6
Controlled By:  ReplicaSet/my-release-reportportal-uat-77b4999b65
Init Containers:
  migrations-waiting-init:
    Container ID:  docker://c3f28ec5bdffd9f29e07d1c638966e3a94d5873a73dc2ae54a3e9c67f96f2f88
    Image:         pegasystems/k8s-wait-for:latest
    Image ID:      docker-pullable://pegasystems/k8s-wait-for@sha256:b2366bcb3a24275a31f3db6a03ecfbbd9f55703454a03f45c9f5a088828f931d
    Port:          <none>
    Host Port:     <none>
    Args:
      job-wr
      my-release-reportportal-migrations
    State:          Running
      Started:      Thu, 07 Mar 2024 12:55:16 +0200
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     50m
      memory:  100Mi
    Requests:
      cpu:        50m
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wxtrj (ro)
Containers:
  uat:
    Container ID:
    Image:          reportportal/service-authorization:5.10.0
    Image ID:
    Port:           9999/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   512Mi
    Liveness:   http-get http://:9999/uat/health delay=60s timeout=5s period=40s #success=1 #failure=10
    Readiness:  http-get http://:9999/uat/health delay=60s timeout=5s period=40s #success=1 #failure=10
    Environment:
      SERVER_SERVLET_CONTEXT_PATH:  /uat
      RP_AMQP_PASS:                 rabbitmqpassword
      RP_AMQP_ADDRESSES:            amqp://rabbitmq:$(RP_AMQP_PASS)@my-release-rabbitmq.default.svc.cluster.local:5672
      RP_INITIAL_ADMIN_PASSWORD:
      RP_SAML_SESSION-LIVE:         4320
      JAVA_OPTS:                    -Djava.security.egd=file:/dev/./urandom -XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=90.0
      RP_SESSION_LIVE:              86400
      RP_DB_HOST:                   my-postgresql.host.local
      RP_DB_PORT:                   5432
      RP_DB_NAME:                   reportportal
      RP_DB_USER:                   my-user
      RP_DB_PASS:                   my-password
      DATASTORE_TYPE:               minio
      DATASTORE_ENDPOINT:           http://my-release-minio.default.svc.cluster.local:9000
      DATASTORE_ACCESSKEY:          rpuser
      DATASTORE_SECRETKEY:          miniopassword
      DATASTORE_BUCKETPREFIX:       prj-
      DATASTORE_BUCKETPOSTFIX:
      RP_INTEGRATION_SALT_PATH:     keystore
      DATASTORE_DEFAULTBUCKETNAME:  rp-bucket
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wxtrj (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-wxtrj:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  2m59s  default-scheduler  Successfully assigned default/my-release-reportportal-uat-77b4999b65-g8ql2 to minikube
  Normal  Pulled     2m52s  kubelet            Container image "pegasystems/k8s-wait-for:latest" already present on machine
  Normal  Created    2m51s  kubelet            Created container migrations-waiting-init
  Normal  Started    2m51s  kubelet            Started container migrations-waiting-init

**Comment by ERIK54600** [comment]
How did you deploy to 8080, I just run this command  helm install my-release --set uat.superadminInitPasswd.password="MyPassword" reportportal/reportportal --version 23.2.0
and after that the 8080 port is not showing anything, I use rancher desktop to port forwarding but no working.

**Comment by ERIK54600** [comment]
C:\Windows\System32>kubectl get pods
NAME                                                        READY   STATUS      RESTARTS        AGE
my-release-minio-77875dbd9c-p9j2c                           1/1     Running     0               6m4s
my-release-postgresql-0                                     1/1     Running     0               6m3s
my-release-reportportal-ui-5677b7db48-hkrx2                 1/1     Running     0               6m4s
my-release-reportportal-index-668b55bfd5-ftcfd              1/1     Running     0               6m4s
opensearch-cluster-master-0                                 1/1     Running     0               6m3s
my-release-reportportal-migrations-qmgqt                    0/1     Completed   0               6m4s
my-release-rabbitmq-0                                       1/1     Running     0               6m3s
my-release-reportportal-jobs-84f7cbf97-k4lhw                1/1     Running     0               6m3s
my-release-reportportal-uat-579c866999-p96g6                1/1     Running     0               6m4s
my-release-reportportal-api-dbb4fd8bb-92pgv                 1/1     Running     1 (2m55s ago)   6m4s
my-release-reportportal-analyzer-0                          1/1     Running     0               6m3s
my-release-reportportal-metrics-gatherer-5887f6cfc8-2j6sf   1/1     Running     0               6m3s
my-release-reportportal-analyzer-train-0                    1/1     Running     0               6m3s

**Comment by ArinaNichko** [comment]
@ERIK54600 use this kubectl port-forward <pod-name> 8080:8080

**Comment by ERIK54600** [comment]
I used that, but the UI stuck in loading when doing that, I see reportportal has many services which one I should port forward?

**Comment by ShaiShalevSQream** [comment]
i also has this issue, install latest version of report portal, all pods and init pods run ok, but ui stuck in "loading"
```opensearch-cluster-master-0                      1/1     Running     0          19m
reportportal-analyzer-0                          1/1     Running     0          19m
reportportal-analyzer-train-0                    1/1     Running     0          19m
reportportal-api-6f5f9ff966-hhjz5                1/1     Running     0          19m
reportportal-index-9446ddf9d-ljpp7               1/1     Running     0          19m
reportportal-jobs-7dbd74468-ttfrj                1/1     Running     0          19m
reportportal-metrics-gatherer-595d7cc66c-t6qrp   1/1     Running     0          19m
reportportal-migrations-wjc4b                    0/1     Completed   0          19m
reportportal-minio-7fffd4f58d-6dhh6              1/1     Running     0          19m
reportportal-postgresql-0                        1/1     Running     0          19m
reportportal-rabbitmq-0                          1/1     Running     0          19m
reportportal-uat-659db6786b-rr9dk                1/1     Running     0          19m
reportportal-ui-84ccc9d694-jg9sq                 1/1     Running     0          19m
```
![Screenshot from 2024-03-15 00-50-49](https://github.com/reportportal/reportportal/assets/136981754/bf0843d2-103e-440f-88f6-7e8cd55b19a1)

**Comment by ShaiShalevSQream** [comment]
just to update, when i added gce ingress, and try to access via the loadbalancer IP i can get to UI.
but when i try port-forward the ui service, it get stuck on "Loading.." as it shows above.
