### ISSUE TITLE
Launch Controller API: Merges, need some explanation of what the "launches" integer field actually represents.

### ISSUE THREAD

**Issue by BenManifold** [reportportal/reportportal#2247]
This is what the API documentation provides as a payload example, but there seems to be no...documentation in the documentation that might explain what these options do, specifically the "launches" field. It's a number of launches, presumably, how does it relate to the process of finding some launches by attribute and merging them? Does it govern the merge behavior in some way?

{
  "attributes": [
    {
      "key": "string",
      "value": "string"
    }
  ],
  "description": "string",
  "endTime": "2024-03-08T19:01:03.231Z",
  "extendSuitesDescription": true,
  "launches": [
    0
  ],
  "mergeType": "BASIC",
  "mode": "DEFAULT",
  "name": "string",
  "startTime": "2024-03-08T19:01:03.231Z"
}

**Comment by MaryiaRymarchyk** [comment]
Hi @BenManifold , in the "launches" field you should provide ids of the launches which will be merged. ("launches": [ "{{launchId}}",  "{{launchId2}}"],) 
In the attributes section user may provide new attributes for the merged launch or any of the attributes from the launches which would be merged.

```
"launches": [ 35932, 35934, 30585],
"attributes": [
        { "key": "attribute_from_launch1",
            "value": "01"},
        { "key": "attribute_from_launch2",
            "value": "Android"},
        { "key": "new_attribute_for_merged_launch",
            "value": "new"}
    ]
```

Let me know if any question remains.

**Comment by BenManifold** [comment]
It wasn't quite clear these represent launch IDs, and not a quantity of
launches.

In my mind, it seemed like we would be using the attributes here to query
the launches we wanted to merge, something like "merge all launches that
have the same attributes for git_hash and build_number. Is that possible?
Or do we need to write some scripting to query for launch IDs first?

I'm basically trying to generate clean data, not thousands of "launches"
per set of tests, so that a specific pipeline produces 1 or 2 launches
despite splitting the work up among a bunch of different pods and JVMs
within those pods.

**Comment by BenManifold** [comment]
And this means running the tests with the agent, and then having a cleanup
job that runs after in the pipeline to force-finish the ones that got left
dangling and then merges all the ones with the same attributes. I'm trying
to figure out how to do this from the API documentation, which gives me the
general json structure of a request, but not so much an explanation of what
the options and parameters do.

**Comment by MaryiaRymarchyk** [comment]
Hi @BenManifold, if you want to merge all launches with same attributes - you can do the following:
On the All launches tab use filter by Attribute - and provide key and value.
After launches are filtered - select all with checkbox and start Merge.

![image](https://github.com/reportportal/reportportal/assets/122868739/bf5c2141-58e7-4a61-8176-f6d60d931068)

**Comment by BenManifold** [comment]
So I'm trying to avoid click-ops and actually do this as part of a CICD
pipeline, I'm not going to create a daily chore for myself or someone else
to do this manually.

**Comment by BenManifold** [comment]
So right now I'm writing a small python script, it seems like the only way
to do this is to first make a call for ALL launches from that project, as
the attributes filter doesn't seem to work the way I would expect it to
from the launches API, and then do the filtering and aggregation client
side in my script. I can't really find any examples for how to do a more
selective query against the launches GET endpoint that would reduce the
amount of traffic.

**Comment by MaryiaRymarchyk** [comment]
@BenManifold you can try :
GET   {{url}}/{{projectName}}/launch?filter.has.compositeAttribute=label:Extra,android 10.2

and list all the attribute:value via comma, or provide only value like in my example: "android 10.2" is the attribute value without a key.

**Comment by BenManifold** [comment]
Thank you, this is pretty much exactly what I was trying to do, but the
filter.eq parameter made it seem like it wasn't really possible when I
tried to use it.

**Comment by alena-babrova** [comment]
Hello @BenManifold,

Seems like your question is resolved, isn't it? 
Don't you mind closing the ticket?
