### ISSUE TITLE
Email notifications with a wrong url if using RESOURCE_PATH

### ISSUE THREAD

**Issue by svaraksin-gd** [reportportal/reportportal#2249]
**Describe the bug**
Didn't find an appropriate repository for this issue. When you are using RESOURCE_PATH to land RP under a specific base path it works properly except notifications. Notificatiosn comes but with link to domain without this RESOURCE_PATH inside.

**Expected behavior**
Links in email notifications should respect RESOURCE_PATH as well.

**Screenshots**
<img width="1096" alt="image" src="https://github.com/reportportal/reportportal/assets/133391708/ce6ab645-be48-4ebf-ad6b-98c27d406e96">
<img width="1085" alt="image" src="https://github.com/reportportal/reportportal/assets/133391708/1a2be524-86d2-4917-bd4e-3f5b7843fa80">

**Versions:**
 - Version of RP [find it under Login form, copy as is] kubernetes reportportal-24.1.0 (doesn't have versions under Login form) and reportportal-23.2.0
 
<img width="488" alt="image" src="https://github.com/reportportal/reportportal/assets/133391708/872e90f1-981a-4012-ab58-747bc1dbe3a2">

**Comment by alena-babrova** [comment]
Hello @svaraksin-gd,

I want to inform you that the bug is already fixed and will be released in version 24.2.

**Comment by VeranikaRymzha** [comment]
Hello @svaraksin-gd,
I wanted to let you know that the ReportPortal 24.2 version is now live, along with the improvement you've requested.

You can find more details about the new features and enhancements in the [release notes](https://reportportal.io/docs/releases/Version24.2/). 
Feel free to try it out and share any feedback you may have.

Have a great day!

**Comment by APiankouski** [comment]
@Zenin-Dmitry did you use anync(v2) reporting?

**Comment by Zenin-Dmitry** [comment]
> [@Zenin-Dmitry](https://github.com/Zenin-Dmitry) did you use anync(v2) reporting?

We had version 24 and we used dotnet6 . When we updated to dotnet 8, the link in the letter stopped working and the autotests in the report portal stopped completing correctly. A couple of days ago, I updated the report portal to the latest version. The test completion time became correct, but the link in the letter to launch is incorrect.
