### ISSUE TITLE
v24.1 Migration Guide Clarifications

### ISSUE THREAD

**Issue by tomikonio** [reportportal/reportportal#2252]
Hi,
In the [migration guide to v24.1](https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.24.1) the following is stated:

> ReportPortal has **replaced MinIO with a File system** and ElasticSearch with OpenSearch. To migrate successfully from ReportPortal v5.5 to v24.1, follow these steps:

Following it are steps to use a local path volume for the different services (and PostgreSQL - why?):

> Adjust volume paths for the API, UAT, Jobs, Analyzer, and Analyzer Train containers in the Docker Compose file:
> FROM:
> 
> volumes:
> - storage:/data/storage
> TO:
> 
> volumes:
>    - ./local_path_to_your_storage:/data/storage
> Update the volume path for the PostgreSQL database container:
> FROM:
> 
> volumes:
>    - postgres:/var/lib/postgresql/data
> TO:
> 
> volumes:
>    - ./local_path_to_your_storage:/var/lib/postgresql/data 

Using a filesystem for all services is quite problematic in environments like Kubernetes.
I do see that the helm chart is still using minio though.

Would like to have some clarifications on the above, please.
Best wishes.

**Comment by hlebkanonik** [comment]
Hi! This guide for Docker Compose. The Kubernetes migration guide is available [here](https://github.com/reportportal/kubernetes/wiki/Migration-guide#migration-to-v241).

**Comment by tomikonio** [comment]
Thanks @hlebkanonik 
But, wouldn't it make a potential migration from `docker-compose` to `Kubernetes` and vice-versa more cumbersome?
E.g. for a migration to k8s, we shall be required to switch from `filesystem` to `s3` first (?)

**Comment by hlebkanonik** [comment]
To migrate between Docker and Kubernetes, it is important to backup your binary storage and database.

Amazon S3 is one of the options for binary storage, you can use either S3, or a MinIO container, or a local file system. As for the database, it can also be a PostgreSQL container, Amazon RDS, or another Postgres cloud solution and its standard data backup tools.
