### ISSUE TITLE
Unable to add filter with colon (":") character

### ISSUE THREAD

**Issue by smerberg** [reportportal/reportportal#2254]
**Describe the bug**

My team runs tests on multiple servers, so on each launch we have an attribute with a key of "server" and a value of the corresponding server address (i.e. https://abc.xyz). But it appears that when I create a filter for this attribute, the value is getting cut off after "https".

I am also able to reproduce this behavior on the demo site @ https://demo.reportportal.io/ui/#default_personal/launches/all

**Expected behavior**
1. Load the launches page of RP demo site: https://demo.reportportal.io/ui/#default_personal/launches/all
2. Add a new attribute to any of the existing launches - key = server, value = https://reportportal.io
![image](https://github.com/reportportal/service-api/assets/3135561/c352aac9-8095-4838-93a9-8753bc947022)
3. After saving the new attribute, it looks like the server value is split on the colon (I actually don't see this part of the issue on my company's server, but I did see it on the RP demo server, so I included it since it seems relevant).
![image](https://github.com/reportportal/service-api/assets/3135561/c5df5893-f758-464b-a461-94094e5e99d3)
4. Add a new filter with attribute key/value of "server" and "https://reportportal.io"
![image](https://github.com/reportportal/service-api/assets/3135561/e3bec41c-2571-44ba-87e1-0a9a70773e12)
5. After creating the new filter and saving it, it does actually seem to work initially, even though the "server" value is cut off for the filter and the launch attributes
![image](https://github.com/reportportal/service-api/assets/3135561/e7c0b571-4153-48e3-ac12-4900b23963a7)
6. Click on the "Filters" link in the panel on the left side.
7. Select the newly created filter
8. No results display in launches
![image](https://github.com/reportportal/service-api/assets/3135561/80bf104c-0c2b-4005-83de-bbcbbbec297c)
The filter also does not pull any data into dashboards that we create

**Versions:**
API Service: 5.10.1;
Index Service: 5.10.0;
Jobs Service: 5.10.0;
Authorization Service: 5.10.0;
Service UI: 5.10.0;

This worked up until we upgraded recently (I think we were on 5.6 before).

**Comment by Pink-Bumblebee** [comment]
Hello @smerberg , looks like it is not bug in newer versions. It is new way how to store attributes and double ':' in attribute is not allowed anymore. Sorry.

**Comment by ltowarek** [comment]
Hi. If I understand correctly, this bug prevents links between launches/test items and CI/CD pipelines.

For example, by adding URL to Jenkins build and job as launch's attribute, one could filter all results triggered by given Jenkins job and keep track of its health over time.

Do you plan to fix this issue? If not, is there any workaround to keep two way connection between test results and CI/CD pipeline that produced them?

**Comment by ltowarek** [comment]
I have confirmed, that the issue has been introduced in [v24.1](https://github.com/reportportal/reportportal/tree/v24.1).

[v23.2](https://github.com/reportportal/reportportal/tree/v23.2) works fine i.e. it is possible to add a launch attribute with `:` e.g. `https://example.com`.
