### ISSUE TITLE
Getting hebrew characters data shown in RP

### ISSUE THREAD

**Issue by ladybug101010** [reportportal/reportportal#2257]
Hi, We are using the RP in our organization 
And some of the data that we expect to receive is in Hebrew, but it shown in gibberish 
How can I adapt the imported data so it will show the Hebrew data in the RP?

**Comment by Pink-Bumblebee** [comment]
@ladybug101010 , could you please provide some screenshots and additional information?

**Comment by ladybug101010** [comment]
So apparently i fixed the issue myself. Thanks !

**Comment by Pink-Bumblebee** [comment]
@ladybug101010 , please share your knowledge with community.

**Comment by ladybug101010** [comment]
Right! sure, Just added the specific encoding to my main class
I am coding in Java & Selenium so added  System.setProperty("file.encoding", "UTF-8");
the UTF part is where one can choose the specific character language needed 

https://www.microfocus.com/documentation/idol/IDOL_23_4/Content_23.4_Documentation/Help/Content/Actions/ENCODINGS/_IDOL_ENCODINGS.htm 

Most language use UTF-8
