### ISSUE TITLE
Ability to configure Pass Rate in widgets

### ISSUE THREAD

**Issue by kaushalshah06** [reportportal/reportportal#2267]
**Describe the solution you'd like**
Reportportal [calculates](https://reportportal.io/docs/dashboards-and-widgets/PassingRatePerLaunch) Pass Rate as
Passing rate = Passed / (Passed + Failed + Skipped + Interrupted). While the linked document is specific to a widget but it applies to most of the widgets and pages where pass rate is displayed.

The request is to provide users ability to configure formula (i.e. the denominator) for the pass rate. 

**Is your feature request related to a problem? Please describe.**
The above request is useful when tests are skipped on predefined conditions. For example, a test can not be executed because it is not suitable/applicable on target platforms under test (example: a test is not applicable on iOS but is required on android). Or some pre-requisite conditions required to run test is not met and therefore test must be skipped. In such scenarios, above discussed formula does not give accurate representation of True pass rate and numbers look more alarming than they should. Ability to configure Pass Rate is the most requested feature from our users and we would greatly appreciate assistance with this request.

**Comment by Kozovskaya** [comment]
Hello @kaushalshah06 
Thanks for you request.
In our latest release 24.1 you can find the option to configure the passing rate (excluding/including Skipped) for two widgets: 'Passing rate summary' and 'Passing rate per launch'. We also plan to add this functionality to the Component Health Check widgets as well.
Do you need this functionality in some other widgets?
