### ISSUE TITLE
Cannot connect to postgresql from outside of docker container

### ISSUE THREAD

**Issue by erenkurtt** [reportportal/reportportal#2269]
Hello, 

We are using reportportal with our test automation framework and it works like a charm. We need a requirement traceability page where we can observe relations between requirements and test cases. Our requirements are stored in IBM Doors NG and we managed to export requirements. We want to extend reportportal to have a req-trace page where we can import our requirements and match them with the tags in robot test cases (ex: req_1234). We tried to get unique test cases from the postgreSql db of reportportal. Unfortunately we could not access reportportal postgresql database from another pc. We edited the postgresql.conf and pg_hba.conf with
host    all             all             0.0.0.0/0               md5
host    all             all             ::/0                    md5
but it didn't still work. How can we handle this problem? The error is from our backend:
exp log:
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: 'someip',
  port: 5432

Do you have any suggestions to implement such a feature to reportportal? Are we doing this in a right way or trying to connect the database is a thing we should not do?

Reportportal Service Versions: 5.10.0

**Comment by APiankouski** [comment]
If you using docker first that you should do is open the port
just uncomment this lines in docker-compose (by default ports are closed) same for kubernetes
    ports:
     - "5432:5432"
if you already do this or it didn't help the problem may be related to your network limitations
