### ISSUE TITLE
docker-compose.yaml contains the non Latin1 character

### ISSUE THREAD

**Issue by MohitPardeshi** [reportportal/reportportal#2270]
**Describe the bug**
In docker-compose.yaml on line number 291 contains the non latin1 character.
Its giving error while hosting has app service in Azure.
Please remove the character.

**Expected behavior**
docker-compose.yaml should not have not Latin1 characters.

**Screenshots**
  #№ Ref: https://reportportal.io/blog/double-entry-in-5.7.2
<img width="747" alt="image" src="https://github.com/reportportal/reportportal/assets/77525604/d1da97c2-b0b7-4cf6-abaf-30cf9ca8b039">

**Comment by Pink-Bumblebee** [comment]
@MohitPardeshi , thank you for your highlight! We will check and fix this issue.

**Comment by hlebkanonik** [comment]
Thank you! The issue has already been fixed in the [develop](https://github.com/reportportal/reportportal/commit/c0d1332f92667b50c68a464a700500d2819b8bb6) and will be merged into the master in the release.
