### ISSUE TITLE
Report portal Email notification not worked fine

### ISSUE THREAD

**Issue by GayathriGSelvaraj** [reportportal/reportportal#2276]
**Describe the bug**
...

**Expected behavior**
...

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

**Comment by Pink-Bumblebee** [comment]
@GayathriGSelvaraj , maybe you could provide more information?

**Comment by GayathriGSelvaraj** [comment]
@Pink-Bumblebee . It is working fine now, I have changed the docker compose file. Thanks.
