### ISSUE TITLE
robot framework log does not get published on report portal sometime.

### ISSUE THREAD

**Issue by py2206** [reportportal/reportportal#2285]
**Describe the bug**
...
Sometime robot framework logs does not get published in report portal , although the HTML file generated by robot framework shows the api's call done on report portal. 
Even i get the ReportPortal Launch UUID also in logs.
Not sure how to debug this issue. 

**Expected behavior**
Report portal should have all the logs. 

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

**Comment by terminal-illness** [comment]
Any feedback on this? Which is the last working version of reportportal with regards to Robotframework?
