### ISSUE TITLE
Unable to login into report portal UI

### ISSUE THREAD

**Issue by mohaseen-m-ev** [reportportal/reportportal#2286]
**Describe the bug**

Getting 401 Unauthorized when trying to login with superadmin user. It say's logged in successfully but when i check the console and network logs it is saying 401 Unauthorized 
All the images are healthy and up and running
Here is the CPU and RAM memory limits

<img width="952" alt="Screenshot 2024-05-31 at 5 43 10 PM" src="https://github.com/reportportal/reportportal/assets/154952720/4bbb09cd-97ab-412f-bbc5-e607f71d507b">

**Expected behavior**

Earlier i was using linux/amd64(Intel chip MAC) it was working fine with that.
Now i am using linux/arm64(Apple chip MAC) i have added platform: linux/arm64 in all 13 images attached is the compose file

[docker-compose.yml.zip](https://github.com/user-attachments/files/15513403/docker-compose.yml.zip)

**Screenshots**
<img width="1471" alt="Screenshot 2024-05-31 at 5 33 48 PM" src="https://github.com/reportportal/reportportal/assets/154952720/64088e5b-549a-4cdc-afb6-f4da2063c491">
<img width="1728" alt="Screenshot 2024-05-31 at 5 34 05 PM" src="https://github.com/reportportal/reportportal/assets/154952720/a26f867c-5d43-4cb0-9334-102a2c862191">
<img width="1728" alt="Screenshot 2024-05-31 at 5 34 15 PM" src="https://github.com/reportportal/reportportal/assets/154952720/7c3cf09b-e8d9-4308-b8ec-f225ae9cd356">
<img width="1728" alt="Screenshot 2024-05-31 at 5 34 30 PM" src="https://github.com/reportportal/reportportal/assets/154952720/edfc38d3-63f0-414a-aeb2-c33402f1a1a2">

**Versions:**
 - OS, Browser : MAC M3 CHIP, Chrome browser
 - Version of RP 
 
<img width="1728" alt="Screenshot 2024-05-31 at 5 39 47 PM" src="https://github.com/reportportal/reportportal/assets/154952720/d668f256-93f8-462f-ad41-5f9ac644f5e3">

**Comment by Pink-Bumblebee** [comment]
@mohaseen-m-ev , could you please try another browser? (just for interest...)

**Comment by mohaseen-m-ev** [comment]
Yes tried it in FireFox, Safari and chrome incognito but still same.

**Comment by samixchoumi** [comment]
Hello, we have exactly the same issue on both our Mac with an Apple M1 Pro chip.
@mohaseen-m-ev did you make it work ?

**Comment by mohaseen-m-ev** [comment]
No @samixchoumi  It is still not fixed i did tried with linux/amd64 in a Intel chip MAC it is working as expected, I am facing issues only with Apple M1 pro chip(linux/arm64). 
As a work around if you have a windows OS it works fine there as well.

**Comment by samixchoumi** [comment]
Hello, thanks for your answer.

We actually did the same workaround but it could be better to make it works
directly on a M1 chip.
Hope they will fix this issue soon !

**Comment by bybilo78** [comment]
Hi,

I have the same problem, so I can log in as a "default" user, but not as a "superadmin" user. I also get the error message that the login is successful, but when I access the resources I get the error message "403 Forbidden". The installation is with docker-compose on an AWS EC2 instance. In my case it is an Intel Xeon Platinum processor. I don't understand how the problem here can be related to the processor used.

![image](https://github.com/user-attachments/assets/3a988f9b-d5f5-48d6-9017-33fa3e958d76)

**Comment by Pink-Bumblebee** [comment]
@bybilo78 , is database in your case available? Are all services healthy? Please provide results of "docker ps" and log of uat service.

**Comment by bybilo78** [comment]
All services except the gateway service are "healthy". Need the gateway service also the status "healthy"?
![image](https://github.com/user-attachments/assets/d01645c3-d4d2-4dd1-92ce-340fa0005b3c)

Yes, I can access the database via psql, have exposed the port 5432 in the docker-compose.yml.
I will try to get the desired log output from the aws ec2 instance.

**Comment by Pink-Bumblebee** [comment]
@bybilo78 do you have enough resources? RP need at least 8 Gb RAM.
Also sometimes it happens if you removed user with name 'superadmin'

**Comment by bybilo78** [comment]
No, the user "superadmin" exists. I even set the password to the same as the "default" user, just to test it.
![image](https://github.com/user-attachments/assets/a3309048-b636-423c-b393-74dbf0f4584b)

I think, the RAM is enough.
![image](https://github.com/user-attachments/assets/1872a947-b6c0-461e-b86e-0d01dbbeb1c2)

**Comment by bybilo78** [comment]
Any ideas/hints on how I can further analyze the problem? I changed the initial superadmin password in docker-compose.yml before installation. The "default" user can log in, only the "superadmin" user has the problem.

![image](https://github.com/user-attachments/assets/26e5bd83-9d7f-4864-843d-0ce9d41365b5)


I can successfully send test runs via API and also see “launches” in the “default” user.
This shows that the systems are fundamentally working.

**Comment by bybilo78** [comment]
Finally I could solve the problem. In my case, the port 8081 was not reachable from outside the instance (Application Load Balancer). This seems to be mandatory for the superadmin login.
