### ISSUE TITLE
Unable to view logs for some test items

### ISSUE THREAD

**Issue by aliaksandrbasau** [reportportal/reportportal#229]
service-ui 3.1.1
The issue is very similar to #111. 

![image](https://user-images.githubusercontent.com/6681200/29979967-941d3996-8f15-11e7-9588-4f5ba9486814.png)

The log item that that causes the issue is the following:

> {"content":[{"id":"59a98ed8b9d821000734652b","time":1504284376309,"message":"WebBrowserAutomationCore.Exceptions.ScrollIntoViewException: Timed out after 5 seconds: Failed to scroll into view and do Click. ---> OpenQA.Selenium.WebDriverTimeoutException: Timed out after 5 seconds: Failed to scroll into view and do Click. ---> OpenQA.Selenium.WebDriverException: Unexpected error. Element <a data-bind=\"id: $data.id, href: $data.href, css: { 'disabled': !$data.isEnabled() }\" id=\"Dialog_87caa89b732345819e135386f8c78050_autoID3\" href=\"javascript:;\"></a> is not clickable at point (684, 97). Other element would receive the click: <div class=\"toast-message\"></div>

**Comment by evjlobanova** [comment]
@aliaksandrbasau hello, can you update to the latest version, check the issue and share with a results?

**Comment by aliaksandrbasau** [comment]
@evjlobanova I haven't seen the issue for a long time. It's probably resolved. Closing the issue.. Thanks!
