### ISSUE TITLE
Custom name for test

### ISSUE THREAD

**Issue by aDydykBankVostok** [reportportal/reportportal#2298]
Could you please confirm if there is documentation or functionality within your platform that allows setting custom test names independent of file or function names?

I would appreciate any information or recommendations you can provide on this matter.

**Comment by Pink-Bumblebee** [comment]
@aDydykBankVostok , could you please provide some examples?

**Comment by Pink-Bumblebee** [comment]
Since Issuer did not respond I'm closing this issue.
