### ISSUE TITLE
Robot Framework integration

### ISSUE THREAD

**Issue by Tset-Noitamotua** [reportportal/reportportal#23]
You might want to add the greate and mighty test automation framework named Robot Framework[1] to your documentation[2]. Checkout this repo: https://github.com/reportportal/agent-Python-RobotFramework

[1] http://robotframework.org/
[2] http://reportportal.io/#documentation/Test-framework-integration

**Comment by Tset-Noitamotua** [comment]
Just realised that I gave you a link to you own repo :-/  hehehe

Anyway, why don't you mention Robot Framework in your documentation?

**Comment by avarabyeu** [comment]
@Tset-Noitamotua i believe it's just because this agent is still under development and we are not sure it works as a charm :) @ArtsiomYeliseyenka could you please comment on this?

**Comment by DzmitryHumianiuk** [comment]
@Tset-Noitamotua 
we also consider to refactor documentation source strorage in main repository, since now it's not so obvious how to find right .md file for updates in docs.
At the same time with this update - we will update docs for all available and validated integrations.

**Comment by DzmitryHumianiuk** [comment]
refactoring started.
