### ISSUE TITLE
Escaped logs filter term after refresh

### ISSUE THREAD

**Issue by mishaninss** [reportportal/reportportal#230]
1. Apply test logs filter with a term that contains, for example, spaces
2. Refresh a page
3. Your filter term will be escaped, so it cannot be applied correctly
<img width="1242" alt="before_refresh" src="https://user-images.githubusercontent.com/23655435/30032701-11cf8222-91a0-11e7-9200-9cf7f423d322.png">
<img width="1245" alt="after_refresh" src="https://user-images.githubusercontent.com/23655435/30032704-16fb6efa-91a0-11e7-8799-cf618bcd8fb8.png">

**Comment by evjlobanova** [comment]
Hello! Thanks for finding that issue. We fixed this bug, and you will be able to see corrections in the nearest release.
