### ISSUE TITLE
***Assistance Needed :After change password from UI on whicn configuration file (POSTGRES) the password is getting saved ?***

### ISSUE THREAD

**Issue by subha0990** [reportportal/reportportal#2305]
HI Team,

As per this after i change the default password where exactly the update password is getting stored in POSTGRES?
![image](https://github.com/reportportal/reportportal/assets/140379815/cbe47107-846f-42c2-8150-60cbfcb37df3)

Thanks in Adv!!!!!

**Comment by Pink-Bumblebee** [comment]
@subha0990 , it is stored encrypted in 'users' table in postgres.

**Comment by subha0990** [comment]
I have these folder inside Postgres
Let me know under which file i can find it
![image](https://github.com/reportportal/reportportal/assets/140379815/f2bdc4b0-7c92-4f84-ae7c-bdfab11334de)

**Comment by Pink-Bumblebee** [comment]
I do not know : you are showing filesystem, but I meant database itself.You could view it via Dbeaver (for example)

**Comment by subha0990** [comment]
Hi @Pink-Bumblebee , The above-shared screenshot is my Postgres folder. Could you please help me where exactly the updated password from UI is stored?

**Comment by subha0990** [comment]
hi @Pink-Bumblebee , Could u pls help on this !

**Comment by Pink-Bumblebee** [comment]
@subha0990 , actually i do not understand your request. Why you need to find changed file in filesystem? Don't you have availability to connect to database? Could you please explain?

**Comment by subha0990** [comment]
Hi @Pink-Bumblebee , Postgres is the Database folder created. I just want to know where the updated password getting saved in the Postgres  folder . I dont have any external data base connection for the report portal

Thanks in Adv!!

**Comment by subha0990** [comment]
hi @Pink-Bumblebee , Any update on this. Kindly let me know if you want more information from me!!

**Comment by subha0990** [comment]
hi @Pink-Bumblebee & Team, Could you pls help me on this ?

**Comment by Pink-Bumblebee** [comment]
@subha0990 , your question is quite interesting for me as for curious engineer, but, as I think, quite useless from the point of view of ReportPortal. 
Password data is storing in 'users' table in 'reportportal' database. You could investigate it by yourself by comparing files before and after adding new user to ReportPortal.
I'm closing this issue.

**Comment by subha0990** [comment]
Hi @Pink-Bumblebee , Could you pls tell me where i can find the folder "users' table"?

**Comment by subha0990** [comment]
HI @Pink-Bumblebee , I did not get any solution for this. Could u pls have a look on my above query?

**Comment by Pink-Bumblebee** [comment]
@subha0990 , what kind of solution are you expecting for? What is your real issue?
As I said, I do not understand why you need to find exact file in filesystem where superadmin password is stored.
Maybe you want just to change it?

**Comment by subha0990** [comment]
Hi @Pink-Bumblebee , yes, I want to change the password and want to know where exactly it is getting stored. Kindly help with the exact folder where it is getting stored .
