### ISSUE TITLE
Junit-xml report  import get failed  for zero test case in some suite . 

### ISSUE THREAD

**Issue by ChetanKolhe** [reportportal/reportportal#2309]
I am trying import  junit report which contain no test in some test suite . But getting this bellow issue  . As per Junit-xml standard report is correct . 

API : 

command : 

`curl -X POST "http://10.176.106.65:8080/api/v1/greenplum/launch/import" \
     -H "Authorization: Bearer test-key-chetan_LQOqWtgSRNarmD9hpi3HEDyYhY8_avXyR7pyEyXxRg10iL78-1RWea-OHglep9Vh" \
     -H "accept: */*" \
     -F "file=@/Users/ckolhe/workspace/gpdb/gpMgmt/bin/go-tools/report3.xml"`

**output :** 
{"errorCode":40035,"message":"Error while importing the file. 'Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id '945390''"}%  

**File Name :** Users/ckolhe/workspace/gpdb/gpMgmt/bin/go-tools/report3.xml

`<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="0" failures="0" errors="0" time="0.821405">
	<testsuite tests="0" failures="0" time="0.000000" name="github.com/greenplum-db/gpdb/gpservice/cmd/gpservice" timestamp="2024-07-05T15:21:27+05:30">
		<properties>
			<property name="go.version" value="go1.21.5 darwin/amd64"></property>
		</properties>
	</testsuite>
		<testsuite tests="0" failures="0" time="0.504000" name="github.com/greenplum-db/gpdb/gpctl/test/integration/init_cluster" timestamp="2024-07-05T15:26:37+05:30">
		<properties>
			<property name="go.version" value="go1.21.5 darwin/amd64"></property>
		</properties>
		<testcase classname="" name="TestMain" time="0.000000">
			<failure message="Failed" type="">failed to configure the services: , exec: &#34;gpservice&#34;: executable file not found in $PATH&#xA;FAIL&#x9;github.com/greenplum-db/gpdb/gpctl/test/integration/init_cluster&#x9;0.504s&#xA;</failure>
		</testcase>
	</testsuite>
</testsuites>`

From ui also it is reproduce : 

<img width="1792" alt="Screenshot 2024-07-05 at 3 42 32 PM" src="https://github.com/reportportal/reportportal/assets/18587278/582db1de-6ecc-40f8-9e44-82662ec1e740">

 
...

**Expected behavior**
Either It should create a suite with zero test  OR It should be get skip 

...

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

**Comment by Pink-Bumblebee** [comment]
@ChetanKolhe , is it similar with https://github.com/reportportal/reportportal/issues/2245 ?

**Comment by ChetanKolhe** [comment]
Yes , it is exactly same issue . 

`<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="SuiteName" tests="2" failures="1" errors="0" skipped="0">
        <testcase classname="ClassName" name="test1" time="0.1">
            <failure message="failure message">stack trace</failure>
        </testcase>
        <testcase classname="ClassName" name="test2" time="0.2"/>
    </testsuite>
</testsuites>
`

as per junit-report , it is valid one .  So it should be get imported .
Either skipping the empty test , or import should happen with empty test suite with zero test .

**Comment by Kozovskaya** [comment]
@ChetanKolhe 
I will close the issue as duplicate. You can track updates here https://github.com/reportportal/reportportal/issues/2245
