### ISSUE TITLE
Analysis doesn't work

### ISSUE THREAD

**Issue by 132u** [reportportal/reportportal#231]
I set status for some set of tests (please see screenshot run 20), then i run tests again. Click Analysis for last run 21 but statuses are not provided 
![screenshot_1](https://user-images.githubusercontent.com/5435251/30046823-2a2d3a96-9216-11e7-83f8-aafa91aa4f7f.png)

**Comment by evjlobanova** [comment]
Now we are working on improving the function of AA so soon the problem will be solved

**Comment by avarabyeu** [comment]
@132u Unfortunately, it's extremely difficult for us to handle such issues. Could you please provide us with more information? Demo Project or at least your launch structure, logs of items that are not analyzed as expected, etc

**Comment by avarabyeu** [comment]
Since there is no demo project / example and AA is completely re-implemented, closing this issue. Feel free to re-open if any additional actions are required from our side.
