### ISSUE TITLE
Is the AI feature enabled by default?

### ISSUE THREAD

**Issue by thereshimself** [reportportal/reportportal#2313]
Hi ReportPortal team,

I am doing a review of the application for use in my company, Is the AI feature enabled by default, We plan to host the on-prem version and host it on our AWS instance.

**Comment by Kozovskaya** [comment]
Hello @thereshimself 
If under AI you our Auto-Analysis feature based on Machine Learning, then yes the feature is enaled by default.

**Comment by thereshimself** [comment]
Thanks for the reply.

**Comment by Pink-Bumblebee** [comment]
Issuer satisfied - closing issue.
