### ISSUE TITLE
ReportPortal fails to identify retried TestNG tests when class order is changed in XML

### ISSUE THREAD

**Issue by shilgam** [reportportal/reportportal#2316]
Thank you for creating such a promising tool!

## Description
ReportPortal (RP) fails to correctly identify retried tests when the order of test classes in the XML file is changed between the initial run and the retry run.

## Steps to Reproduce
1. Set up ReportPortal as described in the [documentation](https://reportportal.io/docs/developers-guides/RerunDevelopersGuide/#using-agent)
2. Create two TestNG classes: `module1.MyFeatureTest` and `module1.SecondFeatureTest`
3. Create an XML file `suite_classes.xml` with the following content:
   ```xml
   <!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
   <suite name="Demo Suite">
       <test name="Demo Test">
           <classes>
               <class name="module1.MyFeatureTest"/>
               <class name="module1.SecondFeatureTest"/>
           </classes>
       </test>
   </suite>
   ```
4. Run the tests using: 
   ```
   mvn clean test -Dsurefire.suiteXmlFiles=suites/suite_classes.xml
   ```
5. Rerun the tests with: 
   ```
   mvn clean test -Drp.rerun=true -Dsurefire.suiteXmlFiles=suites/suite_classes.xml
   ```
6. Verify that RP correctly recognizes and marks the retried tests:
![RP-handles-retry-correctly](https://github.com/user-attachments/assets/082719d1-cc7a-42bb-b481-eb7aa9c88d31)

7. Create a new XML file `suite_classes_reordered.xml` with the class order reversed:
   ```xml
   <!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
   <suite name="Demo Suite">
       <test name="Demo Test">
           <classes>
               <class name="module1.SecondFeatureTest"/>
               <class name="module1.MyFeatureTest"/>
           </classes>
       </test>
   </suite>
   ```
8. Run the tests again using: 
   ```
   mvn clean test -Drp.rerun=true -Dsurefire.suiteXmlFiles=suites/suite_classes_reordered.xml
   ```

## Expected Behavior
ReportPortal should correctly recognize and mark the retried tests, regardless of the order of classes in the XML file.

## Actual Behavior
ReportPortal fails to recognize the retried tests and instead treats them as a new set of tests:
![RP-unrecognized-retry](https://github.com/user-attachments/assets/dfc87d5d-410c-478f-ab3d-33768147a04c)

## Additional Information
- **A demo project reproducing this issue can be found here:** https://github.com/reportportal/examples-java/pull/79/files
- The issue also occurs when adding or removing test classes from the list during the rerun.
- This problem is not reproducible for Junit5 (verified with [this example](https://github.com/reportportal/examples-java/commit/a3a5eaf3))

## Environment
- RP Listener: agent-java-testng 5.2.2
- RP version: 
  - API Service: 5.11.1
  - Index Service: 5.11.0
  - Jobs Service: 5.11.1
  - Authorization Service: 5.11.1
  - Service UI: 5.11.1
- OS: MacBook Pro 13.4.1
- Browser: Chrome 126.0.6478.63 (Official Build) (arm64)

**Comment by Pink-Bumblebee** [comment]
@shilgam , QA team checked your issue. We need some time to fix this bug.

**Comment by pbortnik** [comment]
Hi @shilgam, 
I've tried to recreate your scenario using the steps you provided and the resulted launch was 'rerun' as expected.
Tried with reordered suites and with deleted suites as well.
Maybe you have any additional conditions for reproducing this bug?

**Comment by Kozovskaya** [comment]
Hello @shilgam 
the fix is done. Please use the latest release https://github.com/reportportal/agent-java-testNG/releases/tag/5.4.3
