### ISSUE TITLE
Seeking Advice on Report Portal Configuration for Monolithic Application

### ISSUE THREAD

**Issue by GianniGiglio** [reportportal/reportportal#2319]
This has been posted on the Report Portal Slack channels, but I didn't get a response back.

---

Hi everyone,

We're currently using Report Portal for logging test results, primarily for our integration and end-to-end tests. Given that we have a very large monolithic application, our tests are launched from a single Jenkins build and then distributed across multiple machines for execution. Once all tests are completed, the launch is closed.

### Goal:
I aim to create a dashboard that tracks launches for a specific branch (main/releases) and displays statistics such as:
- Launch duration
- Overall statistics
- Failed test cases

So far, this setup is working well since we have a single launch for all distributed tests. However, I'm facing challenges with the following:

### Challenge:
I would like to display the health of components based on attributes attached to the test executions. These attributes, representing the teams responsible for the tests, are added at the test level but not at the launcher level. Consequently, they cannot be selected by the health component, which only works with attributes at the launcher level.

Creating separate launchers per team would result in losing critical global statistics like launch duration, overall statistics, and failed test cases.

### Question:
Has anyone encountered a similar use case? How did you manage to achieve the desired results?

Any advice or suggestions would be greatly appreciated!

Thanks in advance,

**Comment by Kozovskaya** [comment]
@GianniGiglio Hello 
have you tried to create a widget Component Health Check? it's built based on the specified test attributes. You will also need to create a filter to specify the launches which will be taken into account. More information about the widget you can read here: https://reportportal.io/docs/dashboards-and-widgets/ComponentHealthCheck

**Comment by GianniGiglio** [comment]
> @GianniGiglio Hello have you tried to create a widget Component Health Check? it's built based on the specified test attributes. You will also need to create a filter to specify the launches which will be taken into account. More information about the widget you can read here: https://reportportal.io/docs/dashboards-and-widgets/ComponentHealthCheck

He @Kozovskaya Yes I have tried that. I tried described the challenge with this in this ticket and why this isn't working. Let me know if I need to clarify my ticket further

Challenge:

I would like to display the health of components based on attributes attached to the test executions. These attributes, representing the teams responsible for the tests, are added at the test level but not at the launcher level. Consequently, they cannot be selected by the health component, which only works with attributes at the launcher level.

Creating separate launchers per team would result in losing critical global statistics like launch duration, overall statistics, and failed test cases.

**Comment by GianniGiglio** [comment]
@Kozovskaya Any update on this?

**Comment by Kozovskaya** [comment]
@GianniGiglio Hello
why the Component Health Check doesn't work for you?
you filter needed launches. For the level 1 you provide team attribute (ex. Level 1 - team, but it means that your tests need to have attributes like team: abc, team:def etc.).
The widget will group all the test with team: abc and team:def separately. And you will see the statistics for each group.

**Comment by GianniGiglio** [comment]
@Kozovskaya, it seems there might be a bug. The issue I’m describing is that when using a single launcher, it’s not possible to filter on attributes that are only added at the test level.

**Comment by Kozovskaya** [comment]
Here is cthe screenshot how I think you need to create a widget Component Health Check.
Have you tried to configure widget this way?
![image](https://github.com/user-attachments/assets/c9e5c75e-7c3a-40a6-a484-5da9cedbfd74)
