### ISSUE TITLE
As an RP user in case of several issue sub-types configured on server, for 'Launch statistics trend chart' and 'Launch statistics line chart' I want be able to see summary information for all 'Automation bugs', 'Product bugs' etc.

### ISSUE THREAD

**Issue by doctordrue** [reportportal/reportportal#232]
## Configuration
Several amount of custom defect types configured for each group, like e.g.:
![image](https://user-images.githubusercontent.com/16087661/30201839-d99428ee-9484-11e7-8b22-d6ed148bb54d.png)

## Current behavior
Currently when you're configuring such widget you able only to display separate regions for each sub-type of issue:
![image](https://user-images.githubusercontent.com/16087661/30202096-d9e1f1ae-9485-11e7-97b6-a3b496c6a435.png)
So the graph looks like a kind of mess:
![image](https://user-images.githubusercontent.com/16087661/30202272-79e9c32a-9486-11e7-9d71-c549b77d0ce7.png)

## Expected behavior
As RP user I want to see summary values for each defect type group on 'Launch statistics trend chart' and 'Launch statistics line chart' graphs, so I want to see regions for 'Number of passed tests', 'Number of tests failed or skipped due to Product bugs of any type', 'Number of test failed or skipped due to Automation bugs of any type', 'Number of tests failed or skipped due to System issues of any type', 'Number of test failures or skips marked as any type of No defect group', like in case we don't have sub-types configured.

**Comment by Iren-Melnyk** [comment]
It's a very good point. We will make some improvements to these widgets.

**Comment by DzmitryHumianiuk** [comment]
work in progress
