### ISSUE TITLE
How can I import junit XML to report portal for an existing launch?

### ISSUE THREAD

**Issue by Saatvik-droid** [reportportal/reportportal#2323]
**Is your feature request related to a problem? Please describe.**
...
I can start a launch using the API, but once my tests are completed I want to end and import the generated junit XML files into report portal. as of now I can use an API to import but it creates a seperate launch whereas I want to do it for the same launch Id

**Comment by Kozovskaya** [comment]
Hello @Saatvik-droid 
could you please clarify your use case? Why don't you work with executed launch and what is the point to import the same launch?
are they differ somehow?

**Comment by Saatvik-droid** [comment]
Hi, thanks for the response.

To set the context, we start a launch using the API which may then be utilised under some use cases and upon completion of execution of tests I want to update the launch with the results using a junit XML. I tried looking at the import API but unfortunately it doesn't seem to support an import to an existing launch and creates a new one each time which means the launch that was started before doesn't have the results. Starting the launch at first is a given for our use case so I was looking for any way to update it with the results through junit.

Thanks

**Comment by Pink-Bumblebee** [comment]
@Saatvik-droid , how about start and finish launch, then import file, then merge both launches?

**Comment by Saatvik-droid** [comment]
Great tip, will look into how it works for my use case and get back if it's satisfactory. 

Thank you

**Comment by Pink-Bumblebee** [comment]
Hello @Saatvik-droid , have you had a chance to check my proposed variant?

**Comment by Saatvik-droid** [comment]
Hi, yes I tried out your method and it worked but turns out deleting a launch and just using the new launch works for us. Thanks for the tip though, it would've also worked.
