### ISSUE TITLE
Launch attribute is not displaying the full HTTP URL under launch name column.

### ISSUE THREAD

**Issue by gopinathbg** [reportportal/reportportal#2324]
**Describe the bug**
The launch attribute does not display the full HTTP URL under the launch name column. It truncates all characters after `https`
**Expected behavior**
The launch should show the full HTTP URL in the launch attribute under the launch name column.

**Screenshots**
<img width="273" alt="image" src="https://github.com/user-attachments/assets/4dd70b5f-3abf-4c34-948a-82baef8a5149">

**Versions:**
 - Windows 11, Google Chrome 127.0.6533.119
 - 5.11.0

**Comment by Pink-Bumblebee** [comment]
@gopinathbg , it is not a bug. It Please take a look to https://github.com/reportportal/reportportal/issues/2254

**Comment by DzmitryHumianiuk** [comment]
works as desinged:
https://reportportal.io/docs/work-with-reports/LaunchesTestItemsAttributes/#colon-scenarios
