### ISSUE TITLE
Authorization and API services are not starting in Docker installation

### ISSUE THREAD

**Issue by 501NotImplemented** [reportportal/reportportal#2326]
Hi. I'm trying to perform a Docker installation of ReportPortal using docker compose (see file attached). I'm going for the installation with the database on the separate VM.
![19 08 2024_15 32 30_REC](https://github.com/user-attachments/assets/9e7fb6f8-4e1e-41df-9b42-2d9925ee2287)
![19 08 2024_15 45 35_REC](https://github.com/user-attachments/assets/671d74d7-1366-41d7-a5f1-4d3f2cbc22d8)
![19 08 2024_15 33 22_REC](https://github.com/user-attachments/assets/8a015a96-d4f9-4a2e-846d-676f8c13c7ec)

After I've recreated the containers via sudo docker-compose -p reportportal up -d --force-recreate, the API and authorization services are not started. The UI is stuck on 'Loading...'.
From the docker logs of the service containers I see the Java bin exceptions. Any ideas how to fix that?

[api_service_log.txt](https://github.com/user-attachments/files/16660382/api_service_log.txt)
[authorization_service_log.txt](https://github.com/user-attachments/files/16660383/authorization_service_log.txt)
[docker-compose.txt](https://github.com/user-attachments/files/16660386/docker-compose.txt)

**Comment by Pink-Bumblebee** [comment]
@501NotImplemented , as I see in your docker-compose file, you are trying internal setup (not external on the separate instance) of Postgres. Also, you added a lot of parameters into command subsection of postgres service. If you are just trying to deploy ReportPortal for the first time, why don't you try to start it with default settings, that are included into default initial docker-compose file? https://github.com/reportportal/reportportal/blob/master/docker-compose.yml

**Comment by 501NotImplemented** [comment]
@Pink-Bumblebee could you please point me to where I should correct the database settings so it would be pointed to external db?

The reason why I'm starting such a configuration is the predicted test load, we have thousands of tests on different test levels, so according to the documentation, separating the db from the app makes sense for performance reasons. As I understand, there would be no other way to reconfigure the database later, only in the docker-compose of the initial installation. Am I right?

**Comment by Pink-Bumblebee** [comment]
@501NotImplemented , sorry, I couldn't catch your idea about database reconfiguration. 
Let's imagine that you have External Postgres and will create Internal Postgres during ReportPortal installation.
If you will install and use successfully ReportPortal with Internal Postgres, you are always available to migrate you Database from Internal to External Postgres. After that you will be need to change settings in docker-compose.yml and  _sudo docker-compose -p reportportal up -d --force-recreate_ . 
As I see in docker-compose file, we have services api, uat & jobs, that needs to define following parameters:
RP_DB_HOST:
RP_DB_USER: 
RP_DB_PASS: 
RP_DB_NAME: 

Also you need to define for metrics-gatherer, migrations  parameters that starts from POSTGRES
POSTGRES_SERVER:
POSTGRES_DB: 
POSTGRES_USER: 
POSTGRES_PASSWORD: 

POSTGRES_HOST: 
POSTGRES_PORT:

**Comment by 501NotImplemented** [comment]
Thanks. That makes sense. By following the steps in Docker [installation guide](https://reportportal.io/docs/installation-steps/DeployWithDocker/), using the default settings from docker-compose, I see that the RabbitMQ analyzer vhost is not created by default from the docker logs. Same with the database access, PostGres is not healty. These steps and permissions have to be resolved manually, e.g I hade to manually create a vhost on a RabbitMQ container and add rabbitMq user appropriate permissions to access it.

```
sudo docker exec -it <rabbitMQcontainerID> /bin/bash
rabbitmqctl add_vhost analyzer
```

After that I see user permission errors

`2024-08-19 14:14:37.932460+00:00 [info] <0.7458.0> closing AMQP connection <0.7458.0> (172.18.0.11:53228 -> 172.18.0.2:5672, vhost: 'none', user: 'rabbitmq')
2024-08-19 14:14:38.236222+00:00 [info] <0.7466.0> accepting AMQP connection <0.7466.0> (172.18.0.11:53244 -> 172.18.0.2:5672)
2024-08-19 14:14:38.238014+00:00 [error] <0.7466.0> Error on AMQP connection <0.7466.0> (172.18.0.11:53244 -> 172.18.0.2:5672, user: 'rabbitmq', state: opening):
2024-08-19 14:14:38.238014+00:00 [error] <0.7466.0> access to vhost 'analyzer' refused for user 'rabbitmq'
2024-08-19 14:14:38.238437+00:00 [info] <0.7466.0> closing AMQP connection <0.7466.0> (172.18.0.11:53244 -> 172.18.0.2:5672, vhost: 'none', user: 'rabbitmq')
2024-08-19 14:14:38.291858+00:00 [info] <0.7474.0> accepting AMQP connection <0.7474.0> (172.18.0.11:53258 -> 172.18.0.2:5672)
2024-08-19 14:14:38.293930+00:00 [error] <0.7474.0> Error on AMQP connection <0.7474.0> (172.18.0.11:53258 -> 172.18.0.2:5672, user: 'rabbitmq', state: opening):
2024-08-19 14:14:38.293930+00:00 [error] <0.7474.0> access to vhost 'analyzer' refused for user 'rabbitmq'
2024-08-19 14:14:38.294412+00:00 [info] <0.7474.0> closing AMQP connection <0.7474.0> (172.18.0.11:53258 -> 172.18.0.2:5672, vhost: 'none', user: 'rabbitmq')
`
That were resolved by these commands:
```
sudo docker exec -it reportportal-rabbitmq-1 rabbitmq-plugins enable rabbitmq_management
sudo docker exec -it reportportal-rabbitmq-1 rabbitmqctl set_permissions -p analyzer rabbitmq ".*" ".*" ".*"
```

Is anything missing in the installation process guide?

![19 08 2024_16 59 43_REC](https://github.com/user-attachments/assets/7f900df2-12a6-4361-b735-965c0e4828af)
[service-auto-analyzer.txt](https://github.com/user-attachments/files/16661257/service-auto-analyzer.txt)
[service-metrics-gatherer.log](https://github.com/user-attachments/files/16661269/service-metrics-gatherer.log)

**Comment by Pink-Bumblebee** [comment]
@501NotImplemented , may I ask you what is your environment? Maybe you are trying to install ReportPortal without root permissions. Or trying to install on Apple Mac with M processor.

**Comment by 501NotImplemented** [comment]
@Pink-Bumblebee I'm installing it on a VM with Rocky Linux OS. All of the commands were executed as a _sudo_. Please let me know if I can help with any other details.

**Comment by Pink-Bumblebee** [comment]
@501NotImplemented , finally I've succeeded to install Rocky Linux to VM and tried to install reportportal using https://github.com/reportportal/reportportal/blob/master/docker-compose.yml. In my particular case everything is working. 
May I ask you: is your issue still actual for now?

**Comment by 501NotImplemented** [comment]
@Pink-Bumblebee sorry for the late reply. The issue is resolved at the moment. I've asked another user to rerun the docker-compose, and the required steps were completed. The root cause is definitely in the user permissions, however, I don't have any exact details, unfortunately. Closing the issue as it is resolved.
