### ISSUE TITLE
"Latest Launches" Option in Widget Displays Same Data as "All launches" Option

### ISSUE THREAD

**Issue by Priyanshu19992002** [reportportal/reportportal#2329]
**Describe the bug**
- The option of **Latest Launches** in various widgets like **Overall Statistics**, **Component Health Check**, **Component Health Check (Table view)**, **Launches Duration Chart** etc. is expected to show data specifically for the most recent launches. However, I have noticed that it is displaying the same information as the **All Launches** option in the widget, making it difficult to get latest execution visualised on RP. 

**Steps to Reproduce**
- Integrate the Serenity Framework with serenity-reportportal-integration agent v1.5.7
- Ingest multiple launches into ReportPortal.
- Create a Dashboard and filter for these launches to be displayed in ReportPortal
- Go to the dashboard in ReportPortal.
- Add a widget that can display data for both **All Launches** and **Latest Launches**.
- Configure the widget to show data for **Latest Launches**.
- Add the same widget above but now configure the widget to show data for **All Launches**.
- Observe the data displayed in the widget for both **All Launches** and **Latest Launches**.

**Expected behavior**
- The **Latest Launches** configured widget should show data only for the most recent launches, distinct from the **All Launches** widget.

**Screenshots**
- Below screenshot (for RP v24.1) is for widget **Overall Statistics** but the behaviour is observed in all the widgets (which can be configured to show latest launches)

- This shows two launches ingested in RP
<img width="1381" alt="Screenshot 2024-08-20 at 5 43 59 PM" src="https://github.com/user-attachments/assets/057b3cad-0750-4a71-92bf-1722cff221e6">

- This shows "Overall Statistics" widget with comparision of **All Launches** and **Latest Launches** showing same number but it should show for **All Launches** = 2 Test and for **Latest Launches** = 1 Test.
<img width="1370" alt="Screenshot 2024-08-20 at 6 20 21 PM" src="https://github.com/user-attachments/assets/00fff8cd-75d2-4b72-bc8e-23166181e298">

- This is the filter used in the above widget.
<img width="1370" alt="Screenshot 2024-08-20 at 5 47 23 PM" src="https://github.com/user-attachments/assets/39aecece-5dda-4670-9857-27ddc202e4e8">

**Versions:**
Two versions were tested
```
 - OS = RHEL 8
 - Version of RP = API Service: 5.10.1;Index Service: 5.10.0;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0;
 - Browser: Chrome v127.0.6533.120
 - RP Agent = serenity-reportportal-integration (v1.5.7)
 ```

```
- OS = macOS Sonoma 14.2.1
- Browser: Chrome v127.0.6533.120
- Version of RP = v24.1
- RP Agent = serenity-reportportal-integration (v1.5.7)
 ```

**Comment by Pink-Bumblebee** [comment]
@Priyanshu19992002 , may I ask you to do the same check at demo.reportportal.io ?
Also, please read this article about latest launches : https://reportportal.io/docs/dashboards-and-widgets/ComponentHealthCheck/ 
I see there : 
```
**‘LATEST LAUNCH’ option**

For the first level, the flow is almost the same as for the ‘ALL LANCHES’ option. However, after the test cases are grouped around unique values for the attribute key, system only leaves the tests cases from latest launches executions for each selection. For example, if you have Launch A with executions #1 and #2 and Launch B with executions #1 and #2 and they correspond to the applied filter, then building the widget based on “LATEST LAUNCHES’ parameter will take into account only the test cases from Launch A executions #2 and Launch B executions #2.
```

**Comment by Priyanshu19992002** [comment]
Hi @Pink-Bumblebee ,

Thanks for replying. I understood that the behaviour of component health checks widget starts with the launch name, it will group all diff launches (on the basis of their name) into separate groups like Group 1 = Launch A, Group 2 = Launch B , Group 3 = Launch C and so on... and then if we select latest launches option then it will pick the latest launch of all the groups and accumulate them and show it on the widget.

I have few more questions on the basis of above understanding: 
- Is the above behaviour same for all the widgets with option **Latest Launches** and **All Launches**? 
- Let say we have a set of launches in a filter having different launch names for example let say filter name be **Healthcheck** having launches with name **Healthcheck_08/10**, **Healthcheck_08/11**, **Healthcheck_08/12**. Now i want to visualise the latest execution from this filter which will be launch **Healthcheck_08/12** on a widget take component health check widget for now then how to get this desired outcome because when i select **Latest Launches** option on "component health check" widget it accumulate all the latest launches with diff names opposite to what i was expecting. Can u help me with this implementation suggestion? I don't want to change the launch name as i also want a cumulative trend chart widget for this filter where it will show me the trend for my healthcheck executions so if i change my launch name to some static name then as per the implementation of cumulative trend chart widget (in RP docs) i won't be able to visualise the history launches.

**Comment by Pink-Bumblebee** [comment]
@Priyanshu19992002 , if I understood you correctly, you could add one more filter **Healthcheck_08/12**  and create one more widget for it.

**Comment by Priyanshu19992002** [comment]
@Pink-Bumblebee, Let me present it more concisely:

There are three launches in RP with name as below:
1. Healthcheck_08/10
2. Healthcheck_08/11
3. Healthcheck_08/12

Similarly there will be more launches following the above launch name pattern but for now let us consider these 3 launches with latest launch be **Healthcheck_08/12**.

Now, I am creating one filter with name **Healthcheck** which will have all the three launches mentioned above.

Now let say there are two use cases with the above launches for visualization:
- First, I want a trend for all the Healthcheck launches i.e. it should show all the launches present in **Healthcheck** filter. For this, I will use "Cumulative trend chart" widget with filter **Healthcheck** which will be appropriate for this use case.

- Second, I want to show the **latest launch** execution components health, for this component health check widget would be the most appropriate one. So if i take my above example and then my requirement then in the component health check widget it should show only the component of launch **Healthcheck_08/12** but this is not the case. It is combining all the launches **Healthcheck_08/10**, **Healthcheck_08/11**, **Healthcheck_08/12** and then showing which is correct as per the documentation. **So, I want to know if my use case of showing the latest launch in above scenario is possible in ReportPortal or not?**If yes then how.

Hope it was more clear to you this time.

**Comment by Kozovskaya** [comment]
@Priyanshu19992002 Hello
The current behavior of the widget is expected as for ReportPortal launches Healthcheck_08/12, Healthcheck_08/10, Healthcheck_08/11 are different launches. 
When we talk about latest execution we mean the following:
Launch with name 'Healthcheck_08/12' was executed several times and in ReportPortal is displayed as
Healthcheck_08/12 `#1` 
Healthcheck_08/12 `#2` 
Healthcheck_08/12 `#3` - this is the last execution.
For the launch Healthcheck_08/10
Healthcheck_08/10
Healthcheck_08/10
Healthcheck_08/10

**Comment by Kozovskaya** [comment]
If you want ReportPortal to work as if this is the same launch - make a unique launch name (ex. Healthcheck) and such things as 08/12... etc. put either in attributes or in description
![image](https://github.com/user-attachments/assets/511976cb-63fd-43c8-8441-cf00f3fe76c9)
