### ISSUE TITLE
As an RP user I want to have 'Copy Link' button on pages to be able to copy direct short link to page (launch, lunch item etc.) to use it in e.g. JIRA

### ISSUE THREAD

**Issue by doctordrue** [reportportal/reportportal#233]
The thing is that current links if you copy them from the browser's address line have '|' symbols and due to that fact they which can't be properly parsed as URLs by JIRA

**Comment by avarabyeu** [comment]
Please, add:
1. Copy link
2. Copy as cURL
3. Copy as httpie

https://github.com/curl/curl
http://httpie.org

Copied URL should (NOT?) contain UI access token?

**Comment by e-olga** [comment]
Hi @doctordrue, 
Could you please specify which browser you use.
Thanks

**Comment by DzmitryHumianiuk** [comment]
@doctordrue up

**Comment by doctordrue** [comment]
Hi, @e-olga 
We are experiencing the same issue using either Firefox or Chrome

**Comment by evjlobanova** [comment]
@doctordrue the fix will be in 4.0. 
We removed "|" , so a link will be working correctly for Google Chrome, Mozilla Firefox browsers.  But there is some problems with an Edge browser. So is it enough for you?

**Comment by doctordrue** [comment]
@evjlobanova  Yes, this is enough. Another point is that links, copied from the browser's address bar contains issue.type filter, so if you put such a link to JIRA before changing Issue Type you will have wrong link after choosing Issue Type. Has this been this fixed too?

**Comment by evjlobanova** [comment]
@doctordrue  you can move to the log view through the launch structure (launch> suite> test> step> log), so you will get a link without issue.type filter, and the defect type change will not influence on working capacity of the already copied link. But I assume in a case that you described you move through statistics that is why a link  is being increased by  the filter.
