### ISSUE TITLE
Not able to see some of the tests when queried using the api  api/v1/<project name>/item?filter.eq.launchId=<id>

### ISSUE THREAD

**Issue by saiaprameya** [reportportal/reportportal#2334]
**Describe the bug**
We have test suite run in parallel. So while executing we add the suites and then the testcases under the suites as children.

When we query for e.g:

http://<ip>:8080/api/v1/<project name>/item?filter.eq.launchId=<id>

It gives output and when we check for the test name i dont see them present with the api but i do see them in the launch present.

So the api is not giving proper output.

I do see the suite saying it has children but i dont see them.

e.g:
NON WORKING CASE:
===================
   {
      "id": 921783,
      "uuid": "41614c21-def8-4f1a-8c5c-66264472b61b",
      "name": "GUI_User_Settings",
      "description": ....>SUITE CLEANUP</a>",
      "parameters": [],
      "attributes": [
        {
          "key": "project",
          "value": "rapid-production-sanity"
        },
        {
          "key": "week",
          "value": "35"
        },
        {
          "key": "run_reason",
          "value": "sanity"
        },
        {
          "key": "region",
          "value": "None"
        },
        {
          "key": "job",
          "value": "None_RAPID_GUI_SANITY"
        },
        {
          "key": "feature",
          "value": "GUI"
        },
        {
          "key": "testbed",
          "value": "['5_2', '6_1']"
        },
        {
          "key": "build_string",
          "value": "08-29-24_gui_sanity_Production-Rapid"
        },
        {
          "key": "date",
          "value": "08-29-24"
        },
        {
          "key": "cloud",
          "value": "Production-Rapid"
        },
        {
          "key": "year",
          "value": "2024"
        }
      ],
      "type": "STEP",
      "startTime": 1724958316531,
      "endTime": 1724958401917,
      "status": "PASSED",
      "statistics": {
        "executions": {
          "total": 1,
          "passed": 1
        },
        "defects": {}
      },
      "pathNames": {
        "launchPathName": {
          "name": "None_RAPID_GUI_SANITY",
          "number": 14
        }
      },
      "hasChildren": true,
      "hasStats": true,
      "launchId": 3934,
      "uniqueId": "auto:58b08cbed5442798140c38d4724253e8",
      "testCaseHash": -1415641477,
      "patternTemplates": [],
      "path": "921783"                     >>>>>>>>>>>>>>>>>>>>>>>>> i dont see the children here
    },

Working case of other suite:
======================
    {
      "id": 921793,
      "uuid": "d69a6167-d0e1-49f9-99ea-ce930bfe9620",
      "name": "create_policy_profile",
      "description": "....test Report</a>",
      "parameters": [],
      "attributes": [
        {
          "key": "project",
          "value": "rapid-production-sanity"
        },
        {
          "key": "week",
          "value": "35"
        },
        {
          "key": "run_reason",
          "value": "sanity"
        },
        {
          "key": "region",
          "value": "None"
        },
        {
          "key": "job",
          "value": "None_RAPID_GUI_SANITY"
        },
        {
          "key": "feature",
          "value": "GUI"
        },
        {
          "key": "testbed",
          "value": "['c240m5_2', 'c240m6_1']"
        },
        {
          "key": "build_string",
          "value": "08-29-24_gui_sanity_Production-Rapid"
        },
        {
          "key": "date",
          "value": "08-29-24"
        },
        {
          "key": "cloud",
          "value": "Production-Rapid"
        },
        {
          "key": "year",
          "value": "2024"
        }
      ],
      "type": "STEP",
      "startTime": 1724958317757,
      "endTime": 1724958677151,
      "status": "FAILED",
      "statistics": {
        "executions": {
          "total": 1,
          "failed": 1
        },
        "defects": {
          "to_investigate": {
            "total": 1,
            "ti001": 1
          }
        }
      },
      "parent": 921781,
      "pathNames": {
        "launchPathName": {
          "name": "None_RAPID_GUI_SANITY",
          "number": 14
        },
        "itemPaths": [
          {
            "id": 921781,
            "name": "create_profile"
          }
        ]
      },
      "issue": {
        "issueType": "ti001",
        "autoAnalyzed": false,
        "ignoreAnalyzer": false,
        "externalSystemIssues": []
      },
      "hasChildren": false,
      "hasStats": true,
      "launchId": 3934,
      "uniqueId": "auto:b6a38959c4414e1fb83e68eeeb880c70",
      "testCaseHash": 149558059,
      "patternTemplates": [],
      "path": "921781.921793"
    },

**Expected behavior**

Should provide all the suites and tests that are present through API but its not giving.

**Screenshots**
If applicable

**Versions:**
 - OS, Browser  UBUNTU 22.04
 - Version of RP [find it under Login form, copy as is] 
    5.6.0

**Comment by mbryl6** [comment]
Hello @saiaprameya,
The team is experiencing difficulties in reproducing this issue. Could you please share the exact steps you follow to get it reproduced?

**Comment by saiaprameya** [comment]
@mbryl6 i was able to get the details it was just a simple problem with the page size.
i thought that when we dont define the page size it would default to all. But that's not the case.
so had to set the page size to get all the details.
