### ISSUE TITLE
ZIP file import does not import as expected

### ISSUE THREAD

**Issue by AaronMT** [reportportal/reportportal#2336]
I have a zip-file (`*.zip`) containing ~80 XML JUnit reports. When I click `Import` on the Launches view and drag and drop the `zip` file, and hit OK, it imports a single launch containing nothing inside (i.e, no results).

If I manually drag and drop all ~80 XML JUnit reports into the window, it will parse and import them all as expected. 

Currently using `5.11.1` on a new Google Cloud Marketplace deploy.

Attached is the (`*.zip`) if you would like to try out out ~`305KB`. 
[junit-xml-reports.zip](https://github.com/user-attachments/files/16852706/junit-xml-reports.zip)

Similarly, I see the same issue if I try an import via API on command-line.

Not sure if there's logs somewhere through the app or Google Cloud I can provide here?

**Comment by Pink-Bumblebee** [comment]
@AaronMT , your sample file is zip-in-zip. Are you trying to import it? 
I've tried to import junit-xml-reports.zip and also get single empty launch.
I unzipped junit-xml-reports.zip to FullJunitXmlReports_20240903_172801.zip and successfully imported it.

**Comment by AaronMT** [comment]
Oh interesting, MacOS didn't make that obvious for me as the double inflation happens behind the scenes when you uncompress in Finder. I am using GitHub Actions artifact storing and it's zipping twice there. Thanks, I'll double check that Import now works and close this out.
