### ISSUE TITLE
Question: How do one use the feature filter in url parameter

### ISSUE THREAD

**Issue by svallebro** [reportportal/reportportal#2339]
#308 This seems like a good feature.
But where can I find any docs on how it works?

I was trying this feature out and I could not understand how to use it.
This is my attempt:
http://localhost:8080/ui/#test_project/launches/all?filter.cnt.name=testname

And I like all launces with 'testname' in the name

Running on 24.1 release

**Comment by Pink-Bumblebee** [comment]
@svallebro , that's a good question. We will include it into our documentation update backlog.

**Comment by alena-babrova** [comment]
Hello @svallebro,

Sorry for not providing proper documentation on this. 
For now, it works using the `launchesParams` parameter. 
Example: /ui/#project/launches/all?**launchesParams=filter.cnt.name%3Ddemo**
where `launchesParams` parameter contains filtering options in format `<filter_type>=<value>` and should be URL encoded.

**Comment by svallebro** [comment]
@alena-babrova Amazing! Thank you!

This seems to work like a charm.
Feel free to close or keep this until the documentation is updated

I'm satisfied with the answer above.
