### ISSUE TITLE
Remove dashboard number limit

### ISSUE THREAD

**Issue by oscarcenteno** [reportportal/reportportal#2344]
**Describe the solution you'd like**
There is a dashboard limit of 300. In our current automation project, we create dashboards automatically (API) to show different suites running as part of the same pipeline. The limit of 300 requires the maintenance of manually deleting dashboards, but this is cumbersome and shouldn't be needed. Also, it is not good for the image of ReportPortal in front of our client, as we will do a hand-over in a few months.

**Is your feature request related to a problem? Please describe.**
API throws this error when trying to create dashboard #301:

"Dashboard update request contains invalid data. The limit of 300 dashboards has been reached. To create a new one you need to delete at least one created previously."

**Comment by Kozovskaya** [comment]
Hello @oscarcenteno 
In our nearest release the number of dashboards per project will be increased up to 3000.

**Comment by Kozovskaya** [comment]
Duplicates #2168
