### ISSUE TITLE
Junit 4 integration not working.

### ISSUE THREAD

**Issue by ssam921** [reportportal/reportportal#2345]
Hi Team, 
I am trying to integrate Junit4 with reportportal. But doesnt seem to be working.

Steps :
 1. pom.xml updated with the following
```
 `    <!-- ReportPortal agent for JUnit 4 -->
    <dependency>
      <groupId>com.epam.reportportal</groupId>
      <artifactId>agent-java-junit</artifactId>
      <version>5.2.3</version>
    </dependency>

    <!-- ReportPortal logger integration (optional) -->
    <dependency>
      <groupId>com.epam.reportportal</groupId>
      <artifactId>logger-java-logback</artifactId>
      <version>5.2.2</version>
    </dependency>

        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.1.1</version>
        <executions>
          <execution>
            <id>getClasspathFilenames</id>
            <goals>
              <goal>properties</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.22.0</version>
        <configuration>
          <argLine>-javaagent:${com.nordstrom.tools:junit-foundation:jar}</argLine>
        </configuration>
      </plugin>
```
`
2.  Added the below
<img width="458" alt="image" src="https://github.com/user-attachments/assets/ff3936f3-4a77-45a6-8578-e54a58597782">
3. Added reporportal.properties and junit-platform.properties> under src.main.test.resources.

Can someone please help.

**Comment by Pink-Bumblebee** [comment]
Hello @ssam921 , just for interest,  have you tried to integrate according to https://github.com/reportportal/logger-java-log4j/blob/master/README.md ?

**Comment by ssam921** [comment]
Tried this too. but not working. I have successfully done junit5 bt junit4 is facing issues. have you tried with junit4?

**Comment by Pink-Bumblebee** [comment]
No, sorry. It is not my area. But I just compared pom.xml readme with your pom.xml and found that you are trying to use logger-java-logback insted of logger-java-log4j

**Comment by ssam921** [comment]
For someone looking 
https://github.com/reportportal/examples-java this is a working example with Junit4.
