### ISSUE TITLE
Aren't the test cases summarized based on the test case ID?

### ISSUE THREAD

**Issue by bybilo78** [reportportal/reportportal#2347]
I have 3 different testruns as follows:

- Web Smoke Test = 5 tests
- Web Regression = 60 tests
- Web Public Regression = 14 tests

All test cases have a UUID as the testcase id, so they are unique.

The 'Web Smoke Test' testrun contains 3 tests, which are also in the 'Web Regression' testrun.

In the widget I now see a total of 79 testcases instead of the 76 testcases I had hoped. 
Are the testcases not accumulated based on the testcase id?

![image](https://github.com/user-attachments/assets/57906c3a-989b-42c3-ba36-0b25e9110e23)

**Comment by ninamazurenka** [comment]
Hi @bybilo78!  Could you please tell me, do the test cases have the same testcase id in different test runs?

**Comment by bybilo78** [comment]
Hi @ninamazurenka, 3 testcases are in 2 different test runs and have the same testcase ids.

**Comment by ninamazurenka** [comment]
Dear @bybilo78,
could you please attach screenshots of two test cases with the same testcase ids, where testcase ids will be visible in Browser Devtools, so that we can investigate your problem?

**Comment by bybilo78** [comment]
Hi @ninamazurenka, 

apparently I misunderstood the concept. 

I have test runs with the same launch name "Portal Tests". The test cases are always different, and some tests are identical. Depending on how I set the launch type in the widget, all test cases are displayed in total for "All Launches", even if the same test occurs multiple times in different launches. For "Latest Launches" only the last launch is displayed; the previous test cases no longer appear in the widget.

My assumption that test cases with the same test case ID are combined here does not apply here either, even if I only execute all test cases in one launch.

**Comment by bybilo78** [comment]
Ticket can be closed, we have now a workflow to send all related tests into the same launch execution.
Summarize is than no problem in this contellation.
