### ISSUE TITLE
cannot pass dynamic value to the report portal properties file. 

### ISSUE THREAD

**Issue by Gayathrigayu121** [reportportal/reportportal#2350]
rp.launch = ${launchName}
#rp.project = urbansdk_ui_automation
rp.project = ${projectName}
rp.description = UrbanSDK Functional Test
#rp.attributes = Browser:chrome
rp.attributes = Browser:${browserName}

**Comment by Gayathrigayu121** [comment]
If padd dynamic value using java properties.setproperty it does not connect with report portal

**Comment by Pink-Bumblebee** [comment]
@Gayathrigayu121 , could you please explain your issue more detailly step by step?

**Comment by Gayathrigayu121** [comment]
@Pink-Bumblebee ,
I'm trying to run parallel executions using different browsers—Chrome, Edge, and Firefox—and I've created separate projects in ReportPortal. However, in the TestNG file, the listeners are set at the suite level. As a result, when I run the tests in parallel, ReportPortal reflects the results in a single project for all browsers instead of showing the impact on each individual project.

how to run parallel execution using playwright Java TestNG

**Comment by Pink-Bumblebee** [comment]
@Gayathrigayu121 , I think it is not possible. Please read https://github.com/reportportal/client-java?tab=readme-ov-file#jvm-based-clients-configuration .
