### ISSUE TITLE
Passing rate per launch widget - unable to ignore skipped

### ISSUE THREAD

**Issue by mortenb-buypass** [reportportal/reportportal#2352]
**Describe the bug**
In passing rate per launch widget, there is no way to ignore skipped they always show up as failed,

**Expected behavior**
This is a bug skipped tests in any other test reporting framework just ignore them.

If not they should have another color like yellow

**Screenshots**
![bilde](https://github.com/user-attachments/assets/be4c2753-acc4-45df-9397-80f63ce218f3)

But in launch statistics widget we can ignore it:
![bilde](https://github.com/user-attachments/assets/a8014cf4-6bc7-41c2-8c5e-761351fb104d)

**Versions:**
 - OS, Browser, linux ubuntu22.04LTS, chrome v130, firefox v131
 - Version of RP [find it under Login form, copy as is]
 Build: 5.10.0
© Report Portal 2024 All rights reserved

**Comment by mortenb-buypass** [comment]
seems like this is in v24.1, I'll bug my sysadmins to update. 
https://github.com/reportportal/reportportal/issues/2267

**Comment by Kozovskaya** [comment]
Hello @mortenb-buypass,
Yes, the option was alredy added in previous release!

**Comment by Kozovskaya** [comment]
Here you can find the updated documentation on the widget https://reportportal.io/docs/dashboards-and-widgets/PassingRatePerLaunch   
I suupose I can close the issue.
If you have any questions regarding the iisue you can reopen it or create a new one.
Thanks for using ReportPortal!
