### ISSUE TITLE
Lost all projects after upgrade to 24.2 PRE-release version 

### ISSUE THREAD

**Issue by fslevoaca-ionos** [reportportal/reportportal#2353]
Hi,

I've upgraded my ReportPortal from 24.1 to 24.2.
It seems I cannot see any of my projects anymore. Also my credentials are lost. I had to login with default superadmin credentials. It seem like ReportPortal started fresh from scratch. Though, I made sure volumes are the same.

This did not happen with other versions in the past.

I had to revert back to 24.1 in order to see my projects and use my credentials again.

**Comment by HardNorth** [comment]
That's terrible, sorry for this. Looks like we have issues in our migration scripts. I'm reverting the last merge, we need to implement and test additional migration logic.

**Comment by fslevoaca-ionos** [comment]
Issue is fixed
