### ISSUE TITLE
`/v1/user` endpoint was renamed, API expected breaking change or mistake?

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/reportportal#2358]
**Describe the bug**
![image](https://github.com/user-attachments/assets/ea779286-fd4e-4324-8ab5-74f53a47ae51)

**Expected behavior**
Diff is:
Before: GET `/v1/user`
After: GET `/users`

**Versions:**
 - Version of RP 24.2

**Comment by Pink-Bumblebee** [comment]
@nvborisenko , hello.  Thank you for highlighting, but as I see at demo.reportportal.io and in API documentation, it was changed in RP v.24.1. 
![image](https://github.com/user-attachments/assets/2265590b-4620-454e-bff8-39ec56358d6c)
![image](https://github.com/user-attachments/assets/242f5c10-277d-48e9-9198-2077476a26ab)
