### ISSUE TITLE
Not all the test results are logged to ReportPortal

### ISSUE THREAD

**Issue by akshayamaldhure** [reportportal/reportportal#2364]
**Describe the bug**
Recently, we have started observing that all the test results are not getting logged to ReportPortal, i.e. the total/passed/failed number of tests shown on ReportPortal does not match with that from TestNG.

**Expected behavior**
Actual stats (from TestNG):
Total tests run: 175, Passes: 157, Failures: 18, Skips: 0
ReportPortal stats (as seen on ReportPortal launches UI):
Total tests run: 50, Passes: 43, Failures: 7, Skips: 0

**Versions:**
 - OS, Browser (Chrome 129.0.6668.60 on macOS Sonoma 14.4.1)
 - Version of RP [attached the screenshot]
 
![Screenshot 2024-10-02 at 5 46 07 PM](https://github.com/user-attachments/assets/07145334-05e3-4063-a72b-30f4fd7cc19e)

**Comment by Pink-Bumblebee** [comment]
@akshayamaldhure , is it possible to get log of api-service?

**Comment by akshayamaldhure** [comment]
Attaching the logs from the `reportportal-api-1` container.
[service-api-log.zip](https://github.com/user-attachments/files/17228668/service-api-log.zip)

**Comment by Pink-Bumblebee** [comment]
@akshayamaldhure , may I ask you to check "schema_migrations version in the PostgreSQL database".
Sql request : `select * from schema_migrations;`

**Comment by akshayamaldhure** [comment]
Saw this again on the 24.2 version, attaching the logs.
[service-api-log-ChannelContinuationTimeoutException.zip](https://github.com/user-attachments/files/17238267/service-api-log-ChannelContinuationTimeoutException.zip)

I'm unable to log in to psql for running the query, getting the error seen in the screenshot below.

![Screenshot 2024-10-03 at 10 29 55 AM](https://github.com/user-attachments/assets/599e5cf6-f3b3-42d4-a02e-c371720e741e)

**Comment by akshayamaldhure** [comment]
@Pink-Bumblebee I'm able to connect to the db now somehow. Here's the output of the query.
![Screenshot 2024-10-03 at 1 39 03 PM](https://github.com/user-attachments/assets/1afa837b-0d3e-44d2-acb3-c501d9157381)

**Comment by Pink-Bumblebee** [comment]
@akshayamaldhure , thank you. I will transfer this info to dev team.
May I ask you : are you still observing your issue?

**Comment by akshayamaldhure** [comment]
@Pink-Bumblebee Yes, still able to replicate this consistently. Tried with 3 test runs so far.

**Comment by Pink-Bumblebee** [comment]
Just will keep psql request here:
psql -d reportportal -U rpuser -W -c "SELECT * FROM schema_migrations;"

**Comment by akshayamaldhure** [comment]
@Pink-Bumblebee We use Docker based installation. Just used from ReportPortal GitHub and only modified the `volumes` based on the actual file paths on our VM. Attaching the docker-compose.yml file we are using.
[docker-compose.zip](https://github.com/user-attachments/files/17242316/docker-compose.zip)

**Comment by irynakozak2** [comment]
@akshayamaldhure Hi! Could you please [this comment](https://github.com/reportportal/reportportal/issues/2366#issuecomment-2393112717) to double-check that everything is OK with the RabbitMQ assuming the new async reporting configuration in 24.2?

**Comment by hlebkanonik** [comment]
Hi @akshayamaldhure! Could you please provide the status and logs from the RabbitMQ container?

**Comment by akshayamaldhure** [comment]
@irynakozak2 @hlebkanonik I'm still able to replicate the issue through a local test run. Attaching the RabbitMQ container logs (please rename the attached file by removing its .zip extension). As for the RabbitMQ management part, I'm sharing the screenshots below. Please note that I've collected all of these screenshots about 30 seconds after the full test run was completed.

**ReportPortal test launches view (incorrect data)**
![Screenshot 2024-10-04 at 10 55 05 PM](https://github.com/user-attachments/assets/46f3e34a-0625-44a5-a88c-6f5ac825a61e)

**TestNG reporter stats (correct data)**
![Screenshot 2024-10-04 at 10 55 32 PM](https://github.com/user-attachments/assets/5edc8920-2902-41bc-ae34-6d2c680adfb2)

**RabbitMQ Exchanges**
![Screenshot 2024-10-04 at 10 56 07 PM](https://github.com/user-attachments/assets/1b1dfdd9-4026-4b41-b8f4-4bb1a6060d08)

**RabbitMQ Queues and Streams**
![Screenshot 2024-10-04 at 10 56 31 PM](https://github.com/user-attachments/assets/c4a52d64-e646-45eb-a740-b0c1ec2d677c)

Hope this helps.

[rabbitmq-log.txt.zip](https://github.com/user-attachments/files/17260405/rabbitmq-log.txt.zip)

**Comment by akshayamaldhure** [comment]
@irynakozak2 @hlebkanonik Did you get a chance to check this?

**Comment by akshayamaldhure** [comment]
@irynakozak2 @hlebkanonik To my surprise, I see this issue even on a fresh new Docker-based ReportPortal installation.

**Stats reported by TestNG**
![Screenshot 2024-10-08 at 11 22 20 AM](https://github.com/user-attachments/assets/b6a811ff-7b2a-4129-89ff-85275a477c46)

**Stats from ReportPortal**
![Screenshot 2024-10-08 at 11 22 50 AM](https://github.com/user-attachments/assets/1e4a5d9c-02c9-447e-b2aa-01207bff457b)

**Exchanges**
![Screenshot 2024-10-08 at 11 20 53 AM](https://github.com/user-attachments/assets/30003be2-73af-47bb-9c4b-eb10c75b08dc)

**Queues and Streams**
![Screenshot 2024-10-08 at 11 21 26 AM](https://github.com/user-attachments/assets/063555f8-9511-40a2-92c1-3d7e7b8c0af6)

Also attaching the RabbitMQ container logs (.zip extension should be removed).

[rabbitmq-container-log.txt.zip](https://github.com/user-attachments/files/17286959/rabbitmq-container-log.txt.zip)

**Comment by akshayamaldhure** [comment]
On a closer inspection into the test code, it looks like this was happening either because some of the test classes did not implement the `ITest` interface for setting the test name or they did so incorrectly. My bad, apologies for confusion. Closing this here.
