### ISSUE TITLE
Possible to link test item without use of bts integration

### ISSUE THREAD

**Issue by bybilo78** [reportportal/reportportal#2367]
Hi,

Unfortunately, I currently cannot use the Jira plugin because only basic authorization is supported and I cannot log in with a token.

Therefore, we would like to simply add a BTS link directly without using the plugin, but unfortunately it is not possible. 

Is there a general approach where you can store BTS links?

![image](https://github.com/user-attachments/assets/66a4f52e-4f0c-474e-9896-081e025b6027)

**Comment by mbryl6** [comment]
Hello @bybilo78,
It is impossible to link an issue to any BTS without installing the plugin for the needed BTS and without creating an integration for it.
