### ISSUE TITLE
Is the functionality of the auto analyzer affected when outputting the stack trace?

### ISSUE THREAD

**Issue by bybilo78** [reportportal/reportportal#2369]
Hi,

as shown in the screenshot, the stacktrace output contains lines that are different for each test run (e.x. 0x.........). 
The auto analyzer cannot then automatically classify the tests.
Do I have to prevent such stack trace output so that the auto analyzer can work properly or can I configure it directly in ReportPortal?

![image](https://github.com/user-attachments/assets/9cca9cac-87c0-4013-ab88-5902aff8ee9f)

Best regards

**Comment by HardNorth** [comment]
@bybilo78 Yes you would better remove such meaningless stacktraces. It's general advice for any ML/AI platforms: remove any meaningless information.
