### ISSUE TITLE
The redirect_uri is not associated with this application.

### ISSUE THREAD

**Issue by jonathanprior** [reportportal/reportportal#2374]
We are getting the below error when trying to sign in via GitHub
![image](https://github.com/user-attachments/assets/2d663658-dbb5-4bf5-adb2-e0f2a332fea1)
The GitHub Client ID/secret all seem to be set correctly and the Homepage URL and Authorization callback URL seem to be set correctly to HTTPS. Is there somewhere that HTTPS needs to get set in the redirect_uri?

We are using the default [docker-compose](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml) and running this on an EC2 instance with an ALB configured.

Wondering if we need to edit the docker-compose or set the redirect_uri somewhere?

**Comment by Pink-Bumblebee** [comment]
Hello @jonathanprior 
Could you please share your settings with us? Like this:
![image](https://github.com/user-attachments/assets/d2c18ab1-0d31-4614-9a39-0bd711d06f59)

And please do not forget to blur sensitive information.

**Comment by caquinomrge** [comment]
@Pink-Bumblebee I encounter the same error. This is my settings. 

![image](https://github.com/user-attachments/assets/3eb8cafd-7e00-44d0-a53a-f6202fd07afa)

Would you know the cause of it?

**Comment by Pink-Bumblebee** [comment]
@jonathanprior , may I ask you: have you resolved your issue?

**Comment by Armstain** [comment]
hey, im facing the same issue here, heres my settings,
![image](https://github.com/user-attachments/assets/1dc667d2-4c88-4bf4-bedc-f86199594337)
![Screenshot 2024-11-29 174551](https://github.com/user-attachments/assets/e591706f-73e8-4a6b-a41a-ca85f339b7f9)

**Comment by Pink-Bumblebee** [comment]
I'm closing this issue because no response from issuer.

**Comment by aloyzio** [comment]
This issue is still persisting.
![Screenshot 2024-12-03 at 10 56 51 PM](https://github.com/user-attachments/assets/47059ac1-f14f-478b-9fea-2c10f16eca4e)


""...Be careful!

The redirect_uri is not associated with this application.

The application might be misconfigured or could be trying to redirect you to a website you weren't expecting...."

**Comment by Binary-Shade** [comment]
anyone knows how to solve this issue ??

**Comment by Pink-Bumblebee** [comment]
@Binary-Shade , could you please provide screenshots for your settings as I requested here https://github.com/reportportal/reportportal/issues/2374#issuecomment-2410226077 ?

**Comment by Finbocloud** [comment]
> This issue is still persisting. ![Screenshot 2024-12-03 at 10 56 51 PM](https://private-user-images.githubusercontent.com/59551570/392245044-47059ac1-f14f-478b-9fea-2c10f16eca4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTM0NzIsIm5iZiI6MTczMzQ5MzE3MiwicGF0aCI6Ii81OTU1MTU3MC8zOTIyNDUwNDQtNDcwNTlhYzEtZjE0Zi00NzhiLTlmZWEtMmMxMGYxNmVjYTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDEzNTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZTcxNjI3MTBiNjdkODlkZjE4ZmJiOTliNjczMjgxOTdlMWIxYmIxMjQ0NmE0Y2MxMDE2YWY5NmI2MThmNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pXagGJ-c4rV1pAye6APJddn_TLkj5nxTZ3qIYkI_rtU)
> 
> ""...Be careful!
> 
> The redirect_uri is not associated with this application.
> 
> The application might be misconfigured or could be trying to redirect you to a website you weren't expecting...."



> This issue is still persisting. ![Screenshot 2024-12-03 at 10 56 51 PM](https://private-user-images.githubusercontent.com/59551570/392245044-47059ac1-f14f-478b-9fea-2c10f16eca4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTM0NzIsIm5iZiI6MTczMzQ5MzE3MiwicGF0aCI6Ii81OTU1MTU3MC8zOTIyNDUwNDQtNDcwNTlhYzEtZjE0Zi00NzhiLTlmZWEtMmMxMGYxNmVjYTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDEzNTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZTcxNjI3MTBiNjdkODlkZjE4ZmJiOTliNjczMjgxOTdlMWIxYmIxMjQ0NmE0Y2MxMDE2YWY5NmI2MThmNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pXagGJ-c4rV1pAye6APJddn_TLkj5nxTZ3qIYkI_rtU)
> 
> ""...Be careful!
> 
> The redirect_uri is not associated with this application.
> 
> The application might be misconfigured or could be trying to redirect you to a website you weren't expecting...."


Are you running it locally on your machine?

**Comment by Binary-Shade** [comment]
> @Binary-Shade , could you please provide screenshots for your settings as I requested here [#2374 (comment)](https://github.com/reportportal/reportportal/issues/2374#issuecomment-2410226077) ?


i solved this issue :+1:  

NEXTAUTH_URL= "http://localhost:3000"

i found this one in .env file. change this to your original host , then boom !

**Comment by ayuanyuanya** [comment]
you can try edit:  {Homepage URL:   http://localhost:8080/},{Authorization callback URL:  http://localhost:8080/login/oauth2/code/github}

**Comment by Karsenh** [comment]
> Hello @jonathanprior Could you please share your settings with us? Like this: ![image](https://private-user-images.githubusercontent.com/145099680/376136593-d2c18ab1-0d31-4614-9a39-0bd711d06f59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwNTkzOTIsIm5iZiI6MTczNjA1OTA5MiwicGF0aCI6Ii8xNDUwOTk2ODAvMzc2MTM2NTkzLWQyYzE4YWIxLTBkMzEtNDYxNC05YTM5LTBiZDcxMWQwNmY1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNVQwNjM4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTc3MzA5MGJhZjhmODc2NjBlMmFiM2Y0YTI1YWJlNGYyZjcwZTVkYjZlYWRkYjczYjJjZWFiZDVhMGFkZDZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X0rpl5LUnvcHqh8KErcPaxidF3l_IZ5oNcWK4BNJRfM)
> 
> And please do not forget to blur sensitive information.

Where are these dashboard settings? Is this in GitHub under the project or somewhere else?

**Comment by kasvith** [comment]
Having same issue with redirect_uri

there seems to be no place to set it

**Comment by doiali** [comment]
I have the same issue, I just launched my application today:
https://actionbitz.com/auth/signin
But sign in with github does not work!
It worked in localhost:3000 and in staging preview. But I don't know why not in production!

**Comment by Karsenh** [comment]
> I have the same issue, I just launched my application today: https://actionbitz.com/auth/signin But sign in with github does not work! It worked in localhost:3000 and in staging preview. But I don't know why not in production!

Check under <Avatar> > Settings > Developer settings > OAuth Apps > <Your_App_Name> (or you might need to create the app, but if it works locally I'm assuming you've already done that).

Here you can verify the `Homepage URL` and the `Authorization callback URL` which I suspect are set to localhost for you during development. Change them to your hosted domains address.

@kasvith You should try the same. Good luck!

**Comment by milindsatpute** [comment]
Check under Your Avatar > Settings > Developer settings > OAuth Apps > check all the details you have mentioned here.. including 1. http:// or https:// 
2. localhost with (if applicable) correct port number
3. Redirect URL

**Comment by Karsenh** [comment]
> Check under Your Avatar > Settings > Developer settings > OAuth Apps > check all the details you have mentioned here.. including 1. http:// or https:// 2. localhost with (if applicable) correct port number 3. Redirect URL

Reminds me of another comment right above yours lol

**Comment by lesi-nedo** [comment]
In my app, I use Django as the backend framework and django-allauth as the authentication library. I have this setting in GitHub OAuth page 

![Image](https://github.com/user-attachments/assets/7eba14a1-c131-4e27-a7c6-d1539f28e72d)

My solution to the problem was adding to `settings.py` this: `ACCOUNT_DEFAULT_HTTP_PROTOCOL='https'`

**Comment by ElizaCalmau** [comment]
I made it work 
On github settings I have setted a:
**Homepage URL as** http://localhost:3000/ 
**Authorization callback URL** http://localhost:3000/api/auth/callback/github

The solution was to change an [origin] in the callback URL for _http://localhost:3000/_ 
![Image](https://github.com/user-attachments/assets/c24419a1-4677-4f45-ae9d-bc0d5a570f44)

**Comment by cloudcwfranck** [comment]
What do we set that up to in production, it does not work for me in production with the production URL.

**Comment by gourav-bhardwaj** [comment]
I used this command to run the MCP server and allowed the MCP inspector endpoint
`ALLOWED_ORIGINS=http://localhost:6274,http://localhost:8000 npm start`
Github settings given below:

<img width="788" height="823" alt="Image" src="https://github.com/user-attachments/assets/51de9273-387d-411b-8c3d-647901bb9783" />

**Comment by ohus1989** [comment]
callback url 경로가 달라요 
http://{USER_IP OR USER_DOMAIN}/users/auth/-/import/github/callback

**Comment by marcospgp** [comment]
is there a way to enable localhost and my production domain? I can do this for all other social login providers

**Comment by MMenser** [comment]
Login should support multiple redirect URLs so can be used in both dev and prod. Google and other auth providers allow this.

**Comment by rizkyhaksono** [comment]
how can i debug when dev not supported?

**Comment by blackqahwah** [comment]
i solved this by modifying the callback URL to begin with the base path specified in auth.ts.

in auth.ts i have basePath: "/auth",

so instead of http://localhost:3000/api/auth/callback/github, my callback URL is http://localhost:3000/auth/callback/github, and it worked.

**Comment by greg1951** [comment]
I too was getting the redirect error from GitHub when trying to follow the GitHub Next Auth sample project. Looking at the "auth.ts" file I noticed the base path was set to "/auth". I then removed "/api" from the documented callback URL, as shown below. 

`http://localhost:3000/auth/callback/github`

FYI, the "Homepage URL" was set to `http://localhost:3000/`

I was then able to get back to sample project client-side page with the current session displayed.

**Comment by cw-sarvesh** [comment]
Has anyone found a solution for the production URL-based, not localhost, and Docker/k8s host?

**Comment by JunbinZheng** [comment]
I encountered the same problem. I think that the `redirect_url` is not actually set in the GitHub settings.
It comes from our application, after authentication is successful. The GitHub server calls the "callback URL," and the `redirect_url` we return should match the domain configured above.
This is the problem I encountered, and I hope it helps you.
