### ISSUE TITLE
Clean up the launch data older than x days

### ISSUE THREAD

**Issue by akshayamaldhure** [reportportal/reportportal#2378]
Hello. Is there an easy way to delete the launch data older than x number of days from PostgreSQL database? We are seeing that our database instance has been bloated with over 680 GB of data, which we would like to clean up. 

![Screenshot 2024-10-16 at 4 40 18 PM](https://github.com/user-attachments/assets/95664239-d824-4730-89d7-1494253c866f)

**Comment by Pink-Bumblebee** [comment]
@akshayamaldhure , there are 2 articles that related to project settings : https://reportportal.io/docs/configuration/ProjectSettings & https://reportportal.io/docs/configuration/LaunchesRetentionPolicy and 2 articles about postgres:  https://reportportal.io/docs/issues-troubleshooting/HowToCleanUpTheReportPortalDatabaseUsingPGRepack and https://reportportal.io/docs/issues-troubleshooting/HowToCleanUpTheReportPortalDatabaseUsingVacuumFull

**Comment by akshayamaldhure** [comment]
@Pink-Bumblebee How about https://reportportal.io/docs/installation-steps-advanced/JobsConfiguration/? Is that relevant to the issue/help I'm requesting here?

**Comment by Pink-Bumblebee** [comment]
@akshayamaldhure , yes, it is relevant. Jobs service is something like set of cleaning scripts that are working by schedule. They cleans launches and their data (in postgres also) according to project settings. But postgres sometimes needs to be cleaned by vacuum command, as I know.

**Comment by akshayamaldhure** [comment]
@Pink-Bumblebee I've reduced the log retention duration of all our projects to 14 days and I've also set all the cleanup crons to runs every 30 minutes with `0 */30 * * * *` in `docker-compose.yml` (had restarted ReportPortal after this using `docker-compose`), but I do not see any change in the disk utilisation even after ~3 hours of doing these steps. Do you suggest we follow steps using the vacuum command?

**Comment by akshayamaldhure** [comment]
@Pink-Bumblebee Sure, I'll check this. Closing this here for now. Apologies for not going through the documentation before opening this ticket. Thank you for your help.
