### ISSUE TITLE
AD can not add a domain without a dot

### ISSUE THREAD

**Issue by fasterfish** [reportportal/reportportal#238]
In our company, the domain name does not contain dot:
![screenshot_2](https://user-images.githubusercontent.com/18389889/30550477-f9d9a3e8-9cb0-11e7-9809-66dc1107e050.png)

Please, add support for this. Thanks!

**Comment by evjlobanova** [comment]
Hi, @fasterfish  ! We have changed validation rule for a domain, after release you will see a fix.

**Comment by fasterfish** [comment]
Hi, @evjlobanova! Thank you.
