### ISSUE TITLE
defaultProject and projectRole is not getting assigned to new users with SAML group assignment

### ISSUE THREAD

**Issue by abalasub-wm** [reportportal/reportportal#2380]
**Describe the bug**
Initially, I had only three SAML attributes: email, firstName, and lastName, and I used it for the login (Authentication)

Now I added these two parameters defaultProject and projectRole in IDP settings. So that the users can get mapped to the default project automatically instead of mapping them manually. It works well with OKTA roles. But it's not working When I add the users to Okta group. I'm using group attributes for this.

**Expected behavior**
I expect the new user to get mapped to the defaultProject and projectRole I parse with SAML IDP attributes.

**Screenshots**
If applicable

**Versions:**
 - OS, Browser - Chrome
 - Version of RP - 5.11.0

**Comment by Pink-Bumblebee** [comment]
Hello @abalasub-wm , could you please share the link in documentation where you found these 2 parameters: defaultProject and projectRole?

**Comment by abalasub-wm** [comment]
I referred API documentation. 
<img width="1314" alt="image" src="https://github.com/user-attachments/assets/4f23bdc7-9c46-48fb-9a8b-b85bfacf9fb3">

**Comment by raikbitters** [comment]
Hi @abalasub-wm. SAML doesn't use our REST API, instead, it creates a user directly to the database. Currently, SAML can handle the following attributes: email, last name, first name, or full name according to this documentation: https://reportportal.io/docs/plugins/authorization/SamlProviders/Overview/#custom-attributes

We have no plans to provide user and project synchronization support via SAML in the OpenSource version. Something may change in the future.

**Comment by abalasub-wm** [comment]
But it works well when I use the OKTA role instead of the group. I saw that the user is automatically mapped to the project.

**Comment by abalasub-wm** [comment]
@raikbitters @Pink-Bumblebee ^^

**Comment by raikbitters** [comment]
@abalasub-wm SAML creates users and default projects for each user. I don't see any logic in the SAML code for adding a user to the existing project.

**Comment by abalasub-wm** [comment]
My Objective is when a new user is added to OKTA group , the user will gain access to report portal (which is working as expected) and get added to the project we maintain (which is working with OKTA role and not OKTA group)

Currently, we are mapping the user manually to the project once they do the. first login in with OKTA
