### ISSUE TITLE
Could not create postgresql container with error: mkdir: cannot create directory ‘/bitnami/postgresql’: Permission denied

### ISSUE THREAD

**Issue by jusski** [reportportal/reportportal#2385]
**Describe the bug**
Trying to deploy with docker with commands: 
```
curl -LO https://raw.githubusercontent.com/reportportal/reportportal/master/docker-compose.yml
docker-compose -p reportportal up -d --force-recreate
```
getting error on creating postgresql container:

`mkdir: cannot create directory ‘/bitnami/postgresql’: Permission denied`

**Expected behavior**
postgresql container is created without errors

**Screenshots**
![image](https://github.com/user-attachments/assets/ef40172a-fb00-4fc0-8499-6ffbb568ff64)

**Versions:**
 - OS, Browser (windows, red hat 9)
 - Version of RP [find it under Login form, copy as is]
 docker-compose.yml version deecd60b9f3d556adfcb90cb683fe07d888f76c5

**Comment by Pink-Bumblebee** [comment]
@jusski , that's very strange behavior on your side. I've tried to reproduce on ubuntu virtual machine, but I couldn't find any issues.

**Comment by jusski** [comment]
Seems i needed to delete postgres volume, which i had from earlier version of report portal. After that postgres container was created
