### ISSUE TITLE
Tests are displayed wrong on suite level

### ISSUE THREAD

**Issue by naiad09** [reportportal/reportportal#239]
Hi, Report Portal.

I hope you are well.

I have problems with displaying tests under suite level.
To reproduce it just open any launch and then open any suite.
However, you can see right columns if search something, go info test level and return back.
**Actual result (defect)**
![defect](https://user-images.githubusercontent.com/19240314/30593533-908e0070-9d53-11e7-8dd6-c4c07ed98009.png)
**Expected result**
![expected columns](https://user-images.githubusercontent.com/19240314/30594137-a936909a-9d55-11e7-8774-49e12570d1eb.png)

I also recorded a video (from rp.epam.com)
[rp.zip](https://github.com/reportportal/reportportal/files/1314333/rp.zip)
Full steps:
- Open the launch
- Open suite
Result: Columns are incorrect: Method Type, Name, Status, Start, **Defect Type**
- Type "test" in search field
- Open the filtered test
- Return to suite level
Result: columns are correct: Name, Start, **Total, Passed, Failed, Skipped, etc.**

**Comment by evjlobanova** [comment]
Hi! Could you please tell us what the actual method type of these test items (BeforeSuite and Default Test) is? You can get this info via  get request in Test Controller in API.

**Comment by naiad09** [comment]
Hi @evjlobanova 
I'm afraid I'm not so familiar with it, could you please get more information how to get it?

**Comment by evjlobanova** [comment]
Please follow the next steps:
-choose **API** 
![api](https://user-images.githubusercontent.com/30413511/30866006-c7b3ee74-a2e0-11e7-8f85-ba2d0aaed3b7.png)
- choose **Test Item Controller**
- GET /{projectName}/item/{testItemId}
- fill projectName and testItemId
After all tell me please the method type of items

**Comment by naiad09** [comment]
BeforeSuite has type "type": "BEFORE_SUITE",
Default Test has type  "type": "TEST",

**Comment by evjlobanova** [comment]
Hi, @naiad09! A reason why you have seen a different views for the same item (Default Test) is that your test structure consists items that belong to different displayed types on the same level.  RP can show right view when the structure is correct. 
But in your case when there were two items: Default Test (Test level) and Before Test (Step level) - UI displayed view for the Step level.  When there was only Default Test, UI displayed view for the Suite/Test level.
We have changed principles of a view for different levels items.  Now the displayed level depends on the uppest level of the item on the same path level.  So this fixing you will be able to see in the future release.
