### ISSUE TITLE
Failed tests are not marked as "To Investigate"

### ISSUE THREAD

**Issue by silverio82** [reportportal/reportportal#2391]
We use "@reportportal/client-javascript": "5.3.0" and have installed new version of RP build 5.12.0. And now failed tests are not marked as "To investigate". 

![Screenshot 2024-10-29 at 5 38 08 PM](https://github.com/user-attachments/assets/28778472-7d8e-46b1-9261-f6ae140a45a9)

To make a decision on failed tests we need to switch to PASS and then back to FAILED
On version 5.11.1 it was okay.

https://github.com/user-attachments/assets/8c15f7d6-4081-4e1f-b0fb-d81a705541ec

**Comment by silverio82** [comment]
@AmsterGet in package json we have "@reportportal/client-javascript": "5.3.0" only.
RP build 5.12.0 is installed on Azure devops.
With 5.11.1 it was okay and with previous build versions.
I tried to install it on local docker, issue is the same.

**Comment by silverio82** [comment]
This file used during installation https://raw.githubusercontent.com/reportportal/reportportal/master/docker-compose.yml
@AmsterGet

**Comment by alena-babrova** [comment]
Hello @silverio82,

Could you please provide more details - click on number of failed items and:
1. Provide full-page screen
2. Response of the following request {url}/api/v1/{project_name}/item/v2...

These may help me for investigating your issue.

**Comment by silverio82** [comment]
Hello @alena-babrova 
There is not so much info
![image](https://github.com/user-attachments/assets/a1ab23b9-4e21-4186-a271-53d15505fc5f)

But if you'd like we can make a meeting to review it together

**Comment by alena-babrova** [comment]
Dear @silverio82,

Indeed, I see that behavior was changed in the latest version, and now it's expected behavior.
You can find the changes explanation [here](https://github.com/reportportal/reportportal/issues/2360#issuecomment-2407125213).

So it is recommended to use "type": "STEP" for your tests because "Make decision" ("To investigate" items) is designed to work with such kind of items.

**Comment by silverio82** [comment]
Ha-ha, @alena-babrova you are right :) I use cucumber and used SCENARIO type. Switched to STEP. And it works. Thank you.

P.S.: but STEP naming is strange :)
