### ISSUE TITLE
Launches order displayed in back order on Launch statistics chart

### ISSUE THREAD

**Issue by silverio82** [reportportal/reportportal#2393]
Launches order displayed in back order on "Launch statistics chart" widget

![image](https://github.com/user-attachments/assets/bac9b32c-01d8-4007-906a-8c403bc340d1)

Build 5.12.0

**Comment by Pink-Bumblebee** [comment]
Hello @silverio82 , thank you for highlight. 
By the way, are you using firefox?

**Comment by Kozovskaya** [comment]
Duplicate of https://github.com/reportportal/reportportal/issues/2381

**Comment by silverio82** [comment]
@Pink-Bumblebee nope. I use Chrome on Mac

**Comment by silverio82** [comment]
As mentioned it is a duplicate of https://github.com/reportportal/reportportal/issues/2381
