### ISSUE TITLE
JUnit Import Plugin Is Not Applying Attributes to New Launches

### ISSUE THREAD

**Issue by calebevans** [reportportal/reportportal#2398]
**Describe the bug**

When using `/v1/plugin/{projectName}/{pluginName}/import` to invoke the JUnit plugin import functionality, attributes described in the `launchImportRq` object don't seem to be applied to the new launch. I have tried several approaches and have yet to get it to work.

**Example**

1. Import a new launch using the JUnit plugin:
```bash
curl -X 'POST' \
  'http://localhost:9191/api/v1/plugin/test/junit/import' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhb***********' \
  -H 'Content-Type: multipart/form-data' \
  -F 'file=@junit_example.xml;type=text/xml' \
  -F 'launchImportRq={"startTime":"2024-11-04T20:44:48.906Z","name":"string","description":"string","attributes":[{"key":"test123","value":"test123","system":false}],"mode":"DEFAULT"}'
```
RESP:
```json
{
  "message": "Launch with id = 4222753d-5568-4baa-b98c-feed65811569 is successfully imported.",
  "data": {
    "id": "4222753d-5568-4baa-b98c-feed65811569",
    "name": "junit_example",
    "number": 12
  }
}
```

2. Check attributes for new launch `4222753d-5568-4baa-b98c-feed65811569`:
```bash
curl -X 'GET' \
  'http://localhost:9191/api/v1/test/launch/4222753d-5568-4baa-b98c-feed65811569' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhb***********'
```

RESP:
```json
{
  "owner": "superadmin",
  "id": 17,
  "uuid": "4222753d-5568-4baa-b98c-feed65811569",
  "name": "junit_example",
  "number": 12,
  "startTime": "2024-11-04T20:45:20.111238Z",
  "endTime": "2024-11-04T20:45:20.117238Z",
  "lastModified": "2024-11-04T20:45:20.294157Z",
  "status": "FAILED",
  "statistics": {
    "executions": {
      "total": 6,
      "failed": 2,
      "passed": 3,
      "skipped": 1
    },
    "defects": {
      "to_investigate": {
        "total": 3,
        "ti001": 3
      }
    }
  },
  "attributes": [],
  "mode": "DEFAULT",
  "analysing": [],
  "approximateDuration": 0.006,
  "hasRetries": false,
  "rerun": false,
  "metadata": {
    "rp.cluster.lastRun": "1730753120634"
  },
  "retentionPolicy": "REGULAR"
}
```

**Expected behavior**
When importing a new launch, the JUnit plugin should properly populate the attributes of the new launch.

**Versions:**
 - Running RP 24.2 in Docker using [this Docker compose file](https://raw.githubusercontent.com/reportportal/reportportal/refs/tags/v24.2/docker-compose.yml).
     - My browser won't let me copy the version info on the login page, but every service is set to 5.12.0
     - Docker version: 27.3.1, build ce12230

**Comment by waynesun09** [comment]
The function with mark skipped is not issue is not working due to this bug, the doc about this new feature is:

https://reportportal.io/docs/log-data-in-reportportal/ImportDataToReportPortal/#import-via-api

the attribute could not be applied with the api on the latest 24.2 release

**Comment by calebevans** [comment]
I re-deployed this environment today and it seems to be resolved for some reason. Closing this for now.

**Comment by calebevans** [comment]
@hyunil-shin yeah it is working with the launchImportRq on v24.2 using the API
