### ISSUE TITLE
Launch description is displayed in the wrong place

### ISSUE THREAD

**Issue by alex-ucra** [reportportal/reportportal#2399]
**Launch description is displayed in the 'Start time' column instead of 'Launch' column**
...

**Screenshots**
<img width="1401" alt="Знімок екрана 2024-11-06 о 10 23 14" src="https://github.com/user-attachments/assets/8b2413e8-0ee7-4e2f-98d8-5236eb87468e">

**Versions:**
 - Chrome v.130.0.6723.70, macOS Sonoma v.14.6.1
 - Version of RP 24

**Comment by alena-babrova** [comment]
Hello @alex-ucra,

It is as designed. Description was moved to the new place several releases ago for the convenience of our users.
Many users have a long description, and it was difficult to display it before.
