### ISSUE TITLE
Windows support - install ReportPortal with Docker on Windows?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [reportportal/reportportal#24]
Is this one already tested on Windows?

I am aware of theory that with Docker it should be platform agnostic but did anybody really see it run on a Windows host? ;-)

**Comment by avarabyeu** [comment]
There are three options, actually. 
1. Use Windows 10 with native docker support. It should work without any problems.
2. Install docker toolbox on Win prior to 10. It will install VirtualBox and tiny linux image so you can use docker through that VM.
3. Grab JAR files manually and execute them whatever way you want :) If you have a look at docker-compose, you will find all needed services. Dockerfiles for that services contain URL to bintray to download executable JARs.

**Comment by Tset-Noitamotua** [comment]
Thanks for clarification!

**Comment by DzmitryHumianiuk** [comment]
@Tset-Noitamotua Once, on wonderful day, we will create documentation for it.
But, you will follow up with Windows stack, please do not hesitate to contribute steps and descriptions to our documentation.

**Comment by DzmitryHumianiuk** [comment]
@Tset-Noitamotua 
part1 https://www.youtube.com/watch?v=Wdgme8MwQ4g
part2 https://www.youtube.com/watch?v=NKr93F5H0k8

**Comment by michalfar** [comment]
Hi,
Do you support Docker based on Windows server 2016? I don't want to install virtualbox etc.
Should I somehow adjust docker-compose file?

**Comment by DzmitryHumianiuk** [comment]
@michalfar not sure, is the any update required for docker-compose in this case.

Did you already tried it?
