### ISSUE TITLE
Can not connect via ldap to reportportal

### ISSUE THREAD

**Issue by fasterfish** [reportportal/reportportal#240]
As a user i want to successfully login to reportportal with AD credentials

Given i have configured ldap authorization
When i try to login to reportportal with correct AD credentials
Then the authorization must be successful

Actual: You do not have enough permissions. Bad credentials

[uat_logs](https://github.com/reportportal/reportportal/files/1317310/uat_logs.txt)

**Comment by avarabyeu** [comment]
@fasterfish could you please give more details. It might be related to incorrect configuration, not a bug. Was it overlap to conversation where LDAP has no emails at all?

**Comment by fasterfish** [comment]
The problem is resolved. It was necessary to make the following ldap settings (example):
![screenshot_1](https://user-images.githubusercontent.com/18389889/32600957-055a7d66-c563-11e7-890a-8530b67dd788.png)

@avarabyeu thanks!

**Comment by babantax** [comment]
Hello @fasterfish,

Did you solved the issue? I´m facing the same problem.

Thanks a lot

**Comment by guptakapil** [comment]
Although the issue is closed, however I am still commenting in hope it will help others:

1. This set-up needs a manager DN which is user which can be used to query ldap 
2. And Manager Password - which is the password for that user. 

Also, once you have it, delete the set-up (i.e. LDAP integration) and add again. It helped!

**Comment by git-prabhut** [comment]
With "Authorization Service: 5.6.3", still I am facing this problem.

As per the LDAP configuration screen, "Manager DN" and "Manager Password" are optional. Mandatory fields are LDAP URI, "Base DN" and "Email Attribute".
