### ISSUE TITLE
Log files are not viewable or downloadable

### ISSUE THREAD

**Issue by XiyangDong** [reportportal/reportportal#2401]
Describe the bug
Hi, when we first uploaded logs to ReportPortal there is a 'TXT' icon and options to 'view' or 'download'. But recently there is a change of behavior that the icon is gone and the logs are no longer to be viewed or downloaded. See attached photos for before and after.
I tried to zip all logs and send as one file, or sent only one log file, or switched to different browsers, but none of them made a difference. 

Expected behavior
Recover the functionality to view and download uploaded log files

Screenshots
![Screenshot from 2024-08-13 14-12-58 (1) (1)](https://github.com/user-attachments/assets/19a82b73-c5dc-4fe3-be32-5a1f65e35321)
![Screenshot from 2024-09-06 09-52-12 (1) (1)](https://github.com/user-attachments/assets/e66c3b93-6523-4ba2-9d63-eec3ee014c11)

Versions:
 - Browser: Google Chrome Version 128.0.6613.119 (Official Build) (64-bit)
 - Version of RP: 5.7.2

**Comment by Pink-Bumblebee** [comment]
@XiyangDong , what are your settings to keep your data? https://reportportal.io/docs/configuration/ProjectSettings#general-settings

**Comment by XiyangDong** [comment]
@Pink-Bumblebee hello, please see the screenshot.
![Screenshot from 2024-11-11 06-52-47](https://github.com/user-attachments/assets/7d8a55fa-c3ce-4fce-b7cb-8d6c788e9852)
I don't think it's the retention that removed the logs, I can reproduce this issue as of now.

**Comment by alena-babrova** [comment]
Hello @XiyangDong,

Could you please provide more details:
1. What way do you report results (Agent or API)? 
   1.1 If Agent then what is the version?
   1.2 How do you attach files?
2. Did you update ReportPortal version which caused such behavior?

**Comment by XiyangDong** [comment]
@alena-babrova hello,
1. Via API, we are using an internal tool, I will try to ask my colleague to chime in for the answers.
2. No, our target time to upgrade to version 24.2 is before EOY.

**Comment by alena-babrova** [comment]
Dear @XiyangDong,

If via API, please provide detailed information, maybe real example of request with attachment.
From my experience, you need to carefully compose a request with attachment as in example below:

`
const formdata = new FormData();
formdata.append("json_request_part", "[{\"file\":{\"name\" : \"Notebook.txt\"\n},\"itemUuid\": \"e6acac90-92a6-487f-a363-c5acf8da170e\", \"level\": \"error\", \"message\": \" error log with attachment for Launch B log\", \"time\": \"2024-11-12T12:31:43.243Z\"}]");
formdata.append("file", fileInput.files[0], "Notebook.txt");

const requestOptions = {
  method: "POST",
  headers: myHeaders,
  body: formdata,
  redirect: "follow"
};

fetch("{url}/api/v1/helen_bobrova_personal/log", requestOptions);
`

Pay attention, that file name in `json_request_part` should match the file name in `fileInput`

**Comment by waynesun09** [comment]
@alena-babrova we are using the log API with post method same as you are using, and for the file name we do match the name in file input, and the log api succeed with 201.

It turns out is due to the api tasks failed to save file with:

```
Exception in thread "logs-task-exec225" com.epam.ta.reportportal.exception.ReportPortalException: Incorrect Request. Unable to save file
at com.epam.ta.reportportal.filesystem.distributed.minio.MinioDataStore.save(MinioDataStore.java:75)
at com.epam.ta.reportportal.binary.impl.CommonDataStoreService.save(CommonDataStoreService.java:44)
at com.epam.ta.reportportal.binary.impl.AttachmentBinaryDataServiceImpl.saveAttachment(AttachmentBinaryDataServiceImpl.java:92)
at com.epam.ta.reportportal.binary.impl.AttachmentBinaryDataServiceImpl.saveFileAndAttachToLog(AttachmentBinaryDataServiceImpl.java:117)
at com.epam.ta.reportportal.core.log.impl.SaveLogBinaryDataTask.run(SaveLogBinaryDataTask.java:49)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
2024-11-12 19:14:10.789 ERROR 7 --- [gs-task-exec227] c.e.t.r.f.d.minio.MinioDataStore : Unable to save file '25/2024-11/e5e52f6b-efe8-4f8f-951a-5e8b44c1ec26/742048e0-199c-4341-ac74-516ecfc749bc-file.txt'
```

The Minio storage is out of space in this case.

I think it will be helpful if the background task could record the error status to the certain log entry.

**Comment by alena-babrova** [comment]
Hello @waynesun09,

So it's good that you found the source of the issue. Indeed, it always makes sense to review API logs when something strange is happening 🙂

I am closing the ticket then. Just in case you have any questions, don't hesitate to get in touch.
