### ISSUE TITLE
Jest test cases not getting reported into reportPortal - Throw Error: Could not finish Test Step - "Test Name" tempId not found

### ISSUE THREAD

**Issue by NaitikPandya** [reportportal/reportportal#2404]
I have a react project that uses the jest for test cases.

So i have done the configuration as per your documentation.
Here is my jest configurations.
```json
"jest": {
    "preset": "ts-jest",
    "testTimeout": 100000,
    "maxConcurrency": 10,
    "maxWorkers": "50%",
    "transform": {
      "^.+\\.(ts|tsx)?$": "ts-jest",
      "^.+\\.(js|jsx)$": "babel-jest",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/fileTransformer.js"
    },
    "moduleNameMapper": {
      "\\.(css|less)$": "identity-obj-proxy"
    },
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>/node_modules/"
    ],
    "setupFiles": [
      "jest-canvas-mock",
      "whatwg-fetch",
      "./src/setupJest.ts"
    ],
    "reporters": [
      "default",
      [
        "@reportportal/agent-js-jest",
        {
          "api_key": "<My API KEY>"
          "endpoint": "http://<URL>:8080/api/v1",
          "project": "test_results",
          "description": "Test result",
          "launch": "demo_test",
          "isLaunchMergeRequired": true,
          "launchUuidPrint": true,
          "restClientConfig": {
            "timeout": 0
          }
        }
      ]
    ]
  }
```
Commonad i'm using to run test cases is
`jest --env=jsdom --no-colors -i`

still i'm getting this error
`Could not finish Test Step - "Test Name" tempId not found`

**Screenshot of reported test in to reportportal**
<img width="1378" alt="Screenshot 2024-11-07 at 4 16 57 PM" src="https://github.com/user-attachments/assets/0d569974-d630-4b84-bc87-b3e4b121fe48">
*I Have more the 600+ test cases but only this much is getting log into the report portal*

Does any one have any idea so please guide through this as i'm not able getting any proper document for the same issue to look and resolve it.

It would be great help if anyone reply as soon as possible.

**Comment by Pink-Bumblebee** [comment]
https://github.com/reportportal/agent-js-jest/issues/153
