### ISSUE TITLE
Share filter option missing in RP24.2

### ISSUE THREAD

**Issue by meenakshimoody1** [reportportal/reportportal#2409]
Share filter option missing in RP24.2

![image](https://github.com/user-attachments/assets/88a0c486-db4d-4e9a-bf15-c67d224ad790)

I can see a share option in version 5.6.2 while editing a filter as below
![image](https://github.com/user-attachments/assets/79d80cfd-3385-4364-8bb3-2ee0e3a2e444)

**Comment by Pink-Bumblebee** [comment]
@meenakshimoody1 , thank you for using our ReportPortal. 
We regret to inform you that we have decided to change our approach to filters and dashboards. Starting from version 23.1, all filters and dashboards will be visible to all members of the project team. https://reportportal.io/docs/releases/Version23.1#1-whats-changed

**Comment by meenakshimoody1** [comment]
@Pink-Bumblebee Actually issue is that with RP5.6 once we shared all members could see it. But with RP24.2 - If its supposed to be visible for all members then below is the screenshot of superadmin view where filters display -
![image](https://github.com/user-attachments/assets/fd02dff6-ffeb-4565-be77-e53548edda15)

But below in member view its missing-
![image](https://github.com/user-attachments/assets/8f54e6d7-6c80-4f81-bcf9-1f72e8303548)

**Comment by Pink-Bumblebee** [comment]
@meenakshimoody1 , have you switched ON visibility of your filters at launches page?
 
![image](https://github.com/user-attachments/assets/777ebc7e-b6fa-4211-8242-b8e49f348317)

**Comment by meenakshimoody1** [comment]
@Pink-Bumblebee Yes its on for all of them.
![image](https://github.com/user-attachments/assets/6936199c-5d23-4a3f-8140-18bb08ce7575)
