### ISSUE TITLE
Failed to start nested step. Error: socket hang up

### ISSUE THREAD

**Issue by toduyemi** [reportportal/reportportal#2410]
**Describe the bug**
```
Failed to start nested step. Error: socket hang up
URL: http://localhost:8080/api/v2/superadmin_personal/item/52fe3998-b041-4db6-ae81-66a25ff5229e
method: POST
    at /Users/temi/work/spire-web-tests-playwright/node_modules/@reportportal/client-javascript/lib/rest.js:56:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
node:internal/child_process:421
    throw new ErrnoException(err, 'spawn');
          ^

Error: spawn EBADF
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:760:9)
    at Object.fork (node:child_process:171:10)
    at WorkerHost.startRunner (/Users/temi/work/spire-web-tests-playwright/node_modules/playwright/lib/runner/processHost.js:50:43)
    at WorkerHost.start (/Users/temi/work/spire-web-tests-playwright/node_modules/playwright/lib/runner/workerHost.js:60:23)
    at Dispatcher._startJobInWorker (/Users/temi/work/spire-web-tests-playwright/node_modules/playwright/lib/runner/dispatcher.js:88:20)
    at Dispatcher._scheduleJob (/Users/temi/work/spire-web-tests-playwright/node_modules/playwright/lib/runner/dispatcher.js:57:5) {
  errno: -9,
  code: 'EBADF',
  syscall: 'spawn'
}

Node.js v22.5.1
```
UI shows white page that says "gateway timeout". Though I've been getting errors like this for weeks while the UI has been operational (though increasingly slow and unresponsive). Nothing changed in config or env when UI stopped working  Docker shows all containers green and active. Deleted containers and redeployed, still getting errors and broken ui.

**Expected behavior**
For the test execution to finish with no exceptions thrown.

[nov 14.txt](https://github.com/user-attachments/files/17759100/nov.14.txt)

**Comment by toduyemi** [comment]
[nov 14.txt](https://github.com/user-attachments/files/17759097/nov.14.txt)

**Comment by alena-babrova** [comment]
Hello @toduyemi,

Thank you for providing logs.
As I see in the logs there is an issue with RabbitMQ. Did you try to restart all containers? Didn't it help?

**Comment by toduyemi** [comment]
@alena-babrova i've restarted, i've `docker-compose down` and back up, i've deleted the docker-compose file, deleted all containers + volumes then pulled cURL the compose file from scratch. All containers are green and look healthy. But the ui simply won't load. Yesterdays logs after I did the clean install. Gratitude for the assistance.
[nov15.txt](https://github.com/user-attachments/files/17788437/nov15.txt)

**Comment by irynakozak2** [comment]
@toduyemi Hi! Could you please specify the CPU/RAM size dedicated to the ReportPortal docker machine? From the logs perspective it looks like there is 1 CPU on the instance.

**Comment by toduyemi** [comment]
The resource usage view of reportportal:
<img width="1542" alt="Screenshot 2024-11-18 at 12 36 58 PM" src="https://github.com/user-attachments/assets/784d0f79-cee6-4c04-a560-2b3e3ee12a7b">

`docker info`:
<img width="682" alt="Screenshot 2024-11-18 at 12 42 23 PM" src="https://github.com/user-attachments/assets/0d4f7b05-ca68-4176-a6cd-3e4d7059d387">

@irynakozak2 is the information you're looking for?

**Comment by irynakozak2** [comment]
@toduyemi Exactly, thank you. 
Based on the [minimum system hardware requirements](https://reportportal.io/docs/installation-steps/HardwareRequirements#2-cpu-utilization) for Docker installation, I recommend increasing the CPU for ReportPortal to at least **2 cores** in case of limited capacity and rechecking the issue. However, for a stable local instance, my recommendation is 4 CPUs.

**Comment by toduyemi** [comment]
@irynakozak2 Looking at my docker setting, I've already maxxed out the CPU limit to 12. That page doesn't show how to dedicate cores to report portal. Is there another method to increase core use?
<img width="1542" alt="Screenshot 2024-11-19 at 9 45 55 AM" src="https://github.com/user-attachments/assets/77b7cc6a-88f9-4832-aad9-aa500601318c">

**Comment by toduyemi** [comment]
Attempted a 3rd "Reset to factory defaults" and my available cores became 12 again. Redeployed ReportPortal and it is now working without the thrown exception and the UI loads. Gratitude for your help @irynakozak2 :)

**Comment by irynakozak2** [comment]
@toduyemi Nice catch, thank you for your contribution to ReportPortal!
