### ISSUE TITLE
Pod - pod/report-portal-reportportal-api failing 

### ISSUE THREAD

**Issue by amarjotkalraTR** [reportportal/reportportal#2417]
Description: 
Report portal was deployed using helm chart deployment.
https://github.com/reportportal/kubernetes/blob/master/README.md

pod/report-portal-reportportal-api  is failing continuously(CrashLoopBackOff) as a result of below error:
Logs:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginStartUpService': Invocation of init method failed; nested exception is com.epam.reportportal.rules.exception.ReportPortalException: Error during plugin uploading: 'Plugin with ID = 'junit' of the same VERSION = '1.0.0' has already been uploaded.'

**Expected behavior**
Pod should come up fine . It was running fine before . I did some upgrades and now I am facing this issue.

**Comment by DorAzouri-tipalti** [comment]
I'm getting the same error

**Comment by Pink-Bumblebee** [comment]
Hello @amarjotkalraTR and @DorAzouri-tipalti . As a workaround please try to use tip from this comment: https://github.com/reportportal/reportportal/issues/2372#issuecomment-2401615507

**Comment by amarjotkalraTR** [comment]
Many thanks @Pink-Bumblebee  - This fixed the issue. Do we know why this happens? Also I believe this should flagged as warning and skip if record for junit with same version already exists.

**Comment by Pink-Bumblebee** [comment]
Dev Team knows why this happens and they promised to fix in next releases.
