### ISSUE TITLE
"Replace Comments to All Selected Items" should be checked only after a comment is typed

### ISSUE THREAD

**Issue by aliaksandrbasau** [reportportal/reportportal#242]
When you change Defect Type of multiple test failures, you can also change Defect Comment on the same dialog. The dialog also has "Replace Comments to All Selected Items" checkbox that is checked by default. If you forget about unchecking the checkbox, it will clear all defect comments. I, personally, never change a defect comment and always have to remember to uncheck the checkbox.

![image](https://user-images.githubusercontent.com/6681200/31023923-6300711e-a50b-11e7-9546-01853834658b.png)

I would like to see the following improvement:
- "Replace Comments to All Selected Items" is unchecked by default.
- "Replace Comments to All Selected Items" is automatically checked after the first letter is typed into comment text area.

It's a very rare case when you want to clear all comments that are assigned to selected test failures. For that rare case, user can check "Replace Comments to All Selected Items" himself/herself.

**Comment by DzmitryHumianiuk** [comment]
Agree.

right to the next sprint,

**Comment by evjlobanova** [comment]
@aliaksandrbasau  by default, the check box is selected, but if you uncheck it, your selection will be saved to the local store in the browser. You can see this improvement in the future release.

**Comment by aliaksandrbasau** [comment]
@evjlobanova Works for me. Many thanks!
