### ISSUE TITLE
Help needed to setup DNS configuration and https configuration for RP via docker-compose

### ISSUE THREAD

**Issue by KriTh07** [reportportal/reportportal#2420]
Hi Team,

We have currently setup report portal latest version and its up. However we want to make certain configurations like - instead of connection using 'http://hostname:8080'  we would like to configure like 'https://reportportal.xyzdomain.com'.

Can you please help us with necessary changes to be made on docker-compose.yml file - we have not modified much in the sample file available in the master branch 'https://github.com/reportportal/reportportal/blob/master/docker-compose.yml'

Please help at the earliest.

**Comment by Pink-Bumblebee** [comment]
@KriTh07 , please read https://reportportal.io/docs/installation-steps-advanced/SetupTSLSSLInTraefik2.0.x and ask your system administrator or network engineer or DevOPS to help you to setup records or redirects on your DNS Server.

**Comment by KriTh07** [comment]
Awesome, thanks!
