### ISSUE TITLE
Need help configuring certs and 443 connections for Report Portal

### ISSUE THREAD

**Issue by KriTh07** [reportportal/reportportal#2429]
We have the below certs provided by the team, however I am not sure if all these certs need to configured in certs-traefik.yaml file. 

- reportportaldev_com.crt
- reportportaldev.com.key

For now, in my certs-traefik file I have configured the first two certs and its key file. 

Also, I am seeing "Not Secure" when i access https://reportportaldev.domain.com 
Should I remove the 8080 configuration for Report portal UI in the docker-compose.yml file and modify that to 443? Or if we fix the certs, the Not Secure prompt would go away? My Network Architects suggested to check with you guys.

  ## Traefik gateway for routing and load balancing
  gateway:
    image: traefik:v2.11.11
    container_name: traefik
    logging:
      <<: *logging
    ports:
      ## ReportPortal UI
      - "8080:8080"
      ## Uncomment to expose Traefik dashboard
      - "8081:8081"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik/dynamic/certs-traefik.yaml:/etc/traefik/dynamic/certs-traefik.yaml
      - ./data/certs/traefik:/etc/certs/
    command:
      - --providers.docker=true
      - --providers.docker.constraints=Label(`traefik.expose`, `true`)
      - --entrypoints.web.address=:8080
      - --entrypoints.traefik.address=:8081
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.file.directory=/etc/traefik/dynamic
      - --entrypoints.websecure.address=:443
    networks:
      - reportportal
    restart: always

**Comment by Pink-Bumblebee** [comment]
@KriTh07 , as we are opensource project, your request is out of our scope. We have a little outdated article in our documentation https://reportportal.io/docs/installation-steps-advanced/SetupTSLSSLInTraefik2.0.x but you could use it as a start point.
