### ISSUE TITLE
Need help to copy the postgres dump into 24.2 postgres docker container

### ISSUE THREAD

**Issue by KriTh07** [reportportal/reportportal#2437]
Hi Team,

We are migrating from 5.3.5 version of RP to 23.2. I have hosted the application and it running fine. However I am not sure how to copy the `global_users.sql` and the DB dump file `reportportal_5.3.5.dir` from older server to the docker container. Can you please provide some guidance?

**My container:**
`2a0b227a1cb5   bitnami/postgresql:16.4.0-debian-12-r7            "/opt/bitnami/script…"   7 days ago   Up 7 days (healthy)   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp`

**When I login to the container, I see the below:**
```
docker exec -it 2a0b227a1cb5 /bin/bash
I have no name!@2a0b227a1cb5:/$
I have no name!@2a0b227a1cb5:/$ cd /var/lib/postgresql/data
bash: cd: /var/lib/postgresql/data: No such file or directory
```

**I can also login as reportportal user:**
```
I have no name!@2a0b227a1cb5:/$ psql -U rpdbuser -d reportportal
Password for user rpdbuser:
psql (16.4)
Type "help" for help.

reportportal=> 
```

Now where do I copy the dump files since there is no /var/lib/postgresql/data?

**Comment by Pink-Bumblebee** [comment]
@KriTh07 , have you tried to use this approach: https://github.com/reportportal/reportportal/wiki/Upgrading-PostgreSQL-for-ReportPortal-v24.2-and-later ?

**Comment by elvovsky** [comment]
@KriTh07 Please read instructions. The version 16 of PostgreSQL is not there until after 24.2 . There are other changes , but also the default directory for it changed and it is no longer the directory you are looking for . I believe it is bitnami/postgresql

**Comment by KriTh07** [comment]
Yes, I read the instructions, the version is 16.4 in the docker-compose.yml file. Instructions dont have answer for my query! Can you be more specific? Do you want me to copy the file to /bitnami/postgresql? also the rpuser created via docker-compose file will not have any super user/create role/create db access. how do we restore using that user?

**Comment by Pink-Bumblebee** [comment]
@KriTh07 , have you resolved this issue?

**Comment by Pink-Bumblebee** [comment]
Closing issue as issuer hasn't responded.
