### ISSUE TITLE
How to restore db dump into postgres container when rpuser does not have SuperUser access.

### ISSUE THREAD

**Issue by KriTh07** [reportportal/reportportal#2444]
Hi Team,

We have hosted RP using docker compose and upon trying to restore the old db dump, getting the permission denied error as the `docker-compose.yml` file creates `rpuser` by default with no super user access. Only `postgres` user in reportportal db has that access and we don't know `postgres`  password. Can you please help?

```
docker exec -i -e PGPASSWORD=******** postgres psql -U rpdbuser -d reportportal < global_users.sql
SET
SET
SET
ERROR:  permission denied to create role
DETAIL:  Only roles with the CREATEROLE attribute may create roles.
```

```

docker exec -i postgres psql -U postgres -d reportportal < global_users.sql
Password for user postgres:
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  password authentication failed for user "postgres"

```

```
reportportal=> \du
                             List of roles
 Role name |                         Attributes
-----------+------------------------------------------------------------
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS
 rpdbuser  | Create DB

```

**Comment by Pink-Bumblebee** [comment]
@KriTh07 , ask you DBA to help you. Have you used in previous version of RP the separate instance of Postgres?

**Comment by KriTh07** [comment]
the previous version was created manually (5.3.5) and this version is configured via Docker. DBAs can help when they configuration is set manually on the server. However here, you have provided via yml files. Hence posted the query here.

**Comment by Pink-Bumblebee** [comment]
So, isn't it possible to reset password in old database for postgres user, add new user with credentials from yml file to old database, give full rights to this new user, dump database, restore database ? It's just an idea.

**Comment by CanalWood** [comment]
Yes, We don't know the default passwordd used by the docker image: bitnami/postgresql:16.6.0
But you can reset it.

To reset the password of the postgres superuser use this command in your container : 

```
@7b0dfa471b74:/$ sed -ibak 's/^\([^#]*\)md5/\1trust/g' /opt/bitnami/postgresql/conf/pg_hba.conf
@7b0dfa471b74:/$ pg_ctl reload -D /bitnami/postgresql/data/
@7b0dfa471b74:/$ psql -U postgres
postgres=# alter user postgres with password 'NEW_PASSWORD';
postgres=# \q
```

Source : https://docs.bitnami.com/aws/infrastructure/postgresql/administration/change-reset-password/
