### ISSUE TITLE
Report portal V24.2 no longer support configuring AWS SMTP as a email server

### ISSUE THREAD

**Issue by nabeykoon** [reportportal/reportportal#2447]
**Describe the bug**
When we use Report Portal version 5.7.2, we have successfully configured and used AWS SMTP using email server plugin (please see screenshot RP v5.7.2)
In that case, even though the report portal does not offer a username field according to the documentation (https://reportportal.io/docs/plugins/EmailServer/) as a workaround we have configured our API key using "Sender email" field available in the plugin config UI.
However, after upgrading to RP version 24.2, we couldn't use "Sender email" field to configure API key as we did before due to frontend validation added to validate real email address. (screenshot RP v24.2.png) 
Also, it does not offer any username field to do that either.

Another bug could be related: https://github.com/reportportal/reportportal/issues/962

**Expected behavior**
RP V24.2 should offer "username" filed to configure email server as per the documentation (https://reportportal.io/docs/plugins/EmailServer/)
or ELSE it should support entering the API key through "Sender email" field without string validation. 

**Screenshots**
![RP v5 7 2](https://github.com/user-attachments/assets/235ecc4c-3d96-4385-80df-fe2e70609320)
![RP v24 2](https://github.com/user-attachments/assets/9d58fcc9-6d01-4393-b9f8-d1a8817d01c8)

**Versions:**

 - Version of RP -24.2

**Comment by raikbitters** [comment]
Hi @nabeykoon. Could you try the latest release with service API 5.13.1 and service UI 5.12.1

We changed the SMPT integration fields.

**Comment by nabeykoon** [comment]
I have uplifted my services like below,
 service-api: v5.12.1 --> v5.13.1
 service-ui: v5.12.0 --> v5.12.1
 Now it throws an attached error when starting  service-api container
 log: 
[service-api error log.txt](https://github.com/user-attachments/files/18181260/service-api.error.log.txt)
Please note that this environment is already migrated to Postgres v16

**Comment by raikbitters** [comment]
Sorry @nabeykoon. You have to perform the latest migrations before run service API.

**Comment by nabeykoon** [comment]
The issue is fixed with the given versions. Thanks for the quick reply.
