### ISSUE TITLE
Default TestNG xml report isn't compatible with RP report 

### ISSUE THREAD

**Issue by skiesInSpace** [reportportal/reportportal#245]
Default TestNG **timestamp format** "dd MMM yyyy HH:mm:ss z" (e.g. "10 Oct 2017 13:02:47 GMT") isn't compatible with **RP Import**.
Please refer to attached xml report.
Thank you!
![bug](https://user-images.githubusercontent.com/29520759/31388262-2890fea8-add6-11e7-88d6-193e4143a878.PNG)
[report.zip](https://github.com/reportportal/reportportal/files/1371983/report.zip)

**Comment by pictureb00k** [comment]
Fixed. Will be available in 3.3 release
https://github.com/reportportal/service-api/pull/221/commits/d120d5325558dcff00f81003fdfe6b7e2b7d3562
