### ISSUE TITLE
Empty project list and credentials reset after upgrading to ReportPortal 24.2.2

### ISSUE THREAD

**Issue by fslevoaca-ionos** [reportportal/reportportal#2451]
Hi,

I've just upgraded from ReportPortal 24.2 to ReportPortal 24.2.2.
And it seems that the credentials were reset do default ones and also the project list is empty inside the UI.

An identical problem happened between two versions upgrade in the past: #2353

What is the actual problem here ? Is this the same bug on migrations script or extra configuration is needed ?!

**Comment by Pink-Bumblebee** [comment]
@fslevoaca-ionos , sorry to hear that. Do you have backup of your database?
another question: what was your version of postgres at your 24.2 RP instance?

**Comment by fslevoaca-ionos** [comment]
I have ReportPortal 24.2 witch uses postgres:12.17-alpine3.17 in docker-compse.yml.
ReportPortal 24.2.2 uses bitnami/postgresql:16.6.0.  These are the versions with which these two ReportPortal versions come with. It seems **they are not compatible** since upgrading to 24.2.2 I cannot see my projects and I must use the default set of credentials.
Database is not lost. I downgraded to 24.2 and everything is there.

**Comment by Pink-Bumblebee** [comment]
@fslevoaca-ionos , yes. you are right. And it is not our fault. 
Anyway, we have postgres migration guide : [https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.24.2 where y](https://github.com/reportportal/reportportal/wiki/Upgrading-PostgreSQL-for-ReportPortal-v24.2-and-later). Please use it.

**Comment by fslevoaca-ionos** [comment]
Nice,
Thank you ! I will use it and come back with feedback
