### ISSUE TITLE
Can not share any link to particular test item

### ISSUE THREAD

**Issue by rbhbokka** [reportportal/reportportal#246]
Can not share any link to test item or open shared link. 
Also can not refresh page, as after refresh I'm getting 'Error item' page.
Sometimes instead of error item page you can see blank view 
Sometimes hard to reproduce, no ideas what is the difference between reproducible/not

note: issue was originally found by URL with ',' character automatically converted to '%2CD'

Safari 10.0
Mac OS Sierra

**Comment by DzmitryHumianiuk** [comment]
@rbhbokka which version of UI?

![image](https://user-images.githubusercontent.com/11332788/32064914-eb1dbfe2-ba83-11e7-8057-5a5a233a6db3.png)

**Comment by evjlobanova** [comment]
@rbhbokka ^

**Comment by DzmitryHumianiuk** [comment]
@rbhbokka up )
