### ISSUE TITLE
Get launch's URL using ReportPortal agent-java-testNG

### ISSUE THREAD

**Issue by ulmanA** [reportportal/reportportal#247]
I want to print the launch URL to the console after the execution.
is there a way to get that URL? I am using Java and TestNG.
thanks.
Copied from stackoverflow: [https://stackoverflow.com/questions/46306245/get-launchs-url-using-reportportal-agent-java-testng](url)

**Comment by DzmitryHumianiuk** [comment]
@ulmanA 
agent returns `launchID`, right after launch start on server.
and you know `project` from params
you know `endpoint`

append it all together 
`endpoint` + `/ui/#` + `project` + `/launches/all/` + `launchID`
`http://RP_SERVER/ui/#superadmin_personal/launches/all/599afcb39194be00011919d9`


cc @avarabyeu

**Comment by DzmitryHumianiuk** [comment]
@ulmanA could you please send it as a PR?

**Comment by ulmanA** [comment]
I solved it using AspectJ:
```
    /**
     * Save the Launch URL in system property
     * Will be used for printing it to the console
     *
     * @param parameters
     */
    @After("execution(com.epam.ta.reportportal.ws.model.launch.StartLaunchRQ com.epam.reportportal.testng.TestNGService.buildStartLaunchRq(com.epam.reportportal.listeners.ListenerParameters))" +
            "&& args(parameters)")
    public void saveLaunchBaseUrl(ListenerParameters parameters) {
        if (parameters == null) {
            return;
        }
        Mode mode = parameters.getLaunchRunningMode();
        String page = (mode == Mode.DEBUG) ? "userdebug" : "launches";
        System.setProperty("LaunchURL",
                parameters.getBaseUrl() + "/ui/#" + parameters.getProjectName() + "/" + page + "/all/");

    }

 /**
     * add the Launch ID to the Saved URL
     *
     * @param id
     * @param rq
     */
    @After("call(* com.epam.reportportal.service.ReportPortalClient.finishLaunch(..))" +
            "&& args(id,rq)")
    public void saveLaunchURL(String id, FinishExecutionRQ rq) {
        if (id == null || id.equals("null")) {
            return;
        }
        if (!isLaunchIdWasSet && !System.getProperty("LaunchURL", "").isEmpty()) {
            String launchURL = System.getProperty("LaunchURL") + id;
            System.setProperty("LaunchURL", launchURL);
            isLaunchIdWasSet = true;
        }
    }


```

**Comment by avarabyeu** [comment]
starting from 4.x version JVM-based client save launch ID and number in tmp file so you can use it to avoid AOP. As for now, closing.

**Comment by Gulats** [comment]
@avarabyeu, @DzmitryHumianiuk : has the URL template changed? I am seeing a 404 in dev-tools console log
`GET http://reporter.xyz.com/api/v1/xyz-ft/launch/NaN 404 (Not Found)`

on trying to open the following page: `http://xyz-reporter.myntra.com/ui/#xyz-ft/launches/all/9f5fe4f3-3108-419c-b441-7191bfec5f1b`
(where the uuid is fetched from `<project-root>/reportportal.sync` file

ReportPortalUI:  5.3.0

dependencies
```
testCompile "com.epam.reportportal:agent-java-junit5:5.0.0"
compile "com.epam.reportportal:logger-java-log4j:5.0.2"
compile "com.epam.reportportal:client-java:5.0.2"
```
