### ISSUE TITLE
Log message is not expanded if lower than 'level-ERROR'

### ISSUE THREAD

**Issue by iKozzz** [reportportal/reportportal#248]
UI version - 3.3.0

Actual: message block 'rp-table-row' got new css-class 'open' but not expanded on click, if it has css-class another than 'level-ERROR'.

failed for: level-INFO, level-WARN, level-DEBUG, level-TRACE

p.s.
also message is not fully displayed if you switch toggle to "CONSOLE VIEW"

**Comment by evjlobanova** [comment]
Fixed in 3.3.2
