### ISSUE TITLE
Notifications rule for rp.mode

### ISSUE THREAD

**Issue by ulmanA** [reportportal/reportportal#249]
Add notifications rule for the launch mode (`rp.mode` property).
For example, 
send notification only when the launch mode is: DEFAULT

**Comment by DzmitryHumianiuk** [comment]
it should send emails only for launches in DEFAULT.

@evjlobanova could you please trace it in requirements/stories.

@avarabyeu, @pbortnik if it's not, then it's a bug

**Comment by avarabyeu** [comment]
@evjlobanova @DzmitryHumianiuk so finally this functionality is considered as bug, right?

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu right.
emails should not be triggered for **DEBUG** launches

**Comment by evjlobanova** [comment]
@ulmanA a notification constrain for launches in Debug wil be added in 4.0
