### ISSUE TITLE
Error Message does not contain a list of available external bug-track services

### ISSUE THREAD

**Issue by shaburov** [reportportal/reportportal#252]
When using the Issue.ExternalSystemIssue class, in the event of an error, error message does not contain a list of available/registered external bug-track services

```
Caused by: com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 404
Status message: Not Found
Error Message: ExternalSystem with ID 'JIRA' not found. Did you use correct ExternalSystem ID?
Error Type: EXTERNAL_SYSTEM_NOT_FOUND
```

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu ^

**Comment by avarabyeu** [comment]
Duplicate of reportportal/reportportal#360

**Comment by shaburov** [comment]
@avarabyeu @DzmitryHumianiuk  это не дубликат.
Я незнаю ID под которым зарегиcтрирован jira-service в RP.
Нужно переться в WEB консоль и там искть ExternalSystem ID (у меня например 59f20f36a7b11b0001a545a1) для того чтобы закинуть в код TestNGService.
![image](https://user-images.githubusercontent.com/15269131/37352646-c9be051e-26ee-11e8-84cb-eef79484a335.png)

Переоткройте дефект.

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu @DzmitryHumianiuk это не дубликат.
Я незнаю ID под которым зарегиcтрирован jira-service в RP.
Нужно переться в WEB консоль и там искть ExternalSystem ID (у меня например 59f20f36a7b11b0001a545a1) для того чтобы закинуть в код TestNGService.
 
![image](https://user-images.githubusercontent.com/11332788/37356432-012e825a-26f7-11e8-91a9-84dac84b32fe.png)

Переоткройте дефект.

**Comment by avarabyeu** [comment]
don't really understand what you wanted to add? Put the list of available IDs in the error response? How would that help to submit an issue? Error responses are not intended for sharing IDs of existing entities. 
I guess you guys might want to put external system type instead of ID there. It would make sense but require modifications on both client and server side.

**Comment by DzmitryHumianiuk** [comment]
close with respect to #360
