### ISSUE TITLE
When defect type is changed for certain failed test item the URL to this test item will become invalid.

### ISSUE THREAD

**Issue by andrey-patin-1979** [reportportal/reportportal#254]
There is a workaround to change value of "filter.in.issue$issue_type"-URL parameter manually to the changed defect type.

**Comment by evjlobanova** [comment]
@andrey-patin-1979 will be in a 4.0

**Comment by andrey-patin-1979** [comment]
@evjlobanova I think that also could be added UI button to receive such absolute URL (it should be useful when you add link to the failed item manually or send it to someone). But as MVP current solution is good enough.
