### ISSUE TITLE
[UI][Unique bugs table] Invalid link for the test in the "FOUND IN" column

### ISSUE THREAD

**Issue by shaburov** [reportportal/reportportal#255]
Invalid link for the test in the "FOUND IN" column if defect type is "**NO_DEFECT**"
![image](https://user-images.githubusercontent.com/15269131/32070409-df8cef0c-ba94-11e7-81c9-bc38e4c100b0.png)

![image](https://user-images.githubusercontent.com/15269131/32070896-5e48a52e-ba96-11e7-82a8-eb1ebce3fc57.png)

![image](https://user-images.githubusercontent.com/15269131/32071998-d2ce162e-ba99-11e7-8ec0-1de8b48b3268.png)

Errors do not occur if the defect type "**Product Bug**"

![image](https://user-images.githubusercontent.com/15269131/32072142-3c76aa82-ba9a-11e7-900e-23c553529504.png)

**Comment by evjlobanova** [comment]
@shaburov now we are investigating your issue, could you please tell me what RP version are you using now? 
![image](https://user-images.githubusercontent.com/30413511/32651514-5af09c10-c612-11e7-8f11-0ca054949e39.png)

**Comment by shaburov** [comment]
@evjlobanova 
![image](https://user-images.githubusercontent.com/15269131/32662794-c510cadc-c63c-11e7-9f6d-12b67552bcf4.png)

**Comment by DzmitryHumianiuk** [comment]
@shaburov not reproducible with 3.2.1 and 3.3.1

have you tried 3.3.1 UI?

**Comment by shaburov** [comment]
![image](https://user-images.githubusercontent.com/15269131/32951573-707506f8-cbbb-11e7-8e73-c35ebaa43057.png)

![image](https://user-images.githubusercontent.com/15269131/32951581-74e10bb0-cbbb-11e7-8ce6-60c2e86b346f.png)

![image](https://user-images.githubusercontent.com/15269131/32951588-79b8f418-cbbb-11e7-9288-51fe10782834.png)

![image](https://user-images.githubusercontent.com/15269131/32951591-7d4f8164-cbbb-11e7-9ace-b1099e3598b5.png)

**Comment by evjlobanova** [comment]
@please give us a full link from your print screen

**Comment by shaburov** [comment]
From launch : https://rp.stageoffice.ru/ui/#catalog/launches/all|page.page=1&page.size=50&page.sort=start_time%2CDESC/59f23f6ca7b11b0001a55fcf|page.page=1&page.size=50&page.sort=start_time%2CASC/59f23f6da7b11b0001a55fd4|page.page=1&page.size=50&page.sort=start_time%2CASC/59f23fb0a7b11b0001a566da|page.page=1&page.size=50&filter.cnt.name=test_20170526192760&page.sort=start_time%2CASC?page.page=1&page.size=50&filter.cnt.name=test_20170526192760&page.sort=start_time%2CASC&log.item=59f23fb7a7b11b0001a567f1

From Unique bugs table: https://rp.stageoffice.ru/ui/#catalog/launches/all/59f23f6ca7b11b0001a55fcf/59f23f6da7b11b0001a55fd4/59f23fb0a7b11b0001a566da?log.item=59f23fb7a7b11b0001a567f1

**Comment by shaburov** [comment]
@evjlobanova @DzmitryHumianiuk 

![image](https://user-images.githubusercontent.com/15269131/32952424-51808756-cbbe-11e7-8a07-f632cae71af3.png)

![image](https://user-images.githubusercontent.com/15269131/32952474-7c9e0030-cbbe-11e7-8812-b382ee5fc73e.png)

**Comment by evjlobanova** [comment]
@shaburov I suppose we can solve this issue with adding `UniqueID` (http://reportportal.io/docs/A-test-item) to this widget

**Comment by shaburov** [comment]
@evjlobanova 
![image](https://user-images.githubusercontent.com/15269131/32952836-753880da-cbbf-11e7-8e14-e20ae618bec5.png)

**Comment by shaburov** [comment]
@evjlobanova In what version corrected?

**Comment by evjlobanova** [comment]
@shaburov this issue is fixed in 4.0. We are planing a RC of 4.0 tentatively until the end of next week
