### ISSUE TITLE
Notifications: send notification to none user  

### ISSUE THREAD

**Issue by ulmanA** [reportportal/reportportal#262]
Please add option to send notifications to any email and not just to registered users

**Comment by evjlobanova** [comment]
hello!  You can change notification rules by yourself in project setting, where you can add  different emails. There is no restriction that limites a list of receivers. 
![image](https://user-images.githubusercontent.com/30413511/32319707-8c667586-bfcc-11e7-97de-36d376931281.png)

As well this case is described in our documentation on a section [CONFIGURE EMAIL NOTIFICATION  ](http://reportportal.io/docs/Getting-started) item 6. 

If it is not work for you, could you please describe your proposal more  wide?

**Comment by ulmanA** [comment]
Sorry my bad,
It is seem like the problem is in our SMTP Relay

**Comment by evjlobanova** [comment]
@ulmanA  can I close an issue?
