### ISSUE TITLE
RETRY  functionality

### ISSUE THREAD

**Issue by evjlobanova** [reportportal/reportportal#264]
**RETRY:** summary
Description: As a user I can possibility to see all test items on Step level with the same UID and different numbers of execution as a one retried test item (retry). 
A name of retry test is a link that forwards a User to the test item with the latest start time. As a User I can see all logs and attachments of the last test item. Also I have possibility to view all the other test items which are included in this retry with their logs and attachments.

![image](https://user-images.githubusercontent.com/30413511/32381459-c380bc00-c0c3-11e7-92b8-410182a91316.png)

**Acceptance criteria:**
A name of retry should be a link to the test items with the last start time.
Only a test item with the last start time have an issue type. Test items with an earlier start time should not have an issue type.
In the list of test items in a launch view there should be only one test item with the last start time.
A User should have possibility to view all the other test items which are included in this retry with their logs and attachments
Launch statistic should include only statistic of the last item case execution. Previous test items are not considered in statistic.
All test item functions are required for the last retries test item.
For an earlier retried test case user can`t “Post bug” or “Load bug”, Match issue
User can move from one test item to the another (test items with different names) via arrows.
Mobile view is required.

![image](https://user-images.githubusercontent.com/30413511/32381469-cc40ed4c-c0c3-11e7-8847-4f913e5f0122.png)

**Comment by avarabyeu** [comment]
reportportal/service-api#236

**Comment by KursLabIgor** [comment]
We have problem when tests which has been passed after retry has different run type. so in result report i see two tests with same name and with different result. as correctly understood this ticket requested handle this. Am i right? if yes i dont see such feature from my side.

**Comment by evjlobanova** [comment]
@KursLabIgor a feature implementation is in progress now, in plans to release  Retries in 4.0.

**Comment by KursLabIgor** [comment]
@evjlobanova when will be release 4.0 ?

**Comment by evjlobanova** [comment]
@KursLabIgor tentative early in the year

**Comment by KursLabIgor** [comment]
@evjlobanova  thanks!

**Comment by evjlobanova** [comment]
in 4.0

**Comment by VitaliiDolotov** [comment]
Hi guys, is this already implemented? As soon as I can see reportPortal count retries as separate tests but according to the requirements about shouldn't be. Or to achieve this some sort of setup is required?

**Comment by nvborisenko** [comment]
@VitaliiDolotov could you please create a separate issue in https://github.com/reportportal/agent-net-specflow repository with describing how you use scenario retries in specflow? Will think about how to implement it.

**Comment by DzmitryHumianiuk** [comment]
implemented in https://github.com/reportportal/reportportal/issues/363
as 5.0 feature
