### ISSUE TITLE
[Roadmap 4.0] Questions and discussion

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [reportportal/reportportal#265]
You can ask your question here, related to [**Roadmap 4.0 wikipage**](https://github.com/reportportal/reportportal/wiki/Roadmap-4.0)

And up vote with 👍🏻 features, which you want to get earlier.
More _likes_ feature has, more priority it will gain.

Please see list of included features in [**Roadmap 4.0 wikipage**](https://github.com/reportportal/reportportal/wiki/Roadmap-4.0)

**Comment by fasterfish** [comment]
It would be nice to see an approximate implementation time for the [tree view](https://github.com/reportportal/reportportal/wiki/Roadmap-4.0#tree-view).

**Comment by DzmitryHumianiuk** [comment]
@fasterfish aprox as like at Roadmap pic. ~Mar-Apr 2018

**Comment by naiad09** [comment]
How does Retry teature works with @DataProvider and tests with several invocation counts?

**Comment by avarabyeu** [comment]
@naiad09 good question! since we already have draft implementation, may i ask you to provide some simple hello-world like project with mentioned functionality so we can check/adjust/fix retries?

**Comment by LowryTang** [comment]
I'd like to have a Jmeter report. I think many people use Jmeter as Load test.

**Comment by DzmitryHumianiuk** [comment]
@LowryTang,
JMeter is about performance. Adopting of performance testing will bright a lot of testing and functionality.
We still have a lot to implement for regular test automation, hence focus on it for the next milestones.

But we have performance on radar, and will consider it for implementation one day
