### ISSUE TITLE
[Widget]: Component Health Check Widget Table View

### ISSUE THREAD

**Issue by evjlobanova** [reportportal/reportportal#269]
![image](https://user-images.githubusercontent.com/30413511/88919667-31194380-d274-11ea-9704-12b87523cf2f.png)
![image](https://user-images.githubusercontent.com/30413511/88919696-3ecec900-d274-11ea-8097-e7048c84eaf3.png)

**Comment by evjlobanova** [comment]
@JustasM11 , we are discussing a possibility to integrate a new widget. Is this functionality will cover your needs that have been described in the issue #44 ? Would you mind reviewing this issue and giving your vision about it

**Comment by JustasM11** [comment]
@evjlobanova I think such a widget is very good idea and may solve #44

**Comment by evjlobanova** [comment]
Available in version 5.3
