### ISSUE TITLE
Report Portal Email Notification should have "link" configuration

### ISSUE THREAD

**Issue by iKozzz** [reportportal/reportportal#270]
1. Set up email notifications for Launch
2. Receive notification on your email

Inside Email you've got a line:
``` To view it on Report Portal just visit this link. ```

The ```link``` will be something like  ```http://127.0.0.1/#superproject/launches/all/3f07a90bdsg97sdhj6d1a0gh0121123```

I want to replace IP address to defined Domain name:
```https://my.rp.com/#superproject/launches/all/3f07a90bdsg97sdhj6d1a0gh0121123```

**Comment by pbortnik** [comment]
The problem was on a client side. Resolved by writing a correct link in reportportal.properties

**Comment by priyankagarga** [comment]
Is there a way to trigger report portal notification as soon as test fails rather than waiting for the launch to complete? This is to capture live results.
