### ISSUE TITLE
Add way to change the user invitation expiration

### ISSUE THREAD

**Issue by ulmanA** [reportportal/reportportal#271]
We need a way to change the user invitation expiration
(Currently the invitation expired after 24 hours)

It can be added to the Administrate page or the Project Settings or even to the docker-compose.yaml file

Thanks

**Comment by DzmitryHumianiuk** [comment]
I guess, parameter for docker-compose is the best option.

But why you need it longer then 24 hours?

**Comment by ulmanA** [comment]
In our company sometimes its take more than 24 hours to people to read a new e-mail
for example someone has All Day course, or too many new e-mails ...

**Comment by DzmitryHumianiuk** [comment]
@ulmanA is it still actual issue for you?

**Comment by ulmanA** [comment]
Very minor

**Comment by evjlobanova** [comment]
@ulmanA we do not have plans to to change the user invitation expiration. 
Feel free to reopen it, if it is still actual for you.
