### ISSUE TITLE
[UI] [Unique bugs table] Duplicates of tests in the widget

### ISSUE THREAD

**Issue by shaburov** [reportportal/reportportal#272]
![image](https://user-images.githubusercontent.com/15269131/32792427-63b67fc6-c974-11e7-8bde-6b9e80941ac2.png)

![image](https://user-images.githubusercontent.com/15269131/32792349-37c8a420-c974-11e7-955c-8e324cff6688.png)
![image](https://user-images.githubusercontent.com/15269131/32792598-c95b1e5e-c974-11e7-8d42-e1c2a702e3c1.png)

![image](https://user-images.githubusercontent.com/15269131/32792392-4ef2b906-c974-11e7-9a8c-8f1d0f2ee00d.png)

**Comment by evjlobanova** [comment]
@shaburov as i see from your printscrin, the widget works as it has been planned. RP catches unique bugs and shows all test cases from all launches which have such bug.  We will discus with a team a possibility to add Watch latest function for this widget

**Comment by evjlobanova** [comment]
@shaburov is option with latest launches is suitable for you?

**Comment by shaburov** [comment]
@evjlobanova Yes. It would be great.

**Comment by evjlobanova** [comment]
The feature ia available in ver 5.0
