### ISSUE TITLE
Wrong view in case of suite that contains another suites

### ISSUE THREAD

**Issue by ulmanA** [reportportal/reportportal#273]
Hi,
We are using TestNG and we have suite.xml file that contains suite-file tags
So I expect to see in report portal something like:
```{  
   "My_Launch":[  
      "MultiSuite":[  
         "Suite1":[  
            "test1",
            "test2"
         ],
         "Suite2":[  
            "test3",
            "test4",
            "test5",
            "test6",
            "test7",
            "test8"
         ]
      ]
   ]
}
```

And My_Launch will have total of 8 tests

But what actual happens:
```
{  
   "My_Launch":[  
      "MultiSuite":[  
      ],
      "Suite1":[  
         "test1",
         "test2"
      ],
      "Suite2":[  
         "test3",
         "test4",
         "test5",
         "test6",
         "test7",
         "test8"
      ]
   ]
}
```
And the total tests is 9 (it counting the multi-suite as 1 more test)
(see attached screenshoot
![report portal launches](https://user-images.githubusercontent.com/7766743/32828405-a88a79a8-c9f7-11e7-8c8a-91e5d38f4caf.jpg)
![report portal - suites](https://user-images.githubusercontent.com/7766743/32828406-a8b093cc-c9f7-11e7-9228-bb8d074489a6.jpg)

)

so, there is 2 issues here:
1) The visual representation (the child suite is beside the parent suite)
2) The total tests and passed tests calculations are wrong

**Comment by evjlobanova** [comment]
@ulmanA  Use different methods for start your suites: 
* for the `MultiSuite` use POST /{projectName}/item - start root test item;
* for `Suite1` and `Suite2` - POST /{projectName}/item/{parentItem} - start a child test item

Please, try to do this, and share your results with us

**Comment by ulmanA** [comment]
I am not call directly to the API.
I am using the TestNG Listener: com.epam.reportportal.testng.ReportPortalTestNGListener
From the artifact: com.epam.reportportal : agent-java-testng

**Comment by avarabyeu** [comment]
@ulmanA could you please give us some example of your testng.xml file?

**Comment by ulmanA** [comment]
Here:
[Suites.zip](https://github.com/reportportal/reportportal/files/1474826/Suites.zip)

**Comment by ulmanA** [comment]
Sorry closed by mistake

**Comment by pbortnik** [comment]
@ulmanA Hello, do you want to see your root suite as the parent of other suites? How important is to see the root suite?  
The problem is that testNG runs inner suites at first and after then the root one to summarize results. ReportPortal creates items on runtime, so it is difficult to change the tests' structure after inner suites have finished.
The possible solution is to ignore root suite if it has only inner suites. If the root suite has test cases as well, so it could be placed with inner suites on the same structure's level. Does it work for you?

**Comment by ulmanA** [comment]
1) we have project here that run whole tree of suites (suite that have 4 suites that each have few inner suites and so on...).
so with your solution we will lose all that tree (that represent separation by features for example )

2) Maybe you can add ability to update finished test item with new parent?

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu @pbortnik 
please check possibility to updated parents on Finish.
or consider it in statistics, based on PostgreSQL

**Comment by avarabyeu** [comment]
Depends on cbeust/testng#1656

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu can we start automatically master object (startRQ), if child object of it started?

**Comment by avarabyeu** [comment]
@DzmitryHumianiuk doesn't understand. Could you please re-phrase?

**Comment by evjlobanova** [comment]
@DzmitryHumianiuk could you please add more details?

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova @avarabyeu 
as i see, related issue in testNG closed without any code change.
They proposed the solution, without code change.

My question was, can we start parent suite for child suite automatically? (in case if context can give us such details)


@ulmanA can you try testNG 6.13+
and this
https://github.com/cbeust/testng/issues/1656#issuecomment-356477013

**Comment by ulmanA** [comment]
@DzmitryHumianiuk Still the same behavior in TestNG 6.14.3

**Comment by DzmitryHumianiuk** [comment]
@ulmanA could you plz share details on your suites structure at https://github.com/cbeust/testng/issues/1656#issuecomment-356477013

it's testNG related issue, and we can't fix it, until testNG will provide a fix

**Comment by ulmanA** [comment]
Done.

**Comment by DzmitryHumianiuk** [comment]
@ulmanA your are awesome, thank you!
