### ISSUE TITLE
Auto grouping by text of error

### ISSUE THREAD

**Issue by ailjushkin** [reportportal/reportportal#274]
Proposal:

Show similarities report with a counter by a text.

Use case:

1. Run launch analysis.
2. Open investigations list.
3. Click on "duplication analysis report".
4. This report is actually a grouped list of errors with similarity percentage.
5. Each group of errors could be linked with a bug type and/or issue with one click.
6. While linking a group with bug type and issue, there could be review step where you can exclude certain tests from labeling/linking.

This report could look similar to a code duplication analysis.

What do you think? Is that possible from the view of RP architecture?

**Comment by DzmitryHumianiuk** [comment]
this will be done as a part of #259  - sub-launch widgets.

more similar to 
* Issue grouping widget (relevant to  #26 #42 #136 )

**Comment by ailjushkin** [comment]
I appreciate for your answer. Closing this as duplicate.
