### ISSUE TITLE
Nested steps: Summary 

### ISSUE THREAD

**Issue by evjlobanova** [reportportal/reportportal#275]
DESCRIPTION
As a User  I report test with nested steps without statistics.
So that Statistics should calculated only for test items which have statistics. 
Items which do not have statistics should be  stacked up with  their logs on a parent log view.
For that I should report results with flag "hasStats:false". 

![image](https://user-images.githubusercontent.com/30413511/61809181-7a56dc00-ae45-11e9-84f2-80573f08268f.png)

![image](https://user-images.githubusercontent.com/30413511/61809146-690dcf80-ae45-11e9-9e5d-b866649d86b6.png)

Example for Nested Steps: 
https://github.com/reportportal/example-java-TestNG/tree/nested-steps-example

- If agent reports tests item with annotation @Step  , ReportPortal will be viewed such tests as a nested steps
- If a test items has a descendants (that don`t have descendants), his "children" should be viewed as a nested steps

- Statistic will be calculated only for test item with descendants.
- The nested steps do not have defect type
- The nested steps is not calculated in statistics
- Status of test item with nested steps:
  - If all nested steps are passed - Parent item is *passed*
  - If one of nested steps is failed - Parent item is *failed*
  
- Actions can be done only under parent items.
- History line in Log view shows status of a parent test item in different executions
- Search engine is required
- All logs are reflected on a one page without pagination
- Auto Analyzer defines a defect type only for parent item.

**Contains following issues on GitHub:**
#5 Is it possible to have test step annotations like Allure reports have ?
#83 [BDD] Have a report (dashboard) which allows to see test scenarios and related features, and tests statistic
#13 RP makes each keyword as a separate test in launch

**Comment by ailjushkin** [comment]
Hi! Can we uprank this issue due to the  high demand of it?

**Comment by evjlobanova** [comment]
@ailjushkin now we are in the middle of the great moving to React and PostgreSQL. Nested steps is in a plans after all these processes, because any new feature now will be a double work for us.

**Comment by tareqalayan** [comment]
@evjlobanova Hi, in case i am running an instance on mongodb is it possible to upgrade to the new version with react and postgresql?
thanks

**Comment by evjlobanova** [comment]
@tareqalayan there is not new version yet. React and PostgreSQl will be in 5.0 version.

**Comment by amalsgit** [comment]
Is there any update on this feature? This would be a really useful feature to have for us since we write our tests in BDD form with robot framework.

**Comment by evjlobanova** [comment]
Hi, @amalsgit ! We are planning to implement this feature after  version 5.0. Now we are in the middle of the moving to PostgreSQL and React

**Comment by nstbushneva** [comment]
Hello, 

The original link with example (https://github.com/reportportal/example-java-TestNG/tree/nested-steps-example) seems to be broken and can't find any in the repo. Could you please send the valid one if there? =)

**Comment by DzmitryHumianiuk** [comment]
@nstbushneva https://github.com/reportportal/examples-java/tree/nested-steps-example/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/step

will be merged into `master` with v5 release
