### ISSUE TITLE
Keep logs for a long period of time

### ISSUE THREAD

**Issue by lifemanship** [reportportal/reportportal#276]
We need to keep test logs for years. Is it possoble to add custom period of time to keep logs?

**Comment by evjlobanova** [comment]
@lifemanship hi! now we have possibility to choose 2 weeks, 1 month and 3 months. You can choose a period in a settings. 
![image](https://user-images.githubusercontent.com/30413511/32943956-ea82cb96-cb9e-11e7-85d8-02faeffc004a.png)

Could you please clarify, how exactly long you should keep your logs, for what reasons you should do this and how will you use kept logs?

**Comment by pbortnik** [comment]
In the first approximation, we are going to add keeping logs and screenshots forever. Probably, in the nearest future, we will make an opportunity to remove the logs for some period by hands.

**Comment by lifemanship** [comment]
>In the first approximation, we are going to add keeping logs and screenshots forever on own instances. 

@pbortnik It would be enough for us too

**Comment by e-olga** [comment]
The issue is resolved
Will be available in  v 4.0
