### ISSUE TITLE
Dashboard with mapping of test environment timeline on test launches

### ISSUE THREAD

**Issue by ailjushkin** [reportportal/reportportal#278]
Use case: 

Ability to look at launch statistics dashboard in Report Portal in the context of the life stages of the test environment.

Test environment timeline could be manually filled.

**Comment by evjlobanova** [comment]
@ailjushkin we are planning to implement a Status page, you can see it on our RoadMap https://github.com/reportportal/reportportal/wiki/Roadmap-4.0. 

Status page is a default dashboard with an admin information about project. It is the identical page that situated on a admin panel. 
![image](https://user-images.githubusercontent.com/30413511/32951517-45273d7c-cbbb-11e7-807f-69a6ed152eb3.png)

We plan to refactor that page and make more useful and informative for Users. After refactoring a User can get useful widgets, that show a dynamic of launches in the cross-section:
- releases, 
- monthes 
- custom  filter
Is it cover your needs?

**Comment by ailjushkin** [comment]
@evjlobanova For now, it seems that yest.

**Comment by evjlobanova** [comment]
connected with #132
