### ISSUE TITLE
Incorrect working of profile page on Microsoft Edge

### ISSUE THREAD

**Issue by DmitryBets** [reportportal/reportportal#279]
env = Microsoft Edge 38.14393.1066.0
-  UUID value is absent
- after pressing 'genegate'-button nothing happen (no connect with server) 
- Language table is absent
- mail value is absent
- configuration examples are absent. press any examples button = 422 Oops, this page was not found

![untitled](https://user-images.githubusercontent.com/19532715/33025338-bf3d76e8-ce1e-11e7-9e2d-95599de05466.png)

**Comment by evjlobanova** [comment]
@DmitryBets hello! Is it still an actual issue? Can we close it?

**Comment by DmitryBets** [comment]
yep, now it works
best regards, D.B.
