### ISSUE TITLE
[agent-ruby + cucumber] if tags have gap - error returned

### ISSUE THREAD

**Issue by esoskovets** [reportportal/reportportal#28]
rp_tags=["Assemble issues build"] - ERROR
rp_tags=["Assemble_issues_build"] - ok
rp_tags=["issue***", "Assemble_issues_build"] - ERROR
rp_tags=["issue***","Assemble_issues_build"] - ok

**shell command**
> cucumber --tags @build_test HOMEPAGE_URL=http://??? DATABASE=???
> rp_uuid=14808c29-63fb-4eb8-90be-a4b6b83d6d34 rp_endpoint=http://???/api/v1 rp_tags=["Assemble issues build"] rp_project=urspectr rp_launch=issues/??? -f ReportPortal::Cucumber::Formatter

**error log**
> Starting virtual X frame buffer: Xvfb.
> (<unknown>): did not find expected ',' or ']' while parsing a flow sequence at line 1 column 1 (Psych::SyntaxError)
> /usr/local/lib/ruby/2.2.0/psych.rb:370:in 'parse'
> /usr/local/lib/ruby/2.2.0/psych.rb:370:in 'parse_stream'
> /usr/local/lib/ruby/2.2.0/psych.rb:318:in 'parse'
> /usr/local/lib/ruby/2.2.0/psych.rb:245:in 'load'
> /usr/local/bundle/bundler/gems/agent-ruby-4416bda50ea5/lib/reportportal/settings.rb:72:in 'setting'
> /usr/local/bundle/bundler/gems/agent-ruby-4416bda50ea5/lib/reportportal/settings.rb:51:in 'block (2 levels) in initialize'
> /usr/local/bundle/bundler/gems/agent-ruby-4416bda50ea5/lib/reportportal.rb:66:in 'start_launch'
> /usr/local/bundle/bundler/gems/agent-ruby-4416bda50ea5/lib/reportportal/cucumber/report.rb:57:in 'start_launch'
> /usr/local/bundle/bundler/gems/agent-ruby-4416bda50ea5/lib/reportportal/cucumber/report.rb:42:in 'initialize'
> /usr/local/bundle/bundler/gems/agent-ruby-4416bda50ea5/lib/report_portal/cucumber/formatter.rb:32:in 'new'
> /usr/local/bundle/bundler/gems/agent-ruby-4416bda50ea5/lib/report_portal/cucumber/formatter.rb:32:in 'block in initialize'
> Stopping virtual X frame buffer: Xvfb.

**Comment by abotalov** [comment]
Unfortunately, we weren't able to reproduce this issue on Windows and Linux.
We used something like:
```
 bundle exec cucumber --tags @tag rp_tags=["Assemble issues build"] -f ReportPortal::Cucumber::Formatter
```

I tried to do the following in `irb`:
```ruby
YAML.load("[Assemble issues build")
> Psych::SyntaxError:  (<unknown>): did not find expected ',' or ']' while parsing a flow sequence at line 1 column 1
```

So I think that this issue is shell-related and happens because `ENV['rp_tags']` contains either `[Assemble` or `[Assemble issues build]` (hence `did not find expected ',' or ']'` is shown in error message because this YAML is invalid).

So my current assumption is that this issue might be shell-related. Which OS and shell do you use? Could you try to do it in a different shell?

**Comment by esoskovets** [comment]
Sorry for long time reaction. Yes you are right! If I use bash on Ubuntu 15.04 - all is ok (space in tags working well), but when I try to run cucumber in docker container with spaces in tags - error appear.

Sorry for the inconvenience. Issue can be closed.
