### ISSUE TITLE
<system-out> is not recognized when importing junit

### ISSUE THREAD

**Issue by rkumarrb** [reportportal/reportportal#281]
When I try to import junit xml with <system-out> it says invalid json format. If I remove the <system-out> in very first test case alone then it works and imports all but ignores the <system-out> in following test case too.

Could you please have a look at it and also Is it possible to report content of <system-out> to stacktrace section of report portal. 

and I also would like to know what tag in junit xml will be imported to stack trace.

**Comment by avarabyeu** [comment]
@rkumarrb could you please share your report with us.

**Comment by rkumarrb** [comment]
Attached the xml file. In this 2nd test case is having system-out  and system-err but in report portal it shows for first test case.

If I have system-out and system-err in first test case instead of 2nd, Im not able to upload the test case, it shows xml is invalid when try to upload.

[sample.zip](https://github.com/reportportal/reportportal/files/1512264/sample.zip)

**Comment by pbortnik** [comment]
@rkumarrb Thank you for the issue. Fix will be available in 4.0.
