### ISSUE TITLE
Adding new user - password is not being obfuscated

### ISSUE THREAD

**Issue by ludeknovy** [reportportal/reportportal#285]
1. Open dialog for adding new user
2. Password input is not being obfuscated

![image](https://user-images.githubusercontent.com/13610612/33430626-7ceb5d54-d5d1-11e7-9d16-ff27a08118bf.png)

**Comment by DzmitryHumianiuk** [comment]
@ludeknovy not sure it is an issue.
It’s admin page, and admin create user. Copy password to share with new user.

Closing as `Won’t fix`

**Comment by DzmitryHumianiuk** [comment]
@ludeknovy there is another mechanism, called `Invite user`.
server sends special link, which valid for 24h.
User opens this link and see fields for input.
Password and clarification for password hidden under *** in this fields.

**Comment by mikewillard-ableto** [comment]
Where can I find this add user screen? I am not seeing it. I do not want to set up an email server for the invite user feature.

**Comment by DzmitryHumianiuk** [comment]
@mikewillard-ableto https://reportportal.io/docs/Creation-of-project%3Eadd-users-to-project

**Comment by mikewillard-ableto** [comment]
Great, that worked! Thanks for the fast reply
