### ISSUE TITLE
Several tests project in one solution. how should be installed report portal

### ISSUE THREAD

**Issue by KursLabIgor** [reportportal/reportportal#288]
What about case when we have in one solution two and more project for tests. Need to install reportportal extension for each project. in each project will be created their own conf file. but after build conf file can  overwritten. or need rename conf file according to each project?

**Comment by evjlobanova** [comment]
@KursLabIgor please, give more details

**Comment by KursLabIgor** [comment]
ok. 
Lets assume situation when i have project with following structure. We have framework
Solution
|__
     ProjectTests1
|__
     ProjectTests2
|__
     ProjectTests3
|__
     OtherProjectStuff

ProjectTestx - it is different project which has their own logic and technologies. 
So after install report portal for nunit framework it creates ReportPortal.conf. So what is my next steps. Do I need to rename each conf file for each project and make somewhere reference to renamed conf file.  Or i need to have one conf file and this conf file can be placed in any project. 
Thanks

**Comment by evjlobanova** [comment]
@KursLabIgor if you have separate spaces for each project, you can overwrite a  project name by  parameter in a command line

CC @nvborisenko

**Comment by nvborisenko** [comment]
Each project has own output folder (`bin/debug`) and own `ReportPortal.conf` file. You can configure reporting for each project. I don't see conflicts. If you specified one folder as output location for all projects (I believe you know what you do), files are copied from the latest built project.

If you don't want to configure each project separately, you can put all ReportPortal dlls somewhere (with config file and dependencies) and say nunit use the addin from your well-known folder.

**Comment by KursLabIgor** [comment]
sorry, not clear for me. elaborate please.

**Comment by KursLabIgor** [comment]
ok. thanks. that what i want to know.
