### ISSUE TITLE
No run creates in reportportal in case if tests run Jenkins

### ISSUE THREAD

**Issue by KursLabIgor** [reportportal/reportportal#289]
I have tests based on nuint3 framework. I configured and run reportportal, locally run test in debug reason and check that launch creates in reportportal. Then I make commit to repo and Jenkins started build. But what I see that no launch with name specified in Jenkins. log in to VM locally where build run , execute command locally and everything works. 
Where can be a problem? any ideas?

**Comment by KursLabIgor** [comment]
some additional info in case if some one run into same issue: 
jenkins for run file produce following command line `powershell.exe -NonInteractive -ExecutionPolicy ByPass "& 'random_file_name.ps1'"`

**Comment by KursLabIgor** [comment]
indeed problem in command launch type. 
In case if i put all command to file and then start file in following way `powershell.exe  'C:\Users\$$$\Desktop\1.ps1'` no run creates in reportporta. any ideas why?

**Comment by DzmitryHumianiuk** [comment]
@KursLabIgor you are on the right way.
problem is about parameters on command line.

i guess, you should append something in the line.

@nvborisenko @aliaksandrbasau are experts in .net world, they can help

**Comment by KursLabIgor** [comment]
Using Fiddler i see that no outgoing connection to reportportal server, on automation clients, seems like previous my comments can be ignored. Continue investigation.

**Comment by KursLabIgor** [comment]
this is example of file which after all execute jenkins 
`$checkoutFolder = "$ENV:WORKSPACE"
$testDll = "$ENV:TestDll"
$targetDll = "$checkoutFolder\$testDll"
$what_run = "$ENV:what_run"
$report1 = "--result=Result.xml"
$report2 = "--result=ResultN2.xml;format=nunit2"
# Set nunit path test runner
$nunit = "$checkoutFolder\nunit\nunit-console\nunit3-console.exe"
& $nunit $targetDll $report1 $report2 --where $what_run --params=lastRun=$status
exit 0`

**Comment by KursLabIgor** [comment]
Seems like issue in conf file. 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'ReportPortal.NUnitExtension.ReportPortalListener' threw an exception. ---> System.Runtime.Serialization.SerializationException: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''.

Continue investigating.

**Comment by KursLabIgor** [comment]
Could be a problem if element in conf file mixed. make different order from origin example?

**Comment by KursLabIgor** [comment]
issue with configuration of conf file found. but still dont see launches from reportportal side.

**Comment by aliaksandrbasau** [comment]
@KursLabIgor Do you see messages in job output in Jenkins that indicate that the tests started?
If not, then there are issues with running tests in general.
If yes, then it's a RP agent configuration issues. In that case I would check that `ReportPortal.addins` in the directory with `nunit3-console.exe` contains correct path to `ReportPortal.NUnitExtension.dll`.
In general, it would be helpful to see Jenkins job output.

**Comment by KursLabIgor** [comment]
@aliaksandrbasau test from Jenkins runs. 
I'll check path to the listener again. 
`NUnit Console Runner 3.6.0 
 Copyright (C) 2017 Charlie Poole

 Runtime Environment
 OS Version: Microsoft Windows NT 10.0.15063.0
 CLR Version: 4.0.30319.42000

 Test Files
     C:\jenkins\workspace\<folder>\webclient.solution\Output\Client.Auto.Tests.dll
 
 Test Filters
 Where: cat=UWP
 Fixture Start: Assets Add Move Resize Refresh Fixture
 Fixture status: Passed
`
As you can see from log. execution works.

**Comment by KursLabIgor** [comment]
On automation clients listener registered 
[http://prntscr.com/hkpcr1](url)
continue investigating

**Comment by KursLabIgor** [comment]
So actually problem still relevant. If i run from cmd  same command line launch creates into reportportal.
In case Jenkins run same command but via power-shell no run creates. 
Will add to Jenkins command which will show listeners

**Comment by KursLabIgor** [comment]
FOUND ROOT: 
So in cases if nunit run via powershell with option start process using call operator (&) no run creates
https://ss64.com/ps/call.html
I switched to cmd option run from Jenkins and everything works. 
WDYT? is it expected

**Comment by aliaksandrbasau** [comment]
@KursLabIgor I am not sure whether it's expected. In any way the issue doesn't seem to be related to report portal agent. I am glad that you found the root cause.

**Comment by KursLabIgor** [comment]
until now i close issue
