### ISSUE TITLE
Add feature to hide 'Match issues in Launch' link for specified user roles

### ISSUE THREAD

**Issue by OstapJ** [reportportal/reportportal#29]
'Match issues in Launch' link is pretty close to 'resolution button'.
![match_issues_in_launch_link](https://cloud.githubusercontent.com/assets/5707734/21044412/813e7c82-be04-11e6-979f-374bbecede62.png)
Hence we have some cases when someone clicks on the link by mistake and it blocks the whole regression analysis. Since we can't modify the test resolution while auto analysis in progress.

One of possible solutions is to disable this link for certain roles.

**Comment by Iren-Melnyk** [comment]
Hi there!
It's really a suggestion to improve and in our next release, it'll be fixed.

**Comment by DzmitryHumianiuk** [comment]
@OstapJ 
now it will be on different sides of toolbar
![image](https://cloud.githubusercontent.com/assets/11332788/24118113/b634e742-0dbd-11e7-9aec-b245a85d3806.png)
it will reduce the chance of accidental click.

in 3,0

limitation by roles is not the best one.
