### ISSUE TITLE
Launch comparison

### ISSUE THREAD

**Issue by evjlobanova** [reportportal/reportportal#290]
request  from @pskvortsov (slack /QAGuild/ rp)

As a User I want to compare results of different launches. So that I can see a status change of tests with the same UID and can quickly find the test with  unstable behavior and check it.

**Comment by katya13zhe** [comment]
I need the same thing as a User. Right now I have two launches with 46 and 47 failed scenarios accordingly, and I have to look for a new failed scenario manually, which is very painful.

**Comment by thrix** [comment]
+1 comparison between launches would be awesome

**Comment by Witos** [comment]
+1

**Comment by evjlobanova** [comment]
We will add such functionality in the version 5.1:
You will be able to compare results from launch with the latest results from filter.
![image](https://user-images.githubusercontent.com/30413511/76981421-a0d50480-694b-11ea-9d12-c3b730eb9357.png)
![image](https://user-images.githubusercontent.com/30413511/76981518-c3ffb400-694b-11ea-9945-4e969a361257.png)

What do you think about this functionality? 
Does it cover your need?

**Comment by Witos** [comment]
Not bad. 

My proposition - use "Compare" function you have already there:
1. Select runs to compare.
2. Action -> Compare.
3. Nice graphs shown
4. Add "Detail" buttons
5. After pressing this button the details view among selected runs appear, similar to the above one.

**Comment by edyp** [comment]
I agree with @Witos, and in my pov it is more important than comparison on filters level, nevertheless it will be very useful to have both approaches so please consider it.

**Comment by evjlobanova** [comment]
@Witos and @edyp in this approach you can create a filter based on one launch, and compare it with needed one.

The real case for this feature.
For example, different versions are testing. F.e. build: 2 Build: 3 Build:4.
You have got the final test runs for version build:2. You created a filter, which includes launches with the latest results for build: 2.

Then you have started to run tests for version build:3. And you can compare the results of version 3 and the latest results of version 2. 
So that you can understand if your tests have the same behavior in different versions.

So the reason, why we choose such an approach, is flexibility.
A user can compare the results of 2 launches.
Or launch and filter.

Or even more, a user can compare the results of 2 filters.

In version 5.0 we have added a clickable area for widgets which is based on a filter.
For example Overall Statistics widget.
![image](https://user-images.githubusercontent.com/30413511/76962989-4d55bd00-6931-11ea-9f61-519b2f8179e0.png)

It shows summary information about the filter.
When a user clicks on the widget.
Then system redirects the user to the *list view for filter*
![image](https://user-images.githubusercontent.com/30413511/76963068-7d04c500-6931-11ea-9e21-46a0cbd9b282.png)
This view combines test cases from different launches.

And you can also add a compare column to this view.
![image](https://user-images.githubusercontent.com/30413511/77172694-73b15f00-6acf-11ea-8e9a-9bfb7c922af0.png)

I like the @Witos idea, but this nice chart can contain more than two launches. And a comparing table for more than 2 launches can be quite heavy (it is better to say awfully) heavy.

![image](https://user-images.githubusercontent.com/30413511/77173245-4618e580-6ad0-11ea-86f2-0d08cf0f991f.png)


What do you think:))

**Comment by Witos** [comment]
Ok, fine.

**Comment by evjlobanova** [comment]
Approx 1-2 week

**Comment by evjlobanova** [comment]
Connected with #899
