### ISSUE TITLE
Embedded cucumber log attachments are displayed incorrectly via reportportal

### ISSUE THREAD

**Issue by triesz** [reportportal/reportportal#292]
Feeding reportportal with java cucumber tests and attaching various longer strings (like formatted list of cookies, browser console logs etc) like this:

`ScenarioUtil.getScenario().embed(someLongString.getBytes(), "text/plain");`

some of these attachments are missing completely from the log in reportportal, others are mixed up. (I.e. the very first attachment link consistently points to the second attachment.)

locally produced html and json reports look OK.

used versions:
agent-java-cucumber 3.0.1
cucumber-core 1.2.5
selenium-java 3.8.1

Also tried with "text/html" mime but it did not make a difference.

**Comment by pbortnik** [comment]
@triesz 
Could you please reproduce the issue in a new branch somewhere [here](https://github.com/reportportal/example-java-cucumber) ?

**Comment by triesz** [comment]
hi @pbortnik , I did not have permission on that repo so I forked it and created branch here:
https://github.com/triesz/example-java-cucumber/tree/reportportal-issue-292

steps:

1. update reportportal.properties
2. mvn test
3. open result in reportportal
4. open the first attachment

Expected content: "first attachment content"
Actual content: "second attachment content"

**Comment by triesz** [comment]
Have you guys managed to reproduce this? This unfortunately blocks the introduction of reportportal for our cucumber tests as without test artifacts results cannot be analyzed in most cases... :-(

Any idea to work this around somehow?

**Comment by triesz** [comment]
found a workaround: adding this to the reportportal.properties helps:
rp.batch.size.logs = 1

in fact any rp.batch.size.logs value from 1-6 works well. And any value from 7 will reproduce this issue.

Hope it helps!

**Comment by evjlobanova** [comment]
@pbortnik ^^

**Comment by avarabyeu** [comment]
@evjlobanova plz add to 4.2 backlog.

**Comment by avarabyeu** [comment]
@triesz Have you tried to reproduce it with 4х client version?

**Comment by triesz** [comment]
@avarabyeu, yes, issue still occurs with 4x client.
