### ISSUE TITLE
Run duration for/per fixture doesn't equal to overall execution time.

### ISSUE THREAD

**Issue by KursLabIgor** [reportportal/reportportal#298]
We have noticed that all fixtures run 3 h 17. In case if you navigate to fixture level you will see that execution time will much greater than overall time. 

Nunit3 framework
ReportPortal.Client v2.0.0-beta3
ReportPortal.NUnit v 3.3.0-beta1
ReportPortal.Shared v2.0.0-beta1

Current version: API Service: 3.3.1; Service Index: 3.1.1; Jira Service: 3.3.0; Authorization Service: 3.3.0; Service UI: 3.3.2;

**Comment by nvborisenko** [comment]
@KursLabIgor, do you execute tests in several threads?

**Comment by KursLabIgor** [comment]
@nvborisenko we dont have parallel execution. Fixture starts one by one, but again we have retry. could be issue here ?

**Comment by nvborisenko** [comment]
Not sure, any details/screenshots/specifics would be appreciated.

**Comment by KursLabIgor** [comment]
This is screen when all fixture listed
http://prntscr.com/i0kv8e
This is view of LoginLogout fixture 
http://prntscr.com/i0kvkh

We can see that time didnt match in both view.

**Comment by evjlobanova** [comment]
@KursLabIgor is issue still reproducing?

**Comment by KursLabIgor** [comment]
@evjlobanova can't tell you. we don't use RP anymore. i consider can be closed.
