### ISSUE TITLE
Email client is not compatible with Amazon SES

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/reportportal#3]
I use [Amazon SES](https://aws.amazon.com/ses/) service. I configured Report Portal instance to use SMTP server, but RP cannot send emails.

Logs of API service:

> javax.mail.MessagingException: Could not connect to SMTP host: email-smtp.us-west-2.amazonaws.com, port: 465, response: -1
>         at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2042) ~[javax.mail-1.5.4.jar!/:1.5.4]
>         at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:697) ~[javax.mail-1.5.4.jar!/:1.5.4]

It seems current implementation of email client doesn't support SMTPS.

Below is SMTP server details:
Server Name: email-smtp.us-west-2.amazonaws.com
Port: 25, 465 or 587
**Use Transport Layer Security (TLS):    Yes**

**Comment by avarabyeu** [comment]
@nvborisenko supposed to be fixed in 2.7. You can actually test it in our dev environment.

**Comment by avarabyeu** [comment]
Fixed in 2.7

**Comment by nvborisenko** [comment]
Now Report Portal is able to send notifications about finished launches, but cannot send invitations. I guess it is related to issue #40
