### ISSUE TITLE
Add feature to stop 'Auto-analisys'

### ISSUE THREAD

**Issue by nagaeva-anastasia** [reportportal/reportportal#30]

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu is it really possible with current implementation?

**Comment by avarabyeu** [comment]
@DzmitryHumianiuk yes. With current implementation it may leave DB in inconsistent state.

**Comment by DzmitryHumianiuk** [comment]
@nagaeva-anastasia new version of AA will work much quicker.
almost close to real-time.

and this will not affect and block launch for a long time.
will be available with version 4.0

it issue will still affect you, please open new issue for us
