### ISSUE TITLE
Idea: emailing widget or launch report by email

### ISSUE THREAD

**Issue by ailjushkin** [reportportal/reportportal#302]
**Proposal:**

Email certain launch info without printing it to a file.

**Comment by evjlobanova** [comment]
@ailjushkin please tell us what kind information you wanna receive from RP? In 4.0 when you print a dashboard you can save it as a PDF and than send as email. Does it work for you?

**Comment by ailjushkin** [comment]
@evjlobanova thank you, Zhenya, our users requirement is to send it without any additional steps. So the question is can we send it just with one click.

**Comment by evjlobanova** [comment]
@ailjushkin ok, I understand. Could you please clarify if you wanna send only launch info?

**Comment by ailjushkin** [comment]
@evjlobanova First of all the most wanted feature is to send an aggregated information of a certain launch. At least the number of passed and failed tests for each of the test tags.

**Comment by ailjushkin** [comment]
Unfortunately I didn't see a picture of your launch dashboard.

**Comment by ailjushkin** [comment]
@evjlobanova I got new criterias.

Use case:
- filter some results in a certain launch.
- save this information as a file.

Use case:
- filter results of a certain launch.
- range them by a failure count.
- download it as a file or email it directly to a list of emails.

**Comment by DzmitryHumianiuk** [comment]
I see 3 feature here:
1. Trigger email sending with launch info, equal to existing triggered emails (see also #312 #349 )
2. export of filtered content at ListView (test cases view) as a file (XLS)
3. emailing of filtered content at ListView (test cases view)

@ailjushkin plz confirm


@ailjushkin will  #312 #349 help you as a part of 1st feature, mentioned above?

**Comment by evjlobanova** [comment]
I include this request in a scope of #97
