### ISSUE TITLE
When job aborted from Jenkins side RP doesnt catch it and run infinite continues 

### ISSUE THREAD

**Issue by KursLabIgor** [reportportal/reportportal#303]
When job aborted from Jenkins side RP doesnt catch it and run infinite continues. is it correct behavior?

**Comment by evjlobanova** [comment]
@KursLabIgor it is a correct behavior, RP is waiting for the request. As far as the request is not received, the launch saves the previous state and continues running. You can finish your launch manually. But it is better to investigate a reason for job aborting in Jenkins.

**Comment by KursLabIgor** [comment]
ok, got it. thanks
