### ISSUE TITLE
Extra true/false option for Fixed/Not fixed failures

### ISSUE THREAD

**Issue by dmitryyu** [reportportal/reportportal#304]
After investigation of a failure, I can understand that's reason of it is Automation Bug.
I can add the defect type: "Automation Bug" or any other custom defect type.
But it's really not always possible to fix the issue on "the fly", so such failures can be  "Fixed/Not Fixed".

I have tried to use a custom defect type like "Fixed. Automation Bug." and for all fixed tests i added the label with a real reason of a fail and what's fixed. But for the next run I am forced to manually change all "Fixed. Automation Bug" statuses which were automatically detected and categorized. (For instance, pre-staged test-data for a user has been added, but another user doesn't have the test-data)

Thus, **it would be cool to have an extra option (for example, "Fixed" ) which can be set to any failed case, which was fixed.** 

**Pros:**
1. Manual team has a possibility to mark the fail as automation bug - but automation fix will be done later (by automation team). 
2. Automation team can apply quick fixes on the fly by setting the option on, and complex fixes can be done later (probably by other QA). And having a filter by the option will allow to find "Not fixed" failures.
3. The option should not be set during Auto analysis. (but in case of the same fail reason - it would be cool to add something like "this failure have been marked as "Fixed" in prev. launch".
4. Also it's possible for other defect types. For example, System issue - Investigation can be done by QA Engineers, but fixes for it - by devops (and as usually after some days).

Thanks.

**Comment by evjlobanova** [comment]
@dmitryyu hi! we aren't planing to implement such feature in the nearest time. 
But we see two ways how you can act in such situation:
1. In 4.0 we have implemented "Ignore" function, that gives possibility to ignore a test item in Auto-Analysis. So f.e. you can set to the item defect type "Fixed Auto Bug" and set "Ignore in AA". So in a future run this defect type won`t be set to the item.

2. Another way, you can set a standard defect type Auto Bug and also set a tag `fixed`. Then you can filter items by filter easily. And in the future runs you will get just Auto Bug.

Does it work for you?

**Comment by dmitryyu** [comment]
Thank you for the replay, yep it looks possible ib v4.0
In v 3.1 I am using the way you described with some additions. In your case auto analasys will set auto bugs that's true, but for the third+ runs you will get "fixed" autobugs :)  (and younwill be a bit confused if it's fixed or not.) 
For now i am using the way, but after any run I change my custom "Fixed. Autobugs" type to "to investigate" type(and saving a comment).

**Comment by evjlobanova** [comment]
@dmitryyu I need some refinements about this sentence: "auto analasys will set auto bugs that's true, but for the third+ runs you will get "fixed" autobugs " . 
What do you mean? If you use a second way that I have described (a situation when you put a tag `fixed` on a test case and set AutoBug), in all runs of AA you will get an AutoBug, and manually you could put a tag Fixed (if it will be necessary).  Please share with your doubts about this method of solving this issue?

If you want to use Fixed. AutoBug defect type, so soon 4.0.0 will be released, and Ignore in AA functionality solve your problem :)

**Comment by dmitryyu** [comment]
Yep, i didn't understand your way correctly, with the tag "Fixed" it should work fine. Thank you for the response. :)
