### ISSUE TITLE
Build tag doesn't change launch number.

### ISSUE THREAD

**Issue by dmitryyu** [reportportal/reportportal#306]
It looks like it doesn't work. 
From Jenkins, my job starts with the following params:
`-Drp.tags="build:%BUILD_NUMBER%"  //for example build number 123

As a result:
`# 123` will not be used in a launch name,
instead of this, tag `build:123` will be added to the launch.

Looking into the documentation:

> Set of tags for specifying additional meta information for current launch. Format: tag1;tag2;build:12345-6. Tags should be separated by “;”. There are one special tag- build – it should be used for specification number of build for launch.

Current version: API Service: 3.3.1; Service Index: 3.1.1; Authorization Service: 3.3.0; Service UI: 3.3.2;

**Comment by avarabyeu** [comment]
@dmitryyu this is expected behaviour. Build number is actual number of launch with some name in ReportPortal. It cannot be changed.
