### ISSUE TITLE
Filter parameters in URL

### ISSUE THREAD

**Issue by valerius257** [reportportal/reportportal#308]
Return possibility to specify filter parameters in the URL for example https://rp.epam.com/ui/#project/launches/all?filter.has.tags=Tag1%2Tag2
It worked in previous versions and we used this feature to post link with test status on Gitlab merge requests.
It would be very inconvenient to created new filter for every merge request.

**Comment by avarabyeu** [comment]
hi @valerius257. Do you need web page or just json response?

**Comment by evjlobanova** [comment]
@valerius257 ^^

**Comment by valerius257** [comment]
Hi, we need a web page

**Comment by DzmitryHumianiuk** [comment]
will be considered with migration to ReactJS, release 5.0

**Comment by pantosha** [comment]
Will it be implemented?

**Comment by DzmitryHumianiuk** [comment]
@pantosha yes.

**Comment by pthexton** [comment]
We'd really like this feature too but it's difficult to tell now whether it's still on plan, as it's in a 5.9 milestone but it looks like you've changed your version numbering scheme?
