### ISSUE TITLE
Remove limit for cont of 20 widgets per dashboard

### ISSUE THREAD

**Issue by iKozzz** [reportportal/reportportal#31]
It's unable to add more then 20 widgets on 1 dashboard.

Clients might like to have more than this limit

**Comment by DzmitryHumianiuk** [comment]
it might be considered as 50

**Comment by DzmitryHumianiuk** [comment]
@iKozzz limit removed.
Now there is no limit.
Widgets will be loaded as soon as reach visible screen area after scroll
