### ISSUE TITLE
Set up different "superadmin" password

### ISSUE THREAD

**Issue by ailjushkin** [reportportal/reportportal#314]
To be able to have the superadmin with different password during full reinstallation of an instance with a database migration from the old instance to a new one.

**Comment by avarabyeu** [comment]
@ailjushkin should be fixed in 4.0.

**Comment by pbortnik** [comment]
@avarabyeu Yes, from 4.0 the admin and default user profiles are initialized only on the first installation

**Comment by ailjushkin** [comment]
Thank you, guys

**Comment by pbortnik** [comment]
@ailjushkin is it ok for you? can we close the issue?
