### ISSUE TITLE
Bad request. The importing file has invalid format. 'There are invalid xml files inside.

### ISSUE THREAD

**Issue by bolatbekb** [reportportal/reportportal#317]
Can not load file.
[jUnitUnit0.zip](https://github.com/reportportal/reportportal/files/1634112/jUnitUnit0.zip)

**Comment by evjlobanova** [comment]
@pbortnik Pavel, please take a look

**Comment by pbortnik** [comment]
@bolatbekb While investigating the issue i found out such tag <warning> that is not described anywhere in xunit format. Is the information in this tag important? Do we need to put it into item's logs as a warn log?

**Comment by pbortnik** [comment]
Resolution: <warning> is saved as WARN log. Importing doesn't stope if face a unknown tag.
