### ISSUE TITLE
Statistics are missing if there is "BeforeSuite"

### ISSUE THREAD

**Issue by ulmanA** [reportportal/reportportal#318]
I execute the same TestNG suite file
the only different is that I added @BeforeSuite method.
and the view has been changed.
After adding the @BeforeSuite I loose the statistics on the sub-suite view (those are tests tags in the suite.xml file)
Without BeforeSuite:
![without beforesuite](https://user-images.githubusercontent.com/7766743/34994171-5605f03a-fadb-11e7-96cf-68949a10a4a2.jpg)

With BeforeSuite:
![with beforesuite](https://user-images.githubusercontent.com/7766743/34994183-5efa1c16-fadb-11e7-86e5-1a0b0fcadef2.jpg)

The suite.xml:
![image](https://user-images.githubusercontent.com/7766743/34994347-d903b03a-fadb-11e7-8f26-9c561651b1cf.png)

**Comment by pbortnik** [comment]
What version of the agent do you use?

**Comment by ulmanA** [comment]
agent-java-testng
version: 3.0.6

**Comment by pbortnik** [comment]
@ulmanA 
Cannot reproduce with latest 4.0.0 version testng and 4.0.0 RP.
So, it seems to be fixed. 
Could you please try the latest versions and check the issue

**Comment by ulmanA** [comment]
Yes it has been fixed :)
![image](https://user-images.githubusercontent.com/7766743/35775096-f19c5062-098a-11e8-99a8-ad17cd6e732f.png)

Closing the issue
