### ISSUE TITLE
It will be good feature in case if we want generate email notification via API by specified rule

### ISSUE THREAD

**Issue by KursLabIgor** [reportportal/reportportal#319]
Actually we need to generate report for merged run. Email notification catch only finish events. Our needs that we have three different run , than merge them and want to generate email. As i see such flow not possible. That's why we need to get ability send email notification with result after merge action for ended runs. 
Now trying make some kind of workaround via API calls.
This is enhanced request.

**Comment by DzmitryHumianiuk** [comment]
exactly the case
#349 

closing as duplicate
