### ISSUE TITLE
Failed to update password : Incorrect Request

### ISSUE THREAD

**Issue by iKozzz** [reportportal/reportportal#32]
Front End: 
Failed to load resource
 `/api/v1/user/password/reset` `400`

`Fetching scripts with an invalid type/language attributes is deprecated and will be removed in M56, around January 2017. See https://www.chromestatus.com/features/5760718284521472 for more details.
scripts.d34776b3.js:1 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
EQCSS.load @ scripts.d34776b3.js:1
https://your.company.com/api/v1/user Failed to load resource: the server responded with a status of 401 ()
https://your.company.com/epam/externalServices.js Failed to load resource: the server responded with a status of 404 ()
https://your.company.com/api/v1/user/password/reset Failed to load resource: the server responded with a status of 400 ()
scripts.d34776b3.js:1 POST https://your.company.com/api/v1/user/password/reset 400 ()
send @ scripts.d34776b3.js:1
ajax @ scripts.d34776b3.js:1
o @ scripts.d34776b3.js:1
ct @ scripts.d34776b3.js:1
submitChangePass @ scripts.d34776b3.js:1
n @ scripts.d34776b3.js:1
dispatch @ scripts.d34776b3.js:1
y.handle @ scripts.d34776b3.js:1`

Backend:
`2016-12-12 18:14:02.263 ERROR 1 --- [-8080-exec-2900] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Validation failed for argument at index 0 in method: public com.epam.ta.reportportal.ws.model.OperationCompletionRS com.epam.ta.reportportal.ws.controller.impl.UserController.resetPassword(com.epam.ta.reportportal.ws.model.user.ResetPasswordRQ), with 1 error(s): [Field error in object 'resetPasswordRQ' on field 'uuid': rejected value [null]; codes [NotNull.resetPasswordRQ.uuid,NotNull.uuid,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [resetPasswordRQ.uuid,uuid]; arguments []; default message [uuid]]; default message [may not be null]]`

**Comment by e-olga** [comment]
Added to RP backlog

**Comment by DzmitryHumianiuk** [comment]
fixed
#EPMRPP-23252
