### ISSUE TITLE
Most Failed tests Widget. Improvement

### ISSUE THREAD

**Issue by evjlobanova** [reportportal/reportportal#320]
**Improvements:**
- Increase a number of launches for the Most failed test cases: more than 150 items;
- Increase a number of shown items on the widget:  more than 20 _(f.e. show all failed tests or make this number configurable)_
- Show an info about failed test case o the widget: Defect type, Description, Date

(request from Serhii  Zharskyi)

**Comment by Oleksii-kh89** [comment]
The possibility for such improvements is investigated
