### ISSUE TITLE
Make startTestItemRQ in API 4.x case insensitive

### ISSUE THREAD

**Issue by fasterfish** [reportportal/reportportal#322]
Could you please make flag values in startTestItemRQ case insensitive (key and value)?

"parameters": [
    {
      "key": "string",
      "value": "string"
    }
  ]

This is necessary so that the client-net (C#) can use the Dictionary<string, string>, instead of the List<KeyValuePair<string, string>>.

**Comment by pbortnik** [comment]
@avarabyeu 
possible solution is to make an object mapper accepting case insensitive properties
https://fasterxml.github.io/jackson-databind/javadoc/2.5/com/fasterxml/jackson/databind/MapperFeature.html#ACCEPT_CASE_INSENSITIVE_PROPERTIES

**Comment by avarabyeu** [comment]
@pbortnik i would rather make them lower-case explicitly on the server. Moving this to client side is good idea in general, but nobody can guarantee that all clients follow the rule (not only java ones).

**Comment by pbortnik** [comment]
https://github.com/reportportal/service-api/pull/278

**Comment by fasterfish** [comment]
Thank you
