### ISSUE TITLE
Allow Admin to Edit, unShare(maybe), Delete shared filters

### ISSUE THREAD

**Issue by iKozzz** [reportportal/reportportal#33]
Let Admin to make changes for shared filters

**Comment by DzmitryHumianiuk** [comment]
pretty reasonable

**Comment by iKozzz** [comment]
Also can be implemented to Dashboards and widgets

**Comment by DzmitryHumianiuk** [comment]
@iKozzz 
Done.
Admin/PM can delete shared widgets and dashboards at project.
in 3.0
