### ISSUE TITLE
Launch list statistics.

### ISSUE THREAD

**Issue by ailjushkin** [reportportal/reportportal#331]
Improvement proposal:

The Failure Frequency column.

Use case:

- Open a launch.
- Filter tests by a criteria.
- Click on the Fail Frequency column to sort cases from the most frequently failed to the less failed ones.

Common idea:
To get filtered tests cases sorted by failures in one launch.

**Comment by evjlobanova** [comment]
@ailjushkin do you use Most failed test cases widget for this reasons now?

**Comment by ailjushkin** [comment]
@evjlobanova hi, it's not for to our needs, we need to filler this list and open it in one certain launch. Widget does not have this functionality

**Comment by evjlobanova** [comment]
@evjlobanova so could you please told me a business value of this filtering? What do you want to do with this list? Could you please describe me a whole use case?

**Comment by ailjushkin** [comment]
Closing, because seems like the widget fits to our needs, we need to split launches to separate projects.
