### ISSUE TITLE
RP v3:  C#+nunit3 tests which are fails due exception in [OneTimeSetUp] section didn't appears in RP as fails and in total count. But nunit recognize them as fails and show correct run summarry

### ISSUE THREAD

**Issue by KursLabIgor** [reportportal/reportportal#335]
Actually i' not sure is it expected behavior. 
Test Run Summary
  Overall result: Failed
  Test Count: 57, Passed: 21, Failed: 36, Warnings: 0, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 0, Errors: 36, Invalid: 0
  Start time: 2018-01-24 13:22:29Z
    End time: 2018-01-24 13:55:26Z
    Duration: 1977.052 seconds

Inside RP i see only passed and total count didn't match to nunit. 
Here is example of project structure: 
BaseFixture{
[OneTimeSetUp]
method1{
///code
}
}
TestFixture : BaseFixture{

[OneTimeSetUp]
override method1{
//code
here is error 
}
}

**Comment by evjlobanova** [comment]
@nvborisenko could you please take a look on this issue?

**Comment by DzmitryHumianiuk** [comment]
fixed?

**Comment by nvborisenko** [comment]
Fixed in v3.3.5
