### ISSUE TITLE
Show attachment's message/title  on the gallery

### ISSUE THREAD

**Issue by ulmanA** [reportportal/reportportal#338]
Hi
on the gallery of the attachments the titles are missing
this text is importent for understand what is the purpose of the attachment.
for example,
- Test has few screenshots and the title said on which test's phase there was taken.
- Test with few log files attached. each came f4om different component of the testesd application.

thanks!

**Comment by evjlobanova** [comment]
the same request from Sergey Mishanin (via skype)

**Comment by evjlobanova** [comment]
duplicate of #665
