### ISSUE TITLE
OAuth App on GitHub requires the user scope instead of read:user

### ISSUE THREAD

**Issue by OstapJ** [reportportal/reportportal#339]
Report Portal asks a read-write permissions on GitHub user profile.
The suggestion is to reduce permissions to read:user.
![image](https://user-images.githubusercontent.com/5707734/35436338-b3a16dd8-0296-11e8-9c43-6c55735cf050.png)

Link to config file.
https://github.com/reportportal/service-authorization/blob/master/src/main/resources/application.yaml

**Comment by avarabyeu** [comment]
@evjlobanova plz add to 4.2

**Comment by avarabyeu** [comment]
@e-olga could you please close it as soon as testing is done

**Comment by e-olga** [comment]
Testing is finished.
