### ISSUE TITLE
Junit - display capabilities

### ISSUE THREAD

**Issue by ludeknovy** [reportportal/reportportal#340]
I would be great if RP could display capabilities:

` <property name="capabilities" value="ie.11"/>`

Ideally on launches overview.

Thus it would be obvious on which browser given test has failed.

**Comment by evjlobanova** [comment]
@ludeknovy hello! do you add browser name in a tags now?

**Comment by ludeknovy** [comment]
@evjlobanova hello! What do you mean by ` add browser name in a tags` ?

**Comment by DzmitryHumianiuk** [comment]
@ludeknovy 
Here how it works:
- send it as tag for launch
- send it as a part of description

the only thing you need is to extend listener, and provide this day either into the `reportportal.properties`, or via command line `-Drp.tags=ie.11`

**Comment by DzmitryHumianiuk** [comment]
@ludeknovy did it help you?

**Comment by ludeknovy** [comment]
@DzmitryHumianiuk unfortunatelly not :/. I do upload my results using import api endpoint

**Comment by DzmitryHumianiuk** [comment]
@ludeknovy integration did not work properly for you?
