### ISSUE TITLE
Unable to filter launches by a launch id

### ISSUE THREAD

**Issue by ailjushkin** [reportportal/reportportal#344]
**The problem:** 

Each launch is represented by a launch name which consists of two things: a name and an id of the launch. Meanwhile users read this name as a whole thing. They want to find certain launch by its unique id.

**For instance:**

`Launch name: cnt = 257`

This filter will not work.

**Comment by evjlobanova** [comment]
@ailjushkin this function will be in 4.0.0 (#22)
