### ISSUE TITLE
Exception encountered unloading application domain with agent-net-specflow and nunit3-console 3.8.0

### ISSUE THREAD

**Issue by fasterfish** [reportportal/reportportal#345]
Given I have .net solution with next packages:
```
<packages>
  <package id="Castle.Core" version="4.2.1" targetFramework="net45" />
  <package id="IIS.Microsoft.Web.Administration" version="8.5.9600.17042" targetFramework="net45" />
  <package id="MSBuildTasks" version="1.5.0.235" targetFramework="net45" developmentDependency="true" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net45" />
  <package id="NLog" version="4.4.12" targetFramework="net45" />
  <package id="NUnit" version="3.9.0" targetFramework="net45" />
  <package id="NUnit.ConsoleRunner" version="3.8.0" targetFramework="net45" />
  <package id="ReportPortal.Client" version="1.2.9" targetFramework="net45" />
  <package id="ReportPortal.NLog" version="1.1.8" targetFramework="net45" />
  <package id="ReportPortal.Shared" version="1.4.3-beta-1" targetFramework="net45" />
  <package id="ReportPortal.SpecFlow" version="1.2.2-beta-7" targetFramework="net45" />
  <package id="RestSharp" version="105.2.3" targetFramework="net45" />
  <package id="Selenium.Support" version="3.8.0" targetFramework="net45" />
  <package id="Selenium.WebDriver" version="3.8.0" targetFramework="net45" />
  <package id="Selenium.WebDriver.IEDriver" version="3.8.0" targetFramework="net45" />
  <package id="SpecFlow" version="2.2.1" targetFramework="net45" />
  <package id="SpecFlow.CustomPlugin" version="2.2.1" targetFramework="net45" />
  <package id="SpecFlow.NUnit" version="2.2.1" targetFramework="net45" />
  <package id="TestStack.White" version="0.13.3" targetFramework="net45" />
</packages>
```
When I execute any scenario on windows server 2008r2
Then test should successfully executed
And nunit3-console should be exit correctly

But at the end of the nunit3-console runner, I see the following:
NUnit.Engine.NUnitEngineUnloadException : Exception encountered unloading application domain
----> NUnit.Engine.NUnitEngineException : Exception encountered unloading application domain: Ошибка при выгрузке домена приложения. (Исключение из HRESULT: 0x80131015)
Application domain name: domain-
Application domain BaseDirectory: C:\Tests

And nunit3-console exited with error code -5.

**Comment by nvborisenko** [comment]
It seems this is related to nunit itself: https://github.com/appveyor/ci/issues/1812

**Comment by fasterfish** [comment]
@nvborisenko in progress state

**Comment by nvborisenko** [comment]
@fasterfish cannot reproduce it. My packages:
<package id="NUnit" version="3.9.0" targetFramework="net45" />
  <package id="NUnit.Engine.Api" version="3.8.0" targetFramework="net45" />
  <package id="ReportPortal.Client" version="2.0.0" targetFramework="net45" />
  <package id="ReportPortal.Log4Net" version="1.1.5-beta2" targetFramework="net45" />
  <package id="ReportPortal.NUnit" version="3.3.0-beta2" targetFramework="net45" />
  <package id="ReportPortal.Shared" version="2.0.0-beta4" targetFramework="net45" />

Could you please upgrade packages and try to reproduce the issue?

**Comment by evjlobanova** [comment]
@fasterfish ^

**Comment by fasterfish** [comment]
@nvborisenko, @evjlobanova, this problem in nunit-console project ([https://github.com/nunit/nunit-console/issues/371](https://github.com/nunit/nunit-console/issues/371)).
