### ISSUE TITLE
RP 3  Unable to perform Edit defects for tests with status interrupted

### ISSUE THREAD

**Issue by KursLabIgor** [reportportal/reportportal#346]
Tests with status interrupted cant be set defect type. 
C# + nunit3. Such test gets status in case they stop due time out.

**Comment by evjlobanova** [comment]
@KursLabIgor Could you please detail the reason why you  want to set a defect type for interrupted tests. Might they have a different reasons for interruption? Or there is only  in case of time out.

**Comment by KursLabIgor** [comment]
@evjlobanova in our case they interrupted due time out, and this time out cause defect , in case if it fails due other reason it is ok. but if know that time out caused problem we want to specify what exactly it was the problem

**Comment by evjlobanova** [comment]
@KursLabIgor for this case in version 5.0 we added a status change feature.
In this case, you will be able to change status from Interrupted to Failed and then add a defect type.

Does it work for your case?

**Comment by evjlobanova** [comment]
Feel free to reopen, if your solution doesn`t resolve your problem
