### ISSUE TITLE
Print logs using monospace font, reduce interval between lines, remove checkerboard for lines

### ISSUE THREAD

**Issue by JustasM11** [reportportal/reportportal#35]
Compare RP logs:
![rp_example](https://cloud.githubusercontent.com/assets/12593214/21141743/d6b776c0-c14f-11e6-86b7-083425320be4.png)
with Robot Framework logs:
![robot_example](https://cloud.githubusercontent.com/assets/12593214/21141741/d53396c6-c14f-11e6-8327-8bc336679bc6.png)
And less:
![less_example](https://cloud.githubusercontent.com/assets/12593214/21141768/ffcac0ee-c14f-11e6-8c05-4f25ef28254e.png)

**Comment by JustasM11** [comment]
Gateway Service: 2.6.0;UI Service: 2.6.0;Rally Service: 2.6.0;Authorization Service: 2.6.0;API Service: 2.6.0;Registry Service: 2.6.0;

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/reportportal/issues/43

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 monospace - done.
available with 3.0

_intervals and checkerboards_ will be done with #43
