### ISSUE TITLE
Ability to merge retried test items in deep merge

### ISSUE THREAD

**Issue by fasterfish** [reportportal/reportportal#354]
Given I have several identical launches
When I try to deep merge them
Then I want to be able to merge test items with retry option

For example:
![screenshot_1](https://user-images.githubusercontent.com/18389889/36086448-445f5ff6-0fee-11e8-82dd-ecfa552146a5.png)

If i check this and the launches contains some test items with retry field = true, then these tests should be merged.

**Comment by evjlobanova** [comment]
@fasterfish this feature is close to Rerun function #264

**Comment by fasterfish** [comment]
@evjlobanova thank you

**Comment by Shakevg** [comment]
@evjlobanova Could you clarify is it possible to merge 2 existing closed launches with retry logic? And how to perform it if it is possible?

**Comment by evjlobanova** [comment]
For now no, you can only use rerun fuctionality
