### ISSUE TITLE
RP v3 : Widget for most failing test shows fixture and test 

### ISSUE THREAD

**Issue by KursLabIgor** [reportportal/reportportal#356]
http://prntscr.com/ie2fc2

highlighted on snapshot it is fixtures. 
nunit 3 + C#
Problem described in summary.

**Comment by evjlobanova** [comment]
@KursLabIgor widget aggregates info about items on the different levels, doesn`t it? If it does, please tell us, do circled fixtures have descendants?

**Comment by evjlobanova** [comment]
@KursLabIgor ^

**Comment by KursLabIgor** [comment]
please close issue, not relevant for any more.
