### ISSUE TITLE
Support proxy in Java client

### ISSUE THREAD

**Issue by andrei-khveras** [reportportal/reportportal#357]
It looks like [proxy settings](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html) provided via VM arguments as described in [RP documentation](http://reportportal.io/docs/JVM-based-clients-configuration) don't work.
It would be great to have any easy enough option to provide proxy params to Java client so tests started behind corporate proxy can log their execution results to the ReportPortal.

**Comment by avarabyeu** [comment]
Proxy can be enabled via manual http client configuration. Please, refer this example to see how to provide agent with customized client:
https://github.com/reportportal/example-java-TestNG/blob/master/logback/src/main/java/com/epam/rp/tests/extension/ParameterizedTest.java#L47

Please, let us know if issue can be closed.
