### ISSUE TITLE
Idea: Log warnings when project name doesn't exist

### ISSUE THREAD

**Issue by sinwat** [reportportal/reportportal#358]
We had an issue when no reports were submitted because of small typo in project name (config file). Used '_' instead of '-'.
That would be great to see some kind of warning message in logs, that we try to use unexisted project name. Could save us hell of a time :)

Thanks!

**Comment by DzmitryHumianiuk** [comment]
@pbortnik @avarabyeu 
make a call to RP, if project exists before launch start.
OR
return error with message then project doesn't exist on luanchStart

and output it into console.
with 

```
 _    _______ _____ _   _ _____  ____________ _____   ___ _____ _____ _____ 
| |  | | ___ \  _  | \ | |  __ \ | ___ \ ___ \  _  | |_  |  ___/  __ \_   _|
| |  | | |_/ / | | |  \| | |  \/ | |_/ / |_/ / | | |   | | |__ | /  \/ | |  
| |/\| |    /| | | | . ` | | __  |  __/|    /| | | |   | |  __|| |     | |  
\  /\  / |\ \\ \_/ / |\  | |_\ \ | |   | |\ \\ \_/ /\__/ / |___| \__/\ | |  
 \/  \/\_| \_|\___/\_| \_/\____/ \_|   \_| \_|\___/\____/\____/ \____/ \_/  
                                                                            
                                                                            
```

**Comment by avarabyeu** [comment]
>make a call to RP, if project exists before launch start.
it does not make sense since reportportal respond with error if case project doesn't exist. The error should be shown in the logs as regular log entry. If it isn't, please, submit bug

**Comment by DzmitryHumianiuk** [comment]
@sinwat main question: is there any type of log that project is incorrect, or there is not any type of log?

**Comment by avarabyeu** [comment]
@nvborisenko cc'ing Nikolay who is main contributor for .NET

**Comment by evjlobanova** [comment]
@nvborisenko Nikolay, could you please take a look on this issue?

**Comment by nvborisenko** [comment]
The initial issue is specific to specflow plugin, we don't see any console output from the agent. Tracking this issue as a separate https://github.com/reportportal/agent-net-specflow/issues/27.
