### ISSUE TITLE
Cannot comment on result using monospace, code tag doesn't work also

### ISSUE THREAD

**Issue by JustasM11** [reportportal/reportportal#36]
Before submit:
![before_submit](https://cloud.githubusercontent.com/assets/12593214/21142110/ad2f8002-c151-11e6-815c-c1e5b41ea92a.png)

After submit:
![after_submit](https://cloud.githubusercontent.com/assets/12593214/21142112/ae6121ba-c151-11e6-9f56-ada7b20d6971.png)

Expected result:
Newlines are preserved, I can also set monospace font for text

**Comment by JustasM11** [comment]
Gateway Service: 2.6.0;UI Service: 2.6.0;Rally Service: 2.6.0;Authorization Service: 2.6.0;API Service: 2.6.0;Registry Service: 2.6.0;

**Comment by lexecon** [comment]
Fix in 3.0
