### ISSUE TITLE
[Feature request] Kubernetes deployment

### ISSUE THREAD

**Issue by noadmin** [reportportal/reportportal#362]
It will be nice to have chart for helm to make able deploy reportportal on Kubernetes, not only in swarm.

**Comment by DzmitryHumianiuk** [comment]
We need a k8s expert for this :)
Don't have one in the team.

@noadmin can you contribute into this?

**Comment by DzmitryHumianiuk** [comment]
@sayems we have no k8s expertise in the team.

And, maybe, only @avarabyeu can help you with troubleshooting.
ask here, or join our slack chat: https://reportportal-slack-auto.herokuapp.com/

**Comment by sayems** [comment]
Hi @avarabyeu, I successfully got ReportPortal running on Kubernetes cluster, but I am having an issues logging into ReportPortal. I think I am missing something in Kubernetes Charts for ReportPortal. Would appreciate it if you get a chance to look at it and help us out. Thanks

ReportPortal Kubernetes Charts
https://github.com/sayems/reportportal-charts/tree/master/templates

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/kubernetes
