### ISSUE TITLE
RE-RUN Launch functionality (multi-threaded execution in one launch)

### ISSUE THREAD

**Issue by evjlobanova** [reportportal/reportportal#363]
**RERUN** : Summary

**This features (available from clients with version 5+) allows:**
1. report launch, executed in multi-threads in one physical launch in RP
2. re-run results of tests on top existed tests (replace them)

**Wiki:**
https://github.com/reportportal/client-java/wiki/How-to-aggregate-Multi-thread-process-execution-in-one-launch

**Description**: 
As a user I can possibility to report results of a new launch to the already existing launch and update the earliest launch with the recent results. The process is called Rerun (Russian localization is “Перезапуск”).. 
The RERUN process is shown on a scheme. 
 
![image](https://user-images.githubusercontent.com/30413511/65167047-7a8ce580-da4a-11e9-8cdd-939c300bf010.png)

![image](https://user-images.githubusercontent.com/30413511/65167079-8a0c2e80-da4a-11e9-974a-c6b4da771e0d.png)

![image](https://user-images.githubusercontent.com/30413511/65167164-b2942880-da4a-11e9-814f-928413863ccf.png)

**Acceptance criteria:**
WS should define in which launch the result should being reported
The uniqueness of the test item is determined by UID.
There should be symbol for rerun launch in All launches list.
In case of rerun of several Step Level items with the same UID, there should be viewed the test item with the latest start time as retry.
Test items of Step level lose their defect type and these items shouldn`t be taken into account in statistic.
The status of rerun test items of different steps are determined by items with the latest start time.

**HOW RERUN LAUNCH**
**If you want to rerun the last launch - Specify in a Property file:**
rp.rerun=true

**If you want to rerun the chosen launch - Specify in a Property file:**
rp.rerun=true
rp.rerun.of=UUID launch

PS:
You can find UUID in console
![image](https://user-images.githubusercontent.com/30413511/65754009-d0cbe980-e118-11e9-8a2c-41fc527f6700.png)

**Comment by evjlobanova** [comment]
#13

**Comment by evjlobanova** [comment]
#264

**Comment by DzmitryHumianiuk** [comment]
#296

**Comment by vitali-sonchyk-epam** [comment]
Is any info available regarding the approximate time of feature realization?

**Comment by DzmitryHumianiuk** [comment]
@vitali-sonchyk-epam we will start right after 5.0
5.0 is ~~2 months

**Comment by Balamurugan-R** [comment]
When this functionality is available?

**Comment by evjlobanova** [comment]
@Balamurugan-R we will start right after 5.0. Approximate date for 5.0 is flexible, we suppose, that it should be in April 19 (+/-)

**Comment by mdilovar** [comment]
Is there updated ETA for this functionality ?

**Comment by DzmitryHumianiuk** [comment]
@mdilovar it already in. but not tested properly.
both for version 4 and version 5.

**In version 4.x**
put flag `rp.rerun=true` in property file or add `-Drp.rerun=true` in command line.
Agent will start process and create temporary file and temporary folder with `launchID`.
If other thread will find this file, it will reuse shared ID of launch to post results into it.
Results will be stored the same way like if you do [Linear Merge](https://reportportal.io/docs/Operations-under-launches%3Emerge-launches)

**In version 5.0**
put flag `rp.rerun=true` in property file or add `-Drp.rerun=true` in command line.
Agent will make API call and ask for launch with the same name. If no - create new.
If yes - will take `launchID` to post data into it.
Data will be posted equal to Deep Merge.
But re-executed tests will be pushed as Re-Tries for original test cases


ETA for version 5 is early October 2019

**Comment by evjlobanova** [comment]
https://github.com/reportportal/client-java/wiki/How-to-aggregate-Multi-thread-process-execution-in-one-launch

**Comment by DzmitryHumianiuk** [comment]
**Configure launch re-run**
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/rerun.md

**Configure multi-threaded execution to be collected in one launch:**
https://github.com/reportportal/client-java/wiki/How-to-aggregate-Multi-thread-process-execution-in-one-launch
