### ISSUE TITLE
The last logon for ldap users is not work correctly

### ISSUE THREAD

**Issue by fasterfish** [reportportal/reportportal#365]
Given I have reportportal instance with ldap users
When user log in to reportportal
Then last login time should be change

In my case the user last login time are equals to registration time (http://rp.address/ui/#administrate/users)

**Comment by evjlobanova** [comment]
https://github.com/reportportal/service-authorization/pull/94

**Comment by evjlobanova** [comment]
Fixed and verified.
Will be available in the final version 5.0
