### ISSUE TITLE
Bulk delete of linked issues

### ISSUE THREAD

**Issue by fasterfish** [reportportal/reportportal#366]
In our case we have too many failed test cases (from 300 to 400) with wrong investigation (type of defect and linked bugs from bts). 

To return the launch to the initial state takes a very long time, so we ask you to add a button to clear the launch from the defects (AB, PB, etc.) and the associated defects.

**Comment by evjlobanova** [comment]
@fasterfish you want to have bulk operation to remove defect type, linked bug and comment, do you?

**Comment by fasterfish** [comment]
@evjlobanova yep

**Comment by fasterfish** [comment]
@DzmitryHumianiuk when the number of tests exceeds the maximum page limit (300), these actions will have to be repeated at least one more time.

**Comment by DzmitryHumianiuk** [comment]
@fasterfish that's right.
but even in such situation, it's much better then click on by one.

The root of the problem is ML, which learns at first 7 iterations.
This issue will not be actual pretty soon,
so i don't see any background to add special `Reset` button

**Comment by fasterfish** [comment]
@DzmitryHumianiuk I agree with you
