### ISSUE TITLE
[v4][ACTIVE DIRECTORY] User with login already exists

### ISSUE THREAD

**Issue by shaburov** [reportportal/reportportal#367]
After moving to version 4.0.0, I did not successfully pass authentication using the active directory account in browsers that previously did not have authorization in the reportportal.

**Precondition**:
mongo is installed on a separate KVM
Active Directory is installed

**Steps**:
**1**. [run docker-compose v.3 +](https://gist.github.com/shaburov/e857326255e3b590bf7077863fce1a9a)
**2**. configure the connection to AD
**3**. sign in as AD user in Chrome
**4**. stop docker-compose v.3 +
**5**. [run docker-compose v.4.0.0](https://gist.github.com/shaburov/e82624bcf43f7fbf2ba99de557d16f27)
**6**. sign in as AD user in Chrome
**ER**
Successful Authentication
**AR**
Successful Authentication

**7**. log in as AD user in FireFox or another PC
**ER**
Successful Authentication
**AR**
`An error occurred while connecting to the server: You do not have enough permissions. User with login 'oleg.shaburov' already exists`
[Exception in the service-authorization logs](https://gist.github.com/shaburov/691f998e6894edaa4a4722786937e3dc)
![image](https://user-images.githubusercontent.com/15269131/37105707-ec9e9cae-2240-11e8-967e-9b7f93b5dcf7.png)

**Comment by shaburov** [comment]
@avarabyeu 
`{ "_id" : "oleg.shaburov", "_class" : "com.epam.ta.reportportal.database.entity.user.User", "password" : "519dda1ebe0f1fff0e514ff558473147", "email" : "oleg.shaburov@ncloudtech.ru", "role" : "ADMINISTRATOR", "type" : "INTERNAL", "isExpired" : false, "defaultProject" : "catalog", "fullName" : "Oleg Shaburov", "metaInfo" : { "lastLogin" : ISODate("2018-03-07T16:15:44.588Z") }, "photoId" : "59f240dca7b11b0001a56883" }`

**Comment by avarabyeu** [comment]
@shaburov type of user should be changed to LDAP. 
Please, let us know if we can close the issue

**Comment by evjlobanova** [comment]
@shaburov Oleg, please let us know info about this issue. Can we close it?

**Comment by shaburov** [comment]
@avarabyeu  @evjlobanova 
I deleted the user. After authorization through AD, the user was created anew. Formally, the problem is solved.
