### ISSUE TITLE
Wrong TI count when launch interrupted by rp

### ISSUE THREAD

**Issue by fasterfish** [reportportal/reportportal#370]
Given I have project with Launch inactivity timeout = 1 day
When I start tests with execution time more than 1 day
Then launch should be interrupted by rp
And TI count should be equal to Failed + Interrupted

But TI = 27, Failed = 3, Interrupted = 0

Following packages used:

IIS.Microsoft.Web.Administration = 8.5.9600.17042
MSBuildTasks = 1.5.0.235
Newtonsoft.Json = 11.0.1
NLog = 4.4.13
NUnit = 3.10.1
NUnit.ConsoleRunner = 3.7.0
ReportPortal.Client = 2.0.0
ReportPortal.NLog = 1.1.9-beta1
ReportPortal.Shared = 2.0.0-beta3
ReportPortal.SpecFlow = 1.2.2-beta-11
Selenium.Support = 3.11.0
Selenium.WebDriver = 3.11.0
Selenium.WebDriver.IEDriver = 3.11.1
SpecFlow = 2.2.1
SpecFlow.CustomPlugin = 2.2.1
SpecFlow.NUnit = 2.2.1

Tests contains retry

**Comment by avarabyeu** [comment]
@fasterfish so what is the problem? How many tests in the launch? How many of those are failed/skipped? It that possible that other test items are before\after methods?

**Comment by evjlobanova** [comment]
more info about the issue ![image](https://user-images.githubusercontent.com/30413511/37660262-0cfc8cb4-2c63-11e8-9a12-8584aef146af.png)

**Comment by evjlobanova** [comment]
@nvborisenko Nikolay, could you please look at this issue? It seems that you can help with a problem.

**Comment by nvborisenko** [comment]
@fasterfish is the problem still reproducible given that newer ReportPortal.SpecFlow plugin is available?

**Comment by evjlobanova** [comment]
Closed because of no answer
