### ISSUE TITLE
Unable to delete multiple launches (>296) from debug view

### ISSUE THREAD

**Issue by fasterfish** [reportportal/reportportal#372]
Given I have more than 300 launches in debug view
And 300 launches per page
When I select all launches from checkbox
And click on Manage -> Delete
Then all selected launches should be successfully deleted

But if selected launches count more than 296 (297, 298, 299 or 300), then i got "An error occured while connecting to server". Expected: all selected launches should be successfully deleted

**Comment by evjlobanova** [comment]
@e-olga Olga, could you please check this case?

**Comment by avarabyeu** [comment]
i guess issue is rather related to connection timeout since operation is performed synchronously. @evjlobanova Consider for 5.0

**Comment by DzmitryHumianiuk** [comment]
verified
