### ISSUE TITLE
I'm not able to get the analysis feature to work

### ISSUE THREAD

**Issue by braindonor** [reportportal/reportportal#374]
Initially, I checked the logs and found I had a permissions issue on the /data/elasticsearch directory.  I've fixed this and I'm not seeing any errors in the logs now.

However, I'm not seeing any tests getting auto analysed even though I have manually updated some tests that were marked for investigation.

I have the auto analyse switched on.   If I run the analyse manually, I see the red analysis flag against the test run, but it doesn't seem to be doing anything.

Maybe I have missed something.  Any help in getting this up and running would be greatly appreciated as the report portal application looks like it could be very useful.

**Comment by evjlobanova** [comment]
@braindonor hello! 
Could you please check:
- if items that have been marked with defect type have logs with log level higher than 40 000 ( higher than Error):
- the number of items in ElasticSearch should be more than 7,  for that  you need to uncomment ports of ElasticSearch  in docker- compose and send request to ElasticSearch GET http://host:9200/_cat/indices?v

If you have less than 7 items in ElasticSearch, you should investigate more items in RP. 
Please after share with your results.

**Comment by braindonor** [comment]
Thanks very much for your help. 

**db.getCollection('log').find({"level.log_level": {$gt: 40000}})** returns 0 records.

It appears that my failure log entries have log_level 30000 ("Error").

Is it possible to configure the system to analyse failures with log_level >= 30000 ?

**Comment by evjlobanova** [comment]
@braindonor Log level Error includes logs of levels Error, Fatal  and custom level  with log number more than 40 thousands. So we are considering in AA a logs with the reason of failure.

**Comment by evjlobanova** [comment]
@braindonor can I close an issue?

**Comment by braindonor** [comment]
Yes.  Thanks for your help.  
I'm going to try and raise the failure exception in my tests to get the required log_level.

**Comment by braindonor** [comment]
Tried to log a Fatal error via slf4j, but it didn't appear in report portal as a fatal log.

In the end I logged it directly from my service class on test failure:
ReportPortal.emitLog("Failed: " + testName, "FATAL", new Date());

I now have log entries with log_level 50000.

**Comment by evjlobanova** [comment]
@braindonor 
it is a bug. Thank you for you for find this issue. 
Unfortunately, we have found that only logs with level Error can be used in Auto-Analysis. We will fix this issue in 4.2 version. 
Concerning your situation I can advise you to report logs with level Error by the time the bug will be fixed.

**Comment by braindonor** [comment]
Thanks for the update.   All my test logs are still at error level, but I've logged one message at fatal level for failed tests.   After I manually investigate the failures, would you expect AA to work for me now?
   
I haven't tested the auto-analysis yet as all our CI envs are down.   I ran some individual tests yesterday and I am seeing some output from http://host:9200/_cat/indices?v, so I'm hopeful.

**Comment by braindonor** [comment]
AA is working now.   Thanks again.
