### ISSUE TITLE
flaky tests widget show also non-test items

### ISSUE THREAD

**Issue by ulmanA** [reportportal/reportportal#375]
the widget of most falky tests count also before-method items and after-method items.
I want to see only flaky tests and not configuration methods

please add option to filter it on the widget configuration

thanks!

**Comment by artoyer** [comment]
@evjlobanova any update on this? this spoils all the data. In all widgets we see "to investigate" issues more than our tests count

**Comment by DzmitryHumianiuk** [comment]
@ulmanA @artoyer 
will checkbox `Show @Test only` in widget config resolve it?

**Comment by ulmanA** [comment]
@DzmitryHumianiuk 
Yes :)
If such checkbox will be added, it will be very helpful!

BTW,
About the label `Show @Test only` 
I suggest: `Show Test only` without the `@`
Because `Test` is valid Method Type of ReportPortal
And `@Test` is right only for frameworks such TestNG, JUnit
But there is no `@Test` on the JavaScript frameworks (Mocha, Jasmine)
Thanks!

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova plz address discussion of this point at next workshop.
Consider as in 4.3 scope

**Comment by artoyer** [comment]
@ulmanA absolutely yes
