### ISSUE TITLE
Unnecessary logging of all items in the run in case if run cannot be completed

### ISSUE THREAD

**Issue by tmatveyeva** [reportportal/reportportal#376]
Hello,

We have ReportPortal v4, and agent and logger as follows:
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>4.0.1</version>
        </dependency>

Sometimes (most of the times), runs on report are not completed correctly, but get stuck, even though run is completed in Jenkins. Not completed run is not big problem, however when it happens, there is the following exceptio in log:

io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
Status code: 500
Status message: Internal Server Error
Error Message: Finish test item is not allowed. Test item '5ab97a7d7b125e0001c6fd05' has descendants with 'IN_PROGRESS' status. All descendants '[TestItemid='5ab97a897b125e0001c70290', name='springTestContextBeforeTestClass', type=BEFORE_CLASS, startTime=Mon Mar 26 22:56:09 UTC 2018, endTime=Mon Mar 26 22:56:09 UTC 2018, status=PASSED, tags=null, statistics=TestItemStatistics [executionCounter=TestItemExecutionCounter [total=0, passed=0, failed=0, skipped=0], issueCounter=IssueCounter [productBug=total=0, PB001=0, automationBug=AB001=0, total=0, systemIssue=total=0, SI001=0, toInvestigate=total=0, TI001=0, noDefect=ND001=0, total=0]], issue=null, path=[5ab978f47b125e0001c65eeb, 5ab97a7d7b125e0001c6fd05], parent='5ab97a7d7b125e0001c6fd05', launchRef='5ab978d27b125e0001c65854', hasChilds=false, itemDescription='', parameters=null, lastModified=Mon Mar 26 22:56:09 UTC 2018, uniqueId='auto:5f923e54d44b9a779b0df150e17f0f8c', retries=null, .....

And then follows all details of our 10000 tests, twice. With our number of tests, this produce 500MB+ of logs, which is an issue.  Can you please stop logging all descendant items in case of such errors? This issue is quite critical for us. 

Note, I tried to find in log an item in status IN_PROGRESS or IN PROGRESS, but there are just none, so I'm not even sure that this error should actually happen. In Report Portal UI there are no In Progress or Interrupted items for all recent runs with such an issue. 

Regards,
Tatyana

**Comment by avarabyeu** [comment]
@pbortnik Pasha, please, truncate error message on server side as well to avoid load on network
