### ISSUE TITLE
AssumptionViolatedException makes test failed

### ISSUE THREAD

**Issue by vseslovur** [reportportal/reportportal#377]
Hi,

I intentionally throw org.junit.AssumptionViolatedException in one test to skip it. 
And I expect that Report portal will mark it as skipped too. But it was marked as failed. 

If you need more information or logs or whatever, tell me please what exactly.

P.S. We are using cucumber and agent-java-cucumber version 4.0.0
In the cucumber report such test marked as pending:
4 Scenarios (1 pending, 3 passed)
24 Steps (1 pending, 23 passed)

**Comment by evjlobanova** [comment]
@vseslovur does this issue is still reproducing?

**Comment by DzmitryHumianiuk** [comment]
@vseslovur we have updated junit4 agent. it might help.

is it still reproducible for you. Or you have refused usage?

**Comment by evjlobanova** [comment]
Closed because of no answer
