### ISSUE TITLE
Refresh button disabled in merge/compare mode

### ISSUE THREAD

**Issue by fasterfish** [reportportal/reportportal#38]
When I am in **merge/compare** mode at launches page, **Refresh** button has disbled status:

![screenshot_3](https://cloud.githubusercontent.com/assets/18389889/21171629/1b976396-c1ef-11e6-8e2e-8f13c6dca69a.png)

But, when i'm clicked to refresh, it's work properly.

I propose to leave the **Refresh** button is enabled, regardless of the current mode (merge/compare).

**Comment by DzmitryHumianiuk** [comment]
**RESOLUTION:** rejected

it will be disabled.

In new design 3.0 it fully refactored with `multi-actions`
