### ISSUE TITLE
Unexpected total tests count

### ISSUE THREAD

**Issue by fasterfish** [reportportal/reportportal#380]
Given I run some long test with retry attribute
When the first test fail and restart automatically
And I force finish launch in rp
Then tests count should greater than or equal to 1

But tests count equals to -1:

![screenshot_1](https://user-images.githubusercontent.com/18389889/38290099-06edfc68-37f3-11e8-8917-6ca7864ea9e0.png)

**Comment by evjlobanova** [comment]
@fasterfish could you please send me a screenshots with step view  and log view of this test?

**Comment by fasterfish** [comment]
@evjlobanova 

![screenshot_2](https://user-images.githubusercontent.com/18389889/38349585-2b6dfce0-38c1-11e8-83fd-73e40635f81d.png)
![screenshot_4](https://user-images.githubusercontent.com/18389889/38349587-2d316dc8-38c1-11e8-88ee-c41234156b1c.png)

**Comment by e-olga** [comment]
Bug fixed and will be available in release version 4.2
