### ISSUE TITLE
[FR] Make possible filtering launches that do NOT contain specified tags

### ISSUE THREAD

**Issue by jan-zmeskal** [reportportal/reportportal#384]
As of now ( Build 4.0.0), you can only create filter based on tags that are present in a launch. It would be very useful if you could create a filter that for example shows all the launches that DO NOT have a tag "stopped'.
Best regards!

**Comment by evjlobanova** [comment]
connected with issue https://github.com/reportportal/service-ui/issues/613

**Comment by evjlobanova** [comment]
![image](https://user-images.githubusercontent.com/30413511/40706603-0cb1ebca-63f7-11e8-891a-8dcc71f5fb9d.png)

**Comment by jan-zmeskal** [comment]
@evjlobanova Hello, which version has that been implemented in?

**Comment by jan-zmeskal** [comment]
@evjlobanova Great, thank you!
