### ISSUE TITLE
Не достаточно прав для записи файлов в volumes

### ISSUE THREAD

**Issue by Metatronishe** [reportportal/reportportal#386]
Если создать файл docker-compose через конфигуратор на сайте reportportal.io , то выдает ошибку access denied, в docker-compose volumes прописаны в корневую папку проекта. 
Чтоб поправить надо ручками прописать:
- ./data/consul:/consul/data
для консул
- ./data/elasticsearch:/usr/share/elasticsearch/data
для эластик
- ./data/mongo:/data/db
для монго

**Comment by avarabyeu** [comment]
@yana95 the issue is related to docker-compose generator. Plz, change default volume mapping to provided above one.

**Comment by e-olga** [comment]
Folder 'data' is created and contains folders with other volums.
The fix is already available on http://reportportal.io/download.
