### ISSUE TITLE
launches list is not loaded when project name is `Admin`

### ISSUE THREAD

**Issue by AlexeyAltunin** [reportportal/reportportal#388]
![report-portal-admin](https://user-images.githubusercontent.com/27734925/38601997-c364a98e-3d69-11e8-90b4-eab3c038c9b9.png)

Steps:
1. Create project with name 'Admin'
2. Open launches or any main-menu tab

Console error: 
`{"error_code":5000,"message":"Unclassified error [An Authentication object was not found in the SecurityContext]"}`

**Comment by DzmitryHumianiuk** [comment]
@AlexeyAltunin awesome catch!

**Comment by evjlobanova** [comment]
![image](https://user-images.githubusercontent.com/30413511/77077878-e4d90f80-6a06-11ea-95d8-3401d8aca906.png)
Fixed in version 5
