### ISSUE TITLE
[Swagger] Add more complete documentation for REST API

### ISSUE THREAD

**Issue by abotalov** [reportportal/reportportal#39]
Current documentation (/ui/swagger-ui.html) lacks quiet a lot of information, e.g.:
* a way to send a log with an attached file (clients use multipart)
* allowed logging levels
* allowed issue types
* GET /{projectName}/item?{queryParams} and query parameters usable by it

It would be better to have more complete documentation for API.

**Comment by DzmitryHumianiuk** [comment]
@abotalov this usually described with logger integrations.

Swagger provides default representation. Not sure it can give more

**Comment by abotalov** [comment]
Based on my understanding of http://petstore.swagger.io/ Swagger is capable of at least the following:
* display "Implementation notes" that can contain some arbitrary information if Swagger UI doesn't directly support something - see "GET /pet/findByStatus" or "GET /pet/{petId}" endpoints
* display a select list with some options in "Value" column - see "GET /pet/findByStatus"
* display enums as possible values - see "POST /pet", "GET /pet/findByStatus" or "POST /store/order" endpoints
* display file fields - see "POST /pet/{petId}/uploadImage" endpoint

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu this one for you

**Comment by avarabyeu** [comment]
@DzmitryHumianiuk @lexecon 
Requires swagger API update. Please, schedule. Not a big deal for server side, but requires some changes on UI side.

**Comment by avarabyeu** [comment]
Let me comment on the items:

- a way to send a log with an attached file (clients use multipart) - It might be possible to send multipart via swagger, but request request some logic (putting filename into the main part with json which reflect name of file in multpart)
- allowed logging levels - Possible
- allowed issue types - Impossible. This is not static information and depends on the project you assigned to.

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/reportportal/issues/85

**Comment by avarabyeu** [comment]
>a way to send a log with an attached file (clients use multipart)

see [documentation](http://reportportal.io/docs/How-to-implement)

>logging levels

done

issue types depend on project, but REST API documentation (swagger) is static for whole RP instance, this is why cannot be implemented

**Comment by filossof** [comment]
@avarabyeu 
Hi there, I've managed attaching image (png) to a log using the JS client, but when I try doing it using the API, I have no success. Not sure how to use 'Multipart' directly from the Swagger. Can you please refer me to an example of how to do it? Thanks!

**Comment by DzmitryHumianiuk** [comment]
@filossof swagger do not support multipart in this version.
we should update it.

**Comment by filossof** [comment]
Thanks @DzmitryHumianiuk

**Comment by DzmitryHumianiuk** [comment]
Swagger updated in 5.0 RC
