### ISSUE TITLE
Response Code 403, "You do not have enough permissions. Access is denied".

### ISSUE THREAD

**Issue by Kuzukaze** [reportportal/reportportal#390]
Trying to GET api/v1/{projectName}/launch/{launchId}/report from API on _rp.epam.com_.
Using token from PROFILE page UUID(or can get same from GET uat/sso/me/apitoken).
And get 403, am I have no right for this or I miss something?

Request: {Method: GET, RequestUri: 'https://rp.epam.com/api/v1/WestKM 6.0 - SELENIUM/launch/191/report?view=xls', Version: 1.1, Content: <null>, Headers:{  Accept: application/json  Authorization: Bearer 5868b301-75a6-4fea-b035-618532689fdb  User-Agent: .NET  User-Agent: Reporter}}

Response: {StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
Connection: keep-alive
Vary: Accept-Encoding
Pragma: no-cache
X-Application-Context: api:docker:8080
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
Cache-Control: no-store, must-revalidate, no-cache, max-age=0
Date: Wed, 11 Apr 2018 14:16:39 GMT
Server: nginx
Content-Length: 84
Content-Type: application/json; charset=UTF-8
Expires: 0
}}

**Comment by avarabyeu** [comment]
Thange the URL to 
'https://rp.epam.com/api/v1/{project_name}/launch/191/report?view=xls
