### ISSUE TITLE
Not able to make report portal work within Kubernetes

### ISSUE THREAD

**Issue by thasherwin** [reportportal/reportportal#394]
I deployed report portal in a minikube(kubernetes) using [Kompose ](https://github.com/kubernetes/kompose) 
After the deployement there where some issues with some of the pods that needed to fixed.

Below some notes of what i did to solve all issues with the pods

- Deleted memory limit configuration 
- minekube ssh and sudo sysctl -w vm.max_map_count=262144	
- Made all deployements Stalefull Sets so that they will have an unique name
- Created ingress with the hope that all pods can communicate with each other
- Created Services with the correct portnumbers

Currently all pods are running fine:
![image](https://user-images.githubusercontent.com/17144752/38892256-0ea966b0-4287-11e8-83c9-a5dd6cfbb6d9.png)

There are no errors in the logs

I am able to open reportport url that i configured as ingress but i see an issue with the following API call:
http://sherwin.reportportal.com/composite/info
It gives 404. 
![image](https://user-images.githubusercontent.com/17144752/38892719-59884e20-4288-11e8-8c09-b6a89c6fec49.png)

I wonder what this api call(/composite/info) is.. What service is being called?
Also, is there an application landscape? I could help to get a better understanding on the communicatiion between services

This YML is used to deploy report-portal in K8 using kompose

[docker-compose.txt](https://github.com/reportportal/reportportal/files/1921356/docker-compose.txt)

**Comment by thasherwin** [comment]
/composite/info issue is solved. I added the following line in ingress because @avarabyeu told me that composite is part of the index service. 
```
          "path": "/composite/info",
              "backend": {
                "serviceName": "index-0",
                "servicePort": 8090
              }
            },
```
I do have another issue.
When trying to login i get redirected to /ui/404.html

For some reason ui is a root domain in k8... See the below example:

**Docker ui url looks like this:**
http://localhost:8090/ui/compiled/js/scripts.d5976053.js
http://localhost:8090/ui/compiled/css/styles.min.948ce870.css
http://localhost:8090/ui/compiled/fonts/font-MaterialIconsRegular/MaterialIcons-Regular.woff2?v=08.22.201

**Kubernetes ui urls looks like this**
http://sherwin.reportportal.com/compiled/js/scripts.d5976053.js
http://sherwin.reportportal.com/compiled/css/styles.min.948ce870.css
http://sherwin.reportportal.com/compiled/fonts/font-MaterialIconsRegular/MaterialIcons-Regular.woff2?v=08.22.201

I need to check with a K8 expert whether I can configure k8 to work with **_ui/compi..._** instead of **_compi../_**.

**Comment by thasherwin** [comment]
It works now!
I am closing this issue.. I will try to write down a complete manual with all the steps i did to deploy report portal within k8!

**Comment by sayems** [comment]
Hi @thasherwin can you share the working docker-compose file here please, thanks!
