### ISSUE TITLE
Ambiguous handler methods error message 

### ISSUE THREAD

**Issue by bbartok76** [reportportal/reportportal#395]
When I tried to create a new root item I got the following error message:

_"Unclassified error [Ambiguous handler methods mapped for HTTP path 'http://XX.XX.XX.XX:8080/api/v1/demo/item': {com.epam.ta.reportportal.demo_data.DemoDataRs com.epam.ta.reportportal.demo_data.DemoDataController.generate(java.lang.String,com.epam.ta.reportportal.demo_data.DemoDataRq,java.security.Principal), public com.epam.ta.reportportal.ws.model.EntryCreatedRS com.epam.ta.reportportal.ws.controller.impl.TestItemController.startRootItem(java.lang.String,com.epam.ta.reportportal.ws.model.StartTestItemRQ,java.security.Principal)}]"_

**Build: 4.1.0**

First I faced it with python but then I tried with the reportportal's own api ui and got the following result:

**Curl:**
```curl
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: bearer XXX' -d '{ \ 
   "launch_id": "5ad65a6fadbe1d0001ae2706", \ 
   "name": "test suite", \ 
   "start_time": "2018-04-18T09:53:21.891Z", \ 
   "type": "SUITE" \ 
 }' 'http://XX.XX.XX.XX:8080/api/v1/demo/item'
```
**Request URL:**

http://XX.XX.XX.XX:8080/api/v1/demo/item

**Response Body:**
```
{
  "error_code": 5000,
  "message": "Unclassified error [Ambiguous handler methods mapped for HTTP path 'http://XX.XX.XX.XX:8080/api/v1/demo/item': {com.epam.ta.reportportal.demo_data.DemoDataRs com.epam.ta.reportportal.demo_data.DemoDataController.generate(java.lang.String,com.epam.ta.reportportal.demo_data.DemoDataRq,java.security.Principal), public com.epam.ta.reportportal.ws.model.EntryCreatedRS com.epam.ta.reportportal.ws.controller.impl.TestItemController.startRootItem(java.lang.String,com.epam.ta.reportportal.ws.model.StartTestItemRQ,java.security.Principal)}]"
}
```
**_IP addresses and credentials replaced with Xs._**

**Comment by bbartok76** [comment]
Thank you very much!

**Comment by DzmitryHumianiuk** [comment]
@bbartok76 resolved?

plz comment or reopen in case if not
