### ISSUE TITLE
Unable to integrate RP with SoapUI

### ISSUE THREAD

**Issue by boyfromearth** [reportportal/reportportal#399]
WHen i tried to integrate RP with SOAPUIU i got error in the log:
ERROR [errorlog] java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory

When i went to look for that class in SoapUI jar i couldn't find it, BUT i was able to find that class in readyAPI jar. 
SoapUI and Error logs attached

[soapui.log](https://github.com/reportportal/reportportal/files/1932304/soapui.log)
[soapui-errors.log](https://github.com/reportportal/reportportal/files/1932305/soapui-errors.log)

**Comment by boyfromearth** [comment]
Hello @evjlobanova . WOuld be nice to get some update on this issue? How long do you think it is going to take you to fix it? Thank you

**Comment by evjlobanova** [comment]
@avarabyeu Andrei, could you please answer on @boyfromearth question? Thank you in advance

**Comment by avarabyeu** [comment]
@boyfromearth on my side, issue occurs only on start of application. You can just ignore it, it doesn't affect test execution. Please, let us know if we can close the issue

**Comment by boyfromearth** [comment]
Thank you. You can close this ticket.
