### ISSUE TITLE
Smart Analysis passes by 'To Investigate' items once modified by user

### ISSUE THREAD

**Issue by andrei-khveras** [reportportal/reportportal#4]
The case is when somebody adds comment to some test item that is initially in "To Investigate" status, but doesn't change resolution to some specific one ("Product Bug", "System Issue", etc.). One more case is when somebody changes resolution from some particular issue type down to "To Investigate".
In that cases after next launch execution, when Smart Analysis processes launch result, it **skips** updating **issue type** for such items, but it does extend the comment using previous resolutions history.
"To Investigate" resolution ALWAYS stands for the fact that decision hasn't been made yet.
If Smart Analysis allocates some resolution for History it should ALWAYS be allowed to use it for "To Investigate" items. For deferred decisions users can use custom issue types, etc.

**Comment by DzmitryHumianiuk** [comment]
@andrei-khveras this one is very contradictory.
**From one side:** if something changed in defect - means that resolution by engineer was already made, and we can't rewrite it.
**From the other side:** you can bypass some data (e.g. comment) for defect with fail, and this should not be override by `Smart Analysis`.

This enhancement will be considered with `Smart Analysis` refactoring.

**Comment by avarabyeu** [comment]
@DzmitryHumianiuk @andrei-khveras what about introducing one more field like "trustMe" or "imsure" to notify auto analysis that issue should not be picked up?

**Comment by DzmitryHumianiuk** [comment]
**Flag 1**
* АА - analysed by AA
* HM - analysed by Human - boost priority in BOOL elastic request

**Flag 2**
IGNORE - ignore this item in AA - add to wildcard BOOL elastic request

@avarabyeu @pictureb00k

**Comment by DzmitryHumianiuk** [comment]
for the Auto-Analysis in 4.0,
algorithm will not consider test items, which have comment but defect type is `To Investigate`
because of `wildcard` in `must_not` part of BOOL request to Elastic

this
```javascript
    "must_not": map[string]interface{}{
     "wildcard": map[string]interface{}{
      "issue_type": "TI*",
     },
```

in
```javascript
   "bool": map[string]interface{}{
    "must_not": map[string]interface{}{
     "wildcard": map[string]interface{}{
      "issue_type": "TI*",
     },
    },
    "must": []interface{}{
     map[string]interface{}{
      "term": map[string]interface{}{
       "log_level": 40000,
      },
     },
     map[string]interface{}{
      "exists": map[string]interface{}{
       "field": "issue_type",
      },
     },
     map[string]interface{}{
      "more_like_this": map[string]interface{}{
       "fields":               []string{"message"},
       "like":                 logMessage,
       "minimum_should_match": "90%",
      },
     },
    },
    "should": map[string]interface{}{
     "term": map[string]interface{}{
      "launch_name": map[string]interface{}{
       "value": launchName,
       "boost": 2.0,
      },
```
