### ISSUE TITLE
Email from ReportPortal@service.com - make configurable default sender address

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [reportportal/reportportal#40]
Where could I change the default mail from domain?

**Comment by DzmitryHumianiuk** [comment]
@Ilya-Kuchaev Did you mean default mail address which sends email notifications?

![image](https://cloud.githubusercontent.com/assets/11332788/21180003/d48bbeb6-c207-11e6-8e7d-14a8b8be4163.png)

**Comment by Ilya-Kuchaev** [comment]
No. I'm inviting users right now. And invite email is from ReportPortal@service.com. I just can't find where I can configure it.
The email client can't send the messages via SSL also. So I can't configure for ex. SparkPost as a relay.

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu is it hardcoded?

**Comment by admizh** [comment]
@DzmitryHumianiuk - seems hardcoded:
https://github.com/reportportal/service-api/blob/master/src/main/java/com/epam/ta/reportportal/util/email/EmailService.java#L213

**Comment by admizh** [comment]
need add field to mailing configuration. 
![image](https://cloud.githubusercontent.com/assets/6014483/21291985/8c4a698c-c50d-11e6-8ad4-e8d2be9b0b57.png)

**Comment by admizh** [comment]
@DzmitryHumianiuk pls change label for current issue

**Comment by DzmitryHumianiuk** [comment]
In backlog now

**Comment by DzmitryHumianiuk** [comment]
Done.
available with 3.0
