### ISSUE TITLE
Marking failed tests as passed

### ISSUE THREAD

**Issue by talgreen1** [reportportal/reportportal#400]
We are starting to user Report Portal to include our manual tests as well.

Our solution so far is to create tests from code to represents the manual tests and fail (or skip) them by default.
Then – after running the tests manually, we are changing the fail reason. Currently – we are changing it from ‘To Investigate' to some other reason. We’ve created some sub defect types- ‘Manual Pass’ & ‘Manual Fail’.
The problem is that when we change it to ‘Manual Pass’ – the test will not appear in the widgets as passed.
We need a way to make failed test to be marked as ‘real’ pass.

**Comment by evjlobanova** [comment]
@talgreen1 we are planning to implement a possibility to change test status, approximately date is after v5.

**Comment by DzmitryHumianiuk** [comment]
Sounds like #191 Semi-automation.
considered to be done in 2 stages:

 - [ ] 5.0 version will allow to change PASSED<->FAILED
 - [ ] with #191 introduce interim undefined state for test case. And allow to change it on UI. Or follow the concept to keep all test cases failed by default, and possibility to change status will resolve it.

**Comment by DzmitryHumianiuk** [comment]
@talgreen1 implemented.
available with in v5

**Comment by DzmitryHumianiuk** [comment]
equal to #672
