### ISSUE TITLE
Filtering bug when trying to open "to investigate"

### ISSUE THREAD

**Issue by ailjushkin** [reportportal/reportportal#404]
RP version:

Current version: Analysis Service: 4.0.0; API Service: 4.0.0; Index Service: 4.0.0; Jira Service: 4.0.0; Authorization Service: 4.0.0; Service UI: 4.0.0;

We have some launch:

![1](https://user-images.githubusercontent.com/3462506/39247916-64016a64-48a3-11e8-98cc-e09766c61de1.png)

Opening "To investigate" shows different results to us - there is no 16 tests, but only two:

![2](https://user-images.githubusercontent.com/3462506/39247919-66fa52b2-48a3-11e8-9973-124402bf2d81.png)

Meanwhile we got no any errors in the javascript console.

**Comment by DzmitryHumianiuk** [comment]
@pbortnik @e-olga take this investigation into 5.0 backlog.
Might be an statistics calculation issue, because of concurrent access.

**Comment by DzmitryHumianiuk** [comment]
@ailjushkin is it still reproducible?

**Comment by ailjushkin** [comment]
Seems like after installation of the new version of RP this is issue was resolved.
