### ISSUE TITLE
Question: how to configure a Jira BTS which is running on ssl ?

### ISSUE THREAD

**Issue by braindonor** [reportportal/reportportal#405]
I've configured Reportportal to run under ssl and want to connect to a jira instance which is ssl.

I'm currently seeing this in the jira service log:

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Presumably I need to somehow configure the certificate in the Docker container ?

**Comment by braindonor** [comment]
I got Jira ssl integration working by loading my root certificate into the docker container:

docker cp cert.der reportportal_jira_1:/cert.der
 
docker exec -t -i reportportal_jira_1 ./usr/lib/jvm/java-1.8-openjdk/jre/bin/keytool -import -alias rootcert -keystore /usr/lib/jvm/java-1.8-openjdk/jre/lib/security/cacerts -file /cert.der

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova it should be documented

**Comment by lvonah** [comment]
@DzmitryHumianiuk I ended up editing the jira image to add jira cert to keystore in the container on creation and referencing that updated image in the compose file

**Comment by DzmitryHumianiuk** [comment]
@lvonah workable approach!
good one
