### ISSUE TITLE
An error occurred while connecting to server

### ISSUE THREAD

**Issue by aamorozov** [reportportal/reportportal#406]
### Meta
Platform: macOS High Sierra 
Docker engine: 18.05.0-ce-rc1
Compose: Compose: 1.21.0
Machine: Machine: 0.14.0

Not sure if node matters here, but 
Node v9.11.1

### Reference
I was trying to set up the service following the steps in the description here http://reportportal.io/download, but once I start the services with docker compose i get the following error: 

<img width="1272" alt="screen shot 2018-04-28 at 9 19 31 am" src="https://user-images.githubusercontent.com/10227658/39396968-86e68900-4ac5-11e8-995f-45d8073a68ba.png">

**Comment by evjlobanova** [comment]
@aamorozov  check if all services are up, it takes some time to install all services and than try again

**Comment by evjlobanova** [comment]
@aamorozov please share with your results. Have you opened RP?

**Comment by aamorozov** [comment]
@evjlobanova All services seem to be installed and running correctly. When logging in the portal, i don't get any console errors so unfortunately cannot provide any more details to help to reproduce the issue

**Comment by kaushik2306** [comment]
I am observing the same issue but on Windows 7 -Home pc..Any idea how can I start all the services

**Comment by knayeneni** [comment]
@kaushik2306 @aamorozov Wondering whether you guys were able to solve this issue. I am having the same issue currently and I installed ReportPortal without docker. I reported #617. Please provide feedback if it worked for you guys...thanks
