### ISSUE TITLE
cannot log with attachment

### ISSUE THREAD

**Issue by nkthota** [reportportal/reportportal#407]
while trying to log with attachment based on the below example, data logged as binary data rather than an attachment.
I see the same working in older RP instance. 

Current instance details

Current version: API Service: 4.1.0; Index Service: 4.0.0; Jira Service: 4.1.0; Rally Service: 4.0.0; Authorization Service: 4.1.0; Service UI: 4.1.0;

Nunit 3.8
 var filePath = TestContext.CurrentContext.TestDirectory + "\\dog.png";
 Bridge.LogMessage(ReportPortal.Client.Models.LogLevel.Info, "my dog {rp#file#" + filePath + "}");

![image](https://user-images.githubusercontent.com/11020602/39510005-d364723e-4dad-11e8-939b-843d208876da.png)

**Comment by evjlobanova** [comment]
@nvborisenko please take a look on this issue

**Comment by nvborisenko** [comment]
I cannot reproduce this issue. Dog is successfully reported to the server.

@nkthota Could you please verify your integration in comparison with https://github.com/reportportal/example-net-nunit ?

**Comment by nkthota** [comment]
i'm able to use the sample project and go it working. not sure what might the root cause. closing the issue.
