### ISSUE TITLE
restarting server deletes all the projects?

### ISSUE THREAD

**Issue by csekamal** [reportportal/reportportal#408]
Hi,
I have reportportal server running with several projects. Then there were some OS update and I had to restart my machine. But after that, I cannot find any of my projects except the default superadmin_personal project. Is this expected behavior? Is there any extra configuration to make so that in case of machine restart all the projects and their reports are saved?
Thanks
A.K.

**Comment by csekamal** [comment]
My docker-compose.yml file contains the below lines related to mongodb,
mongodb:
    image: mongo:3.4
#    ports:
#        - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    restart: always

I have mongo 3.2 installed under "C:\Program Files\MongoDB\Server\3.2\bin". I use command line to cd to this bin folder and run "mongod" to start the mongodb server. What things I have to specify in my docker-compose.yml file so that all my projects and data are saved if I have to restart reportportal server machine by typing "docker-compose -p reportportal up -d --force-recreate"?
I could NOT find a good document on setting mongodb properties so that projects and data are saved. Thanks for your help.

**Comment by csekamal** [comment]
Another point is, shall I install mongo under host machine or under the docker image? Currently, I have installed it in my host machine and I don't know how to install it under docker.

**Comment by csekamal** [comment]
I see that mongo database service is running along with other report portal services after I restart my PC. My question is why is it not saving all the projects and data. After restart all projects and data are gone and the superadmin has the default password even though I changed the password. Any help to diagnose the problem is appreciated.

**Comment by csekamal** [comment]
Hi avarabyeu, 
My reportportal instance uses the mongo db that is inside docker. If I restart my pc, all the reportportal services are automatically up and running. See below,
<img width="833" alt="docker_reportportal_services" src="https://user-images.githubusercontent.com/36864730/39819188-5e477d4e-5392-11e8-943a-6d01c7225289.PNG">
but for some reason, all the data and projects are gone and the superadmin user reverts to default password even though I have changed it. Any idea why it is not saving the data between machine restarts? Is it related to docker settings or reportportal settings or something else?

**Comment by DzmitryHumianiuk** [comment]
@csekamal did you find answer?

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/reportportal/issues/642#issuecomment-501676413
