### ISSUE TITLE
Exception was thrown in 'BeforeTestFinished' subscriber.

### ISSUE THREAD

**Issue by nkthota** [reportportal/reportportal#409]
Getting the below error message while using TestEvents. attached Nunit report file

Exception was thrown in 'BeforeTestFinished' subscriber.
System.NullReferenceException: Object reference not set to an instance of an object.
   at EBridge.Tests.ReportPortal.Customization.ReportPortalListenerOnBeforeTestFinished(Object sender, TestItemFinishedEventArgs e) in C:\Automation\X-Test\EBridge.Tests\ReportPortal\Customization.cs:line 24
   at ReportPortal.NUnitExtension.Repo
[TestResult.zip](https://github.com/reportportal/reportportal/files/1975136/TestResult.zip)

**Comment by nvborisenko** [comment]
It's your exception. You subscribed to 'BeforeTestFinished' event.
Are you able to share C:\Automation\X-Test\EBridge.Tests\ReportPortal\Customization.cs ?

**Comment by nkthota** [comment]
here is my customization code. i'm trying to add a tag to test at the finish event.

using System;
using NUnit.Engine;
using NUnit.Engine.Extensibility;
using ReportPortal.Client.Models;
using ReportPortal.Client.Requests;
using ReportPortal.NUnitExtension;
using ReportPortal.NUnitExtension.EventArguments;
using ReportPortal.Shared;

namespace EBridge.Tests.ReportPortal
{
    [Extension]
    public class Customization : ITestEventListener
    {
        public Customization()
        {
            ReportPortalListener.BeforeSuiteStarted += ReportPortalListenerOnBeforeSuiteStarted;
            ReportPortalListener.BeforeRunStarted += ReportPortalListenerOnBeforeRunStarted;
            ReportPortalListener.BeforeTestFinished += ReportPortalListenerOnBeforeTestFinished;
        }

        private void ReportPortalListenerOnBeforeTestFinished(object sender, TestItemFinishedEventArgs e)
        {
            e.TestItem.Tags.Add("Bing");
        }

        private void ReportPortalListenerOnBeforeSuiteStarted(object sender, TestItemStartedEventArgs e)
        {
            if (e.TestItem.Name == "EBridge.Tests.dll" || e.TestItem.Name == "Hooks")
            {
                e.Canceled = true;
            }
        }

        private void ReportPortalListenerOnBeforeRunStarted(object sender, RunStartedEventArgs e)
        {

        }

        public void OnTestEvent(string report)
        {

        }
    }
}

**Comment by nvborisenko** [comment]
It seems TestItem.Tags might be null. Try to use 'new List<string>{"abc"}'

**Comment by nkthota** [comment]
i tried the below, i dont see an error now but still, i don't see tags added.

            List<string> newTags = new List<string> {"Bing"};
            e.Service.UpdateTestItemAsync(e.TestReporter.TestId, new UpdateTestItemRequest
            {
                Tags = newTags
            });

**Comment by nkthota** [comment]
it works with below.
            var updateTestRequest = new UpdateTestItemRequest();
            updateTestRequest.Tags = new List<string> {"Bing"};
            e.TestReporter.Update(updateTestRequest);

Thanks a lot for quick response.
