### ISSUE TITLE
Q: how to integrate with JUnit

### ISSUE THREAD

**Issue by talmoshe** [reportportal/reportportal#410]
Hi, I want to integrate with JUnit, can anyone help me with the below error?

```java
@RunWith(Suite.class)
@Suite.SuiteClasses({ 
	SimpleTest1.class,
	SimpleTest2.class
})
```

Execution shows:
```
09:43:40 1157 [main] ERROR com.epam.reportportal.junit.ParallelRunningHandler - Unable start test suite: 'null'
09:43:40 com.epam.reportportal.exception.ReportPortalClientException: Report Portal returned error
09:43:40 Status code: 400
09:43:40 Status message: Bad Request
09:43:40 Error Message: Incorrect Request. [Field 'name' shouldn't be null.]
09:43:40 Error Type: INCORRECT_REQUEST
```
It was solved by switching to `@RunWith(com.epam.reportportal.junit.CustomJUnitRunner.class)`
But now I'm getting the error - No runnable methods
```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR] null
[ERROR] simpleTestSuite1.initializationError » No runnable methods
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by evjlobanova** [comment]
@avarabyeu could you please look at this issue?

**Comment by evjlobanova** [comment]
@talmoshe  could you please send an example?

**Comment by talmoshe** [comment]
Yes, this is my example code:
============================================

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(com.epam.reportportal.junit.CustomJUnitRunner.class)
@Suite.SuiteClasses({ 
	SimpleTest1.class,
	SimpleTest2.class
})

public class simpleTestSuite1 {

}

**Comment by talmoshe** [comment]
I also noticed that I'm getting "no runnable methods" error

log4j: Adding appender named [ReportPortalAppender] to category [root].
[INFO] Running com.xxx.auto.simpleSuite1Test
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.204 s
<<< FAILURE! - in com.xxx.auto.simpleSuite1Test
[ERROR] Test mechanism  Time elapsed: 0.14 s  <<< ERROR!
java.lang.NullPointerException

[ERROR] initializationError(com.xxx.auto.simpleSuite1Test)  Time elapsed: 0.14
 s  <<< ERROR!
**java.lang.Exception: No runnable methods**

[ERROR] Test mechanism  Time elapsed: 0.14 s  <<< ERROR!
java.lang.NullPointerException

[ERROR] Test mechanism  Time elapsed: 0.14 s  <<< ERROR!
java.lang.NullPointerException

May 31, 2018 11:30:13 AM com.epam.reportportal.listeners.ListenersUtils handleEx
ception

**Comment by talmoshe** [comment]
@evjlobanova @avarabyeu Any updates?

**Comment by avarabyeu** [comment]
@talmoshe 
Example of project can be found here:
https://github.com/reportportal/example-java-junit
