### ISSUE TITLE
Operators/Members cannot add a tag/description.

### ISSUE THREAD

**Issue by dmitryyu** [reportportal/reportportal#412]
Why can't members/operators (not owners) add tags/description? 

The information which can be added to TC (tag/comment) is displayed for a specific run. so changes for current run will not impact to other ones... so i guess, it would be cool to provide the option to add tags and description at least for members.

**Comment by DzmitryHumianiuk** [comment]
@dmitryyu owner can change his object as he wants.
Lead/PM/Admin can change object of another users.

Member role considered for Juniors, so they can't make a mess.

after 5.0 we will introduce custom roles per user.
