### ISSUE TITLE
Report generation: Creates more than 25000 live and 25000 daemon threads

### ISSUE THREAD

**Issue by Lunar12** [reportportal/reportportal#413]
Application is using Report Portal. During the report generation when it works with maven-surefire-plugin, it starts to create more than 25000 live and 25000 daemon threads, after that our job on Jenkins fails with the "Out of memory error". 
Please find attached the detailed information.
![rp-threds](https://user-images.githubusercontent.com/13586672/40055581-80208f84-5859-11e8-8095-0a99c0b8adc2.png)
[threaddump_tdump.txt](https://github.com/reportportal/reportportal/files/2004914/threaddump_tdump.txt)

**Comment by Lunar12** [comment]
Actually HeapDump I was not able to attache here because of not supported format.

**Comment by Lunar12** [comment]
Attached also details about error from Jenkins 
![error1](https://user-images.githubusercontent.com/13586672/40108089-134fb86e-590b-11e8-9a76-d6756ddd88c7.PNG)
![error2](https://user-images.githubusercontent.com/13586672/40108090-13718412-590b-11e8-9b5a-f2068e7f1ab4.PNG)

**Comment by DzmitryHumianiuk** [comment]
assigned for investigation

**Comment by Lunar12** [comment]
Hi. Is there any news related to this bug?

**Comment by avarabyeu** [comment]
@Lunar12 we've just released testng agent v.4.2.0
Issue is supposed to be fixed. 
Please, let us know if it helps, feel free to re-open the issue or create new one if it doesn't

**Comment by DzmitryHumianiuk** [comment]
@Lunar12 does it work?
