### ISSUE TITLE
Add the ability to specify launch number using the REST API

### ISSUE THREAD

**Issue by avishaymahluf** [reportportal/reportportal#414]
We're using Jenkins to execute our tests and at the end of the build we're using the REST API to upload the XML report. 
We would like to have the ability to control the launch ID using the REST API so we can match it to the Jenkins build ID.

Thanks!

**Comment by DzmitryHumianiuk** [comment]
@avishaymahluf could you please specify details of request?

Did not get, how you can control launch ID via API?

**Comment by avishaymahluf** [comment]
Hi @DzmitryHumianiuk,

I think that ID is not the right word here. What I meant is to control the counter launch number (I'll also update the title of the issue).

I'll also give an example:
We already have existing Jenkins jobs. Now we want to add report portal on those jobs and publish our test results to reportportal.
When I'm using the reportportal REST API to publish the xUnit XML report, a new launch is created in reportportal with the same name of our Jenkins job but the launch number is 1.
My problem is that since the job in Jenkins already exists, its build number is higher than 1 and I want to be able to match the launch number to the current build number that we have on our Jenkins job.

Right now there is no option in REST API to change the launch counter number.

**Comment by DzmitryHumianiuk** [comment]
@avishaymahluf got you.

Well, we don't see any other reasons to make launch numbers changeable.
The case, you have described above, is a good one.

But i can propose a **workaround** for you:
- send Jenkins Job number via launch description.
It supports Markdown, so you can make it even clickable.
Jenkins can return you job number as internal variable, at the same time as a link to the job (if URI in Jenkins configured).

![image](https://user-images.githubusercontent.com/11332788/40247688-e1a65616-5ad5-11e8-83b9-7169ab88406a.png)

![image](https://user-images.githubusercontent.com/11332788/40247749-14d68a10-5ad6-11e8-8898-c7d92edee7fc.png)
![image](https://user-images.githubusercontent.com/11332788/40247761-1ee39d2c-5ad6-11e8-83f1-5f7600ca7125.png)

**Comment by DzmitryHumianiuk** [comment]
@avishaymahluf does it help?

**Comment by avishaymahluf** [comment]
@DzmitryHumianiuk 
Thanks for the quick response!
Actually, we've already done those workarounds, we also added build ID as tags to the launch.
However, as you said this is a workaround and still a bit confusing to see different numbers on the description and on launch number.

We think that It would be nice to have this feature.

**Comment by DzmitryHumianiuk** [comment]
Launch number used for our internal back-end needs,
possibility to change it will bring tons of possible issues.

the same in Jenkins, you can't change number of job execution.

resolution `Won't fix` for now.

**Comment by avishaymahluf** [comment]
@DzmitryHumianiuk 
Thank you for your response.
Actually changing the number of job in Jenkins is possible. Please refer to:
https://wiki.jenkins.io/display/JENKINS/Next+Build+Number+Plugin

But anyway, if this is not possible in the current architecture of reportportal, I guess we will stay with build_id in tags as a workaround.

**Comment by phartheeb** [comment]
Hi @avishaymahluf Could you please help in sharing the APIs and code used in Jenkins pipeline to have the results in report portal?

**Comment by acdurai** [comment]
Hello @avishaymahluf Could you please help in sharing the APIs and code used in Jenkins pipeline to have the results in report portal?. Actually I'm trying to filter the reports based on jenkins build number
