### ISSUE TITLE
AA settings in a separate section, ML configure

### ISSUE THREAD

**Issue by evjlobanova** [reportportal/reportportal#417]
*As a user with PM and Admin role,* I want to configure analyzer manually. For roles less then PM, the section is non-editable, Remove/Generate index are disabled.
*So that* the results  will be more relevant.
*For that* I should open Auto-Analysis section in the Settings and made an appropriate changes into configurations.

![image](https://user-images.githubusercontent.com/30413511/40297121-5b537c9c-5ce7-11e8-8335-cd45b70ff0d8.png)

On this section user can:
1. Switch ON/OFF auto-analyzer;
2. Choose a base for analyzer (All launches/ Launches with the same name);
3. Configure ML settings;
4. Remove ML education (all base with previous investigations)/ generate new one base.

**Configure ML settings**
We give possibility for our user to configure 4 main parameter of ElasticSearch manually:

* *MinDocFreq*  -  the minimum frequency of the saved logs in ElasticSearch (index) in which word from analyzed log should be used. If the log count is below the specified value, that word will be ignored for AA in the analyzed log. The more often the word appears in index, the lower it weights.

* *MinTermFreq* -  the minimum frequency of the word in the analyzed log. If the word count is below the specified value, this word will be ignored for AA. The more often the word appears in the analyzed log, the higher it weights.
 
* *MinShouldMatch* -  percent of words equality between analyzed log and particular log from the ElasticSearch. If a log from ElasticSearch has the value less then set, this log will be ignored for AA.

* *Number of log strings* -  the number of first lines of log message that should be considered in ElasticSearch. Only choosen number of log line will be saved in ElasticSearch.

With parameters **MinDocFreq** and **MinTermFreque** you can normalized log and reduce importance of frequent but useless words in log (f.e. "Java" or prepositions...). 

With parameter  **MinShouldMatch** you can increase search hardness. 

With parameter **Number of log strings** - you create your own  log structure and write the root cause of test fail in the first lines and configure analyzer takes in account only the required lines.

With these 4 parameters you can configure an accuracy of analyzer. We have prepared for you 3 pre-sets:
* *Light* - search conditions are more free. You will get more results, but with the less level of 
similarity;
* *Moderate* - "happy medium";
* *Strict* - search conditions are strict. You will get less results, but with the higher level of 
similarity;

**Remove ML education:**
If ML is a bad student and you are not happy with how  it has learned to analyze, you can start over everything. Remove index from ElasticSearch, and start analyze test results manually again. All investigated data from ElasticSearch will be removed (!!your results in RP will not be changed!!).

Also we give you possibility to regenerate index on base of new settings.

**Comment by Rider1982** [comment]
Hello!
I have a little suggestion.
Could you please add the following functionality to "Generate index in the ElasticSearch": an ability to filter launches to use for learning? For example, use actual launches age or exclude specific launches from learning or learn based on only specific launches?
The case: for example, I'm not satisfied with the auto analysis results and need to rebuild the analysis base. So I could remove index then regenerate it based on a reliable set of launches (well investigated, more relevant to current project state).
