### ISSUE TITLE
e.TestReporter.TestId return null in ReportPortalListenerOnAfterTestStarted

### ISSUE THREAD

**Issue by nkthota** [reportportal/reportportal#419]
private void ReportPortalListenerOnAfterTestStarted(object sender, TestItemStartedEventArgs e)
        {
            Task<TestItem> testItem = Bridge.Service.GetTestItemAsync(e.TestReporter.TestId);           

            e.TestReporter.Log(new AddLogItemRequest
               {
                   Level = LogLevel.Error,
                   TestItemId = e.TestReporter.TestId,
                   Time = DateTime.UtcNow,
                   Text = string.Join("/", testItem.Result.PathNames.Keys.ToArray())
               });
        }
e.TestReporter.TestId return null.

Help needed. I'm able to get the TestId in ReportPortalListenerOnBeforeTestFinished event.

references:

"ReportPortal.Client" version="2.0.0" targetFramework="net45" />
"ReportPortal.Log4Net" version="1.1.5-beta2" targetFramework="net45" />
"ReportPortal.NUnit" version="3.3.0-beta2" targetFramework="net45" />
"ReportPortal.Shared" version="2.0.0-beta4" targetFramework="net45" />

**Comment by avarabyeu** [comment]
^ @nvborisenko

**Comment by nvborisenko** [comment]
@nkthota it is unnecessary to provide TestId property to log you data via TestReporter class. Try to do the same but without TestId, should work.

**Comment by nkthota** [comment]
@nvborisenko i still see an error while trying to get test. i was looking to get the path names. as you mentione i'm able to log without test id.

please advise.

        private void ReportPortalListenerOnAfterTestStarted(object sender, TestItemStartedEventArgs e)
        {
            this.TestName = e.TestItem.Name;
            this.LaunchId = e.TestItem.LaunchId;

            Task<string> task = this.HandleFileAsync(e);
            task.Wait();

            e.TestReporter.Log(new AddLogItemRequest
            {
                Level = LogLevel.Error,
                TestItemId = e.TestReporter.ToString(),
                Time = DateTime.UtcNow,
                Text = task.Result
            });
        }

        public async Task<string> HandleFileAsync(TestItemStartedEventArgs e)
        {
            var getTest = await Bridge.Service.GetTestItemAsync(e.TestReporter);
            return string.Join("/", getTest.PathNames.Keys.ToArray());
        }

**Comment by nvborisenko** [comment]
Added example of your thing into https://github.com/reportportal/example-net-nunit/blob/master/src/Example/ReportPortalCustomization/Customization.cs

It works for me:
```csharp
private void ReportPortalListener_AfterTestStarted(object sender, ReportPortal.NUnitExtension.EventArguments.TestItemStartedEventArgs e)
        {
            e.TestReporter.Log(new ReportPortal.Client.Requests.AddLogItemRequest
            {
                Level = ReportPortal.Client.Models.LogLevel.Trace,
                Time = DateTime.UtcNow,
                Text = "This message is from 'ReportPortalListener_AfterTestStarted' event."
            });
        }
```

**Comment by nkthota** [comment]
can you add a sample to capture test launch path? that will be helpful.

**Comment by nvborisenko** [comment]
@nkthota it's not easy to get the launch path because agent sends data to the server in background, and actually we don't know when exactly data are sent to the server. What is your goal to have launch path in RP server? May be we can resolve your situation in some another way.

**Comment by nkthota** [comment]
I'm looking to provide the test launch path to the end user so the user can navigate to the test execution details directly rather navigating from the launch. I was able to get the value from the earlier RP client version. I'm planning to construct the URL after the test starts event and post it to our internal on-demand test runner.

**Comment by nvborisenko** [comment]
If you really need it then try to use
```
e.TestReporter.StartTask.Wait(); //waiting until test will be posted to the server
// now e.TestReporter.TestId is filled in with real test ID
var testInfo = await e.Service.GetTestItemAsync(e.TestReporter.TestId);
```
But you should understand that tests execution is affected by your code and now the reporting is synchronous.

**Comment by nvborisenko** [comment]
Added into example project: https://github.com/reportportal/example-net-nunit/blob/a3960da023bff5f9863957928e1f17126dd157df/src/Example/ReportPortalCustomization/Customization.cs#L30
