### ISSUE TITLE
A launch filter for machine learning when rebuilding ElasticSearch indexes

### ISSUE THREAD

**Issue by Rider1982** [reportportal/reportportal#421]
Hello!
I have a little suggestion for [this](https://github.com/reportportal/reportportal/issues/417) functionality (parameters for machine learning).
Could you please add the following functionality to "Generate index in the ElasticSearch": an ability to filter launches to use for learning? For example, use actual launches age or exclude specific launches from learning or learn based on only specific launches?
The case: for example, I'm not satisfied with the auto analysis results and need to rebuild the analysis base. So I could remove index then regenerate it based on a reliable set of launches (well investigated, more relevant to current project state).

**Comment by Rider1982** [comment]
@evjlobanova, that looks as workaround, but is usable for me.

**Comment by DzmitryHumianiuk** [comment]
low priority.
backlog

**Comment by evjlobanova** [comment]
We addressed this issue with 3 features:
- first more reliable analyzer #893
- possibility to mark test items by "Ignored in AA" label 
- possibility to move the whole launch to Debug mode. That helps to exclude it from the ES database.
