### ISSUE TITLE
Run pybot got the error

### ISSUE THREAD

**Issue by koala2012** [reportportal/reportportal#422]
I just run the pybot command, but an got error as below

pybot --listener robotframework_reportportal.listener --variable RP_UUID:"b514a045-0a6d-4dc9-a496-fae494f8c928" --variable RP_ENDPOINT:"http://ip172-18-0-10-bc51moquguig00f5g7i0-8080.direct.labs.play-with-docker.com" --variable RP_LAUNCH:"Robotframework_test_demo" --variable RP_PROJECT:"Robotframework_test_demo" -d Results test.robot

==============================================================================
Test
test | PASS |
[ ERROR ] Calling method 'log_message' of listener 'robotframework_reportportal.listener' failed: AttributeError: 'NoneType' object has no attribute 'put_nowait'
gfp Traceback (most recent call last):
File "/Users/Larry/anaconda2/lib/python2.7/site-packages/reportportal_client/service_async.py", line 204, in process_item
getattr(self.rp_client, method)(**kwargs)
File "/Users/Larry/anaconda2/lib/python2.7/site-packages/reportportal_client/service.py", line 187, in finish_test_item
return _get_msg(r)
File "/Users/Larry/anaconda2/lib/python2.7/site-packages/reportportal_client/service.py", line 22, in _get_msg
return _get_data(response)["msg"]
File "/Users/Larry/anaconda2/lib/python2.7/site-packages/reportportal_client/service.py", line 34, in _get_data
raise ResponseError(error_messages[0])
ResponseError: 5000: Unclassified error [null]
[ ERROR ] Calling method 'end_keyword' of listener 'robotframework_reportportal.listener' failed: AttributeError: 'NoneType' object has no attribute 'put_nowait'
[ ERROR ] Calling method 'start_keyword' of listener 'robotframework_reportportal.listener' failed: AttributeError: 'NoneType' object has no attribute 'put_nowait'
[ ERROR ] Calling method 'end_keyword' of listener 'robotframework_reportportal.listener' failed: AttributeError: 'NoneType' object has no attribute 'put_nowait'
[ ERROR ] Calling method 'end_test' of listener 'robotframework_reportportal.listener' failed: AttributeError: 'NoneType' object has no attribute 'put_nowait'

my robot framework version is Robot Framework 3.0.2 (Python 2.7.12 on darwin)

**Comment by evjlobanova** [comment]
@krasoffski  maybe you can help with this issue?

**Comment by koala2012** [comment]
@krasoffski  thanks for you time to take this. this error happened always, I try this on different server had same problem. do you have any suggestions?

**Comment by koala2012** [comment]
@krasoffski I pasted my test case here, you can have try from you side.

*** *** Settings ***
Library    Selenium2Library

*** Variables ***

*** Test cases ***
test
    Open browser    http://www.baidu.com
    Close browser

gfp
    Open browser    http://www.baidu.com
    Close browser

**Comment by krasoffski** [comment]
@koala2012, thank you, try to look on weekend.

**Comment by evjlobanova** [comment]
@krasoffski thank you for your help!

**Comment by koala2012** [comment]
@krasoffski  is there any update?

**Comment by koala2012** [comment]
@krasoffski when will you take a look? thanks a lot

**Comment by krasoffski** [comment]
@koala2012 Unfortunately I am moving to a new job/project and as a result do not have free time for RP for now. :-(
