### ISSUE TITLE
It is not possible to specify the RP endpoint address

### ISSUE THREAD

**Issue by shaburov** [reportportal/reportportal#423]
There is no way to set up an address for RP -> `https://host.ru/`**reportportal**`/`
In the RP documentation and in the docker-compose configuration, there is no information about this possibility.

For example:
`https://host.ru/`**jenkins**`/`
vim /etc/default/jenkins
JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --prefix=/**jenkins**"

**Comment by avarabyeu** [comment]
it's not possible to specify server base. If you need to add some prefix, you might want to put reportportal behind some proxy server with path prefix redirection.
