### ISSUE TITLE
[Log View] make configurable log representation

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [reportportal/reportportal#43]
As a user I want to have ability to change log representation:
- font size
- margins between lines
- coloring schemes
- ....

make configuration per User. And per project.

Extra details
https://github.com/reportportal/reportportal/issues/35#issue-195251253

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/reportportal/issues/35

**Comment by evjlobanova** [comment]
@DzmitryHumianiuk what to think about this feature now?

**Comment by DzmitryHumianiuk** [comment]
Logs page will be re-worked and it is planned to make it as more close to console view as possible for raw output.
ReportPortal v6 will have dark theme, which will address coloring shema, etc.

closing for now
