### ISSUE TITLE
Tags don't trigger notifications when using the REST API

### ISSUE THREAD

**Issue by vgri** [reportportal/reportportal#432]
When importing a new launch to reportportal by REST API there is no option to add tags and description so that tags are added only by editing the launch. As the new imported launches have no tags and launch update doesn't trigger notification the result is that tags are not triggering notifications. 

Thanks!

**Comment by evjlobanova** [comment]
@vgri so the main problem is that you do not receive notifications? You want to add tag and be notified by letter, don`t you?

**Comment by evjlobanova** [comment]
@vgri could you please clarify you want to import launches with tags and description or you want to receive notification after you add tag?

**Comment by vgri** [comment]
@evjlobanova I think that having the ability to add tags and description to the launch import will solve this problem and will spare editing the launch after each import if tags are needed.

Thanks,
Vadim.

**Comment by evjlobanova** [comment]
@vgri Vadim, one more question where do you storage tags and description in xml file and can you send us an example of xml?

**Comment by vgri** [comment]
Hi @evjlobanova, We don't have any tags in our XML files. We add them after the launch. It will be great to have the option to add the tags during the zip file upload (import launch).

**Comment by avarabyeu** [comment]
@vgri unfortunately, default junit xml report doesn't support tags. Do you have any idea where the tags can be placed?

**Comment by talgreen1** [comment]
Hi,
One option is to add them as another parameter of the REST API

**Comment by aganeev** [comment]
Hi @avarabyeu ,
It is possible to use multipart/form-data as the Content Type of the request with individual parts in the multipart with Content Type of application/json and application/xml.

**Comment by avishaymahluf** [comment]
Isn't it possible to add the same parameters we have in startLaunchRQ when using the start a new launch API request?
That way, for example, we will be able to add description and tags to our launch during import without the need of using another API request for updating it and it will also trigger our tags based email notifications.

Maybe something similar to this API request:

> curl
 --request POST \\
  --url <reportportal_api>/<project_name>/launch/import \\
  --header 'accept: application/json' \\
  --header 'authorization: bearer  ...' \\
  --header 'content-type: multipart/form-data; \\
  --form file=@launch_results.zip \\
  --form 'startLaunchRQ={
  "description": "string",
  "mode": "DEFAULT",
  "name": "string",
  "start_time": "2018-08-22T09:53:01.387Z",
  "tags": [
    "string"
  ]
}'

**Comment by DuskoV** [comment]
This still seems unanswered

**Comment by Kozovskaya** [comment]
Hello @DuskoV, @vgri, 
In the 23.2 release, we added the possibility to add a launch description, attributes, and provide a name for the launch. You can create the necessary notification rules based on these parameters.
More information can be found in our documentation at https://reportportal.io/docs/log-data-in-reportportal/ImportDataToReportPortal#import-via-api
I will now mark this issue as resolved. If you have any questions, don't hesitate to contact me.
