### ISSUE TITLE
Error logged in the console when trying to open tests of certain launches

### ISSUE THREAD

**Issue by ailjushkin** [reportportal/reportportal#434]
**Current versions:** 

* Analysis Service: 4.2.0
* API Service: 4.2.1
* Index Service: 4.2.0
* Jira Service: 4.2.0
* Authorization Service: 4.2.0
* Service UI: 4.2.2

**Problem:**

Tests are not shown - the loading process never ends.

**Logs:**

[reportportal.billing.ru-1530363930987.log](https://github.com/reportportal/reportportal/files/2151728/reportportal.billing.ru-1530363930987.log)

[report portal fiddler log.zip](https://github.com/reportportal/reportportal/files/2151730/report.portal.fiddler.log.zip)

**Notes:**

We could not identify a reason of this error, it is the same launch as any other.

**Comment by evjlobanova** [comment]
@ailjushkin Alexandr, we can not open the second file, please send once again. Also could you please send us service API logs?

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova `.saz` inside `zip` can be just renamed to zip.
here it is
[TestLoadHangs.zip](https://github.com/reportportal/reportportal/files/2164375/TestLoadHangs.zip)

and i guess it's more relevant for UI team
@ArtsiomYeliseyenka plz take a look

**Comment by evjlobanova** [comment]
@ailjushkin Alexandr. could you please send us an Error from console and responses on sent request?

**Comment by evjlobanova** [comment]
Please update your version to the latest one, if the issue is still reproducing, feel free to reopen the issue
