### ISSUE TITLE
Jira integration: Bug priority is always `Minor`

### ISSUE THREAD

**Issue by ulmanA** [reportportal/reportportal#436]
No matter which priority (mandatory field) you set when posting a bug from ReportPortal -
the actual priority on Jira will always be `Minor`

**Comment by evjlobanova** [comment]
@e-olga Olga, could you please check this issue?

**Comment by e-olga** [comment]
hi all,
@ulmanA, we have such defect in our backlog. 
@evjlobanova, I think we will discuss whether the issue could be included into the nearest sprints.
