### ISSUE TITLE
Unable to upload test results to reportportal

### ISSUE THREAD

**Issue by vamsivb** [reportportal/reportportal#438]
We have used nunit framework and C# for our reportportal implementation. 
Nunit version - Console Runner 3.7.0
.NET Framework 4.5

we have followed the instructions form link(https://github.com/reportportal/agent-net-nunit) to integrate reportportal with test framework. But, results are not reflected in report portal. please suggest if we have to change anything in setup to see the results in reportportal.

**Comment by nvborisenko** [comment]
@vamsivb please see an example of nunit integration: https://github.com/reportportal/example-net-nunit
Does it work with your instance of RP server?

**Comment by vamsivb** [comment]
@nvborisenko  thanks for the quick reply 

as suggested, I've cloned 'Example' project from link(https://github.com/reportportal/example-net-nunit) and created a ReportPortal.addins file in the NUnitRunner folder with the following content:
../Example/bin/Debug/ReportPortal.NUnitExtension.dll

see the below images for reference
![image](https://user-images.githubusercontent.com/40848389/42321330-3015fc00-8076-11e8-8040-6da697efec6c.png)
![image](https://user-images.githubusercontent.com/40848389/42321578-17bb210c-8077-11e8-91fa-212926a11aec.png)

and also updated url, project and uuid in ReportPortal.conf file. 
but results are not reflected in RP.

**Comment by nvborisenko** [comment]
May be here?
![screenshot_1](https://user-images.githubusercontent.com/22616990/42325533-2faa2e5a-806f-11e8-8c8a-77cba5aecb9e.png)

**Comment by nvborisenko** [comment]
@vamsivb did you find your results in web interface?

**Comment by vamsivb** [comment]
@nvborisenko  nope.

**Comment by nvborisenko** [comment]
Some error messages in console output?

**Comment by rupamchakraborty** [comment]
Hi @nvborisenko ,
I'm facing the same problem as well , here are the details, please help - 
**Report Portal Deployment + Installation -** Done using Docker toolBox on Win 10 Home.  Most of the services are UP post deployment , screenshot attached 
![image](https://user-images.githubusercontent.com/27431386/47061451-88354d80-d19f-11e8-8bea-42deb8d1590c.png)

I have a sample SpecFlow based C# project which I'm executing using Nunit-Console3.exe. I have done the recommended settings in config file, added the addins file as well.
When I run the nunit console3.exe command it states sending results to Report Portal but I can't see the results. Screenshots below - 
![image](https://user-images.githubusercontent.com/27431386/47061519-cfbbd980-d19f-11e8-9b46-632ada75d7d5.png)

![image](https://user-images.githubusercontent.com/27431386/47061605-33460700-d1a0-11e8-8f18-955c482969c2.png)

Please let me know if you need more details.

**Comment by nvborisenko** [comment]
First of all, you installed 2 extensions: for nunit and specflow. NUnit reporter works fine, it is sending results somewhere. Specflow reporter is configured incorrectly.

And verify your RP deployment, I see failing services. Guess all should be passed.

**Comment by rupamchakraborty** [comment]
here you go 
![image](https://user-images.githubusercontent.com/27431386/47086929-bdb25900-d1e8-11e8-9e3b-e8a061f6dae6.png)

**Comment by rupamchakraborty** [comment]
I got it finally, its the Debug where its spitting the results for Default_Project, thanks.  Sorry for the confusion.

![image](https://user-images.githubusercontent.com/27431386/47086980-e2a6cc00-d1e8-11e8-8648-3c37641d595c.png)

**Comment by sjabbal8** [comment]
Hi 
I am unable to upload the results . 
![image](https://user-images.githubusercontent.com/113338514/203546790-592d7b53-5a95-453c-b948-d66b4e25fe09.png)

Can you please help me with it if i am missing something.
