### ISSUE TITLE
Not getting any data on widget when selecting Start Time in filter 

### ISSUE THREAD

**Issue by vivektamrakar91221** [reportportal/reportportal#440]
Whenever I am trying to create a new filter, taking Start Time as one of the option and then selecting any one of the options in the drop down i.e. 'Today', 'Last 2 Days', 'Last 7 Days', 'Last 30 Days', getting below error.
"Bad save user filter request. Incorrect zoneOffset. Expected='+h, +hh, +hh:mm'. Provided value is '+5.5"

After selecting specific time range when user is creating filter, filter is getting created.
[Widget add with filter.docx](https://github.com/reportportal/reportportal/files/2179907/Widget.add.with.filter.docx)

Please find recording in the attached Doc

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/reportportal/issues/440
