### ISSUE TITLE
Separate description field in the JIRA issue posing page

### ISSUE THREAD

**Issue by ailjushkin** [reportportal/reportportal#441]
**Proposal:**
Supporting such use-case would be very appreciated: 

1. Open failed test
2. Open JIRA issue posting page
3. Fill in a description field to be posted into the JIRA, or check in the checkbox "As in the test comment".
4. Unchecking this checkbox allows to edit the test comment.

**Current version:**

- Analysis Service: 4.2.0; 
- API Service: 4.2.1; 
- Index Service: 4.2.0; 
- Jira Service: 4.2.0; 
- Authorization Service: 4.2.0; 
- Service UI: 4.2.2; (edited)

**Comment by DzmitryHumianiuk** [comment]
cover with editor (text field) of ticket description in Post Bug dialog.

**Comment by MaryiaRymarchyk** [comment]
@DzmitryHumianiuk  From my perspective, the task has lost its relevancy. Currently, the Jira plugin retrieves all fields directly from the BTS, enabling users to gain access to all required fields by configuring them directly in Jira. 
Please let me know if the ticket can be closed or you see any value in it.
