### ISSUE TITLE
Add reason description into the test history during AA.

### ISSUE THREAD

**Issue by ailjushkin** [reportportal/reportportal#442]
**Use-case:**

1. Someone incorrectly marked a failed test with a wrong category.
2. This caused to appearing of series of tests marked with a wrong category after the automatic analysis.
3. During investigation of failed tests marked with AA, user finds that some test was marked with wrong category.
4. User looks into the test history and sees:

- **User:** service-analyzer 
- **Action:** set up category "Category 1"
- **Reason:** 
-- **Launch:** Some 123 (hyperlink)
-- **Based on test Item:** Test With Some Error (hyperlink)
-- **Updated by:** Vasya on 05.03.2018

The goal of this scenario is to know the initial point of appearing the data for the automatic analysis.

**Comment by ailjushkin** [comment]
Hi, guys! Thank you very much indeed for the quick implementation of this feature!

Could you please add more details about that: what if I set up my project to keep logs for 2 weeks? What will happen on the first day of the third week of launches? What item will be opened by clicking on the "Based on the item" hyperlink? :)

**Comment by ailjushkin** [comment]
@evjlobanova right, so, can we somehow save a user name of manually added item and possibly a text of error?

**Comment by evjlobanova** [comment]
@ailjushkin could you please explain what you mean under "a user name of manually added item"?

**Comment by ailjushkin** [comment]
@evjlobanova will by saying that I meant a username connected with this information, someone who added this information into the database, but keep that info more than "time to keep logs" value. Unfortunately, I can't say whether it would be efficient from the point of an architecture view, but anyway
