### ISSUE TITLE
Feature request: Add possibility to send logs and attachments straight to the launch 

### ISSUE THREAD

**Issue by SrinivasanTarget** [reportportal/reportportal#444]
For say, i would like to add server logs which are not independent for each test run or suite run. How do we attach a server log or any log globally?

**Comment by evjlobanova** [comment]
@SrinivasanTarget Could you please add more details? Do you want to add logs to launch?

**Comment by SrinivasanTarget** [comment]
@evjlobanova Yes something of that sort. Ideally logs i'm talking about are not specific to single/each test. Its common for entire test suite execution. So is there any way i can add logs to launch or 
in dashboard?

Another question:
* Is there a way to add dashboard programmatically with some information (e.g server version, client version, execution time, log path, etc.

**Comment by evjlobanova** [comment]
@SrinivasanTarget Unfortunately no we do not have know such possibility, but such feature in our Backlog.  Could you clarify your second question? You want to add something on widget?  Or could you send a screenshot with your idea?

**Comment by SrinivasanTarget** [comment]
@evjlobanova Something like this....
![image 1](https://user-images.githubusercontent.com/8896549/42816111-55a89d7c-89e7-11e8-883c-00c5f605111b.png)

**Comment by evjlobanova** [comment]
@SrinivasanTarget could you please tell me what is the business need? What problem do you want to solve?

**Comment by SrinivasanTarget** [comment]
@evjlobanova It helps us to show what kind of env configurations does the tests ran.

**Comment by evjlobanova** [comment]
@SrinivasanTarget  Where do you want to add this information?

**Comment by DzmitryHumianiuk** [comment]
@SrinivasanTarget 
there is not out of the box, same looking widget at the moment.
We assume to add special Launch variables after 5.0 version. Which can be represented on sub-launch widgets view #259

But for now, you can represent this data in launch `description` or `tags`
Just push this data as a part of launch params on start, and you will get:
![image](https://user-images.githubusercontent.com/11332788/42824927-951cae2e-89e9-11e8-90bc-1695f13b3bde.png)

And on dashboard page, you can add `launch table` widget, uncheck all fields except of description and/or tags.
And show it like that:
![image](https://user-images.githubusercontent.com/11332788/42825106-f8328998-89e9-11e8-93c6-bd7c2bcd5433.png)

**Comment by DzmitryHumianiuk** [comment]
@SrinivasanTarget for the main request: `Add possibility to send logs and attachments straight to the launch`
it's planned, and we consider to add possibility to log data directly to the launch root object, including files and any other binary data.

can't predict ETA for now, since we still doing migration to postgreSQL within version 5

**Comment by SrinivasanTarget** [comment]
@DzmitryHumianiuk Thanks for details. Can you also let me know if there are any sample code in java testNG where we can send log data directly to **launch** will help me a-lot? Would be good to know how to tag as well.

**Comment by DzmitryHumianiuk** [comment]
@SrinivasanTarget 
>if there are any sample code in java testNG where we can send log data
do you mean to send into description, like mentioned here? https://github.com/reportportal/reportportal/issues/444#issuecomment-405610781

**Comment by DzmitryHumianiuk** [comment]
if yes - then just send it as launch params on start
`rp.description = Enviroment xxx`

**Comment by SrinivasanTarget** [comment]
@DzmitryHumianiuk thanks that helps. Is there a way we can tag a launch programmatically, coz same test suite can be used as regression, smoke, bla bla bla? Sorry for raising lot of questions on same thread.

**Comment by DzmitryHumianiuk** [comment]
@SrinivasanTarget 
`rp.tags = TAG1;TAG2`

file example
https://github.com/reportportal/example-java-TestNG/blob/master/logback/src/main/resources/reportportal.properties

it can be added into properties file, for launch.
or bypassed via commend line as `-Drp.tags=blablabla`

**Comment by evjlobanova** [comment]
@SrinivasanTarget Hello! Could you please describe your analysis flow in case you have launch logs? How do you plan to analysis launch attachments and logs? In which case do you look through the log messages?

**Comment by evjlobanova** [comment]
#526 
Close as a duplicate

**Comment by Onish1204** [comment]
Apart from snapshot, Any way to attach other type of files with TestNG test. i.e. excel, gif etc. if not at test level at-least do we have provision to attach it at launch level (Using rp ver 5.1).
if yes, please share code for same...  

Appreciate your help in this regards...

**Comment by DzmitryHumianiuk** [comment]
@Onish1204 you can attach any type of files.
Right to the logs, or at Launch level.

https://github.com/reportportal/examples-java/blob/master/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/logging/JsonLoggingTest.java#L28

**Comment by Onish1204** [comment]
Code available if for json file, how should we change it to load xlsx file.

**Comment by DzmitryHumianiuk** [comment]
@Onish1204 https://github.com/reportportal/examples-java/blob/master/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/logging/LuckyPugTest.java
