### ISSUE TITLE
[Feature request] Map new test name to an old one

### ISSUE THREAD

**Issue by jan-zmeskal** [reportportal/reportportal#445]
Imagine this scenario: 
* You have a test case that is called `test_login` that you are running regulary. After a while, this test case has nice history of execution in RP.
* During the execution of this test case, you always log in as user `admin` let's say
* After a while, you realize that use should also testing logging as user `regular`, so you parametrize you test case
* Now you actually have two test cases with two signatures: `test_login[admin]` and `test_login[regular]`.
* You run your regression suite and go check RP. You navigate to `test_login[admin]` and see that there is no history of launches.

Now you probably understand where I am going with this. The launch history in RP is constructed based on test case name. In our imaginary scenario, the test case name was changed for a good reason. However, even when now it is called `test_login[admin]`, it is still actually the very same test as the original `test_login`. It would be great if we could somehow instruct RP to trest history of `test_login` as also being history of `test_login[admin]`. 

Thank you.

**Comment by evjlobanova** [comment]
@jan-zmeskal Is it important for you to add information about `admin` to the test name? Is it possible for you to add this info as description to test case for example? Or give a tag `admin` / `user`?

**Comment by jan-zmeskal** [comment]
@evjlobanova This is just the way how [pytest](https://docs.pytest.org/en/latest/) works and is supposed to be used. I actually provided somewhat stupid example for easier understanding. Our real-life situation is more complicated and unfortunately the change in tests' parametrization cannot be avoided.

**Comment by DzmitryHumianiuk** [comment]
@jan-zmeskal closing issue for now.
plz reopen or open new, in case if it didn't help

**Comment by jan-zmeskal** [comment]
Hello @DzmitryHumianiuk. Thank you very much for such an exhaustive and in-depth explanation! I'll definitely look into it - I was not aware of existence of `uniqueID` and of the way it is composed.

Have a nice day!
