### ISSUE TITLE
Auto - Analysis can't work when screenshot is added to the log

### ISSUE THREAD

**Issue by Tevek** [reportportal/reportportal#446]
I enhanched my reportPortal glue code with a screenshot upload capability, but after that the AA is not working anymore...
Probably i changed the sendLog function with sendLogWithFile in the JS code and I assume that image ruins the log, and the AA can't parse the errors with the latest runs.

Vers.
image: 'mongo:3.4'
image: 'consul:1.0.6'
image: 'reportportal/service-authorization:4.1.0'
image: 'fabiolb/fabio:1.5.8-go1.10'
image: 'reportportal/service-index:4.0.0'
image: 'reportportal/service-api:4.1.0'
image: 'reportportal/service-ui:4.1.0'
image: 'reportportal/service-analyzer:4.1.0'
image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4'
image: 'reportportal/service-jira:4.1.0'
image: 'reportportal/service-rally:4.0.0'

Is it familiar for you guys?

**Comment by evjlobanova** [comment]
@Tevek  Screenshots don`t influence on the working process of aa. Could you please give me more details. First, please check how many items are in the Index;

>Note: If you do not sure how many documents(logs) are contained in the Index on that moment, you can check it. For that, perform following actions:
Uncommented Service ElasticSearch ports in docker-compose file or add them: 9200:9200;
Restart Service ElasticSearch with new docker-compose;
Send a request to ElasticSeaarch:
how many documents in the Index: GET http://localhost:9200/_cat/indices?v
Detailed information: POST http://localhost:9200/{project_name}/_search

Second questions which  log level have your logs in tests?

**Comment by Tevek** [comment]
Yea, so 
It's working as expected, the reason of this issue was the logging level
I was silly when I introduced the sendLogWithFile function and it's modified the logging level to 'info'
So the solution for me is: Change the log level back  to 'Error' at least
Thank You, evjlobanova!
