### ISSUE TITLE
'Launch inactivity timeout' setting doesn't work

### ISSUE THREAD

**Issue by doctordrue** [reportportal/reportportal#447]
'Launch inactivity timeout' setting doesn't work
## Steps to reproduce
Has been found on our private Rp instance, can be reproduced on https://rp.epam.com
### Preconditions
1. Login to RP (e.g. https://rp.epam.com) and go to your personal project settings
1. Set up 'Launch inactivity timeout' to **1 hour**:
![default](https://user-images.githubusercontent.com/16087661/43076699-b2ef9008-8e8d-11e8-9cd6-d7b17c6a709e.png)
### Steps
1. Create unfinished launch, e.g. through the API:
   1. Go to API page
![default](https://user-images.githubusercontent.com/16087661/43076734-d3d1db32-8e8d-11e8-87f0-132139577d2d.png)
   1. go to launch controller -> POST, fill **projectName** with name of your personal project, copy **startLaunchRQ** from the example on the right and click **Try it out!**
![default](https://user-images.githubusercontent.com/16087661/43076931-8e94f1ac-8e8e-11e8-81a1-d33ae1b17219.png)
   1. See unfinished launch has been created:
![default](https://user-images.githubusercontent.com/16087661/43076959-aedfded6-8e8e-11e8-8556-d7da58fccea4.png)
1. Wait for an hour and check if launch has been force finished or not

**Comment by svettsova** [comment]
fixed in 5.1 version

**Comment by BenManifold** [comment]
This really needs to be something we can just specify, and not a dropdown. It makes it a lot harder to merge launches from a single CI job that happens to split the workload across pods.

**Comment by Kozovskaya** [comment]
Hello @BenManifold 
could you please specify what value for the launch inactivity you need to specify in your case? As for now values presented are rather flexible and your request is unique. So if you could provide your use case and values you need, this will help us to understand the value of this enhancement for other users.

**Comment by BenManifold** [comment]
More options in the sub-30 minute range, as low as 1-5 minutes.
