### ISSUE TITLE
[Feature request] a way to share dashboard publicly 

### ISSUE THREAD

**Issue by tareqalayan** [reportportal/reportportal#449]
It will be nice to have the ability to share graphs to people which are not report portal users.
And they can vies the graphs and dashboard as readonly users. 
Currently we do screenshots and paste these screenshots on a different document or email to share the results with other non-reportportal users.

or maybe a way to export the dashboard to a pdf or something

**Comment by evjlobanova** [comment]
@tareqalayan as a quick decision: now you can use feature Print CSS: 
- choose print in a browser;
- save page in PDF.
It is a possible decision for exporting the dashboard to PDF.

**Comment by evjlobanova** [comment]
@tareqalayan we have the same request here #2, so I close your issue as a duplicate. This feature in our backlog and we have intention to implement it. But first of all we should to define the way of realization.
