### ISSUE TITLE
Allow to finish launch with provided status (passed|failed) aka "Skipped test items are marking launch status as failed"

### ISSUE THREAD

**Issue by avishaymahluf** [reportportal/reportportal#451]
Hi,

When I'm pushing a test item with skipped status to an existing launch without any failure, the status of the launch is failed:
![screenshot from 2018-08-01 09-52-23](https://user-images.githubusercontent.com/20201128/43520307-1f6816ba-959b-11e8-822b-824fb2ebb93c.png)

I've also tried to add `issue: {'issue_type': 'NOT_ISSUE'}` to the skipped items but it didn't help (in order to remove the "TO INVESTIGATE").

When I'm trying to force the launch to be PASSED I get the following error from reportportal:

> Cannot finish launch '5b5ea7e897a1c00001795f8b' with calculated automatically status 'FAILED' as 'PASSED'. Did you provide correct status in request?

**Comment by evjlobanova** [comment]
@avishaymahluf which agent do you use?

**Comment by avishaymahluf** [comment]
@evjlobanova I'm using the python client directly without an agent:
https://github.com/reportportal/client-Python

We're parsing the test results in our own code and just using the service to push the results.

**Comment by evjlobanova** [comment]
@avishaymahluf unfortunately we do not have any python specialist in our team. But I can recommend your to address this issue to our community in python slack channel https://reportportal.slack.com/messages/C9PMAA690 . May be they can help you.

**Comment by avishaymahluf** [comment]
@Tygerian I agree, this is not related to python agent. This can be easily reproduced via API.

I talked about this issue also in reportportal slack and got a response from @DzmitryHumianiuk saying that they will allow updating the status to pass in version 5.0:
https://reportportal.slack.com/archives/C2GTJTTNH/p1533156367000053

**Comment by DzmitryHumianiuk** [comment]
@avishaymahluf @Tygerian right.
we consider to add possibility to finish launch with any desired status.
and follow simple flow: if status provided, then set status. If not - use our strategy to identify it. 

will be available with 5.0

for ongoing implementation, we will consider also to add additional statuses as WIP (work in progress) and Empty state (equal to _not implemented_ )

**Comment by naddison** [comment]
Is there any update to this? This seems like a huge oversight to consider skipped tests a failure.

**Comment by DzmitryHumianiuk** [comment]
@naddison will be in v5. out of the box.

**Comment by evjlobanova** [comment]
The feature will be available in the beta release of version 5.

## Reporting 
If a user sends a launch status on the finish, the system should use a received status.
In case of status hasn`t been sent, the system calculates status based on the rule: 
"at least one step isn`t Passed, a launch is failed"
**API**
request 
Launch controller PUT/{projectName}/launch/{launchId}/finish
```
{
  "attributes": [
    {
      "key": "string",
      "system": true,
      "value": "string"
    }
  ],
  "description": "string",
  "endTime": "2019-07-25T09:23:53.089Z",
  "status": "PASSED"
}
```
