### ISSUE TITLE
Add launch description to detailed view

### ISSUE THREAD

**Issue by leistnerova** [reportportal/reportportal#453]
Launch description is visible in all launches view

![screenshot from 2018-08-08 10-28-38](https://user-images.githubusercontent.com/29575480/43826257-33984310-9af7-11e8-891c-1a847349096c.png)

but when I go to detailed view, it is missing. Add it please also there, e.g. like this

![screenshot from 2018-08-08 10-28-50](https://user-images.githubusercontent.com/29575480/43826317-5824769a-9af7-11e8-998c-6dd26282c5db.png)

**Comment by evjlobanova** [comment]
@leistnerova Could you please explain the main goal of this improvement?  What it is your main business need?

**Comment by leistnerova** [comment]
We have link to our testing machine with all different logs and settings in the description. And when I get link to specific launch detail to investigate, I need to go to this link to get more informations.
So is for us more comfortable to see it there and not to find the specific launch in all launches to get the link.

**Comment by nvborisenko** [comment]
The same for me, when I open details page for entity, I want to see details, all related info about entity.

**Comment by evjlobanova** [comment]
@Iren-Melnyk Take a look please on this case

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko @leistnerova when you will drilldown, into suite level.
you still expect to see launch details? you see suite details at this level?

**Comment by leistnerova** [comment]
@nvborisenko According to our needs, It is sufficient to have the launch description in the level directly below the launch. From every other nested level (e.g. specific test case) we can always go directly to the launch from the breadcrumb.

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko what do you think?

**Comment by nvborisenko** [comment]
Right, when I am on launch details page, it's enough to see details only for launch. When I am on suite details page - launch description is unnecessary.

**Comment by DzmitryHumianiuk** [comment]
@leistnerova @nvborisenko 
So when you inside suite - you what to see suite details?
Inside this view

**Comment by DzmitryHumianiuk** [comment]
and make it collapsable :)

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova put it into 5.0 ui

**Comment by nebehr** [comment]
@Iren-Melnyk you already have "Item Details" section on the Test level, why can't it be generalized for other levels? I imagine people would want to see description/tags they added not just for the current launch but for current _anything_, wouldn't they?
