### ISSUE TITLE
AA not working

### ISSUE THREAD

**Issue by nkthota** [reportportal/reportportal#455]
AA feature is not working with log level as an error. are there any steps to debug the issue? starting the analyze manually just blinks without any progress or updates.

**Comment by evjlobanova** [comment]
@nkthota could you please send me screenshot with your AA configurations?

**Comment by nkthota** [comment]
![image](https://user-images.githubusercontent.com/11020602/43959413-60c0cb22-9c74-11e8-9f91-5a19140211d5.png)

**Comment by evjlobanova** [comment]
@nkthota you can update your existing version to the latest. in the latest version we have separate tab with AA configurations. In case you update version, I can try to help you to choose corrrect ElasticSearch configurations for analyzer

**Comment by nkthota** [comment]
I think I'm missing the AA configuration. I don't see a separate tab for AA am I missing something here?
 Current version: API Service: 4.1.0; Index Service: 4.0.0; Jira Service: 4.1.0; Rally Service: 4.0.0; Authorization Service: 4.1.0; Service UI: 4.1.0;

**Comment by evjlobanova** [comment]
@nkthota As I said earlier, you need to update you current version to the latest one

**Comment by nkthota** [comment]
i have updated to 4.2

![image](https://user-images.githubusercontent.com/11020602/43963694-a210bab8-9c80-11e8-8968-033a93e53aa5.png)

**Comment by evjlobanova** [comment]
@nkthota Please set the following configurations, and run AA once again. 
![image](https://user-images.githubusercontent.com/30413511/43963810-0b4d17f4-9cc4-11e8-94f2-b723832dba7e.png)

Please give me know the results of your attempt

**Comment by nkthota** [comment]
i dont see it working. i triggered the analysis manually but dont see any results.

![image](https://user-images.githubusercontent.com/11020602/43964848-54fc1f30-9c83-11e8-822d-ca019fc2c5f5.png)

**Comment by evjlobanova** [comment]
@nkthota could we set up a call via skype?

**Comment by nkthota** [comment]
sure we can do that. my skype id naveen38096
![image](https://user-images.githubusercontent.com/11020602/43965353-9f906dca-9c84-11e8-8887-0507f382339a.png)

**Comment by evjlobanova** [comment]
@nkthota please check Consule localhost:8500, and send us a screenshot

**Comment by nkthota** [comment]
![image](https://user-images.githubusercontent.com/11020602/43965645-6aa7c328-9c85-11e8-99ff-6d85140dce89.png)

**Comment by evjlobanova** [comment]
@nkthota 
ok, thank you. 
You should clean a consul cash. 
Then perform actions which are described on http://reportportal.io/download on the second step.
![image](https://user-images.githubusercontent.com/30413511/43965883-17da4f00-9cc9-11e8-9c6b-313d0aabfa06.png)
 
Than re-start docker-compose.

**Comment by nkthota** [comment]
still no luck.

![image](https://user-images.githubusercontent.com/11020602/43967425-f87ffcfc-9c89-11e8-9cd4-f1b06985de76.png)

**Comment by nkthota** [comment]
i'm able to get it working now. thanks for the prompt support.

**Comment by evjlobanova** [comment]
@nkthota try to use AA with configurations that I have send. And also could you please share with me with your experience? I am aggregating info about accuracy of AA and users` satisfaction of AA results.
