### ISSUE TITLE
Password has limited length up to 25 symbols

### ISSUE THREAD

**Issue by pkubica** [reportportal/reportportal#457]
Password length shouldn't be limited or the limit should be higher. LastPass and other utilities for storing password could work with longer password (up to 100 symbols).

Second reason if somebody is using ldap (and kerberos) authentication across multiple sites, tools (using one password) and he has password with length 30 symbols, he isn't able to login into reportportal until he change his password to shorter form in ldap and then he must use this shorter form in all sites managed by ldap authentication.

**Comment by evjlobanova** [comment]
@pkubica Yes, it is logical point. Could you please explain how you define the max limit for the password (100 symbols)?

**Comment by pkubica** [comment]
@evjlobanova I do some research about password length and I found a methodology [1] published by OWASP. They limit the password length to 128 characters.

[1] https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Password_Length
