### ISSUE TITLE
POST /{projectName}/launch returns 201 for non-existing project

### ISSUE THREAD

**Issue by dagansandler** [reportportal/reportportal#459]
When using the API and supplying a wrong project name, the response returns with a status code 201 (created) and a response body with `number` and `id` fields as if they were actually created.

Steps to reproduce:
1. Send an HTTP request to create a new launch under a **non-existing** project, using any method (Tested through `curl` and through server's swagger API page

Expected Result:
1. A response with some error code indicating that the launch could not be created

Actual Result:
1. Response with status code 201 (created) is returned, with an actual launch id

**Comment by evjlobanova** [comment]
@dagansandler we have checked this issue, this issue is reproducing only for admins. We will fix it. Thank you for post this.

**Comment by DzmitryHumianiuk** [comment]
@pbortnik 4.3.1?

**Comment by e-olga** [comment]
The issue is fixed and not available in RP v.5.0

Regards,
Olga
