### ISSUE TITLE
Populate TestNG group to PR launch tags

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [reportportal/reportportal#46]
TestNg provide ability to set execution groups, will be nice if PR will add group(s) to launch tags + tags from `reportportal.properties` file.

By @adminz

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu will we have it in new TestNG agent, after async client release?

**Comment by avarabyeu** [comment]
@DzmitryHumianiuk @admizh Now it's possible with 3.0.0 version of TestNG client. Documentation should be updated with examples. Closing the issue.
