### ISSUE TITLE
Different "items per page" setting for launches and filtered results

### ISSUE THREAD

**Issue by Rider1982** [reportportal/reportportal#460]
Now there is the same "items per page" value for both launch results and launch items. It is not so comfortable. Often I need a lot of filtered results for a bulk operation and I use 300 items per page to avoid pagination. And this works fine and quickly. But the launch list is too slow to show 300 launches: it takes significantly long time to display and cannot be scrolled smoothly and quickly. It is a good idea to use different values for launches per page and results per page.

Also, there is a little question: is it possible to remove the limit of 300 items per results page?

**Comment by evjlobanova** [comment]
Hello, @Rider1982 ! I am discussing with a team these possibilities.  Could you please tell me what max limit is preferable for you?

**Comment by DzmitryHumianiuk** [comment]
@Iren-Melnyk what do you think about different items-per-page for launches and test cases view?

**Comment by Rider1982** [comment]
Hello @evjlobanova! Now I have about 800 tests and I want to have, for example, 1000 items on a page. Later I may want to see 2000, 10000 etc items. So any pre-defined limit may be insufficient for a project. So if you cannot abandon the limit at all, let's keep it as is.

**Comment by evjlobanova** [comment]
Fixed in version 5.0
