### ISSUE TITLE
RP is not able to show old launches

### ISSUE THREAD

**Issue by lifemanship** [reportportal/reportportal#463]
Current version: API Service: 4.2.1; Index Service: 4.2.0; Authorization Service: 4.2.0; Service UI: 4.2.2;

We setup RP options in the next manner:
![image](https://user-images.githubusercontent.com/6093708/44407906-ea8b1c80-a567-11e8-9b82-ccabf356717a.png)

But RP shows launches only for the last ~4 month.
For example:
- RP page 684 at the time of 4 days ago:
![image](https://user-images.githubusercontent.com/6093708/44408483-2377c100-a569-11e8-99fb-97ec04c7cac5.png)
- RP page 684 at the time of 2 days ago:
![image](https://user-images.githubusercontent.com/6093708/44408566-4dc97e80-a569-11e8-9c6d-24726a0d52f5.png)
- RP page 684 at now:
![image](https://user-images.githubusercontent.com/6093708/44408627-6afe4d00-a569-11e8-99d5-a33b5ffb2284.png)
If i open page 685 i always see **No results found**
![image](https://user-images.githubusercontent.com/6093708/44408788-bca6d780-a569-11e8-96a0-17b40cca5644.png)

As you can see our RP instance has about 88000 launches but shows only last ~34000.
Is it restriction? If so could you please add an option to enable/disable it

**Comment by e-olga** [comment]
hi @lifemanship 
There is a restriction on Mongo side.
"Unclassified error [Query failed with error code 96 and error message 'errmsg: "Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit."' on server http://host:27017; nested exception is com.mongodb.MongoQueryException: Query failed with error code 96 and error message 'errmsg: "Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit."' on server http://host:27017]"
There could be some options to resolve it:
1) add index for "start_time", but in case you will use any another sorting parameter, it will not work again
2) search for a way to increase the Mongo's restriction on operation
3) Merge launches into one 
4) Use some projects for different launches

Could you please share your thoughts/decision on this?

Thank you,
Olga

**Comment by DzmitryHumianiuk** [comment]
@lifemanship could you plz explain you goal, to see more then 34'000 launches back?

Does it have an meaningful reason? or just testing?

if testing, I propose to close issue.
because we migrating on PostgreSQL, and this will be irrelevant pretty soon

**Comment by DzmitryHumianiuk** [comment]
@lifemanship up

**Comment by lifemanship** [comment]
Thanks for the answer, and one more question do you plan to provide some functionality to migrate data from mogo db to postgress db?

**Comment by DzmitryHumianiuk** [comment]
@lifemanship yes. We will provide
