### ISSUE TITLE
Unable to integrade the reprotal portal with spock

### ISSUE THREAD

**Issue by greenleaves1** [reportportal/reportportal#464]
Exception in thread "org.spockframework.runtime.RunContext.stop()" com.epam.reportportal.exception.ReportPortalClientException: Report Portal returned error
Status code: 404
Status message: Not Found
Error Message: Launch 'null' not found. Did you use correct Launch ID?
Error Type: LAUNCH_NOT_FOUND

**Comment by greenleaves1** [comment]
which testing framework you gays actively maintain, right now I am thinking to use spock but open to junit 5

**Comment by user390181** [comment]
is this currently on the roadmap?  This reporting framework looks great but we are blocked from using it due to integration issues with Spock.

**Comment by DzmitryHumianiuk** [comment]
@user390181 no it's not.
we are in a rush with 5.0 and client requests.
have no enough hands to do all things.

so if you can make an input into it, we will really appreciate this!

**Comment by atulsareen1** [comment]
If someone is doing RP setup and facing 
"Error Message: Launch 'null' not found. Did you use correct Launch ID?". 
Add 'client-java-core' dependency and try. It worked for me.

**Comment by JustAlexOne** [comment]
> If someone is doing RP setup and facing
> "Error Message: Launch 'null' not found. Did you use correct Launch ID?".
> Add 'client-java-core' dependency and try. It worked for me. (Frameworks: Geb, Spock, Groovy, Maven)

Yep, I had the same iisue, adding `compile 'com.epam.reportportal:client-java-core:2.7.1'` helped, thank you!

**Comment by Ngaur** [comment]
Same issue I am experiencing with TestNG.
Getting Error : 
com.epam.reportportal.exception.ReportPortalClientException: Report Portal returned error
Status code: 404
Status message: Not Found
Error Message: Launch '8dabd205-f030-47a7-b761-13d458e738d0' not found. Did you use correct Launch ID?
Error Type: LAUNCH_NOT_FOUND


I am using :
<dependency>
  	<groupId>com.epam.reportportal</groupId>
  	<artifactId>agent-java-testng</artifactId>
  	<version>5.0.8</version>
</dependency>
<dependency>
     <groupId>org.testng</groupId>
     <artifactId>testng</artifactId>
     <version>7.3.0</version>
</dependency>

Adding custom listeners like following:
      ```
ReportPortalTestNGListener listener = new ReportPortalTestNGListener();
TestNG tng = new TestNG(); 
 tng.setXmlSuites(suites);
 tng.addListener(listener);
 tng.run();
```

**Comment by HardNorth** [comment]
Offtopic
