### ISSUE TITLE
GET /{projectName}/item returns results from another projects

### ISSUE THREAD

**Issue by ludeknovy** [reportportal/reportportal#465]
Send request: 
```
curl -X GET --header 'Accept: application/json' --header 'Authorization: bearer {token}' '{baseUrl}/api/v1/{projectName}/item'
```
api returns results not bound to specified `projectName`.

Expected behaviour:
Because `projectName` is required param I do expect results to be strictly bound to given project.

**Comment by e-olga** [comment]
@ludeknovy 
The issue is fixed and will be available in v.4.3.

Regards,
Olga
