### ISSUE TITLE
[MAILS] Make invitation emails more friendly

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [reportportal/reportportal#47]
The invitation email looks suspicious and 3 members from my team (they are in different locations so they even didn't discuss it) just ignored it and considered like a spam! 

Customers can do the same. 
The information about the project and sender should help in this case, 
e.g. "_John Doe invites you to join the XXX project on the **Report Portal**_".

**Comment by Iren-Melnyk** [comment]
We made it more user-friendly
![letter_invitation](https://user-images.githubusercontent.com/23101832/27787887-16b91f88-5fef-11e7-95cb-0271fb1bd959.png)
