### ISSUE TITLE
Cannot create container for service elasticsearch: invalid option: Windows does not support Ulimits

### ISSUE THREAD

**Issue by con-hluong** [reportportal/reportportal#470]
C:\Users\hluong\Downloads\HelloDocker>docker-compose -p reportportal up -d --force-recreate
Recreating reportportal_rally_1 ...
Recreating reportportal_gateway_1 ...
Creating reportportal_elasticsearch_1 ... errorRecreating reportportal_jira_1        ...
Creating reportportal_mongodb_1       ...
Creating reportportal_registry_1      ...
Recreating reportportal_ui_1          ...

Creating reportportal_registry_1      ... error
ERROR: for reportportal_elasticsearch_1  Cannot create container for service elasticsearch: invalid option: Windows does not support Ulimits
Creating reportportal_mongodb_1       ... error
Recreating reportportal_gateway_1     ... error
sers\hluong\Downloads\HelloDocker\data\consul:/consul/data:rw': invalid mount config for type "bind": bind mount source path does not exist: c:\users\hluong\downloads\hellodocker\data\consul
Recreating reportportal_rally_1       ... done
ERROR: for reportportal_mongodb_1  Cannot create container for service mongodb: invalid volume specification: 'C:\Users\hluong\Downloads\HelloDocker\data\mongo:/data/db:rw'

ERROR: for reportportal_gateway_1  Cannot start service gateway: failed to create endpoint reportportal_gateway_1 on Recreating reportportal_ui_1          ... done
Recreating reportportal_jira_1        ... done

ERROR: for elasticsearch  Cannot create container for service elasticsearch: invalid option: Windows does not support Ulimits

ERROR: for registry  Cannot create container for service registry: invalid volume specification: 'C:\Users\hluong\Downloads\HelloDocker\data\consul:/consul/data:rw': invalid mount config for type "bind": bind mount source path does not exist: c:\users\hluong\downloads\hellodocker\data\consul

ERROR: for mongodb  Cannot create container for service mongodb: invalid volume specification: 'C:\Users\hluong\Downloads\HelloDocker\data\mongo:/data/db:rw'

ERROR: for gateway  Cannot start service gateway: failed to create endpoint reportportal_gateway_1 on network reportportal_default: HNS failed with error : The process cannot access the file because it is being used by another process.
ERROR: Encountered errors while bringing up the project.

**Comment by DzmitryHumianiuk** [comment]
We never recommend to install it on windows.

but try to comment related lines in `docker-compose.yml`,
as follows here in lines `122-128`
https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L122

**Comment by DzmitryHumianiuk** [comment]
code commit
https://github.com/reportportal/reportportal/commit/7941db82267fc98bcd72b66fa11e57c77089a1f5

**Comment by KCS289** [comment]
Does it mean that Reportportal work with docker must use Linux and not Windows ?

**Comment by DzmitryHumianiuk** [comment]
@KCS289 
https://reportportal.io/docs/Deploy-with-Docker%3Edeploy-reportportal-with-docker-on-windows

Also:
https://reportportal.io/docs/Production-Deployment-And (system requirements)
https://reportportal.io/docs/Deploy-with-Kubernetes
https://reportportal.io/docs/Deploy-ReportPortal-without
https://reportportal.io/docs/Deploy-ReportPortal-on (on Ubuntu OS)
https://reportportal.io/docs/ReportPortal-5.0-File (storage configuration)

all this available under: https://reportportal.io/docs/Installation-steps
