### ISSUE TITLE
Compare test results

### ISSUE THREAD

**Issue by roniezr** [reportportal/reportportal#472]
It would be nice if a user can choose two different history results and compare them
Meaning the user will choose at least two history results, click Compare and a new window will open
showing the two results side by side.
The difference should be highlighted.

**Comment by DzmitryHumianiuk** [comment]
@roniezr if you have good example of what should be shown, plz share it with us

**Comment by Witos** [comment]
+1

**Comment by Witos** [comment]
It's duplicate of #290 I think.
