### ISSUE TITLE
'An error occurred while connecting to server' when trying to login

### ISSUE THREAD

**Issue by CosminGramada** [reportportal/reportportal#475]
Hello.

OS: Windows 10 x64 with latest updates installed: Version 1803 (OS Build 17134.228)
Docker: version 18.06.1-ce, build e68fc7a

I followed the exact same steps from here (no changes were made in the docker-compose.yml file) and when I'm trying to login I'm getting the following error:
`'An error occurred while connecting to server'`

I noticed afterwards there's a newer version for the service-ui so I changed it to 4.3.2, but I'm still getting the same issue.

![rp](https://user-images.githubusercontent.com/15174660/45308518-52f76900-b52a-11e8-96fa-59dfb7552536.png)

![powershellrp](https://user-images.githubusercontent.com/15174660/45308817-06f8f400-b52b-11e8-9107-d87d726ad2ab.png)

Running `docker-compose logs` I notice there's an issue with the connection to mongodb, however I couldn't figure it out what the issue is.

[logs.log](https://github.com/reportportal/reportportal/files/2369527/logs.log)

**Comment by CosminGramada** [comment]
@evjlobanova 
Ok, I'll give it a try.
However, please note that the documentation on the [Install docker](http://reportportal.io/docs/Install-docker) page specifies that the docker should have at least 3GB of RAM and I allocated 4GB for it.

I bumped up the RAM for Docker to 6GB and I'll update with the latest findings.

Thanks for the prompt reply.

**Comment by evjlobanova** [comment]
@CosminGramada thank you for your notes. Please let me know about your result

**Comment by evjlobanova** [comment]
@CosminGramada could you share with your progress?

**Comment by pessimism** [comment]
I was able to resolve this issue.  If you modify the docker-compose file to use named volumes instead of relative path volumes for mongo, consul and elasticsearch, the demo runs on windows.  There is a related bug filed against the mongodb container which contains the workaround I applied:
https://github.com/docker-library/mongo/issues/74

**Comment by pratyush23** [comment]
Thanks @pessimism . Was facing similar issue on MacOS 12 as well and was able to resolve it by not using relative paths
<img width="298" alt="screenshot 2019-02-21 at 11 16 21" src="https://user-images.githubusercontent.com/29707049/53165271-2ca22300-35ca-11e9-8760-46a638712d7c.png">

**Comment by pavithrak2006** [comment]
Hello
I am also getting the same problem of 
![image](https://user-images.githubusercontent.com/5491004/70401414-7c3cc880-19fd-11ea-9bf9-c65aa7f77023.png)

I did the unnamed volume as explained as shown below in "Compose yml".
1. under specific sections,
    volumes:
       - **mongo:'/data/db'**
     volumes:
       - **consul:'/consul/data'**
      volumes:
      - **elasticsearch:'/usr/share/elasticsearch/data'**

Please advice if i am providing the correct format of unnamed volume

2. I run "docker-compose -p reportportal up -d --force-recreate" in command prompt and get errors specific mongo, consul and elasticsearch.
![image](https://user-images.githubusercontent.com/5491004/70401509-e8b7c780-19fd-11ea-8326-520772caf7b5.png)

3. Then I try to login but receive same "cannot connect to server"

4. I then delete the volumes added under specific sections in step-1 and try to run cmd prompt again "docker-compose -p reportportal up -d --force-recreate" and nothing happens.
   
Please advice me on this...

**Comment by evjlobanova** [comment]
New version 5.0 is available, 
Installation steps are described by the link https://reportportal.io/docs/Installation-steps

**Comment by swtestacademy** [comment]
Having the same issues on the M1 machine.
