### ISSUE TITLE
[import] During import of JUNIT.xml "skipped "status is not automatically assigned.

### ISSUE THREAD

**Issue by bolatbekb** [reportportal/reportportal#476]
These test results with "skipped" are assigned to "to investigate" status.

**Comment by DzmitryHumianiuk** [comment]
@bolatbekb this is default logic, which we have for skipped items.
What is expected behaviour?

**Comment by bolatbekb** [comment]
Are you considering this issue?

**Comment by DzmitryHumianiuk** [comment]
@bolatbekb you mean not to add defect type TI for skipped items?
Or skipped elements imported incorrectly itself?

 Configure option is law priority.

But it would be helpful, if you can send us here small xml example, which represents your issue

**Comment by Kozovskaya** [comment]
Hello there,
In version 23.2 we have improved the launch import. And now when importing via API the user can define where he needs the Skipped tests to be marked with 'To Investigate' defect type or not.
More information about the functionality you can find in our documentation:
https://reportportal.io/docs/log-data-in-reportportal/ImportDataToReportPortal#import-via-api
