### ISSUE TITLE
[import] The execution time of the tests is not calculated correctly during import.

### ISSUE THREAD

**Issue by bolatbekb** [reportportal/reportportal#477]
When you import a junit file, the execution time of each test is simply summed.

**Comment by DzmitryHumianiuk** [comment]
@bolatbekb what do you mean under `simply summed`?
What is expected behaviour?

**Comment by bolatbekb** [comment]
At the top level of the junit file (tag "testsuite") it specifies the duration of all tests. If one junit file is unloaded in the archive, I would like the portal to not summarize the duration of all testcases.

e.x.:
<testsuite name="" tests="9778" assertions="23792" errors="0" failures="0" skipped="87" time="216.050180">

**Comment by bolatbekb** [comment]
I closed the issue) accidentally . I will prepare the answer.
