### ISSUE TITLE
requesting integration with Gauge framework

### ISSUE THREAD

**Issue by TzurAnv** [reportportal/reportportal#479]
hi

i would like to request to add support for additional test framework named gauge
https://github.com/getgauge

hopefully this is the correct place for enhancement request

thanks

**Comment by DzmitryHumianiuk** [comment]
@TzurAnv it is right place to ask.

Do you know, which runner used under the hood of Gauge?
of they have own?

**Comment by nvborisenko** [comment]
Own runner. `golang` is behind of scene.

Example of reporters: https://gauge.org/plugins/#reports, also can be found on github.

**Comment by nvborisenko** [comment]
This framework has very good plugins system based on tcp communication between engine and extension points. Time allows me to try to implement a plugin for gauge on `.net`. Thumbs up if we need it. But anyway the implementation on `golang` is better, it is more native.

**Comment by TzurAnv** [comment]
i really prefer implementation for the Python use of gauge, also i can promise a very deep and extended use report in case of someone will write adaptation of the report-portal for it :)

**Comment by nvborisenko** [comment]
`gauge` is language independent. So all plugins work correctly with any language.

**Comment by nvborisenko** [comment]
@TzurAnv basic reporting is available for gauge, please welcome to https://github.com/reportportal/agent-net-gauge. This is first phase of implementation, please submit issues there.

**Comment by TzurAnv** [comment]
hi
we have a blocking bug with the gauge implementation documented at the issues section at the
https://github.com/reportportal/agent-net-gauge/issues
it will be greatly appreciated if someone could take a look on it

thanks :)

**Comment by DzmitryHumianiuk** [comment]
@TzurAnv how is the latest version for you?
(you can reply here in comment)


Will close this issue, since `agent-net-gauge` created.
Plz address all issue into related repo: https://github.com/reportportal/agent-net-gauge
