### ISSUE TITLE
Unable to connect BTS with JIRA

### ISSUE THREAD

**Issue by vivektamrakar91221** [reportportal/reportportal#484]
When trying to connect BTS with JIRA, getting below error.
Impossible interact with external system. <Project Name>

Tried all the options mentioned in the below link but could not get it connected.
https://github.com/reportportal/documentation/blob/master/src/md/src/TipsAndTricks/HowToResolveIssuesWithJira.md

I am suspecting this could be because we have Duo authentication associated with our JIRA login.
But the strange part is I was able to log bug using your RP almost 2 months back (that time also, DUO authentication was enabled with our JIRA)
Please find attached 

Please find attached logs for reference.
[reportportalapi.log](https://github.com/reportportal/reportportal/files/2404169/reportportalapi.log)
[Jira.log](https://github.com/reportportal/reportportal/files/2404170/Jira.log)

**Comment by antlong** [comment]
Any hope for this one?

**Comment by videoguy** [comment]
I see same issue with reportportal that I setup couple of days back. During config, it fails with "Impossible interact with external system" error. Our JIRA uses NTLM authentication I believe.
Wondering how to work around this...

**Comment by evjlobanova** [comment]
Please, update your version to the latest one 5.0
