### ISSUE TITLE
[FR] Alternative Auto Analysis strategy aka Patterns

### ISSUE THREAD

**Issue by slavamarkovski** [reportportal/reportportal#486]
I'd like to suggest to add one more Auto Analysis strategy with manual mapping test(s) to error message(s). 

E.g. we have a failure with message "User with ID 123 not found", suppose it means that Users service is down so a lot of tests will fail with this error message.

In this case we can map all our tests to the bug which will be created for this error:
com.example.tests.user.* >> User with ID .* not found >> BUG-111. 

Benefits:
- Analysis database is created under user control
- No need to "teach" RP to analyze failed tests
- Ability to select alternative AA strategies which is applicable for certain project

**Comment by evjlobanova** [comment]
Strict association of bug vs test case by name our any other can be implemented within own strategy. 
But for you should implement own custom analyzer(https://github.com/pbortnik/example-custom-analyzer). 

We will consider to extend AA config, and add such type of rules and regExps, which can associate known items first, and the rest will go to AA

**Comment by gpucciani** [comment]
+1, we have a similar situation with recurring issues. We'd like to create a database of these errors so that failed tests can be automatically mapped.

**Comment by nebehr** [comment]
@evjlobanova custom analyzer seems to support setting issue type, but can it attach an external issue? Looking at the analyzer request/response model it does not seem possible. See https://github.com/reportportal/service-analyzer/issues/20.

**Comment by DzmitryHumianiuk** [comment]
@slavamarkovski @gpucciani @nebehr 
We plan to add Patters page.
Where you can add specific log pattern, with exact match or regexp.
And define action for it (add Defect Type, assign to person, send notification, edit description, etc.)

This analyzer will work before ML based.

**Comment by slavamarkovski** [comment]
@DzmitryHumianiuk , thank you for the update.

Will it be possible to perform multiple actions on logs match, e.g. set Defect Type and link issue to the test?

**Comment by DzmitryHumianiuk** [comment]
@slavamarkovski good proposal.
will consider several actions per pattern

**Comment by slavamarkovski** [comment]
One more thing - is it possible to add mapping test name + log because the same (similar) error message for different tests can be assigned to different bugs.

**Comment by DzmitryHumianiuk** [comment]
@slavamarkovski hm.... super intellectual pattens )
will consider it

**Comment by rplevka** [comment]
+1
I'd like to see it implement in a way that user would be able to define rules (similar to the email filtering rules), allowing him to combine various fields using boolean logic

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/reportportal/issues/673

**Comment by DzmitryHumianiuk** [comment]
Try patterns.
Open new request if enhancements required.
