### ISSUE TITLE
LDAP authorization has stopped working on Report Portal

### ISSUE THREAD

**Issue by Preyansh91** [reportportal/reportportal#489]
**Describe the bug**
LDAP authorization has stopped working on Report Portal

Our LDAP authorization was working fine till now but it has stopped working suddenly and is not allowing any user to login with the error:
An error occurred while connecting to server : You do not have enough permissions. Bad credentials 

Upon taking a pcap we were able to see that the LDAP authorization on our ldap server is working fine, yet we are not getting logged into the Report Portal. We need help as we are stuck because of this issue.

We have attached a pcap showing the success of LDAP authorization for reference

**Expected behavior**
LDAP based login should work upon authorization success

**Screenshots**
![microsoftteams-image0a09a8532a390ab862c6492cba720b4a03d348e6c4adb654ba8c160a46f5b071](https://user-images.githubusercontent.com/11167119/46030448-0c1d7d80-c0ab-11e8-8cd0-431ff48f24be.png)

**Versions:**
 - OS, Browser (windows 10 and Mac-OS both

 - Version of RP [find it under Login form, copy as is]

Current version: Analysis Service: 4.2.0; API Service: 4.2.1; Index Service: 4.2.0; Jira Service: 4.2.0; Rally Service: 4.2.0; Authorization Service: 4.2.0; Service UI: 4.2.2;

**Comment by svettsova** [comment]
issue is not reproducible in 5.1 version
