### ISSUE TITLE
Expand button on Launches page doesn't work

### ISSUE THREAD

**Issue by JustasM11** [reportportal/reportportal#49]
Cannot make use of this button, looks like it does nothing.
![expand_button](https://cloud.githubusercontent.com/assets/12593214/21315564/dac236ac-c60d-11e6-9c79-0bf894a9de2d.png)

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 this button expands shorted names in breadcrumbs.

![screen shot 2016-12-19 at 23 55 29](https://cloud.githubusercontent.com/assets/11332788/21328816/b80479ac-c646-11e6-9b43-e3cb3e47494e.png)
![screen shot 2016-12-19 at 23 55 39](https://cloud.githubusercontent.com/assets/11332788/21328817/b82c1854-c646-11e6-88c4-0ee2f5bc7ead.png)

**Comment by DzmitryHumianiuk** [comment]
@lexecon 
1. we should hide it when no steps in breadcrumbs
2. add browser tooltip for it, with basic description

**Comment by JustasM11** [comment]
Got it, thanks
