### ISSUE TITLE
/{projectName}/item requires filter.eq.launch param

### ISSUE THREAD

**Issue by ludeknovy** [reportportal/reportportal#494]
**Describe the bug**
`/{projectName}/item` requires `eq.launch` param but thats not marked in swagger as required.
When sending request without `eq.launch`  it returns `400 with: Incorrect Request. Required String parameter 'filter.eq.launch' is not present`

**Versions:**
4.3.0

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu i guess it's more specific of swagger, not to represent this parameter as required, right?

**Comment by e-olga** [comment]
hi @ludeknovy, 
Response is correct, launchId is a required parameter for GET item. API documentation will be updated by release of RP v 5.0 
Regards,
Olga
