### ISSUE TITLE
Choosing multiple tests using shift + mouse_click

### ISSUE THREAD

**Issue by MosheSheena** [reportportal/reportportal#495]
**Describe the solution you'd like**
...Hello,
I think it can be a great improvement if it would be possible to tick a bulk of items using shift + mouse_click 

**Is your feature request related to a problem? Please describe.**
...The problem that brought me this idea is when I come across bulks of test items that all stem from the same defect, and I find myself ticking a lot of items.

**Comment by DzmitryHumianiuk** [comment]
@MosheSheena 
use `Cmd+click` for mac
and `Ctrl+click` for win
