### ISSUE TITLE
If a Jira defect is linked to a failure, RP doesn't escape the defect summary text

### ISSUE THREAD

**Issue by naiad09** [reportportal/reportportal#496]
Hi, Report Portal,
I hope you are well.

We have linked a Jira to our Report Portal.
There is a defect in Jira that has summary: "On user preference page, the column shows "\<center\>""

I linked this defect to a failure in RP. When I hover this defect link, it shows the defect summary and status.
The defect summary contains an HTML tag, and RP doesn't escape it (see screenshot).

Actual: It shows only "On user preference page, the column shows "", the status is centered.
Expected: it should show the whole summary, status should be at left as usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/19240314/46724901-a8d34400-cc83-11e8-8041-5173c0efd3f2.png)

**Versions:**
 - OS Windows 10, Browser Chrome
 - RP 4.2.2

**Comment by DzmitryHumianiuk** [comment]
will take in next minor release

**Comment by svettsova** [comment]
issue is not reproducible in 5.0 
![image](https://user-images.githubusercontent.com/50825875/77736472-731c4980-7036-11ea-93ef-c9c255e42679.png)
