### ISSUE TITLE
Do not reload Edit Defects page on Cancel

### ISSUE THREAD

**Issue by ailjushkin** [reportportal/reportportal#502]
**Current version:** 
Analysis Service: 4.2.0; API Service: 4.2.1; Index Service: 4.2.0; Jira Service: 4.2.0; Authorization Service: 4.2.0; Service UI: 4.2.2;

**Problem:**
When you select your failed tests, choose Edit Defects, then push Cancel. As a result, the page reloads and your selection is cleared. 

**Expected behaviour:**
Pushing Cancel does not reload the page and selection of failed tests is not cleared.

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova consider for next minor release

**Comment by evjlobanova** [comment]
Fixed in version 5.0
