### ISSUE TITLE
Installation without Docker

### ISSUE THREAD

**Issue by ZeeshanFr** [reportportal/reportportal#505]
Installation steps without docker are not up to date, as service ui and service index not accepting ports and never able to run on same machine, please update docs

**Comment by DzmitryHumianiuk** [comment]
@encyclopod took that

**Comment by navinchandrac** [comment]
**Issue-1:**  **fabio.propereties** related configuration is not clear, Need to provide default configuration for local Windows machine configuration including port details (Also need to provide sample fabio.propereties file with default configuration for Windows local configuration)

**Issue-2:**  **Consul** related port information is not clear (example : -bind=127.0.0.0) and meaning of port (like : -client 0.0.0.0 and -bind=127.0.0.0)

**Issue-3:**  **Service API** related Host and Port information is not clear (example : DSPRING_CLOUD_CONSUL_HOST=<server IP or hostname> AND -Drp.uat.serviceUrl="http://<server IP or hostname>:8080/uat")

**Issue-4:**  **service-authorization-3.3.0.jar** is not running without its dependent library folder (Right now we need Lib folder with required dependent jars)

**Issue-5:**  **Service UI** related Host and Port information is not clear (Example : "RP_SERVER.PORT=8082"  AND "RP_CONSUL.ADDRESS=<server IP or hostname>:8500")

**Issue-6:**  **Service Index** related Host and Port information is not clear (Example :  "RP_SERVER.PORT=8081" AND "RP_CONSUL.ADDRESS=<server IP or hostname>:8500")

**Issue-7:**  Instillation steps sequence is not proper and overall port and host details is very much confusing from end user point of view, It would be good if you can describe high level diagram for components level interaction).

**Comment by DzmitryHumianiuk** [comment]
@encyclopod plz review those steps as well

**Comment by ZeeshanFr** [comment]
I manage to run latest version on windows without docker, so much wrong in step documentation above i can put modified steps for others to use somewhere, i also able to create hooks for custom java exposing function to link with any framework , need to do some minor logs details work, was little time consuming documentations

**Comment by DzmitryHumianiuk** [comment]
@ZeeshanFr it would be very helpful!

**Comment by DzmitryHumianiuk** [comment]
@ZeeshanFr also @encyclopod made some updates in here
https://github.com/reportportal/documentation/commit/d4cc98380941a7dc8245201915bd3d4f27834a79
you can also take a look into it, or use as a basement.
@encyclopod also stuck with `service-aut`, you can help him

**Comment by ZeeshanFr** [comment]
i made changed to required step documentation, need permission to push changes to branch install_without_docker

**Comment by DzmitryHumianiuk** [comment]
@encyclopod will help you out.
He've contacted you on slack

**Comment by khatray** [comment]
@ZeeshanFr  Please help with the documentation as am unable to install it on Windows server

**Comment by khatray** [comment]
am getting error of ava.lang.NoClassDefFoundError while running nssm install RP_service_uat "<JDK path>\java.exe" -Xmx512m -DRP_SESSION_LIVE=86400 -DSERVER_PORT=9999 -DSPRING_PROFILES=consul -jar "<full directory path>\service-authorization-3.3.0.jar"

**Comment by encyclopod** [comment]
@khatray Need download dependency archive https://dl.bintray.com/epam/reportportal/com/epam/reportportal/service-authorization/3.3.0/service-authorization-3.3.0.zip and unpack lib folder beside jar-app

**Comment by khatray** [comment]
Thanks a lot for your help

**Comment by khatray** [comment]
am getting Windows cannot start RP_service_api  service on local computer error after running nssm install RP_service_api "<JDK path>\java.exe" -DSPRING_CLOUD_CONSUL_HOST=<ip address> -DRP_ISSUE_ANALYZER_DEPTH=4 -Xmx1g -Drp.uat.serviceUrl="http://<server IP or hostname>:8080/uat" -jar "<full directory path>\service-api-4.3.0.jar"

**Comment by khatray** [comment]
same case with nssm install RP_service_uat "<JDK path>\java.exe" -Xmx512m -DRP_SESSION_LIVE=86400 -DSERVER_PORT=9999 -DSPRING_PROFILES=consul -jar "<full directory path>\service-authorization-4.2.0.jar"

**Comment by khatray** [comment]
http://<server IP or hostname>:8080/ redirects to http://10.5.3.78:8080/ui/404.html with error "This page isn’t working
10.5.3.78 redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS"

all service status are in green http://127.0.0.1:8500/ui/#/dc1/services


api 2 passing
consul 1 passing
index 2 passing
uat 2 passing
ui 4 passing

**Comment by khatray** [comment]
am getting below error 

service-ui_win_amd64.exe RP_SERVER_PORT=8082"
"RP_CONSUL.TAGS=urlprefix-/ui opts strip=/ui" "RP_CONSUL.ADDRESS=i.p:8500"
 "**RP_STATICSPATH=\ui.tar\ui\public**"
2018/11/04 23:50:47 Service Registered!
2018/11/04 23:50:47 Starting on port 8080
2018/11/04 23:50:47 listen tcp :8080: bind: Only one usage of each socket addres
s (protocol/network address/port) is normally permitted.

**Comment by khatray** [comment]
same error for serivice_index

C:\Users\mtaha\Desktop\New folder>service-index_win_amd64.exe "RP_SERVER_PORT=80
81" "RP_CONSUL.TAGS=urlprefix-/" "RP_CONSUL.ADDRESS=10.5.3.78:8500"
2018/11/05 00:04:36 Service Registered!
2018/11/05 00:04:36 Starting on port 8080
2018/11/05 00:04:36 listen tcp :8080: bind: Only one usage of each socket addres

**Comment by ZeeshanFr** [comment]
your UI and index service should run on different port not 8080, also try this for ui, i had "RP_STATICS_PATH=d:\ui\public" ,  at this time i have both variables. please look at the modification i made in the document for ui and index port settings.

**Comment by khatray** [comment]
> your UI and index service should run on different port not 8080, also try this for ui, i had "RP_STATICS_PATH=d:\ui\public" , at this time i have both variables. please look at the modification i made in the document for ui and index port settings.

Havent got the issue resolved so far.

have started debugging the issue  and have started consul and fabio from cmd 

see this messages in consul window after starting fabio.Is this normal.it goes away when i start index service at port 8080

   2018/11/05 22:40:13 [WARN] agent: Check "service:gateway-testmachine-8080-8080"
HTTP request failed: Get http://[10.1.1.56]:8080/health: net/http: request canc
led while waiting for connection (Client.Timeout exceeded while awaiting headers}

**Comment by khatray** [comment]
i can see the login page now but credentials given in documentation are not working 
default\1q2w3e and superadmin\erebus.

"An error occured while connecting to server"

Looks like its not connected to mongodb.Any ways to troubleshoot

**Comment by DzmitryHumianiuk** [comment]
@khatray no ui running. but api don't see database

**Comment by encyclopod** [comment]
@khatray This is my settings. You may try start with delay between start  service. Start Consul in CMD, If you see registration event in consul, you may start next service.

> --logpath c:\mongo\mongo.log --serviceName="RP_mongo" --dbpath c:\mongo --directoryperdb --install

fabio.properties

proxy.addr = registry:8080;rt=300s;wt=300s
registry.consul.addr = registry:8500
registry.consul.register.addr = registry:8080
registry.consul.register.name = gateway
ui.addr = :9998

api -DSPRING_CLOUD_CONSUL_HOST=127.0.0.1 -DRP_ISSUE_ANALYZER_DEPTH=4 -Xmx1g -Drp.uat.serviceUrl=http://127.0.0.1:8080/uat -jar C:\Users\Petr_Pichugin\Desktop\rpp\service-api-4.3.0.jar

uat -Xmx512m -DRP_SESSION_LIVE=86400 -DSERVER_PORT=9999 -DSPRING_PROFILES=consul -jar C:\Users\Petr_Pichugin\Desktop\rpp\service-authorization-4.2.0.jar

index RP_SERVER.PORT=8081 RP_CONSUL.TAGS=urlprefix-/ RP_CONSUL.ADDRESS=127.0.0.1:8500

ui RP_SERVER.PORT=8082 RP_CONSUL.TAGS=urlprefix-/ui opts strip=/ui RP_CONSUL.ADDRESS=registry:8500 RP_STATICSPATH=C:\Users\Petr_Pichugin\Desktop\rpp\public

**Comment by ZeeshanFr** [comment]
use  RP_SERVER_PORT not RP_SERVER.PORT for  ui and index and this what i have. 
Also clean fabio.properties files and only add what you need.

**Comment by khatray** [comment]
strangely enough even if i give port 8081 and 8082 for UI and Index services ,these services try to register at 8080 only

**Comment by khatray** [comment]
BTW which version of service authorization jar are you using

**Comment by encyclopod** [comment]
@khatray What about running services? Maybe one or more service is not started. String: "Current version is indicator of services".
![123](https://user-images.githubusercontent.com/34941277/48542106-58c54e00-e8cf-11e8-971f-5b8dcdba1a67.png)

**Comment by khatray** [comment]
am getting this mesage while i just started consul and fabio

![image](https://user-images.githubusercontent.com/42056501/48550705-845d2e00-e8f9-11e8-9687-bfa1d20bbc20.png)

**Comment by encyclopod** [comment]
@khatray , try to start the next service in order. Fabio run without errors after start index-service.

**Comment by ocherniavskyi** [comment]
Hi, can anybody help: no matter what i do i get:
![image](https://user-images.githubusercontent.com/45246546/52021199-cbbc8900-24fc-11e9-86b8-a191b3157561.png)

**Comment by Remambian** [comment]
> 
> 
> am getting Windows cannot start RP_service_api service on local computer error after running nssm install RP_service_api "\java.exe" -DSPRING_CLOUD_CONSUL_HOST= -DRP_ISSUE_ANALYZER_DEPTH=4 -Xmx1g -Drp.uat.serviceUrl="http://:8080/uat" -jar "\service-api-4.3.0.jar"
> same case with nssm install RP_service_uat "\java.exe" -Xmx512m -DRP_SESSION_LIVE=86400 -DSERVER_PORT=9999 -DSPRING_PROFILES=consul -jar "\service-authorization-4.2.0.jar"
> 
> Also what is the directory path "RP_STATICSPATH="
> 
> will it be "\ui.tar\ui\public"

@khatray Can you please let me know how you resolved this issue ??? I am also getting the same error as unable to start the service. 
![rp_service_uat](https://user-images.githubusercontent.com/38716250/52552093-08458a00-2e05-11e9-9631-a217b91c5030.JPG)

**Comment by phartheeb** [comment]
Hello All,

I tired installing reportportal in windows without docker and followed all your forum suggested steps however getting the below error and no error is shown in the services "http://127.0.0.1:8500/ui/dc1/services". Please help.

![image](https://user-images.githubusercontent.com/47787491/53027573-d185fa00-342a-11e9-830c-a3aa04fc8b2b.png)

**Comment by heilwood** [comment]
Hi,

cannot configure reportportal without docker on azure virtual machine.

All service up and running, when i run fabio manually i see this error:

Error initializing backend. Get http://:/v1/agent/self: dial tcp :80: connectex: No connection could be made because the target machine actively refused it.

Where can be problem?

Fabio config:

```proxy.addr = :8080
rt=300s
wt=300s
registry.consul.addr = :
registry.consul.register.addr = :8080
registry.consul.register.name = gateway
ui.addr = :9998```

**Comment by heilwood** [comment]
Also trying to install without docker, looks like all service is running, but in consul i see next error message and ui on port 8080 is not available:

```2019/03/22 15:40:46 [WARN] agent: Check "service:gateway-AISHORITTESCON-8080" HTTP request failed: Get http://[10.162.46.134]:8080/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by heilwood** [comment]
fabio config has been changed to:

```
proxy.addr = virtual_machine_ip:8080;rt=300s;wt=300s
virtual_machine_ip.consul.addr = virtual_machine_ip:8500
virtual_machine_ip.consul.register.addr = virtual_machine_ip:8080
virtual_machine_ip.consul.register.name = gateway
ui.addr = :9998
```

No error in fabio and consul, everything ok. But when i try to open url http://virtual_machine_ip:8080 next screen appears:

![image](https://user-images.githubusercontent.com/27227165/54912127-9fb7f580-4ef8-11e9-8ea9-3227232dc03c.png)


cannot get UI working :(

**Comment by heilwood** [comment]
@khatray maybe you can help me and post your settings? how you solved this issues?

**Comment by heilwood** [comment]
Services added using this commands:
```
mongod --logpath "C:\reportportal\MongoDB\mongo.log" --serviceName="RP_mongo" --dbpath "C:\reportportal\MongoDB\db" --directoryperdb --install
nssm install RP_consul "C:\reportportal\consul.exe" agent -server -bootstrap-expect=1 -ui -client 0.0.0.0 -raft-protocol=3 -data-dir=consul_data -bind=127.0.0.1
nssm install RP_service_gateway "C:\reportportal\fabio-1.5.11-go1.11.5-windows_amd64.exe" -cfg C:\reportportal\fabio.properties
nssm install RP_service_api "C:\Program Files\Java\jdk1.8.0_202\bin\java.exe" -DSPRING_CLOUD_CONSUL_HOST=127.0.0.1 -DRP_ISSUE_ANALYZER_DEPTH=4 -Xmx1g -Drp.uat.serviceUrl="http://127.0.0.1:8080/uat" -jar "C:\reportportal\service-api-4.3.5.jar"
nssm install RP_service_uat "C:\Program Files\Java\jdk1.8.0_202\bin\java.exe" -Xmx512m -DRP_SESSION_LIVE=86400 -DSERVER_PORT=9999 -DSPRING_PROFILES=consul -jar "C:\reportportal\service-authorization-4.2.0.jar"
nssm install RP_service_ui "C:\reportportal\service-ui_win_amd64.exe"
nssm set RP_service_ui AppEnvironmentExtra "RP_SERVER_PORT=8082" "RP_CONSUL.TAGS=urlprefix-/ui opts strip=/ui" "RP_CONSUL.ADDRESS=registry:8500" "RP_STATICSPATH=C:\reportportal\ui"
nssm install RP_service_index "C:\reportportal\service-index_win_amd64.exe"
nssm set RP_service_index AppEnvironmentExtra "RP_SERVER_PORT=8081" "RP_CONSUL.TAGS=urlprefix-/" "RP_CONSUL.ADDRESS=127.0.0.1:8500"
nssm set RP_service_index DependOnService RP_consul RP_service_gateway
nssm install RP_service_jira "C:\Program Files\Java\jdk1.8.0_202\bin\java.exe" -Xmx256m -DSERVER_PORT=8083 -jar "C:\reportportal\service-jira-4.3.0.jar"
```

Current fabio config:
```
proxy.addr = registry:8080;rt=300s;wt=300s
registry.consul.addr = registry:8500
registry.register.addr = registry:8080
registry.consul.register.name = gateway
ui.addr = :9998
```
Log from fabio:
```
2019/03/26 12:25:57 [INFO] Metrics disabled
2019/03/26 12:25:57 [INFO] Setting GOGC=800
2019/03/26 12:25:57 [INFO] Setting GOMAXPROCS=2
2019/03/26 12:25:57 [INFO] consul: Connecting to "registry:8500" in datacenter "dc1"
2019/03/26 12:25:57 [INFO] Admin server access mode "rw"
2019/03/26 12:25:57 [INFO] Admin server listening on ":9998"
2019/03/26 12:25:57 [INFO] Waiting for first routing table
2019/03/26 12:25:57 [INFO] consul: Watching KV path "/fabio/noroute.html"
2019/03/26 12:25:57 [INFO] consul: Using dynamic routes
2019/03/26 12:25:57 [INFO] consul: Using tag prefix "urlprefix-"
2019/03/26 12:25:57 [INFO] consul: Watching KV path "/fabio/config"
2019/03/26 12:25:57 [INFO] HTTP proxy listening on registry:8080
2019/03/26 12:25:57 [INFO] Access logging disabled
2019/03/26 12:25:57 [INFO] Using routing strategy "rnd"
2019/03/26 12:25:57 [INFO] Using route matching "prefix"
2019/03/26 12:25:57 [INFO] consul: Registered fabio as "gateway"
2019/03/26 12:25:57 [INFO] consul: Registered fabio with id "gateway-AISHORITTESCON-9998"
2019/03/26 12:25:57 [INFO] consul: Registered fabio with address "myIP"
2019/03/26 12:25:57 [INFO] consul: Registered fabio with tags ""
2019/03/26 12:25:57 [INFO] consul: Registered fabio with health check to "http://[myIP]:9998/health"
```
Log from consul:
```
 2019/03/26 12:27:06 [INFO] agent: Synced service "uat-6e6d7a688995b4dd7fa5900972d92378"
    2019/03/26 12:27:06 [INFO] agent: Synced service "api-b26a5945705b27bcc774b8d19af89b18"
    2019/03/26 12:27:06 [INFO] agent: Synced service "uat-3b2f990143e324f465845a6fa7803308"
    2019/03/26 12:27:06 [INFO] agent: Synced service "gateway-myHostName-9998"
    2019/03/26 12:27:06 [INFO] agent: Synced service "jira-57e842d3ce0b6f02bc9edc8860ad1b4a"
    2019/03/26 12:27:06 [INFO] agent: Synced service "ui-localhost-8082"
    2019/03/26 12:27:06 [INFO] agent: Synced service "jira-8924f9ff7c5be5f0784ac56a5629cec5"
    2019/03/26 12:27:06 [INFO] agent: Synced service "api-c1b0bfad397fdeb4fc2a4f52935083e7"
    2019/03/26 12:27:06 [INFO] agent: Synced service "index-localhost-8081"
```
Consul service:

![image](https://user-images.githubusercontent.com/27227165/54990156-b9be0a80-4fc2-11e9-803c-9a5482b82426.png)

When login to myIP:8080  next error appear: This site can’t be reached, refused to connect

@encyclopod  Maybe you can help me with this, where can be the problem.

**Comment by goltopesti** [comment]
@heilwood, I am facing exactly the same problem.

I tried to execute all of the services from the command line for debug and there _were_ some issues with the firewall so I suggest people to run first via cmd and then set it as a service.

My biggest issue is that I cannot set different port on  **index** and **UI** thus they won't start together.. Any ideas here? Would really appreciate some help

**Comment by heilwood** [comment]
i ordered azure vm with linux and installed on it, to much time has been spent for this installation :(

**Comment by goltopesti** [comment]
@heilwood sad to hear, similar issues for me too.

I hope there is a way for a solution because docker is not the best option in my environment

**Comment by DzmitryHumianiuk** [comment]
documentation was re-structured
and updated: 
https://reportportal.io/docs/Deploy-ReportPortal-without  (leads to -> https://github.com/reportportal/shell-installation )

**Comment by khatray** [comment]
While trying to install on Centos 7 ,am getting error while executing this line in shell script

RP_DB_HOST=localhost java $SERVICE_UAT_JAVA_OPTS -jar service-uat.jar 

Error is no main manifest in Service-uat.jar

**Comment by AlehB** [comment]
Hi @khatray ,

Please try the lastest version
We have tested it recently, both services started successfully

Best Regards,
Aleh

**Comment by TestMyCode12345** [comment]
https://github.com/reportportal/example-java-TestNG/issues/23#issuecomment-627732973

> documentation was re-structured
> and updated:
> https://reportportal.io/docs/Deploy-ReportPortal-without  (leads to -> https://github.com/reportportal/shell-installation )

I followed the same steps in AWS centos. I am able to launch report portal. But Laucnh is not finishing in UI. test case is completed by Force to finish .

If I click the test case in ui, I am getting error in query.

Kindly help on this.


https://github.com/reportportal/example-java-TestNG/issues/23#issuecomment-627732973
