### ISSUE TITLE
[FR] Launches and environment matrix 

### ISSUE THREAD

**Issue by rsvoboda** [reportportal/reportportal#509]
Hi. 
I have concern how to track launches of **matrix jobs**. 
One testsuite can be run in multiple combinations of JVM / operating systems / databases. 
Another matrixes can be browsers / android sdk versions / ios sdk versions / devices vendors.
Jenkins supports matrix jobs for long time, it was in core of Jenkins 1 (till 1.561) and now it's plugin [Matrix Project Plugin](https://wiki.jenkins.io/display/JENKINS/Matrix+Project+Plugin)

Pipelines support Matrix-like flow too - https://support.cloudbees.com/hc/en-us/articles/115000088431-Create-a-Matrix-like-flow-with-Pipeline

So I'm wondering how are matrix jobs addressed in ReportPortal ?

One of matrix jobs I have in mind has 24 combinations so 24 runs of the same TS in various conditions. Similar jobs are there also for other platforms we work with.

In https://www.youtube.com/watch?time_continue=279&v=uclswtBgmaw video I noticed tags, but that's additional information that must be provided. And analysis functionality of ReportPortal could also get confused, because some issues can be related to certain OS / JVM / etc.

**Comment by DzmitryHumianiuk** [comment]
@rsvoboda you found the right answer.
**TAGS** provide ability to address this type of combinations.

Tags available for launches. for suites and for test-case level as well.

At the level of launches, you simply can build widget or trends, based on combination of filter, which can use tags.
Like build the widget, which sums up all launches for specific build.
And close ti it build widget, which sums up executions for ios/android/etc.

At the level of test cases, all the same. Tag test case according to specifics.

Tags for launches can be populated by Jenkins. Since it definitely knows what is the env config for certain run. Just push it via command line.
For test cases tags should be populated from code. Annotations or params of test.

All this flexible, and final approach completely depends on what information in which representation you need.

**Comment by DzmitryHumianiuk** [comment]
@rsvoboda as for Matrix views for execution, there is no out-of-the-box solution at the moment.

But we already did few brainstorm session, how this can be addressed in RP.

Main challenge for us is **multi tenancy.** 
We have to address specific of various platforms (java, .net, ruby, js, etc.), testing engines (testng, junit, nunit, pytest, etc), project styles (BDD/non-BDD), Data-driven tests, and so on.

It's much easier to make solution for one certain project and specific, but completely another game for multiply types.

If you have any examples, or proposals, plz share

**Comment by rsvoboda** [comment]
I think labels are better approach. You have `key:value` pairs and there can be more values to a key which basically defines an axis. And of course with multiple keys you get multiple dimensions.
This approach is nice for visualization and allows multi tenancy which is in RP.

RP could have predefined some labels like:
 * programming-language: java, .net, ruby, js, etc.
 * testing-engine: testng, junit, nunit, pytest, jasmine etc.
 * testing-runtime: oracle-jdk-11, oracle-jdk-8, openjdk-8, python-2.7, python-3,  
 * testsuite-name ... I think this could be handy in case of multiple matrix jobs using the same TS
 * operating-system: linux, windows, macos, rhel, ubuntu, debian, centos, arch, suse, etc.
 * type-of-testing: unit, system, integration, backward-compatibility, scalability, load, soak, etc.

Some labels could be automatically filed by agents, user would just select if he/she wants it to have them tracked and visible. Benefit of predefined labels is that RP can provide specialized functionality (analyzing just launches for certain platform and same testsuite-name (aka group-by in sql) or certain testsuite-name, etc.) and charts.

If you want to look into `key:value` labels I suggest to check stuff available in Kubernetes
 * https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
 * https://livebook.manning.com/#!/book/kubernetes-in-action/chapter-3/132
Kubernetes selectors based on labels are pretty powerful.

**Comment by DzmitryHumianiuk** [comment]
@rsvoboda good approach.
btw, we consider this type of `key:value` pairs as a replacement for tags in versions 5.x+

At the moment, our analogue of labels is tag. Which have only `value`
and some of similar functionality was proposed via prefix in tags.

**Comment by MaryiaRymarchyk** [comment]
Hi @rsvoboda ,
the described above  feature is already in live. You can use attributes -  key:value pairs for visualization and categorization your launches. 
Please find more info at our documentation site - [How to add more attributes for filtering launches in ReportPortal ](https://reportportal.io/docs/reportportal-tutorial/#how-to-add-more-attributes-for-filtering-launches-in-reportportal)
I'll close the ticket. If you have remained questions - feel free to contact us.
