### ISSUE TITLE
As user I want to track performance results in RP

### ISSUE THREAD

**Issue by JustasM11** [reportportal/reportportal#51]
I want to save number for test result and specify measurement units (MB/s, IOPS/s, etc.)
I want to be able to get X-Y chart with saved data for particular test.
Optional: I want to setup baseline/threshold so test fails if performance is lower than required.

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 
Performance part is not described yet, so this description will be considered during requirements preparation.

For now, 
1. performance features are not guaranteed to be implemented
2. if **yes**, then first features will be delivered closer to 2017-Q2

**Comment by DzmitryHumianiuk** [comment]
move t backlog.

Performance part is not in priority.
will be considered for as a part of `Sub-launch widgets`

**Comment by drcrazy** [comment]
There is an issue aimed on consolidation of all perf test reporting questions: https://github.com/reportportal/reportportal/issues/1820
