### ISSUE TITLE
"Edit" and "Delete" buttons in widget head get ignored in a narrow browser window.

### ISSUE THREAD

**Issue by sisihi** [reportportal/reportportal#510]
**Describe the bug**
...
When hovering the widget head, “Edit” and "Delete" buttons cant been displayed correctly in a narrow browser window.

**Expected behavior**
...
 When hovering the widget head, "Edit" and "Delete" buttons should appear despite of the width of browser window.

**Screenshots**
If applicable
 "Edit" and "Delete" buttons got ignored in a narrow display mode:
![screen shot 2018-10-29 at 4 52 33 pm](https://user-images.githubusercontent.com/16377386/47639145-8904b100-db9b-11e8-9229-9b2075c7bf33.png)

  "Edit" and "Delete" buttons work as normal in a full screen mode:
![screen shot 2018-10-29 at 4 55 05 pm 2](https://user-images.githubusercontent.com/16377386/47639350-016b7200-db9c-11e8-8099-7737e8211f98.png)

**Versions:**
OS: macOS Version 10.13.4

Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)

RP version: 
Analysis Service: 4.3.0; 
API Service: 4.3.0; 
Index Service: 4.2.0; 
Jira Service: 4.3.0; 
Rally Service: 4.3.0;
Authorization Service: 4.2.0; 
Service UI: 4.3.0;
 - Version of RP [find it under Login form, copy as is]

**Comment by evjlobanova** [comment]
@sisihi in a mobile view not all  functions are available. Edit, Delete and Full screen are hidden on mobile UI.

**Comment by sisihi** [comment]
@evjlobanova Thanks for your immediate reply. 
Yes, I can understand there will be some limitations when visiting the PR server via a mobile. 
But, I encounter this unhandy in the desktop environment. 
I suppose maybe we can have a feature to tell the mobile env and PC env and become more user friendly in the coming future?

**Comment by evjlobanova** [comment]
@sisihi you have posted this issue as a bug, so i clarified, that it is a not a bug, it is a feature)  
In a narrow screen it is difficult to reflect some modals, that is why we limited some functions.
Anyway we will discuss this enhancement and mobile policy in general.
But could you please, describe your case, why you use narrow display mode? Do you usually use display in this mode. How often do you plan to use RP on mobile devices?

**Comment by sisihi** [comment]
@evjlobanova 
Apologies for the misusing of bug report. Maybe I missed something in the [Documentation](http://reportportal.io/docs/Manage-Widgets%3Eedit-widget), I did not find any statement related to the mobile limitation things given in your replay. That why I consider it as a bug.

As for the narrow display mode:
![screen shot 2018-10-30 at 10 18 34 am 2](https://user-images.githubusercontent.com/16377386/47691487-37a50200-dc2d-11e8-8bc0-b5eca65b2954.png)

In my case, the unhandy happens while I am studying the PR tutorial with the such screen on my mac.
First, I cant find any button in the widget head with hovering.Then I try to change the width of browser, then thing goes like the document:
![screen shot 2018-10-30 at 10 26 44 am 2](https://user-images.githubusercontent.com/16377386/47691772-56f05f00-dc2e-11e8-9fc3-906db96871bb.png)
I suppose it's a little bit unhandy to have this on a pc/mac env. and the document did not mention about this feature.
And I admit it's a minor issue. Disabling the UI config in mobile is reasonable.
But it looks like this disabling will affect desktop as well. then it's better if RP can make this feature dedicated for mobile. Thanks.

**Comment by evjlobanova** [comment]
@sisihi ReportPortal application has responsive UI and all components are adjusted in accordance with the screen resolution.
Mobile view -  320 -720рх
Tablet view - 720px
Desktop view 960+px

**Comment by sisihi** [comment]
@evjlobanova Thanks for you kind explanation, Now I have a better understanding of RP.
