### ISSUE TITLE
[FR] Add ability to protect a test result from auto-deletion

### ISSUE THREAD

**Issue by rsvoboda** [reportportal/reportportal#511]
Hi. I would like to know what are the pruning strategies for old lunches or testsuite in RP.

In Jenkins there is option to discard old builds [1] or to keep some runs forever [2].
Is there something similar in RP?

My motivation is that with daily runs of some testsuite I can generate too much data for RP which can lead to slowness of the system and worse usability of some reports.

http://reportportal.io/docs/History-of-launches mentions that users can chose "History Depth" in reports. But I didn't find anything about pruning old data.

[1] https://wiki.jenkins.io/display/JENKINS/Discard+Old+Build+plugin
[2] https://themettlemonkey.files.wordpress.com/2013/01/screen-shot-2013-01-31-at-13-12-481.png

**Comment by DzmitryHumianiuk** [comment]
@rsvoboda project settings -> keep logs, keep screenshots.
It limits time to store logs in test cases.
And limits time to store binary attachement.

As for launches itself, and all underlying test suites for versions 4.x we decided to keep them.
Those object pretty small, and just contains statistics.

In 5.0+ will be introduced job to delete old launches, according to specific rules.

**Comment by VikasKrishnamraju** [comment]
Hi @DzmitryHumianiuk, i have a similar question. Below are settings, where i want the logs and screenshots to be available for 2 weeks. I have made this setting yesterday. Wanted to know when this setting takes into effect. Is it the moment we set these or is there any scheduled time for this.
As i was able to see the logs for tests in launches which were executed 4 months ago

![image](https://user-images.githubusercontent.com/24792711/47711909-6ab2ba00-dc5c-11e8-9a02-0722ff92535e.png)

**Comment by DzmitryHumianiuk** [comment]
@VikasKrishnamraju 
>I have made this setting yesterday. Wanted to know when this setting takes into effect. 

it handled automatically by scheduled Spring Jobs with Quartz.
Default config for this trigger is `24h`.
Just give it a time, it will trigger cleaning on time, when server will be under low load.

For versions 4.3.2+ you can find details in Info request in milliseconds:

![image](https://user-images.githubusercontent.com/11332788/47728043-9b9bea80-dc6e-11e8-9833-f01dc510e3e0.png)


![image](https://user-images.githubusercontent.com/11332788/47727974-8030df80-dc6e-11e8-8766-22d9315d447e.png)


```curl
curl 'http://web.demo.reportportal.io/composite/info' -H 'SESSION=3332f246-054c-4fcb-a4c0-e7f4e60441eb'
```

**Comment by VikasKrishnamraju** [comment]
Thank you @DzmitryHumianiuk. Will wait until 24 hours and let you know if i face any issues
As of now I'm on RP 3.0.5, need to upgrade to the latest

**Comment by DzmitryHumianiuk** [comment]
Let's make it configurable from project settings page

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova @e-olga 
let's have it into next release, after `5.0asis`

**Comment by rsvoboda** [comment]
@evjlobanova can you link related PRs ?

**Comment by DzmitryHumianiuk** [comment]
@rsvoboda there were various improvements around data cleaning.
majority of them was completed during fixes for data cleaning for our prod instance.
Most of them were about more robust data cleaning.

@rsvoboda do i understand you correctly, that you are looking for capabilities to lock some launches/results for deletion?

if yes, we will introduce **Release Lock functionality.** #674

**Comment by DzmitryHumianiuk** [comment]
## resolution: reopen

has correlation with #674 
but should be implemented separately.

**idea:**
at project config page add tag, which will be used to identify launches, which should be ignored during deletion.

**Comment by rsvoboda** [comment]
Thanks for the details, release lock is what I had in my mind too

**Comment by DzmitryHumianiuk** [comment]
@rsvoboda then do you need any possibility to mark launches, that should not be deleted?
or the main goal for request is not possibility to lock specific status for specific release/build?

**Comment by rsvoboda** [comment]
I had in mind to mark launches, that should not be deleted

**Comment by Kozovskaya** [comment]
Hello @rsvoboda 
In our latest release we've introduced new feature - Lanches retention policy which will give you an opportunity to protect some launches from deletion.
Here you can find more information regarding the new feature: https://reportportal.io/docs/configuration/LaunchesRetentionPolicy 
Hope it will cover your needs!
And thank you for using ReportPortal!
