### ISSUE TITLE
Auto-Analysis of launches when the same (standalone) TS is used against different versions of project codebase

### ISSUE THREAD

**Issue by rsvoboda** [reportportal/reportportal#512]
Hi. I have another question, this time related to Auto-Analysis of launches. We have standalone testsuites (TS) which are used against different versions of project release or build from current codebase state.

So the same TS can have certain set A of failures for version x.y.z of the component.
It can have (and usually has) different set B of failures for version x.(y+1) of the component.
And for working / unreleased version there is usually set C.

I'm wondering if RP can be clever enough with Auto-Analysis of the launches for such cases and can differentiate between various streams - x.y  vs.  x.y+1  vs. latest_aka_x+1 ?

Those streams I mentioned could be addressed by labels / tags. Then I would just say: Hey Auto-Analysis, do your magic on launches for test-suite ABC with label x.y and pick just 10 latest launches.

**Comment by rsvoboda** [comment]
And to make the life more complicated, there can be also different set of failures on Windows vs. Linux, databas A vs. database B, browser X vs. browser Y etc :(

**Comment by evjlobanova** [comment]
@rsvoboda hello! now Auto-analysis can distinguish only launches with the same name and only results from one single launch. It means, that you can choose configuration Launches with the same name, and analyzer will try to find the familiar failure reasons test  which belong to launches which the same name. But analyzer checks only name, tags do not taken into account. Also now you can not define exactly which X latest runs should be participate in analysis.

But could you please explain what do you mean under "set A of failures for version x.y.z".  Are failure reasons for different versions has different logs or the similar?

**Comment by rsvoboda** [comment]
> Are failure reasons for different versions has different logs or the similar?

There can be different stack-traces aka different root causes. But tbh it doesn't happen often.
Sometimes it happens that test for issue A fails but it discovers new issue.
Example: test fails for x.y, test passes for x.y+1, test fails again for x+1, but not because the issue A, but new issue B is discovered. It happens usually when component upgrade brings a lot of changes in transitive dependencies.

**Comment by evjlobanova** [comment]
@rsvoboda Analyzer defines defect type (defect comment and link to BTS) based on similarity of error log. F.e your test 1 failed in version x.y. Analyzer send its error log in ElasticSearch and search for the most similar error logs which are storage in ElasticSearch. In case analyzer finds, the appropriate defect type A is set to test 1. 

The same situation with test 1 in version x.y+1. In case analyzer finds, the appropriate defect type is set to test 1 based on error log of this test. For example, defect type B.

This is very simplified scheme of analysis procedure. All details are described here [here](http://reportportal.io/docs/Auto-Analysis-of-launches) our documentation.

Could you please tell do you use analysis already and it works not as expected? Or haven`t use it yet?

**Comment by rsvoboda** [comment]
I think all the main points I needed to know are clear now. I saw http://reportportal.io/docs/Auto-Analysis-of-launches documentation, just wanted to summarize my main uncertainties.

> But analyzer checks only name, tags do not taken into account. Also now you can not define exactly which X latest runs should be participate in analysis.

Are there any plans to implement more fine-grained analysis of launches?
For example using tags or limiting the number of runs.

**Comment by evjlobanova** [comment]
@rsvoboda yes, we have plans, but they are not immediate plans.  
But for me it is important to understand your use case more deep. Could you please describe the desired behavior aa on example?

**Comment by rsvoboda** [comment]
There are few aspects, lets call x.y.z stream A, x.y+1 stream B and x+1 stream C (new stuff)

**a) issues tracking**
For each stream there can be separate bug report so it's properly tracked per stream.
General rule in our case is to first fix stream C -> B -> A so the future releases do not contain the issue.
RP has notion of tracking systems so I would like to have proper issues ID assigned per stream.

**b) owners / reviewers of the failures**
It may happen that issues for stream A are handled and reviewed by different (e.g sustaining) team than issues for stream B and C. It may also happen that issues are tracked in different tracking systems or projects of the same tracker.

**c) performance**
Performing analysis on subset of launches should be faster than on full set of launches.

**Comment by DzmitryHumianiuk** [comment]
@rsvoboda AA do not consider tags at launches level, but does it for test cases.
TestCases with same unique id have boosted priority

https://github.com/reportportal/service-analyzer/blob/master/fixtures/search_rq.json

```json
            "should": [{
                "term": {
                    "unique_id": {
                        "value": "unique1",
                        "boost": 2
                    }
                }
            }, {
                "term": {
                    "is_auto_analyzed": {
                        "value": "false",
                        "boost": 2
                    }
                }
            }, {
                "term": {
                    "launch_name": {
                        "value": "Launch with test items with logs",
                        "boost": 2
                    }
                }
            }]
```
it says that items with equal launch name, with AA flag in false, and equal **uniqueID** will be boosted twice.

unique id = http://reportportal.io/docs/A-test-item%3Euniqueid
 is based on:

- A project name;
- A launch name;
- Names of all parents;
- All parameters of the item;

if test case for env1 will have different parameters then in env2, then AA will boost priority for items for equal env execution
