### ISSUE TITLE
Help/Question: How to update default Default "From" e-mail address in ReportPortal E-mail Notification feature

### ISSUE THREAD

**Issue by mcafeerun** [reportportal/reportportal#516]
How to update default Default "From" e-mail address in ReportPortal E-mail Notification feature

![image](https://user-images.githubusercontent.com/36393899/47737230-4d83e880-dc68-11e8-8546-0bdb68711152.png)

**Comment by DzmitryHumianiuk** [comment]
@mcafeerun 
1) login as admin
2) profile menu -> administrate
2) server settings -> email server

**Comment by mcafeerun** [comment]
Hi @DzmitryHumianiuk; I have already tried it. Its not working. 

![image](https://user-images.githubusercontent.com/36393899/47757207-3dd2c700-dc9d-11e8-8f85-09eabe80f9e6.png)

![image](https://user-images.githubusercontent.com/36393899/47757274-75417380-dc9d-11e8-8b53-d5579e5d2f3c.png)

**Comment by DzmitryHumianiuk** [comment]
Then it’s a bug.

@mcafeerun which version of UI?

@e-olga take a look plz

**Comment by e-olga** [comment]
Hi @mcafeerun 
As for today, it is only possible to update 'From' field in 'Email notification' component via API call.
Please send 
`PUT http://host:8080/api/v1/project/{project_name}/emailconfig`
RQ body should have next required parameters:
`{
  "emailCases": [
    {
      "recipients": [
        "<email_address_of_recipient>"
      ],
      "sendCase": "ALWAYS"
    }
  ],
  "emailEnabled": true,
  "fromAddress": "<email_address_from_Email_server_settings>"
}`

In RP v5 the field will be removed from UI. 
Sender address will be inherited from Email server settings configuration (Administrative part).

Regards,
Olga

**Comment by mcafeerun** [comment]
@e-olga , Thank you!

One question outside of this issue. What is the auth we should send in POST request? I used basic auth with report-portal UI login credentials, it did not work. Appreciate your help!

**Comment by e-olga** [comment]
Hi @mcafeerun 
You should send a token. There are some kind of token are available in RP with different scope: "ui" and "api".
"UI" token has time limitation, it means that it is expired after some period (by default, in docker-compose.yml file 86400 sec is defined). 
You can find the "access_token" ("ui") in response on `POST http://host:8080/uat/sso/oauth/token?grant_type=password&password=1q2w3e&username=default`
"Api" token "leaves" until you re-generate it and available on Profile page ("UUID" field).
In common, for running your automated tests it is better to use token 'api' and not 'ui'.
Note, you should send the token  with "bearer" prefix: 
![image](https://user-images.githubusercontent.com/22497746/47857754-856f6500-ddfb-11e8-88ab-d13ce5784c59.png)

Feel free to contact me, if any questions)

Regards,
Olga

**Comment by mcafeerun** [comment]
Got it.. Thank you, Olga..

**Comment by dmitryyu** [comment]
just remove "disable" attribute for the field in the DOM of the page - and update it directly in your browser. :)

**Comment by DzmitryHumianiuk** [comment]
@dmitryyu 
![image](https://user-images.githubusercontent.com/11332788/54315022-37127400-45ee-11e9-935f-2b9426da06fb.png)
