### ISSUE TITLE
Include 'Project Name' in Launch Completion EMail 

### ISSUE THREAD

**Issue by bvpadmanaban** [reportportal/reportportal#519]
Hi,

I integrated report portal in our 10 projects automation. when i am getting launch completion email, i couldn't able to figure out the project name. 

FYI, we are following same standard of Launch Name in projects and in description I added workaround of CI Integration tool (TC and Jenkins) build numbers , so that I couldn't add the project names in the Launch Name and Description.

It would be great, if we expose project name in the Launch completion Email Template.

Thanks.

**Comment by e-olga** [comment]
@bvpadmanaban 
Could you please define where you would like to see the project name: in the Subject or in Body of the email?
Regards,
Olga

**Comment by bvpadmanaban** [comment]
Hi @e-olga ,

I would to see the project name in Subject.

Thanks,
Padmanaban

**Comment by DzmitryHumianiuk** [comment]
@e-olga @evjlobanova let's take is as improvement for 5.0

**Comment by e-olga** [comment]
The improvement is implemented and will be available in RP version 5.0
