### ISSUE TITLE
I need filter to find out all triaged (investigated) test results

### ISSUE THREAD

**Issue by JustasM11** [reportportal/reportportal#52]
Filter should include the same fields as for launches: time, tags, etc.

**Comment by DzmitryHumianiuk** [comment]
Could you please give more details?

`Triaged` means test case, which changes state as passed->failed->passed->failed->passed->failed?

**Comment by JustasM11** [comment]
Triaged means failed results but with already changed 'Defect Type' from 'To investigate' to any another (System Error, Product Bug, etc.).
So as user I want to get single list from particular launches of:
- Failed tests that still in 'To investigate' state
- Failed triaged tests that were already investigated

**Comment by JustasM11** [comment]
I need it also to get results that were triaged by auto analysis feature

**Comment by DzmitryHumianiuk** [comment]
> I need it also to get results that were triaged by auto analysis feature

here we considering to add `AA.touch` flag for analyzed test cases

> Failed tests that still in To investigate state

1.  click `failed` column
2. add filter. Click `More` => `Defect type` => `To Investigate`

![image](https://cloud.githubusercontent.com/assets/11332788/21458231/d4cb0ce8-c945-11e6-8d5f-7e0f9f90c7b7.png)
![image](https://cloud.githubusercontent.com/assets/11332788/21458241/eca527b8-c945-11e6-87e1-175b37e9021c.png)

> Failed triaged tests that were already investigated

the same as above, but for filter - select all defects, and unselect `To Investigate`
