### ISSUE TITLE
API to Import Junit Results

### ISSUE THREAD

**Issue by sberczuk** [reportportal/reportportal#520]
While I'm aware of the import function via the UI, I'm trying to figure out how to do this programmatically, either via an existing API or something I write (and to do that latter, I feel like I'm missing a sense of how the report elements fit together) . Our specific use case is:
1. Use the Newman command line runner to Postman API Tests, generating a JUnit XML report
2. Push the results toReportPortal

I could not find an obvious way to do this, so perhaps something is missing. Or maybe it's just a matter of documentation.

**Comment by trannguyenhung011086** [comment]
+1 this.
My use case is:
1. run E2E test suites with Selenium + Jest -> export to JUnit xml report via jest-junit
2. import to ReportPortal

**Comment by rplevka** [comment]
```bash
$ ls foo.xml 
foo.xml
$ zip foo.zip foo.xml
  adding: foo.xml (deflated 47%)
$ curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: application/json' --header 'Authorization: bearer aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee' -F file=@foo.zip 'http://192.168.1.224:8080/api/v1/foo/launch/import'
{"msg":"Launch with id = 5be4de6842eba40001b30534 is successfully imported."}
```

**Comment by DzmitryHumianiuk** [comment]
@sberczuk @tamasmartin 
does this help?
http://reportportal.io/docs/Logging-Integration

**Comment by DzmitryHumianiuk** [comment]
@sberczuk issue can be closed?

**Comment by bzsharm** [comment]
@trannguyenhung011086 DzmitryHumianiuk

is that a working solution ?

**Comment by sebastienmascha** [comment]
@bzsharm this is indeed a working solution: 
`curl -X POST "http://localhost:8080/api/v1/superadmin_personal/launch/import" -H "accept: */*" -H "Content-Type: multipart/form-data" -H "Authorization: bearer YOUR_JWT_TOKEN" -F "file=@result.xml;type=text/xml"`

Nevertheless, I the response is not really helpfull. It is a message that includes the launch ID. WOuld be better to add a field launch_id with the ID to not parse on client side.

**Comment by evjlobanova** [comment]
@Yumfriez Ivan could you please create a task to Jira to version 5.4 for changing response

**Comment by gsaslis** [comment]
@evjlobanova hello 👋 

Just wondering if this ☝️ issue about changing the response payload was opened after all? 
I cannot find a reportportal Jira instance to check for myself, and I can't seem to be able to find an issue here in Github (even though it seems that shouldn't be the place I should be looking at, right?) 

Thanks in advance!

**Comment by gsaslis** [comment]
P.S. Happy to open that issue myself, if it hasn't been opened yet.

**Comment by sebastienmascha** [comment]
I personally ended up using regex to get the launch id: 
`
import re  # Regex for launch ID
url = API_URL + "/api/v1/" + RP_PROJECT + "/launch/import"
files = {'file': (open(xml_path, 'rb'))}
r = requests.post(url, headers=API_HEADERS, files=files)
res = re.search(r'\b[A-Za-z0-9-]{10,65}\b', r.text)
`

**Comment by evjlobanova** [comment]
> @evjlobanova hello 👋
> 
> Just wondering if this ☝️ issue about changing the response payload was opened after all?
> I cannot find a reportportal Jira instance to check for myself, and I can't seem to be able to find an issue here in Github (even though it seems that shouldn't be the place I should be looking at, right?)
> 
> Thanks in advance!

Hello @gsaslis 
We created a task to our Jira backlog.
This GitHub ticket is related to your problem.
So that as soon as we add more info to the response, we will close this issue. No need to create one more ticket

**Comment by svettsova** [comment]
Ticket is adeed to Jira

**Comment by gsaslis** [comment]
@svettsova @evjlobanova thank you both! 👍

**Comment by gsaslis** [comment]
@sebastienmascha I used `grep` to achieve the same result, but I changed the lower length bound to `20`, because, with `10`, "successfully" was also returned as a match.

Here it is in full - if others are interested: 

```
      /usr/bin/curl \
        -X POST \
        --silent \
        --header "Content-Type: multipart/form-data" \
        --header "Authorization: bearer ${REPORT_PORTAL_TOKEN}" \
        --header "accept: */*"
        -F file=@$(inputs.params.report-zip-filename) \
        ${REPORT_PORTAL_URL} | grep -oE '\b[A-Za-z0-9-]{20,65}\b' 
```

**Comment by rplevka** [comment]
> I personally ended up using regex to get the launch id:
> 
> ```
> import re  # Regex for launch ID
> url = API_URL + "/api/v1/" + RP_PROJECT + "/launch/import"
> files = {'file': (open(xml_path, 'rb'))}
> r = requests.post(url, headers=API_HEADERS, files=files)
> res = re.search(r'\b[A-Za-z0-9-]{10,65}\b', r.text)
> ```

that might backfire if locale (language) is changed.
This might be less prone to such issues:
```
In [24]: response = "Launch with id = 5be4de6842eba40001b30534 is successfully imported."                                                                                                      

In [25]: re.search("id = ([\w\d^$]+)" ,a)[1]                                                                                                                                                   
Out[25]: '5be4de6842eba40001b30534'
```

**Comment by DzmitryHumianiuk** [comment]
this might be helpfull: https://reportportal.io/docs/log-data-in-reportportal/ImportDataToReportPortal/#import-via-api

that the detailed issue is duplicate for #1483
