### ISSUE TITLE
URL as hyperlink in logitem

### ISSUE THREAD

**Issue by winstondz** [reportportal/reportportal#521]
Hi,

Is there a way to provide a hyperlink when entering url as a logitem instead of plain text. I store video logs on a different server and post the url as a log item. I have to manually copy and paste the url back to the browser to navigate to it. If there was a hyperlink available in the logitem, it would be just one-click solution from report portal. I tried adding the html tags, but was unable to change it to a clickable hyperlink

**Comment by evjlobanova** [comment]
@winstondz you can report logs with support of Markdown. For that please follow the steps http://reportportal.io/docs/How-to-activate

**Comment by DzmitryHumianiuk** [comment]
considered as resolved
