### ISSUE TITLE
Defect comment is not updated during editing

### ISSUE THREAD

**Issue by dmitryyu** [reportportal/reportportal#522]
**Steps:**
1. Open Details for a failed test. 
2. press "pen" to change defect type (for example, from "to investigate" to "system issue")
3. add new comment, for example: "123" and save the change
4. Open the "pen" again to edit comment.
5. type: "234" instead of "123" and press Save

**Actual behavior:** 
The page is not refreshed and the comment stays the same.
If you reload the page - it will be successfully updated.

**Expected behavior**
The Comment should be automatically updated without extra page refreshing.

**Versions:**
- Browser: Win10, FF
- RP:  API Service: 4.3.0; Index Service: 4.2.0; Jira Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.0;

**Comment by eliekoren** [comment]
Reproduced also when editing Defect Types (e.g. To Investigate -> Automation Bug)

**Comment by f4br3** [comment]
Still have this bug.

**Versions:**
- RP:  Service-authorization: 4.2.0, Service-index: 4.2.0, Service-api: 4.3.4, Service-ui: 4.3.6, Service-analyzer: 4.3.0.

**Comment by DzmitryHumianiuk** [comment]
Will be fixed in 5.0 version

**Comment by DzmitryHumianiuk** [comment]
verified in 5.0 beta

**Comment by evjlobanova** [comment]
Will be available in the beta release of version 5
