### ISSUE TITLE
Cant login for the first time - "connection refused" 

### ISSUE THREAD

**Issue by DariaTl** [reportportal/reportportal#523]
Hi , 
I downloaded the docker image as in your documentation, all services are up and running ,I can see it after docker-compose up , all is in "done" state .
I do have more then 5 gb on my docker settings .
but for some reason when I'm trying to login I'm getting connection error , in my docker logs i can see this error   : 
ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.19.0.8:9200: connect: connection refused
and this error on mongodb container : INFO 1 --- [}-mongodb:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server mongodb:27017

I do see only one service on my login page , I waited for more than 30 min but still no updates on the login page , how much long should I wait ? 

![git](https://user-images.githubusercontent.com/36892772/47966670-b7800180-e05d-11e8-99c6-40beef1452ad.PNG)

**Comment by DariaTl** [comment]
It was a mongodb error , i think it will be nice if you will mention in your documentation that there is mongodb changes that need to be done if we are running our containers on windows . i think it will reduce open issues about login .

**Comment by DzmitryHumianiuk** [comment]
@DariaTl could you plz point which documentation you have used for it?

cc @encyclopod

**Comment by DariaTl** [comment]
http://reportportal.io/docs

**Comment by ds12will** [comment]
@DariaTl  what was the fix for mongodb changes
