### ISSUE TITLE
How to get history by item?

### ISSUE THREAD

**Issue by MonkAlex** [reportportal/reportportal#524]
**Describe the bug**
In older version i can get item history by `uniqueId` (for example - `item?filter.eq.uniqueId=auto%3A6a791c938a1d08a4313a7fd48b5b377c`)
Now this query get error 

> {
>   "error_code": 4001,
>   "message": "Incorrect Request. Required String parameter 'filter.eq.launch' is not present"
> }

**Expected behavior**
Any API to get history.

**Versions:**
 - Any OS, Firefox
 - Version of RP [ Analysis Service: 4.3.0; API Service: 4.3.0; Index Service: 4.2.0; Authorization Service: 4.2.0; Service UI: 4.3.0; ]

**Comment by DzmitryHumianiuk** [comment]
@MonkAlex other option, based on ID
`/api/v1/project/item/history?ids=1be08d742ab79c0001febae6d&history_depth=10`

@e-olga @pbortnik plz check `filter.eq.uniqueId` availability

**Comment by MonkAlex** [comment]
@DzmitryHumianiuk miss item/history controller, i try to use it.
History returned with diffirent ids, but with single uniqueId, that what i want.

**Comment by pbortnik** [comment]
"Incorrect Request. Required String parameter 'filter.eq.launch' is not present"
To use this endpoint, you have to specify filter by launch id as well.

**Comment by DzmitryHumianiuk** [comment]
@MonkAlex an update for security reasons was made.
and it brings condition check, that you point to existing launch. which has reference to project, where you have access.

I guess we would not address it for 4.x versions.
it will be complicated update and time waste, since we are about to release 5.0

@e-olga plz submit a bug for 5.0 scope.

**Comment by MonkAlex** [comment]
@DzmitryHumianiuk request `item/history?ids` help me, thanks.

**Comment by DzmitryHumianiuk** [comment]
@MonkAlex glad to hear.

another workaround for you:
1. call `item?filter.eq.uniqueId=id1&filter.eq.launch=id2` - parse item id (e.g. id3)
2. call `item/history?ids` with id3
