### ISSUE TITLE
[FR] Adding attachments(Files) and logs to a launch 

### ISSUE THREAD

**Issue by dgur** [reportportal/reportportal#526]
**Describe the solution you'd like**
...
As a user I would like to attach information/ files to a launch level. Currently we are able to attach logs to failed test case only. But we would like to attach some information that is common to all the cases. For example some file that describes tested setup. Some global log relevant to all tests...

**Is your feature request related to a problem? Please describe.**
The current problem for us is we have such files that are nit related to specific case but they help us to investigate failures launches - and we don;t have where to attach the in RP.

**Comment by evjlobanova** [comment]
@dgur Hello! Could you please describe your analysis flow in case I have launch logs? How do you plan to analysis launch attachments and logs? In which case do you look through the log messages?

**Comment by dgur** [comment]
@evjlobanova  Hello!
The global launch logs have timestamps and operations IDs that we can correlate with the logs we have at test level, Besides the logs it would be good to be able to attach XML/Yaml/ other files that describe the setup that the tests were executed on.  So the first thing is to be able to attach the logs and files as simple attachments, The next nice thing indeed can be as i understood from @DzmitryHumianiuk to have a same log view as we have for test case,

**Comment by evjlobanova** [comment]
@dgur now I try to explore an ideal investigation flow. So may be you can share with a steps how you will investigate a launch with attachments and logs? F.e. "first I check launch logs and if find something in them, I should check ... "

Also could you please clarify what you mean under "we can correlate with the logs we have at test level"?

**Comment by dgur** [comment]
ok, So I woild start investigation on the Test case level. 
1. Filter Failed cases in a specific launch.
2. Enter that case Logs, check the error message in the logs window in the Report Portal.
3. Check additional logs/screen-shuts/Artefacts that are attached to that case/
4.O f additional logs are needed  - opend Launch level logs that can be System logs during the launch, Monitoring data that is not divided per case. In those logs look for the time that is Correlates with the  times at rge test level logs - point 2 above.

I hope I made it clear :)
And as a side note - we love the Report Portal!

**Comment by evjlobanova** [comment]
@dgur the last question. How do you understand that launch log is correlating with the test item?

**Comment by dgur** [comment]
@evjlobanova  
I would search in the launch log the time period that the test Item was executed, ans also I would search some specific events,
For example I know that the test is testing VM reboot so I can search in the global log the "VM reboot events" at around that time.
ok?

**Comment by evjlobanova** [comment]
Thank you

**Comment by evjlobanova** [comment]
*Launch logs* (containeers logs)
*As a User* I can attached logs and attachments to a launch.
*So that* other user and I can see additional information that belongs to all items in the launch.
*For that* I should open necessary launch and choose which attachment I want to look through.

![image](https://user-images.githubusercontent.com/30413511/61861628-0237f700-aed5-11e9-9505-36811ff5a11e.png)
![image](https://user-images.githubusercontent.com/30413511/61861665-0ebc4f80-aed5-11e9-8272-0e7fe7d2bcdf.png)

*Reporting*
request: 
Log controller http://{{host}}:{{port}}/api/v1/{{projectName}}/log
[ 
    {
	"file":{
"name" : "api_report.html"
},
      "itemId": "b0d4fc98-2ad8-448f-b853-1fd97821b5c5",
      "level": "error",
      "message": "09:53:16.412 [main] INFO  com.epam.ta.utils.logger.Logger - Set user email.\n09:53:18.335 [main] INFO  com.epam.ta.utils.logger.Logger - Set user project.\n09:53:21.221 [main] INFO  com.epam.ta.utils.logger.Logger - [STEP] Follow registration link and fill registration form.",
      "time": "2019-11-15T14:35:55.006Z"
    }
  ]

**Comment by evjlobanova** [comment]
The feature will be available in beta version 5.0

**Comment by dgur** [comment]
yeey!

**Comment by dgur** [comment]
When is beta version 5.0 is planned to be released?

**Comment by evjlobanova** [comment]
This or next week. But it will be a beta version so that we do not recommend to use this unstable version for production use.

**Comment by DzmitryHumianiuk** [comment]
@Yumfriez do we have static method in `client-java` to attach file to launch?

**Comment by ihar-kahadouski** [comment]
We have.
https://github.com/reportportal/client-java/blob/9c32e5ccf3424a4aec15dda44ffa089f71e8d0aa/src/main/java/com/epam/reportportal/service/ReportPortal.java#L201

**Comment by DzmitryHumianiuk** [comment]
@dgur `emitLaunchLog(...)`

**Comment by shaburov** [comment]
RP version 5.+
https://web.demo.reportportal.io/ui/#api ->  /v2/{projectName}/log
Body structure example:
```
--Z4FJAHmS5dS2gA6K7teCeUnvGpYqw_HC
Content-Disposition: form-data; name="json_request_part"
Content-Type: application/json; charset=utf-8
Content-Transfer-Encoding: 8bit

[{"itemUuid":"setItemUuid","uuid":"setUuid","launchUuid":"setLaunchUuid","time":1583842528486,"message":"setMessage","level":"ERROR","file":{"name":"50fcbc48-2464-42d4-8aa9-437f516453d0"}}]
--Z4FJAHmS5dS2gA6K7teCeUnvGpYqw_HC
Content-Disposition: form-data; name="binary_part"; filename="50fcbc48-2464-42d4-8aa9-437f516453d0"
Content-Type: application/json
Content-Transfer-Encoding: binary

{"key":123}
--Z4FJAHmS5dS2gA6K7teCeUnvGpYqw_HC--

```

**Comment by almayce** [comment]
@shaburov Hi! I try to send the request: 

`curl --location --request POST 'http://localhost:8080/api/v2/SUPERADMIN_PERSONAL/log' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer 59d0f0d0-e59d-4c99-974b-8ffe42ca53cd' \
--header 'Content-Transfer-Encoding: 8bit' \
--header 'Content-Disposition: form-data; name="json_request_part"' \
--data-raw '{"itemUuid":"20db3afa-aea8-4f6f-a629-5a05f3cf20c9",
"uuid":"ca8a3bfa-2eed-4446-8340-d5f24d450d9c",
"launchUuid":"20db3afa-aea8-4f6f-a629-5a05f3cf20c9",
"time":1584377823551,
"message":"Some critical exception",
"level":"ERROR",
"file":{"name":"log4j.properties"}}'`

to **launch level** and to **step level**.
when I checks Report Portal - there are no any attachments on **launch level**. 
There is message attached, but no file attached on **step level**. 

Whats wrong with my request? Could You provide curl of your example, please.
