### ISSUE TITLE
[Feature request] In filters, allow multiple fields, of the same type (e.g launch name, tags etc.)

### ISSUE THREAD

**Issue by ebenahar** [reportportal/reportportal#527]
I would like to filter according to different tags,launch-names,etc with different operators (e.g !cnt, equals, not equals).
This requires selection of multiple fields of the same kind will be allowed (i.e, picking the 'tags' field multiple time).

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu can we make it possible for PD based version?

**Comment by DzmitryHumianiuk** [comment]
@ebenahar @rplevka, 
@pbortnik currently works on it.
RP will have advanced query builder.

we even think to introduce **advanced query search** as text field, like JIRA has.

**Comment by Balamurugan-R** [comment]
@DzmitryHumianiuk Interested in knowing targeted release timeline for this feature?

**Comment by Nkperiwal** [comment]
I am also going through the same issue. It seems it would be better to have multiple conditions filters in the next release. Thanks.

**Comment by evjlobanova** [comment]
I joined this request with #845.
You can follow the progress on this feature in the mentioned ticket.
