### ISSUE TITLE
QUESTION: API Documentation for Java Client similar to JavaScript Client

### ISSUE THREAD

**Issue by mcafeerun** [reportportal/reportportal#533]
Hi,

The reportportal JavaScript client has very good API [documentation](https://github.com/reportportal/client-javascript)  But, i could not find any documentation for [Java Client](https://github.com/reportportal/client-java). Since i'm familiar with reportportal implementation for javaScript frameworks, all i'm looking for is the some basic info for java client such as,
- Maven dependencies
- Some minimal API doc which can help build the reportportal agent for my custom built java framework

Appreciate your help!

Thanks!

**Comment by DzmitryHumianiuk** [comment]
@mcafeerun good catch.
We also expect some contribution for this docs.

Most of java related documentation covered in corresponding agents, which use client:
https://github.com/reportportal/agent-java-junit
https://github.com/reportportal/agent-java-testNG
and here
http://reportportal.io/docs/JVM-based-clients-configuration

but it definitely should be extended in  [Java Client](https://github.com/reportportal/client-java) as well

**Comment by mcafeerun** [comment]
@DzmitryHumianiuk thanks much!

if i get a starting point, i could definitely contribute on the documentation/wiki for Java Client.

**Comment by ZeeshanFr** [comment]
i have create a java library to use with custom java, i covered only what i needed for my requirement, and i integrated with SOAtest and Selenium custom java framework, i can published them somewhere if any one wants to use and enhance them. initially i was on same boat as you but i start going through other client source code to understand the flow.

**Comment by ZeeshanFr** [comment]
i will put some thing this coming weekend

**Comment by mcafeerun** [comment]
Thanks!

**Comment by mcafeerun** [comment]
@zeeshanFr hope we can get some documentation this weekend. Again, much appreciate your help!!

**Comment by mcafeerun** [comment]
@ZeeshanFr @DzmitryHumianiuk - Can anyone of you help me to head start this?

**Comment by DzmitryHumianiuk** [comment]
@mcafeerun yes, sure.
I can give you a helping hand.

You want to contribute into Java client docs?
