### ISSUE TITLE
More graceful handling of displaying test failures on different levels

### ISSUE THREAD

**Issue by abasau** [reportportal/reportportal#538]
When filtering failed test items by Defect Type (e.g. clicking To Investigate badge on Launches page) and the test items have different Types (e.g. STEP and TEST), the page will not show STEP failures correctly and Defect type Dropdown will look incorrectly.

![image](https://user-images.githubusercontent.com/6681200/50014269-7d294e80-ff91-11e8-8558-cc09c2567371.png)

I would expect at least STEP test failures to be displayed correctly.

![image](https://user-images.githubusercontent.com/6681200/50014314-9c27e080-ff91-11e8-8d8b-fe0d2ba763c0.png)

Usually it happens when RP experience some issues and agent can't create a test item with STEP type.

**Versions:**
 - OS, Browser: Any
 - Version of RP:  Service UI: 4.3.4; API Service: 4.3.3;

**Comment by DzmitryHumianiuk** [comment]
@abasau what's the reason to have Steps and Tests at the same level?
or it is an internal specific of your runner?

**Comment by abasau** [comment]
@DzmitryHumianiuk This is just a true BDD structure and has numerous benefits:
- RP shows troubleshooting information (logs, screenshots) is scope of failed step. It's more easy to find information relevant to the failure.
- You can have several failing steps and link different issues to different steps, and AA will notice fixed steps or new failing steps (multiple failures pattern).
- Easy to read test BDD scenario - step level looks like feature file.
- etc.

**Comment by DzmitryHumianiuk** [comment]
@abasau do you see any options to wrap it into [Nested Steps](https://github.com/reportportal/reportportal/issues/275)?

**Comment by abasau** [comment]
@DzmitryHumianiuk Nested Steps might partially address the issue (e.g. items 1 and 3 from my previous comment) but won't work if support of "multiple failures" is critical (item 2). It would be very difficult to abandon some feature ("multiple failures") that was very useful in past.

**Comment by VolhaKarenko** [comment]
The issue is still reproducible on 5.1 version
