### ISSUE TITLE
Restart ReportPortal

### ISSUE THREAD

**Issue by denispnz** [reportportal/reportportal#541]
Всем привет! Подскажите как корректно нужно и можно перезапускать сам портал без потери данных?  Работает на докер. после попыток перезапуска постоянно пишет что порты заняты и получаю много ошибок. mongodb в докере.

ui_1             | 2018/12/19 17:30:36 Cannot register service: Put http://registry:8500/v1/agent/service/register: dial tcp 172.20.0.6:8500: connect: connection refused
registry_1       |     2018/12/19 17:30:41 [WARN] agent: Check "service:api-e608d8ce796107cd6036c52e3c7be5e1" HTTP request failed: Get http://f9c578ea1805:8080/api/v1/admin/health: dial tcp: lookup f9c578ea1805 on 127.0.0.11:53: server misbehaving

**Comment by denispnz** [comment]
Ошибки типа:

Attaching to ddruzhinin_elasticsearch_1, ddruzhinin_jira_1, ddruzhinin_gateway_1, ddruzhinin_rally_1, ddruzhinin_ui_1, ddruzhinin_registry_1, ddruzhinin_mongodb_1, ddruzhinin_analyzer_1, ddruzhinin_index_1, ddruzhinin_api_1, ddruzhinin_uat_1
gateway_1        | time="2018-12-19T17:30:37Z" level=error msg="Failed to retrieve health checks" error="Get http://registry:8500/v1/health/state/any?wait=15000ms: dial tcp 172.20.0.6:8500: connect: connection refused"
gateway_1        | time="2018-12-19T17:30:37Z" level=error msg="Consul connection error Get http://registry:8500/v1/health/state/any?wait=15000ms: dial tcp 172.20.0.6:8500: connect: connection refused, retrying in 263.276029ms"
gateway_1        | time="2018-12-19T17:30:37Z" level=error msg="Failed to list services: Get http://registry:8500/v1/catalog/services?wait=15000ms: dial tcp 172.20.0.6:8500: connect: connection refused"
ui_1             | 2018/12/19 17:30:36 Cannot register service: Put http://registry:8500/v1/agent/service/register: dial tcp 172.20.0.6:8500: connect: connection refused

**Comment by DzmitryHumianiuk** [comment]
@denispnz most likely you should clean consul cache folder 
`data/consul`

if you loose data in mongo, then you should use setup with mongodb deployed separately.
example of config can be combined at Download page. Under this button:
![image](https://user-images.githubusercontent.com/11332788/50280372-5c636c00-045d-11e9-91af-d5f1d4293580.png)

or if you still want to use mongo in container, that mount mongo storage to a remote directory. Since by default it uses folder in container, and this folder will be killed with container restart.
 
But the main question: why you need to restart RP?

**Comment by denispnz** [comment]
docker-compose stop , is it if in daemon mode.

**Comment by DzmitryHumianiuk** [comment]
@denispnz did you find solution?

Да и к чему вообще его перезапускать?

**Comment by SamSSV** [comment]
Hi everyone.
Dzmitry Humianiuk, I have following issues
registry_1       |     2019/10/10 20:45:44 [ERR] http: Request GET /v1/catalog/services?wait=50s&index=0, error: No cluster leader from=172.18.0.10:48268
registry_1       |     2019/10/10 20:45:44 [ERR] http: Request GET /v1/catalog/services?wait=15000ms, error: No cluster leader from=172.18.0.3:44472
registry_1       |     2019/10/10 20:45:44 [ERR] http: Request GET /v1/catalog/services?wait=2s&index=531, error: No cluster leader from=172.18.0.10:48288
registry_1       |     2019/10/10 20:45:44 [ERR] http: Request GET /v1/health/state/passing?wait=15000ms, error: No cluster leader from=172.18.0.3:44470
gateway_1        | time="2019-10-10T20:45:36Z" level=error msg="Failed to list services: Get http://registry:8500/v1/catalog/services?wait=15000ms: dial tcp 172.18.0.2:8500: connect: connection refused"
gateway_1        | time="2019-10-10T20:45:36Z" level=error msg="Failed to retrieve health checks" error="Get http://registry:8500/v1/health/state/passing?wait=15000ms: dial tcp 172.18.0.2:8500: connect: connection refused"
gateway_1        | time="2019-10-10T20:45:36Z" level=error msg="Consul connection error Get http://registry:8500/v1/catalog/services?wait=15000ms: dial tcp 172.18.0.2:8500: connect: connection refused, retrying in 697.227159ms"
gateway_1        | time="2019-10-10T20:45:44Z" level=error msg="Failed to list services: Unexpected response code: 500 (No cluster leader)"
gateway_1        | time="2019-10-10T20:45:44Z" level=error msg="Consul connection error Unexpected response code: 500 (No cluster leader), retrying in 535.195742ms"
gateway_1        | time="2019-10-10T20:45:44Z" level=error msg="Failed to retrieve health checks" error="Unexpected response code: 500 (No cluster leader)"

CAn you help me please?

**Comment by DzmitryHumianiuk** [comment]
@SamSSV stop all.
delete `data/consul`
restart
