### ISSUE TITLE
unable to create a link to the result log page - page keeps reloading

### ISSUE THREAD

**Issue by jhutar** [reportportal/reportportal#542]
**Describe the bug**
Given project name, launch id and log result id, I'm unable to construct functional link to test result. When link is opened, page keeps reloading.

**Expected behavior**
It should be possible to create nice link to single test result (logs page) I can share with other users in the project.

**Screenshots**
Page is reloading quickly and history bar is getting duplicated:
![screenshot_2018-12-19_23-13-41](https://user-images.githubusercontent.com/3397250/50251554-84fb4f80-03e4-11e9-9f90-3397e6fd028a.png)

**Versions:**
 - desktop: Fedora 28, firefox-63.0.3-2.fc28.x86_64
 - server: RHEL7, docker-1.13.1-75.git8633870.el7_5.x86_64
 - Version of RP: Current version: Analysis Service: 4.3.0; API Service: 4.3.3; Index Service: 4.2.0; Authorization Service: 4.2.0; Service UI: 4.3.5;

**Comment by jhutar** [comment]
CC @rplevka and @schlupov

**Comment by rplevka** [comment]
@jhutar thanks for reporting this. it was making me mad

**Comment by DzmitryHumianiuk** [comment]
@jhutar @rplevka this already fixed in 5.0
which is about to be released.
won't fix in 4.3.+ version

**Comment by jhutar** [comment]
Awesome, thank you!
