### ISSUE TITLE
it is hard to copypaste test name (and nothing else)

### ISSUE THREAD

**Issue by jhutar** [reportportal/reportportal#548]
**Describe the bug**
It is hard to copypaste test name (and nothing else):
- if you click between test name and "Refresh" button and attempt to highlight test name (move mouse to the left) to be able to Ctrl+C it, it also highlights "Refresh" button
- if you click between launch name and test name attempt to highlight test name (move mouse to the right) to be able to Ctrl+C it, it also highlights launch name

**Expected behavior**
Maybe if some borders or paddings are added, it could be easier to highlight test name

**Screenshots**
![screenshot_2019-01-09_12-16-46](https://user-images.githubusercontent.com/3397250/50896217-af02c900-1408-11e9-9565-4bb7f85f0856.png)
![screenshot_2019-01-09_12-18-54](https://user-images.githubusercontent.com/3397250/50896291-e6717580-1408-11e9-9db5-5c4fd303a834.png)

**Versions:**
 - browser: firefox-64.0-4.fc28.x86_64
 - Version of RP: Analysis Service: 4.3.0; API Service: 4.3.3; Index Service: 4.2.0; Authorization Service: 4.2.0; Service UI: 4.3.5;

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova I guess, to search for corresponding test class in code within IDE

**Comment by jhutar** [comment]
@evjlobanova Yes. I want to run that one test with pytest on local setup. Thank you for considering the issue.

**Comment by DzmitryHumianiuk** [comment]
I guess we also can output this information in test case description

**Comment by evjlobanova** [comment]
@jhutar we have added field Code reference with a Copy button.
![image](https://user-images.githubusercontent.com/30413511/77932925-dc11f480-72b6-11ea-9d91-d98f822fc259.png)

Will it helpful for you?

**Comment by jhutar** [comment]
Thank you. I think it is a usable workaround.

**Comment by evjlobanova** [comment]
@jhutar Can I close the issue?

**Comment by jhutar** [comment]
I would keep it open until proper fix is done, but I will certainly not reopen - I assume you have other priorities as well. Thank you!

**Comment by DzmitryHumianiuk** [comment]
@jhutar it's already implemented in 5.0

so i guess can be closed.

![image](https://user-images.githubusercontent.com/30413511/77932925-dc11f480-72b6-11ea-9d91-d98f822fc259.png)
