### ISSUE TITLE
Test execution hangs: ReportPortal exception: System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by michalfar** [reportportal/reportportal#549]
**Describe the bug**

ReportPortal Client throw exception during running nunit tests using nunit3console:

ReportPortal exception was thrown.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ReportPortal.NUnitExtension.ReportPortalListener.FinishTest(XmlDocument xmlDoc)
ReportPortal exception was thrown.
System.ArgumentException: The tasks argument included a null value.
Parameter name: tasks
   at System.Threading.Tasks.TaskFactory.CheckMultiContinuationTasksAndCopy(Task[] tasks)
   at System.Threading.Tasks.TaskFactory`1.ContinueWhenAllImpl(Task[] tasks, Func`2 continuationFunction, Action`1 continuationAction, TaskContinuationOptions continuationOptions, CancellationToken cancellationToken, TaskScheduler scheduler, StackCrawlMark& stackMark)
   at System.Threading.Tasks.TaskFactory.ContinueWhenAll[TResult](Task[] tasks, Func`2 continuationFunction)
   at ReportPortal.Shared.TestReporter.Finish(FinishTestItemRequest request)

Nunit test ends as failed but it is not reported to the ReportPortal. 
Launch and test in RP is still "in progress" state.

**Expected behavior**
Test is finished and reported to the ReportPortal.

**Screenshots**

**Versions:**
-RP:
Analysis Service: 4.2.0; API Service: 4.3.0; Index Service: 4.2.0; Jira Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.0;

-Nunit:
NUnit.3.9.0

-RP client:
ReportPortal.NUnit.3.4.3
ReportPortal.Client.2.1.4
ReportPortal.Shared.2.0.8

**Comment by nvborisenko** [comment]
Based on the exception I can suppose that some unusual case appeared in TestResult.xml. It's hard to investigate what was happened without details. @michalfar is it possible to share your `TestResult.xml` file. It would be very helpful in fixinng this issue. If it's possible, please point me on the test name which you see as unfinished on Report Portal web interface.

**Comment by michalfar** [comment]
@nvborisenko 
It is only one test runned a few times.

[TestResult.txt](https://github.com/reportportal/reportportal/files/2749202/TestResult.txt)

**Comment by nvborisenko** [comment]
Fixed in `ReportPortal.NUnit v3.5.1`.

The issue was in `Assert.Fail()` code in your tests, in this case nunit doesn't generate `failure message`, only stacktrace. `failure message` property was considered as required property by listener.

**Comment by michalfar** [comment]
Thanks for help.
When I try to update ReportPortal.NUnit to the v3.5.1. I got following error:
The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\repositiories\packages\ReportPortal.Client.2.1.6\build\ReportPortal.Client.targets

It seems, package(ReportPortal.Client.2.1.6) are created/saved using VS2017. We use VS2015.
Can you provide a version, which is working on VS2015?

**Comment by nvborisenko** [comment]
Fixed in `ReportPortal.Shared 2.1.1` as well as in `ReportPortal.Client 2.1.7`. Please upgrade these package and verify.

**Comment by michalfar** [comment]
Great. It works like a charm.
@nvborisenko many thanks!

**Comment by nvborisenko** [comment]
Thanks for issues.
