### ISSUE TITLE
Please provide a way to update required listener parameters programatically

### ISSUE THREAD

**Issue by adhithyasrinivasan** [reportportal/reportportal#550]
**Describe the solution you'd like**
... Currently report portal supports loading launch name from property file and run configuration. I have to dynamically update the launch name with the testng suite name or testng test name depending upon the situation i am working on.

please provide a way to update the desired listener parameters through java code.

**Is your feature request related to a problem? Please describe.**
...

**Comment by DzmitryHumianiuk** [comment]
@adhithyasrinivasan https://github.com/reportportal/agent-java-testNG#code-example-how-to-overload-params-in-run-time
