### ISSUE TITLE
ReadyApi - Getting different launches for different suites of a project

### ISSUE THREAD

**Issue by bawarim** [reportportal/reportportal#553]
I have executed my project which contains different test suites. But the problem is I am getting different launches for each suite. And then i need to manually merge those launches.

So is there any way that I can get all the suite results in a same launch for a project. 

## Resolution
https://github.com/reportportal/reportportal/issues/553#issuecomment-466294588

**Comment by DzmitryHumianiuk** [comment]
@bawarim 
there are 2 ways to make it:
1) start launch via code before execution, and share launch id
2) after execution - collect IDs of launches, and trigger merge via API.

More simplistic method will come with 5.0+ version

**Comment by bawarim** [comment]
Okay. But i have few queries now.
1. How to get the launch id of a project? 
   a) If I have 3 launches for same project like ProjectA #1, ProjectA #2, ProjectA #14.  Then how to get the id of latest launch?
2. Where to specify that launch id, so that next suites to be run will go to the same launch?

**Comment by lilacharviv** [comment]
> @bawarim
> there are 2 ways to make it:
> 
> 1. start launch via code before execution, and share launch id
> 2. after execution - collect IDs of launches, and trigger merge via API.
> 
> More simplistic method will come with 5.0+ version

How can we do this? get the launch id?
can u share code example?

**Comment by bawarim** [comment]
@lilacharviv  This is how i achieved it. I have read all launched id from report portal temp files. Then I have merged all launches into a single one using post merge api. Below is the code for reference. 


File[] listOfFiles = folder.listFiles(new File ("Path of report portal temp files"));
 for (int i = 0; i < listOfFiles.length; i++) {			 
	fileName =  listOfFiles[i].getName();
	Path path = Paths.get(tempPath + "\\" + fileName);			
	if(id.equals(""))
	{
		id = "\"" + fileName.split(".tmp")[0].split("-")[3] + "\"";
		startft = attr.creationTime();
		startDateTime =  attr.creationTime().toString();							
	}
	else
	{
	         id = id + "," + "\"" + fileName.split(".tmp")[0].split("-")[3] + "\"";
		endft = attr.creationTime();						
	}
   }
   if(startft.compareTo(endft) < 0)
   {	startDateTime = endft.toString(); endDateTime =  startft.toString();}
  else
   {	startDateTime = startft.toString(); endDateTime =  endft.toString();}
					
  String URL = "rp.endpoint" + "/api/v1/" + "rp.project" + "/launch/merge";
  HttpPost  post = new HttpPost(URL);					
  String payload = "{\"description\":\"Grid Merged 
 Results\",\"end_time\":\"END_DATETIME\",\"extendSuitesDescription\":true,\"launches\": [LaunchID],\"merge_type\":\"BASIC\",\"mode\":\"DEFAULT\",\"name\":\"ProjectName\",\"start_time\":\"START_DATETIME\",\"tags\":[\"TAGS_INFO\"]}";

payload = payload.replace("LaunchID", id);
payload = payload.replace("ProjectName", rp.launch);
payload = payload.replace("END_DATETIME", endDateTime);
payload = payload.replace("START_DATETIME", startDateTime);
								
post.setEntity(new StringEntity(payload, ContentType.APPLICATION_JSON));
post.setHeader("Content-type", "application/json");
post.setHeader("Authorization", "Bearer "+ authKey);
HttpClient   httpClient    = HttpClientBuilder.create().build();
HttpResponse  response=null;
try {
	response = httpClient.execute(post);
	} catch (ClientProtocolException e) {
						e.printStackTrace();
					} catch (IOException e) {
						e.printStackTrace();
					}

**Comment by DzmitryHumianiuk** [comment]
@bawarim can we close it?

**Comment by bawarim** [comment]
@DzmitryHumianiuk Yes, we can close it.
