### ISSUE TITLE
Post all results to same launch instead of creating new launch

### ISSUE THREAD

**Issue by bawarim** [reportportal/reportportal#555]
Hi,

I want to report all my result to the same launch. I am using cucumber test framework.
So is there any way around that i can provide rp.launch.id from property file or from somewhere else, so that my all results will go to the same launch.

**Comment by evjlobanova** [comment]
@bawarim we are planning to implement Rerun functionality #363 .  Is it what you need.

As a work around for now, you can merge launches via API or via UI.

**Comment by bawarim** [comment]
I am executing two test suite together. And for each test suite, currently it creates a separate launch. 
But what I want is that, whenever I run all suites together, they should go to the same launch instead of creating different launches.

So what i basically want that, if we can provide rp.launch.id into property file, and all the test results go to the same launch id which i have given in the property file instead of creating new launch id.

**Comment by evjlobanova** [comment]
@bawarim Yes, you can collate different results together is to provide the same launch id, so suite components’ results will be stored as 1 run or you can report them as different launches and then use Report Portal merge (linear or deep)

**Comment by evjlobanova** [comment]
@bawarim Yes, you can collate different results together is to provide the same launch id, so suite components’ results will be stored as 1 run or you can report them as different launches and then use Report Portal merge (linear or deep)

**Comment by himkumar1990** [comment]
Hi , Can you please explain how can we use launch id in the reportportal.properties
