### ISSUE TITLE
gitlab rp integration

### ISSUE THREAD

**Issue by mohanrajramalingam** [reportportal/reportportal#556]
RP Team,
I am trying to integrate RP from my gitlab runner. I am getting below error while launching the report.
I exported the token first, then I run the reporter command. From my local its working. But from gitlab I'm getting the below error:

Generating HTMLReport report
Run time of JUnit formatter: 9.763ms
Run time of HTML formatter: 625.672ms
[startLaunch] unexpected error:
FetchError: request to https://rp.epam.com/<Path>/ProjectUrl/ launch failed, reason: read ECONNRESET
Reports run time: 1544.786ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! projectname-microservices-qe@1.0.0 reporter: `project-reporter -- {@} -c --`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the projectname-microservices-qe@1.0.0 reporter script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Any idea, what did I miss. Let me know if any information I missed to share.

**Comment by ihar-kahadouski** [comment]
@mohanrajramalingam do you use client/agent or send requests directly to api?

**Comment by mohanrajramalingam** [comment]
This is due to security issue, its resolved. Added the rp.epam.com url in the whitelist category from my cloud server. its working.
