### ISSUE TITLE
Please trim of the spaces in reportportal.properties

### ISSUE THREAD

**Issue by adhithyasrinivasan** [reportportal/reportportal#557]
**Describe the bug**
... Unable to start the test if there is a trailing space in the property rp.endpoint.

**Expected behavior**
... Leading and trailing space should be trimmed of before loading from property file.

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]
Build: 4.3.6

**Comment by DzmitryHumianiuk** [comment]
@adhithyasrinivasan 
can't find situation when it is needed?

do you generate properties file on runtime?

**Comment by evjlobanova** [comment]
Closed, because of no response
