### ISSUE TITLE
Change method name. Include package name and class name.(e.g package.ClassName#methodName)

### ISSUE THREAD

**Issue by Zakaryan92** [reportportal/reportportal#558]
We are running about 4000 tests and using report portal. In a suite run we have tests there have a same name, but there are in a different classes. When suite run finished, report portal merged same name methods in a one and I can't have a true result of my test suite run. Thanks @DzmitryHumianiuk

**Comment by DzmitryHumianiuk** [comment]
@Zakaryan92 what do you mean under
> report portal merged same name methods in a one 

screenshot will be helpful to understand

**Comment by Zakaryan92** [comment]
I have two methods with name filterViewGrouping.
One in a selenium.lists.ProjectsListTest#filterViewGrouping, other selenium.lists.TasksListTest#filterViewGrouping. So both tests was successfully finished but when launches was finished both merged to one.

**Comment by Zakaryan92** [comment]
![screen shot 2019-01-25 at 3 27 45 pm](https://user-images.githubusercontent.com/17787698/51743776-2d24c800-20b7-11e9-98e9-193399598f0b.png)

**Comment by Zakaryan92** [comment]
Retry count when test method failed is 2.

**Comment by Zakaryan92** [comment]
any updates on this? @DzmitryHumianiuk

**Comment by DzmitryHumianiuk** [comment]
@Zakaryan92 this can be done on your side.
just extend the RP agent, in place where it form the test case name.
and push the name with all info

**Comment by Zakaryan92** [comment]
I changed buildStartStepRq method and its working fine for me. Thanks! @DzmitryHumianiuk
