### ISSUE TITLE
PDF Generated from launch report api is blank

### ISSUE THREAD

**Issue by adhithyasrinivasan** [reportportal/reportportal#559]
**Describe the bug**
API -  /{projectName}/launch/{launchId}/report

We tried generating a pdf file from this api. But the pdf result is blank.

**Expected behavior**
... PDF should be generated

**Screenshots**
If applicable
Attached
**Versions:**
 - OS, Browser Windows Chrome
 - Version of RP [find it under Login form, copy as is]
Build: 4.3.6

**Comment by evjlobanova** [comment]
@VolhaKarenko Volha, could you please try to reproduce this issue?

**Comment by evjlobanova** [comment]
@adhithyasrinivasan how is important for you this possibility? 
Now we are moving to PostgreSQL , so we will consider this issue in future version. 
So I `d like to know, if this issue stops you. Or maybe you can use export via UI?

**Comment by adhithyasrinivasan** [comment]
> @adhithyasrinivasan how is important for you this possibility?
> Now we are moving to PostgreSQL , so we have considered this issue in 5.0 version.
> So I `d like to know, if this issue stops you. Or you can use export via UI?

if it is fixed easily without any extra effort, i wish you to fix this in next release.

**Comment by DzmitryHumianiuk** [comment]
verified
