### ISSUE TITLE
Skipped test is marked as 'to investigate'

### ISSUE THREAD

**Issue by maaxlee** [reportportal/reportportal#56]
If test case is reported with status 'SKIP' then it's shown as Skipped but marked as 'to investigate'.
I wish it was ignored in this case or marked as 'No defect' (or there is an option to choose behavior).

![skipped](https://cloud.githubusercontent.com/assets/6975495/21353708/484cff70-c6d8-11e6-821e-f1dbbcd38882.png)

**Comment by admizh** [comment]
Simple case for it (TestNg):

```java
public class ApiAuthTest {
    private Logger logger = LoggerFactory.getLogger(this.getClass());
    
   @Test
    public void sanityCheck() {
        throw new AssertionError("Sanity check is failed");
    }

    @Test(dependsOnMethods = "sanityCheck")
    public void checkAuthViaApiCall() {
        logger.trace("i am depended test");
    }

}
```
Defect should be marked like "No Defect". Because test not started due failing in dependent method
Same situation for @BeforeSuite,@BeforeGroups,@BeforeClass,@BeforeTest,@BeforeMethod - if we have failures on this - we should investigate only it.

**Comment by DzmitryHumianiuk** [comment]
@maaxlee 
which agent do you use?

if it ***TestNG** then try `rp.skipped.issue = FALSE` in parameters. 
> FALSE - skipped tests will not be mark as 'To Investigate' on portal.

Agent will send `EPMTY` defect to server for skipped items.

@avarabyeu 
please show example of empty defect to send

**Comment by admizh** [comment]
@DzmitryHumianiuk it work for me, thank you!
