### ISSUE TITLE
How to send images attachment in POST api/v1/{projectname}/log

### ISSUE THREAD

**Issue by bawarim** [reportportal/reportportal#561]
I am trying to integrate Report portal with my customize test framework. 
I need to send screenshot to the report portal using log api. So please help that how can i achieve the same.

**Comment by Yumfriez** [comment]
To create a log with an attachment you should send a POST request to the 'api/v1/{projectname}/log' endpoint and configure it like this:
1) content type of the request - multipart/form-data
2) in the body of the request should be 2 params: 
                                             a) json_request_part - json file of the following format:
[  
   {  
      "file":{  
         "name":"NAME_OF_THE_FILE_TO_UPLOAD"
      },
      "itemId":"ID_OF_THE_TEST_ITEM",
      "level":"LOG_LEVEL",
      "message":"YOUR_MESSAGE",
      "time":"2019-11-15T14:35:55.006Z"
   }
]
                                            b) file - all files that you want to upload (file names should match with file names from the 'json_request_part'

Here is a raw example from Postman
![image](https://user-images.githubusercontent.com/31598109/52042679-d6a00980-254e-11e9-8e42-f49a2d1c9bb0.png)

**Comment by bawarim** [comment]
@Yumfriez But how can i achieve it through the code? As i'll be integrating this api with my test framework. 
I am trying to send screenshots to the report portal using vbscript.

**Comment by Yumfriez** [comment]
@bawarim Maybe you can use .NET client https://github.com/reportportal/client-net or if it doesn't fit your requirements, the only way is to create your own multipart request and send it right to the RP-api

**Comment by ajaychinthamanipet** [comment]
@Yumfriez I called the API as per your suggestion and I was able to successfully send screenshot to RP logs. But in my code, I am fetching image from another API and I want to attach it to the logs. How do I do it?. I am facing issue in this step. I tried converting fetched image to base64 and send to logs but it didn't worked.

**Comment by bawarim** [comment]
I have also converted the image into base64 and tried to post it. But I am getting below error.
 org.apache.commons.fileupload.FileUploadException: Header section has more than 10240 bytes (maybe it is not properly terminated)]

**Comment by ajaychinthamanipet** [comment]
Below is my code to fetch image from 1 API store it in work space and send it to log API, but its not working. I am not getting any response from API. Please help me in this scenario.

def attach_logs(message):
        #Getting screenshot from another API
        response = requests.get(
            "http://host/screenshot.png")
	
	# Response is the image
        level = "info"
        reportPortalCall.end_time = str(int(time.time() * 1000))
        with open("screenshot.png", "wb") as output_file:
            output_file.write(response.content)

        json_request = [{"file": {"name": file_name, "content-type": "image/png"}, "item_id":reportPortalCall.test_item_id,
                              "level": level, "message": message, "time": reportPortalCall.end_time}]

        with open("screenshot.json", "wb") as f:
            f.write(str(json_request))

        # Calling report portal log API
        test = requests.post(reportPortalCall.end_point + "log",
                             json_request_part="screenshot.json",
                             file="screenshot.png", headers={
                "Authorization": reportPortalCall.auth_token,
                "content-type": "multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW"})

**Comment by Yumfriez** [comment]
@bawarim try to upload attachment of smaller size. Is exception is still thrown?

**Comment by Yumfriez** [comment]
@ajaychinthamanipet Could you please send some screenshots of the attachments reporting flow process?

**Comment by ajaychinthamanipet** [comment]
![screenshot](https://user-images.githubusercontent.com/41054628/53315804-27efae80-38eb-11e9-8bac-acda1229d5d1.png)
![30x_forward](https://user-images.githubusercontent.com/41054628/53315805-28884500-38eb-11e9-9da3-47680cb085a1.png)

@Yumfriez I have atttached Screenshots. If you have a code to atach screenshots to logs and thats working please share it. Thanks

**Comment by DzmitryHumianiuk** [comment]
@Yumfriez ^

**Comment by balachandra2005** [comment]
@bawarim : I am also facing the same issue while trying to send screenshot using VBScript to Reportportal. Please let me know if you find some solution.

Getting error **"{"error_code":4001,"message":"Incorrect Request. Required request part 'json_request_part' is not present"}"**

Please find the attached code. 
[VBscriptCode.txt](https://github.com/reportportal/reportportal/files/3778951/VBscriptCode.txt)

**Comment by Yumfriez** [comment]
This request consists of 2 parts:
1) (Json file) or (Plain JSON Objects) that represent Log RQ entity as first request part;
2) Files that are attached to the logs entities;
----------------------------------------

            File xml = new File("q.xml");
            File part = new File("test.json");
            HttpHeaders logHeaders = new HttpHeaders();
            headers.setContentType(MediaType.MULTIPART_FORM_DATA);
            MultiValueMap<String, Object> body = new LinkedMultiValueMap<>();
            body.add("json_request_part", part);
            body.add("file", xml);
            HttpEntity<MultiValueMap<String, Object>> logRQHttpEntity = new HttpEntity<>(body, logHeaders);
            ResponseEntity<BatchSaveOperatingRS> logExchange = restTemplate.exchange(RP_HOST + "/log",
                    HttpMethod.POST,
                    logRQHttpEntity,
                    BatchSaveOperatingRS.class
            );
----------------------------------------
test.json - first part with log RQ (replace contents by your real data), content of the file:
-----
[ 
   { 
      "file":{ 
         "name":"q.xml"
      },
      "itemUuid":"testItemUuid",
      "level":"error",
      "message":"string",
      "time":"2019-11-15T14:35:55.006Z"
   }
]
-----
Instead of test.json you can use your Json object
q.xml - file that attached to the second part (There is a file object inside of log entity object with name of this file, which can also be rewritten by your data)

**Comment by balachandra2005** [comment]
@Yumfriez: I tried this option suggested. The problem is unable to combine two different objects. 
In this case, JSON object and Image content.  I can send only the binary or only text data in VBScript.

Option 1: Converted both json and image content into binary and sent. Exception is thrown as below.
[VBscriptCode_V2.txt](https://github.com/reportportal/reportportal/files/3790924/VBscriptCode_V2.txt)

> "{"responses":[{"message":"ReportPortalException: Binary data cannot be saved. There is no request part or file with name CleverBaby.png","stack_trace":"com.epam.ta.reportportal.exception.ReportPortalException: Binary data cannot be saved. There is no request part or file with name CleverBaby.png\n\tat 

Option 2: Sending both json and image contents in text format.  Image conversion to text didn't work.

please suggest.

**Comment by balachandra2005** [comment]
@Yumfriez 
I was able to send multipart logging request with below request body. But image file is not displayed in ReportalPortal.
-----------------------------0123456789012
Content-Disposition: form-data; name="json_request_part"
Content-Type: application/json

[{"item_id":"5dbb5e21b9d82100016c7a99","time":"2019-10-31T22:20:17.598Z","level":"info","message":"test step","file":{"name":"CleverBaby.png"}}]
-----------------------------0123456789012
Content-Disposition: form-data; name="binary_part"; filename="CleverBaby.png"
Content-Transfer-Encoding: binary
Content-Type: image/png

iVBORw0KGgoAAAANSUhEUgAABVYAAAMACAIAAABAXKuVAAAAAXNSR0IArs4c6QAAAARnQU1BAA==
-----------------------------0123456789012--

Screenshots are attached.  
![image](https://user-images.githubusercontent.com/41419116/67990408-36c1fa00-fc0c-11e9-8dd9-b1281e2ab84e.png)


when clicked on preview: 
![image](https://user-images.githubusercontent.com/41419116/67990611-cb2c5c80-fc0c-11e9-935c-7b5b18493d07.png)

Base64 image conversion is done in VBScript as below:

	  Dim inputStream
	  Set inputStream = CreateObject("ADODB.Stream")
	  inputStream.Open
	  inputStream.Type = 1   'adTypeBinary
	  inputStream.LoadFromFile ImageFilePath
	  Dim bytes: bytes = inputStream.Read
	  Dim dom: Set dom = CreateObject("Microsoft.XMLDOM")
	  Dim elem: Set elem = dom.createElement("tmp")
	  elem.dataType = "bin.base64"
	  elem.nodeTypedValue = bytes
	  ImageBase64String= Replace(elem.text, vbLf, "")


Please help!

**Comment by ajayrrk** [comment]
@balachandra2005  I tried same approach for my project and was struck at where you are.


@bawarim I would be great if there is any way to integrate screenshots with UFT

**Comment by balachandra2005** [comment]
@Yumfriez
Image is not getting displayed in ReportPortal after sending the following request from VBScript. Could you please help.
-----------------------------0123456789012
Content-Disposition: form-data; name="json_request_part"
Content-Type: application/json

[{"item_id":"5dbb5e21b9d82100016c7a99","time":"2019-10-31T22:20:17.598Z","level":"info","message":"test step","file":{"name":"CleverBaby.png"}}]
-----------------------------0123456789012
Content-Disposition: form-data; name="binary_part"; filename="CleverBaby.png"
Content-Transfer-Encoding: binary
Content-Type: image/png

iVBORw0KGgoAAAANSUhEUgAABVYAAAMACAIAAABAXKuVAAAAAXNSR0IArs4c6QAAAARnQU1BAA==
-----------------------------0123456789012--

Screenshots are attached in my previous post.

**Comment by evjlobanova** [comment]
Please use our dev guide:
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#batch-save-logs

**Comment by edyp** [comment]
@evjlobanova I would like to send bigger log file than 10240 B and it is not possible. I can't find in documentation how big items we can send.
Why is implemented such limitation?

**Comment by DzmitryHumianiuk** [comment]
@edyp are you referring to attachment or the log message itself?
AFAIK, default attachment is limited to 128Mbs.

cc @Yumfriez @pbortnik

**Comment by edyp** [comment]
@DzmitryHumianiuk We found a solution, but we are not sure it this is a bug, it isn't perfect and we would like to stick mostly to documentation. So...
according to [documentation](https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#batch-save-logs) 
`curl --header "Content-Type: application/json" \
     --header "Authorization: Bearer 039eda00-b397-4a6b-bab1-b1a9a90376d1" \
     --request POST \
     --form '[{"itemUuid":"9c7632a2-272e-4c24-9627-d7d509de7620","launchUuid":"96d1bc02-6a3f-451e-b706-719149d51ce4","time":"2019-11-06T15:50:53.187Z","message":"Some critical exception","level":40000,"file":{"name":"file1.pdf"}},{"itemUuid":"16fb3d7f-ddce-407a-8e52-464a596e6da1","launchUuid":"96d1bc02-6a3f-451e-b706-719149d51ce4","time":"2019-11-06T15:50:53.187Z","message":"java.lang.NullPointerException","level":40000,"file":{"name":"file2.txt"}}]' \
     --form "file=@/path/to/file1.pdf" \
     --form "file=@/path/to/file2.txt" \
     http://rp.com/api/v1/rp_project/log`

We got problem to send this request with `--header "Content-Type: application/json"` it was sendable only when `Content-Type: multipart/form-data`
Every `--form` attribute need to have at the end `;type=...` without that we got problem to send bigger logs. 
We couldn't send json as a string in request but we put it in a file and then send it.
our example of working request:
`curl --header "Content-Type: multipart/form-data" \
                    --header "Authorization: Bearer ${RP_API_TOKEN}" \
                    --request POST \
                    --form "json_request_part=@${TMP_FILENAME};type=application/json" \
                    --form "file=@${LOGFILE_FULL_FILENAME};type=text/plain" \
                    ${REPORT_PORTAL_URL}/api/v1/${REPORT_PORTAL_PROJECT}/log)`

Please send me back if you have similar problems. 
How we can send json as a string in request?

**Comment by Yumfriez** [comment]
Added modified script to the new issue:
https://github.com/reportportal/reportportal/issues/985

**Comment by pradeep1299** [comment]
> To create a log with an attachment you should send a POST request to the 'api/v1/{projectname}/log' endpoint and configure it like this:
> 
> 1. content type of the request - multipart/form-data
> 2. in the body of the request should be 2 params:
>    a) json_request_part - json file of the following format:
>    [
>    {
>    "file":{
>    "name":"NAME_OF_THE_FILE_TO_UPLOAD"
>    },
>    "itemId":"ID_OF_THE_TEST_ITEM",
>    "level":"LOG_LEVEL",
>    "message":"YOUR_MESSAGE",
>    "time":"2019-11-15T14:35:55.006Z"
>    }
>    ]
>    b) file - all files that you want to upload (file names should match with file names from the 'json_request_part'
> 
> Here is a raw example from Postman ![image](https://user-images.githubusercontent.com/31598109/52042679-d6a00980-254e-11e9-8e42-f49a2d1c9bb0.png)

This API request send by postman, We try to send a image in multiple form data to API request but facing again 
<img width="865" alt="image" src="https://github.com/reportportal/reportportal/assets/50439015/da6a9147-488b-45c6-b2ba-06178ed4151a">
Any one help to upload image in RP

**Comment by HardNorth** [comment]
@pradeep1299 This might be storage issue, did you check API logs?
