### ISSUE TITLE
[BUG] There is no possibility to enter login/password for email settings with RU local

### ISSUE THREAD

**Issue by shaburov** [reportportal/reportportal#564]
**Expected behavior**
<img width="509" alt="image" src="https://user-images.githubusercontent.com/15269131/52205354-daea6080-2887-11e9-856e-c4eec5449307.png">

**Actual behavior**
<img width="589" alt="image" src="https://user-images.githubusercontent.com/15269131/52205489-47fdf600-2888-11e9-9b9f-abcfe7c2a2a4.png">

**Versions:**
 - iOS, Safari, Chrome
 - Version of RP  
Analysis Service: 4.3.0; API Service: 4.3.4; Index Service: 4.2.0; Jira Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.6;

**Comment by evjlobanova** [comment]
Will be available in beta release of version 5

**Comment by DzmitryHumianiuk** [comment]
Email configuration moved under Plugins

![image](https://user-images.githubusercontent.com/11332788/61892653-f0764400-af14-11e9-802c-70352fb1d6a4.png)
