### ISSUE TITLE
On History page show several test runs in one cell.

### ISSUE THREAD

**Issue by grigaman** [reportportal/reportportal#565]
When you marge launches it can contain several runs of the same test. On history page at present it is shown cell of type 'MANY': 
![image](https://user-images.githubusercontent.com/28654063/52222985-0b8cc300-28a5-11e9-92dc-78fe4ddd57d3.png)

I suggest to show several items in one cell instead (one under one), which is link to specified test run (the same item when there is only one run of test, but can have another height (it depend from realization)).

**Comment by evjlobanova** [comment]
@grigaman we have plans to change the logic of this view

**Comment by grigaman** [comment]
@evjlobanova Thanks for reply

**Comment by DzmitryHumianiuk** [comment]
will be addressed with
#25
