### ISSUE TITLE
SAML authentication

### ISSUE THREAD

**Issue by justinhinze** [reportportal/reportportal#566]
Is SAML authentication on the roadmap? A configuration for Okta would be nice to have.

**Comment by DzmitryHumianiuk** [comment]
@justinhinze it is.
working on that already.

**Comment by DzmitryHumianiuk** [comment]
implemented but hidden.
will release with 5.2 (Feb-March 2020)

**Comment by dsoudakov** [comment]
How's the progress on this?

**Comment by evjlobanova** [comment]
Duplicates of #877

**Comment by diogo-mendes-ifood** [comment]
5.2 was released and nothing related to SAML. Any news on that ?

**Comment by DzmitryHumianiuk** [comment]
@diogo-mendes-ifood that was release with updates for clients.
Paid requests shifts our general backlog.

**Comment by diogo-mendes-ifood** [comment]
So that would be for 5.3 probably @DzmitryHumianiuk ? Any ETA ?

**Comment by pabloli84** [comment]
> implemented but hidden.
> will release with 5.2 (Feb-March 2020)

Hi, is there a way to use this hidden functionality in 5.2? Thanks.

**Comment by evjlobanova** [comment]
In version 5.2 - no.
It is compatible only with version 5.0

**Comment by pabloli84** [comment]
> In version 5.2 - no.
> It is compatible only with version 5.0

I see, thanks. Will wait for 5.3. Are there any estimates for 5.3 release?

**Comment by sapna-dentsu** [comment]
It is there, but are there any logs?

**Comment by llamashoes** [comment]
I would love to see some documentation on this as well, specifically what the values for the Single Sign On, Recipient and Destination URLs need to be related to OKTA.

**Comment by sapna-dentsu** [comment]
@llamashoes let me know if this works for you as for me it is not working. I can't see the sign in with Okta on my signup page after upgrade.

**Comment by evjlobanova** [comment]
@llamashoes @sapna-dentsu Documentation is here
We will update it today with explanation video

**Comment by winstondz** [comment]
What's the app name in okta. I can't find rp okta?

**Comment by malmor** [comment]
Any updates on this?

**Comment by unnisathyarajan** [comment]
ReportPortal now has SAML but it can be integrated only with Okta IDP
Any plans for a generic SAML based authentication support? 
I look forward to Keycloak based integration here.

**Comment by evjlobanova** [comment]
We are planning to make integration with Keycloak, but I can not tell you exactly when we do it

**Comment by kirillbilchenko** [comment]
@evjlobanova any plans abut azure sso saml?

**Comment by malmor** [comment]
Do i understand it correctly that at the moment only Octa is supported as a SAML provider and nothing else like MS ADFS would work?

**Comment by DmitryVityuk** [comment]
Any plans to add support of any IDP for SAML?

**Comment by malmor** [comment]
Any updates on this?

**Comment by DzmitryHumianiuk** [comment]
@malmor not much.

**Comment by sama8** [comment]
If relevant -> [SAML Jackson](https://github.com/boxyhq/jackson)

**Comment by defied** [comment]
Almost a year later, any updates?

**Comment by DzmitryHumianiuk** [comment]
@defied no.
are you willing to contribute?

**Comment by jatin-groww** [comment]
Does it support with JumpCloud SAML?

**Comment by DzmitryHumianiuk** [comment]
@jatin-groww no, as for 09/29/2022

**Comment by Rolika4** [comment]
@DzmitryHumianiuk @evjlobanova do you know any worked cases with keycloak?
@unnisathyarajan Did you able to integrate keycloak with SAML plugin report portals?

**Comment by DzmitryHumianiuk** [comment]
@Rolika4 not yet.
But we just made tech spike to transit RP to the OpenID standard, which will make it easy to integrate with keykloak.

**Comment by sannj143** [comment]
Is OIDC integration in reportportal?
