### ISSUE TITLE
Unable to connect BTS with Jira - No Solution !!

### ISSUE THREAD

**Issue by orvilia** [reportportal/reportportal#568]
**Describe the bug**
...

**Expected behavior**
...

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

**Comment by evjlobanova** [comment]
@orvilia have you tried to follow steps descried [here](http://reportportal.io/docs/Issues-with-JIRA)

**Comment by orvilia** [comment]
We have tried...its not working 

1 - We are using Jira cloud version ( Trial Version ). As mentioned we have tried everything, e.g, providing Jira API Token also. Nothing is working.

**Comment by evjlobanova** [comment]
Send me please screenshot of Consul on localhost:8500 and logs of errors in Jira container and API container on the moment of attempt on connection.

**Comment by evjlobanova** [comment]
@orvilia ^^

**Comment by DzmitryHumianiuk** [comment]
closed as no response
