### ISSUE TITLE
The same TC is considered as another entry if name of launch/test suite differs

### ISSUE THREAD

**Issue by JustasM11** [reportportal/reportportal#57]
I have the same TC but in different launches (launch names differ):
launch1---test suite1---test1
launch2---test suite1---test1

I expect that I can see results for test1 for both launch1 and launch2 
Currently I see that test1 from launch1 and test1 from launch2 are considered as different test cases and I don't have aggregated results trend for test1.

The same issue occurs when test1 is placed in different test suites:
launch1---test suite1---test1
launch2---test suite2---test1

I see issue here: 
- I forced to have the same launch name and keep test case exactly in the same suite hierarchy from launch to launch.
- I cannot change name of launch without losing my results trend (currently I use launch names equal to my Jenkins job, so I cannot move test case from one job to another)
- I cannot move test case to another test suite or change hierarchy of my test suites without losing results trend
This can work for already frozen project, but issue here that I need to change my test infrastructure from time from time especially at early stages!

I would prefer that RP uses test case name as unique ID so I can see test case results history over time despite perturbations of test suites/launches.
I would prefer that also there is possibility to filter results for such aggregated trend line: by launch name/tag/suite/time/tag etc.

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 current history request, consider the same position in hierarchy. Same suite, same test class.
this constraint allow as to avoid situation, when this testcase (method) called in other suites. This is much relevant for Data Driven automation.

two sided:
**first:** if we remove constraint - we will get tons of false found items in other suites.
**second** if we have it - trend is valid only for the same hierarchy.

With ElasticEngine we will try to remove those limitations.

also, it can be covered if every single framework will send unique `test case ID`. in this case, it would be much easier to find them and identify them.
But non of frameworks has it out of the box.
in this case integration became much harder, and out-of-the-box you wouldn't have history at all.

>I would prefer that RP uses test case name as unique ID 

once again, it's not relevant for Data Driven approaches, 

>I would prefer that also there is possibility to filter results for such aggregated trend line: by launch name/tag/suite/time/tag etc.

it can be covered with issue https://github.com/reportportal/reportportal/issues/25

**Comment by DzmitryHumianiuk** [comment]
consider as closed,
please re-open for discussion.

required view will be implemented in issue #25

**Comment by JustasM11** [comment]
Still I don't completely agree with you. The issue here is that RP doesn't distinguish between Test Suite, Test Case, Test Step: they are common Test Item. Also there is no such artifact as Test Result.

I agree that Test Step can be used in many Test Cases, and Test Case can be executed with different parameters. But they still remain the same.

There are different possibilities to separate results for such Data Driven tests: using tags for results, adding additional parameter "Input args", explicitly marking such test as Data Driven so results are not merged by default, etc.

**Comment by DzmitryHumianiuk** [comment]
we introduce **UniqueID** in 3.3 for test cases (test items)

This ID can be

1. populated directly on item creation
2. will be generated based on `ProjectName` + `launchName`+`Suites/Parents names`+`testItem Name` + `parameters`

so if you will populated unique ID for test case, it will show history for it at any place.

**Comment by avarabyeu** [comment]
Starting from version 3.3 users are allowed to provide uniqueID by themselves. 
https://github.com/reportportal/agent-java-testNG/blob/24cc7dc8b8351a1de1988fcfd5a53a51128ae09a/src/main/java/com/epam/reportportal/testng/TestNGService.java#L461
