### ISSUE TITLE
UUID for a project changes automatically

### ISSUE THREAD

**Issue by bawarim** [reportportal/reportportal#570]
I created my project in report portal and copied the UUID of that project in reportportal.properties file.
But the issue is after few days UUID of my project is changing automatically, which leads to the execution failure. 
Please let me know how can I stop UUID to change automatically?

**Comment by lilacharviv** [comment]
me too

**Comment by bawarim** [comment]
Hi,
Is there any update on this?

**Comment by evjlobanova** [comment]
@bawarim we are investigating this issue

**Comment by bawarim** [comment]
Cool. Thanks @evjlobanova

**Comment by evjlobanova** [comment]
@bawarim  do you  restart container docker or not?
 if not, Is the base restarted separately or the base can be dropped once in a while?

**Comment by bawarim** [comment]
No. I have not restarted docker and the base image from a long time.

**Comment by DzmitryHumianiuk** [comment]
@bawarim @lilacharviv the only situation, when it can appear:
1. restart of database container, w/o saving of db files
2. smbd regenerate UUID from UI

Do you use default user?
We did you copy UUID from?

**Comment by bawarim** [comment]
@DzmitryHumianiuk  UUID changes for all users which I use, irrespective of their role.
Also database container is not restarted. Please see the below snapshot. 
![image](https://user-images.githubusercontent.com/46487726/53069310-7c68e780-3501-11e9-8bae-30f17b96b60d.png)

But still it changes automatically even I am not changing it through Profile->UUID.

**Comment by DzmitryHumianiuk** [comment]
@bawarim can you explain (screenshot may help), where you take UUID for configuration?

**Comment by bawarim** [comment]
I take UUID from below location.
![image](https://user-images.githubusercontent.com/46487726/53156205-dbebf380-35e4-11e9-9fba-f686411e904b.png)

**Comment by Nolfgk** [comment]
We also have this issue.
We found out that uuid changes automatically only after login with user, so if nobody logins, uuid stays the same (of course we are not pressing "regenerate" button, and do not restart containers. I am not sure what action on the ui triggers this regeneration.
Workaround: use separate account for ui-login and autotests.

**Comment by DzmitryHumianiuk** [comment]
@pbortnik that's critical issue.
take a look within next sprint.

@evjlobanova plz put in next sprint

**Comment by DzmitryHumianiuk** [comment]
@bawarim @lilacharviv @Nolfgk what you build number (api and ui)
you can find it under login form.

**Comment by bawarim** [comment]
@DzmitryHumianiuk Below is the snapshot of build numbers which I am using. 
![image](https://user-images.githubusercontent.com/46487726/53486837-dfcdb900-3aaf-11e9-8f0a-4115ce8ccddf.png)

**Comment by Nolfgk** [comment]
Current version: API Service: 4.3.5; Index Service: 4.2.0; Authorization Service: 4.2.0; Service UI: 4.3.7;

**Comment by DzmitryHumianiuk** [comment]
@bawarim @lilacharviv @Nolfgk do you guys use RP in Chrome Private mode?

**Comment by Nolfgk** [comment]
No, should we?

**Comment by DzmitryHumianiuk** [comment]
No, you should not.

**Comment by bawarim** [comment]
@DzmitryHumianiuk No, we do not use RP in Chrome Private mode.

**Comment by DzmitryHumianiuk** [comment]
taken for for investigation

**Comment by pbortnik** [comment]
@bawarim @Nolfgk
hello guys, could you please provide some information about you authorization flow
do you use either basic or ldap or smth?

**Comment by pbortnik** [comment]
@bawarim  @Nolfgk 
hello
there is no possibility to introduce the issue
we need more information from your side till how rp is deployed and what authorization flow do you use

**Comment by bawarim** [comment]
@pbortnik I am using basic authorization flow, no ldap.

**Comment by DzmitryHumianiuk** [comment]
@bawarim can we jump with you on a call?

**Comment by bawarim** [comment]
@DzmitryHumianiuk  I am not facing this issue no more. The thing which I have noticed is that, if i execute APIs from swagger by login into the report portal. Then it caused UUID to change, else its working fine.
When I have not executed APIs from swagger from long time then my UUID was working fine. 
So is this expected behavior?

**Comment by DzmitryHumianiuk** [comment]
@bawarim no, it's not. It is bug.
UUID should stay the same, all the time.
Only one event can regenerate it, it is `Generate new UUID` at profile page.

But, at least, now we have a step to reproduce - switch to SWAGGER may update UUID.
@DiscoElevator @pbortnik ^

**Comment by DzmitryHumianiuk** [comment]
@bawarim could you plz identify steps to reproduce issue?

**Comment by bawarim** [comment]
@DzmitryHumianiuk I have tried to reproduce it today but didn't succeed. UUID is not changing. 
Not sure why initially UUID was changing.

**Comment by evjlobanova** [comment]
Fixed in 5 version
