### ISSUE TITLE
[BUG] [API] An error occurs if the transmitted launch status conflicts with the auto-calculate status

### ISSUE THREAD

**Issue by shaburov** [reportportal/reportportal#571]
**Describe the bug**
An error when calling to `/{projectName}/launch/{launchId}/finish` with specified status of the completion of the test run: `"status": "PASSED"` if the test run contains test cases with the status `SKIP`.
> При вызове `/{projectName}/launch/{launchId}/finish` и явном указании статуса завершения задачи возникает ошибка, если передан `"status": "PASSED"`, если запуск содержит тесты в статусе `SKIP`. 

**Expected behavior**
- The passed parameter Status of the run completion has higher priority.
- Error does not occur.
- If the status is not present, then auto-calculation of the run status is triggered.
> - В приоритете статус завершения запука переданный **явно**.
> - Ошибки не возникает.
> - Если статус не передан, то срабатывает автовычисление статуса.

**Explanation**
Test cases that use custom defect types, e.g. "Expected implementation", may have run status `SKIP` or `FAIL`, but such statuses should not affect test run result because test cases with status "Expected implementation" were created before the new feature is ready and are not bugs. Hence, test launch result may have status `PASSED`
> При использовании дополнительных типов ошибок, например **ожидается реализация**, проходящие тесты помеченные данным типом могут иметь статус как `SKIP` так и `FAIL`, однако данные статусы не должны влиять на конечный статус запуска, так как тесты написаны до реализации проверяемого функционала и не являются новыми дефектами. А следовательно запуск может иметь статус `PASSED`.

**Versions:**
Analysis Service: 4.3.0; 
API Service: 4.3.4; 
Index Service: 4.2.0; 
Jira Service: 4.3.0; 
Authorization Service: 4.2.0; 
Service UI: 4.3.6;

**Comment by evjlobanova** [comment]
@shaburov in version 4.3 the system works as designed. We are considering to add such function in 5 ver. But now it is under discussion.

**Comment by DzmitryHumianiuk** [comment]
@shaburov if 5.0 we will accept status as received.
and calculate only of status is missing

**Comment by evjlobanova** [comment]
#451
