### ISSUE TITLE
Remove annotation from RP

### ISSUE THREAD

**Issue by lilacharviv** [reportportal/reportportal#572]
The Report portal showing all the class with annotation of my test.
@before class
@before test
@after class
@after test
and they empty, without any printing
Using testng
![image](https://user-images.githubusercontent.com/47180700/52711948-dca8d800-2f9b-11e9-9e17-72c615b711a5.png)

**Comment by evjlobanova** [comment]
@lilacharviv do you have any methods annotated  with before or after in your tests?

**Comment by evjlobanova** [comment]
@pbortnik Could you please look at this issue?

**Comment by lilacharviv** [comment]
> @lilacharviv do you have any methods annotated with before or after in your tests?

we have this methods in our class

**Comment by DzmitryHumianiuk** [comment]
@lilacharviv click this toggle to hide precondition methods.

![image](https://user-images.githubusercontent.com/11332788/55897967-44f5ed80-5bca-11e9-9bb5-cc2f0c5f219c.png)

**Comment by DzmitryHumianiuk** [comment]
@lilacharviv and let me know if we can close this issue.

**Comment by evjlobanova** [comment]
Closed due to no response
