### ISSUE TITLE
[FR] Show custom Welcome info at login page      (aka Добавить возможность вносить приветственную информацию на страницу авторизации)

### ISSUE THREAD

**Issue by shaburov** [reportportal/reportportal#573]
1. there is no possibility to specify information about the instance-organization.
2. there is no way to add welcome information.
Example with TestRail
![image](https://user-images.githubusercontent.com/15269131/52803184-971b0680-3092-11e9-92f6-429ccb13f111.png)

I wrote a slack-bot that gives access to projects, but few people know about it, and would have added to the main page and there would be no problems.iMER with TestRail

**Comment by Kozovskaya** [comment]
All the issues #1991 #631 are linked to one ticket in our backlog and will be taken in consideration when we will take it into implementation.
