### ISSUE TITLE
Login Issues in ReportPortal

### ISSUE THREAD

**Issue by psubrambe** [reportportal/reportportal#574]
An error occurred while connecting to server . After starting up all the services(Please find the below services).All were up and running but i am not able to login.

Recreating reportportal_rally_1         ... done
Recreating reportportal_registry_1      ... done
Recreating reportportal_gateway_1       ... done
Recreating reportportal_jira_1          ... done
Recreating reportportal_ui_1            ... done
Recreating reportportal_mongodb_1       ... done
Recreating reportportal_elasticsearch_1 ... done
Recreating reportportal_uat_1           ... done
Recreating reportportal_api_1           ... done
Recreating reportportal_index_1         ... done
Recreating reportportal_analyzer_1      ... done

**Comment by BeniKeyserman** [comment]
@psubrambe Have you tried extending the memory for the docker?

Go to | Docker -> Preferences -> Advanced | and assign at least 5 GB for the Memory

![docker_memory](https://user-images.githubusercontent.com/21110702/52909612-1af01100-3294-11e9-806a-e5cb37555dfc.png)

**Comment by DzmitryHumianiuk** [comment]
@psubrambe did [it](https://github.com/reportportal/reportportal/issues/574#issuecomment-464424331) help?

**Comment by psubrambe** [comment]
ya it is working
