### ISSUE TITLE
Support for Mongo Server 4.0

### ISSUE THREAD

**Issue by randomsync** [reportportal/reportportal#575]
Does the latest version of report portal support mongo server 4.0? If not, are there plans to support it?

**Comment by evjlobanova** [comment]
@randomsync we are in the end of the migration on PostgreSQL.

**Comment by randomsync** [comment]
thanks @evjlobanova, just to confirm, reportportal will move from mongo as underlying data storage to PostgreSQL? What version of report portal will that be? And I hope there are migration plans being considered.

**Comment by DzmitryHumianiuk** [comment]
@randomsync it will be in version 5.0
**which will be available in April-May 2019.**
follow our twitter for updates: https://twitter.com/reportportal_io

Alone with new version we plan to release migration microservice.
which will handle data migration issues.
