### ISSUE TITLE
Change launch name for suite name - testng 

### ISSUE THREAD

**Issue by lilacharviv** [reportportal/reportportal#578]
We want to change the launch name of properties file on run time.
We have our listener that under **onStart**, and need to get the suite name that exist under **testng.xml** ,but this **onstart** called after launch method..
We want first to read our **testng.xml** and use this suite name for the launch methods.

**Comment by lilacharviv** [comment]
??

**Comment by DzmitryHumianiuk** [comment]
@lilacharviv 
**option 1**
implement small process and bash script, which can read `testng.xml` in advance and generate required info in `reportportal.properties`

**option 2**
I do remember we made few examples and modifications to make it on runtime.
@avarabyeu made them a year ago, 
but i think, you should resolve it another way

**Comment by DzmitryHumianiuk** [comment]
for reference:
https://github.com/reportportal/agent-java-testNG#code-example-how-to-overload-params-in-run-time

@lilacharviv can be close?

**Comment by DzmitryHumianiuk** [comment]
plz re-open new, if still actual
