### ISSUE TITLE
Is it possible to impement tags/filters for test results?

### ISSUE THREAD

**Issue by JustasM11** [reportportal/reportportal#58]
As user I want to be able to filter test results by tags/time/messages in logs/ etc.
For example, the same tests are executed with different parameters so I need to filter out particular results for specific parameters.

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 
what do you mean under `test results`? Is it test case?

You can also use `List view` 
1. by clicking on number in TOTAL column.
2. selecting filter by tag 

Also,
server side support to add tags to any testItem(it means SUITE, TEST, STEP).
the only thing, you need to implement in your agent, which sends results.
![screen shot 2016-12-23 at 17 31 12](https://cloud.githubusercontent.com/assets/11332788/21455978/a329f2e0-c935-11e6-9994-81289e6f6aaf.png)
in Filter panel

**Comment by JustasM11** [comment]
Please see these green items with #1, #2, ..., #9: 
![test_results](https://cloud.githubusercontent.com/assets/12593214/21456112/907b7460-c936-11e6-86df-2476a85a9fce.png)

Are they called test results?
The idea is to be able to filter them by tags, messages in logs, time, etc.

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 we call it `history-line`

basically, it is the statuses of current test case in executions #8, #7..... #1
that means it only releated to this particular test case.

please see https://github.com/reportportal/reportportal/issues/25
is it the same, you are looking for?

**Comment by DzmitryHumianiuk** [comment]
close for now.
re-open if it did not answer your question
