### ISSUE TITLE
Update user e-mail for AD users

### ISSUE THREAD

**Issue by lifemanship** [reportportal/reportportal#581]
There is a problem with updating e-mail for AD users.
The first time when AD user logins to RP its e-mail will be obtained from AD and then user can not change it by the hands(it is OK). But if we will change user's e-mail in AD settings, nevertheless RP still have an old e-mail of the user.

Is there any way to update AD users's e-mail?

Current version: API Service: 4.2.1; Index Service: 4.2.0; Authorization Service: 4.2.0; Service UI: 4.2.2;

**Comment by DzmitryHumianiuk** [comment]
@lifemanship most likely no.

What's the reason to change email for AD user?
Will it work you you just assign new user (with new email) to the same project?

**Comment by lifemanship** [comment]
The reason is for example migration to another e-mail server, therefore we need to change all user's e-mails addresses

**Comment by DzmitryHumianiuk** [comment]
@lifemanship then it just should be done manually and just once.

My vision, it is unlikely that you will do this periodically or often enough. This is clearly a one-time event, extremely rare.

**Resolution:** rejected.
**Solution:** re-assign all users from new AD in manual or semi-automatic way.

**Comment by lifemanship** [comment]
OK, but in the version 4.2.1 i am unable change e-mail from UI at all.
Could you please unlock in future version ability to change e-mail address even if user is member of AD?

**Comment by DzmitryHumianiuk** [comment]
@lifemanship that might be helpful.
plz create new feature request.
