### ISSUE TITLE
unable to login in report portal once we depolyed in Docker 

### ISSUE THREAD

**Issue by psubrambe** [reportportal/reportportal#582]
**Describe the bug**
...

**Expected behavior**
...

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

**Comment by harsh976** [comment]
Same with me please update here in case find any solution
![screenshot 2019-03-01 at 4 15 36 pm](https://user-images.githubusercontent.com/29836005/53633461-88f5ea00-3c3d-11e9-81ea-fbaf776bd1cb.png)

**Comment by DzmitryHumianiuk** [comment]
@psubrambe we need some details.
since we can't magically define the issue you have.

**Comment by DzmitryHumianiuk** [comment]
@harsh976 according to your screenshot: 
you don't have any micro-service running

Try to:
- restart docker
- clean consul cache by deleting `data/consul` and restart

here how it should look like:
![image](https://user-images.githubusercontent.com/11332788/54379523-9b8b0d00-469a-11e9-98d9-80f7a90e9854.png)

**Comment by psubrambe** [comment]
it is working now .We need to have more memory allocated to docker in system
