### ISSUE TITLE
Create filter on run time

### ISSUE THREAD

**Issue by lilacharviv** [reportportal/reportportal#585]
There is a way to create new filter on run time? by api ?(for build number )

**Comment by DzmitryHumianiuk** [comment]
@lilacharviv check the API section in user menu (on the top right).

`user-filter-controller`
`POST` `/{projectName}/filter`

example from demo instance at http://web.demo.reportportal.io
```bash
curl 'http://web.demo.reportportal.io/api/v1/default_personal/filter'   -H 'Authorization: bearer 4f73871b-e477-4f49-b1bd-805b24201fe0'  --data-binary '{"elements":[{"name":"NAAAME","entities":[{"filtering_field":"tags","condition":"has","value":"build:3.0.1.10"}],"share":"","selection_parameters":{"orders":[{"is_asc":false,"sorting_column":"start_time"},{"is_asc":false,"sorting_column":"number"}]},"type":"launch"}]}' 
```

Tip:
1. Open Launches view in ReportPortal.
2. Create filter
3. Open browser Network tab
4. click save filter back in RP
5. check network tab for request to Filter endpoint

![image](https://user-images.githubusercontent.com/11332788/54140597-0935ff80-4435-11e9-8567-c814b8508ebd.png)

**Comment by DzmitryHumianiuk** [comment]
close for now.
re-open if still actual
