### ISSUE TITLE
Add the ability to go to a launch from Non-passed test-cases trend chart

### ISSUE THREAD

**Issue by itzikb-redhat** [reportportal/reportportal#586]
**Describe the solution you'd like**
...
I would like to be able to switch to a specific launch when choosing clicking on a specific launch from the mentioned widget

**Is your feature request related to a problem? Please describe.**
...

![image](https://user-images.githubusercontent.com/11332788/54140476-be1bec80-4434-11e9-98b0-b4883b4f074b.png)

**Comment by DzmitryHumianiuk** [comment]
valid.
can be taken into implementation in 5.x versions

**Comment by evjlobanova** [comment]
Added in version 5.1

**Comment by AmrWatad** [comment]
regarding to *Passing rate per filter 
its on test level ? 
or its just on launches level
@evjlobanova

**Comment by evjlobanova** [comment]
On the test level
