### ISSUE TITLE
Log Parser to categorize report portal failures

### ISSUE THREAD

**Issue by SagarVasekarRepo** [reportportal/reportportal#589]
Hi Guys,
 
I’m new to Report Portal and my team is looking for some way we can parse the report portal logs and categorize the results as per the failures.
 
I just wanted to know if there’s any existing parser available that does the same thing or is there any API that we can leverage to build a parse. Could you please let me know this?

Our goal is to categorize the failures. We are aware of auto-analysis feature of Report Portal but that will need some manual work before we start using it right?
 
Thanks,
Sagar

**Comment by DzmitryHumianiuk** [comment]
@SagarVasekarRepo 

>We are aware of auto-analysis feature of Report Portal but that will need some manual work before we start using it right?

Yes. You need to give some data, which can be used by ML for further analysis.
Make at least 4-5 manual categorizations of all fails in launches.

As for the custom implementation of categorization, you can implement own services, with own rules.
Also, during deployment with docker, you can set priority for it, so it can be configured to be started before regular AA, or after it.

Here is example:
https://github.com/reportportal/example-custom-analyzer
