### ISSUE TITLE
Add link of build to launches

### ISSUE THREAD

**Issue by szikszail** [reportportal/reportportal#59]
Hi,

It would be a really great feature if the link of the build - which produced that test execution - could be set to launches when we start a launch with it's API call (like description).
This link would be shown on the list of launches, like description and would be clickable.

Thank you in advance.

**Comment by DzmitryHumianiuk** [comment]
Hi,

we will consider to implement it as a markdown support for description

**Comment by szikszail** [comment]
Hi @DzmitryHumianiuk 

Thank you! That's even better than I suggested. I cannot wait for it :)

**Comment by DzmitryHumianiuk** [comment]
implemented in 3.0
