### ISSUE TITLE
404 Page not found when accessing from browser

### ISSUE THREAD

**Issue by bkilada** [reportportal/reportportal#590]
Hello,

First of all, ReportPortal looks awesome, and I can't wait to get an instance up an running. Can't beat free!

Yesterday I ran through the steps in the ReportPortal documentation for setting up the ReportPortal server. Unfortunately, even though I've tried on two PCs on two different networks, I cannot get past a "404 Page Not Found" error when trying to access the server from Chrome.

These are the steps I used (can you tell I'm a SQA engineer?). Note that I am new to docker, so pardon any obvious blunders.

1. Install Docker for Windows on Windows 10 Pro (also tried Docker Toolbox on my Windows 10 Home laptop).
2. Increase Docker memory allocation to 4 GB.
3. Cmd line execute "curl https://raw.githubusercontent.com/reportportal/reportportal/master/docker-compose.yml -o docker-compose.yml"
4. Edit the yml file, line 69 to be "      - "9090:8080" # HTTP exposed" since I have a Jenkins server running on 8080.
5. CMD line execute: "docker-compose -p reportportal up -d --force-recreate"

Result:
Although no errors occurred and all containers appear to be running normally, I get a 404 Page not found error when I enter http://localhost:9090 into Chrome.

Note: I've tried exposing the HTTP Administration page by uncommenting line 70 of the yml file and I can successfully access the traefik administration page using localhost:8081 from Chrome, though it appears to be devoid of content (just a few menu type buttons at the top of the page).

Any tips?

**Comment by mcafeerun** [comment]
See if this helps https://github.com/reportportal/reportportal/issues/591

Even I have same situation.. I could able to hack 😀

**Comment by DzmitryHumianiuk** [comment]
@bkilada did #591 help you?

**Comment by goodbomb** [comment]
I'm running into the same issue on my end. Seems to be an issue with the elasticsearch and registry steps during the docker-compose process. They never complete to a "done" state and I end up with a 404 for http://localhost:8080/ui or http://localhost:4444/ui .

![image](https://user-images.githubusercontent.com/4674973/55108227-58646d00-5090-11e9-970f-b7fd4b192bb5.png)

**Comment by goodbomb** [comment]
Disregard. I upped my memory usage in docker, then restarted it and that seemed to fix my issue.

**Comment by bkilada** [comment]
> @bkilada did #591 help you?

Yes...well, sort of. Using "expose:     - "8080" did work, but I also had to use the IP address of the docker machine instead of localhost (the IP that's displayed when you first run docker quickstart). It seems that Docker Toolbox exposes reportportal to a docker-machine which has a unique IP, while Docker for Windows uses localhost? And yes, @goodbomb, I also had issues with logging in until I increased the RAM to 4GB.

Anyway, I really appreciate the tip @mcafeerun!

I also got to the sign in page on my work PC which is using Docker for Windows, but I restarted reportportal and now I'm getting 404 page not found again. Need to investigate...

**Comment by DzmitryHumianiuk** [comment]
@bkilada did it work, finally?

**Comment by bkilada** [comment]
@DzmitryHumianiuk yes not sure what happened but it's working now! Thanks for the help everyone.

**Comment by DzmitryHumianiuk** [comment]
Usually it need some time to bootstrap all services.
Sometime it is 1 min. Sometimes up to 15 mins

**Comment by swapnilbargal1** [comment]
Boosted my memory storage and changes to windows containers and it worked for me.

![image](https://user-images.githubusercontent.com/20087944/57120908-fcc58780-6d91-11e9-8712-75a9a0a6c243.png)

**Comment by pligor** [comment]
"I upped my memory usage in docker". How one can do this exactly for the docker compose yml file of report portal ?

**Comment by DzmitryHumianiuk** [comment]
@pligor, it's nothing to do it `docker-compose.yml` file.
you need to increase it for your docker-VM.

https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container

**Comment by vikashkumar-discovery** [comment]
Please share yml file. I am still getting error

**Comment by DzmitryHumianiuk** [comment]
@vikashkumar-discovery https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container
