### ISSUE TITLE
[FR] Change user email via profile

### ISSUE THREAD

**Issue by lifemanship** [reportportal/reportportal#592]
The RP does not automatically update user settings for domain user's, hence I want to be able change e-mail from UI. Current behavior of RP does not allow users to change their e-mail if they come from AD.

**Comment by MaryiaRymarchyk** [comment]
Hello @lifemanship, could you please check if the issue still relevant?
I've checked it and see that User's email is updated automatically if it has been updated in Active directory/LDAP.
