### ISSUE TITLE
Is it possible to install reportportal using docker and windows containers instead of linux?

### ISSUE THREAD

**Issue by heilwood** [reportportal/reportportal#593]
Is it possible to install reportportal using docker and windows containers instead of linux containers?

**Comment by DzmitryHumianiuk** [comment]
@heilwood theoretically it is possible.
Steps completely the same.
At least, Docker for windows claims full support and stable version.

Nevertheless, we still receive a lot of issues and question, regarding installation on win docker toolbox.
And we do not test it on docker for win.

After version 5, we will try to find work around for deployment on win.
