### ISSUE TITLE
How to remove Console Debug msg

### ISSUE THREAD

**Issue by lilacharviv** [reportportal/reportportal#594]
How to remove of debug msg that was added from report portal:
![image](https://user-images.githubusercontent.com/47180700/54983646-eddefe80-4fb5-11e9-9aed-42217e2ac473.png)

**Comment by DzmitryHumianiuk** [comment]
@lilacharviv where do you see it?
in test automation logs?

then in logger config define the root level.

https://github.com/reportportal/example-java-TestNG/blob/master/log4j/src/main/resources/log4j2.xml#L14

**Comment by lilacharviv** [comment]
hi,
in the automation log
we have already  the logger u add
