### ISSUE TITLE
Support for Android Test

### ISSUE THREAD

**Issue by spartanglady** [reportportal/reportportal#595]
**Describe the solution you'd like**
... Is there any planned support for a Android Client

**Is your feature request related to a problem? Please describe.**
... Just curious if anyone is using report portal with android tests like espresso or robo electric

**Comment by DzmitryHumianiuk** [comment]
@spartanglady this definitely should be in our backlog.

And i've asked in [SLACK](https://reportportal-slack-auto.herokuapp.com/) chat, if any.

**Comment by spartanglady** [comment]
Thanks.. Lets continue this conversation in slack

**Comment by DzmitryHumianiuk** [comment]
P.S.
from comments in Slack.

`Android studio uses a version of jUnit4 for android test. I think whoever worked on the original Junit client should be able to figure it out easily.`
