### ISSUE TITLE
Wrong statistics is displayed on run level

### ISSUE THREAD

**Issue by MrHobbsT** [reportportal/reportportal#597]
Given:
Cucumber-jvm agent, test run contains merged results.
Expected behavior:
Number of Product Bug items in Run Summary matches number of items with status "Product Bug"
Actual:
Summary: PB qty = 705
Items in list with PB status: 703

![image](https://user-images.githubusercontent.com/11572242/55068834-c78f9080-5093-11e9-97e6-2521c50ab427.png)
![image](https://user-images.githubusercontent.com/11572242/55068877-da09ca00-5093-11e9-9d27-eef8735154c4.png)

Issue is quite hard to catch, not reproducible for 100% of runs

**Comment by DzmitryHumianiuk** [comment]
@MrHobbsT how do you filter these 705 items?
what was in filter?

This issue will be addressed in 5.0

**Comment by MrHobbsT** [comment]
Status: Passed, Method type: Test
The same result for 
Status: Passed

**Comment by Oldsouldier** [comment]
Seeing similar wrong counts in #624 after changing defect type , though it's only after the request times out.

**Comment by DzmitryHumianiuk** [comment]
@MrHobbsT @Oldsouldier refactored and supposed to be fixed.
fix will be in `v5 RC` (aka v5 beta)

if still occuries, please open new in next milestone
https://github.com/reportportal/reportportal/milestone/24
