### ISSUE TITLE
Provide ability to reload .properties on runtime

### ISSUE THREAD

**Issue by iKozzz** [reportportal/reportportal#6]
I would like to update listener with new properties values before tests are executed.

Basically i need to create `reportportal.properties` according to starting suite and then update ReportPortalTestNGListener (in my case) with new information.
Currently this is unable because listener will initialize itself on TestNG framework start.

I know that i can pass environment variables thru command line, but it's not the case for me.
My idea is to keep all configuration inside my framework and require only necessary command line parameters. For example `-Dclient=SomeClientID` is a keyword to setup all the required data for suite.

**Comment by avarabyeu** [comment]
@iKozzz we can provide method for completely re-initialize guice app context. Will it work for you?

**Comment by iKozzz** [comment]
Yeah, we can run this method on @BeforeSomething

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu up?

**Comment by avarabyeu** [comment]
Added in 3.0. Additional details on making this will be provided in documentation

**Comment by Lalesia** [comment]
Hi everyone! 
Where I can find in documetation this approach? 
I really need it right now for project with a lot of modules and projects, so it would be great to change property file in runtime. Thanks

**Comment by avarabyeu** [comment]
@Lalesia properties are being loaded from here: [PropertiesLoader](https://github.com/reportportal/client-java/blob/master/src/main/java/com/epam/reportportal/utils/properties/PropertiesLoader.java)

If i'd like to override properties you can use jvm\env vars or replace\override it on the code level in [Configuration Module](https://github.com/reportportal/client-java/blob/master/src/main/java/com/epam/reportportal/guice/ConfigurationModule.java)

Example of extending TestNG Listener can be [found here](https://github.com/reportportal/example-java-TestNG/blob/master/logback/src/main/java/com/epam/rp/tests/extension/ParameterizedTest.java)

**Comment by iKozzz** [comment]
Way too odd. I was expecting to see something like
PropertiesLoader.add("my_custom_parts.properties");
or
PropertiesLoader.reload();

usecase1 - I'm using ReportPortalTestNGListener and I want too change Launch name prior to test start but after framework initialization. 
usecase2 - I'm using ReportPortalTestNGListener and I want too add more tags after framework initialization

**Comment by KunalShokeen432** [comment]
@DzmitryHumianiuk I have written below snippet in 'BeforeSuite' for setting launch name in reportporttal.properties.
PropertiesConfiguration conf = new PropertiesConfiguration("src/main/resources/reportportal.properties");
			conf.setProperty("rp.launch", "Kunal");
			conf.save();
It is set successfully but after Reportportal listener is initialized in suite.xml file.
Is there a way to set it prior Reportportal listener initialization ?

**Comment by DzmitryHumianiuk** [comment]
@iKozzz can you comment on above as well?

**Comment by mohdsgithub** [comment]
You can achieve using Environment variables. Its working fine for me

**Comment by mohdsgithub** [comment]
> 
> 
> @DzmitryHumianiuk I have written below snippet in 'BeforeSuite' for setting launch name in reportporttal.properties.
> PropertiesConfiguration conf = new PropertiesConfiguration("src/main/resources/reportportal.properties");
> conf.setProperty("rp.launch", "Kunal");
> conf.save();
> It is set successfully but after Reportportal listener is initialized in suite.xml file.
> Is there a way to set it prior Reportportal listener initialization ?

Create environment variables or pass the value from command line. I am passing it from maven command:
mvn -U -fn -Dsurefire.suiteXmlFiles=D:\testng\webdriver\singleTest.xml **-Drp.launch=MOH** **-Drp.enable=true** clean test

**Comment by KunalShokeen432** [comment]
@mohdsgithub Great thanks it works for me too. As it seems, it will override the values present in reportportal.properties if provided via command line ? :)

**Comment by iKozzz** [comment]
we came up with custom runner so we can play with properties prior to ReportPortal.listener start

**Comment by mohdshahab** [comment]
> 
> 
> @mohdsgithub Great thanks it works for me too. As it seems, it will override the values present in reportportal.properties if provided via command line ? :)
awesome!!
Also I stored 'rp.enable' parameter value passed from command line. This will enable us to decide whether to send screen shot attachment to RP or not in case of test failure

**Comment by KunalShokeen432** [comment]
Can anyone of you also look at the issue tagged with RP usage with Selenium Grid.

**Comment by mohdshahab** [comment]
I am using RP with my selenium testng framework.
What exactly r u looking for

**Comment by acdurai** [comment]
Hi @DzmitryHumianiuk , 
I'm using selenium with JUNIT 4.12 framework, I would like to update the reportportal.properties file before the Reportportal listener is getting initialized .
Please help  me on this

**Comment by DzmitryHumianiuk** [comment]
@acdurai join our community in slack
https://reportportal-slack-auto.herokuapp.com/

and ask in #agent_java channel for help

**Comment by acdurai** [comment]
@DzmitryHumianiuk  thank you so much
