### ISSUE TITLE
Add possibility to add JIRA links to test through API

### ISSUE THREAD

**Issue by szikszail** [reportportal/reportportal#60]
Hi,

I would like to request a feature or API call, with we can add JIRA issue links to test items, like we can do with the Load Bug button.
In many case we mark our test cases with tags that indicates which JIRA item is about that exact test cases. Although these JIRA items are not necessary Bugs, we would like to show this information in Report Portal itself, automatically.

Does Report Portal has this feature already? If not, is it possible to add this feature?

Thank you in advance.

**Comment by szikszail** [comment]
Is the PUT /{projectName}/item/issue/add API call specifically for this?

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu

**Comment by DzmitryHumianiuk** [comment]
@szikszail It's correct!
