### ISSUE TITLE
[FR] User Experience improvements (aka Повышение удобства работы в UI)

### ISSUE THREAD

**Issue by ailjushkin** [reportportal/reportportal#601]
_See [translation below](https://github.com/reportportal/reportportal/issues/601#issuecomment-480377490)_

**Проблема**

Не удобный процесс разбора багов.

**Критерии удобства**

- Минимум действий с кнопками мыши
- Минимум работы с колесом мыши
- Минимум обновлений страницы
- Минимум переходов между страницами

**Выгоды**

- Счастливые пользователи, повышение количества потребителей Report Portal

**Предлагаемое решение**

1. Взять **реальных** пользователей. Составить топ 10 **реальных** процессов использования.
2. Выполнить запись этих юзкейсов. Записать информацию по каждому из них рядом с критерием удобства, обозначенным выше. 
3. Спросить про то, что не устраивает в текущем интерфейсе.
4. Выработать рекомендации по тому, как наиболее оптимально должен быть организован разбор багов.

**Пример**

- Использование авторазметки багов в процессе разбора ланча.

1. Открыть ланч, нажать на to investiagate.
2. Разметить падение теста
3. Вернуться к списку ланчей
4. Найти текущий ланч
5. Нажать кнопку меню "analysis"
6. Выбрать в окне опцию for all with same name и нажать кнопку analyse
7. Нажимать кнопку Refresh, пока анализ не остановится
8. Нажать на To Investiagate
9. Вновь выполнить пункт 1-8

Какие тут проблемы:

- Минимум действий с кнопками мыши
1. Авто Refresh статуса анализатора не работает - надо обновлять страницу руками.
2. Чтобы включить анализ, надо кликнуть несколько раз в нескольких окнах - хотелось бы режим одной кнопки и режим "с изменениями". Т.е. иметь две кнопки - одну нажал и пошел размечать, вторую - открыл диалоговое окно кастомных настроек (как сейчас выводится) и выполнить иной анализ.

- Минимум работы с колесом мыши
1. Разметка падения теста обновляет страницу, скроллинг скидывается наверх. Если ты был в середине страницы, то надо скролить обратно на то же место. Надо включить асинхронный режим обновления статуса одного айтема списка, весь список обновлять ради одного падения - это пипец.

- Минимум обновлений страницы
1. В идеале надо убрать кнопку refresh у списка ланчей, все должно обрабатываться асинхронно, налету, через очередь событий.

- Минимум переходов между страницами
1. Для того, чтобы разметить падения, надо возвращаться в общий список ланчей - нельзя исключить дублирующие to investigate изнутри ланча.

**Comment by bkilada** [comment]
Here's a Bing translation I reformatted to match the above.

**Problem**

Not a convenient process of parsing bugs.

**Convenience Criteria**

- Minimum Actions with mouse buttons
- Minimum work with mouse wheel
- Minimum page Updates
- Minimum page Transitions

**Benefits**

- Happy users, increasing the number of Report Portal users

**Proposed Solution**

1. Take real users. Make up the top 10 real-world usage processes.
2. Record these entries. Write down the information for each of them next to the convenience criterion indicated above.
3. Ask about something that is not satisfied in the current interface.
4. Develop recommendations on how to best organize the analysis of bugs.

**Example**

- The Use of Automarkup bugs in the process of parsing launch.

1. Open launch, click on to Investigate.
2. Mark Down the Test drop
3. Back to the list of launches
4. Find Current launch
5. Click the "Analysis " menu button
6. Select the option for all with same name in the window and press the Analyse button
7. Press the Refresh button until the analysis stops
8. Click on to Investigate
9. Re-Implement paragraph 1-8

What are the problems here:

- Minimum Actions with mouse buttons

1. Auto Refresh Status Analyzer does not work-you need to update the page with your hands.
2. To Enable analysis, it is necessary to click several times in several Windows-I would like the mode of one button and the mode  "with Changes ". IE have two buttons-one clicked and went to mark, the second-opened the dialog box custom settings (as it is now displayed) and perform a different analysis.

- Minimum work with mouse wheel

1. Marking the drop of the test refreshes the page, scrolling is dropped to the top. If you were in the middle of the page, you have to scroll back to the same place. It is Necessary to enable the asynchronous mode of updating the status of one list, the whole list to update for one fall is a kick.

- Minimum page Updates

1. Ideally, you should remove the Refresh button On the list of launches, everything should be handled asynchronously, on the fly, through the event queue.

- Minimum page Transitions

1. To Mark Downs, it is necessary to return to the general list of launches-it is impossible to exclude duplicating to investigate from inside launch.

**Comment by DzmitryHumianiuk** [comment]
@ailjushkin we have allocated 2 UX Designers for user experience improvement.
We call this version `6.0`, and designers are conducting interviews with users for at least 2 months already.

We will consider your request as well.

**Comment by evjlobanova** [comment]
In version 5.0 we added a possibility to see a grouped TI by failure reasons.
![image](https://user-images.githubusercontent.com/30413511/77937539-27c79c80-72bd-11ea-8ebf-31f470dd749f.png)


There are 3 options for search:

For the current launch, The system is looking for similar items through the one launch. For using this feature:
Click on the filter on All launches view
click on To investigate items
open a Defect editor modal
choose For the current launch in the drop-down
https://youtu.be/O5cBESXX0l0

For the launches with the same name, The system is looking for similar items through the 10 last launches with the same name. For using this feature:
Click on the filter on All launches view
click on To investigate items
open a Defect editor modal
choose For the launches with the same name in the drop-down
https://youtu.be/q7YRSvAZU18

For the applied filter
The system is looking for similar items through the 10 last launches from the applied filter. For using this feature:

Click on the filter on All launches view
click on To investigate items
open a Defect editor modal
choose For the applied filter in the drop-down
https://youtu.be/PZSfQRsNDrM

The function can be used only for items that belong to the finished launch. The number of logs lines are using for analysis, a user can configure on Project Settings > Analysis.

Available in version 5.0

I closed this issue, but feel free to reopen it if it doesn`t solve your problems.
