### ISSUE TITLE
Analysis doesn't work 

### ISSUE THREAD

**Issue by lilacharviv** [reportportal/reportportal#602]
I set DEFECT TYPE for same failure with the same name,
after choosing "Analysis" from menu it seem to loading but nothing happens, i try some option form the pop up and still nothing changed.
if need more details please update and i will attach

![image](https://user-images.githubusercontent.com/47180700/55328622-774e6f00-5495-11e9-89a0-1bc284356798.png)

![image](https://user-images.githubusercontent.com/47180700/55328735-bc72a100-5495-11e9-8a8d-c1d2bbe6b049.png)

**Comment by DzmitryHumianiuk** [comment]
@lilacharviv AA consider `ERROR` type of logs for analysis.
which is RED colored at test case logs level.

it should also have meaningful information, in order to have enough data for analysis.

can you show how your error log looks like?

**Comment by evjlobanova** [comment]
Closed due to no response
