### ISSUE TITLE
Project name divided to multiple words after dot

### ISSUE THREAD

**Issue by heilwood** [reportportal/reportportal#604]
**Describe the bug**
My project name in solution is "My.Project.Name" (visual studio c#), reportportal reading each word after dot as separate breadcrumb in launches

**Expected behavior**
...
Project name should not be divided to multiple words.

**Screenshots**

![image](https://user-images.githubusercontent.com/27227165/55383424-d01f1580-5530-11e9-92c4-dd9227699933.png)

**Versions:**
 - Ubuntu, browser Opera.
 - Version of RPLogin:
Current version: API Service: 4.3.4; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.6;

**Comment by nvborisenko** [comment]
@heilwood What agent is used to report results?

**Comment by heilwood** [comment]
@nvborisenko VSTest

**Comment by nvborisenko** [comment]
Your default namespace is `Horizon.RM.Automation`, considering it as "root" namespace. **BUT** you may create a new test in `Horizon.RM` namespace, or in `Horizon`, or even in `ABC`. Agent cannot build the tree of namespaces in advance. What runner knows: test passed and fully qualified name was `A.B.C.Test1`, then agent tries to create a tree on RP server. I don't see ways how to support "root" namespaces automatically, only if user provides "root" namespace explicitly (via config).

**Comment by 501NotImplemented** [comment]
Same with NUnit agent. Quite annoying behavior, especially if there's a lot of suites in the hierarchy.

**Comment by nvborisenko** [comment]
No way for NUnit :( See at your *.xml report, report represents a hierarchy of tests by namespaces. Agent knows the same what we see in xml. Any thoughts are appreciated.

**Comment by DzmitryHumianiuk** [comment]
@heilwood @nvborisenko can we close it?

**Comment by nvborisenko** [comment]
Let's leave it as opened. There is a way how to resolve this issue, need choose better one and implement it.

**Comment by nvborisenko** [comment]
Resolved in ReportPortal.NUnit [3.7.1](https://github.com/reportportal/agent-net-nunit/releases/tag/3.7.1). The same is going to for VsTest as well.

**Comment by nvborisenko** [comment]
Resolved in ReportPortal.VSTest.TestLogger [2.0.4](https://github.com/reportportal/agent-net-vstest/releases/tag/2.0.4).
