### ISSUE TITLE
Auto Analysis - not analyze 

### ISSUE THREAD

**Issue by lilacharviv** [reportportal/reportportal#605]
1. Investigate launch cloud#59 
2. In launch cloud#60 (with the same failed) i select : Analysis from menu
3.In "Analyse Launches" pop up select all option...i tried all
3. The launch in marked as red "Analysis" but not stopped and after refresh nothing changed, just the flag "Analysis" disappear

**Comment by DzmitryHumianiuk** [comment]
@lilacharviv check your `service-analyzer` and `elastic` services are running in docker
```shell
>$ docker ps -a
```

The sign on not running containers: 
- buttons for Generate Index and Delete Index disabled in Project Settings > Auto-Analysis
- under login button you do see Service Analyzer listed

**Comment by lilacharviv** [comment]
I checked and the buttons are disabled 
see in my docker the services please, if need to run another service can u write me the command?

`admin@ubuntu9:~$ docker ps -a
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS              PORTS                                                                      NAMES
7aa1b0af7d2c        reportportal/service-authorization:4.2.0                  "/start.sh"              8 weeks ago         Up 3 weeks          8080/tcp                                                                   reportportal_uat_1
e7f75fb3622a        reportportal/service-api:4.3.4                            "/start.sh"              8 weeks ago         Up 3 weeks          8080/tcp                                                                   reportportal_api_1
bd1444e276e8        reportportal/service-index:4.2.0                          "/service-index"         8 weeks ago         Up 3 weeks          8080/tcp                                                                   reportportal_index_1
43dc81824473        reportportal/service-analyzer:4.3.0                       "/service-analyzer"      8 weeks ago         Up 3 weeks          8080/tcp                                                                   reportportal_analyzer_1
d6d46d618d35        reportportal/service-jira:4.3.0                           "/start.sh"              8 weeks ago         Up 3 weeks          8080/tcp                                                                   reportportal_jira_1
c53e98c83253        reportportal/service-ui:4.3.6                             "/service-ui"            8 weeks ago         Up 3 weeks          8080/tcp                                                                   reportportal_ui_1
843094e4ed7d        docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1   "/usr/local/bin/dock…"   8 weeks ago         Up 6 seconds        9200/tcp, 9300/tcp                                                         reportportal_elasticsearch_1
be8c94f1aedf        mongo:3.4                                                 "docker-entrypoint.s…"   8 weeks ago         Up 3 weeks          27017/tcp                                                                  reportportal_mongodb_1
7f31c3420edb        reportportal/service-rally:4.3.0                          "/start.sh"              8 weeks ago         Up 3 weeks          8080/tcp                                                                   reportportal_rally_1
9f17bea758fb        traefik:1.6.6                                             "/traefik --consulca…"   8 weeks ago         Up 3 weeks          80/tcp, 0.0.0.0:8080->8080/tcp                                             reportportal_gateway_1
e3f6601c0175        consul:1.0.6                                              "docker-entrypoint.s…"   8 weeks ago         Up 3 weeks          8300-8302/tcp, 8301-8302/udp, 8600/tcp, 8600/udp, 0.0.0.0:8500->8500/tcp   reportportal_registry_1`

**Comment by DzmitryHumianiuk** [comment]
@lilacharviv according to screenshot, your elastic restarted 6 seconds ago.

plz follow [these steps](http://reportportal.io/docs/Issues-with-Analyzer:)

**Comment by evjlobanova** [comment]
@lilacharviv do you still have a problems?

**Comment by DzmitryHumianiuk** [comment]
no response.
closed

**Comment by Dhams-1** [comment]
@evjlobanova @DzmitryHumianiuk I am very new to reportportal and  I am facing issue with auto analysis. seems not to work.
I have all the setting in place
![image](https://user-images.githubusercontent.com/60965197/79837910-75ae5c80-83b2-11ea-8a7f-9ad68fd49673.png)

both service analyser and elastic service are running. I also started the auto analysis in reportport user interface then generated the index and got an email saying
"The index has been generated successfully.
You can start to use Auto-Analyzer on your project. 
ElasticSearch Index contains 440 record(s) now. "

still reportportal is not doing any autoanalysis or when start manual analysis even then it doesn't work. Kindly let me know if I am missing something or how to solve the same.

**Comment by DzmitryHumianiuk** [comment]
@Dhams-1 first, upgrade it to 5.1

and to you have any ERROR logs in analyzed test cases?

**Comment by troyhugs** [comment]
![image](https://user-images.githubusercontent.com/17424203/81551808-1683ac80-93a0-11ea-91f8-628937160f8a.png)
I have the same issue the autoAnalysis is not working... and the screenshot says the elasticsearch is restarting... always

**Comment by DzmitryHumianiuk** [comment]
@troyhugs 
https://github.com/reportportal/reportportal/issues/605#issuecomment-481756359
