### ISSUE TITLE
Make links clickable in test logs

### ISSUE THREAD

**Issue by heilwood** [reportportal/reportportal#606]
**Describe the solution you'd like**
Would like to be able click on links inside test logs which are started with http://, https://, file://

Now its not clickable:

![image](https://user-images.githubusercontent.com/27227165/55700984-2fba6c80-59da-11e9-884c-3484475bce3a.png)

**Is your feature request related to a problem? Please describe.**
Just for usability, don't like to copy links :(

**Comment by Invictum** [comment]
@heilwood 
You may emit logs with markdown enabled flag to achieve it.
```
logger.info("!!!MARKDOWN_MODE!!![link](https://example.org)")
```

**Comment by DzmitryHumianiuk** [comment]
@heilwood @Invictum in version 5 you just can send it as Markdown, and it will work as a charm.

`!!!MARKDOWN_MODE!!!` will be deprecated.
