### ISSUE TITLE
Unable to deserialize content

### ISSUE THREAD

**Issue by borbamartin** [reportportal/reportportal#607]
Hey there.

I'm getting the following errors:

`
io.reactivex.exceptions.OnErrorNotImplementedException: Unable to deserialize content
`

`
Caused by: com.epam.restendpoint.http.exception.SerializerException: Unable to deserialize content
`

`Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "number" (class com.epam.ta.reportportal.ws.model.EntryCreatedRS), not marked as ignorable (one known property: "id"])
 at [Source: [B@3207abfa; line: 1, column: 12] (through reference chain: com.epam.ta.reportportal.ws.model.EntryCreatedRS["number"])
`

@DzmitryHumianiuk, I tried downgrading as per #535 but it did not help, I'm still getting the error.
I also reviewed the answer suggesting it was being caused by a user trying to work on a project which it does not have access, but it is not my case, I own the project and I'm sending the same credentials, and the launch is being created, but right after creating it, it throws that error.

I'm using Cucumber 4 + TestNG with ReportPortalTestNGListener as annotation in the runner file.

Any ideas?
Thanks in advance!

**Comment by DzmitryHumianiuk** [comment]
@borbamartin did you use it from here?
https://github.com/reportportal/agent-java-cucumber4

**Comment by borbamartin** [comment]
No, @DzmitryHumianiuk, I followed the instructions at https://github.com/reportportal/agent-java-cucumber. What version of that dependency should I use?

Thanks for the quick response, too!

**Comment by DzmitryHumianiuk** [comment]
```xml
<dependency>
  <groupId>com.epam.reportportal</groupId>
  <artifactId>agent-java-cucumber4</artifactId>
  <version>4.0.0</version>
  <type>pom</type>
</dependency>
```

**Comment by borbamartin** [comment]
Using the dependency (removing the `<type>pom<type>`) worked.
Thanks @DzmitryHumianiuk !

**Comment by afsaralihooq** [comment]
I had similar issue for TestNG upgrading to latest helped me :

		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-testng</artifactId>
			<version>4.2.0</version>
		</dependency>

<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>logger-java-log4j</artifactId>
			<version>4.0.1</version>
		</dependency>

<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.10.3</version>
</dependency>
