### ISSUE TITLE
[Auto-analysis] Provide configuration on UI for set launches count to analyze

### ISSUE THREAD

**Issue by admizh** [reportportal/reportportal#61]
RP have limit to perform auto-analyse - only last **4** executions take effect to analyze process.

In our project we have alot launches per day. ~**20-30** executions. For exclude launches from auto-analyse we temporarily move it to debug. This strange approach - but it gives ability to selecting launches for auto analyze

I remember - that your team is planning migrate auto-analyzer to elastic-search - but development is scheduled at the end of 2017 (Q4).

Provide ability to remove limitations for auto-analyze should solve many problems. But it also provide performance issues and increase time for auto analyze. I'd rather go drink coffee - instead of prepare launches to auto-analyze

![image](https://cloud.githubusercontent.com/assets/6014483/21442636/8bc8a826-c8b8-11e6-936b-a6c98c2a094c.png)

**Comment by DzmitryHumianiuk** [comment]
this can be considered to be configurable via server settings.

**Comment by DzmitryHumianiuk** [comment]
@admizh started

**Comment by avarabyeu** [comment]
Parameter (might be added for service-api)  will be called `rp.issue.analyzer.depth`. Default value:
`rp.issue.analyzer.depth=5`
Once 3.0 is released, we update demo docker-compose.yml with that config parameter
