### ISSUE TITLE
Add an API command to start an item only if it's not already started

### ISSUE THREAD

**Issue by abotalov** [reportportal/reportportal#611]
There's a test suite to be run in parallel distributed across several machines. There's a parent CI job that executes tests on other machines.
```
suite
  - folder
    - test item to be distributed to machine 1
    - test item to be distributed to machine 2
    - ...more items...
  - ...other folders...
```
Results from all machines are sent to the same Report Portal launch. The folder structure in Report Portal should replicate folder structure in the actual test suite.

It looks, there are three choices to implement this:
1. Create all items for the folder hierarchy before running tests. When tests are executed, they search for the already created folder items. This has a disadvantage that tests are started only after a delay needed for creating all folder items. It would be better not to have a delay before starting tests as, ideally, all reporting should be asynchronous and not increase test execution time.
2. Start folders by machines that execute tests while executing tests. But if the check is implemented on the client side, this has a disadvantage in the existence of a race condition:
```
if ReportPortal.is_folder_created(...): # folder may be already created by another machine
  ReportPortal.create_folder(...)
```
So folder items may be duplicated.
3. Start folders by machines that execute tests while executing tests. Implement an action on Report Portal BE side to start a folder item only if it's not already started. E.g. via adding some "distinctiveId" parameter to "POST /{projectName}/item/{parentItem}" or adding a new endpoint. If an item with the same "distinctiveId" already exists, Report Portal server returns this item instead of creating a new item.

I think that choice 3 is the best way to go. It will also work if the tests are run not distributed but on the same machine. Using the same code for distributed and not distributed running will simplify client side.

**Comment by abotalov** [comment]
Ping @nvborisenko @aliaksandr-trush @filland @bigbZik @s0undt3ch @avarabyeu 
I think it may be good to hear your opinion on this as you may have worked on adding parallel support in client libraries and so may have an opinion on this.

**Comment by nvborisenko** [comment]
To do it we need synchronization context between runners. The best choice of this context is Report Portal server itself.

**Comment by evjlobanova** [comment]
@iivanou has this issue been addressed in the new implementation?
