### ISSUE TITLE
Custom welcome screen and email templates

### ISSUE THREAD

**Issue by sumeetm18** [reportportal/reportportal#613]
We want to have custom welcome screen and email notification templates 
...

Can we have an option to override the values in home screen and also email notification template.
...

**Comment by evjlobanova** [comment]
@sumeetm18 Could you please provide us your desired template for login screen and for e-mail?

**Comment by evjlobanova** [comment]
#573

**Comment by evjlobanova** [comment]
Closed as a duplicate of #573
