### ISSUE TITLE
Can not login with admin or default credentials 

### ISSUE THREAD

**Issue by knayeneni** [reportportal/reportportal#617]
Hi, I used admin account username: superadmin, password: erebus and tried with default/1q2w3e as well, but I am still not able to login and I am getting "An error occurred while connecting to Server".

Btw, I did the installation part without dockers as I am running it on Windows 7. Once I am able to run it successfuly, I would like to add them to VM's which are on Windows 10.
Currently these are the services which are showing and I am not sure that's the reason why I am not able to login, but in that case can some one please tell me why index, ui and gateway are not showing up even though those services are up and running...thanks
![image](https://user-images.githubusercontent.com/49925642/56937332-b0442880-6ac1-11e9-8497-65a844286a1d.png)

**Comment by knayeneni** [comment]
Now, I have all services up and running, but only Gateway throws an error
Get http://[127.0.0.1]:8080/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
![image](https://user-images.githubusercontent.com/49925642/57793617-638a5f80-7707-11e9-96ac-fb67e613a2d4.png)

This could be the reason, why I still couldn't login
Did anyone encountered this issue and how did you go about resolving it...thanks

**Comment by mcopjan** [comment]
I have followed the steps from the documentation:

- curl https://raw.githubusercontent.com/reportportal/reportportal/master/docker-compose.yml -o docker-compose.yml
- docker-compose up
- http://localhost:8080 -> login as guest or superadmin leads to "an unexpected error occurred"


Attaching logs
[logs.txt](https://github.com/reportportal/reportportal/files/3234079/logs.txt)

**Comment by evjlobanova** [comment]
Please follow the steps described in the latest manual https://reportportal.io/docs/Deploy-ReportPortal-without

But we do not recommend to deploy ReportPOrtal on Windows.
Recommended ens are Linux, MacOS, Kuber
