### ISSUE TITLE
Services Gateway and Index returns HTTP GET http://[127.0.0.1]:8080/health: 404 Not Found Output

### ISSUE THREAD

**Issue by knayeneni** [reportportal/reportportal#619]
Service 'gateway' check
HTTP GET http://[127.0.0.1]:8080/health: 404 Not Found Output: 
Anyone ever had this issue and how you guys resolved it.
Also, Reportportal login url used to be http://127.0.0.1:8080/#login, which isn't working any more and not sure how but got switched over to http://127.0.0.1:8081/#login.
Not sure if this is ok.
![image](https://user-images.githubusercontent.com/49925642/57413195-ea47b580-71b8-11e9-8643-249a2d665c8e.png)

Btw, this installation is done on windows 7 without docker

**Comment by evjlobanova** [comment]
@Yumfriez Ivan, could you please look at this issue?

**Comment by knayeneni** [comment]
I am able to get the error with Service Index resolved, but couldn't proceed further with resolving Gateway error. 
Earlier, it gave me HTTP GET http://[127.0.0.1]:8080/health: 404 Not Found Output
But now its giving me Get http://[127.0.0.1]:8080/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
I updated my comments in #617 as well..thanks

![image](https://user-images.githubusercontent.com/49925642/57793811-d693d600-7707-11e9-9c9e-b3db2e9a1f71.png)

**Comment by Yumfriez** [comment]
@knayeneni Could u provide logs from the Gateway service please?

**Comment by evjlobanova** [comment]
Closed due to no response
