### ISSUE TITLE
/{project}/item PUT fails if item has stacktrace

### ISSUE THREAD

**Issue by Oldsouldier** [reportportal/reportportal#624]
**Describe the bug**
When trying to update a test item categorization, the api hangs if a stack trace is present. It succeeds quickly if there is no stack trace. It also hangs in a way that the category counts don't get updated properly. I apparently have -2 product bugs in my project right now. Description, skip auto-analyze, and category seems to be updated when getting the item back, but summary total is wrong, and the api endpoint hangs. I get a 504 from my ingress resource. There are no relevant logs from the API container.

All items were imported junit xml files.

Deployed with modified helm chart.

**Expected behavior**
Updating an item's information should return 200, and happen within a second.

**Screenshots**

**Versions:**
 - Windows 10, Chrome
 - Current version: API Service: 4.3.9; Index Service: 4.2.0; Authorization Service: 4.2.0; Service UI: 4.3.7;

**Comment by clintmoyer** [comment]
Seeing the same issue. Steps to recreate:

1. Navigate to a test item that has failed and contains a stack trace
2. Click to edit the defect type and when the modal window pops up, edit the description
3. Click "Save"

When the test contains a stack trace, the modal window hangs indefinitely and the service returns an HTTP 504 status code. However the PUT request still works and the change is visible after a hard refresh.

**Comment by Oldsouldier** [comment]
It turns out i had a misconfigured elasticsearch deployment. I scaled down the number of master nodes to 1, and missed setting RECOVER_AFTER_MASTER_NODES=1 in the helm chart.
