### ISSUE TITLE
nginx integration

### ISSUE THREAD

**Issue by Yaromudr** [reportportal/reportportal#625]
I want deploy PR with nginx
For example, need create url for ui as http://host/report/ui/
I create location-file as 
```
location /report/ {
   proxy_pass http://localhost:9999/;
}
```
 where 9999 - gateway port for fabio
After deployment, I see the RP login page at the right address. But I can't login into RP

After load login page I see errors on browser console. Before login
Request http://host/composite/info have status 403, but if I execute the query http://host/report/composite/info I will get the correct response with list services. 

Similarly, when I try to login, I see an incorrect address of the authorization request ... 
http://host/uat/sso/oauth/token?grant_type=password&password=erebus&username=superadmin instead of http://host/report/uat/sso/oauth/token?grant_type=password&password=erebus&username=superadmin

How can I properly configure the interaction between nginx and PR?

My ansible script for RP deploy: https://gist.github.com/Yaromudr/8609e074ccea097a856ce600aadf33e3

**Comment by AlehB** [comment]
Hi @Yaromudr,

We moved to the ReportPortal 5.x. Nginx Controller is used for the Kubernetes version (Traefik for the Docker one)

Please check the following install options available
- Docker - https://reportportal.io/docs/Deploy-with-Docker
- Kubernetes - https://reportportal.io/docs/Deploy-with-Kubernetes
- no Docker version for CentOS/RHEL Linux distributions - https://reportportal.io/docs/Deploy-ReportPortal-without

Best Regards,
Aleh

**Comment by pungorandras** [comment]
You can use nginx over traefik. I used docker compose to run report portal. The nginx configuration is tricky a little bit. Traefik is on port 8888. Nginx passes the contents in /reportportal/, but reportportal tries to load them from the root location. So you need to redirect the calls to /reportportal/request_uri. The temporary redirect (return 307) is very important, because it doesnt change the request.

```
location /reportportal/ {
        proxy_pass http://localhost:8888/;
    }

    location ~ ^/(api|uat|jobs|ui|composite)(.*) {
        return 307 https://$host/reportportal$request_uri;
    }
```
