### ISSUE TITLE
Screenshot attachment not working in report portal using log4j

### ISSUE THREAD

**Issue by mamtag** [reportportal/reportportal#629]
Issue-Email attachment is not working. Using below code-

 public static final Logger LOGGER = LogManager.getLogger(Java fileclassName.class);

Public void test()
{
File file=new File("q.png");                  
ReportPortalMessage message1 = new ReportPortalMessage(file,"image file");                  LOGGER.info(message1);
}

Getting below output in reportportal logs (WITHOUT ANY IMAGE)-
[05:21:31] INFO (?:?) - com.epam.reportportal.message.ReportPortalMessage@1338fb5 

Note- q.png placed at project relative path and i have verified through code and file exist retruning true.

Using below dependencies-
	 <dependency>
	  <groupId>com.epam.reportportal</groupId>
	  <artifactId>logger-java-log4j</artifactId>
	  <version>4.0.1</version>
	  </dependency>

   <dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-testng</artifactId>
			<version>4.2.1</version>
		</dependency>

Please help!

**Comment by tmatveyeva** [comment]
Have same issue, even though screenshot sometimes appears in log, but I cannot figure out when does it work and when not

**Comment by omkarnathsingh** [comment]
You might be logging it as String somewhere which is causing this issue. I tried your code and its working fine for me.

**Comment by tmatveyeva** [comment]
We do not have this issue after updating logger-java-log4j to 4.0.2 (from 4.0.1)

**Comment by Onish1204** [comment]
I am facing same issue, With same code as below, it was working since 1 month, but now suddenly stops. 

Public void test()
{
File file=new File("q.png");
ReportPortalMessage message1 = new ReportPortalMessage(file,"image file"); LOGGER.info(message1);
}

rp ver 5.1
