### ISSUE TITLE
Upgrade process: drops pinned filters (tabs on launches view)

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/reportportal#63]
I upgraded docker images from 2.6 to 2.7 and lost my tabs on launches view.

Logout/login/refresh didn't help.

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko do you mean opened filter-tabs?

filters are still available under `Filters` view?

**Comment by nvborisenko** [comment]
I mean `Launches` tab, filters at top of the page.

Filters still exist on the `Filters` tab.
![screenshot_1](https://cloud.githubusercontent.com/assets/22616990/21496531/3dc6e090-cc30-11e6-9783-1b9cb45a040b.png)

**Comment by avarabyeu** [comment]
@lexecon could you please comment on the issue
