### ISSUE TITLE
Does Report Portal has possibility to be deployed not with MongoDB but with PostgreSQL

### ISSUE THREAD

**Issue by VDouble** [reportportal/reportportal#630]
Hi,
I would like to deploy production Report Portal not with remote MongoDB but with remote PostgreSQL.  This kind of deploy would let our team for easier maintain of data-base for Report Portal.

Question is if there's possibility to deploy Report Portal not with remote MongoDB but with remote PostgreSQL?

**Comment by evjlobanova** [comment]
@VDouble hello for version 4 it is impossible. But soon we will release new version 5.0 which based on PostgreSql

**Comment by VDouble** [comment]
@evjlobanova When we could expect version 5.0?

**Comment by evjlobanova** [comment]
we are planning beta release in June

**Comment by VDouble** [comment]
@evjlobanova Thank you very much :)
