### ISSUE TITLE
Update Status of Steps programmatic 

### ISSUE THREAD

**Issue by RuggeriLuca** [reportportal/reportportal#632]
Hello, 
i have the below case :
- i use newman to run our collection. 
- each API calls had ~3000 assertions 

i manage to extract the assertion  using the below code : 
```javascript
emitter.on('assertion', function (err, o) {
   	   if (err) { throw err; }
       const testObj = collectionMap.get(o.cursor.ref);
	   const stepObj = client.startTestItem({
				name: o.assertion,
				type: 'STEP'//,
				//tags: getTags(collectionRunOptions.environment.values)
				},
				launchObj.tempId,
				testObj.testId);
				testObj.steps.push({
					stepId: stepObj.tempId,
					name: o.assertion
             });
			 
			// console.log(testObj.steps.slice(-1)[0].stepId);
			// finishSteps (reference, testObj, run) 
    });
```
next in the same script i use the below to update it : 

```javascript
 emitter.on('done', (err, o) => {
     if (err) {
          throw err;
      }
    
		for (let [ref, testObj] of collectionMap) {
			console.log(testObj);
			for(let lclStep of testObj.steps){
				client.finishTestItem(lclStep.stepId, {status: TestStatus.PASSED});
			}				
		}
    });
```
Can results is that not all the Steps are update to PASSED, a lot are still in IN PROGRESS status 

can someone help me ?

**Comment by DzmitryHumianiuk** [comment]
@RuggeriLuca what are the server responses during last `for` loop? 
server should give your error description, why it can't finish item.

**Comment by DzmitryHumianiuk** [comment]
@RuggeriLuca for the v4 we also have restriction: status change for completed tests are not allowed.
this is removed in v5, which is in beta at the moment.

but still, in v4, there was a chance to bring test case back to IN_PROGRESS and finish with proper status.

**Comment by DzmitryHumianiuk** [comment]
may have reference with https://github.com/reportportal/reportportal/issues/672

**Comment by DzmitryHumianiuk** [comment]
@RuggeriLuca how it goes?
Most likely newman runner finishes test case before the moment of steps finish.
this leads to error in version 4.

version 5 of RP allows to finish parents before child, and receive status updates later on.

just try the same code with RP v5
