### ISSUE TITLE
Upgrade Spring-Boot version?

### ISSUE THREAD

**Issue by naddison** [reportportal/reportportal#634]
Are there plans to upgrade to a newer spring boot version? I am trying to use a Mongo DB Cluster that is running on 4.0, but I see that ReportPortal uses Spring Boot 1.5.9.RELEASE which contains the 3.4 version of the java mongo driver, which is incompatible with Mongo 4.

https://repo.spring.io/release/org/springframework/boot/spring-boot-dependencies/1.5.9.RELEASE/spring-boot-dependencies-1.5.9.RELEASE.pom

https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#java-driver-compatibility

**Comment by evjlobanova** [comment]
In the latest version of ReportPortal we are using PostgreSQL
