### ISSUE TITLE
How to test Import functionality in Report portal, if possible could please share XML format to import and check whether it is working or not ?

### ISSUE THREAD

**Issue by LakshmiNagandla** [reportportal/reportportal#635]
**Describe the bug**
- I just  imported XML file in Report portal, but I don't see any test steps displaying inside my test cases

**Expected behavior**
...

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

**Comment by DzmitryHumianiuk** [comment]
@LakshmiNagandla 
[test-results.zip](https://github.com/reportportal/reportportal/files/3271821/test-results.zip)

**Comment by LakshmiNagandla** [comment]
Hi,

Thanks for sharing detailed xml report, is there any possiblity to download same kind of zip report for executed launches in our local. 

Can you please let me know how to download the lauch files as zip. 

Thanks,
Lakshmi

**Comment by DzmitryHumianiuk** [comment]
@LakshmiNagandla no, there is no option to download launch as zipped xml for now.
