### ISSUE TITLE
How to download test execution launch results in report portal in zip file format to share with clients.

### ISSUE THREAD

**Issue by LakshmiNagandla** [reportportal/reportportal#636]
**Describe the bug**
...

**Expected behavior**
...

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

**Comment by DzmitryHumianiuk** [comment]
Well, it's pretty philosophic question.
Can't you just share a link to dashboard with him?

**Comment by evjlobanova** [comment]
Closed due to no response
