### ISSUE TITLE
Unable to see Auto Analyzer in Report Portal settings

### ISSUE THREAD

**Issue by vasanth1805** [reportportal/reportportal#637]
**Describe the bug**

Unable to see Auto Analyzer in Report Portal settings, but the elastic search service is up and running. 

Note: Installed Report Portal and elastic search without docker.

Let me know if i am missing any step or doing something wrong. Your help is much appreciated.

**Screenshots**
![elastic search](https://user-images.githubusercontent.com/51641607/59195710-4764cb80-8baa-11e9-9c2d-f419fc6a28a9.jpg)

**Elastic Search Service:**

![service](https://user-images.githubusercontent.com/51641607/59195807-8abf3a00-8baa-11e9-865d-b53d4b0e09f4.jpg)

**Report Portal Setting Page:**

![RP_Setting](https://user-images.githubusercontent.com/51641607/59195949-f6a1a280-8baa-11e9-8e03-7fd59fe3ccb7.jpg)

**Versions:**
 - Windows 7 (Installed Report Portal without docker), Chrome Browser
Current version: API Service: 4.3.9; Service Index: 3.1.1; Jira Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 3.1.1;

**Comment by evjlobanova** [comment]
Please  use the latest manual for ReportPortal installation without docker and the latest version of Report Portal https://reportportal.io/docs/Deploy-ReportPortal-without
