### ISSUE TITLE
com.mongodb.MongoSocketException: mongodb: Name does not resolve

### ISSUE THREAD

**Issue by bencf1** [reportportal/reportportal#638]
Env: Docker for Windows on Windows 10 Pro, with Linux containers
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

Steps:
1) Download latest docker-compose file
2) Run: `docker-compose -p reportportal up -d --force-recreate`

Expected:
I can load the app and log in using the default credentials

Actual:
I get a server error trying to log in, an inspection of the logs shows a MongoDB name resolution error:

`com.mongodb.MongoSocketException: mongodb: Name does not resolve`

I have tried resetting factory defaults in docker, that didn't help

Full logs
[logs3.txt](https://github.com/reportportal/reportportal/files/3280466/logs3.txt)

**Comment by evjlobanova** [comment]
Please use the latest manual for installation with Docker on Windows https://reportportal.io/docs/Deploy-with-Docker%3Edeploy-reportportal-with-docker-on-windows

Please reopen the issue if you still have a problem
