### ISSUE TITLE
Can we log Allure @Step into ReportPortal

### ISSUE THREAD

**Issue by adorovskikh** [reportportal/reportportal#639]
Добрый день. На нашем проекте не используются библиотеки для логирования, так как Allure Steps вполне решали эту проблему. Сейчас я попробовал прикрутить report portal, добавил log4j логирование в несколько тестов, да все работает, Логирование  в rp успешно отображается. Но возможно ли реализовать также как в Allure на основе Steps, или как то подключить логирование через Allure Steps в rp, Стэк maven/junit5/selenide/allure

Просто не переписывать же все тесты с логированием через log4j, может кто-то уже обращался с таким вопросом.

[English]
Good afternoon. Our project does not use libraries for logging, as Allure Steps completely solved this problem. Now I tried to fasten the report portal, added log4j logging in some tests, Yes everything works, Logging in rp is successfully displayed. But is it possible to implement the same as in Allure based on Steps, or how to connect logging via Allure Steps in rp, Stack maven/junit5/selenide/allure

Just do not rewrite all the tests with logging through log4j, maybe someone has already addressed this question.

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/reportportal/issues/275

For version 5 (~~1 month) we releasing Nested Steps.
Which will be equal to `@Step` functionality.
So just wait for it a bit.

At the moment, for v4,  this can be done via customization, and logging of `@Step` annotation as another line of log, but with the text you have in it.

v5
![image](https://user-images.githubusercontent.com/11332788/59359129-78720700-8d36-11e9-9e99-45bf46b5f87b.png)

![image](https://user-images.githubusercontent.com/11332788/59359081-61cbb000-8d36-11e9-9243-6e927117d3d4.png)

**Comment by adorovskikh** [comment]
@DzmitryHumianiuk 
Thanks for the quick response, waiting for version 5))

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/examples-java/blob/master/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/step/NestedStepsTest.java#L92

**Comment by sonamsingh1799** [comment]
Hi, I'm doing the report portal integration with python and I couldn't find how to use this @Step feature in python to log steps in report portal. can anyone help please?

**Comment by DzmitryHumianiuk** [comment]
@sonamsingh1799 it's better to raise this question in client-python repo

**Comment by sonamsingh1799** [comment]
> @sonamsingh1799 it's better to raise this question in client-python repo

@DzmitryHumianiuk  Yeah sure, Thanks
