### ISSUE TITLE
Please correct limitation: test log item time after parent item's start time

### ISSUE THREAD

**Issue by Rider1982** [reportportal/reportportal#64]
I'm trying to add to RP a failed attempt of execution of test case which is cannot be started at all (for example due to environment reasons or conflicting settings). This test has no start time, no end time and no duration. I would add a log item to this test case and I must specify the log item time. The good idea is to use parent test case start time as test case item start and finish time and its log item time, but I see the "Logging is not allowed. Log has incorrect log time. Log time should be after parent item's start time." error. Please allow use test case start and finish time and its log items time equal test suite start time.

**Comment by avarabyeu** [comment]
hi @Rider1982. Good point, thank you. Actually, we are thinking about removing that constraint at all since sometimes (for asynchronous clients) log time can be even after parent's item finish time.

**Comment by avarabyeu** [comment]
Fixed. The following constraints were removed:
1. Logging is allowed only to test items which are in progress state
2. Logging is allowed only to test items which do not have children

Log item still should be after (OR equal) parent's start time and before (OR equal) parent's finish time.
