### ISSUE TITLE
Russian letters are not shown in Reports  (Не отображаются русские символы в тестовых отчетах)

### ISSUE THREAD

**Issue by adorovskikh** [reportportal/reportportal#640]
**Describe the bug**
Подключили к проекту log4j. 

Конфиг:
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
    <Appenders>
        <Console name="ConsoleAppender" target="SYSTEM_OUT">
            <PatternLayout
                    pattern="%d [%t] %-5level %logger{36} - %msg%n%throwable"/>
        </Console>
        <ReportPortalLog4j2Appender name="ReportPortalAppender">
            <PatternLayout
                    pattern="%d [%t] %-5level %logger{36} - %msg%n%throwable"/>
        </ReportPortalLog4j2Appender>
    </Appenders>
    <Loggers>
        <Root level="DEBUG">
            <AppenderRef ref="ConsoleAppender"/>
            <AppenderRef ref="ReportPortalAppender"/>
        </Root>
    </Loggers>
</Configuration>
```
Добавили в тесты логирование типа такого:
```
title = "Попереключаться между вкладками \"Новинки\", \"Повышенный кэшбэк\", \"Популярные партнеры\" блока с предложениями.",
expected = "Происходит переключение.",
stepNumber = 6
```

**Expected behavior**
В интерфейсе не отображаются русские буквы

**Screenshots**
If applicable
![image](https://user-images.githubusercontent.com/47498749/59357753-10babc80-8d34-11e9-919d-6ee9e9dbfd63.png)

**Versions:**
 - Windows 10, Chrome

![image](https://user-images.githubusercontent.com/47498749/59357845-35169900-8d34-11e9-9ffb-9834faeb9db5.png)

**Comment by DzmitryHumianiuk** [comment]
@adorovskikh 
[`WriterAppender`](http://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/WriterAppender.html) (which is the base class for FileAppender and its variants. Has a [`setEcoding`](http://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/WriterAppender.html#setEncoding%28java.lang.String%29) method. So yes: using `log4j.appender.myappender.encoding=UTF-8` should simply work.

**Comment by adorovskikh** [comment]
@DzmitryHumianiuk , не понял куда нужно это 
`log4j.appender.myappender.encoding=UTF-8`
воткнуть, в итоге решил проблему добавив 
`charset="UTF-8"` в log4j2.xml 

```
        <ReportPortalLog4j2Appender name="ReportPortalAppender">
            <PatternLayout
                    pattern="%d [%t] %-5level %logger{36} - %msg%n%throwable"  charset="UTF-8"/>
        </ReportPortalLog4j2Appender>
```
