### ISSUE TITLE
Log4j2 screenshots don't send to reportportal

### ISSUE THREAD

**Issue by adorovskikh** [reportportal/reportportal#641]
Скриншот создается, в папке проекта отображается корректно, но в reportportal не загружается.
Метод:
```
        } catch (e: Throwable) {
            logger.error("ERROR!!!\nTestTitle: $title\nExpextedResult: $expected\nStepNumber: $stepNumber\n")
            logger.error(
                ReportPortalMessage(
                    File(Selenide.screenshot("failed_${(WebDriverRunner.driver().webDriver as RemoteWebDriver).sessionId}")),
                    "ERROR!!!\nTestTitle: $title\nExpextedResult: $expected\nStepNumber: $stepNumber\n"
                )
            )
            throw e
        }
```

ReportPortal

![image](https://user-images.githubusercontent.com/47498749/59380985-0ebc2200-8d63-11e9-9a4c-62c86d8fdf60.png)

![image](https://user-images.githubusercontent.com/47498749/59380900-d61c4880-8d62-11e9-99c6-c3a51e3fbfe7.png)

![image](https://user-images.githubusercontent.com/47498749/59380923-e502fb00-8d62-11e9-86a0-f2d2057754f5.png)

Все сделал в соответствии с инструкцией:

![image](https://user-images.githubusercontent.com/47498749/59381075-4cb94600-8d63-11e9-8055-c1b3c3cbfe87.png)

**Comment by adorovskikh** [comment]
Хорошо, завелось в итоге вот так:
```
 catch (e: Throwable) {
 val screenPath =
                Selenide.screenshot("failed_${(WebDriverRunner.driver().webDriver as RemoteWebDriver).sessionId}")
            logger.error("ERROR!!!$message")
            logger.error("RP_MESSAGE#FILE#{}#{}", screenPath)
            throw e
}
```

Тогда другой вопрос, как туда заслать видео и page_source?

**Comment by DzmitryHumianiuk** [comment]
@adorovskikh https://github.com/reportportal/example-java-TestNG/blob/master/logback/src/main/java/com/epam/rp/tests/logging/LoggingTest.java

**Comment by adorovskikh** [comment]
О, класс, надо попробовать. Тогда закрывайте)
