### ISSUE TITLE
After restart docker all projects are deleted

### ISSUE THREAD

**Issue by vhildebrandt-usa** [reportportal/reportportal#642]
Hello, I know there was already a similar issue (#408 ), but unfortunately without a solution. I have the issue that after a restart (on my local machine) all projects and all data is deleted. Is there a way to save my test results, even if I restart dockers?

**Comment by DzmitryHumianiuk** [comment]
@vhildebrandt-usa you do in on windows?

Please share what you have for mondoDB declarations of your `docker-compose.yml`, in here:
https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L17-L36

https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L22
```yml
    volumes:
      - ./data/mongo:/data/db
```
this refers to volumes creation (basically folder creation), in directory where your `docker-compose.yml` was called. And database storage within container, will be mounted into this folder. So when you will start `docker-compose.yml` from the same location, it will be mounted to the right data.

For instance, if you downloaded ```docker-compose.yml``` into folder `~/user1/rp`
and have it like ```~/user1/rp/docker-compose.yml```
when you will call `docker-compose -p reportportal up -d --force-recreate`
it will create a folder ```~/user1/rp/data/mongo``` and it will be mounted with in-container db storage.

if the next day you will start ```docker-compose.yml```  from another folder, for instance, `/user1/database/`, then data will not be found.


if it's windows, then: https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693/18


For reference:
https://stackoverflow.com/questions/35400740/how-to-set-docker-mongo-data-volume
https://stackoverflow.com/questions/42189091/stop-vm-with-mongodb-docker-image-without-losing-data

**Comment by vhildebrandt-usa** [comment]
@DzmitryHumianiuk : Yes, I do it on Windows Docker Desktop Version 2.0.0.3 (31259)

I still have the default settings in my docker-compose.yml:
![image](https://user-images.githubusercontent.com/46687273/59435669-1eb42000-8dbc-11e9-9752-08c92b15e1af.png)

And the file is here: C:\Users\MyUser

When I populate the data in the Report Portal I don't see any record here:
C:\Users\MyUser\data\mongo

Do you have an idea?

**Comment by DzmitryHumianiuk** [comment]
@vhildebrandt-usa this might be an issue with volume mounts on windows.
here some ideas to start with: https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693/23

try to make replace `./data/mongo` in `./data/mongo:/data/db` with direct address of your folder.

We never do it on windows, so can't comment a lot.

Another workaround:
deploy Mongo on windows without docker. 
go to https://reportportal.io/download
in _2. Configure and deploy ReportPortal with Docker-Compose file_
click _Configure file_
and  _Mongo DB location_
choose _On a separate host_
and enter connection configurations to your mongo
