### ISSUE TITLE
Test Name Modification during Run Time

### ISSUE THREAD

**Issue by rajkumar-cp** [reportportal/reportportal#645]
Hi All,

Current test name property will be fed in properties file and in portal it will be updated as testname_execution number.

It will be cool if there is a way to update the same inside our code based on certain test parameters. Is there any way available for the same.

**Comment by DzmitryHumianiuk** [comment]
@rajkumar-cp take a loook.
it should help.

https://github.com/reportportal/agent-java-testNG#code-example-how-to-overload-params-in-run-time

**Comment by rajkumar-cp** [comment]
@DzmitryHumianiuk 

In that piece of code from which library those functions were imported. (Module.binder,ConfigurationModule,Injector). I have added all the dependencies mentioned in the above steps but still i didn't see these functions in any of the packages mentioned there.

**Comment by DzmitryHumianiuk** [comment]
@Yumfriez can you please verify this example works as desired?
https://github.com/reportportal/agent-java-testNG#code-example-how-to-overload-params-in-run-time
