### ISSUE TITLE
Extension is missing when downloading a file attached to the log

### ISSUE THREAD

**Issue by abotalov** [reportportal/reportportal#646]
**Describe the bug**
I have a launch where there is a file attached to a log.
The file is in a format not supported by Report Portal, so when I click it, it's downloaded. That works fine.
But the downloaded file has no extension. It's not convenient because the user has to manually add it in order to open it in a specialized application.

**Expected behavior**
The downloaded file should have the same extension as the extension of the uploaded file.

**Screenshots**
![Screenshot from 2019-06-21 15-38-02](https://user-images.githubusercontent.com/1497867/59922938-b78d1000-943a-11e9-993f-3697459b4f97.png)

**Versions:**
 - Version of RP = 4.3.6

**Comment by svettsova** [comment]
@abotalov could you please specify which file format did you attach?

**Comment by abotalov** [comment]
Some video file format (mkv probably)

**Comment by evjlobanova** [comment]
@abotalov do you try it on version 5?

**Comment by abotalov** [comment]
No, I tried it only on 4.3

**Comment by evjlobanova** [comment]
@abotalov Do  you have a chance to try on version 5.2?
