### ISSUE TITLE
Log pages are limited to up-to 300 lines - I want to be able to increase that and also to be able to see the entire log

### ISSUE THREAD

**Issue by haelye** [reportportal/reportportal#647]
Hi,

I have noticed the in each log page the UI can display up-to 300 log lines – this limitation creates a great difficulty with troubleshooting issues because I find myself need to turn pages forwards and backwards between many log pages and it is quite uncomfortable..

Can you please add an option to view the entire log file or to set a much much greater entries limitation? - 300 entries are just too few..

(I know that your purpose was to keep on page load performance but this matter requires a solution since the main purpose is to make the troubleshooting much easier)

Thanks a lot!

**Comment by evjlobanova** [comment]
@haelye could you please solution in issue #845? Does it help it to resolve your problem?
