### ISSUE TITLE
Add ability to protect a test result from auto-deletion

### ISSUE THREAD

**Issue by haelye** [reportportal/reportportal#652]
Hi,

Sometimes there are some test results which we want to keep for future comparison - however each test run is deleted by the default after 10 days by the system..
It will be great if the UI would allow me to put a "lock" on a test run which will protect it from deletion for a longer period of time.

It can be set that the lock can protect the test results for 3 months and a week before it is about to be deleted the system will provide a notification that the test results are about to be deleted. 
Once I get this notification it will be very nice if I could also "re-new" the lock and maintain the test results for another 3 months.

The "lock" which I'm talking about could be assigned for:
1. Launch level
2. Test suite level
3. Test method level

**Comment by RPgitHubTestUser** [comment]
@haelye you can configure a period for saving logs and screenshots in the Settings
![image](https://user-images.githubusercontent.com/22913350/62307767-dbf1f880-b48c-11e9-8522-fbb782f2f06b.png)
Does it help you?

**Comment by ehaelyon** [comment]
Hi @RPgitHubTestUser (I'm @haelye - I have another github user) 
I am familiar with this option - however, this configuration is done on the project itself and in my use-case I don't want to keep all my launches for 6 months or forever - I want to be able to mark a certain launch and protect it from being deleted after that period of time

If I will apply your the project-level configuration on a project which is a very main project where many launches are being created each day, then my DB will get full pretty quick :)

**Comment by DzmitryHumianiuk** [comment]
@ehaelyon #674 is your case.
and #511 

closing as duplicate.
follow mentioned items for discussion
