### ISSUE TITLE
Execution continues in RP even after it is completed 

### ISSUE THREAD

**Issue by rajkumar-cp** [reportportal/reportportal#653]
**Describe the bug**
My execution got completed in Eclipse but in RP it is still in execution state and at the end of execution the below error message was logged in eclipse console.

Jun 24, 2019 12:39:35 AM com.epam.reportportal.utils.SubscriptionUtils$3 onError
SEVERE: [15] ReportPortal Finish test item execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish test item is not allowed. Test item '5d0f353fb9d8210001e4fc3d' has descendants with 'IN_PROGRESS' status. All descendants '[init, getMethodName, AddSameVaultAgain, endtestcase, getMethodName, AddVaultDiffUserName, endtestcase, InvalidLoginErrorMsg, getMethodName, endtestcase, getMethodName, LogoutCurrentVaultFromList, endtestcase, getMethodName, RemoveAllVaultsFromList, endtestcase, getMethodName, RemoveCurrentVaultFromList, endtestcase, RemoveVaultFromList, getMethodName, endtestcase, ValidateVaultWithTick, getMethodName, endtestcase, addNewVault, getMethodName, endtestcase, getMethodName, navigateBackVaultPage, endtestcase, cleanApp, init, getMethodName, AddUnmanagedSuggestion, endtestcase, getMethodName, AddUnmanagedSuggestion, endtestcase, getMethodName, IgnoredSuggestionValidation, endtestcase, getMethodName, MultiLookupPropertySuggestion, endtestcase, SuggestionListModification, getMethodName, endtestcase, getMethodName, SuggestionListModification, endtestcase, getMethodName, TestAnalyticsValidation, endtestcase, cleanApp, init, AddCommentInPromotedObject, getMethodName, endtestcase, getMethodName, CheckDuplicateItemIsNotCreated, endtestcase, getMethodName, ContextMenuOptionsPO, endtestcase, ContextMenuOptionsUPO, getMethodName, endtestcase, getMethodName, ConvertSFDtoMFDOfPromotedObject, endtestcase, DuplicateFileNameUPO, getMethodName, endtestcase, getMethodName, MarkUnmanagedObjectToOffline, endtestcase, getMethodName, PromotedObjectSearch, endtestcase, getMethodName, PromoteobjectandaddMetadata, endtestcase, getMethodName, RenameFileUnsupportedCharacters, endtestcase, RenamePromotedObject, getMethodName, endtestcase, getMethodName, SearchusingFileContent, endtestcase, getMethodName, SearchusingFileName, endtestcase, cleanApp, init, validationOfAssignedToMeView, getMethodName, endtestcase, getMethodName, validationOfHideViewFunction, endtestcase, cleanApp, init, getMethodName, BlankTemplateObjectCreation, endtestcase, getMethodName, CreateMFDObjectFromtemplate, endtestcase, getMethodName, CreateNewObjUsingDiffObjTypes, endtestcase, getMethodName, CreateNewSubObjects, endtestcase, getMethodName, EmptyMandatoryPropertyValues, endtestcase, MakeCopyOfExistingObject, getMethodName, endtestcase, getMethodName, RenameFileWithEmptyValue, endtestcase, RenameFileWithSpecialCharacters, getMethodName, endtestcase, cleanApp, init, getMethodName, editPropertyinRelationsPage, endtestcase, getMethodName, verifyRelationshipView, endtestcase, cleanApp, init, ApprovAssignmntWithESign, getMethodName, endtestcase, getMethodName, ESignWithMeaningAndReason, endtestcase, ESignWithWindowsUserWrongPwd, getMethodName, endtestcase, getMethodName, ESigningWithReadOnlyUser, endtestcase, MarkCompleteAssgnmntReadOlyUser, getMethodName, endtestcase, getMethodName, RemoveWorkflowFromObject, endtestcase, getMethodName, StateTransitWithDocNameUpdate, endtestcase, cleanApp, init, CheckSortByOptionIsDisplayedInSearchView, getMethodName, endtestcase, getMethodName, SearchByDifferentObjectTypes, endtestcase, SearchByDifferentObjectTypes, getMethodName, endtestcase, SearchByDifferentObjectTypes, getMethodName, endtestcase, getMethodName, SearchByDifferentObjectTypes, endtestcase, SearchByDifferentObjectTypes, getMethodName, endtestcase, getMethodName, SearchByValueUsingAdvSearch, endtestcase, getMethodName, SearchUsingQuotes, endtestcase, getMethodName, SearchUsingWildcardCharacter, endtestcase, getMethodName, SearchUsingWildcardCharacter, endtestcase, SearchUsingWildcardCharacter, getMethodName, endtestcase, getMethodName, SearchUsingWildcardCharacter, endtestcase, getMethodName, SearchUsingkeyword, endtestcase, cleanApp, init, getMethodName, init, AddPropBasedObjTypeAndClass, endtestcase, endtestcase, getMethodName, AddPropertyInExistingDocument, CheckSpecifiedPropSetIsRequired, getMethodName, endtestcase, NestedRuleOrderConfiguration, getMethodName, endtestcase, cleanApp, init, ExternalRepoErrmsgValidation, getMethodName, endtestcase, getMethodName, PersonalAuthenticationInvalidCr, endtestcase, PersonalAuthenticationExtRepoVC, getMethodName, endtestcase, cleanApp]'
Error Type: FINISH_ITEM_NOT_ALLOWED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Expected behavior**
Execution is expected to be completed in report portal.

**Screenshots**
If applicable

**Versions:**
 - OS, Browser

 - Version of RP Login
Current version: Analysis Service: 4.3.0; API Service: 4.3.4; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.6;

**Comment by DzmitryHumianiuk** [comment]
@rajkumar-cp all in logs:
`Error Message: Finish test item is not allowed. Test item '5d0f353fb9d8210001e4fc3d' has descendants with 'IN_PROGRESS' status.`

you have to many test items still running at the moment of finalization.

try to find out why they are still in progress at the moment, when finalization of execution made by test runner.

p.s.
in version 5 we will stop all descendants automatically.
