### ISSUE TITLE
Using Amazon Elasticsearch Service instead of local

### ISSUE THREAD

**Issue by mcarriga** [reportportal/reportportal#654]
Is it possible to configure RP to use Amazon's Elasticsearch Service instead of installing and hosting ElasticSearch locally as configured in the docker compose file. We currently have that type of ability with MongoDB configuration wherein we can host the MongoDB instance on a different host so just trying to see if we can do the same type of thing with ElasticSearch where we can have it hosted on another server or even use a service like AWS ElasticSearch Service instead.

**Comment by DzmitryHumianiuk** [comment]
we started it here
https://github.com/reportportal/kubernetes/tree/v5_services/reportportal

config, where we will use Amazon DB, Amazon Balancer and Amazon Elastic

**Comment by AlehB** [comment]
Hi @mcarriga ,

Yes, you can Amazon Elasticsearch Service in our ReportPortal 5.x Kubernetes version
https://reportportal.io/docs/Deploy-with-Kubernetes
