### ISSUE TITLE
Question: browseable html reports as attachements

### ISSUE THREAD

**Issue by tuscias** [reportportal/reportportal#655]
Hi, 
I was wondering is it possible to attach html report with multiple folders and static files and make it browseable?
This would be useful when attaching some security, allure, whatever reports to the Launch node.

**Comment by DzmitryHumianiuk** [comment]
@tuscias hey,
in version 5 will be available launch attachment, it means you can attach file by file to the root of launch object.
it will be pretty similar, like you have it for test case (see attachment tab).

But the option of displaying individual files, with folders and subfolders, shown as a single page - probably not the best option. 
This turns the attachment into a file system browser. 
But the display of one file, opened in a separate tab - it will be solved by feature of lunch attachments.
