### ISSUE TITLE
Report portal: There is no escaping in the field with current step details

### ISSUE THREAD

**Issue by vadzimPliuta** [reportportal/reportportal#656]
**Describe the bug**
If test scenario use script as part of any step, the script is executed on details page(find an attachment with an example): 

[Example](https://rptportal.copyright.com/ui/#spr/launches/all%7Cpage.page=1&page.size=50&page.sort=start_time,number%2CDESC/5d1a489424aa9a0001f88b7d%7Cpage.page=1&page.size=50&filter.eq.has_childs=false&filter.in.status=FAILED%2CINTERRUPTED&filter.in.type=STEP&page.sort=start_time%2CASC?page.page=1&page.size=50&filter.eq.has_childs=false&filter.in.status=FAILED%2CINTERRUPTED&filter.in.type=STEP&page.sort=start_time%2CASC&log.item=5d1a68df24aa9a0001f92a89)

**Screenshots**
![report portal script](https://user-images.githubusercontent.com/46567167/60492989-b4a0e380-9cb4-11e9-8e05-999437e47fb1.png)

**Versions:**
Win 10, Chrome 75.0.3770.100 (Official Build) (64-bit)
 Build: 4.3.7

**Comment by evjlobanova** [comment]
@svettsova Valya, could you please check version 5.1

**Comment by svettsova** [comment]
issue is not reproducible in 5.1
