### ISSUE TITLE
Question: Custom XML

### ISSUE THREAD

**Issue by KarneeKarnay** [reportportal/reportportal#657]
Currently I generate a cucumber xml output at the end of my tests, that I then amend, to include some more information. Such as the tags on a tests. 

Can reportportal handle non-default junit xml reports? 

Also is there a way to filter by different elements in an xml file? Currently my tests are broken down by scenario, but I'd really like to see them broken by feature and then scenario.

**Comment by DzmitryHumianiuk** [comment]
@KarneeKarnay RP can import only standard xunit format.
all custom files should be imported with a custom approach.

for that case, we propose to implement own parser, which will read file and send http requests to RP with data.


>Also is there a way to filter by different elements in an xml file? Currently my tests are broken down by scenario, but I'd really like to see them broken by feature and then scenario.
Didn't get the idea behind the question
