### ISSUE TITLE
Multiple lanuches generated in RP for single suite execution

### ISSUE THREAD

**Issue by KunalShokeen432** [reportportal/reportportal#658]
I have created a basic project for TestNg + Maven + RP.It is integrated successfully and I am able to see the launches in my RP for test suite execution.

The issue is when i execute my testng.xml with RP listener two launches are generated in RP with the latest one always in 'pending' state and with no data.

I don't have multiple suites in my xml i.e

The first launch is successful with correct data for each suite execution.
...
Only 1 launch should be generated in RP with correct data.
and a way to delete pending launches.
...
PFB RP screenshot : 

![RPLaunchesIssue](https://user-images.githubusercontent.com/32562642/61001304-03b5db00-a37d-11e9-9aae-3abac6a1c604.png)

**Versions:**
 - Windows 10,Chrome

MY suite xml 👍 
DOCTYPE suite SYSTEM "http://beust.com/testng/testng-1.0.dtd" >
suite name="My Test Suite">
    listeners>
		listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener" />
	listeners>    
    test name="My Test Testname">
        classes>
            class name="com.sapient.tests.MyTests"/>
        classes>
    test>
suite>
Can anyone please help me with this ?

Thanks

**Comment by KunalShokeen432** [comment]
Can anyone please help with this ?

**Comment by evjlobanova** [comment]
@Yumfriez Could you please help with an issue

**Comment by KunalShokeen432** [comment]
Just an update over this,Reportportal listener entry is in testng.xml file only.
Strange is multiple launches are created when running testng.xml directly(via right click -> run as testng suite).
But, when building project via maven it is working fine and creating only one launch.

**Comment by DzmitryHumianiuk** [comment]
@KunalShokeen432 it might be a issue of IDE, where you call `run as testng suite`.

if it works fine thru maven, then there is no issue with RP agent.
