### ISSUE TITLE
The defect type description is overwritten for Launches

### ISSUE THREAD

**Issue by IrinaBucsa** [reportportal/reportportal#659]
**The bug**
Hello.
I am running some tests written in C#, using nUnit and SpecFlow. The run is started from TeamCity (I don't know if that is relevant), with debug mode = false.
While the test suite is still running, if I take a look at the failed tests the defect type description is exactly what I am sending from code.
After the whole test suite is finished, RP is misteriously changing de defect type into "Exception has been thrown by the target of an invocation." 
If I open each test in RP, I can still see the error ok.
?!?! If I run the same test suite in debug mode, RP does not change the defect description.
** I also tried to throw a custom error instead of the "Assert.Fail" - the result was the same.

**Expected behavior**
I need the actual error (or at least it's first lines) to be displayed because it is descriptive and saves us time, while "Exception has been thrown by the target of an invocation." is not helping us as devs, nor the user of our project.
Can someone please tell me if there is a setting somewhere for this replacement?

**Screenshots**
1. the code that throws error
https://www.screencast.com/t/pABwhILr

2. the display from TeamCity after the run
https://www.screencast.com/t/f8zlru4M0O

3. short movie that shows the failed tests during execution, a refresh of the page after is is completed and the final display
https://www.screencast.com/t/GCKY3Uryw2

4. how a test is displayed (the defect rewritten by RP and the actual error)
https://www.screencast.com/t/eEInZDheb

**Versions:**
 - OS, Browser
Win 7, Chrome 75

 - Version of RP 
Current version: Analysis Service: 4.3.0; API Service: 4.3.4; Index Service: 4.2.0; Jira Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.6; 

Thank you!

**Comment by nvborisenko** [comment]
Bug, agent is not a friend with auto-analizer.
https://github.com/reportportal/agent-net-specflow/blob/0f3cc67d9723de1f69b50babdcc6d7caf762bb47/src/ReportPortal.SpecFlowPlugin/ReportPortalHooks.cs#L248
Agent should not assign issue here. Please move to agent-net-specflow repo and assign to me or @aliaksandbasau.

**Comment by nvborisenko** [comment]
@IrinaBucsa this behavior should be fixed in `ReportPortal.SpecFlow 2.1.0` package. Please verify.
@aliaksandrbasau please take this issue on your hands, I might be unavailable.

**Comment by abasau** [comment]
@nvborisenko Could you please elaborate on why we shouldn't set Defect? Is it because auto-analyzer only works if it's empty? As for me, it would be a disadvantage not to fill Defect messages. It would mean that we won't be able to see error messages right from the summary view and we would have to drill in to see them.
I am curious why it wasn't a issue before. And what was throwing TargetInvocationException and changing Defect message?

**Comment by nvborisenko** [comment]
Seems we have different understanding about `defect` property of test. @DzmitryHumianiuk agent reported defect of test item, and then auto-analyzer overrode it. Do you have recommendations for agents what is "safe" for reporting and what is not.
From my point of view user should be stay in context of test framework. If agent sets defect, autoanalyzer shouldn't touch this test.

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko by default, AA consider for analysis only testItems which has `To Investigate` Defect and `null` as comment.
if you don't ask him any different, in request parameters.

`Null` in comments means that `Defect` object doesn't exists, till the moment it is populated in DB.
Even Defect `To investigate` + comment:`` is a defect. But with type `TI` and empty comment.

AA should not override Defect, in case if it is set by agent or user.

**Comment by DzmitryHumianiuk** [comment]
@abasau there is another way to show error lines at test cases list view:
add description with markdown as (remove underscores):
```
_```error
 com.ta.rp.laucnesh.....
_```

```

![image](https://user-images.githubusercontent.com/11332788/63553500-97e09980-c508-11e9-9538-2346d95f3534.png)

![image](https://user-images.githubusercontent.com/11332788/63553549-c2325700-c508-11e9-953b-c6ec6e855100.png)

**Comment by evjlobanova** [comment]
@IrinaBucsa just switch on Auto-Analysis on the Project settings
