### ISSUE TITLE
JIRA integration: possibility to select issue type

### ISSUE THREAD

**Issue by Rider1982** [reportportal/reportportal#66]
Now JIRA integration allows to post the "Bug" issue type only (detected on integration with jira.epam.com). Out project needs to post the "Defect" (custom?) issue type for automation issues.

**Comment by avarabyeu** [comment]
@DzmitryHumianiuk Could you please handle. Not sure if we really need to support it since different defect types can have different fields, so client will have one more step in project-level configuration page

**Comment by Rider1982** [comment]
In out case we setup integration with RP on existing project with existing processes and rules. We use the issue type "Defect" for automation problems to separate manual and automation bugs. RP requires to use Bugs for registration of problems in JIRA, so if we want to continue collect problem statistics in current manner,  we must convert out defects to bugs or do not use the "Create Bug" feature.

**Comment by DzmitryHumianiuk** [comment]
@Rider1982 this considered to be done.

**Comment by Rider1982** [comment]
I can check it only on EPAM Report Portal instance. At the moment it looks as described.

**Comment by DzmitryHumianiuk** [comment]
@Rider1982 we will refactor JIRA Integration.
Selection of issue will be considered

**Comment by ksuglotova** [comment]
@mva730 asked that feature either: "As RP user I want to post bugs to JIRA with different issue types. But field with issue type selection is not editable."
[Page screen](https://user-images.githubusercontent.com/17176601/27785634-e9cbeea4-5fe6-11e7-984c-46f41d190c68.png)
