### ISSUE TITLE
Reportportal with Selenium Grid

### ISSUE THREAD

**Issue by KunalShokeen432** [reportportal/reportportal#663]
This is not an issue. Just an understanding I need before integrating ReportPortal with Selenium Grid for parallel execution on different machines.

i.e...
If we have a host machine(from where execution is triggered and ReportPortal is hosted) and parallel execution takes place on multiple machines(nodes) via Selenium grid.

After execution does Reportportal create a single launch only on host for all test cases that executed on different nodes ?
All nodes execution --- > Single Launch
or do we have different launches for each execution on node respectively 
Node 1 ---- > Launch 1
Node 2 ---- > Launch 2

If second case,then how can we combine multiple launches in RP in Java + TestNg ?

Thanks,
Kunal

**Comment by KunalShokeen432** [comment]
Can anyone please help with this ?

**Comment by rplevka** [comment]
@KunalShokeen432 I believe this is a question to 
https://github.com/reportportal/agent-java-testNG
as this depends on the individual agent's implementation.

I'm not testNG agent user so I can answer this.

**Comment by KunalShokeen432** [comment]
@rplevka Hi Roman,as you mentioned if it is totally dependent on the agent type(testNg) then just for reference if we are using TestNg + Extent/Allure then all nodes executions are collated in a single report on host.
Shall i consider with Reportportal it will be collated in single launch on host itself ?

**Comment by avarabyeu** [comment]
>xecution takes place on multiple machines(nodes) via Selenium grid

**Comment by KunalShokeen432** [comment]
@avarabyeu It will be executed on different machines(windows/linux) server with one of them being host.

My query was : Will reportportal(is up on host) will collate all the results of executions(on different nodes) in single launch ?

**Comment by rplevka** [comment]
@KunalShokeen432 
> Shall i consider with Reportportal it will be collated in single launch on host itself ?
Given the information you provided - yes, it's the "host" which communicates with report portal.
I'd recommend to give report portal a try (quickly set it up using docker-compose) and see.

**Comment by DzmitryHumianiuk** [comment]
@KunalShokeen432 most likely **"yes"**, it will be one launch (based on your explanation).

Separate you multiply launches, this depend on how your runner handles multi-threading.
It doesn't related to SeleniumGrid at all.
TestNG runner is used, so it only depends how multi-threading organized in it.

In case if it will be multi-launches. then:

**Option1:** call merge request via API, send launch IDs and merge launches in post processing.

**Option2:** extend runner, to read local file with `launchID`, and if it exists, than use this id for reporting.

**Option3:** (will be with v5), you can just point with you runner to append and override results in latest launch.

**Comment by KunalShokeen432** [comment]
@DzmitryHumianiuk Hi,can you please help with below issue as well :
https://github.com/reportportal/reportportal/issues/685

Overall,when RP instance is hosted on AWS, test results are not getting pushed into launches section of RP.

Thanks !
