### ISSUE TITLE
Apply multiple filters in a widget

### ISSUE THREAD

**Issue by tusharkhoche** [reportportal/reportportal#667]
Apply multiple filters in a widget – Currently we can apply only 1 filter in a widget. Currently it is not  possible to have a checkbox instead of a radio button so that multiple filters can be applied in a widget.

https://reportportal.slack.com/archives/C2GTJTTNH/p1563633003010100?thread_ts=1563441347.304900&cid=C2GTJTTNH

**Comment by DzmitryHumianiuk** [comment]
@tusharkhoche multiply filters can have controversial conditions.

What's the reason to have selected 2 or more filters, instead of creation one filter, which can fit multiply?

**Comment by evjlobanova** [comment]
Have been resolved with an adding a possibility to choose 'attribute key' on the widget wizard:
Available for: Cumulative trend chart, Component Health Check Widget.

Also, we think about auto-dashboard  https://github.com/reportportal/reportportal/issues/576

**Comment by idan-marciano-jfrog** [comment]
@DzmitryHumianiuk @evjlobanova What is the status with this feature request? We need that filter will take into account multiple conditions on attribute.
Simple example:
Filter that searches lunches that include "x" attribute but NOT have "y" attribute.
We cannot combine multiple simple and\or operators on filters.

**Comment by DzmitryHumianiuk** [comment]
@idan-marciano-jfrog not yet.
we started to make fundamental tech changes which will bring this capabilities,
but it is not something to be available in a nearest future.
