### ISSUE TITLE
Dashboard setup failure on Windows Docker

### ISSUE THREAD

**Issue by sandy170889** [reportportal/reportportal#669]
Hi All,
Even after multiple attempts I’m not able to setup reportportal dashboard. Could you please help me to debug the root-cause and help with the dashboard setup.
Here is the high level progress:
•    Docker setup - Pre-requisite for Dashboard :
     o    Docker is successfully setup.
     o    I’ve tried installing ngnix webserver and it worked fine.
     o    Docker Version: 17.03.1-ce
     o    Windows version:  Windows 10 Enterprise - 64 bit
•    ReportPortal dashboard :
     o    Its failing at various steps while executing commands.
     o    Please find the attached document for steps and errors screenshots
Major challenges and issues:
•    Windows Docker has two containers options:  Windows and Linux
     o     I’ve tried both options but facing issues.
     o    Could you please confirm which one should be used for reportportal dashboard.
•    Reportportal.io commands are failing:
     o    Initial few errors I’m able to resolve but not sure why exactly setup is throwing those errors and the solution used to resolve them are causing later issues.
     o    Please refer the attached screenshots and logs for more details related to issues.
•    Major roadblocks are:
     o    Not able to share c or d drive
              Tried creating local admin user account as well
              I’ve tried sharing manually using below methods but it does not work
             •    Windows explorer
              •    Docker UI setting
     o    Docker default feature is not working and need to enable Daemon experimental feature
     o    Docker compose file version error:  even though file version is greater than the mentioned one, but still it throws error (I’ve to update manually from 2 to 2.1)
      o    After downloading all the files, it fails at configuration setup part (refer screenshots in attached documents for errors)
[ReportPortalSetup.docx](https://github.com/reportportal/reportportal/files/3421206/ReportPortalSetup.docx)

**Comment by DzmitryHumianiuk** [comment]
@Yumfriez plz take a look

**Comment by Yumfriez** [comment]
1) Mongo volumes cannot be mounted on the external Windows 10 filesystem, so you should replace
![image](https://user-images.githubusercontent.com/31598109/61779892-2975c200-ae0a-11e9-9171-4abda2e0f1aa.png)
with
![image](https://user-images.githubusercontent.com/31598109/61780072-7e193d00-ae0a-11e9-8beb-843a15367d34.png)
and also add this statement in the end of the docker-compose.yml:
![image](https://user-images.githubusercontent.com/31598109/61780552-6db59200-ae0b-11e9-81ad-2ffe46bcb532.png)

2) The problem with elasticsearch 'access denied' error can be resolved by resetting docker credentials and 're-sharing' disk to Docker:
![image](https://user-images.githubusercontent.com/31598109/61781001-3abfce00-ae0c-11e9-8e40-b99a6432adf7.png)
Also you can specify volume mount like:
![image](https://user-images.githubusercontent.com/31598109/61781168-88d4d180-ae0c-11e9-844e-3b52e4c8faa6.png)

P.S. Also you can try create Windows ENVIRONMENT variable  COMPOSE_CONVERT_WINDOWS_PATHS with value 1
or create .env file in the same directory as docker-compose.yml and type:
COMPOSE_CONVERT_WINDOWS_PATHS=1

**Comment by ds12will** [comment]
@Yumfriez - thanks!

I do have a really dumb question how do I define a volume on the virtual machine docker technically runs under in windows 10?

**Comment by Yumfriez** [comment]
@ds12will You can either specify path in the VM or just define a relative path like:

someservice:
   image: someimage:1.0
   volumes:
          - **./folder/anotherfolder**:/path/in/the/docker/container
If your Docker runs in the VM, folder will be created in it relatively to the docker-compose.yml file
