### ISSUE TITLE
Possibility to report test items with code reference (location in code)

### ISSUE THREAD

**Issue by evjlobanova** [reportportal/reportportal#671]
## Description
 **As a User** I view test code reference in ReportPortal and can easily copy  from RP
 **So that**  I can quickly find needed test case f.e. in IDF Idea. 
 **For that**  I should go on:
 - Step view and open test editor
 - Log view and open Item Detail tab

## Reporting via API
request
Test itemm controller
POST/{projectName}/item
```
{
  "attributes": [
    {
      "key": "string",
      "system": true,
      "value": "string"
    }
  ],
  "description": "string",
  "hasStats": true,
  "launchId": "string",
  **"codeRef": "string",**
  "name": "string",
  "parameters": [
    {
      "key": "string",
      "value": "string"
    }
  ],
  "retry": true,
  "startTime": "2019-07-25T10:00:08.120Z",
  "type": "SUITE",
  "uniqueId": "string"
}
```

Available for JAVA agents

![image](https://user-images.githubusercontent.com/30413511/61865652-44186b80-aedc-11e9-993d-8d57524eff66.png)
![image](https://user-images.githubusercontent.com/30413511/61865665-4c70a680-aedc-11e9-812f-abea3ee971f9.png)

**Comment by evjlobanova** [comment]
Will be available in the beta release of version 5.

**Comment by nvborisenko** [comment]
Would it be better to send this location info as user defined test attributes? It seems this property is a part of request model, so API will be broken if we need to add more attributes like this. For instance it would be nice to see the line number in code file where test is located. To support it API is going to be changed.
If API takes these attributes in map object, we don't require to update clients. API may reserve some attribute keys like 'codeRef' to show them on UI.

There are many attributes that I would to see: 'sourceCodeRef', 'targetFramework', 'testRunnerName', 'testRunnerVersion'... many attributes. I see that agent can provide these attributes/metadata in 'attributes' json property, I am going to use it. And question: is it possible to search test items by attributes? Thanks.
