### ISSUE TITLE
Possibility to change test item status

### ISSUE THREAD

**Issue by evjlobanova** [reportportal/reportportal#672]
## Description
**As a user** I want to change the status of the test item (step). 
 **So that** the statistic of the parent (test, suite, launch) items should be re-calculating.
 **For that** I should change test item on Step level 
![image](https://user-images.githubusercontent.com/30413511/61866647-3663e580-aede-11e9-829a-6d325a4b74bf.png)

Add possibility to change status from:
 - From Passed to Failed, Skipped;
 - From Failed to Passed , Skipped;
 - From Skipped to Passed, Failed;
 - From Interrupted to Skipped, Passed, Failed;
**Permissions**
All users can perform this action

## How it works
**Scenario: From Passed to Failed;**
![image](https://user-images.githubusercontent.com/30413511/61866161-59da6080-aedd-11e9-8359-1002c34cf275.png)
**Scenario: From Failed to Passed**
![image](https://user-images.githubusercontent.com/30413511/61866178-61016e80-aedd-11e9-9014-b4f0ed39c8e8.png)
**Scenario: From Passed to Skipped**
In case Skipped item can have defect type (parent launch has SYSTEM attribute "skipperd:true"), the flow should be the same as for "Scenario: From Passed to Failed"
In case Skipped item can not have defect type (parent launch has SYSTEM attribute "skipperd:false"), for item should be changed only status of test item and statistics (status) of parent items;
**Scenario: From Failed to Skipped**
In case Skipped item can have defect type (parent launch has SYSTEM attribute "skipperd:true"), for item should be changed only status of test item, statistics (status) of parent items, (in case Failed items has defect type, it should be saved for Skipped )
In case Skipped item can`t have defect type(parent launch has SYSTEM attribute "skipperd:false"), the flow should be the same as for "Scenario: From Failed to Passed";

## API for functionality
Test Item Controller PUT/{projectName}/item/{itemId}/update
```
 { "attributes": [ { "key": "string", "value": "string" }],
"description": "string",
"status": "PASSED"
}
```
## Aditional information
1. User cannot changed status from Skipped, Passed, Failed to Interrupted;
2. Information about availability of defect types of skipped items should be taken from launch attributes (skipped:false/true).
3. If launch doesn`t have such parameter, default value: Skipped has defect type (parent launch has SYSTEM attribute "skipped:true")
4. Test item status can not be updated for test item in progress. 
via API: "Error: can not be performed"
via UI: operation should be disabled
5. Not possible via mobile version

**Comment by evjlobanova** [comment]
In the beta release of version 5 will be available this functionality on via API, in final version UI will be ready as well.

**Comment by DzmitryHumianiuk** [comment]
## Resolution: done
