### ISSUE TITLE
[v5bug] Unnessassery scroll bar in a list of projects

### ISSUE THREAD

**Issue by Kira-Lappo** [reportportal/reportportal#676]
Horizontal scrollbar appears in the list of projects.

1. Click on project button
1. Dropdown appears with the list of projects.

**Expected**: it's enough space for name of projects, no scrollbar should be inside of dropdown
**Actual**: scrollbar appears at mouse over the dropdown element.

![image](https://user-images.githubusercontent.com/11411852/62272680-45014e00-b444-11e9-9de0-449e6c6f76c0.png)

 - OS: windows 10 1903
 - Browser: Google Chrome
 - Version: 75.0.3770.142

**Comment by RPgitHubTestUser** [comment]
@Kira-Lappo I suppose you are using browser scale less than 90%
![image](https://user-images.githubusercontent.com/22913350/62290600-6117e600-b46a-11e9-80f0-799fcd9d9460.png)
Try to change scale to 100%

**Comment by Kira-Lappo** [comment]
@RPgitHubTestUser in google chrome I have 100% scale, in yandex-browser I have 100% scale and 16 font size, but having the issue in both of them.
May be my system interface scaling affects projects dropdown, idk really...

**Comment by Kira-Lappo** [comment]
@RPgitHubTestUser here are my settings
![image](https://user-images.githubusercontent.com/11411852/62357505-e60f0800-b51b-11e9-9b88-46d7900ad3b5.png)

**Comment by Kira-Lappo** [comment]
@RPgitHubTestUser  yep, I set `size of text` to 225 % and scrollbar disappeared
Seems like it is a rare issue for specific system settings

**Comment by RPgitHubTestUser** [comment]
Could I close this issue?

**Comment by Kira-Lappo** [comment]
I think so. If it becomes a problem, users will open another bug.
