### ISSUE TITLE
[v5bug] Incorrect error message for incorrect user credetials

### ISSUE THREAD

**Issue by Kira-Lappo** [reportportal/reportportal#677]
User see non-informational message at entering incorrect credentials.

1. Navigate to login page.
1. Input incorrect credentials.

Expected: User sees "Incorrect username or password" messages
Actual: User sees "An error occurred while connecting to server: Unclassified error [null]"

![image](https://user-images.githubusercontent.com/11411852/62273065-497a3680-b445-11e9-9ea8-7ac17a875347.png)

 - OS: windows 10 1903
 - Browser Google Chrome
 - Version 76

**Comment by RPgitHubTestUser** [comment]
Fixed
