### ISSUE TITLE
"No Defect" column is needed in Lauches table (hidden defects)

### ISSUE THREAD

**Issue by Rider1982** [reportportal/reportportal#68]
There is "No Defect" column needed in Launches table. Story:
1. Test failed
2. At investigation moment the found problem is not reproducible
3. Autotetster marks fail as "No Defect"
4. The problem continues to reproduce later
RP does not show the "No Defect" column, but the problem still be "No Defect" (due to auto analyzis) and stay hidden from statistics in Launches table.

**Comment by DzmitryHumianiuk** [comment]
This will be covered with parent line in design of version 3.0.
Parent line will be extended with`No Defect` item

**Comment by DzmitryHumianiuk** [comment]
`No defect` will not be populated by auto-analysis for the next launch

**Comment by DzmitryHumianiuk** [comment]
@Rider1982 
can this help?
![image](https://cloud.githubusercontent.com/assets/11332788/24112158/a9901e62-0da9-11e7-9e3b-00c8fccabc7a.png)

**Comment by DzmitryHumianiuk** [comment]
@Rider1982 ??

**Comment by DzmitryHumianiuk** [comment]
@Rider1982 proposed representation good enought?

**Comment by Rider1982** [comment]
Yes.
