### ISSUE TITLE
Plugin system. Upload plugin/ Configure plugin/ Update plugin/ Uninstal plugin

### ISSUE THREAD

**Issue by evjlobanova** [reportportal/reportportal#680]
You can integrate ReportPortal with different external systems:
- Jira 
- Rally 
- Sauce Labs #348 (here you can find description for Saucelabse integration)
- Saml (will be implemented in version 5.0 Final)

## Upload plugin
**As a Admin** I can add new  plugins to ReportPortal;
**So that** I can extend the functionality of the application;
**For that** I should:

- come on Admin> Plugin
- click on button Upload
- choose .jar file which should be uploaded;
- and click Upload

.Jar files for plugins
[Jira](https://bintray.com/beta/#/epam/reportportal/plugin-bts-jira?tab=overview)
[Rally](https://bintray.com/beta/#/epam/reportportal/plugin-bts-rally?tab=overview)
[SauceLabs](https://bintray.com/beta/#/epam/reportportal/plugin-saucelabs?tab=overview)

![image](https://user-images.githubusercontent.com/30413511/62381732-c811c980-b554-11e9-8e2a-0d6f712b0267.png)
![image](https://user-images.githubusercontent.com/30413511/62381743-cfd16e00-b554-11e9-9ecb-86ea7a21483c.png)
![image](https://user-images.githubusercontent.com/30413511/62381799-eaa3e280-b554-11e9-8792-76a7f23be760.png)
![image](https://user-images.githubusercontent.com/30413511/62381994-5ab26880-b555-11e9-98d6-15ee89146501.png)

**Uploading/Update plagin process**
![image](https://user-images.githubusercontent.com/30413511/62381872-17f09080-b555-11e9-9510-3a2932c21b58.png)

If you want to update the existing plugin, upload a new .jar file, and the system automatically updates the plugin with the same type.

## Configure plugin
You can configure for the whole Report Instance in the tab Plugins
![image](https://user-images.githubusercontent.com/30413511/62382333-065bb880-b556-11e9-87b2-e7a464d52b12.png)

Or you can specify the special configuration for each project via Project settings > Integration tab
![image](https://user-images.githubusercontent.com/30413511/62382423-3014df80-b556-11e9-9105-ad813e08d68d.png)
If you have configured integration for the project, global configurations will be ignored for that project. 

## Uninstall plugin 
**As a User** I   remove plugin from system.
**So that** I can allocate more space on the memory.
**For that**  I should come to Admin > Plugin tab > Plugin > Plugin details and click button Uninstal
![image](https://user-images.githubusercontent.com/30413511/62382279-e926ea00-b555-11e9-896b-b7c6b1034846.png)

**Comment by RG108** [comment]
I am experiencing an issue wherein I am getting an error while uploading the Jira jar file from the same source as mentioned above.
unable to upload the plug-in id -Jira 
tried with the latest jira jar file i.e. 5.1 but same fate :( 
@evjlobanova  Please let me know if you have answer for above issue. I am using latest report portal 5.0

**Comment by allanbeumer** [comment]
Uploading the jira plugin does not work here, filename is "plugin-bts-jira-5.1.0.jar" but reportportal error is "Error during plugin uploading: 'Plugin version should be specified.' What am I missing here?

**Comment by gunjan-sap** [comment]
> Uploading the jira plugin does not work here, filename is "plugin-bts-jira-5.1.0.jar" but reportportal error is "Error during plugin uploading: 'Plugin version should be specified.' What am I missing here?

I am also getting the same issue. I have downloaded the latest plugin-bts-jira-5.7.4.jar available. Any known solution for this?
