### ISSUE TITLE
coldparadise

### ISSUE THREAD

**Issue by cold1111** [reportportal/reportportal#681]
hi i swith from ally to horde and i have all ally mounts pvp titles pls fix it thx 
...

**Expected behavior**
...

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

**Comment by DzmitryHumianiuk** [comment]
@cold1111 could you please be more specific with details?

**Comment by DzmitryHumianiuk** [comment]
resolution: closed.
