### ISSUE TITLE
coldparadise #2

### ISSUE THREAD

**Issue by cold1111** [reportportal/reportportal#682]
hi i swap from ally to forde pay 500 mps , after this my mage can teleport to ally stormwind ,ironforge , use only ally mounts , pvp titles, medalion of the aliance instand of the horde...i make a ticket in  1 mint metaxa come try to help me, swap me back to ally and horde after  i notice i lost half on my mounts (mounts with pvp tokents and more)where 156-158 now i have 85,lost exalted reputation ,achievement points from 7000k + to 6640, and i think are more problems ..after this told me to dont wory tomorrow he will help fix it .Saturday was the same make another ticket for answers to metaxa ...he maill me to contact janitor on discord , i dont know how to contact him .. send another ticket ! answer Aymelek told me to contact metaxa .. i wont make more tickets they will send me one to another and wont fix my little mage(coldparadise name in game).. i get mad and dicide to delete my acc i cant play with pleasure anymore ! pls who know janitor report this to him more i cant do or say i will w8 the result max 1 week
If applicable

![WoWScrnShot_080419_194418](https://user-images.githubusercontent.com/53626530/62426837-10d59980-b69f-11e9-8650-fdcc23da8b60.jpg)
![WoWScrnShot_080419_194440](https://user-images.githubusercontent.com/53626530/62426838-116e3000-b69f-11e9-97b3-025e10260ffa.jpg)
![WoWScrnShot_080419_194455](https://user-images.githubusercontent.com/53626530/62426839-116e3000-b69f-11e9-88a3-86ec61549038.jpg)
![WoWScrnShot_080419_194510](https://user-images.githubusercontent.com/53626530/62426840-116e3000-b69f-11e9-93b6-6bfca5cffca1.jpg)
![WoWScrnShot_080419_194539](https://user-images.githubusercontent.com/53626530/62426841-116e3000-b69f-11e9-88f5-393533015ee6.jpg)
![WoWScrnShot_080419_194353](https://user-images.githubusercontent.com/53626530/62426842-116e3000-b69f-11e9-96c3-05030faa0fd7.jpg)
![WoWScrnShot_080419_194357](https://user-images.githubusercontent.com/53626530/62426843-1206c680-b69f-11e9-8c89-e17d35c590cd.jpg)
![WoWScrnShot_080419_194405](https://user-images.githubusercontent.com/53626530/62426844-1206c680-b69f-11e9-82c5-c439353be5dc.jpg)

**Comment by Legionivo** [comment]
Hello @cold1111, support team is here. Thank you very much for contacting us. We will do our best in order to help you. 
In order to identify that this ticket is really submitted by you, could you please attach login password of your account, written on a piece of paper which you're holding in front of mirror?  

Thank you very much @cold1111

**Comment by cold1111** [comment]
i wont add my password!

**Comment by Legionivo** [comment]
Hello again @cold1111, following our strict policies unfortunately I have to say that without this information our support team will not be able to identify you as real account owner.
Account is going to be completely blocked until the real owner will not contact us via support ticket and will not pay penalty. 
Please use the following ticket number in all further communications - #loh9emmnt.
Thank you very much @cold1111.

**Comment by cold1111** [comment]
do what you have to do block, ban if u have the tools, servar owner or gms in game will never ask  for password so pls dont write here thx for understanding

**Comment by nvborisenko** [comment]
@cold1111 you wrote to incorrect support channel, please verify it. This thread is not related to gaming.

**Comment by cold1111** [comment]
ok i withdraw my words

**Comment by DzmitryHumianiuk** [comment]
@cold1111 
After a long discussion, we think that if you have such a problem - then you should not play this game. 
We just want you to have a happy life, you spend time learning, find a partner, have beautiful babies, drove to nature and walked with the dog. 
Finally, learn how to program and become a good test automation engineer, and contribute into ReportPortal

P.s. Wrong channel.
This github organization related to http://ReportPortal.io
