### ISSUE TITLE
[v5bug] Postgres issue on Windows10

### ISSUE THREAD

**Issue by z41** [reportportal/reportportal#686]
**Describe the bug**
if you try to use a default docker-compose.yml on Windows10, you'll face a known issue with Postgres:

> FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
> HINT:  The server must be started by the user that owns the data directory.

https://github.com/docker-library/postgres/issues/435

Using a named volume is a known workaround. Nothing about this in documentation. I think it worth adding something

**Desktop (please complete the following information):**
Windows10

**Comment by DzmitryHumianiuk** [comment]
thank you, will be added into v5 installation on Win

**Comment by netsrotr** [comment]
Is there any date the v5beta goes public? I really would like to use the postgres docker image on windows too...

**Comment by DzmitryHumianiuk** [comment]
@netsrotr version 5.0.0 was already released. https://github.com/reportportal/reportportal/releases/tag/5.0.0
