### ISSUE TITLE
Implement sticky tagging 

### ISSUE THREAD

**Issue by pondrejk** [reportportal/reportportal#688]
**Describe the solution you'd like**

If a test result was assigned a defect type in a previous launch and it fails in the current launch with the same problem, it is likely that the defect type is the same as before. With sticky option enabled the defect type would be inherited from the previous launch if the result is the same.

**Is your feature request related to a problem? Please describe.**
Having to revisit "to investigate" test failures each launch even if these are known problems generates additional legwork.

**Comment by pondrejk** [comment]
just realized there is "send effect to" button which is great, but even better would be to do it automatically if the result is the same (possibly as an optional checkbox)

**Comment by DzmitryHumianiuk** [comment]
@pondrejk we have Auto-Analysis, which is ML based for this.
'Sticky issue' implemented via boost ratio coefficients for same test case.

give it a try.
