### ISSUE TITLE
Qst: My RF test cases are passed but should be failed

### ISSUE THREAD

**Issue by kingages** [reportportal/reportportal#689]
Hi,
I'm new in using ReportPoratl but I've write simple robotframework tests as example for this issue I have.

```
*** Settings ***
Library  Selenium2Library

Test Teardown  Close browser

*** Test Cases ***
Open google and fill search pass
    Open browser  http://www.seznam.cz  chrome
    Page should contain element  //*[@class="szn-input-with-suggest-list search-form__input input input--hp-search"]



Open google and fill search fail
    Open browser  http://www.seznam.cz  chrome
    Page should contain element  //*[@class="szn-input-with-suggest-list search-form__input input input--hp-search xcxccxxxc"]

```

First test is passing and second failing but in ReportPortal are both passed.

![image](https://user-images.githubusercontent.com/26042586/62728078-263e2100-ba1b-11e9-9fcc-71ececcfd30e.png)

If I open test that should fail I see this:
![image](https://user-images.githubusercontent.com/26042586/62728168-600f2780-ba1b-11e9-8677-d503f9422192.png)

But when I open failed step I see this:

![image](https://user-images.githubusercontent.com/26042586/62728247-96e53d80-ba1b-11e9-879b-ef8fa0dc772c.png)

Witch is good because it took screenshot but test case have to be failed.

```
> robot --listener robotframework_reportportal.listener --variable RP_UUID:0fe489c7-7598-4uo7-9uaf-460049jkd54f --variable RP_ENDPOINT:http://localhost:8080 --variable RP_LAUNCH:RF_Test_Run --variable RP_PROJECT:smart testReportPortal.robot 
> ==============================================================================
> testReportPortal                                                              
> ==============================================================================
> Open google and fill search pass                                      | PASS |
> ------------------------------------------------------------------------------
> Open google and fill search fail                                      | FAIL |
> Page should have contained element '//*[@class="szn-input-with-suggest-list search-form__input input input--hp-search xcxccxxxc"]' but did not.
> ------------------------------------------------------------------------------
> testReportPortal                                                      | FAIL |
> 2 critical tests, 1 passed, 1 failed
> 2 tests total, 1 passed, 1 failed
> ==============================================================================
> 
```

I use libraries.
robotframework-selenium2library 3.0.0 
robotframework-reportportal     3.0.0 
reportportal-client             3.2.0 

May please help me why is this happening? Thank you for any advice.

**Comment by kingages** [comment]
Nobody can help me?

**Comment by digaetan** [comment]
Hi,

I just introduced the usage of Report Portal in a large project in my company and Robot Framework is our main TA Framework, we use below versions and I have not faced the same issue as you:
robotframework==3.1.1
robotframework-seleniumlibrary==3.0.0
robotframework-async==1.0.3
robotframework-requests==0.5.0
robotframework-reportportal-ng==1.0.4.9
reportportal-client==3.2.0  # via robotframework-reportportal-ng
requests==2.21.0          # via reportportal-client, robotframework-requests

**Comment by kingages** [comment]
> Hi,
> 
> I just introduced the usage of Report Portal in a large project in my company and Robot Framework is our main TA Framework, we use below versions and I have not faced the same issue as you:
> robotframework==3.1.1
> robotframework-seleniumlibrary==3.0.0
> robotframework-async==1.0.3
> robotframework-requests==0.5.0
> robotframework-reportportal-ng==1.0.4.9
> reportportal-client==3.2.0 # via robotframework-reportportal-ng
> requests==2.21.0 # via reportportal-client, robotframework-requests
> 
> And I have below Report Portal version in use:
> Analysis Service: 4.3.0
> API Service: 4.3.4
> Index Service: 4.2.0
> Jira Service: 4.3.0
> Authorization Service: 4.2.0
> Service UI: 4.3.6;

Thank you. I tried robotframework-seleniumlibrary==3.0.0 and it's working with it. I also tried 3.1.0 and with this version it's not working.
