### ISSUE TITLE
Issue in reportportal V5 Login

### ISSUE THREAD

**Issue by ghost** [reportportal/reportportal#692]
Hi All,

I have successfully installed the report portal v5 in Mac Laptop  (High Sierra ,Version 10.13.6).When I am running first time after installation then it is working fine but when I am resting the docker or Mac machine after that unable to sign in or Login screen is not loading .I have tested this issue in multiple mac machine .

Need a solution of it ASAP.

**Comment by moinuddin14** [comment]
You need to provide more details for anyone to be able to help you. Check in chrome dev tools and see what errors you are getting, or try to clear the cache and try again to login, try on different browser and see if its the same problem.

**Comment by evjlobanova** [comment]
I close an issue because of lack of details. 
Please, if need a help, feel free to reopen it

**Comment by Kanhaiya1k** [comment]
Getting same issue on mac, this url **http://localhost:8080/ui/** showing loading...

**Comment by sheeik89** [comment]
Gertting the same issue on Windows.. the login page remains loading

**Comment by sheeik89** [comment]
Getting the same issue on windows.. the login page remains loading..

**Comment by avaparna-max** [comment]
i am also getting same issue
<img width="1440" alt="Screenshot 2022-08-31 at 3 21 49 AM" src="https://user-images.githubusercontent.com/81403537/187550193-fbea4697-4206-4065-9c4e-be668f286bef.png">

**Comment by assiakhateeb** [comment]
@avaparna-max how did you solve the issue?
