### ISSUE TITLE
The link of test steps just reload current page

### ISSUE THREAD

**Issue by Aynur11** [reportportal/reportportal#698]
Repro steps:
1. Open some lauch
2. Open some Suite
3. Try to open any Test

Expected: Test steps will be opened correctly

Actual: The current page just will be reloaded

Workaround:
Click the link of current launch that is on the header (All > MyLaunchName > ...). Then all test step links work correctly.
Sometimes reset helps.

Notes:
The problem is reproduced not all the time.

Versions:
 - Windows 10, Chrome, Opera
 - RP 4.3.7

**Comment by evjlobanova** [comment]
@Aynur11 we have fixed this bug in version 5
