### ISSUE TITLE
Test Framework Integration docs are out-of-date

### ISSUE THREAD

**Issue by abotalov** [reportportal/reportportal#699]
**Describe the bug**
Test framework integration docs (https://reportportal.io/docs) are out-of-date, at least for Ruby.

**Expected behavior**
These docs are either removed or are synced from agent documentation (e.g. from READMEs).

**Comment by evjlobanova** [comment]
We have updated doc on reportportal.io and transfere all integration staff directly to agent repositories https://reportportal.io/docs/Log-Data-in
