### ISSUE TITLE
No 'history view' button if launch is moved to DEBUG 

### ISSUE THREAD

**Issue by JustasM11** [reportportal/reportportal#70]
History button disappears after run is moved to DEBUG mode.
I want to see history of runs during issue analysis:
![debug](https://cloud.githubusercontent.com/assets/12593214/22153109/f09f9df6-df36-11e6-8ac7-312ccc157cf8.png)

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 
Work as desired

History button removed from `Debug Mode`. This is done intentionally.

Could you please describe your use case?

**Comment by JustasM11** [comment]
@DzmitryHumianiuk 
My use case is:
We have several team members and many nightly/weekly jobs (~12 jobs every night with total ~1200 TCs every night). Every day there are 3-5-10 failed issues that needs to be investigated.
We tried RP in hope that it will help us to solve 2 problems:
1) Easily track investigation results: we strive to have zero non-triaged failures
2) Easily submit investigation results
3) Ease communication between QA members while assigning tasks for investigation and distributing investigation efforts.

First two problems were solved, at least partially: +light and fast web client, +multiselect/edit, +custom DE types (of course with issues: -ugly logs, -RP was designed to work with only one unique test run).
We are trying to solve third problem with DEBUG mode: if run is added to DEBUG mode it is under investigation and locked by some team member. So while investigation I store run in DEBUG mode.

**Comment by JustasM11** [comment]
Additionally we see lack of callbacks that may be assigned to events of changing TC state. For example, we need to update our custom bug tracking system and attach failed test run after found issue.

**Comment by JustasM11** [comment]
What is the purpose for DEBUG mode then?

**Comment by JustasM11** [comment]
@DzmitryHumianiuk What is the purpose for DEBUG mode then?

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu that's for you
>Additionally we see lack of callbacks that may be assigned to events of changing TC state. For example, we need to update our custom bug tracking system and attach failed test run after found issue.

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 initial idea for the `Debug` was like to hide invalid execution from the finite work (launches tab).
Launches in `Debug` will not be shown in widgets/dashboards, will not be counted in auto-analysis and will not affect overall project state.
This also can be used for experimental executions (`rp.mode = DEBUG`) to avoid the mess in launches.

that was not for locking or investigation purpose.

**Does additional defect types solves the assignment issue?**

**Comment by DzmitryHumianiuk** [comment]
close with no response.
details above
