### ISSUE TITLE
Query launches within given time window + launches in progress

### ISSUE THREAD

**Issue by ekisielinski** [reportportal/reportportal#704]
I want to get all launches with specific criteria:

- start time >= date1 && end time <= date2
OR
- start time >= date1 && end time = null (in progress)

Is it possible to do it in one request?

**EDIT:**
Also I cannot create Filter with logic for: **end_time == null**. It says bad request or something.

C#:
`new Filter (FilterOperation.Equals*???*,  "end_time",   null*???*));`

**Comment by nvborisenko** [comment]
@DzmitryHumianiuk is it possible on API layer?

**Comment by DzmitryHumianiuk** [comment]
@ekisielinski @nvborisenko 
yes.

**v4**
```
# Dynamic range
/api/v1/project/launch?filter.btw.start_time=-83913;14007;+0300

# Solid range
/api/v1/project/launch?filter.btw.start_time=1568062800000,1568126783000
```


**v5**
```
# Dynamic range
/api/v1/project/launch?filter.btw.startTime=0;1070;+0300

# Solid range
/api/v1/project/launch?filter.btw.startTime=1568062800000,1569532500000
```


In case of **solid range** just linux time timestamps FROM-TO
in case of **dynamic range** `filter.btw.startTime=N;M;T` where
`N` = number of minutes to shift from NOW(), equal to `TO` in range
`M` = number of minutes to shift from NOW(), equal to `FROM` in range
`T` = time zone shift. GMT+3 equals to `+0300`

**Comment by ekisielinski** [comment]
OK, I'll check it soon. Don't close it yet :)

**Comment by svettsova** [comment]
@ekisielinski could you try it in version 5.0? 
You can set a custom range of filter and input current date to "TO" field and enable the "Dynamic update" to see launches "in progress"

**Comment by rahulbhaviri** [comment]
@svettsova Tried this on v5: "http://10.51.52.44:8080/api/v1/mindtickle-api-automation/launch?filter.btw.startTime=0;120;+5"
Still the same error: "{
    "errorCode": 40011,
    "message": "Incorrect filtering parameters. Incorrect zoneOffset. Expected='+h, +hh, +hh:mm'. Provided value is ' 5'"
}"

Is it possible, the "+" sign is not recognisable? Even in the error "+" sign is omitted.

**Comment by svettsova** [comment]
@rahulbhaviri please try to change '+5' to '+0500'

**Comment by rahulbhaviri** [comment]
Same error 
{
    "errorCode": 40011,
    "message": "Incorrect filtering parameters. Incorrect zoneOffset. Expected='+h, +hh, +hh:mm'. Provided value is ' 0500'"
}

**Comment by yay14** [comment]
@svettsova Is this issue fixed, I am getting this in the latest version, please help.
