### ISSUE TITLE
[v5bug] agent-java-testng-5.0.0-BETA-6 with Logback failed to create SUITE & its child

### ISSUE THREAD

**Issue by arunkumar-muthusamy** [reportportal/reportportal#709]
**Describe the bug**
Java+TestNG+Logback failed to create SUITE and further child entities. I'm running with two threads in TestNG.xml. 

I did some digging and here is the reason for failure, 
```
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'launchId' should not contain only white spaces and shouldn't be empty.] 
Error Type: INCORRECT_REQUEST
```
![image](https://user-images.githubusercontent.com/47788194/64729788-dfc16380-d4ab-11e9-8271-d26ef6822db4.png)

_Note: Launch is created successfully and I can able to see the launch in UI. Screenshots given below._

**To Reproduce**
Run any tests Java+TestNG+logback, only launch will be created. There will not be any other child entities.

**Expected behavior**
Launch should have the child entities SUITE > TEST > METHOD > LOGS

**Screenshots**
Start Launch
![image](https://user-images.githubusercontent.com/47788194/64729236-c4098d80-d4aa-11e9-9e0c-56b2379e2013.png)
![image](https://user-images.githubusercontent.com/47788194/64729387-0d59dd00-d4ab-11e9-9837-9e076eb3f56b.png)

Start Suite:
![image](https://user-images.githubusercontent.com/47788194/64729527-51e57880-d4ab-11e9-888b-5cf09ca20ee1.png)

![image](https://user-images.githubusercontent.com/47788194/64729645-8ce7ac00-d4ab-11e9-828a-7dd86ad61acd.png)

![image](https://user-images.githubusercontent.com/47788194/64729788-dfc16380-d4ab-11e9-8271-d26ef6822db4.png)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version [76]

**Additional context**
This is happening while running Java TestNG with logback.
**pom.xml**
```
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-testng</artifactId>
			<version>5.0.0-BETA-6</version>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>logger-java-logback</artifactId>
			<version>5.0.0-BETA-4</version>
		</dependency>
```
**TestNG.xml**

```
<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite" parallel="classes" thread-count="2" data-provider-thread-count="2">
	<listeners>
		<listener class-name="com.ctm.nexgen.listeners.AlterSuiteListener" />
		<listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener" />
	</listeners>
	<test name="mavtest">
		<method-selectors>
			<method-selector>
				<script language="beanshell">
                <![CDATA[packageName = System.getProperty("packageName");
                method.getDeclaringClass().getPackage().getName().contains(packageName);]]>
				</script>
			</method-selector>
		</method-selectors>
		<packages>
			<package name="com.od.example.*" />
		</packages>
	</test>
</suite>
```

**Comment by DzmitryHumianiuk** [comment]
@arunkumar-muthusamy same issue when you run in 1 thread?

**Comment by arunkumar-muthusamy** [comment]
@DzmitryHumianiuk ,  Did you get chance to look in to this issue?

**Comment by Yumfriez** [comment]
@arunkumar-muthusamy New beta instance version should be released soon. This issue will be fixed. I will acknowledge you when to run your tests again.

**Comment by arunkumar-muthusamy** [comment]
@Yumfriez , Did we have any ETA for the next beta release which will fix this issue? Thanks!

**Comment by DzmitryHumianiuk** [comment]
@arunkumar-muthusamy already released
available at https://beta.demo.reportportal.io

**Comment by arunkumar-muthusamy** [comment]
After upgrading, I'm not able to login to the portal. I used default credentials **superadmin\erebus**. This is blocking me to test the actual issue!

![image](https://user-images.githubusercontent.com/47788194/66062859-33a1f400-e510-11e9-82ea-45739eae2a31.png)

Note:

Token Call is successful:
![image](https://user-images.githubusercontent.com/47788194/66063436-58e33200-e511-11e9-832c-9bed5d9f7237.png)


All services are running healthy while checking from console...
```
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS                   PORTS                                                                                        NAMES
8a1f179a969d        reportportal/service-index:5.0.3                          "/service-index"         7 minutes ago       Up 7 minutes             8080/tcp                                                                                     reportportal_index_1
9020315a2633        reportportal/service-api:5.0.0-BETA-12                    "/start.sh"              7 minutes ago       Up 7 minutes             8080/tcp                                                                                     reportportal_api_1
f5aa714f80c0        reportportal/service-analyzer:5.0.0-BETA-4                "/service-analyzer"      7 minutes ago       Up 7 minutes             8080/tcp                                                                                     reportportal_analyzer_1
922e9555548b        reportportal/service-authorization:5.0.0-BETA-12          "/start.sh"              7 minutes ago       Up 7 minutes             8080/tcp                                                                                     reportportal_uat_1
d42df3c9f178        rabbitmq:3.7.16-management                                "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes (healthy)   4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   reportportal_rabbitmq_1
2f59f64d6561        reportportal/service-ui:5.0.0-BETA-12                     "/service-ui"            7 minutes ago       Up 7 minutes             8080/tcp                                                                                     reportportal_ui_1
bff8cdee3105        docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1   "/usr/local/bin/dock…"   7 minutes ago       Up 7 minutes (healthy)   0.0.0.0:9200->9200/tcp, 9300/tcp                                                             reportportal_elasticsearch_1
b2a2057f1ef8        traefik:1.7.12                                            "/traefik --docker -…"   7 minutes ago       Up 7 minutes             80/tcp, 0.0.0.0:4444->8080/tcp, 0.0.0.0:443->8081/tcp                                        reportportal_gateway_1
89fa5f8cccc6        postgres:11-alpine                                        "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes (healthy)   0.0.0.0:4445->5432/tcp                                                                       reportportal_postgres_1

```

**Comment by DzmitryHumianiuk** [comment]
@arunkumar-muthusamy 
clean database completely. it has changes.

and 
```
API Service: 5.0.0-BETA-13
Service UI: 5.0.0-BETA-14
```

make a quick try at beta instance, login with github https://beta.demo.reportportal.io

**Comment by arunkumar-muthusamy** [comment]
@DzmitryHumianiuk , i see the original issue is fixed. I'm able to see all child entities as expected. I tested through https://beta.demo.reportportal.io 

On my setup, i still see the same error. i will change to the version you mention and try it out. BTW, i did clean reinstall (deleted all old data)..

![image](https://user-images.githubusercontent.com/47788194/66068991-8a152f80-e51c-11e9-80ca-0fcb6502153e.png)

**Comment by DzmitryHumianiuk** [comment]
@arunkumar-muthusamy are you in our slack?
find me (ghdmitry) and `Ivan Budaev` for help with deploy.

assume issue fixed, for initial request

**Comment by arunkumar-muthusamy** [comment]
Sure, thanks @DzmitryHumianiuk !!
