### ISSUE TITLE
Sending log reports from external dependency

### ISSUE THREAD

**Issue by nlipkow** [reportportal/reportportal#710]
We define our steps in another module and include them as a dependency in the module where the cucumber feature are being executed. Is there a smart solution to that problem? Because we want to log and send screenshots which is being done within the steps of the external dependency. Thanks in advance!

**Comment by nlipkow** [comment]
Thank you for your answer! The steps, including the logging (the `ReportPortalLog4j2Appender`) are "glued" to the starting method to our starting point from an external dependency. I just thought it might cause trouble as the Appender probably won't have the correct `ReportPortal` instance to call its `emitLog()` method. Sorry if I am phrasing my problem incomprehensible. 

Or am I understanding something wrong? The attachements I log don't reach my ReportPortal application.

```@RunWith(Cucumber.class)
@CucumberOptions(
        strict = true, // true (will fail execution if there are undefined or pending steps)
        monochrome = true, // Output on console is readable
        // dryRun = true,
        tags = { "~@skip" },
        plugin = { "pretty", "html:target/cucumber-results/chrome", "json:target/cucumber.json", "com.epam.reportportal.cucumber.StepReporter" },
        glue = { "com.dummy.qa.acceptancetest.steps", "com.dummy.qa.acceptancetest.configuration.steps" },
        features = {
                "classpath:com/dummy/qa/acceptancetest/features/"
        })
public class RunChromeAcceptanceTests {

    @BeforeClass
    public static void setup() {
        System.setProperty("spring.profiles.active", "chrome");
    }

}```

**Comment by DzmitryHumianiuk** [comment]
@nlipkow right, if you bypass logging to another context, then it doesn't have access to active test structure from agent.
Since appender should know ID of test case, from agent, where he should report.

With version 5 we allow to report data (logs and attachement) even into closed items.
So, you can initiate log posting in dependant method, just pointing it to the right test item ID

make sense?
