### ISSUE TITLE
[v5bug] LDAP manager password shouldn't be hashed

### ISSUE THREAD

**Issue by strangeman** [reportportal/reportportal#713]
**Describe the bug**
If I set a Manager password in the settings, it stored in DB in the hashed form. Then, during authorization, this password sent to LDAP in the same hashed form, which leads to 'Bad credentials' error, because LDAP waits for the clear password.

Also, if I save LDAP settings twice - it stores hash from password hash, etc.

**Expected behavior**

LDAP Manager password should be stored in the plain form, or be decrypted before sending it to the LDAP server.

**Comment by ihar-kahadouski** [comment]
https://github.com/reportportal/service-authorization/pull/119

**Comment by ihar-kahadouski** [comment]
Will be fixed in final version 5.0
