### ISSUE TITLE
Is there a way , we can monitor Performance of Test Cases/Test Suites

### ISSUE THREAD

**Issue by ChitraLekhaBHeemana** [reportportal/reportportal#716]
Are there any widgets for reportportal that can give Performance of Test Cases/Test Suites like Top 10

**Comment by evjlobanova** [comment]
@ChitraLekhaBHeemana Hello! Do you want to track test duration?
For now there is no such widget. As a work around you can export launch, and sort items by duration fild.

Anyway, could you please provide some information on this widgets? What should be the base for analysis? Which metrics do you need? Maybe you have a vision how such widget can be look like?

**Comment by ChitraLekhaBHeemana** [comment]
Looking something like Robotfrmaework robometrics , to monitor the execution time bottlenecks.

**Comment by ChitraLekhaBHeemana** [comment]
Worked ! Wrote Function similar to 'call_stored_procedure' by calling cursor.callfunc .
