### ISSUE TITLE
Does report portal support Allure Test Annotations or anything similar ? 

### ISSUE THREAD

**Issue by azakordonets** [reportportal/reportportal#72]
Hi, 

Not sure whether i should write into this repo or into testng client, but does report portal support anything like Allure Step annotations? Is there any way to integrate Allure reports with ReportPortal ? https://github.com/allure-framework/allure1/wiki/Steps

**Comment by avarabyeu** [comment]
@azakordonets Unfortunately, we don't support Allure annotations now. But i like the idea :)

**Comment by azakordonets** [comment]
Ok, thanks. I'm gonna to start watching your project then :)

**Comment by xescuder** [comment]
Has been added to ReportPortal?. I don't see from documentation?

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/reportportal/issues/275
we implemented this as a part of Nested Steps feature.

@Yumfriez plz share the link to the examples

**Comment by Yumfriez** [comment]
@xescuder 
https://github.com/reportportal/examples-java/tree/nested-steps-example

**Comment by xescuder** [comment]
I expected more the integration with
@Epic
@Features
@Stories/@Story
@Severity(SeverityLevel.BLOCKER)
@Description("In this cool test we will check cool thing")
@Step
@Attachment
@Link

To see structured information from ReportPortal, not as a simple tag.

**Comment by DzmitryHumianiuk** [comment]
@xescuder can you please elaborate on 
>To see structured information from ReportPortal, not as a simple tag.
