### ISSUE TITLE
Add a feature of providing option to merge n-retry runs into one final launch with showing last retry results in main dashboard

### ISSUE THREAD

**Issue by Nkperiwal** [reportportal/reportportal#720]
**Describe the solution you'd like**
Currently, we are having the option to merge with Linear and Deep processes. But these two will not give option of showing which final result should be displayed in ReportPortal Dashboard. It combines the Total, Passed and Failed Counts values and give results in Dashboard. 

I want to have an option where I can merge n retry launches into one like Linear Merge but it should also give option of showing final nth result counts (last retry results) in the main dashboard because that what actually matters.
 
**Is your feature request related to a problem? Please describe.**
I cannot find any but please suggest we have any process or feature branch which relates to it and would give desired results.

Please do let me know if you need more info to clarify my required solution.

Thanks in advance.

**Comment by DzmitryHumianiuk** [comment]
@Nkperiwal we call it #363 
It all will allow run one launch into another with overlay of results via test case retries.

New strategy for merge is also a good idea

**Comment by Nkperiwal** [comment]
Sure @DzmitryHumianiuk, I will try the above solution you provided and update here. Thanks

**Comment by evjlobanova** [comment]
Please follow #363, it should close your needs

**Comment by DzmitryHumianiuk** [comment]
Configure launch re-run
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/rerun.md

Configure multi-threaded execution to be collected in one launch:
https://github.com/reportportal/client-java/wiki/How-to-aggregate-Multi-thread-process-execution-in-one-launch
