### ISSUE TITLE
Not able to investigate failed cases in Report Portal 

### ISSUE THREAD

**Issue by rajkumar-cp** [reportportal/reportportal#724]
![1](https://user-images.githubusercontent.com/39653778/66540491-a1ba6c80-eb49-11e9-91d3-0bfde864ae32.PNG)
![2](https://user-images.githubusercontent.com/39653778/66540492-a2530300-eb49-11e9-9fe8-8680e613f005.PNG)

When the run was successfully completed in RP UI it shows 17 cases needs to be investigated. On clicking that 17 it displays an empty page showing No results
...

Expected behavior:
Failed 17 cases should be displayed
...

**Screenshots**
If applicable

**Versions:**
 - OS, Browser:  Chrome 77.0.3865.90
 - Version of RP : Current version: Analysis Service: 4.3.0; API Service: 4.3.4; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.6;

POM dependencies:
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>client-java</artifactId>
			<version>4.0.8</version>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-testng</artifactId>
			<version>4.2.1</version>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>logger-java-log4j</artifactId>
			<version>4.0.1</version>
		</dependency>

**Comment by DzmitryHumianiuk** [comment]
@rajkumar-cp what will happen, if you will click on launch name, instead of number in label?

see if you have structure under launch itself.
most likely structure reported with wrong object types.

**Comment by evjlobanova** [comment]
@rajkumar-cp Have you resolved your issue?

**Comment by rajkumar-cp** [comment]
@DzmitryHumianiuk 

If the click the launch name then also that count 15 will be available . If i click the same there then also it will be the same.

**Comment by DzmitryHumianiuk** [comment]
@rajkumar-cp when you click on numbers (this 15, or any other column with numbers) it will open default filter as `item.type=test`

if you see nothing after the click, that means that you structure send with invalid levels. Tests send as Suites or kind of it.

if you will drilldown thru the names, you will see what kind of types you have.

**Comment by rajkumar-cp** [comment]
@DzmitryHumianiuk 

Could you be a little more specific about this point

if you see nothing after the click, that means that you structure send with invalid levels. Tests send as Suites or kind of it.

**Comment by DzmitryHumianiuk** [comment]
@rajkumar-cp 
could you please click on Launch name
![image](https://user-images.githubusercontent.com/11332788/71278345-67025b00-2368-11ea-82ac-1bc0382b6b0f.png)
instead of `To investigate` badge, and show what's below it.

**Comment by rajkumar-cp** [comment]
@DzmitryHumianiuk 

On clicking the launch name it displays 4 test names ( which i have defined in my testNg.xml file). In that if 1 case failed in test 1 it shows 1 case needs to be investigated. On clicking that 1 again it navigates me to a blank screen where no cases are available for investigation.

**Comment by DzmitryHumianiuk** [comment]
@rajkumar-cp could you please screenshot those 4 test names?

you can blank the names, i just need to see which application grid is used for it

**Comment by rajkumar-cp** [comment]
[Report Portal Challenges.docx](https://github.com/reportportal/reportportal/files/4024740/Report.Portal.Challenges.docx)

PFA the document

**Comment by DzmitryHumianiuk** [comment]
@rajkumar-cp almost there.
could you please click on `AndroidMobile` name in **Step3**
so we can see what type of object corresponds to Tests with `To Investigate` issue.

Reason why view is empty once you click at `To Investigate`, ReporPortal send filter like `give me Test cases (step type) for AndroidMobile with issue=ToInvestigate`.
If data was sent with incorrect type, like if you test was sent as Suite, then it can be a result of empty view,

![image](https://user-images.githubusercontent.com/11332788/72077556-7a219e80-3308-11ea-8670-03f514a1179a.png)

**Comment by rajkumar-cp** [comment]
@DzmitryHumianiuk 

On clicking AndroidMobile all the cases in that test(AndroidMobile) was displayed except the cases that needs to be investigated. If you can see number of cases corresponding to that test is 52 but i see only 50 cases there.

**Comment by DzmitryHumianiuk** [comment]
@rajkumar-cp then it is issue statistics.
runtime calculation made it wrong, cause of concurrency access to objects in DB.

this was an issue for MongoDB (reportportal v1-v4)
in v5 we switched to PostgreSQL, which should not have this issue anymore.

**Proposal**: switch to v5
