### ISSUE TITLE
[Filter] Implement a possibility to query data based on RPQL 

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [reportportal/reportportal#726]
**Describe the solution you'd like**
Hi is it possible to query report portal similar to JQL for Jira via the UI, the reason this would be useful is you can create custom dashboard from virtually any information stored on report portal and it makes it very flexible for teams to tailor the information however they like.

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/reportportal/issues/610#issuecomment-533072426

**Comment by DuskoV** [comment]
And also be able to attach custom results to graphing system would be awesome. There are not so many reports, so this would help out to build more of them

**Comment by DzmitryHumianiuk** [comment]
we plan to have graphQL embedded.

**Comment by omkarnathsingh** [comment]
Any update on this?

**Comment by evjlobanova** [comment]
This feature is in our Backlog,
We are planning to implement it.
But it is difficult to say exactly in which version it will be included.

**Comment by Giladr** [comment]
Hey @evjlobanova ! 
Do you have any estimation when are you going to release it?
It's will give us (the users) super-powers :)

**Comment by evjlobanova** [comment]
We want to make our  users super-powered, but unfortunately, this feature requires a big refactoring on the back-end side and on the UI as well (
So, for now, I can not tell you estimations, but we are thinking in this way

**Comment by evjlobanova** [comment]
We have plans to introduce it in a version 6+, and add a possibility to create custom queries, and create graphs on the base of these queries

**Comment by marcinlesek** [comment]
Hey @evjlobanova, any rumours when version 6+ will be released?

**Comment by DzmitryHumianiuk** [comment]
@marcinlesek not earlier then EOY 2021.

**Comment by marcinlesek** [comment]
Thank you for clarification 👍

**Comment by evjlobanova** [comment]
Closed as a duplicate
