### ISSUE TITLE
How to change launch name on the fly in reportportal.config.json

### ISSUE THREAD

**Issue by heilwood** [reportportal/reportportal#727]
Hi,

Is it possible to change launch name on the fly in reportportal.config.json? We have multiple environments  and we would like to have for each separate environment unique launch name, for example: "UI Tests STEST", "UI Tests ATest". As we have only one project with one reportportal.config.json but we are running this project on multiple environments, how to override launch name before launch start? We are using latest VStest reportportal agent and .net framework.

**Comment by DzmitryHumianiuk** [comment]
in Java we allow to overload params via command line. Like `java jar -Drp.launch=zzz`
and this param will replace the name of launch from config file.

most likely something similar available in VSTest.
@nvborisenko to comment

**Comment by nvborisenko** [comment]
It is possible to do it via [command line parameters](https://github.com/reportportal/agent-net-vstest#parameters-overriding) or via [environment variables](https://github.com/reportportal/agent-net-vstest#environment-variables)

**Comment by baradhiren** [comment]
Any idea on how I can achieve this for mocha agent? I tried the options in environment variables link mentioned above but that doesn't seem to work in my scenario.

**Comment by DzmitryHumianiuk** [comment]
@baradhiren please specify what's your case, do you want to overload the name of the launch via command line params over the property files params?

**Comment by baradhiren** [comment]
Hi @DzmitryHumianiuk,
Here it goes:
I am using mocha-multi-reporter and other mochawesome reporters to generate HTML reports. On top of it I have added [agent-js-mocha](https://github.com/reportportal/agent-js-mocha). The configuration works great on my local. Now I was wondering if I want to dynamically change the launch attribute of reporterOptions how can I achieve that?

ReporterOptions:
`"reportportalAgentJsMochaReporterOptions": {
        "token": "",                
        "endpoint": "",
        "project": "",
        "launch": "DEV/Prod/Demo/PR/etc.",    <----------------------- This guy
        "description": "report portal test"
    }`

**Comment by praveentata** [comment]
Is there a way to overwrite the variable for JS (Cypress)?
I am trying it this way:
`npx cypress run --reporter @reportportal/agent-js-cypress  --reporter-options "launch=sanity"`

I am getting an error `Fail to start launch Error: connect ECONNREFUSED 127.0.0.1:80`

I am not able to overwrite the launch variable.

**Comment by DzmitryHumianiuk** [comment]
@praveentata please redirect this questions into https://github.com/reportportal/agent-js-cypress issues
