### ISSUE TITLE
Incorrect last login date and time for LDAP users

### ISSUE THREAD

**Issue by vgri** [reportportal/reportportal#729]
**Describe the bug**
Looking at the Project Members screen, Last login is showing the first login of the user instead of the latest connection of the user when connected through LDAP.

**Expected behavior**
Show real last login date and time.

**Screenshots**
If applicable

**Versions:**
 - OS, Browser: Fedora 30, Chrome 
 - Version of RP [find it under Login form, copy as is]  Current version: API Service: 4.2.1; Index Service: 4.2.0; Jira Service: 4.2.0; Rally Service: 4.2.0; Authorization Service: 4.2.0; Service UI: 4.2.2;

**Comment by evjlobanova** [comment]
#365

**Comment by evjlobanova** [comment]
https://github.com/reportportal/service-authorization/pull/94

**Comment by evjlobanova** [comment]
Fixed and verified.
Will be available in the final 5.0 version
