### ISSUE TITLE
[Log View] Need way to correctly select and copy log messages

### ISSUE THREAD

**Issue by JustasM11** [reportportal/reportportal#73]
Currently selection and paste results are ugly - I cannot use it while submitting issue in bug tracker:
Selected in RP:
![selected_rp](https://cloud.githubusercontent.com/assets/12593214/22238840/abf75c3e-e224-11e6-9b77-74e86e62648e.png)

Pasted from RP into Notepad++ (Monospace):
![pasted_rp](https://cloud.githubusercontent.com/assets/12593214/22238842/afb5eb38-e224-11e6-9fce-89b4c020d738.png)

Expected:
Compare with Robot Framework:
Selected in Robot Framework:
![selected_robot](https://cloud.githubusercontent.com/assets/12593214/22238846/b3b4797a-e224-11e6-8359-145ef1d88d9d.png)

Pasted from Robot Framework in Notepad++ (Monospace):
![pasted_robot](https://cloud.githubusercontent.com/assets/12593214/22238850/b8b4c358-e224-11e6-8882-dc0206a32c5e.png)

**Comment by avarabyeu** [comment]
Good idea. Thank you for contribution!

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 this will be covered with `console` view for logs.
planned for 3.1

**Comment by DzmitryHumianiuk** [comment]
will be covered with `Console View`

![image](https://user-images.githubusercontent.com/11332788/32057620-7110d0e4-ba70-11e7-89b3-a43602a95595.png)
