### ISSUE TITLE
 launch don't finish

### ISSUE THREAD

**Issue by summergan** [reportportal/reportportal#730]
**Describe the bug**
When the test execution is complete, launch don't finish, a suite is running and that not logs
 **To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/38934767/67378187-760f9b80-f5b9-11e9-84be-a9364cf20f4d.png)
![image](https://user-images.githubusercontent.com/38934767/67378237-8c1d5c00-f5b9-11e9-8570-531bcf033a3b.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: chrome
 - Version: 
 Analysis Service: 4.3.0; API Service: 4.3.0; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.0;
**Smartphone (please complete the following information):**
 
**Additional context**

**Comment by evjlobanova** [comment]
@summergan You have added label v5beta, but add info about version 4.3.0. 
Do you have problems on both envs?

**Comment by HardNorth** [comment]
@summergan Please provide more context. Do you have any errors in logs? Which agent version do you use? Do you run your tests in parallel or in single-thread?
