### ISSUE TITLE
JMeter Test Plan integration

### ISSUE THREAD

**Issue by sspieker-cc** [reportportal/reportportal#731]
JMeter is a tool that is heavily used for Load Testing and API testing operations.  This is a tool that is heavily relied upon in many companies and institutions.  Having a pre-built or at least a guide as to how reportportal.io can be integrated with JMeter as a part of a logging solution or an official agent would be absolutely wonderful to have access to.

Implementation could be as simple as a drop-in Jar file within the JMeter tool or addition of the necessary JARs as a part of the classpath when starting the JMeter tool along with reportportal properties either contained within the testplan or passed as additional command line parameters would be ideal and very flexible.

I am happy to expand on this topic if additional information is requested or required.
...

This feature request is NOT related to a problem.
...

**Comment by DzmitryHumianiuk** [comment]
@sspieker-cc 
integration with JMeter thru
https://github.com/carrier-io/carrier-io/wiki/Performance-Testing.-PerfMeter-%28jMeter%29

**Comment by DzmitryHumianiuk** [comment]
@sspieker-cc appender used as additional output stream.
In case of integration with RP, appender extended to have information from agent, in order to know which test case is active, in order to bind to active ID.

you need appender in order to send logs.
you need agent to send structure.

**Comment by naganaidu-rezi** [comment]
@DzmitryHumianiuk 
any update on when can Jmeter will be available in RP ?
Thanks.

**Comment by DzmitryHumianiuk** [comment]
end of 2020

**Comment by naganaidu-rezi** [comment]
> end of 2020

can we contribute on this ?

**Comment by albadam000** [comment]
+1, we might have the capacity to contribute here as well

**Comment by ankitps1807** [comment]
> end of 2020
Hey @DzmitryHumianiuk any update on this? Struggling to deliver a solution with this.
cheers

**Comment by sspieker-cc** [comment]
I have come up with a partial solution to this particular use case.  I have mentioned in previous posts regarding the variances in the tooling that we needed to use to report output to the reportportal.  Some of those tools have failed to deliver reliable results (i.e. using different JUnit Test runners for example) would fail to report ANY test executions, etc.  We have also had challenges with communications to the reportportal due to our environments and firewalls being too difficult to manage for this application.

Here is the solution that had worked for us:
1 - Created a java library that did the work of communicating to the reportportal's API - this could pretty easily be substituted with the client-java library from ReportPortal github or maven repository.
2 - When running tests use the option to output to JUnit from JMeter - these output file(s) will need to be zipped to use the import endpoint to supply the results to RP.  IMPORTANT NOTE:  When using a zip file for importing results, the filename is the resulting launch name within reportportal.  This name cannot be modified by the API!!!
3 - A properties file is used by the client-java library as well as the in-house library.  This properties file is the 'standard' file used by the reportportal tooling - why re-invent the wheel here, right???
4 - The API-library reads the properties file for the UUID, tags and description
5 - Supplies the ZIP file for the import to create the launch (returning the launch ID for later interactions)
6 - The API-Library updates the launch with the correct description and applies the tags to the launch attributes

In our specific usecase, we have a docker container that can be used with a docker-compose file or even deployed within kubernetes for on-demand / cron based testing.  This container's entrypoint script does the work of running the Jmeter and outputing the report to a JUnit formatted file, zipping the file and supplying the properties file to perform the import.  These files are then delivered to a filesystem where the library can access it (this library / application) can even be packaged within the jmeter container can called by the entrypoint script).

This is the solution that we had managed to generate in house:
NOTE: Ansible could be used to keep everything in sync with regards to JAR file versions, URLs and such within the Dockerfile, entrypoint scripts and reportportal.properties as well as Test files if so desired as a part of a Jenkins pipeline or as a simplified process for a shell script - assuming that these values may change regularly for some reason.

**Directory Structure:**
Dockerfile
entrypoint.sh
properties/user.properties
properties/reportportal.properties
properties/sftp.properties
tests/*.jmx, *.csv, etc.
xslt/jmeter-results-to-junit.xsl

**Dockerfile:**
# inspired by https://github.com/hauptmedia/docker-jmeter  and
# https://github.com/hhcordero/docker-jmeter-server/blob/master/Dockerfile
FROM alpine:3.10

MAINTAINER Just van den Broecke<just@justobjects.nl>

ARG JMETER_VERSION="5.1.1"
ENV JMETER_HOME /opt/apache-jmeter-${JMETER_VERSION}
ENV JMETER_BIN	${JMETER_HOME}/bin
ENV JMETER_DOWNLOAD_URL  https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz
ENV JMETER_TEST_RESULTS ${JMETER_HOME}/test-report/junit
ENV TZ "America/New_York"
# Set global PATH such that "jmeter" command is found
ENV PATH $PATH:$JMETER_BIN


# Install extra packages
# See https://github.com/gliderlabs/docker-alpine/issues/136#issuecomment-272703023
# Change TimeZone TODO: TZ still is not set!
# ARG TZ="Europe/Amsterdam"
ARG TZ=${TZ}
RUN    apk update \
	&& apk upgrade \
	&& apk add ca-certificates \
	&& update-ca-certificates \
	&& apk add --update openjdk8-jre tzdata curl unzip bash dos2unix zip expect \
	&& apk add --no-cache nss \
	&& rm -rf /var/cache/apk/* \
	&& mkdir -p /tmp/dependencies  \
	&& curl -L --silent ${JMETER_DOWNLOAD_URL} >  /tmp/dependencies/apache-jmeter-${JMETER_VERSION}.tgz  \
	&& mkdir -p /opt  \
	&& tar -xzf /tmp/dependencies/apache-jmeter-${JMETER_VERSION}.tgz -C /opt  \
	&& rm -rf /tmp/dependencies

# TODO: plugins (later)
# && unzip -oq "/tmp/dependencies/JMeterPlugins-*.zip" -d $JMETER_HOME

# This jar is used to convert the results of the JMeter execution to JUnit - used as a part of the entrypoint script
ADD https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/10.2/Saxon-HE-10.2.jar ${JMETER_HOME}/lib/ext

# XSLT Processor to convert the junit output
COPY xslt /xslt
# JMeter JMX files
COPY tests /tests
# User Properties to hand off to the JMeter execution
COPY properties/user.properties ${JMETER_HOME}/bin

# Create directories for JMeter logs, properties files and output
RUN mkdir -p ${JMETER_TEST_RESULTS} && mkdir -p /properties && chmod -R 777 ${JMETER_TEST_RESULTS}/../ /properties && chmod -R 644 ${JMETER_HOME}/lib/ext/*.jar

# Entrypoint has same signature as "jmeter" command
COPY entrypoint.sh /

WORKDIR ${JMETER_HOME}

ENTRYPOINT ["/entrypoint.sh"]

**entrypoint SH file:**
[entrypoint.sh.txt](https://github.com/reportportal/reportportal/files/5245742/entrypoint.sh.txt)

**XSLT File:** (Attached)
[jmeter-results-to-junit.xsl.txt](https://github.com/reportportal/reportportal/files/5245627/jmeter-results-to-junit.xsl.txt)

**JMeter User Properties file:** (Attached)
[user.properties.txt](https://github.com/reportportal/reportportal/files/5245659/user.properties.txt)


What you do with the resulting ZIP file will depend on what your solution might be.

**Comment by DzmitryHumianiuk** [comment]
@sspieker-cc sounds like a good solution.

Since real-time reporting of Performance tests generate big load on RP API itself.
Thus upload of finalized and summed up report makes more sense.

@sspieker-cc btw, did you try https://getcarrier.io/ ?

**Comment by karthikeyans1** [comment]
@DzmitryHumianiuk  I did implemented carrier but RP integration is not working

**Comment by karthikeyans1** [comment]
seems like its not yet implemented , is it right?

**Comment by DzmitryHumianiuk** [comment]
@karthikeyans1 i've double checked it with @arozumenko : carrier is just not updated for RPv5. works with RPv4 API now.

**Comment by tokarthik** [comment]
thanks, @DzmitryHumianiuk  any idea when you guys will upgrade to v5, If you guys guide me how to do it, I will happy to contribute

**Comment by vijaymishra-dan** [comment]
Hi @DzmitryHumianiuk, any update on the JMeter integration with Report Portal?

**Comment by tokarthik** [comment]
@vijaymishra-dan yes it sends data from carrier-io to RP

**Comment by DzmitryHumianiuk** [comment]
@vijaymishra-dan we plan to address manual test cases first.

But you also can take a look into [Carrier](https://getcarrier.io/#about)

**Comment by sspieker-cc** [comment]
We have been meeting with more success by outputting the JMeter results to Junit XML and then uploading them to reportportal instead of attempting to do realtime reporting.

This is a mechanism that has worked well for our needs as outlined above.  This approach has been a saving grace for us.

**Comment by drcrazy** [comment]
There is an issue aimed on consolidation of all perf test reporting questions: #1820
