### ISSUE TITLE
Not able to send PUT request with failed status

### ISSUE THREAD

**Issue by rupeshkumarram** [reportportal/reportportal#733]
**Describe the bug**
I am using integrating my test framework with report-portal.
Json payload provided on page "Extended scheme of integration ReportPortal with the test framework" is used

Request Body
```json
{"description": "description",
"end_time": "2018-02-01T13:24:37.954Z ",
"issue": {
"comment": "comment_text",
"externalSystemIssues": [
{
"submitDate": 0,
"submitter": "string",
"systemId": "string",
"ticketId": "string",
"url": "string"
}
],
"issue_type": "string"
},
"status": "PASSED",
"tags": ["tags"]}
```
When i change status from PASSED to fail FAILED or SKIPPED i get below error message
```json
{
    "error_code": 40019,
    "message": "Test item status is ambiguous. Invalid test item issue type definition 'string' is requested for item '5db1896eb9d821000191e221'. Valid issue types locators are: [AB001, TI001, ND001, SI001, PB001]"
}
```
**Expected behavior**
ReportPortal should allow FAILED status 

**Screenshots**
If applicable
![image](https://user-images.githubusercontent.com/10478612/67481174-23001c00-f67f-11e9-8250-d38c2f459d9a.png)

**Versions:**
 Window

**Comment by evjlobanova** [comment]
@rupeshkumarram Which version do you use?

**Comment by DzmitryHumianiuk** [comment]
@rupeshkumarram read the error message to the very end.

you send ` "issue_type":"string"`
but it should be one of `[AB001, TI001, ND001, SI001, PB001]`

the reason it asks for issue type, is a logical constraint: Failed item should have either correct issue type, or don't have it.

remove this line with ` "issue_type"`
or add the right state from `[AB001, TI001, ND001, SI001, PB001]`

**Comment by rupeshkumarram** [comment]
Thanks This has resolved the issue
