### ISSUE TITLE
Correct time is not showing in start section of reportPortal

### ISSUE THREAD

**Issue by rupeshkumarram** [reportportal/reportportal#734]
**Describe the bug**
I wrote below date method to push start date in reportPortal by json payload given on "Extended scheme of integration ReportPortal with the test framework" but the time is not showing correctly on reportPortal
```java
public static String getDate() {
		String pattern = "yyyy-MM-dd'T'HH:mm:ss";
		SimpleDateFormat sdf = new SimpleDateFormat(pattern);
		String dateWIthoutZ = sdf.format(new Date());
		String date = dateWIthoutZ+"Z";
		return date;
	}
```
Am i using correct date format? However, if i above method to push test result through Rest request the there is difference of 5:30 hours

**Expected behavior**
Correct time should display on reportPortal

**Screenshots**
If applicable
![image](https://user-images.githubusercontent.com/10478612/67482546-868b4900-f681-11e9-9f93-84b50625e2f7.png)

**Versions:**
Window

**Comment by DzmitryHumianiuk** [comment]
@Yumfriez @HardNorth please assist

**Comment by evjlobanova** [comment]
@rupeshkumarram Have you resolved this issue?

**Comment by evjlobanova** [comment]
@rupeshkumarram I close this issue, please reopen, if you still have an issue
