### ISSUE TITLE
[Widget] [Launches duration chart] Reflect a full name of a launch in the tool tip on a widget

### ISSUE THREAD

**Issue by itzikb-redhat** [reportportal/reportportal#740]
**Describe the solution you'd like**
I want to be able to see the Launches' names on the X-axis besides the launches' numbers

**Is your feature request related to a problem? Please describe.**
It's hard to determine the launches' duration just from looking at the chart - You need to hover the mouse over the bar of the specific launch to see which job it is (And as for other widgets as well - if the launch name is long you might not figure out still because it's shortened )

**Comment by evjlobanova** [comment]
@itzikb-redhat Hello, we  have added this request to Backlog. Thank you very much for this note.

**Comment by evjlobanova** [comment]
@itzikb-redhat Hello! Launch name takes a lot of space on the widget, so that we put it to the hover. And in case of the very long name the widget wouldn`t be informative. 

If we would not  cut long launch name in the tool tip, does it solve the problem?

**Comment by itzikb-redhat** [comment]
Yes this is what I intended.

**Comment by evjlobanova** [comment]
We added this request to our backlog

**Comment by ElenaRomanchuk** [comment]
Fixed in scope of PR [2215](https://github.com/reportportal/service-ui/pull/2215).

**Comment by evjlobanova** [comment]
Improvement will be available in version 5.1
