### ISSUE TITLE
[Widget] [Launches Table] Add a possibility to collapse/expand additional launch info

### ISSUE THREAD

**Issue by itzikb-redhat** [reportportal/reportportal#741]
**Describe the solution you'd like**
The widget 'Launches table' shows all the launches (based on the filter used) - their names as well as their tags. 
It would be great to add an option to collapse/expand the tags' list

**Comment by evjlobanova** [comment]
@itzikb-redhat Hello, we have added this request to Backlog. Thank you very much for this note.
