### ISSUE TITLE
Test status is in progress whenever there is a SoftAssertions fail

### ISSUE THREAD

**Issue by anilpatidar24x7** [reportportal/reportportal#742]
I'm running my test, and observed that, for all pass scenarios report portal is getting updated, but in case of failure of SoftAssertions, report portal is not getting updated. test status is getting stuck in progress .

Package : import org.assertj.core.api.SoftAssertions;

**Comment by DzmitryHumianiuk** [comment]
@anilpatidar24x7 you should double check if this `org.assertj.core.api.SoftAssertions` can generate fail event at the end.
`in progress` state means that no Finish event was sent to ReportPortal,
which means that internal event of your test runner (testNG, junit, etc) which corresponds to TestCase finish did not happen.

**Comment by evjlobanova** [comment]
@anilpatidar24x7 Have you resolved your issue?

**Comment by anilpatidar24x7** [comment]
Yes,

The issue was with soft assertion . got resolved .

Thanks,
Anil
