### ISSUE TITLE
[v5bug] Retries view overlaps reason text

### ISSUE THREAD

**Issue by abotalov** [reportportal/reportportal#743]
**Describe the bug**
Retry view overlaps investigate reason.

**To Reproduce**
1. Open https://beta.demo.reportportal.io/ui/#test_io-1_personal/launches/all/4367/96626/96777
2. Click 3 retries link
Actual: Retries view overlaps issue/reason text.

**Expected behavior**
Retries view doesn't overlap issue/reason text.

**Screenshots**
![Screenshot from 2019-11-05 16-11-46](https://user-images.githubusercontent.com/1497867/68210674-15d01f00-ffe7-11e9-918f-ebdfdda2b93b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 78

**Comment by KatsiarynaTatarynovich** [comment]
It will be fixed in the 5.1 version on the UI side.
