### ISSUE TITLE
[v5bug] Log entries with MARKDOWN_MODE are not compatible with new version of API

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/reportportal#746]
`!!!MARKDOWN_MODE!!!` string is not cut. If test frameworks provide log messages which starts from above string, UI shows this string.

**Expected behavior**
v5 is compatible with v4.

**Screenshots**
![image](https://user-images.githubusercontent.com/22616990/68325059-c74f7d00-00d9-11ea-99c4-75ea34b23549.png)

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**
It's expected that v5 is backward compatible with v4 clients.

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko just remove it for v5 supported loggers.
it's deprecated.
Now you can enable markdown transformation via toggle on log view:
![image](https://user-images.githubusercontent.com/11332788/68337870-75672100-00f2-11ea-954b-a540917f10e0.png)

**Comment by nvborisenko** [comment]
I'm reopening it because v5 is going to be backward compatible with v4.

We are appending "MARKDOWN_MODE" string because we think we are interacting with v4. Interaction with v5 should not be broken because of backward compatibility.

As I understand client should not be changed.

**Comment by DzmitryHumianiuk** [comment]
my assumption here that if we will keep cutting `!!!MARKDOWN_MODE!!!` for v5 then nobody will know that it should be removed.

and there will no be push for update.

does it make sense?

**Comment by nvborisenko** [comment]
If it is not backward compatible, we need adapt client call. Is `v5` backward compatible with `v4`?

**Comment by DzmitryHumianiuk** [comment]
>If it is not backward compatible, we need adapt client call. Is v5 backward compatible with v4?

yes it does,
at least we struggle to keep it compatible with latest fixes

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko how do you think we should do with it?

keep cutter in logs, and rid of it in next version later?

**Comment by nvborisenko** [comment]
I think so, trimming allows to be closer to backward compatibility. V5 doesn't require client to be upgraded.

**Comment by KatsiarynaTatarynovich** [comment]
https://github.com/reportportal/service-ui/pull/2311
https://github.com/reportportal/service-ui/pull/2313
