### ISSUE TITLE
[v5bug] Logs are shown with red error on test level

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/reportportal#747]
**Describe the bug**
When I open logs for particular test, I see error message at the bottom of page.

**To Reproduce**
Just execute tests from `example-net-nunit` (build.cmd).

**Expected behavior**
No error?

**Screenshots**
![image](https://user-images.githubusercontent.com/22616990/68325853-54df9c80-00db-11ea-8e14-112ed31c2bb6.png)

**Comment by DzmitryHumianiuk** [comment]
Current version:
API Service: 5.0.0-RC-3-SNAPSHOT;Index Service: 5.0.4;Authorization Service: 5.0;

**Comment by pbortnik** [comment]
@nvborisenko
it will be pretty good if you ll share more information. if it is beta instance, could you please provide us project, so we can reproduce it.
if not, then it will be good if you show us the whole returning error stack trace from browser dev tools

**Comment by nvborisenko** [comment]
https://github.com/reportportal/example-net-nunit
build.cmd, don't forget to direct tests to beta rp via config.json

**Comment by iKozzz** [comment]
I see this in `userdebug` section
There is API call failure when you observe TestItem log:
* `http://my-super-rp.com/api/v1/myproject/item/history?ids=6361&history_depth=10`
* `{"errorCode":5000,"message":"Unclassified error [org.hibernate.exception.SQLGrammarException: could not extract ResultSet]"}`

service-api:5.0.0-RC-2

Server Log:
* [extract_result_set.log](https://github.com/reportportal/reportportal/files/3832318/extract_result_set.log)

**Comment by nvborisenko** [comment]
Please find existing [launch](http://beta.demo.reportportal.io/ui/#default_personal/userdebug/all/7969) on public beta instance. Open any test with logs.

**Comment by pbortnik** [comment]
Fixed on the backend side.
Should be fix on ui side as well. @AmsterGet

**Comment by DzmitryHumianiuk** [comment]
@pbortnik do you have referring commit number?

**Comment by evjlobanova** [comment]
Will be available in 5.0
