### ISSUE TITLE
Not able to attach file into logs with REST API

### ISSUE THREAD

**Issue by rupeshkumarram** [reportportal/reportportal#748]
**Describe the bug**
I am trying to add attachment with logs but not able to do so

{"file": {
"name": "C:\\Users\\ru20104049\\Desktop\\screenshot.jpeg",
"content" : "byte content",
"contentType" : "image/jpeg"
},
"item_id": "5dc2b3ccb9d8210001920851",
"level": "Log info",
"message": "Result=Failed",
"time": "2019-10-23T21:27:33.280Z"}

Please help me to add attachment with REST API in log screen of reportportal
**Expected behavior**
...

**Screenshots**
If applicable
![image](https://user-images.githubusercontent.com/10478612/68362181-50070100-014c-11ea-9377-5b863de35ae8.png)

**Versions:**
 - OS, Browser
Current version: API Service: 4.3.0; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.0;

**Comment by DuskoV** [comment]
Uploads are zip archives. It would be great if files can be recognized inside of the zip file. For example, JUnit can create screenshots, so it would be great if import procedure can properly recognize and import screenshots

**Comment by e-olga** [comment]
Hello @rupeshkumarram ,

Could you please tell us, which agent you use? So, we will be able to provide the appropriate example.

In general, to load the attachments into ReportPortal, you need to send multi-part request, that contains of the .json file and the attachments themselves. 
The .json file should have the content like the next:
[ 
    {
	"file":{
"name" : "API Report.html"
},
      "item_id": "",
      "level": "error",
      "message": "java.lang.AssertionError: 1 expectation failed.",
      "time": "2019-01-01T14:35:55.006Z"
    },
    {
  "file":{
"name" : "Filter name.png"
},
      "item_id": "",
      "level": "error",
      "message": "java.lang.AssertionError: 1 expectation failed.",
      "time": "2019-01-01T14:35:55.006Z"
    }
]
The request should be look like 
![Multipart](https://user-images.githubusercontent.com/22497746/69244308-c88ea880-0bb5-11ea-9089-8b7f9d744ce9.png)

Please let us know whether you are able to load the attachments.

Regards
Olga

**Comment by evjlobanova** [comment]
Due to no response I close the issue, if you still have this issue, feel free to reoprn it
