### ISSUE TITLE
Unable to scroll in full screen mode for widgets

### ISSUE THREAD

**Issue by AshwinNS** [reportportal/reportportal#749]
**Unable to scroll down in full screen mode in Google chrome Version 78.0.3904.97 (Official Build) (64-bit)**
I checked the behavior in Firefox(70.0 64-bit) , was able to scroll down and working as expected. 

cross checked the following widgets and found same issue in chrome:
 - Launches table
 - Project activity panel

**Versions:**
 - Windows 10 64-bit
 
![rp_bug](https://user-images.githubusercontent.com/40761333/68396128-08599700-0197-11ea-9049-97b40a301f07.PNG)

Current version: API Service: 4.3.0; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.0;

**Comment by DzmitryHumianiuk** [comment]
@AshwinNS could you plz double check it with version 5 at https://beta.demo.reportportal.io ?

**Comment by AshwinNS** [comment]
@DzmitryHumianiuk Yes, I'm able to reproduce the same in v5 as well. I have uploaded some test data into project "ASHWINNS_PERSONAL" in case if you would like to cross check.

**Comment by evjlobanova** [comment]
@ElenaRomanchuk Could you please add a link to pull request?

**Comment by ElenaRomanchuk** [comment]
Fixed in scope of [UI PR #2200](https://github.com/reportportal/service-ui/pull/2200)
