### ISSUE TITLE
Sort doesn't work for results

### ISSUE THREAD

**Issue by JustasM11** [reportportal/reportportal#75]
1) Go to Launches
2) Find launch with "To investigate" issues 
3) Click on yellow number in "To investigate" column
4) On page with "To investigate" try to sort by Status
Expected: Results are sorted by status
Actual: Results are not sorted by status
See attached image. 
![sort_issue](https://cloud.githubusercontent.com/assets/12593214/23216825/5ee2b270-f928-11e6-85fc-b027e544c691.png)

Build:
Gateway Service: 2.7.1;UI Service: 2.7.0;Rally Service: 2.7.1;Authorization Service: 2.7.1;API Service: 2.7.1;Registry Service: 2.7.1;

**Comment by DzmitryHumianiuk** [comment]
@e-olga

**Comment by e-olga** [comment]
Hi @JustasM11,
In current implementation, the sorting is executed by Status under a particular parent group (the same Suite/Test).
So, sorting works correctly for your example.

**Comment by avarabyeu** [comment]
@e-olga feel free to close as invalid if it is not an issue :)

**Comment by JustasM11** [comment]
@e-olga Do I understand correctly that I cannot sort because results are grouped by Test Folders and sorting actually works for test folders? Is there way to get the same view but not grouped to be able to sort results?

**Comment by e-olga** [comment]
Yes, it's correct for current version of product. 
The possible workaround is to drill down to STEP view via launch structure. But in this case you can see items from one folder only .
The sorting could be a bit changed with new implementation. This case (issue) is added to be discussed on development workshop meeting

**Comment by e-olga** [comment]
@JustasM11 
With Release 3.0 functionality of sorting will be changed.
It seems to me that the sorting will work in the same way as you expected.

**Comment by avarabyeu** [comment]
Closing issue since it's resolved in 3.0

**Comment by JustasM11** [comment]
@DzmitryHumianiuk
@avarabyeu You stated issue is closed in v3.0. I cannot find v3.0 with fix. Could you please help me and point to link with fix?

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 will be release soon.
please see https://github.com/reportportal/reportportal/releases
