### ISSUE TITLE
Integration with Codeception - failing due to empty test name passed to the reportportal

### ISSUE THREAD

**Issue by mlukjanska25f** [reportportal/reportportal#757]
I was trying out the integration of the codeception (https://github.com/reportportal/agent-php-Codeception) with the reportportal, and the posting to reportportal fails because the test name/description are being passed empty on the post request.

When running the codeception test (**Unit Test**) I am getting the following error:
```bash
<pre>Exception &#039;TypeError&#039; with message &#039;Argument 1 passed to ReportPortalBasic\Service\ReportPortalHTTPService::finishItem() must be of the type string, null given, called in /vendor/reportportal/codeception/src/agentPHPCodeception.php on line 228&#039; 
in /vendor/reportportal/basic/src/service/ReportPortalHTTPService.php:498
Stack trace:
#0 /vendor/reportportal/codeception/src/agentPHPCodeception.php(228): ReportPortalBasic\Service\ReportPortalHTTPService::finishItem(NULL, &#039;STOPPED&#039;, &#039;&#039;)
#1 /vendor/symfony/event-dispatcher/EventDispatcher.php(264): agentPHPCodeception-&gt;afterTestError(Object(Codeception\Event\FailEvent), &#039;test.error&#039;, Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher-&gt;doDispatch(Array, &#039;test.error&#039;, Object(Codeception\Event\FailEvent))
```

For unit test the following piece of code is not returning the test name (it returns it as expected for Acceptance tests though): https://github.com/reportportal/agent-php-Codeception/blob/8d21e833de68f9acd22cb129936c427f61604807/src/agentPHPCodeception.php#L153

Also opened an issue in Codeception: https://github.com/Codeception/Codeception/issues/5761

**Codeception version:**
Codeception PHP Testing Framework v3.1.2
Powered by PHPUnit 8.4.3 by Sebastian Bergmann and contributors.

**Reportportal versions:**
Current version: Analysis Service: 4.3.0; API Service: 4.3.0; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.0;

**Comment by DzmitryHumianiuk** [comment]
Share with Codeception developers

**Comment by mlukjanska25f** [comment]
Yes, thanks, it looks like the issue is with the UnitTester (Unit Tests), the Acceptance tests are working fine:
https://github.com/Codeception/Codeception/issues/5761

**Comment by DzmitryHumianiuk** [comment]
@mlukjanska25f should we close ticket?
