### ISSUE TITLE
Data Validation Test Results as CSV is not publishing in Report portal

### ISSUE THREAD

**Issue by Agurul** [reportportal/reportportal#759]
I have a test results (Data Validation) which stored in csv file. I will not use Assertion in my test file due to huge data records validation.
Report portal is not showing any results for my Passed test case.

Is it possible to avail my csv results file from project directory to report portal ? If so please guide me on this how to publish CSV data on report portal?

Or

Is there any way that I can have/attach my results csv file from resources folder of project to report portal ?

**Comment by Agurul** [comment]
I'm using report portal with Serenity Framework. Please suggest me on the above query ASAP.

**Comment by Agurul** [comment]
Can Someone help me on this please

**Comment by evjlobanova** [comment]
@Agurul your use case is a little bit confusing. Could you pleas clarify it? Do you want to attach this file to test in ReportPortal, or do you want to import results from csv file to report portal?

**Comment by nvborisenko** [comment]
She wants to attach file as log item.

**Comment by evjlobanova** [comment]
@Agurul Could you please drop us an e-mail at ![image](https://user-images.githubusercontent.com/30413511/71177928-1f9fa000-227e-11ea-8ff2-02923611938f.png)
 and we will orginize a call with you and we would dive into details

**Comment by evjlobanova** [comment]
No response
