### ISSUE TITLE
No results after click on 'Failed' number in launch

### ISSUE THREAD

**Issue by JustasM11** [reportportal/reportportal#76]
1) Go to Launches
2) Find launch with 'Failed' results
3) Click on 'Failed' number
Expected: List of failed results
Actual: No results
See attached image
![no_results](https://cloud.githubusercontent.com/assets/12593214/23216950/bf883334-f928-11e6-8b20-03ea730de52f.png)

Build:
Gateway Service: 2.7.1;UI Service: 2.7.0;Rally Service: 2.7.1;Authorization Service: 2.7.1;API Service: 2.7.1;Registry Service: 2.7.1;

**Comment by e-olga** [comment]
Hi @JustasM11 
When you click 'Failed' items link you get to STEP view, i.e. you see all items with 'type'="STEP":
..filter.eq.has_childs=false&filter.in.status=FAILED&filter.in.type=STEP...
In case you have launch structure SUITE>TEST>STEP, failed items will be displayed.
In case you have launch structure SUITE>TEST, failed items are NOT on STEP view, so they are not shown.  (But you can see the correct statistics on LAUNCH level).
The issue could be resolve with implementation of BDD approach, when items will be calculated by SCENARIOs (TESTs) and  not by STEPs.

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 
after clicking on `7 failed` items, please remove `Method Type` filter
and let us know the result (screenshot).
Thank you

**Comment by JustasM11** [comment]
@DzmitryHumianiuk this fixed issue :)
So bug is that Method Type "Test" is set as default filter after one click on number of failed items, right?
Correct behavior should be setting proper Method type that allows to view failed items.

![test_filter_removed](https://cloud.githubusercontent.com/assets/12593214/23547620/e8a0a59c-0014-11e7-9efa-e76a3e6e6465.png)

**Comment by avarabyeu** [comment]
@JustasM11 befores and afters also may fail. so that's correct behaviour i assume.

**Comment by JustasM11** [comment]
@avarabyeu I'm sorry but I don't understand why it is correct behavior that I don't get any results after clicking on number in "Failed" column? 
For me it is like you have underscored link that leads to 404 page.

**Comment by avarabyeu** [comment]
@lexecon @DzmitryHumianiuk Guys, could you please handle.
