### ISSUE TITLE
Duplicate suites/launch does not finish.

### ISSUE THREAD

**Issue by Baivalr** [reportportal/reportportal#763]
I added reportportal to my project following the instructions here > https://github.com/reportportal/example-java-TestNG and using the @listeners annotation. The lunches appear in reportportal and everything looks fine until the test runs end. The launch in RP never finishes and has to be forced to finish. The launches have duplicate suites, one of which finishes as expected, the other never finishes.  This happens whether we run it locally/manually or use Jenkins. Does anyone have nay thoughts on why this is and how I can fix it? This is a selenium/java project ultimately running from a jenkins pipeline job.

Thx

**Comment by DzmitryHumianiuk** [comment]
@Baivalr duplicated suites and items means that you have declared ReportPortal listener twice.

Not finished execution, in situation of doubled declaration, means that 2 listeners can't decide who should finalize execution.

**Comment by Baivalr** [comment]
The report portal listener declaration exists in exactly 1 place in the whole project. 
`@Listeners({LoggingListener.class,
    EnvironmentPropertyLoaderListener.class,
    CorporationPropertyLoaderListener.class,
    UserAndMasterPropertyLoaderListener.class,
    TestPropertyLoaderListener.class,
    RetryFailedTestsListener.class,
    BuildInformationRetriever.class,
    ReportPortalTestNGListener.class})`

**Comment by evjlobanova** [comment]
https://github.com/reportportal/agent-java-testNG/issues/66

**Comment by DzmitryHumianiuk** [comment]
same to reportportal/agent-java-testNG#66
