### ISSUE TITLE
How to configure Elasticsearch Service from external server instead of local

### ISSUE THREAD

**Issue by Vasanth185** [reportportal/reportportal#764]
Is there any way to point report portal to use the elastic search installed in a different server? If so how to configure the same?

**Comment by evjlobanova** [comment]
@AlehB Please help with this issue?
@Vasanth185 could you please send us where you want to deploy? Is it Docker or Kuber?
Which version 4 or 5?

**Comment by AlehB** [comment]
Hi @Vasanth185 ,

If you are using Kubernetes version of RP 5.0, then it is described in the documentation (https://github.com/reportportal/kubernetes/tree/master/reportportal/v5#7-elasticsearch-installation). All you need to do is correctly set ES address and port in values.yaml and make sure your network rules are allowed such connection
For Docker version please use env variable "ES_HOSTS" for service analyzer to change the ES endpoint

**Comment by Vasanth185** [comment]
Hi @AlehB & @evjlobanova  ,

Thanks for the response and solution, I am using Report Portal 4 and using Docker version for ES. Adding "ES_HOSTS" for service analyzer did the trick.

But after adding the endpoint in service analyzer the logs are routed to ES, but AUTO-ANALYSIS is not working after i changed the endpoint of ES. Every launch is going to 'To Investigate' status. In AUTO-ANALYSIS settings the Remove and Generate Index are disabled. PFA for screenshot. Let me know if any more information is required from my end.


![Capture](https://user-images.githubusercontent.com/58480211/70803868-0d83b480-1ddb-11ea-9f17-6dd19100adcb.PNG)

**Comment by AlehB** [comment]
Hi @Vasanth185 ,
We propose you to move to ReportPortal 5, we do not fully support the previous version anymore
Docker Compose https://github.com/reportportal/reportportal/blob/master/docker-compose-v5.yml
Kubernetes Helm chart https://github.com/reportportal/kubernetes/tree/master/reportportal/v5

**Comment by Vasanth185** [comment]
Hi @AlehB ,

Thanks for the help. After migrating to RP 5, I am able to configure Elasticsearch Service to external server and AUTO-ANALYSIS also working. 👍
