### ISSUE TITLE
Launches Tab Attachment displays only base-encoded images

### ISSUE THREAD

**Issue by chhatbarjignesh** [reportportal/reportportal#765]
Launches Tab Attachments is displaying only base encoded images, everything else is going as a attachment of txt see attached screenshot

is there any way to render the image that is uploaded somewhere as a part of attachment in launch?
for example to reduce the data load in our reporting we upload all our screenshots in S3 and just render the URL from S3 inside the report, I wanted to know if this feature is available or not

![image](https://user-images.githubusercontent.com/34551874/70149813-df81d000-1676-11ea-9178-679717d0ffdb.png)

**Comment by DzmitryHumianiuk** [comment]
you can add link into logs, using markdown.
and share it within logs.

like this
```
![Image of From S3](https://reportportal.io/resources/site.bb1ee4.png)
```
will show you this in logs
![Image of From S3](https://reportportal.io/resources/site.bb1ee4.png)

**Comment by sandeepnagra** [comment]
@DzmitryHumianiuk - is that the correct image you intended to upload? I think it should be the image for scenario logs. We tried it at our end with following markdown didn't work. It just print it as a string. @chhatbarjignesh will share the screenshot

`![Image of From S3](https://reportportal.io/resources/site.bb1ee4.png)`

**Comment by chhatbarjignesh** [comment]
I tried as per your suggestion but it is not rendering the image.

![image](https://user-images.githubusercontent.com/34551874/70170950-bfb0d300-169b-11ea-8622-c143ca39829a.png)

**Comment by sandeepnagra** [comment]
Also, we know it supports embedded base64 screenshot images and text file but does it support videos too?

**Comment by DzmitryHumianiuk** [comment]
@chhatbarjignesh @sandeepnagra 
sorry, missed it with v5 already :)

**in v5** we have markdown parsed by default.
in case if switcher is ON.
![image](https://user-images.githubusercontent.com/11332788/70241771-a6358700-1780-11ea-9b29-ac7493fad8a7.png)



**in v4** you have to prepend `!!!MARKDOWN_MODE!!!` to you log.

like   
```java
String log = "![Image of From S3](https://reportportal.io/resources/site.bb1ee4.png)";
log = "!!!MARKDOWN_MODE!!!" + log;
```

**Comment by chhatbarjignesh** [comment]
@DzmitryHumianiuk Thanks for the quick response. I tried the solution and looks like it worked half
Do you know what might be wrong, its displaying broken thumbnail

![image](https://user-images.githubusercontent.com/34551874/70243334-65b61900-1740-11ea-9776-6308eba59d9f.png)

**Comment by DzmitryHumianiuk** [comment]
@chhatbarjignesh most likely you should have access token embedded into the url of the image.

google for it.
i'm sure it's a general question.

and most likely you will see access error in network tab of your browser when loading the page with image, which you mentioned above.
this error can give you some details

**Comment by DzmitryHumianiuk** [comment]
@sandeepnagra yes, it supports video as well, if send as base64 encoded.

**Comment by chhatbarjignesh** [comment]
Thank you @DzmitryHumianiuk for quick responses, will Markdown work for videos? just asking

**Comment by DzmitryHumianiuk** [comment]
@chhatbarjignesh nope.

**Comment by chhatbarjignesh** [comment]
Thank you so much @DzmitryHumianiuk closing the issue
