### ISSUE TITLE
[v5bug] Send defect to the latest launches returns 500 status code 

### ISSUE THREAD

**Issue by OstapJ** [reportportal/reportportal#766]
**Describe the bug**
`Send defect to` feature doesn't copy the defect link to the latest launch

**To Reproduce**
1. Open the test which has a history of launches where previous launches have Bug-type
2. Click on `Send defect to` button to copy the bug type to the latest launch

**Expected behavior**
The latest launch has Product bug attached the same as from where you copied it

**Screenshots**
![image](https://user-images.githubusercontent.com/5707734/70163218-c6553f80-16c7-11ea-8a81-fe5f997fa243.png)
![image](https://user-images.githubusercontent.com/5707734/70163372-04eafa00-16c8-11ea-81a5-183297472112.png)

**Desktop (please complete the following information):**
 - OS: [MacOS 0.14.6]
 - Browser [chrome]
 - Version [78.0.3904.108]

**Additional context**
Payload request 
`{"issues":[{"issue":{"issueType":"pb001","comment":"RPD-5700 values in Source filter populated from incorrect DB column Similar issue has been found in history as: *IssueType:* Product Bug *TicketIds:* *IssueDescription:* RPD-5700 values in Source filter populated from incorrect DB column","autoAnalyzed":false,"ignoreAnalyzer":false,"externalSystemIssues":[]},"testItemId":60}]}`
That's the test from generated DEMO data (**updateDefaultMode**)

**Comment by DzmitryHumianiuk** [comment]
@OstapJ what are the services numbers in `docker-compose.yml`?

**Comment by evjlobanova** [comment]
@OstapJ

**Comment by OstapJ** [comment]
@DzmitryHumianiuk @evjlobanova sorry for the delay.
Current version:
API Service: 5.0.0-RC-2;Index Service: 5.0.4;Authorization Service: 5.0;Service UI: 5.0.0-RC-3

**Comment by evjlobanova** [comment]
@OstapJ Hello, please check the latest version of RP 5.0.0-RC-6

Soon official 5.0 version will be available.
If issue reproduces on RC-5, please reopen this issue
