### ISSUE TITLE
GitHub Authorization Not Working[v5bug]

### ISSUE THREAD

**Issue by nickhodaly** [reportportal/reportportal#767]
**Describe the bug**
GitHub Authorization is not working properly. After clicking the `Login with GitHub` button I am redirected to a page with the following text:
`Full authentication is required to access this resourceunauthorized`

The Authorization callback URL I am using is: `/uat/sso/me/github/synchronize`

**To Reproduce**
Enable GitHub Authorization on V5. Use Login with GitHub.

**Expected behavior**
I should be logged into Report Portal using my GitHub credentials.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 78

This was working fine on V4.

**Comment by DzmitryHumianiuk** [comment]
@nickhodaly do you use GitHub Enterprise?

**Comment by nickhodaly** [comment]
> @nickhodaly do you use GitHub Enterprise?

@DzmitryHumianiuk Yes sir, I do.

**Comment by nickhodaly** [comment]
I have also tried `/uat/sso/login/github` as the authorization callback URL with no success as well.

**Comment by DzmitryHumianiuk** [comment]
That requires some changes in code. 
We never used enterprise version, so don’t have account to test

**Comment by nickhodaly** [comment]
> That requires some changes in code.
> We never used enterprise version, so don’t have account to test

Is this something that is specific to V5? We had GitHub auth working properly in V4.

**Comment by DzmitryHumianiuk** [comment]
Hmmmmm. Then it should be a bug

**Comment by nickhodaly** [comment]
> Hmmmmm. Then it should be a bug

@DzmitryHumianiuk Can you let me know if I am using the correct authorization callback URL? Where can I find documentation on the homepage URL and authorization callback URL that are required by GitHub Auth?

Thanks for your help!

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/reportportal/wiki/How-to-configure-login-via-GitHub

**Comment by nickhodaly** [comment]
> https://github.com/reportportal/reportportal/wiki/How-to-configure-login-via-GitHub

Using the Homepage URL and Authorization callback URL listed on that doc I go through the process of sharing my GitHub details with Report Portal, click 'Authorize' button and I am redirected to:

```
Access to test.reportportal.com was denied You don't have authorization to view this page.
HTTP ERROR 403
```

The url in the address bar on this page is: `https://test.reportportal.com/uat/sso/login/github?code=4cdXXXXXXXXXXX12&state=bXXXXi`

**Comment by nickhodaly** [comment]
@ihar-kahadouski Thank you very much for pointing us in the right direction. 

Our issue was with our minio configuration where we set our minio domain incorrectly. Once this issue was resolved profile pictures started working, logs with attachments started working as well as GitHub OAuth.

**Comment by DzmitryHumianiuk** [comment]
@nickhodaly did you made any specific configuration for GitHub enterprise other than listed here?
https://github.com/reportportal/reportportal/wiki/How-to-configure-login-via-GitHub

Just want to clarify that instruction is correct.
plz let me know

**Comment by nickhodaly** [comment]
> @nickhodaly did you made any specific configuration for GitHub enterprise other than listed here?
> https://github.com/reportportal/reportportal/wiki/How-to-configure-login-via-GitHub
> 
> Just want to clarify that instruction is correct.
> plz let me know

No, nothing special needed to be done. We had misconfigured minio and that was blocking the user profiles pictures, test attachments and the github Auth. Once we corrected the minio deployment issue it fixed our other issues.

**Comment by DzmitryHumianiuk** [comment]
@nickhodaly thanks bro!
