### ISSUE TITLE
Markdown support for Video links in Logs

### ISSUE THREAD

**Issue by chhatbarjignesh** [reportportal/reportportal#768]
**Describe the solution you'd like**
It would be great if ReportPortal can support Video markdown similar to how it supports for Images in Logs

something like that is already available for images like below

`![Image of From S3](https://reportportal.io/resources/site.bb1ee4.png)`

**Is your feature request related to a problem? Please describe.**
Its not related to any problem in reportportal but in our framework we record all our execution as a video and upload them in AWS S3 to save space in the report. So if markdown can support video that will be great feature for us.

**Comment by sandeepnagra** [comment]
@DzmitryHumianiuk - I know you had recommended attaching videos as base64 encoded however when I did that, it doesn't render the video and it looks like:
![image](https://user-images.githubusercontent.com/9598669/70267869-500b1880-176d-11ea-89f9-4b2bd6c91ddc.png)
Clicking on it downloads the .mov of the videos which plays fine in local player. One thing to note here is that the original video file was an mp4. I am encode it in base64 and then embed in our reports.
```
base64_vid = Base64.encode64(File.open('./videos/sample.mp4', 'rb:ASCII-8BIT:UTF-8', &:read))
embed(base64_vid, 'video/mp4;base64')
```

**Comment by sandeepnagra** [comment]
Just to add more context to original request, we are looking for markdown support for video which can render videos like:
![image](https://user-images.githubusercontent.com/9598669/70272749-c5c7b200-1776-11ea-8382-395ddd894400.png)

**Comment by chhatbarjignesh** [comment]
If html markdown support is added this will solve the bigger problem for us as well we have some custom html reporting that we do for some of our different test.

**Comment by sandeepnagra** [comment]
> @DzmitryHumianiuk - I know you had recommended attaching videos as base64 encoded however when I did that, it doesn't render the video and it looks like:
> ![image](https://user-images.githubusercontent.com/9598669/70267869-500b1880-176d-11ea-89f9-4b2bd6c91ddc.png)
> Clicking on it downloads the .mov of the videos which plays fine in local player. One thing to note here is that the original video file was an mp4. I am encode it in base64 and then embed in our reports.
> 
> ```
> base64_vid = Base64.encode64(File.open('./videos/sample.mp4', 'rb:ASCII-8BIT:UTF-8', &:read))
> embed(base64_vid, 'video/mp4;base64')
> ```

I noticed that this bug is reported here already - https://github.com/reportportal/service-ui/issues/2243

**Comment by sandeepnagra** [comment]
> Just to add more context to original request, we are looking for markdown support for video which can render videos like:
> ![video_markdown](https://user-images.githubusercontent.com/9598669/70273085-6a49f400-1777-11ea-8770-6ec3cbf95933.png)
> If inline HTML markdown support is added then it will solve all the problems. I think markdown does have inline HTML support - https://daringfireball.net/projects/markdown/syntax#html

We are using a hack to display a thumbnail clicking which open an html page in new tab with video embedded in it.
```[![Watch the video](https://<s3-bucket-url>/sample-thumbnail.jpg)](https://<s3-bucket-url>/page-with-embedded-video.html) ```

**Comment by DzmitryHumianiuk** [comment]
Than it should be splitted in 2 requests:

- support inline HTML in logs
- add video player for representing video links

**Comment by evjlobanova** [comment]
#117
