### ISSUE TITLE
ReportPortal V5 API Log Attachments Documentation

### ISSUE THREAD

**Issue by nickhodaly** [reportportal/reportportal#769]
Can someone please provide more detailed documentation on how to attach screenshots and other files to logs. This functionality was working fine for me on V4 and does not seem to work on V5. I am using multi-part requests with no luck.

I am using the `/v1/{projectName}/log` endpoint.

**Comment by evjlobanova** [comment]
https://github.com/ihar-kahadouski/dev-guide/blob/master/reporting.md#batch-save-logs

**Comment by evjlobanova** [comment]
If it helps, please close the issue.

If you still have questions regarding this topic, please let @ihar-kahadouski know

**Comment by nickhodaly** [comment]
@evjlobanova @ihar-kahadouski I have followed the documentation [you linked above](https://github.com/ihar-kahadouski/dev-guide/blob/master/reporting.md#batch-save-logs) using postman to keep things as simple as possible and I still have not had any success attaching files to logs in Report Portal V5.

Again, this functionality was working fine for me in V4.

These are the versions we are using:
Current version:
- API Service: 5.0.0-RC-2;
- Index Service: 5.0.4;
- Authorization Service: 5.0;
- Service UI: 5.0.0-RC-3;

Is this something someone can look into and determine if it is a reproducible bug?

**Comment by ihar-kahadouski** [comment]
@nickhodaly Have you joined to our slack? Can you contact me there and provide mode detailed information about your problem?

**Comment by nickhodaly** [comment]
@ihar-kahadouski Thank you very much for pointing us in the right direction. 

Our issue was with our minio configuration where we set our minio domain incorrectly. Once this issue was resolved profile pictures started working, logs with attachments started working as well as GitHub OAuth.
