### ISSUE TITLE
Send Email notification with attachment (Log files)

### ISSUE THREAD

**Issue by Agurul** [reportportal/reportportal#770]
Hi, Is there any option to send email with log files attached ? If not Can you add it.

I'm using report portal for data validation test results publishing. Since it is huge data validation I can't use assertion in my code instead of that I ll write results into csv file and publishing csv file as my log file. 

I need this file to be attached to email and send the results through email. Since Assertions not using all my tests will be passed. So I need this attachment in the email to know the failures.

**Comment by DzmitryHumianiuk** [comment]
hi @Agurul,
This request is quite specific to your case, and does not fall under the General solution. 
So I'm not sure we'll ever put it in our backlog.

My vision here, first of all, that automated test cases with **no** Assertions is not the best choice.

At least,  if you have a mixture of tests that have Asserts and that do not, then I would recommend to set No-Assertion test cases to `FAILED` state by default.
And switch state to `PASSED` only after passed manual verification of CSV file.

This can guarantee that you will not miss any NO-ASSERT-CSV test case for verification.
We call it Semi-automation.
And have some thoughts to introduce additional state, as `Undefined` or smth similar.

Anyway, in RP v5.0 we added possibility to switch tests from PASSED to FAILED and vice versa from UI.

I'm not sure about you landscape, but most likely CSV can be verified in test itself.
Still if above does not make sense, you can list CSV file in logs, not like attachment file, but full content. And verify it right from RP screen.

With expert mode ON, there is a way to implement custom script, which can trigger RP API and collect required attachments either to send it via email, push it to the chat or anything else.


![image](https://user-images.githubusercontent.com/11332788/70623210-a5906b00-1c2e-11ea-8521-85f6c12da4c1.png)
