### ISSUE TITLE
[v5bug] - Test data not displayed on ReportPortal from XCUITest

### ISSUE THREAD

**Issue by moatazeldebsy** [reportportal/reportportal#771]
**Describe the bug**
Hi I want to integrate ReportPortal with XCUITest using this agent and I updated the info.plist with the data like the screenshot, but when running the test and after the test finished I didn’t get any data in report portal.

**Screenshots**
<img width="739" alt="70258076-d9314800-178b-11ea-9dde-19d16ac1767c" src="https://user-images.githubusercontent.com/45570191/70526983-18c0b100-1b4b-11ea-9fff-4412534e756f.png">

**Desktop (please complete the following information):**
 - OS: [Mac OS]
- XCode 11.2.1

**Comment by evjlobanova** [comment]
@moatazeldebsy please add any details. Could you please send a link to agent that you used?

**Comment by SriMus** [comment]
Hi
Im having the same issue '**Test data not displayed on ReportPortal from XCUITest**' 
Any update on it? 
Thanks
