### ISSUE TITLE
Not able to add Project activity panel widget

### ISSUE THREAD

**Issue by pkum11** [reportportal/reportportal#778]
**Describe the bug**
When trying to add project activity panel widget, getting error

Could not save widget on server : incorrect save widget request. Field 'start_time' cannot be used for creating data for widgets.

**Expected behavior**
Widget should get added.

**Screenshots**

**Versions:**
 - OS=Mac Mojave, Browser=chrome 78
 - Version of RP 
Current version: Analysis Service: 4.3.0; API Service: 4.3.0; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.0;

**Comment by pkum11** [comment]
Went through default selections only

**Comment by evjlobanova** [comment]
@pkum11 Going to be fixed in version 5.0

**Comment by evjlobanova** [comment]
Release of version 5.0 will be on the next week, please try and let us know if we can close an issue.

**Comment by pkum11** [comment]
Once we upgrade to 5.0, i will check and close this tkt accordingly.

**Comment by evjlobanova** [comment]
I close issue, feel free to reopen in case of problems
