### ISSUE TITLE
Cannot login, need Default Admin

### ISSUE THREAD

**Issue by dmakhno** [reportportal/reportportal#78]
After #seleniumcamp and @DzmitryHumianiuk. 
I've installed locally. Reading docs.
Everything is up, however I cannot find an default admin or/and how to create it.

Please add somewhere to docs how to login. 
Now new fancy ReportPortal, like a brick for me. Happy jumping, but no entrance and no wonderful reports.

PS. Cannot use github login, since it works locally for now.

**Comment by fasterfish** [comment]
You can use next:
>>5. User next login\pass for access: default\1q2w3e and superadmin\erebus.

admin account username: superadmin, password: erebus.
user account username: default, password: 1q2w3e

**Comment by dmakhno** [comment]
Thanks. I read getting started on the site and upped site. But not in readme.

**Comment by knayeneni** [comment]
Hi, I used admin account username: superadmin, password: erebus and tried with default/1q2w3e as well, but I am still not able to login and I am getting "An error occurred while connecting to Server".

Please let me know what else needs to be done...Thanks

**Comment by knayeneni** [comment]
Btw, I did the installation part without dockers as I am running it on Windows 7. Once I am able to run it successfuly, I would like to add them to VM's which are on Windows 10.
Currently these are the services which are showing and I am not sure that's the reason why I am not able to login, but in that case can some one please tell me why index, ui and gateway are not showing up even though those services are up and running...thanks
![image](https://user-images.githubusercontent.com/49925642/56930537-93e4c380-6aa2-11e9-9af8-0ea081868960.png)

**Comment by DzmitryHumianiuk** [comment]
@knayeneni if you don't see them under login form on ui, mostly likely they are not registered in consul.

try to delete consul cache at `/data/consul` first. and restart
