### ISSUE TITLE
Use of import of zip file in reportportal.io

### ISSUE THREAD

**Issue by likitha-dot** [reportportal/reportportal#780]
I used the import functionality to importing a zip file. That zip file contains test cases, reportportal.properties file, drivers, pom.xml file and also a testNg.xml file but i didn't get any update can anyone suggest me or explain me how to use this import functionality in reportportal.io below i have attached a image after uploading the zip file the wrong output was generated some of failed issues also are there but we are getting wrong output.

**Comment by likitha-dot** [comment]
<img width="640" alt="demo_maven" src="https://user-images.githubusercontent.com/59014290/71171634-4660d500-2284-11ea-86fd-878edbf63429.png">

**Comment by evjlobanova** [comment]
@likitha-dot Please check documentation about import https://reportportal.io/docs/Log-data-import

**Comment by evjlobanova** [comment]
@likitha-dot did it help?

**Comment by evjlobanova** [comment]
Because of no responce, I have closed this issue, feel free to reopen it
