### ISSUE TITLE
Widgets copying

### ISSUE THREAD

**Issue by hs-nmikulskaya** [reportportal/reportportal#785]
**Describe the solution you'd like**
As a user with the role of a project manager, I want to be able to copy widgets, which allows me to create similar widgets with different filters.

**Is your feature request related to a problem? Please describe.**
When I customize dashboards, I need to create a series of similar widgets that have the same functionality and are based on filters, where the difference is only in the parameters. For example, I create widgets with launch statistics for each environment. Conveniently, after you create a widget, you get the next one by simply copying this one and changing the name of the widget and its filter.

**Comment by evjlobanova** [comment]
Can be resolved with the same solution as https://github.com/reportportal/reportportal/issues/784
Closed as a duplicate
