### ISSUE TITLE
TestNG 7.1.0 and DataProvider

### ISSUE THREAD

**Issue by nagaeva-anastasia** [reportportal/reportportal#789]
**Describe the bug**
I have test with 17 data sets in yml file
Before it was split into separate test methods in RP, now RP shows it like attempts for Retry
So, I can't see failed items as 'To investigate'
**Expected behavior**
Each data set should be equals to test method in RP, failed item should be marked as 'To investigate'

**Screenshots**
previous behavior
![image](https://user-images.githubusercontent.com/5585400/71475340-cf31c080-27f0-11ea-9e0f-13e23fa6793b.png)

current behavior
![image](https://user-images.githubusercontent.com/5585400/71475297-9eea2200-27f0-11ea-99d8-8c084f0b755e.png)

**Versions:**
TestNG 7.1.0

compile group: 'com.epam.reportportal', name: 'agent-java-testng', version: '4.2.0'
compile group: 'com.epam.reportportal', name: 'logger-java-log4j', version: '4.0.1'

Current version: 
Analysis Service: 4.3.0; API Service: 4.3.4; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.6;

**Comment by evjlobanova** [comment]
@Yumfriez @HardNorth could you please check this case for version 5.0?

**Comment by HardNorth** [comment]
@nagaeva-anastasia Could you please switch on logger-java-log4j version 4.0.2 and agent-java-testng version 4.2.2?

**Comment by nagaeva-anastasia** [comment]
@HardNorth I switched on 
compile group: 'com.epam.reportportal', name: 'agent-java-testng', version: '4.2.2'
compile group: 'com.epam.reportportal', name: 'logger-java-log4j', version: '4.0.2'

but behavior is still the same

**Comment by HardNorth** [comment]
@nagaeva-anastasia which version of client-java your code uses now?

**Comment by nagaeva-anastasia** [comment]
4.0.19
![image](https://user-images.githubusercontent.com/5585400/71512404-11b5d480-28a7-11ea-9cf2-fcca70c67ca3.png)

**Comment by HardNorth** [comment]
How do you bypass these data-sets? Can you share the code of a data provider?

**Comment by nagaeva-anastasia** [comment]
the test has the following structure

```
public class SomeTest extends BaseTest {

    Entity entity;

    @DataProvider (name = "provider")
    public static Object[][] getData(){
        return readParametersFromYaml();
    }

    @Factory (dataProvider = "provider")
    public SomeTest(String param1, String param2, String param3) {
        entity = new Entity(param1, param2, param3);
    }

    @Test
    public void someChecks() {
        SoftAssert softAssert = new SoftAssert();
        // some actions
       softAssert.assertAll();
    }
}
```

with 

```
protected static Object[][] readParametersFromYaml() {
        return commonReadParametersFromYaml(baseConfiguration.getTestAPIBasePackage(), baseConfiguration.getDataAPIPath());
    }
```

and

```
protected static Object[][] commonReadParametersFromYaml(String testBasePackage, String dataPath) {
        LOG.traceEntry();

        String className = Thread.currentThread().getStackTrace()[3].getClassName()
                .replace(testBasePackage, "")
                .replace(".", "/");

        String fileName = String.format("%s%s.%s", dataPath, className, baseConfiguration.getDataExtension());
        LOG.info("File name: {}", fileName);

        Object[][] data = null;

        try {
            Yaml yaml = new Yaml();
            ClassLoader classLoader = ClassLoader.getSystemClassLoader();
            File file = new File(classLoader.getResource(fileName).getFile());
            FileInputStream ios = new FileInputStream(file);

            ArrayList<Map<String, String>> list = yaml.loadAs(ios, ArrayList.class);

            data = new Object[list.size()][];
            for (int i = 0; i < list.size(); i++) {

                List<String> values = list.get(i).values().stream().collect(Collectors.toList());
                int valuesSize = values.size();

                data[i] = new Object[valuesSize];
                for (int j = 0; j < valuesSize; j++) {
                    data[i][j] = values.get(j);
                }
            }
        } catch (Exception e) {
            LOG.error(e.getMessage());
        }

        return LOG.traceExit(data);
    }
```

**Comment by nagaeva-anastasia** [comment]
Hi, any updates on this?

**Comment by HardNorth** [comment]
@nagaeva-anastasia We are working on it

**Comment by evjlobanova** [comment]
We take this issue in the nearest sprints

**Comment by HardNorth** [comment]
@nagaeva-anastasia Hey, checkout this version: https://bintray.com/epam/reportportal/agent-java-testng/4.2.3

V5 fix will be released with new BETA.
