### ISSUE TITLE
How to attach Test failure ScreenShots and TestFailure Video To Logs in reportportal Using TestNG and Log4j2 With  java 

### ISSUE THREAD

**Issue by dharma-keyutech** [reportportal/reportportal#791]

**Comment by evjlobanova** [comment]
For version 4: https://github.com/reportportal/example-java-TestNG

Version 5 agent examples : https://github.com/reportportal/examples-java
And dex guide for reporting for version 5: https://github.com/ihar-kahadouski/dev-guide/blob/master/reporting.md

**Comment by dharma-keyutech** [comment]
Closed with This Below Code 
_______________________________________________________________________________________

// Take screenshots
		public static void onTestFailure() {
			   
			 ReportPortalMessage message = null;
			    try {
			    	TakesScreenshot ts = (TakesScreenshot)driver;
			    	File srcFile = ts.getScreenshotAs(OutputType.FILE);
			    	java.util.Date d= new java.util.Date();
			    	 org.apache.commons.io.FileUtils.copyFile(srcFile, new File("./ScreenShots/"+d.toString().replace(":", "_")+".png"));
			    	String rp_message = "test message for ReportPortal";
			        message = new ReportPortalMessage(srcFile, rp_message);
			    } catch (IOException e) {
			        e.printStackTrace();
			    }
			    logger.info(message);
		   
		}

**Comment by prilearning20** [comment]
This code is not working in adding screenshots.it displays like this as report portal object than as image 

14:08:22.694 [TestNG-PoolService-0] INFO Logs.Log4j.LogDriver - com.epam.reportportal.message.ReportPortalMessage@9e5e7e

**Comment by GopalSawant** [comment]
> Below Code Is for Taking Screenshots and passing to reportportal with logs
> 
> // Take screenshots
> public static void ScreenShot() {
> 
> ```
> 		 ReportPortalMessage message = null;
> 		    try {
> 		    	TakesScreenshot ts = (TakesScreenshot)driver;
> 		    	File srcFile = ts.getScreenshotAs(OutputType.FILE);
> 		    	java.util.Date d= new java.util.Date();
> 		    	 org.apache.commons.io.FileUtils.copyFile(srcFile, new File("./ScreenShots/"+d.toString().replace(":", "_")+".png"));
> 		    	String rp_message = "test message for ReportPortal";
> 		        message = new ReportPortalMessage(srcFile, rp_message);
> 		    } catch (IOException e) {
> 		        e.printStackTrace();
> 		    }
> 		    logger.info(message);
> 	   
> 	}
> ```

in which file should I add the mentioned code

**Comment by saicharan-ally** [comment]
in which file should the above mentioned code should be added  @meka-dharma ?

**Comment by OscarCarrilloTR** [comment]
@saicharan-ally did you find where should we add the code?

**Comment by OscarCarrilloTR** [comment]
> For version 4: https://github.com/reportportal/example-java-TestNG
> 
> Version 5 agent examples : https://github.com/reportportal/examples-java And dex guide for reporting for version 5: https://github.com/ihar-kahadouski/dev-guide/blob/master/reporting.md

I have tried to use with different examples, but unfortunately can't see any logs printed in ReportPortal neither for screenshots or messages. Is there any configuration or documentation that may I need to review?

**Comment by sharathhatter1** [comment]
I am not seeing the logs in the report portal, normal info and also screenshots. Can anyone help here
