### ISSUE TITLE
After a filter was edited a 'Display on launches' switch become switch on automatically 

### ISSUE THREAD

**Issue by hs-nmikulskaya** [reportportal/reportportal#794]
**Describe the bug**
1. Go to the 'Filter' tab.
2. Click on any filter has a 'Display on launches' switched off
3. Edit the filter and save it

Actual result: on the Filter tab the edited filter has the 'Display on launches' switch in On status.

**Expected behavior**
on the Filter tab the edited filter has the 'Display on launches' switch in OFF status.

**Versions:**
 - macOS, Chrome (the latest version)
 - Version of RP : 4.3.7

**Comment by DzmitryHumianiuk** [comment]
@hs-nmikulskaya it's not a bug. it works as designed.
once you click on the name - it opens it in Launches view, and displays it on it.

just click `Close` after edit and save

![image](https://user-images.githubusercontent.com/11332788/72163543-1022fb00-33d5-11ea-982c-e61459c8b1b3.png)
