### ISSUE TITLE
"error_code":5000,"message":"Unclassified error [null] while trying to create launch

### ISSUE THREAD

**Issue by shailesh07us-adp** [reportportal/reportportal#796]
**Describe the bug**
I am trying to create a launch by making API call. See the example powershell script below:
I had been using this script for long. I had created several launches with name 'currentgen_develop'
**If I change launch name then launch is getting created.**
### Is there any limit on number of launches with same name?

```
$apiKey = "4c5aa448-497d-485d-802f-00f090b768be"
$project = "abc"
$url = "http://101.19.404.69:8080/api/v1/" +$project + "/launch"
$headers = @{"Authorization" = "BEARER " + $apiKey}
$startTime = Get-Date
$tags = [System.Collections.ArrayList]@()
$tags.Add("develop")
$tags.Add("2230")

$body = @{
    description=''
    mode='DEBUG'
    name='currentgen_develop'
    start_time=$startTime.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss.ffffZ")
    tags=$tags
}

$launch = ""
$json = $body | ConvertTo-Json
$launch = Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $json -ContentType 'application/json'
Write-Host "Launch Id:" $launch.id
```
### tried on linux box too
```
set -x #echo off

url='http://101.19.404.69:8080/api/v1/abc/launch'
header="Authorization: bearer 4c5aa448-497d-485d-802f-00f090b768be"
body="{  
   	   \"description\": \"\",  
	   \"mode\": \"DEBUG\" ,
	   \"name\": \"currentgen_develop\",  
	   \"start_time\": \"$(date -u +"%Y-%m-%dT%T.%3NZ")\", 
	   \"tags\": [\"develop\",\"2230\"]  
	 }"
echo $url
echo $body

curl -X POST "$url" --header 'Content-Type: application/json' --header 'Accept: application/json' --header "$header" -d "$body"
```

But this is resulting in 
```
Invoke-RestMethod : {"error_code":5000,"message":"Unclassified error [null]"}
At line:21 char:11
+ $launch = Invoke-RestMethod -Uri $url -Method Post -Headers $headers  ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Expected behavior**
Launch should be created successfully

**Screenshots**

**Versions:**
 - OS, Browser
Win10, Linux

 - Version of RP [find it under Login form, copy as is]
Current version: Analysis Service: 4.3.0; API Service: 4.3.0; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.0;

**Comment by evjlobanova** [comment]
@shailesh07us-adp we have released a new version of ReportPortal 5. 
Now we do not support the 4th version.
Please, update your version to the latest one:
All details (reporting, deployment, data migration) about 5th version you can find in release note
https://github.com/reportportal/reportportal/releases/tag/5.0.0

**Comment by evjlobanova** [comment]
Please update ReportPortal, and tell us if your issue resolved.
If you still have a problems, please reopen this issue
