### ISSUE TITLE
Report Portal Display Count Of Test Cases

### ISSUE THREAD

**Issue by Hemanth211** [reportportal/reportportal#800]
Hi Team,

     I'm new to the report portal. I have installed the report portal in my local. Currently, I can see the count of lines executed in all test cases in the launches. 

- Is it possible to check the test case count also form the launches?
- Is it possible to display the dashboard whenever a launch is triggered?

Thanks in advance...

**Comment by evjlobanova** [comment]
@Hemanth211 could you pleae add  more context to these questions, they are a  little bit confusing.
What do you mean under:" the test case count also form the launches"
And: "Is it possible to display the dashboard whenever a launch is triggered?"

**Comment by evjlobanova** [comment]
Due to response, i close this issue.
Feel free to reopen it
