### ISSUE TITLE
How to Remove Reportportal  completly From localhost

### ISSUE THREAD

**Issue by dharma-keyutech** [reportportal/reportportal#801]

**Comment by DzmitryHumianiuk** [comment]
@dharma-keyutech what do you mean?

**Comment by dharma-keyutech** [comment]
Need To remove Reportportal From my PC

**Comment by DzmitryHumianiuk** [comment]
- stop docker `docker stop $(docker ps -q)`
- find all RP related images
- delete images with docker
- delete folder `/data` in folder, where your `docker-compose.yml` file was placed

**Comment by dharma-keyutech** [comment]
Thank You
