### ISSUE TITLE
[v5] Permission error message from API with valid token

### ISSUE THREAD

**Issue by liiight** [reportportal/reportportal#805]
**Describe the bug**
Many documented API endpoints return the following error :
```
{
  "errorCode": 4003,
  "message": "You do not have enough permissions. Access is denied"
}
```
Even though the used token is valid.

**To Reproduce**

An example of a cURL that works:
```bash
Ors-MacBook-Pro-2:~ orcarmi$ curl --request GET \
→   --url http://127.0.0.1:8080/api/v1/user \
→   --header 'authorization: Bearer 5838afe2-b6df-4146-b6e1-c569fde9516f'
{"id":2,"userId":"default","email":"defaultemail@domain.com","photoId":"dXNlcnMvZGVmYXVsdA","fullName":"tester","accountType":"INTERNAL","userRole":"USER","photoLoaded":true,"metadata":{"last_login":1580290294647,"attachmentContentType":"image/png"},"assignedProjects":{"default_personal":{"projectRole":"PROJECT_MANAGER","entryType":"PERSONAL"}
```

An example of one (using the same token) that doesn't work:

```bash
Ors-MacBook-Pro-2:~ orcarmi$ curl --request GET \
→   --url http://127.0.0.1:8080/api/v1/project/list \
→   --header 'authorization: Bearer 5838afe2-b6df-4146-b6e1-c569fde9516f'
{"errorCode":4003,"message":"You do not have enough permissions. Access is denied"}
```
There many other endpoints documented on the Swagger page that share this issue (like `project/list`, `project/names` and more)

**Note**: I am aware that the token is shown here, it is deliberate in order to demonstrate that both requests are using the same token. I run this instance on a local docker in my network and I regenerated a new token right after openeing this issue :) 

**Expected behavior**
API should work as credentials are valid.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 5.0.0

**Additional context**
Installed via docker-compose

**Comment by avarabyeu** [comment]
@liiight in order to list all the project, your user should has ADMINISTRATOR role. Plz, make sure you have one.

**Comment by liiight** [comment]
Oh wow. I was confused by a PM and admin. My apologies.
