### ISSUE TITLE
 [v5] Method Type filter is not applied to Test History

### ISSUE THREAD

**Issue by atilainovecky** [reportportal/reportportal#806]
**Describe the bug**

1. Report a test which include some method type like 'Before class',  'Before method' ..
e.g. 10 Test and 2 Before Method
![image](https://user-images.githubusercontent.com/56154736/73468329-e5e5ad00-4384-11ea-97d0-721960ffb316.png)
2. Apply Method type filter -  Only tests are filtered
![image](https://user-images.githubusercontent.com/56154736/73468942-e16dc400-4385-11ea-99b1-f85e62ed3200.png)
3. Click on History button
4. Test history is generated for 'Before class' too but only first 10 items is generated. 2 rows for with method type Test are missing.
![image](https://user-images.githubusercontent.com/56154736/73469498-b768d180-4386-11ea-96c3-834be91440bd.png)

**Comment by evjlobanova** [comment]
![image](https://user-images.githubusercontent.com/30413511/74744417-458ff380-5273-11ea-9c90-6ea762cac0fb.png)
![image](https://user-images.githubusercontent.com/30413511/74744436-4c1e6b00-5273-11ea-88b9-910294b7cb2e.png)

**Comment by evjlobanova** [comment]
I have checked the version 5, and I can see Before methods on the History table.
Could you please check one more time

**Comment by evjlobanova** [comment]
Closed because of no response, feel free to reopen
