### ISSUE TITLE
Test launch doesn't finish despite all tests are finished

### ISSUE THREAD

**Issue by Natallia1** [reportportal/reportportal#807]
**Describe the bug**
The same issue as https://github.com/reportportal/reportportal/issues/795 
I get it for ReportPortal.Shared v2.5.0 and ReportPortal.VsTest.TestLogger v2.3.9.

Test passes, but it can't finish on report portal. 

Error:
Finishing to send results to Report Portal...System.AggregateException: Cannot finish launch due finishing of child items failed. .......
Response Body: {"error_code":4001,"message":"Incorrect Request. [Field 'name' should not contain only white spaces and shouldn't be empty.] [Field 'name' should have size from '1' to '256'.]

What is field 'name' in this context? 'Name' field in ReportPortal.config.json is filled and is shown in report portal as expected.

**Versions:**
ReportPortal.Shared v2.5.0
ReportPortal.VsTest.TestLogger v2.3.9.

**Comment by nvborisenko** [comment]
Your configuration is correct. The issue is that logger cannot understand test name correctly. Could you please set `ReportPortal_TraceLevel=Verbose`, execute tests again and share `ReportPortal.*.log` files.

Or prepare simple test project to reproduce the issue?

**Comment by nvborisenko** [comment]
@Natallia1 any news? The fix is easy, but we need reproduce the issue.

For internal team: we need document how to turn on internal logging mechanism. It was appeared in recent versions.

**Comment by evjlobanova** [comment]
Closed due to no response
