### ISSUE TITLE
Forgot superadmin password

### ISSUE THREAD

**Issue by hiro-satoh-nestle** [reportportal/reportportal#809]
I forgot my superadmin password. So how to reset or recover it?

Thanks!

**Comment by evjlobanova** [comment]
@hiro-satoh-nestle try to change it in DB manually.

**Comment by chgans** [comment]
Is there any instruction for that?

**Comment by evjlobanova** [comment]
UPDATE users
    SET password = 'a0$vhlxLsj.HcuQVrbRTmOu6OOjTYK/ZeiLTKEA2Sf5JOaxZ98/KHGem'
    WHERE login = 'superadmin';

**Comment by Pink-Bumblebee** [comment]
@tmax22 , maybe this information will help you: https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.5.1#migration-from-version-50-to-51

**Comment by tmax22** [comment]
@Pink-Bumblebee yes it did! thank you!
