### ISSUE TITLE
Can't finish launch on v5

### ISSUE THREAD

**Issue by nagaeva-anastasia** [reportportal/reportportal#810]
**Describe the bug**
Can't finish launch with exception
Failed to force finish the launch: Unclassified error [org.hibernate.exception.SQLGrammarException: could not execute statement]

Also, all test methods are still running. 
Before and After methods are finished normally.
In Test NG I can see that all methods are finished normally.

I tried to debug finish methods in TestNGService, and everything looks ok, except rq.launchUuid= null in method buildFinishTestMethodRq.

build.gradle
    compile group: 'com.epam.reportportal', name: 'agent-java-testng', version: '5.0.0-BETA-8'
    compile group: 'com.epam.reportportal', name: 'logger-java-log4j', version: '5.0.0-BETA-8'
    testCompile group: 'org.testng', name: 'testng', version: '7.1.0'

Current version:
API Service: 5.0.0;
Index Service: 5.0.5;
Authorization Service: 5.0.0;
Service UI: 5.0.0;

Please, help me to understand the possible reasons.

Launch does not have passed or failed items
![image](https://user-images.githubusercontent.com/5585400/73750192-cb894600-476d-11ea-858d-4708a491afa3.png)

The same for suite and for tests
![image](https://user-images.githubusercontent.com/5585400/73750220-d80d9e80-476d-11ea-949c-ca0a5860e354.png)

Test is in progress
![image](https://user-images.githubusercontent.com/5585400/73750265-ee1b5f00-476d-11ea-82b0-6b7bde3716dd.png)

But it completely finished in TestNG
![image](https://user-images.githubusercontent.com/5585400/73750310-fecbd500-476d-11ea-9525-eecd31c5fa0d.png)

Additional stack trace from log file
`Caused by: org.postgresql.util.PSQLException: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification
  Where: SQL statement "INSERT INTO statistics (s_counter, statistics_field_id, item_id)
            (SELECT 1, executions_field_id, item_id
             FROM (SELECT item_id FROM test_item WHERE path @> (SELECT path FROM test_item WHERE item_id = new.result_id)) AS temp_bulk)
        ON CONFLICT (statistics_field_id,
            item_id)
            DO UPDATE SET s_counter = statistics.s_counter + 1"
PL/pgSQL function update_executions_statistics() line 72 at SQL statement
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
        ... 154 common frames omitted`

**Comment by nagaeva-anastasia** [comment]
I also tried to remove elastic search indexes or re-generate it. It does not help.

**Comment by nagaeva-anastasia** [comment]
Sorry, I can't live without RP, so I revert update back to
Analysis Service: 4.3.0; API Service: 4.3.4; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.6;

**Comment by evjlobanova** [comment]
@HardNorth @ihar-kahadouski could you please look why this issue appears? 
 Can we help?

**Comment by numo16** [comment]
While it doesn't solve the problem from a clean setup standpoint, you can execute the following in the reportportal database on your postgresql instance to create the necessary unique indices required to finish launches

```sql
CREATE UNIQUE INDEX ON statistics (statistics_field_id, item_id);

CREATE UNIQUE INDEX ON statistics (statistics_field_id, launch_id);
```

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova we need to put it for api team for investigation.
why these indexes missing from clean setup

**Comment by HardNorth** [comment]
@DzmitryHumianiuk I believe it depends on user setup path. If there was something like this: RP4->RP5-RC->RP5 there might be DB migration issues. But for clean setup it works rather good now.

**Comment by DzmitryHumianiuk** [comment]
Ok,
then we can close this.

As I see topic started @nagaeva-anastasia reverted to RPv4.

@nagaeva-anastasia i'll recommend you to try RPv5.1 once it available.
it should rid off child'ish issues.

**Comment by nagaeva-anastasia** [comment]
we tried to upgrade our instance once again
from RP4 to RP5.2, got the same error, and workaround with manual creating of indexes helped.

**Comment by DzmitryHumianiuk** [comment]
The flow should be 4.x -> 5.0 ->5.x
in order to avoid extra manual steps.

but glad it worked.

**Comment by nagaeva-anastasia** [comment]
yep, we did it according to instruction
https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.5.1

**Comment by tdaniely-dn** [comment]
I also migrated 4.3 -> 5.0 -> 5.5. And same thing happened.
It seems at some point in the migration somehow these constraints disapear:
```sql
    CONSTRAINT unique_stats_item UNIQUE (statistics_field_id, item_id),
    CONSTRAINT unique_stats_launch UNIQUE (statistics_field_id, launch_id),
```

**Comment by evjlobanova** [comment]
@tdaniely-dn Could you please check the documentation https://reportportal.io/docs/How-to-resolve?

**Comment by tdaniely-dn** [comment]
None of that is relevant, I fixed by manually adding the constraints again.
Unclear why they are getting removed. Possibly something to do with the migrate tool, but I'm not going to analyze further.

**Comment by evjlobanova** [comment]
@pbortnik @miracle8484 could you please check this thread
