### ISSUE TITLE
ERROR: for db-scripts  Container "0aaed66aebea" is unhealthy

### ISSUE THREAD

**Issue by ShashiSasuke02** [reportportal/reportportal#811]
Unable to start the Portal.

Machine:
Windows 10
Docker 2.1.03

Command to launch :
docker-compose -p reportportal up -d --force-recreate
[docker-compose.txt](https://github.com/reportportal/reportportal/files/4164902/docker-compose.txt)

Errors:
ERROR: for api  Container "0aaed66aebea" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by pbortnik** [comment]
Hi, can you provide us some logs for api, postgres?

**Comment by ShashiSasuke02** [comment]
2020-02-07 09:24:28.080 UTC [50] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
2020-02-07 09:24:28.080 UTC [50] HINT:  The server must be started by the user that owns the data directory.
child process exited with exit code 1
Logs :
initdb: removing contents of data directory "/var/lib/postgresql/data"
running bootstrap script ... The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

**Comment by Dhams-1** [comment]
Hi All,
@ShashiSasuke02 
I am very new to reportportal. I also face the issue. kindly let me know how to solve the same

**Comment by barvin** [comment]
@Dhams-1, first, make sure you have commented/uncommented appropriate lines in docker `docker-compose.yml` file according to this section: [Deploy ReportPortal with Docker on Windows](https://reportportal.io/docs/Deploy-with-Docker%3Edeploy-reportportal-with-docker-on-windows).

Then before running `docker-compose up` command, set this environment variable:
```
set COMPOSE_CONVERT_WINDOWS_PATHS=1
```
That worked for me on Windows 10.

**Comment by Dhams-1** [comment]
@barvin Thank you for you help. it worked for me :)

**Comment by jsingh-qualitrol** [comment]
Hello @Dhams-1 @barvin 

I am also facing same issue, Please let me know how i can set the environment variable. Please share the updated docker-compose.yml



PS D:\> docker-compose -p reportportal up -d --force-recreate
Recreating reportportal_gateway_1       ... done
Recreating reportportal_ui_1            ... done
Recreating reportportal_uat_1           ... done
Recreating reportportal_minio_1         ... done
Recreating reportportal_elasticsearch_1 ... done
Recreating reportportal_rabbitmq_1      ... done
Recreating reportportal_postgres_1      ... done
Recreating reportportal_index_1         ... done
Recreating reportportal_analyzer_1      ... done

ERROR: for db-scripts  Container "de8f90b8f974" is unhealthy.

ERROR: for api  Container "de8f90b8f974" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by lind-eduard** [comment]
For those who still struggle on windows: 
-this worked for me: [docker-compose.txt](https://github.com/reportportal/reportportal/files/6821857/docker-compose.txt)

**Comment by nandyQA** [comment]
Any one know how to deal this issue with Linux machine?

**Comment by xiaochuansun** [comment]
I'm also facing the same issue, kindly let me know how to solve the same.
One of docker containers doesn't run, and I can't login reportportal

f3a161c3f476   reportportal/migrations:5.7.0                          "/entrypoint.sh up"      8 minutes ago   Exited (0) 31 seconds ago                                                         reportportal-db-scripts-1

![image](https://user-images.githubusercontent.com/37564800/172541001-611a0708-0264-4d92-b010-97ce0f9e1596.png)
