### ISSUE TITLE
Add attachments to test itself

### ISSUE THREAD

**Issue by lenosky** [reportportal/reportportal#812]
It is possible to attach files only to launch, not to the test itself, using api v1, and the v2 does simply nothing.
Is this intended or a bug?

**Comment by DzmitryHumianiuk** [comment]
for v5 use
https://github.com/reportportal/client-java/blob/9c32e5ccf3424a4aec15dda44ffa089f71e8d0aa/src/main/java/com/epam/reportportal/service/ReportPortal.java#L201

**Comment by evjlobanova** [comment]
@lenosky i close this issue, if it doesn`t help, please feel free to reopen issue
