### ISSUE TITLE
Cannot post issue due to 40302 error

### ISSUE THREAD

**Issue by MaksimPretkel** [reportportal/reportportal#813]
**Describe the bug**
Not able to post a bug from RP because of the following error message:
Error occurred: {"error_code":40302,"message":"Impossible interact with external system. [ErrorCollectionstatus=400, errors=customfield_10170=Could not find valid 'id' or 'value' in the Parent Option object., errorMessages=[]]"}

customfield_10170 - is the environment field in our jira, value of this value is available on project bug-tracking system config page and "post issue" pop-up

**Expected behavior**
Issue should be posted

**Screenshots**
If applicable

**Versions:**
 - Win10, Chrome (Latest)
 - Version of RP:
Current version: API Service: 4.3.7; Index Service: 4.2.0; Jira Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.7;

**Comment by evjlobanova** [comment]
@MaksimPretkel do you use Epam instanse?
Could yoou please send a screen with Jira config?

**Comment by MaksimPretkel** [comment]
Hi @evjlobanova I'm using client RP and Jira instances, I can share API, UI and Jira logs if you want,
but they are identical with the issue I'm getting on UI:
{"log":"com.epam.ta.reportportal.exception.ReportPortalException: Impossible interact with external system. [ErrorCollectionstatus=400, errors=customfield_10170=Could not find valid 'id' or 'value' in the Parent Option object., errorMessages=[]]\n","stream":"stdout","time":"2020-02-10T13:52:04.352488154Z"}

**Comment by MaksimPretkel** [comment]
Here is the similar issue: https://github.com/reportportal/reportportal/issues/536
"This was fixed as part of reportportal/service-jira@8840097 but now this fix is not present on 4.3.0 tag"

Do we need a patch for our version of RP?

**Comment by evjlobanova** [comment]
Which version of reportportal do you use?

**Comment by MaksimPretkel** [comment]
Versions:

Win10, Chrome (Latest)
Version of RP:
Current version: API Service: 4.3.7; Index Service: 4.2.0; Jira Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.7;

**Comment by evjlobanova** [comment]
@e-olga please check if it is know issue on version 4

@MaksimPretkel we do not support version 4, because it has been released the new version 5.
So please update your current version ti the latest one.

We are planning to update the epam instance in the next month.

**Comment by evjlobanova** [comment]
@VolhaKarenko do you have any updates regarding this issue?

**Comment by alena-babrova** [comment]
Hello @MaksimPretkel 
Have you managed to upgrade to the latest Report portal version?
Is the issue still relevant?

**Comment by alena-babrova** [comment]
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
