### ISSUE TITLE
Sender name at mail not updated - version 5

### ISSUE THREAD

**Issue by AssafMCET** [reportportal/reportportal#814]
Hey ,

When I got the mail of the running results the sender name is: prvs=301288280=root@bf4e30313fc3 although I changed and sender name in the Gui of report portal.

Can someone help me?

**Comment by evjlobanova** [comment]
@AssafMCET could you please specify an exact version of ReportPortal.
Could you please send a screen of your letter and your E-mail server config

**Comment by AssafMCET** [comment]
Current version:API Service: 5.0.0;Index Service: 5.0.5;Authorization Service: 5.0.0;Service UI: 5.0.0;
![image](https://user-images.githubusercontent.com/49675239/74741737-09a26180-5266-11ea-8793-fc9745c9c638.png)

![image](https://user-images.githubusercontent.com/49675239/74741837-35254c00-5266-11ea-869f-0d074d38a97b.png)

**Comment by AssafMCET** [comment]
Hey all,

Any answer?

Thanks,
Assaf.

**Comment by evjlobanova** [comment]
@svettsova Valya, could you please try to reproduce this issue?

**Comment by svettsova** [comment]
@evjlobanova I didn't receive sender name in version 5.1 with following configurations:
![2020-03-31_22h24_52](https://user-images.githubusercontent.com/50825875/78050707-7436d900-739e-11ea-8b33-02a0ce8dd42d.png)

![image](https://user-images.githubusercontent.com/50825875/78050765-8d3f8a00-739e-11ea-9735-4fe55372b6c5.png)

**Comment by evjlobanova** [comment]
@AssafMCET try to choose TLS

**Comment by evjlobanova** [comment]
If the issue still reproduce please reopen it again

**Comment by svettsova** [comment]
ticket is added to jira

**Comment by alena-babrova** [comment]
The issue is fixed in v. 5.8
