### ISSUE TITLE
HTML tags in log message

### ISSUE THREAD

**Issue by mnicula** [reportportal/reportportal#815]
I nice feature would be to support HTML tags in the log message.
 :)

**Comment by evjlobanova** [comment]
@mnicula do you want to have a the same feature as a possibility to switch on/off  markdown , but for HTML

![image](https://user-images.githubusercontent.com/30413511/74741647-41150c00-526e-11ea-9680-95e060aab802.png)


Also could you please provide you use case?
Why do you need HTML tags in logs?

**Comment by mnicula** [comment]
didn't knew about markdown. no need for HTML support then. Thanks
