### ISSUE TITLE
Demo report portal is not accessible via github account integration

### ISSUE THREAD

**Issue by podoliuk** [reportportal/reportportal#818]
Hi,
demo report portal is not accessible via github account integration - receiving 403

<img width="1426" alt="rp_error" src="https://user-images.githubusercontent.com/60887082/74222940-41396880-4cbe-11ea-81bf-f64f0d203408.png">

**Comment by evjlobanova** [comment]
Could you please check one more time, I have checked, and everything is good.
I close this issue, feel free to reopen it, in case it still reproduce

**Comment by pjn2work** [comment]
The same happens to me.
Already tried in 2 browsers (also incognito mode) and 2 different GitHub accounts and always get 403.
On GitHub it appears the authorization for ReportPortal

**Comment by evjlobanova** [comment]
I have checked it works for me.
Please provide steps for reproducing
