### ISSUE TITLE
[AGENTS] Support for Protractor+Jasmine tests ?

### ISSUE THREAD

**Issue by psprogis** [reportportal/reportportal#82]

**Comment by DzmitryHumianiuk** [comment]
@psprogis we have it for `"protractor": "^3.0.0"`. should be checked for stability
@avarabyeu could you please upload existing integration from internal gitLab?

**Comment by yana95** [comment]
done https://github.com/reportportal/agent-js-jasmine

**Comment by davoodharun** [comment]
I don't see this mentioned in the docs. is this officially supported?

**Comment by DzmitryHumianiuk** [comment]
@davoodharun 
we refactoring agents to meet changes of version 5 at the moment.
@KatsiarynaTatarynovich has Jasmine on the priority list,
so it should be updated soon
