### ISSUE TITLE
Getting an error when try to execute our script present at git repository through jenkins

### ISSUE THREAD

**Issue by dharma-keyutech** [reportportal/reportportal#820]
![image](https://user-images.githubusercontent.com/58975085/74347480-2870a600-4dd7-11ea-9f5e-0633150e6ebe.png)

**Comment by HardNorth** [comment]
Well, as I see it's yours test class. There is no any classes in RP called "Base.Basetest". So please do not spam our project with unrelated issues or I have to block you. Closing that out.
