### ISSUE TITLE
Not able to see data in widget shared by other project members when I have the role as member for that project.

### ISSUE THREAD

**Issue by VenkataSubbaiahM** [reportportal/reportportal#821]
When I have member as the role in one project and I'm not able to see any data in that widget. I have checked that dashboard and widget are shared by the user who created them.

**Comment by VenkataSubbaiahM** [comment]
![Screenshot 2020-02-14 at 5 40 13 PM](https://user-images.githubusercontent.com/51957560/74530919-49f59d00-4f51-11ea-8b7c-b926e326e8cd.png)
![Screenshot 2020-02-14 at 5 40 27 PM](https://user-images.githubusercontent.com/51957560/74530921-4c57f700-4f51-11ea-88dc-22f03866e046.png)

**Comment by evjlobanova** [comment]
Hello!
Could you please tell us which version of RP you use?
Could you please send a screenshot of widget wizard for this widget?

**Comment by evjlobanova** [comment]
Closed due to know response
