### ISSUE TITLE
Unable to Start API Service in Report Portal 5 [v5]

### ISSUE THREAD

**Issue by SrikanthSunder** [reportportal/reportportal#826]
**Describe the bug**
Unable to start the below Service API Service.
RP_AMQP_HOST=localhost RP_DB_HOST=localhost java $SERVICE_API_JAVA_OPTS -jar service-api.jar 2>&1 &

**To Reproduce**
Getting the Following Error message,
rg.postgresql.util.PSQLException: FATAL: password authentication failed for user "rpuser"

**Expected behavior**
API Service should be up & running

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Centos 7
 - Browser Not Applicable

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, s
![API Service Issue](https://user-images.githubusercontent.com/51087768/74741998-d8388e80-5283-11ea-93fb-7a3e990ca294.JPG)
afari]

**Additional context**

**Comment by khatray** [comment]
Whats the password of rpuser that you have created?if its different than default one then you need to provide the password here

**Comment by omkarnathsingh** [comment]
Any solution on this?

**Comment by HardNorth** [comment]
How do you actually run it? Docker-compose? Do you have SELinux installed on your machine? What happens if disable it?

**Comment by omkarnathsingh** [comment]
yes, using docker-compose. It was running fine some time back. Then we did configuration for elastic search and then restart. After that this issue started appearing.

**Comment by HardNorth** [comment]
@omkarnathsingh Is it possible that your RP looks on different DB? E.G. you installed another postgres locally?

**Comment by omkarnathsingh** [comment]
@HardNorth Thats not the case. Auth service is returning the token successfully. Only API is down

**Comment by HardNorth** [comment]
@omkarnathsingh OK, can you send me your docker-compose file?

**Comment by omkarnathsingh** [comment]
We removed all firewall rules, took db backup, shutdown container, restarted it, imported db. All working fine now.

**Comment by HardNorth** [comment]
A DB configuration issue not related to RP
