### ISSUE TITLE
Data migration

### ISSUE THREAD

**Issue by AlZero-t** [reportportal/reportportal#829]
Hello, I now need to migrate the running reportportal to the new server. I use docker save images and then copy the path file of volume in docker-compose. Yml to the new machine.

**Comment by AlZero-t** [comment]
I run docker-compose ,It shows that docker ps is running, but the 8080 I accessed on the local machine does not exist, I used netstat and did not have 8080, is it necessary to map out docker-p

**Comment by AlZero-t** [comment]
Could you please tell me where this log was recorded? Now I visit the address 404

**Comment by DzmitryHumianiuk** [comment]
@AlZero-t do you migrate from version 4 to version 5 (https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.5)?

or just move deployment from server A to server B?

**Comment by evjlobanova** [comment]
Closed due to no response.
Please reopen the issue, if it is still actual
