### ISSUE TITLE
[v5] Unable to login Report portal after restart the Docker/Windows machine [Error 502 Bad GateWay]

### ISSUE THREAD

**Issue by GopinathCTS** [reportportal/reportportal#831]
> **Unable to login Report portal after restart the Docker/Windows machine  [Error 502 Bad GateWay]**

**To Reproduce**
Step1 - Install all the Docker required stuffs using dockertoolsbox and  access RP with default login details
Step2 - Restart the Windows machine (Wireless Desktop)
Step3 - Start the Virtual Box
Step4- Login the Report-portal with default login details
Step5-  Observed "Successfully Logged-in" notification but no response 
Step6- Again Clicked Login button and Observed Sign-in Popup box and unable to proceed further

Note : Tried in Chrome (incognito mode) and IE browser.

**After First Login Click**
![RP_ISsue](https://user-images.githubusercontent.com/16055900/75119931-38d91a00-563c-11ea-9ec8-f7890a3f1b48.PNG)
**After Second Login Click**
![Chrome](https://user-images.githubusercontent.com/16055900/75119861-97ea5f00-563b-11ea-9957-1fd05e2deda4.PNG)

IE Browser 

![IE](https://user-images.githubusercontent.com/16055900/75119966-61f9aa80-563c-11ea-90af-c63f02cf8e5b.PNG)

**Comment by omkarnathsingh** [comment]
I am facing the same issue. Anyone can help on this?

**Comment by HardNorth** [comment]
So, you are not entering `docker-compose -p rp up -d --force-recreate`, you just restart your machine?

**Comment by chhatbarjignesh** [comment]
@GopinathCTS check `docker ps` one of your service is keep restarting and that one is probably service `reportportal/service-authorization` is keep on restarting and that might be because you haven't set permission correctly

**Comment by omkarnathsingh** [comment]
![image](https://user-images.githubusercontent.com/12734027/75158019-517c2980-573b-11ea-8a40-5b22d8d94a4b.png)

**Comment by omkarnathsingh** [comment]
I see all are up, I am missing anything?

**Comment by chhatbarjignesh** [comment]
did you give the correct permission to data/elasticsearch ?

**Comment by omkarnathsingh** [comment]
Yes, I followed the step from here

**Comment by omkarnathsingh** [comment]
We removed all firewall rules, took db backup, shutdown container, restarted it, imported db. All working fine now.

**Comment by kiryl-naurotski** [comment]
The issue is after the system reboot all containers start at the same time and not in the specified order.
See attached logs with errors
[reportportal_logs.txt](https://github.com/reportportal/reportportal/files/4256601/reportportal_logs.txt)

As a workaround, you need to add "restart: always" to the following services in the docker-compose file:
postgres
rabbitmq

I tried on my virtual machine and it works.

**Comment by omkarnathsingh** [comment]
http://<RP-URL>/api/v1/user

This request is not returning anything, but all services are up and running. What should I check?

**Comment by HardNorth** [comment]
@omkarnathsingh Please stick to the topic.

**Comment by AlehB** [comment]
Hello,

Restart policies were updated in the Docker Compose file
https://github.com/reportportal/reportportal/blob/master/docker-compose.yml

Best Regards,
Aleh

**Comment by vikasChobey** [comment]
I also face same issue in the past, Every time need to restart the container is only a solution as of now

**Comment by AlehB** [comment]
As I mentioned above, the policies were updated, no restart is needed anymore

**Comment by mnicula** [comment]
i'm facing the same issue, even with the updated Docker Compose file

**Comment by evjlobanova** [comment]
@AlehB What can be wrong?

**Comment by mnicula** [comment]
You can try to increse the alocated space for docker. This solved the problem in my case.

**Comment by gsumit1** [comment]
> restart

restart: always is not working when running from docker in windows 10

**Comment by wallacekabum** [comment]
> You can try to increse the alocated space for docker. This solved the problem in my case.
Thanks!!. this working for me, increse the alocated space in docker .

SO: Mac Os Monterrey 12.0.1

**Comment by pligor** [comment]
"You can try to increse the alocated space for docker. This solved the problem in my case."

How to do this ? Any link that explains this ?

**Comment by mnicula** [comment]
> "You can try to increse the alocated space for docker. This solved the problem in my case."
> 
> How to do this ? Any link that explains this ?

https://reportportal.io/docs/Deploy-with-Docker

_If you use Docker for Windows or MacOS, make sure there is at least 3gb dedicated for Docker_

**Comment by pligor** [comment]
Hi @mnicula many thanks for your answer but not sure how this link answers that. Perhaps you think that we can use docker desktop and set memory via Preferences via gui but unfortunately we are restricted to Ubuntu server and thus need to do everything via terminal.
So far searching online has revealed ways of how to set the memory for each docker container separately, but Reportportal deploys a large range of containers via docker compose.
So how to set the docker memory limit or the allocated space of docker via terminal ?

**Comment by mnicula** [comment]
@pligor sorry, can't help here

**Comment by alizaidi96** [comment]
I'm actually fed up with this now. At our organisation nurture.farm, we thought we will use Reportportal for our build reports but the issues are just endless. Setup was okay but never works on restart.
Have tried all the approaches mentioned. Maxed out memory requirements to 10GB+.
Nothing works. Please fix your product if you don't want business impacts!
