### ISSUE TITLE
How to remove Console Debug log from eclipse Console window 

### ISSUE THREAD

**Issue by GopinathCTS** [reportportal/reportportal#832]
Hi Team,

I could see more DEBUG Logs in my eclipse console window after implementing the log4j root level ="DEBUG", could you please help to disable this logs .

**Console Logs:**
![logs_1](https://user-images.githubusercontent.com/16055900/75184373-24a72280-56f9-11ea-8804-fe6828b7e432.PNG)

**Logs4j:**
![logs](https://user-images.githubusercontent.com/16055900/75184383-27a21300-56f9-11ea-9582-0685fb3e376c.PNG)

**Comment by HardNorth** [comment]
Please refer Log4j documentation and not treat us as your personal Stackoverflow or interactive encyclopedia.
