### ISSUE TITLE
[v5] unable to login although it is showing "Sign in successfully"

### ISSUE THREAD

**Issue by labidiadnene** [reportportal/reportportal#833]
Hi , i am trying to run RP locally , so i can add some features but i am unable to login although it is showing "Sign in successfully" but nothing happens ( no redirection , and when i open home page from link it redirects me to login page) , here what i did :
1-created magic-script.sh in empty folder in mac and run it in terminal with "sh magic-script.sh"
2-it downloaded the report portal services , created the images but service-authorization was showing an error during the build of docker image in the step "COPY --from=builder /usr/src/reportportal/build/libs/app.jar ./" of the dockerfile "Dockerfile-develop" because in couldn't find the app.jar so i went to the build.gradle of service authorization and changed in the bootJar "**System.getenv().containsKey("K8S") ? getArchiveFileName().set('app.jar') : archiveClassifier.set('exec')**" to "**getArchiveFileName().set('app.jar')**" to force create the app.jar
3- now all the RP are running fine , i run the service migration to initialize the database and went to http://localhost:8080/ui/#login (i changed the port in trafeik from 9080 to 8080) and logged in with superadmin/erebus
and it showed me "Sign in successfully" but nothings happens 
<img width="1440" alt="Screenshot at Feb 25 09-57-16" src="https://user-images.githubusercontent.com/60707715/75238181-dbbaa100-57c0-11ea-9106-4047e3bf6688.png">
<img width="671" alt="Screenshot at Feb 25 09-58-04" src="https://user-images.githubusercontent.com/60707715/75238197-dfe6be80-57c0-11ea-8351-c472a7d6229b.png">

4-i tested RP with the docker-compose that uses the images from the docker hub and everything worked fine , in that docker-compose.yml i changed the service-api image
from :
    **image: reportportal/service-api:5.0.0**
to :
    **build:
      context: ./service-api
      dockerfile: ./docker/Dockerfile-develop**

and it recreated the problem , i can't login anymore so i think the problem is from that service
can anyone please help me ?  and thank you a lot !

Logs : 
[reportportal_analyzer_1_log.txt](https://github.com/reportportal/reportportal/files/4249559/reportportal_analyzer_1_log.txt)
[reportportal_api_1_log.txt](https://github.com/reportportal/reportportal/files/4249560/reportportal_api_1_log.txt)
[reportportal_elasticsearch_1_log.txt](https://github.com/reportportal/reportportal/files/4249561/reportportal_elasticsearch_1_log.txt)
[reportportal_gateway_1_log.txt](https://github.com/reportportal/reportportal/files/4249562/reportportal_gateway_1_log.txt)
[reportportal_rabbitmq_1_log.txt](https://github.com/reportportal/reportportal/files/4249563/reportportal_rabbitmq_1_log.txt)
[reportportal_uat_1_log.txt](https://github.com/reportportal/reportportal/files/4249564/reportportal_uat_1_log.txt)
[reportportal_ui_1_log.txt](https://github.com/reportportal/reportportal/files/4249566/reportportal_ui_1_log.txt)

Docker-compose file generated by magic-script:
[docker-compose.yml.zip](https://github.com/reportportal/reportportal/files/4249597/docker-compose.yml.zip)

**Comment by Siddh010** [comment]
I am also getting same problem during login.
I also can see service-analyzer:5.0.0  is restating state even after following step mention in 
https://reportportal.io/docs/Deploy-with-Docker

![Screen Shot 2020-02-26 at 10 39 31 AM](https://user-images.githubusercontent.com/20200289/75314084-bbecb100-5884-11ea-9970-37b0aa3e16da.png)

**Comment by labidiadnene** [comment]
service-analyzer:5.0.0 also restart few times for me , if i remember because it needs postgres or service-api to be up and running , then when everything starts it starts and stay up so i think nothing is wrong with that , but there is the problem of signing in , still trying to understand why

**Comment by evjlobanova** [comment]
@AlehB Could you please check?

**Comment by AlehB** [comment]
Hi @labidiadnene,

It’s not quite clear to me what type of installation you are using.

a) Why do you need magic-script.sh?
b) If you want to run the latest ReportPortal with Docker, you can get Docker compose file from https://github.com/reportportal/reportportal/blob/master/docker-compose.yml
(Guide https://reportportal.io/docs/Deploy-with-Docker)
c) If you want to run the services with no docker (locally) there is shell installation is available - https://github.com/reportportal/shell-installation
Please take into account that it is limited version for CentOS/RHEL Linux distributions

Best Regards,
Aleh

**Comment by HardNorth** [comment]
Well, I believe I helped this person in a Slack in a private chat and fixed that 'magic-script.sh'. The case was in the necessity to build a personal version of RP for development and extension.

**Comment by labidiadnene** [comment]
Hi ! @HardNorth  thank you a lot ! yes as Vadzim said i needed to run reportproal in docker but throught the local projects files on my pc so that i can add features and then i can build it and run it locally in docker and Vadzim helped me to overcome this problem after fixing the docker-compose file like this 
[docker-compose.yml.zip](https://github.com/reportportal/reportportal/files/4286740/docker-compose.yml.zip)
, thank you everyone !

**Comment by srinivas2501** [comment]
Hi, I am also facing the same issue, unable to login to reportportal although it is showing "Sign in successfully" . Could you help me on this?, thanks and much appreciated.
let me know if you need any further information
<img width="1427" alt="Screenshot 2021-12-09 at 11 41 40 AM" src="https://user-images.githubusercontent.com/16115589/145330590-12303080-1d06-4a3a-90ba-eaff5e3ec5d5.png">
.

**Comment by Kamala-Priyanka** [comment]
How is this gets fixed
