### ISSUE TITLE
[Widget] Grid of Launch result/status groups by attribute

### ISSUE THREAD

**Issue by LupusUmbrae** [reportportal/reportportal#837]
**Describe the solution you'd like**

For a single release we have a collection of different launches we run, we'd like to be able to show the final status of each launch in a grid, grouped by the version. Something like:

Attribute Key | Launch name 1 | Launch name 2 | Launch name n
------------------|----------------------|----------------------|----------------------
value | passed | passed | failed
value | passed | passed | passed

I cannot see an existing widget that would let me do this

**Is your feature request related to a problem? Please describe.**

**Comment by evjlobanova** [comment]
@LupusUmbrae for we can propose you a implemented solution described in the ticket #839  

The feature that you have described is a very simiar to the widget from ticket #269.

I close a ticket as a duplicate, I you are disagree please feel free to reopen this issue.
