### ISSUE TITLE
Charts basing on attribute value

### ISSUE THREAD

**Issue by filipcynarski** [reportportal/reportportal#839]
**Describe the solution you'd like**
I'd like to have possibility to generate charts from attribute value.

For example I'm storing attributes for performance tests and I'd be glad If I can visualize the trend of such attribute.

**Is your feature request related to a problem? Please describe.**
As above

**Comment by evjlobanova** [comment]
We have two widgets which based on attributes:

Cumulative trend chart:

![image](https://user-images.githubusercontent.com/30413511/75771101-50aa4f80-5d5a-11ea-9920-677a61bd42a3.png)
For this widget you can choose `attribute key` of needed attribute, and then you can see group statistics for 15 groups which based on `attribute value`

![image](https://user-images.githubusercontent.com/30413511/75771562-46d51c00-5d5b-11ea-88f8-0ca79508f728.png)

**Comment by evjlobanova** [comment]
Component heakth check widget

![image](https://user-images.githubusercontent.com/30413511/75771614-5fddcd00-5d5b-11ea-84f8-15b3bd00844f.png)

![image](https://user-images.githubusercontent.com/30413511/75771759-ab907680-5d5b-11ea-8510-e343ae98291d.png)

![image](https://user-images.githubusercontent.com/30413511/75771855-d67aca80-5d5b-11ea-990c-8b4384eb2138.png)

**Comment by evjlobanova** [comment]
Please give us a feedback, can you use this widgets?
Does they help you?
If not, please let us know how this widgets can be improved

**Comment by filipcynarski** [comment]
Hello @evjlobanova 

Thank you for response, it looks promising so I've tried to configure it. For each launch I'm string performance tests statistics and adding some additional data in tags:

req_count:30
req_percentile:833
req_max_time:10.714
req_long_count:25

And I wanted to draw each one as a trend (so aggregate each metric and draw)

Right now for both types of widgets it is not working so looks like it expects some enum not numbers as a value of tag. Am I correct?

Would you consider to extend any widget by such functionality in nearest feature?

Thank you

**Comment by DzmitryHumianiuk** [comment]
@filipcynarski RP of version v4 and v5 was never expected to be used with performance tests results.
we keep it in mind for v6.
but there is nothing in v5 that can resolve your query.

**Comment by DzmitryHumianiuk** [comment]
Closing issue.

RP won't build charts based on attributes values.
But we will address performance results with a separate view.

**Comment by filipcynarski** [comment]
That's a pity ;( Thank you for information, can you provide any time frames or road map when you expect the v6 available?

**Comment by DzmitryHumianiuk** [comment]
@filipcynarski end of 2020

**Comment by jcarenas** [comment]
Hi guys! I'm facing an issue when I try to add a tag from gradle execcution to the reportPortal. My command line is: gradle clean test -Drp.tags=country:Sweden; I expect to have an attribute called country with a value Sweden, in my launch, but instead of that I have found an attribute with an empty key and as value "country:Sweden". This occurs in widget Component Health Check.
Please, can you help me with this issue? Many thanks in advance

**Comment by DzmitryHumianiuk** [comment]
@jcarenas open new issues for questions, rather than commenting closed.

Tags are tags. Attributes are attributes.
send it as:
```rp.attributes = country:Sweden;```

**Comment by sspieker-cc** [comment]
How can we differentiate tags from attributes using the API?  The UpdateLaunchRQ object does not allow for setting tags separate from the attributes.  So far, we have been setting attributes without keys and that seems to work as tags.  Is there a different method that should be used to update the tags separately from the attributes of a launch?

**Comment by evjlobanova** [comment]
@sspieker-cc We replaced tags with attributes in version 5.0
Because now we can create widgets which helps us to group item around the attribute key.

So no tags in version 5.0
But you can use your approach
