### ISSUE TITLE
Integration of Report Portal with UFT

### ISSUE THREAD

**Issue by satishultimate** [reportportal/reportportal#841]
I am looking out for a solution on how to integrate UFT with ReportPortal. I am ware that there is an REST API option to leverage, but I am not sure on how to get started. 
  My requirement is to pass over the test report generated by UFT with screenshots to report portal as it is being done by many agents currently available for ReportPortal. I am looking out on how to tag the UFT report to ReportPortal API to start off with.  Please bear with me, as I am completely new to the functionality of ReportPortal

**Comment by DzmitryHumianiuk** [comment]
@satishultimate 
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md

**Comment by DzmitryHumianiuk** [comment]
@satishultimate also if your company is willing to go with payed support, our team can investigate possibility of implementation of it for you.
let us know at 
![image](https://user-images.githubusercontent.com/11332788/76873136-6fdace00-687e-11ea-9bd5-2b69d62191d5.png)

**Comment by satishultimate** [comment]
> 
> 
> @satishultimate
> https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md

Thank you very much DzmitryHumianiuk. Actually, I have started working over the ReportPortal UFT Implementation. If I am stuck anywhere, I would let know the forums know over the progress/hiccups, i have faced yet.

**Comment by DzmitryHumianiuk** [comment]
@satishultimate Don't hesitate to contribute back :)
