### ISSUE TITLE
How to setup ReportPortal with AWS

### ISSUE THREAD

**Issue by Bharadwaj-vana** [reportportal/reportportal#844]
Hi Team,

I am trying to use ReportPortal in my project where I am using TestNG reports and using Jenkins to execute & display reports with status. Can you please help me how to start & where I need to do config changes within my framework to use ReportPortal. 

Thanks 
Bharat

**Comment by HardNorth** [comment]
Please read our documentation here: https://reportportal.io/docs/Test-Framework-Integration
