### ISSUE TITLE
[v5] Jira integration is not installed

### ISSUE THREAD

**Issue by b1zzu** [reportportal/reportportal#846]
**Describe the bug**

Hi, Following the [Jira integration](https://reportportal.io/docs/Jira-Integration) documentation, it seems that the Jira plugins should be already installed on ReportPortal but it's not for me. I have installed ReportPortal on Kubernetes following the Kubernetes tutorial but Jira is not mentioned anywhere https://github.com/reportportal/kubernetes/tree/master/reportportal/v5

**To Reproduce**

Install ReportPortall on Kubernetes following this guide: https://github.com/reportportal/kubernetes/tree/master/reportportal/v5

**Expected behavior**

To have the Jira integration installed by default

**Screenshots**

![image](https://user-images.githubusercontent.com/7964685/75876030-341f1d80-5e15-11ea-9588-f1fea600557d.png)

**Comment by evjlobanova** [comment]
Please follow the steps which are described here https://reportportal.io/docs/Plugins%3Eupload-plugin

Jira is a plugin, so firstly you need to upload plugin and then configure the integration.
If you still have a question or problems please reopen the issue
