### ISSUE TITLE
Please help , having issues uploading Log with screenshot using Unirest for Java

### ISSUE THREAD

**Issue by YarKr** [reportportal/reportportal#847]
HttpResponse<String> response = Unirest.post("******")
  .header("Authorization", "Bearer *******")
  .field("json_request_part", new File("test.json"))
  .field("file", new File("screenshot16249438513890412689.png"))
  .asString();

**Comment by DzmitryHumianiuk** [comment]
@YarKr 
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#batch-save-logs

**Comment by evjlobanova** [comment]
@YarKr I close this issue, but if you still have problems, please feel free to reopen
