### ISSUE TITLE
[v5] OutOfMemoryError exception crashes API service without automatic restart.

### ISSUE THREAD

**Issue by blue995** [reportportal/reportportal#850]
**Describe the bug**
If an OutOfMemoryError exception (GC overhead Limit exceeded) is thrown in the API service, the API service does not recover or restart on it's own (docker-compose `restart:always` does not work). When you try to login, the UI is stuck in the loading screen.

**To Reproduce**
Execute the export as PDF/XLS/HTML feature on a launch with a high amount of test cases (e.g. 100k).

**Expected behavior**
If this exception occurs, the API service should be able to recover on it's own. (e.g. handle the exception correctly or crash completely so that docker can restart the container)

**Application Server:**
 - OS: Ubuntu 18.04.3
 - CPU: 16 Cores, 2.6 GHz
 - RAM: 32 GB
 - Java Option: -Xmx2g

**Database Server:**
 - OS: Cent OS 7
 - CPU: 8 Cores, 2.6 GHz
 - RAM: 32 GB

**Comment by blue995** [comment]
**Additional Context**

The exported result includes the item description in the "Name" column. (see screenshot below)
![image](https://user-images.githubusercontent.com/36842443/76096594-a3883f00-5fc6-11ea-9cee-bedb20581c21.png)

The item descriptions of **our** suites and steps are bigger compared to the image above. They can cover 50 to 80% of the whole name column per page.

**Example**: If I export a launch with ~11.000 test cases as PDF, the resulting PDF has ~10.000 pages, because the export feature includes the whole item descriptions.

**Comment by DzmitryHumianiuk** [comment]
We will consider re-working of export mechanism.

**Comment by irynakozak2** [comment]
hello, @blue995, could you please check that issue on the latest RP version(5.3)? As for now, we've improved the export feature performance for PDF and HTML. For Xls export performance I've raised a ticket to our backlog.
Also, I suggest you increasing the -Xmx option to the best performance on your specs of the application server.

**Comment by blue995** [comment]
Hi @irynakozak2, I will check on this feature as soon as I update our instance to V5.3. We have customized instances of the API and UI service, so I can't update by changing the version number :)

**Comment by irynakozak2** [comment]
@blue995 thanks a lot! please keep us updated

**Comment by blue995** [comment]
@irynakozak2 I've built the API service from scratch (without downloading any binaries from reportportal bintray) with the "Dockerfile-develop" Dockerfile by executing the following command:
`docker build -f docker/Dockerfile-develop --tag "my-api-service:latest" .` (=> Is this the correct way to build the docker image from scratch?)

I guess some dependencies are missing in the Dockerfile-develop file. I'm not able to test the new export feature, because of a few font and "no class def found" problems (see the following example).

### Example: I try to execute "Export as PDF" 3 times

If I try to execute the "Export as PDF" feature on a generated demo launch **for the first time**, I get an exception about
`java.lang.UnsatisfiedLinkError: /usr/local/openjdk-11/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory`
(more details see [export_as_pdf_1st_call.log](https://github.com/reportportal/reportportal/files/5059684/export_as_pdf_1st_call.log))

When I execute the feature **a second time**, I get exceptions like `InvalidFontException` (fonts/noto-sans/NotoSans-Regular.ttf) and `NoClassDefFoundError` (sun.awt.X11FontManager) 
(more details see [export_as_pdf_2nd_call.log](https://github.com/reportportal/reportportal/files/5059700/export_as_pdf_2nd_call.log))

When I execute the feature **a third time**, I also get an `NoClassDefFoundError`, but this time with a different class (net.sf.jasperreports.engine.util.JRStyledTextParser).
(mor details see [export_as_pdf_3rd_call.log](https://github.com/reportportal/reportportal/files/5059703/export_as_pdf_3rd_call.log))

**Comment by blue995** [comment]
The export feature works with the official docker image, but I'm using a manually built one.
