### ISSUE TITLE
Select specific launches for Auto-Analysis feature

### ISSUE THREAD

**Issue by blue995** [reportportal/reportportal#852]
**Describe the solution you'd like**
I'd like a to declare launches (e.g. By Name or Attribute) that should be considered for an automatic analysis as soon as the launch finishes.

**Is your feature request related to a problem? Please describe.**
Currently you can enable or disable the feature for all launches. A software project with multiple development teams, where each development team monitors their own launches and maybe launches from dependend teams, it's not possible to check if all automatic investigations are correct.

**Comment by evjlobanova** [comment]
@blue995 Actually we do not plan to add this feature. But we will think about it.
For now we can propose you two workarounds:
- you can devide your project on two projects, so different teams will be able to post launches to different projects

- you can launch AA manually for needed launches
![image](https://user-images.githubusercontent.com/30413511/76315264-6505c380-62e9-11ea-8a69-35623564b5e6.png)

**Comment by blue995** [comment]
Thank you @evjlobanova for considering my feature request.

We're currently doing the second workaround because we want a single elasticsearch index instead of two separated ones.

**Comment by arunkumar-muthusamy** [comment]
Just in case if an automated workaround is needed, We can make an API call `/v1/{projectName}/launch/analyze` after test test execution, in the pipeline.

**Comment by blue995** [comment]
@arunkumar-muthusamy This is actually a great idea, thank you

**Comment by evjlobanova** [comment]
@blue995 Can I close this issue?
