### ISSUE TITLE
Reset password email not received

### ISSUE THREAD

**Issue by mnicula** [reportportal/reportportal#854]
I tried to reset the password for two users, but no email received :(

**Comment by DzmitryHumianiuk** [comment]
@mnicula any other details?
RP version?
did it work previously?

**Comment by mnicula** [comment]
V5
Can't tell, didn't use it before

**Comment by mnicula** [comment]
until you're looking into the problem, could you please provide the hashed password for the superadmin user, I will update the password in db :)

**Comment by evjlobanova** [comment]
@mnicula Do you have configured E-mail server integration?
Could you please send us a screenshot?
Could you please describe your steps, to reproduce the bug?

**Comment by DzmitryHumianiuk** [comment]
@mnicula please give a bit more context.

exact version of RP API.
How was email configured?
do you receive any other type of emails from this instance?

**Comment by mnicula** [comment]
hi @DzmitryHumianiuk , @evjlobanova, sorry for the late response.
I changed the password and email for superadmin user and then forgot it after some time. So I tried to recover it with the email set previously, but no email received. Do I need to have the email integration configured I order to receive the email? (that kinda makes sense)

**Comment by DzmitryHumianiuk** [comment]
@mnicula yes you are.

**Comment by evjlobanova** [comment]
@mnicula Have you resolved the issue?

**Comment by mnicula** [comment]
@evjlobanova yes, thanks
