### ISSUE TITLE
[v5] Can't Login with Github Authorization

### ISSUE THREAD

**Issue by jonacarvalheiro** [reportportal/reportportal#856]
**Description**
Trying to login with Github, but appears an error on the UI
![image](https://user-images.githubusercontent.com/11489396/76641495-a1375f00-6549-11ea-8717-798fb9881cb4.png)

Configurations: 
Followed the ones in here:
https://github.com/reportportal/reportportal/wiki/How-to-configure-login-via-GitHub

![image](https://user-images.githubusercontent.com/11489396/76641754-ff644200-6549-11ea-885f-3157dd39f448.png)

Response Headers:

Bearer realm="oauth2-resource", error="unauthorized", error_description="Full authentication is required to access this resource"

Could you help me with this?

**Comment by DzmitryHumianiuk** [comment]
@jonacarvalheiro do you use GitHub Enterprise or free version?

**Comment by jonathancarvalheiro** [comment]
@DzmitryHumianiuk I'm using the cloud version.

**Comment by evjlobanova** [comment]
@jonacarvalheiro Could you please send logs, screenshots of configuration in RP or some details so that we can be able to debug the problem?
