### ISSUE TITLE
Total Failed count is not matched with Test cases after Merging the multiple Launches [ deep merge] 

### ISSUE THREAD

**Issue by GopinathCTS** [reportportal/reportportal#857]
Steps to reproduce
1. Merged Multiple launches into one Launche [ deep merge]
2. Selected checkbox in all field while merging [Extend child suites description with original launch name]
3. Deleted all the Failed Cases [ except product Bug]
4.But the Failed Total is not matched with actual test cases [ When we click the failed count from launch]
![laucn_Step1](https://user-images.githubusercontent.com/16055900/76723192-adffb280-6703-11ea-8b38-12ed421e46ba.PNG)
![laucn_Step2](https://user-images.githubusercontent.com/16055900/76723193-ae984900-6703-11ea-89da-5a0c73097ae3.PNG)
![laucn_Step3](https://user-images.githubusercontent.com/16055900/76723194-ae984900-6703-11ea-818c-843d75136d24.PNG)

**Comment by evjlobanova** [comment]
@GopinathCTS Whicj version of reportportal do you use?

**Comment by GopinathCTS** [comment]
@evjlobanova  I'm using Report portal Version 5

**Comment by evjlobanova** [comment]
@GopinathCTS How much launhce have you merged?

And one more question could you please tell me your use case? Why do you merge launhces?
Maybe we can help you to find workaround?

**Comment by GopinathCTS** [comment]
In total we had [128] launch 
Since we have data issue in our automation suite , we planned to execute the case one by one sequentially and some multiple cases [ max of 10 cases together]. Post execution, we decided to delete the invalid failure cases and merged pass and valid failure cases into one Launch.

**Comment by evjlobanova** [comment]
@GopinathCTS the feature is working incorrectly because of a lot of launches. 
We can advise you to use rerun functionality (https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/rerun.md) or https://github.com/reportportal/client-java/wiki/How-to-aggregate-Multi-thread-process-execution-in-one-launch

@irynakozak2 Ira, could you please tell me, if this performance issue for deep merge we have discussed?

**Comment by irynakozak2** [comment]
@evjlobanova I think, this is no performance issue with Deep Merge actually. May be this is incorrect display or recount of statistics.
@GopinathCTS could you please tell, Deep Merge operation itself had been completed successfully?

**Comment by evjlobanova** [comment]
Added a ticket to the Jira for investigations

**Comment by Yumfriez** [comment]
Fixed in https://github.com/reportportal/migrations/pull/161
