### ISSUE TITLE
Report Portal unable to uplaod jira plugin 

### ISSUE THREAD

**Issue by RG108** [reportportal/reportportal#859]
I migrated to report portal 5.0 and saw Jira as a service not found in UI so I tried using download it from site https://bintray.com/beta/#/epam/reportportal/plugin-bts-jira/5.0.1?tab=files and tired uploading it on report portal UI but getting error unable to upload plugin Jira to the data store.

![Screen Shot 2020-03-18 at 9 04 13 PM](https://user-images.githubusercontent.com/39192799/76977966-15b03a80-695c-11ea-93d8-96c2901bb004.png)

**Versions:**
 - MAC OS, Browser-Chrome
Can someone please suggest the solution.

**Comment by evjlobanova** [comment]
@RG108 which file do you use?
![image](https://user-images.githubusercontent.com/30413511/78051309-2910cc00-7386-11ea-9c94-77bcda6aaf6a.png)

**Comment by RG108** [comment]
@evjlobanova I believe the first one which has 12.3 MB space.

**Comment by evjlobanova** [comment]
Do you use the latest version of rp?

**Comment by RG108** [comment]
yep latest one 5.0.0 I believe. @evjlobanova

**Comment by evjlobanova** [comment]
@RG108 I am using versions 
![image](https://user-images.githubusercontent.com/30413511/78103821-82b0df00-73f6-11ea-8b2d-72675b477685.png)
and the mentioned plugin file. Everything is working.

Could you please double-check?
If it is still reproduced, please describe all preconditions, steps, and logs.

**Comment by RG108** [comment]
Sure. I will revert back here in some time.
Thanks, @evjlobanova for following up.

**Comment by evjlobanova** [comment]
I close this issue as non-reproducible.
But feel free to reopen it, if you still have a problem with a plugin.

**Comment by sasikala-codoid** [comment]
I am facing the below issue when I try to upload jira plugin,

![issue-rp](https://user-images.githubusercontent.com/15124663/80127928-a2c95d80-85b2-11ea-82d7-4de15f39a9aa.png)

I am using report portal build 5.0 and tried uploading jira 5.0

**Comment by evjlobanova** [comment]
Try to upload the latest version of plugin

**Comment by sasikala-codoid** [comment]
I have tried with the latest version also. It is not working

**Comment by RG108** [comment]
@evjlobanova 

Please open this case as it is reproducible in Report portal version 5.0. 
I am uploading jar file from link below:
https://bintray.com/beta/#/epam/reportportal/plugin-bts-jira/5.0.0?tab=files
Can you suggest the resolution of error message as shown in screenshot plz .
![Screenshot 2020-12-14 at 4 00 19 PM](https://user-images.githubusercontent.com/39192799/102071035-f16b8680-3e25-11eb-8ef0-486974e9b169.png)
![Screenshot 2020-12-14 at 4 00 39 PM](https://user-images.githubusercontent.com/39192799/102071045-f4ff0d80-3e25-11eb-8930-cad7e672970c.png)

**Comment by amnonmaimon** [comment]
Failed to introspect Class [com.epam.reportportal.extension.bugtracking.jira.JiraStrategy] from ClassLoader [org.pf4j.PluginClass.... 
This is the error I'm getting while the class is there.
Probably some collision with an older one loaded?

**Comment by amnonmaimon** [comment]
<img width="706" alt="Screen Shot 2022-06-27 at 19 56 58" src="https://user-images.githubusercontent.com/33728669/175995408-f3cb854a-c3db-43c6-8cfb-a57f3c02ace3.png">

**Comment by saiaprameya** [comment]
I am facing the same issue:

Failed to introspect Class [com.epam.reportportal.extension.bugtracking.jira.JiraStrategy] from ClassLoader

UI - 5.3.5

**Comment by amnonmaimon** [comment]
I've got recover from this issue by searching class after class on the missing binaries and add the same Jira plugin version that is suitable with my current ReportPortal Version.
But unfortunately I understand that the containerized deployment of report portal cannot connect to the Jira SSO, only the regular/trivial installation can.
