### ISSUE TITLE
Will RP 3.0 answer following questions?

### ISSUE THREAD

**Issue by JustasM11** [reportportal/reportportal#86]
Some words about my project. I have total ~800 unique automated TCs that are executed on daily basis in 3 pipelines, each pipeline executes all TCs but on different environments:
* CentOS6 pipeline, ~700 regression TCs executed nighly, 7 jobs (each job produces separate RP launch)
* CentOS7 pipeline, ~700 regression TCs executed nighly, 7 jobs
* HW pipeline, 700 regression + 100 long-running and performance TCs executed on weekly basis (3-4 jobs per night), 16 jobs total

Current RP version cannot answer following questions. Will RP 3.0 be able to do this?
* What is the total number of test cases?
* What are the latest results for all test cases ("snapshot" of current project health)?
* How many TCs were not executed within last X period (1 day, 30 days) - do I have stale tests? Some kind of histogram here with TCs in each column.
* Which TCs have last result as "To-investigate" and "Fail"?
* How can I mark particular TC with known DE/BUG so all following failed results are set as Known Issue?
* What are the trends for total number of TCs, failed TCs, triaged TCs, etc. with custom time window (day, week, month, half-a-year, year, 10 years)?

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 
could you please contact me via messages in Facebook https://www.facebook.com/ReportPortal.io 

>What is the total number of test cases?
Do you mean unique test cases? no matter how many launches have been executed?
Basically answer is `NO`.
ReportPortal do not track unique ID of test cases. That could be possible, if we will add TestManagement support.
in this case, we can find, how many unique test cases you have.

workaround for now: have a separate launch, where you sure, you have all unique test cases.

>What are the latest results for all test cases ("snapshot" of current project health)?
this can be done by using the tags.
put the `latest` tag, or `build#zzz`. and create filter for it. and then dashboard

>How many TCs were not executed within last X period (1 day, 30 days) - do I have stale tests? Some kind of histogram here with TCs in each column.
considering to implement such a view. not available for now.
you are welcome with idea scatches or similar functionality screenshots.

>Which TCs have last result as "To-investigate" and "Fail"?
in one click, via `To-investigate` and `Fail` columns

>How can I mark particular TC with known DE/BUG so all following failed results are set as Known Issue?
change defect type and link in to existing issue in bug tracking system.
if it will be the equal fail next time - ReportPortal will find it with auto-analysis and copy defect and related bugs.

>What are the trends for total number of TCs, failed TCs, triaged TCs, etc. with custom time window (day, week, month, half-a-year, year, 10 years)?
use filters for it. select time range.

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 with 3.3.0 version, RP supports uniqueID for test cases.
can be populated via code.
It can be populated from the code, or will be generated for every single test case, based on project, launch, suites name, test case name and params.

>What are the latest results for all test cases ("snapshot" of current project health)?
this will be covered with `Product status widget`
widget will represent summary status for only latest launch of particular jobs.

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova 
please add it as feature request for sub-launch widgets:
* How many TCs were not executed within last X period (1 day, 30 days) - do I have stale tests? Some kind of histogram here with TCs in each column.

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 did you find answers?

**Comment by JustasM11** [comment]
@DzmitryHumianiuk We bumped into the same bug as reported in #134 so we were not able to use RP for quite a long time and abandoned it. I see that uniqueID were implemented. Have you guys implemented view mentioned in #53 and #25 I mean History view with all TC ? If yes, I think we can make another try to use RP )

**Comment by DzmitryHumianiuk** [comment]
@JustasM11 #53/#25 in our roadmap already
https://github.com/reportportal/reportportal/wiki/Roadmap-4.0
