### ISSUE TITLE
Need to Capture Log's

### ISSUE THREAD

**Issue by Bharadwaj-vana** [reportportal/reportportal#861]
HI Team,

I am trying to integrate Report Portal into my TestNG framework, where we have test classes and once execution is done, I am trying to validate network log's of transaction across web and do certain validations where I have logic in PageBase or testbase classes and when I added LOGGER logic into those classes I am unable to see those log's in report protal. 

Can anyone help me to understand is there any way to capture log's from testBase & PageBase classes with in framework and display logs from those classes in report portal dashboard. 

Thanks In Advance.

Thanks 
Bharadwaj

**Comment by ramkumar-yoganathan** [comment]
This should help you.  https://github.com/reportportal/example-java-TestNG

**Comment by Bharadwaj-vana** [comment]
@ramkumar-yoganathan  Thanks for the help this worked.

I have one more question: I am generating HTML reports based on my execution and saving them in AWS, is it possible can I give that HTML as input to the report portal ??

**Comment by evjlobanova** [comment]
HTML question is a duplicate.
https://github.com/reportportal/reportportal/issues/868

Closing because the original question has been resolved.
