### ISSUE TITLE
Overall stats don't appear after launch completes

### ISSUE THREAD

**Issue by LittleColin** [reportportal/reportportal#863]
I assume this is something I'm doing wrong but no summary stats (total, passed, failed etc.) are appearing for my launch. This was a simple test run with two tests and if I drill into the launch I see they've both passed.
![2020-03-19_09-54-54](https://user-images.githubusercontent.com/1062116/77060880-336bb700-69d1-11ea-90af-cda24364011f.jpg)

I'm using codeceptjs-rphelper and v5 of reportportal. This appears to indicate the launch finished:
```
Success finish item 3iu1b1ybk7yka3f9
Finish launch 3iu1b1ybk7yka3e4
Success finish launch 3iu1b1ybk7yka3e4
```

**Comment by evjlobanova** [comment]
@LittleColin have you resolved this issue?

**Comment by LittleColin** [comment]
Yes thank you - the suggestion to downgrade to https://www.npmjs.com/package/codeceptjs-rphelper/v/1.1.12 and use hasStats: false worked.

I'm still not clear on why we can't use the latest plugin given I'm using the latest v5 report portal but it works so thank you for your support.

**Comment by iamtech123** [comment]
I am facing same error while using Robot Framework integration with Report Portal5

Issue occurs when Test teardown or Suite Teardown is used. Test are updated when Test teardown is removed.

**Comment by iamtech123** [comment]
Since this is closed i have created a new bug here: https://github.com/reportportal/reportportal/issues/908
