### ISSUE TITLE
[v5] JVM options don't change  with JAVA_OPTS env var for API and Authorization services

### ISSUE THREAD

**Issue by ivan-sukhomlyn** [reportportal/reportportal#864]
### **Describe the bug**

Java Virtual Machine parameters **can not be changed** for Service-API and Service-Authorization as they are hardcoded in the release Dockerfile for each service.
For example, Service-API - https://github.com/reportportal/service-api/blob/5e38ac4e81f0be7d352165e8728e4bafeca3f00d/docker/Dockerfile-release#L9

Each Java process starts with already pre-defined `JAVA_OPTS` and can not be configured during Kubernetes pod startup as described in the API service Helm template by the link - https://github.com/reportportal/kubernetes/blob/eccd692a744b5a1102c241f64c64623a4e6f8746/reportportal/v5/templates/api-deployment.yaml#L34

### **To Reproduce**

1. Deploy API-service within Kubernetes cluster with updated **JAVA_OPTS** environment variable
2. Login into container's shell
3. Compare `JAVA_OPTS` env var and actual Java process for the service

```
/ # env | grep JAVA
JAVA_ALPINE_VERSION=8.212.04-r0
JAVA_VERSION=8u212
JAVA_OPTS=-Xms1g -Xmx2g -Djava.security.egd=file:/dev/./urandom -XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=90.0
JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre

/ # ps aux
PID   USER     TIME  COMMAND
    1 root      1:18 java -Xmx1g -Djava.security.egd=file:/dev/./urandom -jar service-api-5.0.0-exec.jar
   77 root      0:00 sh
  105 root      0:00 ps aux

/ # cat start.sh 
#!/bin/sh 
exec java -Xmx1g -Djava.security.egd=file:/dev/./urandom -jar service-api-5.0.0-exec.jar
/ # exit
```

### **Expected behavior**
JVM parameters can be changed with `JAVA_OPTS` environment variable during a Java process starting of API and Authorization services

### **Additional context**
Service API version - 5.0.0
Service Authorization version - 5.0.0

**Comment by evjlobanova** [comment]
@ivan-sukhomlyn this issue can be closed as soon as a pr to kuber repository will be merged, am I right?

**Comment by ivan-sukhomlyn** [comment]
@evjlobanova Yes, you are right.
I see that PR is already approved but not merged yet

**Comment by evjlobanova** [comment]
Thank you, @HardNorth
