### ISSUE TITLE
Attachment with json-file - doesn't shows content

### ISSUE THREAD

**Issue by almayce** [reportportal/reportportal#866]
Hello!
When I attach a json-file to my report:

```
curl --location --request POST 'http://localhost:8080/api/v1/SUPERADMIN_PERSONAL/log' \
--header 'Content-Type: multipart/form-data' \
--header 'Authorization: Bearer 59d0f0d0-e59d-4c99-974b-8ffe42ca53cd' \
--form 'json_request_part=@/home/almayce/IdeaProjects/testing/leadium/leadium-core/temp.json;type=application/json' \
--form 'file=@/home/almayce/IdeaProjects/testing/bae/bpm-automation-testing/source/apps/fundstransfer/resources/fundstransfer/dev/mobile/clone.json'
```

json_request_part:
```
[{
   	"itemUuid": "17f3dbc4-1a5e-4905-9de4-b08594031db1",
	"launchUuid": "17f3dbc4-1a5e-4905-9de4-b08594031db1",
	"time": "1584630047051",
	"message": "some message",
	"level": 5000,
	"file": {
  		"name": "clone.json"
	}
}]
```

file:
```
{
  "Id": 584041,
  "Remarks": "ssss",
  "Amount": 50.00,
  "Currency": "usd"
}
```

The json is attached, but there is no preview of its content.
![Screenshot from 2020-03-23 18-01-09](https://user-images.githubusercontent.com/18463941/77336524-4e6f5b80-6d30-11ea-8179-ab9f75874ec7.png)

And after click - redirects to this page:
![Screenshot from 2020-03-23 18-02-17](https://user-images.githubusercontent.com/18463941/77336632-79f24600-6d30-11ea-9d38-653763bbaebb.png)

Attachment with png works correctly, but with json - doesn't shows content.
Whats wrong? How I can see content of the attachment?

**Comment by evjlobanova** [comment]
@DiscoElevator @ElenaRomanchuk do you have an idea why it can happen?

**Comment by evjlobanova** [comment]
@svettsova Could you please check if this issue reproduce?

**Comment by svettsova** [comment]
@evjlobanova I've retested this issue in 5.0 version and it is not reproducible for me
![2020-04-01_11h20_15](https://user-images.githubusercontent.com/50825875/78102003-fd83f500-740a-11ea-82a0-af97a8613118.png)
@almayce Could you check this issue again?

**Comment by almayce** [comment]
![demo](https://user-images.githubusercontent.com/18463941/78120884-5192d780-7413-11ea-90cc-4d836c46cf34.gif)

**Comment by evjlobanova** [comment]
@almayce which agent (name/version) do you use?

**Comment by almayce** [comment]
@evjlobanova I don't use agent, just sending curl requests to api.

**Comment by svettsova** [comment]
@almayce could you specify version of RP, browser and OS?

**Comment by almayce** [comment]
RP - [5.0.0](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml)
Browser - Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)
OS - Ubuntu 18.04.2 LTS (64-bit)

**Comment by evjlobanova** [comment]
@almayce do you still have this issue on ver 5.1?

**Comment by almayce** [comment]
@evjlobanova now it works!

but I've been faced one moment with file type: json displayed like txt

![Screenshot from 2020-05-15 16-22-36](https://user-images.githubusercontent.com/18463941/82055251-e2bec480-96c8-11ea-8669-de596fcf9b82.png)

Now we can close the issue. Thanks for your support!
