### ISSUE TITLE
Input format as HTML

### ISSUE THREAD

**Issue by Bharadwaj-vana** [reportportal/reportportal#868]
HI Team,

I am generating HTML after my execution and printing status of executions PASS / FAIL in report. Can I input my HTML into report portal ?? Will report portal do analysis of my execution status PASS / FAIL and display the data ?? I have attached sample HTML report that I am generating currently.
Is there any way that we can input HTML to report portal ? If so please let me know Thanks !
 OR

To display sample HTML data in current format (PASS / FAIL) into report portal what is the process !! please let me know.

[QMetryResponse_0.4462879839146868.html.zip](https://github.com/reportportal/reportportal/files/4377584/QMetryResponse_0.4462879839146868.html.zip)

Thanks,
Bharadwaj

**Comment by evjlobanova** [comment]
@Bharadwaj-vana Do you want ReportPortal to have a possibility to import your HTML report and reflect in the application?

The process of login data to ReportPortal is described https://reportportal.io/docs/Test-Framework-Integration
![image](https://user-images.githubusercontent.com/30413511/77512617-71128900-6e84-11ea-91e9-2e582e9a65f1.png)

**Comment by DzmitryHumianiuk** [comment]
@Bharadwaj-vana no, it won't read HTML data as regular logs.

if you already do generation of HTML file you definitely read and access process in runtime.
so you can wrap it with ReportPortal related requests to send data in runtime to RP in form of regular log/steps.

Here are the Reporting DevGuide which you can use:
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md

And here are implemented API clients which implements it:
- https://github.com/reportportal/client-java
- https://github.com/reportportal/client-net
- https://github.com/reportportal/client-Python
- https://github.com/reportportal/client-javascript
- https://github.com/reportportal/client-php

So the only thing you need to do is to add call of required request from client library in your framework at specific moment, and populate it data
