### ISSUE TITLE
reportportal gui doesn't work on firefox?

### ISSUE THREAD

**Issue by rabusiak** [reportportal/reportportal#869]
**Describe the bug**
...  reportportal web page is working in every browser except Firefox. Any idea how to fix this? When I type http:[dnsname]:8080 got redirected to https:// and get this error: SSL_ERROR_RX_RECORD_TOO_LONG

**Expected behavior**
... page should open like on every other browser, unsecured over http

**Screenshots**
If applicable

**Versions:**
 - Windows 10 (19587.1000), Firefox 74.0 (64 bits)
 - Version of RP API Service: 5.0.0;Index Service: 5.0.5;Authorization Service: 5.0.0;Service UI: 5.0.0;

**Comment by DzmitryHumianiuk** [comment]
added for reference:
https://www.thesslstore.com/blog/ssl_error_rx_record_too_long/

**Comment by rabusiak** [comment]
Clearing site preferences do the trick for me :)
https://stackoverflow.com/questions/30532471/firefox-redirects-to-https
