### ISSUE TITLE
[v5][API] ExternalSystemIssues not work

### ISSUE THREAD

**Issue by marysia16122** [reportportal/reportportal#870]
**Describe the bug**
Don't attach jira issue via api
I send HTTP request
`curl -X PUT "http://localhost:8080/api/v1/myProject/item/9f4ada25-8557-432b-af90-298eb4363709" -H "accept: */*" -H "Content-Type: application/json" -H "Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODUyNDAwNTcsInVzZXJfbmFtZSI6InN1cGVyYWRtaW4iLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOSVNUUkFUT1IiXSwianRpIjoiMmU1NGQwMmUtYWRkMS00YmIyLTg4NjgtODMyNjkzMWNmODc3IiwiY2xpZW50X2lkIjoidWkiLCJzY29wZSI6WyJ1aSJdfQ.xnDMQPoiJsQC8_sq4fAMPvWscg32e4RTdQZanyJZA10" -d "{ \"attributes\": [ { \"key\": \"string\", \"system\": true, \"value\": \"string\" } ], \"description\": \"aaaaa\", \"endTime\": \"2020-03-26T15:23:43.690Z\", \"issue\": { \"autoAnalyzed\": true, \"comment\": \"sssss\", \"externalSystemIssues\": [ { \"btsProject\": \"PA\", \"btsUrl\": \"https://jira.domain.net/\", \"submitDate\": 0, \"ticketId\": \"PA-174\", \"url\": \"https://jira.domain.net/browse/PA-174\" } ], \"ignoreAnalyzer\": true, \"issueType\": \"pb_toddc3g1sa5f\" }, \"launchUuid\": \"d25a424b-7042-44f4-9d68-ee09452ccb86\", \"retry\": true, \"status\": \"SKIPPED\"}"`

Request
![image](https://user-images.githubusercontent.com/1968384/77666623-39920280-6f92-11ea-82c1-9bfa368b0274.png)

Response (Code 200)
![image](https://user-images.githubusercontent.com/1968384/77666818-79f18080-6f92-11ea-98ff-716786cf7d54.png)

**Expected behavior**
Add PA-174 as tickets

**Screenshots**
![image](https://user-images.githubusercontent.com/1968384/77666909-9d1c3000-6f92-11ea-8ee5-42ef0ffd499b.png)

Plugin work good, tickets are added, problems only API

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version 80.0.3987.132

**Additional context**
reportportal/service-api:5.0.0
no error in logs

**Comment by evjlobanova** [comment]
@marysia16122 It is a known issue, we have fixed it in the version 5.1
It will be available ~ in 2 weeks
