### ISSUE TITLE
how testrail can be integrated with report portal.

### ISSUE THREAD

**Issue by Onish1204** [reportportal/reportportal#873]
what ever execution results are pushed to report portal. same should be pushed to test rail by report portal.

expectation:
No additional code should required to add for test rail integration. Is it feasible, 

Issue, i am facing is rest rail api are implemented in my test framework. Testrail is pushed at end of execution and report portal at end of each test. So, report portal test is not updating till we disable testrail listener.

pls suggest on same...

**Comment by evjlobanova** [comment]
@DzmitryHumianiuk can rp suggest something?

**Comment by shaburov** [comment]
@Onish1204 What is the language for developing autotests?

**If java**
You can add as many independent listeners as you like in both junit and TestNG
For example
https://gitlab.com/TouchBIT/Buggy/-/blob/master/buggy-testrail/src/main/java/org/touchbit/buggy/testrail/listeners/DefaultTestRailListener.java

In any case, your request is somewhat strange.

**Comment by DzmitryHumianiuk** [comment]
@Onish1204 this should be reviewed in details.
Listeners shouldn't have any interceptions or block each other.

I guess this is an issue relevant to specific setup.
And we can't comment without any details.

**Comment by Onish1204** [comment]
It is resolved by implementing TestNG Listener. Earlier it was not working as TestRail was posting result after complete suit execution Now, posting after test and issue resolved.

Thank You !!
