### ISSUE TITLE
[FR] - Attach failure step video along with exception

### ISSUE THREAD

**Issue by ramkumar-yoganathan** [reportportal/reportportal#875]
**As a User, I should be able to attach the failure step video with on click preview, So that I can able to investigate the failure and understand the actions such as unhandled popup, crash popup if any, before the failure.**

**Comment by ramkumar-yoganathan** [comment]
#117

**Comment by evjlobanova** [comment]
Duplicate of #117

I close this issue and link it to #117 .
For now, there is only a possibility to add a link to the video to the logs.
As far as logs are supported Markdown, the link will be clickable and you will be able to view the video.
https://github.com/reportportal/reportportal/issues/768

Also, we have an integration with SauceLabs https://github.com/reportportal/reportportal/issues/348
