### ISSUE TITLE
Reportportal5: high load on postgres after data migration from ReportPortal4

### ISSUE THREAD

**Issue by duzztie** [reportportal/reportportal#876]
Could you please give some reasons for the high load on postges db after data transfer? Data migration completed successfully, considering entries in the batch_job_execution table. When trying to open the ReportPortal5 dashboard, to execute queries such as /api/v1/xcom/widget/319, it takes about 5 minutes. I think postgres node is powerful enough, so I think problem may be in reportportal misconfiguration.

**Comment by DzmitryHumianiuk** [comment]
@duzztie PostgreSQL does indexing.
just give it a time to index newly inserted data after migration.

Duration depends on your data volume and hardware capacity.
