### ISSUE TITLE
[v5] Typo in the email notification "Password recovery"

### ISSUE THREAD

**Issue by evgenytkachenko** [reportportal/reportportal#879]
**Describe the bug**
An email notification "Password recovery" has a typo in the line "If you didn’t request this email, you may **safety** ignore it."

**To Reproduce**
On the login page click "Forgot password?" link
Enter your email address and click submit button
Go to your mailbox and open an email "Password recovery"
You will see  "If you didn’t request this email, you may **safety** ignore it." text

**Expected behavior**
 "If you didn’t request this email, you may **safely** ignore it."

**Comment by evjlobanova** [comment]
We have already fixed this bug in ver 5.1
