### ISSUE TITLE
[WIDGETS] Passing rate

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [reportportal/reportportal#88]
Create widget to represent passing rate

**Comment by avarabyeu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [one-two](https://trello.com/c/3fjt5kDh/1-one-two)

**Comment by jurteg** [comment]
Hi guys,
any due dates for this useful widget? or 3.1 release (it it icludes this widget)?

**Comment by DzmitryHumianiuk** [comment]
@jurteg ~July22

**Comment by jurteg** [comment]
Thank you!

**Comment by DzmitryHumianiuk** [comment]
available with 3.1
