### ISSUE TITLE
Authentication/authorization support using github enterprise

### ISSUE THREAD

**Issue by ranga543** [reportportal/reportportal#888]
* I'm not a `JAVA` developer but based on code, I'm guessing it supports `github.com` but not `GitHub Enterprise`
* I was looking around and I came across this `https://<my-reportportal>/uat/settings/default/oauth/github` api endpoint to update but it's returning `400 status code`
```
{
  "error_code": 4001,
  "message": "Incorrect Request. [Field 'userAuthorizationUri' should match '^(http:\\/\\/|https:\\/\\/)?(www.)?([a-zA-Z0-9]+).[a-zA-Z0-9]*.[a-z]3.?([a-z]+)?$\n' pattern.] [Field 'accessTokenUri' should match '^(http:\\/\\/|https:\\/\\/)?(www.)?([a-zA-Z0-9]+).[a-zA-Z0-9]*.[a-z]3.?([a-z]+)?$\n' pattern.]"
}
```
* And I'm assuming based on this line of [here](https://github.com/reportportal/service-authorization/blob/master/src/main/java/com/epam/reportportal/auth/integration/github/GitHubClient.java#L47) code it supports only `github.com`

**Comment by evjlobanova** [comment]
Duplicate of #877
