### ISSUE TITLE
Getting incorrect basePath for the API in the swagger docs which means "try it now" fails

### ISSUE THREAD

**Issue by LittleColin** [reportportal/reportportal#889]
The UI for the swagger client shows the following:
`[ Base URL: reportportal.mydomain.net/ ]`

but looking at the demo site it should be:
`[ Base URL: reportportal.mydomain.net/api ]`

In the swagger docs returned by /api-docs endpoint it has "basePath":"/" so I guess the issue must be in my service-api configuration somewhere. Is there a way for me to troubleshoot this further?

Note this is using Report Portal v5 docker image on Kubernetes AKS in Azure.

**Comment by Yumfriez** [comment]
@LittleColin It works as expected. API has base path "/", but all requests from the UI side are sent through the LoadBalancer (which handles prefixes aka "/uat" or "/api". And all requests from the swagger page are sent with these prefixes in the request
