### ISSUE TITLE
[UI] The "Method type" filter button work not properly

### ISSUE THREAD

**Issue by admizh** [reportportal/reportportal#89]
Expected behavior:
After click to "Method type" button - methods with type: before/after test should be hidden.

Current results:
Enabled  "Method type" filtering doesn't hide all methods (before/after)

![filter methods](https://cloud.githubusercontent.com/assets/6014483/24534731/e079f116-15e0-11e7-8ad1-da3666ab986b.gif)

Also I see borders - which should not be displayed
![2017-03-31_7-05-35](https://cloud.githubusercontent.com/assets/6014483/24534961/31148126-15e2-11e7-96b1-325ce36ebda2.png)

**Comment by e-olga** [comment]
Hi @admizh,

Collapse/Expand hides all precondition methods,  **except** methods with status FAILED (mentioned in  [Docs](http://reportportal.io/#documentation/Viewing-data)).
Borders are visible intentionally, due to show that some items are collapsed.

**Comment by admizh** [comment]
@e-olga  Thank you.
