### ISSUE TITLE
Response code is still 201 even though exception occured

### ISSUE THREAD

**Issue by schrufygroovy** [reportportal/reportportal#892]
When I do an invalid request to report portal `log` api, then I get still the 201 created success code:

![image](https://user-images.githubusercontent.com/50398024/77920564-ee803400-729e-11ea-90c0-976aeb7cee2c.png)

This causes clients that dont check the response content (e.g. the JavaScript client) to think the request was successful and continue with 'success' even though the log message was never created

**Comment by evjlobanova** [comment]
@Yumfriez could you please take a look?

**Comment by evjlobanova** [comment]
@svettsova Could you please check this issue?

**Comment by svettsova** [comment]
@schrufygroovy could you provide the request example (including body)?

**Comment by schrufygroovy** [comment]
Looks like the JavaScript library is using some illegal content format: `multipart/form-data; boundary=8571066768`. with binary data. So it seems to be caused by them. I cannot reproduce with usual API request using 'application/json'. Sorry for the confusion...

**Comment by evjlobanova** [comment]
Can I close this issue?
