### ISSUE TITLE
New field: Test Case ID

### ISSUE THREAD

**Issue by evjlobanova** [reportportal/reportportal#895]
# Test Case ID: What is it?

If you are using any of the Test Management System(TestRail, Jira, ALM, and others), you have a unique identification of test cases in it.
In version 5.1 you have an ability to report test cases with TestCase ID from TMS. That gives you an ability to link a source of the test case in TMS and its execution in ReportPortal.

![image](https://user-images.githubusercontent.com/30413511/78219304-ec4cee00-74c7-11ea-96ac-a52f4b9e6fb5.png)

# How Test Case ID can be reported to ReportPortal
## Via agents
Users can add a Test Case ID number via agents.  All details you can find in the dev guide https://github.com/reportportal/client-java/wiki/Test-case-ID

If test execution has test parameters, a test case ID will be generated on the base of:
TestCaseID + all test  parameters

## Automatically based on 'Code reference' and 'Parameters'
If users do not report test case ID, it is generated automatically on the base of:
'Code reference' + all test parameters

## Automatically based on Test Execution name, All parents name, Parameters
If users do not report Test Case ID and Code reference, then test case ID is generated on the base of:
Test Case Name  + All parents Name (except Launch name) + All parameters

# Where is Test Case ID using in ReportPortal ver 5.1
1. The history line is based on the Test Case ID 
2. The history table is based on the Test Case ID
3. Test Case ID in added on UI tot "Edit Modal' for test case

# What will change in version 5.1
 The main difference:
Before ReportPortal is using **a test unique ID**. UID has been generated on the base of Launch name + Test Case Name  + All parents Name + All parameters.
**Test Case ID does not include Launch name**
![image](https://user-images.githubusercontent.com/30413511/78221739-9af32d80-74cc-11ea-93f3-2ca69490a14d.png)

History table changes #896 
History line changes #894

**Comment by mnicula** [comment]
Will there be an improvement that will allow to search for a test based on this field? Thank you.
