### ISSUE TITLE
[UI] Twice rendered controls

### ISSUE THREAD

**Issue by admizh** [reportportal/reportportal#90]
1. Open Test Case view under Test Launch
2. Scroll down
3. Select all Tests

Current results:
![2017-03-31_7-32-13](https://cloud.githubusercontent.com/assets/6014483/24535373/b72f55b8-15e4-11e7-9aa0-e27962e98848.png)

Steps:
![twice rendering](https://cloud.githubusercontent.com/assets/6014483/24535380/c19a7e2e-15e4-11e7-92ab-0cbfbf30abeb.gif)

**Comment by e-olga** [comment]
Added to RP backlog
