### ISSUE TITLE
ReportPortal.addins integration with TestCentric.GuiRunner.1.3.2

### ISSUE THREAD

**Issue by eddie101AMR** [reportportal/reportportal#902]
Hi,
I'm trying to run tests via TestCentric.GuiRunner.1.3.2, but I can't see the results uploaded to ReportPortal, I added ReportPortal.addins to folder in packages folder,
the same thing I did with NUnit.ConsoleRunner.3.11.1 and it's working fine when I run my tests via Nunit console runner,
what I'm missing?
I need to run tests of my dll tests file from some nunit gui runner?
any ideas ?

Thanks

**Comment by evjlobanova** [comment]
@nvborisenko maybe you can help with it?

**Comment by nvborisenko** [comment]
Transferred to https://github.com/reportportal/agent-net-nunit/issues/58.

Because of some issues in github this is sill stay here. Closing it.
