### ISSUE TITLE
[RP5] Improvement. Add 'Download artifact' button

### ISSUE THREAD

**Issue by alex-i-rybkin** [reportportal/reportportal#903]
During test run, we usually post to RP different logs, test-recordings, screenshots, etc. When analyzing test results I usually need to download these results for further detailed analysis and reposting them to Jira or share with somebody directly. 

In RP4 it was possible to download any artifact by right-clicking on its icon in logs and pressing the 'Save link as' button.

In RP5 I could not find an easy way to download an artifact, apart from going to browser dev-tools and extracting URL of the artifact while it is loaded in the browser, then downloading it with CURL. Sound and feels pretty uncomfortable, considering that this operation is a daily routine.

Thus, I suggest adding a small download button near each artifact attached to logs. Something like on the screen below.
![image](https://user-images.githubusercontent.com/30799266/78226528-81ee7a80-74d4-11ea-927f-a832ae35243b.png)

**Comment by evjlobanova** [comment]
In version 4
![image](https://user-images.githubusercontent.com/30413511/78342347-d14eac80-75a1-11ea-80a5-551bfb879f8a.png)
In version 5
There is no option "Save as a link"

**Comment by evjlobanova** [comment]
I a version 5.0 has been changed a logic, that why this improvement should rethink. 
For now, we can not mimic a behavior from 4 the version

**Comment by schrufygroovy** [comment]
If the attachment is of some unknown type, then the download is possible via clicking on the icon.
![image](https://user-images.githubusercontent.com/50398024/88177696-97291980-cc29-11ea-801d-df587b96f35e.png)

**But**, it seems that the file name is always some guid and not the file name I specified when uploading the file. Is there any possiblity to download an attachment with the correct file name anywhere?

**Comment by VolhaKarenko** [comment]
The improvement is implemented in version 5.4
