### ISSUE TITLE
Endless loop when the plugin stops

### ISSUE THREAD

**Issue by shaburov** [reportportal/reportportal#905]
Precondition.
Build plugin-bts-jira jar with java 11 (last master)
Load plugin to reportportal
**Result**: infinity loop with error `java.lang.UnsupportedClassVersionError`
logs service-api
```
2020-03-04 17:09:05.317  INFO 1 --- [ult-task-sched2] org.pf4j.AbstractPluginManager           : Stop plugin 'jira@5.1.0-SNAPSHOT'
2020-03-04 17:09:05.318 ERROR 1 --- [ult-task-sched2] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.UnsupportedClassVersionError: com/epam/reportportal/extension/bugtracking/jira/JiraStrategyPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by evjlobanova** [comment]
@shaburov please wait a release of 5.1 (next week). 
In ver 5.1 Jave 11 will be introduced.
So that this problem will be resolved.
Also in the version 5.1  some improvements for plugin uploading have been done.
