### ISSUE TITLE
[UI] Disabled "Refresh" button - need take action

### ISSUE THREAD

**Issue by admizh** [reportportal/reportportal#91]
![image](https://cloud.githubusercontent.com/assets/6014483/24535621/3e4fff06-15e6-11e7-8d74-cdf83be32d52.png)

Steps to reproduce:
1. Go to "Tests investigation" view
2. Select all tests 
3. Change defect type
![disabled refresh button](https://cloud.githubusercontent.com/assets/6014483/24535653/747faec8-15e6-11e7-99a3-1f9c4bbd5bd9.gif)

**Comment by DzmitryHumianiuk** [comment]
will be fixed in 3.0 beta

**Comment by lexecon** [comment]
The counter will be removed when the button is not active
