### ISSUE TITLE
github actions not detected

### ISSUE THREAD

**Issue by paulpach** [reportportal/reportportal#910]
the Uploader cannot detect when it is running inside github actions

**Comment by DzmitryHumianiuk** [comment]
@paulpach could you please elaborate this issue?

**Comment by evjlobanova** [comment]
Could you please describe the whole  process of how you use GitHub actions and ReportPortal and what stage the issue happens on?

**Comment by evjlobanova** [comment]
Connected with #909

**Comment by paulpach** [comment]
Thank you for the quick response,  here is the failed job:
https://github.com/MirrorNG/MirrorNG/runs/560588315?check_suite_focus=true

This is the relevant piece of my github action pipeline:

```cs
jobs:
  testRunnerInAllModes:
    name: Unity test
    runs-on: ubuntu-latest
    steps:     
    - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

    - name: Run editor Tests
        # .. my step runs nunit tests and results are generated in Test/*.xml

     - name: Publish tests
        if: always()
        run:
          curl -s https://report.ci/upload.py | python - --include='Tests/*.xml'

```

Here is the link to the actual line that invokes it:
https://github.com/MirrorNG/MirrorNG/blob/d348d3a7994377c8b30b0cf31356051010e9e134/.github/workflows/main.yml#L95

**Comment by evjlobanova** [comment]
But it is still unclear how you use reportrpotal.io?

**Comment by DzmitryHumianiuk** [comment]
@paulpach Adoption for usage in GH Actions in or roadmap with high priority.
there is no any comment right now.

but we will get back to it, once have any certain fix or suggestion.

**Comment by DzmitryHumianiuk** [comment]
@paulpach Are you confusing us with Report.ci ?
