### ISSUE TITLE
[v5] [GitHub] [Auth] Organization authentication does not work for private members

### ISSUE THREAD

**Issue by shaburov** [reportportal/reportportal#913]
Current version: API Service: 5.0.0;Index Service: 5.0.5;Authorization Service: 5.0.0;Service UI: 5.0.0;

### Steps
Create token with `read:org` scope
![image](https://user-images.githubusercontent.com/15269131/78501840-5682be80-7766-11ea-93ff-8bf2d472d07f.png)

Add configuration
![image](https://user-images.githubusercontent.com/15269131/78501813-2affd400-7766-11ea-9593-589d9603e9a5.png)

### Actual error:
```
An error occurred while connecting to server: User 'shaburov' does not belong to allowed GitHUB organization
```

```
com.epam.reportportal.auth.integration.github.GitHubTokenServices$InsufficientOrganizationException: User 'shaburov' does not belong to allowed GitHUB organization
	at com.epam.reportportal.auth.integration.github.GitHubTokenServices.loadAuthentication(GitHubTokenServices.java:71) ~[classes!/:na]
```

If change `Organization visibility` to Public - **authentication works**
![image](https://user-images.githubusercontent.com/15269131/78501885-9a75c380-7766-11ea-98a1-5e3a2d967a40.png)
### Problem 
Authentification must be work with `read:org` token scope.
`read:org -> Read org and team membership, read org projects`

GitHubTokenServices#loadAuthentication(String)
```
assignedToOrganization = gitHubClient.getUserOrganizations(gitHubUser)
```
You should make a request **not** by user, but by **members of the organization**
You have from config
1. List of organisation names
2. Api token with `read:org` scope
3. Client ID for token (optional)

**I checked api calls with a token that has access only to the organization’s reading**
Even if member "visibility of the organization" is "private"
Call work as expected according to the github documentation
**[Check membership](https://developer.github.com/v3/orgs/members/#check-membership)**
> Response if requester is an organization member and user is a member
> Status: 204 No Content
```
curl -H "Authorization: token <TOKEN>" "https://api.github.com/orgs/insolar/members/shaburov" -I
HTTP/1.1 204 No Content
Date: Sun, 05 Apr 2020 15:53:15 GMT
Server: GitHub.com
Status: 204 No Content
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4999
X-RateLimit-Reset: 1586105595
X-OAuth-Scopes: read:org
X-Accepted-OAuth-Scopes: read:org, repo, user
```

**Pay attention**
```
204 No Content
X-OAuth-Scopes: read:org
X-Accepted-OAuth-Scopes: read:org, repo, user
```

Assumes a solution similar to the example below
```
boolean isOrganisationMember = false;
if (!allowedOrganizations.isEmpty()) {
  for (String organisation: allowedOrganizations) {
    OrganizationResource gitHubOrganization = gitHubClient.getOrganization(organisation);
    boolean result = gitHubClient.isOrganisationMember(gitHubOrganization, gitHubUser);
    if (result) {
      isOrganisationMember = true;
    }
  }
  if (!isOrganisationMember) {
    throw new InsufficientOrganizationException(
      "User '" + gitHubUser.getLogin() + "' does not belong to allowed GitHUB organization");
  }
}
```

**Comment by evjlobanova** [comment]
@svettsova Valya, could you please check this issue for version 5.1 and tell us results?

**Comment by shaburov** [comment]
@shaburov I looked at the implementation in the last commit of `origin/develop` in the `service-authorization` project. Everything is as described in the defect.
