### ISSUE TITLE
[v5][SAML] Authorization callback request from Okta doesn't work on Safari browser

### ISSUE THREAD

**Issue by ivan-sukhomlyn** [reportportal/reportportal#914]
**Describe the bug**
SAML authorization doesn't work properly on the **Safari** browser.
RP doesn't authorize a user and redirect to UI after IdP callback request to ReportPortal after successful login.

But SAML authorization method works properly at Google Chrome browser

**To Reproduce**

1. Open Safari browser
2. Go to ReportPortal URL
3. Login with SAML
4. After redirection to IdP (Okta) - authorize with correct credentials
5. Safari browser redirects to ReportPortal's login page instead of the dashboard after successful authorization at Okta side

Open

**Expected behavior**
User can be authorized at ReportPortal with SAML method on Safari browser like on Google Chrome

**Additional context**
- SAML provider: Okta
- ReportPortal version: 5.0
 - OS: macOS 10.15.4
 - Browser: Safari 13.1

**Comment by evjlobanova** [comment]
@ivan-sukhomlyn we are planning to introduce SAML officially in the version 5.3, so that we will check and fix this bug in the 5.3.

@svettsova Valya, could you please add an appropriate test for SAML integration?

**Comment by ivan-sukhomlyn** [comment]
@evjlobanova Thanks for your quick reply and clarifying

**Comment by VolhaKarenko** [comment]
The issue is not reproducible on 
ReportPortal version: 5.3
Safari Version 13.1.2
