### ISSUE TITLE
[v5] Failed to save Edit defect type if defect already have linked Jira ticket

### ISSUE THREAD

**Issue by rasim-sitmanbetov** [reportportal/reportportal#916]
**Describe the bug**
Failed to save **Edit defect type** if the defect already has linked Jira ticket. 
Edit might be initiated from the **Defect details** page or from **Defect list** page
Error **Failed to update defects**

**To Reproduce**
1. Have a defect with linked Jira ticket
2. try to edit the defect type (**pencil** button), e.g. **add a comment** and/or **change defect type** and **save changes**
**Expected behavior**
Result of defect edit is saved
**Screenshots**
<img width="1648" alt="RP_edit_defect_type_with_linked_jira_ticket" src="https://user-images.githubusercontent.com/62949781/78695372-b0ba8580-7906-11ea-8e53-134caa6cfb82.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 80.0.3987.163

**Additional context**
1. Valid both for single and bulk ticket update
2. Edit works fine if the Jira ticket is unlinked. After that, you can link the ticket again.
3. RP logs **TBD**

**Comment by evjlobanova** [comment]
Fixed in version 5.1. 
Please update to the latest version

**Comment by Ngaur** [comment]
I can still see the same issue for me. I am using v 5.2

**Comment by evjlobanova** [comment]
Please update to the latest version, and check once again.
Please let me know if it is still reproduce

**Comment by Ngaur** [comment]
Thanks @evjlobanova !
I updated the containers to 5.3 as per latest docker-compose file.
Still I can see this issue. I looked into analyser log got Connection Error with "Name or service not known"
Attached a screenshot of log for reference.
<img width="1435" alt="Screenshot 2020-09-18 at 3 11 16 PM" src="https://user-images.githubusercontent.com/1961119/93590135-9ca5a480-f9cb-11ea-8b33-e467f933bd43.png">

**Comment by Ngaur** [comment]
Just an update -- 
I just changed the owner of elasticsearch for example chown 1000:1000 /data/elasticsearch
It just solve this issue, I can update the defect successfully now. 
But auto-anlyser still says following --  
"analyzerApp.esclient - ERROR - NotFoundError(404, 'index_not_found_exception', 'no such index [4]', 4, index_or_alias)"

**Comment by evjlobanova** [comment]
@MariyaIvanina could you please check?

**Comment by MariyaIvanina** [comment]
@Ngaur Hi! Have you regenerated the index after moving to the newest version? It seems, that the index 4 was not saved in the elasticsearch.

**Comment by Ngaur** [comment]
@MariyaIvanina Let me just try re-indexing. Thanks for the info.
