### ISSUE TITLE
i couldn't able to login 5.1 docker application instance use following username and password

### ISSUE THREAD

**Issue by madhukeshava** [reportportal/reportportal#917]
**Describe the bug**
i couldn't able to login 5.0.1 docker application instance use following username and password
superadmin\erebus
default\1q2w3e 
**Expected behavior**
login should success

**Screenshots**

![image](https://user-images.githubusercontent.com/28648906/78770232-ebc2c480-79ab-11ea-910c-8b2638611ff2.png)

If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is] 5.1

**Comment by DzmitryHumianiuk** [comment]
@madhukeshava there is no up-and-running services of RP.
You should see at least 4 services available.

see `docker ps` for containers statuses.


Example from https://web.demo.reportportal.io
![image](https://user-images.githubusercontent.com/11332788/78773562-1573ef80-799c-11ea-8600-fba24938ae3a.png)

**Comment by waynesun09** [comment]
This also happen to me with the latest 5.1 version
Raised issue in service-authentication:

https://github.com/reportportal/service-authorization/issues/178

all services are running

**Comment by waynesun09** [comment]
Closed the issue, this is due to latest hash changed from md5 to BCrypt in service authorization, which require run latest migration to update the md5 password in db to bcrypt.
