### ISSUE TITLE
[Merged launches] Negative value in the "To Investigate" counter for merged launch

### ISSUE THREAD

**Issue by admizh** [reportportal/reportportal#92]
Steps to reproduce:
1. Generate demo data under project settings
2. Go to launches
3. Select all launches
4. Merge selected launches
5. Open items with status "To Investigate"
6. Select all "To Investigate" items
7. Perform bulk operation -> change Defect type
8. Go back to "launches" view
9. Check "To Investigate" counter value

![2017-03-31_8-05-59](https://cloud.githubusercontent.com/assets/6014483/24536159/a2cd84d2-15e9-11e7-9361-a77ba46ad819.png)

**Comment by pictureb00k** [comment]
Fixed in 3.0
