### ISSUE TITLE
How to get launch non-udid?

### ISSUE THREAD

**Issue by zarashima** [reportportal/reportportal#923]
Hi,

I want to update launch details directly through API. The question is how can I get launch id in my test script using java-testng-agent? The  `rp.launch.id` system property returns udid here, and so I can't use it in because update launch API requires launch non-udid.

Thanks

**Comment by evjlobanova** [comment]
@pbortnik @Yumfriez could you please advice on the issue?

**Comment by Yumfriez** [comment]
@zarashima You can use `getLaunchByUuid` method to access all Launch fields:
https://github.com/reportportal/client-java/blob/develop/src/main/java/com/epam/reportportal/service/ReportPortalClient.java#L61
