### ISSUE TITLE
[v5] No result when click on tests number in launch

### ISSUE THREAD

**Issue by dkuchynskyi** [reportportal/reportportal#924]
1. Go to Launches
2 Click on any tests number (Total, Passed, Failed - no matter)
![image](https://user-images.githubusercontent.com/34566341/79194645-95370980-7e35-11ea-98e6-019417168778.png)

actual result:
empty page with no results opened:
![image](https://user-images.githubusercontent.com/34566341/79194732-be579a00-7e35-11ea-94bf-0cf8dee044c1.png)

Expected result:
list of tests should be present as it was in version 4

**Comment by DzmitryHumianiuk** [comment]
@dkuchynskyi which agent and version?

root cause: Test Cases sent as `type=TEST`
but should be send as `type=STEP`

if you use custom agent then update RQ to server

**Comment by dkuchynskyi** [comment]
pytest-reportportal 5.0.2
migrated to report portal 5.1.0 from the 4 version without any changes in settings

**Comment by DzmitryHumianiuk** [comment]
@dkuchynskyi could you please share with us 2 things:
1) Copy and share link which it referenced by any tests number (Total, Passed, Failed - no matter)
2) Click on launch -> suite -> class and find any test case. make a screenshot of test case representation.

Most likely the same fix was made in RobotFramework https://github.com/reportportal/agent-Python-RobotFramework/pull/57#event-3214823385

CC @iivanou

**Comment by iivanou** [comment]
@DzmitryHumianiuk is correct. The issue has already been addressed.

**Comment by dkuchynskyi** [comment]
@iivanou  will you make the same fix into pytest-reportportal?

**Comment by iivanou** [comment]
@dkuchynskyi open an issue at the pytest-reportportal.

**Comment by dkuchynskyi** [comment]
@iivanou  [https://github.com/reportportal/agent-python-pytest/issues/188](url)
