### ISSUE TITLE
Reset password link leads to login screen in Safari

### ISSUE THREAD

**Issue by ylupinov** [reportportal/reportportal#927]
**Describe the bug**
Reset password link leads to login screen in Safari
1) go to RP
2) click forgot password
3) open received email an click reset password

**Expected behavior**
link should lead to password recovery screen

**Actual behavior**
Reset password link leads to login screen in Safari

**Versions:**
 - macOs Catalina  10.15.4, Safari Version 13.1 (15609.1.20.111.8)
 - Version of RP 
Current version: API Service: 5.1.0;Index Service: 5.0.7;Authorization Service: 5.1.0;Service UI: 5.1.0;

**Additional info**
works fine in Chrome

**Comment by evjlobanova** [comment]
@VolhaKarenko please check if it reproduces, and open a defect in Jira

**Comment by VolhaKarenko** [comment]
The issue is not reproducible on RP version:
API Service: 5.1.0;Index Service: 5.0.8;Authorization Service: 5.1.0;Service UI: 5.1.1;
for Safari Version 13.1 (15609.1.20.111.8)
macOs Catalina 10.15.4 
@ylupinov Could you please do the necessary updates and verify the issue once again?
