### ISSUE TITLE
[v5] Auto-Analyzer not working with nested Steps

### ISSUE THREAD

**Issue by NilsPK** [reportportal/reportportal#928]
**Description**
The Auto-Analyzer-Function does not work if used with nested Steps

**To Reproduce**

- Create a launch containing a number of items which have nested steps. 
- Status has to be "FAILED"
- Nested steps have logs attached with level "ERROR"
- A second launch with similiar/identical logs has to be created
- Analyze the second launch

You can use the attached postman collection
[RP-Nested-Step-Bug.postman_collection.txt](https://github.com/reportportal/reportportal/files/4492711/RP-Nested-Step-Bug.postman_collection.txt)

If executed with collection variable "itemsHaveStats" set to false, a launch with nested steps will be created.
Items are failed and deepest layer has a log.
1. Fill out the three collection variables and auth in the postman collection settings.
2. Execute two times
3. Assign defect of first launch to an existing defect type in ReportPortal
4. Start Auto-Analyzer for the second launch

**Expected behavior**
The defect in the second launch which is "To Investigate" will be set to the type of the first defect

**Actual behavior**
The type of the second defect is not changed.
If you change the "itemsHaveStats" variable to true. The same structure is created without nested steps and the Analyzer works as expected.

**Additional Info**
I'm using the API to integrate reporting to ReportPortal in a custom-made testframework.
The nested steps are essential for displaying our test structure in ReportPortal.

Is this a bug or did I do something wrong when using nested steps?

**Comment by DzmitryHumianiuk** [comment]
@NilsPK what's API version you use?

**Comment by NilsPK** [comment]
RP version is 5.0.0
As for the API I tried both v1 and v2

**Comment by NilsPK** [comment]
If you mean version of the API-Service it is also 5.0.0
![image](https://user-images.githubusercontent.com/45734314/79570227-574a1780-80b9-11ea-85a5-8ea1f9f6a2a7.png)

**Comment by evjlobanova** [comment]
It has been fixed in ver 5.1
Please, update to the latest version

**Comment by NilsPK** [comment]
Didn't get the release notice although I'm watching the project.
Sorry for the bother!
