### ISSUE TITLE
Install Reportportal- API and db-scripts unhealthy

### ISSUE THREAD

**Issue by hby1812** [reportportal/reportportal#930]
Hi all, 

I am getting an error API and db-scripts unhealthy.
Can you please help me to take a look? 
![image](https://user-images.githubusercontent.com/62381132/79697216-ac4d7f80-82ab-11ea-9db3-d0dd10de0975.png)

**Comment by evjlobanova** [comment]
@hby1812 please elaborate on this:
- version of rp
- your os
- any others

**Comment by ariel411** [comment]
Hi, I found the same problem
I'm using windows 10 64 bits as OS

![image](https://user-images.githubusercontent.com/61328207/79808005-81f6d300-833a-11ea-95d6-f202e9e3a619.png)

**Comment by ohank** [comment]
Look like you are using windows. Have you change the volumes: in the docker-compose.yml ?

      # For windows host
      # - postgres:/var/lib/postgresql/data

**Comment by ohank** [comment]
I get this problem when i run it on a ubuntu server that mounts a windows disk and use it as volume.

**Comment by soba1210** [comment]
same on mac os

**Comment by ariel411** [comment]
> Look like you are using windows. Have you change the volumes: in the docker-compose.yml ?
> 
> ```
>   # For windows host
>   # - postgres:/var/lib/postgresql/data
> ```

It works with this change, also I uncommented the last part into docker-compose file
Thanks

**Comment by pbortnik** [comment]
Yes, for windows, you have to change postgres volume.
Anyway, could you please attach the logs of unhealthy services, so we get the starting point for further investigations.

**Comment by evjlobanova** [comment]
Closed, because of no response.
Feel free to reopen if this issue is still reproduce

**Comment by VanKrock** [comment]
I uncomment 
```
  # For windows host
  # - postgres:/var/lib/postgresql/data
```
but
```
c:\reportportal>docker-compose up
ERROR: Named volume "postgres:/var/lib/postgresql/data:rw" is used in service "postgres" but no declaration was found in the volumes section.
```

**Comment by gbuh** [comment]
I have the same issue as @VanKrock

**Comment by VanKrock** [comment]
@gbuh I rosolve this using `./` for mount volume inside current directory.
```
# For windows host
- ./data/postgres:/var/lib/postgresql/data
```

**Comment by gbuh** [comment]
I tried. Unfortunately the following error occurs (as we can saw at the beginning):
Creating reportportal_postgres_1      ... done
Creating reportportal_rabbitmq_1      ... done
Creating reportportal_elasticsearch_1 ... done
Creating reportportal_ui_1            ... done
Creating reportportal_minio_1         ... done
Creating reportportal_gateway_1       ... done
Creating reportportal_uat_1           ... done
Creating reportportal_index_1         ... done
Creating reportportal_analyzer_1      ... done

ERROR: for db-scripts  Container "76a11ce81b47" is unhealthy.

ERROR: for api  Container "76a11ce81b47" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by vrakr19** [comment]
Facing the same issues.

**Comment by 765119** [comment]
facing same issue 
Recreating reportportal_gateway_1       ... done
Recreating reportportal_uat_1           ... done
Recreating reportportal_postgres_1      ... done
Recreating reportportal_rabbitmq_1      ... done
Recreating reportportal_minio_1         ... done
Recreating reportportal_ui_1            ... done
Recreating reportportal_elasticsearch_1 ... done
Recreating reportportal_analyzer_1      ... done
Recreating reportportal_index_1         ... done

ERROR: for api  Container "3307a495531b" is unhealthy.

ERROR: for db-scripts  Container "3307a495531b" is unhealthy.

rp version 5.3.2
os- mac

**Comment by MichalFidor** [comment]
I’m trying to set up and run Reportportal on my Raspberry PI 4 (Raspbian OS). Unfortunately I’m struggling while building it up with exactly the same issue:

```
ERROR: for api Container "25dcfc010336" is unhealthy. 
ERROR: for db-scripts Container "25dcfc010336" is unhealthy. 
ERROR: Encountered errors while bringing up the project.
```

Any progress with solving that out?

![Screen Shot 2021-05-05 at 11 27 20 AM](https://user-images.githubusercontent.com/42964298/117124504-b3e9a480-ad98-11eb-8353-2074c8a0a9b7.png)

**Comment by nandyQA** [comment]
Any progress with this issue?

**Comment by nandha081992** [comment]
@MichalFidor @Cyberglamdring @evjlobanova @vrakr19 @gbuh @VanKrock 
I'm facing the same issue. Im using Linux machine. Can anyone of you help me to resolve this issue ASAP. 

Your helo will be much appreciated!!☺️

**Comment by gbuh** [comment]
Sadly, I'm waiting for someone to help with this.  Almost a year already...

**Comment by nandyQA** [comment]
@gbuh I had a solution for this .

sudo vi docker-compose.yml
Go to :   volumes:
      # For unix host
      - ./data/postgres:/var/lib/postgresql/data
      
      and change as 
volumes:
      # For unix host
      - /var/lib/postgresql/data

Finally enter :wq to exit

Now, Kill all existing containers using 
docker rum -f $(docker ps -a -q)
docker-compose up
 Finally,
docker-compose -p reportportal up -d --force-recreate

here We go!!!

**Comment by Cyberglamdring** [comment]
Hi everyone, 
It looks like a problem with permissions to volume from docker user/group. Try to change the [volume for Postgres](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L105) and gain RW permissions.

**Comment by gbuh** [comment]
Resolved for me. Thanks a lot.
