### ISSUE TITLE
[v5] Jira plugin upload in report portal settings is not working

### ISSUE THREAD

**Issue by sasikala-codoid** [reportportal/reportportal#932]
**Description**
When I try to upload all the latest jira plugins in report portal settings page, then it throws upload error

**Steps:**
1. Upload a latest version of jira plugin
2. It throws error, see attached screenshot

**Observation:**
Report portal Build 5.0
Jira plugin tried - plugin-bts-jira-5.0.1-all, plugin-bts-jira-5.1.0-all, plugin-bts-jira-5.0.0-all

**Screenshot**
![issue-rp](https://user-images.githubusercontent.com/15124663/80216228-5e45cc80-865b-11ea-916f-7d2c3fed80cd.png)

**Comment by pbortnik** [comment]
@sasikala-codoid 
Hi, is it a problem for you to upgrade the version of RP to 5.1.0 and try plugin again?

**Comment by jbadeau** [comment]
Doesn't work with 5.1 either. Looks like the nginx config

client_max_body_size is too small

**Comment by agnes-dober** [comment]
I had the same problem. (Also have nginx.) For anyone else having problems: adding to the server block in /etc/nginx/sites-enabled/[your site]: client_max_body_size 128M and client_body_timeout 180s resolved the issue. (Or it can be done in /etc/nginx/nginx.conf)

**Comment by MungThai** [comment]
I had a problem plugin-bts-jira-5.1.0 does not work with Jira Server. Its only works with Jira Cloud, because the plugin only support Basic Authentication and Does not work with Bearer token
How can I modify the plugin to support both?

Thanks,
