### ISSUE TITLE
Sign in with Github button missing/ cannot access login via github

### ISSUE THREAD

**Issue by nbob31** [reportportal/reportportal#936]
I have configured my Report Portal version 5.1.0 to use Github. When I go to the login page the github button is missing and I can only get to the login by directly going to to the url reportportalurl.com/uat/sso/login/github directly. After I login it brings me to the login page with the error `Could not obtain access token`. The error in the console is `"Full authentication is required to access this resource"`

ENV:
Report Portal 5.1.0 deployed to Kubernetes
OS: MAC
BROWSER: CHROME

**Comment by evjlobanova** [comment]
@nbob31 Any steps to reproduce this issue?

**Comment by nbob31** [comment]
1. Login as a admin user
2. Click the menu icon dropdown on the right side of the nav bar
3. Click Administrate
4. Click on Server Settings
5. Go to Authorization Configuration and toggle github authorization on
6. Enter the client id, secret and organization name.
7.  Click save
8. Logout and go to the login page url /ui/#login
**Actual: Login with Github button is missing
Expected: Login with Github button should be present.** 

9: If you go to the http://reportportal_url/uat/sso/github/login and enter your github username and password and click sign in you are then brought back to the login page with the error `Could not obtain access token` and the error in the console is "Full authentication is required to access this resource". 

I have verified I can successfully authorize with Github from within reportportal and tested having my organization membership set to both public and private and I see the same issues. 


<img width="1591" alt="Screen Shot 2020-04-30 at 1 21 47 PM" src="https://user-images.githubusercontent.com/18319454/80749050-85811b80-8aeb-11ea-8b6a-47e9151bc07f.png">


<img width="1473" alt="Screen Shot 2020-04-30 at 1 23 54 PM" src="https://user-images.githubusercontent.com/18319454/80749145-a5b0da80-8aeb-11ea-9415-cc8e60326097.png">

**Comment by nbob31** [comment]
Does the OAuth Web Application Flow token need to have specific scopes for `read:org` or `"read:user", "user:email"`

**Comment by nbob31** [comment]
@evjlobanova were you able to reproduce this error?

**Comment by evjlobanova** [comment]
@svettsova Could you please try to reproduce this issue?

**Comment by svettsova** [comment]
@evjlobanova as I remember, on 5.1 version was no such issues. I tried to reproduce it on 5.2 - I can see the 'Login with GitHub' button. I guess there can be issues in github settings (OAuth Apps or specific rights) and we should ask dev team to have a look

**Comment by svettsova** [comment]
@nbob31 could you attach a screenshot with uat service from Info request?

**Comment by nbob31** [comment]
I have done the following to produce these logs.

1. Login
2. Go to server settings and turn enable Github auth and save the settings
3. Logout
4. Go to http://reportportal_url.com/uat/sso/login/github with shows the error "could not obtain access token"

[uat-log.log](https://github.com/reportportal/reportportal/files/4635168/uat-log.log)

**Comment by Yumfriez** [comment]
@nbob31 Probably there were some problems with LB configuration, because I can't see any services on the `Login page` in the `versions` list. Try to deploy RP again and wait until services will be displayed. Probably some requests (one of them is `info` that fetches info about services and `github` button) are failing
