### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined" after clicking on Pattern Analysis [v5]

### ISSUE THREAD

**Issue by pbortnik** [reportportal/reportportal#937]
I am getting error as "TypeError: Cannot read property 'toString' of undefined" after clicking on Pattern Analysis first time after migration from V4.3 to V5 to V5.1.

![image](https://user-images.githubusercontent.com/8058828/80571691-b850e400-8a05-11ea-8a61-f9df5dc863d0.png)

**Comment by pbortnik** [comment]
Fixed in the latest version of migration services.
If migration was run before fix there is a workaround. Need to connect to the database and execute the next query:
`INSERT INTO project_attribute (attribute_id, value, project_id)  select 10, false, id from project ON CONFLICT DO NOTHING;`

**Comment by digaetan** [comment]
WA tested to be working!
Maybe when providing WA procedure please provide some clear steps how to apply those (not all may know) ;)
1) docker ps --> identify the container running PostGres
2) connect to that container --> # docker container exec -it <CONTAINER_NAME> /bin/bash
3) connect to DB --> (if you haven´t change default values) # psql reportportal rpuser
4) type SQL query --> INSERT INTO project_attribute (attribute_id, value, project_id) select 10, false, id from project ON CONFLICT DO NOTHING;

**Comment by elavrenchuk** [comment]
@pbortnik just FYI this bug is still in migrations:5.2.0, but anyway query fixed the problem.
