### ISSUE TITLE
Reportportal- API and db-scripts unhealthy on linux with mounted windows volumes

### ISSUE THREAD

**Issue by ohank** [reportportal/reportportal#938]
I get this error when I try to start report portal 
![image](https://user-images.githubusercontent.com/44366788/80577997-1da5d480-8a08-11ea-98a3-e968619bfb68.png)

So how do I get more information what is wrong?
If I use local disk on the server it works fine but when I mount a windows disk for just the data I get this error(image above).

here how it looks when it is working on local disk:
![image](https://user-images.githubusercontent.com/44366788/80578227-6d849b80-8a08-11ea-9b06-94f35d4649c1.png)

So the 70 users don't exist in the AD that the windows disk are hosted in. 
Changing  POSTGRES_USER: rpuser to  POSTGRES_USER: root are not working.
Any help are appreciated =)

**Comment by gireinvent** [comment]
![image](https://user-images.githubusercontent.com/33298211/80652185-0df4b300-8a3d-11ea-9b0b-7285882e1052.png)
 i keeping getting this error and the login page does not load.
![image](https://user-images.githubusercontent.com/33298211/80652281-3bd9f780-8a3d-11ea-911e-4f6b7be514dc.png)

**Comment by evjlobanova** [comment]
@pbortnik Could you please take a look?

**Comment by evjlobanova** [comment]
#930

**Comment by ohank** [comment]
Weird that you refer to a issue that i did help solve for someone else. My problem är based on using mounted Windows disk in linux not how to install om Windows.

**Comment by ohank** [comment]
I need a way to get morse information why the script fail. So i can get morse help from People i my organisation. As of now it just say unhelthy. How to get morse error message?

**Comment by gireinvent** [comment]
My issue was resolved after i changed my vloume to - /var/lib/postgresql/data for windows. Can you please the documentation properly. it says uncomment but does not talk of removing '- postgres:' from windows volume.
- postgres:/var/lib/postgresql/data

**Comment by ohank** [comment]
Where can I find the documentation? Does the documentation have a guide if you using a Linux server and mounting a windows volume?

**Comment by ohank** [comment]
How does the Database script look like?
How do I change the DB user?
How do I get more information about the error?
Are unhealthy healthcheck in the docker-compose.yml file?

**Comment by ohank** [comment]
Ok, I solved this by mounting a Linux image that is hosted on the windows disk. So the problem was the Linux user didn't translate over to windows.

**Comment by nandyQA** [comment]
@ohank Do you have documentation for the solution you mentioned above
