### ISSUE TITLE
Unable to raise JIRA defect in RP[v5]

### ISSUE THREAD

**Issue by ghost** [reportportal/reportportal#940]
**Describe the bug**
I'm unable to post a **defect** in Report Portal. whereas I'm able to post a request 

**To Reproduce**
I have added JIRA plugin - plugin-bts-jira-5.1.0-all.jar.
I had done all the required configurations:
![image](https://user-images.githubusercontent.com/50138350/80708073-a7d56200-8b08-11ea-8aaa-a11209c16817.png)

The same configurations when done from the JIRA UI... I'm able to post the defect.
![image](https://user-images.githubusercontent.com/50138350/80709664-495db300-8b0b-11ea-88c4-919bf23d65bb.png)

when i checked the docker logs for container: reportportal/service-api:5.1.0
it says: [com.epam.ta.reportportal.exception.ReportPortalException: Impossible interact with integration. [ErrorCollectionstatus=400, errors=customfield_10111=data was not an object, errorMessages=[]]]

Here: customfield_10111 is the "found in" field.

Question is: why is various field like "found in" mandatory? whereas in my JIRA UI its not mandatory parameter. is there any way to unmandate it ?

**Expected behavior**
A valid Defect should be created.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: RP v5
![image](https://user-images.githubusercontent.com/50138350/80712938-4f09c780-8b10-11ea-937b-73497a13128d.png)

**Comment by deepaleekhare31** [comment]
@evjlobanova Could you please help?

**Comment by deepaleekhare31** [comment]
@HardNorth Could you please help?

**Comment by evjlobanova** [comment]
The issue connected with a custom Jira field "Found in"
Can be connected with https://github.com/reportportal/reportportal/issues/536

**Comment by deepaleekhare31** [comment]
Hello Team,
For the custom Jira field "Found in" to work. I have made the following changes:
In file: https://github.com/reportportal/plugin-bts-jira/blob/develop/src/main/java/com/epam/reportportal/extension/bugtracking/jira/JIRATicketUtils.java
Added the below-highlighted part of the code:
![image](https://user-images.githubusercontent.com/50138350/82194071-e1350c80-9913-11ea-965e-282701986f1e.png)

These changes helped me to raise the defect in RP. 
But I'm still unable to raise the issue types: Campaign, technical task, and backport. They also require custom fields.
Kindly request you to make the changes and release the latest version asap.

**Comment by evjlobanova** [comment]
@pbortnik @Yumfriez could you please check this info

**Comment by deepaleekhare31** [comment]
hello @pbortnik and @Yumfriez 
any updates?

**Comment by Yumfriez** [comment]
@evjlobanova We have to update our JIRA-plugin mappings. Let's create a ticket for this task

**Comment by evjlobanova** [comment]
Added ticket to Jira

**Comment by evjlobanova** [comment]
± December 2021

**Comment by alena-babrova** [comment]
The ticket is closed as there is no way to communicate with the user (the user has been deleted).
See similar ticket for more information: https://github.com/reportportal/reportportal/issues/536
