### ISSUE TITLE
Importing data to ReportPortal

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#941]
Please share a sample zip archive for importing log files . (https://reportportal.io/docs/Import-data-to) My index is not getting generated for auto-analyzer feature. I am suspecting the logs that I am Importing are incorrect.
![image](https://user-images.githubusercontent.com/50797731/80721824-4fa85b00-8b1c-11ea-8464-dcae38ede29c.png)

**Comment by evjlobanova** [comment]
Do your file has error logs?

**Comment by DzmitryHumianiuk** [comment]
@priyankachaturvedi30 
[Launch C.zip](https://github.com/reportportal/reportportal/files/4574067/Launch.C.zip)

**Comment by priyankachaturvedi30** [comment]
Yes, Please have a look at the zip file I am using. 
Also, I get the following analyzer log when I try to generate
![image](https://user-images.githubusercontent.com/50797731/80967753-8213ca00-8e34-11ea-9021-6bcdfc8e8290.png)
[TEST-BDD-features-Approval.feature.zip](https://github.com/reportportal/reportportal/files/4574735/TEST-BDD-features-Approval.feature.zip)

 index after doing manual analysis.

**Comment by DzmitryHumianiuk** [comment]
@priyankachaturvedi30 try to import attached file by me above.

and make sure you made steps from p.3 at https://reportportal.io/docs/Deploy-with-Docker%3Edeploy-reportportal-with-docker

**Comment by priyankachaturvedi30** [comment]
@DzmitryHumianiuk : I imported files provided by you and it got successfully imported. I turned on Auto-analysis from the UI and did manual analysis for a few bugs and then again imported the file shared by you.  It got imported as Launch.C #2. When I tried to Analyse the second launch, it says that the auto-analyzer has started, and the text "auto-analyzer" blinks next to the launch but nothing happens. I want to get the results for the second launch auto-analyzed based on the manual analysis done on the first launch. What am I missing?

**Comment by priyankachaturvedi30** [comment]
> Do your file has error logs?

@evjlobanova : Yes it has. Still, no index got generated when I imported that file. Please have a look at the file if its in the format of what is expected.
[TEST-BDD-features-Approval.feature.zip](https://github.com/reportportal/reportportal/files/4575377/TEST-BDD-features-Approval.feature.zip)

**Comment by DzmitryHumianiuk** [comment]
@priyankachaturvedi30 
1. make sure your elastic service up and running (see in `docker ps`)
2. make sure you use latest RP (v5.1 for now)

Did you analyze failed items in Launch C?
it has only 4 failed test cases with logs. The rest are skipped, with no any logs inside.

**Comment by priyankachaturvedi30** [comment]
@DzmitryHumianiuk  : yes, the failed cases got analyzed
[TEST-BDD-features-Approval.feature.zip](https://github.com/reportportal/reportportal/files/4575642/TEST-BDD-features-Approval.feature.zip)

. :) But Does that mean it would analyze only the failed cases and not the skipped cases? Also, Can you please have a look at my input log file and see why is not been indexed for auto-analysis, even after been imported successfully. Help Much Appreciated !!

**Comment by evjlobanova** [comment]
The analyzer is analyzing and failed and skipped in case skipped items have an error log. In our imported file, skipped items do not have error logs.
Do you manage to analyze your file?

**Comment by priyankachaturvedi30** [comment]
@evjlobanova : yes I did. But I see that only logs get imported. Is there a way through which we can also import some screenshots?

**Comment by DzmitryHumianiuk** [comment]
@priyankachaturvedi30 no import for screenshots.
we assume it for real-time [agents](https://github.com/reportportal?q=agent-&type=&language=)
