### ISSUE TITLE
Permission Issue with elastic search container

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#942]
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.0
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "logger.level=INFO"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    #ports:
      #- "9200:9200"
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
    restart: always

![image](https://user-images.githubusercontent.com/50797731/80844012-4e158a80-8c23-11ea-9198-4802ee13dc72.png)

**Comment by priyankachaturvedi30** [comment]
@evjlobanova @DzmitryHumianiuk Can you please suggest?

**Comment by evjlobanova** [comment]
Do you follow the 3rd step in the manual https://reportportal.io/docs/Deploy-with-Docker%3Edeploy-reportportal-with-docker ?

**Comment by priyankachaturvedi30** [comment]
Yes, Actually I got it fixed. The issue was because of docker access to the directory I was pointing to without mounting. It's working for me now. Thanks!
