### ISSUE TITLE
307 Temporary Redirect Error when hosted in AWS FARGATE ECS

### ISSUE THREAD

**Issue by vishallanke** [reportportal/reportportal#944]
I am able to deploy all the services in AWS ECS containers. Postgres is hosted in AWS RDS. http://13.233.193.52:8082/#login 
Enter user name and password. User will get error as"Network Error".
When I check in Network Tab, I can see that http://13.234.111.98:8080/uat/sso/oauth/token gets called. It is returning "307 Temporary Redirect "

<img width="818" alt="307 Error" src="https://user-images.githubusercontent.com/46259109/80932516-6e894480-8ddd-11ea-9b3c-4c07a35104d0.PNG">

Note - 
For Index service, I was getting error as port 8080 already in use. Therefore, I have changed port of Gateway to 8083. Then, index service gets started

Please find all the settings that I have used as below.

[ReportPortal JSON Settings.txt](https://github.com/reportportal/reportportal/files/4572569/ReportPortal.JSON.Settings.txt)

Adding Snapshot
[307 Redirect Snapshot.docx](https://github.com/reportportal/reportportal/files/4578844/307.Redirect.Snapshot.docx)

**Comment by DzmitryHumianiuk** [comment]
cc @avarabyeu

**Comment by vishallanke** [comment]
Attaching latest logs
[LOGS.zip](https://github.com/reportportal/reportportal/files/4608435/LOGS.zip)
[NETWORK.zip](https://github.com/reportportal/reportportal/files/4608438/NETWORK.zip)
[SNAP.zip](https://github.com/reportportal/reportportal/files/4608439/SNAP.zip)
[JSON.zip](https://github.com/reportportal/reportportal/files/4608440/JSON.zip)

**Comment by vishallanke** [comment]
On EC2 Instance , its working. I have observed that if I enter http://ec2.compute.amazonaws.com:8080, then it opens http://ec2.compute.amazonaws.com:8080/ui/#login. After clicking on Login, I can see http://ec2.compute.amazonaws.com:8080/uat/sso/oauth/token. If I enter , http://ec2.compute.amazonaws.com:8080/uat/sso/oauth/token. , it is asking me to enter credentials. So, it looks OK to me


However on FARGATE ECS ,  I have observed that if I enter http://fargate.compute.amazonaws.com:8080, then it opens http://fargate.compute.amazonaws.com:8080/#login. /ui is not there. After clicking on Login, I can see http://fargate.compute.amazonaws.com:8080/uat/sso/oauth/token,307 Temporary Redirect error. However, UAT is running under different container having different IP Address. So is there  nay issue or any ENV variable required ? If I enter , http://fargate.compute.amazonaws.com:8080/uat/sso/oauth/token, it navigates me to http://fargate.compute.amazonaws.com:8080/#login. This can be the issue in FARGATE.

**Comment by evjlobanova** [comment]
@Cyberglamdring please take a look

**Comment by vishallanke** [comment]
It seems Report Portal is not compatible with ECS yet

**Comment by evjlobanova** [comment]
@viachka Thank you for your request. For now, we do not support AWS FARGATE ECS officially.
So that there should be done some investigations before we can help.

The team takes a look at this issue as soon as it has a capacity.

If this question is crucial for you, and you need our support. We can provide a paid contract. Paid requests are being implemented with the highest priority.

If you are interested in it, please drop us a letter to support@reportportal.io

**Comment by DzmitryHumianiuk** [comment]
@vishallanke ReportPortal of version 5.x compatible with EKS and ECS.
But not yet compatible with Fargate and Fargate ECS due to some specifics of realization.

We do plan to adopt it,
but most likely it will come with version starting 6.x

**Comment by SandeepDawre** [comment]
Hi @DzmitryHumianiuk ,


Hope you are doing well. 

 Just wanted to know,   Is Fargate ECS support enabled for Report-Portal officially  ?

**Comment by DzmitryHumianiuk** [comment]
@SandeepDawre there is no official support of Fargate it RP at the moment.
some users managed to do so, but it was not shared back with the community.

**Comment by SandeepDawre** [comment]
Hi @vishallanke ,

   Hope you are doing well & safe. 
   
   We request you to let us know if you have managed to get it run on ECS .

**Comment by vishallanke** [comment]
Hi @SandeepDawre 
Report Portal is not compatible with ECS. We tried to achieve this but no luck

**Comment by julbrs** [comment]
Hi @vishallanke, have you tried to deploy ReportPortal using CDK or any IAAC system? If yes, is it an option to share your work? Thanks!

**Comment by vishallanke** [comment]
Report Portal is not compatible with ECS. We tried to achieve this but no luck, many errros

**Comment by julbrs** [comment]
Just to add, today there is 14 containers defined in the reference docker-compose.yml. 
If you plan to remove a couple (use RDS for db, ALB instead of gateway, etc...) there is always a hard limit on 10 containers per task on ECS: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-quotas.html

So yes I give up too!

**Comment by DzmitryHumianiuk** [comment]
Hi all,
there is no much practical sense to update versions 5.x to be compatible with ECS and Fargate.
We will consider it for versions 6+

**Comment by Ernodup** [comment]
Much appreciated @DzmitryHumianiuk 
What is the current ETA on V 6.x ?

**Comment by DzmitryHumianiuk** [comment]
@Ernodup early 2023

**Comment by CraigHead** [comment]
This is a bummer. We'll have to pivot away from Report Portal in our solution until ECS is supported. Running 14 containers on an EC2 instances is far and away from industry and AWS best practices and leaves a lot of room for fragility in this design.

**Comment by julbrs** [comment]
Hi @CraigHead 👋

I have been asked to setup ReportPortal in my own service, and we have finally used the Cloudformation template described in this article: https://medium.com/@chhatbarjignesh/deploy-reportportal-in-aws-with-aws-cloudformation-cd6553e27f74

It's far from perfect (as it relies on EC2 instance) but it's working and the data is safely stored in a dedicated RDS and a S3 bucket. Give a try! 🙃

**Comment by DzmitryHumianiuk** [comment]
@CraigHead did it help?

**Comment by pauljflo** [comment]
> Just to add, today there is 14 containers defined in the reference docker-compose.yml. If you plan to remove a couple (use RDS for db, ALB instead of gateway, etc...) there is always a hard limit on 10 containers per task on ECS: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-quotas.html
> 
> So yes I give up too!

You would use an ECS service for each container rather than fitting them all under one. Or group them by function. 
analyzer, analyzer_train & metrics_gatherer in one service/task definition.
uat, index, api, jobs, ui in another service/task definition. 

Minio would be replaced with S3. Postgres would use RDS and RabbitMQ would be AmazonMQ.
Traefik can be replaced directly with either ALB use or AWS AppMesh.

**Comment by DzmitryHumianiuk** [comment]
https://reportportal.io/docs/Deploy-with-AWS

**Comment by Ernodup** [comment]
> https://reportportal.io/docs/Deploy-with-AWS

Has the page been removed again?empty doc

**Comment by DzmitryHumianiuk** [comment]
@Ernodup we are restructuring documentation now.
please use this link for now
https://github.com/reportportal/documentation/blob/90516cc505e5dad00777cbe63c35dfa2f4b48e21/src/md/src/InstallationSteps/DeployReportPortalECSFargate.md

**Comment by Ernodup** [comment]
Many thanks @DzmitryHumianiuk

**Comment by umang4911** [comment]
@Ernodup is this working now?

**Comment by umang4911** [comment]
Hey @DzmitryHumianiuk any updated link for ecs fargate because the link you provided above is not very clear to me or if you could help me with the process please. its urgent

**Comment by DzmitryHumianiuk** [comment]
@umang4911 https://reportportal.io/docs/installation-steps/DeployWithAWSECSFargate

**Comment by DzmitryHumianiuk** [comment]
@umang4911 if you are looking for a dedicated consultancy,
then we can propose a paid services available here: https://reportportal.io/pricing (on-premises).

as for the instruction, it was made by contributor and our team never tested it.
But you can ask the community in slack for the same issues if any.

**Comment by DzmitryHumianiuk** [comment]
### https://reportportal.io/docs/installation-steps/DeployWithAWSECSFargate/
