### ISSUE TITLE
[v5] Linked issue on TI test item causes NonUniqueResultException during test item update.

### ISSUE THREAD

**Issue by blue995** [reportportal/reportportal#946]
**Describe the bug**
If you link the same issue to more than one "To Investigate" test case in the same launch, you can't change the defect category or comment of these test cases afterwards.

This is because in this case the api service tries to find a single test item to change by it's issue ID, but finds more than one entry in the database. The database query causes a NonUniqueResultException, which results in a failing update of the test item.

If you remove the linked issue of the test item you want to change, you're able to change the defect category or comment again.

**To Reproduce**
* Given: Launch with more than one "To Investigate" item
* Given: Configured BTS Integration
* Link the same issue to all "To Investigate" items
* Try to change the comment or defect category of one of the previously changed "To Investigate" items

**Expected behavior**
The test case details (comment, defect category) should change as expected.

**Additional context**
Using API service 5.0.0. Maybe this problem was already fixed in 5.1.0?

**Comment by evjlobanova** [comment]
@svettsova could you please try to reproduce this issue?  And let me know regarding results

**Comment by evjlobanova** [comment]
@blue995 thank you for posting that, we have checked, and let you know regarding our future actions

**Comment by svettsova** [comment]
Issue is fixed in 5.1 version

**Comment by blue995** [comment]
@evjlobanova @svettsova Thanks!
