### ISSUE TITLE
Auto analysis are not handling skipped test[v5]

### ISSUE THREAD

**Issue by ohank** [reportportal/reportportal#952]
**Describe the bug**
Auto analysis are not analyzing skipped tests and change defect type to no defect

**To Reproduce**
Run test that is skipped:
![image](https://user-images.githubusercontent.com/44366788/81273448-2cffd000-904f-11ea-9d60-c0536da137b5.png)

Analyst tests:
![image](https://user-images.githubusercontent.com/44366788/81273504-4143cd00-904f-11ea-9593-89431fd24e41.png)
![image](https://user-images.githubusercontent.com/44366788/81273526-499c0800-904f-11ea-8ecc-9d2c76da5d56.png)

Run test with skipped again:
![image](https://user-images.githubusercontent.com/44366788/81273943-ebbbf000-904f-11ea-817a-15fe2a4311b7.png)

start auto analyst on the test run:
![image](https://user-images.githubusercontent.com/44366788/81273972-f5ddee80-904f-11ea-9fca-d65293f14ea9.png)
![image](https://user-images.githubusercontent.com/44366788/81273991-fd9d9300-904f-11ea-9d92-0bcb1e3e7738.png)

**Expected behavior**
Skipped test moved form to investigate to no defect
![image](https://user-images.githubusercontent.com/44366788/81274140-30e02200-9050-11ea-967c-446418a360f2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Additional context**
Reportportal server hosted on ubuntu 18.
Using pytest and python to run the test.

**Comment by ohank** [comment]
![image](https://user-images.githubusercontent.com/44366788/81285175-6b04f000-905f-11ea-9731-c6ce723bb512.png)
The log of a skipped test

**Comment by DzmitryHumianiuk** [comment]
@ohank it works as designed for `No Defect` type.

Our strict belief that there can be no `no defect` type of issue in the analysis at all.
If you have test skipped or failed, it should have reason for that.

But we added it because of multiply asks.
and kept the logic that `No Defect` can't be migrated into the next execution.

**Comment by ohank** [comment]
Then this are not a bug. But this work in 4.3 so I did think it was intended.
I did find a way to work for my organization by creating a custom defect type.
