### ISSUE TITLE
Minio keeps on restarting 

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#956]
![image](https://user-images.githubusercontent.com/50797731/81402309-c7930880-914e-11ea-80bb-16447e353b80.png)
Attached are the minio logs.

Docker-compose.yml for minio:

minio:
    image: minio/minio:latest
    ports:
      - '9000:9000'
    volumes:
      #- ./data/storage:/data
      - /c/Users/xyz/data/storage:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 120s
      retries: 3
    restart: always

@DzmitryHumianiuk : Can you please help

**Comment by priyankachaturvedi30** [comment]
I see the issue is probably because of the broken build for latest minio release - https://github.com/minio/minio/issues/9555

**Comment by harshavardhana** [comment]
This is because you need O_DIRECT support which is not available unfortunately on Windows docker.

**Comment by nvborisenko** [comment]
Right now I am sitting on Windows, and it's working on my environment:

![image](https://user-images.githubusercontent.com/22616990/81424357-7b4fc480-915e-11ea-9161-7040f0a8f64b.png)

Does it mean we should use specific "old" version of minio to work properly on windows docker?

**Comment by harshavardhana** [comment]
Yes just use the old release, nothing new added for your usecase to upgrade.

**Comment by sudharsan81** [comment]
Thanks HArsha/Nikolay for your advise.

**Comment by sudharsan81** [comment]
It is not a good practise to use `:latest` version. It has to be a specific version. Otherwise it will lead to unmanageable dependency, like this case.

**Comment by priyankachaturvedi30** [comment]
Yes, The problem was because of the latest released version of minion. It worked well after switching to an older version - minio/minio:RELEASE.2020-05-01T22-19-14Z
