### ISSUE TITLE
An error occurred while connecting to server

### ISSUE THREAD

**Issue by ghost** [reportportal/reportportal#957]
Installed Report Portal through docker toolbox and all containers are running, but still unable to login 

![image](https://user-images.githubusercontent.com/35072860/81808707-bcb8e900-953d-11ea-8bfa-44b0ce8e724c.png)

**Comment by e-olga** [comment]
hello @Rathna-Prashanth 
As I see, not all the services are up. 
At the bottom of the page you can see 'Current version' with services. There are four mandatory services should be available: Index service, UI service, API service, Authorization service.
As far as API and Authorization are not running, there is no possibility to login Report Portal.
Please check logs/state of not available services in docker console.

Regards,
Olga

**Comment by eric-stanley** [comment]
Getting the same issue. Docker log details below

`analyzer_1 | 2020-08-12 12:45:11,690 - analyzerApp - INFO - Starting waiting for AMQP connection
analyzer_1 | 2020-08-12 12:45:11,694 - analyzerApp - INFO - Try connect to amqp://rabbitmq:5672/analyzer?heartbeat=600
rabbitmq_1 | 2020-08-12 12:45:12.651 [info] <0.820.0> accepting AMQP connection <0.820.0> (172.24.0.10:57800 -> 172.24.0.2:5672)
analyzer_1 | 2020-08-12 12:45:12,795 - analyzerApp - ERROR - Amqp connection was not established
analyzer_1 | 2020-08-12 12:45:12,796 - analyzerApp - ERROR - (530, 'NOT_ALLOWED - vhost analyzer not found')
rabbitmq_1 | 2020-08-12 12:45:12.767 [error] <0.817.0> Error on AMQP connection <0.817.0> (172.24.0.10:57798 -> 172.24.0.2:5672, user: 'rabbitmq', state: opening):
rabbitmq_1 | vhost analyzer not found
rabbitmq_1 | 2020-08-12 12:45:12.806 [info] <0.823.0> closing AMQP connection <0.823.0> (172.24.0.10:57802 -> 172.24.0.2:5672, vhost: 'none', user: 'rabbitmq')`

Issue occurs in MAC, but works fine in Linux

**Comment by EasyAutomate** [comment]
<img width="1604" alt="Screenshot 2021-04-01 at 9 12 58 AM" src="https://user-images.githubusercontent.com/15063558/113240533-8a85b680-92ca-11eb-9fd2-f94733d2315b.png">
<img width="1455" alt="Screenshot 2021-04-01 at 9 12 15 AM" src="https://user-images.githubusercontent.com/15063558/113240545-8eb1d400-92ca-11eb-94d3-c67f31a68e95.png">
Facing the similar issue in MAC

**Comment by Faisal3693** [comment]
Can Anyone please assist, I am too facing a similar issue in Mac. 
![image](https://user-images.githubusercontent.com/69522327/116041883-69c33d80-a68b-11eb-93d7-3dc9bd88944c.png)

**Comment by evjlobanova** [comment]
@Cyberglamdring please check

**Comment by dhamo-pk** [comment]
I am facing same issue, adding extra stack trace to the thread FYR

`analyzer_train_1  | Mon Aug  2 18:12:51 2021 - *** uWSGI listen queue of socket ":3031" (fd: 6) full !!! (76809840/64) ***
analyzer_1        | 2021-08-02 18:12:51,438 - analyzerApp.amqp - INFO - Try connect to amqp://rabbitmq:5672/analyzer?heartbeat=600
rabbitmq_1        | 2021-08-02 18:12:50.773 [info] <0.3406.0> accepting AMQP connection <0.3406.0> (172.18.0.11:55326 -> 172.18.0.6:5672)
rabbitmq_1        | 2021-08-02 18:12:51.454 [info] <0.3409.0> accepting AMQP connection <0.3409.0> (172.18.0.11:55328 -> 172.18.0.6:5672)
rabbitmq_1        | 2021-08-02 18:12:51.479 [error] <0.3406.0> Error on AMQP connection <0.3406.0> (172.18.0.11:55326 -> 172.18.0.6:5672, user: 'rabbitmq', state: opening):
rabbitmq_1        | vhost analyzer not found`

**Comment by Cyberglamdring** [comment]
@dhamo-pk, Analyzer can't connect to RabbitMQ. Check URL, User and password [here](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L60) and [here](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L144). Also, all services must be on the same docker network, that helps containers see each other by name.

@lehoanglu0ng, @Faisal3693 for the delayed response. I recommend you update RP to a new version and if you are faced with this issue again, attach Autorisation and API logs. On the main page in "Current version" you should see all services except Analyzer

**Comment by lehoanglu0ng** [comment]
hi @Cyberglamdring 
![Screen Shot 2021-08-08 at 18 29 43](https://user-images.githubusercontent.com/22902128/128630503-300c1ee9-0499-471f-8556-4b935181adb4.png)
The `api` and `uat` keep restarting with the messages: `start.sh: applet not found`

**Comment by eddylee-nsuslab** [comment]
@Cyberglamdring 
On my M1 Mac Mini with Rosetta installed, this is still happening. I want to use Reportportal quickly. please help me. :sob:

![image](https://user-images.githubusercontent.com/89089694/141529052-a4843150-123b-4fd2-9539-b1f1b37b7202.png)

**Comment by Ernodup** [comment]
This is still an ongoing problem @Cyberglamdring @evjlobanova , has anyone been able to find a workaround?

**Comment by Cyberglamdring** [comment]
> This is still an ongoing problem @Cyberglamdring @evjlobanova , has anyone been able to find a workaround?

Currently RP does't support M1, we are working on this issue.

**Comment by alizaidi96** [comment]
@Gl-Canon Is the support for Apple M1 chips up now? It's been a while since you mentioned that you are working on the issue!

**Comment by manojguptavonage** [comment]
I am also facing the same issue currently on Mac M1. Any update by when this issue would be resolved?

**Comment by swtestacademy** [comment]
I am also facing the same issue currently on Mac M1. Any update on when this issue will be resolved?

**Comment by alena-babrova** [comment]
Hello all,
Please follow up M1/ARM related discussion in https://github.com/reportportal/reportportal/issues/1815.
I'm closing the issue as duplicate.
