### ISSUE TITLE
[WIDGETS] The most time-consuming tests

### ISSUE THREAD

**Issue by Andrey-Cherepakha** [reportportal/reportportal#96]
Add a widget to show the most time-consuming tests (top 10 / 20 / 50 / 100) within a launch. Just simply order all test within a launhc by execution time in order to find  the longest ones.

**Comment by e-olga** [comment]
Added to RP backlog

**Comment by DzmitryHumianiuk** [comment]
sub-launch view.
`most time-consuming` widget
