### ISSUE TITLE
Cannot log in to fresh report portal

### ISSUE THREAD

**Issue by marek2209** [reportportal/reportportal#960]
Hi.

I want to setup fresh production reportportal on two separate host as documentation described. 
I already installed postgresql on second host and i modified everything in docker-compose file.
Unfortunetaly i am still not able to log in.

![image](https://user-images.githubusercontent.com/9087374/81555998-dd404200-9389-11ea-8632-063bb2b36757.png)

![image](https://user-images.githubusercontent.com/9087374/81691641-712f0e00-945d-11ea-95c5-653f6279b98c.png)

this is from my docker compose ( i use latest version of file but i just reconfigured values for my postgresql instance)

![image](https://user-images.githubusercontent.com/9087374/81556718-162ce680-938b-11ea-99bf-8108e42ae0c4.png)

![image](https://user-images.githubusercontent.com/9087374/81556515-b8000380-938a-11ea-863a-921e475d6475.png)

![image](https://user-images.githubusercontent.com/9087374/81556570-d82fc280-938a-11ea-95ae-ebe4f078a6b7.png)

As far as i check container logs it looks like db is not iinitalized. 

/service-authorization:5.1.0 
![image](https://user-images.githubusercontent.com/9087374/81667606-c5c58f80-9443-11ea-8bf2-d6332b74f35a.png)

reportportal/service-api:5.1.1 

![image](https://user-images.githubusercontent.com/9087374/81669108-fc040e80-9445-11ea-9061-df0118e825ca.png)

reportportal/migrations:5.1.0 
![image](https://user-images.githubusercontent.com/9087374/81670340-bfd1ad80-9447-11ea-964d-abf35ffaedcb.png)

**Comment by marek2209** [comment]
![image](https://user-images.githubusercontent.com/9087374/81667606-c5c58f80-9443-11ea-8bf2-d6332b74f35a.png)

**Comment by marek2209** [comment]
reportportal/service-api:5.1.1 

![image](https://user-images.githubusercontent.com/9087374/81669108-fc040e80-9445-11ea-9061-df0118e825ca.png)

**Comment by pbortnik** [comment]
Can you share the logs of 'db-scripts' container. It have to be in stopped containers.
To check all containers (running + stopped) use the next command:
`docker ps -a`

**Comment by marek2209** [comment]
> Can you share the logs of 'db-scripts' container? The container have to be in the list of stopped.
> To find all containers (running + stopped) use the next command:
> `docker ps -a`

![image](https://user-images.githubusercontent.com/9087374/81685968-940af380-9458-11ea-8b9d-4ac7bb6884bd.png)

log 
 reportportal/migrations:5.1.0  is the db scripts
![image](https://user-images.githubusercontent.com/9087374/81686092-a5540000-9458-11ea-8bf2-63e0fade2d5c.png)

**Comment by marek2209** [comment]
Ok i resolved issue. 

I just removed migrations and db-scripts section from docker-compose and i runned all of DB 
https://github.com/reportportal/migrations/tree/develop/migrations scripts manually on my DB instance.
