### ISSUE TITLE
[v5] IOException in service-api

### ISSUE THREAD

**Issue by ShashidharSM** [reportportal/reportportal#961]
**Describe the bug**
ReportPortal doesn't allow users to login, and is extremely slow after restarting the docker containers. The service-api container has several IOExceptions ("No file descriptor available")

**To Reproduce**
This is on a production setup: Postgres is running on a separate server, and reportportal containers have a server to themselves. (All m5.large servers). 

We have around 45 testers running their tests from a selenium webdriver test framework, and the issue starts showing up within 20 hours of starting the RP docker containers; it becomes very slow, and then it refuses to open up the login page. 

**Expected behavior**
RP should not become slow and refuse to show up the login page. 

**Screenshots**
Exceptions: 
![IOException_ReportPortal](https://user-images.githubusercontent.com/4965520/81569825-c7248880-936d-11ea-8269-bd13f6028f47.jpg)

**HOST Machine**
 - OS: RHEL

**Desktop (please complete the following information)/HOST Machine**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  80

**Comment by DzmitryHumianiuk** [comment]
@ShashidharSM what's the `service-api` version and `minio` version?

**Comment by ShashidharSM** [comment]
> @ShashidharSM what's the `service-api` version and `minio` version?

service-api is at 5.0.0 and we are using filesystem for storage and not minio. 

![RP_Containers](https://user-images.githubusercontent.com/4965520/81574685-21284c80-9374-11ea-9b19-3e715e8c976e.jpg)

**Comment by DzmitryHumianiuk** [comment]
@ShashidharSM we recommend update to version 5.1 or even 5.2-rc at this point.

the error which is dropped by API is the related to the number of open files by File System.
In your case, you have quite loaded instance, which means that this limit should be extended.

Default docker compose goes for default configuration, which can fit majority of configurations.

https://unix.stackexchange.com/questions/84227/limits-on-the-number-of-file-descriptors

**Comment by ShashidharSM** [comment]
> @ShashidharSM we recommend update to version 5.1 or even 5.2-rc at this point.
> 
> the error which is dropped by API is the related to the number of open files by File System.
> In your case, you have quite loaded instance, which means that this limit should be extended.
> 
> Default docker compose goes for default configuration, which can fit majority of configurations.
> 
> https://unix.stackexchange.com/questions/84227/limits-on-the-number-of-file-descriptors

@DzmitryHumianiuk Thanks! We will explore your suggestions to extend limits. And could you explain why you recommend updating to 5.1 - would that help us with this issue?

**Comment by DzmitryHumianiuk** [comment]
@ShashidharSM 5.1 has dozens of performance fixes and optimizations, found in real-life adoption of 5.0.0 on project with high scale.

**Comment by ShashidharSM** [comment]
Thanks, @DzmitryHumianiuk - could you please share a link to release notes for version 5.1? I couldn't find it anywhere.

**Comment by DzmitryHumianiuk** [comment]
@ShashidharSM https://github.com/reportportal/reportportal/releases/tag/5.1.0

**Comment by evjlobanova** [comment]
@ShashidharSM has it helped?

**Comment by evjlobanova** [comment]
Closed due to no answer, please reopen it, if it is still actual for you
