### ISSUE TITLE
Failure migrate reportportal with 4.3 to 5.0

### ISSUE THREAD

**Issue by hasket** [reportportal/reportportal#964]
Hi, I migrate the reportport from version 4.3 to 5.0, acted on the migration instructions taken from your github repository, with the problem of connecting to Mongodb.
I enclose a log and a migration file.
Moreover, the reportport 4.3 rises without errors.
Please, help.

[out_error.log](https://github.com/reportportal/reportportal/files/4616661/out_error.log)
[migrate_yml.txt](https://github.com/reportportal/reportportal/files/4616673/migrate_yml.txt)

**Comment by pbortnik** [comment]
Hi, as you are running all of the containers in one network (root), you cane provide the services names (mongodb, postgres, minio) in docker-compose file instead of 'localhost'.
Docker cannot connect from inside the container to local machine.
