### ISSUE TITLE
Getting "java.net.UnknownHostException: postgres" after running reportportal-api container

### ISSUE THREAD

**Issue by ishannavgire** [reportportal/reportportal#971]
**Description:** When i up the application via docker-compose, all of the containers start running expect the "äpi" container because it is dependent on "rabbitMQ", "postgres" & "gateway". After some time I get error :
ERROR: for api  Container "xxxxx_container_id_xxx" is unhealthy.
ERROR: Encountered errors while bringing up the project.

Then I wait for all containers to be in "healthy" state & manually up "reportportal api container".
Upon running "api" container, I face "java.net.UnknownHostException: postgres".

**System details:**
1. Windows 10 Home 64 bit (RAM 12 GB, core-i3)
2. DockerToolbox v19.03.1
3. Oracle VM VirtualBox v 6.1.6 r137129 (Qt5.6.2)

![All-containers-up-expect-api](https://user-images.githubusercontent.com/34616452/82196526-6ff75880-9917-11ea-9e95-14a63e5df6ea.png)
[Error_logs_Docker-Quickstart-terminal.txt](https://github.com/reportportal/reportportal/files/4643191/Error_logs_Docker-Quickstart-terminal.txt)
![Failed-to-run-api-container](https://user-images.githubusercontent.com/34616452/82196532-7259b280-9917-11ea-83e0-282883b5d598.png)
![RabbitMQ-posgres-gateway-container-state-before-running-api-container](https://user-images.githubusercontent.com/34616452/82196536-738adf80-9917-11ea-99f2-47bcf1f0f518.png)

Please find attached error screenshots & other details.

How can I resolve this issue.

**Comment by pbortnik** [comment]
Hi, have you modified a docker-compose.yml according to the recommendations for Windows systems?

**Comment by pbortnik** [comment]
@ishannavgire

**Comment by evjlobanova** [comment]
Closed due to no answer, 
please reopen if it is still actual
