### ISSUE TITLE
Config always reset every Day [v5]

### ISSUE THREAD

**Issue by ariel411** [reportportal/reportportal#972]
**Describe the bug**
After to configure a new project into https://github.com/reportportal/reportportal
all the launches, filters, are removed on a day even the API token is not the same.
Using GitHub account as Login

**To Reproduce**
Create a new launch and filter
Login the next day

**Expected behavior**
all changes and configurations into account even the API token should not be changed

**Additional context**
Note: Is this expected to does not keep the changes into https://github.com/reportportal/reportportal?

**Comment by DzmitryHumianiuk** [comment]
@ariel411 data should stay in the, until you delete it.

Reasons of data upsent can be:
- restarting container with database
- restarting pod with db

who do you install RP?

**Comment by ariel411** [comment]
I have been used this link:
https://web.demo.reportportal.io/ui/#login

Using GitHubAccount

![image](https://user-images.githubusercontent.com/61328207/82224702-2ea08200-98f2-11ea-843e-3121f8ced6b0.png)

**Comment by DzmitryHumianiuk** [comment]
@ariel411 it is Demo instance.
it does reset data every 12 hours.
