### ISSUE TITLE
No result when i click test case name

### ISSUE THREAD

**Issue by TestMyCode12345** [reportportal/reportportal#973]
![image](https://user-images.githubusercontent.com/65267827/82271143-9909fe80-9994-11ea-9240-11ec7a5afdb0.png)

I am able to launch report portal.
I can see test suite return SUCCESS with 1 test case.

But when I click test case name in report portal , it return new page with no result. and also there is no count for total, passed.

Please advice.

https://github.com/reportportal/example-java-TestNG/issues/26 - This issue I created for test_case_hash column not exist. 

Followed the instruction in below link for installation as wel project.
https://github.com/reportportal/example-java-TestNG
https://github.com/reportportal/shell-installation

Followed the instruction in below link for installation as wel project.
https://github.com/reportportal/example-java-TestNG
https://github.com/reportportal/shell-installation

**Comment by DzmitryHumianiuk** [comment]
@TestMyCode12345 looks like your are missing db_scripts, which should update tables in DB.

i guess, shell-installation missing it for now.
@pbortnik can suggest here.

**Comment by TestMyCode12345** [comment]
@pbortnik As reportportal throws the error "test_case_hash column does not exist", I have added this column in postresql with varchar(1024) datatype. Once I altered the table , I did not see the error in reportportal page after executing testsuite.xml in eclipse.

But I could not see Total count and other info in Launch page.

![image](https://user-images.githubusercontent.com/65267827/82320835-88d43c80-99f1-11ea-86aa-c1cb88545be8.png)


![image](https://user-images.githubusercontent.com/65267827/82320702-54608080-99f1-11ea-8e53-17500056bb39.png)


I dont have idea where to start and how to solve this issue. Please let me  know if you need any info to debug.

**Comment by TestMyCode12345** [comment]
> @TestMyCode12345 looks like your are missing db_scripts, which should update tables in DB.
> i guess, shell-installation missing it for now.
> @pbortnik can suggest here.

But I executed download-services.sh and start_rp.sh in aws instance from below link.
https://github.com/reportportal/shell-installation

Made below changes as I was getting error on launching reportportal page itself.

1. Created ltree extension in postresql
2. Traefik.toml - changed port no from 8080 as shown below

![image](https://user-images.githubusercontent.com/65267827/82322067-81159780-99f3-11ea-8447-e4bc0c086b7c.png)

3. Added test_case_hash column in test_item table.

**Comment by Yumfriez** [comment]
https://github.com/reportportal/reportportal/issues/1016

We have to update `shell-installation` repository

**Comment by evjlobanova** [comment]
Added ticket to Jira

**Comment by evjlobanova** [comment]
Will be fixed together with 
https://github.com/reportportal/reportportal/issues/1150
https://github.com/reportportal/reportportal/issues/1016

**Comment by bzsharm** [comment]
> Will be fixed together with
> #1150
> #1016

Do we have any ETA for that @evjlobanova . 

Thanks 😊

**Comment by bzsharm** [comment]
Hi Guys, any update on this issue! is the installation document up to date @evjlobanova @Yumfriez, we are planning to deploy the report portal in a large scale! we have to make sure it'll work beforehand!
