### ISSUE TITLE
Can we import a Junit result file , which is an .xml in to the report portal ?

### ISSUE THREAD

**Issue by bzsharm** [reportportal/reportportal#974]
Can we import a Junit result file in to the report portal ?. (its an XML file )

If Yes , could you guys help me or advise me how to get it done .

An abinitio application (business intelligence) creates(its not a Junit Framework)

 this "junit result xml file", so we dont have an option to integrate report portal with this business intelligence tool as per the documentation which i saw in reportportal.io

Thanks in advance guys, have attached a sample junit result file which i found in the internet . (converted that to .txt format, please change it to .xml)
[sample-junit.txt](https://github.com/reportportal/reportportal/files/4648781/sample-junit.txt)

**Comment by HardNorth** [comment]
Have you tried to use search through our documentation?
https://reportportal.io/docs/Import-data-to

**Comment by DzmitryHumianiuk** [comment]
@bzsharm there is another option: implement parser, which will read you results file and sent it to API.
Here are detailed devguide of reporting steps: https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md

So a parser can be implemented, which will trigger reporting events according to data structure.

P.S.
if your company is looking for options with help in adoption, we can provide it.

**Comment by Nayana-BM** [comment]
@DzmitryHumianiuk Can I get a detailed sample xml file for reference. 
I am trying to generate a xml file to import from the UI and I want to add launch and test attributes.

**Comment by DzmitryHumianiuk** [comment]
@Nayana-BM 
[Full Regression Suite.zip](https://github.com/reportportal/reportportal/files/12922791/Full.Regression.Suite.zip)

**Comment by Nayana-BM** [comment]
@DzmitryHumianiuk Do you have example with more properties and attributes defined ?
This sample seems to be very simple one.

**Comment by DzmitryHumianiuk** [comment]
@Nayana-BM 
In attributes in ReportPortal might be added on the level of `launch` and `testItem` objects.
**For the launch:** 
https://reportportal.io/docs/log-data-in-reportportal/ImportDataToReportPortal/#import-via-api

**for the TestItems:**
the import parser doesn't support any additional attributes added into the xml files yet.
but you are free to contribute into this code base.
