### ISSUE TITLE
[v5] Auto Analysis - Not working if logged via log4j2

### ISSUE THREAD

**Issue by narmadha956** [reportportal/reportportal#976]
**Describe the bug**
Auto analysis's "Change Similar Items" feature not working if logged via log4j

**To Reproduce**
1. Log two failures via explicit report portal logging -> ReportPortal.emitlog. Edit Defect - Under "Change Similar Items", both the logs will be seen. 
2. Log two failures via log4j2 to Report Portal ->Log.error() . Edit Defect - Under "Change Similar Items",  **BOTH LOGS NOT SEEN**. Auto analysis unable to identify or is not working if logged via log4j.

**Expected behavior**
If logged via log4j2 auto analysis not recognising similar failures. Hence, auto analysis not working completely if logged via Log4j2.

**Additional context**
It is easily reproducable, let me know if logs or screenshot is required.

**Comment by DzmitryHumianiuk** [comment]
@narmadha956 please share version of RP and screenshots how you see these logs in RP UI.

There are some simple rules:
- categorization and analysis can be applied to test cases only (`type=step` for api)
- logs should be the logs of test case
- logs should be ERROR level

**Comment by narmadha956** [comment]
Thanks for such a quick response. 

**Version :** Current version:API Service: 5.1.0;Index Service: 5.0.7;Authorization Service: 5.1.0;Service UI: 5.1.0;

Same has been working until I integrated with Log4j. 

I have 400 such failures, auto analysis was working perfectly. But once I added used log4j, this stopped working. 

<img width="1680" alt="Test2" src="https://user-images.githubusercontent.com/50320283/82352077-1bd59c80-9a1b-11ea-97ee-11ebe2a12209.png">
<img width="1680" alt="Test1" src="https://user-images.githubusercontent.com/50320283/82352081-1d9f6000-9a1b-11ea-9c4a-b3212cbb08a4.png">
<img width="1680" alt="NotRecogInAutoAnalysis" src="https://user-images.githubusercontent.com/50320283/82352148-327bf380-9a1b-11ea-92db-d7248511a56b.png">

I am now also seeing for some failures logged via ReportPortal.emitLog also auto analysis hasn't worked. I have 14 defect types and only one of them have been marked by auto-analysis, others haven't. 

Is there any limit on the test cases auto analysis can work on ? I have above 30k results.

**Comment by narmadha956** [comment]
Also, now ReportPortal.emitLog("message", "INFO", date, new File("filePath")) only posts log message without attaching file. This was working two days back.
Does Report portal have any space limit ? Is there an API which I can use to check ?

**Comment by DzmitryHumianiuk** [comment]
@narmadha956 there is no any limits in API side.

The only reason of that can be the system level limitations.
Like number of open files, specifics of database configuration, etc.


There is no silver-bullet answer for your questions.
Since described issues are quite unique and we didn't receive something similar from users.
Usually it means that something misconfigured or limited at infrastructure level (OS, hardware, docker process, etc.)

**Comment by DzmitryHumianiuk** [comment]
@narmadha956 
also you didn't mention, what was the previous source of logs, which generated this failed item.

**Comment by narmadha956** [comment]
@DzmitryHumianiuk Used ReportPotal.emitLog only. After freeing up memory and upgrading report portal to latest version, attachment and auto-analysis are working. So I guess you are right.
 
Closing the issue. Thanks.

**Comment by DzmitryHumianiuk** [comment]
@narmadha956 that is it )

To sum-up:
1. Check your `ulimit` param for *unix based OS. Which limits number of simultaneously open files in system, which affect database and as a result affects number of open session/threads to report results  (https://linuxhint.com/linux_ulimit_command/)

2. Check the memory limit for docker process itself, which can cut volume of available system resources for the running process in docker container (RP server app itself).
