### ISSUE TITLE
[v5] Unable to send log to RP using API.

### ISSUE THREAD

**Issue by AutomateItEasyWay** [reportportal/reportportal#977]
I am trying to send log to RP using log API. http://endpoint:8080/api/v1/superadmin_personal/log. I have set the authorization header and executed another get request to ensure that endpoint and bearer token information is accurate.

When executing POST request for sending log I have added json_request_part and file. Doubled checked that file name in json_request_part and file is same. But I still get error code 4001 for missing json_request_part. Below is the screenshot from postman 

Here is the value of json_request_part

{
	"file": {
		"name": "Screenshot1.png"
	},
	"item_id": "",
	"level": "INFO",
	"message": "API Screenshot",
	"time": "2020-05-20T13:35:55.006Z"
}

Also tried with item id as 1 with same outcome.

{
	"file": {
		"name": "Screenshot1.png"
	},
	"item_id": "1",
	"level": "INFO",
	"message": "API Screenshot",
	"time": "2020-05-20T13:35:55.006Z"
}

Expected behavior: Log should be sent along with an attachment to RP.

Versions:
OS: Windows 10
Tool: Postman
RP: API Service: 5.0.0; Index Service: 5.0.5; Authorization Service: 5.0.0; Service UI: 5.0.0

Screenshot:

![image](https://user-images.githubusercontent.com/32865864/82491438-a5847900-9ab2-11ea-8e87-63fd3efa8316.png)

**Comment by mnicula** [comment]
According to this [comment](https://github.com/reportportal/reportportal/issues/621#issuecomment-492666788) json_request_part should also be a file

**Comment by priyankachaturvedi30** [comment]
@mnicula , I am also facing the issue while uploading logs via api but i m getting unauthorized error.
![image](https://user-images.githubusercontent.com/50797731/82810309-b9155280-9eab-11ea-94a2-75db6cb0cc4d.png)


Can you help me with the Authorization types that i need to provide

**Comment by mnicula** [comment]
@priyankachaturvedi30 
please see the dev guide https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md

**Comment by evjlobanova** [comment]
POST {{url}}/{{project}}/log
{
  "launchUuid": "{{current_launch_uuid}}",
  "itemUuid": "{{current_step1_uuid}}",
  "level": "error",
  "message": "log text)",
  "time": "{{date}}"
}

**Comment by evjlobanova** [comment]
Please reopen this issue if you still have problems?
