### ISSUE TITLE
Show tags in the order they were added to the launch/suite/test

### ISSUE THREAD

**Issue by lifemanship** [reportportal/reportportal#98]
I saw through the code in the file: service-ui\src\main\resources\public\js\src\launch\launch-grid.js
and found function tagSorter:
```
tagSorter: function (tags) {
                    return _.sortBy(tags, function (t) {
                        return t.toUpperCase() === 'BUILD' || t.indexOf('uild') !== -1;
                    });
                },
```
It looks like UI changes the **TAGS** order. May be you can add toggle button like: **SORT TAGS**.

**Comment by avarabyeu** [comment]
@lifemanship Putting 'build' tag at the first place of the list was proposed by some of our client and considered as useful improvement. @lexecon The question here: does existing code keep initial order of other (not the 'build') tags?

**Comment by lifemanship** [comment]
I forgot to propose an example:
Our tests have tags like these:
OS, Bitness, Browser, BuildNumber, and so on

In such order it is easy to see which platform/browser were used during tests run

**Comment by DzmitryHumianiuk** [comment]
@lifemanship 
so what is idea?
add customization, to be able to change ordering of tags for particular launch?
so like, for the next execution it will keep the same order?

Practilcally, it will bring a lot of implementation and effort, but will not give much of benefits.

I would suggest you to follow the concept like add name of tag as prefix to tag.
e.g. `OS:win`, `OS:mac`, `OS:lnx`, `BUILD:3.0`, `BUILD:3.0.1105`, `BROWSER:ff43`
this will help you to identify them easy.

And,
if you will keep sending tags with the same sorting via the parameters (`rp.tags=`), they will be saved with the same order as received,
