### ISSUE TITLE
reportportal_db-scripts_1 reportportal/migration:5.2.0 keeps restarting

### ISSUE THREAD

**Issue by krishnakirankambhampatypoq** [reportportal/reportportal#984]
I am new to report portal and I am using a Mac book . Though the portal launches , I can't sign in . Noticed that the reportportal_db-scripts_1 reportportal/migration:5.2.0 keeps restarting

Logs: 
wait-for-it.sh: waiting 15 seconds for postgres:5432
wait-for-it.sh: postgres:5432 is available after 0 seconds
error: pq: no pg_hba.conf entry for host "x.x.x.x", user "rpuser", database "reportportal", SSL off

Please can anyone guide me ?

**Comment by krishnakirankambhampatypoq** [comment]
Now it says 

```
wait-for-it.sh: postgres:5432 is available after 0 seconds
error: pq: database "reportportal" does not exist
```

**Comment by krishnakirankambhampatypoq** [comment]
Working fine now on deleting the data folder

**Comment by swtestacademy** [comment]
I am having the same issue on M1 Pro machine. The default docker-compose file is not working fine and creating this exact problem.

**Comment by swtestacademy** [comment]
> Working fine now on deleting the data folder

This trick worked. Thanks @krishnakirankambhampatypoq

**Comment by swtestacademy** [comment]
The problem again started even after deleting the data folder and reinstalling the reportportal.
