### ISSUE TITLE
Issue with sending large logs (content-type issue)

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [reportportal/reportportal#985]
@DzmitryHumianiuk We found a solution, but we are not sure it this is a bug, it isn't perfect and we would like to stick mostly to documentation. So...
according to [documentation](https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#batch-save-logs) 
```
curl --header "Content-Type: application/json" \
     --header "Authorization: Bearer 039eda00-b397-4a6b-bab1-b1a9a90376d1" \
     --request POST \
     --form '[{"itemUuid":"9c7632a2-272e-4c24-9627-d7d509de7620","launchUuid":"96d1bc02-6a3f-451e-b706-719149d51ce4","time":"2019-11-06T15:50:53.187Z","message":"Some critical exception","level":40000,"file":{"name":"file1.pdf"}},{"itemUuid":"16fb3d7f-ddce-407a-8e52-464a596e6da1","launchUuid":"96d1bc02-6a3f-451e-b706-719149d51ce4","time":"2019-11-06T15:50:53.187Z","message":"java.lang.NullPointerException","level":40000,"file":{"name":"file2.txt"}}]' \
     --form "file=@/path/to/file1.pdf" \
     --form "file=@/path/to/file2.txt" \
     http://rp.com/api/v1/rp_project/log
```

We got problem to send this request with `--header "Content-Type: application/json"` it was sendable only when `Content-Type: multipart/form-data`
Every `--form` attribute need to have at the end `;type=...` without that we got problem to send bigger logs. 
We couldn't send json as a string in request but we put it in a file and then send it.
our example of working request:
```
curl --header "Content-Type: multipart/form-data" \
                    --header "Authorization: Bearer ${RP_API_TOKEN}" \
                    --request POST \
                    --form "json_request_part=@${TMP_FILENAME};type=application/json" \
                    --form "file=@${LOGFILE_FULL_FILENAME};type=text/plain" \
                    ${REPORT_PORTAL_URL}/api/v1/${REPORT_PORTAL_PROJECT}/log)
```

Please send me back if you have similar problems. 
How we can send json as a string in request?

_Originally posted by @edyp in https://github.com/reportportal/reportportal/issues/561#issuecomment-635348580_

**Comment by DzmitryHumianiuk** [comment]
@edyp moved to a separate issue.
will be taken by team in next sprints.

**Comment by Yumfriez** [comment]
@edyp There is a modified script with test data and image (mine was almost 20mb so I can't attach it here, try your own):
`curl --header "Content-Type: multipart/form-data" \
     --header "Authorization: Bearer YOUR_TOKEN" \
     -X 'POST' \
     -F 'json_request_part=[{"launchUuid":"d64bc313-ee55-4177-a31e-45047bca2982","time":"2021-11-06T15:50:53.187Z","message":"Some critical exception","level":40000,"file":{"name":"file1.pdf"}},{"launchUuid":"d64bc313-ee55-4177-a31e-45047bca2982","time":"2021-11-06T15:50:53.187Z","message":"java.lang.NullPointerException","level":40000,"file":{"name":"large.jpg"}}];type=application/json' \
     --form "file=@/path/to/file/file1.pdf" \
     --form "file=@/path/to/file/large.jpg" \
     https://alpha.reportportal.io/api/v1/superadmin_personal/log`

**Comment by DzmitryHumianiuk** [comment]
@edyp does it help?

**Comment by edyp** [comment]
At the beginning sorry for late response but job responsibilities keeping me busy these days. 
I understand that new version was release and I can update my RP instance then check if fixup works?

**Comment by evjlobanova** [comment]
You can try fix even with upgrading new version

**Comment by evjlobanova** [comment]
@edyp Any updates?

**Comment by evjlobanova** [comment]
@edyp ^^

**Comment by edyp** [comment]
Sorry for late response, all right. Issue fixed.
