### ISSUE TITLE
Error during execute Report tool Windows Server 2016 [v5]

### ISSUE THREAD

**Issue by ariel411** [reportportal/reportportal#989]
Hello, I need help please, I'm trying to install Report Portal into Windows Server 2013
After to execute :
        docker-compose -p reportportal up -d 
Display the next, Error:

![image](https://user-images.githubusercontent.com/61328207/83451548-2b92af00-a425-11ea-8f7b-da0e468ff2c7.png)

**Additional context**
Docker tools , have been working as expected,
Is this tool could work on Windows Server 2016?

**Comment by nvborisenko** [comment]
@ariel411 switch docker to use linux containers instead of windows.

**Comment by DzmitryHumianiuk** [comment]
@ariel411 Docker still have not full support on Windows.
Thus we don't test it on windows,
thus we don't recommend to run it on windows.

Please deploy it on linux eviroment.
