### ISSUE TITLE
Is it possible to create filter(not shared) for specified user by admin with using rest api?

### ISSUE THREAD

**Issue by lifemanship** [reportportal/reportportal#99]
I want to automate the procedure of creating user through **REST API.**
1) create user
2) assign to the specified(shared) project
3) add some filters

**Comment by DzmitryHumianiuk** [comment]
![image](https://cloud.githubusercontent.com/assets/11332788/24801541/4fd6bbe4-1bad-11e7-8231-ff73312029b8.png)
`http://YOUR_INSTANCE:PORT/ui/swagger-ui.html`
1. create user
`http://YOUR_INSTANCE:PORT/ui/swagger-ui.html#!/user-controller/createUserByAdminUsingPOST`
![image](https://cloud.githubusercontent.com/assets/11332788/24801636/b147bdce-1bad-11e7-894a-06e84e2b33ff.png)

```json
{
  "accountRole": "USER",
  "default_project": "string",
  "email": "string",
  "full_name": "string",
  "login": "string",
  "password": "string",
  "projectRole": "CUSTOMER"
}
```

2. if you need assigment only to one project, you can make it previous request
3. create filter
`http://YOUR_INSTANCE:PORT/ui/swagger-ui.html#!/user-filter-controller`
![image](https://cloud.githubusercontent.com/assets/11332788/24801666/e33793ae-1bad-11e7-9b8d-380042c28995.png)

```json
{
  "elements": [
    {
      "description": "string",
      "entities": [
        {
          "condition": "string",
          "filtering_field": "string",
          "is_negative": true,
          "value": "string"
        }
      ],
      "is_link": true,
      "name": "string",
      "selection_parameters": {
        "is_asc": true,
        "page_number": 0,
        "sorting_column": "string"
      },
      "share": true,
      "type": "launch"
    }
  ]
}
```

**Comment by lifemanship** [comment]
Just to clarify.
In the last step(3. create filter) we will create filter for user that send the request.
As client for RP I am using https://github.com/reportportal/client-net that sends user's token(**UUID**) for authorization. But after step 1(create user) i know only username\password of the created user. To obtain user's token(**UUID**) i need to login(through UI) with created user credentials.
The question is:
Does RP REST API support basic authentication?

**Comment by avarabyeu** [comment]
@lifemanship no it doesn't. but you can request token the same way as ui does (via basic auth) and then use it. Have a look at request to server after clicking login button
