### ISSUE TITLE
Add error text to test summary page.

### ISSUE THREAD

**Issue by heilwood** [reportportal/reportportal#991]
Hi,

Is it possible to add error message on test summary level. For example if 30 tests failed with same error, we don't see it, we need to check every test by clicking on it, from usability side its not so friendly.

Maybe its possible to add  short error text on this page:

![image](https://user-images.githubusercontent.com/27227165/83522346-36af1300-a4e9-11ea-95b0-95c7244862fe.png)

Thank you!

**Comment by DzmitryHumianiuk** [comment]
@heilwood here is the code example
https://github.com/reportportal/examples-java/blob/master/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/extension/ParametersAsAttributesTest.java#L76

the idea is to override default FinishTest method, and populate description with error log.
