### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by wwissingTechtonic** [reportportal/reportportal#993]
when trying to run a complex BDD test, I get a segmentation fault and the launch duration goes for about 1 day and less than an hr and finally ends. I found the option to force the launch to stop. but wondering why I keep getting seg faults. Trying to use the opensource on a private server instance... what would be the recommended instance size for complex tests to run without seg faults?

**Comment by DzmitryHumianiuk** [comment]
@wwissingTechtonic 
a launch that remains incomplete means that you test execution session didn't send FinishRQ.

- in v4.x it also can be that FinishRQ sent before suites/tests were completed
- in v5.x only if process was interrupted on test side.

(BTW, what's your version?)

For a local installation we recommend to allocated at least 5GB of RAM for your docker process. It may be limited by default, especially on Mac.

If it all fine, but still not finished, please see test cases logs, something related to ReportPortal should appear it in then

**Comment by wwissingTechtonic** [comment]
OK we are upping the instance to 8GB's and hopefully that will solve the seg faults... I am running version `"mocha-rp-reporter": "^1.0.12",`

**Comment by evjlobanova** [comment]
Closed due to no answer
Please reopen, if it is still actual
