### ISSUE TITLE
[v5] v5 mandates LaunchUuid for item extractions  through GET request

### ISSUE THREAD

**Issue by anjanamoorthi** [reportportal/reportportal#994]
Prior to v5,  Simple GET API request been used to extract all testItems inside a particular Launch with just LaunchId. But From v5, LaunchUUid is mandatory parameter to be used to extract testItems.
This requires modifications as many wont store LaunchUuid(If there are more than 1000 Launches) during Launch creation.

Scenario 
Before V5 :
- Generate multiple Launches using POST API
- To obtain details inside each launch(such as number of Test Suites and Test cases etc) ,Use GET API : GET /api/v1/{projectName}/launch where "filter.eq.launch=launchId" . This API responses back with all test suites and testcases inside a particular Launch.This is very useful to process further on each launch items.

On v5  : 
- Generate multiple Launches using POST API
- The details of each launch cannot not be extracted directly with GET /api/v1/{projectName}/launch.
We need to follow these additional steps : 
GET /v1/{projectName}/launch/uuid/{launchUuid} where launchUuid is the id from initial POST response. The response of this command is the actual physical Id which will be further used to extract items.

The question is, What if we didn't store launchUuid's ? . Because there are cases where Launches are generated by a test server which is completely not connected with Analytics server which does processing on launches. The v5 implementation makes me to add a common server for sharing launchUuid's between them which I wont feel necessary. Please confirm.

**Comment by evjlobanova** [comment]
@Yumfriez @pbortnik Could you please elaborate on that?

**Comment by evjlobanova** [comment]
@anjanamoorthi The system works as designed
