### ISSUE TITLE
Jira Cloud Integration with Report Portal 

### ISSUE THREAD

**Issue by vaibhavshukl12** [reportportal/reportportal#996]
Hi Team,
I am trying to configure the Jira with RP its saying connection refused.
I am trying with this Jira URL - https://xyzltd.atlassian.net 

but when I am giving bts URL- https://jira.xyz.com/    -this is working fine.

Is there any issue with Atlassian URL.
Please update on this issue

**Comment by evjlobanova** [comment]
@Vaibhavshukla08 but which actual URL has your Jira?

**Comment by Vaibhavshukla08** [comment]
Hi @evjlobanova Thanks for reply.
This is my Jira link which I need to configure - https://xyzltd.atlassian.net

**Comment by Vaibhavshukla08** [comment]
@evjlobanova is there any issue with Http and https in Jira with Rp Integration.
Please let me know

**Comment by Sunil04925** [comment]
Hi @evjlobanova Hope you are doing well !!
Similar kind of issue, i have also faced while trying to integrate :- https://xyzltd.atlassian.net JIRA into Report portal.
Kindly update on this also it would be great if you could suggest any other way to integrate the atlassian JIRA into RP. Thanks

**Comment by Vaibhavshukla08** [comment]
@DzmitryHumianiuk @evjlobanova Hope you are doing well !!
Kindly update on this issue.
Thanks

**Comment by DzmitryHumianiuk** [comment]
@Vaibhavshukla08 cloud version of Jira works with OAuth2 authorization token only.
we have this implementation planned in our roadmap, but currently shifted do to paid customizations.
Thus can't share any ETA at the moment.

**Comment by Vaibhavshukla08** [comment]
@DzmitryHumianiuk Thank you so much for your reply on the issue .
@evjlobanova - Could you please let me know the cost if I want to customize the RP for Cloud Jira

**Comment by evjlobanova** [comment]
@Vaibhavshukla08 it is difficult to say the cost right now. 
We can organize a call, discuss possible ways of interaction, and define a scope.  

Please drop us a letter on support@reportportal.io and we can discuss all details

**Comment by Vaibhavshukla08** [comment]
@evjlobanova Thanks for reply.
Sure I will drop a letter and we can discuss more on details in a call.

**Comment by yodaqua** [comment]
Hi @evjlobanova @DzmitryHumianiuk 

Has there been any movement on this issue?

**Comment by yodaqua** [comment]
Hi @evjlobanova @DzmitryHumianiuk 

JIRA cloud integration seems to be working

**Comment by DzmitryHumianiuk** [comment]
@yodaqua that is awesome, if it is true.
team will recheck it.

**Comment by VolhaKarenko** [comment]
It is possible to establish the connection with Jira cloud by using generated API token(your profile -> Security -> Create and manage API tokens) as password, but "post issue" option is not available, only "link issue"

**Comment by talmoshe24** [comment]
I installed the plugin but I see only user/pass
Which version includes API token?

**Comment by VolhaKarenko** [comment]
@talmoshe24 simply provide your API token in password field and email in user field
